### ISSUE TITLE
Not able to deploy in Heroku

### ISSUE THREAD

**Issue by anindyamanna** [mirumee/saleor#1003]
Getting this error when trying to deploy Saleor using "Deploy to Heroku" button in "https://github.com/mirumee/saleor/". Had the same problem in my own machine(kali linux), which got resolved when I removed appdirs manually beforehand using pip.

```
Installing collected packages: appdirs, pytz, babel, babeldjango, docutils, python-dateutil, jmespath, botocore, s3transfer, boto3, requests, braintree, pycparser, cffi, idna, pyasn1, cryptography, cssselect, cssutils, dj-database-url, dj-email-url, django, django-absolute, django-bootstrap3, django-cache-url, django-countries, lxml, premailer, django-emailit, django-materializecss-form, django-mptt, pyjwt, stripe, suds-jurko, xmltodict, django-payments, prices, django-prices, django-prices-openexchangerates, redis, django-redis, django-storages, pillow, django-versatileimagefield, django-webpack-loader, djangorestframework, urllib3, elasticsearch, faker, google-i18n-address, google-measurement-protocol, typing, promise, graphql-core, graphql-relay, graphene, iso8601, singledispatch, graphene-django, jsonfield, markdown, maxminddb, maxminddb-geolite2, pbr, mock, oauthlib, psycopg2, purl, py, pyparsing, pytest, pytest-django, requests-oauthlib, satchless, defusedxml, python3-openid, social-auth-core, social-auth-app-django, text-unidecode, uwsgi
         Found existing installation: appdirs 1.4.3
           Uninstalling appdirs-1.4.3:
             Successfully uninstalled appdirs-1.4.3
         Rolling back uninstall of appdirs
       Exception:
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2813, in _dep_map
           return self.__dep_map
         File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__
           raise AttributeError(attr)
       AttributeError: _DistInfoDistribution__dep_map
       
       During handling of the above exception, another exception occurred:
       
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2804, in _parsed_pkg_info
           return self._pkg_info
         File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2624, in __getattr__
           raise AttributeError(attr)
       AttributeError: _pkg_info
       
       During handling of the above exception, another exception occurred:
       
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
           status = self.run(options, args)
         File "/app/.heroku/python/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
           prefix=options.prefix_path,
         File "/app/.heroku/python/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
           **kwargs
         File "/app/.heroku/python/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
           self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
         File "/app/.heroku/python/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
           isolated=self.isolated,
         File "/app/.heroku/python/lib/python3.5/site-packages/pip/wheel.py", line 247, in move_wheel_files
           prefix=prefix,
         File "/app/.heroku/python/lib/python3.5/site-packages/pip/locations.py", line 140, in distutils_scheme
           d = Distribution(dist_args)
         File "/app/.heroku/python/lib/python3.5/site-packages/setuptools/dist.py", line 320, in __init__
           _Distribution.__init__(self, attrs)
         File "/app/.heroku/python/lib/python3.5/distutils/dist.py", line 281, in __init__
           self.finalize_options()
         File "/app/.heroku/python/lib/python3.5/site-packages/setuptools/dist.py", line 386, in finalize_options
           ep.require(installer=self.fetch_build_egg)
         File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in require
           items = working_set.resolve(reqs, env, installer, extras=self.extras)
         File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 862, in resolve
           new_requirements = dist.requires(req.extras)[::-1]
         File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2568, in requires
           dm = self._dep_map
         File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2815, in _dep_map
           self.__dep_map = self._compute_dependencies()
         File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies
           for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
         File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info
           metadata = self.get_metadata(self.PKG_INFO)
         File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
           value = self._get(self._fn(self.egg_info, name))
         File "/app/.heroku/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1577, in _get
           with open(path, 'rb') as stream:
       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/build_e48812842771c8b173aaffba76c2598e/mirumee-saleor-79f5f26/.heroku/python/lib/python3.5/site-packages/appdirs-1.4.3.dist-info/METADATA'
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by michalkalinowski-** [comment]
+1 when I try to deploy using a button - I'm getting the same error. What's more when I follow deploy instructions from documentation I get another issue:

relevant part of logs
```
remote:        $ node ./node_modules/webpack/bin/webpack.js -p
remote: module.js:471
remote:     throw err;
remote:     ^
remote:
remote: Error: Cannot find module '/tmp/build_f4cb2376b5292fb88290ac0837d9db5a/node_modules/webpack/bin/webpack.js'
remote:     at Function.Module._resolveFilename (module.js:469:15)
remote:     at Function.Module._load (module.js:417:25)
remote:     at Module.runMain (module.js:604:10)
remote:     at run (bootstrap_node.js:393:7)
remote:     at startup (bootstrap_node.js:150:9)
remote:     at bootstrap_node.js:508:3
remote: error Command failed with exit code 1.
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote: error Command failed with exit code 1.
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - This project was built with yarn, which is new and under development. Some projects can still be built more reliably with npm
remote:        https://devcenter.heroku.com/articles/nodejs-support#build-behavior
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy....
remote:
remote: !	Push rejected to (***).
remote:
```

**Comment by michalkalinowski-** [comment]
I made a bit of progress:
* using old buildpack for node (https://github.com/mbuchetics/heroku-buildpack-nodejs-grunt.git) solves my issue: node part builds
* pinning `appdirs==1.4.3` in requirement.txt solves what @anindyamanna reported. 

Now my deploy is failing at `python manage.py collectstatic --noinput`

traceback:
```
remote:      $ python manage.py collectstatic --noinput
remote:        Traceback (most recent call last):
remote:          File "manage.py", line 10, in <module>
remote:            execute_from_command_line(sys.argv)
remote:          File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
remote:            utility.execute()
remote:          File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 316, in execute
remote:            settings.INSTALLED_APPS
remote:          File "/app/.heroku/python/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
remote:            self._setup(name)
remote:          File "/app/.heroku/python/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
remote:            self._wrapped = Settings(settings_module)
remote:          File "/app/.heroku/python/lib/python3.5/site-packages/django/conf/__init__.py", line 97, in __init__
remote:            mod = importlib.import_module(self.SETTINGS_MODULE)
remote:          File "/app/.heroku/python/lib/python3.5/importlib/__init__.py", line 126, in import_module
remote:            return _bootstrap._gcd_import(name[level:], package, level)
remote:          File "<frozen importlib._bootstrap>", line 986, in _gcd_import
remote:          File "<frozen importlib._bootstrap>", line 969, in _find_and_load
remote:          File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
remote:          File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
remote:          File "<frozen importlib._bootstrap_external>", line 665, in exec_module
remote:          File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
remote:          File "/tmp/build_20613d67687c9bd7972f159058cc9855/saleor/settings.py", line 12, in <module>
remote:            DEBUG = ast.literal_eval(os.environ.get('DEBUG', 'True'))
remote:          File "/app/.heroku/python/lib/python3.5/ast.py", line 84, in literal_eval
remote:            return _convert(node_or_string)
remote:          File "/app/.heroku/python/lib/python3.5/ast.py", line 83, in _convert
remote:            raise ValueError('malformed node or string: ' + repr(node))
remote:        ValueError: malformed node or string: <_ast.Name object at 0x7f55183ddda0>
remote:
remote:  !     Error while running '$ python manage.py collectstatic --noinput'.
remote:        See traceback above for details.
```

**Comment by patrys** [comment]
It seems your DEBUG environment variable is set to something Python does not understand.

**Comment by michalkalinowski-** [comment]
Ah good catch, thanks @patrys. I managed to deploy to heroku with following steps:
* buildpacks: `https://github.com/heroku/heroku-buildpack-nodejs.git` and `https://github.com/heroku/heroku-buildpack-nodejs.git`
* `NPM_CONFIG_PRODUCTION=true` - otherwise npm part doesn't build
* pinning `appdirs==1.4.3`

What I don't understand (I'm new to django and heroku) is how to build when I'll want to do a prod release as setting npm_config_production to false fails the build.

**Comment by patrys** [comment]
In this case Node is used purely as a build tool so you'll never want to set it's mode to production.

**Comment by michalkalinowski-** [comment]
That makes sense. Thanks for help.

**Comment by michalkalinowski-** [comment]
BTW. is there a way of prebuilding static files locally rather than doing it on heroku?

**Comment by patrys** [comment]
Sure, you could have them tracked by git and skip the node buildpack altogether. The tricky part is you'll likely want to use hashes in static file names which means you'll have to clean up the previous files before adding the new ones. Something like `git rm -r saleor/static/assets && yarn run build-assets --production && git add saleor/static/assets`.

**Comment by michalkalinowski-** [comment]
ok perfect, got it working. Thanks for assistance @patrys. 
@anindyamanna are your issues resolved? If so I think this can be closed.

**Comment by jmichelsen** [comment]
I'm also experiencing the issues with the "Deploy on Heroku" button. I don't think this should be closed until that is fixed. Deploying with workarounds is one thing, but that button still isn't functional.

**Comment by taime** [comment]
+1

**Comment by PlamenHristov** [comment]
+1

**Comment by sfelde** [comment]
+1

**Comment by toguko** [comment]
I tried today and everything was fine, app deployed at Heroku with no errors.

**Comment by patrys** [comment]
This has been since fixed 👍

**Comment by Aditi022003** [comment]
remote:          Installing build dependencies: started
remote:          Installing build dependencies: finished with status 'done'
remote:          Getting requirements to build wheel: started
remote:          Getting requirements to build wheel: finished with status 'done'
remote:        ERROR: Exception:
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
remote:            status = run_func(*args)
remote:                     ^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
remote:            return func(self, options, args)
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
remote:            requirement_set = resolver.resolve(
remote:                              ^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
remote:            result = self._result = resolver.resolve(
remote:                                    ^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
remote:            state = resolution.resolve(requirements, max_rounds=max_rounds)
remote:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
remote:            self._add_to_criteria(self.state.criteria, r, parent=None)
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
remote:            if not criterion.candidates:
remote:                   ^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
remote:            return bool(self._sequence)
remote:                   ^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
remote:            return any(self)
remote:                   ^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
remote:            return (c for c in iterator if id(c) not in self._incompatible_ids)
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
remote:            candidate = func()
remote:                        ^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 182, in _make_candidate_from_link
remote:            base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
remote:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
remote:            self._link_candidate_cache[link] = LinkCandidate(
remote:                                               ^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
remote:            super().__init__(
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
remote:            self.dist = self._prepare()
remote:                        ^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
remote:            dist = self._prepare_distribution()
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
remote:            return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
remote:            return self._prepare_linked_requirement(req, parallel_builds)
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
remote:            dist = _get_prepared_distribution(
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
remote:            abstract_dist.prepare_distribution_metadata(
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 54, in prepare_distribution_metadata
remote:            self._install_build_reqs(finder)
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 124, in _install_build_reqs
remote:            build_reqs = self._get_build_requires_wheel()
remote:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 101, in _get_build_requires_wheel
remote:            return backend.get_requires_for_build_wheel()
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 751, in get_requires_for_build_wheel
remote:            return super().get_requires_for_build_wheel(config_settings=cs)
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
remote:            return self._call_hook('get_requires_for_build_wheel', {
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
remote:            raise BackendUnavailable(data.get('traceback', ''))
remote:        pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
remote:            obj = import_module(mod_path)
remote:                  ^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.12/importlib/__init__.py", line 90, in import_module
remote:            return _bootstrap._gcd_import(name[level:], package, level)
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
remote:          File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
remote:          File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
remote:          File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
remote:          File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
remote:          File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
remote:          File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
remote:          File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
remote:          File "<frozen importlib._bootstrap_external>", line 995, in exec_module
remote:          File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
remote:          File "/tmp/pip-build-env-swc9jzl2/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
remote:            import setuptools.version
remote:          File "/tmp/pip-build-env-swc9jzl2/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
remote:            import pkg_resources
remote:          File "/tmp/pip-build-env-swc9jzl2/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 73, in <module>
remote:            from pkg_resources.extern import appdirs
remote:        ImportError: cannot import name 'appdirs' from 'pkg_resources.extern' (/tmp/pip-build-env-swc9jzl2/overlay/lib/python3.12/site-packages/pkg_resources/extern/__init__.py)
remote:
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to voiceassistant.
remote:
To https://git.heroku.com/voiceassistant.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/voiceassistant.git'

got some PortAudio import error while deploying through streamlit sharing, hence switched to heroku, but these errors never leave !! help me please 
buil
