### ISSUE TITLE
Browser "back" button doesn't work properly when page has tabs

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1005]
"Back" button has to be clicked at least twice on pages with tabs in dashboard.

**Comment by elwoodxblues** [comment]
Issue resolved, it was caused by calling `window.history.pushState` on changing tabs. After removing this it works fine.

**Comment by harinath141** [comment]
HI @maarcingebala where i need to remove this window.history.pushState
is it in VariantPicker.js?
if yes i tried but it didn't work.
