### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by Wahagn** [mirumee/saleor#1006]
password authentication failed for user "saleor"
FATAL:  password authentication failed for user "saleor"

when migrating the first time

**Comment by Wahagn** [comment]
Okay never mind about the above..the solution is you have to create a database called saleor with saleor as a user with password 'saleor'  who is a superuser.

**Comment by gebril9** [comment]
then how to create a database called saleor with saleor as a user with password 'saleor' who is a superuser 
? i would be grateful
