### ISSUE TITLE
Calculating variant cost price doesn't work with more than one stock record and empty cost price

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1011]
When variant has more then one stock record and at least one of them has empty cost price (which is optional), then calling `get_cost_price` method of `ProductVariant` results in the following error:

```
/home/marcin/mirumeeWorkspace/saleor/saleor/saleor/product/models.py in select_stockrecord(self, quantity)
    294             lambda stock: stock.quantity_available >= quantity,
    295             self.stock.all())
--> 296         stock = sorted(stock, key=lambda stock: stock.cost_price, reverse=True)
    297         if stock:
    298             return stock[0]

TypeError: unorderable types: NoneType() < NoneType()
```

I'm not sure how do we want to select the stock record with lowest price when some of them don't have the cost price set. We could require the cost price or assume zero price in this case. What do you think @patrys?

**Comment by patrys** [comment]
I think it does not matter which we pick (either favor the ones with `None` or favor the lowest known and fallback to `None` if not available) as long as we document it in the docstrings.
