### ISSUE TITLE
How to update the storefront.css file after i make changes in the scss files ?

### ISSUE THREAD

**Issue by Kaushik-Roy** [mirumee/saleor#1014]
Trying to make some changes with the .css styles and images in home page.
How to compile it and make some updates and changes..???

**Comment by weronka** [comment]
Did you run `npm start`? It'll start Webpack in watch mode and compile .scss and .js files.

**Comment by Kaushik-Roy** [comment]
Thank you @weronka  ! it helped.  But again after some changes we run " npm start " and the files under " assets " folder it gets replicated. Why is it happens ?

**Comment by patrys** [comment]
Are you by any chance running an older version of Saleor that enabled hashed asset names by default?

**Comment by Kaushik-Roy** [comment]
@patrys , @weronka  i am getting the files in this fashion !!. for every CSS or JS a corresponding .map file is getting created and are replicated everytime. what i have to do ?

storefront.fd490293b9b50cabcb9954f505d81ce4.css
storefront.fd490293b9b50cabcb9954f505d81ce4.css.map

**Comment by patrys** [comment]
Please update the webpack config file to the latest version from Saleor.

**Comment by elwoodxblues** [comment]
Closing for now, please reopen if there are any questions.
