### ISSUE TITLE
An error occurred (InvalidRequest) when calling the PutObject operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

### ISSUE THREAD

**Issue by Aravind-Rajendran** [mirumee/saleor#1018]
When i try to integrate amazon aws , it was throwing error like this.Please tell me

**Comment by patrys** [comment]
Which AWS region is that?

**Comment by aravind12345** [comment]
India mumbai

**Comment by patrys** [comment]
We've since updated the boto libraries. I believe this should work as expected now.
