### ISSUE TITLE
PDF Invoice

### ISSUE THREAD

**Issue by curaloucura** [mirumee/saleor#1021]
Hello guys and awesome work here with Saleor.

I'm going to migrate my online shop to Saleor and need to send the PDF invoices to the customers and to my accountant. Also, I need the shipping list to attach to the products when dispatching as it serves as control in my process.

Is this a planned feature? The print button is not enough for me as it prints a non-formatted page and I need a decent presentation, also I need to make a dozen orders each time and therefore a one click pdf generator is much more efficient.

I started working on this feature in my own fork and I don't know if I can contribute back, especially because selecting a PDF library is a big decision.

Thanks

**Comment by patrys** [comment]
For PDF I can recommend `weasyprint` as it's easy to install and use. As for planned features I'd like Saleor to support both basic invoices and packing slips. For the latter I'd also consider using a thermal printer instead of a traditional office inkjet. I cannot however commit to any deadlines as we have yet to plan a sprint around printing. It would be great if you could lay down the ground work by proposing even an incomplete pull request.

**Comment by curaloucura** [comment]
I actually did with weasyprint. I will create a new fork for contributions later this week and bring the changes over and create some tests.

**Comment by curaloucura** [comment]
I just created a PR for this

**Comment by maxwhosevillage** [comment]
@curaloucura are you going to continue your work on PR #1025 ? 
I would love to use this feature in our saleor project.

@patrys is there a chance this feature could be included in saleor? 

If there is anything i can do, just let me know.

**Comment by curaloucura** [comment]
Hello @maxwhosevillage , as I will need this feature I can do any further work that is needed. I only need a better direction of how this can be improved as I have no requirements except of my own.

**Comment by maxwhosevillage** [comment]
Hi @curaloucura,
I think the first think is to fix the failed travis build and the conflicts to the master branch.
It looks like be changing the templates i could directly use your solution for my project.
Maybe I'll just checkout your branch and start from there.

**Comment by curaloucura** [comment]
Sorry for the delay @maxwhosevillage 
I have limited internet until this weekend and I will take a look at it. I hope just checking out the changes from my branch could help you out but I also need to start looking on how to work on a better template for myself.

**Comment by curaloucura** [comment]
pip-compile was bringing an incompatible version of CairoSVG. now it's working for python 2 and 3 @maxwhosevillage

**Comment by curaloucura** [comment]
@patrys anything I can do to move this ticket forward?

**Comment by patrys** [comment]
Paging @elwoodxblues 😄

**Comment by elwoodxblues** [comment]
PR #1025 looks good. We'll this but first I'd like to make some cosmetic changes to adjust the code style to what we have in Saleor.

**Comment by patrys** [comment]
The related PR is now merged. Thank you everyone! ✨
