### ISSUE TITLE
the graphQL is not getting returned for the feed pages. How do i solve it ? In the terminal also is dosen't show the POST request of the graphQL!

### ISSUE THREAD

**Issue by Kaushik-Roy** [mirumee/saleor#1023]
when i go for a category page , the page gets loaded but the content items are not coming. I checked in the terminal , the grapql POST request -
"POST /graphql/ HTTP/1.1" 200 9457
that comes normally after this :
"GET /cart/summary/ HTTP/1.1" 200 358
is now not coming..!!

how to solve it ?

**Comment by elwoodxblues** [comment]
Hi, the reason for this behavior may be a heavy query to the database that slows everything down. If you added for example a new relationships in product model and not prefetched it properly, then this may be the reason. I'd start debugging the GraphQL query with `grapiql` tool, which is available in debug mode under `http://localhost:8000/graphql`. Also I'd debug the code in `resolve_products` method ([here](https://github.com/mirumee/saleor/blob/master/saleor/graphql/api.py#L118)) which is responsible for loading the products.

**Comment by elwoodxblues** [comment]
@Kaushik-Roy Did you manage to solve this problem?

**Comment by Kaushik-Roy** [comment]
@elwoodxblues   you'r suggestion was helpful. I was wanting to add a new argument to the `products` query in graphQL to fetch apparel according to ProductClass, whenever i change something in the `category.js` or `categoryPage.js `i land up with the graphql problem.

 I want to know how can i add a new argument into the Relay code on CategoryPage.JS  (adding a new variable to products query) to fetch apparel's according to the ProductClass (ProductType) ?

A new graphene argument has been declared under CategoryType class in graphql/api.py for the productClass to accept the id. When i debug in graphiQl it returns result, but i am not able to use the same in CategoryPage.js under the relay code.
![graphql-prosucts](https://cloud.githubusercontent.com/assets/18119362/25497894/a1dcd896-2ba3-11e7-8f96-8feea6452988.png)

**Comment by elwoodxblues** [comment]
@Kaushik-Roy After you make any change in the type system (by adding a new fields or arguments) you should also run `python manage.py graphql_schema`. This command updates the `schema.json` file which is used by Relay to parse the queries defined in its containers (I'm afraid this isn't documented well which I'm sorry for; we still have to work on the documentation). Then you only need to update the query in the respective Relay container, for example here is the query for ProductType:

https://github.com/mirumee/saleor/blob/master/saleor/static/js/components/categoryPage/ProductItem.js#L54

I hope this helps, if not, please show me the error you're getting.

**Comment by elwoodxblues** [comment]
Also make sure that you're actually rebuilding the JS files after you make any changes; it's best to have `yarn start` running somewhere during the development.

**Comment by Kaushik-Roy** [comment]
ok i will try and let you know... and can i get your email

**Comment by Kaushik-Roy** [comment]
ok i will try this way , i will let you know .... and can i get your email @elwoodxblues  ?

**Comment by Kaushik-Roy** [comment]
thanks @elwoodxblues  it is working fine now...

**Comment by elwoodxblues** [comment]
You're welcome, if you have any other questions or problems feel free to open an issue.
