### ISSUE TITLE
"slugify" method keep underscore but the regex in product details url does not allow it

### ISSUE THREAD

**Issue by mperesson** [mirumee/saleor#1027]
Sorry I'm too lazy to create a pull request.

Just to let you know that the uderscore "_" is allowed by the slugify method (get_slug of the product class) but if you call get_absolute_url it will crash because the url does not accept it.

saleor/product/url.py:
```
    url(r'^(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/$',
        views.product_details, name='details'),
```
to
```
    url(r'^(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/$',
        views.product_details, name='details'),
```

**Comment by elwoodxblues** [comment]
Closed by #1190
