### ISSUE TITLE
Dashboard login - Add to documentation

### ISSUE THREAD

**Issue by HawiCaesar** [mirumee/saleor#1028]
`python manage.py createsuperuser`

Is it possible for this to be put in the documentation? I really struggled only to find out; only  to realise its a simple command to above then I could access the dashboard.

**Comment by elwoodxblues** [comment]
Hi, we're planning an entire sprint dedicated only to the documentation improvements, we'll take it into account.

**Comment by HawiCaesar** [comment]
Thats great!! Hope to see it soon

**Comment by HawiCaesar** [comment]
Any luck?

**Comment by simo97** [comment]
Hey !! I was about to work on this, but it seem to be done, here https://docs.getsaleor.com/docs/getting-started/creating-superuser/. can you guys @maarcingebala  close this issue ?

**Comment by maarcingebala** [comment]
Yep, it can be closed. Thanks for reminding!
