### ISSUE TITLE
Category page not loading  after running npm start and yarn run build-assets.

### ISSUE THREAD

**Issue by zmwas** [mirumee/saleor#1030]
After running yarn run build-assets  so that I can change the css, I can't see any of the categories' loading the items in the page. Before running it I could see the category items.
I am using ngx_pagespeed. Could that be the cause the problems I am having? The js in all the other pages is working properly except for categories.

**Comment by elwoodxblues** [comment]
Hi, honestly I don't whether this issue might be caused by `ngx_pagespeed`. Maybe you should disable it and see if the page works without it. Does your browser's developer console show any errors?

**Comment by zmwas** [comment]
It does not show any errors. I have disabled it and it works.
