### ISSUE TITLE
Add new user type (Documentation)

### ISSUE THREAD

**Issue by GembeJr** [mirumee/saleor#1034]
this is great e-commerce application from django, but many standard code from django framework has been gone (changing) for example when i use `admin/`, i got template error and i was curious bout this. Hence of that i search the problem and i was got the django framework has been changing. So how to give user new user type (user group) in this apps or is there documentation bout this allauth?

**Comment by patrys** [comment]
@GembeJr Thank you for your time spent on evaluating Saleor. I am not quite sure what you're asking about however. Saleor does not have Django Admin enabled by default. We provide a custom dashboard built specially with e-commerce in mind and if you wish to use Django's basic Admin panel you'll need to enable it separately (you'll find the exact steps in [Django docs](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/)).
