### ISSUE TITLE
How to add pay on delivery option in django-payments

### ISSUE THREAD

**Issue by zmwas** [mirumee/saleor#1036]
I would like to add pay on delivery for users who don't have paypal. How do I add it?

**Comment by rlimaeco** [comment]
I want the same thing, I was trying to use PagSeguro (Brazillian paypal like) and I was using the module django-pagseguro2, but it doesn't use django-payments and I have to change a lot of the core of saleor.. I don't how to easily inherit an class of django-payments and add this kind of payment.. I'm still looking for it

**Comment by MacLake** [comment]
We need something similar: payment by bank transfer, i. e. no immediate payment with confirmation. I’m surprised that this isn’t handled by Saleor, as it’s quite common to order and pay later by bank transfer, at least in Germany.

Should it be implemented in Saleor or django-payments?

Actually this payment handler doesn’t need to do much: Just confirm the order and leave it in a “not-paid” state.

**Comment by patrys** [comment]
In that case I'd just modify the order logic to not wait for the payment to complete. There's nothing you need `django-payments` for unless there is an API to receive bank transfer confirmations and even then it might be easier to do this directly in your store code.

**Comment by wulaaf** [comment]
> In that case I'd just modify the order logic to not wait for the payment to complete. There's nothing you need `django-payments` for unless there is an API to receive bank transfer confirmations and even then it might be easier to do this directly in your store code.

Any idea how that might be accomplished?
