### ISSUE TITLE
shipping address form field ordering

### ISSUE THREAD

**Issue by bravamin** [mirumee/saleor#1040]
Can someone point me to some documentation or configuration where I can customize the order in which the address fields display? 

It's currently displaying as
```phone
given name | family name
company name
address 1 | address 2
city | state
zip
country
```
but what I'd really like is something like
```
given name | family name
company name | phone
address 1 | address 2
city | state | zip
country
```

**Comment by patrys** [comment]
Currently the forms are constructed using i18n address data provided by Google. You can [take a look at the code](https://github.com/mirumee/saleor/blob/master/saleor/userprofile/i18n.py) to see how this works. You can then override the defaults for a particular country by assigning your own custom form class to `COUNTRY_FORMS[country_iso_code]`.

**Comment by bravamin** [comment]
that makes sense 👍
