### ISSUE TITLE
Compile sass files

### ISSUE THREAD

**Issue by ridiaz** [mirumee/saleor#1042]
Hey guys,

Great work !.  I'm trying to compile sass files with new colors for the dashboard.  But the following files are not present:

```
@import "~materialize-css/sass/materialize";
@import "~dropzone/dist/dropzone";
@import "~select2/src/scss/core";
```

Is there a better way to compile sass files ?

Thanks

Ricardo.

**Comment by patrys** [comment]
Are you using Webpack? These paths are automatically mapped by Webpack to installed packages from `node_modules`.

**Comment by ridiaz** [comment]
Thanks.  That makes the trick.
