### ISSUE TITLE
Saleor uses JS and CSS from S3 although I dont want it to

### ISSUE THREAD

**Issue by bakeriogit** [mirumee/saleor#1043]
Hi and first off thanks for a great product.

I am trying to host my saleor-based webshop with nginx and gunicorn.
The CSS and JS references are pointing to some S3 storage though (e.g. like this https://saleor-demo.s3.amazonaws.com/assets/storefront.4b1b9aabccea94179672.js)

Am I missing an obvious setting? The environment variables concerning AWS are not set, I already checked that.

**Edit:**
I suspect it has something to do with the webpack loader.
It seems that in production use, the webpack.config.js sets publicPath: 'https://saleor-demo.s3.amazonaws.com/assets/'
Even if I uncomment this part of the code and change the else branch to if (true), saleor STILL tries to fetch css and js from the afore mentioned URL. 

Thanks for your help

**Comment by mikeres0** [comment]
Are you sure your assets are being rebuilt when your application has been deployed?

**Comment by bakeriogit** [comment]
Yes they are.
In fact settingchanging the publicPath

**Comment by bakeriogit** [comment]
Yes they are, in fact setting the publicPath correctly (in this case to `/static/assets/`) DID help.
Gunicorn just had to be restarted to pick up on the changes.

Documenting this step somewhere might be helpful.
Also thanks for linking the related issue.
