### ISSUE TITLE
Why are some ModelForms in i18n.py? Can I safely move them elsewhere?

### ISSUE THREAD

**Issue by randomshinichi** [mirumee/saleor#1045]
I want to move userprofile.models.Address out into a separate Django app, because they're not strictly part of UserProfiles anymore in my use case.

But I found that AddressForm is defined in i18n.py. Why not in forms.py? Can I safely move it into myownapp/forms.py?

**Comment by patrys** [comment]
In Saleor `forms.py` depends on `i18n.py` so moving the base class to `forms` would result in a circular dependency. It's probably fine to move it if you've separated address data to a separate app.
