### ISSUE TITLE
Can't build yarn assets

### ISSUE THREAD

**Issue by adsalpha** [mirumee/saleor#1046]
Error
    at NormalModule.onModuleBuildFailed (/home/ubuntu/saleor/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/home/ubuntu/saleor/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /home/ubuntu/saleor/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/ubuntu/saleor/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /home/ubuntu/saleor/node_modules/favicons-webpack-plugin/lib/favicons.js:32:23
    at /home/ubuntu/saleor/node_modules/favicons-webpack-plugin/lib/favicons.js:56:21
    at /home/ubuntu/saleor/node_modules/favicons/es5.js:193:28
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:52:16
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:696:30
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:167:37
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:1209:30
    at /home/ubuntu/saleor/node_modules/favicons/es5.js:143:24
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:52:16
    at done (/home/ubuntu/saleor/node_modules/async/lib/async.js:241:17)
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/saleor/node_modules/favicons/es5.js:137:25
    at /home/ubuntu/saleor/node_modules/favicons/es5.js:122:24
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:726:13
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:52:16
    at done (/home/ubuntu/saleor/node_modules/async/lib/async.js:241:17)
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:723:17
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:167:37
    at /home/ubuntu/saleor/node_modules/favicons/es5.js:110:24
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:52:16
    at done (/home/ubuntu/saleor/node_modules/async/lib/async.js:241:17)
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/saleor/node_modules/favicons/es5.js:107:28
    at /home/ubuntu/saleor/node_modules/favicons/es5.js:72:32
    at /home/ubuntu/saleor/node_modules/async/lib/async.js:52:16

I'm using NodeJS 7, installed and double-checked all prerequisites.

**Comment by cdvv7788** [comment]
Check https://github.com/mirumee/saleor/issues/1064 and https://github.com/mirumee/saleor/issues/1020
After installing libfontconfig and adding 4GB of swap, I was able to finish the build.
