### ISSUE TITLE
CSS & JS linking to AWS - 403 Forbidden

### ISSUE THREAD

**Issue by mikeres0** [mirumee/saleor#1048]
I am deploying my app onto heroku using the python and nodejs buildpacks. The app deploys fine, but when loading the site the CSS and JS are being linked to on an AWS server and I am getting back a 403 response code. Do you guys know what could be causing this? 

![image](https://user-images.githubusercontent.com/5929943/27125936-d2665a40-50ed-11e7-9e34-7c4b4d4bba7c.png)

**Comment by mikeres0** [comment]
Can we edit this block in the  `webpack.config.js` file to point at our static assets? 

```
if (process.env.NODE_ENV === 'production') {
  output = {
    path: resolve('saleor/static/assets/'),
    filename: '[name].[chunkhash].js',
    publicPath: 'https://saleor-demo.s3.amazonaws.com/assets/'
  };
  fileLoaderPath = 'file?name=[name].[hash].[ext]';
  extractTextPlugin = new ExtractTextPlugin('[name].[contenthash].css');
} else {
  output = {
    path: resolve('saleor/static/assets/'),
    filename: '[name].js',
    publicPath: '/static/assets/'
  };
  fileLoaderPath = 'file?name=[name].[ext]';
  extractTextPlugin = new ExtractTextPlugin('[name].css');
}
```

**Comment by patrys** [comment]
The code you pasted currently points to _our_ AWS S3 bucket. Do change it to suit your deployment.

**Comment by mikeres0** [comment]
@patrys well that would explain it... I believe there's another issue related to this #1043 which could probably do with the same explanation. Thanks for your help 👍

**Comment by dtheekshanalinux** [comment]
@patrys how to change aws s3 bucket into suit development
