### ISSUE TITLE
ImportError: No module named autoprefixer -  Error when deploying to Heroku

### ISSUE THREAD

**Issue by mikeres0** [mirumee/saleor#1052]
When deploying to a heroku instance I recieved the following error: `ImportError: No module named autoprefixer` whilst running the heroku-postbuild script: `"heroku-postbuild": "yarn add --force node-sass && yarn run build-assets"`. 

I attempted to fix this using `"heroku-postbuild": "yarn add --force node-sass && yarn run build-assets --production"`, thinking that this would fall into the dependencies section and not devDependencies, but this did not fix the issue. Please find below the node and yarn versions which I was using: 

```
  "engines": {
    "node": "7.9.0",
    "npm": "4.5.0",
    "yarn": "0.24.6"
  }

```

My work around was to copy the devDependencies into the dependencies section, which is obviously not ideal. Do you have any idea what could have caused this? I followed the deployment instructions found here in your docs: https://saleor.readthedocs.io/en/latest/deploy.html#first-steps

**Comment by Pacu2** [comment]
I think this is resolved by now, deploying to Heroku wprks.
