### ISSUE TITLE
List of choices for the variant picker is wrong

### ISSUE THREAD

**Issue by Satloff** [mirumee/saleor#1053]
Why is the attribute creation on a global store level? Perhaps it would be easier and cleaner if attributes were created and stored per product type. 

ex issue:
100 products are added, each with a unique set of colors and sizes. 
Product 1: Sizes - (s, m, l, xl) Colors - (red, blue, green)
Product 2: Sizes - (1, 2, 3, 4) Colors - (maroon, turquoise, beige)
etc. 

The issue is, for each product, I only want the types referring that specific product. 

Posed solution:
instead of having attribute and product type creation as a global policy, make it on a product by product basis. When a new product is created, require attribute name and values. These attributes will be specific to the product. 

Updated product page:
<img width="879" alt="attribute_change" src="https://user-images.githubusercontent.com/14352539/27256518-69fdd164-5385-11e7-8b77-819c255fd031.png">

How would you go about solving this problem?

**Comment by patrys** [comment]
Attributes are specific to product classes. You can create unique product classes with unique attributes to differentiate between things like shoe sizes and shirt sizes.

**Comment by Satloff** [comment]
yes, but that seems cumbersome. Let's say my company only sold jackets. And each jacket had a different selection of colors. Is your suggestion that I have a different product class for each individual model of jacket?

**Comment by patrys** [comment]
Does it really bother you that when creating variants you have a couple extra color options? This should not in any way be visible to your customers as we only list existing variants. On the other hand imagine selling 10+ million books (an actual store we've built) and having to create attributes such as cover type for each individual product.

**Comment by Satloff** [comment]
I may be misunderstanding, but is your suggestion to list all possible attribute values in one attribute? I've listed a larger set of colors in an attribute called "color" which is also part of an product type called "jacket." This model of jacket only has two colors (blue, and light blue), yet the entire list of colors is available. 

My feeling is it would be quite cumbersome to list all of these values (especially as the list grows. Let's say it was 1000 colors). As you point out, "having to create attributes such as cover type for each individual product" would be quite inefficient. Unless i'm misunderstanding, in order to have the presentation in the correct form, one would have to create a new attribute for each color set. 

Below i've supplied the image of product using "color" attribute. 
 
<img width="1130" alt="screen shot 2017-06-20 at 9 47 42 am" src="https://user-images.githubusercontent.com/14352539/27336606-15571e0c-559e-11e7-81e1-940582b48507.png">

**Comment by patrys** [comment]
That seems to be a bug, it's not supposed to list attribute values that don't exist in this particular product.

**Comment by elwoodxblues** [comment]
Fixed by #1088
