### ISSUE TITLE
Redirect after payment points to localhost:8000

### ISSUE THREAD

**Issue by mikeres0** [mirumee/saleor#1054]
After successfully paying for an order via. Stripe, I'm redirected to http://localhost:8000/order/9306ae71-45c1-44b4-8a03-759ffa38cd17/create-password/, instead of the hosted URL. 

I'm not sure why this occurs? This is after deployment to Heroku.

**Comment by patrys** [comment]
Perhaps the `Site` instance referenced by your settings file points to that domain?

**Comment by mikeres0** [comment]
In `/saleor/settings.py`? I cannot find any references to localhost or 127.0.0.1. May you provide an example of where this might be?

**Comment by patrys** [comment]
Please see the [Django documentation](https://docs.djangoproject.com/en/1.10/ref/contrib/sites/). This change has to be done in the database and you'll need to restart the application as there's currently no way to modify the site programmatically (there's a bug in how they are cached by Django).

**Comment by joshkehn** [comment]
@mikeres0 Go to Dashboard -> Scroll down sidebar -> Settings and edit the “Domain” value. 

<img width="800" alt="napkin 06-22-17 9 27 29 am" src="https://user-images.githubusercontent.com/272377/27436294-c4334a38-572c-11e7-9a0d-a19eb110d726.png">

**Comment by mikeres0** [comment]
@joshkehn Thank you. I hadn't delved into the site settings just yet, but thanks for pointing that out.
