### ISSUE TITLE
Problem installing Pillow

### ISSUE THREAD

**Issue by rickbrunstedt** [mirumee/saleor#1057]
I run `$ pip install -r requirements.txt`
error I get is this:
`ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting`
and then it says `Rolling back uninstall of Pillow`

Maybe this doesn't have anything to do with saleor and rather Pillow. 

I read somewhere that one could install a package named libjpeg through homebrew instead, so I did. But then Homebrew is macOS is already providing this and that I should symlink that and it could lead to problems.

How did other people with macOS solve this?

**Comment by patrys** [comment]
Try running:

```
$ brew install jpeg
```

**Comment by rickbrunstedt** [comment]
That returns
`Warning: jpeg-8d already installed`

Should I uninstall that and then run that again?

**Comment by clodal** [comment]
Had issue with Pillow. I just did `pip install pillow`. Doing that also updated my Pillow version to `4.2.0` and I was able to proceed.
