### ISSUE TITLE
Error Deploying to Heroku (webpack-bundle-tracker) 

### ISSUE THREAD

**Issue by mativs** [mirumee/saleor#1059]
When trying to deploy to heroku the webpack-bundler-tracker wasn't installed

I have to run 

`heroku config:set NPM_CONFIG_PRODUCTION=false` 

in order to make it works... 

Hope it helps.

**Comment by ErrolLin** [comment]
how could u install nom and node.js on heroku?

I can't do this.

so I meet the problem

Error reading ./webpack-bundle.json. Are you sure webpack has generated the file and the path is correct?

**Comment by alcfernandes** [comment]
Same problem here.

**Comment by jordantomax** [comment]
Same here, subscribing to this issue.

**Comment by Mitaanshu-Agarwal** [comment]
Has anyone manage to solve webpack-bundle.json error?

**Comment by Pacu2** [comment]
I think this issue is resolved by now. "Deploy to heroku" button works, however, if you are deploying manually (eg. from CLI) remember to set proper Buildpacks. 

Saleor needs `heroku-buildpack-nodejs` and `heroku-buildpack-python` to work properly.

**Comment by chmbrs** [comment]
I used 
`npm install webpack-bundle-tracker --save-dev`
to create the package and then push it to heroku =)
