### ISSUE TITLE
How to change the pic on heroku

### ISSUE THREAD

**Issue by ErrolLin** [mirumee/saleor#1067]
I change the home.html pic block1 ~ block3

but when I deploy on heroku. It doesn't work.

How do I change the pic( block1 ~ block3) correctly?

**Comment by patrys** [comment]
I believe those are backgrounds set using CSS. If so make sure you've replaced the source file and not the destination file and then rebuild front-end assets using `yarn run build-assets` (or run `webpack -p`).

**Comment by ErrolLin** [comment]
It still doesn't work .
https://test-shop-ss.herokuapp.com

**Comment by israelzuniga** [comment]
Same issue over here. There's a hard-coded path in webpack.config.js:18 (https://saleor-demo.s3.amazonaws.com/assets/) and even after making a substitution by my own S3 bucket address is not updating the address after `yarn run build-assets`.

➜  yarn -v
yarn install v0.27.5
➜  node -v
v8.1.2

**Comment by israelzuniga** [comment]
@ErrolLin We quick fixed by replacing the S3 path at this line:
https://github.com/Foodimx/foodiSaleorV1/blob/master/webpack.config.js#L16  (I know there is a redundancy in the evaluation, but we were getting desperate) :)

We also tested with out S3 bucket and works well over Heroku deployments.

**Comment by patrys** [comment]
This is now fixed, target static asset URL is controlled by an environment variable (`STATIC_URL`).
