### ISSUE TITLE
elasticsearch 5 - TransportError(400, 'parsing_exception', 'no [query] registered for [missing]')

### ISSUE THREAD

**Issue by tulsluper** [mirumee/saleor#1069]
I try to run saleor with elasticsearch 5 and see django error:
`        TransportError(400, 'parsing_exception', 'no [query] registered for [missing]')`

I have:
1)
changed backend
    from:
`            'BACKEND': 'saleor.search.backends.elasticsearch2',`
    to:
`            'BACKEND': 'saleor.search.backends.elasticsearch5',`

2)
uninstalled python package (pip):
`            elasticsearch==2.4.1`
and installed:
`            elasticsearch==5.4.0 (elasticsearch>=5.0.0,<6.0.0)`

After change
from:
```
        'missing': {
            'field': column_name,
        }
```
to:
```
        "bool": {
            "must_not": {
                "exists": {
                    "field": "user"
                }
            }
        }
```
in _saleor/search/backends/elasticsearch.py_
search works properly

Could you please perform some changes in _elasticsearch5.py_ in order for it to work from the box.
Thank you.

**Comment by israelzuniga** [comment]
@tulsluper Is this a deployment over Heroku? My testing stage on Docker is working fine with search, but I got the same issue when deploying over Heroku.

I'll try this fix later and confirm.

**Comment by tulsluper** [comment]
@israelzuniga there was local installation of elasticsearch from repositories.
OS - Ubuntu 16.04
Repositories - https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html
tested with Elasticsearch 5.0.0 and 5.5.0 - "TransportError(400, 'parsing_exception'" issue

**Comment by yeahdef** [comment]
I also experienced this.
My fix was to update `elasticsearch.py` to:

```
        # Get pks from results
        pks = [hit['_source']['pk'][0] for hit in hits['hits']['hits']]
        scores = {str(hit['_source']['pk'][0]): hit['_score']
                  for hit in hits['hits']['hits']}
```
and `elasticsearch5.py` changed:
```
class Elasticsearch5SearchResults(Elasticsearch2SearchResults):
    fields_param_name = '_source'
```
in addition to the changes @tulsluper mentioned.
Running local es5 instance on OS X 10.10

**Comment by itomaldonado** [comment]
I can confirm that the changes from @yeahdef and @tulsluper worked for me as well.

**Comment by Hisagr** [comment]
I've done the above steps and then rerun indexing as well and now the search works. However, it doesn't product any results. 
Any thoughts on what can be the reason? I am hosting app on heroku.
