### ISSUE TITLE
menu "hamburger" button does't respond on mouse click in Firefox

### ISSUE THREAD

**Issue by tulsluper** [mirumee/saleor#1070]
menu "hamburger" button does't respond on mouse click in Firefox (small screen, Firefox 54.0.1, Windows 10) 

js console log:
--    ReferenceError: event is not defined[Learn More] storefront.js:1:1089

fixed by replacement of "event.stopPropagation()" to "t.stopPropagation()" in  _saleor/static/assets/storefront.js_

**Comment by elwoodxblues** [comment]
Fixed in #1070
