### ISSUE TITLE
Add region scope to shipping methods

### ISSUE THREAD

**Issue by cdvv7788** [mirumee/saleor#1071]
I would like to have variable scopes on the shipping rates. If I pick a country with no regions, the rate applies to the whole country, but if I pick a country with some specific regions and different values, those rates apply there.
So I could pick country, or country->region or country->region->city (not sure if this last one would be good for the autocomplete on the database side)
I am new to the package, and I am still trying it out, so I don't know if there is a way to tell it that I am shipping only to a certain country (or group of countries).
I am based on what woocommerce calls shipping zones, which I think is a great idea (however, like everything in wordpress, the options to make it usable are premium).
If there is a way to limit target countries, that changes what the "rest of the world" option means. If it is not implemented, that would be nice.
I like the theme and the admin looks great with those material widgets. Liking it so far.

**Comment by tulsluper** [comment]
to limit shipping countries in cart I use this way:

1) add to _saleor/settings.py_ list of countries:
```
from django.utils.translation import ugettext_lazy as _
COUNTRIES = {
    "UA": _("Ukraine"),
}
```

2) in file _/saleor/userprofile/i18n.py_ replace:
```
from django_countries.data import COUNTRIES
```
to:
```
from django.conf import settings
COUNTRIES = getattr(settings, 'COUNTRIES', None)
if not COUNTRIES:
    from django_countries.data import COUNTRIES
```

**Comment by MacLake** [comment]
See my instructions on #1079 how to implement differentiation of the shipping costs per region within a country. You can also define groups of countries like I did for the EU. That’s the most versatile way to determine shipping costs I can imagine.

For autocompletion of cities there isi [django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light) and [django-cities](https://github.com/coderholic/django-cities) and [django-cities-light](https://github.com/yourlabs/django-cities-light), but this is quite some work to get it running.

**Comment by Pacu2** [comment]
Countries scope was added in #2529
