### ISSUE TITLE
Issue updating requirements (django-prices)

### ISSUE THREAD

**Issue by cdvv7788** [mirumee/saleor#1072]
I was playing around with pip-compile --upgrade
I am getting: django-prices<0.5a0,>=0.4.11,>=0.6.1
The "<0.5a0,>=0.4.11" part comes from the in file. The ">=0.6.1" comes from another package: https://github.com/mirumee/django-prices-openexchangerates (Would be hard to find if the names didn't gave a hint).
Contradictory requirements, obviously. I don't know much about those packages, so i don't know if it is safe to remove the "<0.5a0" that is causing the issue.

**Comment by patrys** [comment]
Closing as this was fixed by dropping the upper version limit.
