### ISSUE TITLE
Add a CONTRIBUTING guide

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#1074]
We should describe how we intend the community to take part in building Saleor. This includes programming as well as translation help.

**Comment by maarcingebala** [comment]
We have [Contributing](http://docs.getsaleor.com/en/latest/contributing.html) section in our docs but I guess you mean adding the `CONTRIBUTING.md` file as well?

What I'd also like to see is a section about development tools that we recommend e.g. those that come with `requirements_dev` or any related settings such as enabling debug toolbar, Silk, etc.

**Comment by htukiain** [comment]
Above link "contributing" gives: "Requested page could not be found."

**Comment by NyanKiyoshi** [comment]
Updated the link, thanks!
