### ISSUE TITLE
Custom Attributes

### ISSUE THREAD

**Issue by amorphic** [mirumee/saleor#1080]
First up thanks for Saleor - it's a fantastic platform and very well realised.

We are using Saleor to create a shop selling custom products which are manufactured to order based on the customer's requirements. In a `product class` we might have the following:

__Variant Attributes__

* __design__: *one of twenty+ designs available*
* __length__: *a number from one to eight*

__Product Attributes__

* __color1__: *one of twelve colors*
* __color2__: *one of twelve colors*
* __color3__: *one of twelve colors*
* __color4__: *one of twelve colors*

We want the customer to be able to select their own combination of colors. But currently to do this with Saleor we would need to change all of the colors from __product attributes__ into __variant attributes__. This is impractical because:

* The colors do not affect price, we just need to know which colors the customer chose when we receive the order.
* We cannot create a SKU for every combination. There are 12^4 (20736) combinations of color before we even consider `style` and `length`.

Ideally we would have something like:

* When defining either a __product type__ and/or a specific __product__ we would be able to mark a given __product attribute__ as "user selectable".
* We would set a default value for this attribute but the user would be able to change it before adding an item to their cart.
* The values chosen by the user would be added to the cart line in their order so we know what to create for them.

I am going to build this but before I do I wanted to check if there is a preferred way to do it? It seems like `data` in `CartLine` might be the correct place to store the user's selections but I've only just started looking. Once I am done I would like to submit my work as a PR so that others can use it, so if there is anything you think I should be aware of to make my changes worthy of consideration I would love to hear it.

**Comment by amorphic** [comment]
For anybody interested in doing this I have successfully added a new "custom" attribute class to Saleor in [this branch](https://github.com/amorphitec/enstaved-shop/tree/1080_user-selectable_product_attributes). I still have to add some tests and then I'll submit a PR for consideration.

**Comment by patrys** [comment]
@amorphic Thank you for working on this. May I suggest renaming "user-selectable attributes" to "options", "product options" or something similar to avoid confusion?

**Comment by amorphic** [comment]
@patrys you're very welcome - I'm really glad to be able to help improve Saleor.

In the end I settled on the name "custom" attributes as they're attributes used to customize a product. This fit in really well with the existing code too. As per previous comment, PR coming soon...

**Comment by JeffKnorr** [comment]
@amorphic Did this get merged into the standard Saleor release?  I'm testing Saleor to see if it fits our use case.  We need something just like what you described--custom product attributes that don't require SKU creation.

**Comment by amorphic** [comment]
Hi @JeffKnorr. Alas it was never merged, though it is live and powering [shop.enstaved.com](https://shop.enstaved.com) so custom attributes (while a little tricky) are absolutely possible!

The problem was that just as I started to build our web shop with Saleor the rate of change really picked up! That's a nice problem to have - the guys at Mirumee are really putting a lot of effort into the framework. But is was too difficult to keep our fork (and even just my branch with the custom attribute code) up to date.

I'm looking to revisit our fork and perhaps re-do from scratch using the latest Saleor codebase. I spoke to the guys at Mirumee and they plan some pretty major changes to the backend so I might be able to coordinate my work with theirs.

If you have a specific use-case and you want to chat about it offline feel free to drop me an email via `james[at]amorphitec.io`.

**Comment by xtrasalty** [comment]
I just started with Saleor and I was just looking for this same functionality.  I will take a look at how you implimented this.
