### ISSUE TITLE
Add links for more social media platforms

### ISSUE THREAD

**Issue by amorphic** [mirumee/saleor#1082]
The `base.html` template currently has only limited support for social media links. Currently only Github and Twitter are built-in and are added using specific `.svg` files:

```
<a target="_blank" rel="noopener" class="github-footer" href="https://github.com/mirumee/saleor">
  <svg data-src="{% static "images/github_logo.svg" %}" width="45px" height="45px"/>
</a>
<a target="_blank" rel="noopener" href="https://twitter.com/getsaleor">
  <svg data-src="{% static "images/twitter_logo.svg" %}" width="45px" height="45px" />
</a>
```

One way to support all major social media platforms would be through the integration of [Font Awesome](http://fontawesome.io). This would also allow developers to use the many other FA icons in their stores.

**Comment by tanvirraj** [comment]
@patrys i wants to solve this problem as my first contribution on this awesome project 👍

**Comment by amorphic** [comment]
@tanvirraj sorry I beat you to it in #1083 ;-)
