### ISSUE TITLE
Production use?

### ISSUE THREAD

**Issue by rizplate** [mirumee/saleor#1085]
is any one using this in production?

Does it has concept of Seller or Fulfiller i.e. if the production is fulfilled by 3rd-party?

**Comment by vikas-0** [comment]
It has concept of seller

**Comment by elwoodxblues** [comment]
Hi @rizplate, we've been using Saleor in production successfully for over two years in multiple projects (sometimes in heavily customized versions).
By default we don't have a concept of product seller, but it can be easily added as new model related to product (if I understand you correctly).
