### ISSUE TITLE
Add own item set

### ISSUE THREAD

**Issue by mursalal** [mirumee/saleor#1090]
Hello, is it possible to add my own item set instead original?

**Comment by patrys** [comment]
What do you mean by "own item set"?

**Comment by mursalal** [comment]
@patrys product categories for sale (dresses, TV, Shoes,  etc.)

**Comment by patrys** [comment]
The dashboard should allow you to do just that. Log in as an admin and you should see a link to the dashboard near the top of the page.

**Comment by mursalal** [comment]
@patrys Thank you. I will try.
