### ISSUE TITLE
Specify the versions for node, yarn and webpack module bundler, please.

### ISSUE THREAD

**Issue by tarasinf** [mirumee/saleor#1092]
It is hard to guess what is workable versions.

**Comment by juanflorez** [comment]
hi, for what is worth, on my mac, it took me some time to figure out all the dependencies, as the criptical error of " did webpack created the blabla.json?" was not very helpfull. 
Finally, what I did was to:
1 - Ensure webpack was installed
2 - Run webpack
3 - Read the error of the module it could not find,
4 - run npm install 'module it could not find'
5 - check if some dependencies are needed
6 - run npm install dependencies
7 - go to step 4 until all are installed
8 - go to step 3  until all are installed

**Comment by tarasinf** [comment]
HI, thanks @juanflorez .
I used the next and it works:
- node: v6.11.2
- yarn:  v0.27.5
- webpack: v1.14.0

**Comment by patrys** [comment]
@juanflorez Do you have a list of modules you were unable to install? It's supposed to work out of the box with a single `yarn install` command.
