### ISSUE TITLE
Add option for customizable product

### ISSUE THREAD

**Issue by vikas-0** [mirumee/saleor#1093]
I am trying to implement this. the only problem is that cart is grouping two products as same even those two have different customization request

**Comment by patrys** [comment]
Do they have different `options`? If so, this would be a bug as product with different `options` are not supposed to be grouped together.

**Comment by vikas-0** [comment]
no, I don't think they have a different option. I added extra field "customization_info". content of this field is diffrent

**Comment by patrys** [comment]
Take a look at https://github.com/mirumee/saleor/blob/e9bf520560094fb9817887cbf44834ecf3e0d758/saleor/cart/models.py#L164-L171

**Comment by vikas-0** [comment]
I tried to change the value of data for the different order of same product variant. Now they aren't grouped together. But when trying to delete a line from the cart or update the quantity value, nothing happens. because front end logic is unable to differentiate between two line of the same variant. as there are only two parameters in the ajax request, variant id, and quantity.

**Comment by amorphic** [comment]
@vikas-0 it sounds like you're trying to do something similar to what I am in #1080 

I've made some progress on this and will have a PR up shortly if you're interested...

**Comment by vikas-0** [comment]
@amorphic I can't see any fork in your account

**Comment by hackedbellini** [comment]
@amorphic @vikas-0 I'm starting to take a look at saleor to implement it for my business and, wow, this issue (together with #1080 ) is something that I will need.

You both seems to have been doing some progress towards this. Can you link your changes to me? I want to take a look at it and see if I can contribute in some way so we can get this feature in saleor ASAP!

**Comment by vikas-0** [comment]
@amorphic can you guide me how to store data after the check out as the cart is cleared after chekout.

**Comment by vikas-0** [comment]
@hackedbellini [https://github.com/vikas-0/saleor/tree/data-passing](url) in this branch, I did create a form in product detail which take the json input of customization detail. and finally saved in the order. still there are front end issues like can't delete an item-line from cart if custom data is given.

**Comment by hackedbellini** [comment]
@vikas-0 hrm, after seeing your changes, I think what i need is actually something different from that. I'll probably have to discuss that in another issue. But anyway, good luck in your journey here!

**Comment by amorphic** [comment]
@vikas-0 @hackedbellini In [this branch](https://github.com/amorphitec/enstaved-shop/tree/1080_user-selectable_product_attributes) I've successfully added a new "custom" attribute class to Saleor. I've followed Saleor conventions as closely as possible and custom line items are treated separately in the shopping cart, both for stock management and on deletion.

It all works, I just need to add some tests before submitting a PR for consideration. In the meantime if you want to check out what I've done and provide any feedback please go ahead.

I still have to add some tests and then I'll submit a PR for consideration.
