### ISSUE TITLE
Question about Node & dependencies and Docker

### ISSUE THREAD

**Issue by DDiran** [mirumee/saleor#1097]
Hi,

I've just started learning Docker, Node, Yarn and Webpack so I can fully understand and sink my teeth into this project.

One thing I wanted to ask, shouldn't Node be included within the Docker image with Yarn and Webpack install commands? And shouldn't the [front-end asset and database commands mentioned in your docs](http://saleor.readthedocs.io/en/latest/development.html) be included in the docker-compose.yml? If not, what's the reason behind it? I'm running a windows machine and some of the Node-related stuff fails because of my OS and python version which I thought shouldn't be happening when using Docker.

Apologies if I'm off-track here, as I said I just started learning these tools.

Thanks

**Comment by patrys** [comment]
The main docker image is intended for production use so it's not supposed to contain Node and `node_modules`. You could add a separate image in `docker-compose.yml` that would be responsible for installing Node and running `yarn watch` while developing locally.

**Comment by DDiran** [comment]
Ah, I see now! Perfect, I'll tweak the settings a bit to get a development environment set up then, thanks @patrys!
