### ISSUE TITLE
Default Frontend Broken

### ISSUE THREAD

**Issue by dyablade** [mirumee/saleor#1099]
The default front end of the saleor auto generated website is broken and the elements are in the wrong areas, as shown in the included photo. What is the issue and what is the fix?
http://prntscr.com/gf37sh

**Comment by amorphic** [comment]
I don't think this is an issue with Saleor. A default deployment looks fine to me in various browsers and in various sizes.

**Comment by patrys** [comment]
It seems something went wrong when building assets. Please make sure that your `yarn`/`npm` dependencies are up to date and that the webpack build succeeded and if they fail open a separate bug with any error messages you encounter. Thank you!
