### ISSUE TITLE
Use Materialize.css in the StoreFront

### ISSUE THREAD

**Issue by damianarechar** [mirumee/saleor#1100]
¿It's possible(not to complicated or not to hacking the core) use Materialize.css in the Saleor FrontStore?

**Comment by patrys** [comment]
It would be possible it it's not something we have planned to do. We want the default storefront to remain easily adaptable for all kinds of branding requirements.

**Comment by jackwilsdon** [comment]
Have you considered moving the whole frontend over to react, essentially making it a single-page app?

**Comment by patrys** [comment]
Yes, we have. It's not an either-or decision however as we have projects that are good matches for both approaches.
