### ISSUE TITLE
Clear unused cart after a given time period

### ISSUE THREAD

**Issue by vikas-0** [mirumee/saleor#1101]
Lot of anonymous users can leave unused card in the database which may slow it overtime.

**Comment by elwoodxblues** [comment]
@patrys Do you think we should tackle this issue? I remember we might have had issue with this in one of our projects based on Saleor. Since we're introducing Celery now it could be delegated as a periodic task.

**Comment by Pacu2** [comment]
@maarcingebala shall we proceed?

**Comment by patrys** [comment]
Or provide a Celery beat config in settings?

**Comment by maarcingebala** [comment]
This shouldn't be an issue in the API, since we require emails to create checkout. We should rather think of handling abandoned checkouts.
