### ISSUE TITLE
Language Code

### ISSUE THREAD

**Issue by Danikarik** [mirumee/saleor#1102]
Hi!
I was trying set russian language, but no success.

I configured **LANGUAGE_CODE = 'ru'**, but didn't affect and **<html lang="{{ LANGUAGE_CODE }}" class="no-js">** in source code of html page is **"en"**.

Do I configure it properly?

**Comment by Simproduction** [comment]
Hi, 
you need configure LANGUAGE_CODE = 'ru' and if you want only one language (otherwise the server detect language automatic) on shop you need configure it 
LANGUAGES = [
    ('ru', _('Ru'))
]  
and then this should work as you want :)
