### ISSUE TITLE
Payment create_password redirects to localhost

### ISSUE THREAD

**Issue by xtakacsx** [mirumee/saleor#1105]
I have deployed saleor on heroku, i use Braintree as a payment method.
After a successful card payment i should get redirected to 

> http://<heroku_addres>/order/<order_code>/create-password/

insted of heroku_address i get redirected to localhost:

> http://<localhost:8000>/order/<order_code>/create-password/

 if i replace the localhost address with heroku address everything is fine.

**Comment by bogdal** [comment]
@xtakacsx You have to set an appropriate site domain in the dashboard `http://<heroku_addres>/dashboard/settings/`

**Comment by xtakacsx** [comment]
Thanks a lot!
I have changed the domain from localhost:8000 to <my-app>heroku.com
