### ISSUE TITLE
portfolio.Price.currency: (fields.E300) Field defines a relation with model 'Currency', which is either not installed, or is abstract

### ISSUE THREAD

**Issue by ravinkaur** [mirumee/saleor#1109]
SystemCheckError, when i run the command **_python ./manage.py migrate_**

Errors:

SystemCheckError: System check identified some issues:

ERRORS:

**portfolio.Price.currency: (fields.E300) Field defines a relation with model 'Currency', which is either not installed, or is abstract.
portfolio.Transaction.currency: (fields.E300) Field defines a relation with model 'Currency', which is either not installed, or is abstract.**

I'm quite new to Django. Can you help me how to solve this issue.

Any solutions? 

Thank you,
Ravin

**Comment by patrys** [comment]
What is `portfolio`? How is this related to Saleor?
