### ISSUE TITLE
No cash on delivery payments method

### ISSUE THREAD

**Issue by ghost** [mirumee/saleor#1110]
It will be nice have option to cash on delivery as payments method. It's some one to configure it :) ?

**Comment by gasbakid** [comment]
I agree with you Simon, i think i will give a try ;)

**Comment by CosminG** [comment]
I would also be interested in this.

**Comment by dhruvramdev** [comment]
Anyone Added Cash on Delivery or Any Community Plugin? Help Needed.

**Comment by xtranophilist** [comment]
https://github.com/xtranophilist/django-payments-cod
