### ISSUE TITLE
Standardize naming conventions in templates

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1124]
Template names in dashboard should use one naming convention.
- "list.html" for list views
- "details.html" for details view
- "form.html" for create/edit views
These files should be placed under the one directory named after model or app they relate to.

**Comment by elwoodxblues** [comment]
To do in "saleor/templates":
- [ ] "dashboard/discount" - templates should be grouped in two directories: "sale", "voucher"; inside directories they should be renamed to "form.html", "list.html" etc.
- [ ] "dashboard/shipping" - remove "method_" prefix 
- [ ] Drop "admin" directory, we don't use django-admin
- [ ] "order" - we have two templates "order-details.html" and "details.html" - this could probably be merged into one template

**Comment by salwator** [comment]
@elwoodxblues regarding "order" case:
It might be hard to merge "order/details.html" and "order/order-details.html". Template order-details is included in both details.html, payment.html and is non-trivial. I would suggest renaming order-detail.html to differentiate from details.html or redesign those templates.

**Comment by elwoodxblues** [comment]
Yes, you're right. So we should rename it, maybe something like `_ordered_items_table.html` (we usually use underscore prefix for partial templates)?
