### ISSUE TITLE
Add ability to create order from dashboard

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1125]
Staff users should be able to create orders from the dashboard. This will consist of the following parts:
- [ ] Adding products
- [ ] Ability to apply discounts or vouchers
- [ ] Setting shipping method and price
- [ ] Assigning a customer
- [ ] Setting shipping and billing address
- [ ] Sending confirmation email to the customer once an order is created. Since confirmation email contains a link to an order page, customers should be able to use it to pay for an order themselves.

Related issue: #1908 - on the order details page we should also have the ability to mark an order as paid. This will help when staff is importing an old order or the payment was received in some other way.

**Comment by elwoodxblues** [comment]
As I wrote in the related pull request, we're holding this feature for now. We've recently added the ability to impersonate users, which is the recommended way to create orders by staff users.

**Comment by mad-anne** [comment]
I met some problems during work on this issue.
1. What about updating discount amount with voucher applied?
For example: staff user sets shipping method with price $26 and then adds a voucher for free shipping. Discount amount is $26. If a shipping method will be changed now to a method with different price, e.g. $56, should we update a discount amount? If not, it can lead to a situation, when order with total value less than zero can be created. Same problem is with all types of vouchers.
In my opinion, it would be better to update discount amount every time it's value changes.
2. Should we update an order's discount_amount in draft orders if referenced voucher gets updated?
3. Should we add an ability to create order with no user or user_email provided? Storefront does not allow to do this, but maybe dashboard should.
4. We have two actions for modifying shipping, discount and customer (in progress) - edit and remove. Now they exist in dropdown menu, but maybe they should be in one modal opened on clicking edit button with Cancel/Update actions on the right and Remove action on the left?

**Comment by NyanKiyoshi** [comment]
For 3), in my own implementation of the order creation form, there is two types of customers:
- Registered customer (selected from dropdown);
- Anonymous User (no customer selected).

In my context, anonymous orders are quick IRL checkouts made by the cashier. So the cashier doesn't need to enter enter the customer information when purchasing IRL if the customer doesn't have an account and doesn't want to give us the information. So, the email address of the user is let blank in checkout and addresses blank as well.

Only thing we need is the invoice (and to allow to mark the order as paid and capture a fake full order amount as the payment was IRL and not through Paypal or anything else online requiring a callback).

**Comment by NyanKiyoshi** [comment]
I have a question about taxes, we should be able to choose what tax rate to apply on the order (at least, it's a requirement I have and must respect on my side, if you are okay with it). 

But, tax support will be implemented and merged during April from #1929, while #1971 will be merged way before.

First, do you think we should implement a way to choose the tax rate on order creation form? (and default it to settings default one).
Second, how and when should it be implemented?

My biggest concern is there is a risk of not taking some changes into account as we are creating orders (in #1971 as I write this), through `Order.objects.create(...)` and not like we would be doing during a checkout, through `Checkout.create_order(...)` as most of the order creation logic is inside it.

**Comment by elwoodxblues** [comment]
I think the ability to add orders without customer's data (addresses, email etc.) could be useful in some cases and we'll support it.

As for the taxes, I think we'll tackle it in #1929. I'm not familiar with tax calculation laws and rules yet so I can't tell what's the correct implementation here.
