### ISSUE TITLE
Add new base unit for some products

### ISSUE THREAD

**Issue by ImperfektDaemon** [mirumee/saleor#1126]
Hey,
I wonder what is the easiest and/or most reliable way to new base units for a section of products. For instance by default Saleor offers users to sell products and you can define the price per item it costs. But if i want to sell items per length unit, such as the price depends on the amount of meters a customer wants to order. How should I go about it? I guess I would have to "price_override" in the Product class, and later override the template view. But before I decide to do it I would like to here pros/cons, maybe someone else have already done it? Feel free to comment ideas and suggestions below:

**Comment by patrys** [comment]
Is the concept of "length" different from the usual "quantity"? I mean you'd probably want to change the fields to allow more decimal places but otherwise it sounds a bit like quantity in disguise.

**Comment by elwoodxblues** [comment]
@ImperfektDaemon In Saleor quantity is of integer type, but changing it to decimal should cover your case. Calculating price based on decimal quantities should work by default then. You'll also have to change the quantity inputs on product details page and in cart as they allow only integers as valid quantities. Don't forget about updating `quantity_allocated` field as well.

**Comment by ImperfektDaemon** [comment]
Thanks for your help. I found issue @ #1079 which also helped me understand what to do. So this issue can be closed if you want to. But I wonder, is weight and/or length planned to be part of the core saleor project in the future? Any reasoning you want to share?

**Comment by elwoodxblues** [comment]
Our aim is rather to keep Saleor as universal as possible and provide a good base for customization such as in your case. Decimal quantities are not on our roadmap for the nearest future, but we'll discuss that.

**Comment by patrys** [comment]
@ImperfektDaemon Could you give us some pointers on how we could improve our documentation and docstrings in code to make understanding customization an easier task for newcomers?

**Comment by MacLake** [comment]
What would have helped me in adding shipping by mass (weight) (#1079) is:

- A description of the whole shopping process, mentioning which URLs, views, models and templates are used in which step of the process. I can give you a text with what I found out. Maybe you want to use it as a base.

- Docstrings of all classes methods and functions: What exactly do they do? In many cases it’s not obvious and it takes a lot of time to find out.

Btw, what is the best place to discuss general things like documentation and features? Here or in another forum?

**Comment by patrys** [comment]
I feel that this is the best place to talk about it as it's the closest to the actual code.

**Comment by amorphic** [comment]
I just spent a lot of time understanding the Saleor codebase to add custom properties. I agree with both of @MacLake's suggestions, particularly use of docstrings. I'll add some to the PR I submit and I'd be happy to help out in any other way that I can to make it easier for other devs to modify/contribute.
