### ISSUE TITLE
Navbar renders incorrectly at width >2294px

### ISSUE THREAD

**Issue by amorphic** [mirumee/saleor#1130]
When the browser width is >2294px the `login` and `brand` components of the navbar are rendered side-by-side instead of one above the other:

![image](https://user-images.githubusercontent.com/1538480/30622373-9ca88ec4-9df4-11e7-8c21-8121e67789a6.png)

This seems to be related to the `max-width` set in `storefront.css`. I tried manually incrementing this value and when I hit `max-width: 1274px;` the navbar rendered correctly.

I'm guessing this is due to the recent change to a newer version of bootstrap 4.

**Comment by dominik-zeglen** [comment]
Fixed in #1137
