### ISSUE TITLE
Common template for delete views in dashboard

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1131]
Currently each delete view in dashboard has its own template. Instead we should have one generic template that will be reused in each delete view. Deleting is a two-step action since it's destructive and user has to confirm it. For this reason we use modals as templates for confirmation.

Our new base template should be simple modal with the following [blocks](https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#std:templatetag-block):
- action_url
- title
- content

The modal will have two actions at the bottom:
- Cancel - closes the modal
- Delete - submits the form
They'll be common to each subclassing template so we don't have to wrap them in blocks.

For now we could only customize `category_delete`. Deleting a category results in removing all products which is dangerous and requires a warning.

Definition of done:
- [x] Add generic "modal_confirm_delete.html" template.
- [x] Update existing delete templates to inherit the generic one.
- [x] Add tests for delete views.

**Comment by patrys** [comment]
I would be 👎 on string templates like "Delete {{ object }}" and "Are you sure you want to delete {{ object }}". Those are a nightmare for i18n and don't indicate what object you're removing.

**Comment by elwoodxblues** [comment]
What do you propose instead?

**Comment by patrys** [comment]
I propose that the backend always passes in a full string so I can translate "Delete user {{ user }}" differently than "Delete product {{ product }}".

**Comment by elwoodxblues** [comment]
Do you want to pass both title and body? We could only pass the title and in the body keep generic content as "Are you sure you want to delete this item?".

**Comment by patrys** [comment]
How would you translate this generic message into Polish? Consider that the "item" may very well be a user or an order.

**Comment by elwoodxblues** [comment]
OK so you want to pass both title and content from backend? I hope that this will not tempt people to write HTML tags in backend when they want add a new line in a body etc.

**Comment by elwoodxblues** [comment]
Maybe the best solution would be to have one base template for deleting with good blocks for title and content and extend it each time you want to add a new delete view? This would be a compromise between what we have now and what I initially proposed.

**Comment by patrys** [comment]
Sounds like a plan. I just don't want us to abstract so much away that we eventually paint ourselves into a corner.

**Comment by salwator** [comment]
In case of both title and content being injected from outside, I see little if not none use in delete-specific abstraction for modal. Why wouldn't it be generic modal parametric template?

**Comment by elwoodxblues** [comment]
@salwator I've updated the issue description. I think we'll benefit from introducing a common base template. Adding a new view will require only to add three simple template blocks.
