### ISSUE TITLE
Unable to install Saleor

### ISSUE THREAD

**Issue by Rorroh** [mirumee/saleor#1134]
Recently found this and it looks a lot better to work with than the alternative that I was using previously.  Unfortunately I'm having a few problems getting it installed to my Ubuntu 16.04.3 VPS when following the [RTD guide](http://saleor.readthedocs.io/en/latest/installation.html).  Of note:
 - Doesn't work with NodeJS 7
 - Doesn't work with Yarn 1.x
 - `sudo yarn` warns "fsevents@1.1.2: The platform "linux" is incompatible with this module." (I'm not sure if this is actually bad)
 - Using NodeJS 6.11.3 and Yarn 0.20.3, `sudo yarn run build-assets` crashes with the following:
> saleor@saleor:~/saleor$ sudo yarn run build-assets
> yarn run v0.20.3
> $ node ./node_modules/webpack/bin/webpack.js -p
> internal/child_process.js:303
>   var err = this._handle.spawn(options);
>                          ^
> 
> TypeError: Bad argument

I also tried deploying to Heroku via the button in the readme and that crashed in some way as well, but when I went to try it again just a moment ago to get the error message I'm now apparently having an issue with installing the sendgrid add-on.  That's obviously unrelated to this, but frustrating because it means that I can't give any reference for why that was failing for me.

Any idea what might've gone wrong with this?

**Comment by rlimaeco** [comment]
You could try docker-compose , and relax :)

**Comment by amorphic** [comment]
@Rorroh note the requirements specified in per [`package.json`](https://github.com/mirumee/saleor/blob/master/package.json):

```
  "engines": {
    "node": "6.x",
    "yarn": "0.20.x"
},
```

I'm pretty sure Yarn 1.x is known not to work.

Before raising an issue it's always a good idea to do a quick search through existing issue first. #1076 and #1020 sound relevant to your situation and the comments mention a few things that you might try. You could also try commenting on one of these and ask for questions directly of somebody else in the thread.

Also note that the `fsevents` warning is innocuous and can be safely ignored.

If you're happy with this response then please close this issue off. Persevere - I promise you Saleor is worth it...:-)

**Comment by Rorroh** [comment]
@rlimaeco I was getting permission issue when sudo was omitted.

@amorphic
Yeah I realised the requirements listing, but the guide was pretty ambiguous about it when I first attempted it.

Whoops, my bad!  I did a quick check but I guess I didn't look hard enough.  I'll try their solutions, report back, and close if I get it resolved.  This setup has quite a few hoops to jump through currently.  This better be as worth it as you say ;P  Thanks a lot!

**Comment by patrys** [comment]
We are likely to move to Node 8 and npm 5 soon. Most yarn crashes we know of are caused by running the build command in containers with very little memory.

**Comment by Rorroh** [comment]
The issues were on a 512MB VPS so I started up a new 2GB droplet to take another crack at it.  The upgrade in RAM solved the first issue and I ended up needing to `apt-get install libfontconfig` as well.  Went smooth as butter once everything was taken care of.  Thanks for pointing me in the right direction @amorphic.  I look forward to working with this!
