### ISSUE TITLE
Add cost price to OrderedItem

### ISSUE THREAD

**Issue by mperesson** [mirumee/saleor#1140]
Hey,
Not an issue, just a question/suggestion. I want to know if you may add it to saleor or if I need to make a custom dev.

I buy my stock from different suppliers mostly via API, that's why my stock records quantity/cost price are regularly updated. 

In order to calculate my margin per order, I would need to store the cost price of each item in the OrderedItem object (like it is done for the sell price, because my cost price is varying like my sell price).

It would be a redundant information for most people but it's also the case for "stock_location" of OrderedItem.

(also, I noticed that you merge a lot of pull request ATM, do you plan to make a new "stable" release any time soon?)

**Comment by elwoodxblues** [comment]
Hi @mperesson, OrderedItem is a good place to store such information and we used to do similar things in some of our projects based on Saleor. However this is not something very common so we're not planning to add it to Saleor in the nearest future. Our goal is to keep the "core" simple and flexible.
As for the recent activity in the project you're right - we've assembled a new team of people who are working on Saleor's development. You can find the roadmap in Saleor's wiki. Feel free to give us feedback and share your impressions on what can be improved.

**Comment by mperesson** [comment]
Hi,
Thanks for the answer! I didn't knew the wiki page.

So no "release date" for some stable version? My shop is online at 50% already so I don't want to update saleor version every weeks :)

**Comment by elwoodxblues** [comment]
Not yet, but expect updates in the near future. The wiki page is a new thing. We're working on improving the release process and informing the community about what's going on in the project.
