### ISSUE TITLE
Set currency on the right side of the price

### ISSUE THREAD

**Issue by CosminG** [mirumee/saleor#1142]
Is there a possibility to set the currency to the right of the number? Like: 24.54 RON

**Comment by patrys** [comment]
Currencies are formatted according to the active locale and should always use the correct format given that correct locale rules are in effect. You can also discuss that and do your own price rendering by overriding the price template tag or the template it uses.

**Comment by CosminG** [comment]
I have set in settings.py:

TIME_ZONE = 'Europe/Bucharest'
LANGUAGE_CODE = 'ro'
LOCALE_PATHS = [os.path.join(PROJECT_ROOT, 'locale')]
USE_I18N = True
USE_L10N = True
USE_TZ = True
DEFAULT_COUNTRY = 'RO'
DEFAULT_CURRENCY = 'RON'
AVAILABLE_CURRENCIES = [DEFAULT_CURRENCY]

But the price is displayed: RON24.54, not as desired 24.54 RON.
Is there something I miss here?

**Comment by elwoodxblues** [comment]
@CosminG This configuration you're using looks fine, please check also what locale you have set in your browser.

**Comment by CosminG** [comment]
It is: en-GB, but I would like the store to use 24.54 RON all the time. For now the target is only Romania.

**Comment by elwoodxblues** [comment]
The only solution to force this formatting regardless of browser locale would be to remove all occurrences of `django_prices.templatetags.prices_i18n` that we use both in backend and in frontend to format prices. Instead you should use `django_prices.templatetags.prices` which provides similar template tags but don't take the locale into account.

**Comment by patrys** [comment]
That or force the locale to always be ro_RO. This will also make sure number formatting is correct, dates work as expected etc.

**Comment by elwoodxblues** [comment]
@CosminG Were you able to fix this issue?

**Comment by elwoodxblues** [comment]
I'm closing this for now, please reopen if there are any further questions or problems.

**Comment by CosminG** [comment]
Using django_prices.templatetags.prices do not work:
```
web_1     |   File "/app/saleor/checkout/forms.py", line 5, in <module>
web_1     |     from django_prices.templatetags.prices import format_price
web_1     | ImportError: cannot import name 'format_price'
```

**Comment by CosminG** [comment]
How can I force the locale to always be ro_RO?

**Comment by CosminG** [comment]
@elwoodxblues how can I reopen?
