### ISSUE TITLE
Staff management

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#1143]
AFAIK there's still no easy way to grant/remove `staff membership` to one, from the dashboard. 
`staff list`/`groups` could be grouped under one dropdown in 'Configuration' settings.
`staff list` could be expanded for granting/removing `staff membership`

**Comment by patrys** [comment]
I'm not sure what you're proposing?

**Comment by Pacu2** [comment]
I was thinking about the functionality to grant staff membership to existing customer, by his email.
Would simplify the process of creating new store admins.

**Comment by patrys** [comment]
I think a more common use-case we should also solve is demoting existing staff members when someone leaves the company (remove their staff status and strip all of their permissions).

**Comment by elwoodxblues** [comment]
We should have views to create/edit users from dashboard which would also cover staff users management.

**Comment by Pacu2** [comment]
I would opt for keeping staff management in one place, instead of splitting it to 3 different panels, but some good linking between them will do

**Comment by patrys** [comment]
@Pacu2 Customers management and staff management are two very different use cases even if some people are in both groups.

**Comment by koradon** [comment]
Staff detail view is prepared and we need only to add there next form with all staff related fields.
