### ISSUE TITLE
Unified coding style

### ISSUE THREAD

**Issue by salwator** [mirumee/saleor#1147]
Since it is an open source project, common understanding of coding style might not be achievable by itself. I would suggest putting checker or even auto-formatter inside repository.

One of obvious solution would be [pylint](https://www.pylint.org/). It checks pep8 and supports even auto formatting, however it would not reformat code that does not directly violates any rule, which may be too soft approach for uniform code styling. Pep8 might not be the only source of coding style agreements.

Other tool we could use is [yapf](https://github.com/google/yapf). If follows [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html) footsteps, which in my opinion is a good thing. The idea is  to provide set of guidelines, tool will do best to follow them and reformat code accordingly.

Obviously, we still need wiki/documentation with coding guidelines, with or without automated tool.

What do you think?

**Comment by patrys** [comment]
We use Code Climate: https://codeclimate.com/github/mirumee/saleor

**Comment by elwoodxblues** [comment]
For example we're missing checks that would force consistence in:
- breaking long lines (e.g. parenthesis vs. slashes)
- using single/double quotes

**Comment by salwator** [comment]
@patrys I'm aware of it, it does only pep8 checks and is not capable of auto-formatting code. It should stay to ensure consistency of commited work. @elwoodxblues mentioned two possible problems not covered by it.

I see some issues worth unification effort, for example:
- splitting imports
- blank lines in classes
- closing brackets position
- long list/dict comprehensions
- etc.

**Comment by patrys** [comment]
It should do pylint checks as well unless it's no longer configured properly. Let's try to fix that first.

I'm -1 on _automatic_ code formatting as it tends to introduce unrelated changes. We should keep cosmetic changes separate from changes to logic.

I'm +1 on having a consistent style and possibly an automatic tool we can use to format code. From my experience formatting is one thing but it won't prevent you from writing ugly code (eg. correctly wrapping Django code with long train-wrecks of chained functions will not make the code any more readable).

**Comment by salwator** [comment]
@patrys I would never suggest running automatic reformatting of existing code without coder interaction :smile: Whole point of tool would be to ensure programmers confidence in commit code quality, cut down time spent on tedious stuff.

Fully agree with you, look up yapf or clang-format, you might be surprised how smart it is.

**Comment by patrys** [comment]
I know `yapf` and can tell less than successful stories of it trying to deal with long lines, especially coupled with long string constants 😄

**Comment by maarcingebala** [comment]
See #3846
