### ISSUE TITLE
Sorting products by price

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#1148]
Sorting by price doesn't work as expected when product has discount or it's variants override the price. That's because we're sorting only by the price field from the `Product` model. I'm afraid that with so many factors we're not able to sort products properly using database. On the other hand sorting in Python would be inefficient for large querysets. The only solution I see is to store the current minimum price in Product model in additional field that would serve only sorting purposes. We would have to make sure that this field gets updated when editing products, variants and discounts.

**Comment by patrys** [comment]
I'm not sure we should take variant prices into account. The product price should be indicative of at least some of its variants (if none of the variants have the same price as the product then the product price is meaningless).

**Comment by koradon** [comment]
@elwoodxblues should we also have maximum price for "sort by price descending" option?

**Comment by patrys** [comment]
Are we planning to display "up to $999" on the list? If not, sorting by max price will appear broken to the end user.

**Comment by koradon** [comment]
@patrys do you mean products with price from range 0 to $999?
My question was more if minnimum price is the only one we take in count when we sort products.

**Comment by patrys** [comment]
I mean that if we only show the minimum price and sort by a maximum price all of the results will look broken as prices will appear to be mixed randomly.

**Comment by koradon** [comment]
@patrys in that case there should be different price presented to the user. But I was not sure if we want this at all.
And maybe a minimum_price field would be useful for calculating discounts and removing it but this is a simple math and I don't know what would be more efficient.

**Comment by maarcingebala** [comment]
We support sorting by the minimal variant price now.
