### ISSUE TITLE
update_index not working with Elasticsearch 5.4

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1149]
When running `python manage.py update_index` the following errors occurs:
```
elasticsearch.exceptions.RequestError: TransportError(400, 'No handler found for uri [//storefront__userprofile_user] and method [DELETE]')
```

**Comment by frozenpixel** [comment]
I had the same issue. To fix it, I removed the '/' at the end of the ELASTICSEARCH_URL in docker-compose.yml.
