### ISSUE TITLE
Integrate Celery

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1153]
Almost every project needs a task queue and Saleor should come with one by default. Celery is one of the most popular task queues for Python and it's also easy to integrate and use. Things that should be run in task queue by default include:
- sending emails
- generating feed files (Google Merchant feed)

**Comment by mociepka** [comment]
Thumbnails generation should be delegated as well. What tool for that we are using right now @elwoodxblues ?

**Comment by elwoodxblues** [comment]
`versatileimagefield` generates thumbnails when they are first accessed, there is no pre-generation right now if I'm correct.
