### ISSUE TITLE
Dropdown menu display wrong

### ISSUE THREAD

**Issue by DonerKebab** [mirumee/saleor#1165]
![screenshot from 2017-10-07 22 46 45](https://user-images.githubusercontent.com/10070648/31309590-aa4d8be4-abb2-11e7-832c-7aba3832d24e.png)

I wanna have a multiple-level menu but that's what I got. Dropdown menu didn't display like i expected. Anybody ran into the same problem? Please help !!!

**Comment by patrys** [comment]
Can you explain what this is shown in the screenshot above? Did you get any error when running `yarn run build-assets`?

**Comment by DonerKebab** [comment]
Sorry, my fault. It just related to scss.
