### ISSUE TITLE
Products with sale on category index doesn't have "Sale" string in Spanish

### ISSUE THREAD

**Issue by koradon** [mirumee/saleor#1183]
On the ribbon on the products on category/index.
This translation has comment to be max 4 characters long but in Spanish it is "Liquidación"
![screenshot from 2017-10-12 16-37-08](https://user-images.githubusercontent.com/11785371/31501828-9d3a2482-af6b-11e7-8f6c-6ee21f0eb430.png)

**Comment by juanpagfe** [comment]
Fixed on #1249
