### ISSUE TITLE
Add database backend for search

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1187]
We should add database backend for searching that would use Postgres full text search capabilities. Once we have Elasticsearch integrations sorted out (#1177) we should be able to switch between search backends (with database backend as default). We could also investigate if it is possible to write abstraction for faceted filtering in both database and Elasticsearch backends.

**Comment by salwator** [comment]
@elwoodxblues I think it might be a good idea to implement database search backend after rewrite of elasticsearch backend is ready, or at least its interface matures.
