### ISSUE TITLE
Sitemap always show: http://example.com

### ISSUE THREAD

**Issue by DonerKebab** [mirumee/saleor#1195]
My sitemap.xml always show domain name as: http://example.com/ even I changed domain in dashboard - site settings to my domain.

**Comment by elwoodxblues** [comment]
I think that sitemap uses `django.contrib.sites` to determine the domain. Make sure you have it properly configured. To get the current site:
```
from django.contrib.sites.models import Site
Site.objects.get_current()
```

**Comment by bogdal** [comment]
@DonerKebab Thanks for reporting this. The site map should use the same domain, which you can see in the dashboard.

**Comment by tylfin** [comment]
I'll work on this

**Comment by bogdal** [comment]
@tylfin Please see the discussion in PR #1196

**Comment by koradon** [comment]
With PR #1214 Site.objects.get_current() will return proper value of domain
