### ISSUE TITLE
IE11  incompatibility 

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#1199]
Arrow functions are not supported by IE11. We use some in the storefront, to be discussed if we want to fully support this browser(approx. 3% of global share).
https://caniuse.com/#feat=arrow-functions

**Comment by patrys** [comment]
Don't we use babel?

**Comment by Pacu2** [comment]
@patrys Right, matter of my local configuration, on getsaleor demo store arrow functions are not present
