### ISSUE TITLE
Fix the css style is in dashboard..

### ISSUE THREAD

**Issue by justsushanth** [mirumee/saleor#1203]
Fix the css style is in dashboard..

**Comment by dominik-zeglen** [comment]
Hello!
Thank you for your feedback, but we need some details or screenshot where, when and which element is broken. Also, please make sure that you built up assets correctly.

**Comment by justsushanth** [comment]
I did not change anything in code , when I installed in local machine I got some error in dashboard, please resolve it as soon as possible.

path: login as admin
i

**Comment by dominik-zeglen** [comment]
Could you post full log or at least screenshot, so we know what we are dealing with?

**Comment by justsushanth** [comment]
![screen shot 2017-10-20 at 10 40 49 am](https://user-images.githubusercontent.com/25104420/31806078-4e380de0-b583-11e7-8399-e1ccb4246875.png)
![screen shot 2017-10-20 at 10 41 00 am](https://user-images.githubusercontent.com/25104420/31806079-4f357318-b583-11e7-8a5e-8b8c2a8ab37e.png)


Please find the attachment...

**Comment by dominik-zeglen** [comment]
Thank you very much, our team is working now to solve this issue.

**Comment by MAkcanca** [comment]
Can you check your javascript console for errors? I think this could be an issue with your installation and not script.

**Comment by justsushanth** [comment]
Yes right.. its installation error.. now issue has been resolved .. thanks for your support .
