### ISSUE TITLE
Order details and invoice

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#1216]
Two things need to be fixed:
1. Invoice's grand total cost equals sum of products' and shipping prices from whole instead of a particular shipment.
2. There should be option to change shipping method when splitting order into two or more shipments. Currently it is not possible; also shipping price is set to 0.

**Comment by patrys** [comment]
Note: Splitting order is not meant to increase the total price (or the shipping price). The customer is not expected to pay extra once they went through checkout.
