### ISSUE TITLE
Getting error (Bad Request (400)) Heroku Custom domain

### ISSUE THREAD

**Issue by justsushanth** [mirumee/saleor#1217]
Hi,

I am getting error like Bad Request (400) when I connect the custom domain to my herokuapp ..

Even I add the allowed hosts in settings.py file  but issue still not resolved..

Kindly fix this issue..

Please find the attachment 
![screen shot 2017-10-24 at 6 24 34 pm](https://user-images.githubusercontent.com/25104420/31944115-a22f51f2-b8e8-11e7-8b0f-047596b2361a.png)

**Comment by bogdal** [comment]
@justsushanth Please add your domain to `ALLOWED_HOSTS` env variable `Heroku->Settings->Reveal config vars` (use space as a separator) and then restart all dynos.

**Comment by justsushanth** [comment]
Resolved ,thank you...
