### ISSUE TITLE
BabelDjango upgrade

### ISSUE THREAD

**Issue by bravamin** [mirumee/saleor#1227]
can BabelDjango be upgraded with [django-babel](https://github.com/python-babel/django-babel)?

I see it's set to >=0.2 in `requirements.in` but the most recent version I see is [0.2.2](https://pypi.python.org/pypi/BabelDjango) from 2008?

Seems like the only things that use BabelDjango are the `LocaleMiddleware`(using the pre-1.10 middleware syntax) and `currencyfmt` in `/cart/views`. Is that right?

**Comment by patrys** [comment]
Yes, we should very much upgrade both in Saleor and in django-prices.
