### ISSUE TITLE
CheckoutDiscountForm - queryset is not working as expected

### ISSUE THREAD

**Issue by szewczykmira** [mirumee/saleor#1233]
QuerySet for ModelChoiceField is initialized with start of the server, but evaluated when form is rendered. 
Because of that `today = date.today()` in `active` queryset will be executed only once, and we filter vouchers with `start_date` before start of the server.

**Comment by patrys** [comment]
@koradon Please have the `active()` method explicitly require a `date` parameter instead of determining `today` inside the function. This way no one will be able to shoot their own foot in future.
