### ISSUE TITLE
Please Add the blog and static page features

### ISSUE THREAD

**Issue by iamsushanth** [mirumee/saleor#1240]
With respect to above subject saleor requires some more features like blog & static web pages to manage the static contents ..

**Comment by elwoodxblues** [comment]
Thanks for your input @justsushanth! We've already had a few requests about this feature and also a few discussion internally. Our plan is to add a widget for simple visual text editing, not necessarily a full-featured WYSIWYG, but rather something simple as Medium editor.
As for the static pages, we used to implement them using simple, static Django views or `django.contrib.flatpages`. We'll think if we can add some kind of generic solution to this, but for sure we'd like to avoid implementing a CMS inside Saleor - there are already good solutions for this in Django.

**Comment by ashtonhylton** [comment]
@elwoodxblues do you have any CMS or Django plugins you recommend? Or any guidance on how best to implement a feature like this that will integrate well with Saleor. Also any recommendations like the above but for a blogging feature.

**Comment by amorphic** [comment]
@ashtonhylton FYI we've just been through this process for [enstaved.com](http://www.enstaved.com). We run everything containerised and elected to keep our blog + landing page completely separate from our web shop (as you can see from the link).

It may seem easier to shoehorn your blog + website into your Saleor shop but in the long run it's better to keep the services decoupled. For example we chose [Ghost](https://github.com/TryGhost/Ghost) for blogging (it's awesome). If we want to change that later, we can do so without it having any affect on our web shop.

Just something to think about...

**Comment by ashtonhylton** [comment]
Thanks @amorphic yeah I see your point.

I do want the shop and blog to be more seamless though. I've done this before in php integrating wordpress using the objects provided and generating the blog pages myself. 

I think this is quite important for users experience and branding. However if they are separated then i guess its arguably less difficult to make the two feel like the same website than integrating a blog into saleor.

**Comment by amorphic** [comment]
@ashtonhylton I totally get your points. In fact since I wrote that comment back in January we're re-thinking it all ourselves.

**Comment by maarcingebala** [comment]
As we are focused now on the transition from classic Django to GraphQL + React clients, adding new features is not our priority. But when the whole platform gets more stable, I think we may get back to this idea and implement blogging functionalities. We already have an app for managing static pages. We would only need to think of better editor for rich-text content, e.g. [draft.js](https://draftjs.org/).

**Comment by shakkaist** [comment]
is there any update about blog at Saleor
