### ISSUE TITLE
webpack not generating by yarn or npm, not sure how to get this file and solve this issue.

### ISSUE THREAD

**Issue by Mitaanshu-Agarwal** [mirumee/saleor#1242]
![screen shot 2017-11-02 at 6 29 45 am](https://user-images.githubusercontent.com/18252382/32293473-58ad8dc2-bf97-11e7-9c31-721687dd8d6c.png)

Everything works locally but not when i'm hosting on heroku. Not sure how to configure it accordingly.

**Comment by Mitaanshu-Agarwal** [comment]
Everything works locally but not when i'm hosting on heroku.

**Comment by dominik-zeglen** [comment]
Did you deploy Saleor using Heroku's CLI or by "deploy" button from GitHub page?

**Comment by Mitaanshu-Agarwal** [comment]
@dominik-zeglen using heroku CLI

**Comment by Mitaanshu-Agarwal** [comment]
@dominik-zeglen thanks heaps man it works via "deploy button". 
Just one naive ques for continuous integrations.
I can still do git add .
git commit
and push it to master. Right?

**Comment by patrys** [comment]
@Mitaanshu-Agarwal 

If you visit your Heroku control panel, go into app details and select the "Deploy" tab you should see an option to integrate with GitHub and deploy automatically each time a particular branch is updated on GitHub.

You can also use Heroku Pipelines to automate testing feature branches or to release changes to a staging environment first and then promote them to production after testing.

Do keep in mind that maintaining multiple environments can and likely will incur additional costs. Hope this helps.

**Comment by patrys** [comment]
I believe this is fixed with the updated deployment docs. The command list was missing a critical setting that prevented Webpack from being installed.
