### ISSUE TITLE
Heroku Build failed - Two different lockfiles found: package-lock.json and yarn.lock

### ISSUE THREAD

**Issue by alcfernandes** [mirumee/saleor#1245]
Hi!

I'm getting the message  "Build failed - Two different lockfiles found: package-lock.json and yarn.lock" when deploying the application on Heroku.

Heroku says to remove yarn.lock, but there is no such file.

Does anyone know what I need to do to resolve this?

I'm working with code from v2017.09 release.

Thanks.

**Comment by patrys** [comment]
Likely you have a leftover file from a previous build. Indeed Saleor no longer has a `yarn.lock` file as we no longer require `yarn`.

**Comment by alcfernandes** [comment]
Thanks for the answer. I was making a mess with the branches here and there was actually this file. Problem solved.
