### ISSUE TITLE
Move shipping price from delivery groups to order level

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#1256]
There's not really a business case to keep delivery price (not delivery method!) at group level. I guess it does anwer the hypothetical question "how much did we charge for delivering these" but in practice it complicates cases such as splitting orders or moving the last item line from one delivery group to another where extra care needs to be taken not to change the total shipping cost (the customer has already paid, we promised them a certain price).

**Comment by patrys** [comment]
CC @mociepka

**Comment by elwoodxblues** [comment]
So if I understand correctly:
- delivery price should live at the order level
- delivery method name should remain at the delivery group level

And we assume that in future we'll allow changing the delivery name for a group, keeping the order-level shipping price intact?

**Comment by patrys** [comment]
Yes. If the storeowner has to change the shipping cost after you've already paid for your order (which should be an edge case) then they should do it explicitly by editing the shipping price. No other operations should accidentally affect the pricing (including splitting an order or merging two delivery groups into one).

Price editing is a separate feature (and likely a separate permission) though, we should allow product prices to be edited as well.
