### ISSUE TITLE
Add staff management section in dashboard, add permissions for Configurations section

### ISSUE THREAD

**Issue by koradon** [mirumee/saleor#1259]
In dashboard we need to move 'Staff members' and 'Groups' to separate section called 'Staff management'.
Also we need new permissions for view/edit those sections.

Change Configuration permission check from 'is_superuser' flag to separate permissions.
Add new permissions to SiteSettings model.

DoD:
- [x] New permissions in userprofile.models.User for view/edit Groups and Staff members
- [x] New section in Dasboard 'Staff management'
- [x] Add new permissions for the rest 'Configuration' section to SiteSettings
- [x] Update views permission_required decorators 
- [x] Tests of permissions for new section

**Comment by Pacu2** [comment]
In this issue, we want to get rid of `superuser_required` decorator from the dashboard. Relevant permissions should be created

**Comment by akjanik** [comment]
@Pacu2 Just to  be clear, you want this decorator to be removed from _every_ view and replace with proper `permission_required`?

**Comment by patrys** [comment]
@akjanik Yes, that's the goal. There should be nothing superuser-specific in our code.
