### ISSUE TITLE
Problems with product image view in the dashboard

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1260]
There are few problems with the view for editing images in the dashboard:
- colliding labels at the top ("Point of interest")
- checkbox "clear" is not working
- button to select a new image is not working

![image](https://user-images.githubusercontent.com/5421321/32446797-5c38d570-c30a-11e7-818e-36da250d9088.png)

**Comment by patrys** [comment]
I think showing the *disk* path to the image is a case of oversharing internal details.

**Comment by elwoodxblues** [comment]
Yes, we should only show the file name.

**Comment by koradon** [comment]
Checkbox and button are (probably) not working because something is covering it in template. If path (or in my new version, filename) is too short, clicking on it is not opening an image.
