### ISSUE TITLE
Dashboard improvements

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#1263]
I've recently got a moment to develop my Saleor based site, here's couple of things I found:
1. Logo changing
Logo is named `saleor_logo.svg` renaming it to just `logo.svg` would allow us to drag-and-drop new one. 
Also, some special logo CSS styles (like `fill`) are not helping, little bit of time could be saved here.
1. Breadcrumbs on the dashboard
Can't tell if they are clickable or not at the first sight.
![breadcrumbs](https://user-images.githubusercontent.com/21290461/32451153-722e67e4-c316-11e7-857f-79f9a33f2e2f.png)
Quick sketch of my proposition:
![proposition](https://user-images.githubusercontent.com/21290461/32451320-d5a02786-c316-11e7-9048-a2876af2bbfb.png)

- Separators between breadcrumbs
- Currently active breadcrumb in different color/style
- Clickable breadcrumbs underlined on hover

3. Categories
Deleting/Editing could happen from the list view (more obvious). To edit category one need to enter it and activate small drop-down in the upper right corner

4. Adding attribute values
https://demo.getsaleor.com/dashboard/products/attributes/10/
Only one attribute's value can be added at the time. Dynamically rendered fields would be helpful here.

**Comment by patrys** [comment]
I agree with (1), we should not be branding file names.

(2) looks like a bug. There were proper breadcrumbs with separators.

**Comment by Pacu2** [comment]
Breadcrumbs screenshot comes from the demo store

**Comment by patrys** [comment]
Breadcrumbs work on master (testing on Heroku). I suppose this is related to static file fixes.

**Comment by elwoodxblues** [comment]
1 - it has already been fixed
2 - there was a bug with displaying the separator icon properly, but we fixed that as well
3 - categories views have been updated to follow the same UI patterns as all other views (a details view, list of subcategories with "Add" button at the top etc.)

I'll open a new ticket for UX review in the dashboard and add few things mentioned in this issue that are still open for further discussion.
