### ISSUE TITLE
Use libphonenumber for phone number validation

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#1273]
We do postal address validation but currently do nothing to validate phone numbers.

Here's a Python port of `libphonenumbers`: https://github.com/daviddrysdale/python-phonenumbers

Here's a library that implements a Django field: https://github.com/stefanfoulis/django-phonenumber-field

**Comment by Pacu2** [comment]
Form only or model field as well? 
I think the model change will cause a problem for people who already have some data and would like to update saleor in the future

**Comment by patrys** [comment]
I'm not all that concerned about upgrading outside of the development phase. If you set the default country to a proper value all data should migrate cleanly. Otherwise the migration should fail so you can fix the data first.
