### ISSUE TITLE
Figure out if `email_confirmation_message` template is used for anything

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#1287]
The template at `templates/account/email/email_confirmation_message.txt` looks like an old template with poor grammar and Saleor's name hardcoded in several places.

**Comment by koradon** [comment]
It is not used anywhere in code.
The only occurrence of 'email_confirmation_message' is in locale.

**Comment by elwoodxblues** [comment]
@koradon Then this template can be removed.

**Comment by koradon** [comment]
I believe that email_confirmation_subject comes with this message template. Also not used anymore in project.
