### ISSUE TITLE
Products tags

### ISSUE THREAD

**Issue by bellini666** [mirumee/saleor#1297]
I need a way to set tags in a product. Those tags will be useful to organize products in sections, for searching, to display related products in their pages and also to better categorize somethings for the users.

An example for clothing would be: I have a product named `T-Shirt Foo Bar`. I can tag it with `summer-2017`, `beach`, `casual`, etc.

At first I though to create an attribute for it. The first problem is that there's no way to define multi-valued attributes atm. Other problem is that it would be hard to integrate with the search/product page/etc since it's something custom and created by the user.

The other solution that I thought was to define it in `Product` class. Just like a product have a `name` and a `price` I think it can also have `tags`.

What do you think for the proposal?

I'll try to implement this (unless someone is already working on something like that) and would really appreciate your feedback since I would like to contribute it back to you.

**Comment by patrys** [comment]
Hey, we're planning to change current categories to taxonomies (tree structure, many-to-many) while introducing a strict one-to-many relation to a category. Would this solve your case?

**Comment by hackedbellini** [comment]
@patrys that probably would solve my case! Is that already being worked on? I might need something like that for mid december max.

I can help with the development of the feature also unless there's already enough people working on it.

**Comment by patrys** [comment]
Feel free to help! 👍 I don't think anyone is working on this at the moment.

**Comment by hackedbellini** [comment]
@patrys great! I'll assign this issue to me then.

Btw, do you have a public dev chat place where I can talk to you if I need to ask something quickly? Like an irc channel, a slack room, etc?

**Comment by chrisaq** [comment]
@hackedbellini 
There is gitter, but it seems pretty dead.

https://gitter.im/mirumee/saleor

**Comment by chetabahana** [comment]
@patrys
> Hey, we're planning to change current categories to taxonomies (tree structure, many-to-many) while introducing a strict one-to-many relation to a category. Would this solve your case?

Hey, I am currently being concern to product taxonomy,  I just realized that this case was already discussed. Would you update me how is going on on now with this plan?

I am interested to help in case no body working on it yet. I came to this case as I need to get the taxonomy in my language. I think many user will happy if it available in their language. 

So I would propose you this scenario:

- Would you please consider to use Google Product Categories shown in [Product Taxonomy - Google](https://www.google.com/basepages/producttype/taxonomy.en-US.txt). I think it is a right way to start from that point.
-  I would very happy if you include this as a project in your [Transifex - Mirumee](https://www.transifex.com/mirumee/public/). I just checked that there are no similar project exist there for either [product](https://www.transifex.com/explore/projects/?search=product), nor [category](https://www.transifex.com/explore/projects/?search=category) nor [taxonomy](https://www.transifex.com/explore/projects/?search=taxonomy).

Thanks in advance your your consideration.

**Comment by WillCGitHub** [comment]
Hello @patrys ,

Thanks for this awesome project. I was wondering has this product taxonomy feature implemented or in active development? 

> Hey, we're planning to change current categories to taxonomies (tree structure, many-to-many) while introducing a strict one-to-many relation to a category. Would this solve your case?
