### ISSUE TITLE
PayPal integration problems

### ISSUE THREAD

**Issue by MRTLeo** [mirumee/saleor#1312]
After creating the correct Paypal accounts and setting the correct keys I still get this error:
```
https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-3UC75321TM156221J
```
![screen shot 2017-11-14 at 12 35 05](https://user-images.githubusercontent.com/25492442/32791823-2e858228-c962-11e7-898c-7fc9c9a05d98.png)

but if i go check on my account i found that the payments are working fine
![screen shot 2017-11-14 at 12 34 52](https://user-images.githubusercontent.com/25492442/32791941-6eb690c6-c962-11e7-85df-6db223d6c9e4.png)
Is there a way to avoid this issue?

I alredy trierd to contact [paypal-techsupport](https://www.paypal-techsupport.com/) but their website have broken js and i cannot register on it

**Comment by Pacu2** [comment]
Sorry for the lack of response! I hope your problem is resolved by now, if now please reopen the issue.
