### ISSUE TITLE
Google Oauth Problem

### ISSUE THREAD

**Issue by bakeriogit** [mirumee/saleor#1316]
I am having issues with the social authentication for Google. (Facebook works for me)

I do get to the point where the user is asked for their google credentials, but after entering the password the user gets redirected to this URL
`https://*****.de/complete/google-oauth2/?state=TpX8ADEAFrAVniMqED3MrRQEBD75oual&code=4%2FLxHZZKoviTf4jpJP9QK6vOeD99ogZvBLQpWUv3es3Ko&authuser=2&session_state=de1967f6ab1c2328eea2705b922299de03a4813b..bf7e&prompt=consent#` 
and gets a server error (500).

Am I missing a redirect URL? I allowed following URLs:
`https://*****.de/login/google-oauth2/`
`https://*****.de/complete/google-oauth2/`
`https://*****.de/account/login/`

**Comment by MRTLeo** [comment]
I had the same problem check the create_user pipeline, you will find in extradata(kwargs) username and email but the pipeline can only handle the email so it stop working. I simply add an if that pops out username from my kwargs and it worked just fine

**Comment by elwoodxblues** [comment]
@bakeriogit Have you resolved the issue?

**Comment by bakeriogit** [comment]
Unfortunately no.
I tried to find the mentioned pipeline and pop the username but with no luck. 
I'll edit this post with what I tried exactly when I get home.

**Comment by Pacu2** [comment]
Fixed in #2171
