### ISSUE TITLE
Alert in cart always visible

### ISSUE THREAD

**Issue by yshterev** [mirumee/saleor#1324]
Hi,
There is no logic for showing/hiding cart alert in [`templates/cart/index.html`](https://github.com/mirumee/saleor/blob/master/templates/cart/index.html#L18)

**Comment by elwoodxblues** [comment]
From what I see this piece of markup is used on the JS side `cart.js`, but I don't see this message anyway when doing changes in my cart. Maybe there is something wrong. @dominik-zeglen could you check it when you have time?

**Comment by dominik-zeglen** [comment]
Thanks for pointing it out!
It seems that alerts are generated by JS, but they are not working atm. I'll fix it in a moment.
