### ISSUE TITLE
Exception not handled when removing address 

### ISSUE THREAD

**Issue by mad-anne** [mirumee/saleor#1338]
### What I'm trying to achieve

Remove address from user addresses, when it's already referenced by order.

### Steps to reproduce the problem

1. Place an order with new address.
2. Go to addresses book in user profile.
3. Try to remove the address, which was created while placing order.

### What I expected to happen

Dissociate address with user account (or display information, that address could not be removed).

### What happened instead/how it failed

Exception was thrown, cause address is referenced from ```order.billing_address``` and ```Order``` model has set ```on_delete=models.PROTECT```.

![screen shot 2017-11-21 at 11 51 50](https://user-images.githubusercontent.com/20802901/33069260-419574a2-ceb4-11e7-82a6-2615096d7b71.png)

**Comment by patrys** [comment]
This is a bug in checkout. Address instances should never be shared between users and orders. Otherwise the user would be able to change the address afterwards.

**Comment by mad-anne** [comment]
Bug was occuring due to my own changes to database. Addresses are copied correctly. Sorry for inconvenience.
