### ISSUE TITLE
Some SVG icons are not rendered

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1341]
Some SVG icons are not loading on my local and in the console I get 404. This happens for example on the category page for: `arrow_up.svg`, `arrow_down.svg` and `chevron_up.svg`:
![image](https://user-images.githubusercontent.com/5421321/33080714-0ad9374e-ced9-11e7-996c-b1983712d99a.png)

**Comment by mperesson** [comment]
I don't know if it's the same bug but probably (something linked to webpack build-assets)

It also happens on the dashboard.
saleor/static/dashboard/components/_breadcrumbs.scss:17
`        content: url('/static/dashboard/images/chevron_right.svg');`
This works in local but not in production env.
![screenshot from 2017-11-22 15-48-45](https://user-images.githubusercontent.com/2486416/33133338-b8e317ec-cf9c-11e7-8506-3ff44b4aa827.png)

**Comment by elwoodxblues** [comment]
It may be related, we'll check that. Thanks for reporting @mperesson.

**Comment by elwoodxblues** [comment]
Closed by #1355

**Comment by saqibkhan2523** [comment]
Is this issue resolved? Because in production it is still not displaying svg images

**Comment by NyanKiyoshi** [comment]
@saqibkhan2523 what is the developer console showing (console and network tab)? Can be a CORS issue or other.

I don't have issues on production here.

**Comment by saqibkhan2523** [comment]
There is no error it is just picking up `pass-invisible.svg` from assets in place of the other.svg images like `search.svg` I tried replacing these with png and images gets displayed, but the images are getting distorted that way.

**Comment by NyanKiyoshi** [comment]
There was no changes done to the javascript source code? Or is there no Rockerloader or whatever it's called from Cloudflare to bundle javascript?

And the SVG files are fully loaded? (if you look into the network tab and you look at the response data). What does the inspector show when you inspect a part with a SVG file not showing?

**Comment by saqibkhan2523** [comment]
I havent done any change in js. and when I inspect the svg image it is displaying the link to the image `https://mybucket.s3.amazonaws.com/images/google-logo.svg`

**Comment by NyanKiyoshi** [comment]
@saqibkhan2523 sent you a message about the PR over Gitter.

**Comment by kiran-capoor94** [comment]
Hi,
Still facing this issue. 

"pass-invisible.svg" not rendering as STATIC_URL doesn't get replaced by the S3 Url/Custom Domain Url.

As STATIC_URL environment variable is not changed for Webpack to find, we will need to change it to the new URL.

Possible fix would be:
`S3_URL = 'https://%s.s3.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME`
`STATIC_URL = S3_URL + 'assets/'`

**Comment by saqibkhan2523** [comment]
Your url is not right. 
it should be like this `S3_URL = https://**mybucke**t.s3.amazonaws.com`
