### ISSUE TITLE
Change default store front layout

### ISSUE THREAD

**Issue by alcfernandes** [mirumee/saleor#1342]
Hi. I'm sorry, this is not exactly an issue, but a request for help. How difficult is it to change the default store front layout? I need to apply a very specific template and I find it particularly difficult. Any tips on how to do the layout replacement?
Thanks

**Comment by elwoodxblues** [comment]
Hi @alcfernandes, the storefront's layout is based entirely on Bootstrap 4.0.0-beta with some custom styles added by us. There are few files that you would need to adjust in the first place:
- "templates/base.html" - that's the base template for all pages in the storefront; I would personally start from here, as it allows you to define e.g. your custom page header, navigation or footer.
- "static/scss/storefront.scss" - in this file we include all of our custom styles; they're organized into components and layouts, by their names you should be able to find the piece of UI that you want to adjust.
- "static/scss/variables.scss" - here we define some of the current theme's colors; I would keep these variables and update them with your colors, fonts etc.

I hope this helps you to get started. If you have any further questions feel free to ask.

**Comment by alcfernandes** [comment]
Hi @elwoodxblues, thank you so much for your answer. It helped a lot.
