### ISSUE TITLE
PDF rendering static content improperly in dashboard

### ISSUE THREAD

**Issue by Satloff** [mirumee/saleor#1343]
### What I'm trying to achieve
The static content and style sheets that are used to produce the packing slip and invoice seem to rendering improperly. I am referring to the rendering of the pdf template used within the '_saleor/dashboard/order/utils_' file. 

### Steps to reproduce the problem on the front end:
1. click orders
2. select an order
3. click packing slips

### What I expected to happen
A nicely formated pdf slip like:
[pack_good.pdf](https://github.com/mirumee/saleor/files/1492575/pack_good.pdf)

### What happened instead/how it failed
Instead, the stylesheet seems to fail:
[packing_bad.pdf](https://github.com/mirumee/saleor/files/1492576/packing_bad.pdf)

**Comment by koradon** [comment]
Hi @Satloff 
Did you build your assets? We have recently changed the way stylesheet are included to invoice and packing slips.

**Comment by elwoodxblues** [comment]
Also make sure that you have correct domain set in the current site (`django.contrib.sites`) - we use it to build assets path in the PDF templates.

**Comment by Satloff** [comment]
@elwoodxblues was this change made on the demo.getsaleor.com version?

**Comment by elwoodxblues** [comment]
We have just released a new version of demo.getsaleor.com which includes this change.
