### ISSUE TITLE
Adjust schema.org markup

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#1349]
**Acceptance criteria**
1. Product page
    - [x] Remove ProductSchema.js and related data, generate schema only through json-ld on the backend
    - ~~Implement AggregatedOffer schema (Take a look at the comment below)~~
    - [x] Generate schema markup for all variants

2. Category page
    - ~~Add schema markup for products, same as on the Homepage~~
3. General
    -  [ ] Implement [BreadcrumbList](https://developers.google.com/search/docs/data-types/breadcrumbs) schema markup
    - [ ] Fix [sitelink SearchBox](https://developers.google.com/search/docs/data-types/sitelinks-searchbox) schema markup(there's code responsible for it, but it don't appear on site)
    - [ ] Implement [Logo](https://developers.google.com/search/docs/data-types/logo) schema markup
    - [ ] Implement  [Social Profile](https://developers.google.com/search/docs/data-types/social-profile-links) schema markup
    - [ ] Schema markup should be created as `JSON-LD` whenever possible and reasonable
    - [ ] If reasonable, schema markup should be generated on the backend and passed to the frontend

Test with https://search.google.com/structured-data/testing-tool/u/0/ 

More information:
    http://schema.org/ - docs
    https://developers.google.com/search/docs/guides/intro-structured-data - Introduction to Structured Data by Google
    https://support.google.com/webmasters/answer/7407437?hl=en&ref_topic=3309300  - Google’s guidelines on enriching search results

**Comment by Pacu2** [comment]
I just discovered the bug(?) in the structured data testing tool. 
It may display no errors or warnings, but if 'preview' button is not visible, it means that there's some logic error in the scheme.
Example scheme I was able to create for the product page:
```
<script type="application/ld+json">
{
   "@context": "http://schema.org/",
  "@type": "Product",
        "name": "Allen-Rose",
        "description": "Really cool snippet will show if is in stock or not",
        "offers": {
          "@type": "AggregateOffer",
          "lowPrice": "0.54",
          "highPrice": "13.99",
          "priceCurrency": "USD",
          "availability": "http://schema.org/InStock",
          "sku": "8057",
          "category": "Sweats",
          "image": "/media/products/green_5QAEiDC.jpg",
          "offerCount": 2,
          "offers": [
            {
                "@type": "Offer",
                "availability": "http://schema.org/InStock",
                "price": "0.54",
                "priceCurrency": "GBP",
                "itemCondition": "http://schema.org/NewCondition",
                "image": "/media/products/green_5QAEiDC.jpg",
                "name": "Yellow Allen-Rose",
                "sku": "44692"
            },
            {
                "@type": "Offer",
                "availability": "http://schema.org/InStock",
                "price": "13.99",
                "priceCurrency": "GBP",
                "itemCondition": "http://schema.org/NewCondition",
                "image": "/media/products/green_5QAEiDC.jpg",
                "name": "Green Allen-Rose",
                "sku": "44690"
            }
          ]
        }
    }
}
</script>
```
They may be missing some fields, need to double check

**Comment by patrys** [comment]
Probably unrelated to Google as their bot seems to handle this well but in the past I've encountered tools that can't handle URLs (like images) without protocol and domain.

**Comment by Pacu2** [comment]
Example schema markup for Category page 
```
{
    "@context": "http://schema.org",
    "@type": "ItemList",
    "name": "T-Shirt",
    "url": "/category/t-shirt/",
    "description": "Deserunt quibusdam ipsa illo ex nam ea illo qui. Itaque maiores doloribus accusamus ratione. Aperiam ipsa veritatis quas nisi.",
    "itemListOrder": "Unordered",
    "numberOfItems": 2,
    "itemListElement": [
        {
            "@type": "ListItem",
            "position": 1,
            "url": "/products/lopez-smith-25/?color=yellow&size=XXL",
            "name": "Yellow Lopez-Smith",
            "image": {
                "@context": "http://schema.org",
                "@type": "ImageObject",
                "contentUrl": "/media/__sized__/products/yellow_n2QjKzn-thumbnail-640x640-70.jpg",
                "description": "Lopez-Smith",
                "width": 640,
                "height": 640
            }
        },
        {
            "@type": "ListItem",
            "position": 2,
            "url": "/products/lopez-smith-25/?color=blue&size=37",
            "name": "Blue Lopez-Smith",
            "image": {
                "@context": "http://schema.org",
                "@type": "ImageObject",
                "contentUrl": "/media/__sized__/products/blue_FZ3yJjG-thumbnail-640x640-70.jpg",
                "description": "Lopez-Smith",
                "width": 640,
                "height": 640
            }
        }
    ]
}
```

**Comment by patrys** [comment]
One more thing: the `WebPage` description is only supposed to appear on the home page.

**Comment by patrys** [comment]
And another: I don't think Google expects to see `Product` descriptions to appear outside of the specific product's page.

**Comment by patrys** [comment]
I've reviewed the schema for the `Product` and we should not be using an `AggregateOffer` as it's meant for cases with multiple sellers. Instead we can make `offers` a list:

```json
{
    "@context": "http://schema.org/",
    "@type": "Product",
        "name": "Allen-Rose",
        "description": "Really cool snippet will show if is in stock or not",
        "offers": [
            {
                "@type": "Offer",
                "availability": "http://schema.org/InStock",
                "price": "0.54",
                "priceCurrency": "GBP",
                "itemCondition": "http://schema.org/NewCondition",
                "image": "/media/products/green_5QAEiDC.jpg",
                "sku": "44692"
            },
            {
                "@type": "Offer",
                "availability": "http://schema.org/InStock",
                "price": "13.99",
                "priceCurrency": "GBP",
                "itemCondition": "http://schema.org/NewCondition",
                "image": "/media/products/green_5QAEiDC.jpg",
                "sku": "44690"
            }
        ]
    }
}
```

**Comment by patrys** [comment]
For Logo to work we need a PNG version of the logo that is suitable for display against mostly light backgrounds (Google).
