### ISSUE TITLE
Create configurable delivery methods

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#135]
Like on other e-commerce platforms, we need to store delivery methods in database as normal django model. We should be able to configure:
* delivery pricing (depends on order  weight or not)
* shipping provider (DHL, GLS, etc..)
* Simple panel for shop staff where they'll be able to change delivery statuses, send tracking numbers etc.

What do you think?

**Comment by mociepka** [comment]
Fixed in #449
