### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#1351]
Right now in demo store we display generic 404 page
https://demo.getsaleor.com/i-do-not-exist/

Could implement something more interesting, with a nice design.

What should be included:
- [ ] Drawing
- [ ] Link to the homepage
- [ ] Search bar (?)
- [ ] ...

**Comment by subgrafik** [comment]
helou What about a PIrate like this... 
![saleor_404_01](https://user-images.githubusercontent.com/7837760/33432421-1e0b5ed6-d5d8-11e7-82a2-29296860b14b.png)

svg in zip file 
[saleor_404_01.svg.zip](https://github.com/mirumee/saleor/files/1517872/saleor_404_01.svg.zip)

**Comment by koradon** [comment]
This picture with desert from @Pacu2 presentation stole my :heart: .

**Comment by milosjaros** [comment]
What about the copy for those graphics in random:

Nothing here, comrade!  (@Pacu2 used this one)
It has to be somewhere else!
Nothing in sight comrade!

**Comment by patrys** [comment]
"Comrade" is more "Russian revolution" than "pirates and sailors".

**Comment by milosjaros** [comment]
/SKARB/
I can’t help but feel I’ve been ripped off. 
I’m sure you're feeling something similar, bucko.

/LUNETA/
Is it over? ...Hello? ...Did we win?

**Comment by subgrafik** [comment]
Design style. 
![404-saleor](https://user-images.githubusercontent.com/7837760/33881962-cf94628a-df36-11e7-8759-60175b0bafdb.jpg)

**Comment by elwoodxblues** [comment]
👍  This is fine for the demo page. @subgrafik We could also have some generic 404 page without any branding, that we'll provide by default for development.

**Comment by subgrafik** [comment]
SVG - set of 3 404 vector graphics 
slightly modified 

![saleors 404 a -03](https://user-images.githubusercontent.com/7837760/33993752-26e13c64-e0d8-11e7-9dab-345181ddf791.png)
![saleors 404 a -02](https://user-images.githubusercontent.com/7837760/33993753-26fd9698-e0d8-11e7-9110-c0109d176c3c.png)
![saleors 404 a -01](https://user-images.githubusercontent.com/7837760/33993754-27195c02-e0d8-11e7-9479-5ae9d2692d8e.png)


+ SVG PACK 
[Archiwum.zip](https://github.com/mirumee/saleor/files/1559265/Archiwum.zip)
