### ISSUE TITLE
Consider replacing favicons-webpack-plugin

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#1356]
This Webpack plugin seems to be unmaintained, has heavy dependencies¹ and takes a long time to regenerate the images every time `webpack` is executed.

Maybe we should just add the necessary icons to the repository instead? There are online tools like https://realfavicongenerator.net/ that will provide users with a set of replacement files when customizing the store.

¹ `favicons-webpack-plugin` > `favicons` > `svg2png` > `phantomjs`

**Comment by dominik-zeglen** [comment]
Have you tested it? 
I may be doing something wrong, but average time for `npm run build-assets` to execute with and without favicons-webpack-plugin is nearly the same, , and `npm run build-assets` gains about 1 second if we drop favicons building.

**Comment by patrys** [comment]
I'm mostly interested in the requirements this pulls into the project (PhantomJS et al).

I'm not sure building graphical assets has its place in the deployment pipeline. I get that it's convenient. It would also be convenient to have webpack slice PSD files. I'm not sure where the border lies but to me it seems that building favicons automatically is not a great idea (especially given that there's no way to customize them for legibility in any given resolution).
