### ISSUE TITLE
Heroku Deploy Button

### ISSUE THREAD

**Issue by MAkcanca** [mirumee/saleor#1364]
Hi!
I was testing out the Heroku deploy button on Readme page of Saleor.

Everything was going fine until it produced this error in fourth step "Run scripts & scale dynos".
`CommandError: Unknown command: 'search_index'`

I believe that it's caused by updated dependencies, any ideas?

**Comment by Pacu2** [comment]
Hi @MAkcanca, 
Good catch! We overlooked one variable when rewriting our ES backend. 
It will be solved together with #1362 in #1363, hopefully today.
