### ISSUE TITLE
Dashboard search results visual issues

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1367]
- empty search results page is not consistent with other "zero" pages in the dashboard (screen below)
- when hovering over one results line, all lines get highlighted

![image](https://user-images.githubusercontent.com/5421321/33263411-1781f6e4-d36a-11e7-9c4d-0c15e40e4c1a.png)

**Comment by salwator** [comment]
@elwoodxblues We should do dashboard search result view redesign as previously discussed.
Results are not displayed in useful manner, is it right issue for this discussion?

**Comment by elwoodxblues** [comment]
We should open a separate issue for designing the new search results page.
