### ISSUE TITLE
PaymentForm failing to render credit_card_expiry_widget

### ISSUE THREAD

**Issue by Satloff** [mirumee/saleor#1374]
### What I'm trying to achieve
I'm trying to use the BraintreeProvider form from django payments to perform a checkout. 

### Steps to reproduce the problem

1.  add the braintree provider:

    'braintree': ('payments.braintree.BraintreeProvider', {
        'merchant_id': '112233445566',
        'public_key': '1234567890abcdef',
        'private_key': 'abcdef123456',
        'sandbox': True}),
2. try to perform a checkout

### What I expected to happen

Have the form load with credit_card_expiry_widget rendered properly. 

### What happened instead/how it failed

The form renders with "month" and "year" missing.

<img width="376" alt="screen shot 2017-11-28 at 12 02 03 am" src="https://user-images.githubusercontent.com/14352539/33303186-9b5d7f5a-d3cf-11e7-824a-6ad08e36ce6a.png">

**Comment by elwoodxblues** [comment]
It's the same problem as in #1056.

**Comment by elwoodxblues** [comment]
I'll opened a PR to fix this: #1377 .
