### ISSUE TITLE
Add dropdown for selecting phone number country code in checkout

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1375]
Since we have validation of phone numbers in checkout that requires specifying numbers in international format, it would be useful if we also added a dropdown for selecting the country code  prefixes.

Definition of done:
- [ ] Add a dropdown with phone number country prefixes in the checkout address forms
- [ ] Initialize the field with a country code based on user's IP (`CountryMiddleware`)
- [ ] Move the newly added field and phone number field to bottom of the address form (below the zip code and above the country field).

**Comment by patrys** [comment]
Shouldn't we initialize it with whatever is selected as the address country?

**Comment by elwoodxblues** [comment]
Address country is initialized from user's IP, so will be the phone number prefix.
