### ISSUE TITLE
Hide "Clear filters" in when no filter applied

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1376]
In the storefront the "Clear filters" link is always visible, while it should be hidden when no filters are applied.

**Comment by koradon** [comment]
This issue can be easily resolved with solution from #1299 
Should we wait for merge of this PR or can we add this change in that PR?

**Comment by elwoodxblues** [comment]
I'd rather add it separately, PR #1299 is big enough already .
