### ISSUE TITLE
Design new dashboard search result page

### ISSUE THREAD

**Issue by salwator** [mirumee/saleor#1381]
Current search produces results without clear division of result type and it is unclear on first sight if item is product, order or user.

We might want to make results divided into named easier to navigate separate sections.

Dashboard search should enable quick access to top result so it might be a good idea to limit results to only few items and provide detailed info for each item, ex. order customer info, user first and last name, product description preview.

### What I'm trying to achieve

Make dashboard result page easier to navigate

### Steps to reproduce the problem

1. Go to dashboard search
2. Type search that results in long, multi-type result list

### What I expected to happen

Results formatted in easy to comprehend, more readable way

### What happened instead/how it failed

<img width="1659" alt="result" src="https://user-images.githubusercontent.com/3965807/33369341-8065bfb6-d4f4-11e7-8b59-f62e3f1787db.png">

**Comment by subgrafik** [comment]
What about Flickr solution - I found it very usable I think we can think about sth like this 
![frame 4](https://user-images.githubusercontent.com/7837760/33429466-3fffb68c-d5cd-11e7-9000-d94cb6101c52.png)

We took 3 best results and give user a chance to switch to products/ orders/users category
The other option is to made it similar to filters on the column in the right ....

**Comment by elwoodxblues** [comment]
Looks okay in my opinion, maybe we should put each section in separate cards to make it more visual appealing (cards have elevation and shadows around their borders).
