### ISSUE TITLE
Django Admin on Saleor based app

### ISSUE THREAD

**Issue by alcfernandes** [mirumee/saleor#1386]
Hi.

I would like to reimplement django admin in my Saleor based application. Is there any problem this might cause? What do I need to do to be able to use Django Admin on Saleor?

Thanks for any help.

**Comment by Pacu2** [comment]
Hi @alcfernandes,
I just wonder, what features are you missing from Django admin, that aren't present in Saleor's dashboard?

**Comment by alcfernandes** [comment]
Hi @Pacu2,

There are several simple features that I can add to my application using only Django Admin. Without having to spend hours of development and customer money.

My intention here is not to discuss whether or not to use Django Admin, but to know if there is any contraindication to reinstalling it.

I just want to know the reasons that led to the decision to remove Django Admin from Saleor.

Thanks a lot

**Comment by patrys** [comment]
@alcfernandes You should be able to add it without problems. We don't use Django Admin as we view it primarily as a scaffolding tool for developers. It's not enabled as we don't intend to expose it to any of our customers. We believe a custom-tailored dashboard is the only way to deliver great user experience.

**Comment by alcfernandes** [comment]
Thanks @patrys!

**Comment by zchking** [comment]
I want to use export order, but now I don't know how to develop.
