### ISSUE TITLE
Improvements in order details dashboard 

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1390]
There are few small visual issues to fix on the order details dashboard page.
- [x] Rename label "cancel this shipment" to "cancel shipment" (both in the order details page as well as in the modal)
- [x] Change label "abort" to "back" in the "cancel shipment" modal
- [x] Use regular font in shipping row in delivery groups - now they're bold, which looks like total price of the group. Also, the price of a shipping could be removed from those rows, as we already show total shipping price under groups and for now there will be only one shipping price for the whole order.
- [x] Maybe we could do something about the modals height - it looks that they are taking too much space even when there is only one field (screen below).

![image](https://user-images.githubusercontent.com/5421321/33438215-6ffe0b96-d5ea-11e7-892e-efe40939d84c.png)

**Comment by patrys** [comment]
Related: #1256
