### ISSUE TITLE
Heroku deploy button

### ISSUE THREAD

**Issue by MAkcanca** [mirumee/saleor#1392]
There's a problem with heroku deploy button, again. 

`Couldn't find either the add-on service or the add-on plan of "bonsai:sandbox-10".
`

Is this just me?

**Comment by Pacu2** [comment]
Bonsai addon plan name changed, proper command is:

> [heroku addons:create bonsai:sandbox-6](https://elements.heroku.com/addons/bonsai)
Strange, as we just renamed it to `bonsai:sandbox-10` from `bonsai:sandbox` in #1265 

You can change it in `app.json` and deploy from Heroku CLI. I'll send a PR for that tomorrow
Thing to consider: change bonsai to something more reliable
