### ISSUE TITLE
Mobile improvements

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#1401]
I've got a round with mobile version of Saleor, here's could of things I found:

 1. Scroll issue
    I think I should not be able to scroll the page with navbar open.
     Current behavior:
        (Please use mobile as dev chrome tools is not showing the problem so precisely)
        - Open navbar
        - Scroll to the bottom of it
        - When you reach bottom of the navbar, and keep scrolling, page starts to scroll
        - Try to close navbar with one-click on the right side (on the page)
        - Navbar does not close
        - If you hit action-item, it will be followed
     Expected behavior:
        - Scrolling navbar does not scroll the page
        - Navbar can be closed with one click anywhere on the site, except for navbar
        - Can't follow any on-site links with navbar open (navbar should be closed when clicked outside of it)

 1. Shop site is not filling the Viewport
     Steps to reproduce:
        - On mobile (iphone 5) go to main page
        - zoom out
     Actual result:
        - Column of 'blank space' displays on the right side of the page
        - This problem is not present on the dashboard
        - Can be seen from chrome dev tools (scroll to the left)
        - As I can see website scales badly below 360px
 1. Saleor logo is displaced (iphone 5) 
    - due to that, its covering all the breadcrumbs
 1. Between page body and footer there's ton of whitespace
![viewport_problem](https://user-images.githubusercontent.com/21290461/33514604-c67b914c-d756-11e7-9ac9-46899afc3349.PNG)

 1. `Product` and `Quantity` are displaced on breakpoints smaller than tablet
 1. Checkout button could be stretched side-to-side on mobile, also `Product has been removed from cart` message is present all the time, even on freshly entered cart, can't close it
![mobile_cart](https://user-images.githubusercontent.com/21290461/33514647-c07f16d2-d757-11e7-97e8-7ca9d72643bd.png)

 1. Topbar is transparent on the iPhone
     (when launching site from the home-screen)
    This option was meant to be used on fullscreen websites. Either navbar should not be `fixed` or topbar should be solid
![img_4107](https://user-images.githubusercontent.com/21290461/33514655-0ba14c98-d758-11e7-8ae1-38bd3e208517.PNG)
 1. When adding app to the homescreen, APP name is incorrect (iPhone)
![img_4106](https://user-images.githubusercontent.com/21290461/33514676-62a46048-d758-11e7-8c6e-88d8662c049c.PNG)
 1. Navbar could be smaller,
     Dashboard's one is designed well better, on storefront it's covering too much of the page
 1. Product name is literally taking 1/3rd of the page
![img_4112](https://user-images.githubusercontent.com/21290461/33514684-b3b705b2-d758-11e7-94c0-d023b64d1573.PNG)
1. Filters on category are not visible between ~576-767 pixels width
![filters](https://user-images.githubusercontent.com/21290461/33516383-31484d1a-d772-11e7-9eee-44f9b434e38d.png)
1. Variant picker images are displaying over the navbar (and over side-menu as well)
![variant_picker](https://user-images.githubusercontent.com/21290461/33516457-64b85c34-d773-11e7-8a79-078d9be17d75.png)
1. On mobile category page, clicking on `Filters` expands filters under the subcategories. It does not look bad unless you have few added.
![filters](https://user-images.githubusercontent.com/21290461/33525483-aeb03e98-d830-11e7-9402-b4ceeb22dd4d.png)

**Comment by elwoodxblues** [comment]
Mentioned bugs were fixed in PR #1409. Points that are still open for discussion are 1, 9, 13.

**Comment by patrys** [comment]
13 shows two problems: one is that filters are incorrectly places, the other is that with multiple cubcategories the category list alon can easily take an entire page.

Maybe we should list subcategories inline on mobiles? Like so:

## Accessories

[Foo](#), [Bar](#), [Baz](#), [Lorem ipsum](#)

**Comment by patrys** [comment]
Another problem: "sort by:name" looks like it could use a space after the colon.
