### ISSUE TITLE
Not running as Docker image on Elasticbeanstalk

### ISSUE THREAD

**Issue by guptaabhinav1512** [mirumee/saleor#1402]
### What I'm trying to achieve
I tried to deploy Saleor as a docker container on AWS Elasticbeanstalk.

### What happened instead/how it failed
I am getting error 'Error reading ./webpack-bundle.json. Are you sure webpack has generated the file and the path is correct?'. The issue is related to frontend assets but why is the Docker container not building them? How do I build these as a part of deployment?

**Comment by guptaabhinav1512** [comment]
I tried adding npm run build-assets / yarn run build-assets but neither of them is working and preventing from the image to build. How do I build the frontend assets?

**Comment by patrys** [comment]
Hey, Docker images are supposed to contain the bare minimum required to launch an application therefore they don't have Node.js installed. Any operations requiring Node (including building the assets) need to be performed prior to building the container which is only responsible for packaging (and later running) the Python part of the application.

**Comment by guptaabhinav1512** [comment]
Hi,

Thanks for responding. So I should run npm install and npm run build-assets
first and then deploy  the code to AWS Elastic beanstalk?

**Comment by patrys** [comment]
Yes, you need to run all `npm` commands prior to `docker build`. Then Docker will package the files for you (including the `webpack-bundle.json` file generated by Webpack).

**Comment by Landver** [comment]
Hello.

> "Any operations requiring Node (including building the assets) need to be performed prior to building the container which is only responsible for packaging (and later running) the Python part of the application."

Could you please tell me, did you mention that anywhere in documentation?

**Comment by patrys** [comment]
@Landver Yes, there could be a separate docker container running `npm watch` when running with `docker-compose`. We'll gladly accept a pull request.

I'm going to close this ticket as the discussion has since moved to more general topics.

**Comment by Sshuichi** [comment]
The page you referred to is not found @patrys
