### ISSUE TITLE
Hi guys, given so many commits,  which one is a release version on master 

### ISSUE THREAD

**Issue by kevinchow924** [mirumee/saleor#1404]

**Comment by amorphic** [comment]
@kevinchow924 I think [this](https://github.com/mirumee/saleor/releases/tag/v2017.11) is what you're after?

**Comment by kevinchow924** [comment]
Thanks you very much.
Saleor is a very good platform.
I am considering to build my own project based on saleor.  Do you have any idea for me ?

**Comment by amorphic** [comment]
@kevinchow924 if you're looking to build a web shop then it is indeed an excellent platform. It got us up and running with [shop.enstaved.com](https://shop.enstaved.com) very quickly with the flexibility that we needed to customise things as required.

I think this issue can probably be closed now?
