### ISSUE TITLE
Migration 0040_auto_20171205_0428 (Gin index) not working with long descriptions

### ISSUE THREAD

**Issue by mperesson** [mirumee/saleor#1420]
I tried to update to the last release (11/2017) and got this error while applying migrations:

`psycopg2.OperationalError: index row size 2736 exceeds maximum 2712 for index "product_pro_name_5bb6fa_gin"`

TextField and Index are not really compatible.

**Comment by salwator** [comment]
@mperesson in latest release we introduced PostgreSQL full text search functionality for both storefront and dashboard. For faster searching we use Gin index on product name and description.

Depending on your project goals, there are a few things you might do to fix the problem. If you're not using search, or search is already provided by elasticsearch, you might want to remove the index from a product model entirely. Same solution might apply if your product count is in under few hundred.

In case you want to make use of the PostgreSQL search, you might want to add a [SearchVectorField](https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/search/#searchvectorfield) to your model and keep it up to date on your own. This might be the best solution for a larger applications.

**Comment by patrys** [comment]
@salwator Why does this affect some deployments and not others? That does not seem right.

**Comment by mperesson** [comment]
Hey, thanks for the reply!

I already removed the index cause I use elasticsearch (the new implementation is way better btw).

But I think I will not be the only one with this problem, and editing saleor model/migration might not be the best way to do it.

**Comment by salwator** [comment]
@mperesson  thank you for positive feedback regarding ES changes! As of GIN index size problem, you are absolutely right and this issue must be addressed anyway in a solution that works everywhere.
