### ISSUE TITLE
Order contents are public to everyone

### ISSUE THREAD

**Issue by EduardoZepeda** [mirumee/saleor#1426]
### Order's views are unprotected

I don't know if this should be considered a security issue but all the order's content are public and accesible to anyone who has the link, even if they're not logged in. Anyone with access to your browser history or the corresponding link can see what you (or others) have bought (internet café, shared computer, etc).

#### For example:
[Admin's order](https://demo.getsaleor.com/order/7740e681-47b2-4d20-a11f-bfe0dc13a9d6/)
[User's order](https://demo.getsaleor.com/order/faa40c39-2eee-424e-965c-6e77b2722ec6/)

**Comment by patrys** [comment]
That's expected behavior. We're hiding sensitive information like names and addresses.

If others have access to your browser history they could also find out which items you've visited right before visiting your cart or the checkout page so I don't believe it exposes any critical information.

**Comment by EduardoZepeda** [comment]
Thank you so much for your fast response, you're right maybe it isn't as dangerous as I thought. I close this.
