### ISSUE TITLE
URL internationalization

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#1427]
I need to serve each language of the site under separate url, with adequate prefix
eg. 
getsaleor.com/en/products
getsaleor.com/de/products

Needed:
- [x] `alternate` link tag pointing to each language version in templates
- [x] Implemented [URL internationalization](https://docs.djangoproject.com/en/dev/topics/i18n/translation/#url-internationalization)
- [x] Ability to switch language on the Frontend
- [x] [Update sitemap generation to include language tags](https://support.google.com/webmasters/answer/2620865?hl=en)
- [ ] Extend `Opengraph` markup to include locale

For products:
- [ ] Product translation interface #819 
- [ ] Adjusting ES data scheme to include translated properties

Am I missing something? Can you spot any additional, potential problems?

**Comment by patrys** [comment]
I'd prefer if we could do what IKEA does for example and use `/territory/language/` (`/pl/pl/`, `/jp/ja/`, `/at/de/`, `/us/en/` and so on).

**Comment by patrys** [comment]
Open question: what to show on `/`? Some sites issue a soft (non-permanent) redirect to the negotiated language. IKEA offers a link to the detected language version and a link to the full list of supported locales.

**Comment by koradon** [comment]
Soft redirect with easy to find link for all supported languages is in my opinion more user friendly and seamless.

**Comment by Pacu2** [comment]
@patrys what's your view on implementation`territories` as a part of our urls?
AFAIK django `i18n_patterns` supports `languages` out of the box, however couldn't find any package that would help us with terrorities, other than custom-tailored solution.

**Comment by patrys** [comment]
The default implementation (`LocalePrefixPattern`) uses locale names as prefixes so the territory is part of the locale. For example the United States (territory) English (language) is denoted as `en-us`. The default territory is usually skipped so `pl` and `pl-pl` resolve to the same locale.
