### ISSUE TITLE
Missing pagination on the dashboard's homepage

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1434]
On the homepage in the dashboard, there are three lists and none of them is paginated. Since they are three different querysets, I don't see a reasonable way to paginate them at once. Therefore I'd propose to limit the displayed results to a fixed limit e.g. 10 recent orders, 10 recent preauthorized payments etc.

**Comment by patrys** [comment]
I agree, it would be more useful to see "11 products are out of stock, most recent three are X, Y, Z, click here to see all" than a comprehensive list of all possible actionable items.

**Comment by elwoodxblues** [comment]
Currently, there is no way to have "Show more" links, as some of the sections (e.g. "Preauthorized payments") have no corresponding list views. For now, I would propose to limit the number of items to 10 in each section and show a message "Showing last 10 results" when hovering on the section title.

**Comment by patrys** [comment]
Maybe we should consider dropping some of the sections then? Are we sure there is a use case behind all of them? Maybe there are better metrics we could offer instead?

**Comment by elwoodxblues** [comment]
Yes, I agree that we should discuss that. But before we do this I would really like to fix the problem with three long lists that are not paginated and looks terribly bad in the demo store for instance.
