### ISSUE TITLE
Zero pages design

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1435]
After the recent changes, we have a few inconsistent "zero" page layouts (list views without any results).

Orders:
![image](https://user-images.githubusercontent.com/5421321/33660681-ff11114a-da84-11e7-81b7-952c8b3d7d98.png)

Sales:
![image](https://user-images.githubusercontent.com/5421321/33660691-09bd78b8-da85-11e7-89be-3431c690a41c.png)

Vouchers
![image](https://user-images.githubusercontent.com/5421321/33660708-14ff03c2-da85-11e7-975d-a3b714c14f29.png)

Since we want all the main list views to look the same, I would recommend introducing a "base list" template. It could take care of:
- displaying the list of items
- displaying the filters when there are results on the list (in case of an initially empty list, filters should be hidden in my opinion)
- displaying the pagination
- properly displaying the "zero" page layout

As for the design for the "zero" page, currently, they should look like at in the "Orders" case above, but we're working on the new designs.

**Comment by subgrafik** [comment]
We would like to propose for ZIro pages a fancy illustartion with some "description" about  the section it is about like here for example 
![frame 3 1](https://user-images.githubusercontent.com/7837760/33710219-29ab6304-db40-11e7-9f4c-034c7c4a8038.png)

**Comment by patrys** [comment]
Branded images are nice for the demo store but core Saleor should remain brand-free as it's a white-label platform. This means we still need a solution for Saleor itself.

**Comment by elwoodxblues** [comment]
I agree, here we need something more generic. We could simply keep the white box in the middle and remove the pirate image. One problem is with the FAB button alignment. Maybe we could make the white box wider, equally to the content width in other views.

**Comment by elwoodxblues** [comment]
In order to distinguish the case when the database is empty or the view shows no results because of enabled filtering, we need a flag to be passed in the context from the view. @mad-anne Will you have some time to help with this?

**Comment by mad-anne** [comment]
@elwoodxblues sure, I'll take care of it.

**Comment by mad-anne** [comment]
@elwoodxblues as I see now, there is no need to create additional flags. We can check if there are any records in database simply typing ```{% if filter.queryset.count %}``` in our templates.

**Comment by elwoodxblues** [comment]
Does it return the original count of the queryset always, even if the filtering is enabled?

**Comment by mad-anne** [comment]
Yes. `FilterSet` shares original queryset in `queryset` attribute and filtered in `qs`.

**Comment by elwoodxblues** [comment]
We could use that, but it will work only for list views with filters. A more generic solution would be to have the flag. Then the view's author will how to explicitly implement the case when a "zero page" should be shown. I also think that this will improve the readability of templates.
