### ISSUE TITLE
Images generation performance issue

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#1436]
Right now we are using the `django-versatileimagefield` (VF) package for images thumbnails generation. Its default behavior is to generate images on demand. VF uses cache to determine which images need to be generated.

That behavior is dangerous on typical ecommerce products list. If page for instance has 20 images and 4 different sizes per resolution we end up with 80 request to the cache and in worst scenario 80 images start to be generated on machine which is handling responses. That basically kill the site.

In all previous projects we disabled auto generation. Because of that we had to write custom celery tasks (which generate images in the background) and custom template tag (@artursmet can provide more details). It will be nice to have this done by default.

**Comment by patrys** [comment]
Important note: VF only relies on cache when generating images on-demand. This is not the setup we want to encourage for production use.
