### ISSUE TITLE
Improve user visible strings and fix localization of `_filters.html`

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#1438]
Currently the template looks like this:

```django
<span>{% trans 'Total records found' context 'Dashboard filter' %}: {{ count }}</span>
```

The message is generic and uses the technical term "records" to avoid having to know what type of items is filtered. I think we can do better and provide use case-specific messages that don't look awkward and are easier to translate.

Another problem is that the translation does not include the counter so it's impossible to properly translate it for RTL languages.

Yet another problem is that the translation does not depend on the counter so it's impossible to provide correct grammatical alternatives for various values of the counter.

A good solution would look more like this:

```django
<span>{% blocktrans count counter=count context 'Number of matching product records in the dashboard list of product' %}Found {{ count }} matching products{% endblocktrans %}</span>
```

**Comment by elwoodxblues** [comment]
There is a generic template for rendering the whole block with filters. But I guess we should be able to do it on the Python side and define appropriate messages that are count- and translation-aware for each filter, that we pass to that template.
