### ISSUE TITLE
Add support for webp images by default

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#1439]
[WebP](https://pl.wikipedia.org/wiki/WebP) is an images format which right now only chrome supports but it is a big improvement for android mobile devices (in some cases even 30% of site trafic).

Unfortunately django-versatileimagefield (VF) is not capable of creating webp and I haven't found easy way to generate WebP with it. In this problem and the https://github.com/mirumee/saleor/issues/1436 in mind I think easier will be create our own support for images handling.

We nee:
* celery task for images creation (with PIL code which is like 3 lines),
* debug view for images generation when developing,
* template tag for the picture tag generation like:
```
<picture>
  <source srcset="img/image.webp" type="image/webp">
  <source srcset="img/image.jpg" type="image/jpeg"> 
  <img src="img/image.jpg" alt="Alt Text!">
</picture>
```

We don't want to use images autogeneration so 70% of VF code is not for us. What do you think @artursmet , @bogdal , @elwoodxblues , @patrys ?

**Comment by patrys** [comment]
I'm 👍 on WebP support but 👎 on maintaining a NIH solution in-house. If possible, I'd first attempt to add WebP support to versatileimagefield (it could work in a similar way to how crop flag works).

**Comment by mociepka** [comment]
Addin two files generation with proper names in VF is like changing all architecture. We will create hack code which we need to maintain. So I propose just write our one but clear.

**Comment by patrys** [comment]
We don't need to create two files for a single filter pipeline. I propose adding a separate "webp" flag so you would configure two thumbnail types in settings, one for, say, JPEG at 100x100px and one for WebP at 100x100px.

**Comment by mociepka** [comment]
How you want to introduce webP generation in that scenario @patrys ?

**Comment by patrys** [comment]
```python
VERSATILEIMAGEFIELD_RENDITION_KEY_SETS = {
    'product_list': [
        ('thumbnail', 'crop__100x100'),
        ('thumbnail_webp', 'crop__webp__100x100')
    ],
    ...
}
```

Then:

```django
<picture>
  <source srcset="{{ product.image.crop.webp.100x100 }}" type="image/webp">
  <source srcset="{{ product.image.crop.100x100 }}" type="image/jpeg"> 
  <img src="{{ product.image.crop.100x100 }}" alt="{{ product.name }}">
</picture>
```

**Comment by mociepka** [comment]
So you propose to create custom filter and extend it [save_image](https://github.com/respondcreate/django-versatileimagefield/blob/b305877e47d2c5c587d10648b24de332aafa2dd1/versatileimagefield/datastructures/base.py#L151) method to save both types?

That should works for auto generation but I don't knew how task will behave.

**Comment by patrys** [comment]
The `webp` filter would change the extension and mime type used by `save_image` but otherwise each processing pipeline would still only save one thumbnail file.

**Comment by mociepka** [comment]
Yes you are right one image per filter. But what about task? Are you sure that will work with this change? @artursmet what do you think?

**Comment by artursmet** [comment]
Warmer utility from versatileimagefield just iterates over defined sizes, so if we define the sizes properly it should work well.
Warmer calls `getattr(obj, 'crop')['100x100']` explicitly

**Comment by elwoodxblues** [comment]
I'd also start with adjusting VF to our needs. If it becomes too cumbersome, then we could think of our own solution.

**Comment by mociepka** [comment]
Maybe I outline the solution we wanted to achieve with the VF and previously with the sorl-thumbnail and failed:

1. Do not auto generate images on the machine which handle requests.
2. Use celery for images generation.
2. Save all strange images types which can be uploaded (TIFF, BMP, GIF) as JPG.
3. Set max image dimension for whole site.
4. Generate jpg and webp.
5. Have one DRY template tag which will generate proper picture element which proper srcset.
6. Have template tag which will show an error if wrong size was used.
7. Compress all images types with proper dedicated tools: https://images.guide/

If we want to achieve that list of features with adjusting VF or sorl it requires a lot of hackish code. And this list in my opinion is pretty basic (maybe without point 7).

**Comment by patrys** [comment]
Regarding the above:

1 and 2 are how versatileimagefield is intended to be used.

For 3 I'd rather block uploading of BMP and GIF images than try to convert them to JPEG. For TIFF I agree that ideally we'd serve thumbnails as JPEG.

4: this is the whole point of generating thumbnails I believe.

5 is what we're discussing as a goal in this issue.

6 & 7 are already handled in Saleor. When live thumbnail generation is disabled you can't request size/filter combinations that don't exist.

8: Using external tools does not seem to be a great idea. I'd rather save properly optimized thumbnails than try to re-compress already saved JPEG files (which makes compression artifacts worse).

@mociepka Have you done any estimations that compare the cost of creating a new library with improving an existing solution? What about the cost of maintenance and support (documentation, handling third party users of the new library)?

**Comment by patrys** [comment]
Related:

* https://www.sectorlabs.ro/blog/2016/10/26/on-the-fly-thumbnails
* http://thumbor.org/

**Comment by decimoseptimo** [comment]
you might want to add in the [here](https://docs.saleor.io/docs/dashboard/catalog/products/#step-8-add-images) that webp isn't supported, otherwise if feels like an unexpected bug.
