### ISSUE TITLE
Improve "Sort by" label appearance

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1444]
"Sort by" label is rendered differently on the `demo` branch and on `master`. This is probably due to the fact that on demo it's rendered as React component and on master as Django template. However, we have to make sure that the markup and styling is the same in both cases.

Demo:
![image](https://user-images.githubusercontent.com/5421321/33717732-59419f6e-db5b-11e7-93a0-e0baada82979.png)
- missing space between the colon and the field name

Master:
![image](https://user-images.githubusercontent.com/5421321/33717836-a86de732-db5b-11e7-9508-92a620a9699a.png)
- missing colon
- too much space between the label and the icon

Also, I think that the arrow icon could be a little bit smaller; currently it's visually too heavy compared to the text.

**Comment by patrys** [comment]
The one from master looks like an i18n trap to me unless we have separate "sot by name", "sort by price" etc. strings.

**Comment by elwoodxblues** [comment]
We don't, there is translation for "Sort by" and field names translations comes from models.

**Comment by patrys** [comment]
Then I propose using `_("Sort by: %s")` where %s would be replaced by the name that comes from the backend.

**Comment by elwoodxblues** [comment]
We have it in the template currently: https://github.com/mirumee/saleor/blob/master/templates/category/index.html#L52

**Comment by patrys** [comment]
Template has:

```django
{% trans 'Sort by' context 'Category page filters' %}
<strong>
    {{ now_sorted_by }}
</strong>
```

While it should probably have:

```django
{% blocktrans with sorting_field=now_sorted_by context 'Category page filters' trimmed %}
Sort by: <strong>{{ sorting_field }}</strong>
{% endblocktrans %}
```

**Comment by koradon** [comment]
{{ now_sorted_by }} is translated in saleor.product.filter.py

**Comment by patrys** [comment]
@koradon that's not really relevant though?

**Comment by dominik-zeglen** [comment]
Arrows got shrinked by 1/3.

<img width="625" alt="zrzut ekranu 2017-12-11 o 12 31 52" src="https://user-images.githubusercontent.com/6833443/33830845-1a3c285c-de76-11e7-83dc-efab2d595591.png">
