### ISSUE TITLE
Redirections doesn't work when login form is included

### ISSUE THREAD

**Issue by pr0gramista** [mirumee/saleor#1485]
### What I'm trying to achieve
Fix redirections.

### Steps to reproduce the problem

1. Login on checkout 

or

1. Don't login on checkout
2. Login after placing an order

### What I expected to happen
On `/checkout/login` I should get redirected to `/checkout/shipping-address/`

On `/order/<order-hash>/create-password/` with detected user I should get redirected to `/order/<order-hash>/attach/`

### What happened instead/how it failed
Got redirected to the root URL.

**Comment by elwoodxblues** [comment]
@pr0gramista Thanks for catching this issue!
