### ISSUE TITLE
Add support for prices 1.0.0-beta

### ISSUE THREAD

**Issue by koradon** [mirumee/saleor#1487]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve

New version of prices, django-prices and django-prices-openexchangerates are published we should those new versions in saleor.

Saleor should use new api from:
prices >= 1.0.1-beta
django-prices >= 1.0.0-beta
django-prices-openexchangerates >= 1.0.0-beta

**Comment by patrys** [comment]
Why is there a `1.0.1-beta` if there was no `1.0.0`? It should be `1.0.0-beta2`.

**Comment by elwoodxblues** [comment]
@patrys You're right, it should be `1.0.0-beta2`. Can we correct it somehow? I'm afraid once it was released we cannot do much about it.

**Comment by patrys** [comment]
I can delete the release.
