### ISSUE TITLE
SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by dotslash227** [mirumee/saleor#1489]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
I am trying to deploy saleor on my apache server with nginx using mod_wsgi on a Digital Ocean Centos 7 with Python3 enabled virtual environment.

### What I expected to happen
Normal website.

### What happened instead/how it failed
The website shows a 500 internal server error, on looking at the logs, the errors shown are:-

```
[Sun Dec 17 11:00:10.049185 2017] [:error] [pid 22724] [remote 182.69.138.26:0]   File "/home/admin/web/foodezm.delhinerds.com/public_html/env/lib64/python3.6/site-packages/celery/utils/functional.py", line 11, in <module>
[Sun Dec 17 11:00:10.049306 2017] [:error] [pid 22724] [remote 182.69.138.26:0]     from kombu.utils.functional import (
[Sun Dec 17 11:00:10.049323 2017] [:error] [pid 22724] [remote 182.69.138.26:0]   File "/home/admin/web/foodezm.delhinerds.com/public_html/env/lib64/python3.6/site-packages/kombu/utils/__init__.py", line 5, in <module>
[Sun Dec 17 11:00:10.049369 2017] [:error] [pid 22724] [remote 182.69.138.26:0]     from .compat import fileno, maybe_fileno, nested, register_after_fork
[Sun Dec 17 11:00:10.049383 2017] [:error] [pid 22724] [remote 182.69.138.26:0]   File "/home/admin/web/foodezm.delhinerds.com/public_html/env/lib64/python3.6/site-packages/kombu/utils/compat.py", line 29, in <module>
[Sun Dec 17 11:00:10.049451 2017] [:error] [pid 22724] [remote 182.69.138.26:0]     from typing import NamedTuple
[Sun Dec 17 11:00:10.049514 2017] [:error] [pid 22724] [remote 182.69.138.26:0]   File "/home/admin/web/foodezm.delhinerds.com/public_html/env/lib64/python3.6/site-packages/typing.py", line 133
[Sun Dec 17 11:00:10.049522 2017] [:error] [pid 22724] [remote 182.69.138.26:0]     def __new__(cls, name, bases, namespace, *, _root=False):
[Sun Dec 17 11:00:10.049526 2017] [:error] [pid 22724] [remote 182.69.138.26:0]                                               ^
[Sun Dec 17 11:00:10.049530 2017] [:error] [pid 22724] [remote 182.69.138.26:0] SyntaxError: invalid syntax
```

(Please include a stack trace if this problem results in a crash.)

**Comment by patrys** [comment]
Are you sure your mod_wsgi is actually Python 3? The error you get looks very Python 2 to me.

**Comment by dotslash227** [comment]
I think you are right. I did not install mod_wsgi for python3

**Comment by dotslash227** [comment]
I installed mod_wsgi for python 3 as well. but still getting the 500 internal server error.

**Comment by syedhsn** [comment]
@dotslash227 How you solve the internal server error ? Because I got the same error as you.

**Comment by dotslash227** [comment]
@syedhsn, You can have either modwsgi compiled with py3 or py2 but not both. This error will be produced if you are trying to run a py3 application using modwsgi compiled with py2
