### ISSUE TITLE
is it possible to deploy the sailor with apache?

### ISSUE THREAD

**Issue by kevinchow924** [mirumee/saleor#1490]
Hi,

I 'm planning to deploy the saleor  with apache and mod_wsgi  .
Would you like to give me some instruction please ?
thank you

**Comment by dotslash227** [comment]
Deployment with apache is normal, like you do with the rest of your django projects.
Put the wsgi file in the root saleor directory and link use the WSGIScriptAlias directive normally

WSGIScriptAlias / /home/path/to/saleor/folder/wsgi.py

**Comment by kevinchow924** [comment]
thank you so much .

**Comment by saqibkhan2523** [comment]
In current saleor there is a folder og wsgi. So to what file I should set the path of WSGIScriptAlias /home/path/to/saleor/saleor/wsgi/health_check.py?

**Comment by NyanKiyoshi** [comment]
```
/home/path/to/saleor/saleor/wsgi/__init__.py
```

**Comment by saqibkhan2523** [comment]
Thankyou.
