### ISSUE TITLE
Tune price markup in product details page

### ISSUE THREAD

**Issue by cesarob** [mirumee/saleor#1502]
I want to tune modify the generated html that is generated by the **gross tag** [here](https://github.com/mirumee/saleor/blob/master/templates/product/_price_range.html).

I don't find where is that tag defined. I found that the span is generated by django-prices but I don't know where the gross tag is defined.

Any help ir more than wellcome.

Thanks

**Comment by cesarob** [comment]
I spotted it. I didn't see it in the last verion of django-prices but it is in v.0.7.0.

**Comment by elwoodxblues** [comment]
Saleor still uses `v.0.7.0` version of `django-prices`, but we're working on a new version of `prices` and `django-prices` which have slightly different API.
