### ISSUE TITLE
Category edit, delete methods are there but dashboard doesn't have the buttons. Why?

### ISSUE THREAD

**Issue by Premitium** [mirumee/saleor#1504]
Before I add the buttons myself. Is there a reason why the logic is in the code under:
saleor/dashboard/category/urls.py
e.g. views.category_delete and views.category_edit 

Is there a reason why the buttons are missing?

**Comment by Pacu2** [comment]
Buttons should be present, if we are talking about the demo store, enter the category and click three hanging dots in the upper right corner to open the dropdown menu. Last demo release was in November.

However, on master branch buttons should be present once you enter the category (at the bottom of the top card if I remember correctly)

Not sure if we are on the same side, could you post a screenshot while on some category on the dashboard?

**Comment by elwoodxblues** [comment]
These actions are also restricted by permissions. If you are a superuser then you should have permissions to all actions, but in case of a manually created staff user, make sure that the account belongs to the right group (see the "Groups" section in the dashboard).

**Comment by Premitium** [comment]
Guys I so sorry the debug toolbar icon was hiding the dots!
