### ISSUE TITLE
TemplateDoesNotExist at /dashboard/style-guide/

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor#1508]
At url in dashboard http://localhost:8000/dashboard/style-guide/

TemplateDoesNotExist at /dashboard/style-guide/
dashboard/includes/_messages.html

_messages.html file is missing.

**Comment by elwoodxblues** [comment]
Thanks for reporting. We were recently refactoring the implementation of messages in the dashboard and we must have missed the styleguide.
