### ISSUE TITLE
OSX dlopen() failed to load a library: cairo / cairo-2

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor#1510]
If someone having a problem with generating a PDF document on OSX:
dashboard --> orders --> packing slips returning this:

`OSError at /dashboard/orders/21/packing-slips/
dlopen() failed to load a library: cairo / cairo-2`

he can fix it by:
`brew install python3 cairo pango gdk-pixbuf libffi`

Can you add this information to the documentation?

**Comment by patrys** [comment]
Yes, this should definitely become part of the documentation.

**Comment by primal100** [comment]
roboto-fontface-fonts is also needed and not included for some distributions (e.g. Centos)

**Comment by rupeshcode** [comment]
I experienced the same issue while trying to generate an invoice. 
I solved it by -

1) set my locale in my .zshrc / .bashrc
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

2) making sure dependencies are installed:
brew install python cairo pango gdk-pixbuf libxml2 libxslt libffi
