### ISSUE TITLE
Where do I throw in the configuration for Stripe, Paypal, etc?

### ISSUE THREAD

**Issue by knyzorg** [mirumee/saleor#1520]
The readme (https://saleor.readthedocs.io/en/latest/payments.html) is very lacking, I don't know what files I am suppose to edit. Can I be shown the right direction? Also the readme I linked could use a bit of an improving.

**Comment by knyzorg** [comment]
I have figured it out with intensive grepping that it goes into the settings.py file (shocker)

With that said, docs should still be updated.

**Comment by primal100** [comment]
It's covered in Django-payments docs. The documentation for some of the dependencies, particularly those created by mirumee, go hand in hand with the Saleor docs.
