### ISSUE TITLE
Paypal IPN

### ISSUE THREAD

**Issue by maoxiao** [mirumee/saleor#1526]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
Paypal IPN integration 

Hi, according to Paypal Doc, "**Ensure that you receive an IPN whose payment status is "completed" before shipping merchandise or enabling download of digital goods**". I am not sure how saleor handles IPN? Should I implement IPN listener myself?

Thanks!

**Comment by nikolas310** [comment]
Any solution?
