### ISSUE TITLE
Newly registered user e-mail confirmation

### ISSUE THREAD

**Issue by primal100** [mirumee/saleor#1527]
I see that according to previous issues and pull requests, that e-mail address confirmation for new users was a feature in the past but currently is not. I would like to add it to my site, I can work on it as a pull request for Saleor (mostly taken from the django-allauth implementation, it would be enabled/disabled in settings.py) but first I wanted to check if it's something that would likely be added to Saleor. Also wanted to ask if there is already an easy way to enable it that perhaps I'm missing?

### What I'm trying to achieve

...Users need to confirm their e-mail address before logging in

### Steps to reproduce the problem

1.User registers
2.User is immediately logged in, no activation e-mail

### What I expected to happen

...User needs to confirm e-mail address via e-mail activation link

### What happened instead/how it failed

...User is immediately allowed to login

**Comment by elwoodxblues** [comment]
Hi @primal100, there's currently no such feature but I think it would be very useful to have it by default 
 in Saleor with the ability to switch it through settings. If you are willing to add it, a PR would be welcomed :)

I would start with customizing the `SignupForm` to send the email upon successful registration. It should work similarly to how the "password reset" feature works in terms of separating logic and organizing templates. If you need any further help, feel free to ask.

**Comment by primal100** [comment]
I'm working on this here:

https://github.com/primal100/saleor/tree/feature/user-email-confirmation

It's working well. The one thing I am not sure about is adding the additional strings for messages to the .po files and integrating with transifex. I'm guessing something like:

1) ugettext_lazy for all strings to be contained in messages
2) Add the new strings manually to saleor/dashboard/locale/en/LC_MESSAGES/django.po 
3) Run some script to add them to the other .po files and integrate with transifex?

Any help appreciated.

**Comment by mad-anne** [comment]
Hi @primal100, for translations it will be enough if you use `pgettext` (or `pgettext_lazy`) in code and `trans` (or `blocktrans`) in templates. Also, it would be nice if you use `django-templated-email` package for sending e-mails. You can see how it is used in `PasswordSetUpForm`'s `send_mail()` method for example.
Could you please open a Pull Request based on your changes?

**Comment by Pacu2** [comment]
@maarcingebala Can we get back to this issue? I think it will be needed for most of the big players using Saleor.

**Comment by Boquete** [comment]
Any update? Is there any way to activate activation email link for user?

**Comment by maarcingebala** [comment]
Not yet, but @tomaszszymanski129 is on it, expect a PR soon :)

**Comment by tomaszszymanski129** [comment]
Feature implemented, it's enabled by default, to ensure it works correctly please check following environment variables:

`ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL` - defaults to `True` if not provided
`ALLOWED_CLIENT_HOSTS` - proper storefront url needs to be in there
