### ISSUE TITLE
 cannot import name markdown

### ISSUE THREAD

**Issue by selvailm** [mirumee/saleor#1530]
Invalid template library specified. ImportError raised when trying to load 'saleor.core.templatetags.markdown': cannot import name markdown

New to saleor was trying to run server from http://localhost:8000/ got error plz help me.

**Comment by elwoodxblues** [comment]
Hi @selvailm, does this happen on the master branch?  There is the templatetag `markdown` in file `saleor/core/templatetags/markdown.py` - do you have it? It is imported and used in the template file `templates/product/details.html`. Make sure that you have those files. A quick workaround to make the templates work would be also to comment or remove the occurrences of the `markdown` templatetag.

**Comment by elwoodxblues** [comment]
@selvailm Were you able to resolve this issue?
