### ISSUE TITLE
400 Bad request on image uploading

### ISSUE THREAD

**Issue by dotslash227** [mirumee/saleor#1532]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve

Trying to upload images to the products.

### Steps to reproduce the problem

1. Go to the edit product
2. Click on edit images
3. Drag and drop an image

### What I expected to happen

Image gets uploaded.

### What happened instead/how it failed

Images does not get uploaded.
Console shows the following error on uploading: POST http://foodezm.delhinerds.com/dashboard/products/1/images/upload/ 400 (Bad Request)

The response headers are: 
{"error": {"image": ["This field cannot be blank."]}}

**Comment by primal100** [comment]
Which browser? #1511 refers to an issue with Safari

**Comment by dotslash227** [comment]
I am using Chrome.

**Comment by dotslash227** [comment]
I am having the same issue with Firefox as well. Does not work on either, chrome or firefox.

**Comment by dominik-zeglen** [comment]
Could you tell us which version of Chrome and Firefox do you use?
Also, we recently merged a PR which was supposed to fix this bug - #1497 - please make sure your Saleor fork contains this fix.

**Comment by dotslash227** [comment]
Chrome version: Version 62.0.3202.94 (Official Build) (64-bit)
Firefox: 57.0.1 (64-bit)

**Comment by dotslash227** [comment]
I'll pull Issue 1497 to my repo.

**Comment by elwoodxblues** [comment]
Is this issue resolved?

**Comment by elwoodxblues** [comment]
Closing due to no response. Please reopen if needed.
