### ISSUE TITLE
Error generating a packing slip

### ISSUE THREAD

**Issue by boutinjerome** [mirumee/saleor#1536]
### What I'm trying to achieve

I am clicking on Packing slip on an order.

### Steps to reproduce the problem

1. Create an order
2. Log as an administrator
3. Find the order
4. Click on packing slip.

### What I expected to happen

I was expecting to get a page displaying the packing slip to print.

### What happened instead/how it failed

It generate an eror stack as below.

Request Method: | GET
-- | --
http://127.0.0.1:8000/dashboard/orders/21/packing-slips/
1.11.5
AttributeError
'NoneType' object has no attribute '_meta'
/Users/jboutin/anaconda/lib/python3.5/site-packages/django/forms/models.py in model_to_dict, line 88
/Users/jboutin/anaconda/bin/python
3.5.4
['/Users/jboutin/workspaces/bookstore/saleor',  '/Users/jboutin/anaconda/lib/python35.zip',  '/Users/jboutin/anaconda/lib/python3.5',  '/Users/jboutin/anaconda/lib/python3.5/plat-darwin',  '/Users/jboutin/anaconda/lib/python3.5/lib-dynload',  '/Users/jboutin/anaconda/lib/python3.5/site-packages',  '/Users/jboutin/anaconda/lib/python3.5/site-packages/Sphinx-1.6.3-py3.5.egg',  '/Users/jboutin/anaconda/lib/python3.5/site-packages/aeosa',  '/Users/jboutin/anaconda/lib/python3.5/site-packages/netaddr-0.7.19-py3.5.egg',  '/Users/jboutin/anaconda/lib/python3.5/site-packages/scp-0.10.2-py3.5.egg',  '/Users/jboutin/anaconda/lib/python3.5/site-packages/paramiko-2.3.1-py3.5.egg',  '/Users/jboutin/anaconda/lib/python3.5/site-packages/ncclient-0.5.3-py3.5.egg',  '/Users/jboutin/anaconda/lib/python3.5/site-packages/pyasn1-0.3.6-py3.5.egg',  '/Users/jboutin/anaconda/lib/python3.5/site-packages/PyNaCl-1.1.2-py3.5-macosx-10.7-x86_64.egg',  '/Users/jboutin/anaconda/lib/python3.5/site-packages/bcrypt-3.1.3-py3.5-macosx-10.7-x86_64.egg',  '/Users/jboutin/anaconda/lib/python3.5/site-packages/junos_eznc-1.1.2-py3.5.egg',  '/Users/jboutin/workspaces/bookstore/saleor']
dim, 31 Déc 2017 16:27:12 -0600

**Comment by elwoodxblues** [comment]
Hi @boutinjerome, do you get this error with every new order that you create? I wasn't able to reproduce it on my local master.

**Comment by boutinjerome** [comment]
Hi @elwoodxblues I effectively get this error on every new order I am creating. I wonder if I use a format in one of the field that trigger this error.

**Comment by elwoodxblues** [comment]
I'm wondering if this is a problem with the library that we use for generating PDFs. Could you check if generating the invoices works for you? Invoice URL for this order would be: `http://127.0.0.1:8000/dashboard/orders/21/invoice/`

Also, could you post the full traceback? I see that the error happens in: `/Users/jboutin/anaconda/lib/python3.5/site-packages/django/forms/models.py in model_to_dict, line 88`, but I'd like to see how Python even got to that line of code. You'll find the traceback on the standard Django error page, use "Switch to copy-and-paste view".

**Comment by boutinjerome** [comment]
This direct link works. I am attaching the result output. I also attach
what is output on the console as it hasn't generate an error. Let me know
if you want another "full traceback" and how to obtain it.



2018-01-04 3:47 GMT-05:00 Marcin Gębala <notifications@github.com>:

**Comment by elwoodxblues** [comment]
@boutinjerome I don't see the traceback attached anywhere. Maybe you should respond via Github instead of email to make sure it's attached properly.

**Comment by boutinjerome** [comment]
Here is what was output on the console:

Jeromes-MacBook-Pro:saleor jboutin$ python manage.py runserver
Performing system checks...

System check identified some issues:

WARNINGS:
saleor.W001: Session caching cannot work with locmem backend
	HINT: User sessions need to be globally shared, use a cache server like Redis.

System check identified 1 issue (0 silenced).
January 04, 2018 - 21:28:52
Django version 1.11.5, using settings 'saleor.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
INFO weasyprint Step 1 - Fetching and parsing HTML - HTML string [PID:5005:Thread-1]
INFO weasyprint Step 2 - Fetching and parsing CSS - http://localhost:8000/static/assets/document.css [PID:5005:Thread-1]
ERROR weasyprint Failed to load stylesheet at http://localhost:8000/static/assets/document.css : URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known> [PID:5005:Thread-1]
INFO weasyprint Step 3 - Applying CSS [PID:5005:Thread-1]
INFO weasyprint Step 4 - Creating formatting structure [PID:5005:Thread-1]
ERROR weasyprint Failed to load image at "http://localhost:8000/static/images/logo_document.svg" (URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>) [PID:5005:Thread-1]
INFO weasyprint Step 5 - Creating layout - Page 1 [PID:5005:Thread-1]
INFO weasyprint Step 6 - Drawing [PID:5005:Thread-1]
INFO weasyprint Step 7 - Adding PDF metadata [PID:5005:Thread-1]
INFO django.server "GET /dashboard/orders/21/invoice/ HTTP/1.1" 200 49847 [PID:5005:Thread-1]
INFO django.server "GET /dashboard/orders/21/invoice/ HTTP/1.1" 200 49847 [PID:5005:Thread-1]
INFO django.server "GET /dashboard/orders/21/invoice/ HTTP/1.1" 200 49847 [PID:5005:Thread-1]
WARNING django.request Not Found: /favicon.ico [PID:5005:Thread-8]
WARNING django.request Not Found: /favicon.ico [PID:5005:Thread-8]
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 5469 [PID:5005:Thread-8]
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 5469 [PID:5005:Thread-8]
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 5469 [PID:5005:Thread-8]

And the output page:
[Invoice for Order #21.pdf](https://github.com/mirumee/saleor/files/1607284/Invoice.for.Order.21.pdf)

**Comment by primal100** [comment]
Are the static/media files being served? Make sure to run in with debug=True in settings.py and see if it works. If it works then but not when debug is false then it's just a matter of learning how to serve those files when debug is false.

If it doesn't work even when debug mode is false then there will be an error page generated. Respond on within with screenshots of the error page including the traceback.

**Comment by elwoodxblues** [comment]
`ERROR weasyprint Failed to load stylesheet at http://localhost:8000/static/assets/document.css` - this log clearly shows that the static files were not loaded. Check if you have the proper domain configured in the "Site settings" section in the dashboard, as it is used to determine the path of static files used by PDF generator.

**Comment by boutinjerome** [comment]
I haven't found an error in the domain configuration so I am copying the stacktrace:

Environment:


Request Method: GET
Request URL: http://localhost:8000/dashboard/orders/21/packing-slips/

Django Version: 1.11.5
Python Version: 3.5.4
Installed Applications:
['storages',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sitemaps',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.auth',
 'django.contrib.postgres',
 'django.forms',
 'saleor.userprofile',
 'saleor.discount',
 'saleor.product',
 'saleor.cart',
 'saleor.checkout',
 'saleor.core',
 'saleor.graphql',
 'saleor.order',
 'saleor.dashboard',
 'saleor.shipping',
 'saleor.search',
 'saleor.site',
 'saleor.data_feeds',
 'versatileimagefield',
 'django_babel',
 'bootstrap3',
 'django_prices',
 'django_prices_openexchangerates',
 'graphene_django',
 'mptt',
 'payments',
 'webpack_loader',
 'social_django',
 'django_countries',
 'django_filters',
 'django_celery_results',
 'impersonate',
 'phonenumber_field']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django_babel.middleware.LocaleMiddleware',
 'saleor.core.middleware.DiscountMiddleware',
 'saleor.core.middleware.GoogleAnalytics',
 'saleor.core.middleware.CountryMiddleware',
 'saleor.core.middleware.CurrencyMiddleware',
 'saleor.core.middleware.ClearSiteCacheMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'impersonate.middleware.ImpersonateMiddleware']


Template error:
In template /Users/jboutin/workspaces/bookstore/saleor/templates/dashboard/includes/_address.html, error at line 5
   'NoneType' object has no attribute '_meta'   1 : {% load format_address from i18n_address_tags %}
   2 : {% load staticfiles %}
   3 : 
   4 : <div class="address">
   5 : 	<div class="formatted-address"> {% format_address address latin=True %} </div>
   6 : 	{% if address.phone %}
   7 : 		<div>
   8 : 			<svg data-src="{% static "dashboard/images/phone.svg" %}" width="16" height="16" class="left" />
   9 : 			<a href="tel:{{ address.phone }}" class="phone-number">
   10 : 				{{ address.phone }}
   11 : 			</a>
   12 : 		</div>
   13 : 	{% endif %}
   14 : </div>
   15 : 

Traceback:

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/Users/jboutin/workspaces/bookstore/saleor/saleor/dashboard/order/views.py" in order_packing_slip
  419.     pdf_file, group = create_packing_slip_pdf(group_pk, absolute_url)

File "/Users/jboutin/workspaces/bookstore/saleor/saleor/dashboard/order/utils.py" in create_packing_slip_pdf
  45.     rendered_template = get_template(PACKING_SLIP_TEMPLATE).render(ctx)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/backends/django.py" in render
  66.             return self.template.render(context)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/base.py" in render
  207.                     return self._render(context)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/defaulttags.py" in render
  529.             return self.nodelist.render(context)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  214.                 return template.render(context.new(values))

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/base.py" in render
  209.                 return self._render(context)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/template/library.py" in render
  203.         output = self.func(*resolved_args, **resolved_kwargs)

File "/Users/jboutin/workspaces/bookstore/saleor/saleor/userprofile/templatetags/i18n_address_tags.py" in format_address
  13.     address_data = Address.objects.as_data(address)

File "/Users/jboutin/workspaces/bookstore/saleor/saleor/userprofile/models.py" in as_data
  27.         data = model_to_dict(address, exclude=['id', 'user'])

File "/Users/jboutin/anaconda/lib/python3.5/site-packages/django/forms/models.py" in model_to_dict
  88.     opts = instance._meta

Exception Type: AttributeError at /dashboard/orders/21/packing-slips/
Exception Value: 'NoneType' object has no attribute '_meta'

**Comment by boutinjerome** [comment]
@elwoodxblues site settings has this configured: localhost:8000

Is it what should be define here when no real domain exist on this development setup? Also If I try to access this link directly (http://localhost:8000/static/assets/document.css) it works.

**Comment by elwoodxblues** [comment]
@boutinjerome I've spotted the bug in the traceback that you've posted, namely:
```
File "/Users/jboutin/workspaces/bookstore/saleor/saleor/userprofile/templatetags/i18n_address_tags.py" in format_address
13. address_data = Address.objects.as_data(address)
File "/Users/jboutin/workspaces/bookstore/saleor/saleor/userprofile/models.py" in as_data
27. data = model_to_dict(address, exclude=['id', 'user'])
```
which means that the `shipping_address` is empty in this case and the templatetag that renders the address fails in this case. This is obiously a bug and we'll fix it. I'm wondering, how did you get the order without the shipping address? @rafalp, maybe we could fix that in #1570?

**Comment by patrys** [comment]
@elwoodxblues There won't be a shipping address if there are no shippable delivery groups (which means there are no shippable items in any of the groups).

**Comment by elwoodxblues** [comment]
Correct me if I'm wrong, but currently, there is no possibility to create an order without any shipment groups using either storefront or dashboard. Empty addresses are allowed at the database level and our templates should be robust to that.

**Comment by patrys** [comment]
You can mark all products as not requiring shipping though.
