### ISSUE TITLE
Remove or block impersonate's "list" and "search" urls

### ISSUE THREAD

**Issue by rafalp** [mirumee/saleor#1564]
Saleor uses the [django-impersonate](https://bitbucket.org/petersanchez/django-impersonate/overview) for client impersonation feature. While working on #1549 I've found out that in addition to two views that we are using (start and stop impersonating the user), the library brings additional two views that we don't really want to support:

https://demo.getsaleor.com/impersonate/list/
https://demo.getsaleor.com/impersonate/search/?q=admin (note: this one 500's on link)

Ideally, library would've provided us with a settings to disable those views, but this isn't the case.

So its worth asking ourselves what harm is there in keeping those views around, and if we really want to get rid of those two views, how would we go about it?

Looking at the [imersonate.urls](https://bitbucket.org/petersanchez/django-impersonate/src/f898c697b2bd9945187f8667d680e6d10d06dc33/impersonate/urls.py?at=default&fileviewer=file-view-default), it may be as simple as updating our `urls.py` to explictly define `impersonate-start` and `impersonate-stop`, or perhaps we should open the issue upstream and see what library's author thinks about it?

**Comment by patrys** [comment]
Let's just explicitly link to views we need.
