### ISSUE TITLE
InterfaceError at /admin/products/product/add/

### ISSUE THREAD

**Issue by SanskarSans** [mirumee/saleor#1572]
I get following error when saving product from admin. 

`
InterfaceError at /admin/products/product/add/
Error binding parameter 9 - probably unsupported type.
`

I am confused with the attribute field.

this is what I have provided in attribute field of Product 

`
{
    "color": "Red, Blue, Green"
}
`

![Product Admin](https://i.imgur.com/BOOQ1Ix.png)

**Comment by elwoodxblues** [comment]
@SanskarSans The problem may be with the key "color". Instead, you should use the ID of related `ProductAttribute` instance. E.g. assuming there is the `ProductAttribute` with the following fields: `id=1, name="Color", slug="color"`, then in the "Attributes" field you could have:
```
{'1': 'Red, Green, Blue'}
```
Anyway, we don't support the built-in django-admin by default, so I can't assure you that everything will work there. I recommend using the [dashboard](https://demo.getsaleor.com/dashboard/).

**Comment by SanskarSans** [comment]
@elwoodxblues thanks for your reply. In you dashboard, I did not see the field for attributes in Product table. I tried to understand from the demo that is in the docs section. Can you explain me the attributes part relating to your dashboard, please? I did not see anywhere about it.

**Comment by elwoodxblues** [comment]
## Attributes
The UI for attributes in the product add/edit form is dynamic and depends on the attributes defined at the product type level.

E.g. in the demo, we have type "[E-books](https://demo.getsaleor.com/dashboard/products/classes/1/update/)". So in the dashboard navigation go to "Product types" > "E-books" and you'll find the product attributes in the field "Attributes common to all variants (optional)":
![image](https://user-images.githubusercontent.com/5421321/34712292-99c51b8e-f522-11e7-8f75-62ff5b916b94.png)

Then, when adding a new product, you have to first select the product type of the new product. Select "E-books", and in the view for creating products ([example from demo](https://demo.getsaleor.com/dashboard/products/10/update/)) you'll see the attributes specific to that type in the form (fields "Author", "Language", "Publisher":
![image](https://user-images.githubusercontent.com/5421321/34712318-b29a1f24-f522-11e7-9bec-73b524e11199.png)

## Categories
As for the categories, when in category details view, you have the ability to add subcategories by using the "Add" button in the "Subcategories" table:
![image](https://user-images.githubusercontent.com/5421321/34713425-81048c48-f526-11e7-83cf-edc678d8446e.png)

[Here is the example](https://demo.getsaleor.com/dashboard/categories/4/) from our demo store.

**Comment by elwoodxblues** [comment]
Closing due to no response. Please reopen in case of further questions.
