### ISSUE TITLE
Allow creating customers from the dashboard

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1578]
In the "Customers" view in the dashboard, we should have the ability to add new customers. It should work similarly to creating staff members, so after creating a new User instance, an email with password setup link should be sent.

**Comment by patrys** [comment]
Out of curiosity: why do we need to create customer accounts? Could this be abused? And if so, should it require a special permission?

**Comment by elwoodxblues** [comment]
How could this be abused? It should require a permission just like other dashboard actions. This seems a pretty standard feature in e-commerce platforms and there are valid cases that staff may want to add customers from the dashboard. We've implemented this in at least one project based on Saleor already.

**Comment by patrys** [comment]
My question about potential abuse is an honest one. I'm trying to come up with legitimate reasons to create an account without going through the registration process (and giving us an explicit permission required by soon-to-be-law data protection regulations in Europe).

**Comment by elwoodxblues** [comment]
What's the difference between creating an account through the registration process and the dashboard from the data-protection point of view?

**Comment by patrys** [comment]
With GDPR in place the staff members shouldn't input any personal data into the system without the user explicitly allowing them to do so (which usually happens through clicking "I agree..." during the registration).

**Comment by elwoodxblues** [comment]
We'll have to go through the whole project and check it against GDPR compliance then.
