### ISSUE TITLE
Shipping address card not rendered when the address is empty

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1582]
This happens in the order details view in the dashboard: when there is no shipping address, the whole "Shipping address" card disappears. I think that the card should be rendered with a message "No shipping address" and the "Edit" button below, which will allow setting the address. The same applies to the billing address.

**Comment by patrys** [comment]
Shouldn't this depend on whether order requires shipping?

**Comment by elwoodxblues** [comment]
True, if an order doesn't require shipping, the "Shipping address" card should be hidden.

**Comment by elwoodxblues** [comment]
There are few more issues related to that, but I'll open a separate issue for that. Basically, we don't support the following scenario:
- there is a delivery group that doesn't require shipping,
- we edit the order by adding a shippable item,
- the order becomes marked as shippable
The latter doesn't happen, as we determine the "is shipping required" flag based on the selected shipping method. Shipping method gets copied from a group that requires shipping, but in the scenario above it won't happen.
