### ISSUE TITLE
ProductClass naming consistency

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#1586]
There is no consistency in naming related to the product class concept. We have a model `ProductClass`, but in the dashboard UI it is mostly referred to as "type". I personally think that the "product type" name is more user-friendly, but I'd like to hear some input. We should agree on one name and unify it in Python/templates code, documentation and UI.

**Comment by patrys** [comment]
Both "class" and "type" have a second meaning in programming so I don't have a strong preference between the two but would like if we could come up with something slightly less ambiguous.

**Comment by elwoodxblues** [comment]
I don't have any better ideas about this. We use "type" in the UI already and I find it more natural than "class".

**Comment by mad-anne** [comment]
I agree that ```ProductType``` sounds better, a little bit more natural and that it should be unified.

**Comment by dfee** [comment]
Interesting that I ran across this closed issue tonight. I was wondering what a `product type` was as referred to [in the `product` docs](https://saleor.readthedocs.io/en/latest/architecture/products.html). I guess that's a "product class".

**Comment by elwoodxblues** [comment]
Yes, the diagram in the docs is outdated, thanks for pointing that out!

**Comment by elwoodxblues** [comment]
Todo: update product structure diagram.
