### ISSUE TITLE
Integrate rich text editor

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1587]
I'd like to start the discussion about choosing a rich text editor that we'll use in the dashboard. From what I recall the one that we've liked the most so far was the [Medium-editor](https://github.com/yabwe/medium-editor). @patrys @dominik-zeglen Do you know any other libraries worth considering?

**Comment by dominik-zeglen** [comment]
https://github.com/froala/wysiwyg-editor
https://github.com/GetmeUK/ContentTools

These two look very promising.

**Comment by patrys** [comment]
@dominik-zeglen We're looking for an editor for the dashboard, we're not currently trying to replace the dashboard with inline tools.

**Comment by patrys** [comment]
Froala does not have a compatible license.

**Comment by elwoodxblues** [comment]
I suggest giving a try to medium-editor then. @dominik-zeglen We could start with trying to add the editor in the product description TextArea in the dashboard. From the backend point of view, it would be great if we could have a Django widget e.g. `RichTextArea` that could be used as a drop-in replacement for a standard TextArea.

**Comment by patrys** [comment]
Next step: flat pages? 😄

**Comment by elwoodxblues** [comment]
Well, that might happen :)

**Comment by rafalp** [comment]
Here's [MegaDraft](http://megadraft.io/), build on Facebook's [Draft.js](https://github.com/facebook/draft-js)

**Comment by patrys** [comment]
We've been playing with Draft.js and its derivatives but they all require state to be stored as a JSON object.
