### ISSUE TITLE
No ability to select text in dashboard clickable table rows

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1596]
In the dashboard tables, we have clickable rows that allow going to the details page by clicking anywhere on the highlighted row. However, the script that handles this behavior reacts to the first mouse click which makes it impossible to select anything in the table (e.g. for copy-pasting a customer email from the list, order ID etc.).

**Comment by patrys** [comment]
We should probably mark the action as cancelled on drag start and only navigate on mouse up.
