### ISSUE TITLE
Need to get buyer first name and last name

### ISSUE THREAD

**Issue by tonylampada** [mirumee/saleor#1599]
Hi, sorry if this is not the right place to ask questions like this.

I'm trying to build on top of saleor (while keeping the changes to the core code to a minimum) to build an online store.
Right now what I'm trying to achieve is to integrate saleor with [PagSeguro](https://pagseguro.uol.com.br/), a payment gateway that is very popular and trusted here in Brazil, so I'm trying to follow the example of the DummyProvider that I found inside django-payments code. All good.

To use Pagseguro's API, I need to tell PagSeguro about the buyer's **first name and last name**, but, the sign-up process on saleor only asks for e-mail. Also looking at `saleor.userprofile.models.User` model, it doesn't even have the attributes for first name and last name.

I'm also thinking that knowing the buyer's first and last name might come in handy later, for example, if I want to customize emails for example.

So I'm wondering what's the best "non-invasive" way to have saleor store that information about the buyer.

**Comment by patrys** [comment]
You are right in your discoveries, let me provide some context.

The Address object used for shipping and billing does have the fields for first and last name.

However under certain circumstances you may actually want to include those fields in your payment form as well. Like if you ask for things like a credit card number there are cases where the invoice needs to be addressed for John Doe while the card may belong to a Jane Smith. The bank could rightly refused the transaction if presented with the wrong name just as the accountant may reject an invoice if the other name is present.

**Comment by tonylampada** [comment]
That was fast, thanks!

> The Address object used for shipping and billing does have the fields for first and last name.

Of course! `(payment.billing_first_name, payment.billing_last_name)`
This solves my problem, thanks again!
