### ISSUE TITLE
Order notes enhancements

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1605]
Since we're just finishing a PR that adds the ability to add an order note in checkout (#1535), I was thinking about further improvements to that feature, turning them more into conversations.

- Notes could be displayed in the storefront's order details view. For that purpose, it would be useful to have a flag e.g. `is_public`. Notes added by users in checkout should be public by default.
- When staff users add new notes, they should see the checkbox "Customer can see this note" that determines whether the note is public or not.
- Customers should be notified by an email about new public notes added to their orders.

This is just an idea and I'd find such feature useful, but I'd like to hear some input on this.

**Comment by patrys** [comment]
Maybe customers should be able to add further notes from the order details page (at least until the order is at least partially shipped, I suppose we don't want this to become a support forum).

**Comment by elwoodxblues** [comment]
As long as the order is open, customers should be able to do that.
