### ISSUE TITLE
Installing with docker problem

### ISSUE THREAD

**Issue by sofzer** [mirumee/saleor#1612]
### Installing with docker
 after installing docker and building
i tried to connect to run with docker-compose run web python manage.py migrate
but an error appeared:

ERROR: for saleor_db_1  Cannot start service db: driver failed programming external connectivity on endpoint saleor_db_1 (9833d3b3ef6943ecacbf3386a0821a2684c1fea3b58f47ee1a61e4efc1d2fa4c): Error starting userland proxy: Bind f
Starting saleor_search_1 ... done

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint saleor_db_1 (9833d3b3ef6943ecacbf3386a0821a2684c1fea3b58f47ee1a61e4efc1d2fa4c): Error starting userland proxy: Bind for 127.0.
0.1:5432: unexpected error Permission denied
ERROR: Encountered errors while bringing up the project.

...

please help me to fix

**Comment by dARKf3n1Xx** [comment]
there is this database url in settings.py, did you change it to your own postgresql url?

**Comment by dARKf3n1Xx** [comment]
remove ports from dockerfile and compose again

**Comment by patrys** [comment]
Do you happen to be running something on port 5432? Like a PostgreSQL server outside of Docker?

**Comment by sofzer** [comment]
@patrys: Thank you very much!
That solved the problem
