### ISSUE TITLE
Changing the relationship between Categories and Products to one-to-many

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1619]
Currently, the relationship is M2M but there is an idea to change it to one-to-many, so that:
- a product can belong to a single category,
- a category can contain multiple products.

The reason for having M2M was to have the ability to group products in collections, but that was never fully supported in the UI. For that purpose, we're going to revisit the PR #734, that adds the product collections.

Todo:
- [ ] Change the `categories` field in the Product model to:
`category=ForeignKey(Category, related_name='products')`
- [ ] adjust related views and templates
- [ ] update documentation and tests where neccessary

**Comment by elwoodxblues** [comment]
@patrys What about the `is_hidden` field? Should we allow hiding categories when there is only one per product?

**Comment by patrys** [comment]
I think the main goal of `is_hidden` was to allow hiding non-primary categories (like the ones used for discounts) from the main navigation. With proper collections there's no reason to hide categories.
