### ISSUE TITLE
OrderHistoryEntry allows for adding messages only with 100 characters 

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1629]
The `OrderHistoryEntry.comment` field has max length of 100 characters. This limit should be extended, as it may happen that messages will be longer, as in some cases they are assembled from emails, product names and custom comments.

**Comment by akjanik** [comment]
@elwoodxblues Any desired number for new max length value?

**Comment by elwoodxblues** [comment]
We should be fine using the maximum available length of 255 characters.

**Comment by patrys** [comment]
Why would 255 be the limit? This is not MySQL 😄

**Comment by elwoodxblues** [comment]
True. Anyway, 255 should be okay, or do you think otherwise @patrys? Yesterday I got an error having the limit of 100 characters by doing regular stuff in order detail dashboard, so I wanted to increase it. To be 100% sure we could change it to TextField as well.

**Comment by patrys** [comment]
I think a text field would be more useful, I'd even consider supporting HTML (sanitized) in case someone wants to paste an email message they've received.

**Comment by elwoodxblues** [comment]
Sounds interesting. @akjanik let's make it a TextField then.

**Comment by elwoodxblues** [comment]
Two more things.
- In the OrderNote model, we also have a CharField:
```content = models.CharField(max_length=250)```
while this could similarly be a TextField supporting HTML in the future.
- Wouldn't it be better to change the field name `comment` to something like `content`? It's not a comment 🙂
