### ISSUE TITLE
Handling not shippable products in the order management

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1630]
I've been testing the order management flow recently and it turns out that there is a number of issues related to the fulfillment of groups that don't require shipping.

Below is the screenshot of an order with two groups - one with a shippable item and the second with the digital item (not requiring shipping), which I'll use for reference. The order was created through the storefront:

![image](https://user-images.githubusercontent.com/5421321/34992069-31037eec-facc-11e7-9c5f-82b669c4684f.png)

1. There is no ability to fulfill the group without shipping ("Shipment 32"). The "Dispatch" action is only shown for groups that can be actually dispatched (they require shipping and have the shipping method set). Shouldn't we have some kind of "Fulfill" action in both cases, one that would allow entering the tracking number and the other that would simply mark the order as "fulfilled"?

2. The title "Shipment 32 - None" is wrong. First of all because of unhandled "none" and second, shouldn't it be called differently than "Shipment", since it's not shippable?

3. Staff users are able to modify the order using "Add product" feature. If there's an order only with digital goods and the staff adds a shippable item, the item is added to the same group, but a new group should be created.

4. There is no ability to set the shipping method, price, and address for the newly created groups if it wasn't previously set. Problem with this is, that it may result in higher price of an order, that was already paid. I'm not sure how to handle the payment in this case, but maybe we should allow such modification only for unpaid orders?

**Comment by patrys** [comment]
I think digital groups should automatically become complete once they are paid for. Those cases are usually self-serve (link to download, assigning a license etc.). Others can always customize the logic if there's need for that.

**Comment by patrys** [comment]
For cases where items are added to an order, let the staff decide what to do (discount the item or ask the customer to pay) but I think we should make sure that paying a second time is actually possible (I think we may have an arbitrary limit of one Payment object per order).

**Comment by elwoodxblues** [comment]
I'm not sure about automatic fulfillment. Maybe that's something that should be configurable from the settings? I can imagine that there may be situations that staff would like to have full control on the order and confirm everything manually before it's delivered to the customer.

@patrys What do you think about using the "Shipment" nomenclature in this view? I assume there may be only one group with digital items at once that could be entitled "Digital items" or "No shipping required" etc. (maybe these items don't have to be digital).

**Comment by mad-anne** [comment]
For now we decided to:
- [ ] - improve calculating ```shipping_required``` property in ```DeliveryGroup``` (```True``` if any OrderLine in group requires shipping)
- [ ] - give an ability to edit nullable ```shipping_address``` in order details
- [ ] - exclude ```sku``` from displayed product name
- [ ] - move ```sku``` under product's name in ordered items table
- [ ] - hide stock location name and related actions if only one stock location exists
- [ ] - hide ```Add product``` action on shipped groups

**Comment by elwoodxblues** [comment]
I'm closing this, as we're working on a new order management flow (#1767) that should solve all the issues mentioned here.
