### ISSUE TITLE
List of environment variables used in settings

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#1642]
### What I'm trying to achieve

I'd love to have a page in documentation, where I could find all environment variables used for configuration.
Ideally there should be some example values delivered.

**Comment by primal100** [comment]
Have you seen this?

http://saleor.readthedocs.io/en/latest/configuration.html

**Comment by artursmet** [comment]
Thank you @primal100, I've forgotten that we already have such page ;)
Anyway, it should be linked from deployment page, to make more clear how to deploy with docker.
