### ISSUE TITLE
Help needed: Not an Issue

### ISSUE THREAD

**Issue by gupta** [mirumee/saleor#1644]
Hi,
This is a request for some help, not an issue. I could not find any other forum so am posting it here.

I am trying to understand how a new product image is added in saleor. 

The images for a product are listed by views.product_images, which renders the template "/dashboard/product/product_image/list.html",. When an image is dropped into this page, the view   ajax_upload_image is called.

However: I am unable to find any <input> field and any mechanism for submitting the form in /dashboard/product/product_image/list.html. I have looked through the .js files also but not found anything. I am definitely missing something. Please help.

**Comment by patrys** [comment]
I think you're looking for `saleor/static/dashboard/js/components/image-gallery.js`?

**Comment by gupta** [comment]
Thanks a lot.
