### ISSUE TITLE
I'm prompted for a province in Argentina

### ISSUE THREAD

**Issue by WhyNotHugo** [mirumee/saleor#1646]
I'm trying out the demo, and I'm kinda stuck at the checkout phase. When I'm [prompted for a shipping address](https://demo.getsaleor.com/checkout/shipping-address/), there's a `Province` field.

Now, here's the thing: Argentina is split into 23 provinces and 1 autonomous city. This city _doesn't_ belong to any province (it kinda messes up the hierarchy, I know).

So, technically, this field should be blank. Or `-`, or the city name. But none of these options work; not even the city name.

Also side note: The city is called "Autonomous City of Buenos Aires". There's a province called "Province of Buenos Aires". They're different things.

### Steps to reproduce the problem

1. Add some items to your cart.
2. Reach the shipping address phase.
3. Select Argentina as a country.

### What I expected to happen

I should be able to leave `Province` empty, or the value "CABA" ("Ciudad Autónoma de Buenos Aires") should be accepted.

### What happened instead/how it failed

I'm just prompted that the value is not a valid province, and I've no clear way of moving forward.

This may sound like it has a small impact, but about 10% of our countries population lives here (~4M), and a great deal of our potential customers, so it's a big showstopper.

**Comment by patrys** [comment]
Saleor uses [`google-i18n-address`](https://github.com/mirumee/google-i18n-address) which in turn uses data provided by [Google's i18n APIs](http://i18napis.appspot.com/). I'm confused as data for Argentina does contain [Ciudad Autónoma de Buenos Aires](https://raw.githubusercontent.com/mirumee/google-i18n-address/master/i18naddress/data/ar.json) in its list of province choices.

**Comment by primal100** [comment]
The way it works at the moment is they would have to type Ciudad Autónoma de Buenos Aires exactly, which is not intuitive. #1571 would make things a lot easier for the user.

**Comment by WhyNotHugo** [comment]
Google's data doesn't say "provinces", but subdivisions. This city is a top-level subdivision in my country, but isn't a province.
It's kind of odd, but also consider that there are cities out there that don't belong to any country (or province), so, clearly, all those hierarchical rules we think are universal are kinda broken in some cases 😉.

In any case, typing the entire name works (`Ciudad Autónoma de Buenos Aires`). I may have mistyped something the first time, so my report is kinda bogus.

I do agree that #1571 would be awesome (especially since very-long, non-intuitive input is required here), but I'll close this issue since this was my bad up to here.

**Comment by patrys** [comment]
Google does say "provinces" for Argentina, it't not clear from that file alone as `sub_*` is part of its syntax and this file gets merged with a defaults file which defines the `sub_type` if not specified by a country.

The data is correct, as you've both noticed the problem lies with the lack of a proper selection widget (similar problems make it hard to enter a valid address in Ireland). Let's close this and track it as part of #1571.

**Comment by WhyNotHugo** [comment]
Yeah, the thing is that Argentina has 23 provinces and one city, so it's kinda really odd (there not _single_ name for subdivisions, but you'd normally say "provinces", as most subdivisions are just that).

Just responding in case you care to know though, this is off-topic really and this doesn't need to be addressed 🙂

**Comment by patrys** [comment]
We _do_ care as we want to deliver the best i18n experience. If you think any of the data could be improved, we could attempt to open a ticket with Google. For the implementation we take the full blame and with #1571 merged we're now one step closer to something fully usable all around the world.

**Comment by WhyNotHugo** [comment]
Well, TBH, a lot of local sites also have a "province" field and "city" field, and the show `Ciudad Autónoma de Buenos Aires` as province, and then the _only_ option on the city picker is `Ciudad Autónoma de Buenos Aires`.

So, again, usability-wise, with #1571, you're as good as local sites (which I'd argue is great).
