### ISSUE TITLE
Post codes are rejected for Argentina

### ISSUE THREAD

**Issue by WhyNotHugo** [mirumee/saleor#1647]
During the shipping address phase, any valid post codes for Argentina are rejected as invalid.

### What I'm trying to achieve

Trying to complete a checkout (on the demo server).

### Steps to reproduce the problem

1. Add some items to your cart.
2. Reach the shipping address phase.
3. Select Argentina as a country.

### What I expected to happen

Valid post codes should be accepted. Here's a couple of valid ones I got from official government addresses:

* C1015ABO
* C1128ACF
* C1251ADA
* C1288AFD
* C1230ABE
* C1405BWC
* C1406GMP

My home's one is rejected too. As a reference, all post codes in Argentina take the format of:

* One letter for the province / city (that's the [ISO 3166-2:AR](https://en.wikipedia.org/wiki/ISO_3166-2:AR#Current_codes) code.
* Four numbers that narrow down the area.
* Three letters that identify each side of each city block.

### What happened instead/how it failed

Any post code I've tried is rejected. Actually, I tried `1`, and that worked, very oddly (that's SUPER invalid).

**Comment by patrys** [comment]
Which province are you selecting? Postal codes are validated on a province level.

**Comment by patrys** [comment]
I feel that this could be related to #1571?

**Comment by primal100** [comment]
These postcodes work with Ciudad Autónoma de Buenos Aires (the Federal District), but not Buenos Aires (the province). Do you think it's possible for an Argentinian enduser to mix them up?  

Get the latest commit of Saleor, province is now a datalist which should make things easier.

**Comment by WhyNotHugo** [comment]
Yeah, again, my bad.

The demo env run the latest release, rather than master, right?

Thanks, and sorry for the noise!
