### ISSUE TITLE
Mobile version no logo and menu.

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor#1649]
An iPhone it looks like:
![fullsizeoutput_1541](https://user-images.githubusercontent.com/1561204/35213441-ef9e6804-ff5d-11e7-89ff-f5d787da6216.jpeg)

**Comment by dominik-zeglen** [comment]
Tap on 'x' to hide search menu :)

**Comment by maltitco** [comment]
'x' does not work.

**Comment by patrys** [comment]
It looks as if custom CSS/JS was not properly loaded? @dominik-zeglen any ideas?

**Comment by dominik-zeglen** [comment]
Does it happen on https://demo.getsaleor.com/ , or just locally?

**Comment by maltitco** [comment]
On the local as well as on the demo.

**Comment by dominik-zeglen** [comment]
It looks like JS is not executed, but we can't reproduce this bug. We checked on iPhone 6 (iOS 11.2.1 / Safari) and it works okay. 
Can you tell us which model do you use?

**Comment by dominik-zeglen** [comment]
Also please try this branch - https://github.com/mirumee/saleor/tree/fix/storefront-js-refactor - and let us know it it works as intended.

**Comment by maltitco** [comment]
Im tested on iPhone 5c (iOS 10.3.3 / Safari)

**Comment by dominik-zeglen** [comment]
Unfortunately we have no device that can reproduce the bug you encountered and have no clue what we could possibly change, but please feel free to write to us if you manage to fix it.

**Comment by patrys** [comment]
@maltitco Do you have a Mac you could use to remotely debug?

**Comment by maltitco** [comment]
@patrys I checked using the tool in Xcode and the error only occurs in iOS 10.x
I will try to find this bug...
