### ISSUE TITLE
multidict is Python 3 only

### ISSUE THREAD

**Issue by vitaliyterziev** [mirumee/saleor#1654]
pip install -r requirements.txt 

2.7.x will fail because of the pip package, the Saelor official site states that 2.7.x or 3.x can be used?

**Comment by Pacu2** [comment]
I think we've missed something in the docs, as Saleor is 100% Python 2.x free now.  Only Python 3.4+ is supported.

**Comment by vitaliyterziev** [comment]
Ah I see, well here is the link -> https://saleor.readthedocs.io/en/latest/installation.html
Thanks for the quick reply!
![capture](https://user-images.githubusercontent.com/7005255/35230856-e3cb2624-ff9f-11e7-8d76-9dbce655eb9d.PNG)

**Comment by Pacu2** [comment]
Docs were updated, thanks for a good catch!
