### ISSUE TITLE
Password reset view should use SetPasswordForm?

### ISSUE THREAD

**Issue by primal100** [mirumee/saleor#1657]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve

While figuring out how to use templated-email for for the user activation feature, I was trying understand how it worked with Password Reset and some things don't look right.

From looking at the code, I believe the PasswordSetUpForm in saleor/registration/forms.py is not in use. It's set as the set_password_form attribute in the PasswordResetConfirmView however this attribute is unused in Django. set_password_form was part of the old Django function-based auth views which are now deprecated.

The password_reset_view uses the default Django form for password reset, so it is not using templated e-mail which I assume is the intention. So if I understand the intention correctly:

1) The set_password_form = PasswordSetUpForm line in the PasswordResetConfirmView should be removed

2) The password_reset_view should use the PasswordSetUpForm form.

3) The templated_email/account/password_set.email template needs to be created.

This would make things more consistent as far as using templated email for everything (which I now plan to use for the email confirmation feature).

I believe the code is a leftover from the old Django function-based auth views and needs to be updated. Hope I'm understanding correctly.

**Comment by mad-anne** [comment]
Hi @primal100,
you're right and it has been fixed in #1673. ```PasswordSetUpForm``` has been removed as it was unused. Instead ```PasswordResetForm``` was created and we are using it in ```password_reset``` view. It sends e-mail created in ```templated_email /account/password_reset```.
Thank you for your help :) I'm closing this issue.
