### ISSUE TITLE
Sanitize output from the rich-text editor

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1660]
Output produced by the `RichTextEditorWidget` should be sanitized in backend before saving it to the database. The medium-editor used in frontend already does the sanitization, but that doesn't protect us from posting any malicious content manually. I'm not sure if Django provides any sanitization tools, if not, we should use a third-party library.

**Comment by rafalp** [comment]
If we are going to sanitize before saving, we should also consider signing the stored value using item's ID and `SECRET_KEY`, so we can check if wasn't tampered with via, say, malicious sql query aimed to deface the store by changing products descriptions to adult content.

**Comment by patrys** [comment]
What attack vector do you have in mind? Raw SQL access would likely give you access to more data than you could steal by injecting a cross-site script.

**Comment by rafalp** [comment]
It's the damage control for when you were already compromised but attacker decides to do extra harm to your business or reputation by, say, replacing your products descriptions with iframes to adult sites.

**Comment by patrys** [comment]
I believe if your site is compromised and your database contents are replaced, the actual content of your site is the least of your problems as you'll have to shut it down anyway.

**Comment by rafalp** [comment]
Absolutely, but for your brand manger this makes difference between minutes of having store with products renamed to something offensive vs minutes with store which products descriptions contain some graphic stuff, thats far more likely to go viral and harmful for your brand.

**Comment by patrys** [comment]
I see our role as preventing fraud and money loss, not as protection from defacement until the platform we build becomes a viable attack vector. If I have direct access to the database I can do many things including elevating my own user to admin privileges and uploading terrible stuff using the official dashboard's interface.

**Comment by elwoodxblues** [comment]
Do you recommend any sanitizer for Python? [Bleach](https://github.com/mozilla/bleach) seems quite popular.
