### ISSUE TITLE
Product prices disappear in storefront after removing stock locations

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1661]
When removing all stock locations, product prices disappear in the storefront. I think it's a bug, as prices aren't related to stock locations.

**Comment by patrys** [comment]
Many stores work this way, it's a business decision not to disclose previous prices so you don't see them increase after items are restocked.

**Comment by elwoodxblues** [comment]
I've checked in the template and we don't display prices for products that aren't in stock or before their availability date (if set). Was that implemented on purpose? From the customer's point of view, I'd like to know the price of the listed product.

**Comment by patrys** [comment]
I think it's safest not to disclose prices during embargo period. It's probably safe to display the last known price for an out-of-stock product.
