### ISSUE TITLE
Product variants by size+color for example

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#1663]
are possible use Saelor for variants when need more by one group of variants?

for example, T_shirts:
**colors:** black, white, red
**sizes:** M, L, XL 

and different price for every variant ? any plans ?

**Comment by patrys** [comment]
When you edit a product type you can add as many variant attributes as you want (color, size). Then when creating variants you'll be asked to provide a value for each of those attributes.
