### ISSUE TITLE
Storefront as PWA

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#1666]
Since Saleor delivers both RWD and Payment Request (well, almost), I think it is worth considering making it full PWA (https://developers.google.com/web/progressive-web-apps/).

The main problem is offline mode and I believe it would be resolved only when we rewrite whole front-end as single page application in React. It would also require GraphQL API.
I'd like to propose working on making Saleor PWA in two stages:

Online only
- 
The main goal in this phase would be optimizing current Saleor storefront in terms of performance - as latest Lighthouse audit shows, there are some things which we can improve:
<img width="579" alt="zrzut ekranu 2018-01-23 o 17 42 00" src="https://user-images.githubusercontent.com/6833443/35288419-e342e2f8-0064-11e8-921c-4dafd7abecce.png">
I think that it is worth to think about adding image lazy-loaders and optimizing assets' (`.css`, `.js`) size. Also please look at Webpack's code splitting (https://webpack.js.org/guides/code-splitting/) and share your thoughts about it, beacuse I really can't decide whether Saleor could use it or it's not worth it.
Besides pure performance and RWD, application is considered as PWA when it can be "installed" on the device, providing custom splash screen, setting theme colors and caching assets (and maybe some portion of data) in background. It would require serving `manifest.json` and providing service worker, which acts like proxy in offline mode, serving custom connection error page.

Online + Offline
-
In this stage Saleor goes full PWA, getting whole storefront rewritten as single-page application in React, with fully operational API. Going PWA's direction requires moving all filtering / sorting logic to be moved from Python to JS, beacuse of caching reasons. Offline mode should (at least I think) provide interactions with product list, like viewing, sorting, filtering and searching for a specific product. Or maybe someone has better idea?

EDIT actually it is possible to mock GraphQL API by service worker. Maybe this isn't bad idea to cache all products by storing them in IndexedDB, and do all the filtering / sorting things purely by JS in offline mode?

Feel free to share your opinion.

**Comment by elwoodxblues** [comment]
Thanks for the research @dominik-zeglen. Going full offline sounds really exciting, but rewriting the whole storefront to SPA requires a huge effort. I'm not even sure if it should be done in this repository, or maybe a separate one, holding only the front-end application.

Anyway, the online PWA sounds like something that we could start working on right now. Some of the features are really useful, like images lazy-loading - that's something that any e-commerce project would benefit.

**Comment by patrys** [comment]
Please make sure that you're always testing a deployed production site like the demo store and not a locally running development server.

@krzysztofwolski surely has some input related to lazy image loading. Some links we've discussed recently:

* https://jmperezperez.com/svg-placeholders/
* https://jmperezperez.com/medium-image-progressive-loading-placeholder/

We could also embrace HTTP/2 and split our CSS and JS.

**Comment by krzysztofwolski** [comment]
- I would love to have offline navigation over visited pages
- download data for next results page in categories in background would be insane: instant page changes and more stable expirience for mobile users in ex subway
- notifications for order changes. And only that. If application notify me about some sale crap, it lands in trash bin

**Comment by Pacu2** [comment]
Lazyload can be implemented independently as long as we are talking about lazy loading images, not preloading images and storing in users device(which is great benefit of using PWA)

AFAIK we are serving `manifest.json` but it's not really customized, probably build-in webpack feature

New trend is in inlining critical (above the fold) CSS, which speeds up first paint on the mobile ('Reduce render-blocking stylesheets') - there's no django implementation that's capable of performing it at this moment, however [critical](https://github.com/addyosmani/critical) written in JS works great, would love to see it in Saleor.

**Comment by krzysztofwolski** [comment]
@patrys for product images in saleor based purposes I'm fan of pinterest approach:
- after img is uploaded find its most significant color and use it for placeholder background
- use progressive JPEG

Why not svg placeholder? Or blurred thumb? I think its overcomplicated. It is placeholder in web shop not AAA game.
Why not webp, Its smaller!? Yes, but for fast connections it make no difference for user to wait 50 ms more for loading image, but for slow connections progressive loading show meaningful information faster

**Comment by krzysztofwolski** [comment]
Also, moving into PWA means `mobile saleor app` checkbox done. Thats huge.

**Comment by patrys** [comment]
@krzysztofwolski With offline support a blurred thumb gives much more information than a background color. Also background colors do not work well with images that have a single color backdrop as the end result is a large purple square that gets replaced with a small purple shape on white background.

**Comment by elwoodxblues** [comment]
PR #1709 partially deals with the issue as it adds bare minimum to treat storefront as an "online PWA". I'd like to keep it open and get back to it once we start refactoring the storefront in the future.

**Comment by shadiakiki1986** [comment]
Thanks for the great effort! I'm trying to mirror my saleor site with `wget -mk https://my-saleor-site`, but wget isn't downloading the images because they're lazy-loaded. Is there any config setting that I can flip to disable lazy loading of images? e.g. a webpage setting such that `npm build-assets` no longer lazy loads images?

**Comment by shadiakiki1986** [comment]
Using jquery as I had suggested above doesn't work with wget because it doesn't trigger javascript code.

What I did instead was install the [nginx substitution filter](https://www.nginx.com/resources/wiki/modules/substitutions/) (I'm serving the saleor site through nginx), replace all `data-src` with `src` with the following addition to the `location` tag in nginx

```
      # substitute data-src with src to avoid image lazy-loading
      subs_filter_types text/html;
      subs_filter data-src src;
```

and then just re-run the same `wget -mk ...` command. That disabled all the lazy-loading and got wget to download all the product images.

**Comment by maarcingebala** [comment]
I think we can close this issue since we have [saleor-storefront](https://github.com/mirumee/saleor-storefront). 🙂
