### ISSUE TITLE
In the DummyProvider workflow, two Payments are created for the same Order

### ISSUE THREAD

**Issue by tonylampada** [mirumee/saleor#1671]
I'm trying to create a payment provider for Pagseguro (a popular payment gateway here in Brazil), and I'm looking at the implementation of `dummy.payments.DummyProvider`.

I can debug this code and I notice that `DummyProvider.get_form` can be called twice: One time before the user sees the payment form, and another time after the user submits the payment form with the CONFIRMED status.

![image](https://user-images.githubusercontent.com/218821/35333305-69dd745a-00f5-11e8-8dca-a5da648fa662.png)

Both times, this method gets a `payment` instance. I expected this payment instance to be the same on both calls (*the payment* for that order), but saleor is creating a different payment instance to give to `DummyProvider.get_form`

This seems to be happening on `saleor.order.views.start_payment`, when it's calling `Payment.objects.get_or_create` (line 95 below)

![image](https://user-images.githubusercontent.com/218821/35333556-48740580-00f6-11e8-8f07-0b1bc27a1864.png)

The second time, we're also passing the `status=PaymentStatus.WAITING` parameter to that function, but the payment status was already changed to PaymentStatus.INPUT the first time, so `get_or_create` ends up "creating" instead of "getting".

I'm still not very familiar with saleor, so I'm not sure if this is correct behaviour, but it kinda looks like a bug.

**Comment by maarcingebala** [comment]
Doesn't happend on master anymore after latest payments refactoring.
