### ISSUE TITLE
Consider moving dashboard templates and static files into the dashboard directory

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#1679]
Currently all dashboard templates live together with storefront templates and all dashboard JS files live alone the storefront JS files. This results in translation resources for dashboard being bundled together with storefront. It also impacts IDE features such as "find all occurrences" where a person seeking to customize the storefront has to manually filter out results from the dashboard.

**Comment by elwoodxblues** [comment]
+1 for this. Dashboard and storefront are separate apps and we should also reflect that in the structure of code.

**Comment by maarcingebala** [comment]
We're going to move the entire old dashboard to a separate project most probably (we'll open a new issue for that).
