### ISSUE TITLE
Question about locales

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1686]
Hi!

I saw multiple times sentences containing the character `&` were translated from and to `&amp;` (sometimes `&amp`) [[ex1](https://i.imgur.com/ohh00oM.png), [ex2](https://i.imgur.com/QuqlqPN.png)]. Since Jinja2 is already escaping the characters it renders the text to `Hello &amp; World` instead of `Hello & World`.

![pic](https://i.imgur.com/WyMXd9F.png)

So, my question is: shouldn't we replace the `&amp[;]` by `&`?

**Comment by patrys** [comment]
You are right, these should not include HTML entities.
