### ISSUE TITLE
python: can't open file 'manage.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by umang-t-patel** [mirumee/saleor#1689]
After building docker. When we run below command
`docker-compose run web python manage.py migrate`
It creates containers for redis, search and db. But then it gives below error.

> python: can't open file 'manage.py': [Errno 2] No such file or directory
Am I missing something?
![screenshot 90](https://user-images.githubusercontent.com/23641343/35477590-1b7b7158-0394-11e8-8d5a-7836f2792af5.png)

**Comment by flame0** [comment]
Same promlem on Win 8.1
