### ISSUE TITLE
Issue installing Saleor in Windows 10

### ISSUE THREAD

**Issue by mithundeybd** [mirumee/saleor#1690]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve

I'm  trying to install Saleor locally on my PC to develop. It is a Windows 10.

### Steps to reproduce the problem

1.python manage.py migrate
2.

### What I expected to happen

Install the DB and other settings

### What happened instead/how it failed

django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

(Please include a stack trace if this problem results in a crash.)

**Comment by patrys** [comment]
Which version of Python are you using? Are you using a virtualenv? Could you provide the output of `python -m pip freeze`?

**Comment by mithundeybd** [comment]
I'm using 'python3'.
![image](https://user-images.githubusercontent.com/35906731/35525843-ebd9e700-054f-11e8-956a-b3c655a37b32.png)
![image](https://user-images.githubusercontent.com/35906731/35525862-fbdeb180-054f-11e8-84f4-cd5587aa577a.png)
![image](https://user-images.githubusercontent.com/35906731/35525891-09c8d5b4-0550-11e8-8abf-07d7046ce46b.png)

**Comment by patrys** [comment]
Did you install the requirements using `python -m pip install -r requirements.txt`? Some of the versions are different to the ones we ship in `requirements.txt`.

**Comment by mithundeybd** [comment]
Some of them are not install from the 'requirements.txt' then I install manually.

**Comment by patrys** [comment]
One of the important differences is that you are running Django 2.0 which is a version Saleor does not support yet because of some of our third party dependencies. You can try using the 1.11 branch and see if this fixes your problem.

**Comment by mithundeybd** [comment]
Issue resolved by using old Djengo 1.9.1. Thanks @patrys

**Comment by alexmzirai** [comment]
awesome....I just faced this issue like 5 minutes ago and now i'm sorted. Thanks :)

**Comment by patrys** [comment]
@alexmzirai Please note that Saleor does work with Django 2.0 now so you should not have to manually downgrade to 1.x.

**Comment by desperado54** [comment]
does it work with python 3.6.5?

**Comment by alexmzirai** [comment]
Yes.

On 19 Jun 2018 17:33, "desperado54" <notifications@github.com> wrote:

does it work with python 3.6.5?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mirumee/saleor/issues/1690#issuecomment-398420845>, or mute
the thread
