### ISSUE TITLE
Using "account" name in the registration app.

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1743]
Templates for the `registration` app sit in the `account` directory, also the name `account` is used in URLs. Is there some purpose behind it or is just an inconsistency? I'd rather follow the convention and rename URLs and template directory to `registration`.

**Comment by patrys** [comment]
There's also `userprofile`, maybe registration should be merged into that?

**Comment by elwoodxblues** [comment]
I was thinking about that too, actually. If I was writing these apps today from scratch, I wouldn't divide them into separate ones. The structure would be definitely cleaner.

**Comment by mad-anne** [comment]
We could create an ```account``` app and and merge into it ```userprofile``` and ```registration``` apps. Then all related URL's would start with ```/account``` and templates would live in an ```account``` directory, which fits both apps functionality and keeps consistent naming.

**Comment by patrys** [comment]
`account` sounds good. The current name predates custom User models in Django. Back then there had to be a `OneToOne` profile model for each user hence the `userprofile` name.
