### ISSUE TITLE
Link our others packages in the saleor readme

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#1753]
Saleor uses many of our other libraries (ex. prices). What do you think @elwoodxblues to list them in new section in the readme?

**Comment by elwoodxblues** [comment]
I'm not sure, I think open-source projects usually don't do this, as those who are interested will find other packages on our Github profile anyway. But if others agree, I won't block this. What do you think @patrys?

**Comment by patrys** [comment]
We could mention the pricing types under architecture once we move to prices 1.x but I'd rather avoid marketing in docs.

**Comment by maltitco** [comment]
Who will want to know what the saleor uses will check the requirements.txt
For other users this will be unnecessary and will only add unnecessary work to the team.
