### ISSUE TITLE
Storefront navigation app

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1755]
There's an idea to add an app for managing the storefront navigation menus. Here is a draft of models that we could use:

```
Menu:
  slug

MenuItem:
  menu (foreign key)
  name
  sort_order
  url
```

Once defined, a menu would be referenced in templates with a template tag:
```
{% get_menu <slug> as menu %}
{% for item in menu %}
  <li><a href="{{ item.url }}">{{ item.name }}</li>
{% endfor %}
```

The above idea covers flat menus, but if we wanted to add the ability to define dropdowns, we could use MPTT for menu items.

**Comment by patrys** [comment]
I'm sold on the idea of having a menu editor. I think most stores use at least two levels of navigation though so a flat structure may not cut it.

I'm 👎 on moving the logic to templates though. It's the controller's job to query the model layer.

**Comment by elwoodxblues** [comment]
So we should use MPTT for menu items. Instead of a template tag we can use a context manager, as menus will be accessed in most of the storefront views.

**Comment by elwoodxblues** [comment]
I forgot to mention, that in the dashboard we'll need a management view, that will make it easy to add menu items, by selecting from existing categories, collections or adding custom links.
