### ISSUE TITLE
Bulk add products to collection

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#1756]
In order to make creating collections simpler, there should be a "Add to collection" bulk action in the product list dashboard view. After selecting this option a modal should pop up with a form to select one collection from the list of existing ones.

**Comment by patrys** [comment]
This would be much easier to implement if the view was a React one. We could even allow a new collection to be created.

**Comment by elwoodxblues** [comment]
We decided to hold this until we have more React views in the dashbaord.

**Comment by maarcingebala** [comment]
Will be implemented as part of #3537.
