### ISSUE TITLE
API integration with shipping providers

### ISSUE THREAD

**Issue by tonylampada** [mirumee/saleor#1763]
I'm starting to play with saleor a bit to put together an e-commerce platform.

I'm looking at how shipment pricing is implemented and it's not flexible for most cases in e-commerce in Brazil - here we normally need to use a third party api from correios.com.br (or another shipping provider) to tell the buyer the shipping price.

I've implemented something like this in my local copy of saleor, more or less along the lines of this patch here: https://github.com/lanceotimo/saleor/blob/master/0001-Enfiar-uma-regra-de-shipping-price-arbitraria.patch

If this feature is something that is desired for this official repository, I'd be happy to submit this in the form of a proper PR - although I would probably require some back and forth communication with some of you guys before the implementation meets your standards.

**Comment by elwoodxblues** [comment]
Hey @tonylampada, adding an integration with shipping carriers is on our current [roadmap](https://github.com/mirumee/saleor/projects/6), but I can't tell you yet when we'll start working on this, as we have other priorities right now. We'd have to come up with a generic solution that will make it easy to add other carriers as well. A pull request is welcomed, but I can't assure you when and in what form we'll be able to merge it into Saleor.

**Comment by JPilarr** [comment]
i would like make something like integration system with Shipping carriers. i would like know some requirements for right pull request.

**Comment by NyanKiyoshi** [comment]
@JPilarr I believe you could just create a new branch in your fork, open a PR and commit as you go. Then whenever we get time, we will get to review and give suggestions as you go forward in the implementation.

**Comment by mayank-budhiraja** [comment]
Yes, I am also trying to find a work around this.

**Comment by laf0rge** [comment]
I wonder how anyone is able to operate any webshop / e-commerce website without integration with shipping APIs.  Either directly with UPS/FedEx/DHL/... or indirectly via re-sellers like parcel monkey etc.

It's of course clear that the "core" of the ecommerce system is unlikely to be able to implement and maintain integrations with all those different APIs.

But at the very least, the "core" should be offering an API by which anyone can implement their various shopping provider API integrations.  Has this really still not beein implemented?  I reallly cannot believe that anyone can operate a webshop without suhc an essential feature.

**Comment by havardox** [comment]
Any updates on this?

**Comment by risalfajar** [comment]
Please reopen this issue
