### ISSUE TITLE
Refactor Order and Cart models

### ISSUE THREAD

**Issue by akjanik** [mirumee/saleor#1764]
While working with Saleor, I've noticed `Cart` and `Order` models have some method (e.g. `create_history_entry`, `send_confirmation_email`, `change_status`), that could be moved to proper forms or utility functions.

**Comment by elwoodxblues** [comment]
I think `create_history_entry` is not very useful and could be dropped at all. `change_status` contains a note that it could be replaced with FSM which may be worth considering. `send_confirmation_email` should be also dropped at all and instead functions from order/emails.py should be used directly instead.
