### ISSUE TITLE
Improve order fulfillment process.

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1767]
When an order is placed it shouldn't be divided into separate delivery groups, as it complicates the order management UI in the dashboard. A proposition of changes:
- don't split an order during checkout
- introduce fulfillment view, where the user will determine how many items of each order line should be fulfilled
- allow for multiple fulfillments

**Comment by elwoodxblues** [comment]
@mad-anne Could you upload the DB schema that you were working on? We could also discuss here what actions/functions/API will be required.

**Comment by mad-anne** [comment]
Here is proposed DB schema:

![fulfillment](https://user-images.githubusercontent.com/20802901/36060930-04c9d1ec-0e53-11e8-8652-541b29175b5c.png)
