### ISSUE TITLE
How should I contribute translations if I don't use Transifex?

### ISSUE THREAD

**Issue by tiberiuichim** [mirumee/saleor#1774]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve

Easy workflow for developing my own translations, inside my own copy of the development stack

### Steps to reproduce the problem

Let's say I'm a developer, running my test site straight from saleor/master. The translations on Transifex are out of sync of the master, so I need to generate my own .pot files and run the locales extraction myself, and then use poedit to have my own translation. This, as I have been doing it for the last 2 months, is not optimal: on every merge with the HEAD on master, I have to reset the translation files, as they are way out of line.

On Transifex there are 2 po files. We have 3 po files when generating locales. Yet another problem. The naming of the domains is different: django, djangojs instead of storefront/javascript.

### What I expected to happen

Clear instructions and maybe a script how to contribute a local .po file to transifex.

### What happened instead/how it failed

...

(Please include a stack trace if this problem results in a crash.)

**Comment by patrys** [comment]
Saleor comes with [config files](https://github.com/mirumee/saleor/tree/master/.tx) for the Transifex command-line client. For merging translations I recommend using the standard gettext tools as they can merge newly added strings into an already existing translation. For simple changes you should be able to use Django's `makemessages` command:

```console
$ python manage.py makemessages -l en
$ python manage.py makemessages -l en -d djangojs --ignore=_build/\* --ignore=node_modules/\* --ignore=saleor/static/assets/\*
```

**Comment by tiberiuichim** [comment]
Cool, I didn't know about the transifex command line tool. Yes, I've been regenerating my own locales with makemessages. Thanks!
