### ISSUE TITLE
All Email Templates are not found

### ISSUE THREAD

**Issue by jamespsteinberg** [mirumee/saleor#1783]
On both a local install and heroku push after cloning, emails are sent with no body because they all quietly raise a TemplateDoesNotExist exception.

It appears to be for all emails. So far I have tested it with:
Password Reset
Order Confirmation
Payment Confirmation

```
django.template.exceptions.TemplateDoesNotExist: templated_email/compiled/confirm_payment.html
```

The templated_email/compiled folder is never created

**Comment by NyanKiyoshi** [comment]
Did you compile the emails?

```bash
npm run build-emails
```

**Comment by patrys** [comment]
I see this is missing from the Docker part of our docs.

**Comment by jamespsteinberg** [comment]
npm run build-emails fixes this and #1782

**Comment by jamespsteinberg** [comment]
For anyone else on Heroku,

you have to run 
```
Heroku run bash
npm run build-emails
```

Heroku run npm run build-emails will not work

**Comment by jamespsteinberg** [comment]
How do I run this on Heroku? Or should I run this and then commit the compiled html files before pushing?

**Comment by elwoodxblues** [comment]
We'll update the Heroku config to build the emails automatically. To build them manually try running:
`heroku run npm run build-emails`.

**Comment by patrys** [comment]
Heroku does not persist `heroku run` changes in the slug (as it spins up a new worker for the command) so the only way to make persistent changes is to add `npm run build-emails` to the `heroku-postbuild` script in `package.json`.
