### ISSUE TITLE
Load new folder in static folder

### ISSUE THREAD

**Issue by Bjorninn1** [mirumee/saleor#1789]
When I add a file to static/images I can reference the file, but if I create a folder called fonts: static/fonts and add the same file to it, the file is not found in the browser.

I have tried "npm run build-assets" and cleared Cached images and files in the browser but the font file is still not found.

Works:

`<link href="{% static 'images/font-awesome.css' %}" rel="stylesheet" type="text/css">`
 
Does not work:

`<link href="{% static 'fonts/font-awesome.css' %}" rel="stylesheet" type="text/css">`

Any idea how to make new folders load into static files?

**Comment by patrys** [comment]
All static files are handled by Webpack. Image folder is referenced as-is while CSS files are compiled through JavaScript entry points referenced in `webpack.config.js`. I suggest that you modify the `storefront.js` or `storefront.scss` to reference your font instead of adding to templates manually.

**Comment by Bjorninn1** [comment]
Thanks, but is it possible to have a specific css file for each template using the webpack? It looks like the webpack packs all css files at once for all templates.

**Comment by ankittyagi20** [comment]
I have a similar issue, I made some changes in storefront.css, ran `npm run build-assets` however, the css is not getting reflected. Even I removed the saleor/static/assets folder and rebuilt it still I see the old styling/css being loaded. Any ideas what might be wrong or I'm missing something?
