### ISSUE TITLE
Footer late to show up at bottom of page

### ISSUE THREAD

**Issue by Bjorninn1** [mirumee/saleor#1790]
When loading this demo page: https://demo.getsaleor.com/cart/

the gray footer is shown for a short moment a bit above the bottom of the page, then it pops to the bottom, is there possibly any way to prevent this? For example by loading the footer before loading the more heavy stuff that might be causing the lagging?

**Comment by patrys** [comment]
It seems the problem is that the empty card placeholder image does not have its size specified. We should require sizing for all images to avoid browser having to readjust the layout (which also leads to annoying jumping if you scroll before all images load).

**Comment by Bjorninn1** [comment]
Yes, thanks.
