### ISSUE TITLE
Order confirmation email doesn't show discounts

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1793]
When ordering a discounted product, I discovered the discount was shown in the order details from the frontstore but was not sent in the order confirmation email.

Shouldn't we add it before the total?

![](https://i.imgur.com/AT57SSN.png)

**Comment by patrys** [comment]
I also find it weird that total net does not come before tax in the summary.

**Comment by NyanKiyoshi** [comment]
True! But this one is from my changes, it wasn't a mail from the master branch of saleor.
