### ISSUE TITLE
Trying to Integrate COD

### ISSUE THREAD

**Issue by dhruvramdev** [mirumee/saleor#1800]
I am trying to integrate Cash on Delivery and A Local Payment Gateway (Native in India). Currently Saleor uses Django Payments. Any help or guide how to achieve the same.

Any Community Plugin will also do. Although I was not able to find one

**Comment by maltitco** [comment]
COD waiting for merging: https://github.com/mirumee/django-payments/pull/152

**Comment by shadiakiki1986** [comment]
Check [django-payments-cod](https://github.com/xtranophilist/django-payments-cod) linked from [here](https://github.com/mirumee/saleor/issues/1110#issuecomment-372625250)
