### ISSUE TITLE
Products only show up if mapped to immediate category

### ISSUE THREAD

**Issue by MChiciak** [mirumee/saleor#1802]
### What I'm trying to achieve
When clicking on a category, I want to see all products in the hierarchy.  If a product is mapped to category "brakes" which is mapped to category "auto parts", I expect to see my product when clicking "auto parts"
...

### Steps to reproduce the problem

1.  Create two categories, one parent and one child
2.  Map a product to the child
3.  When going to the storefront, go to product list for the parent.  You should see the product mapped, but it does not show up because the filter only applies to the direct category, not descendants.

### What I expected to happen
I expect the products to show up in descendant categories, not just the category in the URL param.
...

### What happened instead/how it failed
Product list was empty

### File with problem ###
https://github.com/mirumee/saleor/blob/master/saleor/product/views.py
category_index function is filtering like so:
 products = products_with_details(user=request.user).filter(category__id=category.id).order_by('name')

In older versions of saleor, it used to filter like this:
 products = products_with_details(user=request.user).filter(category__in=[category] + list(category.get_descendants())).order_by('name')

**Comment by Pacu2** [comment]
I think same problem was listed in #1786
AFAIK it should be resolved in current sprint

**Comment by elwoodxblues** [comment]
As @Pacu2 mentioned, we already have a ticket for that and we're going to have it fixed in the next release.
