### ISSUE TITLE
GraphQL error when filtering on attributes

### ISSUE THREAD

**Issue by MChiciak** [mirumee/saleor#1803]
### What I'm trying to achieve
Attribute filtering on storefront product list page

### Steps to reproduce the problem

1.  Visit https://demo.getsaleor.com/products/category/groceries-2/
2.  Open chrome debugger->network tab
3. Click 100g under box size
4. An error returns inside response
{"errors":[{"message":"Cannot combine a unique query with a non-unique query."

### What I expected to happen
Products should be filtered down by attributes
If an error occurs, perhaps an error message should be shown to the user so they know their filter failed

### What happened instead/how it failed
The same products returned with an error inside of graphQL

### Error from browser ###
{"errors":[{"message":"Cannot combine a unique query with a non-unique query.","locations":[{"line":29,"column":3}]}],"data":{"category":{"pk":"2","name":"Groceries","url":"/products/category/groceries-2/","ancestors":[],"children":[],"products":null,"__typename":"CategoryType"},"attributes":[{"id":"UHJvZHVjdEF0dHJpYnV0ZVR5cGU6OA==","pk":"8","name":"Box Size","slug":"box-size","values":[{"id":"UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjE1","name":"100g","slug":"100g","color":"","__typename":"ProductAttributeValue"},{"id":"UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjE2","name":"250g","slug":"250g","color":"","__typename":"ProductAttributeValue"},{"id":"UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjE3","name":"500g","slug":"500g","color":"","__typename":"ProductAttributeValue"},{"id":"UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjE4","name":"1kg","slug":"1kg","color":"","__typename":"ProductAttributeValue"}],"__typename":"ProductAttributeType"},{"id":"UHJvZHVjdEF0dHJpYnV0ZVR5cGU6NA==","pk":"4","name":"Brand","slug":"brand","values":[{"id":"UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjc=","name":"Saleor","slug":"saleor","color":"","__typename":"ProductAttributeValue"}],"__typename":"ProductAttributeType"},{"id":"UHJvZHVjdEF0dHJpYnV0ZVR5cGU6Ng==","pk":"6","name":"Candy Box Size","slug":"candy-box-size","values":[{"id":"UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjEw","name":"100g","slug":"100g","color":"","__typename":"ProductAttributeValue"},{"id":"UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjEx","name":"250g","slug":"250g","color":"","__typename":"ProductAttributeValue"},{"id":"UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjEy","name":"500g","slug":"500g","color":"","__typename":"ProductAttributeValue"}],"__typename":"ProductAttributeType"},{"id":"UHJvZHVjdEF0dHJpYnV0ZVR5cGU6Nw==","pk":"7","name":"Coffee Genre","slug":"coffee-genre","values":[{"id":"UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjEz","name":"Arabica","slug":"arabica","color":"","__typename":"ProductAttributeValue"},{"id":"UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjE0","name":"Robusta","slug":"robusta","color":"","__typename":"ProductAttributeValue"}],"__typename":"ProductAttributeType"},{"id":"UHJvZHVjdEF0dHJpYnV0ZVR5cGU6NQ==","pk":"5","name":"Flavor","slug":"flavor","values":[{"id":"UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjg=","name":"Sour","slug":"sour","color":"","__typename":"ProductAttributeValue"},{"id":"UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjk=","name":"Sweet","slug":"sweet","color":"","__typename":"ProductAttributeValue"}],"__typename":"ProductAttributeType"}]}}

**Comment by elwoodxblues** [comment]
Thanks for reporting. We're currently working heavily on the API so this should be fixed soon.

**Comment by MChiciak** [comment]
No problem, love what your team is doing.

I am still going to use demo as my base, i will work around the problem for
now.

**Comment by elwoodxblues** [comment]
This issue has been already resolved.
