### ISSUE TITLE
Blank screen when selecting product type for add product

### ISSUE THREAD

**Issue by MChiciak** [mirumee/saleor#1806]
### What I'm trying to achieve
Create a new product, selecting from 2 different product types

### Steps to reproduce the problem
On Demo branch/Windows OS

1.  Create two product types, one with variants one without
2.  Go to add product, click plus button
3.  Select a product type
4.  You will see a blank screen modal that just says "cancel"
5.  If using chrome dev tools, you can see the redirect was returned in JSON but nothing triggered in the browser.

### What I expected to happen
The new product page should have opened

### What happened instead/how it failed
The modal remained with just a blank screen with a cancel button

**Comment by elwoodxblues** [comment]
I'm using latest master and can't reproduce it. Are you sure your static assets compiled without any errors (`npm run build-assets`)? Does the JS or Python console say anything?

**Comment by MChiciak** [comment]
Sorry, forgot to mention this is on the demo branch and on windows.  No js errors returned either.

**Comment by maarcingebala** [comment]
Hmm, it does work for me. Have you tried doing a hard refresh in your browser? Maybe something got cached and it's breaking the view.

**Comment by turdiyev** [comment]
@maarcingebala I tried chrome incognito mode as well. same error.

**Comment by NyanKiyoshi** [comment]
@turdiyev, hi, could you run this command inside the saleor's directory:
```
node_modules\.bin\webpack -pd
```

This will compile non-minified javascript sources. Then, get back in your browser, hard refresh (`CTRL+SHIFT+R`), open your console, reproduce the issue and retrieve the error. That would really help us! 👍

**Comment by turdiyev** [comment]
@NyanKiyoshi hello. I will try ASAP, but not now. (Sorry for that). 

BTW, this error occurred https://demo.getsaleor.com/dashboard/next/products/add site.

Not on the localhost, I didn't run in my machine yet.

**Comment by turdiyev** [comment]
@NyanKiyoshi here you are:
```
react-dom.production.min.js?ca5d:179 TypeError: Cannot read property 'name' of undefined
    at getAttributeName (ProductOrganization.tsx?c895:102)
    at eval (ProductOrganization.tsx?c895:220)
    at Array.map (<anonymous>)
    at eval (ProductOrganization.tsx?c895:216)
    at sg (react-dom.production.min.js?ca5d:156)
    at yg (react-dom.production.min.js?ca5d:169)
    at fh (react-dom.production.min.js?ca5d:204)
    at gh (react-dom.production.min.js?ca5d:205)
    at Jh (react-dom.production.min.js?ca5d:220)
    at Kh (react-dom.production.min.js?ca5d:219)
```
ProductOrganization.tsx?c895:102 image: 
https://imgur.com/a/DCPsNbr

after following command:
`node_modules/.bin/webpack -pd`
