### ISSUE TITLE
Nonexistent voucher code form crashes when invalid

### ISSUE THREAD

**Issue by rafalp** [mirumee/saleor#1808]
When voucher code for nonexistent voucher is entered on checkout, checkout form crashes, not displaying at all. Here's how it looks like at Saleor's demo:

<img width="454" alt="zrzut ekranu 2018-02-20 o 17 53 36" src="https://user-images.githubusercontent.com/750553/36437343-0277eb9c-1667-11e8-8f2d-87a0eecfe22a.png">

When running Saleor with `DEBUG = True`, Error 500 is produced instead:

<img width="675" alt="zrzut ekranu 2018-02-21 o 10 13 41" src="https://user-images.githubusercontent.com/750553/36471770-f80cdbfc-16ef-11e8-90e8-b583a2740135.png">

Investigating this, I've found that this is caused by the erroneous `default_error_messages` where `pgettext_lazy` is wrapping other `pgettext_lazy`:

```
class VoucherField(forms.ModelChoiceField):

    default_error_messages = {
        'invalid_choice': pgettext_lazy(
            'voucher', pgettext_lazy(
                'Voucher form error', 'Discount code incorrect or expired')),
    }
```

This feels simple fix enough, but the scenario feels important enough for new tests to be added to our tests suite.

**Comment by NyanKiyoshi** [comment]
Oh that's quite interesting. I tried to reproduce it on January release but it doesn't have the issue.
Is there a missing test for this feature? I'm pretty surprised the unit tests didn't catch this bug.
