### ISSUE TITLE
ImportError: cannot import name SubfieldBase

### ISSUE THREAD

**Issue by olahivepriyanka** [mirumee/saleor#1810]
i am trying to install saleor , when i run `python manage.py migrate
`  it is giving this error`
from django.db.models import SubfieldBase
ImportError: cannot import name SubfieldBase
`
i have **Django (1.11.10)**.. i read in some posts SubfieldBase support for Django (1.11.10) is deprecated. what do we need to do in this case?

i am unable to migrate the db. please help me

**Comment by The-Nightwing** [comment]
How did you solve this? @olahivepriyanka
