### ISSUE TITLE
AttributeChoiceValue, slug field max length is much less than max length of name field

### ISSUE THREAD

**Issue by MChiciak** [mirumee/saleor#1814]
Branch: Master

### What I'm trying to achieve
Adding an attribute value that is longer than 50 characters (max allowed is 100)

### Steps to reproduce the problem

1.  Add an attribute choice value of greater than 50
2.  The slug field will throw a constraint error because it defaults to only 50

### What I expected to happen
Slug field should match length of name field

### What happened instead/how it failed
Constraint DB error gets thrown

django.db.utils.DataError: value too long for type character varying(50)

**Comment by MChiciak** [comment]
Other models like category have similar problem.   Since slug is based off name and really just lowercases and hyphenates spaces, we will have constraint issues.

name = models.CharField(max_length=128)
slug = models.SlugField(max_length=50)

**Comment by elwoodxblues** [comment]
We should go over all models and update slug fields so that the `max_length` matches with the length of a field that the slug is based on.

**Comment by elwoodxblues** [comment]
Should be fixed by #1835
