### ISSUE TITLE
slash making month selection disabled using braintree

### ISSUE THREAD

**Issue by Bjorninn1** [mirumee/saleor#1816]
in the file credit_card_expiry_widget.html the line:

      <span class="text-center align-bottom position-absolute w-100 checkout__payments-card-expiry-slash"> /</span>

makes the month not possible to select in the template: 

![screen shot 2018-02-22 at 01 06 50](https://user-images.githubusercontent.com/10634922/36514763-05419276-176e-11e8-8d7a-eb723e4ce193.png)

It can be fixed by removing the "/" so the line looks like this:
      
     <span class="text-center align-bottom position-absolute w-100 checkout__payments-card-expiry-slash"> </span>

![screen shot 2018-02-22 at 01 09 03](https://user-images.githubusercontent.com/10634922/36514782-1fd0ee20-176e-11e8-8782-f99a2e2065b6.png)

I just wanted to point this out, but I don´t know if this affects behavior or desired look in the templates for other providers.

**Comment by elwoodxblues** [comment]
Thanks for pointing that out. I think we should remove the slash from the markup.

**Comment by patrys** [comment]
I think the problem is with styling. The slash is there on credit cards so I'd prefer to keep it in the form as well.
