### ISSUE TITLE
Blockquote tag not rendering properly in rich-text field

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1824]
The `blockquote` tag used in the rich-text seems as unsupported in the storefront, as it lacks any styling that would differentiate the quote from the rest of the text. I think the basic blockquote styling from Bootstrap would work.

Example

Dashboard:
![image](https://user-images.githubusercontent.com/5421321/36679230-fe64aa58-1b12-11e8-8161-927488ac652b.png)

Storefront:
![image](https://user-images.githubusercontent.com/5421321/36679255-0cdd6e9e-1b13-11e8-9972-5f0b87b318ac.png)

**Comment by dominik-zeglen** [comment]
Or maybe something like this instead of default Bootstrap's style?
<img width="479" alt="zrzut ekranu 2018-03-01 o 15 23 29" src="https://user-images.githubusercontent.com/6833443/36849507-888eef4c-1d64-11e8-898f-8ab46a580487.png">

**Comment by elwoodxblues** [comment]
LGTM
