### ISSUE TITLE
npm run build-assets --production is broken under ubuntu 16.04 server

### ISSUE THREAD

**Issue by xponrails** [mirumee/saleor#1826]
Hi all.

When I try to run `npm run build-assets --production` in my staging server, the build fails when tries to build materialize-css fonts.
Below the stack:
```
ERROR in /webapps/ecommerce/saleor/shared/node_modules/materialize-css/dist/fonts/roboto/Roboto-Thin.woff2
    Module parse failed: /webapps/ecommerce/saleor/shared/node_modules/materialize-css/dist/fonts/roboto/Roboto-Thin.woff2 Unexpected character '' (1:4)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ /webapps/ecommerce/saleor/shared/node_modules/css-loader?{"sourceMap":true}!/webapps/ecommerce/saleor/shared/node_modules/postcss-loader/lib?{"sourceMap":true,"plugins":[null]}!/webapps/ecommerce/saleor/shared/node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./saleor/static/dashboard/scss/dashboard.scss 6:62480-62542
cd /webapps/ecommerce/saleor/current && npm run build-assets --production stderrnpm ERR! code ELIFECYCLE
```
The same stack for all fonts inside materialize-css project.

It seems to try to open the file using sass-loader instead of file-loader.

In my osx development machine all works as expected.

I'm using node 8.9.0 and npm 5.6.0

I'm missing some package?

Thanks for your help.

**Comment by maltitco** [comment]
You tried to reinstall npm?

**Comment by xponrails** [comment]
Yes, I've changed also Nodejs version.

**Comment by EduardoZepeda** [comment]
I encountered the same problem but with phantomjs in digital ocean, it looks like the low RAM in my droplet was causing the problem, I didn't upgrade it though. I know maybe the solution is not the best but you can always build your production assets in your development machine and simply replace the files, along with the webpack-bundle.json file(the one that is generated after you run `npm run build-assets`), in your production server.

**Comment by Pacu2** [comment]
I think this is resolved by now.
