### ISSUE TITLE
[Information needed] Customer deletion

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1828]
Hello,

I just saw and searched to discover that there is no mechanism inside saleor to delete a customer (if I'm not wrong at least).

- Would it be possible to fully and safely delete a customer? (by deleting its row in cascade in the database);
- Would you plan to add (at least) an option for the staff members to delete a customer or give the customer a way to request its account and data deletion? (with a few days to wait of course).

The main issue is that from the European law (the [Right to erasure](https://gdpr-info.eu/art-17-gdpr/)), we must be able to delete the data about a user in its entirety.

Thank you in advance for your answers!

**Comment by elwoodxblues** [comment]
We're going to address the GDPR requirements in Saleor so removing the customer will have to be implemented in some way. Right now the `Order` model has a nullable reference to `User` so removing an account shouldn't break the order history.

**Comment by NyanKiyoshi** [comment]
Sounds good and great to me. Thank you for the answer!
