### ISSUE TITLE
Cybersource Payments

### ISSUE THREAD

**Issue by austineinstein** [mirumee/saleor#1829]
I am trying to turn my saleor project to be production ready which is hosted on heroku

I have ran this " heroku config:set DEBUG=`false` "

<img width="855" alt="screen shot 2018-02-26 at 21 06 04" src="https://user-images.githubusercontent.com/12557036/36753474-27dcea30-1bfe-11e8-9c78-ff077be248d0.png">

I expect to be able to add my card details but I currently can't because 

<img width="883" alt="screen shot 2018-02-26 at 21 07 23" src="https://user-images.githubusercontent.com/12557036/36753466-21b149d0-1bfe-11e8-8f2c-2155e1d75b8c.png">

**Comment by elwoodxblues** [comment]
Are you using latest Saleor? Also, what version of `django-payments` do you have? I think we've fixed that problem with missing variables some time ago. I'm testing payment forms on current `master` and it renders properly:
![image](https://user-images.githubusercontent.com/5421321/36784530-03760168-1c80-11e8-9054-ec669f218d60.png)

**Comment by austineinstein** [comment]
Hi, 
Yes i'm using Saleor. On django-payments==0.12.1
