### ISSUE TITLE
Localization of duplicate email account doesn't make sense

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1830]
I saw this weird thing in post production when I was creating a customer account that was already registered.

![](https://i.imgur.com/DIT6uHC.png)

![](https://i.imgur.com/SXlwkvt.png)

---

Edit: note, the untranslated string is ` User with this Email already exists. `

---

I'm not quite sure how to explain this, it doesn't make sense in other language, but make sense in English. It's understandable for a French or a Polish for example but doesn't make real sense it shouldn't be that way, it looks like a debug string (as a dev).

I will wait to hear back from you. I also know it's not from your side, so I'm not quite sure of what you can do about this.

The error is generated by `django.db.models.base.Model#unique_error_message` (sourcing from `django.forms.models.BaseModelForm#_post_clean`).
```python
    def unique_error_message(self, model_class, unique_check):
        opts = model_class._meta

        params = {
            'model': self,
            'model_class': model_class,
            'model_name': capfirst(opts.verbose_name),
            'unique_check': unique_check,
        }

        # A unique field
        if len(unique_check) == 1:
            field = opts.get_field(unique_check[0])
            params['field_label'] = capfirst(field.verbose_name)
            return ValidationError(
                message=field.error_messages['unique'],
                code='unique',
                params=params,
            )

        # unique_together
        else:
            field_labels = [capfirst(opts.get_field(f).verbose_name) for f in unique_check]
            params['field_labels'] = get_text_list(field_labels, _('and'))
            return ValidationError(
                message=_("%(model_name)s with this %(field_labels)s already exists."),
                code='unique_together',
                params=params,
            )
            # ^^^^^^
```

**Comment by elwoodxblues** [comment]
I agree this message is not very user-friendly. Fortunately, we are able to override it in the `SignupForm` like this:
```
class SignupForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput)
    email = forms.EmailField(
        error_messages={
            'unique': pgettext_lazy(
                'Registration error',
                'This email has already been registered.')})
```
What do you think?

**Comment by NyanKiyoshi** [comment]
Nothing else to say other than perfect! :+1:

**Comment by elwoodxblues** [comment]
I'll open a PR.
