### ISSUE TITLE
Order details: notes rendering

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1831]
Without adding any line in the backend, it would be quite nice if the customer could be able to insert blank line and go back at the beginning of the line to let its text breathe.

---

### Currently, if the user tries to do that, it looks like that:

![](https://i.imgur.com/en4dYOR.png)

![](https://i.imgur.com/dbo4Imz.png)

---

### Currently, the code looks like that:
```html
{% for note in notes %}
  <small>{{ note.date }}</small>
  <p>{{ note.text }}</p>
{% endfor %}
```

If we add to the paragraphs this single CSS instruction:
```css
.order-details__total p {
  white-space: pre-wrap;
}
```

We get:
![](https://i.imgur.com/FHXkMvz.png)

![](https://i.imgur.com/xLjf8xk.png)

---

What do you think about this rendering issue? I also think that we should/ could edit a little bit the note template's structure to make it better.

**Comment by patrys** [comment]
I like it. Depending on the level of sanitization we currently have, we could even consider allowing basic formatting but that could backfire with customers making everything large and bold.

**Comment by elwoodxblues** [comment]
I'm not a CSS expert but I'm wondering why the styling is applied to the `.order-details__total` class which seems to be responsible for rendering only the total, so why this affects the notes? Maybe there is something wrong with the template structure. Anyway, it looks much better after your changes.

**Comment by NyanKiyoshi** [comment]
@elwoodxblues woops, that's true. I only did the changes in the element section of the inspector. I never put the edits in the SASS file. And I also just looked, the notes [are not in their section](https://i.imgur.com/aHu2Fpc.png) which should be corrected.

From my tests, doing those changes doesn't break anything.

```django
Index: templates/order/details.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- templates/order/details.html	(date 1519710666000)
+++ templates/order/details.html	(date 1519817106000)
@@ -62,7 +62,8 @@
         {% endif %}
       {% endif %}
       {% include "order/_ordered_items_table.html" %}
-        {% if notes %}
+        <div class="order-notes">
+          {% if notes %}
           <h2 class="order-notes__header">{% trans "Notes" context "Order notes list" %}</h2>
           {% for note in notes %}
             <small>
@@ -90,15 +91,14 @@
             <p>{{ note.content }}</p>
           {% endfor %}
         {% endif %}
-      {% if order.is_open %}
-        <div class="order-notes">
+        {% if order.is_open %}
           <form method="post" class="form-group">
             {% csrf_token %}
             {% bootstrap_form note_form display_labels=False %}
             <input type="submit" value="Submit" class="btn primary" />
           </form>
-        </div>
-      {% endif %}
+        {% endif %}
+      </div>
     </div>
   </div>
 {% endblock content %}
```

**Comment by elwoodxblues** [comment]
Could you open a PR with the changes when you have time?

**Comment by NyanKiyoshi** [comment]
Sure! Do I put the css change as well?

**Comment by elwoodxblues** [comment]
I guess so. If it improves the notes rendering than we should add it, but in the proper selector. I see that in `_order-details.scss` file there is `.order-notes` class, so probably there?

**Comment by NyanKiyoshi** [comment]
Yes, of course! :+1: 
I will do that as soon as I can.
