### ISSUE TITLE
Trying to use materialize instead of bootstrap in storefront

### ISSUE THREAD

**Issue by ajayjindal** [mirumee/saleor#1839]
### What I'm trying to achieve
We are trying to use [materialize](https://github.com/Dogfalo/materialize) for our website development in storefront. although bootstrap is good, but we want to use the material design scheme.

alternatively we can also use [google-mdl](https://github.com/google/material-design-lite), if integrating materialize is not possible.

##### This is how i modified the storefront.scss (saleor/static/scss/)
Although demo website runs, being skewed everywhere. Also this causes conflicts with common similar implementations in both frameworks. resulting in overall big mess to deal with
```
@import "~bootstrap/scss/bootstrap";
@import "~materialize-css/sass/components/color";
$colors: (
        "materialize-red": $materialize-red,
        "red": $red,
        "pink": $pink,
        "purple": $purple,
        "deep-purple": $deep-purple,
        "indigo": $indigo,
        "blue": $blue,
        "light-blue": $light-blue,
        "cyan": $cyan,
        "teal": $teal,
        "green": $green,
        "light-green": $light-green,
        "lime": $lime,
        "yellow": $yellow,
        "amber": $amber,
        "orange": $orange,
        "deep-orange": $deep-orange,
        "brown": $brown,
        "blue-grey": $blue-grey,
        "grey": $grey,
        "shades": $shades
);
@import "~materialize-css/sass/materialize";
@import "variables";
@import "components/breadcrumbs";
@import "components/buttons";
@import "components/cards";
@import "components/cart-dropdown";
@import "components/filters";
@import "components/footer";
@import "components/forms";
@import "components/header";
@import "components/labels";
@import "components/loader";
@import "components/pagination";
@import "components/table";
@import "components/tabs";
@import "components/typography";
@import "components/variant-picker";
@import "layouts/account";
@import "layouts/cart";
@import "layouts/category-page";
@import "layouts/checkout";
@import "layouts/home";
@import "layouts/login";
@import "layouts/no-results";
@import "layouts/order-details";
@import "layouts/product-list";
@import "layouts/product-page";
@import "layouts/styleguide";
```

#### If we omit the bootstrap completely
That leads to number of errors:
```
ERROR in ./saleor/static/scss/storefront.scss
Module build failed: 
    @include transition(background, 0.3s);
            ^
      No mixin named transition
Backtrace:
```
```
ERROR in ./saleor/static/scss/storefront.scss
Module build failed: 
    @include media-breakpoint-down(sm) {
            ^
      No mixin named media-breakpoint-down
Backtrace:
```

This is everywhere! these mixins are only implemented in bootstrap, i couldn't find the alternative in materialize.

**Then i tried to comment out all these `media-breakpoint-down` ,it would still result in crash of the website because of deep implementation of bootstrap.**

#### or we have to stick with bootstrap to work on front end while using saleor as the base?

**Comment by patrys** [comment]
In your case I'd suggest starting by removing all custom styling from `storefront.scss` and its submodules. These are meant as local customizations of Bootstrap and since you're replacing Bootstrap you'd likely be better off starting with a clean slate and building from there.
