### ISSUE TITLE
choosing the language displayed

### ISSUE THREAD

**Issue by jamespsteinberg** [mirumee/saleor#1841]
How can I choose the language displayed? 

I mainly serve english speaking people in Asia so they are forced to see chinese characters, is there any url or way for me to set the language people see. 

In the worst case I would rather leave everything in english until there is a good solution

Thanks

**Comment by elwoodxblues** [comment]
Hi, currently there is no possibility to dynamically switch the storefront's language. But as far as I know, @Pacu2 was about to start working on this feature, so I think we can keep this issue open.

**Comment by jamespsteinberg** [comment]
I just wanted a quick fix until it is part of it, I believe I can just turn it off and do all english with:

Saleor/core/middleware:
language = 'en-us'

and 

Saleor/checkout/core:
'language_code': 'en-us',

**Comment by elwoodxblues** [comment]
This may work, but the proper way to force one language would be rather through `saleor/settings.py`. As Saleor is written entirely in English, you could simply disable the Django translations by setting:
```
USE_I18N = False
```
This will force the default English language.

**Comment by patrys** [comment]
...or you could use the [mechanism provided by Django](https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#switching-language-in-templates) which I believe should still work fine.

**Comment by NyanKiyoshi** [comment]
Or the [set_language](https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#the-set-language-redirect-view) view apparently.
