### ISSUE TITLE
SEO: meta description are showing HTML tags

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1845]
Hello,

If we create a product, let's say the following description:

----
Saleor is the **best** brand.
And here is a new line as well.

----

It results to:
```html
<meta name="description" content="&lt;p&gt;Saleor is the &lt;b&gt;best&lt;/b&gt; brand.&lt;/p&gt;&lt;p&gt;And here is a new line as well.&lt;/p&gt;">
<meta property="og:description" content="&lt;p&gt;Saleor is the &lt;b&gt;best&lt;/b&gt; brand.&lt;/p&gt;&lt;p&gt;And here is a new line as well.&lt;/p&gt;">
```

----

Or even just an empty description will render to:
```html
<meta name="description" content="&lt;br&gt;">
<meta property="og:description" content="&lt;br&gt;">
```

I think we should add a column that would be a cleaned description and SEO friendly (which should be a short. The recommendation being of 155 characters).

I know that for example, not sure if it's still the case, on wordpress we had the possibility to write a short SEO friendly description or else it would take and clean a small part of the article.

**Comment by Pacu2** [comment]
I think we may use [builtin strip_tags templatetag](https://docs.djangoproject.com/en/dev/ref/templates/builtins/#striptags)

Input length is another thing, as I remember there's some SEO related ticket in the roadmap, which should provide additional fields for overriding such properties.

**Comment by NyanKiyoshi** [comment]
But I think it should also be kept in memory, there is no use doing that every time a product is rendered, the value of the description almost never change, it's a waste of CPU cycles.
