### ISSUE TITLE
Product variant without name or attrs displays as blank space in dashboard's breadcrumbs

### ISSUE THREAD

**Issue by rafalp** [mirumee/saleor#1846]
Seems like `__str__` on our `ProductVariant` may produce empty string if ProductVariant has no name or attributes set. Our titles seem to fallback to SKU if this is the case, but not our breadcrumbs:

<img width="362" alt="zrzut ekranu 2018-03-01 o 13 58 23" src="https://user-images.githubusercontent.com/750553/36845921-d21bf616-1d58-11e8-851c-763c32356818.png">

**Comment by NyanKiyoshi** [comment]
I had the exact same issue with products without variants. But I'm not able to reproduce it, I don't remember where and when it occurred. I'm gonna try to find it otherwise it means it's gone or no idea.
