### ISSUE TITLE
Failing to load jsi18n.js is making the dashboard unable to do almost anything

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1848]
Hello, 

I get this issue pretty often, but I'm not quite sure how to reproduce it every time. One way that would work every time would be to make Saleor abort the load of jsi18n or just put a response delay (imagine a server under a lot of load, the admin could very easily have this issue).

So, here is the issue: sometimes in dashboard, when going to the next page/ previous page, etc. or after some inactivity, it happens that the following errors happen:

```
16:36:57.442 Loading failed for the <script> with source “http://0.0.0.0:4999/jsi18n/”. products:706
16:36:57.554 ReferenceError: ngettext is not defined [Learn More] dashboard.js%20line%20157%20%3E%20eval:72:7
```

It makes any action button that is not a "href" link broken. It happened to me quite a lot, if we refresh, it still doesn't work (at least sometimes it's what happens, no idea why jsi18n it fails time to time). It requires a hard refresh (CTRL+SHIFT+R or CTRL+F5).

I'm opening this issue in hope that there will be a work around, that the dashboard would not be totally failing if there is an issue with `jsi18n.js`. What bothers me is that in experienced users don't know that there may be an issue that requires to do a hard refresh.

Edit: I know that you are currently making a lot of changes on how the dashboard is working in #1710. So I'm thinking this issue may not be relevant. I'll wait to hear your thoughts about this.

**Comment by Pacu2** [comment]
We should use [django-static18n](https://django-statici18n.readthedocs.io/en/latest/) to serve JS files from our servers. 
This way, files could be gzipped to save some space, moreover - we can defer them.

**Comment by NyanKiyoshi** [comment]
I agree with this suggestion, that would save a lot of CPU time as well.
But I'm not sure of what you hear about gzipping the files? You mean web server side (e.g. nginx)?

**Comment by patrys** [comment]
Yes, usually that would be the job of either Nginx or a CDN like AWS CloudFront.

**Comment by NyanKiyoshi** [comment]
I'm gonna close this as dashboard 2.0 will most likely not have this issue as how it's planned to be working (otherwise I will look into it).
