### ISSUE TITLE
Random order generator should also randomly set shipping price

### ISSUE THREAD

**Issue by rafalp** [mirumee/saleor#1850]
Something I've noticed when working on my PR changing prices is that our random data generator is not setting any shipping price when it creates fake orders via `create_fake_order`.

This isn't a bug or issue per se, but IMHO updating this function to also include random shipping method with its price on generated order would make it easier in future to develop and test changes that cause order's value recalculation.

**Comment by akjanik** [comment]
Hi, I noticed that shipping price is being set in PR #1777 in this particular commit
https://github.com/mirumee/saleor/pull/1777/commits/de7cbbea8419c940131992f654695b52fecc3a97#diff-103ebc2d83ae6722bfe0b0b21f446da6R437
If that's not enough, I think it's good time to propose changes as long as PR is not closed yet.

**Comment by rafalp** [comment]
@akjanik this is super nice find, thanks!
