### ISSUE TITLE
Translation into spanish

### ISSUE THREAD

**Issue by sleweddock** [mirumee/saleor#1853]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
I want to translate the entire project into spanish, it will increase the reach of the project and allow more spanish users into it, if they are any steps to follow I am happy to oblige by them.

**Comment by rafalp** [comment]
Thank you for stepping up and offering your help!

Saleor translation effort is taking place at our [Transifex](https://www.transifex.com/mirumee/saleor-1/). If you don't have an account there, using "sign in with Github" is fast and free way to join the Transifex. Next step would be joining the translation team for Spanish language.

Thank you!
