### ISSUE TITLE
What's the best way to customise Saleor and stay up-to-date?

### ISSUE THREAD

**Issue by lampyjon** [mirumee/saleor#1858]
### What I'm trying to achieve
I'm a big fan of Saleor, but I can't understand the best way to keep up-to-date with changes here when I've made local customisations. I don't want to fall behind in terms of bug fixes, security updates, and feature improvements from here, but at the same time I have got local tweaks (e.g. template changes, email format updates etc.) which I need to maintain.

### What I'm currently doing
I took a fork of the saleor repo, and then created a feature branch where I do my customisations. Every so often I do `git fetch upstream` and then `git merge upstream/master` to my local master. I then switch to my feature branch and rebase. But this is becoming increasingly time-consuming. It's also tricky with database migrations. 

Finally I've been caught out by merging in changes from the saleor master where they've changed existing behaviour. 

Is this the best approach? Is there a better one? How do others do this? Ideally it would be great to have something in the 'customisation' section of the docs which describe a good way to handle local customisations whilst still retaining the ability to stay current with this fantastic project.

**Comment by NyanKiyoshi** [comment]
Hiya!

It depends on what changes you made... I personally recommend you to keep track of your changes, every changes. So whether on a git fork or in a new github repository (then to pull from saleor you do `git remote add upstream https://github.com/mirumee/saleor.git` then you pull merge from upstream).

  - Your changes must never be on the master branch of Saleor (fork or new repository). This is to keep tract of your changes and Saleor changes.

  - Each change set should be in a pull request in your fork/ repository and then merged in your post-production (or other, depends how your work).

  - Each change set must come with their own tests before merging the pull request to ensure that once you update Saleor, your changes are running like they were designed to.
  I also recommend you to setup travis-ci and codecov on your fork/ repository.

If you made small changes, merge shouldn't make a lot of conflict and not make a lot of breaking.

Then, I would recommend you only merge each new release of Saleor. Which means, they release one every month. If you feel like the latest release of Saleor is not quite stable, I don't recommend you to push it in post-production.

 - I also recommend you to follow the project, to try to keep track of every changes made on saleor though the "Watch" feature of GitHub (at least quickly or when a PR is merged). 

 - Also to keep track of issues, sometimes some issue/ PR are really important and requires to be applied quickly in production, which means you can't wait the next Saleor release.
 So you would need to apply them manually (which will of course result to a conflict on merge).

Then, to merge the latest Saleor release with your current version, I recommend you to merge to a new branch (child of your post-production branch). Then you will probably have a lot of conflict and will need to see yourself how to resolve them depending on your changes and Saleor changes.

Once the conflicts are resolved, you run the tests and fix anything that was broken.
