### ISSUE TITLE
npm run build-emails fails with "find: ‘./node_modules/.bin/mjml’: No such file or directory"

### ISSUE THREAD

**Issue by pards** [mirumee/saleor#1860]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
Following the installation instructions
...

### Steps to reproduce the problem

```
$ npm run build-emails

```

### What I expected to happen

I expected the command to succeed.

### What happened instead/how it failed

```
> saleor@0.0.0 build-emails /home/developer/saleor
> mkdir -p templates/templated_email/compiled/ && find templates -name "*.mjml" -not -path "templates/templated_email/source/*partials/*" -not -path "templates/templated_email/source/*shared/*" -exec ./node_modules/.bin/mjml -l skip {} -o templates/templated_email/compiled/ \;

find: ‘./node_modules/.bin/mjml’: No such file or directory
find: ‘./node_modules/.bin/mjml’: No such file or directory
find: ‘./node_modules/.bin/mjml’: No such file or directory
find: ‘./node_modules/.bin/mjml’: No such file or directory
find: ‘./node_modules/.bin/mjml’: No such file or directory
find: ‘./node_modules/.bin/mjml’: No such file or directory

```

**Comment by patrys** [comment]
It's a bug, the script in `package.json` should not include the relative `./node_modules/.bin/` path as these binaries are automatically added to PATH when `npm run ...` is executed.

**Comment by milven-domingos** [comment]
i have the same error, how to fix it

**Comment by YunazGilang** [comment]
Hey i also encountered the same problems. I am using Windows 10 tho. And none of the above solutions has worked for me. So i tried to do this manually (not using the `npm run build-emails` command) by this step through Windows CMD : 

- first create the `templates\templated_emails\compiled\` directory by executing this : `md templates\templated_email\compiled\ 2>NUL`
- then compile the .mjml files into .html format into that directory by executing this : `for /F "usebackq delims=" %A in (`dir /b /s /a-d *mjml ^| findstr /v partials ^| findstr /v shared ^| findstr /i templates`) do node_modules\.bin\mjml %A -o templates\templated_email\compiled\`

Those steps will give me these files : 
![image](https://user-images.githubusercontent.com/22442215/39955720-5aeb96a8-55fe-11e8-9bdb-07d16b59e89f.png)

But i don't know if i do this correctly, can you please give me some advice. Thanks.
