### ISSUE TITLE
Please add feture for database + mediafile beckup/restore

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#1862]
Please add:
https://github.com/django-dbbackup/django-dbbackup

**Comment by rafalp** [comment]
Hey @mmmcorpsvit! Thank you for suggestion, but We feel that this is out of scope for problems that Saleor should handle out of the box.

Currently, there are many ways to go about setting backups for your site, depending on platform, deployment method one is using, or even personal preference.

Giving the app you are mentioning a skim, there should be no problems for it to work with Saleor, so if somebody is looking for python solution, it should work for him.

Thanks!

**Comment by mmmcorpsvit** [comment]
simple e-shop not full without backup/restore  functions, because there already need system administrator this is not possible always (sorry my poor English)

**Comment by patrys** [comment]
@mmmcorpsvit Cloud services like Google Cloud and AWS provide robust solutions for backups. We've never used `django-dbbackup` and it does not seem to be a very popular project.
