### ISSUE TITLE
.gitignore issue with Heroku deployment 

### ISSUE THREAD

**Issue by flexpeace** [mirumee/saleor#1863]
It looks like this file https://github.com/mirumee/saleor/blob/master/.gitignore 

Is preventing successful deployment to Heroku 

Especially the following are not uploaded to heroku when deployed 

/static/
/saleor/static/assets/
webpack-bundle.json

**Comment by NyanKiyoshi** [comment]
I don't know heroku but I think, if you want those folders in heroku, you should run the following commands to generate them.

- for `/static/`:
```shell
heroku run python manage.py collectstatic
```

- for `webpack-bundle.json`:
```shell 
heroku npm i
heroku npm build-assets --production
heroku npm run build-emails
```

---

**But, from the docs, it also says that you shouldn't do that. You should use a cloud provider like amazon S3 (see https://saleor.readthedocs.io/en/latest/deployment/s3.html#amazon-s3).**

**Comment by elwoodxblues** [comment]
@flexpeace There is the `heroku-postbuild` hook in `package.json` which builds static files after deployment to Heroku. `.gitignore` should have nothing to do with this process.

**Comment by elwoodxblues** [comment]
@flexpeace Please reopen this issue if you have any further questions.
