### ISSUE TITLE
PayPal payment VALIDATION_ERROR 

### ISSUE THREAD

**Issue by yxnkzg** [mirumee/saleor#1872]
paypal response --> 

`{'name': 'VALIDATION_ERROR', 'details': [{'field': 'transactions.item_list.items', 'issue': "Currency amount must be non-negative number, may optionally contain exactly 2 decimal places separated by '.', optional thousands separator ',', limited to 7 digits before the decimal point and currency which is a valid ISO Currency Code"}], 'message': 'Invalid request - see details', 'information_link': 'https://developer.paypal.com/docs/api/payments/#errors', 'debug_id': 'xxx'}
`

raw request post data: -->

{'data': '{"intent": "authorize", "transactions": [{"amount": {"total": "100.00", "currency": "HKD", "details": {"subtotal": "100.00", "tax": "0.00", "shipping": "0.00"}}, "item_list": {"items": [{"name": "product name", "quantity": "1", "price": "**Money(\'100.00\', \'HKD\')**", "currency": "HKD", "sku": "fandee-01"}]}, "description": "xxxxx"}], "redirect_urls": {"return_url": "http://localhost:8000/process/xxxxx/", "cancel_url": "http://localhost:8000/process/xxxxx"}, "payer": {"payment_method": "paypal"}}', 'headers': {'Content-Type': 'application/json', 'Authorization': 'xxxx'}}

package version:

prices (1.0.0)
django-prices (1.0.0)

**Comment by rafalp** [comment]
Thank you for report, @yxnkzg! We've recently revamped a lot of our money handling

Looks like this [line is to blame](https://github.com/mirumee/saleor/blob/master/saleor/order/models.py#L299)

`line.unit_price_gross.quantize(Decimal('0.01'))` returns `Money()` so we'll need to add `.amount` at end of it to drop it to `Decimal`. Looks like we'll also need to add tests to enforce that our payment data is build correctly.
