### ISSUE TITLE
Issue installing Saleor on Windows

### ISSUE THREAD

**Issue by alexmzirai** [mirumee/saleor#1875]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
Getting Saleor up and running on Windows 8/10.
...

### Steps to reproduce the problem

1.Running python migrate.py
2.

### What I expected to happen
Install the DB and other settings
...

### What happened instead/how it failed
raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

This is the stack trace:
![screenshot - 06-mar-18 3_28_56 pm](https://user-images.githubusercontent.com/28978304/37032331-2c98af28-2153-11e8-8301-8407bde4029b.jpg)

This is the settings.py file:
![screenshot - 06-mar-18 3_39_10 pm](https://user-images.githubusercontent.com/28978304/37032728-9b1bb14c-2154-11e8-942f-036e74b8fd65.jpg)

After giving a random secret key, i get the message:
 from django.urls import path
ModuleNotFoundError: No module named 'django.urls'

My pip freeze is:
![screenshot - 06-mar-18 3_42_45 pm](https://user-images.githubusercontent.com/28978304/37032883-0fb43600-2155-11e8-9ea9-1a220e480821.jpg)

I dont know if the problem is the Django version i am running or the inability of manage.py to fetch a SECRET_KEY....
...

(Please include a stack trace if this problem results in a crash.)

**Comment by Pacu2** [comment]
Hi @alexmzirai,
Have you set your `SECRET_KEY` env variable?
Take a look at point 4:  https://saleor.readthedocs.io/en/latest/gettingstarted/installation-windows.html

**Comment by alexmzirai** [comment]
Any advice on how to add that secret key env variable?

this is my sample secret key...
![screenshot - 06-mar-18 3_58_37 pm](https://user-images.githubusercontent.com/28978304/37033501-4bb6341c-2157-11e8-8017-532e530f9bba.jpg)

**Comment by Pacu2** [comment]
I think this one might be helpful
https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10
Have no experience setting up Saleor on Windows 10, can't help other than googling.

**Comment by alexmzirai** [comment]
i assigned a secret key directly...it worked.
Now i'm getting a Postgres user error.

![screenshot - 06-mar-18 4_02_54 pm](https://user-images.githubusercontent.com/28978304/37033702-e380cc30-2157-11e8-830d-b03ce93207a3.jpg)

**Comment by patrys** [comment]
@alexmzirai You will need to create a user and a database in your PostgreSQL instance. This is mentioned in the installation docs.

**Comment by alexmzirai** [comment]
The database is already up and running.
I dont know why the connection is not going through for user "saleor".

Let me read the docs again and see if i missed something.

**Comment by alexmzirai** [comment]
Created the role "saleor" under the saleor DB.
Apparently the issue was that the "CREATE ROLE" command wasn't executing right.
Finally got it fixed.
![screenshot - 06-mar-18 4_27_59 pm](https://user-images.githubusercontent.com/28978304/37034885-d285d318-215b-11e8-9f4b-2f9e8c37599b.jpg)

![screenshot - 06-mar-18 4_29_58 pm](https://user-images.githubusercontent.com/28978304/37034902-dd81bfac-215b-11e8-9fc7-572851d8851e.jpg)

It has finally worked.
@Pacu2 @patrys , thank you.

**Comment by amirulasyraf88** [comment]
> i assigned a secret key directly...it worked.
> Now i'm getting a Postgres user error.
> 
> ![screenshot - 06-mar-18 4_02_54 pm](https://user-images.githubusercontent.com/28978304/37033702-e380cc30-2157-11e8-830d-b03ce93207a3.jpg)

hi how do you set up the Environment Variable? Because I am stuck here too.

**Comment by amirulasyraf88** [comment]
> Any advice on how to add that secret key env variable?
> 
> this is my sample secret key...
> ![screenshot - 06-mar-18 3_58_37 pm](https://user-images.githubusercontent.com/28978304/37033501-4bb6341c-2157-11e8-8017-532e530f9bba.jpg)

hi how do you set up the Environment Variable? Because I am stuck here too.

**Comment by amirulasyraf88** [comment]
thank you soo much your ticket help me alot ..

**Comment by maarcingebala** [comment]
That depends on what operating system and shell you use. In UNIX-based systems you would usually use the `export` command. There is a lot of resources online, look for "setting environment variables in [your OS name]".
