### ISSUE TITLE
How to get product to show as "currently available"

### ISSUE THREAD

**Issue by alexmzirai** [mirumee/saleor#1877]
How to change product to currently available?

### What I'm trying to achieve
I am trying to change the availability of a product in my demo store on localhost, but i get the "This product is currently unavailable." error message.
...

### Steps to reproduce the problem

1. Changed the "availability from" date to a past date.
![screenshot - 06-mar-18 6_44_58 pm](https://user-images.githubusercontent.com/28978304/37042091-c1bdefe4-216e-11e8-87dc-f2f77b6f0300.jpg)

### What I expected to happen
Change product to "currently available"..

### What happened instead/how it failed
![screenshot - 06-mar-18 6_42_33 pm](https://user-images.githubusercontent.com/28978304/37042108-cbdce886-216e-11e8-9363-a0d488fcfcd5.jpg)

...

(Please include a stack trace if this problem results in a crash.)

**Comment by alexmzirai** [comment]
How to change product to currently available: please advise.

**Comment by rafalp** [comment]
Hey Alex, can you please confirm that your product is has at least one variant added that has stock?

**Comment by alexmzirai** [comment]
I just have one of each product in the DB for now.
Should i add variants of the product to the sytem too?

**Comment by alexmzirai** [comment]
![screenshot - 06-mar-18 6_55_26 pm](https://user-images.githubusercontent.com/28978304/37042666-f71840bc-216f-11e8-8216-6dc64151f8a6.jpg)

**Comment by rafalp** [comment]
Yes, add at least one variant to the product, and then set stock amount for the variant. Once this is done, you'll have a variant on the table with green "AVAILABLE" text displayed in its "status" column.

**Comment by alexmzirai** [comment]
Thanks.
What about the SKU value? This refers to the set stock amount?

**Comment by rafalp** [comment]
SKU is product's internal identifier that your shop uses. There's [wikipedia article](https://en.wikipedia.org/wiki/Stock_keeping_unit) explaining it, but the main bit is:

> These codes are not regulated or standardized. When a company receives items from a vendor, it has a choice of maintaining the vendor's SKU or creating its own.

**Comment by alexmzirai** [comment]
Thank you.
Let me get right to it.
