### ISSUE TITLE
Add flag `is_visible` to Collection 

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#1878]
We should add `is_visible` flag to Collection model. It would allow staff to create promotion collections ahead of time.

- [ ] Add `is_visible` flag to Collection model
- [ ] Enhance dashboard collection form and template to include the flag
- [ ]  List visible collections in the sitemap (Collection will be added to Sitemap in #1871)
- [ ] Staff should be able to see collections with `is_visible` set to `False` on the storefront, appropriate message should be displayed (as currently done with `is_published` on the Product, regular customers should receive regular 404 error)
- [ ] Changes are well tested

**Comment by rafalp** [comment]
If we already have `is_published` flag on products meaning "this product is visible in storefront", wouldn't it be more consistent to also use `is_published` for collections?

**Comment by elwoodxblues** [comment]
We also have "is_visible" for pages. I agree that we could use one naming convention here.

**Comment by Pacu2** [comment]
Resolved in #2109
