### ISSUE TITLE
How to edit templates files to add custom shop name instead of "SALEOR"

### ISSUE THREAD

**Issue by alexmzirai** [mirumee/saleor#1879]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
I want the store front to have a custom name instead of the SALEOR text.

How do I achieve this?

Thankyou.

**Comment by alexmzirai** [comment]
Or, to make it easier...is there a link to some documentation or site on how to edit template files in Saleor?

**Comment by elwoodxblues** [comment]
Please take a look at the [Customization](https://saleor.readthedocs.io/en/latest/customization.html) section in Saleor docs. Basically, you should start with adjusting the templates. For instance, the `templates/base.html` file contains things like storefront's header (along with the logo), footer and general page layout. The logo is `.svg` file so you should replace it with your own file. In the dashboard, there is the "Site settings" section where you'll find the input to set the title displayed in storefront's `<title>` tag and page domain.

**Comment by alexmzirai** [comment]
Understood, thank you.

**Comment by elwoodxblues** [comment]
Please reopen this issue if you have any other questions.
