### ISSUE TITLE
Customize Stripe payment form

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1890]
Hello, 

I'm wondering how should we customize the rendering of Stripe (I'm not sure if I should post it there or into django-payment, but since it's the about the UI of Saleor I'm thinking it's better posting it here).

From what I see, we just have to edit `payments.stripe.widgets.StripeCheckoutWidget`, so we would have to inherit/ override `payments.stripe.StripeProvider` to customize the form. I thinking it would probably be better to have a template that we can override (like the [csrf-failure-view](https://docs.djangoproject.com/en/2.0/ref/settings/#csrf-failure-view) template of django for example).

What do you think? How should we make it look great?

From Stripe's document, we could make Stripe look way better on Saleor.
![](https://i.imgur.com/0ZVZDAL.png)

Here is how Saleor looks like right now with Stripe.
![](https://i.imgur.com/f98L59o.png)

**Comment by NyanKiyoshi** [comment]
I also saw that when paying using dotpay, all we have is a "Save changes" button, nothing else (expect the page title). It's really confusing, wouldn't be a way to improve this step and make it more user friendly?

**Comment by prabhatb2000np** [comment]
Hi, how can I integrate stripe to Saleor?
