### ISSUE TITLE
Commit hash information in dashboard

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor#1894]
Is it possible to add information about the commit hash in the dashboard?
Now it's only information:  `Release: dev`
This would help in reporting issues, and should be required when reporting a issue.

**Comment by NyanKiyoshi** [comment]
I think it's a good idea.

One way would be, in `__init__.py` or `settings.py`, to read the `__VERSION__` variable and look for `rc` or `a` at the end of the version number. If there is `rc` (or `a`). Then using subprocess, try to get the revision short hash `git rev-parse --short HEAD` and default it to `''`.

So for example, we are currently on the release of March 2018, so:
```python
__VERSION__ = '2018.3rc'
```

Then, thanks to git:
```python
__VERSION__ = '2018.3rc2c4eb448'
```

Or if the current working directory is not git (git command returned a non-zero value):
```python
__VERSION__ = '2018.3rc'
```

That's my suggestion on that.

**Comment by patrys** [comment]
We do something similar on the demo branch where the dashboard displays the version in the sidebar.
