### ISSUE TITLE
Saleor deployment to Heroku fails: ModuleNotFoundError: No module named 'celery'

### ISSUE THREAD

**Issue by liaojim** [mirumee/saleor#1897]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve

I was following the Deploy to Heroku button on the git page to deploy Saleor to Heroku. But the deployment failed with error: ModuleNotFoundError: No module named 'celery'

### Steps to reproduce the problem

1. Click the button on github page of Saleor
2. Fill the info required on Heroku to deploy it. 
3. It failes

### What I expected to happen

I expect the deployment to succeed but it failed. 

### What happened instead/how it failed

Not sure why, but I suspect there are issues with the current Saleor release in Git and it's causing the error on Celery. 

I also downloaded a copy of Saleor to my Mac and tried to deploy to Heroku through command line and ran into the same error. Even though it works fine on my Mac.  

(Please include a stack trace if this problem results in a crash.)

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/saleor/__init__.py", line 1, in <module>
    from .celeryconf import app as celery_app
  File "/app/saleor/celeryconf.py", line 3, in <module>
    from celery import Celery
ModuleNotFoundError: No module named 'celery'

**Comment by NyanKiyoshi** [comment]
Could you send us the output of `pip freeze`?
The module `celery` should have been installed through the dependency `celery[redis]`.

**Comment by liaojim** [comment]
You are right NyanKiyoshi. Celery is there, and Saleor works fine on my Mac. But in deploying to Heroku, the error shows up consistently. 

Here's the pip freeze result on my Mac: 

amqp==2.2.2
asn1crypto==0.24.0
attrs==17.4.0
awsebcli==3.12.4
Babel==2.5.3
billiard==3.5.0.3
bleach==2.1.2
blessed==1.14.2
boto3==1.5.18
botocore==1.9.6
braintree==3.39.1
cairocffi==0.8.0
CairoSVG==2.1.3
celery==4.1.0
cement==2.8.2
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
colorama==0.3.7
cryptography==2.1.4
cssselect2==0.2.1
defusedxml==0.5.0
dj-database-url==0.5.0
dj-email-url==0.0.10
Django==2.0.2
django-babel==0.6.2
django-bootstrap4==0.0.5
django-cache-url==2.0.0
django-celery-beat==1.1.1
django-celery-results==1.0.1
django-countries==5.0
django-elasticsearch-dsl==0.4.4
django-filter==1.1.0
django-fsm==2.6.0
django-heroku==0.3.1
django-impersonate==1.3
django-js-asset==0.1.1
django-mptt==0.9.0
django-payments==0.12.1
django-phonenumber-field==2.0.0
django-prices==0.7.1
django-prices-openexchangerates==0.1.15
django-redis==4.8.0
django-render-block==0.5
django-storages==1.6.5
django-templated-email==2.2.0
django-versatileimagefield==1.9
django-webpack-loader==0.5.0
dockerpty==0.4.1
docopt==0.6.2
docutils==0.14
elasticsearch==5.5.2
elasticsearch-dsl==5.4.0
Faker==0.8.8
freezegun==0.3.9
google-i18n-address==2.2.1
google-measurement-protocol==0.1.6
graphene==2.0.1
graphene-django==2.0.0
graphql-core==2.0
graphql-relay==0.4.5
gunicorn==19.7.1
html5lib==1.0.1
idna==2.6
iso8601==0.1.12
jmespath==0.9.3
jsonfield==2.0.2
kombu==4.1.0
Markdown==2.6.11
maxminddb==1.3.0
maxminddb-geolite2==2017.803
multidict==3.3.2
oauthlib==2.0.6
pathspec==0.5.5
pdfrw==0.4
pew==1.1.2
phonenumberslite==8.8.9
Pillow==5.0.0
pipenv==11.0.2
pluggy==0.6.0
prices==0.5.9
promise==2.1
psycopg2==2.7.4
psycopg2-binary==2.7.4
purl==1.3.1
py==1.5.2
pycparser==2.18
PyJWT==1.5.3
Pyphen==0.9.4
pytest==3.4.0
pytest-django==3.1.2
pytest-mock==1.6.3
pytest-vcr==0.3.0
python-dateutil==2.6.1
python-slugify==1.2.4
python3-openid==3.1.0
pytz==2018.3
PyYAML==3.12
redis==2.10.6
requests==2.9.1
requests-oauthlib==0.8.0
Rx==1.6.0
s3transfer==0.1.12
semantic-version==2.5.0
singledispatch==3.4.0.3
six==1.11.0
social-auth-app-django==2.1.0
social-auth-core==1.6.0
stripe==1.77.1
suds-jurko==0.6
tabulate==0.7.5
termcolor==1.1.0
text-unidecode==1.1
tinycss2==0.6.1
transifex-client==0.13.1
typing==3.6.2
Unidecode==1.0.22
urllib3==1.22
uWSGI==2.0.15
vcrpy==1.11.1
vine==1.1.4
virtualenv==15.1.0
virtualenv-clone==0.3.0
wcwidth==0.1.7
WeasyPrint==0.42.2
webencodings==0.5.1
websocket-client==0.47.0
whitenoise==3.3.1
wrapt==1.10.11
xmltodict==0.11.0
yarl==0.17.0

**Comment by NyanKiyoshi** [comment]
> Here's the pip freeze result **on my Mac**
Could you take a look if it installed correctly on Heroku and, or, reinstall it using `pip install celery[redis]`?

**Comment by liaojim** [comment]
Hi NyanKiyoshi, 

I'll try the workaround. In the meantime, please look into the issue and fix the root cause. The feature on Saleor git page to deploy to Heroku is clearly broken. It'd be better to have the right fix in place. 

Thanks,
Jim

**Comment by liaojim** [comment]
Hi NyanKiyoshi,

I tried but don't see a way to check if celery is installed, or reinstall it on Heroku. The command to push Saleor over is this: 

git push heroku master

It errors, and doesn't allow me to check in the middle of the execution. I'd appreciate any recommendations to get this going. 

Thanks,
Jim

This is the complete output of the command: 

Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 372 bytes | 372.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote: -----> Installing dependencies with latest Pipenv…
remote:        Installing dependencies from Pipfile…
remote: -----> Python app detected
remote: -----> Installing dependencies with latest Pipenv…
remote:        Installing dependencies from Pipfile…
remote: -----> Discovering process types
remote:        Procfile declares types -> release, web
remote:
remote: -----> Compressing...
remote:        Done: 64.6M
remote: -----> Launching...
remote:  !     Release command declared: this new release will not be available until the command succeeds.
remote:        Released v15
remote:        https://shrouded-citadel-89663.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
remote: Running release command....
remote:
remote: Traceback (most recent call last):
remote:   File "manage.py", line 10, in <module>
remote:     execute_from_command_line(sys.argv)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
remote:     utility.execute()
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 317, in execute
remote:     settings.INSTALLED_APPS
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
remote:     self._setup(name)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
remote:     self._wrapped = Settings(settings_module)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
remote:     mod = importlib.import_module(self.SETTINGS_MODULE)
remote:   File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
remote:     return _bootstrap._gcd_import(name[level:], package, level)
remote:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
remote:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
remote:   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
remote:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
remote:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
remote:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
remote:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
remote:   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
remote:   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
remote:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
remote:   File "/app/saleor/__init__.py", line 1, in <module>
remote:     from .celeryconf import app as celery_app
remote:   File "/app/saleor/celeryconf.py", line 3, in <module>
remote:     from celery import Celery
remote: ModuleNotFoundError: No module named 'celery'
remote: Waiting for release.... failed.
To https://git.heroku.com/shrouded-citadel-89663.git
   0ddcfed..f66a7e0  master -> master

**Comment by Pacu2** [comment]
Hi @liaojim,
I've just successfully deployed to Heroku using 'Deploy to Heroku' button.
Could you confirm on your end?

**Comment by liaojim** [comment]
Hi @Pacu2, 

Thank you for looking into this issue for me! Appreciate it. 

In the past several days, I was able to consistently reproduce this issue from the git page, and also through Heroku CLI on my Mac. I'm glad to hear that you were able to successfully deploy it. 

I tried to redo it again just now and ran into a new issue on sendgrid add-on and submitted a ticket to Heroku support. Will update later.

**Comment by liaojim** [comment]
Hi @Pacu2,

The git page deploy button worked for me this time. Heroku Tech Support changed something on my account and fixed the issues (both senddrid and previously reported error on celery). :)

Thank you for taking the time looking into this issue for me!

My local Mac Heroku CLI deployment still has the same error on celery though. I compared the log with the git deploy and found the following difference: CLI deployment doesn't run pip install on requirements.txt for some reason. 

Git deployment: 
-----> Installing pip
-----> Installing requirements with pip
       Collecting amqp==2.2.2 (from -r /tmp/build_b90780110e79ca25923fd53bf266f109/mirumee-saleor-e8abab5/requirements.txt (line 7))
...

Mac CLI deployment: 
remote: -----> Installing pip
remote: -----> Installing dependencies with latest Pipenv…
remote:        Installing dependencies from Pipfile…
remote: -----> $ python manage.py collectstatic --noinput
remote:        Traceback (most recent call last):
remote:          File "manage.py", line 10, in <module>
...

What's causing the difference behavior on Heroku? Something is wrong with my local Mac dev. settings?

Thanks,
Jim

**Comment by patrys** [comment]
@liaojim From the messages it seems that you've added a Pipenv/Pipfile to your copy of the project? If so I'd see if removing those from the repository fixes your problem.

**Comment by liaojim** [comment]
@Pacu2, 
The culprit is a pipfile on my Mac app folder. After I renamed it, the celery issue went away. I had to turn off COLLECTSTATIC to avoid an error. But eventually I was able to deploy it to Heroku. 
Can't explain why my git page Deploy to Heroku failed with the same 'celery' issue. 
But I'm glad that I can now deploy. :)
Thanks again!
Jim

**Comment by liaojim** [comment]
Thank you a bunch! @patrys

**Comment by Pacu2** [comment]
You're welcome!
