### ISSUE TITLE
Payment status on the orders list and  in order details

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor#1902]
The payment status should be visible on the order list and in the order details.
In the details of orders now it looks like that if the order is not paid, you can see the button "Pay For Order".
Example: order 54 is paid and 47 is not paid.
<img width="836" alt="zrzut ekranu 2018-03-12 o 23 16 52" src="https://user-images.githubusercontent.com/1561204/37312790-c2c8158a-264c-11e8-90ed-15dfb23ed429.png">

**Comment by Pacu2** [comment]
I think this is resolved by now.
