### ISSUE TITLE
initial test data

### ISSUE THREAD

**Issue by austineinstein** [mirumee/saleor#1903]
In trying to populate my local database with initial test data

./manage.py populatedb

I have no clue as to why it breaks here every time

<img width="565" alt="screen shot 2018-03-13 at 05 25 50" src="https://user-images.githubusercontent.com/12557036/37324719-a5232390-2682-11e8-949f-b30b954d4eb6.png">
<img width="1008" alt="screen shot 2018-03-13 at 05 26 31" src="https://user-images.githubusercontent.com/12557036/37324768-d6bcb786-2682-11e8-84d1-013646875dc8.png">

**Comment by Pacu2** [comment]
Hi austineinstein, I can see two things on attached screenshot:
- You are using Python 2.7, where Saleor officially supports Python 3.4+
- Error code is related to missing database migrations, try running ./manage.py migrate

**Comment by Pacu2** [comment]
Closing for now, please reopen in the future if you have any further questions.
