### ISSUE TITLE
Be able to create an order from dashboard

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1904]
Hello, since Saleor is responding the almost all our special needs, we (the commercial for now) are currently using Saleor as backoffice. 

I was quite surprised that we don't have the possibility to create orders from dashboard.

Shouldn't we add this possibility?

I will start working on it ASAP on my side since we need it. I just want to hear back from you and then make a PR if you feel like it should belong in Saleor features.

**Comment by elwoodxblues** [comment]
Hey, improving the whole order management process in the dashboard is one of our top priorities right now (see the [roadmap](https://github.com/mirumee/saleor/projects/6)). We've just merged [a huge PR](https://github.com/mirumee/saleor/pull/1777) that makes the flow more intuitive and cleans up the UI. Creating orders is actually the next step that I'd like to take. However, this is a big huge feature consisting of many pieces such as:
- adding discounts
- assigning customers
- setting shipping method and price etc.
Each piece will probably require a separate view, form and a modal window. Each part will also have to be well-tested. There are still some open questions e.g. how to handle payments. Due to the amount of work here, I think our team should take care of this feature.
I initially thought that for the best UI we should implement this as dynamic view in React, which we'll eventually do, but now I think we're ready to start with simpler UI using only Django templates. Assuming that we'll finish [the menu app](https://github.com/mirumee/saleor/pull/1886) soon, we could start this one as a next feature.

**Comment by NyanKiyoshi** [comment]
That's really great. Thank you for your answer! This also answers #1907 then.
That's gonna be quite messy to add all that to our Saleor version but will see. Looking forward for that. Thanks a lot.

**Comment by NyanKiyoshi** [comment]
@elwoodxblues I just saw in the roadmap that you have added the following entry:

----

**Saving checkouts in database**
Checkout should have a dedicated model that would be stored in the database. This will allow other features such as:
- sharing checkouts
- creating better checkout API (multiple calls to create/edit checkout)
- tracking abandoned checkouts

----

Are you planning on sharing cart link? I'm not quite sure if that's what you hear by that. This feature was requested to me today, I have to work on that ASAP as well. 
Many websites have a feature to generate a link from carts.
What would probably be useful as well, would be that staff members could transfer a cart to a given customer.

----

I have a lot of work to do on saleor, I'm really wondering if there is no way to work closer or something. I'm not a django dev, more pylons, pyramid and flask. So I'm learning and refreshing my 8 years old knowledge about django through saleor.

I'm not currently paid and gonna negotiate for 1.5 to 2k eur/ mo. I'm a student, so for them they think I'm just doing that for some extra cash. Except that I'm working for them 80+ hours per week and my old setup is starting to die so productivity is starting to go low.

The reason why I say that, is because I'm also planning on giving back a percentage to Mirumee to thank you for your work and keep you going. I'm not quite sure how well Mirumee is financially going, but seems like you are quite busy on some private projects those recent times (judging by your overall activity on this project).

**Comment by patrys** [comment]
@NyanKiyoshi Your contributions are more than we could have asked for, it would be unfair to expect anything more. Please make sure you don't overwork yourself as getting burned out is a major threat and maintaining a work-life balance is very important.

**Comment by NyanKiyoshi** [comment]
Thank you for that! I need to go forward and quick with the enterprise I'm working with, my huge project in my minds is not gonna build itself :wink: 

Is the mirumee email monitored? Sometimes there are things that are not worth creating an issue for, I'm not sure if that would be a preference or not, depending how you use mails.

**Comment by patrys** [comment]
That makes sense, we should probably display the slug under the display name when presenting choices.

**Comment by NyanKiyoshi** [comment]
But also be searchable when typing, it would allow to find what we are looking for more quickly. But I think, if I recall correctly, we can set that in ProductAttributeFilter.

**Comment by NyanKiyoshi** [comment]
What do you think about this solution for displaying slugs in selects?
```diff
Index: saleor/dashboard/product/forms.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- saleor/dashboard/product/forms.py	(date 1521691293000)
+++ saleor/dashboard/product/forms.py	(revision )
@@ -11,6 +11,7 @@
     AttributeChoiceValue, Collection, Product, ProductAttribute, ProductImage,
     ProductType, ProductVariant, Stock, StockLocation, VariantImage)
 from ..forms import RichTextField
+from ..widgets import StaffValuesMultipleChoiceField, StaffValuesChoiceField
 from .widgets import ImagePreviewWidget
 
 
@@ -59,6 +60,9 @@
 
 
 class ProductTypeForm(forms.ModelForm):
+    variant_attributes = StaffValuesMultipleChoiceField(queryset=ProductAttribute.objects.all())
+    product_attributes = StaffValuesMultipleChoiceField(queryset=ProductAttribute.objects.all())
+
     class Meta:
         model = ProductType
         exclude = []
Index: saleor/dashboard/widgets.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- saleor/dashboard/widgets.py	(date 1521691293000)
+++ saleor/dashboard/widgets.py	(revision )
@@ -35,3 +35,27 @@
         if attrs:
             default_attrs.update(attrs)
         super().__init__(default_attrs)
+
+
+class StaffValuesChoiceFieldMixin(object):
+    DEFAULT_REPR_ATTR = '__str_staff__'
+
+    def __init__(self, queryset, *args, **kwargs):
+        self._representation_attribut = kwargs.pop('representation_attribute', self.DEFAULT_REPR_ATTR)
+        super(StaffValuesChoiceFieldMixin, self).__init__(queryset, *args, **kwargs)
+
+    def _get_attribute_for_node(self, node):
+        return getattr(node, self._representation_attribut)
+
+    def label_from_instance(self, node):
+        """Creates labels which will represent each node when generating option labels."""
+        result = self._get_attribute_for_node(node)
+        return result
+
+
+class StaffValuesChoiceField(StaffValuesChoiceFieldMixin, forms.ModelChoiceField):
+    pass
+
+
+class StaffValuesMultipleChoiceField(StaffValuesChoiceFieldMixin, forms.ModelMultipleChoiceField):
+    pass
Index: saleor/product/models.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- saleor/product/models.py	(date 1521691293000)
+++ saleor/product/models.py	(revision )
@@ -392,10 +392,12 @@
         ordering = ('slug', )
 
     def __str__(self):
-        # debug purposes!
-        # return '{0.name} ({0.slug})'.format(self)
         return self.name
 
+    @property
+    def __str_staff__(self):
+        return '{0.name} ({0.slug})'.format(self)
+
     def get_formfield_name(self):
         return slugify('attribute-%s' % self.slug, allow_unicode=True)
```

**Comment by elwoodxblues** [comment]
I think your solution is fine. A model property looks like a good place to put custom model representation that can be consistently used across the dashboard.

**Comment by patrys** [comment]
I don't like the idea of naming it `__str_staff__`. Names starting and ending in double underscores are reserved for Python internals.
