### ISSUE TITLE
Be able to manually capture a given amount on order

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1908]
Hello,

If we go in order details in dashboard, we are unable to change the payment status. What we can do to fake it, is to dispatch the order, but it doesn't capture the amount.

We should add a way to manually set the captured amount/ set to fully paid.

If the captured amount is equal to the total, it would automatically flag as fully paid.

Edit: we can capture if there has been a payment, but for example, if client paid us in real life, we would need to confirm that.

**Comment by elwoodxblues** [comment]
We definitely need this. It will be also required for creating orders through the dashboard.
