### ISSUE TITLE
Can we create smart basket based on their buying pattern

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [mirumee/saleor#1916]
Can we create smart basket based on their buying pattern. It may help in groceries/monthly order segment.

**Comment by elwoodxblues** [comment]
I'm not sure I understand correctly, what do you mean by "smart basket"?

**Comment by rafalp** [comment]
I'm guessing this is about detecting shopping patterns and suggesting next item based on what user already has in the cart? Ergo "You've added bread to you cart, would like butter, milk and cheese as well?"

**Comment by maltitco** [comment]
It works on the principle of related products, is this improvement planned in saleor?

**Comment by elwoodxblues** [comment]
It's not on the roadmap currently, but I'm sure this is something that we'll want to eventually have. Adding a simple mechanism to manually assign related products doesn't sound like much effort and would cover most cases. ML-based solution is not in our scope currently.

**Comment by Jeyakumarrathnaselvi** [comment]
Example : your have ordered 20 different products last few months. It will be there in smart basket. May be add configurable rules(admin) to add products in smart basket if it is ordered more than once. 

This will reduce customers total time to place order.

Suggestions must be shown while placing order so they can pick while ordering as mentioned by rafalp

**Comment by elwoodxblues** [comment]
As I wrote earlier, this is not planned for the next few releases, but it's on our minds to add such features once we sort our current priorities.
