### ISSUE TITLE
No total french translation during the checkout (for first name, last name, street address...)

### ISSUE THREAD

**Issue by opticrew** [mirumee/saleor#1917]
### What I'm trying to achieve

I want that my saleor's site is automatically translated in French thanks to i18n.

### Steps to reproduce the problem

I set in "fr-FR" for the language_code in my settings.py 

### What happened instead/how it failed

But during the checkout everything is translated into French excepted :
Company Name
First name
Last name
Street address 1
Street address 2
City
Country
Phone

Someone can help me ?

**Comment by patrys** [comment]
@elwoodxblues This looks like a bug, our address forms use "given name" and "family name". Where do these strings come from?

**Comment by opticrew** [comment]
It's for www.mysite.com/checkout/shipping-address/

**Comment by Pacu2** [comment]
I think it's related to #1648

**Comment by patrys** [comment]
It's also broken in the current demo store.

**Comment by opticrew** [comment]
I understand that the solution is in the account/i18n.py file but I don't know how to solve the problem...

**Comment by NyanKiyoshi** [comment]
Should be fixed now :smile:
