### ISSUE TITLE
Webpackbundle problem

### ISSUE THREAD

**Issue by austineinstein** [mirumee/saleor#1921]
In trying to update to the current version of saleor 

I have confused my webpack 

everything builds ok but when i run python manage.py runserver

I get
<img width="1377" alt="screen shot 2018-03-15 at 05 58 51" src="https://user-images.githubusercontent.com/12557036/37446848-d27b05a2-2816-11e8-9af0-e699eb926f1f.png">

heres the crash

<img width="1163" alt="screen shot 2018-03-15 at 06 00 54" src="https://user-images.githubusercontent.com/12557036/37446854-dff230a2-2816-11e8-95d5-120734f0d18b.png">

**Comment by elwoodxblues** [comment]
We got rid of `vendor` bundle some time ago. Looking at the `base.html` I assume you're using an older version of Saleor. Please try pulling the latest master and rebuild your static files with `npm run build-assets`.
