### ISSUE TITLE
Install saleor version v2018.02 failed

### ISSUE THREAD

**Issue by lieuvinhthu** [mirumee/saleor#1922]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve

I'm trying to install Saleor version v2018.02 in Window 7.
The Saleor version v2018.01 is worked

### Steps to reproduce the problem
python manage.py migrate 

### What I expected to happen
From django_prices.models import MoneyField
ImportError: cannot import name 'MoneyField'
...

### What happened instead/how it failed
![image](https://user-images.githubusercontent.com/9067918/37448300-5dde3c04-2858-11e8-8b30-6c85622df3c0.png)

...

(Please include a stack trace if this problem results in a crash.)

**Comment by rafalp** [comment]
Hey, we've updated `django_prices` to new version sometime ago, together with few other libraries, and you should update them too before installing Saleor `v2018.02`.

I've also looked at your stacktrace and I don't see you using any solution for isolating dependencies between installed python apps. This makes running multiple python projects *very* error prone.

**Comment by Pacu2** [comment]
Closing for now, please reopen if you have any further problems.
