### ISSUE TITLE
Deleting a category deletes all subcategories and their products

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#1928]
Since there's no way to undo deleting one of the main categories is a great way to accidentally get rid of most if not all of your products. The only remedy is restoring the entire store from a recent backup.

**Comment by maarcingebala** [comment]
I think we could revisit this issue. As @NyanKiyoshi noticed we'd have to change the model to allow for `null` values in the `Product.category` relationship.

**Comment by maarcingebala** [comment]
We would have to somehow tell the users that category needs to be assigned to start selling the product. I see two options here:
- display a warning message in the dashboard UI if no category is set
- add a check in the `Product.is_available` property to include checking if a category is set. If it's null, product would be simply unavailable for customers.

**Comment by maarcingebala** [comment]
Actually both of these options could work together :)
