### ISSUE TITLE
i can't find the versatileimagefield.css file

### ISSUE THREAD

**Issue by woodme0000** [mirumee/saleor#1931]
hi ,i am sorry , when  i am reading your code,  i can't find the versatileimagefield.css file in project.

step 
1' i had install the  'pip install django-versatileimagefield'
2. when i go into the  PROJECT/templates/dashboard/base.html, there have：
      <link rel="stylesheet" type="text/css" href="{% static "versatileimagefield/css/versatileimagefield.css" %}">

but  in the saleor/static directory, i can't find the  file....

i am studing you code, can you tell me ,how to find or study the  'versatileimagefield.css' file

**Comment by NyanKiyoshi** [comment]
Hiya!

This is from the module `django-versatileimagefield` if that's the question. Here is the file: https://github.com/respondcreate/django-versatileimagefield/blob/master/versatileimagefield/static/versatileimagefield/css/versatileimagefield.css

`django-versatileimagefield` is a django module, it's registered in `saleor.settings.INSTALLED_APPS`. When trying to get static files, django first looks into saleor's static directory, then if it fails, tries to look into the installed apps.

Hope it answers your question.

**Comment by woodme0000** [comment]
yes, i had find it, you are good man, i am newer!~~so ......

3ks!~~

very much
