### ISSUE TITLE
Question: Is there any API documentation?

### ISSUE THREAD

**Issue by Jgerardopine** [mirumee/saleor#1936]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
We need to communicate some actions with scripts that will be part of other services.
In order to do so, we would need to communicate Saleor with our services through an API, butI don't see any documentation showing the endpoints

### Steps to reproduce the problem
1.NA
### What I expected to happen
NA

### What happened instead/how it failed
NA

(Please include a stack trace if this problem results in a crash.)

**Comment by elwoodxblues** [comment]
Hey, we're building a GraphQL API right now and unfortunately, at the moment we don't have any documentation and endpoints for all the models. Current work-in-progress storefront's API is available under `/graphql/` and it allows you to fetch products, categories and product attributes. We are also working on a separate API for the dashboard (`/dashboard/graphql/`). Our plan is to have both APIs ready in June/July releases this year ([roadmap](https://github.com/mirumee/saleor/projects/6)).

**Comment by elwoodxblues** [comment]
I'm closing this if there are no further questions and open a dedicated issue for adding API documentation.
