### ISSUE TITLE
JSONDecodeError at /

### ISSUE THREAD

**Issue by nmasella** [mirumee/saleor#1937]
Hi,

i'm trying to view Saleor with my browser but I have following error

JSONDecodeError at /

Expecting value: line 1 column 1 (char 0)

this is a screen of my error:

![screencapture-localhost-8000-2018-03-17-19_00_43](https://user-images.githubusercontent.com/198417/37558524-a4c74390-2a15-11e8-8207-c2d639267a63.png)

**Comment by NyanKiyoshi** [comment]
Hello!

Looks like there is an issue with the file `webpack-bundle.json` (at `/Users/nicolamasella/Documents/Code/saleor/webpack-bundle.json`). Did you run `npm i` then `npm run build-assets --production` in your saleor project (`/Users/nicolamasella/Documents/Code/saleor/`)?

I would recommend you to rerun these two commands even if you did or didn't already do that as they may be the source of the issue from what we can see on the stack.

**Comment by nmasella** [comment]
Hi,

thank you very much NyanKiyoshi, now it works.

**Comment by querybridge** [comment]
Same issue but had to restart docker (up/down/up)
