### ISSUE TITLE
Storefront navbar header does not hide when scrolling down in mobile

### ISSUE THREAD

**Issue by maniotrix** [mirumee/saleor#1938]

**Comment by maniotrix** [comment]
I find it necessary to hide the navbar when scroliing down and show when user scrolls up.

**Comment by Pacu2** [comment]
Hi @maniotrix 
Such change should should be implemented via CSS and JS individually for your shop, we don't offer this functionality in Saleor at this moment.
I think this might be helpful: https://medium.com/@mariusc23/hide-header-on-scroll-down-show-on-scroll-up-67bbaae9a78c

**Comment by maniotrix** [comment]
Thanks for your time and support @Pacu2 .
