### ISSUE TITLE
Some tests for dashboard logic are mixed with non-dashboard tests outside of /tests/dashboad

### ISSUE THREAD

**Issue by rafalp** [mirumee/saleor#1950]
Note for keeping:

Some of dashboard's logic tests are outside of `/tests/dashboard`, or even mixed with other tests:

- `/tests/test_collection.py` has tests for collections CRUD
- `/tests/test_products.py` has tests for dashboard product suggestion engine

Those tests may be found by searching for `reverse('dashboard:` string in our tests directory.

**Comment by Pacu2** [comment]
I did a little clean up to collections tests in #1882, however the rest still needs addressing
