### ISSUE TITLE
Drop variant name field

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1957]
Currently `ProductVariant.name` field is not particularly useful. Moreover, it causes some confusion in code when it comes to variant representation. and should be dropped. In my opinion, we should drop this field and use variant attributes as a name. We already do it, but our model allows variants without attributes which doesn't make much sense and we should eventually change it, but for now we could use SKU as fallback.

**Comment by elwoodxblues** [comment]
Related issue: #1846

**Comment by elwoodxblues** [comment]
One problem with creating variant name from its attributes is that we need to prefetch them in advance to get their names. Maybe a better idea would be to keep the `name` field and update it accordingly when attributes change? What do you think?

**Comment by patrys** [comment]
For reference, Shopify seems to set the variant title on change and it returns `Black / 10` in the API (notice how it does not contain the product title).

**Comment by elwoodxblues** [comment]
I think it's a good idea that would save us from:
- problems with prefetching the attributes
- confusion about how to represent the variant

**Comment by patrys** [comment]
In that case we lack one feature that Shopify offers: their attributes have a defined order.

**Comment by elwoodxblues** [comment]
Why is this a problem?

**Comment by patrys** [comment]
It's only a problem if you have preference of either "Black / 10" or "10 / Black".
