### ISSUE TITLE
New orders in the client's panel do not appear

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor#1960]
After updating to the dev version commit afc26b0 new orders in the client's panel do not appear.
In the dashboard is ok.

**Comment by elwoodxblues** [comment]
@mad-anne Could you take a look?

**Comment by mad-anne** [comment]
Hi @maltitco, I can't reproduce your problem - orders are always visible for customer. Could you please provide more details?

**Comment by maltitco** [comment]
@mad-anne the problem is in the display order:
<img width="987" alt="zrzut ekranu 2018-03-22 o 12 33 21" src="https://user-images.githubusercontent.com/1561204/37768308-6749e5c0-2dcd-11e8-884c-ed704845f43e.png">
in DB view:
<img width="341" alt="zrzut ekranu 2018-03-22 o 12 47 27" src="https://user-images.githubusercontent.com/1561204/37768819-3fe9fbe4-2dcf-11e8-8dd8-2b9fa8862f42.png">
