### ISSUE TITLE
Category missing on the home and other page.

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor#1961]
After updating to the dev version commit afc26b0 category missing on the home and other page.
<img width="1196" alt="zrzut ekranu 2018-03-22 o 11 38 48" src="https://user-images.githubusercontent.com/1561204/37765913-c36b040e-2dc5-11e8-9996-4c8c3f4b2e2b.png">

**Comment by elwoodxblues** [comment]
We've added a `menu` app that lets you organize all the menus yourself from the dashboard. When setting up a clear copy `python manage.py populatedb` should create two example menus. If not, go to "Dashboard > Navigation" where you can configure it.

**Comment by Pacu2** [comment]
It's a feature!

**Comment by maltitco** [comment]
@elwoodxblues it works ;)
