### ISSUE TITLE
Chevron up on category filter is huge

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor#1962]
After updating to the dev version commit afc26b0 - arrow up on category filter is huge:
<img width="678" alt="zrzut ekranu 2018-03-22 o 11 50 31" src="https://user-images.githubusercontent.com/1561204/37766527-708ce0e8-2dc7-11e8-8bd1-d06f7d35097b.png">

**Comment by dominik-zeglen** [comment]
Did you rebuild front-end assets? It looks like browser loaded old css with new markup.

**Comment by maltitco** [comment]
@dominik-zeglen front-end assets were rebuilt but chrome still loaded old ccs.
flush cache - helps
