### ISSUE TITLE
[I18n] Sales decorations character limit breaking the design

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1965]
Hello!

We have an issue with the sales decoration in some languages. At least for the French locale.

![](https://i.imgur.com/rxTKIJW.png)

The text doesn't fit like said in the notes for the translators.

https://github.com/mirumee/saleor/blob/95f88885367dfe1b40bc59c882ccc0df5123df4b/templates/_items.html#L22-L30

She shortest way to say this in French would be "Promo" ("Promotion") or "Offre" ("Offer") which also break the design.

Is there no way to fix this so it fits?

**Comment by patrys** [comment]
We've discussed replacing these badges with something similar to [what Chrome Industries does](https://www.chromeindustries.com/bags/?start=0&sz=36#tile-0).

**Comment by NyanKiyoshi** [comment]
I see! Seems cleaner and easier to customize!

**Comment by patrys** [comment]
Yes, I imagine we could even use the offer name instead of the generic "sale".

**Comment by Pacu2** [comment]
Solution proposed in #2146 will resolve this problem
