### ISSUE TITLE
[discussion] Allowing customers to buy products without stock

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1979]
Hello,

As I recently spoke with @elwoodxblues, we said it could be interesting to allow customers buy products without checking the stock level and, thus without reducing the stocks.

The current progress on our store are making that we will need to—and will implement this during the coming days.

I would like to take some time to get some thoughts from Saleor's team as I would like to submit a pull request (I'm gonna try to open before Thursday or Friday hopefully) to officially integrate this feature into Saleor.

### The reasons behind this feature
- We, and some other stores, and businesses are working on "tight flows", just-in-time deliveries;
- We, businesses working on that stock model, only have a few items in stock, which are whether used for IRL sells, demos or for showrooms.

### Example

Currently, shopify handle this issue by putting a little checkbox to set the stock to allow customers to purchase even if it's out of stock as below.
![](https://i.imgur.com/YzyLBis.png)

### Proposition

- I would suggest and, currently would be going for **adding a new field in the `Stock` model** (`saleor.dashboard.product.forms.StockForm`).
We are currently checking stock when adding to cart by posting to `/products/<slug>-<pk>/add/` with `variant` & `quantity` as parameters. Which means there is hopefully no javascript code to change as of now;
- With this new field set in at least one of the stock of a product variant will mean that we won't check the stock level;
- We will only reduce stock level if a stock without this flag is available. Otherwise we don't reduce.

I think this would be the best way, as we could reduce stocks that are not in just-in-time delivery when they are available.

----

I would really like to hear your thoughts before starting working on it. Thanks a lot! :+1:

**Comment by elwoodxblues** [comment]
This sounds very good. In the future, we're planning to drop multiple stock locations as we find it overcomplicated, so eventually, there will be single stock item per variant.

**Comment by NyanKiyoshi** [comment]
I see.
As I now, I know that we have only one stock location, which means per supplier per product and thus, per variant. That's understandable to remove stock locations and easily droppable.

Thanks for the information!

**Comment by NyanKiyoshi** [comment]
As you are planning on dropping multiple stock, we care about reducing other stock quantities if the `can_ignore_stock` flag is set on one but other stock doesn't have it set?

I think I won't implement the stock reduction of stocks that doesn't have the flag set when others have on the variant.

https://github.com/VanilleBid/weekly-saleor/pull/120/files#diff-dbeee0803f307c3b8099a139fc8da5beR97

**Comment by elwoodxblues** [comment]
We should be reducing stock quantities anyway so we keep track on how many items were sold. What `can_ignore_stock` flag could do is to allow for a negative quantity value. In the case above I would expect stockA reduced to 0 and stockB reduced to -2. 

This would be much easier after we remove multiple stocks (I'll add an issue in a minute). Right now we can either take multiple stocks into consideration in the calculations or we should hold this feature until we have one stock item.

**Comment by elwoodxblues** [comment]
Btw. also a good name for this flag would be `allow_overselling`, what do you think?

**Comment by elwoodxblues** [comment]
Related issue: #1994

**Comment by it-all** [comment]
I recommend storing 2 separate fields: 1 for actual physical sku stock on hand, and 1 for the number or special/back orders. I've designed a custom ecom system using 1 field which can go negative, but we occasionally have the situation where we have an item in stock that we don't want to ship out for an order*, so the on hand stock should be 1 (so we can sell what we have to another customer) not 0.

*In our case it's for apparel and has to do w/ dye lots - complicated, and not something we'd want to make into separate skus.

**Comment by patrys** [comment]
@it-all It sounds like you've made the conscious decision to track physically different products under the same SKU. To me that sounds like a compromise and I don't think it's worth making stock tracking a complex task for everyone else.

The way Saleor tracks stock there are two values: stock at hand and stock allocated. Negative stock means that the allocated number is higher than the number in stock, not that the stock level is negative. The number at hand should always accurately represent the state of your warehouse and both numbers are decreased as an order is shipped.

**Comment by it-all** [comment]
@patrys Yes, I have made that compromise for these edge cases that affect less than 1% of orders where dye lot has to be taken into account in addition to the standard color and size variants. Perhaps I should add a dye lot variant to some (or all) products.

There could potentially be other reasons, though, for having a product sku on hand and not wanting to ship it for an order (maybe the customer is going on vacation), but still wanting the ability to be able to sell and ship immediately the one on hand to another customer. 

I'm completely ignorant of the internal workings of Saleor, but it sounds from your comment that there are two values and this is possible. That wasn't what I gathered from reading the issue comments above yours.

**Comment by derickkemp** [comment]
This would also be a very useful setting for drop shippers, who don't keep any stock on hand. The easy (but ugly) work around that we're currently using is just setting the stock number very high on all products with a manage.py job.

**Comment by NyanKiyoshi** [comment]
That's really nice to hear. Just to keep updated, I'm planning into working on this issue during the end of this week. And then will keep updated on the solution.
I'm really sorry that many of my contributions are stuck at the moment, I'm swamped with work.

Thanks again for the answers !

**Comment by sycts88** [comment]
Hi, 
may i ask the below issue.  I have downloaded the latest saleor dashboard, master and storefront.  However the images are not loading in storefront and dashboard
