### ISSUE TITLE
Error: Cannot find module 'C:\Users\vio\Desktop\My_Django_stuff\saleor\node_modules\webpack\bin\webpack.js'

### ISSUE THREAD

**Issue by chiranjitkuiry** [mirumee/saleor#1982]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve

...

### Steps to reproduce the problem

1.
2.

### What I expected to happen

...

### What happened instead/how it failed
npm run build-assets 
...
show me this error 
(Please include a stack trace if this problem results in a crash.)
> saleor@0.0.0 build-assets C:\Users\vio\Desktop\My_Django_stuff\saleor
> node ./node_modules/webpack/bin/webpack.js -p --progress

module.js:557
    throw err;
    ^

Error: Cannot find module 'C:\Users\vio\Desktop\My_Django_stuff\saleor\node_modules\webpack\bin\webpack.js'
    at Function.Module._resolveFilename (module.js:555:15)

    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor@0.0.0 build-assets: `node ./node_modules/webpack/bin/webpack.js -p --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vio\AppData\Roaming\npm-cache\_logs\2018-03-27T07_30_32_261Z-debug.log

And I am update node sass to 4.7.x and my node version is 9.5

How do I fix this problem ??

**Comment by NyanKiyoshi** [comment]
Did you run `npm i` before?

**Comment by Pacu2** [comment]
We have step by step installation docs for Windows. You can find them at [readthedocs](http://saleor.readthedocs.io/en/latest/gettingstarted/installation-windows.html)

**Comment by chiranjitkuiry** [comment]
I am following installation for windows, and everything works fine, till I hit this command npm run build-assets . And got the above problem. And yes I ran the command npm i

**Comment by Pacu2** [comment]
Did you run into any errors during `npm install`?
You may try deleting `node_modules` and reinstalling all packages.

**Comment by chiranjitkuiry** [comment]
I did, but got the same problem. :(

**Comment by Pacu2** [comment]
Were there any errors during `npm install`?

**Comment by patrys** [comment]
The scripts in `package.json` are incorrect. They should be (I've only listed the lines that need to change):

```
{
  ...
  "scripts": {
    "build-assets": "webpack -p --progress",
    ...
    "start": "webpack -d --watch --progress",
    ...
  }
}
```

**Comment by chiranjitkuiry** [comment]
no there was not a problem during npm install. I tried "Mr Patrys " solution and it told me download  webpack CLI . Below the error code 

> saleor@0.0.0 build-assets C:\Users\vio\Desktop\My_Django_stuff\saleor
> webpack -p --progress

The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor@0.0.0 build-assets: `webpack -p --progress`
npm ERR! Exit status 1
npm ERR!

npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vio\AppData\Roaming\npm-cache\_logs\2018-03-27T10_49_26_726Z-debug.log

I download the webpack cli using this command npm i webpack-cli. Then I ran the command "npm runn build-assets" but again it gives me above error

**Comment by maarcingebala** [comment]
Please update to latest Saleor, reinstall all dependencies and rebuild assets. If the issue still occurs, please reopen the issue.
