### ISSUE TITLE
Refactor checkout_success view

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1987]
The `checkout_success` view is currently used as a success callback for payment gateways, but it also allows to register a new user and assign a new order to the existing user account. These functionalities should be split into separate views.
- some payment gateways call POST response for success callback; currently, this results in 403 error, since this view is protected as it may change the database state
- more granular views are easier to maintain

**Comment by elwoodxblues** [comment]
Related discussion in PR #1967.

**Comment by szymi-** [comment]
Just to make sure we are on the same page: at the moment, after completing payment using a payment gateway, I get redirected to a url using the checkout_success view, like in the screenshot below. I used my branch to generate this screen, in which the checkout_success view is decorated with @csrf_exempt. The page displayed correctly despite payment gateway posting some data without csrf token or cookie when redirecting me there. The "why not create an account" form was displayed (or, if I happened to use an email of a registered user, I would see something like "hey, log in and add associate this order with your account"). After the change, when completing the successful payment, we would just be redirected to a simple view saying "thank you for your order", without the ability to log in or create an account.

So the goal is to have two separate urls, using two separate views, eg:

 - payment_success
 - checkout_success

Before I try fixing this issue, please let me know if my understanding is correct and also:

 - can you give me another example path leading to checkout_success view, but not via a payment gateway page? It would be useful for testing.
 - should the new view payment_success include a link to the checkout_success page? Or should the functionality of linking order with account or creating an account after successful payment be dropped altogether?

![selection_101](https://user-images.githubusercontent.com/7512741/38028559-8de32d20-3293-11e8-8b99-5dffda38b77d.png)

**Comment by elwoodxblues** [comment]
1. I think the only way to get this view is as a result of the successful payment.
2. We should keep the functionality, but it has to be moved to another view. So I guess `payment_success` should render a link redirecting to `checkout_success` and `checkout_success` would only render forms which are currently in the `checkout_success_anonymous.html` template.

**Comment by szymi-** [comment]
Ok, thanks.

**Comment by elwoodxblues** [comment]
Fixed by #2012
