### ISSUE TITLE
Drop Stock model

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#1994]
We should simplify our inventory model that currently assumes that a variant can have multiple stock records. It's a specific case that could be implemented as a customization by those who actually need it. In our case, it would be much simpler (in terms of UI and the code) while still covering most use cases, if we moved quantity tracking to the ProductVariant model.

As a result, ProductVariant would have additional fields:
- `quantity`
- `quantity_allocated`
- `cost_price`

**Comment by NyanKiyoshi** [comment]
Heya!

I would like to have some thoughts about something. As we can see on #1996, permissions `product.view_stock_location` and `product.edit_stock_location` were dropped and replaced by `product.view_product` and `product.edit_product`. Which is quite normal, as we dropped stock model.

So, now... Here is my question: do you think we should add a permission to view and edit the stock data of a variant / product?

I think, it makes sense to add this kind of permission/ restrictions for staff users, as we may not want in some cases to allow some members to edit the stock information, but still be able to edit variants/ products.

In our case, we do need this permission, and a permission of this kind was added/ fixed recently on our side (permission to view stock information on a variant/ product).
But as of now (#1996), if we would want to restrict the access, we would have to make two forms. Which in a template, would and can be in the same form. So someone that has the permissions, can edit the stock while editing a variant, and someone who doesn't, can't edit stock while editing the product.

I will be waiting for your thoughts on that, whether it would by interesting or not to implement in #1996.

---

*I'm currently trying to close a little the differences gap between our/ my Saleor version and the master one, as master is changing a lot recently and will change even more during the following months.*

---

Thank a lot :ok_hand:

**Comment by Pacu2** [comment]
@NyanKiyoshi 
We've considered that, but in order to simplify as much as possible we've decided that 'edit product' permission might be enough, for both, product & stock editing.

**Comment by patrys** [comment]
We could separate the permissions but then we could end up with a configuration where the person adding products can only complete half of the steps and would then need to ask another person to add the stock information. What if the other person has the stock permission but not the product management permission? What does the UI look like?
