### ISSUE TITLE
Display logo in emails without internet access

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#1999]
I really think we would shouldn't be putting [our logo as a link to our remote server](
https://github.com/mirumee/saleor/blob/master/templates/templated_email/source/shared/header.mjml#L8).

The reasons are:
- It may generate useless bandwidth to our server/ static server and use customers data;
- We are dependent on a remote server which is not "reliable" (may happen to be unavailable, slow, ...);
- Requires explicit permission from the customer on mail clients most of the time.

Also, despite allowing the remote pictures on the gmail mail client on Android, I never managed to make it load the logo. Not sure why. With, and without static only server.

![](https://i.imgur.com/Nowplxv.png)

(*note: I took the screenshot of one of the local test server emails, as I don't want to display sensitive information. But of course, 127.0.0.1 would not work without any doubt*).

---

**I think that it would be better to just (put) include the SVG file in the mails instead of linking it**, the SVG logo and SVG logos in general have really small footprint.

---

Edit: if we have a S3 bucket for static files, we get both the website domain and the s3 bucket domain (see on the right, where there are black squares).
![](https://i.imgur.com/xWWGcaq.png)

**Comment by elwoodxblues** [comment]
I'm not sure how does embedding SVGs in email templates work, but from what I recall it's still not supported by some of the popular inboxes.

In the line, that you highlighted, the path is constructed in a wrong way - the `{% static %}` template tag resolves the absolute URL when `STATIC_URL`.

**Comment by elwoodxblues** [comment]
@mad-anne Could you take a look when you have time? As far as I remember you were implementing those templates.

**Comment by patrys** [comment]
It's possible to attach the file as an "inline" multipart attachment and reference that in the "src" attribute.

**Comment by cmoralesmx** [comment]
Is this issue still relevant? I would like to work on it. @patrys's solution seems doable, I think I can implement this.

**Comment by maarcingebala** [comment]
This issue is not relevant anymore as we removed a logo from emails. This is part of reworking the email mechanism where we want to move email templates out from the Saleor core repository.
