### ISSUE TITLE
Non super-staffusers shouldn't be able to edit staff users email address

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2000]
A staff user having permissions to edit staff members shouldn't be able to edit staff members email address. Allowing staff members do edit other staff members email address allows to bypass user restrictions.

For example, let's imagine, we are human.resources@example.org, we can add staff users and edit their groups because it's part of our job. But cannot see and edit orders, because it's not part of our job.

Now, we want to be able to create orders and steal information we shouldn't be able to access from the website. Let's imagine, we want to access the commercial, or even worst... The superuser.
**All we have to do, to gain higher privileges (if #1966 is not enough for us!), is to edit the superuser (or the commercial)'s email address to an email address that is in our control and, reset the password and... Enjoy.**

**Comment by NyanKiyoshi** [comment]
Please note that I will open a PR soon for that one as I fixed the issue. So no need to work on it (#1966 soon but didn't fix it yet).

I also wrote tests for the dashboard customers views because I saw there was none (for the views). And moved the ajax listing of customers of dashboard in the dashboard tests folder as it is a dashboard test, irc there is an open issue about moving tests to dashboard.

And also refactored the dashboard customer creation and edition views to make them cleaner, and fixed a bug on success message translation (`pgettext('ctx', 'msg here %s' % this_was_the_bug)`).

**Comment by mad-anne** [comment]
Hi @NyanKiyoshi,
would you like to share changes you metioned in above comment with us? If not, someone from our team could fix this issue soon.

**Comment by NyanKiyoshi** [comment]
Hi!

The changes were at [fix/privilege-escalations](https://github.com/NyanKiyoshi/saleor/tree/fix/privilege-escalations), but only one commit was done https://github.com/NyanKiyoshi/saleor/commit/20a313c1805cf7a6800f8252a3d05678d397c63a. It mainly fix #2000, by checking if the user has greater privileges than the user to be edited.

But those changes are quite messy as of now, I didn't have time to get back to them.

So, if someone wants to take care of those issues, I think it would be best to take over from scratch.

I'm really sorry, I don't have much time available.

**Comment by ajostergaard** [comment]
@NyanKiyoshi in your original example `we are human.resources@example.org, we can add staff users and edit their groups because it's part of our job` - couldn't I just create an account with the permissions I want? If you truly want security at this level you need to split account creation and activation.

Seems to me only superuser should be able to edit staff email addresses (which shouldn't change often), the remaining risks can only be managed through 'human security', e.g. trusting staff and background checks (if necessary).

**Comment by NyanKiyoshi** [comment]
@ajostergaard Yes, it is #1966.

Only the user owning the account and super users should be able to edit staff email addresses.

**Comment by patrys** [comment]
@ajostergaard I don't think any actions should be reserved to super users. I don't encourage having such accounts on production servers.

**Comment by ajostergaard** [comment]
@patrys I don't disagree but eventually at some level we have to break a stalemate and the only solutions are to remove risky features, trust or the doer/approver model.

@NyanKiyoshi I don't think #1966 is the solution, if I am HR I should not edit orders but I need to be able to setup a user who can edit orders... If you try to solve this using hierarchy eventually you either need a super user or you replace super user with elevated admin which is the same thing.

A slightly tangential idea which might mitigate some risk would be to only allow staff to have email addresses on the business domain (e.g. @mirumee.com), essentially pushing some responsibility to the mail server admins, combined with making staff email addresses read only and activating account by proving access to the email account? That way an evil HR can't hijack an account or easily create a new one. This should mitigate a fair amount of risk without being an undue burden on most businesses though I realise the business email part of it could be unpopular with some 'unruly' admins. :)

As far as I can tell the only way to safeguard 'self-elevation' is for all permissions changes to be done by one person and approved by another... For example using something https://github.com/dominno/django-moderation
