### ISSUE TITLE
 can you supply the rich text editer

### ISSUE THREAD

**Issue by woodme0000** [mirumee/saleor#2001]
thank you very much,

i am study you code,

i found ,if  i  want to edit article ,it was a  rich text, contains  some image,some video and some text, 

then  i can't to do it .

may be  in the code ,it support the feature, but i don't find it.

give you a picture, is the wechat rich text editer. if we have this ,i think ,the saleor will be very good!~~

demo1: the detail is editer by the rich text editer 
https://www.duocaitou.com/project/detail/id/bEhzY0FMQUxvb009#invest_return  t
demo2: the wechat 
https://mp.weixin.qq.com/cgi-bin/appmsg?t=media/appmsg_edit&action=edit&type=10&isMul=1&isNew=1&lang=zh_CN&token=1808348470

![image](https://user-images.githubusercontent.com/10584910/38078972-6fa52b82-3370-11e8-9c50-6eb044b7ecef.png)

**Comment by NyanKiyoshi** [comment]
So, what you are saying, is that you are not able to put videos and pictures, or at least, to find those features in the rich text editor?

**Comment by NyanKiyoshi** [comment]
I just tried. We can drag and drop pictures and it will show it on the preview. But... That's it. When trying to view the pictures on the result page, it doesn't work.

On the left, are the results on the static page. And on the right, the POST request to create the static page with a picture. Not sure, may be a bug.

![screenshot](https://i.imgur.com/D9vjkei.png)

And videos... You cannot... Yet at least.
