### ISSUE TITLE
Add notes to customers

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2013]
Hello, this is a quick feature suggestion for Saleor.

- Be able to add notes to customers through the dashboard (e.g. self/team-reminders, warning, information about customer, etc.);
- Be able to see those notes when we are creating an order for a given customer, as it may be useful or important (needs #1971).

I recently saw that shopify has this feature as well, but didn't try it out.

----

As screenshots are speaking a lot, here is the current implementation:

### Customer form (RichText)
![](https://i.imgur.com/QhHdaN5.png)

### Customer details
![](https://i.imgur.com/JSw2vPH.png)

### Order creation, with this customer selected
![](https://i.imgur.com/bKT9yE0.png)

----

I want your thoughts about this feature, I think it would be great to add it to everyone.

**Comment by Pacu2** [comment]
Maybe we could follow Order Notes convention here? I think we should track who added which note, specially if based on notes, one want to apply some discounts manually.

**Comment by NyanKiyoshi** [comment]
I think, keeping track of who added which note is a good idea!

This is also what Shopify does, which quite look nice.

![](https://i.imgur.com/xtxbiYb.png)

**Comment by Pacu2** [comment]
Seems related to Timeline, which is planned for April's roadmap https://github.com/mirumee/saleor/projects/6#card-7287412

**Comment by NyanKiyoshi** [comment]
Interesting, I didn't see that one. Thanks for pointing it to me!
