### ISSUE TITLE
Shortening the check out -> payment path

### ISSUE THREAD

**Issue by szymi-** [mirumee/saleor#2018]
There are seven steps required to get from the shopping cart to complete payment (plus however many steps on the payment provider's site). I think this is a rather lengthy process. In my opinion it should be shortened - some of the less patient customers might get bored by a payment process that is longer than in other shops. Even if they complete the first order, the long and boring payment process may prevent them from making future orders. Below is the current seven step path:

cart (/en/cart/): checkout -> log in (/en/checkout/login/) -> shipping address (/en/checkout/shipping-address/) -> shipping method (/en/checkout/shipping-method/) -> billing address, summary (/en/checkout/summary/) -> select payment method (/en/order/<order>/payment/) -> proceed to payment (/en/order/<order>/payment/<provider>/) -> provider

I think it should be shorter:

cart -> log in -> shipping and billing address -> shipping method -> payment

The payment provider selection should happen in Java Script instead of yet another html form (I saw a related card in the roadmap planned for July). Moreover, I think the user should know where they currently are in the process of making a payment - a sort of clear, consistent, tabbed view after the log in (or buy without account) screen would be desirable.

**Comment by maarcingebala** [comment]
We're not planning to change the checkout flow in the old storefront as we're developing the [PWA storefront](https://github.com/mirumee/saleor-storefront/) now which includes a complete redesign of the checkout flow.
