### ISSUE TITLE
Selling contract creation and customization

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2022]
Hello,

As already made by #2021, we, Saleor, would need to allow staff users to add and customize the selling contract of their store.

I would like to discuss with Saleor's team on how to implement the later (selling contract customization process).

### First solution — a simple page

The easiest (as of #2021), would be to create and edit a simple page through Saleor's page mechanism. And thus, of course, if the selling contract page is missing, the user would see a 404 error, so Saleor won't depend on it.

### Second solution — store settings

The more user/ staff friendly (+ we could restrict access through permissions), would be to add options to the store settings, just like Shopify does. Or another way, as we will need to set some settings, for VAT for example, would be inside a law settings or something.

![shopify screenshot](https://i.imgur.com/HgWsOpm.png)

----

What are your thoughts on this?

**Comment by patrys** [comment]
I like Shopify's approach as it means other parts of the store can rely on certain pages existing. Being able to link to the correct terms of service page and privacy policy during checkout are becoming even more important with GDPR right around the corner.

**Comment by NyanKiyoshi** [comment]
I'm thinking about creating a new section named `checkout settings` under `site settings` in dashboard. This section would contain some other sections, as, for example `order processing`, which would contain VAT settings. And thus, also a section `Refund, Privacy and TOS policies`.

What would be the best way to store those policies data? Should we create a new table for storing policies data like we do for `SiteSettings` (have three fields: `Refund`, `Privacy`, `TOS`)?

**Comment by elwoodxblues** [comment]
For now, I would try to solve it with the page mechanism as it would be the simplest solution, not requiring any UI changes. A proposition of implementation:
- In `settings.py` add a configuration of these special pages (a list of slugs, or maybe even slugs with titles plus some commentary about the purpose).
- Add a data migration that creates these pages (if necessary), using the configuration from `settings.py`. As for content, we could leave it empty or on each page generate something like "Example privacy policy page", "Example terms of service page" etc.
- In the delete view for pages add a check that would block the user from removing those.

**Comment by NyanKiyoshi** [comment]
That's a great idea! I will work on this ASAP!

**Comment by stephenmoloney** [comment]
Just wondering the status of this ? @NyanKiyoshi

**Comment by NyanKiyoshi** [comment]
I closed the PR since it was in a stagnant state and thus was needed to be redone for GraphQL and PWA. We need to prove that the user accept the selling contract, so I guess that we would need to force the user to set a parameter to `true` on the GraphQL API otherwise they cannot order anything. Which, proves the user accepted the contract and the seller received the customer's electronic signature.

I could work on it if it will get merged, or it can get picked up.

**Comment by maarcingebala** [comment]
I think it's still relevant.
