### ISSUE TITLE
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):

### ISSUE THREAD

**Issue by suthargk** [mirumee/saleor#2039]
$ npm install

Issue : 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
 

how to fix these warnings?

**Comment by NyanKiyoshi** [comment]
Hello! It's an optional dependency, it's only npm saying that it didn't install the optional dependency as it wasn't needed. `fsevents` is only needed for Mac OS users, not for Linux users (which is your case).

So no worries, you can safely ignore those messages, they are not errors.
