### ISSUE TITLE
ModuleNotFoundError: No module named 'celery'

### ISSUE THREAD

**Issue by milven-domingos** [mirumee/saleor#2042]
Please help i cloned the saleor project and i did pip install and i have configured the postgress database and secretkey. and when i run the following command  manage.py migrate,
i get this.

```
(ecommerce) F:\milven\projects-robobo\ecommerce\saleor>manage.py migrate
Traceback (most recent call last):
  File "F:\milven\projects-robobo\ecommerce\saleor\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\arnal_000\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_l
ne
    utility.execute()
  File "C:\Users\arnal_000\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "C:\Users\arnal_000\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\Users\arnal_000\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\conf\__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\arnal_000\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\conf\__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\arnal_000\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\milven\projects-robobo\ecommerce\saleor\saleor\__init__.py", line 1, in <module>
    from .celeryconf import app as celery_app
  File "F:\milven\projects-robobo\ecommerce\saleor\saleor\celeryconf.py", line 4, in <module>
    from celery import Celery
ModuleNotFoundError: No module named 'celery'

(ecommerce) F:\milven\projects-robobo\ecommerce\saleor>
```

**Comment by patrys** [comment]
Did you get any errors during `python -m pip install -r requirements.txt`?

**Comment by milven-domingos** [comment]
no, when i run manage.py migrate

**Comment by milven-domingos** [comment]
and i have installed celery package manually to certify if it was installed correctly with pip install, and the import error its comming from. saleor/saleor/celeryconf.py

**Comment by patrys** [comment]
Could you provide the output of `python -m pip freeze`?

**Comment by milven-domingos** [comment]
here is the output
`(ecommerce) F:\milven\projects-robobo\ecommerce\saleor>python -m pip freeze
amqp==2.2.2
anyjson==0.3.3
asn1crypto==0.24.0
attrs==17.4.0
Babel==2.5.3
billiard==3.5.0.3
bleach==2.1.3
boto3==1.5.31
botocore==1.8.45
braintree==3.39.1
cairocffi==0.8.0
CairoSVG==2.1.3
celery==4.1.0
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
colorama==0.3.9
cryptography==2.1.4
cssselect2==0.2.1
defusedxml==0.5.0
dj-database-url==0.4.2
dj-email-url==0.0.10
Django==2.0.3
django-babel==0.6.2
django-bootstrap4==0.0.5
django-cache-url==2.0.0
django-celery==3.2.2
django-celery-results==1.0.1
django-countries==5.2
django-debug-toolbar==1.9.1
django-elasticsearch-dsl==0.4.4
django-environ==0.4.4
django-filter==1.1.0
django-fsm==2.6.0
django-graphql-jwt==0.1.9
django-impersonate==1.3
django-js-asset==1.0.0
django-mptt==0.9.0
django-payments==0.12.1
django-phonenumber-field==2.0.0
django-prices==1.0.0
django-prices-openexchangerates==1.0.0
django-redis==4.8.0
django-render-block==0.5
django-storages==1.6.5
django-templated-email==2.2.0
django-versatileimagefield==1.9
django-webpack-loader==0.5.0
docutils==0.14
elasticsearch==5.5.2
elasticsearch-dsl==5.4.0
Faker==0.8.11
freezegun==0.3.9
google-i18n-address==2.2.2
google-measurement-protocol==1.0.0
graphene==2.0.1
graphene-django==2.0.0
graphql-core==2.0
graphql-relay==0.4.5
html5lib==1.0.1
idna==2.6
iso8601==0.1.12
jmespath==0.9.3
jsonfield==2.0.2
kombu==4.1.0
Markdown==2.6.11
maxminddb==1.3.0
maxminddb-geolite2==2017.803
multidict==3.3.2
oauthlib==2.0.6
pdfrw==0.4
phonenumberslite==8.9.1
Pillow==5.0.0
pluggy==0.6.0
prices==1.0.0
promise==2.1
psycopg2-binary==2.7.4
purl==1.3.1
py==1.5.2
pycparser==2.18
PyJWT==1.5.3
Pyphen==0.9.4
pytest==3.4.0
pytest-django==3.1.2
pytest-mock==1.7.0
pytest-vcr==0.3.0
python-dateutil==2.6.1
python3-openid==3.1.0
pytz==2018.3
PyYAML==3.12
redis==2.10.6
requests==2.18.4
requests-oauthlib==0.8.0
Rx==1.6.0
s3transfer==0.1.12
singledispatch==3.4.0.3
six==1.11.0
social-auth-app-django==2.1.0
social-auth-core==1.6.0
sqlparse==0.2.4
stripe==1.77.1
suds-jurko==0.6
text-unidecode==1.1
tinycss2==0.6.1
typing==3.6.2
urllib3==1.22
vcrpy==1.11.1
vine==1.1.4
WeasyPrint==0.42.2
webencodings==0.5.1
wrapt==1.10.11
xmltodict==0.11.0
yarl==0.17.0
`

**Comment by patrys** [comment]
Can you try running `python manage.py migrate` instead of `manage.py migrate`?

**Comment by milven-domingos** [comment]
thanks, thanks,  it worked. 
what a silly mistake, when i use django on windows i dont put python ... only in linux
one more time thanks

**Comment by patrys** [comment]
I'm glad it worked!

**Comment by sonal-410** [comment]
> python -m pip install -r requirements.txt

Yes I am having this error after running above command.

 Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: could not determine PostgreSQL version from '11.1'
    
    ----------------------------------------
^[Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4n/3lvnj57504jbvwd3pq33621w0000gn/T/pip-install-gGT0dX/psycopg2/

**Comment by hetendra** [comment]
This is what I get if I check installed requirements-
`python -m pip free

zeapturl==0.5.2
asn1crypto==0.24.0
Brlapi==0.6.6
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
command-not-found==0.3
cryptography==2.1.4
cupshelpers==1.0
defer==1.0.6
distro-info===0.18ubuntu0.18.04.1
Django==1.11.11
httplib2==0.9.2
idna==2.6
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
louis==3.5.0
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.0
netifaces==0.10.4
notify2==0.3
numpy==1.13.3
oauth==1.0.1
olefile==0.45.1
pexpect==4.2.1
Pillow==5.1.0
ply==3.11
protobuf==3.0.0
pycairo==1.16.2
pycparser==2.18
pycrypto==2.6.1
pycups==1.9.73
pygobject==3.26.1
pymacaroons==0.13.0
PyNaCl==1.1.2
pyRFC3339==1.0
python-apt==1.6.5+ubuntu0.2
python-debian==0.1.32
pytz==2018.3
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
requests==2.18.4
requests-unixsocket==0.1.5
SecretStorage==2.3.1
simplejson==3.13.2
six==1.11.0
sqlparse==0.2.4
system-service==0.3
systemd-python==234
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.22
usb-creator==0.3.3
wadllib==1.3.2
xkit==0.0.0
zope.interface==4.3.2
`
