### ISSUE TITLE
Display similar and related products when we click on the particular product

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [mirumee/saleor#2051]
Do we have any option or plans to display similar products below main product clicked. 

It can help customers select product faster by viewing multiple options

Similar means - Same product in different color, brand, size or price

Related means - Product related the product you are viewing now

**Comment by elwoodxblues** [comment]
This feature has been requested a few times already, and we also talked internally about having it. It's on our [roadmap](https://github.com/mirumee/saleor/projects/6) but hasn't been scheduled for a particular release yet. I'll discuss with the team how do we want to approach this and for when we could plan the development.

**Comment by Jeyakumarrathnaselvi** [comment]
Okay. Noted. Looking forward to hear tentative plan.

**Comment by h3** [comment]
I have a simple solution using templatetags, sorry the project I'm working on is pre PWA :/

**myapp/templatetags/similar_products.py**:

```python
from django import template
from django.conf import settings

register = template.Library()

@register.simple_tag(name="get_similar_products_for")
def similar_products(product, limit=5):
    return product.category.products.order_by('?').all()[0:limit]
```

**templates/product/detail.html**:

```html
  {# somewhere in your template #}
  {% load similar_products %}
  {% get_similar_products_for product limit=5 as similar_products %}
  {% if similar_products %}
  <div class="row related-products">
    {% for similar_product in similar_products %}
      {% include "product/_item.inc.html" with product=similar_product %}
    {% endfor %}
  </div>
  {% endif %}
```

Also modified **templates/product/_items.html**:

{% for product, availability in products %}
  {% include "product/_item.inc.html" with product=product %}
{% endfor %}

Moved everything in **templates/product/_items.inc.html** so it can be reused for similar products:

```html
{% load i18n %}
{% load static %}
{% load taxed_prices %}
{% load get_thumbnail from product_images %}
{% load placeholder %}

<div class="col-6 col-lg-3 product-list">
  <a href="{{ product.get_absolute_url }}" class="link--clean">
    <div class="text-center">
      <div>
        <div class="product-image">
          <img class="img-responsive lazyload lazypreload"
               data-src="{% get_thumbnail product.get_first_image method="thumbnail" size=255 %}"
               data-srcset="{% get_thumbnail product.get_first_image method="thumbnail" size=255 %} 1x, {% get_thumbnail product.get_first_image method="thumbnail" size=510 %} 2x"
               alt=""
               src="{% placeholder size=255 %}">
          </div>
        <span class="product-list-item-name" title="{{ product.translated }}">{{ product.translated }}</span>
      </div>
      <div class="panel-footer">
        {% if availability.available %}
          {% price_range availability.price_range %}
          {% if availability.discount %}
            {% if availability.price_range_undiscounted.start != availability.price_range.start %}
              <div class="product-list__sale">
                <span class="product-list__sale__text">
                  {% comment %}Translators: Layout may break if character length is different than four.{% endcomment %}
                  {% trans "Sale" context "Sale (discount) label for item in product list" %}
                </span>
              </div>
            {% endif %}
          {% endif %}
        {% else %}
          &nbsp;
        {% endif %}
      </div>
    </div>
  </a>
</div>
```

**Comment by LeOndaz** [comment]
> I have a simple solution using templatetags, sorry the project I'm working on is pre PWA :/
> 
> **myapp/templatetags/similar_products.py**:
> 
> ```python
> from django import template
> from django.conf import settings
> 
> register = template.Library()
> 
> @register.simple_tag(name="get_similar_products_for")
> def similar_products(product, limit=5):
>     return product.category.products.order_by('?').all()[0:limit]
> ```
> 
> **templates/product/detail.html**:
> 
> ```
>   {# somewhere in your template #}
>   {% load similar_products %}
>   {% get_similar_products_for product limit=5 as similar_products %}
>   {% if similar_products %}
>   <div class="row similar-products">
>     {% for similar_product in similar_products %}
>       {% include "product/_item.inc.html" with product=similar_product %}
>     {% endfor %}
>   </div>
>   {% endif %}
> ```
> 
> Also modified **templates/product/_items.html**:
> 
> {% for product, availability in products %}
> {% include "product/_item.inc.html" with product=product %}
> {% endfor %}
> 
> Moved everything in **templates/product/_items.inc.html** so it can be reused for similar products:
> 
> ```
> {% load i18n %}
> {% load static %}
> {% load taxed_prices %}
> {% load get_thumbnail from product_images %}
> {% load placeholder %}
> 
> <div class="col-6 col-lg-3 product-list">
>   <a href="{{ product.get_absolute_url }}" class="link--clean">
>     <div class="text-center">
>       <div>
>         <div class="product-image">
>           <img class="img-responsive lazyload lazypreload"
>                data-src="{% get_thumbnail product.get_first_image method="thumbnail" size=255 %}"
>                data-srcset="{% get_thumbnail product.get_first_image method="thumbnail" size=255 %} 1x, {% get_thumbnail product.get_first_image method="thumbnail" size=510 %} 2x"
>                alt=""
>                src="{% placeholder size=255 %}">
>           </div>
>         <span class="product-list-item-name" title="{{ product.translated }}">{{ product.translated }}</span>
>       </div>
>       <div class="panel-footer">
>         {% if availability.available %}
>           {% price_range availability.price_range %}
>           {% if availability.discount %}
>             {% if availability.price_range_undiscounted.start != availability.price_range.start %}
>               <div class="product-list__sale">
>                 <span class="product-list__sale__text">
>                   {% comment %}Translators: Layout may break if character length is different than four.{% endcomment %}
>                   {% trans "Sale" context "Sale (discount) label for item in product list" %}
>                 </span>
>               </div>
>             {% endif %}
>           {% endif %}
>         {% else %}
>           &nbsp;
>         {% endif %}
>       </div>
>     </div>
>   </a>
> </div>
> ```

This is a performance killer, never use ?, better query all and randomize with python or search for alternative ways
