### ISSUE TITLE
Extend current shipping methods to include price based shipping

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2054]
Hello,

We are gonna move Saleor into production this Wednesday, and, we are currently using price based shipping methods. :tada:!!

For now, Saleor doesn't include any other shipping methods than Country Based methods, meanwhile, others, like Shopify, are including price based and weight based shipping methods.

I really think Saleor should include this feature, in addition to `Integrations: shipping carriers` (which is part of the roadmap).

What do you think? This is still the issue #2029, but way lighter.

I'm thinking we could pass the cart to `get_shipment_options` and filters the shipment methods by country and for price based country shipment, check the conditions (min cart price, max cart price).

So, we would have a real simple shipment method that would contain:
- a price,
- a cart price range,
- a shipment price (which can be set to free).

---

I will be waiting to hear back from you. I'm creating this issue and not a pull request as editing the shipping methods may not respond correctly to the planned feature path of Saleor.

---

Thank you for your work!

**Comment by elwoodxblues** [comment]
Sounds good, we could include that in Saleor. I'd find it very useful to be able to define free shipping above some specific order total value.

Good luck with the deployment! We're happy that another shop powered by Saleor will be released to production and would love to see it when it's ready!
