### ISSUE TITLE
Sort filters values

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2055]
Hello!

This issue has been discovered some time ago and fixed on our production version. I would like to take some to discuss about a final patch for this issue.

### Filters values sorting
Here is an example, we have 100g, 150g, 200g and 1kg. But we now have a few new products (yay!): 50g and 2kg.

![result - screenshot](https://i.imgur.com/ekx87Zm.png)

So, here we go, we add everything, everything is great and we take a look into the groceries category. Issue: the filters values are unordered. Which means, the customer will have a few logical issues when filtering.

### Proposition
I'm thinking, maybe we could reorder the values when we are adding them (by adding a `position` column for example and cache the sorted data).

---

Edit: while I'm looking at my Saleor checklist, I also note that we shouldn't be showing filters containing no values. This case was happening when using attributes containing no pk values, only text values in products.

**Comment by Pacu2** [comment]
ref #915

**Comment by elwoodxblues** [comment]
I think we had a discussion about it in one of the PRs recently. We agreed that there should be the ability to reorder attribute values.
