### ISSUE TITLE
"Calling get_price_range() on an empty item range" after populatedb

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#206]
After calling `populatedb` command and viewing `/products/category/shirts/` the following error occurs: <pre>AttributeError at /products/category/shirts/
Calling get_price_range() on an empty item range
Error during template rendering
In template /home/marcin/mirumee/saleor/saleor/saleor/product/templates/category/index.html, error at line 23
</pre>
Full traceback: http://dpaste.com/2FMGA9C

**Comment by patrys** [comment]
This is fixed with #268.
