### ISSUE TITLE
Automatic location detection and display products accordingly

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [mirumee/saleor#2065]
Do we have any plans to implement automatic location detection and display the products only near to the location?

**Comment by elwoodxblues** [comment]
Sounds like an exciting feature, but at the moment we're focused on other priorities and haven't planned to tackle it soon. Of course, as with every other feature, we do accept pull-requests from the community, and if anyone else submits even draft of the implementation, we'll take a look and provide every help needed.
