### ISSUE TITLE
Facebook and Gmail login feature

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [mirumee/saleor#2066]
Any plan to integrate facebook and gmail based login to simplify the login experience

**Comment by elwoodxblues** [comment]
This feature is already available. To enable it, go to "Dashboard" > "Site settings" > "Authorization keys". From there you can set up OAuth keys for Google or Facebook.

**Comment by Pacu2** [comment]
I think we should mention that in the docs

**Comment by elwoodxblues** [comment]
True, it's missing. It was added a long time ago in the dark times when we didn't develop the documentation along with the features.

**Comment by patrys** [comment]
Eventually I'd like to refactor this to "Settings > Integrations" as the list is growing longer.

**Comment by Rabia23** [comment]
Can anyone please tell me which password do I need to enter in the screen?
Thanks

<img width="1008" alt="screen shot 2018-10-07 at 9 09 15 pm" src="https://user-images.githubusercontent.com/13939335/46583793-6d632a80-ca75-11e8-90bf-3a3870922e2c.png">

**Comment by Pacu2** [comment]
The oauth2  web application credentials, that you can generate in the Google API Console.

**Comment by Rabia23** [comment]
Thank you @Pacu2

**Comment by maarcingebala** [comment]
Hey @Rabia23, did you resolve your problem? If I'm correct you should set the App ID in the "Key" input and App secret in the "Password" field. Let me know if that worked for you.

**Comment by Rabia23** [comment]
@maarcingebala when I add the facebook OAuth credentials then it redirects me to the following screen.
<img width="1235" alt="screen shot 2018-10-08 at 12 54 52 pm" src="https://user-images.githubusercontent.com/13939335/46597451-8b726e80-caf9-11e8-9dce-e69e092752a6.png">

Seems like we don't have a write access on the admin dashboard in demo site. What should I do now?

**Comment by patrys** [comment]
@Rabia23 We do not allow random people to change the configuration of demo.getsaleor.com. You will need to run your own (local) store to play with configuration.

**Comment by Rabia23** [comment]
Thankyou @patrys. I'll setup it locally.

**Comment by Pacu2** [comment]
@maarcingebala This issue regards adding docs for this feature, I think we should keep it open

**Comment by maarcingebala** [comment]
This is mentioned in the new User Guide for Dashboard 2.0.

**Comment by JannikZed** [comment]
Just one question: the social login feature is mentioned in the Dashboard 2.0 docs, but there is no login button in the dashboard after adding a social network provider .. the old dashboard has this option - is this going to be added some time?

**Comment by appleyuchi** [comment]
> Thank you @Pacu2

Hi ,could you tell me if facebook still support local test for "facebook login"?
Thanks for your help

**Comment by JannikZed** [comment]
could we re-open this issue? It's really confusing to have settings in the dashboard, that has no effect. Either remove them or add the feature.

**Comment by JannikZed** [comment]
yes exactly. - Or does this setting has any effect right now?

**Comment by maarcingebala** [comment]
Not really, it was used in Saleor 1.x (django-based storefront). With current approach, we would rather try to implement this feature as a plugin. I'll discuss with the team what's the best approach, we'll probably remove authorization keys from API and dashboard and open issues with specs how Facebook/Google auth could be implemented.

**Comment by PirunSeng** [comment]
Hi @maarcingebala :) May I ask if the team could bring Facebook auth to the platform yet? Otherwise, I wonder if it is possible that we can use react-facebook-login.

**Comment by maarcingebala** [comment]
@PirunSeng We're working on adding OpenID support in Saleor so you'll be able to use providers as Auth0 to enable FB or Google authentication. It is expected to be released in Saleor 3.0. Related backend pull request that will add it: https://github.com/mirumee/saleor/pull/6182

**Comment by PirunSeng** [comment]
Thanks a lot @maarcingebala  :) for your prompt response and the team to bring it to the platform and for the community. Looks like it's gonna be released soon. Can't wait for it.

**Comment by jpromanonet** [comment]
Hi! my team and I been working with the latest version of Saleor and we can't make it work with social media, any news or updates about when the social media login function will be released?

Thanks!

**Comment by Sparksys98** [comment]
@maarcingebala Hey buddy!
Can you please clarify what should be done after adding the key and password for Google/Facebook OAuth in the dashboard?

How to activate the login buttons on the frontend website?
And are there any GraphQL Mutations to test signing up using Google/Facebook?

I just wanna know what are the next steps to activate social media login after adding the key and password of each platform.

**Comment by fedexin40** [comment]
@Sparksys98 were you able to configure it?

**Comment by Yahyaali1** [comment]
Any help on this ? Or link to documentation ? 
We wish to enable google login on react storefornt.

**Comment by Yahyaali1** [comment]
@PirunSeng Anything on this ? How can I enable social logins for customers ?
