### ISSUE TITLE
Should API return url and localizedUrl?

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2071]
Currently API returns localized url to product/page/category storefront page, but lacks ability to return url that contains store default language code - for example, if one queries japanesse store for product url, API will return url that contains client's browser default language, and there is no possibility to obtain japanesse url without changing browser settings. Should we return `url` field that is not affected by client's settings and `localizedUrl`, or should we solve this little problem in another way?

**Comment by patrys** [comment]
How about we let you query for it:

```
query {
  pages {
    edges {
      node {
        id
        publicUrl
        japaneseUrl: publicUrl(language="jp-ja")
      }
    }
  }
}
```

**Comment by patrys** [comment]
I suppose that now that we're working on building a single-page storefront, the concept of backend servers knowing public URLs is no longer applicable. @maarcingebala?

**Comment by maarcingebala** [comment]
It won't be when we drop the current Django-based storefront.
