### ISSUE TITLE
Homepage products as collection

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2076]
Products that are displayed on the homepage could be implemented using a fixed collection. It would make the management of those products more convenient, as at the moment the user has to go to each product details form and from them select/unselect the checkbox "Feature this product on homepage".

"Homepage" collection should be generated in a migration. It should be protected from removing by excluding it in `settings.py`. To conveniently hide it in the storefront, I think we should first implement #1878.

**Comment by Pacu2** [comment]
How about assignig HomePage collection to SiteSettings instead, same as we do with the Menu?
It would allow us to easily swap between currently promoted collections
