### ISSUE TITLE
Wrong captured amount displayed in the dashboard

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2077]
### Steps to reproduce the problem

1. Place an order and pay using Stripe (might happen with other gateways as well).
2. Go to order details in the dashboard.

### What I expected to happen

Since the payment was successful, I see a correct captured amount and have the ability to refund money.

### What happened instead/how it failed
The captured amount showed in order details page is $0.00, there is no ability to refund the payment.

I checked what might be the issue in the code. While making the payment two `Payment` objects were saved, first with the status `input` and the second with the status `confirmed`. [In this line](url) the last payment is supposed to be taken, but instead, the first one (`input`) was fetched which is not the correct one.

**Comment by elwoodxblues** [comment]
Next question would be, why a single payment process creates multiple Payment objects?

**Comment by Pacu2** [comment]
Maybe related to #1671 ?

**Comment by maarcingebala** [comment]
This is already fixed.
