### ISSUE TITLE
Missing variable in "fulfillment" email

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#2081]
Two small issues in the "fulfillment" email:
- logo is missing
- in footer there is missing template variable

I've just tested it and this is how the email looks like:

![image](https://user-images.githubusercontent.com/5421321/38736166-7bd21386-3f2b-11e8-99e0-65459f62602a.png)

**Comment by patrys** [comment]
Also headers are not aligned with the column contents.
