### ISSUE TITLE
Webhooks Events Subscription

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2084]
Hello, here is a draft of a feature for Saleor I'm planning on working on. It's something that is needed for us internally, in addition to the GraphQL API.

I will open a PR as soon as I start working on it. But I'm really not sure if I will be really available to work on it (as it may be visible in my current open PR, which I apologize about them stagnating).

There is no real standard for Webhooks, I'm basing this work on my knowledge, documentation and implementation of Shopify, Discord, Slack, GitHub and Wordpress as they are implementing it their own way with unique features. 

This Webhook feature has two key focus though:
1. Security and Privacy, ensure the data is being safely transferred from the origin to the external app, and to ensure that the data is at low risk from being decoded and or altered (especially as we are getting closer and closer from the GDPR regulation :wink:);
2. Efficiency, ensure the data, the event is being sent as soon as possible and that the external app have a chance to get even if the event happened while the target was down. While keeping the server's load available to customers.

---

I really hope to get your feedback on this! :+1: 

---

### 1. — Objective

The objective behind this feature, is to allow Saleor users to receive, to push notifications about particular events from their shop. Which can be useful, for example:
  - get order notifications on slack, or discord;
  - get notifications on mobile;
  - update external application data on change;
  - ...

Which avoids to make external apps to monitor the shop from the shop's API, and thus, save bandwidth and a lot of CPU cycles. Those webhooks will ensure an efficiant and almost, instant notifications. But note that it doesn't mean that we can rely on those events, the apps should ensure data integrety through Saleor's API if data integrety is a requirement.

### 2. — Settings keys

```python
WEBHOOKS_REQUIRES_HTTPS = True
WEBHOOKS_REQUIRES_VALID_CERTIFICATE = True  # Means that the target must have a valid and CA verified certificate. Means we are TLS strict.
WEBHOOKS_HTTP_POST_TIMEOUT = 5  # seconds
```

#### 3.1. — Create Subscriptions

You,

- Must select, or create an host (TCP) from a list. And then enter the full HTTP path (`/` by default);
- Must select if the HTTP connection must use or not TLS (field disabled and value set to true, if `WEBHOOKS_REQUIRES_HTTPS` is true);
- Must select the event type;
- Must select what fields of the model you want to send (all by default).

#### 3.1. — Subscriptions Logs

You can see the logs of a subscription, which will contain sent and response payloads. Which also include the HTTP response codes and headers.

#### 4.1.0. — Message Content

- Message are sending JSON encoded objects through HTTP POST requests;
- Each JSON message contains, and, will contain the trigger date of the event;

#### 4.2.0. — Headers

When Webhooks events are being sent (async queue), the server is sending a few headers of data which are needed and required by the external apps to identify to content and check the integrety of the received event data.

##### 4.2.1. — Definitions

- `{EventName}` will, in most cases, be the model that triggered the event. Which of course means, the event that you subscribed to. Example: `Order`, `Customer`, or `Product`;
- `{TaskID}` will be the webhook event UUID,
- `{EventType}` will be the type of event. It can be one of the following: Create, Update, Delete;
- `{ShopDomain}`, will be the shop's domain name that got the event triggered (as of now, Saleor only has one shop per site, which means it will be the domain you set in your site settings);
- `{HMAC_SHA256}`, will be the auth message of the application for the event using a shared secret key. It will be used by the external application to check the data integrety and the shop authentication, to avoid any malicious, fake and unauthorized events.

##### 4.2.2. — (Sent) Context Headers

```http
X-Saleor-Event: {EventName}/{EventType}
X-Saleor-Task: {TaskID}
X-Saleor-Domain: {ShopDomain}
X-Saleor-HMAC-SHA256: {HMAC_SHA256}
```

### 5. — Webhooks Events — External App's Side

Saleor is expecting an HTTP OK (200) response. Any other response than that will be processed as an error. It includes HTTP redirections (301 or 3XX).

### 6. — Time to Live and Deliverability

Saleor will try to send an event, as soon as it can but may fail for some reasons. Those reasons, in most cases, whould mostly be an issue from the external app (unavailable, overloaded, firewall issue, errors, etc). In which case, Saleor will whether, timeout its request (5 seconds by default, see the settings section to change this value), or get an HTTP or socket error and thus do nothing.

If you get any timeout issues, make sure the external app is responding an HTTP 200 as soon as it receives the data.

A failed webhook event will be put back in queue and, from the stored event in Saleor's database, it will retry for 72 hours before giving up. Saleor will first wait 10 minutes, then, will wait 30 minutes, 60 minutes, and then will retry every 3 hours.

Saleor will also keep a list of failed subscriptions and flag them as unhealthy if failing (timeouts) to avoid retrying one host too many times.

Note that this implementation was based on the SMTP's [RFC5321 guidance (section 4.5.4)](https://tools.ietf.org/html/rfc5321#section-4.5.4) while trying to be more appropriate for a shop that may generate many events.

----

Useful Resources:
- [Webhook Reference of Shopify](https://help.shopify.com/api/reference/webhook);
- [Webhook Reference of GitHub](https://developer.github.com/webhooks/);
- [Webhook Reference of Discord](https://discordapp.com/developers/docs/resources/webhook);
- [Some more information about Webhooks but not quite useful or complete](https://webhooks.pbworks.com/w/page/13385124/FrontPage).

----

Edit: renamed `X-Saleor-Shop-Domain` header to `X-Saleor-Domain` as `Shop` was mostly redundant, simplifying.

**Comment by NyanKiyoshi** [comment]
I would like to know if implementing a `as_data()` to hookable/ subscribable models to make them serialize would be in according to Saleor's implementation? I want to avoid model repetition, but seems like there is no better way than writing both a GraphQL type and a dict type through `as_data` in models.
Unless we make those types usable and serializable from instances, which would probably require to change the whole current GraphQL typing.

What would you suggest?

**Comment by elwoodxblues** [comment]
Hey @NyanKiyoshi, the idea of webhooks in Saleor sounds exciting! I read through your detailed description and your thoughts seem reasonable. The only thing that I'm concerned is the serialization of models to JSON. I'd like to avoid implementing our serializers, as we will end up with a lot of duplication (it's already happening with storefront's [variant picker](https://github.com/mirumee/saleor/blob/master/saleor/product/utils/variants_picker.py#L10)).

We would have to experiment with Graphene and see to what extent it allows us to serialize models. One possibility that I just tried is to query the schema directly:

```
from collections import namedtuple
from saleor.graphql import schema

Context = namedtuple('Context', ['user'])
ctx = Context(user)
query = '''{product(id: "UHJvZHVjdDo0NA==") { name } }'''
response = schema.execute(query, context_value=ctx)
```
`response.data` would contain `OrderedDict` with product data. This is obvioulsly not the perfect solution but if we don't come up with anything better, maybe we could build a small client around it for webhooks purposes.

**Comment by ajostergaard** [comment]
Very much like the idea of webhooks, could be very useful. Though I'd like to be able to rely on it as much as I can rely on the API. :)

Just one thing however, if you're going to conflate `create` and `change` you might as well conflate `change` and `delete` for the same reason. In general explicit is better than implicit. Change implies preexistence, something has to exist to be changed. Hence `create` and `change` normally exist separately. From an event perspective there is of course no useful difference between `change` and `update`.
