### ISSUE TITLE
Professional Copywriter Willing To Contribute...

### ISSUE THREAD

**Issue by order4adwriter** [mirumee/saleor#2090]
I've seen the dashboard  and used the demo of your opensource storefront platform app [Saleor ](http://getsaleor.com/)at your website...and I must say that it looks pretty cool!

I am a professional copywriter and I 'd like to contribute to your repository by writing compelling and informative content/webpage copy for the About Saleor/ About Us page, Privacy Policy, Help/FAQ, Terms Of Use, Case Studies, Blog posts ... and other necessary marketing content for your app website.

My question is .... would you merge it into your repository when it is done?

Please let me know so I can get started as soon as possible.

Thanks.

**Comment by elwoodxblues** [comment]
Hey @order4adwriter, I'm not sure how much of that we need at the moment for Saleor app itself, but we're working on a new getsaleor.com page, where we could use your help. Please contact us by email: milosz@mirumee.com (Milosz is responsible for the content on new site). Thanks!

**Comment by order4adwriter** [comment]
Thanks for the reply @elwoodxblues .

I have sent a mail to Milosz  like you suggested but I still haven't  heard from him yet.

Any chance you could contact him on my behalf,... or better yet, maybe you could just tell me all about the new page and What kind of assistance you'd like me to contribute.

Either way, please let me know.

Thanks.

**Comment by elwoodxblues** [comment]
Hey, I talked to Milosz and he got your email, he's going to respond to you today. I'm closing this for now and let's continue the communication over emails.
