### ISSUE TITLE
Fulfillment of digital products

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2098]
Saleor should provide ways to fulfill digital products and send the digital content to the customer. Ideas of how we could implement it:
- Allow defining the digital content at the variant level. It would become available to customers once the order is fulfilled.
- Send an email with a generated, unique link to access the digital content.
- "Automatic fulfillment" - if enabled, order lines with digital products should be automatically fulfilled, without interaction from the staff. Question - should this be a global setting or product-specific?

**Comment by saqibkhan2523** [comment]
I have downloaded saleor for digital file downloads. But I find that there is no template for that. If anyone here have any kind of tutorials or guide for saleor please refer it here.

**Comment by maarcingebala** [comment]
I cannot give yet any estimates on where we'll have it, but I'll put it as one of the priorities on our roadmap. It's an essential feature that a lot of users is asking about.

**Comment by blitzd** [comment]
In addition to this (or possibly as a separate request), the ability to have products with no deliverable (aside from an email confirmation) like memberships and donations would attract a lot of non-profits. The donation one is often tricky due to the variable nature of the price, and possible maximums for political entities. Memberships can get complex too with optional family members being included at different price points.

**Comment by creveco** [comment]
It would be really nice to have a unique serial number to sell tickets to events. 
This is a like product keys proposed  by ByteX7, but  with a unique auto-generated key.

**Comment by korycins** [comment]
Hi Guys

We discussed it with @maarcingebala.
At the beginning, we would like to add base logic and model that we will develop in future
We were thinking about the two DB models.
DigitalContent which will store the digital content for each product variant.
DigitalContentUrl will be responsible for URLs pointing to digital content. The second model will give a possibility to manage URLs shared with customers, limit number of downloads, set expiration time for URL, create a unique link for each customer.

**Comment by maarcingebala** [comment]
Resolved by #3868

**Comment by R5n3h** [comment]
First of all, thank you guys for a great product! (Saleor)
I personally actually waited for this PR to be merged.
I have just a small question, maybe I'm missing something here...

The field 'is_digital' is missing in dashboard.product.forms.ProductTypeForm?
I can see any way to enable this product type from the dashboard...

Thanks again,
Ron

**Comment by maarcingebala** [comment]
@R5n3h We're focused on developing the new Dashboard 2.0 and the GraphQL API and we won't add any new features to the Django-based dashboard, that's why we haven't changed anything there. We're accepting PRs from the community though so if you were interested in implementing it, we can provide some guidance and code reviews.

**Comment by R5n3h** [comment]
Thanks, @maarcingebala. I do interested in trying implementing it myself, so I would like some guidance on how do you guys think this should work.
Because this is a OneToOne relation, I thought perhaps to add a DigitalContent section to the product variant page.

Also, do I need to create a new issue with this topic or something like that?
I want to do it the right way :)

Thanks again,
Ron

**Comment by korycins** [comment]
@R5n3h 
Basically, I did almost all implementation for old dashboard during a weekend. 
I just need a couple of days to clean up and add some tests.
Hope it is fine for you :)

**Comment by R5n3h** [comment]
@korycins 
It's excellent, not just fine.

But on the other hand, this might be a good point for me to do my first step for contributing to the open source community.

Anyway, any news regarding the PR we are talking about? :)

**Comment by korycins** [comment]
@R5n3h 
I didn't have enough time to finish the feature.I still need to add some tests. 
I've created the draft PR #3956. 
I will try to add tests tomorrow.

**Comment by adrienshen** [comment]
This would be a really awesome feature for us as well. We're designing a home furniture e-commerce store and one of the features in our roadmap is to offer interior designs as well as a service. The digital content download would make this much easier to implement and streamline our work flow.

**Comment by ianninirojas** [comment]
Hello, how can I use this function? I am creating an ecommerce for events with ticket sales, we do not need shipping, I need it to be automatic to finish the purchase
