### ISSUE TITLE
Common Attributes to each Product Variant

### ISSUE THREAD

**Issue by dragonleopardpig** [mirumee/saleor#2102]
I propose to add Common Attributes to each Product Variant.

### What I'm trying to achieve

Take the Demo site as example, when customer select Hard Cover from a Book, there will be one common attribute like this: **Available For Sale: US only**. When customer select Soft Cover, the common attribute changed to: **Available For Sale: International Edition only**.

Thanks.

**Comment by elwoodxblues** [comment]
You can add attributes common to all variants of a product. See for example "Product Types" > "Books":
![image](https://user-images.githubusercontent.com/5421321/38982736-ebed2322-43c2-11e8-8951-4f361930cd18.png)

Doesn't that solve your case?

**Comment by dragonleopardpig** [comment]
Nope.
Attributes common to ALL variants will not change neither the Hard or Soft cover is selected. What I expect to see is changing of the common attribute when customer click an variant.

**Comment by patrys** [comment]
I think what you're asking for is variant attributes that do not appear as pickers?

**Comment by dragonleopardpig** [comment]
Exactly!

**Comment by dragonleopardpig** [comment]
More example on this:
- click on variant Hard Cover, the variant attribute change to:
  - **Available For Sale: US only**
  - **Page Color: Full Color**
  - **Paper Quality: Premium**

- click on variant Soft Cover, the variant attribute change to:
  - **Available For Sale: International Edition only**
  - **Page Color: Black and White**
  - **Paper Quality: Normal**

Any plan to implement this?

**Comment by patrys** [comment]
Similar use case: book cover type + number of pages. We only want to select the first while the second changes for informational purposes.

**Comment by maltitco** [comment]
Size and length, you must choose the first and second option.
![nagranie ekranu 2018-06-29 o 13 15 14](https://user-images.githubusercontent.com/1561204/42090075-2e45a464-7ba0-11e8-87eb-6e96f594793d.gif)
