### ISSUE TITLE
Use separate forms for API mutations

### ISSUE THREAD

**Issue by akjanik** [mirumee/saleor#2103]
We should use separate forms for our mutations in API. Right now most of them are using dashboard's ones, which are not designed to work with GraphQL and so changes to the forms may break API.

**Comment by elwoodxblues** [comment]
I would even try generating model forms inside our mutations. In order to exclude/include fields in the form we would use mutation's `Meta` options.

**Comment by patrys** [comment]
In that case why not use mutations directly? What do we gain from using forms if they can't be shared?

**Comment by elwoodxblues** [comment]
They validate incoming data and save it in model instances which is very convenient. In case of mutations, often the most straightforward model forms are enough to provide the necessary functionality. Dashboard forms, however, are adjusted for specific UI, which makes them less reusable.

**Comment by elwoodxblues** [comment]
We switched from form-based mutations to a custom solution, it's already merged to `dashboard-2.0`.
