### ISSUE TITLE
Shall it works on Mochahost.com?

### ISSUE THREAD

**Issue by ice1x** [mirumee/saleor#2104]
Shall it works on Mochahost.com?

I am trying to find best hosting for the project based on Saleor.

Could anybody help?

**Comment by rafalp** [comment]
Looks like it should but you'll need to use their [VPS offer](https://mochahost.com/vps.php), likely using the "Perfetto1" as its first one that has reasonable cpu/ram.

**Comment by ice1x** [comment]
Thank you very much!
