### ISSUE TITLE
referral links

### ISSUE THREAD

**Issue by seniorivn** [mirumee/saleor#2107]
Is there an existing feature of referral and affiliate links/prices?
Will it be hard to implement?

**Comment by Pacu2** [comment]
Hi @seniorivn,
This feature is missing from the Saleor, and as far as I'm concerned it's not on our roadmap at this moment.

However, community pull requests are always welcomed! If you decide to work on it we will provide you with a support.

Not sure what exactly is the scope of your feature, but I can imagine few things being added:
1. Affiliated partner/network name could be stored in `Order` model
2. Javascript code to read the URL parameter (referral/affiliate link), setting affiliated cookie in users' browser
3. You could read it back during order placement handling, from request, in https://github.com/mirumee/saleor/blob/master/saleor/checkout/views/summary.py#L34-L46
4 ...

**Comment by EduardoZepeda** [comment]
Use pinax referrals, you just need to add a few lines of code and you're done.

**Comment by Pacu2** [comment]
Closing for now, referral links are not on our road map at this moment, but if you'd like to start working on them we will be more than happy to provide you with support and mentorship if needed.
