### ISSUE TITLE
S3 as storage on Heroku

### ISSUE THREAD

**Issue by austineinstein** [mirumee/saleor#2116]
Hi, 

Not sure what i've done wrong here. I  just added keys to enable me store static files & images on s3.

<img width="1204" alt="screen shot 2018-04-23 at 23 00 23" src="https://user-images.githubusercontent.com/12557036/39155644-bd347ba8-474a-11e8-99c2-d7b4229fd99e.png">
<img width="1354" alt="screen shot 2018-04-23 at 23 00 02" src="https://user-images.githubusercontent.com/12557036/39155656-c89e398e-474a-11e8-89ec-9a9c371541dc.png">

**Comment by patrys** [comment]
Hey, noticed that your template shows `{% static "" %}` while the same file in Saleor contains `{% static "images/block1.png" %}`.

**Comment by austineinstein** [comment]
Thank you!
