### ISSUE TITLE
The sales label on the product does not fit

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor#2117]
Depending on the language chosen, the "sale" label does not fit on the ribbon.
<img width="607" alt="zrzut ekranu 2018-04-24 o 09 20 42" src="https://user-images.githubusercontent.com/1561204/39172341-c251f474-47a1-11e8-891e-1668fe33598e.png">
<img width="354" alt="zrzut ekranu 2018-04-24 o 09 23 51" src="https://user-images.githubusercontent.com/1561204/39172343-c26fb05e-47a1-11e8-94f8-04e2c72fba1e.png">
<img width="341" alt="zrzut ekranu 2018-04-24 o 09 24 17" src="https://user-images.githubusercontent.com/1561204/39172344-c28baad4-47a1-11e8-8fab-4204b4055782.png">

**Comment by Pacu2** [comment]
I think this is the same as #1965 
There was a proposition to change this label, to similar as Chrome Industries does 
![chromeindustries example](https://user-images.githubusercontent.com/21290461/39175225-0c8e7bf4-47aa-11e8-9383-d1528f274371.png)

**Comment by Pacu2** [comment]
Solution proposed in #2146 will resolve this problem
