### ISSUE TITLE
View not refreshing on selecting the product attributes from the left side bar

### ISSUE THREAD

**Issue by codalprashant** [mirumee/saleor#2118]
View not refreshing on selecting the product attributes from the left side bar
.
Not sure what to do for this. I have setup a saleor and made changes as instructed in the document.

Can you let me know what I am missing ?

**Comment by Pacu2** [comment]
@codalprashant Do you mean filters on  Category Page view? They work dynamically only on our demo store, where they're build on react. 
Master branch still uses Django Views, which means that after choosing filters, you need to click 'Update' button.
We are planning to rebuild whole storefront into SPA further this year(planned for July 2018).
You can check our current roadmap at https://github.com/mirumee/saleor/projects/6

**Comment by codalprashant** [comment]
@Pacu2 Yes, I am talking about the filters on Category Page view. May I know what alternate I can use if you have any in saleor ?

**Comment by Pacu2** [comment]
@codalprashant There's none as long as I'm concerned, you might take a look at the demo branch which is React-powered, and work it up from there.

**Comment by NyanKiyoshi** [comment]
@codalprashant if you want, you/ we could do like [newegg.com](https://newegg.com) does while waiting for the react frontstore.

To explain, when selecting an attribute, newegg show a apply button at the end of the selected attribute values. The button applies all selected property values (which means, you can select multiple properties and click on any of the `apply` buttons).

But I feel like it's not... The good way. At least, it makes the user think that they have to apply each selected value.

My solution, that I currently use on production, is to show a Update (apply) button at the top of the filters, in addition to the bottom one when there more than 3 properties. So the user doesn't have to scroll to the bottom to apply. There are a lot of chances that the apply button is always visible, or at least close front the user viewpoint.
