### ISSUE TITLE
Remove "color" field from AttributeChoiceValue

### ISSUE THREAD

**Issue by akjanik** [mirumee/saleor#2119]
Field `color` in `AttributeChoiceValue` seems to an obsolete legacy one that could be removed after investigating and ensuring it is not used.

**Comment by NyanKiyoshi** [comment]
:+1: Especially as people I'm working with always think it's to set tell the website what color the product is (they have a hard time to get the whole process of product types and product attributes + variant attributes. Takes some training as this is not really user friendly as of dashboard 1.0.).
