### ISSUE TITLE
Rename address fields

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2121]
![screenshot](https://i.imgur.com/lugvcZp.png)

I think we should rename 'Address' and 'Address' to 'Address 1' and 'Address 2' or, even better, we could change the logic of addresses.

For example, Amazon, we have a field set "Street", then inside it:
- Street and number, P.O. box,
- Apartment, suite, building, floor, etc.

![screenshot](https://i.imgur.com/M7AYMaE.png)

We don't need to use placeholders, event just as labels "Address 1 (Street and number, ...)", "Address 2 (...)".

I get negative feedbacks on this part as being confusing, and get the questions "What is it?" and "What is address 1 and 2?.

**Comment by patrys** [comment]
We should only display one "Address" label. I like what Amazon and Shopify do in this regard, they display one label and use placeholders to provide hints.

**Comment by tomcio1205** [comment]
@Pacu2 Can You assign me for this issue?

**Comment by tomcio1205** [comment]
@patrys, @Pacu2 Can you tell me if this looking good?
<img width="1173" alt="bez nazwy" src="https://user-images.githubusercontent.com/7680353/44152361-a0edf492-a0a5-11e8-8546-491a233e425c.png">

**Comment by Pacu2** [comment]
@tomcio1205 Looks good to me

**Comment by patrys** [comment]
Looks good! 👍
