### ISSUE TITLE
[Help needed]Stop internationalization in all templates

### ISSUE THREAD

**Issue by Premitium** [mirumee/saleor#2126]
Hi!
I need to stop the internationalization since the website is going to be used in Cyrillic using countries and the fonts we use look terrible in Cyrillic.
The product implies the website to be in English and Euro so internationalization is not needed.

Do I need to remove the 'django_babel.middleware.LocaleMiddleware' and then go through all templates and remove the tags or there is a way to "turn it off".

**Comment by Tchayo** [comment]
I think settings.py file can be of assistance. You can remove the languages you don't need and set the default encoding for the language you prefer. the file is located in the saleor folder

**Comment by Tchayo** [comment]
The settings.py file is in this directory "saleor/saleor/" depending on where you cloned saleor to of course. Don't need to use django debug..just find that path in your project

**Comment by Premitium** [comment]
There is nothing obvious in settings.py that is taking care of this except the django_babel middleware.

**Comment by Tchayo** [comment]
Your mind is set I see. Remove the django_babel middle then of course remove all the tags

**Comment by patrys** [comment]
As mentioned by @Tchayo, you can use Django's [`LANGUAGES` setting](https://docs.djangoproject.com/en/2.0/ref/settings/#languages) to override the list of available languages. You can also disable internationalization in its entirety by setting `USE_I18N` to `False`.

**Comment by Premitium** [comment]
@patrys It worked, thank you!
