### ISSUE TITLE
custom payment options

### ISSUE THREAD

**Issue by Tchayo** [mirumee/saleor#2127]
I'm trying to integrate a payment method that is not yet supported by django-payment. Service providers (Mpesa) have an api on their developers portal and I can/have managed to correctly configure it in another project. My question is, is there an easy way of updating the payment statuses to db without using django-payment/ BasePayment superclass? I need some guidance because I personally like Saleor and I don't wanna use anything else.
ps: This could possibly be a stupid question but I'm a newbie to django and saleor

**Comment by MR612** [comment]
did you implement it? cause i need to know how to provide a custom payment method too.
thanks

**Comment by Tchayo** [comment]
Unfortunately no. I was hoping they would respond to this. Otherwise I'm gonna have to reverse engineer the whole thing to understand how it works then I customize it. All i need is time.

**Comment by Premitium** [comment]
Hi did you do any work on the payment method?

**Comment by KingOlami** [comment]
@Tchayo did you do any work on the payment method?

**Comment by Tchayo** [comment]
working on it.

**Comment by ljcljc** [comment]
Have you finished the implementation? I am also looking for a customized way

**Comment by Tchayo** [comment]
My solution to this is was to Use the Dummy Payment Gateway to create my custom payment gateway. I made my own Payment form from DummyPaymentForm located here 'saleshop/saleor/payment/gateways/dummy' and set up the necessary functionalities (refund, capture, process_payment) of my gateway in the __init__.py file in the custom gateway folder.

**Comment by Tchayo** [comment]
User the Dummy Payment Gateway as a Blueprint to whichever payment gateway you want to implement.
