### ISSUE TITLE
Did saleor not support uwsgi run directly?

### ISSUE THREAD

**Issue by zchking** [mirumee/saleor#2128]
### What I'm trying to achieve
Hi, I want to delpoy saleor with uwsgi on ubuntu 16.04
now I can run it normally with
 `python manager.py runserver `
...

### Steps to reproduce the problem

1. I use minial command to test.
    ~/saleor$ `uwsgi --http 0.0.0.0:8000 --module saleor:wsgi`
   the result is:
   
![image](https://user-images.githubusercontent.com/5665818/39289984-9fe10324-4960-11e8-9a9b-2e00246fdbd2.png)

### What I expected to happen
it should run as normal, but now no app load.
...
 **Does any trick with saleor to run with uwsgi?**

**Comment by zchking** [comment]
## I use global python3 so all lib have included.

and it can run with manager.py

**Comment by artursmet** [comment]
Hello @zchking 

Saleor should work fine with uWSGI

Did you tried to use `uwsgi --ini saleor/wsgi/uwsgi.ini`?

There's some additional config in the ini file we deliver.

**Comment by zchking** [comment]
thank you. @artursmet  yes I have try it same problem.

I have try to use --wsgi-file saleor/wsgi/__init__.py.

now it work as normal.

**Comment by zchking** [comment]
now can run it directly, thank you. thank you so much.

but uwsgi --ini saleor/wsgi/uwsgi.ini still not work, I will find the reason.

**Comment by patrys** [comment]
@zchking You're using a globally installed `uwsgi` binary. In that case you will need to support `-H /path/to/saleor/virtualenv` as a parameter to correctly set the Python library path.
