### ISSUE TITLE
Can't run saleor

### ISSUE THREAD

**Issue by marabqa** [mirumee/saleor#2130]
When I run this command **python manage.py runserver** I got below error, I'm stuck now here.

raceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

**Comment by marabqa** [comment]
Its already installed **pip install -r requirements.txt**

**Comment by marabqa** [comment]
I got this error now....

File "/root/env/lib/python3.5/site-packages/django/conf/__init__.py", line 125, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by akjanik** [comment]
Looks like `SECRET_KEY` is not set, please check point 4 in Installation section.
https://saleor.readthedocs.io/en/latest/gettingstarted/installation-linux.html#installation
Maybe you had set it before and then log out and it's not in `env` anymore.

**Comment by nguyenvantiendat** [comment]
Need to set SECRET_KEY first, export SECRET_KEY ='XXXXX'

**Comment by Pacu2** [comment]
I think this is resolved as per #2108
