### ISSUE TITLE
[Bug] Sometime system returns 'shipping - address' page when clicking 'continue' from 'shipping method' page 

### ISSUE THREAD

**Issue by nguyenvantiendat** [mirumee/saleor#2132]
1. I order some product and checkout
2. select shipping address and continue
3. select shipping method and continue 
symptom: sometime system return shipping address page
is it cache?
i deploy saleor by follow doc (http://saleor.readthedocs.io/en/latest/gettingstarted/installation-linux.html) and config nginx by http://michal.karzynski.pl/blog/2013/06/09/django-nginx-gunicorn-virtualenv-supervisor/

**Comment by Pacu2** [comment]
Haven't experienced it on my own, were you able to reproduce it on https://demo.getsaleor.com/?

**Comment by Pacu2** [comment]
Please reopen if you find a way to reproduce an issue.
