### ISSUE TITLE
Handle not published items in Menu

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#2137]
At this moment, one can add not published (Collection / Page) to the menu. Such item will be listed on the Storefront, but cannot be viewed by regular user(returning 404-instead).

My proposition is:
- [ ] Display a warning when one adds not published item(Collection / Page) to the Menu
- [ ] Display a warning if any MenuItem contains not published Collection / Page 
~- [ ] Hide items linking to not published instances, on the storefront~

Related discussion in #2109

**Comment by NyanKiyoshi** [comment]
To confirm, a "draft" would or could be a simple toggle box to set the item/ menu as published/ not published?

**Comment by Pacu2** [comment]
I think we misunderstood each other a little, I meant that `Page` or `Collection` might be not published, but can be assigned and displayed in the menu.

**Comment by NyanKiyoshi** [comment]
Oh, I see, thanks!
