### ISSUE TITLE
In mobile version, nothing tips after add to cart, like it doesn't work.

### ISSUE THREAD

**Issue by zchking** [mirumee/saleor#2138]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
It should show Checkout or Go to cart like Desktop verion.
...

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/5665818/39395659-9f6baf52-4b13-11e8-96a3-4e8ee7cc53dd.png)

## In mobile version after click add to cart, only the number change which is not very clear to curstomer.
they may think nothing happened.

**Comment by Pacu2** [comment]
I think that was desired behaviour, however we are planning to rebuild Storefront completely with GraphQL + React combo later this year, such feedback is really helpful!
