### ISSUE TITLE
Top and Bottom Menus (Navbar/Footer) ids get set to None when  Header text  is changed in Site Settings

### ISSUE THREAD

**Issue by dano000** [mirumee/saleor#2139]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve
Remove the default Header Text (ie. "Test Saleor - a sample shop!") by removing it completely in the Dashboard part of the app.
...

### Steps to reproduce the problem

1. Clone a new Saleor shop/site.
2. Setup everything as normal (run migrations etc, as stock).
3. Define one or more categories in the Dashboard.
4. Assign the categories in Navigation > Navbar/Footer > Add Menu Items
5. Navigate to "Site settings > Edit Site Settings" in dashboard 
6. Delete field contents of " Header text (optional) "
7. Click "Update"
8. Navigate to main home page (http://localhost:8000 for development) to find there are no items in the navbar or the menu.
9. (optional) go into db shell and look at SiteSettings to see that top and bottom ids are None! 

### What I expected to happen
The menu items of the navbar and footer to still be there.
...

### What happened instead/how it failed
The items are gone (there is nothing).
...
_

**Comment by Pacu2** [comment]
Thanks for a catch, that's a nasty one!
Your navigation just got set blank, you can reassign them in Navigation tab, as nothing should be gone forever, problem should be resolved by #2140
