### ISSUE TITLE
npm run build-emails [FAILS]

### ISSUE THREAD

**Issue by leikoilja** [mirumee/saleor#2143]
### What I'm trying to achieve
I'm trying hard to install Saleor on Win10 machine for the first time and have run into a problem compile e-mails (as described in docs)

### What i do:
I have installed latest node.js and when running "npm run build-emails" i am getting the following error:
```
(Saleor) E:\Development\Web\eCommerce\saleor>npm run build-emails

> saleor@0.0.0 build-emails E:\Development\Web\eCommerce\saleor
> mkdir -p templates/templated_email/compiled/ && find templates -name "*.mjml" -not -path "templates/templated_email/source/*partials/*" -not -path "templates/templated_email/source/*shared/*" -exec mjml -l skip {} -o templates/templated_email/compiled/ \;

The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor@0.0.0 build-emails: `mkdir -p templates/templated_email/compiled/ && find templates -name "*.mjml" -not -path "templates/templated_email/source/*partials/*" -not -path "templates/templated_email/source/*shared/*" -exec mjml -l skip {} -o templates/templated_email/compiled/ \;`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the saleor@0.0.0 build-emails script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ilja\AppData\Roaming\npm-cache\_logs\2018-05-04T21_12_18_762Z-debug.log

```

This is the log file referenced in the error - [https://paste.ubuntu.com/p/snx3KS2v5d/](url)

**Comment by NyanKiyoshi** [comment]
Hi!

If I recall correctly, it's an issue with whether:
- the directory permissions;
- the node & npm versions;
- the Unix core commands versions.


And I'm also noting that you are using Windows and seems like, you are running the command through the Windows's msdos interpreter.


Here is an ordered checklist:
1. Can you try running this command in a bash shell? (You can get one simple to install [here](https://git-scm.com/download/win)). It will make Unix commands (`mkdir` and `find`) available for npm, it may fix the issue.
2. Make sure you are using NodeJs 8+.


I think that's it, at least in the issues I can see/ imagine for Windows.

**Comment by leikoilja** [comment]
Thank you, @NyanKiyoshi for your reply. Unfortunately, i doesn't help.
I have tried running the command both in windows msdos interpreter and in Git Bash(for windows). Using git bash i can manually create folders using "mkdir" and use "find", so that's not a problem. Once I navigate to the saleor dir and run 'npm run build-emails' it shows me the same error. 
```
Ilja@IAP-Leiko MINGW64 /e/Development/Web/eCommerce/saleor (master)
$ npm run build-emails

> saleor@0.0.0 build-emails E:\Development\Web\eCommerce\saleor
> mkdir -p templates/templated_email/compiled/ && find templates -name "*.mjml" -not -path "templates/templated_email/source/*partials/*" -not -path "templates/templated_email/source/*shared/*" -exec mjml -l skip {} -o templates/templated_email/compiled/ \;

The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor@0.0.0 build-emails: `mkdir -p templates/templated_email/compiled/ && find templates -name "*.mjml" -not -path "templates/templated_email/source/*partials/*" -not -path "templates/templated_email/source/*shared/*" -exec mjml -l skip {} -o templates/templated_email/compiled/ \;`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the saleor@0.0.0 build-emails script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ilja\AppData\Roaming\npm-cache\_logs\2018-05-05T06_33_24_699Z-debug.log

```
And from the log file autocreated i can see that my versions to be:
```
2 info using npm@5.6.0
3 info using node@v8.11.1
```

**Comment by NyanKiyoshi** [comment]
Okay! If you managed to run the command from the shell, it's already that taken, since it means you managed to build the emails. 
Just need to figure what is triggering the error on `npm`'s side. I'm gonna be out to work soon, so I will be able to take a look from the environment where I had this same issue, which I did manage to fix, but I'm not sure anymore how I did it, and what was my final conclusion on the issue. I will keep you updated.

**Comment by patrys** [comment]
The problem is that the `build-emails` script relies on POSIX commands `mkdir` and `find`. They are not available on Windows. Even if you execute `npm` from a bash shell you are likely executing the Windows build of `npm` which internally executes the script using the regular Windows kernel calls (which I think nowadays uses PowerShell).

The proper solution would be not to rely on POSIX tools in the script (essentially reimplement it using JS or Python).
