### ISSUE TITLE
Feature (1): Product Labels

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2146]
Hello, I would like to take some time to discuss with the Saleor's team and anyone wanting to be involved with Saleor's development about a few features and improvements.

I'm swamped by work, but Saleor is also part of my work, thus of my time. This week should, hopefully, be a little more quiet as we are gonna launch a marketing campaign over our Shopify store.
So, I would like to take those hopefully quite days to make some changes over Saleor, work on it.

Currently, we are running two different and separated stores:
- Our main one is Saleor, focused in IRL sales;
- Our secondary one is Shopify, this one is focused on bulk sales. We (mostly I), chose to not use Saleor because of a few issues, mostly because of law issues. I will take time later to work and list the issues blocking us from deploying Saleor for this second store.

### The Feature

So, now that the introduction is over, I would like to discuss the first feature: product labeling. This feature was already proposed and quickly discussed over #1965 and #2117.

What was suggested, was doing like was Chrome Industries does. Which means that:

![screenshot](https://i.imgur.com/2MJ96WN.png)

I also saw other interesting examples over [shopify](https://apps.shopify.com/product-labels), wix (see bellow) and other stores.

The most interesting and efficient method I saw was wix's ribbon mechanism.

![screenshot](https://i.imgur.com/jsnlhva.png)

It's simple. Very user friendly. We have a ribbon field on the product form, we type what text we want and that's it (so, it's like we are doing on Saleor, a select + input field). And thus, we have a many-to-one relationship (`Product.label -> ProductLabel`)

![screenshot](https://i.imgur.com/3KkIYZn.png)

And then, we have a 'Manage Ribbons' page to manage the data.

![screenshot](https://i.imgur.com/xdNGvSk.png)

### The Current Proposal

From the previous section, I note that we have the above data sets (tables).
Where I would also propose that we give a few additional options to allow the user to set a text color and background color, so we let the user have maximum control over the visual. Maybe a color picker field?

#### Tables

So here it is (syntax: `field: type=default_value`).

```
ProductLabel
------------
text: str
color: int=None
background: int=None
```

Note: int, would be a hex value, in Python we would have to format it through:
```django+html
#{{ product.label.color | stringformat:'x' }}
```

```
Product
-------
label: ProductLabel
```

#### Views

1. We must be able to see the list of `ProductLabels`.

Text | Text Color | Background Color |
-----|------------|------------------|
Label 1 | None | None |
Label 2 | #ff0000 | #000000 |
... | ... | ...

2. We must be able to edit all the attributes, and delete objects.

#### Forms

1. Product Form: a 'label' field (`ProductLabel`), which would only accept text and create if not existing.
2. Product Labels: we can edit product labels, where we can also set/ change the visual rendering (colors), which will not be made available from the product form view.

### Sale handling

Here is our main current issue, I think. How do we handle the case where we have both a label, and a sale?

1. We could say the user overridden our default sale label, maybe we should check for a flag telling us if we should override it? (e.g.: `label.is_sale: bool`);
2. We could say, we stack them, a sale label and the current label, while checking if the user wants us to not add a label under their label.
3. We could drop the one-to-many relationship for a many-to-many, and, thus, only use label stacking.

**Comment by Pacu2** [comment]
I think that's a great idea, and we should put this on our roadmap
