### ISSUE TITLE
Give the user a way to edit their email address from their profile

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2148]
Hi!

I just remembered that, as users, we cannot edit our email address in our account in Saleor. We should add this feature in Saleor.

Note: I assign this task to myself. I will put it on my todolist.

It's rather simple: 
1. Add a edit button next to the email address in `/profile/`, which would link to a form in the `account` namespace;
2. Then, once changed (need to check if the data is changed or not, in the form), we would put a pending verification (TTL of 15 minutes) on the new user email address which would activate the email address.

**Comment by Pacu2** [comment]
Thing to remember: reassign all Carts and Orders to new user email

**Comment by Pacu2** [comment]
@NyanKiyoshi are you working on it or can we clear it and leave it for someone else?

**Comment by NyanKiyoshi** [comment]
I will not have the time to work on it for now, you can clear it. Thank you!

**Comment by tomcio1205** [comment]
@Pacu @NyanKiyoshi  I want to go with that, but I can't find the /profile page. This page was removed from current version or what? I thinkining of puting change email options under the My Account, same as change password option.

**Comment by Pacu2** [comment]
@tomcio1205 I think @NyanKiyoshi meant My Account, which you can find at http://localhost:8000/account/ while being logged. 

I wonder if we shouldn't move 'Change password' section to the 'Settings', and add Change email option in there?

**Comment by tomcio1205** [comment]
@Pacu2 Could you tell my what do you think of this styling? I'm not pretty sure how to style settings section, so before I start write any code I want to be sure how to style this. Maybe I should place buttons only with redirects to forms.
<img width="1068" alt="email" src="https://user-images.githubusercontent.com/7680353/43353980-a0cb0c90-9243-11e8-93f3-c7806e5f852c.png">

**Comment by Pacu2** [comment]
To be honest is as good as it gets, the whole section needs some sort of a redesign, personally, I like what Zalando does but think that can be addressed at some other occasion. 
![zalando](https://user-images.githubusercontent.com/21290461/43354128-7e7f7038-9246-11e8-8735-53f481637c11.png)

**Comment by tomcio1205** [comment]
Ok,  thanks. So I focus on functionality itself and style will remain as it is.

**Comment by patrys** [comment]
Notice how Zalando requires you to enter your current password in order to change the email address.

**Comment by maarcingebala** [comment]
It will be addressed in Storefront 2.0 and Dashboard 2.0. Related backend issue: #4648
