### ISSUE TITLE
Open Graph image tag on category should change

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2149]
Hi!

I just saw that we are putting `block1.png` in categories (well, everywhere in the store except on product details).

I think, in the category details view, we should put the category cover image if set. Otherwise... Block1 or the logo? I am not sure if we should whether put block1 or the logo everywhere as default.

Also, that would be quite a nice feature to allow to customize the page first image.

**Comment by patrys** [comment]
I think `{% if ... %}...{% else %}{{ block.super }}{% endif %}` would work the best (least number of places to edit when customizing).
