### ISSUE TITLE
Feature: allow to toggle indexing on custom pages

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2150]
Hi!

This was quite an issue here, we have a few pages, with two special pages:
1. Privacy Policy;
2. Selling Contract.

In our `robots.txt`, as of now, we are blocking those pages from indexing, as there is really no use to index those kind of pages, they could even bother us on search results.

I think that we should put a toggle for indexing bellow the SEO fields. A field `Allow indexing`, if set to `False`, it would put a `noindex` robot meta tag and won't appear in the `sitemap.xml` (otherwise it's a waste and makes Google a tiny bit angry).

I would like to hear back on that issue, if you think it's a good idea or not.

**Comment by Pacu2** [comment]
Taking this step further, we could add `Allow crawling` for `nofollow` meta tag

**Comment by NyanKiyoshi** [comment]
Totally agreed.
