### ISSUE TITLE
Order events should contain type and parameters fields

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2154]
At this moment order events consist with `content` and `user` fields, which are just fine to just display them, but in upcoming dashboard's version, we should expand this section a little, making the distinction between different types of events. Therefore I would like to propose introducing additional fields `type` and `parameters`, which would precisely describe what happened in the exact event, allowing us to display additional actions, information or just change appearance.

Also, please do not save translated messages, as they are currently being.

**Comment by patrys** [comment]
Blocks part of #2639

**Comment by maarcingebala** [comment]
Related issue: #2617

**Comment by patrys** [comment]
Closed by #2811
