### ISSUE TITLE
Use Pinyin URL structure for Chinese website Baidu SEO

### ISSUE THREAD

**Issue by alexander-sibert** [mirumee/saleor#2157]
Often in E-Commerce solutions missed for growing China E-Commerce market. Pinyin URL structure

For example: 中文网站
Result in URL should be: zhong-wen-wang-zhan

Here is a good description of this topic: https://dengruo.com/en/blog/use-pinyin-url-structure-chinese-website-baidu-seo

**Comment by Pacu2** [comment]
I think we got it covered already, `中文网站` will be slugified to `zhong-wen-wang-zhan`, seems right, right?

**Comment by alexander-sibert** [comment]
I can help translate into german language. My girlfriend with the time the Chinese language (she speaks Mandarin)

**Comment by NyanKiyoshi** [comment]
AliPay is huge in China. Almost everyone is using it, even just to pay IRL. There are a lot of Saleor Chinese users, it would be great to add.

@alexander-sibert keep us updated! If you need help feel free to contact.

**Comment by NyanKiyoshi** [comment]
It looks like you [can accept AliPay through Stripe](https://stripe.com/docs/sources/alipay), which is supported by Saleor.

**Comment by alexander-sibert** [comment]
I read it also but they charge per transaction? Then i have to clear if they support AliPay International or also AliPay within Mainland China.

**Comment by alexander-sibert** [comment]
Another thing are international address formats for checkout. For example China has also another address format than western world Europe or USA.

**Comment by Pacu2** [comment]
Saleor uses geolocation to enhance the experience of the customers, it understands international addresses, can convert prices to other currencies and offers translation where needed.

**Comment by alexander-sibert** [comment]
Ok Ok, i will install it and use it ;) for a hopefully growing project

**Comment by alexander-sibert** [comment]
@NyanKiyoshi maybe you can help me out with setup on Server and Docker?

**Comment by maarcingebala** [comment]
@alexander-sibert Take a look at the [Deployment section in our docs](https://saleor.readthedocs.io/en/latest/deployment.html). Please reopen the issue if you have any particular questions or reach us out on [Gitter](https://gitter.im/mirumee/saleor).

**Comment by shellwang** [comment]
@alexander-sibert have you finished include the alipay and wechat payment solutions?
