### ISSUE TITLE
`DistinctFilterSet` breaks filtering abilities

### ISSUE THREAD

**Issue by akjanik** [mirumee/saleor#2163]
Right now we are using `DistinctFilterSet` as a `filterset_class` for most of the queries for `DjangoFilterConnectionField`, except `products`, which uses `ProductFilterSet`. I realised that it disable ability to use filters defined in `filter_fields` meta attribute of given type.
I think we could drop this in most cases (which require also removing `.distinc()` from related queries) - maybe a special filter is needed for `Category` type, as it has `ancestors` and `children` attributes.

**Comment by maarcingebala** [comment]
This is no longer relevant, we don't use `DistinctFilterSet` in API anymore.
