### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor#2167]
I am trying to install a new release on my OSX and I have a npm installation error:

`node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz`

`node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.1.0 (node-v64 ABI) (falling back to source compile with node-gyp) `

The error can be repaired by:
`npm install fsevents`

Then running npm run build-assets is another error:

`ERROR in ./saleor/static/dashboard/js/dashboard.js
Module build failed: Error: [BABEL] /Users/malt/PycharmProjects/saleor363/saleor/static/dashboard/js/dashboard.js: The new decorators proposal is not supported yet. You must pass the `"legacy": true` option to @babel/plugin-proposal-decorators (While processing: "/Users/malt/PycharmProjects/saleor363/node_modules/@babel/plugin-proposal-decorators/lib/index.js")`

**Comment by NyanKiyoshi** [comment]
Thanks for the report! They (fsevents) may have deleted the 1.1.2 release which is in `package-lock.json`, the latest version which is the 1.2.3, is not returning an error at https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.3/fse-v1.2.3-node-v64-darwin-x64.tar.gz.

Someone will take a look and fix this.

**Comment by maltitco** [comment]
Completely removing node_modules and reinstalling npm helps to resolve this issue.
