### ISSUE TITLE
Import products from another DB and understand how assign attributes

### ISSUE THREAD

**Issue by pceuropa** [mirumee/saleor#2169]
Tanks for your impressive code. 
### I'm trying to achieve
import 20k products from another DB to saleor DB (postgres). Automatic import category and products without attributes work well.
But i have problem **understand how assign ProductAttribute to ProductType**. In step 4 i must assign attributes to ProductType manually in dashboard.

**Step1. Create ProductType - _done_**
`ProductType.objects.create(**{'id': 1, 'name': 'type',})`

**Step2. Create ProductAttribute - _done_**
```
data = {
        'slug': 'shop',
        'name': 'shop',
    }
ProductAttribute.objects.create(**data)
```

**step3. AttributeChoiceValue - _done_.**
```
attr = ProductAttribute.objects.get(pk=1)
data = {'id':1, 'slug': 'shop_name', 'name': 'Shop_name', 'attribute': attr}
AttributeChoiceValue.objects.create(**data)
```

**step4**. Try assign attribute to productType FAIL
```
product_type = ProductType.objects.get(pk=1)
attr = ProductAttribute.objects.get(pk=1)

product_type.product_attributes = attr
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use product_attributes.set() instead.

product_type.product_attributes.set(attr)
TypeError: 'ProductAttribute' object is not iterable
```

**step5. Try assign attribute to product - _done_**
```
pro = Product.objects.get(pk=3)
pro.attributes = {1:1, 2:2}
pro.save()
```

Tanks for your time.

**Comment by Pacu2** [comment]
I think you should try 
```
product_type.product_attributes.add(attr)
```
They're helpful examples for many-to-many relations in [Django docs](https://docs.djangoproject.com/en/2.0/topics/db/examples/many_to_many/)

**Comment by pceuropa** [comment]
Work well, great thanks for keywords. Maybe letter I'll pull some PR.

**Comment by patrys** [comment]
I'd suggest trying to use the same form classes that are used in admin views rather than manipulating the ORM directly if you're fine with creating objects one by one (as opposed to a bulk insert).

**Comment by pceuropa** [comment]
Ok, thank you for your suggestion. I'll try use form class to.
