### ISSUE TITLE
Creating a new product or variation with an existing value, raises 500 error

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2172]
## How to reproduce (see demo)

1. Create a product with a new attribute value created from the product form;
2. Hit 'previous' to recreate a product with the same templates;
3. Edit some of the information, except the new attribute value;
4. Enjoy the internal error.

Same thing for variations.

## Demo
See: https://www.youtube.com/watch?v=76sOSG4p1Yk

**Comment by NyanKiyoshi** [comment]
It's very likely that it doesn't occur on dashboard 2.0 though, so it shouldn't really matter right now. If it someone can confirm.

**Comment by maarcingebala** [comment]
I wasn't able to reproduce this issue in both dashboards.
