### ISSUE TITLE
Please show me how to translate the status of order

### ISSUE THREAD

**Issue by nguyenvantiendat** [mirumee/saleor#2180]
![statusoforder](https://user-images.githubusercontent.com/28885418/40160080-3e4bf6ec-59d6-11e8-9fdc-537e580eeb44.png)

**Comment by Pacu2** [comment]
Saleor is translatable via [transifex](https://www.transifex.com/mirumee/saleor-1/)  we will be more than glad if you'd like to join one of our translation teams.

If you're working on behalf of your local instance, string to translate could be found in .po files. Just find the corresponding string and fill the translation.
More on translations can be found in [django docs](https://docs.djangoproject.com/en/2.0/topics/i18n/translation/)

**Comment by nguyenvantiendat** [comment]
Actually, i translate all in .po and almost are affected, but only status of order in "your account" is not affected.

**Comment by Pacu2** [comment]
Have you run [compilemessages](https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#compiling-message-files) command after updating translation files?

**Comment by nguyenvantiendat** [comment]
yes, i have and other translation is ok, only status of order. could you provide me that which msgid i can oversee ?

**Comment by NyanKiyoshi** [comment]
@Pacu2 I just checked, statues are not translated

**Comment by nguyenvantiendat** [comment]
what is msgctxt you refer, i translate in local

**Comment by NyanKiyoshi** [comment]
- Status for a fully editable, not confirmed order created by
- Status for an order with any items marked as fulfilled
- Status for an order with some items marked as fulfilled
- Status for an order with all items marked as fulfilled
- Status for a permanently canceled order

c.f.: https://github.com/mirumee/saleor/blob/master/saleor/order/__init__.py#L21-L37

**Comment by nguyenvantiendat** [comment]
I have to translate in .PO file, but it does not affect

#: saleor/order/__init__.py:21
msgctxt "order status"
msgid "Unfulfilled"
msgstr "Chưa hoàn thành"

#: saleor/order/__init__.py:23
msgctxt "order status"
msgid "Partially fulfilled"
msgstr "Đã hoàn thành một phần"

#: saleor/order/__init__.py:24 saleor/order/__init__.py:33
msgctxt "order status"
msgid "Fulfilled"
msgstr "Hoàn thành"

#: saleor/order/__init__.py:25 saleor/order/__init__.py:34
msgctxt "order status"
msgid "Canceled"
msgstr "Đã hủy"

**Comment by Pacu2** [comment]
@nguyenvantiendat Your won't be visible unless you run [compilemessages](https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#compiling-message-files) command. Have you?

**Comment by nguyenvantiendat** [comment]
i always run compilemessages after i translated, and as i told that other translation is affected, but only status of order is not.

**Comment by NyanKiyoshi** [comment]
And restarted django after? And made sure that you were set to the Vietnamese language on frontstore?

That's dumb questions, but we never know.

I will try on my own tomorrow as I don't have my development environment on me right now.

**Comment by NyanKiyoshi** [comment]
@nguyenvantiendat could you pull the latest version of Saleor? You are in a old version (~one month old). From what it looks like on https://github.com/mirumee/saleor/issues/2180#issuecomment-390406195. If I recall correctly, there was a change about that and contexts were changed in a PR.

**Comment by Pacu2** [comment]
Please try with the latest master, this translation works properly on my local instance

**Comment by nguyenvantiendat** [comment]
thanks
