### ISSUE TITLE
Unable to create products with variants disabled

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2185]
### What I'm trying to achieve
Create a product with variants disabled (in the product type).

### Steps to reproduce the problem

1. Use or create a product type with variant disabled;
2. Try to create a product using this type;
3. If you submit the form, the product should have failed to be created, and no errors shown. 

### Notes
The error from the variant form is the following one (not showing in the view rendering):
```html
<ul class="errorlist"><li>quantity<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
```

See: https://github.com/mirumee/saleor/blob/8da1add5be0ae451add19a19f510fa2dd0f7a91e/saleor/dashboard/product/views.py#L117

**Comment by patrys** [comment]
The variant form should be displayed inline when variants are disabled, shouldn't it? We still create a single variant as you can only add variants to the cart.
