### ISSUE TITLE
Unable to add a new address on checkout of digital goods

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2192]
### What I'm trying to achieve

Enter a new billing address on checkout when ordering a digital good.

### Steps to reproduce the problem

1. Make sure you have a default billing address;
1. Add to cart a book;
1. Go to checkout;
1. At billing address step, create a new address with a different country;
1. Correct any errors if the default billing address fields differs from the new country;
1. Place order;
1. Shipping address should not have been created.

### What I expected to happen
Have the new address as billing address on order.

### What happened instead/how it failed
Got no address created, and got the previous address as billing address for order.

**Comment by mad-anne** [comment]
There is a problem with `summary_without_shipping` view and `billing_address` property on checkout object. When user has default_billing_address and no other billing address for checkout process set, a default_billing_address is returned by property. Then it is took as an instance to create AddressForm (in view mentioned before, `summary.py` file). When modified instance is assigned to checkout, it has and `id` of a user's default address. So restoring it again in checkout's `billing_address` property causes calling `_get_address_from_storage` which fetches from database an object with given id.
I will open a PR with a change solving this problem soon.
