### ISSUE TITLE
Adding delivery time slot

### ISSUE THREAD

**Issue by Kuntal-KK** [mirumee/saleor#2196]
I am new to django and for practice I was exploring saleor. I wanted to implement some feature and failed on those. So, kindly help me.

### What I'm trying to achieve

I am trying to add a delivery slot time. After adding the product to the cart, when user click on checkout, there I need that drop down list (slot timing) below the address selection section, above **Add a Note to Your Order** text box.

### Steps to reproduce the problem

1. I have created a model **DeliveryTime** in order app and taking the model form in **order app** forms.py file
2. Rendering that form to the **summary view** of **checkout app** inside **summary_without_shipping(request, checkout),  anonymous_summary_without_shipping(request, checkout) and summary_with_shipping_view(request, checkout)** function
2. I have added **user and order model** to the **DeliveryTime** table as foreign key

### What I expected to happen

As soon as an user clicks on Place Order button, it should add selected time slot, user id and corresponding order id to the table 

### What happened instead/how it failed

Only data I got in the db is Delivery time slot.

### Some Queries

In the **summary.html** file or **summary_without_shipping.html** file inside template/checkout, after clicking on Place order, it is redirecting to /order/token/payment.
But in the above mentioned html file, there is no action mentioned in the form as I have done till now. Can anyone please explain how that form working and redirecting to those url?

**Comment by Pacu2** [comment]
Redirect to order/token/payment comes from `create_order` function, which is fired by `handle_order_placement` helper

Do you need `DeliveryTime` as a separate class? Couldn't this be stored inside of `Order` model?

**Comment by Kuntal-KK** [comment]
Yes, inside of Order model will be more convenient way to implement. 
I have a question. From which view I can get the current order id?
