### ISSUE TITLE
Unable to impersonate a user when already impersonating

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2200]
### What I'm trying to achieve
To impersonating another user while impersonating someone, because I'm too lazy to click on 'Stop impersonating' :wink: 

### Steps to reproduce the problem

1. Impersonate a customer;
2. Impersonate someone else;
3. The impersonating should have failed, meaning that you are still impersonating the same user (which may be confusing).

### What I expected to happen
To be impersonating the newly selected user.

### What happened instead/how it failed
Still impersonating the previous user and no message to warn me about it.

---

It's quite a simple bug: when wanting to impersonate a user from dashboard (`/dashboard/customers/`), we are clicking on a link that is pointing to `/impersonate/<uid>/`. So we are pointed outside of the dashboard.

As of now, Saleor is excluding dashboard from being impersonated, so if in a dashboard view we are trying to read the current user, we will get the admin user, not the impersonated user.

Now, we are trying to impersonate someone, we hit `/impersonate/<uid>`, which is not excluded from impersonation. So we are hitting this view as the impersonated, not as the admin. Which gets us denied from impersonating, and thus, redirects us to the homepage.

So, the fix is fairly simple: exclude `/impersonate/` from impersonation in settings. That's it.

**But now...** The question is: why should the impersonation views be outside of dashboard? Shouldn't we move them over `dashboard.customer`? Wouldn't it make more sense to do that way, and thus not having to add a new exclusion?

Thanks a lot for your feedback!

**Comment by tomcio1205** [comment]
@Pacu2 I try to fix that

**Comment by NyanKiyoshi** [comment]
Oh wow that's old, that just a little check to do here if I recall correctly. I never opened a pull request for it, weird.
https://github.com/mirumee/saleor/blob/2a5e3e7114471ce4bb93ab2edb0b2005cf0e10f2/saleor/core/views.py#L33-L40

Thanks @tomcio1205 for picking this up! (I'm swamped by work so I only will have time to review your PR).
