### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by Yiesta** [mirumee/saleor#2211]
I did manage to setup saleor to my vps server. But now the issue is i can not reach it. 

I ran the command `python manage.py runserver 29.32.132.59:8080`
result = 
```
Performing system checks...

System check identified some issues:

WARNINGS:
saleor.W001: Session caching cannot work with locmem backend
	HINT: User sessions need to be globally shared, use a cache server like Redis.

System check identified 1 issue (0 silenced).
May 24, 2018 - 17:55:16
Django version 2.0.3, using settings 'saleor.settings'
Starting development server at http://29.32.132.59:8080/
Quit the server with CONTROL-C.
```

When i try to access with ip or my domain which i pointed the ns servers to my vps ip. Also i edited settings.py ALLOWED_HOSTS=['myhost']

Don't really know what is happening here. Is it because of the 1 issue that popped up when i run the server. But it did not prevent my server to run. I did search quite a bit but no luck.

**Comment by NyanKiyoshi** [comment]
Hi!

This is a warning (obviously), which is there to remind you to setup a session caching, for which, we recommend to use Redis.

This can be safely ignored for a development environment (which seems to be your case), unlike for production.

---

Also, why are you making python to listen on `46.45.163.59`? Pretty sure you don't have a network interface with this IP address. If you want to open the server for outside connections, you can make it listen on `0.0.0.0`.

**Comment by Yiesta** [comment]
Hey,
I solved it in combination with what you said and also configuring the firewall

```
salfirewall-cmd --zone=public --add-port=8000/tcp --permanent
salfirewall-cmd --reload
```

Now i can reach my site through servers ip adress. But still am not able to connect my domain and my django server. Is it because my Ns servers are pointed to the ip but not ant port. Should i somehow redirect the request to the django's running port. 
Such as `python manage.py runserver 0.0.0.0:8080`

Should i redirect the request to port "8000"

Not sure if i am making any sense.

**Comment by patrys** [comment]
We do not recommend running Django in production using `runserver`. Saleor comes preconfigured for WSGI-based application servers and includes a [default configuration file](https://github.com/mirumee/saleor/blob/master/saleor/wsgi/uwsgi.ini) for [`uwsgi`](https://uwsgi-docs.readthedocs.io/en/latest/).

**Comment by Pacu2** [comment]
Please reopen if you have any further questions.
