### ISSUE TITLE
Deploy to Heroku failed

### ISSUE THREAD

**Issue by austineinstein** [mirumee/saleor#2217]
Please what could I possibly do in such situations; apart from minifying js files/ shrink images ? 

<img width="1440" alt="screen shot 2018-05-25 at 16 37 02" src="https://user-images.githubusercontent.com/12557036/40575439-032dc2c6-60dd-11e8-8e80-900e487bb7d0.png">

<img width="1107" alt="screen shot 2018-05-25 at 16 37 41" src="https://user-images.githubusercontent.com/12557036/40575452-1d7bc934-60dd-11e8-8f95-691feb357396.png">

In trying to push to heroku which I'm hosting on, I get this 
<img width="837" alt="screen shot 2018-05-25 at 16 41 27" src="https://user-images.githubusercontent.com/12557036/40575461-34a64a4e-60dd-11e8-80a1-e40c8b9ecf83.png">

**Comment by Pacu2** [comment]
I don't find this a problem, sending gzipped JS and CSS files would weight around 160KB altogether.

The error seems not related to the big files, have you set up your buildpacks properly on Heroku? Saleor needs nodejs and python to work properly

How did you deploy, manually or via 'deploy to Heroku' button on our initial page?

**Comment by austineinstein** [comment]
So I shrinked the pictures, the existing problem now are about the js files being too big. Please how can I possibly fix this ?
<img width="1275" alt="screen shot 2018-05-29 at 09 31 39" src="https://user-images.githubusercontent.com/12557036/40647358-97eb7bcc-6323-11e8-90f0-1d91f72fb079.png">

**Comment by austineinstein** [comment]
<img width="812" alt="screen shot 2018-05-29 at 09 46 09" src="https://user-images.githubusercontent.com/12557036/40648264-e426283c-6325-11e8-9f38-230ea03145cc.png">

**Comment by patrys** [comment]
@austineinstein The size warning is just that, a warning. It's not the cause of the problems you're having. It seems that you're using an older build of Saleor.

What happens if you change the `scripts` section of your `package.json` to match what is currently on `master`. Mainly:

```
  "scripts": {
    "build-assets": "webpack -p --progress",
    ...
  }
```

**Comment by austineinstein** [comment]
Thank you!
