### ISSUE TITLE
Countries in address form are not sorted alphabetically due to translation

### ISSUE THREAD

**Issue by mad-anne** [mirumee/saleor#2220]
List of countries in the AddresForm used during checkout is not sorted alphabetically due to translation. As a result, when language is set to different than English, sorting doesn't change.

Below is a screenshot showing that in polish translation Czarnogóra (eng. *Montenegro*)  appears after Mongolia.

![checkout-list](https://user-images.githubusercontent.com/20802901/40622260-ed949ffa-62a0-11e8-9baa-69c507a1bf27.png)

**Comment by DigitalProFound** [comment]
can anyone help me to install this on my domain ? please
