### ISSUE TITLE
Checkout process improvements

### ISSUE THREAD

**Issue by mad-anne** [mirumee/saleor#2234]
During my work on PR #2206 I found out few things that may improve checkout process.

#### Going forward/back between steps

Although we can go back to shipping address step from choosing shipping method, we can't go back from summary step, where billing address is set. I think that passing between steps should be allowed.

#### Clearing cart

We can remove every single item from cart, but there is no button like `Clear cart`. It would be useful, when customer wants to cancel all cart lines at once.

**Comment by NyanKiyoshi** [comment]
@maarcingebala what about "Going forward/back between steps"? We probably could go for something like [that](https://aramvisser.github.io/bulma-steps/#example)?
