### ISSUE TITLE
[GDPR] Data removal tool

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#2235]
A logged in user should have the ability to remove their own data (and effectively close their account).

We should likely require a confirmation link to be clicked to prove that the person has access to the email address of the logged in account, otherwise, data removal could become a DoS attack vector.

Anonymous users should have a way to request their data being removed by providing an identifying piece of information like the email address or a phone number. Similar confirmation methods could be used to ensure this feature is not abused with malicious intent.

As the store is required to fulfill any outstanding contracts, orders and financial records should be preserved until they are no longer needed.

**Comment by Pacu2** [comment]
When deleting User's account, should we remove `user_email`  from `Order` and `phone number` from order's addresses as well? 
I don't find them necessary to keep

**Comment by Pacu2** [comment]
Should we keep a track of who deleted which user?

**Comment by patrys** [comment]
We should not delete any address data as we may still need to contact the user regarding their orders. We have a contractual requirement here but also a legal obligation (the store still needs to be able to accept returns, replacements, refunds and so on).

As for keeping track of who deletes whom:
* if the user deletes their own account we don't need to keep track of that as long as we make sure random people can't delete data that belongs to others
* if an admin fulfills a right to be forgotten in response to a legitimate request, the company is required to keep this information in an audit log (it's company-level, like accounting, not specific to Saleor, and we don't need to provide such functionality as part of this issue)

**Comment by Pacu2** [comment]
During this issue, I'll handle #2000 and #1966 as they seem related to the problems I'm facing. 
eg. staff user deleting another's staff user account 
I'll introduce another permission 'edit_staff' for this purpose
