### ISSUE TITLE
Cart migration fails: cannot drop/alter table `cart_cart`

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#2236]
It looks like merging cart with checkout generated a migration that causes problems:

```console
$ python manage.py migrate --no-input
...
Running migrations:
  Applying checkout.0007_merge_cart_with_checkout...Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: cannot ALTER TABLE "cart_cart" because it has pending trigger events
```

**Comment by NyanKiyoshi** [comment]
If it can help:

```
ERROR: cannot drop table cart_cart because other objects depend on it DETAIL: constraint cart_cartline_cart_id_c7b9981e_fk_cart_cart_token on table cart_cartline depends on table cart_cart HINT: Use DROP ... CASCADE to drop the dependent objects too.
```

**Comment by NyanKiyoshi** [comment]
@patrys could you rename the issue title so people can find this issue easier if they run into it (very likely)?

If people don't care about losing carts, they can run this on their database as temporary solution:
```sql
TRUNCATE TABLE cart_cart CASCADE;
```

**Comment by Pacu2** [comment]
Just successfully deployed to Heroku, not sure if the issue still persists?

**Comment by patrys** [comment]
It only breaks if you have existing data from before that migration and try to upgrade.

**Comment by NyanKiyoshi** [comment]
@Pacu2 as this migration was introduced by #2206 (v2018.05), it's only concerning people that were using Saleor before the 2018.05 release. 

Here are the steps to reproduce the issue:

1. Checkout and migrate ([v2018.04](https://github.com/mirumee/saleor/tree/v2018.04)),
2. Login as user (can still be done after adding the item to the cart),
3. Add an item to the cart,
4. Checkout to master (or v2018.05),
5. Run the migrations.

The migrations should fail.
