### ISSUE TITLE
Saleor - Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by YunazGilang** [mirumee/saleor#2254]
Hi, i am new in using saleor. I ve been creating my custom saleor in my repository : https://github.com/YunazGilang/saleor-custom . I ve been adding several npm package. Now I dont know what i have done, but now my saleor-custom shows error in it's console log.
![image](https://user-images.githubusercontent.com/22442215/41027299-d8cb8974-69a0-11e8-99d5-ec5a70a45250.png)

I wan't to resolve that error. It seems like my saleor load an JQuery Ajax from CDN, and maybe that's the issue. but i don't know how to resolve or prevent my saleor from loading that.

### Steps to reproduce the problem

1. Adding several npm modules : lightgallery, slide-pro.
2. Editing the home and product-details template
3. Getting the error

**Comment by Pacu2** [comment]
Saleor loads storefront dependencies inside of `storefront.jsx` file, you can remove it from there.

**Comment by YunazGilang** [comment]
Yea thanks,  the problem has been solved now.
