### ISSUE TITLE
docker-compose web_1 | python: can't open file 'manage.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by emidiotorre** [mirumee/saleor#2259]
Hi, It's my first time working on a Django project, i succeded to get everything working fine, and i'm very happy with Django and Saleor. 
Until a few weeks ago everything went smoothly, but today i tried to restart the project using Docker for development and couldn't get it to work.

I'm using Windows 10 Pro v.1803 build 17134.48
Docker for Windows Community Edition Version 18.03.1-ce-win65 (17513)

and locally i have installed Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32

i follow the instructions on the docs to start up the docker containers at this page: https://saleor.readthedocs.io/en/latest/customization/docker.html

but when i try to run:
`docker-compose run web python manage.py migrate`

i get: 
```
Creating network "saleor_default" with the default driver
Creating saleor_db_1     ... done
Creating saleor_search_1 ... done
Creating saleor_redis_1  ... done
python: can't open file 'manage.py': [Errno 2] No such file or directory
```

i am using the default Dockerfile and docker-compose.yml

i face the same problem if i try to run `docker-compose up --force-recreate`

i even tried 
```
docker system prune
docker volume prune
```

to remove everything that could cause a conflict

I have tried to fix this in a lot of ways without any result, any help is greatly appreciated :)

**Comment by Pacu2** [comment]
Hi @emidiotorre 
A similar problem was mentioned here: https://github.com/mirumee/saleor/issues/1689
Could you try the solution proposed?

**Comment by emidiotorre** [comment]
I looked into It and the problem seems to appear when you mount a volume outside the C:/Users folder, so i moved the project, because i didn't want to spin up a VM just to mount a volume as it is done with node-docker-share. BTW i'll try and let you know, thanks

**Comment by maarcingebala** [comment]
We were doing a lot of changes in Docker configuration recently. Could you update your codebase with recent `master` and try to set everything up again? I'd recommend removing all containers and rebuilding them from scratch.

**Comment by carstenblt** [comment]
Why did I buy a Windows machine again? Ran into the same problem today.
Use this:

docker-compose run -v "C:/Users/pathtoyour/saleor:/app" web manage.py ...

**Comment by pavanmaradia** [comment]
Same thing happens to me. My configuration was, docker-desktop in windows 10. I have figured that i have changed my windows password and docker does not able to access my c or d drive which one i shared with docker desktop. Quick fix was reset credentials from docker-desktop > shared Drives > reset credentials at bottom.

**Comment by NyanKiyoshi** [comment]
I'm guessing you have do this for windows?
docker-compose run -v "C:/Users/pathtoyour/saleor:/app" web **python** manage.py ...

**Comment by angel-jadan** [comment]
Tengo el mismo inconveniente, por favor ayudeme si alguien si logro solucionar el error
