### ISSUE TITLE
Feature: generate invoice when order is placed

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2268]
### Objective
The objective of this feature is to generate a PDF invoice when order is created (checkout or dashboard) that cannot be changed as it is requiring by the law.

#### 1 — Generation and Storage

1.1. The invoice is generated at order creation (async);
1.2. The invoices are stored in a private storage;
1.3. The storage would be code controlled access to avoid unauthorized access;
1.4. This has in mind that the user is *obviously* using a cloud storage solution to ensure the long term storage.

#### 2 — Invoice Language
2.1. Invoices would be generated using the request language assuming the customer would only want its invoice with its current language.

#### 3 — Handling of Missing Invoices

3.1. I would suggest, that we generate invoices during migration;
3.2.1. In case of missing file, I would suggest to throw a 404.
3.2.2. **The risky thing is that we don't ensure that the PDF was generated successfully (e.g.: AWS S3 is down for maintenance).**

#### 4 — Access to Invoices
4.1. Customer can access the order invoice from the order details view;
4.2. Customer can't access others' invoices;
4.3. Staff users with order access can access invoices from order details in dashboard through a 'Client Invoice' button.

---

### Placement of an order
![](https://i.imgur.com/R6K7NYe.png)

### Access to invoice (private storage)
![](https://i.imgur.com/ML8Txaj.png)

**Comment by Pacu2** [comment]
How about the orders that were placed, but their payment wasn't successful?

**Comment by NyanKiyoshi** [comment]
Payments are not mattering for the invoices, they are only saying what is to be paid for the given items or services.

**Comment by NyanKiyoshi** [comment]
Thus, we would be generating a receipt instead, as invoices are an invitation to pay.

The issue with Saleor is that we don't ensure invoice data are frozen, which is required by the law that the invoice cannot be changed (we have organisms in France checking if we can edit invoices or not).
Right now, the only frozen copy we have is the order confirmation email, which cannot be retrieved from dashboard/ frontstore and can be deleted.

We can edit the order, but only be able to generate a credit note without the invoice changing.

**Comment by itsgauravjain22** [comment]
Is saleor able to have pdf invoices of orders?
It's a required domain of any ecommerce platform.

**Comment by maarcingebala** [comment]
We're working on it currently, will be released within the next 2 or 4 weeks.

**Comment by itsgauravjain22** [comment]
@maarcingebala Thanks for the update. Will be waiting for it.

**Comment by segidev** [comment]
@maarcingebala Any news on that?

**Comment by maarcingebala** [comment]
Yes - a good one! Backend for invoices is finished on branch `feature/invoices` and now it's waiting for related frontend work in the dashboard. All of that should be merged to master at the beginning of next week.

**Comment by DmytroRohaninMashub** [comment]
@maarcingebala Can't find the feature/invoices branch, is it already merged?
