### ISSUE TITLE
Feature: generate cart permalink from current cart

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2269]
### What I'm trying to achieve
The objective would be to let the user create its cart, and add an option at the bottom to get the permalink to it.

It would allow users and staff users to share pre-composed carts.

It would also allow users to compose some kind of saved carts.

### A first solution
A solution that is currently used in production, is to get the current cart items and generate a short link that contains the item ID and the quantity as follows.

```
/...../{line.variant_id_1}-{line.quantity_1}-{line.variant_id_n}-{line.quantity_n}
```

As @elwoodxblues said some time ago, the issue with this solution is that we are exposing the variants ID to the user (which are already currently exposed in frontstore).

### A second solution
We could introduce a feature of "saved lists" which would allow the user to add and manage items lists and allow them to:
- get to get a permalink;
- add to cart;
- manage them.

This solution kind include #1120 which is often a pre-created list.

**Comment by Pacu2** [comment]
We could create an uuid token field on the Cart that would be used only for sharing
