### ISSUE TITLE
Add mutations for permission groups

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2289]
Add GraphQL mutations for managing the permission groups:
- [ ] `permissionGroupCreate(name: String!, permissions: [PermissionEnum!])`
- [ ] `permissionGroupUpdate(id: ID!, name: String, permissions: [PermissionEnum!])`
- [ ] `permissionGroupDelete(id: ID)`
- [ ] `permissionGroupAssignUsers(id: ID!, users: [ID!])`
- [ ] `permissionGroupUnassignUsers(id: ID!, users: [ID!])`

Queries:
- [ ] `permissionGroups` - returns connection of permission groups, ability to sort by name, filtering by name
- [ ] `permissionGroup(id: ID!)`

**Comment by elwoodxblues** [comment]
Related discussion: #2291

**Comment by Pacu2** [comment]
I think it's no longer needed after we've dropped groups.

**Comment by maarcingebala** [comment]
We need to revert permission groups (we want to call them "user roles") in API as a primary way of managing user permissions. Underneath we can use Django's permission groups for that.
