### ISSUE TITLE
Mutation to reset password by email

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2292]
We have mutations to create users through the API: `customerCreate` and `staffCreate`, but they don't allow to set the password. Both of them should be extended with an extra argument: `send_password_email: Boolean`. If set to true, this argument would trigger sending an email with a link to set the password.

We should also add the mutation to trigger this action once the user is created:
`passwordReset(id: ID!)` - clear password and send an email with a link to set it up.

**Comment by patrys** [comment]
If `passwordReset` requires a user `ID` then we create a chicken and egg problem for regular users where if you don't know your current password there's no way for you to obtain your user ID.

**Comment by elwoodxblues** [comment]
True, this would work only in the dashboard where we have the users list. Then we could instead use `email` since it is unique. This mutation should also only send the email, without clearing the password, as I originally wrote.
