### ISSUE TITLE
Problems installing: Django looks in python environment 

### ISSUE THREAD

**Issue by RoelantStegmann** [mirumee/saleor#2299]
Trying to install saleor on a webfaction server, but I'm running into some problems. 

### Steps to reproduce the problem
1.  When going to my website after collectstatic, it seems that django looks for the static files in the environment path

```
    The joined path (/images/placeholder255x255.png) is located outside of the base path component (/path/to/lib/python3.6/versatileimagefield/static)

    20 | </ol>
    -- | --
    {% else %}
    <p>{% trans "None" %}</p>
    {% endif %}
 
    <h4>{% blocktrans count staticfiles\|length as staticfiles_count %}Static file{% plural %}Static files{%     endblocktrans %}</h4>
    {% if staticfiles %}
    <dl>
    {% for staticfile in staticfiles %}
    <dt><strong><a class="toggleTemplate" href="{{ staticfile.url }}">{{ staticfile }}</a></strong></dt>
    <dd><samp>{{ staticfile.real_path }}</samp></dd>
    {% endfor %}
    </dl>
    {% else %}
    <p>{% trans "None" %}</p>
    {% endif %}
 
 
    {% for finder, payload in staticfiles_finders.items %}
    <h4>{{ finder }} ({% blocktrans count payload\|length as payload_count %}{{ payload_count }} file{%     plural %}{{ payload_count }} files{% endblocktrans %})</h4>
    <table>`
```
My settings are 

```
MEDIA_ROOT = '/home/static/app/saleor/media'  # os.path.join(PROJECT_ROOT, 'media')
MEDIA_URL = 'https://img.website.com/saleor/media/'

STATIC_ROOT = '/home/static/app/saleor/static' #os.path.join(PROJECT_ROOT, 'static')
STATIC_URL = 'https://img.website.com/saleor/static/'
```

**Comment by NyanKiyoshi** [comment]
Hi!

For production use, you have to set up a static file serving. Django only serves static files on the development server.

You will need to add a static path to your web server config (nginx, Apache, ...):

| path | target |
|-|-|
| `/static` | `/home/static/app/saleor/static/` |
| `/media` | `/home/static/app/saleor/media/` |

For the media files (at least), the best would be to setup a S3 bucket to store and serve them.

**Comment by RoelantStegmann** [comment]
Hi!

Not sure I understand…

What I did:

  *   I made a Django app at /home/app/Djangoapp , this is website.com
  *   I made a static app at /home/app/staticapp, this is img.website.com
  *   I changed STATIC_ROOT to put the files in the static app
  *   I changed STATIC_URL to server from this second domain

If I have debug = false: it does find the image files on this second server, but still tries to load assets locally (javascript and css are not found). Don’t understand why this can be different? :)

If I have debug = true: it is not looking for the files on this second server, but rather in my python environment (nothing is found +  suspisciousfiles errors)

**Comment by RoelantStegmann** [comment]
Thanks for your reaction!

- static.website.com is a [nginx service](https://docs.webfaction.com/software/static.html#static-only).
- website.com is a [apache server](https://docs.webfaction.com/software/django/getting-started.html#configuring-django-to-serve-static-media)  using the standard setup of webfaction

Is there a way i can just e-mail you the domain? :) 

```
Failed to load resource: net::ERR_FILE_NOT_FOUND.%
storefront.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)*
storefront.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)*
storefront.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)*
```
% this starts with blob: (blob:website.com/some-hash-1231
* These are all trying website.com/static/assets/file.ext whereas I would expect them to try static.website.com/assets/fil.ext

**Comment by patrys** [comment]
@RoelantStegmann If you take a look at `webpack.config.js` you will see that the `publicPath` is set to either `/static/assets/` or whatever the contents of the `STATIC_URL` environment variable are. This affects paths that end up in `webpack-bundle.json` and in turn that are used by Django.

Just make sure it's set to a proper URL (ie. `//static.website.com/assets/` or `/assets/`) before rebuilding the assets.

**Comment by RoelantStegmann** [comment]
Thanks @patrys. I adjusted it to point to the other website, but what do you mean with rebuilding the assets? manage.py assets rebuild results in the below notification. 

```
No asset bundles were found. If you are defining assets directly within your templates, you want to use the --parse-templates option.
INFO django-assets No asset bundles were found. If you are defining assets directly within your templates, you want to use the --parse-templates option. [PID:89764:MainThread]
 ```

**Comment by patrys** [comment]
@RoelantStegmann I mean `npm run build-assets`

**Comment by RoelantStegmann** [comment]
I did a fresh installation to see if I could at least get it working with all the pictures in the same domain. Then I


  *   Followed the steps in https://saleor.readthedocs.io/en/latest/gettingstarted/installation-linux.html
  *   Change import .health_check to import saleor.health_check in wsgi/__init__.py to prevent an error with wsgi
  *   Added the domain to allowed_host
  *   Ran collectstatic

In debug=True I still end up with the SuspiciousFileOperation.

Exception Value:

The joined path (/images/placeholder255x255.png) is located outside of the base path component (/home/user/lib/python3.6/versatileimagefield/static)

Exception Location:

/home/roelant/lib/python3.6/django/utils/_os.py in safe_join, line 49



Pff, feels like I’m not doing anything strange so really lost now :/

**Comment by mayank-budhiraja** [comment]
> Hi! Not sure I understand… What I did: * I made a Django app at /home/app/Djangoapp , this is website.com * I made a static app at /home/app/staticapp, this is img.website.com * I changed STATIC_ROOT to put the files in the static app * I changed STATIC_URL to server from this second domain If I have debug = false: it does find the image files on this second server, but still tries to load assets locally (javascript and css are not found). Don’t understand why this can be different? :) If I have debug = true: it is not looking for the files on this second server, but rather in my python environment (nothing is found + suspisciousfiles errors) From: NyanKiyoshi <notifications@github.com> Sent: 20 June 2018 19:06 To: mirumee/saleor <saleor@noreply.github.com> Cc: RoelantStegmann <roelant_stegmann@live.nl>; Author <author@noreply.github.com> Subject: Re: [mirumee/saleor] Problems installing: Django looks in python environment (#2299) Hi! For production use, you have to set up a static file serving. Django only serves static files on the development server. You will need to add a static path to your web server config (nginx, Apache, ...): path target /static /home/static/app/saleor/static/ /media /home/static/app/saleor/media/ For the media files (at least), the best would be to setup a S3 bucket to store and serve them. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmirumee%2Fsaleor%2Fissues%2F2299%23issuecomment-398825151&data=02%7C01%7C%7C60d25eb2a3ec4cba7a3308d5d6d05aa9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636651112709090770&sdata=bb%2FkYeIhia4LeNI6H60bQSeA35JHTOHM5tHW%2BMGPm00%3D&reserved=0>, or mute the thread<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACJ8mJLGAYZPfoYsgMmHxW_IJ1YrPlKqks5t-oEEgaJpZM4Uu7Ua&data=02%7C01%7C%7C60d25eb2a3ec4cba7a3308d5d6d05aa9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636651112709090770&sdata=XtYzdjXbiZryt0aRGaJ2ldzpKqjtLfUmY43RRJW49mM%3D&reserved=0>.

@RoelantStegmann facing the same problem. Django cannot load the css and js files
