### ISSUE TITLE
Nav login links disappear when swapping from mobile back to desktop breakdown

### ISSUE THREAD

**Issue by jeszod** [mirumee/saleor#2304]
### What I'm trying to achieve
when switching from mobile back to desktop view, the login, register, and language picker nav links should reappear.

### Steps to reproduce the problem
1. Make browser window narrower than the mobile break point.
2. Make browser window wider than the mobile break point.

### What I expected to happen
The nav links should re-appear.

### Screenshots
![desktop](https://user-images.githubusercontent.com/17969485/41747587-7d27a9d0-757c-11e8-94a9-6cfca26e58b3.png)
![mobile](https://user-images.githubusercontent.com/17969485/41747588-7d366c54-757c-11e8-94d8-1f6d8927e02e.png)

**System information**
Operating system: MacOS High Sierra & Windows 10
Browser: Chrome 67

**Comment by NyanKiyoshi** [comment]
Can you try on a non-modified Saleor version? I cannot reproduce.

The language picker issue is mentioned in #2188.

**Comment by Pacu2** [comment]
Please reopen if this problem further exists on the latest master.
