### ISSUE TITLE
Business-to-business (B2B) model support

### ISSUE THREAD

**Issue by jfialkoff** [mirumee/saleor#2318]
### What I'm trying to achieve
Better support of business-to-business (B2B) sales.

In the B2B model, the customer is a business which, in turn, may have multiple purchasers (i.e., users), and whose purchasers may change over time. It is important in the B2B model to link all sales to the appropriate business-customer to inform marketing and customer relationship management decisions. Also, in the B2B model, certain sellers may offer discounts to customers that are purchasing in high volume, and may only offer certain products to specific customers.

It's also worth noting that I've evaluated a number of cart systems. I've only found 2 that, in my opinion, do a decent job of supporting the B2B model: TradeGecko and Odoo. TradeGecko's cart, however, is severely lacking in most of the features one expects of a cart (e.g., catalog browsing). Odoo's is fairly complete and would work for our initial needs. We'll likely be selecting Saleor, however, because we envision a number of future enhancements that are somewhat specific to our business and Saleor is fully open source while Odoo is only partially open source.

### Describe a proposed solution

- Introduce a `Company` model in the `accounts` module. This can be done in a way that doesn't disrupt B2C support. A `User` can then be optionally associated with a `Company` (via a foreign key). 
- `Users` who are associated with a `Company` will inherit settings from the associated `Company` including: `addresses`, `default_billing_address`, as well as a list of stored credit cards (as tokens). It doesn't look like stored credit card tokens are currently a supported feature so I think that would need to be introduced. I envision users being able to choose whether or not to share the credit card with the whole company or make it private.
- Add an optional `Company` FK to `orders.Order`.
- Modify the order history view to show all orders placed by the company-customer in the case that the `User` is associated with a `Company`.

I am happy to make these changes and submit them to the core. I much prefer that to maintaining a separate branch, and I think that these features would look particularly valuable to B2B users such as ourselves, especially given the dearth of solutions.

### Other solutions I've tried and won't work
I can't really think of another solution to this. The best alternative would be to use a separate inventory/order management system that would identify the order's company using the users's email address (or a custom field for customer_id). A solution of this nature would only support a subset of what I'm trying to achieve, however. For example, I wouldn't be able to show a user a list of all the orders made by their company - only the orders they've made.

### Screenshots or mockups
I don't think this is necessary but I'm happy to provide some if requested.

**Comment by f3n1Xx** [comment]
Oh i need this please. I will be very eager to contribute on this. But need someone to guide.

**Comment by jfialkoff** [comment]
I've begun this work here: https://github.com/jfialkoff/saleor/tree/b2b

**Comment by maarcingebala** [comment]
Hey @jfialkoff, I'm happy to read that you're choosing Saleor. I'd like to share my thoughts on your issue.

My main concern about it is how general is the use-case of the `Company` model and whether it will be useful and understandable to others. For sure it can't interfere with the flow for regular customers, and the visibility of it in the UI should probably be switchable in settings (I guess).

If I understand correctly, you will use that model mainly to group the orders and share addresses between users. I'm not sure though if we would use that for sharing credit cards, as we don't store them in Saleor and I guess we'll never be. This is due to security reasons (we want payment gateways to be responsible for that), second, we're planning a new storefront with checkout based on the Payment Request API, that stores credit cards in the browser. I don't know if sharing credit cards as you described would work then.

You also wrote about offering discounts or products to specific customers based on the `Company`. To me, it sounds like a more general feature that I'd love to have in Saleor - customer groups. As a shop admin, you should be able to create arbitrary groups of customers based on various rules, e.g., a number of placed orders, total money spent or belonging to a particular company. Those groups could be then used to create specific discounts or product-visibility rules.

Do you think that implementing such general approach would solve your issue?

**Comment by jfialkoff** [comment]
Hey @maarcingebala, thanks so much for truly considering this, and for your well thought out reply. I don't have any data to back up the claim that this is generally useful but it's hard for me to understand how it wouldn't be, at least for companies that operate on this model. That said, I think B2B is a little behind B2C when it comes to ecomm so the demand might not be there, and many B2B companies have probably just shoehorned themselves into a B2C solution. I'd prefer something that works correctly for us.

I also can't speak to how intuitive it would be. It seems intuitive to me but I'm clearly biased and entrenched in the B2B market.

As far as approach, I do really like your suggestion of  Customer Groups. That sounds really powerful, and was offered by many of the systems I evaluated. That alone won't satisfy my needs because it won't allow for shared order history, addresses, or CCs (more on this later). However, I do see it as a more general, and superior, solution to offering different product sets and unique pricing. I'd be happy to use this approach to satisfy those requirements. I'd have to allow the list to to include companies and customers though. It'd be good to code this alongside a core developer since there are some design decisions we'd need to make, and I'd want to ensure the Mirumee team would accept it into master once complete.

Regarding CCs, thanks for sharing info about moving to the Payment Request API. That's a pretty interesting development I wasn't aware of. I don't think my proposal is incompatible with that move. 

First, a clarification on storing CCs: I didn't mean to recommend storing actual information about the CC. The recommended approach here is to let the gateway gather all the information and return a token. With the token, you can get some non-sensitive data like name, and last 4 digits. With this approach you don't need to worry about PCI compliance. Not sure if that's an international standard or not though.

So now, a case for stored CCs. Many businesses doing online sales will also do sales and support over the phone. With a stored CC token, a representative can make a purchase on behalf of a customer much more easily, and certainly more securely (since the representative will never see all the CC info, and the information isn't passed over an insecure phone line). I do like the idea of using the Payment API, but whether the user enters their info manually or it's gathered through the API, I'd strongly argue for a stored CC feature.

It might be good to do a video chat sometime if that works for you. There's a lot to weed through here, and it seems like a voice conversation would be more efficient. Thanks!

**Comment by maarcingebala** [comment]
@jfialkoff Sure, feel free to reach me via email: marcin@mirumee.com and I'd be happy to schedule a video call with you to talk about this issue as well as our plans.

**Comment by NyanKiyoshi** [comment]
@jfialkoff what do you have in mind for companies discounts? In production we had global discounts for given companies (fixed percentage in user account), and the logged company user sees the prices with that percentage removed. 

I'm gonna re-implement tomorrow or the following day, so if there are things that could be taken into consideration maybe for a PR.

Is this also what you are looking for? Applying a account fixed percentage to every products, no matter what category, etc.

**Comment by jfialkoff** [comment]
Hey, thanks for checking in. My goal would be to be able to specify a discount (as a percentage or absolute value) to a particular category, product, or variant. I would also like the ability to override the `active` state of a product. This way, for my use-case, certain products could be made available only to certain companies. This is relevant to us because we produce custom products for our customers that they tend to repurchase. It might be better to introduce a new `available` state for this purpose instead of repurposing `active`. 

In my ideal world, you would be able to set availability, and discounts at the global, category, product, and variant level. A good way, in my opinion, to present this to users is to introduce an interface for managing groups - a set of customers and/or companies (according to @marekbrzoska 's suggestion). Then, there'd be another interface for overriding price and availability for any category, product, or variant for any single group.

One issue that comes up here is what to do in the case that a single customer/company has multiple overrides for the same category/product/variant. In that case, I'd propose we just give them the most favorable price.
