### ISSUE TITLE
Identify customer name from user attributes rather than address

### ISSUE THREAD

**Issue by jfialkoff** [mirumee/saleor#2324]
### What I'm trying to achieve
A more intuitive handling of customer name. Currently, it seems that the User's `first_name` and `last_name` fields are ignored. Instead, the user's name is gathered from `default_billing_address`. This seems non-ideal for a few reasons:
1. It's unintuitive. When I edit a customer in Dashboard, I expect to see (and be able to edit) the customer's name.
2. There are use-cases where the user's name might be different than the name attached to the billing address. For example, a child who's purchasing using their parents' credit card.  Or, a company's representative purchasing with the company president's card.

Another minor complaint is a slight wasting of resources. To get a list of user's with their name requires a table join.

### Describe a proposed solution
Refactor code to use `User.first_name` and `User.last_name` instead of fields on `default_billing_address`.

### Other solutions I've tried and won't work
N/A

**Comment by maarcingebala** [comment]
I also find it unintuitive. This is also a problem in case of staff users who may not use addresses at all, so there would be no way to set their first and last name. I guess we should add `first_name` and `last_name` to the `User` model and use that to represent the user in UI (probably along with the email).

**Comment by patrys** [comment]
Please note that there is currently no `first_name` or `last_name` on user model.

**Comment by jfialkoff** [comment]
Ahh, right. I was thinking that `AbstractBaseUser` had those fields but I see it does not. In any case, easily added.

**Comment by jfialkoff** [comment]
@maarcingebala and @patrys , how do we feel about moving on this? I'm running into some roadblocks with #2318 (I'll open a pull request for this shortly) because we're getting the user's name from `default_billing_address`. Can I move ahead with the work to add first_name and last_name to `User` as part of that work?

**Comment by patrys** [comment]
I think we're both 👍 on this but neither had the chance to pick this up.
