### ISSUE TITLE
Group form is showing multiple times the same thing/ text

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2343]
### Steps to reproduce the problem
1. Edit a group.
2. It should show multiple times the same things.

### Screenshots
![screenshot](https://i.imgur.com/PlMhbYw.png)

**Comment by NyanKiyoshi** [comment]
Looks like it may be an issue with migrations, as the `Permission` model doesn't have any constraint ensuring the uniqueness.

**Comment by Pacu2** [comment]
Is this problem still relevant after we've dropped groups?

**Comment by maarcingebala** [comment]
Should be fixed now.
