### ISSUE TITLE
Option to toggle html editor

### ISSUE THREAD

**Issue by fpytloun** [mirumee/saleor#2347]
### What I'm trying to achieve

Medium editor is nice but it has only very limited set of features.
My use-case is to have complex product pages with images, etc. so I typically need to add classes to some elements, etc.

### Describe a proposed solution

For more complex pages, it would be good to implement `Toggle html editor` button in dashboard to switch into direct HTML editing mode.
It should be simple but I am not very familiar with Javascript to implement this correctly.

**Comment by maarcingebala** [comment]
Our intention was to keep the editor simple just as Medium does and provide features that work in most cases. I understand however that some people may want to use it to build more complex pages. My only concern is what to do with the HTML sanitization we have in the backend (see `ALLOWED_TAGS` in settings.py). We would have to either extend it to allow for more common tags (which sounds a bit cumbersome) or exclude those that are forbidden, like scripts or iframes.

**Comment by NyanKiyoshi** [comment]
Scripts are useful as well, for showing some dynamic components like maps.

So that's quite difficult to know what we should allow or not. Maybe we could have a permission that allows "advanced tags/ content" in the rich text editor, and if someone that doesn't have that permission tries to edit/ create a page with a `script` tag for example, would get an error (no sanitization, otherwise they break the page content).

**Comment by fpytloun** [comment]
Or enhance medium editor by developing plugin that would allow setting classes on objects + implement couple of extensions:
- http://linkesch.com/medium-editor-insert-plugin/
- https://github.com/yabwe/medium-editor-tables

Maybe some more from the list https://github.com/yabwe/medium-editor/wiki/Extensions-Plugins

**Comment by NyanKiyoshi** [comment]
What would be perfect in the case of a e-commerce website would be a wysiwyg editor with grid layout to allow users to build easily a user friendly and responsible page. Which would allow users to be able to make great product show cases for the customers.

A good example is mailjet's editor: https://www.mailjet.com/feature/passport/

There is also wix that some people use, which is also achieving a responsive design and fully customization page (but seriously not to use, it's filled with `position: absolute` and pages are taking 5 minutes to load so much the generated pages are heavy).

I can't get my hands onto a wysiwyg editor allowing users to use grids as layout.

**Comment by fpytloun** [comment]
That would be great :-)
Anyway for now, having just this simple option would be sufficient. There's currently no way how to customize style in pages.
Does anyone know about easy way how to implement this toggle?

**Comment by fpytloun** [comment]
Is anyone able to help me with implementing html editor toggle for Medium Editor?
I suppose it should be trivial, javascript only thing.

**Comment by maarcingebala** [comment]
@fpytloun Have you looked for a solution in the [medium-editor](https://github.com/yabwe/medium-editor) repository? I'm not sure, but maybe there is such option in the configuration. I would also search for an answer in their issues.

**Comment by petedermott** [comment]
This is sort of possible to do without massive amount of editing.

First edit /saleor/static/dashboard/js/components/editor.js file to add the following to the toolbar buttons object:
`      {
        name: 'html',
        aria: pgettext('Rich text editor option', 'HTML')
      },`

Then edit /saleor/dashboard/products/forms.py file to strip out the cleaning methods of the RichTextField e.g:
`class RichTextField(forms.CharField):
    """A field for rich text editor, providing backend sanitization."""

    widget = RichTextEditorWidget

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.help_text = pgettext_lazy(
            'Help text in rich-text editor field',
            'Select text to enable text-formatting tools.')

    def to_python(self, value):
        # tags = settings.ALLOWED_TAGS or bleach.ALLOWED_TAGS
        # attributes = settings.ALLOWED_ATTRIBUTES or bleach.ALLOWED_ATTRIBUTES
        # styles = settings.ALLOWED_STYLES or bleach.ALLOWED_STYLES
        value = super().to_python(value)
        # value = bleach.clean(
        #     value, tags=tags, attributes=attributes, styles=styles)
        return value
`
Making these changes will allow admins to write html, highlight it and then click a HTML button in the editor to turn it into proper HTML. A few things to be aware of:

1. This is **potentially dangerous!** The code is stripped of tags to ensure that staff members don't add code that could cause problems, such as changing their account to be a super-user, if you don't 100% trust your users then don't make this change.
2. The remove formatting can be a little buggy so the best way to write / update any text added like this is to write it as HTML in an external editor then copy and paste it into Saleor before hitting the HTML button

**Comment by fpytloun** [comment]
@petedermott Thank you! It's not exactly a html toggle implementation but works as a workaround for now :-)

**Comment by NyanKiyoshi** [comment]
You could also add a settings key `EDITOR_ALLOW_UNTRUSTED_CODE` or something like that. So you don't end up with failing tests.

**Comment by carstenblt** [comment]
There are two parts to it: server-side filtering of tags and the editor. The filtering is fine, however the editor is pretty much unusable for me. As soon as it gets to placing images for example it gets pretty much impossible to design a good page. There are better alternatives out there, but a button to switch to pure HTML would help a lot!
