### ISSUE TITLE
Session caching cannot work with locmem backend

### ISSUE THREAD

**Issue by jxltom** [mirumee/saleor#2354]
I am just curious. Is this the limitation with django or only with saleor?

From django doc, I didn't find any hints which imply that locmem can not work with cached_db in sessions.

THANKS.

**Comment by patrys** [comment]
It cannot work when you have multiple workers (which is a typical production setup). As worker processes cannot share memory you end up with one cache per worker and no way to ensure cache is properly propagated and invalidated across the entire application. A typical symptom is that users only appear to be logged in on every n-th request.

**Comment by jxltom** [comment]
@patrys Thanks a lot for your quick and clear explanation :+1: 

So we should use non-cached session or cached session with non-local cache backend.
