### ISSUE TITLE
Deployment to Bluehost.com

### ISSUE THREAD

**Issue by NumanIjaz** [mirumee/saleor#2364]
Hi
I am new to this saleor project. I have set up the project on my local machine and now I want to deploy the project on bluehost.com
Can you please guide me the steps to perform for the deployment?

Thanks

**Comment by Pacu2** [comment]
We have a guide for docker deployment, I think it can be used in your case.

There was some discussion regarding Bluehost (and shared hostings in general) in #1986, you might find it helpful.

**Comment by maarcingebala** [comment]
Please reopen if you have any particular problems.
