### ISSUE TITLE
Demo store doesn't get parent categories' children

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2365]
### What I'm trying to achieve
Browse all the groceries on the demo branch.

### Steps to reproduce the problem
1. Browse the `Groceries` category ([direct link](https://demo.getsaleor.com/en/products/category/groceries-7/));
2. Look the listed products;
3. There are no product showing if the bug is there.

### What I expected to happen
Having the list of coffees and candies as they are the children.

### Screenshots

[![Screenshot](https://i.imgur.com/xRZsQKnl.png)](https://i.imgur.com/xRZsQKn.png)

**Comment by maarcingebala** [comment]
This has been resolved.
