### ISSUE TITLE
Promo & Sale

### ISSUE THREAD

**Issue by KingOlami** [mirumee/saleor#2366]
I am new to django saleor so I was working arounfd it and I could not figure out how to add a promo banner via the dashboard and if i had a navigation via the dashboard how do I make it refelect on the home page

**Comment by Pacu2** [comment]
At this moment there's no way to edit templates (other than static pages) via the dashboard, you should edit them directly.

In `Navigation` tab on the dashboard, you have an option to change your currently active menu.

**Comment by Pacu2** [comment]
Please reopen if you have any further questions
