### ISSUE TITLE
Pagination: better backend implementation

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#2377]
### What I'm trying to achieve
Currently we're exposing a cursor-based API (which is great) but internally we still cast it to page numbers which result in an `OFFSET` + `LIMIT` database query.

Unfortunately using `OFFSET` means the database has to fetch `OFFSET` + `LIMIT` rows and then discard the first `OFFSET` results before sending the remaining ones to the client. This means the cost of each page increases linearly with the page number and there's risk of temporary disk tables being used for pages where the number of required rows exceeds the available results buffer.

It's slow when using pagination in your own shop but can become a denial-of-service attack vector for deployments under software-as-a-service model where a malicious agent could intentionally put stress on the database server.

### Describe a proposed solution
I propose that we cease to use the connection fields provided by `graphene-django` and instead write a resolver that takes care of both filtering and pagination and embraces the cursor based approach (where the resulting query should only utilize `WHERE` and `LIMIT` without an `OFFSET` clause). This way database indexes can be used and the workload related to fetching any particular page is independent of the page number.

In addition we would be free to use data loaders which are currently incompatible with the `DjangoFilterConnectionField`. This is a major performance win.

### Other solutions I've tried and won't work
I've considered extending the `DjangoConnectionField` but as the query is sliced inside the field's implementation we would likely need a separate class for each model. I think just writing a resolver for each case and maintaining a common structure for results is much easier.

**Comment by kswiatek92** [comment]
opened issue in graphene-django
https://github.com/graphql-python/graphene-django/issues/829

there's workaround (useless in our case)
https://gist.github.com/crucialfelix/d14506cdb9d3a04427a72aadcad30af4

**Comment by patrys** [comment]
I don't think the upstream issue is related. In our case, we want to improve SQL queries, the upstream ticket seems to be about time spent in Python.

**Comment by kswiatek92** [comment]
it's not direct but `resolve_connection` in `DjangoConnectionField` use count() which slows sql query, if we manage to fix this without losing any feature, we could propose this as solution to issue above

**Comment by patrys** [comment]
See #5149
