### ISSUE TITLE
Having variants mutates 'Add to cart' button appearance

### ISSUE THREAD

**Issue by raybesiga** [mirumee/saleor#2384]
### What I'm trying to achieve
I wish to have my "Add to cart" button use the generic `btn btn-primary` class. The code for it in `orderform` block is as follows:

```django
{% block orderform %}
          {% if show_variant_picker %}
            {% csrf_token %}
            <div id="variant-picker" data-variant-picker-data="{{ variant_picker_data }}" data-action="{% url 'product:add-to-cart' product_id=product.pk slug=product.get_slug %}"></div>
          {% else %}
            <form id="product-form" role="form" class="product-form clearfix" method="post" action="{% url 'product:add-to-cart' product_id=product.pk slug=product.get_slug %}" novalidate>
              {% csrf_token %}
              {% bootstrap_field form.variant %}
              <div class="product__info__quantity">
                {% bootstrap_field form.quantity %}
              </div>
              <br>
              <div class="form-group product__info__button">
                <button class="btn btn-primary">
                  {% trans "Add to Cart" context "Product details primary action" %}
                </button>
              </div>
            </form>
          {% endif %}
        {% endblock %}
```

When I have a product with no variants, it works perfectly fine and show below:

![screen shot 2018-07-11 at 11 55 06](https://user-images.githubusercontent.com/405697/42564549-55423fae-8501-11e8-8049-365a20f9e0b4.png)

However, when the product has variants, such as size, it drops the `btn-primary` class, at least in appearance, as shown below:

![screen shot 2018-07-11 at 11 56 41](https://user-images.githubusercontent.com/405697/42564611-84e165fa-8501-11e8-98f3-516c2c25e4e4.png)

Why is this the case?

**System information**
Operating system: Mac OSx 
Browser: Chrome

**Comment by Pacu2** [comment]
I think it's related to the javascript code inside `VariantPicker.js` file

**Comment by patrys** [comment]
In case variants need to be selected this section is replaced by a React component found in `saleor/static/js/components/variantPicker/VariantPicker.js`.

**Comment by raybesiga** [comment]
Oh wow @Pacu2 @patrys you guys are rockstars. Thanks. Just one last little thing. I think if you take a look at the bottom screenshot, you will see that the product description has `span` tags that are injected forcefully by the text editor. Is this a bug as well?

**Comment by patrys** [comment]
@raybesiga Please open an issue for this, it does look like a bug. If you can come up with steps to reproduce it would be even better.

**Comment by raybesiga** [comment]
I will do that. Thanks @patrys
