### ISSUE TITLE
Undefined names in test_product.py

### ISSUE THREAD

**Issue by cclauss** [mirumee/saleor#2393]
https://github.com/mirumee/saleor/blob/master/tests/dashboard/test_product.py#L268-L273

flake8 testing of https://github.com/mirumee/saleor on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./tests/dashboard/test_product.py:268:12: F821 undefined name 'response'
    assert response.status_code == 302
           ^
./tests/dashboard/test_product.py:269:34: F821 undefined name 'response'
    assert get_redirect_location(response) == reverse('dashboard:product-list')
                                 ^
./tests/dashboard/test_product.py:271:14: F821 undefined name 'product_list'
    for p in product_list:
             ^
3     F821 undefined name 'response'
3
```

**Comment by Pacu2** [comment]
Looks like a wrong merge

**Comment by NyanKiyoshi** [comment]
The commit that added those tests: https://github.com/mirumee/saleor/commit/aa5dc88d6260b1e0371a3395dcb48052810d6e62#diff-70296847f6f51488c62795d05f3cb4e4R258

The commit that broke the tests: https://github.com/mirumee/saleor/commit/e53ef3038928ccbc2c559586a4ef809e08cf07a6#diff-70296847f6f51488c62795d05f3cb4e4R256

**Comment by NyanKiyoshi** [comment]
How comes pytest doesn't raise a `NameError`?

**Comment by cclauss** [comment]
Because PyTest does not attempt to build an Abstract Syntax Tree for all .py files in the project/
