### ISSUE TITLE
Raven is not configured

### ISSUE THREAD

**Issue by NumanIjaz** [mirumee/saleor#2402]
Hi
While deploying Saleor project to heroku, I am getting an error when I run the command:
git push heroku master

The error info is following:

 INFO raven.contrib.django.client.DjangoClient Raven is not configured (logging is disabled). Please see the documentation for more information. [PID:1112:MainThread]

I am using windows command prompt, please see the image below:

![heroku deployment](https://user-images.githubusercontent.com/12031506/42719198-4dfcb554-8712-11e8-95ed-ab5e295d44cf.png)

Please help me in this regard.

**Comment by maarcingebala** [comment]
Btw we should be adding Raven client to INSTALLED_APPS only when SENTRY_DSN is set, this would prevent showing this INFO message when it is disabled.

**Comment by maarcingebala** [comment]
The issue with info log from Raven has been resolved. @NumanIjaz please open a new issue if you're still facing troubles with setting up Saleor on Heroku.
