### ISSUE TITLE
stylesheet and script missing (404 status)

### ISSUE THREAD

**Issue by xbandi** [mirumee/saleor#2411]
[Demo website](https://demo.getsaleor.com/) can't load script and stylesheet. 
![screenshot](https://user-images.githubusercontent.com/34173728/42760947-5946e92e-890c-11e8-8727-d5b8eb3f9c3f.png)

**Comment by Pacu2** [comment]
This issue is known to us and we are working on the fix, thanks for the reporting!

**Comment by maarcingebala** [comment]
Should be all right now.
