### ISSUE TITLE
Update Twitter badge in README.md

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#2414]
Current badge seems not loading for some reason
We could swap it for official twitter's one
```
<a href="https://twitter.com/getsaleor?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @getsaleor</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

**Comment by NyanKiyoshi** [comment]
What about this @Pacu2 https://github.com/NyanKiyoshi/saleor/blob/edit/twitter-badge/README.md?

I based the SVG on the script's one while trying to stay in a close style from the other badges.
