### ISSUE TITLE
[question] add date to a product

### ISSUE THREAD

**Issue by aguilbau** [mirumee/saleor#2425]
Hello, I want to add a date to a product, as the shop I'm building will have different products available each days.

I'm wondering which is the most "saleoric" approach to this ?
I was thinking about modifying the product model for this, however, I'm wondering if there is a way to do that without modifying the model.

Thanks in advance

**Comment by akjanik** [comment]
Hi @aguilbau. `Product` model has a variable `available_on`:
https://github.com/mirumee/saleor/blob/master/saleor/product/models.py#L107
In dashboard form, there is a field named `Publish product on (optional)` which refers to this field in the code.  
Is that wha you meant?

**Comment by aguilbau** [comment]
Ah yes totally ! I actually saw that in the code, but did not see it on the dashboard, i overlooked it.. Thanks a lot.

And also, is there a way to add a date to an order ? say, deliver on <this date>.

And last question.. is this the right place to ask questions ? :D

**Comment by akjanik** [comment]
Order have date assigned automatically, `placed on...`. To control delivery process, you use fulfillments - you may choose which (if not all) of the products (`lines`, more technically speaking) in the order are being shipped to customer.  
This is fine place to asks question, however, github often serves as place of solving technical issues - for problems of type "How to do..." I would like to recommend [gitter].(https://gitter.im/mirumee/saleor)

Also, you may check [documentation](https://saleor.readthedocs.io/en/latest/).

**Comment by aguilbau** [comment]
thanks you for your help ! i will close this issue now.
