### ISSUE TITLE
Fulfillment shipping_date field is not used

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2433]
In the `Fulfillment` model we have `shipping_date` which isn't used anywhere in the UI nor in the code. I assume that the idea behind this field is to give the user the expected date of shipping. To handle that field we should do the following:
- [ ] include this field in `FulfillmentForm` and `FulfillmentTrackingNumberForm`,
- [ ] include it in fulfillment emails sent to the customer,
- [ ] show it in the customer's order view in the storefront.

**Comment by akjanik** [comment]
This field is being used, it sets itself as the moment of creation of the fulfillment. We could consider to display it in dashboard UI or move this to dashboard 2.0.

**Comment by maarcingebala** [comment]
Since the `shipping_date` serves only the purpose of keeping the creation date of the instance, I would rewrite it to make it more consistent with the codebase to:
```
created = models.DateTimeField(auto_now_add=True)
```
