### ISSUE TITLE
Add the possibility to edit and insert VAT rules in dashboard

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2436]
Hi!

A saleor user was needing a way to edits taxes—since we are giving the users a way to fetch tax rates, we should also give them a way to edit the taxes themselves.

#### The form

The user can add a rate to a country, the user has two fields:

| Field name | Info |
| ---------- | ---- |
| The targeted country | This would set which country to apply this rate. |
| The rate name | This field is to be defaulting to the standard rate and will be a simple char field field. |
| The tax rate value | Nothing special about it, a percentage coded as double |

##### Adding a new rate and (eventually) add a new country
The user can add a new rate using the `add` button in the main VAT view, meaning they will have to select what country to target.

If the form is valid, and if the country is not in the list, it will be inserted, in the same time of this new rate.

If the country is already in the list, it doesn't create a new country (of course) but still inserts the rate (less steps for the users and no special logic required).

##### Adding a new rate to an existing country
The user can go to the VAT details of a country, where they will find a add button as well, this one will take care of filling the country field by passing the instance to the form (thus, we don't show the country field to the user).

##### Deleting or editing a rate from a country
Just like the attributes values view, we would have a simple `Delete` and `Edit` button on the right side of the rate.

##### Fetching rates
Fetching rates would override any edited or conflicting rates. What we could do is first of all, show a warning to the user letting them know about this.

In a second time, we could extend the current implementation of rate fetching to allow the user to select what they want to fetch and thus override or not.

We could allow the user to select countries (default: the whole Europe (as select option)) to fetch and countries to exclude in the case of the whole Europe being selected.

**Comment by NyanKiyoshi** [comment]
I believe it doesn't need to be implemented into the dashboard 1.0. Instead, it would just implementing it to the API and to the dahsboard 2.0 would be just great. This is definitively a feature that some people want to have.

But for now, I believe it is probably better to wait for the Avalara integration so we have a better idea of this should be structured, if some VAT logics were to change.

**Comment by decimoseptimo** [comment]
> I believe it doesn't need to be implemented into the dashboard 1.0. Instead, implementing it to the API and to the dashboard 2.0 would be just great. This is definitively a feature that some people want to have.
> 
> But for now, I believe it is probably better to wait for the Avalara integration so we have a better idea of this should be structured, if some VAT logics were to change.

@NyanKiyoshi Since both conditions have been met, might be good time to dust this off.

**Comment by dekoza** [comment]
Not available in 3.x
