### ISSUE TITLE
Add bulk edit

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2440]
### What I'm trying to achieve
Edit a lot of products in one go (or other forms that could be interesting to bulk edit).

Which means, we would change one field value in a form, and it would edit all the selected objects in one go.

Example: the user wants to add every product filtered (thus selected as well) to a given collection.

**Comment by maarcingebala** [comment]
In the current dashboard we already have some foundations for this feature:

![image](https://user-images.githubusercontent.com/5421321/43126414-f091de12-8f2c-11e8-89c2-ca6a63219f11.png)

At the moment there are only two actions available but it should be fairly easy to extend it with other actions. Adding products to collection is one of the typical cases for that.

We're planning to build this feature in the forthcoming Dashboard 2.0.
