### ISSUE TITLE
Log order and customer actions and events

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2443]
### What I'm trying to achieve
Keep track of whatever changes and actions were made by the staff.

This is useful to catch errors and check data changes.

#### 1 — Models
Introduce a new model containing log entries. A possible model (based on django-admin's `LogEntry` model) would be the following:

| field name | content |
| ---------- | ---- |
| action_date | Datetime of the action |
| action_type | Action type from the enum: `CREATE\|EDIT\|DELETE` |
| user | FK to `User` |
| object | Object type name or verbose name if available (e.g.: `Product Variant`) |
| object_info | The object representation through `__str__` |

This model would introduce a new listing view: action logs.

#### 2 — Event trapping
To only log dashboard action, we cannot trap at the model level efficiently (unless we want to log the whole website).

##### 2.1 — Object creation and update
Object creation and update could be trapped by making a base form receiving the user request object (to catch the requester) and handling calls to `save(...)`.

##### 2.2 — Object deletion
We could implement a method `delete_object(request, object)` to replace `object.delete()` to trigger a log creation.

#### 3 — Log saving
As the dashboard doesn't depend on logging, we probably could make log entry creation as an asynchronous task.

**Comment by maarcingebala** [comment]
As part of that issue, we should also think of the unified API for using events in the code (see #3966).

**Comment by NyanKiyoshi** [comment]
- For the gql type of OrderEvent we have to include:
	- A order_customer field of type User. (Null if it's an automated task) [1]
	- New fields for getting data from the JSON parameters. [2]
	- A payment method field taken from the parameters.

- The OrderEvent model should have:
	- A field [insert name] containing who triggered the event. [4]

- Introduce new order event types (OrderEventsEnum):
	- the order was placed
	- the order payment failed [failure event]-> what data? How to get the data and the payment ID/toke.
	- the order is ready to fulfill
	- the order is ready to be captured
	- the payment was captured (+ amount)
	- a note was added to the order
	- the order confirmation has been set
	- digital link was sent to the customer
	- Manual staff actions events:
		- the tracking email was sent
		- a draft was created
		- a shipping method was selected (no data)
		- added products (data, [how to store?])
		- removed products (idem)
		- order was manually fulfilled
		- order was manually marked as paid

- CustomerEvents:
	- the order was placed
	- a note was added to the order
	- downloaded digital link

- We need to migrate the old events to the new model.

[1] Allows to fetch all the order events from a given customer.
[2] Allows to retrieve additional data from an event (e.g., an amount, a quantity, a message, etc.)
[4] We want to know who triggered the event, even if it's the customer itself or a staff user.
