### ISSUE TITLE
Digital Downloads

### ISSUE THREAD

**Issue by saqibkhan2523** [mirumee/saleor#2444]
Hello, I am currently using saleor and I have to say it is amazing. Everything is setup and its easy to manage the store. I am making a digital store and I am finding it difficult to implement. Please can someone refer to some guide or give me some step here to handle a digital product, its payment and downloading part. It will be very helpful. 
Thanks.

**Comment by patrys** [comment]
Hello and thank you for the kind words! Have you considered joining the [community chat](https://gitter.im/mirumee/saleor) on Gitter?

**Comment by saqibkhan2523** [comment]
sure
