### ISSUE TITLE
Need add venv/ to .gitignore

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2451]
please add venv/ to .gitignore how default folder of VirtualEnv in top popular - Pycharm

**Comment by patrys** [comment]
FYI: you can exclude your local tools from tracking using a [global gitignore file](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore).

**Comment by mmmcorpsvit** [comment]
ok, hope this can help anither peoples: https://gist.github.com/subfuzion/db7f57fff2fb6998a16c
