### ISSUE TITLE
Product listing's clear filters button never shows up and doesn't work.

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2453]
### What I'm trying to achieve
Having the clear button to show up on filters.

### Steps to reproduce the problem
1. Go to a category,
2. Select filters values,
3. Apply;
4. No clear filters button is being shown.

### What I expected to happen
Having the clear filters button to be shown when some filters are selected. And it should redirect to `./` not to `../`.

**Comment by zdpx** [comment]
I'll take that

**Comment by zdpx** [comment]
I suppose that it is fixed now, please check.

**Comment by NyanKiyoshi** [comment]
All good! Thanks :+1:
