### ISSUE TITLE
Installation Error when running python3 manage.py migrate

### ISSUE THREAD

**Issue by kmanojkumar** [mirumee/saleor#2457]
### What I'm trying to achieve
I am trying to install Saleor on my Ubuntu machine with all dependencies and requirements installed successfully as per instructions on [http://saleor.readthedocs.io/en/latest/gettingstarted/installation-linux.html]

### Steps to reproduce the problem
1. Run `python3 manage.py migrate` after installing the requirements.txt
2. `TypeError: unhashable type: 'TaxedMoneyField'` - **Error is thrown and process exited**

### Screenshots
![screenshot 1](https://user-images.githubusercontent.com/14366356/43075220-bad0b1d4-8e9d-11e8-94da-8c24d085d531.png)

**System information**
Operating system: Ubuntu 17.10 Server
Python3: 3.6.3

**Comment by maarcingebala** [comment]
Hey, can you check what version of graphene and graphene-django is installed in your python env? You can do that by running: `pip freeze | grep graphene`. Please paste the output here. I'm wondering if it's related to #2454.

**Comment by kmanojkumar** [comment]
On running, `pip freeze | grep graphene` , here is the following output:
```
graphene==2.1.3
graphene-django==2.1.0
```

**Comment by maarcingebala** [comment]
So you have the newest versions. Please try downgrading those libs. Here are the commands you can use to install versions that work on my machine.
```
pip install graphene==2.0.1
pip install graphene-django==2.0.0
```

**Comment by kmanojkumar** [comment]
Thank you @maarcingebala , It worked!

I have uninstalled the existing packages using `pip uninstall` command and executed the commands you shared.

**Comment by maarcingebala** [comment]
There's a problem with those versions as described in #2454. I'm closing this one, let us know if you encounter any other issues.
