### ISSUE TITLE
How to Integrate Payment for PayUMoney

### ISSUE THREAD

**Issue by yogesh-kamble** [mirumee/saleor#2458]
I am developing Ecommerec site using Saleor Just want to know is it to possible to integrate PayUMoney into Saleor ?

**Comment by maarcingebala** [comment]
Hey @yogesh-kamble, we haven't done any integration with PayUMoney yet, but after looking briefly at their docs I don't see any reasons why it wouldn't be possible to integrate it in Saleor. Their API looks pretty standard - you have to gather your checkout data into a form, submit it to their API and provide redirect links for success and failure pages. They even provide code examples for Django of how this integration might look like: https://developer.payumoney.com/redirect/

**Comment by Pacu2** [comment]
Please reopen if you have any further questions
