### ISSUE TITLE
Installation on Ubuntu 17.10 Failed at the saleor@0.0.0 build-assets script 'webpack -p --progress'.

### ISSUE THREAD

**Issue by Ajorona** [mirumee/saleor#2459]
### What I'm trying to achieve
I am following the [getting started guide](https://saleor.readthedocs.io/en/latest/gettingstarted/installation-linux.html) using npm@3.5.2 and node@6.11.4. 

### Steps to reproduce the problem
1. On step 7: **python manage.py migrate** I get the exception: psycopg2.ProgrammingError: permission denied to create extension "hstore" HINT:  Must be superuser to create this extension.

I continued on from this step as the database tables were setup.

2. When I reach step 9: Prepare front-end assets and I run **npm run build-assets** I get the following npm debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build-assets' ]
2 info using npm@3.5.2
3 info using node@v6.11.4
4 verbose run-script [ 'prebuild-assets', 'build-assets', 'postbuild-assets' ]
5 info lifecycle saleor@0.0.0~prebuild-assets: saleor@0.0.0
6 silly lifecycle saleor@0.0.0~prebuild-assets: no script for prebuild-assets, continuing
7 info lifecycle saleor@0.0.0~build-assets: saleor@0.0.0
8 verbose lifecycle saleor@0.0.0~build-assets: unsafe-perm in lifecycle true
9 verbose lifecycle saleor@0.0.0~build-assets: PATH: /usr/share/npm/bin/node-gyp-bin:/home/aorona/workspace/web/garagerot/node_modules/.bin:/home/aorona/.local/share/virtualenvs/garagerot-rwFoTlUE/bin:/home/aorona/workspace/qPy/anaconda3/bin:/home/aorona/workspace/qPy/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle saleor@0.0.0~build-assets: CWD: /home/aorona/workspace/web/garagerot
11 silly lifecycle saleor@0.0.0~build-assets: Args: [ '-c', 'webpack -p --progress' ]
12 silly lifecycle saleor@0.0.0~build-assets: Returned: code: 2  signal: null
13 info lifecycle saleor@0.0.0~build-assets: Failed to exec build-assets script
14 verbose stack Error: saleor@0.0.0 build-assets: `webpack -p --progress`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid saleor@0.0.0
16 verbose cwd /home/aorona/workspace/web/garagerot
17 error Linux 4.13.0-46-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build-assets"
19 error node v6.11.4
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error saleor@0.0.0 build-assets: `webpack -p --progress`
22 error Exit status 2
23 error Failed at the saleor@0.0.0 build-assets script 'webpack -p --progress'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the saleor package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack -p --progress
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs saleor
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls saleor
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Operating system:  Ubuntu 17.10
Python Version: Python 3.6.3 |Anaconda, Inc. using pipenv virtual environment
Browser: Chrome Version 67.0.3396.99
npm - @3.5.2
node - @6.11.4

**Comment by NyanKiyoshi** [comment]
Hi! 

1. You need to make the `saleor` db user a superuser;
2. Could you upgrade nodejs to 8.0 or higher and retry?

**Comment by Pacu2** [comment]
Glad to see this resolved
