### ISSUE TITLE
REST api for all the endpoints

### ISSUE THREAD

**Issue by arangates** [mirumee/saleor#2460]
### What I'm trying to achieve
…
REST api for all the endpoints so that new frontend can be built using some other framework
### Describe a proposed solution
...
Django REST framework
### Other solutions I've tried and won't work
…
tried to use DRF

**Comment by NyanKiyoshi** [comment]
Hi! We currently have a GraphQL API, which was shipped with the latest June release. More information on the [release note](https://medium.com/saleor/june-release-of-saleor-graphql-is-here-bf55cc8b500)!

It should fulfill all your API need. But there is no RESTful API.

Also note that the GraphQL API is still under a lot work and thus is subject to changes and will be way more optimized over the time to come.

**Comment by Pacu2** [comment]
Please reopen if you have any further questions

**Comment by sidhumanjinder** [comment]
how we can integrate saleor and woocommerce using rest api or graphql api?
