### ISSUE TITLE
how to get product_name OrderLine class in orders class

### ISSUE THREAD

**Issue by saqibkhan2523** [mirumee/saleor#2461]
![screenshot from 2018-07-24 09-28-11](https://user-images.githubusercontent.com/41151726/43117222-229eeda8-8f25-11e8-9101-03ab8cfa6d9e.png)

Can anyone tell me where this data is coming from?

**Comment by oldPadavan** [comment]
If I understood You correctly, You might be interested in `templates/order/_ordered_items_table.html`. 
```
{% for line in order %}
  <div class="table__row order-details__product{% if forloop.last %} order-details__last-row{% endif %}">
    <div class="row">
      <div class="col-md-8">
        <a class="link--clean" href="{% if line.variant %}{{ line.variant.get_absolute_url }}{% endif %}">
          <img data-src="{% product_first_image line.variant.product size="60x60" method="crop" %}"
                data-srcset="{% product_first_image line.variant.product size="60x60" method="crop" %} 1x, {% product_first_image line.variant.product size="120x120" method="crop" %} 2x"
                class="float-left lazyload lazypreload"
                src="{% placeholder size=60 %}">
          <span class="order-details__product__description">{{ line.product_name }}</span>
        </a>
      </div>
      <div class="col-md-4">
        <div class="row">
          <div class="col-md-6 col-12">
            <p class="float-right">x {{ line.quantity }}</p>
          </div>
          <div class="col-md-6 col-12">
            <p class="float-right">
              {% price line.get_total display_gross=order.display_gross_prices %}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
```

**Comment by Pacu2** [comment]
@saqibkhan2523 You should expand your `Order` model, then some changes in `forms` might be required, not sure what's your experience with Django, but [Tango with Django](http://www.tangowithdjango.com/) book is usually a great start

**Comment by saqibkhan2523** [comment]
Sorry if i was not clear enough but here is what i am doing:

As you can see in the image above i have created "Downlaod" which contains a link to some file.Every product has its own link when they are created . Now i have updated Product class in models and added a link field. From there i have tried multiple logics to get link of the respective object in that row above but its not working.
If you can tell me how to get that download link linked to orders detail page(what change are required in orders, orderline etc) it will be a great help.

**Comment by Pacu2** [comment]
You should take a look at the following function https://github.com/mirumee/saleor/blob/master/saleor/order/views.py#L27-L48
From what you can see, in the context there's `order` object, then in the file linked by oldPadavan above we are iterating over Order getting OrderLine `{% for line in order %}`
Orderline contains ForgeinKey to the ProductVariant (`variant` field), from ProductVariant contains ForgeinKey to the Product via `product` field.

So for each line you could use something like `{{ line.variant.product.your_custom_url_field }}` for accessing your product link url via templates

**Comment by saqibkhan2523** [comment]
It works, Thanks a lot for this and also for the book.
