### ISSUE TITLE
Try to empty cart after payment instead of after checkout

### ISSUE THREAD

**Issue by ajaypratapyadav** [mirumee/saleor#2462]
### What I'm trying to achieve
1. i'm trying to remove the product on after payment success not on checkout summary can anyone help me to solve this problem
2. When i'm to create another url of cart empty in same file summary.py but it's giving me error that WGSIrequest doesn't have cart

### What I expected to happen
… i need to empty cart after checkout success page

**Comment by Tomasvrba** [comment]
This has also been causing issues on our instance of Saleor so I have made an initial quick fix here: https://github.com/Tomasvrba/saleor/commit/a67884f09537a52c018b5607f865a04e38634bbb
Sorry if it's too late for you @ajaypratapyadav, but feel free to use it. 

@maarcingebala Is this something that you could see merged into Saleor? We have found that the current checkout process is quite confusing for our customers and we are getting a lot of dead orders that never get paid for that users never return to after their cart is emptied (even though they are real orders, with customers' shipping notes etc.)

I am planning to make more updates to my changes such as different handling for authenticated and anonymous users, and having the "Checkout" button in the cart take the user directly back to the payment page if the corresponding order has been found. 

Let me know if you would be interested in any of these modifications and I can open a PR
