### ISSUE TITLE
New address not saved in database

### ISSUE THREAD

**Issue by Kuntal-KK** [mirumee/saleor#2463]
### What I'm trying to achieve
At the time of checkout, when user clicks on Enter a New Address radio button, that form data is not getting saved. Instead in the next page, after clicking Place Order, the old address is showing which user gave at first time order.
…

### Steps to reproduce the problem
1. After a new user logs in, checkout and add address. Place order.
2. Next time when user tries to add new address by clicking the radio button, the data is not getting saved.

### What I expected to happen
…

### Screenshots

**System information**
Operating system: Windows 10
Browser: Google Chrome, FIrefox
![nutri1](https://user-images.githubusercontent.com/34389428/43119055-6bb16658-8f32-11e8-9c0d-8f14254ee2c6.jpg)
![nutri2](https://user-images.githubusercontent.com/34389428/43119060-70138c1c-8f32-11e8-96f4-bc6a11babcf1.jpg)

**Comment by NyanKiyoshi** [comment]
Hi!

Do you mean, that adding the same data as an already existing address in the user's account, is not creating a new one? If so, it's a normal behavior.

Here is what I have done from what I understand from your issue:

1. Checkout in which I enter a new address;
1. Address is created and being showing in the account detail;
1. Checkout in which I enter a new address with the **exact same data as the previous checkout address**;
1. Address is **not being created** and the address count being showing in the account detail remain unchanged.

---

Feel free to reply any more details.

**Comment by Kuntal-KK** [comment]
No, I am providing new address as you can see in the screenshot. Then also I am not able to save it.

**Comment by Kuntal-KK** [comment]
Actually I have added google auto complete feature to that form. So the form gets auto filled after selecting address from suggestion that map api provides. So, do you think it is creating the problem?

**Comment by NyanKiyoshi** [comment]
It's worth a try to disable it and see if that's the issue or not.

**Comment by Kuntal-KK** [comment]
Yes, tried but still same issue is there. Any method to check whether that post method is working or not?

**Comment by NyanKiyoshi** [comment]
This is the part saving it:

https://github.com/mirumee/saleor/blob/06e74acd890ac53e9332aef13a8b47b88e13723c/saleor/account/utils.py#L4-L15

**Comment by Kuntal-KK** [comment]
I cloned Saleor on march, 2018 so I don't have the latest code. The code you have provided is not releavent with my version.

**Comment by NyanKiyoshi** [comment]
Is there a way that you could update to the June release? The bug you are facing was fixed by https://github.com/mirumee/saleor/pull/2201.

**Comment by Kuntal-KK** [comment]
Yes, it is working properly now. Thanks a lot. You have saved lot of time of mine. Thanks.
