### ISSUE TITLE
Integration of paypal

### ISSUE THREAD

**Issue by saqibkhan2523** [mirumee/saleor#2467]
what are the steps of integrating paypal as payment method

**Comment by NyanKiyoshi** [comment]
Hi! 

As of now there you have to edit the payment methods in the `settings.py` file. You can follow the instructions [here](https://django-payments.readthedocs.io/en/latest/modules.html#paypal).

Anyway, here is all the information that should lead you to the full setup of PayPal in Saleor:

First of all, you need to create a REST API app on your PayPal account: [here](https://developer.paypal.com/developer/applications/create)

Once created, you will be able to get the application credentials on this [page](https://developer.paypal.com/developer/applications/) in the `REST API apps` section (by clicking on the name of your newly created app).

Then you will get credentials for the sandbox API (to test and do fake test payments) and the live API (for production use, real payments. Requires you to activate your email address on your account). Also, if you encounter any issue, try to switch to Google Chrome as PayPal support recommends, the developer interface is often bugged.

Then, in `settings.py` you can override (or append on) the example data, which are those lines:

https://github.com/mirumee/saleor/blob/1dc5dd61410af1af44f8bd914ff3fa3dbca27e1a/saleor/settings.py#L341-L342

By your PayPal API information:

```python
PAYMENT_VARIANTS = {
    'paypal': ('payments.paypal.PaypalProvider', {
        'client_id': 'your_client_id',
        'secret': 'your_secret_key',
        'endpoint': 'https://api.sandbox.paypal.com',  # 'https://api.paypal.com' for production use (through the 'live account' API credentials)
        'capture': False})}  # set to True to automatically capture (take) the money when paid, or False to manually capture
```


Once you have done this, you can replace (or append data) on those lines:
https://github.com/mirumee/saleor/blob/1dc5dd61410af1af44f8bd914ff3fa3dbca27e1a/saleor/settings.py#L351-L352

By this:
```python
CHECKOUT_PAYMENT_CHOICES = [
    ('paypal', 'This Is The PayPal Payment Method! (customers see this message!)')]   # The first 'paypal' is telling the framework to look for the 'paypal' keyword in `PAYMENT_VARIANTS`
```

That's it! You should be good to go.

**Comment by saqibkhan2523** [comment]
ok. Thanks a lot for your help

**Comment by dannybombastic** [comment]
is this working on 2019 ?

**Comment by dannybombastic** [comment]
where we need to capture the payments exatly because there is only thre froms DUMMY BRAINTREE AND STRIPE

**Comment by jdmueller** [comment]
I am also looking to integrate payment methods found in django-payments. Paypal, Google Wallet and Authorize.net would be great to have. I was just wondering if anyone has found a work around using Saleor 2.8.0?

**Comment by appleyuchi** [comment]
> I am also looking to integrate payment methods found in django-payments. Paypal, Google Wallet and Authorize.net would be great to have. I was just wondering if anyone has found a work around using Saleor 2.8.0?

Hi I'm also working on this,
could you leave your chatting tool number.
I want to have a discussion with you if possible.

**Comment by jdmueller** [comment]
> > I am also looking to integrate payment methods found in django-payments. Paypal, Google Wallet and Authorize.net would be great to have. I was just wondering if anyone has found a work around using Saleor 2.8.0?
> 
> Hi I'm also working on this,
> could you leave your chatting tool number.
> I want to have a discussion with you if possible.

Whatsapp +593 98 259 3350

**Comment by williamyorkl** [comment]
Hi there, may I know if this still works in 2022? then why there are some issues about the case below ?

https://github.com/saleor/saleor/pull/5577
