### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by luceroster** [mirumee/saleor#2478]
when i proceed to payment then i got error message: "Oops, it looks like we were unable to contact the selected payment service "
…

PAYMENT_VARIANTS = {
'paypal': ('payments.paypal.PaypalProvider', {
'client_id': 'luceroster-facilitator@gmail.com',
'secret': 'secretkey123',
'endpoint': 'https://api.sandbox.paypal.com',
'capture': False})}

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

CHECKOUT_PAYMENT_CHOICES = [
('paypal', 'PaypalProvider')]

…

**Comment by NyanKiyoshi** [comment]
Hi!

Your client ID is wrong. You will find it by clicking on application from the section `REST API apps` on this [page](https://developer.paypal.com/developer/applications/). Also check if you put a valid secret key while you are in there!

**Comment by luceroster** [comment]
Thank you !!! It worked @NyanKiyoshi
