### ISSUE TITLE
Improve dev requirements file

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2485]
We already have `requirements_dev.txt` in the repo, but it lacks most of the tools that we use on a day-to-day basis. We should extend it and encourage using it in our contributing guide. Tools to add:

```
django-extensions
pylint
pylint-celery
pylint-django
pylint-plugin-utils
yapf
coverage
pytest-cov
```

**Comment by patrys** [comment]
Maybe it's time to consider #2430?

**Comment by mmmcorpsvit** [comment]
+ pipenv already support in Pycharm)

**Comment by NyanKiyoshi** [comment]
We are also missing the requirements to build the docs. Not sure if we should add them?

**Comment by maarcingebala** [comment]
I think yes, or at least we should open an issue for that. I won't be able to configure it on `readtthedocs` right now anyway, as I don't have access to the admin panel yet (waiting for Patrys to return from holidays 🌴).

**Comment by NyanKiyoshi** [comment]
@maarcingebala it only requires to install `sphinx` and `sphinx-rtd-theme`, unless I'm missing a feature.
So we could quickly do that.

**Comment by maarcingebala** [comment]
Now I see that I misunderstood your original comment, I was thinking about the docs build which happens on ReadTheDocs. But you're right, we could add those two requirements as well.
