### ISSUE TITLE
Image Mutation Graphql

### ISSUE THREAD

**Issue by git-Pqrd** [mirumee/saleor#2488]
I am new to opensource dev and I want to help and dev new features! 
I would be very interested to be able to upload images through the GraphQL API to automatize my product creation/update stream.

### What I'm trying to achieve
Two mutations one to upload images and the second to change mutate

### Describe a proposed solution
kinda like  -https://github.com/graphql-python/graphene-django/issues/101-
```python
  class UploadFileMutation(graphene.ClientIDMutation):
         class Input:
             pass
             # nothing needed for uploading file
     
         # your return fields

@classmethod
def mutate_and_get_payload(cls, input, context, info):
      files = context.FILES
      print(files)
```

### Feedback 
Open to feedbacks

**Comment by mmmcorpsvit** [comment]
binary data uploaded to server are coded in base64 string + some metadata (real file name for example)

P.S. Warning! All servers have upload data size limitations per request!

**Comment by git-Pqrd** [comment]
I think it would be better if I had the mutation just upload a url to the image and some data then.
Thanks for your comment @mmmcorpsvit

**Comment by maarcingebala** [comment]
We have a mutation to upload product images: `productImageCreate`. It differs a bit from other mutations as it requires a multipart request. It implements the specs described here: 
https://github.com/jaydenseric/graphql-multipart-request-spec

**Comment by maarcingebala** [comment]
Closing for now, please reopen if you have any other questions.
