### ISSUE TITLE
django-prices 1.0.2 has requirement Django<2.1.0

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2509]
django-prices 1.0.2 has requirement Django<2.1.0, but you'll have django 2.1 which is incompatible.

please fix in reqirenements.in
Django>=1.11,<2.1.0

and yet error: 
Pillow==5.0.0 # this version setup normal on Windows, and must be before cairosvg
cairosvg

**Comment by patrys** [comment]
It should be `Django<3`, minor Django releases no longer remove deprecated features.
