### ISSUE TITLE
Where i can get fixture data ?

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2511]
Need fixture data?

where can search? Please share

**Comment by patrys** [comment]
You can run `python manage.py populatedb` to create sample data. Is this what you're asking about?

**Comment by mmmcorpsvit** [comment]
th for help! in my case try find some string "fixture" )
already see: https://saleor.readthedocs.io/en/latest/gettingstarted/example-data.html?highlight=populate

**Comment by Pacu2** [comment]
Glad to see this resolved, please reopen if you have any further questions.
