### ISSUE TITLE
[backend] Default SECRET_KEY

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2514]
this litle fix can do run more simple
`SECRET_KEY = os.environ.get('SECRET_KEY') if not DEBUG else '<< DEFAULT SECRET_KEY  >>'`

dont forget what manag.py too need this key (for exmaple in Pycharm IDE, so need not empty any key!)

**Comment by patrys** [comment]
We don't want to provide a default secret key as people will inevitably forget to set one and will end up using the default key in production which poses a security threat.

**Comment by mmmcorpsvit** [comment]
default key can safe use in DEBUG mode
more danger when DEBUG=true on production

**Comment by mmmcorpsvit** [comment]
also you can do:

1. settings.py
if DEBUG:
    MIDDLEWARE.append(
        'debug_toolbar.middleware.DebugToolbarMiddleware')
    INSTALLED_APPS.append('debug_toolbar')
    INSTALLED_APPS.append('django_extensions') # add this
2. add to requirenemets.txt

django-extensions
Werkzeug

and run project by command line
`manage.py runserver_plus`

Werkzeug - webSGI very quick server, some soft for example Odoo use this for default, try
and Werkzeug have PIN protected panel (we can access to him after enter PIN code)... and can use for 404 pages handle
please see: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=3&cad=rja&uact=8&ved=0ahUKEwiSqYLlodHcAhUEMZoKHTTkBUAQuAIILjAC&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DOPUkm-6sTzU&usg=AOvVaw0ibZMUB7oFOT3NPDsqXUk1

**Comment by patrys** [comment]
If we change the token between restarts then some things will break including sessions, password reset emails, signed cookies and tokens.

**Comment by maarcingebala** [comment]
I agree with @patrys here; we should not set any SECRET_KEY by default. I also don't find it particularly problematic to require setting a single env variable when setting up the project.
