### ISSUE TITLE
Webpack doesn't look into the right folder when STATIC_URL is supplied 

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2515]
It seems like there is an issue with the configuration of webpack. Which is described as below.

Webpack is building under the folder named `assets` (of which the parent is `static`).

The webpack configuration seems to be expecting the user to supply the base static folder to look into. Which, by default is `/static/`. If, the environment variable `STATIC_URL` is not set, the webpack configuration sets the assets path to `/static/assets/`, which appends to the default `/static/`.

Now, if we are supplying the environment variable `STATIC_URL` to webpack, it make sense that the webpack would expect the assets folder to be appended to the base static folder. But webpack doesn't manually appends `assets` to the base path.

As a result, webpack is looking for the assets at the root static folder instead of its generated folder (`assets`).

As of now, the way to prevent conflicts between the `settings.py`, django side, would be to supply a `STATIC_URL` for request serving; and a different `STATIC_URL` including the `assets` folder in the URL on compilation time of webpack (for `webpack-bundle.json` thus). Which can make sense, but would be really confusing for the users.

### Steps to reproduce the problem
1. Set the environment variable `STATIC_URL` to `/static/` and keep it for every command below;
2. Compile the assets **in production mode**;
3. `webpack-bundle.json` should have `publicPath` set to `/static/` instead of `/static/assets/`;
4. Launch Saleor;
5. Make a request on the home page;
6. Saleor will find anything non-related to the webpack bundles (e.g.: placeholder images) but not the assets.

### Proposed solution
As the target folder (`assets`) is hard coded in the config, thus non changeable by the user, I would propose to join `process.env.STATIC_URL` with the folder `assets`.

```patch
Index: webpack.config.js
===================================================================
--- webpack.config.js	(revision 89489fa751617fdb1e60f508ef6eb05931398c5b)
+++ webpack.config.js	(date 1533322641000)
@@ -11,11 +11,13 @@
 var output;
 
 if (process.env.NODE_ENV === 'production') {
+  const baseStaticPath = process.env.STATIC_URL || '/static/';
+  const publicPath = path.join(baseStaticPath, 'assets/');
   output = {
     path: resolve('saleor/static/assets/'),
     filename: '[name].[chunkhash].js',
     chunkFilename: '[name].[chunkhash].js',
-    publicPath: process.env.STATIC_URL || '/static/assets/'
+    publicPath: publicPath
   };
   fileLoaderPath = 'file-loader?name=[name].[hash].[ext]';
   extractCssPlugin = new MiniCssExtractPlugin({

```

**Comment by 2XL** [comment]
```nodejs
$ nodejs
> var path = require('path');
undefined
> path.join('https://google.es/', 'assets/') 
'https:/google.es/assets/'                                         <------ wrong `//` after URI  scheme
> path.join('https://google.es/', '/assets/') 
'https:/google.es/assets/'
> var url = require('url');
undefined
> url.resolve('https://google.es/', 'assets/') 
'https://google.es/assets/'
> url.resolve('https://google.es', 'assets/') 
'https://google.es/assets/'
> url.resolve('/static/', 'assets/') 
'/static/assets/'
> 

```

replace  `path.join` with `url.resolve` ?

**Comment by 2XL** [comment]
https://github.com/mirumee/saleor/blob/master/templates/dashboard/base.html#L57
Raising 400 error
```python        
               ↓
return static('/images/placeholder{size}x{size}.png'.format(size=size))
```
Should be:
```python
return static('images/placeholder{size}x{size}.png'.format(size=size))
```
Same applies for:
https://github.com/mirumee/saleor/blob/master/saleor/core/templatetags/placeholder.py#L9
```html
                          ↓
<svg data-src="{% static "/dashboard/images/account-circle.svg" %}" width="24" height="24" fill="#fff" />
```
Should be:
```html
<svg data-src="{% static "dashboard/images/account-circle.svg" %}" width="24" height="24" fill="#fff" />
```
