### ISSUE TITLE
Question: Product Variant Discounts

### ISSUE THREAD

**Issue by steffenmllr** [mirumee/saleor#252]
Hey there, trying to get my head around discounts. 

I had a look at the sample implementation which discounts on a per Product level. How would you handle a discount per variant, let's say I want to make all green bags minus 10% ?

**Comment by patrys** [comment]
As you can tell, `get_price` is called with whatever parameters you pass. You could create a `Discount` model that has a color field identical to the one in your variants and then pass in a list of all active discounts whenever you determine product price. Your `Variant` model could then traverse the list to determine whether any of the passed discounts were applicable depending on its color.

**Comment by steffenmllr** [comment]
Ah ok I get it. Thanks. One question about the variants: How would go about setting a discount on a per variant level (without color). Every time I try to get the list of all products in the admin I only get the parent product and not the attached variants.

Thanks for your support!

**Comment by patrys** [comment]
You would need to change what the discount object refers to. I am not sure what UI would make the most sense though, for large stores we usually build discounts as models with a name, discount value and a list of affected SKUs.

**Comment by patrys** [comment]
I'm closing this since things seem to work for you :)

**Comment by steffenmllr** [comment]
Yes kind of. Skipped discounts until the rest of shop is done :) Thanks for your help!
