### ISSUE TITLE
On payment, user receives email with localhost URL instead of production URL

### ISSUE THREAD

**Issue by raybesiga** [mirumee/saleor#2521]
### Production server shows localhots URL for cart payments.

I tested my payment process by adding products to a cart and going through the checkout process. However, when I get the email notifying me of the transaction, it shows the localhost URL as in the image below:

![screen shot 2018-07-27 at 19 10 43](https://user-images.githubusercontent.com/405697/43760938-380388a4-9a2c-11e8-88d2-12ad25fadf94.png)

Is there a setting I am missing in Heroku? Thanks in advance.

**Comment by NyanKiyoshi** [comment]
You need to change the site's domain in the dashboard site settings. That should fix it.

**Comment by raybesiga** [comment]
Thanks @NyanKiyoshi you the best!
