### ISSUE TITLE
Additional Cloud Deployment Options

### ISSUE THREAD

**Issue by raybesiga** [mirumee/saleor#2533]
### Is it possible to add guides for deployment on alternative cloud services?

I really like Heroku but I have an issue with how pricey it is to have SSL with a custom domain. Ideally, I would also like to host my Saleor instance on a different cloud provider, say Digital Ocean or Google Cloud Compute. 

### Does anyone have a written guide for alternative cloud deployments?

This is only a request. Thank you.

**Comment by patrys** [comment]
There's a Dockerfile in the repository so you can readily deploy to any Docker-capable cloud (including Google Cloud). You can also follow our deployment docs and Django's standard deployment procedures to get it running on any host, physical or virtual, as long as it's running Linux.

**Comment by raybesiga** [comment]
Hi @patrys so I can deploy to any Docker capable cloud with Linux but I would still have to use AWS for the media files, right? I hope this is not a dumb question.

**Comment by patrys** [comment]
You're not forced to use S3, it's just convenient to do so, especially if you're deploying the Docker container to AWS infrastructure and can utilize features like Elastic Load Balancer and CloudFront. You can however use local media directory (and map it to a volume outside of your Docker container as Docker storage is volatile) or use a different backend from `django-storages`.

We would very much welcome a pull request that adds some of this information to our docs 😉

**Comment by jdivins** [comment]
Hi @raybesiga have you already got a solid deployment, and a documentation of it?
Thank you!

**Comment by jdivins** [comment]
And what about Google Cloud? I have found https://cloud.google.com/python/django/ could be a good start point?

**Comment by raybesiga** [comment]
This is a great option as well but I have not explored it. Do you have any experience with it @jdivins?

**Comment by jdivins** [comment]
Not with saleor. Maybe with the documentation https://cloud.google.com/python/django/ and with the [saleor deployment documentation](https://saleor.readthedocs.io/en/latest/deployment.html) we can achieve it, if anyone hasn't done it yet.

**Comment by raybesiga** [comment]
Do you want to start on it? I am a little busy at the moment but maybe I can join to help down the line @jdivins

**Comment by stephenmoloney** [comment]
I'm currently working of a saleor helm chart. It's still WIP. You can find the work here
https://github.com/stephenmoloney/saleor-helm

I will update the PR #2702 once I've completed the [roadmap](https://github.com/stephenmoloney/saleor-helm/projects/1).

**Comment by jdivins** [comment]
Thank you very much @stephenmoloney !

**Comment by chetabahana** [comment]
On [GCP](https://cloud.google.com/) we can do it on [GAE Flexible Environtment](https://cloud.google.com/appengine/docs/flexible/)

1. Build image with docker and place it [GCR](https://cloud.google.com/container-registry/) (I use [codefresh](https://codefresh.io/) to do that)
2. Create Postgress in [Cloud SQL](https://cloud.google.com/sql/docs/postgres/)
3. Then you may try to deploy like this at your Console:
```
$ git clone https://github.com/mirumee/saleor.git
$ cd saleor
sudo cat <<EOF app.yaml >/dev/null
env: flex
runtime: custom
entrypoint: safe_load(stream)
env_variables:
  SECRET_KEY: [DJANGO_SECRET_KEY]
  ALLOWED_HOSTS: [PROJECT_ID].appspot.com
  DATABASE_URL: 'postgresql://saleor:saleor@172.17.0.1:5432/saleor'
beta_settings:
  cloud_sql_instances: [PROJECT_ID]:[REGION]:[CLOUD_SQL_INSTANCE_NAME]=tcp:5432
EOF
$ gcloud app deploy --image-url=gcr.io/[PROJECT_ID]/saleor:latest --version=v1-1
$ gcloud app instances enable-debug
Akses SSH :~$ sudo docker exec -it gaeapp /bin/bash
root@id:/app# python manage.py migrate
root@id:/app# python manage.py populatedb
root@id:/app# python manage.py createsuperuser
root@id:/app# exit
```

Point your browser to https://[PROJECT_ID].appspot.com

**Comment by chuanman2707** [comment]
> By [GCP](https://cloud.google.com/) we can do it on [GAE Flexible Environtment](https://cloud.google.com/appengine/docs/flexible/) with [_custom runtimes_](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/).
> 
> 1. Build image with docker and place it to [_GCR_](https://cloud.google.com/container-registry/). Name it: `saleor` and tag: `latest`
>    (I use [_Codefresh_](https://g.codefresh.io/signup?ref=ByhLQyoQ4). You can get US$ 500 credits on [Google Free Tier](https://cloud.google.com/free/) there)
> 2. Create [Postgres in Cloud SQL](https://cloud.google.com/sql/docs/postgres/quickstart). Add user/password/database: `saleor`
> 3. Then you may try to [deploy](https://cloud.google.com/appengine/docs/flexible/python/testing-and-deploying-your-app#remote-container-build) at your [_Console Cloudshell_](https://console.cloud.google.com/cloudshell) like this:
> 
> ```
> $ git clone https://github.com/mirumee/saleor.git
> $ cd saleor
> $ sudo cat <<EOF app.yaml >/dev/null
> env: flex
> runtime: custom
> entrypoint: safe_load(stream)
> env_variables:
>   SECRET_KEY: [DJANGO_SECRET_KEY]
>   ALLOWED_HOSTS: [PROJECT_ID].appspot.com
>   DATABASE_URL: 'postgresql://saleor:saleor@172.17.0.1:5432/saleor'
> beta_settings:
>   cloud_sql_instances: [PROJECT_ID]:[REGION]:[CLOUD_SQL_INSTANCE_NAME]=tcp:5432
> EOF
> $ gcloud app deploy --image-url=gcr.io/[PROJECT_ID]/saleor:latest --version=v1
> $ gcloud app instances enable-debug
> Akses app instances by SSH :~$ sudo docker exec -it gaeapp /bin/bash
> root@id:/app# python manage.py migrate
> root@id:/app# python manage.py populatedb
> root@id:/app# python manage.py createsuperuser
> root@id:/app# exit
> ```
> Point your browser to **https://[PROJECT_ID].appspot.com**

Hey,
I'm following exactly what you did, but got a problem with python manage.py migrate step.
```django.db.utils.OperationalError: could not connect to server: Connection timed out
	Is the server running on host "xxxxxxxxxxxx" and accepting
	TCP/IP connections on port 5432?```
Seem like my app engine couldn't connect to cloud SQL.

**Comment by chetabahana** [comment]
> Hey,
> I'm following exactly what you did, but got a problem with python manage.py migrate step.
> 
> ```
> 	Is the server running on host "xxxxxxxxxxxx" and accepting
> 	TCP/IP connections on port 5432?```
> Seem like my app engine couldn't connect to cloud SQL. 
> ```

@chuanman2707
Here are some points to check connection:
- To run Cloud SQL, you need to [Enable Billing](https://console.cloud.google.com/project/_/settings) and [SQL Admin API](https://console.cloud.google.com/flows/enableapi)
- Follow Quickstart to create [PostgreSQL on Cloud SQL](https://cloud.google.com/sql/docs/postgres/quickstart). 
- Make user: `saleor` with password: `saleor` and database: `saleor`
- Check connection
$ gcloud sql connect [INSTANCE_NAME] --user=saleor

- The response should be like this
```
Whitelisting your IP for incoming connection for 5 minutes...done.
Connecting to database with SQL user [saleor].Password for user saleor:
psql (9.6.10)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256, bits: 128, compression: off)
Type "help" for help.
```
- Describe the instance using command below and copy the value of: `connectionName`
`
$ gcloud sql instances describe [INSTANCE_NAME]
`
- Put the value in [beta_settings](https://cloud.google.com/sql/docs/postgres/connect-app-engine#connecting_the_flexible_environment_to) of your `app.yaml`
```
beta_settings:
  cloud_sql_instances: cloud_sql_instances: [PROJECT_ID]:[REGION]:[CLOUD_SQL_INSTANCE_NAME]=tcp:5432=tcp:5432
```

**Comment by chuanman2707** [comment]
@chetabahana thanks mate i think i found my mistake, in DATABASE_URL instead of putting exactly 172.17.0.1 i did put my cloud sql public ip in there.
by the way do you know how to serves static files using google cloud storages bucket ? it would be nice if you have tutorial to do so.

**Comment by chetabahana** [comment]
> @chetabahana thanks mate i think i found my mistake, in DATABASE_URL instead of putting exactly 172.17.0.1 i did put my cloud sql public ip in there.
> by the way do you know how to serves static files using google cloud storages bucket ? it would be nice if you have tutorial to do so.

@chuanman2707
I'm working on it but in the mean time you may follow [PR#2626](https://github.com/mirumee/saleor/pull/2626) which detail can be viewed [_here_](https://github.com/mirumee/saleor/pull/2626/files).

**Comment by acabezasg** [comment]
> By [GCP](https://cloud.google.com/) we can do it on [GAE Flexible Environtment](https://cloud.google.com/appengine/docs/flexible/) with [_custom runtimes_](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/build).
> 
> 1. Build image with docker and place it to [_GCR_](https://cloud.google.com/container-registry/). Name it: `saleor` and tag: `latest`
>    (I use [_Codefresh_](https://g.codefresh.io/signup?ref=ByhLQyoQ4). You can get US$ 500 credits on [Google Free Tier](https://cloud.google.com/free/) there)
> 2. Create [Postgres in Cloud SQL](https://cloud.google.com/sql/docs/postgres/quickstart). Add user/password/database: `saleor`
> 3. Then you may try to [deploy](https://cloud.google.com/appengine/docs/flexible/python/testing-and-deploying-your-app#remote-container-build) at your [_Console Cloudshell_](https://console.cloud.google.com/cloudshell) like this:
> 
> ```
> $ git clone https://github.com/mirumee/saleor.git
> $ cd saleor
> $ sudo cat <<EOF app.yaml >/dev/null
> env: flex
> runtime: custom
> entrypoint: safe_load(stream)
> env_variables:
>   SECRET_KEY: [DJANGO_SECRET_KEY]
>   ALLOWED_HOSTS: [PROJECT_ID].appspot.com
>   DATABASE_URL: 'postgresql://saleor:saleor@172.17.0.1:5432/saleor'
> beta_settings:
>   cloud_sql_instances: [PROJECT_ID]:[REGION]:[CLOUD_SQL_INSTANCE_NAME]=tcp:5432
> EOF
> $ gcloud app deploy --image-url=gcr.io/[PROJECT_ID]/saleor:latest
> $ gcloud app instances enable-debug
> Akses app instances by SSH :~$ sudo docker exec -it gaeapp /bin/bash
> root@id:/app# python manage.py migrate
> root@id:/app# python manage.py populatedb
> root@id:/app# python manage.py createsuperuser
> root@id:/app# exit
> ```
> 
> Point your browser to **https://[PROJECT_ID].appspot.com**


I followed all the steps but I'm stuck in the command: 

$ sudo docker exec -it gaeapp /bin/bash

Error: No such container: gaeapp

Could there be any solution? please

**Comment by chetabahana** [comment]
> @chetabahana
> I followed all the steps but I'm stuck in the command:
> 
> $ sudo docker exec -it gaeapp /bin/bash
> 
> Error: No such container: gaeapp
> 
> Could there be any solution? please

@acabezasg
Follow the [detail step](https://github.com/mirumee/saleor/issues/2533#issuecomment-480592821) 

`
$ sudo docker ps
`
Check the `<Container Name>`, it might be name is not `gaeapp` .

`
$ sudo docker exec -it <Container Name> /bin/bash
`
You could also run it using `<Container ID>` like so:
`
$ sudo docker exec -it ba72d25928cd /bin/bash
`

**Comment by acabezasg** [comment]
> > @chetabahana
> > I followed all the steps but I'm stuck in the command:
> > $ sudo docker exec -it gaeapp /bin/bash
> > Error: No such container: gaeapp
> > Could there be any solution? please
> 
> @acabezasg
> Make sure you run the command by [connecting to the instance](https://cloud.google.com/appengine/docs/flexible/python/debugging-an-instance) via SSH
> [![ssh_console_flex](https://user-images.githubusercontent.com/36441664/57708740-0f926300-7694-11e9-9620-8f2ef725177e.png)](https://cloud.google.com/appengine/docs/flexible/python/debugging-an-instance)
> 
> You may follow the [detail step](https://github.com/mirumee/saleor/issues/2533#issuecomment-480592821) on how to [connect](https://cloud.google.com/appengine/docs/flexible/python/debugging-an-instance) then run this to check the Containers
> 
> `$ sudo docker ps`
> 
> Look at `<NAMES>`, it might be the name is not `gaeapp` .
> `$ sudo docker exec -it <NAMES> /bin/bash`
> 
> You could also run it using `<CONTAINER ID>` like so:
> `$ sudo docker exec -it ba72d25928cd /bin/bash`

@chetabahana 

great! now. that works. Now I have another error :(

admin@saleor ~/urpi-final $ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

**Comment by chetabahana** [comment]
> @chetabahana
> 
> great! that works. Now I have another error :(
> 
> admin@saleor ~/urpi-final $ python manage.py migrate
> Traceback (most recent call last):
> File "manage.py", line 8, in 
> from django.core.management import execute_from_command_line
> ImportError: No module named django.core.management

@acabezasg 
It may be the image, try using mine.. 
`
$ gcloud app deploy --image-url=chetabahana/saleor
`

**Comment by acabezasg** [comment]
> > @chetabahana
> > great! that works. Now I have another error :(
> > admin@saleor ~/urpi-final $ python manage.py migrate
> > Traceback (most recent call last):
> > File "manage.py", line 8, in
> > from django.core.management import execute_from_command_line
> > ImportError: No module named django.core.management
> 
> @acabezasg
> It may be caused by the image, try using [mine](https://hub.docker.com/r/chetabahana/saleor)..
> `$ gcloud app deploy --image-url=chetabahana/saleor`

Hello! Now he says he can not find the command. 


![image](https://user-images.githubusercontent.com/45835413/57809786-e02f3500-772b-11e9-8aed-e11d0006b6d5.png)


sorry for bothering :(

**Comment by acabezasg** [comment]
> > @chetabahana
> > great! that works. Now I have another error :(
> > admin@saleor ~/urpi-final $ python manage.py migrate
> > Traceback (most recent call last):
> > File "manage.py", line 8, in
> > from django.core.management import execute_from_command_line
> > ImportError: No module named django.core.management
> 
> @acabezasg
> It may be caused by the image, try using [mine](https://hub.docker.com/r/chetabahana/saleor)..
> `$ gcloud app deploy --image-url=chetabahana/saleor`


Hello! Now that puts this

![image](https://user-images.githubusercontent.com/45835413/57811117-0f937100-772f-11e9-94d2-00fb91b79e04.png)



sorry for bothering :(

**Comment by chetabahana** [comment]
@acabezasg 
The output shall be similar like this

```
~$ sudo docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                                                  NAMES
ba72d25928cd        gcr.io/chetabahana/saleor                "uwsgi --ini /app/sa…"   5 hours ago         Up 5 hours          8000/tcp, 172.17.0.1:8080->8080/tcp                                    gaeapp
c0fdcc8ecab0        gcr.io/google-appengine/api-proxy        "/proxy"                 5 hours ago         Up 5 hours                                                                                 api
829f7a631c00        gcr.io/google-appengine/nginx-proxy      "/var/lib/nginx/bin/…"   5 hours ago         Up 5 hours          8080/tcp, 0.0.0.0:8443->8443/tcp, 8090/tcp, 0.0.0.0:10402->10402/tcp   nginx_proxy
00b8be4f0ef4        gcr.io/google-appengine/iap-watcher      "./start_iap_watcher…"   5 hours ago         Up 5 hours                                                                                 iap_watcher
b671d1701612        gcr.io/google-appengine/fluentd-logger   "/opt/google-fluentd…"   5 hours ago         Up 5 hours                                                                                 fluentd_logger
```

**Comment by chetabahana** [comment]
> @acabezasg
> The output `$ sudo docker ps` in your terminal was not what is expected.
> 
> When I am looking to your screen, it seems that you haven't [connected to your instance via SSH](https://cloud.google.com/appengine/docs/flexible/python/debugging-an-instance).
> 
> Let's put this way.
> 
> * Click this link:
>   https://console.cloud.google.com/appengine/instances
> * Select the instance then wait the page is reloaded.
> * Go to the bottom of page. Find the SSH button at the far right.
> * Click the button. Wait till SSH is connected.
> * Put the command. It shall be similar like this:
> 
> ```
> chetabahana_gmail_com@aef-product-v1--3-39p9:~$ sudo docker ps
> CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                                                  NAMES
> ba72d25928cd        gcr.io/chetabahana/saleor                "uwsgi --ini /app/sa…"   5 hours ago         Up 5 hours          8000/tcp, 172.17.0.1:8080->8080/tcp                                    gaeapp
> c0fdcc8ecab0        gcr.io/google-appengine/api-proxy        "/proxy"                 5 hours ago         Up 5 hours                                                                                 api
> 829f7a631c00        gcr.io/google-appengine/nginx-proxy      "/var/lib/nginx/bin/…"   5 hours ago         Up 5 hours          8080/tcp, 0.0.0.0:8443->8443/tcp, 8090/tcp, 0.0.0.0:10402->10402/tcp   nginx_proxy
> 00b8be4f0ef4        gcr.io/google-appengine/iap-watcher      "./start_iap_watcher…"   5 hours ago         Up 5 hours                                                                                 iap_watcher
> b671d1701612        gcr.io/google-appengine/fluentd-logger   "/opt/google-fluentd…"   5 hours ago         Up 5 hours                                                                                 fluentd_logger
> ```

**Comment by chetabahana** [comment]
> @acabezasg
> The output `$ sudo docker ps` in your terminal was not what is expected.
> 
> When I am looking to your screen, it seems that you haven't [connected to your instance via SSH](https://cloud.google.com/appengine/docs/flexible/python/debugging-an-instance).
> h
> Let's put this way.
> 
> * Click this link:
>   https://console.cloud.google.com/appengine/instances
> * Select the instance then wait the page is reloaded.
> * Go to the bottom of page. Find the SSH button at the far right.
> * Click the button. Wait till SSH is connected.
> * Put the command. It shall be similar like this:
> 
> ```
> chetabahana_gmail_com@aef-product-v1--3-39p9:~$ sudo docker ps
> CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                                                  NAMES
> ba72d25928cd        gcr.io/chetabahana/saleor                "uwsgi --ini /app/sa…"   5 hours ago         Up 5 hours          8000/tcp, 172.17.0.1:8080->8080/tcp                                    gaeapp
> c0fdcc8ecab0        gcr.io/google-appengine/api-proxy        "/proxy"                 5 hours ago         Up 5 hours                                                                                 api
> 829f7a631c00        gcr.io/google-appengine/nginx-proxy      "/var/lib/nginx/bin/…"   5 hours ago         Up 5 hours          8080/tcp, 0.0.0.0:8443->8443/tcp, 8090/tcp, 0.0.0.0:10402->10402/tcp   nginx_proxy
> 00b8be4f0ef4        gcr.io/google-appengine/iap-watcher      "./start_iap_watcher…"   5 hours ago         Up 5 hours                                                                                 iap_watcher
> b671d1701612        gcr.io/google-appengine/fluentd-logger   "/opt/google-fluentd…"   5 hours ago         Up 5 hours                                                                                 fluentd_logger
> ```

**Comment by acabezasg** [comment]
@chetabahana 
hello again! going forward.

great, now when I put "python manage.py migrate"

I put that error

![image](https://user-images.githubusercontent.com/45835413/57890787-995e3f80-77fe-11e9-934b-e14b8d4b693a.png)

**Comment by chetabahana** [comment]
@acabezasg 
Glad that you have resolve your previous case.
For the new error I think you need to follow another step that I have explained regarding [Postgres Connection](https://github.com/mirumee/saleor/issues/2533#issuecomment-480592821).

-

**Comment by chuanman2707** [comment]
> @acabezasg
> Glad that you have resolve your previous case.
> For the new error please follow another step that I have explained regarding [Database Connection](https://github.com/mirumee/saleor/issues/2533#issuecomment-480592821).

Hey just wondering did you figure out the way to serve static files using cloud bucket ?

**Comment by acabezasg** [comment]
> @acabezasg
> Me alegro de que haya resuelto su caso anterior. 
> Para el nuevo error, siga otro paso que he explicado con respecto a la [conexión de base de datos](https://github.com/mirumee/saleor/issues/2533#issuecomment-480592821) .

@chetabahana agaiin hahaha.


I follow all the steps, but I have an error in the command:

$ psql postgresql://saleor:saleor@172.17.0.1:5432/saleor 

![image](https://user-images.githubusercontent.com/45835413/57931897-31037280-787f-11e9-849f-9162595e9bb0.png)


thank you very much for your help

**Comment by chetabahana** [comment]
> @chetabahana agaiin hahaha.
> 
> I follow all the steps, but I have an error in the command:
> 
> $ psql postgresql://saleor:saleor@172.17.0.1:5432/saleor
> 
> ![image](https://user-images.githubusercontent.com/45835413/57931897-31037280-787f-11e9-849f-9162595e9bb0.png)
> 
> thank you very much for your help

@acabezasg 

Never mind. I am glad to help. 
Please show me your app.yaml file and the respond of this command:

`
<user>@<instance_id>: $ netstat -nlt

`

**Comment by acabezasg** [comment]
> > @chetabahana agaiin hahaha.
> > I follow all the steps, but I have an error in the command:
> > $ psql postgresql://saleor:saleor@172.17.0.1:5432/saleor
> > ![image](https://user-images.githubusercontent.com/45835413/57931897-31037280-787f-11e9-849f-9162595e9bb0.png)
> > thank you very much for your help
> 
> @acabezasg
> 
> Never mind. I am glad to help.
> Please show me your app.yaml file and the respond of this command:
> 
> ```
> ~$ gcloud sql connect [CLOUD_SQL_INSTANCE_NAME] --user=saleor
> ```
> 
> also
> 
> ```
> <user>@<instance_id>: $ netstat -nlt
> ```

@chetabahana 
![image](https://user-images.githubusercontent.com/45835413/57937658-fbb15180-788b-11e9-9370-2785d9d47b13.png)

![image](https://user-images.githubusercontent.com/45835413/57937710-1edc0100-788c-11e9-8eaa-1dfa11a585c1.png)


there is :(

**Comment by acabezasg** [comment]
> > @chetabahana agaiin hahaha.
> > I follow all the steps, but I have an error in the command:
> > $ psql postgresql://saleor:saleor@172.17.0.1:5432/saleor
> > ![image](https://user-images.githubusercontent.com/45835413/57931897-31037280-787f-11e9-849f-9162595e9bb0.png)
> > thank you very much for your help
> 
> @acabezasg
> 
> Never mind. I am glad to help.
> Please show me your app.yaml file and the respond of this command:
> 
> ```
> ~$ gcloud sql connect [CLOUD_SQL_INSTANCE_NAME] --user=saleor
> ```
> 
> also
> 
> ```
> <user>@<instance_id>: $ netstat -nlt
> ```

![image](https://user-images.githubusercontent.com/45835413/57937864-7b3f2080-788c-11e9-83e1-1b6adf4a891f.png)



![image](https://user-images.githubusercontent.com/45835413/57937792-4d59dc00-788c-11e9-9a36-79504ada8126.png)

![image](https://user-images.githubusercontent.com/45835413/57937797-50ed6300-788c-11e9-8e60-e50618356ec4.png)

there is :(

**Comment by chetabahana** [comment]
@chuanman2707 
> Hey just wondering did you figure out the way to serve static files using cloud bucket ?

Yes. I got the way to serve static fiiles using google bucket , just about recently.

- DEBUG will be set to False so it run in production. 
- Static files (templates/webpack) will remain using django static
- Media files  (images) will be made by celery to google storage and serve from there. 

I am preparing to send a pull request , hope it will pass the test..

**Comment by chetabahana** [comment]
> @chetabahana
> ![image](https://user-images.githubusercontent.com/45835413/57937864-7b3f2080-788c-11e9-83e1-1b6adf4a891f.png)
> 
> ![image](https://user-images.githubusercontent.com/45835413/57937792-4d59dc00-788c-11e9-9a36-79504ada8126.png)
> 
> ![image](https://user-images.githubusercontent.com/45835413/57937797-50ed6300-788c-11e9-8e60-e50618356ec4.png)
> 
> there is :(

@acabezasg 
Everything are in order. It should be connected actually. Let me think what the problem is.

**Comment by acabezasg** [comment]
> us-centrall


there is like us-central1

**Comment by acabezasg** [comment]
@chetabahana Unfortunately I could not solve the problem :(

**Comment by chetabahana** [comment]
@acabezasg 
I have been thinking it is blocked by Firewall Rules.
Try to expose IP Address on Cloud SQL Server.

**Comment by acabezasg** [comment]
@chetabahana 
a question. I have to put that command in the SSH?


![image](https://user-images.githubusercontent.com/45835413/57985984-bed48e80-7a34-11e9-8eed-c8f4bc3d3b3c.png)

**Comment by chetabahana** [comment]
> @chetabahana
> a question. I have to put that command in the SSH?
> 
> ![image](https://user-images.githubusercontent.com/45835413/57985984-bed48e80-7a34-11e9-8eed-c8f4bc3d3b3c.png)

@acabezasg 
 Yes. Akses app instances by SSH :l
```
~$ sudo docker exec -it gaeapp /bin/bash
root@id: cd /app
root@id:/app# psql "sslmode=disable dbname=saleor user=saleor hostaddr=[INSTANCE_IP]"
```

**Comment by acabezasg** [comment]
@chetabahana 

and if I get the answer '-bash: psql: command not found'?

in the path / usr / lib / is not: / postgressql

![image](https://user-images.githubusercontent.com/45835413/58055314-fde10d80-7b22-11e9-9871-dfcf36f84b60.png)

**Comment by chetabahana** [comment]
Actualy `psql` is not a must. It is used only to test the connection. 
In your path there is `google-cloud-sdk`, means you could use [gcloud](url)

**Comment by acabezasg** [comment]
@chetabahana  
finally after all these days I was able to do the deploy hahaha. really thank you very much, you are the best

**Comment by chetabahana** [comment]
> @chetabahana
> finally after all these days I was able to do the deploy hahaha. really thank you very much, you are the best

@acabezasg 
Really nice to hear that, I was also face the same when begin to learn Google Cloud. You can go forward now to explore more on GCP such as [Google Bucket](https://github.com/mirumee/saleor/issues/2533#issuecomment-493491117), [Docker Compose with Celery](https://github.com/chetabahana/saleor/blob/0343e1f0a19ba2196765e9f24291c9913fdf51ef/docker-compose.yml#L37) on Google Compute, or even play with Google Kubernetes.

**Comment by acabezasg** [comment]
@chetabahana 
Hello again! a question. if I want to put two or more allowed hosts, where do I put them?

**Comment by chetabahana** [comment]
> @chetabahana
> Hello again! a question. if I want to put two or more allowed hosts, where do I put them?

@acabezasg 
You can put them separated by comma as below:
```
ALLOWED_HOSTS: .appspot.com, .example.com
```
Morover if you put dot in font of a domain luke abive then it will aloows all subdomains under that domain

**Comment by acabezasg** [comment]
@chetabahana 
One last thing, how do I redirect the domain to https? already has ssl but I can not get it to redirect from http to https

**Comment by chetabahana** [comment]
> @chetabahana
> One last thing, how do I redirect the domain to https? already has ssl but I can not get it to redirect from http to https

@acabezasg 
Actually Google will maintain an automatic extend of ssl for your domain as long you use the cloud services so you don't need to get one. You just need to verify the domain
in and _[add it](https://cloud.google.com/appengine/docs/standard/python/mapping-custom-domains#adding_a_custom_domain_for_your_application)_ in to the [AppEngine.s domain page](https://console.cloud.google.com/appengine/settings/domains/add).

**Comment by acabezasg** [comment]
@chetabahana 
![image](https://user-images.githubusercontent.com/45835413/58425520-99acd500-805f-11e9-9bc5-db361a96b834.png)

I already did it but it does not redirect to https

**Comment by chetabahana** [comment]
@acabezasg 
Try to add ["secure: always"](https://cloud.google.com/appengine/docs/python/config/appconfig?hl=en#Python_app_yaml_Secure_URLs) to your yaml file
```
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
```

**Comment by acabezasg** [comment]
@chetabahana hi! 
that worked, but then caused a loop on the web, will it be because I did it in both ways? by google cloud domains and by the domain panel of app engine?

**Comment by chetabahana** [comment]
@acabezasg 

I think in your case the `secure always` is the right option. I have read  somewhere that redirect setting by fiil in `A` and `AAAA` in dns panel is deprecated in vapor of G Suite.

**Comment by Gugure** [comment]
Do you guys know how to add the saleor storefront (PWA) through google cloud?

**Comment by simon-online** [comment]
I'm looking at hosting the Saleor v3 backend on Google App Engine. I assume the approach below would still work.

How would you go about hosting the Celery worker?
Set up a separate Celery worker app on GAE?
Or convert it to use Google Cloud Tasks?

> By [GCP](https://cloud.google.com/) we can do it on [GAE Flexible Environtment](https://cloud.google.com/appengine/docs/flexible/) with [_custom runtimes_](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/build).
> 
> 1. Build image with docker and place it to [_GCR_](https://cloud.google.com/container-registry/). Name it: `saleor` and tag: `latest`
>    (I use [_Codefresh_](https://g.codefresh.io/signup?ref=ByhLQyoQ4). You can get US$ 500 credits on [Google Free Tier](https://cloud.google.com/free/) there)
> 2. Create [Postgres in Cloud SQL](https://cloud.google.com/sql/docs/postgres/quickstart). Add user/password/database: `saleor`
> 3. Then you may try to [deploy](https://cloud.google.com/appengine/docs/flexible/python/testing-and-deploying-your-app#remote-container-build) at your [_Console Cloudshell_](https://console.cloud.google.com/cloudshell) like this:
> 
> ```
> $ git clone https://github.com/mirumee/saleor.git
> $ cd saleor
> $ sudo cat <<EOF app.yaml >/dev/null
> env: flex
> runtime: custom
> entrypoint: safe_load(stream)
> env_variables:
>   SECRET_KEY: [DJANGO_SECRET_KEY]
>   ALLOWED_HOSTS: [PROJECT_ID].appspot.com
>   DATABASE_URL: 'postgresql://saleor:saleor@172.17.0.1:5432/saleor'
> beta_settings:
>   cloud_sql_instances: [PROJECT_ID]:[REGION]:[CLOUD_SQL_INSTANCE_NAME]=tcp:5432
> EOF
> $ gcloud app deploy --image-url=gcr.io/[PROJECT_ID]/saleor:latest
> $ gcloud app instances enable-debug
> ```
> 
> Akses app instances by SSH : ![ssh_console_flex](https://user-images.githubusercontent.com/36441664/57710324-ea532400-7696-11e9-867a-abee9777458c.png)
> 
> Then run:
> 
> ```
> ~$ sudo docker exec -it gaeapp /bin/bash
> root@id:/app# python manage.py migrate
> root@id:/app# python manage.py populatedb
> root@id:/app# python manage.py createsuperuser
> root@id:/app# exit
> ```
> 
> Point your browser to **https://[PROJECT_ID].appspot.com**
> 
> In case any problem please see the step on [database connection](https://github.com/mirumee/saleor/issues/2533#issuecomment-480592821) or [docker containers](https://github.com/mirumee/saleor/issues/2533#issuecomment-492978361) for more details.
