### ISSUE TITLE
Docker-compose should not use UWSGI

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2537]
### What I'm trying to achieve
Not to run UWSGI inside docker-compose.

### Steps to reproduce the problem
1. `docker-compose up` 

### What I expected to happen
Run `python manage.py runserver`

**Comment by mmmcorpsvit** [comment]
#2499

**Comment by carstenblt** [comment]
The real problem for developing with container right now is that all the data is copied to a volume. So either you need to edit files in that volume or you need to rebuild the container every time you edit files... For development purposes you should just bind the directory directly.

https://docs.docker.com/storage/bind-mounts/#start-a-container-with-a-bind-mount

**Comment by carstenblt** [comment]
@patrys Yup, c7f380a

**Comment by patrys** [comment]
@carstenblt Care to open a separate bug for that?

**Comment by maarcingebala** [comment]
Fixed by #2714
