### ISSUE TITLE
Replace regular tables with DataTables

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#255]
https://www.datatables.net/

**Comment by patrys** [comment]
There are several bindings available for Django. This should replace the current dashboard lists for products and orders.

**Comment by paweltin** [comment]
What do we gain by using these?

**Comment by patrys** [comment]
Umm, a UI for filtering, sorting and pagination I guess?

**Comment by 3ka5-cat** [comment]
What do you think about [Django-Tables2](https://github.com/bradleyayers/django-tables2) ?

**Comment by patrys** [comment]
It does not seem to offer the same feature set as DataTables?

**Comment by elwoodxblues** [comment]
We're not planning to use this solution anymore.
