### ISSUE TITLE
Deployment on Amazon EC2 and Apache

### ISSUE THREAD

**Issue by saqibkhan2523** [mirumee/saleor#2554]
I have been trying to deploy it. I am using EC2 and also I have bought a domainalso installed mod-wsgi. I have setup my virtual env. folder inside. Something like this:
example.com
--test
----testenv
----saleor

I have a separate .conf file for this domain and I tried some guides on interent but I seems to be making some mistake that dont know. I can access saleor on `0.0.0.0:8000` when I run `python3 manage.py runserver 0.0.0.0:8000`. Can anyone provide step-wise process to make it live? Thanks

**Comment by neerajgupta2407** [comment]
@saqibkhan2523 Did you figure out how it works on apache.
