### ISSUE TITLE
Allow easy searching and filtering of tables

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#256]
Spree has this one figured out pretty well

![Zrzut ekranu z 2015-05-07 13-59-58.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Zrzut%20ekranu%20z%202015-05-07%2013-59-58-22c68f03f29df618bbfa0cf1a6c2831feb7b64e6668eebd5bec17345b3648a04.png)

**Comment by elwoodxblues** [comment]
As we discussed we're going to add filtering capabilities to our list/table views in the dashboard. For the backend, we can use the `django-filters`. The more detailed description of what should be included:
- [ ] sorting the list by clicking on the column names
- [ ] filters corresponding with the displayed columns
- [ ] UI should be compliant with Material Design. [These](https://material.io/guidelines/components/data-tables.html#data-tables-tables-within-cards) designs include filter icon in the table header. We could use similar solution to reveal the filters, however, I'm not sure how they should be presented exactly (maybe we'll need to design this first)
