### ISSUE TITLE
Search existing customer using phone number in connect an order with an account dialog

### ISSUE THREAD

**Issue by Vinit-Koshti** [mirumee/saleor#2561]
### What I'm trying to achieve
I want to attach an order to the existing customer,  where existing users are searchable using phone number. As of now I can search only using E-mail Address.

CHECKBOX: Set billing and shipping address in order to customer details, should work in similar way with phone number as it is working for E-mail.

### Describe a proposed solution
Is there a way where I could simply replace or duplicate the E-Mail validation with a Customer's Phone Number which is similarly searchable like an E-Mail address!

### Screenshots or mockups

![screenshot from 2018-08-14 15-36-40](https://user-images.githubusercontent.com/16951071/44085700-f006c848-9fd7-11e8-98e7-f4afa9929210.png)

**Comment by maarcingebala** [comment]
The function responsible for searching users is [ajax_users_list](https://github.com/mirumee/saleor/blob/master/saleor/dashboard/customer/views.py#L88). There is a queryset of users that we filter using provided `search_query`. Filtering by phone number would require adding the following query:
```
Q(addresses__phone__icontains=search_query)
```
The above would search the phone number in all user's addresses.

**Comment by Vinit-Koshti** [comment]
Hey thank you for that, but one little help,
In the drop down its still showing E-mail, how can i get phone numbers there.

![screenshot from 2018-08-14 18-51-05](https://user-images.githubusercontent.com/16951071/44094569-25429a7a-9ff4-11e8-8073-33207906dafe.png)

**Comment by NyanKiyoshi** [comment]
@Vinit-Koshti 

To customize the line, you need to edit `get_ajax_label` of the model Account:

https://github.com/mirumee/saleor/blob/232a743bc63f5dcc4455bb025bd66733eb218670/saleor/dashboard/customer/views.py#L97-L99

https://github.com/mirumee/saleor/blob/232a743bc63f5dcc4455bb025bd66733eb218670/saleor/account/models.py#L148-L153

**Comment by Vinit-Koshti** [comment]
https://github.com/mirumee/saleor/blob/232a743bc63f5dcc4455bb025bd66733eb218670/saleor/account/models.py#L110
In models.py I have added the phone field.
`phone = PossiblePhoneNumberField(unique=True, blank=True, default='')`

https://github.com/mirumee/saleor/blob/232a743bc63f5dcc4455bb025bd66733eb218670/saleor/dashboard/customer/views.py#L88
My Edited Code: I have added below query in ajax_users_list 
`Q(phone__icontains=search_query)`


After above changes, I got the below results. but I want phone number in the drop down.
![screenshot from 2018-08-14 18-51-05](https://user-images.githubusercontent.com/16951071/44133797-4cb81978-a07f-11e8-832f-f7251871d9d7.png)


now I am trying to return `self.phone` from below in line 153, but getting nothing in the ajax drop down.
https://github.com/mirumee/saleor/blob/232a743bc63f5dcc4455bb025bd66733eb218670/saleor/account/models.py#L148-L153
