### ISSUE TITLE
VariantImageAssign mutation can assign one image multiple times

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2563]
### What I'm trying to achieve
To assign an image to a product variant.

### Steps to reproduce the problem
Execute the following mutation multiple times:
```language=graphql
mutation {
  variantImageAssign(variantId:"", imageId: "") {
    image {
      id
    }
  }
}
```

### What I expected to happen
To return an error, or at least do nothing.

**Comment by patrys** [comment]
Didn't we agree that "image" would become a foreign key of a variant (ie. the image to which the carousel should scroll when selecting that variant)?

**Comment by maarcingebala** [comment]
I don't remember any discussion about it. Right now the model allows you to assign more than one variant image and I didn't change that when implementing the mutations.

**Comment by patrys** [comment]
@apsummers I've discussed it some time ago with @dominik-zeglen and one other person, I though that was you.

**Comment by maarcingebala** [comment]
So, to sum things up, do we agree that we should instead change the relationship between ProductVariant and ProductImage to allow setting only one variant image? I'd open a separate issue for that then.

**Comment by maarcingebala** [comment]
Sorry, closed accidentally.

**Comment by patrys** [comment]
To elaborate, my proposal was to:

1. Always show all product images, no matter which variant is selected.
2. Give each variant a foreign key to one of the product's images.
3. When a variant is selected, switch the image carousel to its associated image (eg. to present the red color option if a red variant is selected)
