### ISSUE TITLE
Mockups for model translations interface

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2564]
We need mockups for the model translations views. I'm not sure how other platforms approach this problem, but here is the scenario that seems to me most reasonable:

1. Go to a "model translations" section in the dashboard.
2. Select a language to edit.
3. Display a list of all translatable strings in a more or less this form:
    Context - Field name - Original value - Input
e.g.
    Product - description - "Description in the original language." - "Description in a different language."

The biggest advantage of this approach is that we have all translations in one place and can easily give access to this section only to translators with proper permissions.

Any ideas are welcomed. Also, let me know if there are better approaches to this problem.

**Comment by patrys** [comment]
I think having dedicated UI for different models would work better. For example I imagine na interface where you see the original product name and description on the left and inputs for translated ones on the right. Otherwise it's not only hard to consistently translate strings for the same product instance but we also can't make any of the fields required.

**Comment by Pacu2** [comment]
From things that could be considered:
- Displaying language coverage for each language
- I think it would be more convenient to divide to-be-translated strings by model (eg. Product, ProductVariant...) (maybe as subpages?)
- Indicator if a translation is up to date (eg. we could invalidate it after parent model changed)
- Ability to search for translated/not translated string
- Ability to import/export the translations
- Ability to easily jump between models to be translated (with arrow keys? just "next string" button?)
- Ability to filter for translated/not translated properties

**Comment by Pacu2** [comment]
@pwgryglak could we get back to this please?

cc @diramazioni

**Comment by diramazioni** [comment]
I was thinking something very simple and intuitive like
![image](https://user-images.githubusercontent.com/682046/49383483-24e48800-f719-11e8-8cc6-5f310a7aa702.png)
![image](https://user-images.githubusercontent.com/682046/49386393-bfe06080-f71f-11e8-85a0-29b7fcfb6121.png)

**Comment by maarcingebala** [comment]
Mockups are available on Figma.
