### ISSUE TITLE
Populatedb script creates out-of-stock variants

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2572]
[In this line](https://github.com/mirumee/saleor/blob/master/saleor/core/utils/random_data.py#L305) we generate random `quantity_allocated` which may result in an impractical state of having out-of-stock variants without corresponding orders. This should be dropped in my opinion.
On the other hand in `create_order_line` function we create fake orders and allocate appropriate quantity which is totally fine as it corresponds with a real-life case.

**Comment by maarcingebala** [comment]
Hey, we could entirely remove generating value for `quantity_allocated` field in the `create_variant` function. I don't think that this is particularly useful to anyone.

**Comment by MartinSeibert** [comment]
Okay. I'm gonna do that and put a pull request in.

**Comment by MartinSeibert** [comment]
I put the pull request in... I hope I did it right. I had a fork made and added the master as an upstream so that I could get my fork back up to the master... and then when I pushed to my branch it also pushed it to the original master.

**Comment by patrys** [comment]
I think a better solutions would be one that increases both quantity in stock _and_ quantity allocated by the total number used by orders. Otherwise stock numbers won't behave properly when fulfillment happens.
