### ISSUE TITLE
Implement filtering interface

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2588]
We should be able to filter objects given certain parameters.

**Comment by maarcingebala** [comment]
Before we move on with implementing proper filtering in Dashboard 2.0, we need to figure out how the implementation should look like in the backend. First I'd like to analyze few other GraphQL APIs and propose a design of universal filtering interface in our API. 

Requirements:
- ideally filtering should be enclosed within a single object, similarly to how we handle sorting in `products` query:

```
type ProductOrder {
  field: ProductOrderField!
  direction: OrderDirection!
}
```

- it should be relatively easy to reuse the code that handles filtering between different queries/resolvers, so we can use the same patterns across the API

Some examples that I found:

- Github v4 API - filtering issues: `issues(filterBy: {states: OPEN, assignee: ""})` - seems very simple but I think the pattern it's not really re-used across different queries
- Strapi - [see the "Filters" section in the documentation](https://strapi.io/documentation/3.x.x/guides/graphql.html#configurations) - seems like quite powerful filtering capabilities which may be a good idea in an open API
- [GraphCMS](https://docs.graphcms.com/developers/api#filtering-entries)

We need to do some research and decide what shape of filtering API we need and can implement. Maybe we'll have to take a look at built-in support for `django-filters` in Graphene.
