### ISSUE TITLE
Support Wombat

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#259]
https://wombat.co/ is what gives Spree most of its features. They offer an API we can implement. Unfortunately they don't offer any form of sandbox accounts so our only chance is using the two weeks provided by free trial.

**Comment by auvipy** [comment]
I will be happy to create the API module using django-rest-framework

**Comment by patrys** [comment]
See the pull request #369 as it already does parts of what is needed here.

**Comment by patrys** [comment]
Wombat is no more.
