### ISSUE TITLE
Should product types contain attributes?

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2596]
At this moment attributes and product types are the separate views which is confusing to new users. Maybe we should embed attributes in product type view?

**Comment by patrys** [comment]
@maarcingebala @pwgryglak Let's discuss.

**Comment by pwgryglak** [comment]
We had a discussion with Marcin and we think we have a solution - Let's meet tomorrow and discuss it.

**Comment by pwgryglak** [comment]
Like we discussed I've prepared project in Figma - it's ready to review
