### ISSUE TITLE
[Database], slow requests

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2605]
Find slow requests:

1. http://127.0.0.1/en/account/
SELECT * FROM "order_order" WHERE ("order_order"."user_id" = 122 AND NOT ("order_order"."status" = 'draft'))
- using string compare are slow, need refactor to digits with index

2. http://127.0.0.1/en/cart/
SELECT * FROM "shipping_shippingmethodcountry" WHERE "shipping_shippingmethodcountry"."country_code" = 'US' LIMIT 1
- too
3. every page call 
SELECT "menu_menu"."id", "menu_menu"."name", "menu_menu"."json_content" FROM "menu_menu" WHERE "menu_menu"."id" = 1
SELECT "menu_menu"."id", "menu_menu"."name", "menu_menu"."json_content" FROM "menu_menu" WHERE "menu_menu"."id" = 2
.
.
- maybe have possible merge to one sql?
4. site_authorizationkey
- in first i see keys for auth stored in database, very strange solution....
social auth have variables in settings for this, please see: https://python-social-auth.readthedocs.io/en/latest/backends/google.html

**Comment by patrys** [comment]
Ad 4: we don't want to force users to restart the server just so they can enable social auth.

**Comment by mmmcorpsvit** [comment]
5. checkout, like: http://localhost:8000/en/order/74dc5dce-9830-46f2-8dab-03d951533ae4/payment/
SELECT ••• FROM "order_order" INNER JOIN "account_address" ON ("order_order"."billing_address_id" = "account_address"."id") LEFT OUTER JOIN "account_user" ON ("order_order"."user_id" = "account_user"."id") LEFT OUTER JOIN "account_address" T4 ON ("order_order"."shipping_address_id" = T4."id") WHERE (NOT ("order_order"."status" = 'draft') AND "order_order"."billing_address_id" IS NOT NULL AND "order_order"."token" = '74dc5dce-9830-46f2-8dab-03d951533ae4')
- str compare very slow, need use digits (if possible)+ indexing

6. too page
SELECT  ••• FROM "order_payment" WHERE ("order_payment"."order_id" = 25 AND "order_payment"."status" = 'waiting') 
SELECT ••• FROM "order_payment" WHERE ("order_payment"."order_id" = 25 AND "order_payment"."status" = 'preauth')
SELECT ••• FROM "order_payment" WHERE ("order_payment"."order_id" = 25 AND "order_payment"."status" = 'confirmed') ORDER BY "order_payment"."id" DESC

- similar queries must be merge

**Comment by maarcingebala** [comment]
Recently we've made a few improvements to the database performance, I guess it should be much better now. Soon we'll also introduce tests that check the number of queries.
