### ISSUE TITLE
Please append "Internal" check-box for Product type

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2606]
This feature need for internal products.

For example: 
we sell phones (this is normal product) and sell some service with this product, for example setup Skype
but in normal way user cannot buy "setup Skype" only how subproduct
too this can use for another features for example for delivery: we sell phone + internal product "delivery" or any product-like item (sell product, sell service, delivery, employee salaries, buy hosting for site etc... etc...).
and please add feature for assign product to another products, this can in feature use for bandles

so Internal product - this is casual product but not show on site Categories and cannot find from search line. Very need and important part of any real shop.

P.S. very powerfull solution for e-comerce is Odoo (but bad frontend), please rewiev on weekend if can (have simple setup from Docker)

**Comment by Pacu2** [comment]
I'm afraid product bundles are not currently on our roadmap

**Comment by maarcingebala** [comment]
As @Pacu2, we won't implement such feature in the nearest time. This is a specific use case and it should be fairly easy to customize Saleor on your side to support that. Of course, we can offer guidance about implementation details if you have some particular problems or questions. Please reopen the issue if you do.
