### ISSUE TITLE
[backend, frontend] Add product code to search and product page

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2607]
Very important feature of any product for search and for buy (for example to approve by phone) very need product code (can be just product.id).

When have very big database of products append product from dashboard will be slow, speedest way - use code for all parts where need add product.

**Comment by Pacu2** [comment]
There's no such product code at this moment, the only thing we have is SKU for ProductVariant.
I think that product's id is more of the database-thing and should not be used directly in the storefront.

**Comment by mmmcorpsvit** [comment]
SKU - need for staff, for internal works, for storage works, this is not same, because this is internal data
Product code - need for frontend, for example when need by phone agree buy - this is can be **product.id-productvariant.id**, and for this feature need search by code at maximum speed

please rewiew

**Comment by Pacu2** [comment]
I still think that you should use an SKU(stock keeping unit) or EAN(International Article Number) for the product, as ID is purely database thing and will change if you, for example, delete a product and add it once again.

**Comment by mmmcorpsvit** [comment]
if i delete product - i too must delete all asigned orders etc.

if delete product when not have any assigned data - this is not have any problems

id - good because:
1. maximum search speed
2. simple autogenerated by database
3. short and usable format code, example: product code 0001-01

**SKU present only in variants, not in products!**

**Comment by Pacu2** [comment]
Deleting a product won't affect your orders and order lines, they will be preserved to maintain your financial and historical data. 
Relevant product fields (eg. prices, product name, product SKU) are saved as text fields on OrderLines.

As far as I know, we are not planning to introduce id-based product codes for the storefront.

**Comment by mmmcorpsvit** [comment]
ok, but why product model don't have SKU, variant have ? Can explain please.
SKU must be unique, ok, but if i don't need fill this field, just don't use it, in this case need feature for auto-generate in back-end and front-end this value. You agree?

P.S. just maybe help, i investigate some time ago how architect variants feature and was:
1. one product table, + field group of products (after product create - auto-create group and assign product to group). In this case in one group can be any type products, all products independent.
2. one product table + field assign to parent product. Classic binary tree, independent type of product, multi-deep product tree
3. any type, but for search use search engine of elasticsearch features. For example: request main page, load empty search line. Request cat1 search - load this cat1, etc.

oh... my "English"(

**Comment by patrys** [comment]
@mmmcorpsvit It does not make sense for products to have an SKU. If you have a blue and a green color version of the same product, your warehouse needs to track them separately. Similarly your customers need to order either the green one or the blue one. SKU codes (most often a GTIN is used as SKU) are commonly in use for this purpose as they are the same codes that appear as barcodes on labels.

**Comment by mmmcorpsvit** [comment]
for example: in Ukraine all items must have unique code for documents

1. just think (from real live): we have big physical storage with 100k+ items, and delivery say: "we need 10 shirts, 10 blue shirts etc...." this will be hell))))
much more speed when primary compare items to code, storage separate by digits (from-to) and this easy system to simply find what need
2. another sense: have much similar items and some grandfather buy some items (like how me, with terrible English verbal skill) and by phone can mistake with detect, what say man. Very good solution: when man can speak digital code of product (from real live, know basic language how digits are primary).
3. another way: call my to cell phone and try buy product named **"ولد جميع الناس أحرارًا متساوين في الكرامة الحقوق. وقد"**, or like **"大汉和字典"** (in this case all (customer, staff, support, delivery, storage workers etc..) must know language, but its impossible).

**Comment by mmmcorpsvit** [comment]
from real live: have few suppliers: Adidas, puma, reabok
and have same name product: "super puper shirt", all public all, and what i must do when customer call and say "i wont buy 5 super puper shirts"? In this case i need ask about brand... this bad because not standartized. If i change name of product this can degree SEO, this can be problem with suppliers...

so in all cases: one and right way solution: use unique in database product code

**Comment by patrys** [comment]
@mmmcorpsvit That's where you normally use SKU (GTIN/ISBN/EAN).

**Comment by mmmcorpsvit** [comment]
how, if products don't have SKU, only variants have

**Comment by NyanKiyoshi** [comment]
Can you check you have this field?

![screenshot](https://i.imgur.com/FncR7pW.png)

A product without variant still has an auto-created single variant, which contains the product SKU.

**Comment by mmmcorpsvit** [comment]
wow...
now understand, little bad because SKU not auto-generated by default for minimize enter product item time
