### ISSUE TITLE
One can see someone else's payment page

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2609]
### What I'm trying to achieve
Paymant process dont assign to authorized customer

### Steps to reproduce the problem
1. login
2. do some buy
3. cheout to when you URL will like: http://127.0.0.1/en/order/d24f8259-6d0d-438c-8644-58ad7d03bc6e/payment/ and copy this **link**
4. open this **link** in another browser and we see what page not ptotected!

### What I expected to happen
Page 404 or login form (need investigate)

### Screenshots
![45d3c5e1e3 1](https://user-images.githubusercontent.com/9638835/44227252-d37cb100-a19a-11e8-9273-a6a4e1042bbd.jpg)

**Comment by NyanKiyoshi** [comment]
It was voluntary, some websites allows those behaviors to allow an order to be paid from another device or user through a link. 

But I think that the question is that if we want to hide or not the order lines. And if we want to put a settings to toggle the behavior that may be unwanted (like it probably is in your case).

**Comment by mmmcorpsvit** [comment]
agree, need setting (defaut must be check) for this important feature

**Comment by mmmcorpsvit** [comment]
idea:
we can generate PIN secure key on page, when we wont give for another user session way for payment, in any way i think this info must be closed

**Comment by patrys** [comment]
As you can see the checkout page:

1. has a unique URL that is not guessable
2. does not contain any address information unless it's your order

The worst that you could do is pay for someone else's order in which case you are only doing yourself a disservice. This is not a security issue and seems to work as intended.

**Comment by mmmcorpsvit** [comment]
check page like: http://127.0.0.1/en/order/d24f8259-6d0d-438c-8644-58ad7d03bc6e/
possible add Note for not authorized user - this is normal?)

please add settings.variable for open/closed this data options

**Comment by Pacu2** [comment]
@mmmcorpsvit In terms of payments and note-adding, I think that's the desired behavior, as the only way to get one to this page is by sharing the link with someone else.  

Saleor is made as a forkable storefront, so one can copy it and adjust to its business needs, that's the idea we've got in mind, as one size does not fit all, we have to compromise and create a universal solution, that would be a solid ground for your customizations.
