### ISSUE TITLE
[Templates] Logo URL is broken in mail body when remove account

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2614]
### What I'm trying to achieve
Logo broken in mail body when remove account

### Steps to reproduce the problem
1. login
2. enter to account page
3. click "remove account"
4. see broken logo url, must be like http://localhost/static/images/logo-document.svg , but got http://127.0.0.1/en/products/mccarthy-llc-2/%3C%3C%20MISSING%20VARIABLE%20%22protocol%22%20%3E%3E://localhost:80/static/images/logo-document.svg . In another mail (in my case order details logo show normal).

### Screenshots
![7b790d456a 1](https://user-images.githubusercontent.com/9638835/44259041-15e4d300-a219-11e8-9db1-3ae989b05c52.jpg)

To read mail use: https://github.com/mirumee/saleor/issues/2610

**Comment by Pacu2** [comment]
@tomcio1205 Thanks, go for it!
