### ISSUE TITLE
[Extension] Immediately buy product without cart

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2631]
### What I'm trying to achieve
Cases:
single goods (cart don't need)
special goods (pay entrance, premium access) for continue buy - (my case, we sell entrance pay for some product, use random.org for select winner who can buy product with very low price)
landing page with few products, where need shortest way to sell product

### Describe a proposed solution
Add field "single" to product_variant.single = BooleanField(default=False, ....)
when True, and press "Buy" user must be redirect to checkout (in this cart must be only this single product, optional)

**Comment by Pacu2** [comment]
I think it would be way easier to implement if you’d programically create a cart with a single item.

**Comment by maarcingebala** [comment]
I think it's a very specific requirement that one could easily achieve in Saleor by customizing the code, but it's not something that we'd want to add for now.
