### ISSUE TITLE
LANGUAGES = ('zh-tw', _('Chinese(Taiwan)')) needs to be changed into 'zh-hant'

### ISSUE THREAD

**Issue by elsagong** [mirumee/saleor#2634]
### What I'm trying to achieve
...
Fix the languages problem of Chinese (Taiwan/HongKong)

### Describe a proposed solution
...
Change `LANGUAGES = ('zh-tw', _('Chinese(Taiwan)'))` into 
`LANGUAGES = ('zh-hant', _('Chinese(Taiwan)'))`
### Other solutions I've tried and won't work
…

### Screenshots or mockups

<img width="1114" alt="wx20180820-150041 2x" src="https://user-images.githubusercontent.com/26538238/44324964-ed174480-a489-11e8-988c-24ede0f81f6a.png">

**Comment by Pacu2** [comment]
Other languages should be checked as well to make sure they're resolved properly

**Comment by Pacu2** [comment]
Same situation with the Persian language

**Comment by Pacu2** [comment]
@elsagong So apparently Django has no support for `Persian (Iran)`and `Chinese (Taiwan)`, fallback respectively to `Persian` and `Chinese (Traditional)`. 

Did you mean that under `Chinese (Taiwan)` we are serving `Chinese (Traditional)` or was it an attempt to fix the issue with a missing language?

**Comment by patrys** [comment]
@Pacu2 The change from Taiwanese Chinese to Traditional Chinese is a wanted one but we probably need to rename the locale files and fix the mapping used by Transifex.

**Comment by AtlasMaxima** [comment]
@pacu2 @patrys  it seems as though Taiwanese Chinese is Traditional Chinese (last one) and Mainland Chinese is Simplified Chinese which is the last second one. 

I would like to contribute. Is the issue just to change the language tag from 'zh-tw' to 'zh-hant'?

**Comment by patrys** [comment]
@AtlasMaxima Locale files need to match the language code. As we update translations from Transifex, we'll need a mapping for that as well (Transifex has "Taiwanese" where Django has "Traditional", Transifex has "Chinese" where Django has "Simplified").

**Comment by elsagong** [comment]
@Pacu2 You are welcome, I'm sorry again for my late reply, and It is worth mentioning that there is no "Taiwanese" in China,  people live in Hong Kong, Taiwan and Macao, China all use "Traditional Chinese".
