### ISSUE TITLE
Uncaught ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2641]
### What I'm trying to achieve
To use storefront on dashboard-2.0 branch, but get `Uncaught ReferenceError: webpackJsonp is not defined` error in console.

### Steps to reproduce the problem
1. Go to any storefront url
2. Check console

### What I expected to happen
To execute js as usual.

**System information**
Operating system: MacOS High Sierra 10.13.6 (17G65)
Browser: Chrome 68.0.3440.106 x64

**Comment by maarcingebala** [comment]
I cannot reproduce this issue, it might have been a temporary problem with webpack build.
