### ISSUE TITLE
CircleCI API deprecation problem

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#2655]
CircleCI is forcing new API we need to adjust before August 31.

![image](https://user-images.githubusercontent.com/1870738/44454023-bad92480-a5fa-11e8-9694-ff91a34e0d9b.png)

**Comment by maarcingebala** [comment]
As far as I remember @patrys migrated our config to 2.0 some time ago.

**Comment by patrys** [comment]
Correct: https://github.com/mirumee/saleor/blob/c560c188e8bcc08b813f386e1e802fdc1f539da6/.circleci/config.yml#L1
