### ISSUE TITLE
Add translations to GraphQL API

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#2660]
We need to add translations GraphQL API to all respective models.

First proposition by @maarcingebala  was something like: 
```
{
  product  {
    name
    description
    translation(language: "pl") {
      name
      description
    }
  }
}
```

This way we can ask for several translations in one query

We should also implement an API for adding translations.

**Comment by mociepka** [comment]
Nice idea, could it also works like:
```
translation(language: "pl") {
    products {
        name
    }
    categories {
      name
  }
}
```
The main case for the client will be asking for an object in one language.

**Comment by maarcingebala** [comment]
The first case may be much easier to implement. In the second, we would have to somehow wrap the whole `Query` type with the `translation` type. Asking for one language is a valid in case mostly in the storefront. I can imagine however that in the dashboard you might want to ask for multiple translations of a single product.

**Comment by patrys** [comment]
I prefer the original implementation with the added suggestion that the backend automatically handles translation fallbacks ("de-AT" -> "de" -> "en") so a value is always returned for each field that is requested.

**Comment by Pacu2** [comment]
Should we assume that if a translation exists, it has all of its fields translated?

**Comment by patrys** [comment]
`gettext` module implements the correct fallback logic in its `_expand_lang` helper however it uses underscores to separate the language from the territory and we don't need the `codeset` support.

@Pacu2 If we make the same fields required in the base class that are required in translation classes then I believe that we can.

**Comment by mociepka** [comment]
Could we get both?

**Comment by patrys** [comment]
@mociepka You'd need to make the language part of the returned object IDs, otherwise you'd end up with multiple versions of the same object depending on the wrapping language.

**Comment by michaljelonek** [comment]
After some investigation it looks like adding separate field into the query is easier and the simplest solution while still looking nice. I looked into adding it on the query level i.e. `product(languages: ["pl"])`, but that might be trickier and not as nice considering translations are a separate model. Would have to bother with defaults as well.

Proposed queries:
```
{
  categories(first: 10) {
    edges {
      node {
        name
        id
        translations { # or translations(languages: ["pl", "de"] limited to those languages
          languageCode
          name
          description
        }
      }
    }
  }
}
```

```
{
  category(id: "Q2F0ZWdvcnk6Nw==") {
    name
    translations { # or translations(languages: ["pl", "de"] limited to those languages
      name
      description
      languageCode
    }
  }
}
```

Reasoning: this should make it easier if multiple languages have to be requested at once (for example for dashboard).

Mutations relatively simple, one mutation per language I think would be best:
```
mutation CategoryTranslate {
  categoryTranslate(
    categoryId: "Q2F0ZWdvcnk6Nw==",
    languageCode: "fr",
    name: "accessoires",
    description: "quelques accessoires")
  {
    category {
      name
      translations { # or translations(languages: ["pl", "fr"] limited to those languages
        name
        description
        languageCode
      }
    }
  }
}
```

@patrys @maarcingebala opinions?

**Comment by patrys** [comment]
I believe there should only be one party responsible for the fallback logic. Example:

I'm a client and I request titles of two products in Swiss German. None of them have a specific Swiss German translation, one of them has a generic German translation and one only has a default (English) name.

I'm not sure we ever need to fetch all translations for a single model. The dashboard UI only ever shows a single translation and compares it to the default version. The dashboard UI translation switcher shows all languages configured for the store (although it may want to indicate which translations exists for the currently edited object).

**Comment by michaljelonek** [comment]
The models have something like `TranslationProxy` which I believe is what you're suggesting (i.e. `de-AT -> de -> en`). However by the looks of it that is based on i18n urlpatterns which we can't benefit here from.

As for multiple languages I can see above it was said that dashboard might request multiple languages (benefit of using `translations(languages: graphene.List(graphene.String, required=False)` which works as a filter if any specific languages are requested.

I based this off the original suggested implementation, which again does not mention any fallback (instead it asks for a language). It requested name, description and translated name, description, so I assume if there's no translation for a particular code then the non-translated default fields can be used. In case of `de-AT -> de -> default (i.e. en)` we can implement a simple fallback mechanism, but that's about it, I'd say. Also this is assuming that translated fields require name and description to not be empty.

**Comment by maarcingebala** [comment]
I also doubt we need a way to list all translations per model. As for the queries, I think we could have:
```
category(id: ID!) {
  name
  translation(languageCode: String!)
    name
    language: LanguageDisplay
  }
}
```

**Comment by patrys** [comment]
I think the dashboard needs the following:
* the list of all active languages (something the `shop` should expose)
* the list of translations for a particular object (not strictly necessary unless we want to indicate them in the language switcher)
* the details of a particular translation _with fallback disabled_ (editing `de-AT` should not display data from `de` or default)

The storefront needs:
* the list of all active languages (see above)
* the details of a particular translation _with fallback enabled_ (ideally including the information as to which language it fell back to if possible so we can provide helpful `lang=...` HTML attributes)

**Comment by maarcingebala** [comment]
We'll also need a list of all translatable items within a language:

![image](https://user-images.githubusercontent.com/5421321/53495470-5498f700-3aa0-11e9-850f-d1e5dfe615f3.png)

We could use GraphQL unions to return different types of items e.g.:

```
union TranslatableItem = Attribute | AttributeValue | Category | Collection | Product | ...
```

and a top-level query:

```
translations(languageCode: String!): [TranslatableItem!]!
```

But I have no idea how we would tackle pagination for the above query/view.

**Comment by patrys** [comment]
Is it a requirement that we mix these within a single list? I think it makes more sense to translate pages and products separately (from the translator's point of view).

**Comment by maarcingebala** [comment]
That's a question to @pwgryglak. From the API perspective, I would prefer having a single query for that and maybe include filtering by type.

**Comment by patrys** [comment]
How would you imagine ordering and pagination though?

**Comment by maarcingebala** [comment]
That's the question if we're able to do that or not. I can imagine a similar case for search results pages - you have a global search and return results from multiple models.
