### ISSUE TITLE
Docker volumes impractical for development

### ISSUE THREAD

**Issue by carstenblt** [mirumee/saleor#2663]
Commit c7f380a introduced volumes for the web and celery containers. While this might be a good idea for deployment, it's not useful for development.

Reverting this and implementing #2537 would make development much easier. The documention promises to "automatically reload code", which is not the case right now.

**Comment by patrys** [comment]
I agree, we consider `docker-compose` mostly a tool for local development.

**Comment by stephenmoloney** [comment]
I can make a PR to reverse the volumes change.

**Comment by carstenblt** [comment]
I'm just using a postgres and redis container right now and just run the development server in a venv. What are the reasons to keep the web container?

**Comment by stephenmoloney** [comment]
generally , a docker-compose should launch the entire stack. If you only want to start parts of it you can do that. `docker-compose up -d redis postgresql`

**Comment by stephenmoloney** [comment]
#2695

**Comment by maarcingebala** [comment]
Closed by #2695. Thanks @stephenmoloney!
