### ISSUE TITLE
Set up .gitattributes to mark generated files as such

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#2673]
Some of the files are generated by scripts (like `package-lock.json`, the GraphQL schema, `gql-types.ts` and so on), we should tell GitHub that those are generated to make them appear collapsed in pull requests by default. I don't think we need to mark them as binary though.

**Comment by NyanKiyoshi** [comment]
Things that I think we could hide:
- `*.svg`
- `*.po`
- `*_auto_*.py` (maybe include those migrations as well? If we rename them when a manual change was done; they still have to be checked but probably still be collapsed by default).
- `gql-types.ts`
- `schema.json`

We could also include pre-compiled emails like we spoke some time ago:
- `*.mjml`

If we start using `pipenv` we could also include the lock file.

**Comment by NyanKiyoshi** [comment]
Opened a PR for this because the pipenv lock file diff is quite ugly :wink: 

---

> We could also include pre-compiled emails like we spoke some time ago

@patrys we spoke a while ago about providing the pre-compiled mjml templates instead of requiring the user to compile them. Do we go for it?

**Comment by patrys** [comment]
I think that would be a nice thing to have as unlike compiled CSS/JS these files are not particularly large. @maarcingebala?

**Comment by maarcingebala** [comment]
I agree, email templates change rarely, so we could keep the generated versions in the repository. Also, it would save one step in project setup.
