### ISSUE TITLE
Add tax rate types to API

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2679]
At this moment API's client is unaware of the full list of good types.
It should return this: 
https://vatlayer.com/documentation#type_of_goods

**Comment by dominik-zeglen** [comment]
Blocks #2665

**Comment by patrys** [comment]
I think we should keep this list in code in the backend so that we can provide translated labels for these options (we also need a "default" option for product types that are never reduced).

**Comment by maarcingebala** [comment]
@patrys We do: https://github.com/mirumee/saleor/blob/master/saleor/core/i18n.py#L8
@dominik-zeglen API returns those lists for each country, isn't that enough?

**Comment by dominik-zeglen** [comment]
No, because each country has only a part of the full list. Product's tax group should not depend on the shop's default country.

**Comment by patrys** [comment]
@maarcingebala Front-end does not need to know this for a particular country, we need the full list to assign tax classes to product types.
