### ISSUE TITLE
Update Windows installation guide

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#2680]
In windows installation guide we've missed a point, stating that database should be created. Something like:

```
Create a PostgreSQL database:

Unless configured otherwise the store will use saleor as the database name.

   $ createdb saleor
```

However, this information is present for both Mac and Linux

**Comment by patrys** [comment]
Windows docs tell the user to create a SUPERUSER so that Django can create the DB for itself.

**Comment by NyanKiyoshi** [comment]
@patrys does it?

On Linux I get `django.db.utils.OperationalError: FATAL:  database "saleor" does not exist`. Maybe a parameter to pass? Or I am missing something?

**Comment by piotrpiotr1** [comment]
First:
- Django 3.6.6 
- Add environment variable System - Advanced System Settings - System variables: SECRET_KEY = 'yourssecretkey'
- Open settings.py add SECRET_KEY = os.environ.get('SECRET_KEY')
-pgAdmin: create database saleor,

**Comment by mmmcorpsvit** [comment]
For create database in Postgress need first connect to system database "postgres", then we can create new databases.
so, usual way connect from default postgress user and create saleor database: 
1. open you favorite pgadmin/ems manager/dbForge Studio for PostgreSQL/psql.exe 
2. or use ready Docker image from hub with postgres (have official)
3. or use virtualbox/vagrant/VPS/VDS....

developer must have variants, in any way Docker - mainstream - and this easy and universal way for see "what it is Saleor?"

**Comment by maxpaynestory** [comment]
> Windows docs tell the user to create a SUPERUSER so that Django can create the DB for itself.

Correct, windows documentation clearly tell us to create a superuser and i guess require no change.

**Comment by patrys** [comment]
@Pacu2 Not sure what is the scope of work here?

**Comment by ajostergaard** [comment]
Following the Windows install docs results in this error after `python manage.py migrate`:

`django.db.utils.OperationalError: FATAL:  database "saleor" does not exist`

Instructions should be added to the Windows docs to say that the user needs to create a database. It is not done automatically for production type deployments.

**Comment by ajostergaard** [comment]
> Windows docs tell the user to create a SUPERUSER so that Django can create the DB for itself.

@patrys I think that's only true when running tests, no?!?

**Comment by NyanKiyoshi** [comment]
@ajostergaard yes, looks like there is and was no such things in django's source code.

**Comment by patrys** [comment]
You're right, I've checked and it's definitely only supported during tests.
