### ISSUE TITLE
Refactor product variant inheritance

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#270]
Current implementation makes it impossible to prefetch product variants with `prefetch_related()`. This causes us to execute an additional query per product on category indexes.

We need a single base class for the variants that points to the base product class.

**Comment by mociepka** [comment]
I propose to use the same approach like we have in products. It works on main `Product` model (not abstract), this model contains only common fields, new products inherit from it. So in database we have one table product with all necessary data for prefetch.

**Comment by 3ka5-cat** [comment]
BTW, why base Product isn't abstract and table inheritance is used?

**Comment by patrys** [comment]
This is so we can fetch all products using a single database query.
