### ISSUE TITLE
Ability to store credit card for further usage

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#2700]
Most of the payment providers allow storing tokenized credit card data in a secure way for further transactions.
So after the first transaction, the customer doesn't have to enter credit card details again but just selects stored card from a list.

- [ ] Adapt payment gateways interface to support storing credit cards
- [ ] Implement flag for storing card data in payment method endpoint
- [ ] Add an endpoint that will return list of stored payment methods for the customer

We should be able to store the credit card data in such way we can retrieve them later (e.g. token) but never as plain.

**Comment by krzysztofwolski** [comment]
Good news everyone, we are going forward!

We discussed how it should work:
- we should not save Card details in our db - gateways nowadays provide extra features like automatic card update after exp. date. So we need to pull saved cards directly from the provider
- User model needs hstore field for keeping external ids (ex. Stripe does not provide a way to get stripe customer id by email). Proposed format: key - gateway name, value - the id from the gateway
- changes in API: Extend Checkout with new field: available payment methods. This will contain saved cards, and in the future also loyalty points an prepaid cards

I'll start implementing this in my project and soon™️ will send PR to Saleor :)

**Comment by krzysztofwolski** [comment]
#3899 - Gift cards payments. Related API changes

**Comment by maarcingebala** [comment]
@salwator Please see the issue #4285 - we'll need to provide queries for fetching saved payment method to display them in the user profile.
