### ISSUE TITLE
[FrontEnd][Templates] trash code

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2704]
### What I'm trying to achieve
see: templates/base.html
at end of file code:
```
{% if LANGUAGES|length > 1 %}
  {% include "_language_picker_modal.html" %}
{% endif %}
```
for what need this code? this can be quit delete

**Comment by Pacu2** [comment]
We are including language picker modal template, that will be displayed on the mobile if they're languages to choose from.
