### ISSUE TITLE
Urls returned by GraphQL API should be absolute

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#2718]
### What I'm trying to achieve
Right now default media storage returns relative assets URLs. For instance:
```
/media/__sized__/products/saleor/static/placeholders/t-shirts/6-crop-c0-5__0-5-255x255-70.jpg
```
For API consumers will be much easier to work with relative URLs like:
```
https://example.com/media/__sized__/products/saleor/static/placeholders/t-shirts/6-crop-c0-5__0-5-255x255-70.jpg
```

### Describe a proposed solution
My current solution fixes only product images and looks like:

```
def resolve_thumbnail_url(self, info, *, size=None):
        if not size:
            size = 255
        thumbnail_url = get_thumbnail(self.get_first_image(), size)
        is_absolute_url = urlparse(thumbnail_url).netloc
        if not is_absolute_url:
            return info.context.build_absolute_uri(thumbnail_url) 
        return thumbnail_url
```

But we need a solution which will be working for all media urls.

**Comment by patrys** [comment]
Nitpick: `/foo/` is an absolute URL but I agree that the URLs should contain both the protocol and the FQDN.

**Comment by maarcingebala** [comment]
Also todo in this issue - make sure that `backgroundImage` fields return correct URL. Right now there is a bug and a path to the file is returned if I'm correct. Also, it would be nice if those fields would allow fetching image in different sizes, just as product images do.

**Comment by artursmet** [comment]
In a real deployment scenario, the URLs will be absolute with FQDN because of external storage like S3 or Google Cloud Storage. Prefix (FQDN) will be controlled with `STATIC_URL` and `MEDIA_URL` variables which could be controlled via environment variables.

The other case that @maarcingebala reported with `backgroundImage` URL  is really a bug which I will fix in this issue.

**Comment by patrys** [comment]
Why not use the request variable to make sure URLs are fully qualified on all environments? Having the API return domain-less ones while in development makes it unnecessarily hard to build a non-web client.
