### ISSUE TITLE
Mutation to create products doesn't create the default variant

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2724]
### Steps to reproduce the problem
1. In the new dashboard, create a product of a type that doesn't use variants.

### What I expected to happen
A product is created correctly, but it is missing the default variant, that should be created in that case as well.

**Comment by oldPadavan** [comment]
Does it mean a field `defaultVariant` should be added to `ProductCreateInput`, which should be ignored in case if this type has variants and added as a variant otherwise?

**Comment by maarcingebala** [comment]
To give a bit more explanation - our whole cart and checkout flow is based on `ProductVariant` instances, but at the same time, we want to allow creating simple products that don't have variants. Hiding variants is done at the presentation layer (in the dashboard and the storefront), while under the hood we always create a "hidden" variant to make the checkout possible.

The issue is that this logic hasn't been implemented in the API yet. For instance, take a look at [the implementation of this logic in the old dashboard](https://github.com/mirumee/saleor/blob/master/saleor/dashboard/product/views.py#L107). As you can see, we artificially create an empty variant there, only for holding the SKU and quantity.

We need to implement the same logic in the API. So when the user creates a product of a type that doesn't use variants, API should create a default variant anyway. I don't know yet how to tackle passing additional data (e.g. SKU or quantity) in the mutation for creating products. Maybe we could try what you propose and have this extra field. I don't know, we would have to implement it and see how it works and looks. For sure there sure be a good description of that field explaining that it is only used in that particular case.
