### ISSUE TITLE
Add a "ready for pickup" status for orders

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#273]
Sometimes people want to pick up their stuff in person. We should make it easy to place and handle such orders (ie. don't ask for a shipping address and provide a list of such orders for quick access).

**Comment by maarcingebala** [comment]
This issue is almost as old as Saleor but I guess it's still valid, what do you think @patrys? 😀

**Comment by maarcingebala** [comment]
Maybe this shouldn't be handled as an order status, but as a shipping method.

**Comment by patrys** [comment]
I think we should rather introduce a "confirmed" status between "new" and "fulfilled" to allow for flows where warehouse/wholesaler confirms availability before money is captured.

**Comment by maarcingebala** [comment]
Statuses that we have now are:
- unfulfilled (I guess this could be just "new")
- partially fulfilled
- fulfilled
- canceled

Maybe it's a good idea to revisit this and introduce "confirmed" as you suggests.

**Comment by xu4wang** [comment]
We have some potential clients who sale goods online but never make shipment, instead, the buyer will get a QR code after payment, and visit the shop in person, showing the QR to pick up in a pickup zone.

**Comment by zudheer** [comment]
Is there a chance of pickup  implementation?

**Comment by eCzerniak** [comment]
Hi @zudheer few days ago click and collect feature was merged :) 
https://github.com/mirumee/saleor/pull/7673
