### ISSUE TITLE
Get rid of manually generating URLs in the email templates

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#2730]
In some places, in the emails templates we are creating full absolute URLs in such ways:
```
{{ protocol}}://{{ domain }}{% url 'account:reset-password-confirm' uidb64=uid token=token %}
```
Which leads to hard to catch bugs. 

All URLs should be created on the backend, passed to the templates, instead of gluing protocol/domain/URL manually in the templates. 
This could be also an template tag.

**Comment by NyanKiyoshi** [comment]
Also relate to #1999 where if we have a S3 bucket storage set-up, the logo URL become invalid.

**Comment by tomcio1205** [comment]
@Pacu2 I will take care of that
