### ISSUE TITLE
Can't delete Collections

### ISSUE THREAD

**Issue by aTonyXiao** [mirumee/saleor#2732]
### What I'm trying to achieve
I have create a bunch of collections through the admin dashboard, but I can't find a way to delete any collections in the dashboard.

I didn't see any button for delete collections.

Any idea?

**Comment by NyanKiyoshi** [comment]
On the collection details page, on the far right of the screen there is a three dots button that opens a drop-down allowing you to delete the collection.

**Comment by aTonyXiao** [comment]
Thanks!

**Comment by patrys** [comment]
This will work better in the new dashboard that we're working on.
