### ISSUE TITLE
Simple declarative style work with ENV (like common.env in Docker)

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2739]
### What I'm trying to achieve
Wide use env variables do develop process more hard that can be simple. And we have saleor + celery where too need ENV. So this situation do Saleor not trivial for run, but easy start - very important for any library.

### Describe a proposed solution
Setup simple battery:
`pip install django-environ`

**manage.py**
```
#!/usr/bin/env python3
import os
import sys
import environ
environ.Env.read_env()

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "saleor.settings")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
```

**celeryconf.py**
```
import os
from celery import Celery

import environ

path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '.env'))
environ.Env.read_env(env_file=path)

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'saleor.settings')

app = Celery('saleor')

CELERY_TIMEZONE = 'Europe/Kiev'

app.config_from_object('django.conf:settings', namespace='CELERY')
app.autodiscover_tasks()

```

and now create on root path of project file **.env**:
```
SECRET_KEY=bla-bla-bla
DEBUG=True
CREATE_IMAGES_ON_DEMAND=False
REDIS_URL=redis://127.0.0.1:6379
ELASTICSEARCH_URL=http://127.0.0.1:9200
DEFAULT_COUNTRY=UA
DEFAULT_CURRENCY=UAH
ALLOWED_HOSTS=*
CELERY_BROKER_URL=amqp://login:password@localhost:5672/
EMAIL_URL=smtp://email@gmail.com:password@smtp.gmail.com:465/?ssl=True

```

so, now we have one declarative style environments file in docker style (see common.env). Too PyCharm have support .env files with highlight, comment support etc.... Simple, easy to manage, docker-like. Please review to accept.

**Comment by dominik-zeglen** [comment]
I deleted screenshot because it was revealing you tokens and passwords. Please double check next time.

**Comment by mmmcorpsvit** [comment]
there was test data for local dev only, dont worry about this)

**Comment by patrys** [comment]
@dominik-zeglen FYI everyone can see what the comment was before your edit by clicking the dropdown that says "edited by ...". You can't anonymize content this way.

**Comment by NyanKiyoshi** [comment]
@mmmcorpsvit you really should delete the first version, by clicking on the "edited by..." dropdown then clicking the last one and hitting `Delete`.
