### ISSUE TITLE
Consider moving all templates to one dir

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#274]
We currently use per-app template directories which results in a nice structure but may be a nightmare for new users to localize the file they want to edit.

**Comment by patrys** [comment]
@bogdal, @mociepka?

**Comment by bogdal** [comment]
Frankly, I like the idea that we have templates per app, mostly because I got used to them :) Applications seem to be separated as much as possible, however the extra nesting can introduce muddle. Anyway, we have to have a main templates directory, so maybe It's a good idea to simplify this structure and use one directory for all project's templates.

:+1: for one `templates` directory

**Comment by mociepka** [comment]
I don't see an issue in current structure. New users without bad habits are used to this structure. If someone request this feature we can implement it.

**Comment by bogdal** [comment]
Both solutions are good and they have their pros and cons. Generally it's a matter of users approach.

**Comment by artursmet** [comment]
I think that when someone has dedicated front-end developer in team, it's better to use one directory for templates. Because there are all templates in one place (and also PyCharm integrates with this approach very well). For new users it will be easier to have one templates directory

**Comment by paweltin** [comment]
:+1: for one dir for templates. I end up with some global dir for cross-app includes either way, so having all templates in a tight hierarchy is a pro for me.

**Comment by paweltin** [comment]
There is also one more pro for this (minor): I usually set up a watcher that sniffs for changes in html and reloads all my devices when got one. It's impossible with current structure.

**Comment by patrys** [comment]
I propose moving all storefront templates and static files to a separate app. This will allow us to introduce the concept of themes. Just copy the default theme to a new dir and add it to `INSTALLED_APPS` before the default one.
