### ISSUE TITLE
Release August 2018 (v2018.08)

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2742]
Release plan for the `v2018.08` version of Saleor.

## Prepare new release
- [x] All qualifying changes are merged to `master` and issues from the current milestone are resolved or moved to future milestones.
- [x] Update the `demo` branch to include changes from the current release
- [x] Add "preview" note in the new dashboard on demo
- [x] Make sure "readonly" mode and data anonymization works on demo

## Release new version
- [x] Tag the `master` branch with: `v2018.08` and push to Github.
- [x] Tag the `demo` branch with: `demo/v2018.05` and push to Github.
- [x] Update `master` in [saleor-demo]([url](https://github.com/mirumee/saleor-demo)) if necessary.
- [x] [Deploy](https://github.com/mirumee/saleor/wiki/Demo-deployment) the demo.
- [x] Configure JWT token expiration on demo

## Publish release notes
- [x] Prepare screenshots and GIFs showing highlighted features.
- [x] Publish [release notes](https://github.com/mirumee/saleor/releases) on Github.
- [x] Publish the [blog](https://medium.com/saleor) post.

## After release
- [x] Update Github [roadmap](https://github.com/mirumee/saleor/projects/6).
- [x] Update [getsaleor.com](http://getsaleor.com/) page - link to the latest release and the [roadmap.](http://getsaleor.com/roadmap/)

**Comment by mmmcorpsvit** [comment]
are any plans to Saleor on Docker Hub (stable + current branches) how part of release?

**Comment by maarcingebala** [comment]
@mmmcorpsvit We're not planning to tackle that in this release. Most of our efforts are focused on GraphQL API and the new dashboard.

**Comment by maarcingebala** [comment]
New release is out:
- [Medium blog post](https://medium.com/saleor/august-release-of-saleor-dashboard-2-0-preview-c48ea14431ca)
- [Github release](https://github.com/mirumee/saleor/releases/tag/v2018.08)
