### ISSUE TITLE
Apply textwrap.dedent to GraphQL descriptions

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#2747]
Currently the descriptions returned by introspection look like this:

```graphql
# Variables of this type must be set to null in
#         mutations. They will be replaced with a filename from a following
#         multipart part containing a binary file. See:
#         https://github.com/jaydenseric/graphql-multipart-request-spec
scalar Upload
```

This also causes GraphiQL and Playground to show tooltips like that:

```
Variables of this type must be set to null in         mutations. They will be replaced with a filename from a following         ...
```

**Comment by fowczarek** [comment]
I can't reproduce this bug. 
![image](https://user-images.githubusercontent.com/43955230/47358934-90bfe380-d6cb-11e8-962d-2cb7a8a9cc6a.png)

**Comment by patrys** [comment]
You are looking at HTML doc output. HTML rendering by default folds all whitespace into a single character which hides the problem. Take a look at tooltips (hover over something in the query editor on the left in GraphiQL/Playground) to see the issue.
