### ISSUE TITLE
[Templates] [Cosmetics] Add Alt text to cart

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2749]
Add Alt text to 
`<svg data-src="{% static "images/cart.svg" %}" width="35" height="30"/>`
in **base.html**
details: https://www.w3.org/wiki/HTML/Usage/TextAlternatives

**Comment by MartinSeibert** [comment]
What would we want the alt text to be? The icon is next to a navigation link for Your Cart and below/to the left of the cart counter badge, so maybe it should say "Items"?

**Comment by MartinSeibert** [comment]
Created a pull request at https://github.com/mirumee/saleor/pull/3060 adding an alternative text of "Items"
