### ISSUE TITLE
Mobile version template need rework

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2753]
Mobile version at this moment can't be usable, 
just see: 
![fecd53bb17 1](https://user-images.githubusercontent.com/9638835/44855602-2151e880-ac74-11e8-848a-bf398f2f19fd.jpg)
there present catalog and language picker, but i cant login/logount there

How solution in real shops use separated system for catalog and user menu, please see:
https://repka.ua/
![6c021a7b4b 1](https://user-images.githubusercontent.com/9638835/44855911-c4a2fd80-ac74-11e8-8293-7e501db9e7c2.jpg)

![86bc501964 1](https://user-images.githubusercontent.com/9638835/44855902-bf45b300-ac74-11e8-8632-ac908fc399c4.jpg)

yet screenshots:
user menu expanded:
![f70cf082ca 1](https://user-images.githubusercontent.com/9638835/44856013-0af85c80-ac75-11e8-8872-49908feb88d3.jpg)
catalog expanded menu:
![e9049c3a9d 1](https://user-images.githubusercontent.com/9638835/44856071-295e5800-ac75-11e8-8c56-5205686d9a1b.jpg)

**Comment by Pacu2** [comment]
I think it's resolved on the latest master
