### ISSUE TITLE
Make API field names more consistent

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#2757]
We should introduce some project-wide pattern for endpoints and mutations naming.
In some parts of the project, we have different styles of naming for mutations and it makes hard to figure out if some API scenarios are covered or not.

I recommend to keep following approach:
`<Entity><Action` examples:
`categoryCreate`
`orderUpdate`

now we have for example `orderAddNote` and it should be refactored to `orderNoteAdd`
Also, we should consider using the same verbs for common operations like `Create`, `Update` or `Delete`. Now it's mixed up sometimes.

The second recommendation is to sort alphabetically and group mutations in `api.py` file because now it's hard to find interesting mutations there.

What do you think?

**Comment by Pacu2** [comment]
I think we should stick to `Create`, `Update` and `Delete`, what's more I'm in for `<Entity><Action>` naming, eg. `OrderNoteAdd`, `AttributeValueCreate` etc.

**Comment by the-bionic** [comment]
I'm on it.

**Comment by the-bionic** [comment]
What do we do in cases where ```<Entity><Action>``` does not apply?

For instance, there is ```OrderUpdateShipping```, should it be refactored to ```OrderShippingUpdate``` even though OrderShipping isn't really an entity?

**Comment by maarcingebala** [comment]
Maybe first let's analyze existing names and look for those that we wanted to refactor. I'm not 100% convinced that such strong naming conventions always work, sometimes it may just sound unnatural.

**Comment by the-bionic** [comment]
I'll open a PR for review.

**Comment by patrys** [comment]
@artursmet I'd consider "add note" to be action, not subject so "OrderAddNote" and "OrderUpdateShipping" are correct.

**Comment by maarcingebala** [comment]
Agree with @patrys - it sounds much more natural.
