### ISSUE TITLE
Upgrade to pillow 5.2.0

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#2758]
`Pillow ≥ 5.1.0` ships Python 3.7 wheels for Windows but [requirements.txt](https://github.com/mirumee/saleor/blob/84490be7608a144fb0dcc47339d78ccb09c5ac81/requirements.txt#L86) is requiring to install Pillow 5.0.0 because `django-versatileimagefield` is still blocking the upgrade. Because of that, some Windows users have issues installing Pillow as they have to compile from sources because of that.

I opened https://github.com/respondcreate/django-versatileimagefield/pull/131 a while ago to fix that issue but the project doesn't seem to be alive. How should we handle this issue? Should we force the installation of Pillow 5.2.0?

**Comment by patrys** [comment]
Given that we try to avoid cropping merchandise photos I'd consider the pros and cons of dropping the ability to specify focus points and switching to another thumbnailing solution.
