### ISSUE TITLE
Can't update the payment status by Dashboard order menu

### ISSUE THREAD

**Issue by cfprabhu21** [mirumee/saleor#2773]
### What I'm trying to achieve
…
I can't see any way to update the order payment status by manually using dashbord

### Steps to reproduce the problem
1.  Simply create the one order by using storefront with 'Dummy provider' and complete the order with 'Pre-authorized' status
2. After that login the Dashboard and check the latest order 
3. There is no option to update the payment status by manually.

### What I expected to happen
…
shop Admin can able to update the order payment status by using Dashboard

### Screenshots

![image](https://user-images.githubusercontent.com/20884305/44992968-87ad7280-afb6-11e8-9140-ba46ed792912.png)

**System information**
Operating system:  windows 10
Browser: chrome

**Comment by maarcingebala** [comment]
The only way you can changes payment statuses from the dashbaord is by performing actions such as "Capture", "Refund" or "Void" which are available in the order details view (depending on the current state of order and payment).
