### ISSUE TITLE
Dashboard 2.0: Update window title when views change

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#2775]
Currently the window title is always the generic "Dashboard" so it's impossible to tell two tabs apart. We should have key components update the window title when they are mounted.

Could we use the PageHeader for this?

**Comment by the-bionic** [comment]
We could use a library called [React Helmet](https://alligator.io/react/react-helmet/), or something like [this](https://stackoverflow.com/questions/46160461/how-do-you-set-the-document-title-in-react)

**Comment by patrys** [comment]
Helmet seems to be exactly what's needed. Thank you for the link @the-bionic.

**Comment by the-bionic** [comment]
Happy to help.
