### ISSUE TITLE
Mutations for staff management

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#2776]
There are no mutations available for staff and permission management.

Blocks #2593

**Comment by maarcingebala** [comment]
Queries and mutations that we have now:

- query to fetch all staff users:
```
users(isStaff: true) {
    edges {
      node {
        id
      }
    }
  }
```

- query to fetch all available permissions:
```
shop {
    permissions {
      code
      name
    }
  }
```

- mutation to create a staff user:
```
mutation {
  staffCreate(input: {email: "", permissions: [], sendPasswordEmail: true}) {
    errors {
      field
      message
    }
    user {
      id
    }
  }
}
```

- mutation to update the staff user:
```
staffUpdate(id: "", input: {permissions: ["order.manage_orders"]}) {
    errors {
      field
      message
    }
    user {
      id
    }
  }
```

What else would we need @patrys? These above should allow to implement most of the logic.

**Comment by patrys** [comment]
Sorry, I've missed `staffCreate` and `staffUpdate`. As for the API I'd consider providing explicit endpoints for customers and staff. Currently it's quite confusing as we're exposing the database structure rather than logical units it represents.

**Comment by Pacu2** [comment]
@patrys Should we split it between `customers` and `staff` as it was on the old dashboard?

At this moment we have a generic `users` which returns every User registered in the store.
