### ISSUE TITLE
[Dashboard 2.0] Dont clicable configure items, wrong load login template

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2789]
Try use new Dashboard 2.0 on demo site:
1. https://demo.getsaleor.com/dashboard/next/configuration/ , items not clickable 
2. try refresh by F5 page, see on one second login page

Firefox 61.0.2 + Windows 10

**Comment by maarcingebala** [comment]
Exactly. To avoid confusion, maybe we should consider putting an information somewhere in the UI saying that a particular feature is not yet available.
