### ISSUE TITLE
Return user's geolocalization based on IP

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2790]
API should return geolocalization data guessed from users's IP. We already have all the logic in the `saleor.core.middleware.country` function. What needs to be done is to wrap this data in a GraphQL type and tie it up to the API. 

E.g.:
```
shop {
  geolocalization {
    countryCode
  }
}
```

Should it return DEFAULT_COUNTRY from settings as a fallback?

@mociepka Please provide more information about what data you'd need in the storefront.

**Comment by patrys** [comment]
I think it's not necessary to automatically default to DEFAULT_COUNTRY. Let the client handle the case where the country is not possible to determine. I think we ought to return more than the country code though. There's #2745 for displaying richer representations (so you don't need to fetch the full list of countries). There's also the problem of knowing which currency to default to for the given country.
