### ISSUE TITLE
Add ability to store color and images in the variant attribute model

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#2793]
### What I'm trying to achieve
I would like to be able to render variant picker with color or image like adidas.com does:
![image](https://user-images.githubusercontent.com/1870738/45107115-db47c980-b138-11e8-8376-a50724212c64.png)

Currently, an attribute has only one field: name. In the past, we have the attribute type model but that was over-engineered. 

### Describe a proposed solution

I propose to introduce a new `value` field (CharField) in the attribute model (not required if empty filled by the slug). This field could be filled with a color (#aabbcc), an image url (https://a.b/image.svg) or a string. 

API consumer will decide what to do with those values (or just omit them). For my data picker, I could simple match regexps for url and color and decide how to render my widget.

In the future dashboard could be doing the same and provide a nice interface for color picker or images selector.

```graphql
query Product {
  product(id: "UHJvZHVjdDo0") {
    id
    variants {
      edges {
        node {
          id
          sku
          name
          attributes {
            attribute {
              id
              slug
              name
            }
            value {
              id
              name
              value
            }
          }
        }
      }
    }
  }
}

```

**Comment by mociepka** [comment]
Great idea @NyanKiyoshi I found a really nice regexp here:
https://gist.github.com/olmokramer/82ccce673f86db7cda5e#gistcomment-2174868

We could use it and that will cover all cases.

**Comment by maarcingebala** [comment]
I like the idea of values other than just string. I'm not convinced about regex parsing for the long run. If you need the simplest solution that works for now then OK, but maybe we should consider allowing a dict as the value:
```
{
  type: COLOR|URL|STRING
  value: ""
}
```
Then we could take advantage of enums for the type in the API.

**Comment by mociepka** [comment]
If you are proposing @maarcingebala saving those types in the DB then we are going back to the attribute types which was over complicated.

If you are proposing to do a regexp validation on the backend side and returns type base on it that is the best solution in my opinion. The client won't worry about that matching anymore.

And please don't forget about @NyanKiyoshi proposition:
```ts
{
  type: COLOR|GRADIENT|URL|STRING
  value: ""
}
```

**Comment by maarcingebala** [comment]
I didn't mean doing regexp validation in the backend. If we had a simple field "value" as you suggest, in the dashboard we would allow putting there any string and the client would have to figure out the type of this string by using regexp, am I right? For me it's fine for now as it is very simple to handle in the UI. But again, if we want to rely on it in the future, the additional `type` field seems much more elegant than regexp.

**Comment by mociepka** [comment]
If the type is an abstract thing like product type than I agree. But if you have a string with a technical specification (which format never change) and this string contains information about its type I don't see any benefits.

I see corner cases like type set to `color` and value set to `http://some.image/url`. I really like the idea (a type generation on the fly) which born in this brainstorm, please reconsider it @maarcingebala .

**Comment by maarcingebala** [comment]
I'm thinking about an _elegant_ solution, as the API we're building is also meant for other people than us. I don't want to slow down the development so If you believe your solution is fine then we can go for it and see how it works, and reiterate later if we change our minds.
