### ISSUE TITLE
Return a variant price instead of the priceOverride

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#2794]
### What I'm trying to achieve
In my impression, `priceOverride` is an internal functionality which shouldn't be available in the API.
In addition, when I want to show a variant price I need to always introduce logic like:
```
let variantPrice = variants[0].priceOverride || product.price
```

### Describe a proposed solution
I propose to change the attribute `priceOverride` to `price` which shows product price when the override is empty.

**Comment by patrys** [comment]
I think we should offer both, the price override requiring product admin privileges.
