### ISSUE TITLE
Incomplete orders persists and lock product availability

### ISSUE THREAD

**Issue by xponrails** [mirumee/saleor#2797]
### What I'm trying to achieve
Suppose that I have only 1 quantity of product A.
Customer X adds A into his cart.
Customer Y adds A into his cart.
Customer X starts the checkout flow.
Customer Y starts the checkout flow: he is notified that A is no longer available.
Customer X doesn't continue the checkout flow, without pay the rder for example: A remains locked forever and no one can buy it or add it into the cart again.

Admin sees the order into his dashboard and cannot delete the order.

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
…

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by xponrails** [comment]
I think that the problem is related to the way you are tracking inventory at runtime.
System should not consider not completed orders.
Moreover, if I set a quantity of 5 elements for a variant, that number should go to 0 every time someone buy a product.

**Comment by xponrails** [comment]
I'm Italian :-) 
The problem is that when a customer start the checkout procedure, all quantities are locked. 
But the customer can leave and the order remains incomplete.
At least an admin could be able to delete the order from the dashboard, or just free the locked inventory.

**Comment by xponrails** [comment]
I agree, orders must not be deleted.

In my opinion there are three ways:
- create an order only after a valid payment, before that there sould be a model Cart
- add a button (for an admin) to manually set the order as incomplete and free the stock
- add a background task that runs every hours and check for left orders and free the stock

**Comment by maarcingebala** [comment]
In API we create orders only after when the selected payment method succeeds (either credit card is charged or if this is another payment method, the customer is somehow obligated to pay).
