### ISSUE TITLE
Add price fields to the checkout API

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#2798]
### What I'm trying to achieve
A common scenario in an e-commerce API is to return calculated prices for subtotal, total, discountedTotal etc. for product list (cart, checkout, order etc.)

That eliminates price calculation in the clients. I propose to add:
* `totalPrice` both for whole checkout object and checkout item,
* `subtotalPrice` is a price without shipping cost,

### Describe a proposed solution
```graphql
query getCheckout($token: UUID!) {
  checkout(token: $token) {
    token
    id
    totalPrice
    subtotalPrice
    lines {
      edges {
        node {
          id
          quantity
          totalPrice
          variant {
            id
            name
            product {
              id
              name
              thumbnailUrl
              price {
                amount,
                currency
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by artursmet** [comment]
Implemented in `checkout-2.0` branch - https://github.com/mirumee/saleor/pull/2567/commits/02a5820f980e3d8b089ab429ebc5dc85653ead9c
