### ISSUE TITLE
Use Django's JSONField instead of external package

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#2802]
Since v1.9 Django comes with builtin `JSONField`, we could start using it instead of an external `jsonfield` package.

Potential drawbacks:
- It's PostgreSQL-specific field
But we are supporting only PostgreSQL + HStoreField(postgres-specific as well) is already in use

Docs:
https://docs.djangoproject.com/en/2.1/ref/contrib/postgres/fields/#jsonfield

**Comment by patrys** [comment]
We already use `django.contrib.postgres` extensively, including using PostgreSQL-specific `hstore` format.

**Comment by the-bionic** [comment]
Hello. How can I help with this?

**Comment by Pacu2** [comment]
Hi @the-bionic,
We are currently getting `JSONField` field from the `jsonfield` package. 
We are eventually looking to drop this package, and use  `JSONField` from django instead as defined in https://docs.djangoproject.com/en/2.1/ref/contrib/postgres/fields/#jsonfield

Pull request is more than welcome!

**Comment by the-bionic** [comment]
Great. I will work on this.
