### ISSUE TITLE
Dashboard 2.0: We need a mutation to change the shipping method of an order

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#2807]
I couldn't find a mutation that allows an order's shipping method to be changed. There is an `orderUpdate` mutation that looks like a candidate for this field but I'd like to see it split into separate mutations instead of being an all-in-one function that it currently is.

**Comment by Pacu2** [comment]
Should this mutation return a `shipping_method` and `order`, or just the `order`?

**Comment by patrys** [comment]
I think just the `order`. We don't modify the method in any way.
