### ISSUE TITLE
Dashboard 2.0: Replace `fulfillmentCreate` mutation with `orderCreateFulfillment`

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#2809]
Creating an order fulfillment is an operation on the order object so it should follow the naming scheme of other mutations. It should return `order` as well as the newly created `fulfillment`.

It should also take `order: ID!` as a named argument outside of `input` like other mutations do. This allows the client to bind the `order` variable separately from the user input:

```jsx
<OrderFulfillmentCreate variables={{ order: order.id }}>
  {createFulfillment => (
    // ...
  )}
</OrderFulfillmentCreate>
```

**Comment by Pacu2** [comment]
Should this be applied to the rest of fulfillment mutations as well? eg. `FulfillmentCancel`, `FulfillmentUpdate`

**Comment by patrys** [comment]
Yes, we should have `orderCancelFulfillment` and `orderUpdateFulfillment` and both should return the `order` as an additional field in output. Question is should they have the signatures of `(id: ID!, fulfillment: ID!, input: ...)` (ie. specify both order ID and fulfillment ID)?

**Comment by dominik-zeglen** [comment]
It should be noted that `FulfillmentCreateInput` should take at least `lines: [FulfillmentLineInput!]!` and still api should check if any product would be fulfilled - at this moment it is possible to create empty fulfillment.
