### ISSUE TITLE
npm run build-assets not working

### ISSUE THREAD

**Issue by hasher-hasher** [mirumee/saleor#2817]
When i try to run "npm run build-assets" command, the output freezes on the warning
"DEPRECATION WARNING on line 4, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer" and i'm stuck on this step so the build doesn't finish.

![npm build-assets error](https://user-images.githubusercontent.com/6460771/45312835-8d014480-b503-11e8-951d-8dd27ca38a64.png)

Someone knows how to fix this error?

**Comment by Pacu2** [comment]
It's just a warning, I doubt if that's an issue directly. What are your Node and npm versions

**Comment by hasher-hasher** [comment]
Node 10.10.0 and npm 6.4.1. But the problem is that the build don't finish. Stop at the last line and i wait hours and nothing

**Comment by NyanKiyoshi** [comment]
If you hit CTRL+C, what does it show? Maybe the error stack would be helpful to see where it's hanging/ stuck.

**Comment by patrys** [comment]
It could be memory related, current Webpack config can easily peak at 1.5GB.

**Comment by hasher-hasher** [comment]
@NyanKiyoshi Just stop the process. Nothing but this.

**Comment by hasher-hasher** [comment]
@patrys I will try to see the memory. I don't now if it have something with it, but i'm running on a Linux subsystem for windows. I will check the memory issue

**Comment by hasher-hasher** [comment]
It seems to be a problem with Linux Subsystem for Windows. I had to change the environment to windows to work properly. Closing the issue.

**Comment by danrleywillyan** [comment]
[2018-10-24T14_39_02_266Z-debug.log](https://github.com/mirumee/saleor/files/2510980/2018-10-24T14_39_02_266Z-debug.log)

It`s not memory problem!  See the error messages:
![error saleor1](https://user-images.githubusercontent.com/12025215/47439529-e60afc00-d782-11e8-8a58-7df0aff65605.png)

> TS2349: Cannot invoke an expression whose type lacks a call signature.  ....    has no compatible call signatures.  

All the error messages has that sentence.  Do I have to change the code ?

**Comment by the-bionic** [comment]
I noticed this error recently, too. 

Are you using VS code?

**Comment by the-bionic** [comment]
Also, I think your issue is unrelated to the original issue. You probably updated your tslint or Typescript -- it is not in sync with the ```saleor's```.

**Comment by JPilarr** [comment]
ihe same problem ... this problem still continue

i have Linux Mint 19

npm run build-assets


> saleor@0.0.0 build-assets /home/honza/projects/saleor/saleor
> webpack -p

sh: 1: webpack: not found

npm ERR! Linux 4.15.0-43-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build-assets"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! saleor@0.0.0 build-assets: `webpack -p`
npm ERR! spawn ENOENT

npm ERR! Failed at the saleor@0.0.0 build-assets script 'webpack -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the saleor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs saleor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls saleor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/honza/projects/saleor/saleor/npm-debug.log

 error log>
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build-assets' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild-assets', 'build-assets', 'postbuild-assets' ]
5 info lifecycle saleor@0.0.0~prebuild-assets: saleor@0.0.0
6 silly lifecycle saleor@0.0.0~prebuild-assets: no script for prebuild-assets, continuing
7 info lifecycle saleor@0.0.0~build-assets: saleor@0.0.0
8 verbose lifecycle saleor@0.0.0~build-assets: unsafe-perm in lifecycle true
9 verbose lifecycle saleor@0.0.0~build-assets: PATH: /usr/share/npm/bin/node-gyp-bin:/home/honza/projects/saleor/saleor/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle saleor@0.0.0~build-assets: CWD: /home/honza/projects/saleor/saleor
11 silly lifecycle saleor@0.0.0~build-assets: Args: [ '-c', 'webpack -p' ]
12 info lifecycle saleor@0.0.0~build-assets: Failed to exec build-assets script
13 verbose stack Error: saleor@0.0.0 build-assets: `webpack -p`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid saleor@0.0.0
15 verbose cwd /home/honza/projects/saleor/saleor
16 error Linux 4.15.0-43-generic
17 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build-assets"
18 error node v8.10.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error saleor@0.0.0 build-assets: `webpack -p`
24 error spawn ENOENT
25 error Failed at the saleor@0.0.0 build-assets script 'webpack -p'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the saleor package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     webpack -p
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs saleor
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls saleor
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by hasher-hasher** [comment]
Have you checked your webpack installation? It's up to date? Last version of npm/Nodejs?

**Comment by Overboard92** [comment]
Try and change your npm permission. Worked for me.
`sudo chown -R $USER ~/.npm`

**Comment by saik999** [comment]
Hi, 
Whenever I run the command npm run build-assests ; i get following output, It nevers ends after running for hours; I have been trying for days now. Its so diffcult to get saleor up and running. 
```
_**root@Saikat:/home/saleor# npm run build-assets

> saleor@0.0.0 build-assets /home/saleor
> webpack -p

Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
(node:4055) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
DEPRECATION WARNING on line 4, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.**_
```
**Screenshot**  
<img width="908" alt="saleor-assest build" src="https://user-images.githubusercontent.com/1397538/55166478-399bce80-5195-11e9-962a-d8da58c30f6d.PNG">

**Comment by elsagong** [comment]
@Pacu2 Hi, same issue here, I have a server with 1GB memory and 4GB swap, it doesn't work without any errors.

**Comment by patrys** [comment]
@elsagong It's a bad idea to build assets on your production server. Use another machine or a laptop and only upload resulting files (what Django collects during `collectstatic`).

**Comment by elsagong** [comment]
@patrys Got it, thank you so much.

**Comment by elsagong** [comment]
@patrys Hi, I use another machine with 8 GB memory, it still says ```
`Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
(node:9782) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist``
```

**Comment by imrbg** [comment]
still a problem on win10

**Comment by aquaerius** [comment]
I get a differrent error, whe running `$npm run build-assets`
I doesn´t find it, and this is the package.json:
```js
{
  "name": "saleor",
  "version": "0.0.0",
  "repository": {
    "type": "git",
    "url": "git://github.com/mirumee/saleor.git"
  },
  "author": "Mirumee Software",
  "license": "BSD-3-Clause",
  "bugs": {
    "url": "https://github.com/mirumee/saleor/issues"
  },
  "homepage": "http://getsaleor.com/",
  "dependencies": {},
  "devDependencies": {
    "mjml": "^4.6.2"
  },
  "scripts": {
    "build-schema": "python manage.py get_graphql_schema > saleor/graphql/schema.graphql",
    "heroku-postbuild": "npm run build-emails",
    "build-emails": "mjml --config.beautify false -l skip \"templates/templated_email/source/*.mjml\" -o templates/templated_email/compiled"
  }
}
```

Am I missing something?
Im following the installation docs for linux, [Step #9](https://docs.saleor.io/docs/getting-started/installation-linux#9-prepare-front-end-assets)

**Comment by maarcingebala** [comment]
@aquaerius Please see [this comment](https://github.com/mirumee/saleor/issues/5539#issuecomment-619821751) in another issue.
