### ISSUE TITLE
Async endpoints in Saleor

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#282]
We need to decide how to implement endpoints for asynchronous requests in Saleor. For instance, now we need to add endpoint that will handle reordering product images by drag and drop. In a moment we will need the same feature for categories. Doing this in a Django way would be implementing custom formsets to validate and get the data. This would require replacing simple list of images with more complicated forms on frontend side. On the other hand, we could add API-like views and just send simple JSON structures. With this approach we could use Django REST Framework which gives for example easy json validation. Which idea is better?

**Comment by elwoodxblues** [comment]
@patrys, @mociepka?

**Comment by patrys** [comment]
I highly recommend going with REST framework as we will likely need to expose an API at one point or another.

**Comment by mociepka** [comment]
:+1:
