### ISSUE TITLE
No react in the latest version

### ISSUE THREAD

**Issue by hassanzadeh** [mirumee/saleor#2823]
### What I'm trying to achieve
I installed the site but there is no react anywhere, all is plain templates!

### What I expected to happen
I expected to see the dashboard and the filtering sections, at least, to be implemented with graphql and Apollo.

I'm using my Mac local server, but I doubt that could be the issue.

**Comment by Pacu2** [comment]
New dashboard is available at `/dashboard/next`, is that what you're looking for?

**Comment by hassanzadeh** [comment]
Thanks, so which branch is the newest? Also search criteria is also react based in that release?

On Sep 11, 2018, at 9:41 AM, Filip Kucharczyk <notifications@github.com<mailto:notifications@github.com>> wrote:


New dashboard is available at /dashboard/next, is that what you're looking for?

**Comment by Pacu2** [comment]
@hassanzadeh All latest changes are merged into the master. As far as I remember the search was not implemented yet.

**Comment by hassanzadeh** [comment]
Sorry I meant the filtering, see figure bellow:
[cid:FAF31602-349D-4F10-9890-BC9D4B2C7B4B@hsd1.ga.comcast.net]

On Sep 11, 2018, at 9:46 AM, Filip Kucharczyk <notifications@github.com<mailto:notifications@github.com>> wrote:

merged

**Comment by patrys** [comment]
Do you mean what is available on demo.getsaleor.com? That is released from the `demo` branch and it contains some customizations, including a React-based product list.

**Comment by hassanzadeh** [comment]
Thanks,
Yes I guess that’s what I mean. For example, when I click on some filtering option, the output will refresh without a need to press the update. But in the master’s branch that is not implemented.
Does it mean that the master’s branch is not unto date?

**Comment by patrys** [comment]
Demo is always going to be a little bit more customized than the master branch, its purpose is to showcase possibilities. It also has additional Saleor mascot branding that we don't want custom stores to use.

**Comment by hassanzadeh** [comment]
I see, thanks.

On Sep 11, 2018, at 10:56 AM, Patryk Zawadzki <notifications@github.com<mailto:notifications@github.com>> wrote:

mascot

**Comment by Pacu2** [comment]
Please reopen if you have any further questions
