### ISSUE TITLE
TaxRate on the Product model should be a choice field

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#2829]
We're missing `choices` on `tax_rate` field for `Product` model. Should be set the same way as on the ProductType.

**Comment by axce1** [comment]
@Pacu2 please, assign me for this

**Comment by Pacu2** [comment]
@axce1 How you doing with this issue?

**Comment by axce1** [comment]
@Pacu2 almost done, need fix tests

**Comment by Pacu2** [comment]
@axce1 That's great! We always encourage to open pull requests as soon as possible, so we can work on them together and eventually propose minor improvements earlier.

**Comment by axce1** [comment]
@Pacu2 i cant understand how fix tests
can you help me?

travis-ci log: https://travis-ci.com/axce1/saleor/jobs/146880154

**Comment by Pacu2** [comment]
In saleor/graphql/core/types/money there's `TaxRateType` Enum
You could import it to your tests and use it like `TaxRateType.STANDARD.name`
That would do the job

**Comment by axce1** [comment]
@Pacu2 i fix tests but need your review and them i create PR
https://github.com/axce1/saleor/pull/1#issuecomment-425643557

**Comment by Pacu2** [comment]
@axce1 Please create a PR first, so I and other contributors can review it. I think that's the usual workflow we have.
