### ISSUE TITLE
Figure out how to keep a track on what changes were made to the model

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#2833]
At this moment OrderEvent just gives a generic "ORDER_UPDATED" message without stating what was updated.

We could store the state between the updates and display what exactly changed in the event, using an app like:
https://django-simple-history.readthedocs.io/en/latest/

This should concern not only the order but also all connected instances that can be changed

**Comment by NyanKiyoshi** [comment]
Closing this would close #2443.

**Comment by maarcingebala** [comment]
There is already a bunch of events implemented for orders so we can close this one.
