### ISSUE TITLE
Dashboard 2.0: Consider maintaining the GraphQL schema in DSL instead of JSON

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#2836]
Currently we use `python manage.py graphql_schema` to save the schema in JSON format. Most tools can't consume this format so it's useless for features like editor IntelliSense. It being JSON also means it's almost impossible to tell what changed when reviewing a pull request.

I suggest using a dedicated tool to dump the schema in GraphQL DSL format instead. It's text and it's easily diffable during review plus it can be used together with tools like [`gql`](https://www.npmjs.com/package/@playlyfe/gql) to get autocomplete in IDEs. The main downside is that external tools require the server to be running before the schema can be generated.

Potential candidates:
* [`graphql-cli`](https://github.com/graphql-cli/graphql-cli)
* [`get-graphql-schema`](https://github.com/prisma/get-graphql-schema)

**Comment by rafalp** [comment]
GraphQL-Core provides the `print_schema` utility that takes GraphQLSchema and returns `str` with schema's SDL. I'll PR with management command printing SDL on stdout for us to print in terminal or redirect to file.
