### ISSUE TITLE
Error when I execute NPM install

### ISSUE THREAD

**Issue by OneBoYun** [mirumee/saleor#2839]
### What I'm trying to achieve
…

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
…

### Screenshots

**System information**
Operating system: 
Browser:

The problem I have is executing NPM install
Thank you, everybody

![1](https://user-images.githubusercontent.com/29030022/45465277-0b99f400-b747-11e8-80b6-85e824f9956d.png)
![2](https://user-images.githubusercontent.com/29030022/45465278-0b99f400-b747-11e8-978e-e00ae352be8b.png)
[2018-09-13T03_17_19_844Z-debug.log](https://github.com/mirumee/saleor/files/2377577/2018-09-13T03_17_19_844Z-debug.log)

**Comment by akjanik** [comment]
Can you please provide console output in the issue ticket? Most people are not eager to download and open file from the unknown source. Triple backtick (\`\`\`) should do the work.
From the screenshot above I can only guess, but it seems to me that there is a permission problem with installing node modules into directory that user has no access.

**Comment by dominik-zeglen** [comment]
Have you ever run `node` with `sudo`?

**Comment by OneBoYun** [comment]
I gave root permission, but it didn't work after several attempts. I also replaced the NPN node

**Comment by OneBoYun** [comment]
> Can you please provide console output in the issue ticket? Most people are not eager to download and open file from the unknown source. Triple backtick (```) should do the work.
> From the screenshot above I can only guess, but it seems to me that there is a permission problem with installing node modules into directory that user has no access.

I gave root permission, but it didn't work after several attempts. I also replaced the NPN node

**Comment by OneBoYun** [comment]
> Have you ever run `node` with `sudo`?

I use sudo and I still can't

**Comment by OneBoYun** [comment]
> 你能向我们的输出`ls -la /home/zhangbo/saleor`和`ls -la /home/zhangbo/saleor/node_modules`



> Could you send us the output of `ls -la /home/zhangbo/saleor` and `ls -la /home/zhangbo/saleor/node_modules`

OK

**Comment by OneBoYun** [comment]
> Could you send us the output of `ls -la /home/zhangbo/saleor` and `ls -la /home/zhangbo/saleor/node_modules`

OK
![11](https://user-images.githubusercontent.com/29030022/45527504-9691f180-b80e-11e8-8c5d-8fd6e7417f4d.png)
![22](https://user-images.githubusercontent.com/29030022/45527506-9691f180-b80e-11e8-9433-ad96ab16d3ca.png)

**Comment by OneBoYun** [comment]
![image](https://user-images.githubusercontent.com/29030022/45538225-04eba980-b839-11e8-8d7e-b4a7d1ec7ffd.png)

**Comment by OneBoYun** [comment]
Who can check the problem for me? Thank you very much

**Comment by maarcingebala** [comment]
Please reopen if the issue still occurs.
