### ISSUE TITLE
Refactor `fulfillmentUpdate` mutation

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2843]
`fulfillmentUpdate` mutation should be renamed to `orderUpdateFulfillmentTrackingInfo` to clarify what exactly would be updated since fulfillment lines are immutable. Its signature should also be changed to 
```graphql
orderUpdateFulfillmentTrackingInfo(id: ID!, input: { trackingNumber: String! }, notifyUser: Boolean)
```
so we won't mix object properties and action options in one input.

**Comment by Pacu2** [comment]
related: #2809
