### ISSUE TITLE
Creating empty order draft causes API to explode

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2849]
### What I'm trying to achieve
To get order draft details from API.

### Steps to reproduce the problem
Execute this query
```
{
  orders {
    edges {
      node {
        id
        userEmail
      }
    }
  }
}
```

### What I expected to happen
Definitely not to throw an error.

**Comment by dominik-zeglen** [comment]
Blocks #2754

**Comment by Pacu2** [comment]
On it
