### ISSUE TITLE
Docker install Stuck 

### ISSUE THREAD

**Issue by Sshuichi** [mirumee/saleor#2857]
### What I'm trying to achieve
Install and run 

### Steps to reproduce the problem
1. 
Just install using Docker

2. 

### What I expected to happen
Install the app

### Screenshots

![image](https://user-images.githubusercontent.com/5939429/45553598-6d408800-b845-11e8-84fb-1aa04f6d7ad9.png)

**System information**
Operating system:  Ubuntu
Browser:

**Comment by Pacu2** [comment]
Please take a look at #2817, seems similar to me

**Comment by Sshuichi** [comment]
Let me resize the ec2 instance and see.

**Comment by Sshuichi** [comment]
Yep, resized it to t2.small and it works now.

**Comment by Pacu2** [comment]
Glad to see this resolved, please reopen if you have any further questions

**Comment by Sshuichi** [comment]
Sorry, after setting up docker and building the image, does it automatically listen to Port 80 or should I have an interface like Nginx? 

Thanks.

**Comment by artursmet** [comment]
Hi @Sshuichi, docker by default binds to port `8000`,  to run docker on 80 you should use nginx, this is the recommended approach.
