### ISSUE TITLE
Design a product placeholder image

### ISSUE THREAD

**Issue by paweltin** [mirumee/saleor#287]
Current:

![product-image-placeholder.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/product-image-placeholder-8015099ce17bab46e49d6b77eb3a2a692ea94ad1677918a1d4c42200d0e2d1ff.png)

**Comment by subgrafik** [comment]
![no-image](https://cloud.githubusercontent.com/assets/7837760/8329021/46b02f94-1a76-11e5-877c-3f52b0b14817.png)
 first draft - do dyskusji. - generlanie ja sie musze ciut bardzie w identyfikacjie samego saleora wbic by uspojnic te rzeczy / brazki placeholdery itd ... )

**Comment by patrys** [comment]
wydaje mi się, że taki placeholder to jest pierwsza grafika, którą każdy sklep będzie musiał wymienić, więc nie wiem, czy jest w czymś lepsza od aktualnego różowego 404

**Comment by subgrafik** [comment]
![no-image-proposal](https://cloud.githubusercontent.com/assets/7837760/11337892/cda71c82-91f0-11e5-9162-f74058ac8b8f.png)

sth like saleor leica

**Comment by mociepka** [comment]
Jak dla mnie wypas :+1:

**Comment by subgrafik** [comment]
OOo misu -

dzieki za propsy :)

**Comment by mirekm** [comment]
:+1:

**Comment by car3oon** [comment]
:+1:

**Comment by mociepka** [comment]
No, to @subgrafik rób PR i lecimy z koksem :D.

**Comment by mirekm** [comment]
cc @car3oon ;)

**Comment by subgrafik** [comment]
![no-image](https://cloud.githubusercontent.com/assets/7837760/11340547/a6a06644-91fe-11e5-8286-2e0b1554ceb1.png)
4 Patrys with love as requested.

**Comment by subgrafik** [comment]
![no-image-1000-x-1000-b](https://cloud.githubusercontent.com/assets/7837760/11341651/9d40bec8-9203-11e5-83a5-0edab815591a.png)
![no-image](https://cloud.githubusercontent.com/assets/7837760/11341650/9d4081a6-9203-11e5-954e-952984c7ab98.png)
