### ISSUE TITLE
Bad Request when run locally

### ISSUE THREAD

**Issue by raybesiga** [mirumee/saleor#288]
Hi Community

I follow the steps defined in the README successfully but when I try to run the application locally, it returns a BAD REQUEST(400) error.

```python 
Performing system checks...

System check identified no issues (0 silenced).
June 14, 2015 - 14:18:35
Django version 1.7, using settings 'saleor.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
[14/Jun/2015 14:18:46] "GET / HTTP/1.1" 400 26
[14/Jun/2015 14:18:46] "GET /favicon.ico HTTP/1.1" 400 26
[14/Jun/2015 14:18:46] "GET /favicon.ico HTTP/1.1" 400 26
```
Any advice on next steps?

**Comment by bogdal** [comment]
Hi @raybesiga. Try to fill out `ALLOWED_HOSTS` settings or change `DEBUG` to True. I guess this should be by default.

**Comment by raybesiga** [comment]
Thanks @bogdal that fixed it. Cheers!
