### ISSUE TITLE
PyCharm, manage.py, Error parsing command test: No module named '.'

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2888]
### What I'm trying to achieve
Try use manage.py feature in PyCharm, i dont know this is bug or not

### Steps to reproduce the problem
1. run im pycharm Ctrl+Alt+R
2. get message ```Error parsing command test: No module named '.'```

### What I expected to happen
empty 

### Screenshots
![1303fc542b](https://user-images.githubusercontent.com/9638835/45642316-84d77500-bac0-11e8-88c1-d5c3afbfb4ef.jpg)

**System information**
Operating system:  Windows 10

**Comment by Pacu2** [comment]
Does the app works if you use it outside the PyCharm? 
I Think it might be a problem with the PyCharm rather than Saleor

**Comment by mmmcorpsvit** [comment]
yes, all work fine

**Comment by Pacu2** [comment]
Then you should check your PyCharm configuration as I suppose there's a problem.

**Comment by Pacu2** [comment]
Closing for now, please reopen if you have further questions
