### ISSUE TITLE
Design example product images

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#289]
This is for the `populatedb` command that creates a bunch of example products.

**Comment by subgrafik** [comment]
testowo narazie - 1 zajawka - punkt zaczepienia do dalszej dyskusji.. fajnie by wymyslec jakis wspolny patent poza nazwa na produkty ... ze np jedzenie czy kolorystyka ... tbc ... 
wrzucam pare opcji zeby zobaczc w ktora strone najlepiej isc z dizajnami ewentualnie czego nie chcemy...  
![tst-a](https://cloud.githubusercontent.com/assets/7837760/8328772/f72bc2f0-1a73-11e5-9bd7-51f3297551b8.png)
![tst-b](https://cloud.githubusercontent.com/assets/7837760/8328774/f72d91fc-1a73-11e5-8a9e-a69d9e47b6d5.png)
![tst-c](https://cloud.githubusercontent.com/assets/7837760/8328775/f72f3ebc-1a73-11e5-84ae-21f3e09a1feb.png)
![tst-d](https://cloud.githubusercontent.com/assets/7837760/8328773/f72bcf66-1a73-11e5-86ba-574cc186a063.png)

**Comment by elwoodxblues** [comment]
:+1: x 4

**Comment by patrys** [comment]
Awesome :astonished:

**Comment by mirekm** [comment]
Wypas @subgrafik !

**Comment by mirekm** [comment]
Each of this images should contain Mirumee logo (perhaps the framed one, similar to how we brand our Twitter marketing materials).

**Comment by patrys** [comment]
@subgrafik try to provide @paweltin with images ready to check-in (optimized for size, color profiles stripped etc.) by Friday

**Comment by subgrafik** [comment]
![a01](https://cloud.githubusercontent.com/assets/7837760/11338636/a49a5be2-91f5-11e5-9b71-32222bde6a69.png)
![a02](https://cloud.githubusercontent.com/assets/7837760/11338637/a49c15c2-91f5-11e5-97d1-fcc98f76fa00.png)
![a03](https://cloud.githubusercontent.com/assets/7837760/11338638/a49d433e-91f5-11e5-9fe0-9ec8d5a5061a.png)
![a04](https://cloud.githubusercontent.com/assets/7837760/11338640/a4a0a48e-91f5-11e5-9ad6-0ef474e2fdad.png)
![a05](https://cloud.githubusercontent.com/assets/7837760/11338641/a4a1b8a6-91f5-11e5-83a3-d7f8d40af1f6.png)
![a06](https://cloud.githubusercontent.com/assets/7837760/11338639/a49fd306-91f5-11e5-8526-3863362f39a8.png)

**Comment by subgrafik** [comment]
koszulki nie zyskuja w wektorze .. wiec nie me czy nie zrobimy foto bazy /// 
formatkla do szerowania wygladala by jakos tak 
![skladka-share](https://cloud.githubusercontent.com/assets/7837760/11338695/e257ce38-91f5-11e5-84cf-ad58029581dc.png)

**Comment by subgrafik** [comment]
https://github.com/mirumee/saleor-product-mockups
