### ISSUE TITLE
Replace Bag and Shirt with GenericProduct

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#290]
We only want to provide one product class for physical goods (supported by EAV later) out-of-the-box. We also want to drop dimensions other than the weight.

**Comment by hongquan** [comment]
I appreciate this.

**Comment by patrys** [comment]
If you look at pending pull requests for Saleor, you will find one for a new dashboard. It contains this change among many others that we believe will make building new stores much easier (including EAV for product variants). We expect it to finally land on Monday :)
