### ISSUE TITLE
Consider changing order lines to a list

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2900]
Currently, the `lines` field in the `Order` type is a connection. I think we should simplify this and change it to a simple `graphene.List`. I cannot imagine a situation where pagination of those lines should be necessary. 

The query currently looks like this:

```
{
  order {
    id
    lines {
      edges {
        node {
          quantity
          productName
        }
      }
    }
  }
}
```

We could change it to:
```
{
  order {
    id
    lines {
      quantity
      productName
    }
  }
}
```

**Comment by Pacu2** [comment]
@maarcingebala Shall we proceed?

**Comment by maarcingebala** [comment]
I think yes. @dominik-zeglen knows of few other nested connections that could be turned into lists, as we shouldn't ever paginate them in UI.
