### ISSUE TITLE
Use profile picture in Social Auth 

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2903]
1. add to SOCIAL_AUTH_PIPELINE
`    'saleor.pipeline.save_profile_picture',`
2. declare function (i do only for Google)
```python
def save_profile_picture(backend, user, response, details, is_new=False, *args, **kwargs):
    if backend.__class__.__name__ == 'CustomGoogleOAuth2':
        # user_object = User.objects.get_or_create(user=user)  # RETURNS TUPLE (instance, created(boolean))
        image = response['image'].get('url')
        display_name = response['displayName']

        user.image = image
        user.display_name = display_name
        user.save()
```
3. now we can use user avatar in templates:
`                    <img src="{{ user.image }}" alt="Avatar" class="img-rounded" style="width:30px;">`

![e694d13b15](https://user-images.githubusercontent.com/9638835/45719537-6f8a4580-bba9-11e8-88f8-d0e178fb383a.jpg)

**Comment by Pacu2** [comment]
I don’t feel like we should use pictures for the customers. Can’t find the reason why the user appearance would help with anything that happens in the shop.

**Comment by maarcingebala** [comment]
I agree with @Pacu2. We're not planning to introduce avatars in the current storefront. It's the type of customization that people can do themselves in their forks of Saleor. This issue is a good reference for anyone looking for a possible solution.
