### ISSUE TITLE
Unused code in the templates

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2904]
Tiny piece text can be simple delete

in file:
**templates\dashboard\base.html**
line:
{% load version %}
and 
{% version %}

file:
saleor\core\templatetags\version.py

in file:
saleor\__init__.py
line:
__version__ = 'dev'

and little fix in settings.py:
SENTRY_DSN
...'release': 'dev'

**Comment by Pacu2** [comment]
„Trash code” is not a proper

**Comment by maarcingebala** [comment]
To be verified - we should display the current version (as the latest commit's SHA for example) in the dashboard.

**Comment by mmmcorpsvit** [comment]
> 
> 
> „Trash code” is not a proper wording when it comes to code that’s unused and can be taken offensively. Please use „unused code” or „legacy code” next time

Sorry, you right, my low English skill restrict some time me.


> 
> 
> To be verified - we should display the current version (as the latest commit's SHA for example) in the dashboard.

SHA + datetime,

Get the current git hash in a Python script: 
https://stackoverflow.com/questions/14989858/get-the-current-git-hash-in-a-python-script
https://gist.github.com/simonw/091b765a071d1558464371042db3b959

Get timestamp of the last commit in git repository:
https://stackoverflow.com/questions/13104495/get-time-of-last-commit-for-git-repository-files-via-python
https://gist.github.com/bitrut/1494315

**Comment by ajostergaard** [comment]
I'd like to pick this one up but @maarcingebala need clarification on requirement please.

Not sure requiring git to be installed on production instances is a good idea so perhaps rather update the static __version__ string as part of release packaging? If so am perhaps not best placed for this issue after all.
