### ISSUE TITLE
Recommended spot for payment processing

### ISSUE THREAD

**Issue by chadsaun** [mirumee/saleor#292]
Sorry, this is more of a question than an issue.

I'm using django-payments as well and I was thinking about the best place to put the code for actually processing the payment.  I was thinking it might be best in the the last step (say SummaryStep) in the `process` method just before it creates the order since in my case, if the CC declines I don't want to create an order.  Then if it declines I could just redirect them back to the last step with error messages.

Does this sound right?  Or is there a better spot/way of doing this?

**Comment by patrys** [comment]
Sorry for the late reply. Is there a reason why you don't want to create an order before payment? It offers a convenient way to reserve stock for the duration of payment, gives the user an URL to return to in case they don't complete the payment in time and nothing stops you from purging orders that don't receive payments within a certain time frame.

**Comment by chadsaun** [comment]
I don't mind creating an order earlier in the checkout process.  Can you create an order without Billing and Shipping information?  I just noticed that in Saleor's repo it looks like it's creating the order in the `process` method of the `SummaryStep`.   My main concern (or question) is if the credit card payment fails, can I redirect them back to the "Summary Step" with the error message so that they can correct the credit card information and try again?

**Comment by patrys** [comment]
That's how the payment works currently. If it fails, you are getting redirected to the order details page where you can re-attempt payment. The order has a unique URL so it's possible to email payment reminders etc.
