### ISSUE TITLE
Allocate stock when draft orders are completed

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2923]
Currently, when creating a draft order through the API, the stock is instantly allocated for newly added order lines (I think this is also the case in the old dashboard). Instead, we should allocate the stock only when a draft order is ready and is turned into a regular order. As a result of allocating items too early, we may be blocking the stock for customers in the storefront.

**Comment by Pacu2** [comment]
@maarcingebala Sure, what in case when one wants to turn draft order into a regular one, but the stock is not sufficient? Should we allocate as much as possible? Not allocate at all? Or just throw an error

**Comment by maarcingebala** [comment]
I think we should give admins enough freedom to create the orders with the quantities they wanted, even if that would result in negative stock for some products. We should only make sure that we notify the admin about that (maybe by creating an order event?).
