### ISSUE TITLE
npm run build-assets trouble (Exit status 2)

### ISSUE THREAD

**Issue by HardMaxwellRobo** [mirumee/saleor#2927]
### What I'm trying to achieve
Hi, I have problems with installing saleor. I trying 

### Steps to reproduce the problem
1. I reinstall nodejs and npm from version 8.x to 10.x (latest)
2. I trying to clone git repository and reinstall requirements.txt

### What I expected to happen
After npm install I trying to use command "npm run build-assets" also try yarn build-assets
### Screenshots
<img width="655" alt="snapshot2" src="https://user-images.githubusercontent.com/32393876/45839324-b9e00380-bd1c-11e8-9169-94b0298b2bfb.png">
<img width="653" alt="snapshot3" src="https://user-images.githubusercontent.com/32393876/45839489-2d821080-bd1d-11e8-9e68-67e208aef57e.png">

Logfile: 
[2018-09-20T18_25_56_221Z-debug.log](https://github.com/mirumee/saleor/files/2402620/2018-09-20T18_25_56_221Z-debug.log)

**System information**
Operating system: Linux Ubuntu 16.04 LTS x64
Nodejs version: 8.x and 10.6 and 10.11
npm version: 6.4.1 and 6.1.0

Thank you very much for help. Have a good day.

**Comment by the-bionic** [comment]
It's most likely a node/npm version issue. Please what are the exact results of:
npm -v 
node -v

**Comment by HardMaxwellRobo** [comment]
> It's most likely a node/npm version issue. Please what are the exact results of:
> npm -v
> node -v

node: 10.6.0
npm: 6.1.0

**Comment by Pacu2** [comment]
Is your master branch up to date? You might want to try removing node_modules and reinstalling if you've changed your nodejs version in between.

**Comment by HardMaxwellRobo** [comment]
> Is your master branch up to date? You might want to try removing node_modules and reinstalling if you've changed your nodejs version in between.

I have already tried. Still have same issue :(

**Comment by Pacu2** [comment]
@HardMaxwellRobo I see your copy of saleor is 12 commits behind, could you try updating to latest master? It doesn't happen to me on a clear Saleor copy

**Comment by HardMaxwellRobo** [comment]
Thank you very much for help @Pacu2 
Just clone new master branch working for me.
