### ISSUE TITLE
Provide Saleor logo as svg

### ISSUE THREAD

**Issue by paweltin** [mirumee/saleor#293]
The one from landing page.

**Comment by subgrafik** [comment]
![love.svg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/love-fa1a2ffcf8445ce8b167ece3d63fc06678960d23ccb18b92658da3f3219aa570.svg)

![LOGO SALEOR-02.svg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/LOGO%20SALEOR-02-b6066336138627353ab429f332bd92a8082b8df9324014050087d7785a28390e.svg)

**Comment by subgrafik** [comment]
![LOGO SALEOR-01.svg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/LOGO%20SALEOR-01-459af6ccb85fc41601a2ff8195bf65e3f27bf5ac17fa8edb41d114733ce6808d.svg)

![LOGO SALEOR-02.svg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/LOGO%20SALEOR-02-8d9da0c31b3da5909c1c67f2e0502e16d83a12842dc6df28e6826a16c9e1c4f1.svg)

**Comment by subgrafik** [comment]
![LOGO SALEOR black.svg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/LOGO%20SALEOR%20black-943d28a68a1dbef4fdb0fdcd20b48e40ef83736cd7fb0afe544862be6a511514.svg)

**Comment by subgrafik** [comment]
![LOGO SALEOR black FIX.svg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/LOGO%20SALEOR%20black%20FIX-60bbb4015b1d8794e53ba7e0ca12d525327582c3249025a8da0273fb7ba4e704.svg)

**Comment by paweltin** [comment]
Letter `O` sticks out of the baseline

**Comment by patrys** [comment]
Isn't it expected to bleed a little vertically in most fonts?
