### ISSUE TITLE
Need remove Django 1.* from some files

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2947]
in files:
```
tox,ini
travis.yml 
requirements.in
```

still present DJANGO=1.*

**Comment by Pacu2** [comment]
We are supporting latest release(2.1) + last LTS(1.11), it will change after the next LTS is released

**Comment by mmmcorpsvit** [comment]
1.11? but for what?

**Comment by Pacu2** [comment]
Some of the folks prefer to stick to the LTS releases, 1.11 is latest LTS so we will support it until the new one is out (2.2)
