### ISSUE TITLE
How about broke E501 (lines limit)

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#2948]
4 years ago Django developers broken this PEP8: https://code.djangoproject.com/ticket/23395
and i full agree, what this PEP8 full deprecated, Code climate used PR still have check to 79 symbols limit...
anybody real work on this limit?

do this, lets broke this stupid PEP in Saleor!

P.S. im my practice i up this limit to 120 chars

**Comment by Pacu2** [comment]
As I remember we've discussed it at some point, and 80 chars limit is still live in the community so we've decided to keep it, not to style-shock the newcomers.
