### ISSUE TITLE
Product form tax_rate

### ISSUE THREAD

**Issue by ggmomo** [mirumee/saleor#2953]
### What I'm trying to achieve
When I edit a product on the dashboard I would like to have the product tax_rate as the selected option. Instead the product type tax_rate is selected.

### Steps to reproduce the problem
1. Set a tax_rate on a product type
2. Set a different tax rate on a product
3. Go to the dashboard and edit the product
4. When you look at the tax_rate select field, the selected value is the product type tax_rate 

### What I expected to happen
When I edit a product I would like to have the product tax_rate (if set) as the selected option.

### Screenshots
![issue_saleor](https://user-images.githubusercontent.com/5839095/45964444-1cd7e000-c026-11e8-9d91-21a53e32881d.jpg)

**System information**
Operating system: OSX 10.13
Browser: Firefox

Thank you.

**Comment by Pacu2** [comment]
Blocked by #2829 
I think that product_type tax rate should be set as the placeholder, and a product's tax_rate should be blank by default

**Comment by tomcio1205** [comment]
@Pacu2 I can resolve that issue but can you tell me what do you mean by poduct_type tax_rate as placeholder and tax_rate as blanked?

**Comment by Pacu2** [comment]
@tomcio1205 `tax_rate` field's widget should have a [placeholder](https://www.w3schools.com/tags/att_input_placeholder.asp), which should be equal to product's product type tax rate
Then, if no value is provided, product's tax rate should be set to None
