### ISSUE TITLE
Allow creating attributes with values in one mutation

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2967]
We need to change the signature of `productAttributeCreate` mutation to allow creating attribute values in the same mutation. This is required by the new UI for the product attributes dashboard.

**Comment by Pacu2** [comment]
@marcingebala should we change update mutation as well?

**Comment by maarcingebala** [comment]
I think we should do that only in the "create" mutation. "Update" mutation is more problematic because you would have to always pass the whole list of attributes; also, if you accidentally passed an empty list you'd remove all values. Take a look at `MenuCreate` and `MenuUpdate`, we did a similar change there recently.
