### ISSUE TITLE
Add WeightField

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#297]
We need a field that will handle weights. It should work like PriceField in django-prices (decimal values, unit).

**Comment by artursmet** [comment]
Maybe we should introduce more customizable field? For example `MeasureField` which will take unit, exactly as `PriceField` takes currency? What do you think @mociepka, @patrys ? Any suggestions?

**Comment by patrys** [comment]
Definitely nothing specific to weight. It should just take a unit and provide a form input and a way (could be a template tag) to display it to the user.
