### ISSUE TITLE
Need Cart Management Mutations in GraphQL

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#2972]
### What I'm trying to achieve
I'm building a custom storefront using React and the GraphQL API. I cannot find a mutation that allows one to add/edit/remove a product to cart. Mutations that would create/edit/delete `OrderLine` data structures, basically.
On a related note, how would checkout be handled on the GraphQL API?

### Other solutions I've tried and won't work
Storing the cart on the React app itself won't work because the cart needs to be persisted across devices and sessions.

**Comment by Pacu2** [comment]
There's a branch `checkout-2.0` which might be worth checking, as checkout mutations are kept in there.

**Comment by khalibloo** [comment]
Thanks very much, I'll have a look.

**Comment by khalibloo** [comment]
Great, the `checkout-2.0` branch has the cart management mutations I was looking for.

**Comment by khalibloo** [comment]
I'm glad there's a pure SPA storefront in development. Storefront 2.0
For my use case, the approach you've described works great. I'll use that approach as well. Thanks a lot for sharing. I'll keep an eye on the progress of the development on `checkout-2.0`.
