### ISSUE TITLE
Use enum as permission code

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2986]
### What I'm trying to achieve
Code transparency and type safety.

### Describe a proposed solution
Return `enum` instead of `string` as permission code.

**Comment by dominik-zeglen** [comment]
Blocks #2964

**Comment by maarcingebala** [comment]
I removed the `blocker` label - let's implement those changes using strings for permission codes and later we'll refactor them to enums.

**Comment by the-bionic** [comment]
Please, how can I locate where the permission codes are?

**Comment by Pacu2** [comment]
@the-bionic permissions are obtained via `get_permissions()` helper function (it only gets the ones we are using)

**Comment by the-bionic** [comment]
I'm sorry, I missed this. I picked another ticket. When I finish with that and this is still open, I'll pick it up.

**Comment by the-bionic** [comment]
Doing this: 
``` python
PermissionEnum = graphene.Enum(
    'PermissionEnum', [(str_to_enum(permission.codename), permission.codename)
                       for permission in get_permissions()])
``` 
during import time crashes the app when testing. 

```django-pytest``` complains because the code is trying to access the database during import time here: ```get_permissions()```

``` python
def get_permissions(permissions=None):
    if permissions is None:
        permissions = MODELS_PERMISSIONS
    codenames = [permission.split('.')[1] for permission in permissions]
    return Permission.objects.filter(codename__in=codenames).prefetch_related(
        'content_type').order_by('codename')
```

```Failed: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.
```

What if the ```MODELS_PERMISSIONS```  was used instead?

**Comment by patrys** [comment]
Why do we need to fetch permissions from the database? We already know which permissions are supported.
