### ISSUE TITLE
publish a saleor store on ubuntu and using Apache

### ISSUE THREAD

**Issue by wubuyun** [mirumee/saleor#2993]
![default](https://user-images.githubusercontent.com/35350235/46273260-2cc25900-c52b-11e8-9cd7-d9d1a38553e0.PNG)
![2](https://user-images.githubusercontent.com/35350235/46273269-321fa380-c52b-11e8-9864-bf9f53530da4.PNG)
![3](https://user-images.githubusercontent.com/35350235/46273292-49f72780-c52b-11e8-832f-185df2edafde.PNG)

varnish  port 80

**Comment by artursmet** [comment]
Hello,

It looks like you didn't install the project requirements. Did you executed `pip install -r requirements.txt`?

**Comment by patrys** [comment]
@wubuyun If you're using a virtualenv to install, make sure you [specify the `python-home=` param to `WSGIDaemonProcess`](https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html).

**Comment by Pacu2** [comment]
Please reopen if you have any further questions.
