### ISSUE TITLE
Bring back 'Wishlist' or 'Mail me when available'

### ISSUE THREAD

**Issue by scottyeung** [mirumee/saleor#3004]
### What I'm trying to achieve
…
Wishlist feature used to be available last year but went missing in the latest releases

**Comment by Pacu2** [comment]
As far as I remember wishlist was never available, wasn't it?
There were attemps to include it in https://github.com/mirumee/saleor/pull/1120 and https://github.com/mirumee/saleor/pull/737

**Comment by Pacu2** [comment]
Regarding the 'Mail me when available' I'm not sure as well if we've supported something like it.

**Comment by maarcingebala** [comment]
They were never available in Saleor, but I'd put both on our features roadmap. It's not our priority for now, but once we stabilize the API, we could get back to implementing new features.

**Comment by maarcingebala** [comment]
I've both to the roadmap: https://github.com/mirumee/saleor/projects/6
