### ISSUE TITLE
Turn FulfillmentLines into a list

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#3008]
I can't imagine a situation where we should paginate fulfillment lines, think that they could be changed into Graphene.List type, same as we did with the Order lines

**Comment by dominik-zeglen** [comment]
It makes no sense fulfillment lines being paginated while order lines are flat.

**Comment by maarcingebala** [comment]
Related fields that I think should be changed to lists:
- [ ] `Checkout.payments`
- [ ] `Order.payments`

**Comment by maarcingebala** [comment]
- [ ] `User.addresses` - no need to paginate them as well.

**Comment by maarcingebala** [comment]
Resolved in #3307
