### ISSUE TITLE
Make different parts of dashboard depend on different permissions

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#301]
Currently the entire dashboard depends on a single `is_staff` permission. This won't work for larger teams where responsibilities are divided.

**Comment by 3ka5-cat** [comment]
I've implemented same feature in current work project, based on saleor. 
Actually, we have two groups: content managers, who fill info about products, and operators of call center, who proceed orders.
First group has permissions only on product list and creation views, while last group couldn't create products, but has access to all tabs linked with orders processing -- payments, customers and, surprisingly, orders. All this is obvious, I think.. May be I've missed something?
If your vision of permission system in dashboard matches with described approach and you will specify concrete groups, or if there are some differences, I'm happy to implement it via PR.

Oh, there is one detail -- these two groups are created on initial deployment. So, it is also should be implemented in utils script, which will be called on populatedb management command.

**Comment by mociepka** [comment]
After some discussion we decide to introduce only view and edit permissions on views level not the model level. We will have permissions like "product.view", "product.edit", "category.view", "category.edit", "order.view", "order.edit" etc. The "order.edit" will give ability to edit `order_line`, `delivery_group` not only `order`.

**Comment by elwoodxblues** [comment]
@koradon A more detailed list of things to do in this task:
- [ ] Add view in dashboard to list only staff users. We should also exclude staff users from the current customers list. Both views should use the same templates, only queryset is different.
- [ ] Add form to manage permissions in staff users' details view (in dashboard). This form should have one multiple-choice field `permissions` and submiting it should update user's permissions. As choices we should provide something more readable than Django's permissions, but rather simple choices as for example `product.view`, `product.edit`. We don't want to require permission at such granular level as Django does be default. Instead we want to only add permission to the "main" model such as `Product` or `Order` and only check those when accessing related views.
- [ ] Add decorator that will check if user has right permissions to access the view. All dashboard views should be decorated. `PermissionDenied` should be raised if user has no rights to access the view.
