### ISSUE TITLE
Add `product` field to OrderLine

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#3014]
It would enable us to go from order details view to product / variant details, and enable API consumer to use different product name format than `Product (variant)`.

**Comment by patrys** [comment]
This field would have to be nullable and I'd like to ask that its description makes it clear that the API client can't depend on the product being returned. We can't and shouldn't use the `product` link to construct a product name like the original comment is seeming to propose. If a better name is desired, it should be assigned to `product_name` as the order needs to reflect the state of the database from the point in time it was placed.

**Comment by maarcingebala** [comment]
`OrderLine` model has a relation with `ProductVariant` but it's excluded in the GraphQL type. But `product_name` should always contain the right name, as we set that field when creating an order, taking into account the variant's attributes and translations, if they're available.

**Comment by dominik-zeglen** [comment]
How about splitting `product_name` into `product_name` and `product_attributes` then? 
I don't like the idea of creating product name in backend, because it forces consumer to either use provided format, or parse it on his own.
If not, can we at least provide field containing ProductVariant's ID?

**Comment by maarcingebala** [comment]
The idea behind `product_name` field was that any client wouldn't have to worry about manually assembling the simple representation of the ordered item. Why do you need to parse the provided name?

**Comment by patrys** [comment]
Consider an order that's been placed a year ago. There's no guarantee that the product (or variant) still exists. There's no guarantee that the price or name are representative of what was purchased two years ago.

As for constructing names in the client I really don't like the idea of the eventual invoice not matching contents of the order as two pieces of software disagree on how a product name is constructed. Product names/variant names should be considered simple strings for the purpose of display. I agree that we should consider saving the attributes but not for the purpose of reconstructing the variant name on the client side.

**Comment by dominik-zeglen** [comment]
@maarcingebala I'd like to create something like this:
<img width="313" alt="zrzut ekranu 2018-10-03 o 11 55 22" src="https://user-images.githubusercontent.com/6833443/46403842-e2480480-c703-11e8-8fd1-415ff1408b52.png">

**Comment by Pacu2** [comment]
I think it's not possible in our current data structure, as `product_name` is created from both, product's and variant's names. We should split it between `product_name` and `variant_name` for each orderline

**Comment by maarcingebala** [comment]
This will be required by [Order History view in the Storefront 2.0](https://github.com/mirumee/saleor-storefront/issues/259).

**Comment by patrys** [comment]
Please don't parse product names. This will become a nightmare if someone tries to localize how the variant name is constructed (think Chinese where everything might become a single string without spaces or parentheses).

**Comment by maarcingebala** [comment]
Currently we have the following fields in the `OrderLine` type:
- `productName: String!`
- `variantName: String!`
- `productSku: String!`
- `variant: ProductVariant`

I think it coveres all requirements mentioned here. `variant` is nullable and if it's not empty, it allows navigating to `product`.
