### ISSUE TITLE
Missing template for product attributes

### ISSUE THREAD

**Issue by acrive82** [mirumee/saleor#3024]
In the dashboard is present the menu link for the product attributes, but the reference template is missing under the directory _templates/dashboard/product/_***product_attribute***

[Screenshot](https://imgur.com/a/VYmxZAo)

**System information**
Operating system: Linux
Browser: Firefox

**Comment by Pacu2** [comment]
Thanks for reporting in, I've missed it in Attributes refactor in #2969

**Comment by NyanKiyoshi** [comment]
@pacu2 you can close this.
