### ISSUE TITLE
Odoo API Integration

### ISSUE THREAD

**Issue by alexander-sibert** [mirumee/saleor#3033]
Odoo ERP System (Hosted/Self-hosted and Open-Source solution) is based on Python and works with Hardware Barcode-Scanners, Banks, APIs for tax etc.

https://www.odoo.com/

It would be awesome to have a API in Core to this solution.

**Comment by EinsteinYang** [comment]
I am going to try to do such a integration

**Comment by SirRwema** [comment]
@EinsteinYang did you ever succeed ?

**Comment by rdewolff** [comment]
We are interested in using this as well.

**Comment by eduard-motesque** [comment]
We are also interested. Has someone tried to implement it yet? And have you been successful?

**Comment by Boquete** [comment]
Any update on it? Anyone tried integrating it?
@eduard-motesque @rdewolff @alexander-sibert  @EinsteinYang  @SirRwema

**Comment by acgray** [comment]
Also interested in this.  Has anyone had any luck?

**Comment by vladox** [comment]
Having development experience in Saleor & Odoo, I can say that's not a minor undertaking so keep your hopes low for a magic solution....
