### ISSUE TITLE
Error  build-assets: `webpack -p`

### ISSUE THREAD

**Issue by karimation** [mirumee/saleor#3041]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build-assets' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild-assets', 'build-assets', 'postbuild-assets' ]
5 info lifecycle saleor@0.0.0~prebuild-assets: saleor@0.0.0
6 silly lifecycle saleor@0.0.0~prebuild-assets: no script for prebuild-assets, continuing
7 info lifecycle saleor@0.0.0~build-assets: saleor@0.0.0
8 verbose lifecycle saleor@0.0.0~build-assets: unsafe-perm in lifecycle true
9 verbose lifecycle saleor@0.0.0~build-assets: PATH: /usr/share/npm/bin/node-gyp-bin:/home/pingo/Desktop/sensor2cloud/saleor/node_modules/.bin:/home/pingo/Downloads/google-cloud-sdk/bin:/home/pingo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle saleor@0.0.0~build-assets: CWD: /home/pingo/Desktop/sensor2cloud/saleor
11 silly lifecycle saleor@0.0.0~build-assets: Args: [ '-c', 'webpack -p' ]
12 silly lifecycle saleor@0.0.0~build-assets: Returned: code: 1  signal: null
13 info lifecycle saleor@0.0.0~build-assets: Failed to exec build-assets script
14 verbose stack Error: saleor@0.0.0 build-assets: `webpack -p`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid saleor@0.0.0
16 verbose cwd /home/pingo/Desktop/sensor2cloud/saleor
17 error Linux 4.15.0-36-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build-assets"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error saleor@0.0.0 build-assets: `webpack -p`
22 error Exit status 1
23 error Failed at the saleor@0.0.0 build-assets script 'webpack -p'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the saleor package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack -p
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs saleor
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls saleor
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by the-bionic** [comment]
Try updating your node/npm. I'd suggest this be added to the docs, as well.

**Comment by Pacu2** [comment]
Could you please upgrade to nodejs 10+ and check how it goes?

**Comment by Pacu2** [comment]
@the-bionic I think that all of the docs state, that one should use NodeJS 10 or newer

**Comment by the-bionic** [comment]
@Pacu2, alright. I've seen too many of this issue. I fell for it, too.

**Comment by karimation** [comment]
@the-bionic  you are right.

**Comment by Pacu2** [comment]
@karimation Is it resolved?

**Comment by karimation** [comment]
@Pacu2  yes.

**Comment by Pacu2** [comment]
Glad to see this resolved.

**Comment by yourtechcare** [comment]
Node Js 11 & npm 6 but still facing error while npm run build-assets

**Comment by yourtechcare** [comment]
![Saleor_NPM_Error](https://user-images.githubusercontent.com/16338809/54340240-f69e0f00-465c-11e9-9560-9a3c3d3eadb1.PNG)

**Comment by jxltom** [comment]
@yourtechcare This is just a warning. It should be fine.

**Comment by yourtechcare** [comment]
Is that RAM (MEMORY) needs to be higher than 2GB while installation ?
