### ISSUE TITLE
Django debug toolbar errors on 'python manage.py migrate' during installation

### ISSUE THREAD

**Issue by ProgrammingJoe** [mirumee/saleor#3042]
### What I'm trying to achieve
I was using the installation instructions for Linux here: https://saleor.readthedocs.io/en/latest/gettingstarted/installation-linux.html

I got stuck at step 7 `python manage.py migrate` with the errors

`ImportError: No module named 'debug_toolbar'`
and
`ImportError: No module named 'ddt_request_history'`

### Steps to reproduce the problem
1. Follow the steps here: https://saleor.readthedocs.io/en/latest/gettingstarted/installation-linux.html
2. Bug occurs when running `python manage.py migrate`

### What I expected to happen
No errors on install.

### Proposed Solution

Add
```
django-debug-toolbar==1.10.1
django-debug-toolbar-request-history==0.0.9
```
to the `requirements.txt`

**System information**
Operating system: Ubuntu 16.04

If you'd like, I can submit a pull request for this issue.

**Comment by Pacu2** [comment]
The problem is, we've moved both of the packages into the `requirements_dev.txt`, while they should stay inside of `requirements.txt`

**Comment by ProgrammingJoe** [comment]
Do you want them to be in `requirements_dev.txt` and `requirements.txt` or just `requirements.txt`.

Cool, I'll create a PR in a little while!

**Comment by Pacu2** [comment]
I think just the `requirements.txt` is fine

**Comment by jxltom** [comment]
Maybe just update the docs about ```pip install requirements_dev.txt``` if saleor needs running for development?

```requirements.txt``` needs to be installed for production server. Including dev packages may cause security and performance issues.

**Comment by jxltom** [comment]
@ProgrammingJoe Or you could just ```export DEBUG=False``` to enable production mode, which does not needs intalling ```requirements_dev.txt```. 😃

**Comment by ProgrammingJoe** [comment]
Yeah, good point actually. I'll adjust my PR to make that change to the docs and I'll revert the requirements change.

**Comment by patrys** [comment]
@jxltom @ProgrammingJoe Please move them to regular requirements. They _are_ imported by the codebase even if it depends on a specific environment variable. Dev dependencies should be stuff that never makes it to a server like the `ipython` console or some linting tools.
