### ISSUE TITLE
Order details page error: shippingAddress is null

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3051]
Order details page fails with error:

```
TypeError: shippingAddress is null
OrderCustomer.tsx:241
```

### Steps to reproduce the problem
1. Create an order through the storefront, adding a product that doesn't require shipping.
2. Go to the new dashboard and see details page of this order.

In the case above only billing address is available, but shipping address is `null` and is not required at all.

**Comment by patrys** [comment]
This should result in a new storybook entry.
