### ISSUE TITLE
Optimize updating variant names when attribute changes

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3053]
Function `saleor.graphql.product.utils.update_variants_names` is meant to update variant names e.g. when product attributes changes within a product type ( used for example in `productTypeUpdate` mutation). The problem is that if we have a lot of variants it gets terribly slow (I've tested with ~800 variants). We should think if we can optimize this function somehow, as it causes noticable lags in the new dashboard's product type management.

**Comment by patrys** [comment]
Should this become a Celery task?
