### ISSUE TITLE
Order completion, feedback, review, and ratings system

### ISSUE THREAD

**Issue by Rabia23** [mirumee/saleor#3058]
Can we track our order and give rating, review, and feedback on order?

**Comment by Pacu2** [comment]
That's not possible at this moment, however, there's a possibility to send an automated email with the tracking code to the customer, but it needs to be provided manually

**Comment by Rabia23** [comment]
@Pacu2 can you please guide me through the steps that how can we provide it manually?

**Comment by Pacu2** [comment]
On the dashboard, in the order section, you can add a tracking number while fulfilling the order

**Comment by Rabia23** [comment]
Thank you @Pacu2 :)
