### ISSUE TITLE
Two Sided Marketplace?

### ISSUE THREAD

**Issue by ctailo** [mirumee/saleor#3075]
Hello. Thanks so much for all of the work that you have all done with Saleor. I am relatively new to Django programming and am writing to respectfully ask if it is possible to modify Saleor for a two-sided marketplace. If so, I would greatly appreciate it if you could please shared advice with me about how to do this. Thank you.

**Comment by maarcingebala** [comment]
It's on our radar for 2019 to think how to add marketplace features to Saleor, but it's a big change and I can't give any estimates when would that happen. I'm closing the issue for now, since this is not a priority at the moment.
