### ISSUE TITLE
fix: replace COUNTRIES with countries.countries

### ISSUE THREAD

**Issue by neeraj1909** [mirumee/saleor#3077]
### What I'm trying to achieve
I was using your open source project to develop a store website. You have used the "django-countries" as a third party app.
Instead of importing COUNTRIES , we should import countries in the file "saleor/account/i18n.py".

### Steps to reproduce the problem
1. replace from django_countries.data import COUNTRIES by from django_countries import countries
2. replace for country in COUNTRIES.keys()  by for country in countries.keys()
3.replace COUNTRY_CHOICES = [(code, label) for code, label in COUNTRIES.items()......] by COUNTRY_CHOICES = [(code, label) for code, label in countries.items()
### What I expected to happen
While using the saleor in the project, I have to set the countries-limit to India only. For this I read the Django-Countries documentation to solve this issue. 
After reading the documentation, when I made the change in settings.py file, but there was no effect on the counties-list. Then I have to made changes in several files.
Then DRY concept came into my mind. After that I read the whole code of Django-Countries to solve this new issue.
I saw that you have imported COUNTRIES which is a bad idea if anyone have to do some modifications for their project.

### Screenshots

![1](https://user-images.githubusercontent.com/20766288/46650144-20886c80-cbb9-11e8-9330-3a5140ee58b5.png)
![2](https://user-images.githubusercontent.com/20766288/46650146-20886c80-cbb9-11e8-83b9-df5863acf1d1.png)
![3](https://user-images.githubusercontent.com/20766288/46650147-21210300-cbb9-11e8-860a-6f4c790aeb86.png)
![4](https://user-images.githubusercontent.com/20766288/46650148-21210300-cbb9-11e8-9eab-bf1d1cd22004.png)
![5](https://user-images.githubusercontent.com/20766288/46650149-21210300-cbb9-11e8-87a3-06c10658649c.png)
![6](https://user-images.githubusercontent.com/20766288/46650150-21b99980-cbb9-11e8-8054-94ed162f2814.png)

**System information**
Operating system: Linux(Bionic)
Browser: Google Crome
IDE: PyCharm

**Comment by neeraj1909** [comment]
I want to work on this issue. Please give the access rights.
![country_issue](https://user-images.githubusercontent.com/20766288/46651067-73afee80-cbbc-11e8-8b8f-468362acabab.png)

**Comment by Pacu2** [comment]
@neeraj1909 Glad that you want to pick it up. Please fork the Saleor, create a branch on your local fork and then open a pull request to mirumee/saleor's master.

**Comment by Pacu2** [comment]
So this problem persists only in places where we've imported `COUNTRIES` instead of `countries`. 
In such case, if one wants to modify the countries list by settings provided by the django-countries package (eg. `COUNTRIES_ONLY = ['NZ', 'AU']`), the countries' list is invalid.

**Comment by neeraj1909** [comment]
Yes, this problem persists only in places where we've imported
COUNTRIES instead
of countries.
I am creating the PR.

**Comment by Pacu2** [comment]
I think this was resolved in #3079
