### ISSUE TITLE
Facebook login - TypeError: 'username' is an invalid keyword argument for this function 

### ISSUE THREAD

**Issue by quarkpol** [mirumee/saleor#3085]
I'm trying to login thru facebook login, and I'm getting TypeError: 'username' is an invalid keyword argument for this function error. 

[Wed Oct 10 08:54:42.115137 2018] [wsgi:error] [pid 14689] ERROR django.request Internal Server Error: /complete/facebook/ [PID:14689:Dummy-1]
[Wed Oct 10 08:54:42.115272 2018] [wsgi:error] [pid 14689] Traceback (most recent call last):
[Wed Oct 10 08:54:42.115276 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
[Wed Oct 10 08:54:42.115279 2018] [wsgi:error] [pid 14689]     response = get_response(request)
[Wed Oct 10 08:54:42.115281 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
[Wed Oct 10 08:54:42.115283 2018] [wsgi:error] [pid 14689]     response = self.process_exception_by_middleware(e, request)
[Wed Oct 10 08:54:42.115285 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
[Wed Oct 10 08:54:42.115287 2018] [wsgi:error] [pid 14689]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Oct 10 08:54:42.115289 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
[Wed Oct 10 08:54:42.115291 2018] [wsgi:error] [pid 14689]     response = view_func(request, *args, **kwargs)
[Wed Oct 10 08:54:42.115293 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Wed Oct 10 08:54:42.115308 2018] [wsgi:error] [pid 14689]     return view_func(*args, **kwargs)
[Wed Oct 10 08:54:42.115310 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_django/utils.py", line 49, in wrapper
[Wed Oct 10 08:54:42.115312 2018] [wsgi:error] [pid 14689]     return func(request, backend, *args, **kwargs)
[Wed Oct 10 08:54:42.115314 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_django/views.py", line 33, in complete
[Wed Oct 10 08:54:42.115316 2018] [wsgi:error] [pid 14689]     *args, **kwargs)
[Wed Oct 10 08:54:42.115318 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_core/actions.py", line 41, in do_complete
[Wed Oct 10 08:54:42.115320 2018] [wsgi:error] [pid 14689]     user = backend.complete(user=user, *args, **kwargs)
[Wed Oct 10 08:54:42.115321 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_core/backends/base.py", line 40, in complete
[Wed Oct 10 08:54:42.115323 2018] [wsgi:error] [pid 14689]     return self.auth_complete(*args, **kwargs)
[Wed Oct 10 08:54:42.115325 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_core/utils.py", line 252, in wrapper
[Wed Oct 10 08:54:42.115327 2018] [wsgi:error] [pid 14689]     return func(*args, **kwargs)
[Wed Oct 10 08:54:42.115329 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_core/backends/facebook.py", line 111, in auth_complete
[Wed Oct 10 08:54:42.115330 2018] [wsgi:error] [pid 14689]     return self.do_auth(access_token, response, *args, **kwargs)
[Wed Oct 10 08:54:42.115332 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_core/backends/facebook.py", line 153, in do_auth
[Wed Oct 10 08:54:42.115334 2018] [wsgi:error] [pid 14689]     return self.strategy.authenticate(*args, **kwargs)
[Wed Oct 10 08:54:42.115336 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_django/strategy.py", line 107, in authenticate
[Wed Oct 10 08:54:42.115338 2018] [wsgi:error] [pid 14689]     return authenticate(*args, **kwargs)
[Wed Oct 10 08:54:42.115340 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 70, in authenticate
[Wed Oct 10 08:54:42.115342 2018] [wsgi:error] [pid 14689]     user = _authenticate_with_backend(backend, backend_path, request, credentials)
[Wed Oct 10 08:54:42.115343 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 115, in _authenticate_with_backend
[Wed Oct 10 08:54:42.115451 2018] [wsgi:error] [pid 14689]     return backend.authenticate(*args, **credentials)
[Wed Oct 10 08:54:42.115457 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_core/backends/base.py", line 80, in authenticate
[Wed Oct 10 08:54:42.115459 2018] [wsgi:error] [pid 14689]     return self.pipeline(pipeline, *args, **kwargs)
[Wed Oct 10 08:54:42.115461 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_core/backends/base.py", line 83, in pipeline
[Wed Oct 10 08:54:42.115463 2018] [wsgi:error] [pid 14689]     out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
[Wed Oct 10 08:54:42.115464 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_core/backends/base.py", line 113, in run_pipeline
[Wed Oct 10 08:54:42.115466 2018] [wsgi:error] [pid 14689]     result = func(*args, **out) or {}
[Wed Oct 10 08:54:42.115468 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_core/pipeline/user.py", line 75, in create_user
[Wed Oct 10 08:54:42.115475 2018] [wsgi:error] [pid 14689]     'user': strategy.create_user(**fields)
[Wed Oct 10 08:54:42.115477 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_core/strategy.py", line 53, in create_user
[Wed Oct 10 08:54:42.115479 2018] [wsgi:error] [pid 14689]     return self.storage.user.create_user(*args, **kwargs)
[Wed Oct 10 08:54:42.115480 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/social_django/storage.py", line 70, in create_user
[Wed Oct 10 08:54:42.115482 2018] [wsgi:error] [pid 14689]     user = cls.user_model().objects.create_user(*args, **kwargs)
[Wed Oct 10 08:54:42.115484 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/ampli-shop/saleor/userprofile/models.py", line 79, in create_user
[Wed Oct 10 08:54:42.115486 2018] [wsgi:error] [pid 14689]     **extra_fields)
[Wed Oct 10 08:54:42.115488 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/django/contrib/auth/base_user.py", line 68, in __init__
[Wed Oct 10 08:54:42.115490 2018] [wsgi:error] [pid 14689]     super(AbstractBaseUser, self).__init__(*args, **kwargs)
[Wed Oct 10 08:54:42.115491 2018] [wsgi:error] [pid 14689]   File "/home/invena/invena-sklep/venv/lib/python3.5/site-packages/django/db/models/base.py", line 573, in __init__
[Wed Oct 10 08:54:42.115493 2018] [wsgi:error] [pid 14689]     raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
[Wed Oct 10 08:54:42.115497 2018] [wsgi:error] [pid 14689] TypeError: 'username' is an invalid keyword argument for this function
[Wed Oct 10 08:54:42.115504 2018] [wsgi:error] [pid 14689]

**Comment by Pacu2** [comment]
What's the version of Saleor you're using? I think we have the similar case handled in Google Social Auth

**Comment by quarkpol** [comment]
Problem is, I can not, but thank you for help.

**Comment by Pacu2** [comment]
@quarkpol If you are using old version of saleor, please try adding this line https://github.com/mirumee/saleor/blob/master/saleor/account/models.py#L83
to your local instance, it should solve the problem.

**Comment by Pacu2** [comment]
Please reopen if you have further questions
