### ISSUE TITLE
Manually created facets

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#3088]
We're moving towards a model where product attributes belong to a single product type. This will likely break the automatically generated facets as some attributes like size or color could be repeated for multiple product types.

We could try to fix this by making the logic smarter however I propose that we instead make facets something that is explicitly defined by the store owner.

A facet would be a (translatable) name tied to a product field (from a predefined set of options), or a list of product attributes (not their values).

A facet option would be a (translatable) name tied to a list of product attribute values.

Examples:

| Facet name | Attribute(s) | Facet option name | Values
| ------ | ------ | ------ | ------
| Shoe size | Shoes: size, Trekking shoes: size | 44 | 43⅔, 44, 44⅓
| | | 45 | 44⅔, 45, 45⅓
| Screen size | TVs: screen size | 55"-59" | 55, 57, 57.4, 58, 59
| Top size | Shirts: size, Sweaters: size, Tees: size | XL | XL
| Price | product price | Under $100 | 0-100

What we gain by managing facets by hand:
* Control over which facets are available (filtering books based on the number of pages is useless)
* Control over the order of facets and values
* Ability to merge related values from different attributes (ie. propose size "M" when filtering by size "32")
* Ability to create named ranges or buckets instead of listing individual values
* Control over which values are available as options (example: only propose 10 currently trending book authors instead of a long phone book-like list of random names)

**Comment by wulaaf** [comment]
Anyone figure out a way to render repeated attributes only once?
