### ISSUE TITLE
shopDomainUpdate should return errors when empty strings given

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#3090]
### What I'm trying to achieve
To unset the shop's domain.

### Steps to reproduce the problem
1. Execute the following query:
```
mutation {
  shopDomainUpdate(input: {domain: ""}) {
    errors {
      field
      message
    }
    shop {
      domain {
        host
        url
      }
    }
  }
}
```
2. Notice that while domain was not updated, API returned no errors.

### What I expected to happen
To get an error.

**Comment by maarcingebala** [comment]
An empty domain would break some functionalities of Saleor such as generating URLs in emails. We rather shouldn't allow setting an empty value there.
