### ISSUE TITLE
Dockerfile installs dev dependencies

### ISSUE THREAD

**Issue by stephenmoloney** [mirumee/saleor#3110]
### What I'm trying to achieve

Have a production ready docker build

At the moment, pipenv installs dev dependencies which I presume 
are not required nor needed in production.

### What I expected to happen

Have a dockerfile suitable for production

Could be achieved in one of two ways:

1. Create a dedicated `Dockerfile.prod`

2. Add build-arg to the `Dockerfile` which will take different action for production builds - see https://github.com/mirumee/saleor/pull/3111. I've
create a PR for this option although is pipenv  suitable for production use?

Also, having `pipfile` and `requirements.txt` is a bit confusing, what is the purpose of the `requirements.txt` now that using `pipfile`?

**Comment by stephenmoloney** [comment]
ref #3117 and #3111

**Comment by maarcingebala** [comment]
Is this issue still valid? I see that both referenced issues are closed.

We have both `requirements.txt` and `pipfile` as we still kind of support both solutions. Personally, I still don't see many advantages of having `Pipenv`, it seems slower than `pip` and resolving dependencies in `pipfile` already caused some problems in few PRs. We had a small internal discussion whether not to drop it and return to good old `pip` 🙂 But no decision has been made yet.

**Comment by stephenmoloney** [comment]
Re `other issues`: I closed the other referenced issues as I think they were basically duplicates.
Re `pip vs pipenv`: I don't have any insights - not proficient enough in python to have an opinion.

This issue still stands which is that dev dependencies are being installed which is probably undesirable in a production context.
`RUN pipenv install --system --deploy --dev`

**Comment by maarcingebala** [comment]
As far as I remember we added this flag on purpose, as the build was failing without it, but don't remember what was the issue exactly.

**Comment by stephenmoloney** [comment]
I will probably look into this, I'll post back when I have more info.
