### ISSUE TITLE
Celery generates thumbnails in infinite loop

### ISSUE THREAD

**Issue by fowczarek** [mirumee/saleor#3114]
### What I'm trying to achieve
Run Saleor with Docker

### Steps to reproduce the problem
1. docker-compose build 
2. docker-compose run web python3 manage.py migrate
3. docker-compose run web python3 manage.py collectstatic
4. docker-compose run web python3 manage.py populatedb --createsuperuser
5. Celery generate thumbnails in infinite loop 

This doesn't happen every time. Cann't specify the conditions.

### Screenshots
![image](https://user-images.githubusercontent.com/43955230/46939549-d8f55b00-d066-11e8-94cd-5fc72b7cc8a9.png)

**System information**
Operating system: macOS High Sierra Version: 10.13.6

**Comment by patrys** [comment]
The problem is that docker-compose is set to restart all containers so unless you explicitly pass `--rm` to `docker run`, both the `populatedb` and the `collectstatic` commands will be executed over and over again.

**Comment by maarcingebala** [comment]
@patrys Can we fix that in Dockerfile or docker-compose config?

**Comment by patrys** [comment]
Yes, I'd suggest to start by dropping all [`restart: unless-stopped`](https://github.com/mirumee/saleor/blob/master/docker-compose.yml#L10) or at the very least change them to `restart: on-failure` .

**Comment by stephenmoloney** [comment]
The choices really are:

1. To set restart to `restart: "no"`

options:
```
restart: "no"
restart: always
restart: on-failure
restart: unless-stopped 
```

or

2. To document that `docker-compose run --rm web python3 manage.py migrate` instead of `docker-compose run web python3 manage.py migrate`

or 

3. To document

`docker-compose exec -ti web python3 manage.py migrate`

**Comment by patrys** [comment]
Note that we should always provide examples using `--rm` when using `docker-compose run` as skipping it will result in leftover junk even when restarting is disabled.

**Comment by maarcingebala** [comment]
This issue should be already resolved, using `--rm` has been documented.
