### ISSUE TITLE
Is there a /health/ path

### ISSUE THREAD

**Issue by stephenmoloney** [mirumee/saleor#3116]
### What I'm trying to achieve

I just want to know if there is a url like `/health/` and if there is any documentation about it.
I want to use such a url for a liveness and readiness probe in helm

**Comment by Pacu2** [comment]
I think just `/health/` will do

**Comment by patrys** [comment]
Indeed, [`/health/` is supported](https://github.com/mirumee/saleor/blob/cbc72d3417482d20ae9f64b61a0f8964e728e56b/saleor/wsgi/__init__.py#L28).

**Comment by stephenmoloney** [comment]
Ok, The liveness probes and readiness probes were failing with just `/health/` - they worked when I removed them. 

I'll try this again though, perhaps I had something wrong.

**Comment by stephenmoloney** [comment]
closing, I'm using this for k8s liveness and readiness probes 

https://github.com/stephenmoloney/saleor-helm/blob/master/deployment/helm/templates/django-deployment.yaml#L62-L69

**Comment by stephenmoloney** [comment]
@NyanKiyoshi  Neer noticed that before - that is handy - thanks.
