### ISSUE TITLE
Is Pgadmin4 import product possiable?

### ISSUE THREAD

**Issue by kirktsao** [mirumee/saleor#3119]
I'm looking for the method to import products data.i had try using pgadmin4 export a csv file as a template and add new products.it's always issue error when importing.is there any good way to solve this?

**Comment by Pacu2** [comment]
Hi @kirktsao, we have no ready-to-go solution, you could handle that by creating a dashboard section, where one can upload a .csv file to create products from. It could be handled asynchronously via the Celery task.

**Comment by kirktsao** [comment]
Thank you!I see.
