### ISSUE TITLE
Add a documentation sub domain to getsaleor.com

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#3121]
Hi,

I would think that adding a subdomain to `getsaleor.com` to accede the docs (`docs.getsaleor.com`) would really be handy instead of going to `saleor.readthedocs.io` ([documentation about custom domains](https://docs.readthedocs.io/en/latest/alternate_domains.html#subdomain-support)). Especially for people that don't know the RTD URL, that would try to append `docs` to the URL or want a quick access.

**Comment by patrys** [comment]
http://docs.getsaleor.com/ is now a thing 🎉
