### ISSUE TITLE
How to change translation?

### ISSUE THREAD

**Issue by quarkpol** [mirumee/saleor#3124]
Is there an easy way to change translation of the orange label? I've tried manualy change django.po file in locale/pl folder, and it didn't work. If it isn't place to ask this kind of questions I will cancel it.

![internation](https://user-images.githubusercontent.com/16999124/47013534-cbfc6880-d147-11e8-9a48-c33497f5a125.jpg)

**Comment by Pacu2** [comment]
@quarkpol Have you fired `compilemessages` after changing the translation files? I lives under `./manage.py compilemessages`

**Comment by quarkpol** [comment]
I've tried this localy on my machine and it works. I can't compile messages on production server. Is it enough if I copy just one pl folder with compiled messeges to server? Or I need to compile it on production server?

**Comment by maarcingebala** [comment]
Compiling them on a server shouldn't be necessary - compiled messages are stored in the repo, so if you make changes locally, compile the messages and push everything to your server, everything should work.

**Comment by quarkpol** [comment]
Thank you, it works.
