### ISSUE TITLE
How to update the model where id is not necessary? 

### ISSUE THREAD

**Issue by MilanRgm** [mirumee/saleor#3126]
I am trying to use its graphql based api but I have a doubt on the update part. I am not quite sure, so i am asking first on how you are handling the update part where id is not necessary? Like for updating the user profile, id is not necessary, we can get the requested user(info.context.user) and update the items.

Here is an example

```python
class Profile(models.Model):

    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='profile')
    # Introduction
    bio = models.TextField(blank=True, validators=[MaxLengthValidator(1000)],
                           help_text='No more than 1000 characters')
    website = models.URLField(blank=True)
    avatar = models.ImageField(null=True, blank=True,
                               upload_to=get_upload_file_name)
```

```python
class ProfileUpdate(ModelMutation):
    class Arguments:
       # id = graphene.ID(description='ID of address to update', required=True) # this is not necessary
        input = ProfileInput(
            description='Fields required to update profile', required=True)

    class Meta:
        description = 'Updates Profile'
        model = models.Profile
```

If i don't provide id, the update does not work, it works as a create view instead of update view. How should i handle such case?

**Comment by Pacu2** [comment]
Our mutations are based on our custom helpers, one is `ModelMutation`, where the other is `BaseMutation`. You can think of them as ModelForm and Form in Django (they are not twins, more like cousins, distant ones.) 

I think you might want to use `BaseMutation` in such case, and write a custom `mutate` method to handle your case.

**Comment by MilanRgm** [comment]
Thanks a lot for such quick reply. By custom mutate you mean to say something like this.

```python
class ProfileUpdate(BaseMutation):
    class Arguments:
        input = ProfileInput(description='Fields required to update profile', required=True)

    class Meta:
        description = 'Updates Profile'
        model = models.Profile

    @classmethod
    def mutate(cls, root, info, input):  
        if info.context.user.is_authenticated:
            profile = Profile.objects.get(user=info.context.user)
            profile.name = input.get('name', None)
            profile.email = input.get('email', None)
            profile.phone_number = input.get('phone_number', None)
            profile.save()
            return ProfileUpdate(profile=profile)
```

**Comment by MilanRgm** [comment]
Thanks a lot. I am closing this then.

**Comment by MilanRgm** [comment]
I passed the user's ID, i got the error AssertionError('Must receive a ProfileNode id.'). 

```python
class UpdateProfile(ModelMutation):

    class Arguments:
        id = graphene.ID(description="ID to update the user profile", required=True)
        input = ProfileInput(description="These fields are required", required=True)

    class Meta:
        description = 'Updates a new Profile.'
        model = Profile

```

**Comment by Pacu2** [comment]
Right, that was my misunderstanding, as in Saleor we are using the User instead of Profile. 
ModelMutation takes an ID of given model (Profile in your case)
