### ISSUE TITLE
VariantPicker broken

### ISSUE THREAD

**Issue by carstenblt** [mirumee/saleor#3127]
The VariantPicker does not show anymore for products with multiple variants. The element doesn't get rendered and the picker and the add-to-cart button don't show.

Completly fresh install, commit afce249.

There is no specific error showing, however this looks new in the JS console: (shows on every page, not just one with a variantpicker)

```
Uncaught TypeError: Cannot read property 'unstable_cancelScheduledWork' of undefined
    at storefront.js:formatted:19083
    at Object.31 (storefront.js:formatted:24354)
    at n (storefront.js:formatted:11)
    at Object.<anonymous> (storefront.js:formatted:3831)
    at Object.1379 (storefront.js:formatted:3863)
    at n (storefront.js:formatted:11)
    at Object.1364 (storefront.js:formatted:877)
    at n (storefront.js:formatted:11)
    at 0 (storefront.js:formatted:71)
    at storefront.js:formatted:72
```

**Comment by maarcingebala** [comment]
So far I discovered that importing `ReactDOM` causes this error. We [upgraded it's version recently](https://github.com/mirumee/saleor/commit/b35c0f749ecfe475b094d56ea2518a0f470792ac), maybe some other package should be updated as well as they're not compatible at the moment?

**Comment by dominik-zeglen** [comment]
It appears that the UMD version of `ReactDOM` is broken since `CommonJS` is working perfectly. I'll post a fix in a few minutes.
