### ISSUE TITLE
Performance measurement

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#313]
We should write some scenarios for instance in [locust]( http://locust.io/) and test theirs performance.
We should start with:
* [x] fully loaded with content product page,
* [x] basket addition,
* [ ] checkout.

**Comment by patrys** [comment]
![zrzut ekranu z 2015-07-31 17-08-50](https://cloud.githubusercontent.com/assets/81205/9010386/e944734e-37a6-11e5-9d9b-c918ed2aa961.png)

Does not include checkout but at any realistic conversion rate it would not affect the results much.
