### ISSUE TITLE
Using of wrong Money constructor on displaying order info in dashboard

### ISSUE THREAD

**Issue by kirillmakhonin** [mirumee/saleor#3130]
### What I'm trying to achieve
I've tried to add refunds / captures (using dummy provider's preauth. payment)

### Steps to reproduce the problem
1. Create payment using dummy provider
2. Preauth. payment
3. Make payment refunds and captures in dashboard
4. Open order in dashboard

### What I expected to happen
I expected to see order page in dashboard, but I've got `conversion from dict to Decimal is not supported` on order's page
I guess the root of the problem is (from Django debugger information):
Line: `/app/saleor/order/__init__.py : 134-135` in display_order_event

Code:
```
amount = Money(
            amount=params['amount'], currency=settings.DEFAULT_CURRENCY) 
```

Local vars:
```
event_type | 'captured'
order_event | OrderEvent(type='captured', user=<User: ***@***>)
params | {'amount': {'_type': 'Money', 'amount': '500', 'currency': 'USD'}}
```

Possible solution:
```
amount = Money(
            amount=params['amount']['amount'], currency=params['amount']['currency']) 
```

**System information**
Operating system: ubuntu 16.04
Browser: chrome

**Comment by Pacu2** [comment]
Right, Money serialization changed to the dictionary at some point and this function was not adjusted. It's tested, but params could be json dumped and loaded again instead of hardcoding them.
