### ISSUE TITLE
Support image upload with dropzone in Dashboard 2.0

### ISSUE THREAD

**Issue by SanskarSans** [mirumee/saleor#3133]
I am using dropzone for uploading the product images. I am not sure what to pass so I passed whole File object but I am getting error `unhashable type: 'list'`. This is what I provided 

<img width="500" alt="screen shot 2018-10-18 at 7 25 38 pm" src="https://user-images.githubusercontent.com/23137016/47158778-14fd1a00-d30c-11e8-8331-1f378145a7fc.png">

my mutation is 

```javascript
const ProductImage = gql`
  mutation productImageMutation(
    $image: Upload!
  ) {
    productImage(
      input: {
        image: $image
      }
    ) {
      success
    }
  }
`;
```

I could not figure out the way to upload image when using javascript in client side. Can anyone help me at this, please?

**Comment by maarcingebala** [comment]
Dropzone is currently not supported in the new Dashboard, but file upload does work. You may want to take a look [at this code](https://github.com/mirumee/saleor/blob/master/saleor/static/dashboard-next/collections/views/CollectionDetails.tsx#L248) and track how `onImageUpload` function works.

**Comment by maarcingebala** [comment]
We should add dropzone support in the Dashboard 2.0, I'll keep this issue and just change the title respectively.
