### ISSUE TITLE
Getting error when try to run webpack in watch mode.

### ISSUE THREAD

**Issue by quarkpol** [mirumee/saleor#3152]
I am getting error when try to run webpack in watch mode.

'UV_THREADPOOL_SIZE' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor@0.0.0 start: `UV_THREADPOOL_SIZE=8 node ./node_modules/webpack/bin/webpack.js -d --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the saleor@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mrokicki\AppData\Roaming\npm-cache\_logs\2018-10-22T07_13_27_415Z-debug.log

**Comment by maarcingebala** [comment]
Hey, what Node version do you have? Make sure that you're running Node > 10.x. (I'm using 10.11.0 with latest `master` and everything works well).

**Comment by harshpanchal-hp** [comment]
Getting Same thing with node 10.13
[npm.log](https://github.com/mirumee/saleor/files/2539082/npm.log)

**Comment by maarcingebala** [comment]
To make it clear - you're running `npm start` and get this error? What version of Saleor are you using? I'm looking at the current `package.json` and the in `start` command `UV_THREADPOOL_SIZE` variable isn't used (I remember it was a long time ago).

**Comment by maarcingebala** [comment]
Please reopen the issue if it still occurs.
