### ISSUE TITLE
How to make phone number field required?

### ISSUE THREAD

**Issue by quarkpol** [mirumee/saleor#3164]
I am trying to make phone number field required when adding shipping address. I can't find a place where required property is set up. Can anybody help?

**Comment by Pacu2** [comment]
How about making it required in the `AddressForm`'s `__init__` method? Would that work?

**Comment by quarkpol** [comment]
Thank you. I've found it in i18n.py file (still don't understand how saleor generates shipping address form). I have one more problem, The phone field changes red, but the message: "this field is required" doesn't appear. Maybe some hints on that?

**Comment by Pacu2** [comment]
Tbh I don't know the reason why it's set as display:none, tried looking for the CSS class but it looks like it's not coming from Saleor's code.
