### ISSUE TITLE
Using Saleor on DIGITAL ocean

### ISSUE THREAD

**Issue by lehnerv** [mirumee/saleor#3171]
Hello

Sorry for that basic question, but can i deploy you solution on VPS (Digital Ocean) Centos server ? I have checked the documentation but i found instruction only development not for production environment.

Thanks

Viktor

**Comment by NyanKiyoshi** [comment]
Hello,

Saleor is production ready and used in production. It can be installed and used on any cloud provider you want, Digital Ocean, AWS, OVH, ...

**Comment by lehnerv** [comment]
Thanks, finally i have managed the deployment ,but it was a challenge for me. For example if you choose a digital ocean server you should select minimum 2 GB RAM. Otherwise it is a very nice app, so i want to give back something, and i started to translate to Hungarian.
