### ISSUE TITLE
LANGUAGE_CODE = 'en', but default language is no English but Chinese

### ISSUE THREAD

**Issue by elsagong** [mirumee/saleor#3179]
### What I'm trying to achieve
When user opens the website on a new device, the default language is (en)English, not (zh-hans)Chinese.

### Steps to reproduce the problem
LANGUAGE_CODE = 'en' was set in settings, but when new user open the website, the default language is Chinese, not English.

### What I expected to happen
I would like to let `en`(English) as the default language.
Thank you so much for any advice~

**System information**
Operating system: Mac OSX/ iPhone ios
Browser: Chrome/Safari

**Comment by ajostergaard** [comment]
Does the browser have a language preference set? If so, that will be respected if Saleor has that same language enabled in `settings.LANGUAGES`.
