### ISSUE TITLE
Query logged in user (self) on GraphQL API

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#3185]
### What I'm trying to achieve
Query the API for information on the currently logged in customer. Currently, only staff are allowed to query information on users. Customers should at least be able to query their own information.

### Describe a proposed solution
Allow customers to query their own profile information.

### Other solutions I've tried and won't work
This is possible using the `tokenVerify` mutation, but using a mutation to query information isn't convenient. It cannot be used with relay's `QueryRenderer` for example.

**Comment by the-bionic** [comment]
I think it's possible to retrieve a user's information if a valid token is provided.

**Comment by khalibloo** [comment]
That only works for me if the token is for an admin user. With a customer token, I get an error saying I do not have permission to perform the action.

**Comment by khalibloo** [comment]
Looking at the code in https://github.com/mirumee/saleor/blob/master/saleor/graphql/api.py
```
    @permission_required('account.manage_users')
    def resolve_user(self, info, id):
        return graphene.Node.get_node_from_global_id(info, id, User)

    @permission_required('account.manage_users')
    def resolve_customers(self, info, query=None, **kwargs):
        return resolve_customers(info, query=query)

    @permission_required('account.manage_staff')
    def resolve_staff_users(self, info, query=None, **kwargs):
        return resolve_staff_users(info, query=query)
```
Yeah, the queries require admin permissions

**Comment by khalibloo** [comment]
It would seem the `addressCreate` mutation and possibly other address management mutations only allow staff access as well.
```
    @classmethod
    def user_is_allowed(cls, user, input):
        return user.has_perm('account.manage_users')
```
Since the user model itself lacks some fields I need in my use case (name, phone), I've found it convenient to use the first address instance to store those information. It seems reasonable to me that the user should be able to update their address as well.

**Comment by maarcingebala** [comment]
Hey @khalibloo, thanks for reporting those problems! You're right - user-related mutations and queries require staff permissions as we wrote them with Dashboard 2.0 in mind. Of course, this should be changed as you suggest - authenticated customers should be able to fetch their account data with `user(id:"")` query as well as to modify their addresses.

**Comment by khalibloo** [comment]
Managing customer addresses (other than `defaultShippingAddress` and `defaultBillingAddress`) still require admin permissions. Is this by design? Otherwise, I'd expect mutations like `addressCreate`, `addressUpdate` and `addressDelete` to be accessible to the logged in user.

**Comment by maarcingebala** [comment]
Right, we're still missing it. I'll open a new issue for that.
