### ISSUE TITLE
Redirect super user to dashboard

### ISSUE THREAD

**Issue by emz6039** [mirumee/saleor#3190]
Hello, I'm trying to redirect a superuser to dashboard after login instead of the home page can anyone help me?

**Comment by ajostergaard** [comment]
As far as I can tell this is not a feature of Saleor today. Are you looking for advice on how you might go about adding the feature?

**Comment by emz6039** [comment]
Yes, Im looking for advice on how I might go about adding this feature to saleor.

**Comment by ajostergaard** [comment]
You'd need to monkey patch the LoginView used here: https://github.com/mirumee/saleor/blob/7fa04dbb3e79532124494323fdcbc54c41166425/saleor/account/views.py#L25

You need to override `get_success_url` to do your bidding. The original is https://github.com/django/django/blob/a906c9898284a9aecb5f48bdc534e9c1273864a6/django/contrib/auth/views.py#L63

There may be more to it than that but I don't think so.

Might be worth checking with mirumee that they would accept a PR as they may not be interested. Also worth considering that Storefront 2.0 is on the horizon... So perhaps wait and see how that pans out before doing anything.

**Comment by ajostergaard** [comment]
You'll want to monkey patch `LoginView` used here: https://github.com/mirumee/saleor/blob/7fa04dbb3e79532124494323fdcbc54c41166425/saleor/account/views.py#L25

Probably by overriding `get_success_url` - original here:
https://github.com/django/django/blob/a906c9898284a9aecb5f48bdc534e9c1273864a6/django/contrib/auth/views.py#L63

Don't forget Storefront 2.0 is around the corner so unless critical to you it might be worth waiting to see what that looks like before attempting to customise. Also worth getting feedback from Mirumee as to whether they'll accept a PR as they may not be interested (which would be fine just need to include managing your customisation in your plans).
