### ISSUE TITLE
operational Error 

### ISSUE THREAD

**Issue by manish211215** [mirumee/saleor#3193]
when i was installing the saleor project in my windows 10 than i have a issue with " python manage.py  migrate " command on my powershell , please give me the right solution . thanks 
the powershell text are as follows -
File "F:\myprojects\lib\site-packages\psycopg2\__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "saleor"

**Comment by Pacu2** [comment]
Looks like an incorrect setup of the database, have you followed the installation steps in the docs?

**Comment by manish211215** [comment]
yes i created the database manually  going through pgadmin with name saleor

**Comment by Pacu2** [comment]
Have you created the user as well?

**Comment by manish211215** [comment]
how to create user on  database

**Comment by manish211215** [comment]
please clarify sir

**Comment by manish211215** [comment]
sir  could  you please give me the solution of this problem ?

**Comment by Pacu2** [comment]
In Windows Installation docs, point 5 is about creating the user for the database, please check it out. 
Docs can be found at https://readthedocs.org/projects/saleor/

**Comment by manish211215** [comment]
thanks i got it

**Comment by manish211215** [comment]
but when i run command in powershell ' npm install ' then it stuck here as below in image , so my question is is npm installed or not , please give me reply asap . thanks
![npm](https://user-images.githubusercontent.com/37300125/47731983-491cf700-dc8b-11e8-828c-2b23b4a1e087.png)

**Comment by manish211215** [comment]
and further when i run all commands and finally run 'python manage.py runserver' and open in my browser than i got this error as below -
    for entry in os.listdir(path):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\myprojects\\saleor\\saleor\\static\\assets'

**Comment by manish211215** [comment]
please help me sir i am stuck with it

**Comment by manish211215** [comment]
Sir please help asap .

**Comment by manish211215** [comment]
sir please help what should i do now ??

**Comment by manish211215** [comment]
i am stuck very badly

**Comment by patrys** [comment]
Hey, would you mind joining the Gitter chat at https://gitter.im/mirumee/saleor and asking there? This will be much easier to debug if you could talk to someone in real time.

**Comment by manish211215** [comment]
okk sir
