### ISSUE TITLE
Add mutation to use voucher in checkout.

### ISSUE THREAD

**Issue by IFLead** [mirumee/saleor#3222]
### What I'm trying to achieve
I am trying to add voucher to the cart with help of graphql

### Describe a proposed solution
Add mutation to the graphql api

### Other solutions I've tried and won't work
…

### Screenshots or mockups
...

**Comment by Pacu2** [comment]
Please note: voucher should be validated on each step that Cart content changes.

Eg. shipping voucher might be valid only on shippment to certain countries, so we should handle that on shipping address change.

Some orders can be valid but only for orders over certain amount, so we should check if voucher is still valid on cart's items change (add/delete/change the quantity)

**Comment by maarcingebala** [comment]
Indeed I don't see any option to add a voucher to checkout in API. I guess we should add a new mutation for that purpose. E.g.:

```checkoutUpdateVoucher(checkoutId: ID!, voucherCode: String)```

where `voucherCode` is the unique code of the voucher. Passing a `null` code would result in removing the voucher from checkout.
