### ISSUE TITLE
facebook oauth login exception

### ISSUE THREAD

**Issue by o1lo01ol1o** [mirumee/saleor#323]
I'm running into an exception using the FacebookClient oauth class as it is currently implemented in saleor.  I've set up the app access on facebook and using the facebook authenticate method from /login/ correctly produces the facebook dialogue requesting permission. However, the response isn't what's expected:  

`Django Version:	1.8.3`
`Exception Type:	KeyError`
`Exception Value:	`
`'verified'`
`Exception Location:	[..]/saleor/registration/utils.py in get_user_info, line 186`

I've gone through the code and I can't tell if the facebook API has changed or if there's some misconfiguration on the facebook side.

The request URL that facebook returns is:

`Request URL:	http://localhost:5000/account/oauth_callback/facebook/?code=AQCDRZbizgMZ6bMjcUwk5_yRsvW4Ix10hrJsuqpJ_Ce5PVjoXyOpnBG27jSijFCD6kascY0NbhtSA3t1oQWyAjNwRser48t6oAQGxr-P7a_toXE-a96ctooe7BQ0vb_1_er5CVCa3E10w_rFQn-OkGgHpNPdrgMhe-XtRKrIx5kyEdUAP_dw1ndg3PBd3mxrvDU1W35ntqIZCZ_fNHM4Vj8pH-eONj6VljH9HTzZELpzJuRi81sklVnrr-K8Z0OnLksmf4erzixyIEhPBs_C2n_f4Shx_DDjfHvzKO-f5RkhgXq3mMw4LgEBZmlN0HM2AdU`

Can someone advise on how I might rectify this?  Thanks.

**Comment by patrys** [comment]
Thanks, @paweltin will look into this shortly.

**Comment by o1lo01ol1o** [comment]
I'm not sure if this commit was considered sufficient, but the `response` object doesn't pass the conditional check.  In my case, here's what `response` in line 186 names:  
`{u'name': u'Dummy Name', u'id': u'10102280833422211'}`

**Comment by bogdal** [comment]
@o1lo01ol1o This was fixed in https://github.com/paweltin/saleor/commit/2fc112c055186b9cdacae69e858919819fc08b32. The latest facebook api returns only `name` and `id` fields by default.

**Comment by o1lo01ol1o** [comment]
@bogdal Sweet, thanks!
