### ISSUE TITLE
Unable to add Attribute to multiple ProductTypes

### ISSUE THREAD

**Issue by t3c404** [mirumee/saleor#3231]
### What I'm trying to achieve
Add one attribute to multiple product types

### Steps to reproduce the problem
1. Create attribute "colour"
2. Create product type "Vases"
3. Create another product type "Tablecloths"
4. Add colour to Vases --> works
5. Add colour to Tablecloths --> doesn't work 

### What I expected to happen
Add the attribute "colour" to product type "Vases" and "Tablecloths"

**Comment by Pacu2** [comment]
That's a feature
