### ISSUE TITLE
Anonymize data produced by populatedb on demo

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3244]
As described in issue [#110](https://github.com/mirumee/saleor-storefront/issues/110) in Saleor Storefront repo - we should anonymize data produced by `populatedb` script to avoid confusion that we may be exposing personal data. This should be implemented only in `demo` branch.

**Comment by maarcingebala** [comment]
Resolved via #3246

**Comment by Pacu2** [comment]
Are Orders/Addresses created via the GraphQL API anonymized as well? I think that was my main concern in Saleor Storefront's issue.

**Comment by maarcingebala** [comment]
The mutation that creates orders uses `create_order` function underneath, the same the old storefront does. On `demo` branch this function anonymizes user's data after an order is created.
