### ISSUE TITLE
Having saleor automatically enabling payment gateways if configured

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#3250]
### What I'm trying to achieve
Configure braintree API keys, using environment variables and then, automatically having it enabled without changing anything in `settings.py`. 

### Describe a proposed solution
Check if a API key was set, if it is, add it to the valid payment gateways in `settings.py` (`CHECKOUT_PAYMENT_GATEWAYS`).

### Other solutions I've tried and won't work
Adding manually each payment gateway that I configured, which makes me change the source code and, thus, would create conflicts.

----

*Note: this is a temporary solution until we fully implement payment configuration from the dashboard 2.0.*

**Comment by NyanKiyoshi** [comment]
If this is good as is, please assign me.

**Comment by patrys** [comment]
I would like to get rid of `CHECKOUT_PAYMENT_GATEWAYS` as a Django setting. This should be constructed when needed based based on what is configured and enabled.

**Comment by NyanKiyoshi** [comment]
Sounds good to me.

You do well of raising that point. I was thinking about `CHECKOUT_PAYMENT_GATEWAYS` being empty by default, then having a flag set through a variable environment, where `USE_DUMMY_PROVIDER = DEBUG`. If the value is `True`, it adds the dummy provider to the checkout gateways.

**Comment by patrys** [comment]
What if we iterated over `PAYMENT_GATEWAYS` and asked each endpoint whether it was enabled passing it the site config and the currency? Then the dummy payment could say it was on if debug was on and Braintree could say it was on if we had API keys in place. I imagine the Razor Pay backend could say it was enabled only if the currency was INR and so on.

**Comment by NyanKiyoshi** [comment]
We could define a function `is_available_for(payment)` in the gateway's module as you say. Thus we would make the payment API able to handle a multiple-currency shop.

Then, over the GraphQL API, we could have a field that does the same job when we fetch the gateways (we don't have a GraphQL API to fetch gateways yet, looks like?). So, depending on how we want to implement the gateway fetching, we could whether set a set of rules or return a list of supported gateways from a payment ID.

**Comment by arlejeun** [comment]
Do we have any update on this point? Since we moved away from django-payments, I can no longer checkout successfully. 
I'm stuck with order details. Can you please advice?

![image](https://user-images.githubusercontent.com/4977163/49094426-db350280-f22b-11e8-96bc-845c4ed53bab.png)

**Comment by NyanKiyoshi** [comment]
@arlejeun seems like your order is already paid.

On a side note, it reminds me that I don't think that adding and enabling gateways is documented. I could probably add it here: http://docs.getsaleor.com/en/latest/gettingstarted/configuration.html for now; while waiting for a proper/ decent solution.

**Comment by NyanKiyoshi** [comment]
@arlejeun if your question was also about on how to enable payment gateways:

```patch
Index: docs/gettingstarted/configuration.rst
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- docs/gettingstarted/configuration.rst	(revision 18a71626df701a190e82946e58702a396a1c02d0)
+++ docs/gettingstarted/configuration.rst	(date 1543336352000)
@@ -6,6 +6,30 @@
 We are fans of the `12factor <https://12factor.net/>`_ approach and portable code so you can configure most of Saleor using just environment variables.
 
 
+Payment gateways
+----------------
+
+``CHECKOUT_PAYMENT_GATEWAYS``
+  This contains the list of enabled payment gateways, with the payment friendly name
+  to show to the user on the payment selection form.
+
+  For example, to add braintree to the enabled gateways,
+  you can do the following:
+
+  .. code-block:: python
+
+    CHECKOUT_PAYMENT_GATEWAYS = {
+        DUMMY: pgettext_lazy('Payment method name', 'Dummy gateway'),
+        BRAINTREE: pgettext_lazy('Payment method name', 'Brain tree')
+    }
+
+  The supported payment providers are:
+
+  - ``DUMMY`` (for tests purposes only!);
+  - ``BRAINTREE``;
+  - ``RAZORPAY``.
+
+
 Environment variables
 ---------------------
 
```

**Comment by arlejeun** [comment]
Thanks for the update @NyanKiyoshi!
You're right.. the order is paid and I click on 'Make Payment' but it is no longer redirecting me to the checkout with success page
/en/order/a7c1b475-5f5f-4f32-aaba-d54de308a7a5/checkout-success/

Please help appreciated!




















































































































































































































































![image](https://user-images.githubusercontent.com/4977163/49097057-9b711980-f231-11e8-8045-d80a6acaf7ff.png)

**Comment by NyanKiyoshi** [comment]
It is now a feature.
