### ISSUE TITLE
Multi Vendor

### ISSUE THREAD

**Issue by scroogeT** [mirumee/saleor#3252]
### What I'm trying to achieve
Hello there I like Saleor a lot especially GDPR compliance & graphQL, it helped me a lot with my previous project.

I wanted to know, whats the status with the multi tenant/ multi-vendor option ? I want a storefront where I can add vendors who can sell on my site in the same way as Amazon or Ebay.

**Comment by Pacu2** [comment]
Hi @scroogeT, unfortunately, the multi-tenant option is not currently on our roadmap. I believe that Saleor can be used as a solid base in such case, as several modules could be reused, but that would still require some manual tweaking.

**Comment by maarcingebala** [comment]
Thanks for the issue @scroogeT! We are aware of anticipation for this feature and we want to put it on our roadmap for 2019. However, I cannot yet promise when we'll start working on it, as it will probably require rebuilding a lot of internal stuff in Saleor. I would advise following our blog for more information on our plans for future releases.
