### ISSUE TITLE
ProductImage  GraphQL type should contain alt_text

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#3257]
We should expose the `alt` (text) on `ProductImage` type and all relevant types (eg. `Product` contains `thumbnail_url`). 

All images on the storefront should contain an alt text for accessibility & SEO reasons.

**Comment by maarcingebala** [comment]
- [ ] update `thumbnailUrl` field to use `ProductImage` type
- [ ] add `background_image_alt` text field to `Collection` and `Category` models and expose it in API (queries and mutations)
- [ ] add `alt` text field in the `Image` type
