### ISSUE TITLE
Webpage Error at first level

### ISSUE THREAD

**Issue by raviprakash007** [mirumee/saleor#3259]
### What I'm trying to achieve
I have done setup for saleor on Google Cloud Centos7 linux instance. I followed all instructions for installation of saleor  from https://docs.getsaleor.com/en/latest/gettingstarted/installation-linux.html. 
Now I run the server on console.

(saleorenv) [bete-2@e-commerce saleor]$ sudo python3.6 manage.py runserver 0.0.0.0:80
Performing system checks...

System check identified no issues (0 silenced).
November 09, 2018 - 02:00:49
Django version 2.1.3, using settings 'saleor.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.

### Steps to reproduce the problem
1. open www.jakheera.com 
2. you can see 

Request Method: | GET
-- | --
http://www.jakheera.com/en/
2.1.3
**RelatedObjectDoesNotExist**
**Site has no settings.**
/usr/lib64/python3.6/site-packages/django/db/models/fields/related_descriptors.py in __get__, line 414
/bin/python3.6
3.6.5
['/home/simpy.sri/saleor/saleor',  '/usr/lib64/python36.zip',  '/usr/lib64/python3.6',  '/usr/lib64/python3.6/lib-dynload',  '/usr/lib64/python3.6/site-packages',  '/usr/lib/python3.6/site-packages',  '/home/simpy.sri/saleor/saleor']
Fri, 9 Nov 2018 02:00:59 -0600

 

### What I expected to happen
… Default Home page

### Screenshots

 **pls visit www.jakheera.com for viewing the bug.**

**System information**
Operating system: CentOS7
Browser: Chrome 67

**Comment by RaviDon** [comment]
Yes

$sudo Python3.6 manage.py migrate

**Comment by raviprakash007** [comment]
Yes, I have used all the steps mentioned in installation documents and PGSQL shows 68 rows for tables in the database.

Again, I deleted database from pgsql and re-applied all migrations , but same issue.

**Comment by raviprakash007** [comment]
(saleorenv) [beta-2@e-commerce saleor]$ sudo python3.6 manage.py migrate
Operations to perform:
  Apply all migrations: account, auth, checkout, contenttypes, discount, django_celery_results, django_prices_openexchangerates, django_prices_vatlayer, impersonate, menu, order, page, payment, product, sessions, shipping, site, sites, social_django
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying account.0001_initial... OK
  Applying shipping.0001_initial... OK
  Applying product.0001_initial... OK
  Applying checkout.0001_initial... OK
  Applying discount.0001_initial... OK
  Applying django_celery_results.0001_initial... OK
  Applying django_prices_openexchangerates.0001_initial... OK
  Applying django_prices_openexchangerates.0002_auto_20160329_0702... OK
  Applying django_prices_openexchangerates.0003_auto_20161018_0707... OK
  Applying django_prices_openexchangerates.0004_auto_20170316_0944... OK
  Applying django_prices_vatlayer.0001_initial... OK
  Applying django_prices_vatlayer.0002_ratetypes... OK
  Applying django_prices_vatlayer.0003_auto_20180316_1053... OK
  Applying impersonate.0001_initial... OK
  Applying page.0001_initial... OK
  Applying menu.0001_initial... OK
  Applying order.0001_initial... OK
  Applying payment.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying site.0001_initial... OK
  Applying social_django.0001_initial... OK
  Applying social_django.0002_add_related_name... OK
  Applying social_django.0003_alter_email_max_length... OK
  Applying social_django.0004_auto_20160423_0400... OK
  Applying social_django.0005_auto_20160727_2333... OK
  Applying social_django.0006_partial... OK
  Applying social_django.0007_code_timestamp... OK
  Applying social_django.0008_partial_timestamp... OK
(saleorenv) [beta-2@e-commerce saleor]$ sudo python3.6 manage.py runserver 0.0.0.0:80
(saleorenv) [beta-2@e-commerce saleor]$ sudo python3.6 manage.py runserver 0.0.0.0:80
Performing system checks...

System check identified no issues (0 silenced).
November 09, 2018 - 02:18:15
Django version 2.1.3, using settings 'saleor.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
ERROR django.request Internal Server Error: /en/ [PID:10335:Thread-3]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/simpy.sri/saleor/saleor/saleor/core/views.py", line 17, in home
    request.site.settings.homepage_collection)[:8]
  File "/usr/lib64/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 414, in __get__
    self.related.get_accessor_name()
django.contrib.sites.models.Site.settings.RelatedObjectDoesNotExist: Site has no settings.
ERROR django.request Internal Server Error: /en/ [PID:10335:Thread-3]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/simpy.sri/saleor/saleor/saleor/core/views.py", line 17, in home
    request.site.settings.homepage_collection)[:8]
  File "/usr/lib64/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 414, in __get__
    self.related.get_accessor_name()
django.contrib.sites.models.Site.settings.RelatedObjectDoesNotExist: Site has no settings.

**Comment by Pacu2** [comment]
It seems like you've deleted all of the Saleor's migrations and recreated them from scratch, what's the reason? It won't work this way. If you want to minimize the number of migrations, you should squash them instead.

**Comment by raviprakash007** [comment]
Should I re-install Saleor from scratch?

**Comment by Pacu2** [comment]
You should include all the migrations that came originally with Saleor. It might be necessary to drop the database and reapply all of them.

**Comment by raviprakash007** [comment]
Yeah, Its working now , Thanks @Pacu2  for your timely response. It saved my hours.

**Comment by Pacu2** [comment]
Glad to see this resolved
