### ISSUE TITLE
Saleor 2.0 and docs

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#3261]
Hi,

I was wondering if there was any plan into updating the docs as Saleor 2.0 was updated.

First of all: the [logo](https://github.com/mirumee/saleor/blob/master/docs/logo.svg).

Then, maybe adding a bit of CSS to remove the hard blue with something else, same with the dark area if needed.

Is there any other change we should/ could do to make the docs fit with the 2.0 or anything planned?

**Comment by Pacu2** [comment]
Sure, docs styling should be adjusted accordingly, we've discussed this internally, but not sure if we already have a vision on how we want them to look like, as we wanted to do something more than just a simple color change. Sphinx gives us lots of possibilities in here.

**Comment by patrys** [comment]
Yes, we're definitely planning a larger docs overhaul. Saleor's lead, @maarcingebala, is still in SF after attending the GraphQL Summit so expect the pace to pick up again next week.

**Comment by NyanKiyoshi** [comment]
Alright, thanks for the info! Sounds great.
I will close this as it's already something that is planned.
