### ISSUE TITLE
Psycopg2 binary for production?

### ISSUE THREAD

**Issue by ClaudiuPID** [mirumee/saleor#3292]
According to the official documentation: http://initd.org/psycopg/docs/install.html#binary-install-from-pypi

> The -binary package is meant for beginners to start playing with Python and PostgreSQL without the need to meet the build requirements. If you are the maintainer of a publish package depending on psycopg2 you shouldn’t use psycopg2-binary as a module dependency. For production use you are advised to use the source distribution.

And some more details why one should not use -binary version in production: http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/

But maybe I am missing something and you have a good reason for using binary version.

**Comment by patrys** [comment]
Saleor is not a library so I don't think the "publish package depending (...)" part applies. We use the binary package so it's possible to install Saleor on Windows without having to install Visual Studio and a bunch of other tools first.

**Comment by ClaudiuPID** [comment]
Please take a look at the second link I posted. I was in that situation, reason why I opened this issue.
It is no big deal, cloning the repo and changing requirements.txt is nothing to worry about.
This was more of a heads up if you guys did not know about it already.
