### ISSUE TITLE
Error resolving ProductType with no TaxRateType

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#3294]
### What I'm trying to achieve
To resolve `TaxRateType` on `ProductType`, when it's set to null.

### Steps to reproduce the problem
1. Execute query
```
{
  productType(id: "UHJvZHVjdFR5cGU6MTA=") {
    id
    taxRate
  }
}
```
2. Get an error
```
{
  "message": "Expected a value of type \"TaxRateType\" but received: ",
  "path": [
    "productType",
    "taxRate"
  ]
}
```

**Comment by NyanKiyoshi** [comment]
Not only if it's set to null, but also when `tax_rate` is blank (as it is allowed to be blank in the models and an empty tax rate is inserted during the db populate), it still tries to convert it to the TaxRateType `enum`: https://github.com/mirumee/saleor/issues/3278#issuecomment-438065757.

**Comment by patrys** [comment]
We should fix this by ensuring we don't have products with invalid/missing tax rates. Everything that is not explicitly assigned to a special group should be assigned to default.

**Comment by maarcingebala** [comment]
So maybe we should remove `blank=True` from models and ensure that we always set the default tax rate? Originally I thought that having `null` is fine - if you don't use taxes and even the "standard" rate doesn't make sense, you wouldn't ever set any value for that field.

**Comment by patrys** [comment]
Well, if you don't apply taxes then I guess "standard" is not to apply a tax 😄
