### ISSUE TITLE
Variant picker not working in storefront

### ISSUE THREAD

**Issue by dinhnghia** [mirumee/saleor#3297]
<img width="1422" alt="screen shot 2018-11-18 at 12 19 41 am" src="https://user-images.githubusercontent.com/13850307/48663786-aefce180-eac7-11e8-8564-85adc5848e01.png">

**Comment by dinhnghia** [comment]
@maarcingebala @dominik-zeglen

**Comment by maarcingebala** [comment]
Closing in favor of #3274
