### ISSUE TITLE
Dropdown not showing states

### ISSUE THREAD

**Issue by harinath141** [mirumee/saleor#3299]
On selection of country india,state dropdown not populating state list.

**Comment by Pacu2** [comment]
Could you provide more information? Where does it happen? Is it checkout, your account details, dashboard?

**Comment by harinath141** [comment]
@Pacu2 while checkout from storefront.

**Comment by Pacu2** [comment]
Works for me on the demo store.
Could you provide complete steps to reproduce?
![screenshot 2018-11-19 at 14 48 00](https://user-images.githubusercontent.com/21290461/48710932-220e7100-ec0a-11e8-8247-3eefa67e3bec.png)

**Comment by harinath141** [comment]
@Pacu2 yeah its populating might be issue with connectivity thanks for the prompt response.I'll close the issue.
