### ISSUE TITLE
Integrated cod but after payment not redirecting

### ISSUE THREAD

**Issue by harinath141** [mirumee/saleor#3304]
I integrated cod option by adding django-payments-cod to installed apps and by tweaking below

```
PAYMENT_VARIANTS = {
    'default': ('django_payments_cod.CODProvider', {})}

```
```
CHECKOUT_PAYMENT_CHOICES = [
    ('default', 'Cash On Delivery')
]
```
 in settings file
The problem I am currently facing is after making payment its freezing without redirecting to order success or payment success page.
<img width="1196" alt="screen shot 2018-11-20 at 12 18 00 am" src="https://user-images.githubusercontent.com/17981729/48728092-02069e00-ec5a-11e8-8194-92435d15b5bc.png">
<img width="1198" alt="screen shot 2018-11-20 at 12 18 17 am" src="https://user-images.githubusercontent.com/17981729/48728098-07fc7f00-ec5a-11e8-83f2-7f79ae9a4db5.png">
thanks in advance..

**Comment by Pacu2** [comment]
Django payments are not compatible with Saleor anymore. We've dropped it for our custom solution, and payment gateways should be integrated directly into Saleor. 

We have a guide on adding new payment methods in https://docs.getsaleor.com/en/latest/guides/payments.html#adding-payments
