### ISSUE TITLE
Can I list all categories in a single page ??

### ISSUE THREAD

**Issue by ayushgangrade11** [mirumee/saleor#3314]
### What I'm trying to achieve
… I am trying to add all the categories in a single page and when customer clicks SHOW NOW on home page, he should be landed on that page 

### Describe a proposed solution
... Ideally a django view which has access to all the categories and list them together to make urls.

### Other solutions I've tried and won't work
… Haven't tried anything yet

**Comment by Pacu2** [comment]
I don't think we have such view in Saleor,  that should be a part of your local customization.
