### ISSUE TITLE
Create sub-categories for random data

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#3315]
I noticed that the demo doesn't have any sub-categories anymore, thus we don't have access to this feature. Shouldn't we add some again? (#2056)

**Comment by jxltom** [comment]
Just mentiion it here the demo doesn't have sales neither.

**Comment by maarcingebala** [comment]
We can re-iterate on the products catalog and introduce some subcategories. They were removed when we made new products for Saleor 2.0 release. It wasn't intentional, I think we just forgot that we can have them 😉

**Comment by maarcingebala** [comment]
@timcla Maybe you'd had some time to take a look at the current structure and propose some subcategories?

**Comment by timcla** [comment]
(Current...)

ACCESSORIES
Homewares 
Paints

APPAREL
T-shirts
Polo shirts
Hoodies
Footwear

GROCERIES
Juices
Alcohol

----

(planned...)

ACCESSORIES
Homewares 
Paints
Music
Mugs

APPAREL
T-shirts
Polo shirts
Hoodies
Footwear

GROCERIES
Juices
Alcohol
Coffee
Tea
Oil
