### ISSUE TITLE
Support for Appengine

### ISSUE THREAD

**Issue by Mistobaan** [mirumee/saleor#3319]
### What I'm trying to achieve
Be able to run sale or over appengine

### Describe a proposed solution
Show a set of steps to run the project on appengine

### Other solutions I've tried and won't work
It runs on heroku so it should be possible to run on Appengine as well

**Comment by jxltom** [comment]
For the free tier, does it support run as 24/7/365 service?

I checked the doc it saids ```28 frontend instance hours per day, 9 backend instance hours.``` I think saleor can run as a ```frontend instance```?
