### ISSUE TITLE
Allow rectangular product images

### ISSUE THREAD

**Issue by BenSturmfels** [mirumee/saleor#3320]
Hi Folks,

It looks as though commit 20a67e79 removed the ability to have rectangular product images (rather than the square defaults). The `get_thumbnail` tag used to support a size like `100x200`, eg.

`{% get_thumbnail product.get_first_image method="thumbnail" size="100x200" %}`

Now it only takes a single size integer and automatically squares it as in the following, meaning that the above usage fails.

`{% get_thumbnail product.get_first_image method="thumbnail" size=255 %}`

From a design perspective, having rectangular images was a useful feature, since photographers tend to set up their shots to get the best out of a rectangular frame, similarly most mobile devices have rectangular screens.

Regards,
Ben

**Comment by BenSturmfels** [comment]
This is made harder still by the Javascript in `static/js/components/misc.js:36` that applies CSS to force the image height to be set to the width:

`$('.product-image').css({'height': productImageWidth + 'px'});`

And by switching from method `crop` to `thumbnail` (see above), rectangular images now don't thumbnail to a consistent size, making it fairly easy to mess up a float layout.

**Comment by patrys** [comment]
Dashboard code will center any image within a square box and that's by design as we have to accommodate all sorts of ratios there. For your own storefront you are not limited to any shape. The size param specifies the limit on the longer side, we don't crop (or at least we shouldn't, if we do it anywhere, it's a bug) images so the resulting thumbnail is going to have the same aspect ratio as the original.

**Comment by patrys** [comment]
We try to avoid `crop` as it can do more harm than good, chopping off parts of the product in the process.

**Comment by BenSturmfels** [comment]
Preferring `thumbnail` is fine, it's just confusing that there's a `method` argument to  the `get_thumbnail` template tag which really only works properly for the `thumbnail` method.

Perhaps the `method` argument should be dropped? At least this would send a clear signal that if you want something else, you need to do it yourself (as I've reallised I have to do in this case).

**Comment by maarcingebala** [comment]
I agree - we should drop the `method` argument to avoid confusion.

**Comment by NyanKiyoshi** [comment]
Looks like it's safe to drop, there is no code using `crop` for thumbnails. Maybe we could add a constant settings setting the default method to `thumbnail`? (e.g.: on my production fork, we use a custom method than `thumbnail`)

**Comment by BenSturmfels** [comment]
@raybesiga I've attached a patch showing how I did it. I've modified this by hand to remove some irrelevant bits, so it probably won't apply cleanly with `patch`. You'll get the idea anyway. I modified the template tag to allow it to take width/height, passed the height across in the template, and removed the "product-image" class that the JavaScript code was looking for and automatically making the image square.

[rectangular-images.diff](https://github.com/mirumee/saleor/files/2748201/rectangular-images.txt)

**Comment by NyanKiyoshi** [comment]
Can you test on latest master without the patch? This [commit](https://github.com/mirumee/saleor/commit/7a5185cd491e928f2a534355ae04f6f54767ca35#diff-423ca3c20dd6bc937fff4331e7097e8d) should allow getting rectangular sizes.

**Comment by raybesiga** [comment]
Hi @NyanKiyoshi let me update my git log and pull. Will revert with the outcome. Thank you.

**Comment by patrys** [comment]
@raybesiga If you specify 600 as size, it should give you 400×600 assuming that the uploaded aspect ration is correct. We no longer crop any images when creating thumbnails.

**Comment by raybesiga** [comment]
@patrys how does it know to make the image 400x600 if I only specify the size as 600? Is there a way to make an explicit declaration, say 400x600? I ask this because it may not always be the case that the height of an uploaded image is 600. Also, when we declare the size, is that strictly for the height?

**Comment by raybesiga** [comment]
Oh wow. This is fabulous @patrys Just pulled and now installing the required Python and Node packages. Will let you know how it goes.

**Comment by raybesiga** [comment]
I think the update [commit](https://github.com/mirumee/saleor/commit/7a5185cd491e928f2a534355ae04f6f54767ca35#diff-423ca3c20dd6bc937fff4331e7097e8d) fixed the issue of the images. The only really weird thing is that now, the `product-image` div inherits the `size` specified as the image height for its element. This inadvertently crops the image upwards and changes the focus of the image. Here is an example:

Height inherited by default 

![height-inherited](https://user-images.githubusercontent.com/405697/52552786-89475600-2df2-11e9-8f05-77eeeeacf8a9.png)

Height inherit disabled on the element

![height-not-inherited](https://user-images.githubusercontent.com/405697/52552810-99f7cc00-2df2-11e9-9073-bd55fe083a6c.png)

Is there a way to make the element not inherit the height? Thanks @patrys @NyanKiyoshi @BenSturmfels
