### ISSUE TITLE
[Docker] The SECRET_KEY setting must not be empty.

### ISSUE THREAD

**Issue by Sshuichi** [mirumee/saleor#3325]
### What I'm trying to achieve
Install and run Saleor on Docker in production

### Steps to reproduce the problem
1. docker build -t mystorefront .
2. docker run mystorefront:latest

### What I expected to happen
Launch the store on port 8000

### Screenshots
![image](https://user-images.githubusercontent.com/5939429/48978439-d3a71980-f0c4-11e8-8acf-da00e6d83c43.png)

**System information**
Operating system: UBUNTU 18.04
Browser:

General questions: 
What are the env variables that docker is using and how can I change them?

**Comment by Pacu2** [comment]
For local development you might want to use `docker-compose up`

Env variables are listed here: https://docs.getsaleor.com/en/latest/gettingstarted/configuration.html

**Comment by Sshuichi** [comment]
Hi @Pacu2, this is not for development, it's for production.

**Comment by Sshuichi** [comment]
I'm really confused here and I don't know how to deploy using docker. I'm still getting this error. 
What are the correct steps please?

**Comment by jxltom** [comment]
Please try ```docker run -e SECRET_KEY=*** -e DATABASE_URL=*** -p 8000:8000 saleor```

**Comment by Sshuichi** [comment]
Are those parameters (-e DATABASE_URL=*** ) referring to docker's postgres?

**Comment by jxltom** [comment]
It can be any postgres database owned by you. You can run postgresl via docker or buy postgreql from cloud provider.

**Comment by Sshuichi** [comment]
But isn't that docker's purpose? To have everything in a single container that doesn't affect the system you're working on? 
I really don't want to run postgres outside docker as I think it'd become harder to maintain..

**Comment by jxltom** [comment]
Sure, then you can run another postgresql container via docker. You can not setup multiple services in one container. So I would recommend you use ```docker-compose```. Refer https://docs.getsaleor.com/en/latest/customization/docker.html

**Comment by Sshuichi** [comment]
Thanks for your comment, but isn't that, per say, for development and not for production?

**Comment by jxltom** [comment]
Or you can run ```docker run -d -e POSTGRES_USER=saleor -e POSTGRES_PASSWORD=saleor postgres:9.6-alpine``` to startup your postgresql service. Then you database url would be ```postgres://saleor:saleor@localhost:5432/saleor```

**Comment by jxltom** [comment]
IMO, docker-compose can be used for production, only if you setup correctly

**Comment by Sshuichi** [comment]
Ok, let's see what the maintainers have to say in this. 
Thanks for your efforts.

**Comment by Sshuichi** [comment]
Yes, the env command gives the secret_key I set. But I noticed it got reset every time I ssh to my server. 
Should I set it inside docker or the ubuntu server?

**Comment by Sshuichi** [comment]
I added the export command to .bash_profile and now it's persisted. But so is the problem :)

**Comment by patrys** [comment]
@jxltom is right. You need to set the environment variable from outside the Docker. Either give it explicitly when starting docker (`docker run -e SECRET_KEY=soverysecret ...`) or export it in your startup script and tell Docker to use the value (`docker run -e SECRET_KEY ...`).

**Comment by Sshuichi** [comment]
Thanks for the confirmation. 
Thanks to @jxltom too. I'll try and get back to you. 
More stress for a detailed documentation.

**Comment by Sshuichi** [comment]
UPDATE, the server runs without issues, but when I try to connect to ip:8000 the connection is refused. 
Any idea why? I checked iptables, explicitly allowd tcp on 8000 but still connection refused.

**Comment by jxltom** [comment]
It should be accessed in ```127.0.0.1:8000```.

For accessed via ```0.0.0.0:8000```, probably you need to setup proxy if your server is running behind a reverse proxy such as nginx

**Comment by Sshuichi** [comment]
I don't think it works: 
curl: (7) Failed to connect to 127.0.0.1 port 8000: Connection refused

**Comment by jxltom** [comment]
Have you you added ```-p 8000:8000``` in ```docker run```?

Besides, are you sure you have never set ```PORT``` environment varialble other than ```8000```?

**Comment by Sshuichi** [comment]
I didn't change anything in that. it's by default. 
EXPOSE 8000
ENV PORT 8000

**Comment by Sshuichi** [comment]
It works thanks a lot. 
Why do you think the initial config didn't work out?

**Comment by jxltom** [comment]
It is because EXPOSE only make the port be accessed within docker. ```-p``` which is publish argument make it can be accessed anywhere.

**Comment by Sshuichi** [comment]
Awersome. Thanks a lot for all the help.
