### ISSUE TITLE
Cannot query field "edges" on type "ProductImage"

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#3341]
### What I'm trying to achieve
I get the error message `Cannot query field "edges" on type "ProductImage"` when I run the following query.
```
query sampleQuery {
  products(first: 10){
    edges{
      node{
        images{
          edges{
            node{
              alt
            }
          }
        }
      }
    }
  }
}
```
`edges` is highlighted by the Playground editor. This query ran fine on previous versions of saleor. And the GraphQL schema itself also suggests that `images` should be a list.

### Screenshots
![image](https://user-images.githubusercontent.com/6402969/49071757-1e04d380-f248-11e8-87a9-25496e0f2ca8.png)

**System information**
Operating system: Windows 10 (64 bit)
Browser: Firefox 63

**Comment by Pacu2** [comment]
That's right, images should be a list, as that's not a connection field anymore. We've changed that recently

**Comment by maarcingebala** [comment]
Our API is in beta and we're still doing improvements like this. We decided to change some of the connections to simple lists as there is no need to do the pagination where number of related object isn't expected to be high (e.g. product images or variations). See PR #3307 for details.
