### ISSUE TITLE
Redis inside docker

### ISSUE THREAD

**Issue by Sshuichi** [mirumee/saleor#3347]
Is redis running inside docker? If not, can we have it and have it as default in docker setup for production?

**Comment by patrys** [comment]
`Dockerfile` is only for the web container. Each service (web, celery, database, cache) runs in an isolated container.

**Comment by Sshuichi** [comment]
So, if I follow this documentation
https://docs.getsaleor.com/en/latest/deployment/docker.html
Does it mean that the container actually runs web,celery, database and cache and I can just use the ENV variables to tell it to use REDIS as cache? 
Or how does it work?

**Comment by patrys** [comment]
These instructions assume that you have PostgreSQL, Redis etc. already running somewhere (which is often the case with AWS RDS, AWS ElastiCache and similar services). If you want to deploy everything then I suggest you use `docker-compose` instead.

I would welcome a change to the documentation to clarify that.

**Comment by Sshuichi** [comment]
I'll be happy to contribute to the documentation, but I need to understand how this works first 😅 
The documentation states that docker-compose is for development only, to what extent is that correct? 
Also, how easily is it to maintain different docker containers that interact with each other, wouldn't be super easier to just bring everything under the same container?

**Comment by patrys** [comment]
The config we distribute (`docker-compose.yml`) is meant for local development as it uses `python manage.py runserver` to start Django. There is a [pull request](https://github.com/mirumee/saleor/pull/3093) however that begins to change that.

If you remove the `command: ...` line from the `web` container you should be able to use the config to build a production environment. Make sure to edit the `common.env` file to disable `DEBUG` and make sure other variables are set to correct values (and use a safe `SECRET_KEY`).

As for running everything under one container it has several problems:
* Docker is meant to oversee a single process in each container, you could add a supervisor process inside the container to orchestrate a number of other dependencies but if one of those experiences a failure, your Docker server will not know about it (from its point of view, your container is there to run the supervisor which probably still runs as a process)
* The resulting image would have to be manually assembled and would need to be large to satisfy the the requirements of all the services running inside
* It would be impossible to scale: you'd normally scale services by spawning more containers but spawning a second container would mean you would now have two (five, a hundred) separate database servers and two (five, a hundred) separate caches with no way to synchronize state between them
