### ISSUE TITLE
Images aren't found in startproject

### ISSUE THREAD

**Issue by johnchendev** [mirumee/saleor#3357]
### What I'm trying to achieve
Have the Saleor template just as it is

### Steps to reproduce the problem
1. Follow the tutorial to install Saleor

### What I expected to happen
Saleor to be created as per the demo

### Explanation

Hi guys,  just started a fresh install of Saleor in my system.

Everything works fine, except some of the images.

Here's the output that I got.

WARNING django.server "GET /static/dashboard/images/logo.svg HTTP/1.1" 404 1813 [PID:7264:Thread-31]
WARNING django.server "GET /static/dashboard/images/account-circle.svg HTTP/1.1" 404 1843 [PID:7264:Thread-32]
WARNING django.server "GET /static/dashboard/images/logo.svg HTTP/1.1" 404 1813 [PID:7264:Thread-31]
WARNING django.server "GET /static/dashboard/images/account-circle.svg HTTP/1.1" 404 1843 [PID:7264:Thread-32]
WARNING django.server "GET /static/dashboard/images/mobile-menu.svg HTTP/1.1" 404 1834 [PID:7264:Thread-33]
WARNING django.server "GET /static/dashboard/images/mobile-menu.svg HTTP/1.1" 404 1834 [PID:7264:Thread-33]
WARNING django.server "GET /static/dashboard/images/account-circle.svg HTTP/1.1" 404 1843 [PID:7264:Thread-32]
WARNING django.server "GET /static/dashboard/images/logo.svg HTTP/1.1" 404 1813 [PID:7264:Thread-31]
WARNING django.server "GET /static/dashboard/images/mobile-menu.svg HTTP/1.1" 404 1834 [PID:7264:Thread-33]
WARNING django.server "GET /static/dashboard/images/search.svg HTTP/1.1" 404 1819 [PID:7264:Thread-34]
WARNING django.server "GET /static/dashboard/images/search.svg HTTP/1.1" 404 1819 [PID:7264:Thread-34]
WARNING django.server "GET /static/dashboard/images/search.svg HTTP/1.1" 404 1819 [PID:7264:Thread-34]

**Please note that at this moment, i've not touched anything in the code. This is running directly off a fresh install. I thought it might have been an error whilst installing, so I tried it again. No luck on the second try either.**

**System information**
Operating system: Windows 10 with Pycharm
Browser: Chrome

**Comment by Pacu2** [comment]
Have you ran `npm run build-assets`? As it seems like static files were not generated properly

**Comment by johnchendev** [comment]
Yep, ran it again and same problem. Any idea? @Pacu2

**Comment by Pacu2** [comment]
@johnchendev Were there any errors during this command, or `npm i`?

**Comment by majzlik** [comment]
Ran into same issue on windows 10 install, solved it with adding dashboard path in settings.

I.E. from this:
STATICFILES_DIRS = [
    ('assets', os.path.join(PROJECT_ROOT, 'saleor', 'static', 'assets')),
    ('favicons', os.path.join(PROJECT_ROOT, 'saleor', 'static', 'favicons')),
    ('images', os.path.join(PROJECT_ROOT, 'saleor', 'static', 'images')),
    ('dashboard/images', os.path.join(PROJECT_ROOT, 'saleor', 'static', 'dashboard', 'images'))
    ]

to this:
STATICFILES_DIRS = [
    ('assets', os.path.join(PROJECT_ROOT, 'saleor', 'static', 'assets')),
    ('favicons', os.path.join(PROJECT_ROOT, 'saleor', 'static', 'favicons')),
    ('images', os.path.join(PROJECT_ROOT, 'saleor', 'static', 'images')),
    ('dashboard', os.path.join(PROJECT_ROOT, 'saleor', 'static', 'dashboard')),
    ('dashboard/images', os.path.join(PROJECT_ROOT, 'saleor', 'static', 'dashboard', 'images'))
    ]
