### ISSUE TITLE
How to use stripe with Saleor? 

### ISSUE THREAD

**Issue by Sshuichi** [mirumee/saleor#3368]
Hi guys, how to add stripe payment to Saleor?

**Comment by Pacu2** [comment]
Stripe is not currently supported, as we’ve just migrated from Django-payments to our custom solution. We have quite a nice docs on integrating new payment methods into Saleor if you want to handle it

**Comment by Sshuichi** [comment]
Alright, thanks!

**Comment by hairychris** [comment]
I will be working on this shortly if you want to collaborate.

**Comment by hairychris** [comment]
Working on it here: https://github.com/hairychris/saleor/tree/stripe feel free to pitch in, the basics are there but for some reason the Payments aren't being stored in the database, we then need to write some tests before we can make a pull request.
