### ISSUE TITLE
AMP pages

### ISSUE THREAD

**Issue by Sshuichi** [mirumee/saleor#3370]
### What I'm trying to achieve
AMP pages

### Describe a proposed solution
Implement AMP pages
https://www.ampproject.org/

Hey guys, are AMP pages on the roadmap for Saleor? they do boost SEO traffic.

**Comment by Pacu2** [comment]
They're not on the roadmap, as the gain from it for e-commerce businesses is still controversial, and they require rebuilding the whole front end from the ground up.

**Comment by Sshuichi** [comment]
Sounds good. PWA is a good thing to have now at least.

**Comment by Pacu2** [comment]
Here's a nice article about AMP for e-commerce
https://thirtybees.com/blog/amp-is-bad-for-e-commerce/

Well-build website won't be much slower than AMP itself unless you throw a dozen affiliates & ads on it.

**Comment by Sshuichi** [comment]
Good point. Thanks
