### ISSUE TITLE
Date filter of order is not working

### ISSUE THREAD

**Issue by haoyuc1** [mirumee/saleor#3371]
### What I'm trying to achieve
I want to show orders of specific date, but when I used date filter, result is same as no filter.

**Comment by Pacu2** [comment]
Just to double check, you mean that issue occurs on the Orders panel, in the dashboard?

**Comment by NyanKiyoshi** [comment]
If that's the dashboard, I cannot manage to reproduce the issue. If you could give us a little more information 👍 (steps to reproduce, version, modified Saleor or not).

<div align='center'><img src='https://user-images.githubusercontent.com/6186720/49344166-08dadb00-f674-11e8-970c-a7e7bdfc9dff.png' alt='screenshot'/></div>

**Comment by haoyuc1** [comment]
It occurred in dashboard, I will upload a picture.

**Comment by haoyuc1** [comment]
This is image which haven't apply filter
![image](https://user-images.githubusercontent.com/7530207/49349273-b80cb780-f65e-11e8-814a-a9dd4d763361.png)

This is link which applied filter
https://demo.getsaleor.com/dashboard/orders/?id=&name_or_email=&created_0=2018-11-01&created_1=2018-11-30&status=&payment_status=&total_net_0=&total_net_1=&sort_by=

This is image which applied filter
![image](https://user-images.githubusercontent.com/7530207/49349340-ff934380-f65e-11e8-9f86-20506a03d9d7.png)

It should be no order show up, but it still show all of orders.

I found this problem which I run saleor on my computer, the version of saleor I used is commit 5a7e2e8f179425d4b50f2ccb154d3ac5c5a425f0.

I used demo website version to reproduce this issue. but I don't know how to fix this problem.

**Comment by NyanKiyoshi** [comment]
@haoyuc1 hi, could you give the steps to reproduce and what is your browser/ version + os. As said above, I cannot reproduce your issue.

**Comment by Pacu2** [comment]
I see the other issue here, order date filter is applied, but it's not present in the range filter

**Comment by haoyuc1** [comment]
@NyanKiyoshi I am sorry, maybe my poor English made misunderstanding. 
Steps:
Purpose: For example, if I want to show all of orders which place on Nov 9.
1, I go to order page in dashboard.
2, I selected date Nov 9 - Nov 10 in (Placed on) option on filter which on right side of order page.
3, Then, I click FILTER button. 
Result: Order page still show all of orders, but it should only show orders which placed on Nov 9 - Nov 10.
