### ISSUE TITLE
Order GraphQL product search results by relevance

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#3373]
### What I'm trying to achieve
When searching for products/categories using the `query` parameter of the graphql queries, the results are returned in the order of the product IDs rather than by how relevant they are to the search. Since it is not possible to specify what fields to search in, even products whose description fields match the query rank above those whose name fields match the query. Additionally, fuzzy search is still missing in the graphql API.

### Describe a proposed solution
By default, search results should be ranked by the quality of the match. Names that start with the query should rank highest, followed by names that contain the query, followed by descriptions that contain the query and category names that match the query

### Other solutions I've tried and won't work
If there was a way to query those different ranks separately, that might serve as a somewhat clumsy workaround.

### Screenshots or mockups
![image](https://user-images.githubusercontent.com/6402969/49358817-87c02a00-f6ed-11e8-98cc-760c283833a5.png)
In the screenshot, Red Wine and Red Dwarf Red Paint should both rank first since they start with the query. The ranking remains the same for the matches regardless of the quality of the match.

**Comment by maarcingebala** [comment]
Related #3400

**Comment by maarcingebala** [comment]
In PR #3736 we've added support for using searching products using search backends. If that works correctly in the long run, we'll add search support in other queries as well.
