### ISSUE TITLE
Update Process?

### ISSUE THREAD

**Issue by chadsaun** [mirumee/saleor#338]
If I want to update Saleor, how would I do that?

**Comment by patrys** [comment]
Saleor was designed to be easily forkable. It would be much easier to port the features you are after than to replace your entire storefront.

**Comment by chadsaun** [comment]
So basically just using a git merge and then resolving any conflicts?

**Comment by patrys** [comment]
If you want to apply all changes then yes. However I would start by cloning the current master branch in a separate directory and check which parts of it are actually useful for you.
