### ISSUE TITLE
Extendable User Profile

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#3388]
### What I'm trying to achieve
To be able to add arbitrary fields to the user profile. The user profile is a good place to store various kinds of information. It makes sense to allow extending it without modifying the underlying models.

### Describe a proposed solution
This could be approached the same way product attributes were designed. We could have a `UserType` to support different classifications of users. Each `UserType` would have a set of fields it requires. For example, in a scenario, a B2B `UserType` may have a `companyName` field while regular users would have `firstName` and `lastName`. Validation of these fields could be up to the user or a basic set of types could be provided as options when creating the fields (int, bool, phone, etc).

### Other solutions I've tried and won't work
In my current project, the client does not ship products. So I hijacked the `defaultShippingAddress` to store basic profile information. This is very limited and obviously won't work in every use case.

**Comment by maarcingebala** [comment]
We have now `meta` fields that you can use to assign arbitrary fields to various models, but it's only available in the API. Would that solve your use-case? 

https://docs.getsaleor.com/docs/next/api/metadata/

**Comment by khalibloo** [comment]
Thanks, that looks like it'll work great indeed! One question, though. Can the user update their own private meta? (similar to editing their user profile). Or is that restricted to staff only?

**Comment by maarcingebala** [comment]
CC @korycins? I guess we had a similar discussion recently. I think it requires staff permissions currently since private meta fields were designed to be used by admins. But maybe this is a valid use-case where we should allow authenticated customers to change their metadata as well.

On the other hand, could we use public meta fields for that? "Public" means that you don't need permission to change this metadata, but in the case of the `User` type - it's hidden in the API anyway. Only staff users can get access it and an authenticated customer gets it after logging in,

**Comment by khalibloo** [comment]
I was just thinking the same thing. Since other users cannot access the user object, the public meta should work!
That takes care of my use-case. Thanks.

**Comment by korycins** [comment]
The only logged-in user should have access to its public meta. We don't want store user data without logged-in permission. `meta` will be useful for implementation of a storefront where the owner requires to store some custom data dedicated only to the user.
`private_meta` and `meta` should be available for staff users.
As @maarcingebala, currently, `meta` doesn't require any permissions which is wrong and I am gonna fix it before coming release. `private_meta` requires staff permissions to manage users.
