### ISSUE TITLE
Adopt prettier for older JS files

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#3404]
We currently have two contradicting styles in the same repository. Typescript uses `prettier` but the old storefront code follows a different set of rules. Let's make `prettier` the only accepted style and update our JS files to match it.

**Comment by Julian-B90** [comment]
I want to try to help

**Comment by maarcingebala** [comment]
@Julian-B90 Sorry for no earlier response, are you still interested in helping out?

**Comment by Julian-B90** [comment]
@maarcingebala yes im interested :-)

**Comment by maarcingebala** [comment]
Great! So we have a bunch of JS files in Saleor repo, inside `saleor/static/js` catalog. They are all used either by the static storefront and the dashboard served by Django. To fix the styling you should use [prettier](https://github.com/prettier/prettier) and apply it on these JS files.

**Comment by Julian-B90** [comment]
Do you want do integrate prettier with [husky](https://github.com/typicode/husky#readme) or eslint -plugin ?

**Comment by maarcingebala** [comment]
I don't know Husky, but it seems similar to pre-commit that we use (see `.pre-commit-config.yaml`), so we could plug `prettier` there.

**Comment by Julian-B90** [comment]
I have create a PR https://github.com/mirumee/saleor/pull/4791
