### ISSUE TITLE
Missing release note for 2.0

### ISSUE THREAD

**Issue by jxltom** [mirumee/saleor#3414]
I remember there is release note created in Github here https://github.com/mirumee/saleor/releases for 2.0 release. I would like to read the changelog from it, but now it is missing.

Could I have it getting back? Thanks

**Comment by maarcingebala** [comment]
Should be fine now: https://github.com/mirumee/saleor/releases/tag/2.0.0.

**Comment by jxltom** [comment]
Thanks!
