### ISSUE TITLE
Bridge between Saleor and Navision

### ISSUE THREAD

**Issue by bingimar** [mirumee/saleor#3415]
Has anyone built a bridge between Navision and Saleor?

If not please let me know if you want to collaborate on this project.

- Some processes need to live in Nav
  - Shipping
  - Billing
  - Order status updates
  - Customer info
  - Customer discounts?

**Comment by patrys** [comment]
I assume you mean Dynamics NAV? https://docs.microsoft.com/en-us/dynamics-nav/fin-graph/index

**Comment by bingimar** [comment]
yeah, they change the name of it every full moon

**Comment by maarcingebala** [comment]
We have never worked with this tool. Nevertheless, we'll be happy to provide guidance (related to Saleor) if you're stuck with the integration. Please reopen the issue in that case.
