### ISSUE TITLE
Uploading Files to S3

### ISSUE THREAD

**Issue by ayushgangrade11** [mirumee/saleor#3416]
### What I'm trying to achieve
… Trying to deploy heroku app

### Steps to reproduce the problem
1. set config vars to use amazon s3 as static files server
2. Deploy your app
3. Since Npm rebuilds the prod packages hence prod hash changes ie django is not able to find the static files with updated hash.
4. In order to upload those files I have to heroku run python manage.py collectstatic everytime I go live even I dont have any scss changes.

### What I expected to happen
…Should go live without running build for assets.

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by jxltom** [comment]
If the frontend code doesn't change, the hash of assets shouldn't change. So if the the hash changes, it means your frontend code is changed and you have to upload it, othewise you website may not function well.

So are you sure  you hashes is changed though you didn't change of  your saleor code?

**Comment by ayushgangrade11** [comment]
Hi ... 
I am sure that my Frontend are same 
but I deploy my app it runs the node build everytime .... and it is almost about to eat up all the allowed put requests that I have for free in my s3 bucket ...

Is it possible to change this using a config ?

**Comment by jxltom** [comment]
Yeah, it will run the build everytime for sure. But the generated hash should be same. Are you sure the asset names are different?

**Comment by ayushgangrade11** [comment]
I agree ... the hash ideally shouldn't change at all ... However I found a workaround ... I have removed heroku postbuild & now going forward when I have changes I will upload them manually to my s3 just to make sure I am not running out of free limit quota .... 

was thinking about whitenoise in b/w but I am not sure if it will increase my response time a lot ... ?

**Comment by jxltom** [comment]
Another solution is writing your own ```collectstatic``` command which checks file md5 to determin upload it or not. In this way, even the hashes change, same file won't be uploaded twice since they didn't change at all and having same md5.

CDN is better than whitenoise since it also prevent ddos attacks. But whitenoise is also fine if security is not a priority concern.

**Comment by ayushgangrade11** [comment]
Thanks jxltom :+1:

**Comment by jxltom** [comment]
Glad to help. To be honest, I'm very curious about why the hashes are changing... But these workarouds will solve your issue any way. :smile:

**Comment by ayushgangrade11** [comment]
Time is little bit a constraint for me as of now since I am alone working on this project .... Lets do a deep dive once I am free ... Hopefully.. by the end of This month. :)

**Comment by jxltom** [comment]
Of course, no rush for it :D
