### ISSUE TITLE
 Dashboard-next- Could not create product with Product attributes

### ISSUE THREAD

**Issue by selvara80** [mirumee/saleor#3419]
### What I'm trying to achieve
Create a new product based on a Product-Type, which has Product Attribute.
…

### Steps to reproduce the problem
1. Create a new product-type(Say.,  X) which has product attribute.
2. Try Create a new product for the product-type (X)
3.While using the drop-down and trying to select the product-type (X), application opens up a blank page and fails to load

### What I expected to happen

While trying to select the product-type (X), application should load the product-type (X) along with its attributes.

### Screenshots

Debug Logs:
TypeError: Cannot read property 'name' of undefined
ProductOrganization.tsx:48
    at getAttributeName (\saleor\static\dashboard-next\products\components\ProductOrganization\ProductOrganization.tsx:48:87)

**System information**
Operating system: Windows 10
Browser:Chrome

**Comment by dominik-zeglen** [comment]
Same as #3420 - I couldn't reproduce this problem.

**Comment by selvara80** [comment]
With the latest master, issue is not there
