### ISSUE TITLE
Dashboard-next- Could not create product even WITHOUT Product attributes

### ISSUE THREAD

**Issue by selvara80** [mirumee/saleor#3420]
### What I'm trying to achieve
Create a new product based on a Product-Type, which does NOT have any Product Attribute.

…

### Steps to reproduce the problem
1. Create a new simple product-type(Say., X). This does not have any product or variant attributes
2. Try create a new Product based on product-type (X)
3.Able to select X from the product-type drop-down
4.However upon SAVE action, this transaction fails and SAVE button converts to ERROR button.

### What I expected to happen
New product should be created , without throwing any errors

### Screenshots

No relevant debug logs found

**System information**
Operating system: Windows10
Browser:Chrome

**Comment by dominik-zeglen** [comment]
Sorry, but I am unable to reproduce this. Do you work on the latest master branch?

**Comment by selvara80** [comment]
With the latest master, issue is not there.
