### ISSUE TITLE
Update python package on heroku to 3.6.7

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#3430]
```Python has released a security update! Please consider upgrading to python-3.6.7```

## TODO
1. update `runtime.txt file`

**Comment by Pacu2** [comment]
Had some troubles installing `uwsgi` on python 3.6.7 and 3.7.1 on Heroku, please ensure it's working properly after the upgrade.

Had no time to debug it so rolled back to 3.6.6 for now.

**Comment by kiran-capoor94** [comment]
Hi, 
I have set runtime to 3.7.3 and it works fine.

**Comment by maarcingebala** [comment]
It's been fixed some time ago already.
