### ISSUE TITLE
Cannot update staff member's permissions

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#3432]
### What I'm trying to achieve
To add or remove permissions from a staff member.

### Steps to reproduce the problem
1. Execute the following query
```
mutation {
  staffUpdate(id: "insert-id-here", input: {permissions:["IMPERSONATE_USERS"]}) {
    errors {
      field
      message
    }
  }
}
```
2. Get an error:
```
Unknown permission: IMPERSONATE_USERS
```

### What I expected to happen
To properly add IMPERSONATE_USERS permission.

**Comment by maarcingebala** [comment]
Resolved in #3434.
