### ISSUE TITLE
How to add Japanese shipping address

### ISSUE THREAD

**Issue by kimnam-server** [mirumee/saleor#3438]
### What I'm trying to achieve
Shipping in Japan

### Steps to reproduce the problem
1. Purchase
2. Enter shipping address

### What I expected to happen
Go to the payment screen

### Screenshots
![2018-12-12 10 32 09](https://user-images.githubusercontent.com/40751632/49841112-9f886400-fdf9-11e8-89ff-1feb1917956f.png)

**System information**
Operating system: mac
Browser: chrome

## Explanation
Using saleor
I am making a toy shopping mall. thank you.
I have one problem and I have a question.

```
Unfortunately we do not ship to your selected country. 
Please enter an alternative shipping address or contact us, if you think that's a mistake.
```

I have a tester to ship to Japan. The following message appears. How do I add Japan to my shipping address?

**Comment by kimnam-server** [comment]
This problem is solved.

**Comment by Pacu2** [comment]
That was due to lack of shipping methods in `populatedb`, we know that it might be confusing so we are planning to introduce some improvements in #3436
