### ISSUE TITLE
mutations to create and update variants do not allow sku and id to be set separately

### ISSUE THREAD

**Issue by cprinos** [mirumee/saleor#3439]
### What I'm trying to achieve
Set the name and sku for a product variant (not using attributes) via productVariantCreate or productVariantUpdate mutation

### Steps to reproduce the problem
1. create multiple product variants via graphql and specify a sku (no attributes)
2. the sku is set for the variants, and in the storefront you will see a variant select menu item that shows  <sku> - <price> fore each item. 
3. productVariantCreateInput! has a sku field, but no 'name' field, so you can set the variant name

Note if you create the product variant in the ui, specifying only a sku (no attributes), it will show up as having both sku and name set to the sku (it's not that way in the database though)

### What I expected to happen
allow variant name (product_productvariant.name) to be set in the variant mutations, so that the variant select menu shows <name> - <price> instead of <sku> - price

this is important for being able to set variant 'names' that shouldn't be attributes (and thus should show up in the filters)

### Screenshots
<img width="347" alt="image" src="https://user-images.githubusercontent.com/671656/49846232-4b00cc80-fd98-11e8-9eac-910ef952c16b.png">

<img width="679" alt="image" src="https://user-images.githubusercontent.com/671656/49846424-222d0700-fd99-11e8-8362-a4c36a3ae688.png">

**Comment by maarcingebala** [comment]
By design, variant names are used to represent attributes assigned to a variant and that's why they are generated and we don't allow to change them.

**Comment by piyushs02** [comment]
We dont want to show my sku name to frontstore, instead a business need to show a easyly understandle name to its customers. It is a needed feature. Also if you do not allow to change the variant name then why there is a separate field in the database ?

**Comment by maarcingebala** [comment]
@piyushs02 In Saleor you have full freedom in what do you want to show in the frontstore. Variant name field is stored in the database for optimization (and convenience). Since those names are based on variant attributes, we don't want to lookup them in the database every time we render a variant / order line / checkout line.
