### ISSUE TITLE
Implement Product's Open Graph

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#3447]
Specs (currently not responding): https://developers.facebook.com/docs/reference/opengraph/object-type/product/

This can be helpful as well: https://webcode.tools/open-graph-generator/product-item

All tags in the snippet below should be present on the product page:
```
<meta property="og:type" content="product.item">
<meta property="og:title" content="My red product">
<meta property="og:url" content="https://fullabsoluteurl.com/my-red-product-49/">
<meta property="og:image" content="https://fullabsoluteurl.com/media/products/product.jpg">
<meta property="product:condition" content="new">
<meta property="product:availability" content="in stock">
<meta property="product:price:amount" content="49.99">
<meta property="product:price:currency" content="USD">
<meta property="product:retailer_item_id" content="SKU">
```

If implemented properly, snippets, eg. on slack, should contain price ("cena") and color ("kolor")
<img width="1209" alt="screenshot 2018-12-12 at 20 22 00" src="https://user-images.githubusercontent.com/21290461/49893431-a8098a80-fe4b-11e8-9b42-64dab9ee9490.png">

**Comment by vladox** [comment]
@Pacu2 is this still open for grabs?
It seems that the only part missing is:

```
<meta property="product:condition" content="new">
<meta property="product:availability" content="in stock">
<meta property="product:price:amount" content="49.99">
<meta property="product:price:currency" content="USD">
<meta property="product:retailer_item_id" content="SKU">
```

**Comment by Pacu2** [comment]
@vladox Yes, would be awesome if you'd like to handle it, let us know! Probably the basic open graph tags were already implemented, but the ones you've quoted are responsible for displaying a really nice product thumbnail.

cc @maarcingebala @salwator
