### ISSUE TITLE
Add different payment status to GraphQL API such as fully-paid/partially-paid/

### ISSUE THREAD

**Issue by jxltom** [mirumee/saleor#3449]
### What I'm trying to achieve

Since https://github.com/mirumee/saleor/pull/3398 introduces ```is_party_paid```, same field should be added to graphql and then the storefront could use this field to determine whether showing pay button or not in order detail page. This is because partial payment is not supported. The pay button shouldn't show once the order is partly paid. Currently we only have ```is_paid``` field https://github.com/mirumee/saleor/blob/ecf9823ac695cc3ee1b37f601f154a36e4949c0f/saleor/graphql/order/types.py#L265-L268 in GraphQL api to determine the order payment status.

**Comment by patrys** [comment]
I'm not sure I agree with adding a ton of boolean flags to the API. Could these not be handle by a single status field with an enum? The order is either unpaid, partially paid or fully paid, it can't be two or three at the same time.

**Comment by jxltom** [comment]
Yeah, I agree, using enum is a better design. But it is fine to have different property/flag in the model which is added in #3398.

This issue can be used for tracking adding this feature, as for implementation, we could use enum or any better solution. :D
