### ISSUE TITLE
Add PWA support

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#3450]
### Goals
As a Saleor user, I'd like my site to be available offline. I'd like to give a user a possibility to navigate between previously seen pages, even if his internet connection broke. 
I'd like to inform a user that he can add my app to the home screen, so he will interact with my app more often, what's more - essentials will be already so it should run faster precached. 

### Challenges
Django resolves our URLs so it might need some trick to properly  resolve them in javascript

### Parts needed
1. Registration of the service worker
2. Service worker
3. A solution for adding new URLs to the service worker (eg. user enters a category page and we will cache all the future products beforehand)
4. A solution for displaying not available images while offline
5. offline.html page (design needed)

### Proposition
The solution could consist of 4 parts:
1. `sw.js` view, containing the service worker code, which should be served by Django. This way we can resolve URLs for the shell application parts, eg. `storefront` bundle
2. Service worker registration. Not sure what will be the difference between registering the service worker before the bundles loads, or after. This might need some more research.
We could just add it to `storefront.js` bundle, or create a new file for it as it can be loaded asynchronously. The last solution is to add it to `base.html` template. 
3. Adding new URLs to cache could be handled via jQuery, eg. URLs worth caching beforehand could be marked with a special class, retrieved in JS and added to the cache. In this case, we could even skip the first point.
4. Offline.html page, displayed when a user loses the internet connection

### Estimations
A simple solution would be possible to squeeze out in under 1 hour.

**Comment by maarcingebala** [comment]
We're not planning to add PWA capabilities to the Django-based storefront. [Storefront 2.0](https://github.com/mirumee/saleor-storefront/) already supports PWA features and we're going to improve it.
