### ISSUE TITLE
Change logs are not valid markdown

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#3453]
## Issue
Right now we have the [following change log file](https://github.com/mirumee/saleor/blob/bd0247953381adb307e585ef62feb71778142914/CHANGELOG.md) which lists the changes with a new line as separator:

```markdown
change1
change2
```

Which, is an invalid markdown list.

## Proposed Solution
Maybe we could or should use a item list instead, as below.

```markdown
- change1
- change2
```

**Comment by maarcingebala** [comment]
Right, we should change that as you propose 👍
