### ISSUE TITLE
I want to delete the DJDJ script from the screen.

### ISSUE THREAD

**Issue by kimnam-server** [mirumee/saleor#3467]
### What I'm trying to achieve
I want to delete the DJDJ script from the screen.

![screen_shot](https://user-images.githubusercontent.com/40751632/50064305-c973c900-01f3-11e9-9802-633e31f51c91.png)

**Comment by koradon** [comment]
Hi @kimnam-server this is django debug toolbar. You can find installation instruction here [https://django-debug-toolbar.readthedocs.io/en/latest/](url)

I believe it is also showing up when environment variable `DEBUG` in is set to `True` in `settings.py`

**Comment by kimnam-server** [comment]
@koradon thank you. Thanks.
