### ISSUE TITLE
【Thumbnail】Do not you consider using url directly in image of productimage instead of file?

### ISSUE THREAD

**Issue by kimnam-server** [mirumee/saleor#3477]
I would like to save the path of the image url without saving the image file directly.
```
@ register.simple_tag ()
def get_product_image_thumbnail (instance, size, method):
     image_file = instance.image if instance else None
     return get_thumbnail (image_file, size, method)
```
If so, it's probably not in the file format, so it will throw an error in `instance.image`.

In saleor2.0, do not you consider handling images as s3 or other url?

![2018-12-18 14 17 21](https://user-images.githubusercontent.com/40751632/50133853-c00c5e80-02d0-11e9-8b59-3e4608e3e77e.png)

**Comment by maarcingebala** [comment]
We support file storage on S3, see in the docs: http://docs.getsaleor.com/en/latest/deployment/s3.html
