### ISSUE TITLE
Deploying saleor aws beanstalk failed

### ISSUE THREAD

**Issue by Jisanbd** [mirumee/saleor#3488]
I've been trying for several days now to set up saleor under Amazon Web Services' Elastic Beanstalk. I am getting the following error most of the time:

ERROR: Your requirements.txt is invalid. Snapshot your logs for details.

Here's directory structure:

```
├── .ebextensions
│   └── django.config
├── .elasticbeanstalk
│   ├── config.yml
├── .git
├── .gitignore
├── manage.py
├── saleor
│   ├── __init__.py
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
└── requirements.txt
```
Here is django.config file inside .ebextensions:

option_settings:
 ```
 aws:elasticbeanstalk:container:python:
    WSGIPath: saleor/wsgi.py
packages:
  yum:
    gcc: []
    python36-devel: []
    gcc-c++: []
    libffi-devel: []
    postgresql93-devel: []
```

Error:

```
-------------------------------------
/var/log/eb-activity.log
-------------------------------------
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-q1ck81sr/cffi-1.11.5/setup.py", line 240, in <module>
        File "/usr/lib64/python3.6/distutils/core.py", line 163, in setup
          raise SystemExit("error: " + str(msg))
      SystemExit: error: command 'gcc' failed with exit status 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
          run_setup(setup_script, args)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 251, in run_setup
          raise
        File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
          self.gen.throw(type, value, traceback)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
          yield
        File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
          self.gen.throw(type, value, traceback)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules
          saved_exc.resume()
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 144, in resume
          six.reraise(type, exc, self._tb)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
          raise value.with_traceback(tb)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
          yield saved
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
          yield
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
          DirectorySandbox(setup_dir).run(runner)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
          return func()
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
          _execfile(setup_script, ns)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-q1ck81sr/cffi-1.11.5/setup.py", line 240, in <module>
        File "/usr/lib64/python3.6/distutils/core.py", line 163, in setup
          raise SystemExit("error: " + str(msg))
      SystemExit: error: command 'gcc' failed with exit status 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-y4onvdfc/cairocffi/setup.py", line 51, in <module>
          'test': ['pytest-runner', 'pytest-cov'],
        File "/usr/lib64/python3.6/distutils/core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
          self.fetch_build_eggs(attrs['setup_requires'])
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
          replace_conflicting=True,
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
          dist = best[req.key] = env.best_match(req, ws, installer)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
          return self.obtain(req, installer)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
          return installer(requirement)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
          return cmd.easy_install(req)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 695, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1103, in run_setup
          raise DistutilsError("Setup script exited with %s" % (v.args[0],))
      distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
```

**Comment by patrys** [comment]
@artursmet I think you have a working EBS config for Saleor. Could we either document it or add it to the repository?

**Comment by artursmet** [comment]
Yes, that's correct I have a working config for saleor, just have to review if it works with the current version.
@Jisanbd Did you tried to configure elastic beanstalk for using Docker under the hood? It would be easier to achieve to be honest instead of building the dependencies every single time.

**Comment by Jisanbd** [comment]
@artursmet I am completely new in AWS. Would you please share step by step deployment procedure?

**Comment by NyanKiyoshi** [comment]
@Jisanbd looks like you are missing some libraries for installing `cairocffi`.

```
packages:
  yum:
    libffi-devel: []
    gcc-c++: []
    python27-devel: []
    gcc-gfortran: []
    readline-devel: []
    make: []
    atlas: []
    blas: []
    lapack-devel: []
    blas-devel: []
    atlas-devel: []
    libffi-devel: []
    libjpeg-turbo-devel: []
    zlib-devel: []
    cairo-devel: []
    pango-devel: []
```

**Note 1:** you may need to upgrade NPM and node.js, if not already done, otherwise you will get trouble (saleor is requiring Node 10+):

```
commands:
  03-update-npm:
    command: "curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash - ; yum -y install nodejs npm"
```

**Note 2:** you may need to install postgres's development library (adapt the below code with your version).
```
    postgresql96-devel: []
```

**Comment by Jisanbd** [comment]
@NyanKiyoshi After changing django.config file from your suggestion still I am getting the same error  

django.config 
```
option_settings:
  aws:elasticbeanstalk:container:python:
    WSGIPath: saleor/wsgi.py
packages:
  yum:
    libffi-devel: []
    gcc-c++: []
    python36-devel: []
    gcc-gfortran: []
    readline-devel: []
    make: []
    atlas: []
    blas: []
    lapack-devel: []
    blas-devel: []
    atlas-devel: []
    libjpeg-turbo-devel: []
    zlib-devel: []
    cairo-devel: []
    pango-devel: []
    postgresql93-devel: []

commands:
  03-update-npm:
    command: "curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash - ; yum -y install nodejs npm"
```

Error:
```
File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-oltgps6t/cffi-1.11.5/setup.py", line 240, in <module>
        File "/usr/lib64/python3.6/distutils/core.py", line 163, in setup
          raise SystemExit("error: " + str(msg))
      SystemExit: error: command 'gcc' failed with exit status 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
          run_setup(setup_script, args)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 251, in run_setup
          raise
        File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
          self.gen.throw(type, value, traceback)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
          yield
        File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
          self.gen.throw(type, value, traceback)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules
          saved_exc.resume()
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 144, in resume
          six.reraise(type, exc, self._tb)

```

**Comment by pshangov** [comment]
Had the same problem, adding libffi-devel fixed it for me:

    packages:
      yum:
        libffi-devel: []

**Comment by Jisanbd** [comment]
Is this issue resolved?

**Comment by maarcingebala** [comment]
I assumed that from the last comment by @pshangov. If it isn't, we can reopen and continue the discussion.

**Comment by Jisanbd** [comment]
I have tried again and can see the same error like before. Any expected timeframe to solve this issue?

**Comment by maarcingebala** [comment]
I can give any estimates yet. We are now focused on payment refactoring, once we're done with this we'll be able to look closer into all devops related issues.

**Comment by artursmet** [comment]
@Jisanbd Please try spliting the packages section out of the django.conf file, try naming it for example `.ebextensions/01_install_packages.config` and the other `.ebextensions/02_django.config` Elastic beanstalk sorts the config names by their names at first. 
According to your log - the `libffi` compilation headers are missing and your packages config was not taken into account at all.

**Comment by Jisanbd** [comment]
After changing two separate file `ebextensions/01_install_packages.config` and `.ebextensions/02_django.config` i can

**Comment by Jisanbd** [comment]
After creating two separate file .ebextensions/01_install_packages.config and .ebextensions/02_django.config, i can still see the same error

01_install_packages.config
```
packages:
  yum:
    libffi-devel: []
    gcc-c++: []
    python36-devel: []
    gcc-gfortran: []
    readline-devel: []
    make: []
    atlas: []
    blas: []
    lapack-devel: []
    blas-devel: []
    atlas-devel: []
    libffi-devel: []
    libjpeg-turbo-devel: []
    zlib-devel: []
    cairo-devel: []
    pango-devel: []
    postgresql95-devel: []
```
02_django.config 
```
option_settings:
  aws:elasticbeanstalk:container:python:
    WSGIPath: saleor/wsgi/__init__.py

commands:
  03-update-npm:
    command: "curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash - ; yum -y install nodejs npm"
```
Please find below attached logs:
[eb-activity.log](https://github.com/mirumee/saleor/files/2769698/eb-activity.log)

**Comment by NyanKiyoshi** [comment]
@Jisanbd can you try adding this at the top of `01_install_packages.config`:
```
commands:
  03-force-libffi-level-to-latest:
    command: "yum -y install libffi-devel"
```

And in the yum package list, we can add `libffi: []` as well, even if I'm guessing `libffi-devel` is already depending on `libffi`.

**Comment by Jisanbd** [comment]
This gitignore file causing this issue. Saleor app is now deployed in the AWS after removing this file. Added my application domain name  in the Allowed host section in the settings.py by 
`ALLOWED_HOSTS = ['eb-django-app-dev.elasticbeanstalk.com']`
After entering command `eb open` i can see new issue
 ```
 could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
```
Do i need to change anything in the settings file apart from allowed host?

**Comment by artursmet** [comment]
@Jisanbd You have to configure proper `DATABASE_URL` environment variable, please refer to https://docs.getsaleor.com/en/latest/gettingstarted/configuration.html#environment-variables

AWS Beanstalk injects the `RDS_HOST` or similar variable which contians an hostname of the RDS server that you've configured within your environment, but it doesn't automatically convert that to a variable that saleor expects.

**Comment by Jisanbd** [comment]
`webpack-bundle.json  ` is already generated in my local folder. When I run the app locally in my virtual environment, it works perfectly .But now in the AWS beanstalk showing following error in the base.html:
`Error reading /opt/python/current/app/webpack-bundle.json. Are you sure webpack has generated the file and the path is correct?`

**Comment by Jisanbd** [comment]
Finally, I can run the page in AWS beanstalk without any error but the page is not loading properly. I have added the screenshot of the page. 

![screenshot1](https://user-images.githubusercontent.com/16919815/51426480-c6516b80-1beb-11e9-8f7d-78726dd54b7a.PNG)

![screenshot2](https://user-images.githubusercontent.com/16919815/51426481-c9e4f280-1beb-11e9-9ebd-db76768ee600.PNG)

So this is the current config file inside the. ebextension folder

01_install_packages.config:
```
packages:
  yum:
    libffi: []
    libffi-devel: []
    gcc-c++: []
    python36-devel: []
    gcc-gfortran: []
    readline-devel: []
    make: []
    atlas: []
    blas: []
    lapack-devel: []
    blas-devel: []
    atlas-devel: []
    libffi-devel: []
    libjpeg-turbo-devel: []
    zlib-devel: []
    cairo-devel: []
    pango-devel: []
    postgresql95-devel: []
```
02_django.config
```
option_settings:
  aws:elasticbeanstalk:container:python:
    WSGIPath: saleor/wsgi/__init__.py

commands:
  03-update-npm:
    command: "curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash - ; yum -y install nodejs npm"
```
db-migrate.config
```
container_commands:
  01_migrate:
    command: "django-admin.py migrate"
    leader_only: true

option_settings:
  aws:elasticbeanstalk:application:environment:
    DJANGO_SETTINGS_MODULE: saleor.settings
```
It is difficult to generate webpack-bundle.json . So, I just copied the local one. Am I missing any more steps which cause the page not loading properly?

**Comment by NyanKiyoshi** [comment]
I'm guessing that your project's static folder (the one next to .gitignore, etc.) is empty.
Did you build your assets (`npm run build-assets`) in your local project and then, did `python manage.py collectstatic`?

Then make sure the static path is correctly deployed (you can SSH into your EC2 instance and take a look, iirc the **successfully** deployed app is stored under `/opt/python/current/app/`).

Also, I would recommend you using a CDN (e.g.: S3 buckets) for your media files (and even static files). But for now the important thing, is getting the app correctly running.

**Comment by Jisanbd** [comment]
@NyanKiyoshi @artursmet It was working on AWS elastic beanstalk. Thank you for all your support. Now I have some problem creating the superuser and some other issues relating to payment. So I would like to keep this ticket open.

**Comment by artursmet** [comment]
@Jisanbd Glad that you managed to deploy it! Please feel free to report other issues that you encounter with using Saleor on elastic beanstalk. I'm happy to help you with them

**Comment by Jisanbd** [comment]
Currently, I am using this saleor app in Germany. But the page is not translating automatically. Moreover, I have added some product on the page.Whenever I am trying to buy the product it shows 

```
Unfortunately we do not ship to your selected country. 
Please enter an alternative shipping address or contact us, if you think that's a mistake.
```
This is the current settings.py

```
TIME_ZONE = 'Europe/Berlin'
LANGUAGE_CODE = 'de'
LANGUAGES = [
    ('de', _('German')),
    ('en', _('English')),
    ('es', _('Spanish')),
    ('fr', _('French')),
    ('it', _('Italian')),
    ('nl', _('Dutch')),
    ('pl', _('Polish')),
    ('cs', _('Czech')),
    ('da', _('Danish'))]

LOCALE_PATHS = [os.path.join(PROJECT_ROOT, 'locale')]
USE_I18N = True
USE_L10N = True
USE_TZ = True
```

**Comment by NyanKiyoshi** [comment]
Hi,
You need to add shipping methods in the Saleor dashboard.

**Comment by NyanKiyoshi** [comment]
@Jisanbd whether your browser is set to have English as preferred language, instead of German, whether you need to clear you cookies. Let me know.

For instance, in Firefox you can set your preferred language in the settings, under the languages section:
![image](https://user-images.githubusercontent.com/6186720/51834356-55503900-22fa-11e9-80c4-a3d11cbc20d5.png)

About your data being lost, you need to set-up a S3 bucket for your media files. For that, please refer to the [S3 deployment section of the Saleor documentation](http://docs.getsaleor.com/en/latest/deployment/s3.html).

**Comment by Jisanbd** [comment]
I have checked my Firefox setting and it is set to English. so is this the reason page is loaded with english even though default language set to german? is there any way to load the page with default language german?

Moreover I have created bucket in aws s3. From there .jpg image file is showing in the page.But other image file (ex .svg) file  is not loadinng in the page. Please find attached pics

![image1](https://user-images.githubusercontent.com/16919815/52178657-8ab0c700-27d1-11e9-9b4c-fe69291269c1.PNG)

![image2](https://user-images.githubusercontent.com/16919815/52178658-8c7a8a80-27d1-11e9-8450-6cefc120a9d0.PNG)

**Comment by NyanKiyoshi** [comment]
> I have checked my Firefox setting and it is set to English. so is this the reason page is loaded with english even though default language set to german? is there any way to load the page with default language german?

Since the English language is available in your website, and you set your web browser to tell the websites you visit that you preferring pages being shown in English than in German, your website is thus showing it in English. The preferred language order set in your web-browser is telling web pages your language preferences. German users will see your website in German, as their preferred language is German.

> Moreover I have created bucket in aws s3. From there .jpg image file is showing in the page.But other image file (ex .svg) file is not loadinng in the page. Please find attached pics

If you take a look at your developer console, you will see those messages:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://skhanbucket.s3.amazonaws.com/images/cart.svg. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).


It's a CORS issue, you need to change the S3 settings to allow the host/ any host to embed SVG files. 
In your S3 bucket, under permissions and CORS, put:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

**Comment by Jisanbd** [comment]
I would like to configure ssl for deployed saleor in AWS elastic beanstalk. For this I am using the following link for SSL configuration. But it is not working.  
https://www.mattbutton.com/2018/08/06/enabling-https-on-elastic-beanstalk-without-a-load-balancer/
ssl.conf file 
```
LoadModule wsgi_module modules/mod_wsgi.so
      WSGIPythonHome /opt/python/run/baselinenv
      WSGISocketPrefix run/wsgi
      WSGIRestrictEmbedded On
      Listen 443
      <VirtualHost *:443>
        SSLEngine on
        SSLCertificateFile "/etc/letsencrypt/live/xxx/fullchain.pem"
        SSLCertificateKeyFile "/etc/letsencrypt/live/xxx/privkey.pem"

        Alias /static/ /opt/python/current/app/static/
        <Directory /opt/python/current/app/static>
        Order allow,deny
        Allow from all
        </Directory>

        WSGIScriptAlias / /opt/python/current/app/xxx/wsgi/__init__.py

        <Directory /opt/python/current/app>
        Require all granted
        </Directory>

        WSGIDaemonProcess wsgi-ssl processes=1 threads=15 display-name=%{GROUP} \
          python-path=/opt/python/current/app:/opt/python/run/venv/lib/python3.6/site-packages:/opt/python/run/venv/lib64/python3.6/site-packages \
          home=/opt/python/current/app \
          user=wsgi \
          group=wsgi
        WSGIProcessGroup wsgi-ssl

      </VirtualHost>
      <VirtualHost *:80>
          RewriteEngine On
          RewriteCond %{HTTPS} off
          RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
      </VirtualHost>  

```
Do I need to add anything in settings.py file.

**Comment by mayank-budhiraja** [comment]
> Finally, I can run the page in AWS beanstalk without any error but the page is not loading properly. I have added the screenshot of the page.
> 
> ![screenshot1](https://user-images.githubusercontent.com/16919815/51426480-c6516b80-1beb-11e9-8f7d-78726dd54b7a.PNG)
> 
> ![screenshot2](https://user-images.githubusercontent.com/16919815/51426481-c9e4f280-1beb-11e9-9ebd-db76768ee600.PNG)
> 
> So this is the current config file inside the. ebextension folder
> 
> 01_install_packages.config:
> 
> ```
> packages:
>   yum:
>     libffi: []
>     libffi-devel: []
>     gcc-c++: []
>     python36-devel: []
>     gcc-gfortran: []
>     readline-devel: []
>     make: []
>     atlas: []
>     blas: []
>     lapack-devel: []
>     blas-devel: []
>     atlas-devel: []
>     libffi-devel: []
>     libjpeg-turbo-devel: []
>     zlib-devel: []
>     cairo-devel: []
>     pango-devel: []
>     postgresql95-devel: []
> ```
> 
> 02_django.config
> 
> ```
> option_settings:
>   aws:elasticbeanstalk:container:python:
>     WSGIPath: saleor/wsgi/__init__.py
> 
> commands:
>   03-update-npm:
>     command: "curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash - ; yum -y install nodejs npm"
> ```
> 
> db-migrate.config
> 
> ```
> container_commands:
>   01_migrate:
>     command: "django-admin.py migrate"
>     leader_only: true
> 
> option_settings:
>   aws:elasticbeanstalk:application:environment:
>     DJANGO_SETTINGS_MODULE: saleor.settings
> ```
> 
> It is difficult to generate webpack-bundle.json . So, I just copied the local one. Am I missing any more steps which cause the page not loading properly?

@Jisanbd I am facing the similar issue while deploying with docker. 

1. I moved static and media files to S3. 
2. DEBUG = False

Error I am getting is "Django Warning Cannot find storefront.js" and when I set DEBUG = True everything works fine. 

Can you help?
