### ISSUE TITLE
Cancelling an unpaid order in Dashboard 2.0 results in a GraphQL error.

### ISSUE THREAD

**Issue by chrisfranklin** [mirumee/saleor#3491]
### What I'm trying to achieve

I'd like to be able to cancel an order that has not been paid from Dashboard 2.0, it works fine it Dashboard 1.0 so I'm assuming it should work in Dashboard 2.0.

### Steps to reproduce the problem
1. Configure Stripe payment gateway (not tested others, might be the same)
2. Purchase product and go through the checkout process, click pay with card and then close the Stripe popup without entering any information.
3. Go to Dashboard 2.0 and find the order.
4. Click the 3 dot menu button then click on cancel order.
5. You will receive an error.
6. Find the order in Dashboard 1.0 and then click cancel order.
7. The order will be successfully be cancelled.

### What I expected to happen
The behaviour of Dashboard 2.0 should match Dashboard 1.0 and the order should be cancelled. 

### Screenshots / Error Messages

> Something went wrong: GraphQL error: ("Cannot delete some instances of model 'Order' because they are referenced through a protected foreign key: 'Payment.order'", <QuerySet [Payment(gateway=stripe, is_active=True, created=2018-12-19 12:49:41.082598+00:00, charge_status=not-charged)]>)

**System information**
Operating system:  MacOS Mojave
Browser: Safari 12.01

**Comment by maarcingebala** [comment]
Thanks for reporting! I'm wondering why we're trying to remove the order as we should never do that for placed orders. Only draft orders that are not finalized can be removed. In the case of regular orders we should only change the status to "canceled".

**Comment by maarcingebala** [comment]
This should be fixed in #3624.
