### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'ENABLE_SSL' python manage.py runserver

### ISSUE THREAD

**Issue by officerebel** [mirumee/saleor#3493]
I try to install with docker.
This tuck forever

so got back into manual installation on osx.

with pipenv as virtualenv.
1) I need to install dajngo prices with is not in the requirements.txt
2) AttributeError: 'Settings' object has no attribute 'ENABLE_SSL'
when try to do python manage.py migrate https://docs.getsaleor.com/en/latest/gettingstarted/installation-macos.html
So cannot install or run the saleor on mac osx. 

### What I'm trying to achieve
Run Saleor with docker or with regualar local installation on osx

### Steps to reproduce the problem
https://docs.getsaleor.com/en/latest/gettingstarted/installation-macos.html
### What I expected to happen
Run the saleor in local port 8000 
<img width="977" alt="schermafbeelding 2018-12-19 om 16 13 59" src="https://user-images.githubusercontent.com/7673074/50228776-0d5bff00-03a9-11e9-9a0c-7bf62eba9d07.png">

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by maarcingebala** [comment]
It takes some time to build the containers for the first time but I'd recommend sticking to Docker. Did docker output any errors?

1. `django-prices` is present in both `requirements.txt` and in `Pipfile` so it should be installed properly by both `pip` or `pipenv`.
2. This error suggests that `DJANGO_SETTINGS_MODULE` is not set. You can try setting it to `saleor.settings` and see if it helps. Also, are you sure that you're using `python` from your virtual environment that you installed all packages in?

Again, I'd recommend trying again with Docker and reporting the errors you encounter (if any).

**Comment by officerebel** [comment]
I Try to build the docker container local and deploy on digital ocean on centos.

Local I do
$pipenv shell 

sudo docker-compose up
Building web
Step 1/35 : FROM python:3.6 as build-python
 ---> 1ec4d11819ad
Step 2/35 : RUN   apt-get -y update &&   apt-get install -y gettext &&   apt-get clean &&   rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> f70fde31e040
Step 3/35 : RUN pip install pipenv
 ---> Using cache
 ---> ae0563a952a6
Step 4/35 : ADD Pipfile /app/
 ---> Using cache
 ---> a7c53b4792da
Step 5/35 : ADD Pipfile.lock /app/
 ---> Using cache
 ---> e3bbb3d0963f
Step 6/35 : WORKDIR /app
 ---> Using cache
 ---> ab2c58177796
Step 7/35 : RUN pipenv install --system --deploy --dev
 ---> Running in feda514bba80
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 527, in _parse_pipfile
    return tomlkit.parse(contents)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/tomlkit/api.py", line 49, in parse
    return Parser(string).parse()
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/tomlkit/parser.py", line 146, in parse
    key, value = self._parse_table()
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/tomlkit/parser.py", line 965, in _parse_table
    values.append(_key, item)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/tomlkit/container.py", line 139, in append
    raise KeyAlreadyPresent(key)
tomlkit.exceptions.KeyAlreadyPresent: Key "stripe" already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/toml/decoder.py", line 456, in loads
    multibackslash)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/toml/decoder.py", line 728, in load_line
    raise ValueError("Duplicate keys!")
ValueError: Duplicate keys!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1751, in do_install
    pre = project.settings.get("allow_prereleases")
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 557, in settings
    return self.parsed_pipfile.get("pipenv", {})
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 509, in parsed_pipfile
    parsed = self._parse_pipfile(contents)
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 531, in _parse_pipfile
    return toml.loads(contents)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Duplicate keys! (line 164 column 1 char 3923)
ERROR: Service 'web' failed to build: The command '/bin/sh -c pipenv install --system --deploy --dev' returned a non-zero code: 1

**Comment by jxltom** [comment]
It looks like there is a duplicate stripe package in your Pipfile

**Comment by officerebel** [comment]
Removed it 
now again
Step 7/35 : RUN pipenv install --system --deploy --dev
 ---> Running in a9e1585d7d1b
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    Your Pipfile.lock (e8f71d) is out of date. Expected: (a48e30).
sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1874, in do_install
    keep_outdated=keep_outdated
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1192, in do_init
    raise exceptions.DeployException
  File "/usr/local/lib/python3.6/site-packages/pipenv/exceptions.py", line 168, in __init__
    PipenvUsageError.__init__(message=fix_utf8(message), extra=extra, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'self'
ERROR: Service 'web' failed to build: The command '/bin/sh -c pipenv install --system --deploy --dev' returned a non-zero code: 1

**Comment by Pacu2** [comment]
Could you please update your Pipfile.lock? `Your Pipfile.lock (e8f71d) is out of date. Expected: (a48e30).`

**Comment by officerebel** [comment]
ok ons step further ;-)(saleor) bash-3.2$ docker-compose up
saleor_redis_1 is up-to-date
Starting saleor_db_1 ... 
Starting saleor_db_1 ... error

ERROR: for saleor_db_1  Cannot start service db: b'driver failed programming external connectivity on endpoint saleor_db_1 (bdbd0377a98d5696d9007b182e7a835f09a3111f1b118ef069c56a7c0898a4a0): Error starting userland proxy: Bind for 0.0.0.0:5432 failed: port is already allocated'

ERROR: for db  Cannot start service db: b'driver failed programming external connectivity on endpoint saleor_db_1 (bdbd0377a98d5696d9007b182e7a835f09a3111f1b118ef069c56a7c0898a4a0): Error starting userland proxy: Bind for 0.0.0.0:5432 failed: port is already allocated'
ERROR: Encountered errors while bringing up the project.

**Comment by jxltom** [comment]
It looks like port ```5432``` is already used in your system.

**Comment by Pacu2** [comment]
how about `http://localhost:8000`?

**Comment by officerebel** [comment]
http://localhost:8000

Request Method: | GET
-- | --
http://localhost:8000/
2.1.4
ProgrammingError
relation "django_session" does not exist LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...                                                              ^
/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py in _execute, line 85
/usr/local/bin/python
3.6.7
['/app',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages',  '/app']
di, 25 Dec 2018 15:31:37 +0100

**Comment by officerebel** [comment]
I had to stop my local postgres server 
:It looks like port 5432 is already used in your system. 
Now It seems like is needs the postgres server.
I changed the database name. 
Could that be the case? Need to change the database name in docker files too?

**Comment by jxltom** [comment]
Have you ever run ```python manage.py migrate``` to migrate your database?

**Comment by officerebel** [comment]
yes i followed this https://docs.getsaleor.com/en/latest/customization/docker.html?highlight=docker

http://localhost:8000
Request Method: | GET
-- | --
http://localhost:8000/
2.1.4
ProgrammingError
relation "django_session" does not exist LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...                                                              ^
/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py in _execute, line 85
/usr/local/bin/python
3.6.7
['/app',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages',  '/app']

docker-compose up
terminal output.
^C(saleor2) MacBook-Pro-15-Officerebel:saleor timvogt$ docker-compose up
Starting saleor_redis_1 ... done
Starting saleor_db_1    ... done
Starting saleor_web_1    ... done
Starting saleor_celery_1 ... done
Attaching to saleor_db_1, saleor_redis_1, saleor_celery_1, saleor_web_1
db_1      | 2018-12-25 14:51:25.347 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1      | 2018-12-25 14:51:25.347 UTC [1] LOG:  listening on IPv6 address "::", port 5432
redis_1   | 1:C 25 Dec 2018 14:51:25.317 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1   | 1:C 25 Dec 2018 14:51:25.318 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1   | 1:C 25 Dec 2018 14:51:25.318 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
db_1      | 2018-12-25 14:51:25.351 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
redis_1   | 1:M 25 Dec 2018 14:51:25.320 * Running mode=standalone, port=6379.
redis_1   | 1:M 25 Dec 2018 14:51:25.320 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1   | 1:M 25 Dec 2018 14:51:25.320 # Server initialized
redis_1   | 1:M 25 Dec 2018 14:51:25.320 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
db_1      | 2018-12-25 14:51:25.371 UTC [25] LOG:  database system was interrupted; last known up at 2018-12-25 14:47:19 UTC
redis_1   | 1:M 25 Dec 2018 14:51:25.320 * DB loaded from disk: 0.000 seconds
redis_1   | 1:M 25 Dec 2018 14:51:25.320 * Ready to accept connections
db_1      | 2018-12-25 14:51:25.616 UTC [25] LOG:  database system was not properly shut down; automatic recovery in progress
db_1      | 2018-12-25 14:51:25.618 UTC [25] LOG:  redo starts at 0/17E7230
db_1      | 2018-12-25 14:51:25.618 UTC [25] LOG:  invalid record length at 0/17E7268: wanted 24, got 0
db_1      | 2018-12-25 14:51:25.618 UTC [25] LOG:  redo done at 0/17E7230
db_1      | 2018-12-25 14:51:25.643 UTC [1] LOG:  database system is ready to accept connections
web_1     | Performing system checks...
web_1     | 
celery_1  |  
celery_1  |  -------------- celery@008facdb311f v4.2.1 (windowlicker)
celery_1  | ---- **** ----- 
celery_1  | --- * ***  * -- Linux-4.9.125-linuxkit-x86_64-with-debian-9.6 2018-12-25 15:51:30
celery_1  | -- * - **** --- 
celery_1  | - ** ---------- [config]
celery_1  | - ** ---------- .> app:         saleor:0x7fae6525db38
celery_1  | - ** ---------- .> transport:   redis://redis:6379/1
celery_1  | - ** ---------- .> results:     
celery_1  | - *** --- * --- .> concurrency: 4 (prefork)
celery_1  | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
celery_1  | --- ***** ----- 
celery_1  |  -------------- [queues]
celery_1  |                 .> celery           exchange=celery(direct) key=celery
celery_1  |                 
celery_1  | 
celery_1  | [tasks]
celery_1  |   . saleor.account.emails.send_account_delete_confirmation_email
celery_1  |   . saleor.account.emails.send_password_reset_email
celery_1  |   . saleor.core.analytics.ga_report
celery_1  |   . saleor.dashboard.emails.send_promote_customer_to_staff_email
celery_1  |   . saleor.dashboard.emails.send_set_password_email
celery_1  |   . saleor.order.emails.send_fulfillment_confirmation
celery_1  |   . saleor.order.emails.send_fulfillment_update
celery_1  |   . saleor.order.emails.send_order_confirmation
celery_1  |   . saleor.order.emails.send_payment_confirmation
celery_1  |   . saleor.product.tasks.update_variants_names
celery_1  |   . saleor.product.thumbnails.create_category_background_image_thumbnails
celery_1  |   . saleor.product.thumbnails.create_collection_background_image_thumbnails
celery_1  |   . saleor.product.thumbnails.create_product_thumbnails
celery_1  | 
web_1     | System check identified no issues (0 silenced).
celery_1  | [2018-12-25 15:51:30,919: INFO/MainProcess] Connected to redis://redis:6379/1
celery_1  | [2018-12-25 15:51:30,930: INFO/MainProcess] mingle: searching for neighbors
web_1     | 
web_1     | You have 221 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): checkout, discount, django_celery_results, django_prices_openexchangerates, django_prices_vatlayer, impersonate, menu, order, page, payment, product, sessions, shipping, site, sites, social_django.
web_1     | Run 'python manage.py migrate' to apply them.
web_1     | December 25, 2018 - 15:51:31
web_1     | Django version 2.1.4, using settings 'saleor.settings'
web_1     | Starting development server at http://0.0.0.0:8000/
web_1     | Quit the server with CONTROL-C.
celery_1  | [2018-12-25 15:51:31,956: INFO/MainProcess] mingle: all alone
celery_1  | [2018-12-25 15:51:31,978: WARNING/MainProcess] /usr/local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
celery_1  |   warnings.warn('Using settings.DEBUG leads to a memory leak, never '
celery_1  | [2018-12-25 15:51:31,979: INFO/MainProcess] celery@008facdb311f ready.
web_1     | ERROR django.security.DisallowedHost Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS. [PID:12:Thread-3]
web_1     | ERROR django.security.DisallowedHost Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS. [PID:12:Thread-3]
web_1     | WARNING django.request Bad Request: / [PID:12:Thread-3]
web_1     | WARNING django.request Bad Request: / [PID:12:Thread-3]
web_1     | WARNING django.server "GET / HTTP/1.1" 400 77133 [PID:12:Thread-3]
web_1     | WARNING django.server "GET / HTTP/1.1" 400 77133 [PID:12:Thread-3]
web_1     | WARNING django.server "GET / HTTP/1.1" 400 77133 [PID:12:Thread-3]

**Comment by officerebel** [comment]
Perhaps I should download new saleor project run it in  docker  and add the changed an dcustorized files inside?

**Comment by jxltom** [comment]
```
web_1 | You have 221 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): checkout, discount, django_celery_results, django_prices_openexchangerates, django_prices_vatlayer, impersonate, menu, order, page, payment, product, sessions, shipping, site, sites, social_django.
web_1 | Run 'python manage.py migrate' to apply them.
```

From your output, it looks like you didn't migrate the database.

**Comment by officerebel** [comment]
few!😁👍 Now try to deploy to digital ocean. 

- [ ]  deploy to digital ocean. 
- [ ]  use sendgrid. 
- [ ]  make payment system work (molie).

**Comment by officerebel** [comment]
got the same as https://github.com/mirumee/saleor/issues/2694
Any tips?

And saleor is really slow in loading in the browser now.
celery_1  | ERROR saleor.core.utils Failed to generate thumbnails [PID:13:MainThread]
celery_1  | [2018-12-25 22:48:05,101: ERROR/ForkPoolWorker-2] Failed to generate thumbnails
celery_1  | [2018-12-25 22:48:05,094: INFO/MainProcess] Received task: saleor.product.thumbnails.create_category_background_image_thumbnails[aa463fbe-cea3-4298-804e-3e6e30201916]  
celery_1  | [2018-12-25 22:48:08,016: INFO/MainProcess] Received task: saleor.product.thumbnails.create_category_background_image_thumbnails[362c1eef-9788-405a-8458-b5e2887a44d6]  
celery_1  | [2018-12-25 22:48:08,252: INFO/MainProcess] Received task: saleor.product.thumbnails.create_category_background_image_thumbnails[e58113cd-735b-44a4-8eb9-49bfd3a5d5be]  
celery_1  | [2018-12-25 22:48:08,306: INFO/MainProcess] Received task: saleor.product.thumbnails.create_category_background_image_thumbnails[8dff8649-031e-4220-b1a7-980a2b03b662]  
celery_1  | [2018-12-25 22:48:08,318: INFO/ForkPoolWorker-2] Task saleor.product.thumbnails.create_category_background_image_thumbnails[35ac8ed8-7530-44e5-bcad-d6dfc9c61cb3] succeeded in 12.458174270002928s: None
celery_1  | [2018-12-25 22:48:08,767: INFO/MainProcess] Received task: saleor.product.thumbnails.create_category_background_image_thumbnails[6c23554d-af85-4018-a895-816e1462a0cd]  
celery_1  | [2018-12-25 22:48:08,827: INFO/MainProcess] Received task: saleor.product.thumbnails.create_category_background_image_thumbnails[0d852e94-bf84-479c-bd91-de94fca41ee3]
