### ISSUE TITLE
OverflowError uploading image - Python int too large to convert to C ssize_t

### ISSUE THREAD

**Issue by devharis** [mirumee/saleor#3495]
### What I'm trying to achieve
Upload a image to product in Dashboard

### Steps to reproduce the problem
1. Create a product
2. Navigate to Change Image
3. Upload image I provided
4. Image gets saved to database and a Overflow exception is thrown
5. Product isn't reachable as Overflow exception is thrown when it loads image in detail page

#### Payload used
![alt text](https://i.imgur.com/EXLRQy7.jpg
)

### What I expected to happen
Successfully uploaded image

### Screenshots
![alt text](https://i.imgur.com/rSyuDpc.png)

**System information**
Operating system: 
Browser: Windows 10 x64

**Comment by maarcingebala** [comment]
I'm on latest master and successfully uploaded the image you provided:
![image](https://user-images.githubusercontent.com/5421321/50232626-c0c8f180-03b1-11e9-8e1a-4d18abd72242.png)

From the stacktrace I can see that the issue maybe related to `Pillow`, image processing library for Python - maybe that's a problem specific to Windows? I would look for a solution in their repository:
https://github.com/python-pillow/Pillow

**Comment by devharis** [comment]
I've uploaded tons of images before without any issue. Yes, the issue is thrown within the library.
Just on this specific image I'm getting this error and i can reproduce it every single time.

I'm also on latest master. I'll create a issue on Pillow repo and see what their response is.

**Comment by maarcingebala** [comment]
OK, so I'm closing this one. You can also link to this issue in Pillow repo so we have some reference between them.
