### ISSUE TITLE
Validation errors are not displayed for autocomplete/select fields

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3496]
Validation errors are not rendered for autocomplete selection fields in the Dashboard 2.0. This happens for example when creating a product without some of the required fields.

### Steps to reproduce the problem
1. Go to the "Create product" view in the Dashboard 2.0.
2. Fill only the title and click "save" button.
3. A validation error is only shown for the "description" field.
4. Inspect the GraphQL response - there are more validation errors that were not rendered.

If we pass this set of variables to the `productCreate` mutation:
```
{
  "availableOn": null,
  "category": "",
  "chargeTaxes": false,
  "isPublished": false,
  "name": "Test",
  "price": 0,
  "productType": ""
}
```

the following errors are returned:
```
"errors": [
        {
          "field": "productType",
          "message": "This field cannot be null.",
          "__typename": "Error"
        },
        {
          "field": "description",
          "message": "This field cannot be blank.",
          "__typename": "Error"
        },
        {
          "field": "category",
          "message": "This field cannot be null.",
          "__typename": "Error"
        }
]
```

But only the "description" error is rendered in UI:

![image](https://user-images.githubusercontent.com/5421321/50278615-c83ada00-0447-11e9-8508-9d78265c98e2.png)

**Comment by korycins** [comment]
On `Add Variant` section, when I try to fill up an attribute field with the value that is not defined in a given attribute. I am getting an error during saving a variant.
Graphql returns errors `{"errors": [{"field": "attributes:abc", "message": "This field cannot be blank.", "__typename": "Error"}]`
