### ISSUE TITLE
Enable add address from django-admin

### ISSUE THREAD

**Issue by imakin** [mirumee/saleor#350]
I failed login using admin@example.com/admin, fresh install doesn't provide any admin user. but creating user from django-admin needs to create address first, which is unavailable from django admin.
adding this Address model to `saleor/userprofile/admin.py` will do it. 
```
from .models import Address
admin.site.register(Address)
```

**Comment by patrys** [comment]
The supplied login/password is only valid for Heroku deployments. You can create a new admin user by running:

```
python manage.py createsuperuser
```

As for the actual bug you found: addresses should be optional and that is fixed now. There is no reason to expose them in the admin UI though. It's not intended to be used as a store management interface.
