### ISSUE TITLE
Product/Variant images 60x60 not loading in cart and checkout

### ISSUE THREAD

**Issue by devharis** [mirumee/saleor#3501]
### What I'm trying to achieve
Show variant/product image in cart and checkout

### Steps to reproduce the problem
1. Add image to your product and set it to variant as well
2. Go to storefront and add product to cart
3. Image in cart doesn't load, only shows placeholder 60x60

Stacktrace:
```
Traceback (most recent call last):
  File "....\saleor\product\templatetags\product_images.py", line 90, in get_thumbnail
    thumbnail = getattr(image_file, method)[used_size]
AttributeError: 'ProductImage' object has no attribute 'thumbnail'
ERROR saleor.product.templatetags.product_images Thumbnail fetch failed [PID:14208:Thread-4]
```

### What I expected to happen
Should show variant image

### Screenshots

**Checkout**
![alt text](https://i.imgur.com/wuM15c7.png)

**Cart**
![alt text](https://i.imgur.com/lEsJzxv.png)

**System information**
Operating system: 
Browser: Windows 10, Linux, Mac

**Comment by Pacu2** [comment]
Is this resolved? From the traceback it looks like some recent changes  with the `get_thumbnail` function broke something

**Comment by devharis** [comment]
Its resolved. Seems to be due to some merging conflicts.
