### ISSUE TITLE
Settings to enable/disable add to cart

### ISSUE THREAD

**Issue by kwatog** [mirumee/saleor#3503]
Is there a settings that will allow disabling/enabling the add to cart button? I know I can set the available stock to zero to do this. But then again, I don't want to show the product as out of stock.

Use-case for this is when you want to show your customers your upcoming product and its variants. Another is having your saleor act as a product catalog.

**Comment by maarcingebala** [comment]
There is no such thing currently, as you said, the only way to achieve that is by decreasing the stock quantity to zero. Actually, I think that this is quite an interesting feature. I'm not sure if or how other e-commerce platforms support it, but we could think of adding some kind of "preview" for customers.
