### ISSUE TITLE
Types of ProductImages

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#3504]
If we are talking about the real world e-commerce, it's more and more common that one provides various types of images. 

For fashion niche, one could provide a nonmodel photo, a photo of the product on the model, close upon the material, or some other representing the preferred usage, eg. "premium" type, which should be used as the main thumbnail whenever possible.

At this moment we have only "Product Images" and "Variant Images" with no ability to set the main image of the product/variant. 

My proposition is to introduce a new field on the `ProductImage` which could be called `usage_type` or `character_code`, which would store the information of what's the style of the photo, so one can easily manipulate the photos order on the storefront.

In the API I'd like to receive something like:
```
media: [
    {
        "media_type": ["IMAGE", "VIDEO", "GIF"],
        "character_code": ["STYLE", "NON_MODEL", "PREMIUM", "CLOSEUP"]
        "path": "somelink.jpg",
        "alt": ...
    },
...
```

**Comment by maarcingebala** [comment]
Currently, the first product image is used as the main thumbnail, but I'm not sure if that's clear enough from the UI/UX perspective, maybe we could improve that.

About the image types, I don't clearly see how else we could support that in Saleor except for just adding the model field? Isn't it something outside of Saleor's scope and should be implemented by those who really need this in their specific use-cases?

**Comment by mihaildragos** [comment]
Also, I think it might be useful if the images would be attributed to specific product variants and by choosing one variant the attributed image should be displayed (selected). For example if a product has different colour variants when the specified colour is selected the image should change to the one with the chosen colour.

**Comment by maarcingebala** [comment]
We support assigning images to particular variants in the backend, but non of our storefronts currently supports that. Will be added soon in Storefront 2.0 (see mirumee/saleor-storefront repo).
