### ISSUE TITLE
Client Product Reviews

### ISSUE THREAD

**Issue by EmmanuelPerezP** [mirumee/saleor#3513]
I looked everywhere in the docs and some of the code but i didn't found an implementation of user reviews on products, i think user reviews is one of the core features an e-commerce site should have, it adds trust to the client and alot of other e-commerce solutions has them, have you guys considered adding them?, and if there is a reason why you guys haven't done it yet, do you have any rough suggestions in how i could implement them and dont break anything?
thanks

**Comment by maarcingebala** [comment]
Related topic on Spectrum: https://spectrum.chat/saleor?thread=5ccbafa6-4125-43cd-8d58-da315891a3c9
