### ISSUE TITLE
Inefficient prefetch_related calling

### ISSUE THREAD

**Issue by hassanzadeh** [mirumee/saleor#3514]
Hey Guys,
I was looking at your code, I believe in some places your code is inefficient when you call the prefetch_related function. For example, in proudct/models.py, in the products_for_homepage function you have:
products = products.prefetch_related(
        'translations', 'images', 'variants__variant_images__image')
products = products.filter(collections=homepage_collection)
These two lines lead to two different queries, the latter will render the cached result useless, 
See the notes from Django documentation https://docs.djangoproject.com/en/2.1/ref/models/querysets/

```Note

Remember that, as always with QuerySets, any subsequent chained methods which imply a different database query will ignore previously cached results, and retrieve data using a fresh database query. So, if you write the following:

>>> pizzas = Pizza.objects.prefetch_related('toppings')
>>> [list(pizza.toppings.filter(spicy=True)) for pizza in pizzas]
…then the fact that pizza.toppings.all() has been prefetched will not help you. The prefetch_related('toppings') implied pizza.toppings.all(), but pizza.toppings.filter() is a new and different query. The prefetched cache can’t help here; in fact it hurts performance, since you have done a database query that you haven’t used. So use this feature with caution!

Also, if you call the database-altering methods add(), remove(), clear() or set(), on related managers, any prefetched cache for the relation will be cleared.```

**Comment by Pacu2** [comment]
I don't think that's the same case, in the docs you've linked, one is running `.filter()` on each iteration of the `pizzas` queryset, and that's the reason why the cached result is not used.

Django's querysets are lazy by nature, and no database hit will be fired until you evaluate the queryset.
From Django docs:

> Internally, a QuerySet can be constructed, filtered, sliced, and generally passed around without actually hitting the database. No database activity actually occurs until you do something to evaluate the queryset.

**Comment by hassanzadeh** [comment]
Makes sense,
Thanks for the explanation :)
