### ISSUE TITLE
npm run build-schema not working

### ISSUE THREAD

**Issue by zadigus** [mirumee/saleor#3517]
### What I'm trying to achieve

I am adapting your software to my current needs (multi-shops, multi-vendors). To do so, I need to upgrade your graphql api. I just started working on this project, so I did some minor changes to the graphql api in order to test its generation out. After applying my minor changes, I did

### Steps to reproduce the problem
1. Run

```
npm run build-schema
``` 

### What I expected to happen

I expected an updated graphql schema to be located under `saleor/graphql/schema.graphql`.  Instead, I get this:

```
Unknown command: 'get_graphql_schema'. Did you mean graphql_schema?
Type 'manage.py help' for usage.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor@0.0.0 build-schema: `python manage.py get_graphql_schema > saleor/graphql/schema.graphql`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the saleor@0.0.0 build-schema script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mihl\AppData\Roaming\npm-cache\_logs\2018-12-27T09_09_50_047Z-debug.log
```
And indeed, if I run

```
python manage.py help
```

I don't see `get_graphql_schema` in the list. Instead I see `graphql_schema`. It seems like that command doesn't work the way it used to in previous saleor releases.

**System information**
Operating system: Windows
Browser: N/A
Saleor release: 2.1.0
graphene-django: 2.2.0
graphene: 2.1.3

**Comment by maarcingebala** [comment]
Do you have `saleor.graphql` in your `INSTALLED_APPS` in `settings.py`? `get_graphql_schema` is a [custom command implemented by us](https://github.com/mirumee/saleor/blob/master/saleor/graphql/management/commands/get_graphql_schema.py). I can confirm that it works on `master`.

**Comment by zadigus** [comment]
Ok. No we have our own graphql api which inherits from yours. I didn't notice that the command was implemented by your app. I'll enable it again. Thank you!

_________________________________________________________________________

Dr Laurent Michel

Product Owner
http://www.softozor.ch


077 428 83 94

**Comment by maarcingebala** [comment]
Our command is different than the built-in, as it produces schema in SDL format which is way more readable and it allows integration with Apollo tooling.
