### ISSUE TITLE
ERROR django.security.DisallowedHost Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.

### ISSUE THREAD

**Issue by officerebel** [mirumee/saleor#3521]
### What I'm trying to achieve
Deploy docker local and prepare for deploy on digital ocean centos

### Steps to reproduce the problem
1. docker-compose up
open http://localhost:8000

### What I expected to happen
see the page running in docker on http://127.0.0.1:8000/

### Screenshots

Request Method: | GET
-- | --
http://127.0.0.1:8000/
2.1.4
ProgrammingError
relation "django_site" does not exist LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...                                                              ^
/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py in _execute, line 85
/usr/local/bin/python
3.6.8
['/app',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages',  '/app']
do, 27 Dec 2018 22:03:08 +0100

Request Method: | GET
-- | --
http://127.0.0.1:8000/
2.1.4
ProgrammingError
relation "django_site" does not exist LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...                                                              ^
/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py in _execute, line 85
/usr/local/bin/python
3.6.8
['/app',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages',  '/app']
do, 27 Dec 2018 22:03:08 +0100

http://0.0.0.0:8000

Request Method: | GET
-- | --
http://0.0.0.0:8000/
2.1.4
DisallowedHost
Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
/usr/local/lib/python3.6/site-packages/django/http/request.py in get_host, line 106
/usr/local/bin/python
3.6.8
['/app',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages',  '/app']
do, 27 Dec 2018 22:09:12 +0100

**System information**
Operating system: 
Browser:

**Comment by hairychris** [comment]
The first error is caused by needing to run the migrations, not sure if the later errors are then related.

**Comment by officerebel** [comment]
It seems like it wants the old settings.
When I migrate
python manage.py migrate
ValueError: Invalid currency: 'EUR' (expected 'USD')

 docker-compose run web python3 manage.py migrate
ValueError: Invalid currency: 'USD' (expected 'EUR')

my settings file
DEFAULT_COUNTRY = os.environ.get('DEFAULT_COUNTRY', 'nl')
DEFAULT_CURRENCY = os.environ.get('DEFAULT_CURRENCY', 'EUR')
DEFAULT_DECIMAL_PLACES = get_currency_fraction(DEFAULT_CURRENCY)
DEFAULT_MAX_DIGITS = 12
AVAILABLE_CURRENCIES = [DEFAULT_CURRENCY]
COUNTRIES_OVERRIDE = {
    'EU': pgettext_lazy(
        'Name of political and economical union of european countries',
        'European Union')}

**Comment by hairychris** [comment]
Pull the latest version from master, that bug was fixed in https://github.com/mirumee/saleor/pull/3506

There is also a workaround if you'd rather use the released version, set DEFAULT_CURRENCY to USD until after you have run the migrations and then change it back to EUR, this should be fine and other uses were doing it but if it causes any weirdness save yourself the hassle and pull master version.
