### ISSUE TITLE
Order confirmation email is sent before order is paid

### ISSUE THREAD

**Issue by tiberiuichim** [mirumee/saleor#3527]
### What I'm trying to achieve

Avoid customer and staff confusion related to orders. Sometimes the customers just want to see the total cost of the product (shipment, taxes and so), they should not receive a confirmation email when they have aborted their payment process. Staf needs to call those customers, to check if they have really wanted to place the order, or just abandoned it.

### Steps to reproduce the problem
1. Make a checkout, get to the payment gateway selection form
2. Check your email as a customer, you should have received an email with the order confirmation

### What I expected to happen
The order confirmation email is sent when I've completed the payment process

### Screenshots

**System information**
Operating system: Linux, Windows
Browser: not relevant

This method is called from the "summary_with_shipment_view". It handles order creation and redirection to the actual payment view. But sending the email here is too soon. This should be done at the end of the payment process. If the user has an account where they have entered credit card data into the website, and recorded that data in the website, then it makes sense to have this behaviour. But if the user is redirected to the payment processor, then this is way too soon.

<pre>
def handle_order_placement(request, cart):
    """Try to create an order and redirect the user as necessary.
    This is a helper function.
    """
    try:
        order = create_order(
            cart=cart,
            tracking_code=analytics.get_client_id(request),
            discounts=request.discounts,
            taxes=get_taxes_for_cart(cart, request.taxes))
    except InsufficientStock:
        return redirect('cart:index')

    # happens when a voucher is now invalid
    if not order:
        msg = pgettext('Checkout warning', 'Please review your checkout.')
        messages.warning(request, msg)
        return redirect('checkout:summary')

    cart.delete()
    order.events.create(type=OrderEvents.PLACED.value)
    send_order_confirmation.delay(order.pk)
    order.events.create(
        type=OrderEvents.EMAIL_SENT.value,
        parameters={
            'email': order.get_user_current_email(),
            'email_type': OrderEventsEmails.ORDER.value})
return redirect('order:payment', token=order.token)
</pre>

**Comment by maarcingebala** [comment]
@fowczarek We'll have to look into this.

**Comment by maarcingebala** [comment]
@tiberiuichim This is the default flow that we want to have. We send two emails during checkout flow - first when an order is placed and second when succesfull payment is made.

Order summary with a total amount for an order is displayed on the right side in the Storefront 1.0 ("order review"):
![image](https://user-images.githubusercontent.com/5421321/51113860-d3ddae80-1803-11e9-8bc3-f709804b3558.png)
