### ISSUE TITLE
Packaging support

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3529]
We should be able to predefine shipping packages which should define:
- Dimensions (Height, width, depth)
- The weight of an empty package

Loose idea - as we create the packages, we could rely on pulling the rates from carriers website.

**Comment by adrienshen** [comment]
Second this. To give some context. We're building a furniture e-commerce app and dimensions on product variants is super important. We're adding this ourselves, but would be great if can be supported natively one day.

**Comment by jyoost** [comment]
Anyone interested in pursuing this project to present a finished project to miramee please contact me as I already have 80% of this complete jyoost@gmail.com

**Comment by NyanKiyoshi** [comment]
@jyoost feel free to send an email to hello@mirumee.com 👍
