### ISSUE TITLE
Click & collect support

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3530]
Shipping methods could be extended to contain "Click and collect" option.

**Comment by Jufik** [comment]
We've been thinking this around actualy, we're thinking about twisting around views to create a specific shipping method which lock down the address. 
Any suggestion or pattern is welcomed.

**Comment by MikkelScheike** [comment]
A very good idea. Things to consider (through real experience): 
- Clearly specify that the order is not ready to pick up before they receive an order confirmation. Many expect the order to be ready right after they put in the order
- Potential multiple pickup points
- Custom pricing for pickup
