### ISSUE TITLE
Kombu 4.2.2 is missing in Pypi and make the CI failing

### ISSUE THREAD

**Issue by jxltom** [mirumee/saleor#3533]
I reported it in upstream https://github.com/celery/kombu/issues/975, if they are not going to fix it, we can update the Pipfile.lock in our side.

**Comment by maarcingebala** [comment]
We've already updated `Pipfile.lock` in PR #3505, could you take a look?

**Comment by jxltom** [comment]
Thanks for mention it. I've left some comments in https://github.com/mirumee/saleor/pull/3505#issuecomment-451089083.

**Comment by maarcingebala** [comment]
Fixed in #3505
