### ISSUE TITLE
Classic Storefront Changes

### ISSUE THREAD

**Issue by pwgryglak** [mirumee/saleor#3534]
**HOMEPAGE**
DESKTOP:
- [x] Search bar - change style
- [x] Change basket icon
- [x] Adjust color pallette
- [x] Change Footer

MOBILE:
- [x] Fix PWA STOREFRONT message - shows under navi bar
- [x] Adjust color pallette
- [x] Change Icons
- [x] Change Footer

**CATEGORY PAGE**
DESKTOP:
- [x] Change Breadcrumbs
- [x] Change style of Filters
- [ ] Add number of products

MOBILE: 
- [ ] Change Filters behaviour
- [ ] Add number of products

**PRODUCT PAGE**
DESKTOP: 
- [ ] Change gallery behaviour
- [ ] Adjust Colors

MOBILE: 
- [ ] Add gallery indicators
- [ ] Adjust Colors

**CHECKOUT**
- [x] Adjust style

Designs are here:
https://www.figma.com/file/DgsfSV7zP0gFlBMyEKu9Itad/NORMAL-SALEOR-STOREFRONT?node-id=0%3A1

**Comment by maarcingebala** [comment]
Thanks, @pwgryglak. These are the changes that we want to apply to the old Django-based storefront to refresh its appearance a bit before we entirely move on to Storefront 2.0.

**Comment by Pacu2** [comment]
I'd opt for a simple change of cards appearance to make them look like the ones in the new storefront.
That should be quite an easy task
