### ISSUE TITLE
Webpack cannot build 'dashboard-next' on EC2 t2.micro

### ISSUE THREAD

**Issue by pshangov** [mirumee/saleor#3536]
I've been trying for a while now to get Saleor to run on AWS Beanstalk. I'm currently stuck on getting `npm build-assets` to work. When trying to build "dashboard-next", webpack gets stuck at "92% chunk asset optimization TerserPlugin" (this appears to be the JS minification stage), with memory usage maxed out at 100%. The other three entry points build fine. Node.js is up-to-date (version 10+) .

The EC2 instance I'm currently using is t2.micro with 1GB memory. Do you know how much memory is required to build the new dashboard? Any ideas how to optimize the build process so it can complete on low-memory environments?

**Comment by patrys** [comment]
Hello, I highly recommend that you do not build assets on your target machine. It requires a lot of memory and computing power that the server is better off using to server web requests. This is especially trie for metered instances in the `t2` tier as you only get so many resource credits to use each hour. Consider running your build locally or—even better—in a dedicated CI/CD environment like Travis or Circle CI and only push the resulting files to the EC2 instance.

**Comment by pshangov** [comment]
OK thanks, I'll look into what I can use for CI/CD on AWS (my goal is to only use infrastructure supported by CloudFormation).

**Comment by patrys** [comment]
Maybe AWS CodeDeploy would work for you?
