### ISSUE TITLE
Avalara integration

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3539]
Currently, we support VAT calculations for EU with Vatlayer and manual tax configuration through the dashboard. Our goal, however, is to provide integration with third-party service and delegate all tax calculations there. [Avalara](https://developer.avalara.com/) seems to be the most promising option. 

We have to investigate how we could integrate it with Saleor. Since Avalara is a paid solution, we may want to provide it optionally and leave the current implementation as the default one.

**Comment by patrys** [comment]
One note: AFAIK Avalara (unlike Vatlayer) does not expose its ruleset. Instead we have to report each transaction as it happens and update the fields according to Avalara's response. Their service tiers are based around the number of transactions served over a time period (whereas for Varlayer we only do one API call a day).

**Comment by beatboxchad** [comment]
For USA sales taxes, a Saleor-based project I work on now uses a custom dashboard area where sales tax rates are entered manually state-by-state. This has worked for them for awhile, but an integration would obviously remove the manual labor for the staff user. 

Maybe something simple and naive like that would be a base feature, and the integration could be optional to automate it?

**Comment by krzysztofwolski** [comment]
Bump - we are looking forward to this integration.
ATM we are using tax calculation thru Stripe, but thats not sufficient solution for us.

**Comment by maarcingebala** [comment]
@krzysztofwolski Could you or someone from your team briefly describe your use-case for Avalara? Just to better understand where in Saleor we would have to plug it. Or is there a single standard workflow for this integration?

**Comment by krzysztofwolski** [comment]
ATM our client displays prices with taxes on the checkout page. The whole cart is sent to stripe which calculates tax for all items and then this info is presented to the user. 
Problems with this approach:
- every cart change triggers an additional call to stripe which means a performance hit
- product price displayed in storefront does not include taxes. ATM we only sell in the USA and it's not a problem, but we want to go international and in Europe law enforces us to display prices with taxes included

What I need:
- integration with Avalara which will dynamically pull prices with taxes
- taxes need to be automatically adjusted to the country of the visitor
- caching solution which will prevent us from doing too many calls to the API (afaik API is priced by the number of calls)
- built-in solution for cart, which will save tax data in it
- tax rates need to be also remembered in order object

What would be nice:
- Update google feed to use tax rates: https://github.com/mirumee/saleor/issues/3832

**Comment by patrys** [comment]
Regarding the law, if we only sell to businesses (like the project we talk about), we could get away with net prices only until checkout but I don't think Saleor can make that assumption.

**Comment by krzysztofwolski** [comment]
Note: not sure how this should work in the USA, where each state has different tax laws. Probably in this situation taxes are displayed only during checkout, after providing a shipping address.

**Comment by patrys** [comment]
Yes, for the US it's expected to only display taxes during checkout.

**Comment by bvanvooren** [comment]
@krzysztofwolski - By chance, would you be able to share the Stripe / Sales Tax code you mentioned above or maybe suggest the best place in the Saleor codebase to integrate our own similar Stripe API code?  We're working on a U.S.-only project w/ Stripe, and the solution you mentioned above would do the job.  We're still getting up to speed on the architecture.  Thank you -- sorry for the off-topic post.
