### ISSUE TITLE
Order model improvements proposal

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#354]
In my opinion `Order` model should have `total` field with the default store currency value and we should replace `anonymous_user_email` field by just `email` (always required filled) and maybe with property `is_anonymous` (`user is None`).

Now we don't have possibility to filter, analysis orders by total because `get_total` is complicated function working on iterator not accessible from database. Mailing campaign and simple sorting will be more simple with email approach.

**Comment by patrys** [comment]
Yes, we do need to store `total` at the order level. :+1: on the email change as well. Not sure we need a separate property for checking whether order is anonymous or not. Checking the user should be enough.

**Comment by elwoodxblues** [comment]
Looks like we have it implemented now.
