### ISSUE TITLE
AttributeError: module 'django_filters.widgets' has no attribute 'DateRangeWidget'

### ISSUE THREAD

**Issue by AdamHowardIRL** [mirumee/saleor#3541]
### What I'm trying to achieve
Installation of Saleor on Windows 10.

### Steps to reproduce the problem
1. Run python manage.py migrate 

### What I expected to happen
Migrate application data to database.

I've tried running python -m pip install -r requirments.txt to intstall all of the necessary packages. Unfortunately, this does not istall all of the packages. I have been running python manage.py migrate over and over for a while and have been installing the missing packages manually. I would like to know how I will be able to install the missing attribute 'DateRangeWidget' using pip. I can not find a command. Or any other fix that will allow me to continue installing these packages manually. 

**System information**
Operating system: Windows 10
Browser: Chrome

**Comment by Pacu2** [comment]
What's the version of django_filters you have installed?

**Comment by maarcingebala** [comment]
I suppose that might be a local problem with the environment. I'd like to close this issue as there was no further response. Please reopen if it happens again and we are able to reproduce it.
