### ISSUE TITLE
Support returning user's checkouts in GraphQL API

### ISSUE THREAD

**Issue by jxltom** [mirumee/saleor#3542]
### What I'm trying to achieve

The checkouts (carts) can be associated with a user. But in current GraphQL API, these checkouts are not returned in ```me``` or ```user``` API. This makes gettting existed checkout (cart) for a logged-in user impossible. In the frontend, we have re-create a new cart/shopping bag when cached sessions are cleared.

**Comment by maarcingebala** [comment]
Thanks for opening this issue - this is exactly what we wanted to do as a part of checkout refactoring sprint that starts next week!
