### ISSUE TITLE
Price Field in Dashboard?

### ISSUE THREAD

**Issue by taedori81** [mirumee/saleor#355]
Doesn't accept floating point number like 9.99 in price field in dashboard.
I look up in model.py in product, and looks ok with price = PriceField(
        pgettext_lazy('Product field', 'price'),
        currency=settings.DEFAULT_CURRENCY, max_digits=12, decimal_places=2).
What am I missing?

**Comment by patrys** [comment]
Are you using the latest version of `django-prices`? There was a bug in that package that caused all price fields to require integer input.

**Comment by taedori81** [comment]
Yes I think so.
0.4.0

**Comment by patrys** [comment]
I've just released version 0.4.1 which hopefully fixes that. Please try to reproduce with latest `django-prices` and `prices` and reopen if the problem persists.
