### ISSUE TITLE
Improving translations with consistency, cleanup, and better explanations

### ISSUE THREAD

**Issue by MikkelScheike** [mirumee/saleor#3552]
### What I'm trying to achieve
Assure better and more consistent translations for all current and new languages.

### Describe a proposed solution
There is a need for the translations to be managed so the consistency is higher. Currently, there seem to be strings that has the exact same purpose but has to be translated individually. So if we could merge some of these strings.

There is also inconsistency on words such as e-mail/email, which is randomly used. I do not have any preference, but I certainly think they should be consistent. 

I also feel like descriptions could be optimized to actually explain the context. In general, this is not a problem, but when it comes to shipping, I feel like the descriptions could easily be a sentence longer to assure that nothing is lost in the translation process.

A few of the translations also start off with a line break, which is not really good practice and also makes it hard to get some translations approved by the system if these are missing.

Documentation of overlapping translation, inconsistent use of e-mail/email in this case and strings starting with linebreaks.
![image](https://user-images.githubusercontent.com/10270075/50757986-4f76b300-127a-11e9-86c5-6fb95acb9be9.png)

![image](https://user-images.githubusercontent.com/10270075/50758016-65847380-127a-11e9-9984-5343a3162e5f.png)

![image](https://user-images.githubusercontent.com/10270075/50758112-a9777880-127a-11e9-93a4-0f544606b469.png)

**Comment by MikkelScheike** [comment]
I'll take the liberty to add another example of how confusing translation can be. It looks like a code string, so if i should actually translate it or not is impossible to say. 
Key: tax_amount = (tax_rate * price) / (1 + tax_rate) 
Context: Dashboard site taxes settings form help text
Resource: storefront.po
String Hash: 06653fb8214b9d333f3cc2d361edc319 
![image](https://user-images.githubusercontent.com/10270075/50776725-27f00c80-12b3-11e9-8938-10149087f10c.png)

**Comment by tiberiuichim** [comment]
While on topic, I have another issue, I took a brief look but abandoned it: the sent emails are only partially translated, which, of course, makes the website look unprofessional. The subject is translated, the line of the email body is translated, but wherever the message string is two lines (so a longer literal message id), it's not properly detected and translated. To me, the result html in the compiled template looked fine (identical to the message id in the po file), but there must be some problem I didn't see.

**Comment by MikkelScheike** [comment]
@NyanKiyoshi I think the confusing part is two folded here:

1. Starting with a line change and a tab.
2. The English translation is done with underscores. No under outside development would use it that way. The idea is great, but the actual use case (from the translation) is practically pointless I'd say.
