### ISSUE TITLE
Shared attribute between different product types

### ISSUE THREAD

**Issue by jxltom** [mirumee/saleor#3554]
### What I'm trying to achieve

The attribute couldn't be shared between different product type. Each product type must have its own attributes. How about making same attribute able to be shared by different product types?

I can create a ```productTypeA``` with ```size``` attribute (S, M, L). But if I would like to create another ```productTypeB``` with same ```size``` attribute, I have to create another ```size``` attribute, even they have same values.

Will there have any issue if we change the ```product_type``` and  ```product_variant_type``` of ```Attribute``` to ManyToMany fields?

**Comment by maarcingebala** [comment]
It used to work like that but we've changed it a few months ago - https://github.com/mirumee/saleor/issues/3086. It allowed us building attributes management through the product types in the new Dashboard.

**Comment by jxltom** [comment]
Thanks for reply! If I have so many different product types with one same attribute and additional different attributes. For example:

ProductTypeA: size and weight
ProductTypeB: size and color
ProductTypeC: size and length

I don't want to create three same ```size``` attributes. Any suggestions for solving this? Many thanks.

**Comment by maarcingebala** [comment]
Well, at the moment you can achieve that only by creating three separate size attributes. I'm thinking about the possibility of cloning attributes but it wouldn't help if you wanted to edit their values and would have to do that anyway for every single attribute.

**Comment by mociepka** [comment]
We could introduce an autocomplete input for attributes. You could choose from existed ones if you want to but we won't complicate architecture at the same time.

**Comment by jxltom** [comment]
Besides, I'm quite understand why using m2m relationship of attributes and product types will break the API of the new dashboard?

**Comment by maarcingebala** [comment]
PR #4351 reintroduces standalone attributes that can be shared between different product types.
