### ISSUE TITLE
Removing Product Types and Collections

### ISSUE THREAD

**Issue by MichaelSaah** [mirumee/saleor#3559]
First off, big thanks to the Mirumee team for Saleor. I've spent the past few days customizing it for a project and working with the codebase has been extremely easy.

I'm trying to remove the test product types and collections via the dashboard, but I don't see any interface to do so. Removing products was easy, so I expect such functionality to be in place for other models. I'd rather not have to do it manually via the shell. This is in the old dashboard.

For reference, my fork is off of commit ffd1a03be15c2662f9e1adcaa30f286eaca5cec0.

Happy to provide any other info as needed.

**Comment by Pacu2** [comment]
While on the Collection/Product Type page, click on the three dots in the upper right corner, and there should be a "delete" option listed in the dropdown

**Comment by MichaelSaah** [comment]
Ahah, the debug toolbar was covering it up. I figured I was missing something obvious. Thanks for the quick reply.

**Comment by Pacu2** [comment]
You're welcome!

For usage-related questions you might want to check our community channels: [spectrum](https://spectrum.chat/saleor) and [gitter](gitter.im/mirumee/saleor) (we are planning to migrate to spectrum only eventually)

I think that more folks are active in there and one can get help quicker
