### ISSUE TITLE
'Home page' menu item is active when it shouldn't be

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#3566]
### Steps to reproduce the problem
1. Go to the old dashboard
2. Go to 'navigation' or 'site settings' section
3. Notice that 'home page' menu item is active too

### What I expected to happen
'home page' menu item to be inactive

### Screenshots
<img width="238" alt="zrzut ekranu 2019-01-8 o 11 55 57" src="https://user-images.githubusercontent.com/6833443/50826604-62ea5280-133c-11e9-9106-1163193f12af.png">

**Comment by NyanKiyoshi** [comment]
We need to set the block `body_class`.
