### ISSUE TITLE
Successfully paid orders are no longer redirected to the success page

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#3567]
### What I'm trying to achieve
Get the "Thank you for your order!" message after the user successfully paid.

### Steps to reproduce the problem
1. Make an order;
2. Pay it;
3. It doesn't redirect to `payment_success` anymore.

### What I expected to happen
To get redirected to the `payment_success`.

### References (dead codes):
https://github.com/mirumee/saleor/blob/56b5bce1a127d531d3eb0bfb1daba2f383aed0d7/saleor/order/urls.py#L14-L17

https://github.com/mirumee/saleor/blob/56b5bce1a127d531d3eb0bfb1daba2f383aed0d7/saleor/order/views.py#L151-L157

---

How should we handle the payment success? Should we always say "Thanks for your payment!", or should we redirect the user back to the order?

----
*Issue created from https://github.com/mirumee/saleor/issues/3250#issuecomment-442130475.*

**Comment by jxltom** [comment]
I don't have a strong preference actually but personaly I would recomment saying thank you and add a link to view the order. This is an explicit way to indicate the users that the payment is successful.
