### ISSUE TITLE
Refactor checkout mutations 

### ISSUE THREAD

**Issue by fowczarek** [mirumee/saleor#3575]
Checkout mutations need to be refactored to increase code coverage and code quality.

**Comment by maarcingebala** [comment]
We could fix this small related issue that I found.

Passing empty `variantId` in input to `checkoutLinesAdd` or `checkoutLinesUpdate` mutations causes the following error which seems as an unhandled exception in our Python code error: `zip argument #1 must support iteration`:

Input:
```graphql
variables: {
    "checkoutId": "some-checkout-id",
    "lines": [{ quantity: 1, variantId: "" }]
}
```

**Comment by fowczarek** [comment]
Need to fix unhandled exception when a non-existent country code.

**Comment by jxltom** [comment]
As for the ```zip argument #1 must support iteration``` error, that's why I udpated the ```quantity``` and ```variantid``` as required arguments.
