### ISSUE TITLE
creating user in dashboard sends 'staff' set-password email

### ISSUE THREAD

**Issue by cprinos** [mirumee/saleor#3581]
### What I'm trying to achieve
As an staff user, create a customer from the dashboard

### Steps to reproduce the problem
1.  login to dashboard
2. create a new customer (not staff)

### What I expected to happen
customer receives email with link to set password.  <-- this happens, _but the email template is written for a staff user, not a customer_  (see `dashboard/emails.py:send_set_password_email` and `dashboard/staff/set_password.email` template

**Comment by maarcingebala** [comment]
Right, I can confirm the bug. We should make sure that the proper email template is used there.
