### ISSUE TITLE
Dropdown categories/collections in navigation menu of storefront 1.0 has no margins or paddings

### ISSUE THREAD

**Issue by jxltom** [mirumee/saleor#3585]
It looks like the css for the dropdown menu is incorrect. Maybe no padding or margins? Looks weired.

### Screenshots

![screenshot from 2019-01-11 18-26-30](https://user-images.githubusercontent.com/1401630/51028497-7876ab00-15ce-11e9-8d9d-74087125c081.png)

**Comment by dominik-zeglen** [comment]
Nice catch!
