### ISSUE TITLE
Show products in category section in dashboard

### ISSUE THREAD

**Issue by taedori81** [mirumee/saleor#359]
I think it will be better to show products count and products in category in dashboard.
So When I click category it shows root category list with total number of products like
- Electronics(29)
- Books(123)

and, when I click Electronics, if it has subcategory, then shows subcategory(ex- Computer(14)) if no subcategory then show products list of electronics.

What do you think?

**Comment by maarcingebala** [comment]
It has been implemented in the Dashboard 2.0.
