### ISSUE TITLE
Deploy saleor application on Google Cloud App Engine

### ISSUE THREAD

**Issue by lyrapedro** [mirumee/saleor#3613]
I need to deploy to the google app engine, has anyone done this or know how I can do it? I tried following the google app engine documentation for django applications but could not, it creates a conflict between app.yaml and Dockerfile present in the original repository

**Comment by nixxon111** [comment]
If a specific issue is keeping you back, Some details about it might be helpful.

I used a kubernetes cluster to succesfully run the base saleor project in the cloud with public IP address and postgres running in Google Cloud as well.

1. Build your docker image locally, and publish to Google Cloud Container Registry
2. Follow a guide to setup "generic" Kubernetes cluster and remember to set environment variables when creating your workload based on the uploaded image.
3. Go to your workload and pick EXPOSE in the top to create a public IP pointing to your application.
4. Setup Postgres in cloud. Many options, I went with their "Cloud SQL" solution, which was quite straightforward.

**Comment by patrys** [comment]
@nixxon111 We'd love to see a guide contributed to Saleor's deployment docs! 😄

**Comment by chetabahana** [comment]
Guides - Install [Saleor](https://getsaleor.com/) in [Google Cloud](https://cloud.google.com/)

**Comment by chetabahana** [comment]
Guides - Install [Saleor](https://getsaleor.com/) in [Google Cloud](https://cloud.google.com/)

**Comment by chetabahana** [comment]
#
