### ISSUE TITLE
Guide to integrate a new payment gateway

### ISSUE THREAD

**Issue by pelaohxc** [mirumee/saleor#3614]
Hi anyone have a guide of how to integrate a new payment gateway???
I'm from Chile and I am trying to integrate WebPay Plus from my country.

**Comment by Pacu2** [comment]
Hi, we have several guides in our docs, one of them is about integrating a new payment gateway
https://docs.getsaleor.com/en/latest/guides.html

**Comment by maarcingebala** [comment]
As @Pacu2 said you will find the guide in our docs, but at the moment we're in the middle of major refactoring of payments implementation (see #3422, #3519) so you should be aware that it is going to change within next few weeks.
