### ISSUE TITLE
how to create object with foreign key field in model using django graphane?

### ISSUE THREAD

**Issue by bhanuchander008** [mirumee/saleor#3618]
### What I'm trying to achieve
…

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
…

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by bhanuchander008** [comment]
from django.db import models

class Actor(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    actors =models.ForeignKey(Actor, on_delete=models.CASCADE)
    year = models.IntegerField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)

**Comment by Pacu2** [comment]
I think you'd have better luck asking in `django-graphene` repository. Closing as that's not really Saleor related.

You might want to check our spectrum and gitter, maybe someone from the community will help you find the way
