### ISSUE TITLE
how to create object with foreign key field in movie model using django graphane?

### ISSUE THREAD

**Issue by bhanuchander008** [mirumee/saleor#3619]
class Actor(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    actors =models.ForeignKey(Actor, on_delete=models.CASCADE)
    year = models.IntegerField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)
![screenshot from 2019-01-17 17-45-50](https://user-images.githubusercontent.com/34958449/51318882-95edbe00-1a81-11e9-9b7b-5119166bbfe7.png)

am geting error actor_id field cannot be null

**Comment by dominik-zeglen** [comment]
I think you should ask for help here:
https://github.com/graphql-python/graphene-django
