### ISSUE TITLE
Upgrade to django-recaptcha 2.x

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#3625]
New version has a cleaner API and an updated list of supported ReCaptchas.

**Comment by krzysztofwolski** [comment]
@patrys can we upgrade to v3? ( https://github.com/kbytesys/django-recaptcha3 )

**Comment by patrys** [comment]
`django-recaptcha` 2.x supports ReCaptcha v3 and I think it has more than 18 stars on GitHub 😉
