### ISSUE TITLE
Support returning merged attributes by slug in GraphQL API

### ISSUE THREAD

**Issue by jxltom** [mirumee/saleor#3630]
### What I'm trying to achieve

Since we use attribute slug ```attribute_slug:value_slug``` instead of specific pks to filter products, we can consider attribute/value pairs with same slug are same attributes, even though they are different objects stored in db actually. Is that reasonable to provide a ```mergedAttributes``` API in GraphQL? In this API which is very similar with ```Attributes```, but it returns merged attributes with attribute values by same slugs.

For example, if have a ```color``` attribute with ```blue``` and ```black``` values, and have another ```color``` attribute with ```blue``` and ```purple``` values, current attributes API will return
```
color
- blue
- black
color
- blue
- purple
```
It would be nice for ```mergedAttributes```  to return
```
color:
- blue
- black
- purple
```

It is very useful for storefront 2.0 or any other frontend app, for example, current storefront 2.0 will dispaly all attributes even though they have same attribute slug, as below image.

![screenshot from 2019-01-22 15-50-55](https://user-images.githubusercontent.com/1401630/51520073-bccf3a00-1e5d-11e9-996b-0c5c5b099c11.png)

### Describe a proposed solution

I know this can be implemented in frontend, but it would be nice to do it in backend. I tried to do some postprocess for ```Attributes``` API. But that API requires returning queryset instead of postprocessed list. And obviously I can not and there is no point to convert list to querysets back. Any hints for implement this? Thanks!

**Comment by patrys** [comment]
See #3088 for a similar feature. Merging based on slugs alone has the problem of potentially varying user-visible names and their translations.

**Comment by maarcingebala** [comment]
I was just going to link to the same issue. I think we should put it high on our priorities list, however I would also like to do some research before, how other e-commerce platforms approach that.

**Comment by jxltom** [comment]
@patrys @maarcingebala Thanks for the info! I will go for a look before making any comments. I agree it should taken as priority, since this will be a big refactor and some APIs may be changed or even deprecated.
