### ISSUE TITLE
Optimize Storefront 2.0 queries and mutations

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3631]
We should analyze GraphQL queries sent by Storefront 2.0 and try to optimize the number of database queries made underneath. Currently, I'm getting the following counts:

- product details page: 40 queries
- mutation `updateCheckoutLine` with single variant: 34 queries
- mutation `checkoutShippingAddressUpdate`: 38 queries

I suspect that the `Checkout` type is not optimized well. It has relationships with a few other models and every mutation that returns it seems to be performing too many DB queries.

**Comment by CharlyJazz** [comment]
https://github.com/graphql-python/graphene/issues/197

Maybe we can add a dataloader algorithm

**Comment by maarcingebala** [comment]
We took a different approach and we dynamically add database prefetches by using [graphene-django-optimizer](https://github.com/tfoxy/graphene-django-optimizer). It works well, we just have to double check whether all the fields in queries used by Storefront 2.0 have those optimizations enabled properly.

**Comment by maarcingebala** [comment]
We would also have to check Dashboard 2.0 views, e.g. order details page does between 30-40 queries right now.
