### ISSUE TITLE
Application doesn't reload when change is made in codebase. Development is running on docker. 

### ISSUE THREAD

**Issue by adorum** [mirumee/saleor#3634]
### What I'm trying to achieve
Running development in docker with `docker-compose up` I want to reload the source code in docker when I make a change in code on host.

### Steps to reproduce the problem
1. run `docker-compose up`
2. change something in code base, e.g. change currency in `settings.py`  `DEFAULT_CURRENCY = 'EUR'`

### What I expected to happen
Currency is not changed in running application and  still showing in USD. 

### Screenshots

**System information**
Operating system: Linux Mint 19.1
Browser: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by jxltom** [comment]
The settings is not loaded dynamically, you have to restart your application.

**Comment by adorum** [comment]
@jxltom even if I change something in django template it does not affect the running app until I restart the docker.

**Comment by jxltom** [comment]
I think it is because you just edit the sources in your local system instead of the ones inside the docker container.

**Comment by adorum** [comment]
yes, I edit the files in host compoter. Is it a common practice to edit the files inside the container?

**Comment by michaljelonek** [comment]
This issue should have been fixed by merging https://github.com/mirumee/saleor/pull/3657 (code wasn't mounted on the `web` service). @adorum could you re-check whether you still have it after updating your branch?

**Comment by adorum** [comment]
@michaljelonek yes, after updating the branch it works like a charm. Thx.
