### ISSUE TITLE
environment variables A basic question

### ISSUE THREAD

**Issue by mathtecg** [mirumee/saleor#3651]
Hi guys!

I'm pretty new to Django / Saleor...

How can I set environment variables? Right now I'm doin this via
Control Panel\System and Security\System\Advanced System Settings\Environment Variables... 

so maybe someone can give me a short explanation. I searched in the DjangoDocs but couldn't figure out how to do this smart.

Thanks a lot!

**Comment by maarcingebala** [comment]
Hey, env variables aren't related much to a web framework like Django in this case, but rather to your operating system. I assume you're using Windows, so in your case this might be helpful:

https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt

In general, you should set your env variables in the console where you're running your programs, in this case, Django application server.

I'm closing this as it's not related to Saleor.
