### ISSUE TITLE
Add sale list manipulation mutations

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#3653]
### What I'm trying to achieve
To add and delete categories, collections, and products from sale. 

### Describe a proposed solution
Add `saleAssignCategories`, `saleAssignCollections`, `saleAssignProducts`, `saleUnassignCategories`, `saleUnassignCollections` and `saleUnassignProducts`, as it is done in collections.

### Other solutions I've tried and won't work
`saleUpdate` has the ability to set items in these lists, but it does not provide a safe interface to manipulate lists, because it overrides them.

**Comment by michaljelonek** [comment]
@maarcingebala @dominik-zeglen would it better to have one mutation to add and one to remove, that would allow to set products or collections or categories or any mix of those, rather than three separate mutations to add and three to remove?

**Comment by maarcingebala** [comment]
We also need very similar mutations for vouchers. In total that would be 12 very similar mutations. Instead, we can try with something like:
```
saleAddProducts(saleId: ID!, products: [ID]!, collections: [ID]!, categories: [ID]!)
saleRemoveProducts(saleId: ID!, products: [ID]!, collections: [ID]!, categories: [ID]!)
voucherAddProducts(voucherId: ID!, products: [ID]!, collections: [ID]!, categories: [ID]!)
voucherRemoveProducts(voucherId: ID!, products: [ID]!, collections: [ID]!, categories: [ID]!)
```
