### ISSUE TITLE
Implement redirection based payment gateway

### ISSUE THREAD

**Issue by adorum** [mirumee/saleor#3663]
Hi, 
I would like to implement a [gopay](https://doc.gopay.com/en/?_ga=2.148776951.1508962901.1548625662-1149765658.1548191423) payment gateway where basically I must redirect the user to gopay specific url where the magic happens. 

Any ideas how to do it with the current saleor payment architecture?
Many thanks.

**Comment by maarcingebala** [comment]
Hi @adorum, I have two questions:
- Do you want to use only `gopay` or some other gateways as well?
- Do you use Storefront 1.0 (Django-based, static) or Storefront 2.0 (SPA)?

If you're using the classic Django-based storefront you would have to customize the `start_payment` view and redirect to the payment gateway in this view. Next, you would need a return URL that the gateway would use to return to your shop. We have a view `payment-success` which is no longer used with the current approach but you could use it to provide post-processing of the payment.

**Comment by adorum** [comment]
@maarcingebala 

- yes, gopay is the only payment gateway
- yes, I am using Storefront 1.0

I guess when I change the `start_payment` view, then won't be able to integrate another payment gateway - but in my case it's not problem. What about using Storefront 2.0 SPA? Would it work with my approach?

**Comment by maarcingebala** [comment]
I don't know how this gateway works exactly, from what I saw it has some REST API and Python bindings which seems nice. If you wanted to use it with Storefront 2.0, you would have to provide support for this gateway in GraphQL API. Storefront 2.0 is written entirely in JS so if that gateway needs some redirects, it would have to be implemented over there. If they provide some JS integrations, maybe that could be used as well.

**Comment by wulaaf** [comment]
@adorum did you figure out a way to get this done? I'm trying to rewrite the start_payment and payment-success views to account for a redirection based payment gateway. I'm guessing I'll have to move a lot of processing done within start_payment to payment_success?
