### ISSUE TITLE
DisallowedHost Heroku help

### ISSUE THREAD

**Issue by afhaider** [mirumee/saleor#3674]
heroku config:set ALLOWED_HOSTS='<your hosts here>'

this command not working 
Invalid HTTP_HOST header: 'fvcollection.herokuapp.com'. You may need to add 'fvcollection.herokuapp.com' to ALLOWED_HOSTS.

i keep adding this 
heroku config:set ALLOWED_HOSTS='fvcollection.herokuapp.com'

**Comment by Pacu2** [comment]
You should pass a list of allowed hosts instead

**Comment by afhaider** [comment]
> You should pass a list of allowed hosts instead

how can i? can u give an example?

**Comment by afhaider** [comment]
ALLOWED_HOSTS = get_list(
    os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1'))
it not take more then 2 arugement

**Comment by afhaider** [comment]
ALLOWED_HOSTS = get_list(
    os.environ.get('fvcollection.herokuapp.com', 'localhost,127.0.0.1'))

ALLOWED_HOSTS = ['fvcollection.herokuapp.com']

no luck :_

**Comment by Pacu2** [comment]
Leave the Saleor's settings untouched, as it was. 

When setting an `ALLOWED_HOSTS` env variable set it to a comma-separated list, eg `fvcollection.herokuapp.com,othersite.com`

**Comment by afhaider** [comment]
heroku config:set ALLOWED_HOSTS='.herokuapp.com,*,iscollection.herokuapp.com,iscollection.com'

did everything u sayed still getting disallowed host

**Comment by afhaider** [comment]
![herokuf](https://user-images.githubusercontent.com/43029071/52108279-657c5700-261f-11e9-8688-783345e13191.png)
