### ISSUE TITLE
heroku deploy mirumee github instead my custom saleor

### ISSUE THREAD

**Issue by afhaider** [mirumee/saleor#3677]
![mirume](https://user-images.githubusercontent.com/43029071/52112553-d83fff00-262c-11e9-921c-dce4d6d18d84.png)
![mycus](https://user-images.githubusercontent.com/43029071/52112561-dbd38600-262c-11e9-8294-0e7ef9d487c7.png)

**Comment by afhaider** [comment]
https://saleor.readthedocs.io/en/latest/deployment/heroku.html

this method only clone the repos of miruee not our custome 

(do i need to do something with app.json or package.json?)for example changing repos and uploading my custom one first on github?

**Comment by Pacu2** [comment]
Have you modified the right static files?

**Comment by afhaider** [comment]
i edit scss

**Comment by afhaider** [comment]
variables.scss
thnx pacu2 u awesome bro

**Comment by afhaider** [comment]
u notice it also not migrate data like navbar it probably making cloning of miruee repos from github

**Comment by Pacu2** [comment]
It's not possible that it cloned directly from mirumee's repository.
You're pushing the data to the heroku instance with the `git push heroku master` command. 
Please make sure you've commited your data and ran `collectstatic` on the heroku's instance

**Comment by afhaider** [comment]
Is the server running on host "127.0.0.1" and accepting
remote:         TCP/IP connections on port 5432?
remote:
whenever i do commit it make fail push

**Comment by afhaider** [comment]
![iasd](https://user-images.githubusercontent.com/43029071/52116843-37efd780-2638-11e9-971b-6a267b13953b.png)
i did what u sayed bro

**Comment by afhaider** [comment]
bro are u in discord or in fb:

**Comment by afhaider** [comment]
this happen whenever we (git commit -am "make it better")
                          then postgres connection refused

**Comment by afhaider** [comment]
i fixed it by linking of postgres of heroku but my question is that how can we send postgress data of our computer to heroku postgress their must be a way



this heroku postgress online database

DATABASES = {
    'default': dj_database_url.config(
        default='postgres://******',
        conn_max_age=600)}
and this my offline database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'AF',
        'USER': 'postgres',
        'PASSWORD': '#####',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
how can i transfer offline to online database their must be way can u help me bro

**Comment by Pacu2** [comment]
Glad to see this resolved
