### ISSUE TITLE
Merge "charge" and "auth" payment operations

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3679]
Saleor used to have two operations related to charging payments: authorization and capture. In this context, "charge" is simply an operation which immediately performs "capture" after "authorization". If that's possible, we should merge those two operations to simplify the payments architecture.

Related discussion can be found here: https://github.com/mirumee/saleor/pull/3519#discussion_r247864471. 

As far as I remember, "charging" as a separate operation was introduced with Stripe, but this gateway supports charing in two steps: https://stripe.com/docs/charges#auth-capture

**Comment by NyanKiyoshi** [comment]
We should add a flag to gateways to say whether the gateway supports authorization or not. And then check for the authorization's presence or not depending on that during `gateway_capture(...)`.

**Comment by NyanKiyoshi** [comment]
Some work have been done at https://github.com/mirumee/saleor/commit/c7f93b3054fdf231b7576385f705466b9758d9c2 to introduce a boolean constant `SUPPORTS_AUTHORIZATION` in gateways that is used to check or not for the authorization payment when capturing.

**Comment by maarcingebala** [comment]
Resolved in #4098
