### ISSUE TITLE
Editing collection seo info throws an error

### ISSUE THREAD

**Issue by cherniavskii** [mirumee/saleor#3681]
Hi Mirumee team,
Great work on Saleor project!
I really like new dashboard :)

### What I'm trying to achieve
I was exploring new dashboard, and got an error when trying to edit Collection SEO details.

### Steps to reproduce the problem
1. Go to https://demo.getsaleor.com/dashboard/next/collections/Q29sbGVjdGlvbjoy
2. Click "Edit website SEO"
3. See console output

Code fails here:
https://github.com/mirumee/saleor/blob/ed18bee914781e8465015765cbd9fdb8fb1c5a70/saleor/static/dashboard-next/components/SeoForm/SeoForm.tsx#L118-L121

### What I expected to happen
No error, SEO form with title and description fields appears

### Screenshots

**System information**
Operating system: N/A
Browser: N/A

### Details
Existing collections have `seoDescription` and `seoTitle` set to `null`, which doesn't happen when creating a new collection (both are set to an empty string in that case). I guess those collections' model is a bit outdated and needs to be updated, since after looking at source code looks like `seoDescription` and `seoTitle` are always required.

Cheers ;)

**Comment by Pacu2** [comment]
I think that might be a case with the data generated by the `populatedb` command

**Comment by cherniavskii** [comment]
@Pacu2 I think you're right, it's right here:

https://github.com/mirumee/saleor/blob/ed18bee914781e8465015765cbd9fdb8fb1c5a70/saleor/core/utils/random_data.py#L52-L65

I can submit a PR

**Comment by cherniavskii** [comment]
Hmm, looks like the real issue is in `db.json`:

https://github.com/mirumee/saleor/blob/ed18bee914781e8465015765cbd9fdb8fb1c5a70/saleor/static/db.json#L4743-L4748

**Comment by maarcingebala** [comment]
As far as I remember, `db.json` was generated using `dumpdata` command, but we could manually update those values in `db.json`.

**Comment by cherniavskii** [comment]
`dumpdata` command was removed in https://github.com/mirumee/saleor/commit/be3346eaa2acf8793467c7d0f1dd0252dc53ce88 , updating `db.json` should be enough
