### ISSUE TITLE
THNX SALEOR LOVE U GUYS 

### ISSUE THREAD

**Issue by afhaider** [mirumee/saleor#3686]

**Comment by afhaider** [comment]
![bug1](https://user-images.githubusercontent.com/43029071/52268540-d09c9500-2961-11e9-80ff-3b66a2e7d5d5.png)
this bug i keep getting  Use new API on `.hooks` instead does saleor api old version?

**Comment by Pacu2** [comment]
Glad you enjoy Saleor!
