### ISSUE TITLE
Add django bootstrap3 templatetags

### ISSUE THREAD

**Issue by car3oon** [mirumee/saleor#370]
I think we need more complex solution for bootstrap3 tempalatetags in Saleor. I was facing some problems while customizing "Add to cart" form. I couldn't clearly add `non_field_errors`, as it's not correctly done in current version. I had to use this code: 
`{% include "bootstrap/_non_field_errors.html" with errors=form.non_field_errors %}`
I suggest to use [django-bootstrap3](http://django-bootstrap3.readthedocs.org/en/latest/) or maybe you have some propositions.

**Comment by patrys** [comment]
Hmm, last time we checked `django-bootstrap3` added lots of overhead when dealing with many forms due to its deep `{% include ... %}` tree. What is the exact problem with non-field errors in the current implementation? Maybe we can fix that first and look into replacements later?

**Comment by car3oon** [comment]
I have to explicit call "protected" template it is not dry approach. I think we should have instead of including templates we should have simple templatetag for it. For exmaple: http://django-bootstrap3.readthedocs.org/en/latest/templatetags.html#bootstrap-form-errors
It'll be nice to have exclude for fields in form as well.

**Comment by patrys** [comment]
I'm not a huge fan of whole forms rendering themselves. I'd much rather have the template explicitly render each field as that makes sure their order depends is up to the designer and not the programmer. Otherwise it's easy to accidentally break UX while refactoring the backend.

**Comment by mociepka** [comment]
I think we should give a chance `django bootstrap3`. It looks more solid then before and definitely including internal filter templates doesn't look good to me as well.
