### ISSUE TITLE
Sending Email failed when assign new staff.

### ISSUE THREAD

**Issue by syedhsn** [mirumee/saleor#3703]
I already configure my EMAIL_URL=smtp://username:password@smtp.gmail.com:587/?ssl=True.
but when I assign new staff, there is no email send and then when I check through inspect element and it says that error 302 Found.

**Comment by Pacu2** [comment]
Have you checked the error logs? Is there any stack trace available?

**Comment by Kwaidan00** [comment]
I've checked sending emails via SMTP and it works for me; I suppose you have some problem with email server configuration.

I've parsed your `EMAIL_URL` with `dj-email-url` package (Saleor does it in `settings.py`) and I've got:

    {'EMAIL_FILE_PATH': '',
     'EMAIL_HOST_USER': 'username',
     'EMAIL_HOST_PASSWORD': 'password',
     'EMAIL_HOST': 'smtp.gmail.com',
     'EMAIL_PORT': 587,
     'EMAIL_USE_SSL': True,
     'EMAIL_USE_TLS': False,
     'EMAIL_BACKEND': 'django.core.mail.backends.smtp.EmailBackend'}

Now I can see all email configuration for Django. The point is, I think, you should use SSL on port 465 __or__ TLS on port 587. For more details, please visit https://support.google.com/a/answer/176600?hl=en

Last but not least - did you let less secure apps to access your Google account? It is described on https://support.google.com/accounts/answer/6010255?hl=en

**Comment by syedhsn** [comment]
> Have you checked the error logs? Is there any stack trace available?

**Comment by syedhsn** [comment]
> > Have you checked the error logs? Is there any stack trace available?

Im newbie in python. Where can I check the error logs?

**Comment by syedhsn** [comment]
> Have you checked the error logs? Is there any stack trace available?

**Comment by syedhsn** [comment]
> > Have you checked the error logs? Is there any stack trace available?

Where can I check the error log? Im newbie in python

**Comment by syedhsn** [comment]
> I've checked sending emails via SMTP and it works for me; I suppose you have some problem with email server configuration.
> 
> I've parsed your `EMAIL_URL` with `dj-email-url` package (Saleor does it in `settings.py`) and I've got:
> 
> ```
> {'EMAIL_FILE_PATH': '',
>  'EMAIL_HOST_USER': 'username',
>  'EMAIL_HOST_PASSWORD': 'password',
>  'EMAIL_HOST': 'smtp.gmail.com',
>  'EMAIL_PORT': 587,
>  'EMAIL_USE_SSL': True,
>  'EMAIL_USE_TLS': False,
>  'EMAIL_BACKEND': 'django.core.mail.backends.smtp.EmailBackend'}
> ```
> 
> Now I can see all email configuration for Django. The point is, I think, you should use SSL on port 465 **or** TLS on port 587. For more details, please visit https://support.google.com/a/answer/176600?hl=en
> 
> Last but not least - did you let less secure apps to access your Google account? It is described on https://support.google.com/accounts/answer/6010255?hl=en

Ya I realize there are some mistakes with my email configuration but ive changed it same like you show and activate less security for my email but still nothing happen.

**Comment by syedhsn** [comment]
EMAIL_FILE_PATH = ''
EMAIL_HOST_USER = 'dsmrgroupnotify@gmail.com'
EMAIL_HOST_PASSWORD = 'notification2020'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

This is my email configuration.

**Comment by syedhsn** [comment]
EMAIL_FILE_PATH = ''
EMAIL_HOST_USER = 'username'
EMAIL_HOST_PASSWORD = 'username'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

This is my email configuration!

**Comment by Kwaidan00** [comment]
> > > Have you checked the error logs? Is there any stack trace available?
> 
> Where can I check the error log? Im newbie in python

I suppose you work with development server - so all logs and exceptions are printed to the console.

**Comment by syedhsn** [comment]
I got this error:

INFO django.server "GET /dashboard/staff/staff-create/ HTTP/1.1" 200 24125 [PID:20779:Thread-3]
INFO django.server "GET /dashboard/staff/staff-create/ HTTP/1.1" 200 24125 [PID:20779:Thread-3]
INFO django.server "GET /dashboard/staff/staff-create/ HTTP/1.1" 200 24125 [PID:20779:Thread-3]
INFO django.server "GET /static/versatileimagefield/js/versatileimagefield.js HTTP/1.1" 304 0 [PID:20779:Thread-5]
INFO django.server "GET /static/versatileimagefield/js/versatileimagefield.js HTTP/1.1" 304 0 [PID:20779:Thread-5]
INFO django.server "GET /static/versatileimagefield/js/versatileimagefield.js HTTP/1.1" 304 0 [PID:20779:Thread-5]
INFO django.server "GET /static/assets/dashboard.c914c1577aabf96731d6.js HTTP/1.1" 304 0 [PID:20779:Thread-4]
INFO django.server "GET /static/assets/dashboard.c914c1577aabf96731d6.js HTTP/1.1" 304 0 [PID:20779:Thread-4]
INFO django.server "GET /static/assets/dashboard.c914c1577aabf96731d6.js HTTP/1.1" 304 0 [PID:20779:Thread-4]
INFO django.server "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0 [PID:20779:Thread-6]
INFO django.server "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0 [PID:20779:Thread-6]
INFO django.server "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0 [PID:20779:Thread-6]
INFO django.server "GET /en/jsi18n/ HTTP/1.1" 200 3185 [PID:20779:Thread-3]
INFO django.server "GET /en/jsi18n/ HTTP/1.1" 200 3185 [PID:20779:Thread-3]
INFO django.server "GET /en/jsi18n/ HTTP/1.1" 200 3185 [PID:20779:Thread-3]
INFO django.server "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 41 [PID:20779:Thread-5]
INFO django.server "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 41 [PID:20779:Thread-5]
INFO django.server "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 41 [PID:20779:Thread-5]
INFO django.server "GET /static/versatileimagefield/css/versatileimagefield.css HTTP/1.1" 200 262 [PID:20779:Thread-8]
INFO django.server "GET /static/versatileimagefield/css/versatileimagefield.css HTTP/1.1" 200 262 [PID:20779:Thread-8]
INFO django.server "GET /static/versatileimagefield/css/versatileimagefield.css HTTP/1.1" 200 262 [PID:20779:Thread-8]
INFO django.server "GET /static/assets/dashboard.c914c1577aabf96731d6.css HTTP/1.1" 200 229546 [PID:20779:Thread-7]
INFO django.server "GET /static/assets/dashboard.c914c1577aabf96731d6.css HTTP/1.1" 200 229546 [PID:20779:Thread-7]
INFO django.server "GET /static/assets/dashboard.c914c1577aabf96731d6.css HTTP/1.1" 200 229546 [PID:20779:Thread-7]
INFO django.server "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 14835 [PID:20779:Thread-4]
INFO django.server "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 14835 [PID:20779:Thread-4]
INFO django.server "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 14835 [PID:20779:Thread-4]
INFO django.server "GET /static/assets/chevron-right.b90a94d3bf483b8d97e4647049ecdaa2.svg HTTP/1.1" 200 210 [PID:20779:Thread-7]
INFO django.server "GET /static/assets/chevron-right.b90a94d3bf483b8d97e4647049ecdaa2.svg HTTP/1.1" 200 210 [PID:20779:Thread-7]
INFO django.server "GET /static/assets/chevron-right.b90a94d3bf483b8d97e4647049ecdaa2.svg HTTP/1.1" 200 210 [PID:20779:Thread-7]
INFO django.server "GET /static/favicons/apple-touch-icon.png HTTP/1.1" 200 6600 [PID:20779:Thread-7]
INFO django.server "GET /static/favicons/apple-touch-icon.png HTTP/1.1" 200 6600 [PID:20779:Thread-7]
INFO django.server "GET /static/favicons/apple-touch-icon.png HTTP/1.1" 200 6600 [PID:20779:Thread-7]
INFO django.server "GET /static/favicons/favicon-16x16.png HTTP/1.1" 200 877 [PID:20779:Thread-4]
INFO django.server "GET /static/favicons/favicon-16x16.png HTTP/1.1" 200 877 [PID:20779:Thread-4]
INFO django.server "GET /static/favicons/favicon-16x16.png HTTP/1.1" 200 877 [PID:20779:Thread-4]
INFO django.server "GET /static/dashboard/images/search.svg HTTP/1.1" 200 383 [PID:20779:Thread-5]
INFO django.server "GET /static/dashboard/images/search.svg HTTP/1.1" 200 383 [PID:20779:Thread-5]
INFO django.server "GET /static/dashboard/images/logo.svg HTTP/1.1" 200 2233 [PID:20779:Thread-3]
INFO django.server "GET /static/dashboard/images/logo.svg HTTP/1.1" 200 2233 [PID:20779:Thread-3]
INFO django.server "GET /static/dashboard/images/logo.svg HTTP/1.1" 200 2233 [PID:20779:Thread-3]
INFO django.server "GET /static/dashboard/images/search.svg HTTP/1.1" 200 383 [PID:20779:Thread-5]
INFO django.server "GET /static/dashboard/images/account-circle.svg HTTP/1.1" 200 391 [PID:20779:Thread-8]
INFO django.server "GET /static/dashboard/images/account-circle.svg HTTP/1.1" 200 391 [PID:20779:Thread-8]
INFO django.server "GET /static/dashboard/images/account-circle.svg HTTP/1.1" 200 391 [PID:20779:Thread-8]
INFO django.server "GET /static/dashboard/images/mobile-menu.svg HTTP/1.1" 200 850 [PID:20779:Thread-6]
INFO django.server "GET /static/dashboard/images/mobile-menu.svg HTTP/1.1" 200 850 [PID:20779:Thread-6]
INFO django.server "GET /static/dashboard/images/mobile-menu.svg HTTP/1.1" 200 850 [PID:20779:Thread-6]
INFO django.server "GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 200 404 [PID:20779:Thread-6]
INFO django.server "GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 200 404 [PID:20779:Thread-6]
INFO django.server "GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 200 404 [PID:20779:Thread-6]
INFO django.server "GET /static/debug_toolbar/img/djdt_vertical.png HTTP/1.1" 200 882 [PID:20779:Thread-8]
INFO django.server "GET /static/debug_toolbar/img/djdt_vertical.png HTTP/1.1" 200 882 [PID:20779:Thread-8]
INFO django.server "GET /static/debug_toolbar/img/djdt_vertical.png HTTP/1.1" 200 882 [PID:20779:Thread-8]
INFO django.server "GET /static/dashboard/images/arrow-left.svg HTTP/1.1" 200 224 [PID:20779:Thread-9]
INFO django.server "GET /static/dashboard/images/arrow-left.svg HTTP/1.1" 200 224 [PID:20779:Thread-9]
INFO django.server "GET /static/dashboard/images/arrow-left.svg HTTP/1.1" 200 224 [PID:20779:Thread-9]
ERROR celery.app.trace Task saleor.dashboard.emails.send_promote_customer_to_staff_email[8879d032-2848-4c58-ac07-4a643c9e9ce1] raised unexpected: SMTPServerDisconnected('Connection unexpectedly closed',) [PID:20779:Thread-3]
Traceback (most recent call last):
  File "/home/sydhsn/saleor/env/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/sydhsn/saleor/saleor/dashboard/emails.py", line 41, in send_promote_customer_to_staff_email
    context=ctx)
  File "/home/sydhsn/saleor/env/lib/python3.6/site-packages/templated_email/__init__.py", line 70, in send_templated_mail
    headers=headers, create_link=create_link, **kwargs)
  File "/home/sydhsn/saleor/env/lib/python3.6/site-packages/templated_email/backends/vanilla_django.py", line 263, in send
    e.send(fail_silently)
  File "/home/sydhsn/saleor/env/lib/python3.6/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/sydhsn/saleor/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/home/sydhsn/saleor/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.6/smtplib.py", line 338, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python3.6/smtplib.py", line 394, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
INFO django.server "POST /dashboard/staff/staff-create/ HTTP/1.1" 302 0 [PID:20779:Thread-3]
INFO django.server "POST /dashboard/staff/staff-create/ HTTP/1.1" 302 0 [PID:20779:Thread-3]
INFO django.server "POST /dashboard/staff/staff-create/ HTTP/1.1" 302 0 [PID:20779:Thread-3]
INFO django.server "GET /dashboard/staff/ HTTP/1.1" 200 28024 [PID:20779:Thread-3]
INFO django.server "GET /dashboard/staff/ HTTP/1.1" 200 28024 [PID:20779:Thread-3]
INFO django.server "GET /dashboard/staff/ HTTP/1.1" 200 28024 [PID:20779:Thread-3]
INFO django.server "GET /static/assets/dashboard.c914c1577aabf96731d6.css HTTP/1.1" 200 229546 [PID:20779:Thread-6]
INFO django.server "GET /static/assets/dashboard.c914c1577aabf96731d6.css HTTP/1.1" 200 229546 [PID:20779:Thread-6]
INFO django.server "GET /static/assets/dashboard.c914c1577aabf96731d6.css HTTP/1.1" 200 229546 [PID:20779:Thread-6]
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 47426)
INFO django.server "GET /static/versatileimagefield/css/versatileimagefield.css HTTP/1.1" 200 262 [PID:20779:Thread-5]
INFO django.server "GET /static/versatileimagefield/css/versatileimagefield.css HTTP/1.1" 200 262 [PID:20779:Thread-5]
INFO django.server "GET /static/versatileimagefield/css/versatileimagefield.css HTTP/1.1" 200 262 [PID:20779:Thread-5]
INFO django.server "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 8192 [PID:20779:Thread-3]
INFO django.server "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 8192 [PID:20779:Thread-3]
INFO django.server "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 8192 [PID:20779:Thread-3]
INFO django.server "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 41 [PID:20779:Thread-9]
INFO django.server "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 41 [PID:20779:Thread-9]
Traceback (most recent call last):
INFO django.server "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 41 [PID:20779:Thread-9]
  File "/usr/lib/python3.6/socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/home/sydhsn/saleor/env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/sydhsn/saleor/env/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
INFO django.server "GET /en/jsi18n/ HTTP/1.1" 200 3185 [PID:20779:Thread-8]
INFO django.server "GET /en/jsi18n/ HTTP/1.1" 200 3185 [PID:20779:Thread-8]
INFO django.server "GET /en/jsi18n/ HTTP/1.1" 200 3185 [PID:20779:Thread-8]
INFO django.server "GET /static/dashboard/images/account-circle.svg HTTP/1.1" 200 391 [PID:20779:Thread-8]
INFO django.server "GET /static/dashboard/images/account-circle.svg HTTP/1.1" 200 391 [PID:20779:Thread-8]
INFO django.server "GET /static/dashboard/images/account-circle.svg HTTP/1.1" 200 391 [PID:20779:Thread-8]
INFO django.server "GET /static/dashboard/images/search.svg HTTP/1.1" 200 383 [PID:20779:Thread-10]
INFO django.server "GET /static/dashboard/images/search.svg HTTP/1.1" 200 383 [PID:20779:Thread-10]
INFO django.server "GET /static/dashboard/images/search.svg HTTP/1.1" 200 383 [PID:20779:Thread-10]
INFO django.server "GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 200 404 [PID:20779:Thread-15]
INFO django.server "GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 200 404 [PID:20779:Thread-15]
INFO django.server "GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 200 404 [PID:20779:Thread-15]
INFO django.server "GET /static/debug_toolbar/img/djdt_vertical.png HTTP/1.1" 200 882 [PID:20779:Thread-16]
INFO django.server "GET /static/debug_toolbar/img/djdt_vertical.png HTTP/1.1" 200 882 [PID:20779:Thread-16]
INFO django.server "GET /static/debug_toolbar/img/djdt_vertical.png HTTP/1.1" 200 882 [PID:20779:Thread-16]
INFO django.server "GET /static/dashboard/images/add.svg HTTP/1.1" 200 199 [PID:20779:Thread-13]
INFO django.server "GET /static/dashboard/images/add.svg HTTP/1.1" 200 199 [PID:20779:Thread-13]
INFO django.server "GET /static/dashboard/images/add.svg HTTP/1.1" 200 199 [PID:20779:Thread-13]
INFO django.server "GET /static/images/filter-icon.svg HTTP/1.1" 200 523 [PID:20779:Thread-14]
INFO django.server "GET /static/images/filter-icon.svg HTTP/1.1" 200 523 [PID:20779:Thread-14]
INFO django.server "GET /static/images/filter-icon.svg HTTP/1.1" 200 523 [PID:20779:Thread-14]

**Comment by syedhsn** [comment]
> @syedhsn I think you should use the 465 port (SSL) instead of the 587 port (STARTTLS) since you are using SSL.

I've tried create a new project and using same configuration as above and its working. I dont think I have the problem with the config, maybe something else but I dont know what it is.

**Comment by maarcingebala** [comment]
This problem seems like a general issue with email backend configuration in Django, not really related to Saleor.
