### ISSUE TITLE
Delete button for product is misplaced

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#371]
And why we're using this 3 dots as an icon for menu, even when there is only one option?

![saleor_dashboard](https://cloud.githubusercontent.com/assets/1754812/10632958/e4b425a0-77e7-11e5-97bd-153fc9b5e228.png)

**Comment by patrys** [comment]
Overflow menu is by design, we don't want to offer remove directly.

**Comment by artursmet** [comment]
It's already fixed.
