### ISSUE TITLE
Product image div wrongly adopts image height from child element

### ISSUE THREAD

**Issue by raybesiga** [mirumee/saleor#3712]
### What I'm trying to achieve

I am trying to show the product image on the product detail page in full height. However, the div with the `product-image` CSS class adopt the height of the image. The image then shows only partially instead of the full image.

### Steps to reproduce the problem

Height inherited by default 

![height-inherited](https://user-images.githubusercontent.com/405697/52552786-89475600-2df2-11e9-8f05-77eeeeacf8a9.png)

This what the code looks like when rendered

```html
<div class="product-image" style="height: 540px;">
      <img class="d-block img-fluid lazypreload lazyloaded" 
        data-src="/media/__sized__/products/flying-tomato-1-thumbnail-540x540-70.jpg" 
        data-srcset="/media/__sized__/products/flying-tomato-1-thumbnail-540x540-70.jpg 1x, 
        /media/__sized__/products/flying-tomato-1-thumbnail-1080x1080-70.jpg 2x" alt="" 
        src="/media/__sized__/products/flying-tomato-1-thumbnail-540x540-70.jpg" 
        srcset="/media/__sized__/products/flying-tomato-1-thumbnail-540x540-70.jpg 1x, 
        /media/__sized__/products/flying-tomato-1-thumbnail-1080x1080-70.jpg 2x">
</div>
```

### What I expected to happen

Height inherit disabled on the element

![height-not-inherited](https://user-images.githubusercontent.com/405697/52552810-99f7cc00-2df2-11e9-9073-bd55fe083a6c.png)

What the code should look like 

```html
<div class="product-image">
      <img class="d-block img-fluid lazypreload lazyloaded" 
        data-src="/media/__sized__/products/flying-tomato-1-thumbnail-540x540-70.jpg" 
        data-srcset="/media/__sized__/products/flying-tomato-1-thumbnail-540x540-70.jpg 1x, 
        /media/__sized__/products/flying-tomato-1-thumbnail-1080x1080-70.jpg 2x" alt="" 
        src="/media/__sized__/products/flying-tomato-1-thumbnail-540x540-70.jpg" 
        srcset="/media/__sized__/products/flying-tomato-1-thumbnail-540x540-70.jpg 1x, 
        /media/__sized__/products/flying-tomato-1-thumbnail-1080x1080-70.jpg 2x">
</div>
```

Why is this the case? Cannot seem to find the class in the Product page [SCSS](https://github.com/mirumee/saleor/blob/master/saleor/static/scss/layouts/_product-page.scss) file 

### Screenshots

As shown above.

**System information**
Operating system:  MacOS 
Browser: Chrome

**Comment by raybesiga** [comment]
CC @patrys @maarcingebala @BenSturmfels @NyanKiyoshi any ideas?

**Comment by maarcingebala** [comment]
We should ask our frontend devs, @dominik-zeglen / @piotrgrundas could you investigate the problem here?

**Comment by raybesiga** [comment]
hi guys

So i made the following change to the product image class and it seems to solve inheritance issue

```css
.product-image {
  display: flex;
  align-items: center;
  justify-content: center;
  height: auto !important;
}
```

Let me know what you think @dominik-zeglen @piotrgrundas
