### ISSUE TITLE
Internal Server Error when sending an email

### ISSUE THREAD

**Issue by syedhsn** [mirumee/saleor#3714]
I've set the email configuration using smtp. The problem is by using the same code most of the times the email cannot be send but there are two times the email is succesfully send. How to overcome this kind of issue?

**Comment by Kwaidan00** [comment]
Could you provide additional piece of information about your issue? Is there some `ERROR` entries and stack traces in your logs?

**Comment by maarcingebala** [comment]
Please reopen if you can provide a more accurate description or steps to reproduce the issue.
