### ISSUE TITLE
Changing language not working on sitefront, but works on dashboard.

### ISSUE THREAD

**Issue by totraku** [mirumee/saleor#3729]
![ezgif com-optimize](https://user-images.githubusercontent.com/36606809/52856070-aac27d80-3123-11e9-8ed3-7abe38bdce05.gif)

As seen, the change of language in the language picker has apparently no effect. Meanwhile I checked the django_language cookie and it does change. So the problem here is that the url is not updated to match the cookie, at least in the front site. Moreover for some reason it is always in German, independent of my browser being set to English.

**Edit-1:** Just creating a new category and adding it to the navbar makes it(changing languages) work again, but let's see if this will work persistently.

**Edit-2:** The method from Edit-1 doesn't seem to last. If I go right to the products detail, everything seems to work. As soon as I go into categories, that's where the inconsistencies start to show.

**Comment by NyanKiyoshi** [comment]
This is because of #3154.
