### ISSUE TITLE
Modify Shipping Cost

### ISSUE THREAD

**Issue by mykhul** [mirumee/saleor#373]
Hello..

We are using Saleor to run our e-commerce website.

I see the code for DummyShipping, however it's a bit unclear the correct way to modify this behavior,

Is there any insight you folks can offer?

I think Saleor is amazing.

**Comment by patrys** [comment]
In `saleor.delivery` lives a function called [`get_delivery_options_for_items`](https://github.com/mirumee/saleor/blob/d91369c6d94c8e56c6183068af46638587f51ec2/saleor/delivery/__init__.py#L36). Its intent is to yield a list of possible ways to dispatch a particular delivery group (a subset of an order meant to be shipped together, most orders only have a single delivery group).

By default it returns a `DummyShipping` instance but you can return anything as long as it has the same interface as `BaseDelivery`. For your use case the most important method is `get_delivery_total` that gets a list of cart/order lines and is expected to return the total cost of dispatching said items. Inside that function you can do whatever you want (access database, call an API etc.) as long as you return a `Price` object in the appropriate currency.

**Comment by mykhul** [comment]
Great information, thank you! How is it possible inside of get_delivery_total(..) to access the shipping address?

**Comment by patrys** [comment]
In [checkout steps](https://github.com/mirumee/saleor/blob/d91369c6d94c8e56c6183068af46638587f51ec2/saleor/checkout/steps.py#L149-L150) the address is passed to `get_delivery_options_for_items` so if you modify that function you can pass the address to your delivery class constructor and later access it in `get_delivery_total` to calculate the delivery cost.

**Comment by mykhul** [comment]
OK, great. Thank you! That answers everything.

**Comment by mykhul** [comment]
how does this process differ in the latest version of Saleor?

**Comment by patrys** [comment]
@mykhul Not sure what exactly you're asking about. Did we break something that used to work?
