### ISSUE TITLE
Support checkout partially from cart

### ISSUE THREAD

**Issue by jxltom** [mirumee/saleor#3730]
### What I'm trying to achieve

In storefront 1.0 or ```checkoutComplete```/```checkoutPaymentCreate```, all the checkoutlines have to checkout together. It will be nice to let the users checkout partially. For example, if a user has product ```a```, ```b```, ```c``` in cart, it will be nice to let the user only select product ```a```, checkout only ```a``` and leave others still in cart.

Any thoughts about this feature?

**Comment by maarcingebala** [comment]
It doesn't sound like a typical use-case that we should support in Saleor (I think it's also pretty uncommon for other e-commerce platforms as well). We're interested in supporting the standard flow where customers buy all of their checkout items at once and the checkout instance is deleted afterward.

**Comment by jxltom** [comment]
Sure, no problem for that. Thanks for the reply. :D
