### ISSUE TITLE
Using phone numbers instead of emails

### ISSUE THREAD

**Issue by h8pwn** [mirumee/saleor#3733]
Hi, 
I need to use phone numbers instead of emails when signing up users or use them both alongside each other. 
I'm just getting to get familiar with the code base, I was hoping maybe you can guide me on what's the best approach to do that without the need of changing like 600 unit tests as well.

Thanks in advance.

**Comment by ashishnitinpatil** [comment]
Broadly put, you could add a phone field (optional) to the user model & change the relevant fronted forms to accept phone OR email as the login ID & in the backend, change the login function to treat the login ID field specially, i.e. check login with field as email & then (if wrong credentials) check login with field as phone number. For tests, you could simply add a few more checking that the login works with both, phone as well as email for a given person, other tests don't need to be touched.

If the phone field is not optional, you'll have to update test setups where you create a user (and add phone number to each user).

I'm new to saleor, so this is only a general django answer without the specifics. Others can correct me if the approach is wrong / different with saleor.
