### ISSUE TITLE
Store rich-text content in JSON fields

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3744]
We're introducing a new rich-text editor for Dashboard 2.0 (#3067). This editor stores output as JSON and we need to also extend our backend to support that. We need to extend models that would use the editor with an additional field for storing JSON. Those fields will be used by Dashboard 2.0 and Storefront 2.0. The static storefront and dashboard would continue using existing text/HTML fields.

**Required changes**
1. Add the following model fields:
- `Page.content_json`
- `Product.description_json`
- `Collection.description_json`
- `Category.description_json`

Not sure if we need to use `JSONField` or we could simply use `TextField` with serialized JSON as content - that is to be agreed with @dominik-zeglen about which type works better with Draftail and can be easily rendered in the storefront.

2. Adjust GraphQL API to save content coming from Dashboard 2.0 into the above fields. As for the queries, I think we could keep the original fields returning text/HTML as they are and just extend the types with JSON counterparts.

Last thing to consider is how to properly handle SEO fields. I think that in Dashboard 2.0 we should extract plain text from the editor (@dominik-zeglen has to check if this is possible in Draftail) and use that as SEO description, if it wasn't explicitely overriden by user.

**Comment by patrys** [comment]
Do we want to keep the non-JSON fields indefinitely or are they going to be marked for deprecation? I don't think the backend has enough knowledge about the client to decide what CSS class names to use (or what colors to assign) for regular text, let alone for advanced blocks like "product collection".

For API I recommend that we create an explicit JSON scalar, this would let us automatically handle it on both ends.

**Comment by maarcingebala** [comment]
The idea was to keep the text/HTML fields for the old storefront/dashboard and when we make Dashboard 2.0 the default one, we would deprecate those fields. We could as well use single JSON field for storing content and do the migration from HTML to JSON (if there's any tool worth considering) but then, how can we provide support for the old editor in Dashboard 1.0?

**Comment by patrys** [comment]
The problems I see are:
* if some of my users use the new dashboard they are going to see and edit different content than the rest of the team (and some people will inevitably see/edit content that does not match what the store displays)
* if I try to use Django to generate schema.org snippets/Twitter cards/open graph content then it's going to contain descriptions that do not match what React renders

**Comment by maarcingebala** [comment]
Theoretically yes - it is possible. But is this a real case that we should worry about? I doubt that. I would never think that a team might be using both dashboards at the same time, given that Dashboard 2.0 is still not finished.

But anyway, we could use one field as you suggest and do the migration if there's a tool that allows that. But we will also have to drop the current editor from Dashboard 1.0 and use React to render Draftail both in Dashboard 1.0 and Storefront 1.0.
