### ISSUE TITLE
Partial Fulfillment Not Working when 1 item not fulfilled at all

### ISSUE THREAD

**Issue by ubcamit** [mirumee/saleor#3758]
### What I'm trying to achieve
Partial Fulfillment of an order such that at least one item is not fulfilled at all. 

### Steps to reproduce the problem
1. Create an order with at least 2 different items (SKUs)
2. As a staff, login to dashboard and try and do a partial fulfillment such that at least one of the items is not being fulfilled ( i.e. fulfilled qty = 0)

### What I expected to happen
Expect the item with qty<>0 only to be fulfilled. And the item with qty=0 to be left unfulfilled for fulfillment at a later date/time.

### What actually happens
Am unable to complete the partial fulfillment. For the items with qty=0, get the error: Ensure this value is greater than or equal to 1.

### Screenshots
<img width="1075" alt="screen shot 2019-02-20 at 7 08 35 pm" src="https://user-images.githubusercontent.com/46588259/53140997-5bc18180-3543-11e9-98c9-5aae8cda5c4a.png">

### Suggested Fix
In saleor.dashboard.order.models::FulfillmentLine
change     
    quantity = models.IntegerField(validators=[MinValueValidator(1)])
to 
    quantity = models.IntegerField(validators=[MinValueValidator(0)])

However, I do not know if this will create any bugs in any other workflow.

**System information**
Operating system: Mac OS 10.13.6
Browser: Firefox 66.0b8 (64-bit)

**Comment by jxltom** [comment]
https://github.com/mirumee/saleor/pull/3754 should fix this.

**Comment by ubcamit** [comment]
thanks a lot jxltom
