### ISSUE TITLE
Help needed configuring Tax. Not working as expected.

### ISSUE THREAD

**Issue by gupta** [mirumee/saleor#3759]
I am trying to configure saleor to handle VAT for UAE. My requirements are:
- the prices of the product displayed on the website are inclusive of VAT
- the invoice (displayed online and the PDF) shows the net price and the VAT. net price is calculated by saleor automatically from the product price entered

I have gone through the available documentation and configured saleor through the following steps:

1) settings.py 
- DEFAULT_COUNTRY = 'AE'
- VATLAYER_ACCESS_KEY = some_key

2) Fetched VAT rates

3) DB
INSERT INTO public.django_prices_vatlayer_vat (country_code, data) VALUES ('AE', '{"country_name":"AE","standard_rate":5,"reduced_rates":null}');

4) Dashboard-Taxes
All product prices are entered with Tax included: Ticked
Show gross prices to customers in storefront: Ticked

However, at all stages (during/after checkout), saleor is showing "Taxes (included)" as 0; and showing gross prices for the product prices and subtotal/grandtotal .

Please let me know what changes need to be made to fix this.

Thanks in advance.

**Comment by NyanKiyoshi** [comment]
Does it say the standard rate is 5% in http://example.com/dashboard/taxes/AE/details/?

I tried but I cannot reproduce your issue, does it work if you use the latest version of saleor and create a new database and populate the database?

That's what I see:
![image](https://user-images.githubusercontent.com/6186720/53275620-02508280-36fc-11e9-8155-e02d5e13fbfa.png)

**Comment by ashishnitinpatil** [comment]
Same, can't repro with latest master branch with both products uploaded with tax & without tax setting.

**Comment by ashishnitinpatil** [comment]
Same, can't repro with latest master branch with both products uploaded with tax & without tax setting.

**Comment by gupta** [comment]
The problem was at my end. I has unintentionally created a bug while trying to get tax working for countries not pulled by VATLAYER. Fixed it. 
Apologies and thanks for everyones help..
