### ISSUE TITLE
The checkoutline and orderline should have same structure in API

### ISSUE THREAD

**Issue by jxltom** [mirumee/saleor#3760]
### What I'm trying to achieve

If I understand correctly, there is no much difference between ```CheckoutLine``` and ```OrderLine```. If Orderline has ```productName/translatedProductName```, the CheckoutLine should also has them. If CheckoutLine has ```variant```, the OrderLine should also has it.

**Comment by maarcingebala** [comment]
One difference between them is that `CheckoutLine` operates on product variants that exist in the database. When we create OrderLine, some of the fields have to be copied to ensure that order history is accessible even when products were removed from the database. 

E.g. there is no need for `CheckoutLine` to have `productName` field, as at the time when it is used we can take the name directly from the relationship with `ProductVariant`.

**Comment by jxltom** [comment]
Oh that's why the design is like this, thanks! So the variant of an OrderLine may not exist because of the variant can be deleted after the order is created.

But as for this case, currently there is not way to get the variant name of an OrderLine directly. The ```productName``` is like ```product_name (sku0001)```, it will be nice to get ```product_name``` and ```sku0001``` separately.

**Comment by maarcingebala** [comment]
That's right, there is an open issue for that (#3014).

**Comment by jxltom** [comment]
Thanks for mention this issue!
