### ISSUE TITLE
Custom text input for customizable product.

### ISSUE THREAD

**Issue by xtrasalty** [mirumee/saleor#3763]
### What I'm trying to achieve
Looking to add the option for a customer to add some customized text when adding a product to the cart.  Think customer requesting a monogram for a shirt.  They pick the size, color, type there initials in a text input and click add to cart.  In the cart summary it would show on a separate line due to the customized text.

### Describe a proposed solution
...
I found this in saleor/checkout/utils

> The `data` parameter may be used to differentiate between items with
    different customization options.

I have been trying unsuccessfully to get this information passed when the user clicks Add to Cart.  My idea was to somehow grab the data from the text input and add it to the data parameter.

### Other solutions I've tried and won't work
I tried adding a forms.CharField to the ProductForm in saleor/products/forms.   I was able to get it to display on the page and type in it but when the user clicks add to cart it does not appear in the request.POST.  

I would love to have a go at making a proper implementation but I think my lack of knowledge on how the add to cart button works is holding me back.  I tried to mess with some of the JS files what I can not seem to get any additional data to pass in to the request.POST.

**Comment by amorphic** [comment]
@xtrasalty I successfully implemented custom attributes using the `data` parameter but my work was based on a very old fork of Saleor (the code is in [this branch](https://github.com/amorphitec/enstaved-shop/tree/1080_user-selectable_product_attributes). If you take a look it might point you in the right direction.

Now that Saleor has a separate frontend decoupled from the Django backend it should be easier to add features like customisations.

**Comment by bachp** [comment]
Customizable products would be a great addition. But this might be a duplicate of https://github.com/mirumee/saleor/issues/5036
