### ISSUE TITLE
Duplicate choices in shipping address

### ISSUE THREAD

**Issue by georgy-komarov** [mirumee/saleor#3764]
### What I'm trying to achieve
I'm trying to set shipping user for Russian user and there are duplicate values in "Oblast" selector.

### Steps to reproduce the problem
1. Create new shipping address
2. Country --> Russia
3. There are duplicated values in "Oblast" selector

### What I expected to happen
There are no duplicated values in "Oblast" selector

### Screenshots
What happens now
<img src="https://user-images.githubusercontent.com/13136992/53255369-8a239600-36d6-11e9-84a6-24a10b96a321.png" width="300">

What I expect to see
<img src="https://user-images.githubusercontent.com/13136992/53255400-99a2df00-36d6-11e9-8913-ecaec174487a.png" width="300">

**System information**
Operating system: Manjaro Linux
Browser: Google Chrome 72.0.3626.81

**Comment by jxltom** [comment]
By the way, it has same issue for the GraphQL API. The API returns duplicated item with same ```raw``` but different ```verbose```
