### ISSUE TITLE
Add Discounted Price Field on GraphQL Products

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#3765]
### What I'm trying to achieve
It is normal to display the discounted price for a product on any listings. Ideally, we should have both the original price and the discounted price so we can show them side-by-side to the user. This is currently not available when the product is retrieved from graphql.

### Describe a proposed solution
Add a sale price field that holds the discounted price on the product representation in graphql. Additionally, having a list of the vouchers applicable to that product would be very useful to further entice shoppers.

### Other solutions I've tried and won't work
A roundabout way would be to request all the sales, all the vouchers, and then manually try to figure out if any of them apply to the product. When listing hundreds of products, this is just not efficient or practical.

**Comment by maarcingebala** [comment]
What you are looking for is the `availability` field in the `Product` type. This object provides information about the pricing of a product such as a price including/excluding discount, discount amount, information whether a product is on sale etc.:

```
product(id: "UHJvZHVjdDo2NA==") {
  name
  availability {
    available
    onSale
    discount {
      ...Price
    }
    priceRange {
      start {
        ...Price
      }
      stop {
        ...Price
      }
    }
    priceRangeUndiscounted {
      start {
        ...Price
      }
      stop {
        ...Price
      }
    }
  }
}
```
 
However, we should reiterate on that, as there is little consistency between fields available at the product and variants level. Few problems that I see:
- `ProductVariant` type returns only `price` field which doesn't include discounts. We should provide ways to return the base price (before any discounts are applied) and the actual price that customers see.
- Product price can be accessed through two different fields (that both act differently, which is confusing):
  - `availability` field - with discounts and other useful information about pricing
  - price` field - base price without discounts
- `ProductAvailability` type lacks descriptions

I think we should take a look at this part of the schema and think of a new, unified approach.

**Comment by khalibloo** [comment]
Thank you for the detailed explanation. I'd indeed overlooked `availability`. As someone with no commerce background, could you further explain to me the `gross` and `net` prices in `availability`? I'm guessing the amount to be paid by the customer would include taxes, so I should display `gross` discounted price, but I'm not certain of this.

Those problems listed are all valid and important. Some documentation on how discounts work would also be nice. For example, how are they calculated? How are multiple sales affecting a single product resolved? I'm sure they won't stack... but having these clearly described in the docs would be really helpful to developers with no commerce background.

**Comment by maarcingebala** [comment]
@khalibloo The difference between `gross` and `net` is as you said - `gross` prices include taxes while `net` don't. Whether to display gross or net prices to your customers vary between countries the shops are based in. As far as I know, some countries require to include taxes, e.g. in Europe, you have to use gross prices, while in the US not necessarily (but again - I'm not an expert in this field, and you'd have to read about it more yourself).

About the docs - I know it's not perfect now but we've just started putting together an extensive guide for our dashboard which will also cover such concepts like discounts, sales and how they work.

**Comment by NyanKiyoshi** [comment]
Proposed solution is to add a `availability` field of type `VariantAvailability` based on `ProductAvailability` for the `ProductType` variant as both variants and a products have the same availability data fields, except price ranges.
