### ISSUE TITLE
Dashboard Product Price Field Not Accepting Floats

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#3766]
### What I'm trying to achieve
Trying to set a float value such as 29.99 as a product price on the dashboard (1.0). I get the following error message right below the field `Ensure that there are no more than 0 decimal places.`. I came across https://github.com/mirumee/saleor/issues/355 from many years ago, but I'm not sure if it's the same error message. 

### Steps to reproduce the problem
1. Add a float value to the product price field on the dashboard. I haven't tested with other price fields

### What I expected to happen
I expected the dashboard to accept the float. It is common after all to have floats as product prices.

### Screenshots
![image](https://user-images.githubusercontent.com/6402969/53285612-f1475600-377b-11e9-919e-8f52274f13a6.png)

**System information**
Operating system: Windows 10
Browser: Firefox

**Comment by Pacu2** [comment]
Are you using the latest version of Saleor?

**Comment by patrys** [comment]
Do Mauritian Rupees have any denominations below 1 MUR?

**Comment by khalibloo** [comment]
My last pull was about a week ago. Just to be certain, I deployed a new saleor app on heroku just now. It surprisingly didn't have the same issue. I'll update my deployment to see if it solves it.

**Comment by khalibloo** [comment]
This has been fixed now. It works correctly on both the old and new dashboards. Thanks.
