### ISSUE TITLE
Running Saleor in kubernetes/docker fails to work after some hours.

### ISSUE THREAD

**Issue by nixxon111** [mirumee/saleor#3767]
### What I'm trying to achieve
Running base saleor in Kubernetes/Docker on Google Cloud for an extended period of time.
(only modified database conn. string and file storage in config)

### The Issue
Everything will run smoothly for some time, and then suddenly the site becomes unresponsive after ~4 hours, some times much less. When this happens, all requests hang forever.

### Steps to reproduce the problem
Create and start a workload in a kubernetes cluster on GCP, with the docker-image built like this:
docker build -t mystorefront .
docker push gcr.io/MY_GCP_REPO/mystorefront

The screenshot below is the only clue I have.

Should I attempt to add more logging? Is this a known issue?
I have done very little work with uwsgi and django, and am therefor unsure, exactly what goes wrong, but the logs seem to indicate something with the thread/process manager "behind the scenes".

### What I expected to happen
Saleor running "forever".

### Screenshots
![image](https://user-images.githubusercontent.com/5196017/53319511-04b90500-38d3-11e9-9531-77b1ec9dec58.png)

**Comment by garyrvaz** [comment]
+1
