### ISSUE TITLE
Customer can edit order / add discounts up until they pay

### ISSUE THREAD

**Issue by jamespsteinberg** [mirumee/saleor#3779]
That last button, "Order & Pay" has quite confusing behavior to a customer. 

- It empties the customer's cart
- Does not allow them to go backwards and edit information in the process (what if they realized they typed their address wrong?)
- The paying stage is where a customer is most likely to abandon cart, typically you could offer them a discount or add a free item to the order

![image](https://user-images.githubusercontent.com/1237324/53443522-e558cf80-39d9-11e9-8240-4a9e493a14d9.png)

I understand the only benefit here is it allows the customer to create an order and pay later or in installments? I can't imagine the majority of ecommerce uses this feature.

![image](https://user-images.githubusercontent.com/1237324/53443510-dd992b00-39d9-11e9-8781-6f76d1d230be.png)

For the sake of potentially less clicks / consistent design (https://github.com/mirumee/saleor/issues/2018), it may make sense to just put the payment on the same page as the shipping/billing addresses. 

I will of course look into adding this myself, but is anything related to this being considered?
Thanks!

**Comment by jamespsteinberg** [comment]
Actually noticed the PWA version solves this, awesome, will have to figure something out with the current solution though

**Comment by maarcingebala** [comment]
We're not considering to make any changes to the flow in Storefront 1.0.
