### ISSUE TITLE
npm run build-assets problem

### ISSUE THREAD

**Issue by WrapTheCode** [mirumee/saleor#3793]
Hi

I have a problem with: npm run build-assets. 
I have node -v 
v10.9.0 

and i got this: 
`This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.`

In attachment i put error log and console log.

Thanks for any help
[2019-03-03T16_53_12_867Z-debug.log](https://github.com/mirumee/saleor/files/2923395/2019-03-03T16_53_12_867Z-debug.log)
[console.log](https://github.com/mirumee/saleor/files/2923396/console.log)

**Comment by vasuporov** [comment]
@maarcingebala -  Even I am stuck with this, can you please help. Tried many versions 10.15.1, 10.15.3 and 11.

**Comment by maarcingebala** [comment]
@dominik-zeglen Do you know what might be the issue here?

**Comment by dominik-zeglen** [comment]
Did you install dependencies with `yarn` or `npm`?

**Comment by vkuzma** [comment]
I am having the same issue and I am working with npm.
node v11.14.0

**Comment by NyanKiyoshi** [comment]
@vkuzma can you give the steps to reproduce your issue?

Make sure you:
1. Delete `.node_modules` so we start from scratch
1. `npm i`
1. `npm run build-assets`

**Comment by vkuzma** [comment]
@NyanKiyoshi The issue happens when I am doing these steps (last step).
Here is my log: 
[console.log](https://github.com/mirumee/saleor/files/3127523/console.log)

**Comment by maarcingebala** [comment]
Due to no response, I assume this issue was resolved. There is a lot of similar issues and usually, the problem is the wrong Node/NPM version. Removing `node_modules` and reinstalling dependencies also helps in cases like this.
