### ISSUE TITLE
Adding pipelines in heroku BUG

### ISSUE THREAD

**Issue by afhaider** [mirumee/saleor#3794]
I tried adding requirement.txt/pipfile django-compressor heroku unable to identify even I try heroku run pip it also not work since u people not add pip in piplock

**Comment by jxltom** [comment]
If you are using Pipfile, heroku will ignore requirements.txt. So you can add it to Pipfle by ```pipenv install django-compressor```

**Comment by afhaider** [comment]
Sir their issue with pipenv in window do u have any resolve to it ?like it not recognise I tried in pipenv in Ubuntu it work properly but my project can't push in heroku since it pulling require and remove any changes done

**Comment by jxltom** [comment]
It will easier to diagnose if you include example of heroku output.

But generally speaking, after ```pipenv install django-compressor``` you need to commit the updated Pipfile and Pipfile.lock in git.

**Comment by afhaider** [comment]
Thanks this work I guess those 2file only modify

**Comment by afhaider** [comment]
"Setting %s is not of type" % variable, instance_type
remote: django.core.exceptions.ImproperlyConfigured: ('Setting RECAPTCHA_PRIVATE_KEY is not of type', <class 'str'>)
remote: Waiting for release.... failed.
]
i tried so many thing no work this bug happen when i run on ubuntu saleor copy piplock pipfile into my window saleor

**Comment by jxltom** [comment]
It looks like you setting ```RECAPTCHA_PRIVATE_KEY``` is not a string. It has nothing to do with Pipfile.

**Comment by afhaider** [comment]
Is their any solution ?

**Comment by afhaider** [comment]
Only thing I know if this error occurred I need to remove whole repo from heroku and apply new one with old Piplock pipfile by removing htmlmin pip

**Comment by afhaider** [comment]
Everytime I install pipenv bug come reCAPTCHA private key help

**Comment by afhaider** [comment]
fixed thnx alot bro
