### ISSUE TITLE
Add query to fetch draft orders

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3796]
In the Dashboard 2.0 we want to have separate links to view draft orders and confirmed ones. For that reason we need to add a separate resolver to return only draft orders. Exiting `orders` resolver should be changed to return confirmed orders.

**Comment by jxltom** [comment]
How about adding ```orderStatus``` or ``````orderStatuses``` argument which can filter the draft order or orders with any statuses in the backend for orders API?

**Comment by michaljelonek** [comment]
I agree with @jxltom, a new resolver makes no sense if we have means to use filtering. We already have such argument, but it only allows filtering on two statuses:
```
class OrderStatusFilter(graphene.Enum):
    READY_TO_FULFILL = 'READY_TO_FULFILL'
    READY_TO_CAPTURE = 'READY_TO_CAPTURE'
```
It could be improved to actually use all the status choices and perhaps accept a list of status choices instead of just one.

**Comment by maarcingebala** [comment]
I agree that we need to extend filtering capabilities in the `orders` resolver - that will be required by Dashboard 2.0 anyway at some point. But I would exclude draft status from this resolver and have a separate one for a few reasons:
- drafts use different logic than regular orders - they can be edited in many ways or deleted from DB,
- by having a separate field in API we make it clear to API consumers that "drafts" and "regular" orders are a bit different concepts,
- draft orders are visible only to staff users - it's easier to require permission when we have a separate field for that.
