### ISSUE TITLE
Unable to create product through Dashboard 2.0

### ISSUE THREAD

**Issue by michaljelonek** [mirumee/saleor#3797]
### What I'm trying to achieve
To create a product. 

### Steps to reproduce the problem
1. Try to add a product through the new Dashboard.
* ~Enter just the name -> `Something went wrong: GraphQL error: 'NoneType' object has no attribute 'has_variants'`~ - Fixed in https://github.com/mirumee/saleor/pull/3804
* Enter name and product type (variant-less) and any other fields (all or just couple) -> `Save` changes to `Error` and nothing happens, SKU field is required but not shown
* Required fields are not marked as required.

### What I expected to happen
Product is successfully created.

#### No required fields
![image](https://user-images.githubusercontent.com/7791528/53802590-7122ac80-3f42-11e9-866e-0c1d46ea9933.png)

**System information**
Operating system: n/a
Browser: Chrome

**Comment by michaljelonek** [comment]
One issues with the API:
- throws an exception when product-type is not selected

Other front-end related issues:
- when a variant-less product type is selected the SKU field is not shown
- required fields are not shown, instead "Save" changes to "Error" when attempting to save

**Comment by michaljelonek** [comment]
There's also a problem with sending `"null"` (in quotes) for `descriptionJson` (`JSONString`) fields, it throws an error `Expected type "JSONString", found "null".`. From the looks of it it's a known issue -> https://github.com/graphql-python/graphql-core/issues/224. 

@dominik-zeglen any way we can instead send `null` (without quotes) or `""` for empty description?

**Comment by maarcingebala** [comment]
I think we're not showing errors coming from API in this view (which is not the first time we forget about it - maybe we should improve our components to require it somehow?)
