### ISSUE TITLE
ERROR for site owner: Invalid key type -RECAPTCHA

### ISSUE THREAD

**Issue by afhaider** [mirumee/saleor#3798]
SoS

**Comment by Pacu2** [comment]
Please provide more information

**Comment by afhaider** [comment]
bro
my site is ikcollection.herokuapp.com

**Comment by jxltom** [comment]
Please pin ```django-recaptcha = "<=1.5.0"``` in your Pipfile and lock again since Saleor doesn't support 2.x as https://github.com/mirumee/saleor/issues/3625

**Comment by afhaider** [comment]
http://haideraf.pythonanywhere.com/music/create_album/ bug

**Comment by afhaider** [comment]
BUG FIXED thnx 1.5

**Comment by bishwasbh** [comment]
Use can use Google Recaptcha V2 or this solution for [Invalid key type: RECAPTCHA](https://webmatrices.com/d/235-website-owner-error-key-type-is-invalid-django-recaptcha/4) will surely help you.
