### ISSUE TITLE
Add support for bulk deleting in API

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3799]
We're implementing bulk actions in Dashboard 2.0 (#3537) and we need to support them in API as well. I'd look at our Figma mockups in order to determine which models need that, but I'd guess that all of them.

A first action that we'll add is bulk delete. The easiest and quickest way (1) to support that is to modify our existing "delete mutations" to receive a list of IDs instead of a single ID e.g.:
`categoryDelete(id: ID!)` -> `categoryDelete(ids: [ID!]!)`

Another way (2) is to introduce dedicated bulk delete mutations:
`categoryBulkDelete(ids: [ID!]!)`.

Originally I wanted to choose the first option but now I'm wondering if it wasn't more elegant to have dedicated mutations for that?

**Comment by patrys** [comment]
I would create a separate bulk API as it will return a different shape of errors should anything go wrong. Another problem is that schema gives us no way to indicate that `categoryDelete` without arguments is illegal and so is specifying both `id` and `ids`.

**Comment by maarcingebala** [comment]
Also, if we later introduce other bulk actions, they'll be implemented as new mutations as well. If we do the same for bulk deleting now, eventually we'll have a consistent API where all bulk actions use the same naming pattern and are easy to find and understand.
