### ISSUE TITLE
Add js library to storefront assets

### ISSUE THREAD

**Issue by totraku** [mirumee/saleor#3805]
### What I'm trying to achieve
I want to add the following js [library](https://pawelgrzybek.github.io/siema) and use it in a template in the storefront which extends the base.html template.
### Steps to reproduce the problem
I have installed the siema npm and imported it in the storefront.js
But somehow it isn't included in the sotrefront assets, even after building them.

### What I expected to happen
The library is found in the built assets.

**Comment by dominik-zeglen** [comment]
How do you know it is not included in assets?
Have you initialized it like in docs?

With `storefront.js` like this

```
import 'jquery';
import 'jquery.cookie';
import 'bootstrap';
import Siema from 'siema';

import '../scss/storefront.scss';

import './components/address-form';
import './components/cart';
import './components/footer';
import './components/language-picker';
import './components/misc';
import './components/navbar';
import './components/password-input';
import './components/product-filters';
import './components/sorter';
import './components/styleguide';
import './components/variant-picker';

new Siema();
```

I get siema's error about wrong selector meaning that the library was included in final bundle.
