### ISSUE TITLE
Validate languageCode in API

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3815]
We use `languageCode` argument in various queries and mutations. We should add some validation that will check if the provided code is supported by Saleor i.e. is present in `LANGUAGES` list in Django settings. 

E.g. this should return an error:
```graphql
mutation {
  productTranslate(id: "UHJvZHVjdDo3Mg==", languageCode: "asd", input: {}) {
    errors {
      field
      message
    }
    product {
      name
    }
  }
}
```

**Comment by patrys** [comment]
Since the list of possible languages is predetermined, wouldn't it make sense to make this an enum?

**Comment by maarcingebala** [comment]
Yep, that's even better.
