### ISSUE TITLE
Hidden labels for another payment providers

### ISSUE THREAD

**Issue by mitcom** [mirumee/saleor#384]
We use widget `forms.RadioSelect` for payment providers and render these without any template tags nor by calling method (`.as_...`) in template.

If I set another providers like:

```
CHECKOUT_PAYMENT_CHOICES = [
    ('default', 'Dummy provider'),
    ('other', 'Dummy provider2'),
    ('another', 'Dummy provider3'),
]
```

I only can see:
![download](https://cloud.githubusercontent.com/assets/1809192/10997093/75b8adb0-848a-11e5-9c2d-fae0cf0c22f8.png)

**Comment by krzysztofwolski** [comment]
Tried to reproduce, but it looks good now:
![payment_methods](https://cloud.githubusercontent.com/assets/5188636/20352796/e9521dae-ac18-11e6-9aab-0dc8d2a477c1.png)
