### ISSUE TITLE
Installing - Wrong Version of Node

### ISSUE THREAD

**Issue by agustempo** [mirumee/saleor#3842]
I have a problem as i install everything for the first time, this is it:

```
npm ERR! Linux 4.18.0-16-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build-assets"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! saleor@0.0.0 build-assets: `webpack -p`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the saleor@0.0.0 build-assets script 'webpack -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the saleor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs saleor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls saleor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sugar/sale/npm-debug.log

```

this is the log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build-assets' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild-assets', 'build-assets', 'postbuild-assets' ]
5 info lifecycle saleor@0.0.0~prebuild-assets: saleor@0.0.0
6 silly lifecycle saleor@0.0.0~prebuild-assets: no script for prebuild-assets, continuing
7 info lifecycle saleor@0.0.0~build-assets: saleor@0.0.0
8 verbose lifecycle saleor@0.0.0~build-assets: unsafe-perm in lifecycle true
9 verbose lifecycle saleor@0.0.0~build-assets: PATH: /usr/share/npm/bin/node-gyp-bin:/home/sugar/sale/node_modules/.bin:/home/sugar/saleor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle saleor@0.0.0~build-assets: CWD: /home/sugar/sale
11 silly lifecycle saleor@0.0.0~build-assets: Args: [ '-c', 'webpack -p' ]
12 silly lifecycle saleor@0.0.0~build-assets: Returned: code: 2  signal: null
13 info lifecycle saleor@0.0.0~build-assets: Failed to exec build-assets script
14 verbose stack Error: saleor@0.0.0 build-assets: `webpack -p`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid saleor@0.0.0
16 verbose cwd /home/sugar/sale
17 error Linux 4.18.0-16-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build-assets"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error saleor@0.0.0 build-assets: `webpack -p`
22 error Exit status 2
23 error Failed at the saleor@0.0.0 build-assets script 'webpack -p'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the saleor package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack -p
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs saleor
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls saleor
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

The versions

`(saleor) sugar@charco:~/sale$ node -v
v11.12.0
(saleor) sugar@charco:~/sale$ npm -v
3.5.2
`

**Comment by Pacu2** [comment]
Something is wrong with your nodejs and npm versions.
In the first log it says:
```npm ERR! node v8.10.0
npm ERR! npm  v3.5.2```
Then in the last
```(saleor) sugar@charco:~/sale$ node -v v11.12.0 (saleor) sugar@charco:~/sale$ npm -v 3.5.2```

You should use node v11.x and npm 6.x

**Comment by agustempo** [comment]
Thanks!! that had been very useful! now i'm at the right versions, but i get this in the error logo
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/bin/npm', 'run', 'build-assets' ]
2 info using npm@6.7.0
3 info using node@v11.12.0
4 verbose run-script [ 'prebuild-assets', 'build-assets', 'postbuild-assets' ]
5 info lifecycle saleor@0.0.0~prebuild-assets: saleor@0.0.0
6 info lifecycle saleor@0.0.0~build-assets: saleor@0.0.0
7 verbose lifecycle saleor@0.0.0~build-assets: unsafe-perm in lifecycle true
8 verbose lifecycle saleor@0.0.0~build-assets: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecy
cle/node-gyp-bin:/home/sugar/sale/node_modules/.bin:/home/sugar/saleor/bin:/usr/local/sbin:/usr/local/
bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle saleor@0.0.0~build-assets: CWD: /home/sugar/sale
10 silly lifecycle saleor@0.0.0~build-assets: Args: [ '-c', 'webpack -p' ]
11 silly lifecycle saleor@0.0.0~build-assets: Returned: code: 2  signal: null
12 info lifecycle saleor@0.0.0~build-assets: Failed to exec build-assets script
13 verbose stack Error: saleor@0.0.0 build-assets: `webpack -p`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle
/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle
/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:988:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid saleor@0.0.0
15 verbose cwd /home/sugar/sale
16 verbose Linux 4.18.0-16-generic
17 verbose argv "/usr/local/bin/node" "/usr/bin/npm" "run" "build-assets"
18 verbose node v11.12.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 2
22 error saleor@0.0.0 build-assets: `webpack -p`
22 error Exit status 2
23 error Failed at the saleor@0.0.0 build-assets script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
`
