### ISSUE TITLE
field_types[name] generics type cannot be used with isinstance (python 3.7)

### ISSUE THREAD

**Issue by hanyelbanna** [mirumee/saleor#3844]
### What I'm trying to achieve

Pycharm error

python 3.7

### Steps to reproduce the problem

saleor/saleor/payment/utils.py

Line 332

`field_types = {
        'amount': Decimal,
        'currency': str,
        'is_success': bool,
        'kind': str,
        'transaction_id': str,
        'error': (type(None), str),
    }

    for response in responses:
        if not REQUIRED_GATEWAY_KEYS.issubset(response):
            raise GatewayError(
                'Gateway response needs to contain following keys: {}'.format(
                    sorted(REQUIRED_GATEWAY_KEYS)))

        for name, value in response.items():
            if name in field_types:
                if not isinstance(value, field_types[name]):
                    raise GatewayError('{} must be of type {}, was {}'.format(
                        name, field_types[name], type(value)))

        if response['kind'] not in ALLOWED_GATEWAY_KINDS:
            raise GatewayError(
                'Gateway response kind must be one of {}'.format(
                    sorted(ALLOWED_GATEWAY_KINDS)))

        if response['currency'] != settings.DEFAULT_CURRENCY:
            logger.warning('Transaction currency is different than Saleor\'s.')

        try:
            json.dumps(response, cls=DjangoJSONEncoder)
        except (TypeError, ValueError):
            raise GatewayError(
                'Gateway response needs to be json serializable')`

`if not isinstance(value, field_types[name]):`

error: Parameterized generics cannot be used with instance and class checks

isinstance not accept generics type field_types[name] 

### What I expected to happen
…

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by maarcingebala** [comment]
@hanyelbanna What are the exact steps to reproduce the error? It is not so clear from the description you've provided. Were you able to resolve it?
