### ISSUE TITLE
Right to left support

### ISSUE THREAD

**Issue by j209** [mirumee/saleor#3845]
Can saleor support right to left cultures like Arabic,Hebr,Persian?

**Comment by maarcingebala** [comment]
There is no built-in support for RTL in Saleor, but that's something that should be added in the future. I'd like to hear what's the best approach to achieve that and how much effort would that require.

**Comment by j209** [comment]
These may help:
[Bootstrap4 RTL](https://github.com/RTLCSS/bootstrap)
[Material-UI RTL](https://material-ui.com/guides/right-to-left/#opting-out-of-rtl-transformation)
[Materializecss RTL](https://github.com/MahdiMajidzadeh/materialize-rtl)
[Material Design Light RTL](https://github.com/RTLCSS/material-design-lite)

**Comment by j209** [comment]
Any news?!

**Comment by maarcingebala** [comment]
No update on this so far. I think this issue is more related to our frontend parts. We'll be planning the priorities for next releases soon, I'll make sure to raise this topic as well.

**Comment by jntdst** [comment]
Hi, Is it added?

> Can saleor support right to left cultures like Arabic,Hebr,Persian?

**Comment by selmanuysal** [comment]
Hi, 
Right to Left support is added ?

**Comment by mlamaa** [comment]
Right to Left support is added?

**Comment by proalaa** [comment]
Hi here 

what are the news about supporting RTL?

**Comment by proalaa** [comment]
Hi here 

what are the news about supporting RTL?
