### ISSUE TITLE
Migrate to Black

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3846]
Currently, in Saleor we use Yapf code formatter for Python. The problem is that we've never actually formatted the whole codebase with it which results in mixed code styles across the project. Another problem is that we don't have any automatic formatting enabled so we cannot enforce a unified style in PRs from the community.

We could stick to Yapf, but in the meantime, a new tool appeared - [Black](https://github.com/ambv/black) - and it's becoming adopted by many other Python projects. A few teams also use it at Mirumee and they recommend it. After internal discussion, we decided to migrate to Black in Saleor as well. This change will affect every open PR and will probably cause a lot of merge conflicts for those how regularly update Saleor, but this step is necessary to improve the readability and consistency of Saleor's codebase.

What needs to be done:
- add `black` to dev requirements
- apply the new formatting
- configure automatic formatting - I'd like to hear some feedback on that as I don't know what might be the best way to achieve that. One solution that I found is [pre-commit](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/) and it looks quite promising.

**Comment by jxltom** [comment]
Maybe we could also consider adding isort/db-migration/graphql-schema/ts-types checks in pre-commit.

We may need following part in Pipfile since black still doesn't have a stable release.

```
[pipenv]
allow_prereleases = true
```

**Comment by maarcingebala** [comment]
For now, I would rather only one tool and if it works for us, reconsider adding automating more in the future.

**Comment by krzysztofwolski** [comment]
Also, there should be proper tests launched on CI.

Re isort - I like this tool, but sometimes I've got problems when using with black. And `pre-commit` can't work with it - theres issue with python environment separation.

**Comment by krzysztofwolski** [comment]
@jxltom thanks for code review! 💪  
As you noticed, black has a nonstandard line length of 88 chars. Personally, I like the reasoning and approach of its authors: https://github.com/ambv/black#line-length
88 Chars give extra breathing room when using types and clear (I mean long 😆) variable names. And still can open 2 files on one screen without horizontal scrolling.

Do we embrace 88?

**Comment by krzysztofwolski** [comment]
Update: We are waiting for version 1.0 - ATM black is preparing new version which will for sure affect our codebase. To Avoid making massive formatting twice, we will wait. 

Related tweet: https://twitter.com/llanga/status/1106247623802060802

**Comment by NyanKiyoshi** [comment]
About `pre-commit`, I would suggest to run it inside a GH-action. It would be much faster and won't fail the travis build.

Unless there is a better solution (like a GH bot or something, that could generate rapports).

**Comment by NyanKiyoshi** [comment]
Note that we also need to update the docs accordingly.

**Comment by maarcingebala** [comment]
Merged #3852. A new era has begun 😄
