### ISSUE TITLE
How to access to installed saleor?

### ISSUE THREAD

**Issue by izzy777** [mirumee/saleor#3860]
Hi everyone! First of all sorry for my English and for that I'm newbie at Django, Python and etc.  

My problem is that after I installed saleor on my AWS I cant access to the site from public IP.

With latest command in tutorial I got this message in terminal:

> System check identified no issues (0 silenced).
> March 21, 2019 - 00:48:19
> Django version 2.1.7, using settings 'saleor.settings'
> Starting development server at http://127.0.0.1:8000/

When I'm trying to access http://public.ip:8000 browser says: "Connection Refused".

Please, refer me to the right answer or maybe I forgot something to do while installation steps. Please, help me to solve this problem.

P.S. I added to inbound rules the port 8000 to access anywhere, but no success

**System information**
Operating system: Ubuntu Bionic 18.04

**Comment by NyanKiyoshi** [comment]
Hi,

The HTTP server is listening to the loopback interface (`127.0.0.1`), instead of the network interface. For that, start your server using `0.0.0.0:8000` as binding.
