### ISSUE TITLE
Given name and Family name oddly used in American English (en) locale

### ISSUE THREAD

**Issue by josephmay7** [mirumee/saleor#3864]
All the English used in the "en" locale follows standard American English, except for "Given name" and "Family name", which should be "First name" and "Last name" respectively.

"Given name" and "Family name" would be appropriate for British English, but there is no en_GB locale in this project.

I noticed this when playing with the demo:

<img width="654" alt="saleor_checkout" src="https://user-images.githubusercontent.com/46604847/54844719-ed8ced80-4cad-11e9-9d08-84c5e44ad4c7.png">

**Comment by patrys** [comment]
We prefer "given name" as it's a broader term and it applies to people from all cultures where "first name" is a Christian construct and is only used in some western cultures. We don't translate these fields on a per-country basis.

**Comment by josephmay7** [comment]
No worries - search and replace would solve that.  Saleor currently seems EU-centric, but I do see some efforts in the roadmap to make it more US-friendly (e.g. FedEx/UPS shipping integrations), so I'll keep checking back.
