### ISSUE TITLE
How to integrate the alipay and wechat payment in saleor?

### ISSUE THREAD

**Issue by shellwang** [mirumee/saleor#3870]
I am planned to develop a e-commerce solutions in China using saleor.  But cannot find a solution to integrate the most common-used payment alipay and wechat.

I also read the saleor payment docs (https://docs.getsaleor.com/en/latest/architecture/payments.html). But cannot find the  easy way to integrate.

I also find the wechat docs(https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=11_1) in Chinese. They provide a SDK. But how to integrate the SDK in saleor?

**Comment by maarcingebala** [comment]
Hey @shellwang, currently we don't have any official support for these gateways, I also don't know about any "unofficial" implementations. Payments architecture in Saleor is not in the final form yet as we're going to make the API cleaner by [extracting some of the common payment interfaces](#3678) to an external library. Also, we're going to move the gateways integration code to separate project as well (#3422).

I'm not familiar with neither of these gateways, so I cannot tell you about the details of the implementation, but I would assume that most gateways work in a similar manner. I'd recommend looking at the Stripe or Braintree implementation that we currently have and then try to implement a simliar flow for Alipay/Wechat. 

After quick googling, I found some [Python bindings to Alipay](https://github.com/fzlee/alipay) that could be helpful. In the case of Wechat, if there is no Python library, you'd have to create some Python client yourself, that you could later use with Saleor.

I hope this helps you somehow. If you have more specific questions about our payments architecture, feel free to ask.

**Comment by shellwang** [comment]
@maarcingebala Thanks for your reply. I'm still do research on Alipay and Wechat. Yes, that's true. Someone have integrated Alipay successfully. I will refer to the information you provided. Truly thanks.

**Comment by shellwang** [comment]
Since the payment is the core problem of e-commerce website. I fully support you move the gateway integration to a separate repo.

**Comment by jxltom** [comment]
Alipay and wechat have huge market in China, it sounds very promising to integrate alipay and wechat into Saleor.

**Comment by NyanKiyoshi** [comment]
@shellwang I think you can pay through wechat using Stripe as well. Stripe is already implemented in Saleor, it would probably require some changes though.

That could be a temporary solution, until Alipay gets implemented. Alipay being used by literally everyone in China.

**Comment by bwanglzu** [comment]
@NyanKiyoshi guess this document shows that stripe also supports alipay? [link](https://stripe.com/docs/sources/alipay)
