### ISSUE TITLE
Gateway Timeout 504 Error

### ISSUE THREAD

**Issue by yourtechcare** [mirumee/saleor#3872]
Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.

**Comment by jxltom** [comment]
It's better to mention which api would raise this error.

**Comment by yourtechcare** [comment]
saleor/wsgi/__init__.py used under apache conf file for WSGIScriptAlias

**Comment by yourtechcare** [comment]
cause wsgi.py not available in saleor folder

**Comment by yourtechcare** [comment]
![MyMLAB_Apache](https://user-images.githubusercontent.com/16338809/55054051-598f9d00-5084-11e9-970b-6d3a5b27cf83.JPG)

**Comment by jxltom** [comment]
Did you change the configuration file of uwigi.ini? Did you pass configuration file to uwsgi during startup such as by ```uwsgi saleor/wsgi/uwsgi.ini```?

**Comment by yourtechcare** [comment]
No i didn't changed uwsgi.ini file

**Comment by yourtechcare** [comment]
[uwsgi]
die-on-term = true
http-socket = :$(PORT)
log-format = UWSGI uwsgi "%(method) %(uri) %(proto)" %(status) %(size) %(msecs)ms [PID:%(pid):Worker-%(wid)] [RSS:%(rssM)MB]
master = true
max-requests = 100
memory-report = true
module = saleor.wsgi:application
processes = 4
static-map = /static=/app/static
mimefile = /etc/mime.types

**Comment by yourtechcare** [comment]
Guide me what's wrong in my configuration file & any tutorial how to implement uwsgi with saleor project ?

**Comment by jxltom** [comment]
> Did you pass configuration file to uwsgi during startup such as by `uwsgi saleor/wsgi/uwsgi.ini`? Did you check the logs of uwsgi?

**Comment by yourtechcare** [comment]
Waiting for reply & support !

**Comment by yourtechcare** [comment]
Where do i place this code "uwsgi saleor/wsgi/uwsgi.ini" in which file ?

**Comment by jxltom** [comment]
I think you should start uwsgi by ```uwsgi saleor/wsgi/uwsgi.ini```. How did you start the application?

**Comment by yourtechcare** [comment]
using command "python manage.py runserver 0.0.0.0:8000" but i want to assign that saleor app to my domain using apache web server - no tutorials available anywhere to configure saleor with our domain.

**Comment by yourtechcare** [comment]
i used this command to execute "uwsgi saleor/wsgi/uwsgi.ini" on ssh access, but still unable to get website loads with saleor, please guide to configure saleor with my domain.

**Comment by jxltom** [comment]
The ```runserver``` is not suitable for production server. And you need to bind apache server with your local address with correct port.

**Comment by yourtechcare** [comment]
I did shared my apache configuration in above screenshot, would you please guide me what to changes in it ?

**Comment by jxltom** [comment]
The https://uwsgi-docs.readthedocs.io/en/latest/Apache.html might be useful. You need to setup ```ProxyPass / http://localhost:8000/``` or something like that in Apache.

**Comment by yourtechcare** [comment]
Possible for you to share an example apache configuration file ?

**Comment by yourtechcare** [comment]
(myvirtual_env) admin@host:~/web/ZZZZ.com/myvirtual_env/saleor$ uwsgi saleor/wsgi/uwsgi.ini
[uWSGI] getting INI configuration from saleor/wsgi/uwsgi.ini
[uwsgi-static] added mapping for /static => /app/static
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 28 08:23:52 2019] ***
compiled with version: 7.3.0 on 14 March 2019 05:59:57
os: Linux-4.15.0-1034-aws #36-Ubuntu SMP Tue Mar 5 23:17:16 UTC 2019
nodename: host.ZZZZ.com
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/admin/web/ZZZZ.com/myvirtual_env/saleor
detected binary path: /home/admin/web/ZZZZ.com/myvirtual_env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3841
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :$(PORT) fd 3
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55f360543b30
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55f360543b30 pid: 12496 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12496)
spawned uWSGI worker 1 (pid: 12502, cores: 1)
spawned uWSGI worker 2 (pid: 12503, cores: 1)
spawned uWSGI worker 3 (pid: 12504, cores: 1)
spawned uWSGI worker 4 (pid: 12505, cores: 1)

========================================
Apache set with proxy now error : 
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by yourtechcare** [comment]
any support ?

**Comment by jxltom** [comment]
I think you might need to set ```PORT``` environment variable to startup uwsgi.

**Comment by yourtechcare** [comment]
LIke as any example ?

**Comment by yourtechcare** [comment]
ok domain mapping done, Thanks for your support,
but images not loading !

**Comment by yourtechcare** [comment]
Also it taking way longer to load to website using uwsgi

**Comment by yourtechcare** [comment]
Request Timeout
Server timeout waiting for the HTTP request from the client.

**Comment by yourtechcare** [comment]
& Why saleor doesn't generate wsgi.py file ?
