### ISSUE TITLE
Payment gateways should use VCR casetes for gateway responses

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#3876]
VCR.py allows to record server response and use it during tests. Using that would help validate that payment gateways are correctly working on real life environment instead of using hand-made mockups.

https://vcrpy.readthedocs.io/en/latest/

https://pypi.org/project/pytest-vcr/

**Comment by patrys** [comment]
One thing to consider is how we can prevent cassettes from recording our sandbox API keys.
