### ISSUE TITLE
Alternative order creation flow

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#3877]
Current flow:

- user add products to cart
- fills shipment data
- clicks on 'create and pay' 
- order is created 
- user can pay for order

This flow is good in some applications (That's what for example Allegro doing), but in my projects it's not the best one - it creates many stale orders, reserve stock and block user from changing which products to buy.

Flow I implement in my projects:

- user add products to cart
- fills shipment data
- fills payment data
- if payment was successful - create order

Discussion:
- do we change default flow? Or if we even should
- can we make it confgurable?

**Comment by jxltom** [comment]
Currently, the static storefront 1.0 is using the first approach while GraphQL API is using the second approach, I think. I remember there is discussion here https://github.com/mirumee/saleor/issues/3564.

**Comment by maarcingebala** [comment]
Storefront 1.0 allows you to create order without even providing any payment method. In API the flow is a bit different as we create order and charge the payment in one call. But still, if the payment fails, an unpaid order will be created. I guess we should change this behavior and create order only after successful payment.

**Comment by krzysztofwolski** [comment]
Error in PWA found.

To reproduce: add product to cart, fill checkout etc, use braintree and this card: https://developers.braintreepayments.com/reference/general/testing/php#fraud-tools

Outcome:
![Screenshot 2019-03-27 at 16 25 42](https://user-images.githubusercontent.com/5188636/55089111-30373700-50ad-11e9-875e-d430f9b0624a.png)

And order created anyway: https://demo.getsaleor.com/dashboard/orders/2726/

**Comment by krzysztofwolski** [comment]
Error occurs because 'place your order' uses 'CheckoutComplete' migration. 

```
# CheckoutComplete.mutate function 
        try:
           order = create_order(
                cart=checkout,
                tracking_code=analytics.get_client_id(info.context),
                discounts=info.context.discounts, taxes=taxes)
        except InsufficientStock:
            cls.add_error(
                field=None, message='Insufficient product stock.',
                errors=errors)
            return CheckoutComplete(errors=errors)
        except voucher_model.NotApplicable:
            cls.add_error(
                field=None, message='Voucher not applicable', errors=errors)
            return CheckoutComplete(errors=errors)

        payment = checkout.get_last_active_payment()

        # remove cart after checkout is created
        checkout.delete()
        order.events.create(type=OrderEvents.PLACED.value)
        send_order_confirmation.delay(order.pk)
        order.events.create(
            type=OrderEvents.EMAIL_SENT.value,
            parameters={
                'email': order.get_user_current_email(),
                'email_type': OrderEventsEmails.ORDER.value})
        # order created and we just started to handle payment
        try:
            gateway_process_payment(
                payment=payment, payment_token=payment.token)
        except PaymentError as e:
            cls.add_error(errors=errors, field=None, message=str(e))
        return CheckoutComplete(order=order, errors=errors)
```
