### ISSUE TITLE
Price filter does not consider discounted price

### ISSUE THREAD

**Issue by ipsingh06** [mirumee/saleor#3888]
### What I'm trying to achieve
The price filter on the category page should take the discounted price into account.

### Steps to reproduce the problem
1. Run a fresh copy of the docker image for development.
2. Browse to the category page for Apparel (http://localhost:8000/en/products/category/apparel-9/)
3. Set a price filter for 0 to 25 and hit update results.
    No items are returned in the results.

### What I expected to happen
I expected the 6 items discounted to below $25 to show up in the results.

**Comment by AleRiccardi** [comment]
Because the filter works only matching the field `price` of the model _Product_ with the range price chose by the user, then the _FilterSet_ class cannot understand how to filter by the discounted price.

To do so I created a custom filter that permit: first to retrieve all the products, then filter them by the method `is_in_price_range` and finally filter them by their ids.

```Python
class ProductFilter(SortedFilterSet):
 
    price = RangeFilter(
        label=pgettext_lazy('Currency amount', 'Price'),
        method='filter_price')

    [...]

    def filter_price(self, queryset, name, value):
        q = queryset.filter()
        q_ids = [o.id for o in q if o.is_in_price_range(value.start, value.stop)]
        return queryset.filter(id__in=q_ids)
```

```Python
class Product(SeoModel, PublishableModel):
    
    [...]

    def is_in_price_range(self, start, stop):
        discounts = Sale.objects.active(date.today()).prefetch_related(
            'products', 'categories', 'collections')
        taxes = SimpleLazyObject(lambda: get_taxes_for_country(
            Country(settings.DEFAULT_COUNTRY)))
        price_range = get_availability(self, discounts=discounts, taxes=taxes).price_range
        if display_gross_prices():
            price_start = price_range.start.gross.amount
            price_stop = price_range.stop.gross.amount
        else:
            price_start = price_range.start.net.amount
            price_stop = price_range.stop.net.amount
        start_price = True if start <= price_start <= stop else False
        stop_price = True if start <= price_stop <= stop else False
        return start_price or stop_price
```
I want to say that this is not the best performing solution, but I tried to coming up with a clear and easy one to understand.

**Comment by maarcingebala** [comment]
We now have `minimal_variant_price` field which contains the lowest price of a product. This field should be used for this kind of filtering or sorting.
