### ISSUE TITLE
Config on Ubuntu 18.04

### ISSUE THREAD

**Issue by IoanTuns** [mirumee/saleor#3890]
Hello guys,

I have install Saleor and is running fine with python manage.py.
I have few deployments of Django with wgsi, Gunicorn and Nginx.
I doesn't figured out how to make Saleor running. I have seen that by default deployment use uwgsi, or I am wrong? How to integrate with Nginx, or are there other recommended options witch I haven't found?
Can you help me to go live?
Thanks.

**Comment by artursmet** [comment]
Hi @IoanTuns ,

That's correct, we ship uWSGI config as a default with saleor. But there is no problem with running Saleor using gunicorn. In general any tutorial that describes gunicorn  with Django can be used to deploy Saleor.

Take a look on https://docs.gunicorn.org/en/latest/run.html#django just pass `saleor.wsgi: application` as the application path and that's should be enough. Also be aware of some extra environment variables that are required to run Saleor like the DATABASE_URL etc. 
Full list of env variables is available in the docs - https://docs.getsaleor.com/en/latest/gettingstarted/configuration.html
