### ISSUE TITLE
Private Store - Populated from Foreign Key

### ISSUE THREAD

**Issue by ehutzle** [mirumee/saleor#3892]
Good Afternoon,

Is it possible to create a "private store" that populates items by referencing them through a foreign key? 

We have individual items for customers with special pricing, and referenced by SKU in a different database. 

What Id like them to do is sign in, a menu option "Private Store" shows up, and by clicking it runs a query searching the contract table, references the items by FK, and populates them dynamically on the page. 

Is this something Saleor would be suited to do?

**Comment by maarcingebala** [comment]
Hey @ehutzle, I'd say it's a rather specific feature and I'm not convinced that it should be part of Saleor. It seems also fairly easy to implement and shouldn't be a difficult task for a Python dev customizing the project.

If I understand the problem correctly, this is how I'd implement it in Saleor. The simplest way would be to add a boolean flag to the `Product` model. Then you'd have to modify the querysets that are used by product listings views to exclude those private products. Lastly, you'd need to add a new view, accessible only by your chosen customers that would render only private products. Each "private product" details page would need some to require some permissions as well.
