### ISSUE TITLE
Is it possible to set currency dynamically for MoneyField?

### ISSUE THREAD

**Issue by littlehome-eugene** [mirumee/saleor#3895]
### What I'm trying to achieve
…
I'm trying to support multi currency. 
Order can be placed in USD or YEN. 

currently order has money related field in the form of 

     `total_net = MoneyField(
         currency=settings.DEFAULT_CURRENCY,
         max_digits=settings.DEFAULT_MAX_DIGITS,
         decimal_places=settings.DEFAULT_DECIMAL_PLACES,
         default=zero_money)`

### Describe a proposed solution
...
The currency seems static, so I can't change the currency dynamically, one option I can think of having a separate MoneyField for each currency I want to support..  

But I wonder if there's better way?

### Other solutions I've tried and won't work
…

**Comment by Pacu2** [comment]
This code example shows another problem, if one changes his shop's currency, then the Order's total will be changed. I think those should be static

**Comment by littlehome-eugene** [comment]
Oh I haven't thought about that one, indeed..

**Comment by Kwaidan00** [comment]
I think it was fixed with adding support for newest `django-prices`: https://github.com/mirumee/saleor/pull/4639

**Comment by maarcingebala** [comment]
Yes, currency is now stored for each money field.
