### ISSUE TITLE
High number of duplicated queries on home page

### ISSUE THREAD

**Issue by edevil** [mirumee/saleor#3896]
### What I'm trying to achieve
Trying out Saleor

### Steps to reproduce the problem
1. Install Saleor
2. Use the populatedb management command
3. Access homepage `http://localhost:8000/en/`

### What I expected to happen
No duplicated queries, or at least less of them.

### Screenshots

<img width="706" alt="Screen Shot 2019-04-02 at 15 01 46" src="https://user-images.githubusercontent.com/12426/55408618-4aaf5b80-5558-11e9-857f-c752af99340b.png">

**System information**
Operating system: MacOS
Browser: Chrome

**Comment by maarcingebala** [comment]
Thanks for reporting. We'll investigate the issue.

**Comment by NyanKiyoshi** [comment]
That wasn't cute. Good catch!
<img width="185" alt="Screenshot 2019-04-11 at 16 11 03" src="https://user-images.githubusercontent.com/6186720/55964118-6ca19000-5c74-11e9-862a-6624240b4d24.png">
<img width="185" alt="Screenshot 2019-04-11 at 16 10 53" src="https://user-images.githubusercontent.com/6186720/55964117-6ca19000-5c74-11e9-88aa-69544608bd84.png">

**Comment by auvipy** [comment]
I was hit by this as well
