### ISSUE TITLE
Add reporting to the dashboard

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#3901]
As a store admin, I'd like to have the ability to generate reports about my store's performance, to pass it to other departments for the analysis.

Each report should have 4 statuses: started, finished, error, queued
Reports should be generated asynchronously to not affect the site's performance
There should be no ability to generate another report while the report of the same type is being created

Proposition:
- Sales, basically a drop of Order table
- Item performance, basically a drop of OrderedItem table
- GiftCard usage (once we add them)
- Notify Me Items (once we add it)
- Wishlist items (once we add it)

**Comment by krzysztofwolski** [comment]
Some reporting requests:
- reporting should allow for selecting all or only few lines 
- export as xls would be much welcomed. It could be even possible to do it from frontend 
- areas where it would be used: orders, customers, products and stocks

**Comment by maarcingebala** [comment]
@krzysztofwolski Please talk to @dzkb about that, his team is working on reports.

**Comment by maarcingebala** [comment]
Reports will be built as an external service that will communicate with Saleor through webhooks / API.

**Comment by simon-online** [comment]
> Reports will be built as an external service that will communicate with Saleor through webhooks / API.

Any idea when a reports service will be available to use with a Saleor store?
Is there currently any easy to set up reports solution that you would recommend for a Saleor store?
Or a guide on the best way to develop custom reports for a Saleor store?
