### ISSUE TITLE
sitemap not linking domain 

### ISSUE THREAD

**Issue by afhaider** [mirumee/saleor#3907]
This url is not allowed for a Sitemap at this location.
Examples
URL:
http://ikcollection/en/products/category/female-dress-1/
Line 3
URL:
http://ikcollection/en/products/category/men-2/
Line 3
URL:
http://ikcollection/en/products/category/bridal-3/
Line 3

problem=http://ikcollection.store/sitemap.xml

solution need this 
how can i update sitemap with my buyed domain
http://ikcollection.store/en/products/category/bridal-3/

**Comment by Pacu2** [comment]
I think it's taken from the settings, where you can set your domain's url

**Comment by afhaider** [comment]
bro their no heroku config set ? for it

def get_host():
    from django.contrib.sites.models import Site
    return Site.objects.get_current().domain

**Comment by afhaider** [comment]
yah i notice in dashboard setting domain name i not put full name
