### ISSUE TITLE
Cleanup and maintenance in GraphQL API code

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3909]
There are a few problems with the code style that we should fix in order to make the codebase cleaner and stop repeating problematic patterns in the future. `pylint` and codeclimate might be helpful to detect most of the problems. Few that I found so far are:

- `Unused argument 'info'` - get rid of unused arguments and use `*args` or `**kwargs` instead (or no arguments at all, if that's possible). E.g. we have a lot of resolvers that look like this:
```
def resolve_payments(self, info):
        return self.payments.all()
```
`info` argument is not used which raises `pylint` warning. Here we could use `*args` so that this functions is able to take `info` but not use it.

- `graphql/order/types.py` - get rid of `staticmethod` decorators - they're not required in field resolvers 

- `Redefining built-in 'input'` / `Redefining built-in 'id'` - we should rename those variables, maybe better names would be `data` / `node_id`. I think we should keep those names in the public schema untouched so that we don't have to update our client apps now; just do the change in Python functions that consume those arguments.

**Comment by patrys** [comment]
I think it's cleaner to use `def resolve_payments(self, _info):` as using `*args` makes it possible to pass any number of arguments. The leading underscore is enough to make linters happy.

**Comment by patrys** [comment]
I'm against removing `@staticmethod` decorators as they are all used as static methods and their first argument is `parent`, not `self`.

**Comment by NyanKiyoshi** [comment]
> I think it's cleaner to use `def resolve_payments(self, _info):` as using `*args` makes it possible to pass any number of arguments. The leading underscore is enough to make linters happy.

The only issue with that, is that we lose the ability for dependencies to be able to call our methods through keyword. Is it fine? e.g., `func(info) => func(_info) -> func(info='blah') => not ok`

**Comment by NyanKiyoshi** [comment]
After discussing with @maarcingebala, we come up with the fact that resolvers should be static methods as graphene always pass the object and not the instance as first parameter.

I would be suggesting that we do that in another pull request (thus issue as well) as it would mean changing all the resolvers (except one).

In that PR, we could probably use the generic name `parent` or even `object`? As suggested by @patrys.
