### ISSUE TITLE
API for navigation management in Dashboard 2.0

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3912]
Shortly we'll be implementing a new Dashboard 2.0 section for managing storefront navigation menus. We need to make sure that the API that we have currently allow implementing this UI:

![image](https://user-images.githubusercontent.com/5421321/55486115-0ab9a880-562c-11e9-98aa-4a40d352ef7e.png)

We already have some mutations to add menus and menu items, but I'm not sure if they allow convenient support for all the reordering and drag-drop features that this UI assumes (shape of the API should be discussed with @dominik-zeglen). 

@patrys once suggested if we shouldn't keep the entire menu structure as JSON in the database, instead of MPTT models. In the old storefront, we serialize menus to JSON anyway and cache it in a request to save some database queries. We should do some research whether it is more convenient for us to fully migrate to JSON for menus or keep the current model. We have to remember that menus and menu items are translatable and we should support that.

**Comment by NyanKiyoshi** [comment]
The issue with menus in JSON is that the links doesn't take into account the language #3154. So we need to drop the language code from the URL before saving it to the db.

**Comment by NyanKiyoshi** [comment]
For reordering the menu items, we could pass the menu item IDs and their `sort_order` number. When the user saves, we send the new sorting orders and commit them.
```gql
mutation reorderMenu($menuID: ID!, $items: [ID]!, $order: [Int]!) {
  ...
}
```

Would this solution be responding to this issue?

**Comment by NyanKiyoshi** [comment]
After discussion we decided to do like this:

```gql
input MenuItemPosition {
  menuItemID: ID
  position: Int
}

mutation reorderMenu($menuID: ID!, $positions: [MenuItemPosition]!) {
  ...
}
```

And the below statement:
> @patrys once suggested if we shouldn't keep the entire menu structure as JSON in the database, instead of MPTT models. In the old storefront, we serialize menus to JSON anyway and cache it in a request to save some database queries. We should do some research whether it is more convenient for us to fully migrate to JSON for menus or keep the current model. We have to remember that menus and menu items are translatable and we should support that.

Will be moved to another issue for further look and discussion.

**Comment by NyanKiyoshi** [comment]
During the implementation, we should also keep in my mind that we may implement the same feature to the categories' MPTT tree.

We should also approach the menu reorder in another way as we didn't take into account the fact that the menu is actually a nested list.

A solution would be to mutate one item at once, with its parent (optional) and it order:
```gql
input MenuItemPosition {
  parent: ID
  sortOrder: Int!
}

mutation reorderMenuItem(id: ID!, input: MenuItemPosition) {
  ...
}
```
