### ISSUE TITLE
Show more meaningful traceback for Graphene errors

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3913]
When an error occurs during query/mutation execution, we have no access to any meaningful traceback. As far as I know, errors are caught at the `graphql-core` level and only the last line of the traceback is returned, which makes debugging really annoying. We should do some research if it is possible to catch those errors and throw the entire traceback. This might be enabled by default if `DEBUG=True`.

I think @rafalp has implemented similiar mechanism in [Ariadne](https://github.com/mirumee/ariadne/), we could see how it's done and try to build something similar in Saleor.

**Comment by rafalp** [comment]
Our code is not merged yet in Ariadne, but here's PR for reference: https://github.com/mirumee/ariadne/pull/128

With some meddling we've got custom `format_error` that mimic's Apollo Server by setting `extensions.exception` key with traceback and context:

```json
{
  "data": {
    "people": [
      {
        "fullName": null
      }
    ]
  },
  "errors": [
    {
      "message": "'dict' object has no attribute 'trigger_attr_error'",
      "locations": [
        [
          3,
          5
        ]
      ],
      "path": [
        "people",
        0,
        "fullName"
      ],
      "extensions": {
        "exception": {
          "traceback": [
            "Traceback (most recent call last):",
            "  File \"/Users/rafalpiton/venvs/ariadne/lib/python3.6/site-packages/graphql/execution/execute.py\", line 619, in resolve_field_value_or_error",
            "    result = resolve_fn(source, info, **args)",
            "  File \"demo.py\", line 40, in resolve_person_fullname",
            "    return get_person_fullname(person)",
            "  File \"demo.py\", line 47, in get_person_fullname",
            "    return person.trigger_attr_error",
            "AttributeError: 'dict' object has no attribute 'trigger_attr_error'"
          ],
          "context": {
            "obj": "<ariadne.objects.QueryType object at 0x106a85d68>",
            "age": "234",
            "test": "'abcd'",
            "person": "{'firstName': 'John', 'lastName': 'Doe', 'age': 21}"
          }
        }
      }
    }
  ]
}
```

**Comment by maarcingebala** [comment]
PR #3918 should help. Closing this issue for now.
