### ISSUE TITLE
PopulateDB should also generate some digital products

### ISSUE THREAD

**Issue by korycins** [mirumee/saleor#3923]
### What I'm trying to achieve
It would be great to have logic in `populateDB` to generate digital product type with some test digital products.

**Comment by NileshArnaiya** [comment]
Can I take this up? How do I get started?

**Comment by korycins** [comment]
Yeah sure, you can take this!
All logic for populated DB is here `saleor/core/utils/random_data.py`
Model of DigitalContent is here: `saleor.product.models.DigitalContent`
The flow of the creation, you can find in this test - `test_fetch_single_digital_content
`, please check the logic inside the fixtures which are responsible for creation of all objects.
