### ISSUE TITLE
pdf Invoice renders without css

### ISSUE THREAD

**Issue by RedBeardCode** [mirumee/saleor#3934]
### What I'm trying to achieve
I'm trying to render a pdf invoice.

### Steps to reproduce the problem
1.  Open invoice in demo system https://demo.getsaleor.com/dashboard/orders/2911/invoice/

### What I expected to happen
The invoice doesn't render correctly. On my heroku instance I get the following error `Unsupported stylesheet type text/html for xxx.herokuapp.com/static/assets/document.e601b9186975b1728133.css`. On my local machine it works fine.

**Comment by NyanKiyoshi** [comment]
Can you `ssh` to the heroku app and try to `curl` the URL to see if you get some kind of error? Also, try having a look if any error or access log is being generated from the invoice to the stylesheet.

**Comment by RedBeardCode** [comment]
I can access the stylesheet and it looks fine to me.
