### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#394]
I think we should start versioning saleor and using tags. I knew that saleor meant to be forkable but now when I want to get new feature i create patch from master and most difficult part of it is finding on witch commit I should start.

We can create new workflow for community. We will encourage to fork from tags. If new tag/version will be delivered creating patch from current user tag to new one and applying it will be recommended way of upgrade. 

What do you think @patrys , @bogdal , @artursmet ?

**Comment by patrys** [comment]
Patches should always target master or am I misunderstanding?

**Comment by patrys** [comment]
That being said I am all for versioning releases as it gives us opportunity to say "this part is now 100% what we wanted".

**Comment by mociepka** [comment]
Yep, tags are form master, but ideally latest master commit should always be tagged and versioned. Then by version you always be knew from which commit you forked.

**Comment by patrys** [comment]
That would mean pretty much each commit would be tagged. I'd rather only number things that are either major bugfixes or mark a feature completion.

**Comment by artursmet** [comment]
I agree - we should tag major bugfixes and new features. This will be very helpful for debugging.

**Comment by mociepka** [comment]
Ideally all commits between tags should be on branches and always *latest* one should be tagged. I wrote ideally because of your concern. But we all agree on main point :+1:

**Comment by artursmet** [comment]
Maybe introduce 'release branches' for major releases?

**Comment by mjtamlyn** [comment]
Tagging every commit seems somewhat redundant.

Having intermediate releases would allow a changelog, so if I know I forked off at version X and it's now at version Y I can see the features which have changed and determine whether I want to look at integrating them.

Can I propose maybe having time based "releases" instead (assuming there is something to "release"?). Semver isn't going to necessarily make a huge amount of sense here, as projects using Saleor won't exactly be pip installing the next version.

**Comment by artursmet** [comment]
Idea of time based reases sounds good. For example monthly releases this could also speed up features development or bugfixes, when we exactly know that next tagged release will be at end of the month.

**Comment by mociepka** [comment]
It is still unresolved. We could go with normal releases mode with grapql API. What do you think?

**Comment by maarcingebala** [comment]
We use Semver to create tag names and we create tags for every release. I think this issue is resolved.
