### ISSUE TITLE
Saleor's landing page is not showing websites screenshots on firefox

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#3947]
### What I'm trying to achieve
See the screenshots of the saleor implementation.

### Steps to reproduce the problem
1. Go to https://getsaleor.com ;
2. Go to the `Saleor in action` section ;
3. Click on `Implementation` ;
4. No screenshot should load.

### Screenshots
![Screenshot_2019-04-09_14-55-51](https://user-images.githubusercontent.com/6186720/55802042-b30db800-5ad7-11e9-850b-31454d1418e2.png)

**System information**
Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by korycins** [comment]
It works on OSX Safari and Chrome. @NyanKiyoshi maybe you have some old caches?
![image](https://user-images.githubusercontent.com/23282005/55803702-22d17200-5adb-11e9-9244-773a0e43efac.png)

**Comment by maarcingebala** [comment]
@benekex2 Please take a look at this one.

**Comment by benekex2** [comment]
Fixed.
