### ISSUE TITLE
Define mutation permissions in Meta class

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3949]
Now that PR #3891 is merged we can think of further improvements to our mutations code. One thing that I noticed while doing the refactoring is that almost every mutation defines `user_is_allowed` method and in most cases, they perform the same logic of checking if a user has a particular permission. What do you think about refactoring it so that we could define permissions at the Meta class level, e.g.:

```
class CollectionRemoveProducts(BaseMutation):
    class Meta:
        description = 'Remove products from a collection.'
        permissions = ['product.manage_products', ]
```

At the same time, we could keep the `user_is_allowed` as an internal method used in `BaseMutations`. It could be overridden if you needed to perform some additional checks e.g.:

```
@classmethod
def user_is_allowed(cls, user, input):
    return user.is_authenticated
```
(example taken from `LoggedUserUpdate` mutation).

The default behavior of `user_is_allowed` would simply do `user.has_perms([permissions])` where `permissions` would come from the Meta class.

Such changes would allow us to reduce the number of lines of code per mutation even more.

What do you think @akjanik  @korycins @NyanKiyoshi?

**Comment by NyanKiyoshi** [comment]
I like this suggestion. We could have a meta field `login_is_required = False (default)` for the cases where `permissions = []` (any) and the user is required to be authenticated (or not).

**Comment by maarcingebala** [comment]
At the meta class level, I would only add the `permissions` field as this is the most common case. `login_is_required` as a meta class field limited to a single case; if we needed to also check `is_staff`, we would have to add additional meta class field `staff_is_required`. All of that could be achieved by overriding `user_is_allowed` and doing both checks manually.

**Comment by NyanKiyoshi** [comment]
Alright, sounds good to me :+1:

**Comment by korycins** [comment]
Good to me.
What do you think about changing the name `user_is_allowed` to something like `user_has_perm` or `check_permissions`?
I think that this will be more meaningful and more explicitly pointing to `permissions` object.

**Comment by maarcingebala** [comment]
`check_permissions` sounds good 👍

**Comment by NyanKiyoshi** [comment]
We will need to have #3942 merged first so we don't end up in a big mess!
