### ISSUE TITLE
No matching distribution found for cairocffi==1.0.2

### ISSUE THREAD

**Issue by bergstar** [mirumee/saleor#3951]
### What I'm trying to achieve
…

### Steps to reproduce the problem
1. Blank Ubuntu 18.10 installation
2. `sudo apt-get install build-essential python3-dev python3-pip python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info postgresql-10 python-pip`
3. Git clone and `pip install -r requirements.txt`

### Error I get
`Collecting cairocffi==1.0.2 (from -r requirements.txt (line 11))
  Could not find a version that satisfies the requirement cairocffi==1.0.2 (from -r requirements.txt (line 11)) (from versions: 0.1, 0.2, 0.3, 0.3.1, 0.3.2, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6, 0.7, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0)
No matching distribution found for cairocffi==1.0.2 (from -r requirements.txt (line 11))`

**Comment by NyanKiyoshi** [comment]
Hi,

You can send us the output of `pip install -h | grep index-url`? Thanks!

**Comment by bergstar** [comment]
@NyanKiyoshi 

Hi, sure:

`root@localhost:~/saleor# pip install -h | grep index-url -A 5
  -i, --index-url <url>       Base URL of Python Package Index (default https://pypi.python.org/simple). This should point to a repository compliant with PEP 503 (the simple
                              repository API) or a local directory laid out in the same format.
  --extra-index-url <url>     Extra URLs of package indexes to use in addition to --index-url. Should follow the same rules as --index-url.
  --no-index                  Ignore package index (only looking at --find-links URLs instead).
  -f, --find-links <url>      If a url or path to an html file, then parse for links to archives. If a local path or file:// url that's a directory, then look for archives in
                              the directory listing.
  --process-dependency-links  Enable the processing of dependency links.
`

**Comment by akjanik** [comment]
My guess is that you are using `pip` bound to a python 2.x version, while `cairocffi==1.0.2` is for 3.5+ only (so is Saleor). Can you check it with
`which pip`
and then if `which pip3` points to pip for Python 3.x, I would use this one. Or even better, use virtual environment, as mentioned in docs
https://docs.getsaleor.com/en/latest/gettingstarted/installation-linux.html#installation

**Comment by bergstar** [comment]
@akjanik Thank you, yes it worked perfectly with pip3
