### ISSUE TITLE
Npm build issue

### ISSUE THREAD

**Issue by auvipy** [mirumee/saleor#3957]
### What I'm trying to achieve
trying to build assets using npm install and run build-asset

### Steps to reproduce the problem
1. installed everything as mentioned in the docs and webpacks docs even the new node global webpack local webpack nothing worked!
2. 

### What I expected to happen
…
working
### Screenshots

N @endemolshinegroup/cosmiconfig-typescript-loader@1.0.0 requires a peer of cosmiconfig@>=5 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.10.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.10.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/asif/.npm/_logs/2019-04-11T07_47_08_556Z-debug.log
undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor@0.0.0 build-assets: `webpack -p`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**System information**
Operating system: Ubuntu 18.04.2, node 11.x from nodesource binary
Browser: Chrome

**Comment by auvipy** [comment]
switching to yarn run build-assets --

 + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/postcss-loader/lib/index.js??ref--5-2!node_modules/sass-loader/lib/loader.js??ref--5-3!saleor/static/scss/storefront.scss:
    Entrypoint mini-css-extract-plugin = *
     [0] ./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./saleor/static/scss/storefront.scss 509 KiB {0} [built]
     [3] ./saleor/static/images/arrow-select.svg 95 bytes {0} [built]
     [4] ./saleor/static/fonts/Lato-Light.woff2 95 bytes {0} [built]
     [5] ./saleor/static/fonts/Lato-Light.woff 94 bytes {0} [built]
     [6] ./saleor/static/fonts/Lato-Light.ttf 93 bytes {0} [built]
     [7] ./saleor/static/fonts/Lato-Regular.woff2 97 bytes {0} [built]
     [8] ./saleor/static/fonts/Lato-Regular.woff 96 bytes {0} [built]
     [9] ./saleor/static/fonts/Lato-Regular.ttf 95 bytes {0} [built]
    [10] ./saleor/static/fonts/Lato-Bold.woff2 94 bytes {0} [built]
    [11] ./saleor/static/fonts/Lato-Bold.woff 93 bytes {0} [built]
    [12] ./saleor/static/fonts/Lato-Bold.ttf 92 bytes {0} [built]
    [13] ./saleor/static/images/block1.jpg 89 bytes {0} [built]
    [14] ./saleor/static/images/block2.jpg 89 bytes {0} [built]
    [15] ./saleor/static/images/block3.jpg 89 bytes {0} [built]
        + 2 hidden modules
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by auvipy** [comment]
raise WebpackError(error)
webpack_loader.exceptions.WebpackError: 
            unknown-error in 
            ERROR in /home/asif/upwork/viets/saleor/static/dashboard-next/categories/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

**Comment by auvipy** [comment]
http://127.0.0.1:8000/en/account/login/?next=/dashboard/

WebpackError at /en/account/login/
            unknown-error in 
            ERROR in /home/asif/upwork/viets/saleor/static/dashboard-next/categories/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

**Comment by auvipy** [comment]
19 | <meta name="apple-mobile-web-app-status-bar-style" content="black">
-- | --
<meta name="apple-mobile-web-app-title" content="{{ site.name }}">
<meta name="og:type" content="website">
{% get_available_languages as LANGUAGES %}
{% for lang_code, language_name in LANGUAGES %}
<link rel="alternate" hreflang="{{ lang_code }}" href="{% translate_url url=request.path lang_code=lang_code %}" />
{% endfor %}
{% endblock meta %}
 
{% include 'favicon.html' %}
{% render_bundle 'storefront' 'css' attrs='async' %}
 
{% block stylesheet %}{% endblock stylesheet %}

**Comment by maarcingebala** [comment]
@dominik-zeglen Do you know what might be the issue here?

**Comment by auvipy** [comment]
WebpackError at /en/account/login/
unknown-error in
ERROR in /home/asif/upwork/viets/saleor/static/dashboard-next/categories/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export. just thus issue exist now


{% render_bundle 'storefront' 'css' attrs='async' %}

**Comment by auvipy** [comment]
should i try to follow the suggestions? https://stackoverflow.com/questions/38605974/having-issues-with-es6-based-multiple-react-node-js-module-imports

**Comment by ilya-lysko** [comment]
I have this problem too :(

**Comment by auvipy** [comment]
WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/categories/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/categories/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/categories/views/CategoryDetails/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/categories/views/CategoryDetails/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/collections/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/collections/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/components/AppLayout/MenuList.tsx
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/components/AppLayout/MenuList.tsx(11,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/customers/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/customers/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/discounts/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/discounts/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/discounts/views/SaleDetails/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/discounts/views/SaleDetails/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/discounts/views/VoucherDetails/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/discounts/views/VoucherDetails/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/mutations.tsx
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/mutations.tsx(33,7):
TS2339: Property 'children' does not exist on type 'Pick<TypedMutationInnerProps<TData, TVariables>, Exclude<"children", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"onError", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/mutations.tsx
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/mutations.tsx(34,7):
TS2339: Property 'onCompleted' does not exist on type 'Pick<TypedMutationInnerProps<TData, TVariables>, Exclude<"children", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"onError", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/mutations.tsx
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/mutations.tsx(35,7):
TS2339: Property 'onError' does not exist on type 'Pick<TypedMutationInnerProps<TData, TVariables>, Exclude<"children", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"onError", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/mutations.tsx
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/mutations.tsx(36,7):
TS2339: Property 'variables' does not exist on type 'Pick<TypedMutationInnerProps<TData, TVariables>, Exclude<"children", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"onError", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/mutations.tsx
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/mutations.tsx(44,12):
TS2322: Type '{ children: any; mutation: any; onCompleted: any; onError: (err: any) => void; variables: any; update: MutationUpdaterFn<TData>; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<StrictTypedMutation> & Pick<Readonly<MutationProps<TData, TVariables>> & Readonly<{ children?: ReactNode; }>, Exclude<...> | ... 10 more ... | Exclude<...>> & Pick<...> & Pick<...>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<StrictTypedMutation> & Pick<Readonly<MutationProps<TData, TVariables>> & Readonly<{ children?: ReactNode; }>, Exclude<...> | ... 10 more ... | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/orders/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/orders/urls.ts(2,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/orders/views/OrderDetails/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/orders/views/OrderDetails/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/pages/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/pages/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/products/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/products/urls.ts(2,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/products/views/ProductImage/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/products/views/ProductImage/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/products/views/ProductUpdate/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/products/views/ProductUpdate/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/products/views/ProductVariant/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/products/views/ProductVariant/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/productTypes/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/productTypes/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/productTypes/views/ProductTypeUpdate/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/productTypes/views/ProductTypeUpdate/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/queries.tsx
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/queries.tsx(73,19):
TS2339: Property 'children' does not exist on type 'Pick<TypedQueryInnerProps<TData, TVariables>, Exclude<"require", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"children", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<...> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/queries.tsx
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/queries.tsx(76,19):
TS2339: Property 'variables' does not exist on type 'Pick<TypedQueryInnerProps<TData, TVariables>, Exclude<"require", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"children", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<...> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/queries.tsx
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/queries.tsx(83,20):
TS2322: Type '{ children: (queryData: any) => any; fetchPolicy: string; query: any; variables: any; skip: boolean; context: { useBatching: boolean; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<StrictTypedQuery> & Pick<Readonly<QueryProps<TData, TVariables>> & Readonly<{ children?: ReactNode; }>, Exclude<"client", "query" | (IsExactlyAny<...> extends true ? "variables" : never)> | ... 12 more ... | Exclude<...>> & Pick<...> & Pick<...>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<StrictTypedQuery> & Pick<Readonly<QueryProps<TData, TVariables>> & Readonly<{ children?: ReactNode; }>, Exclude<"client", "query" | (IsExactlyAny<...> extends true ? "variables" : never)> | ... 12 more ... | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/shipping/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/shipping/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/shipping/views/ShippingZoneDetails/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/shipping/views/ShippingZoneDetails/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/siteSettings/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/siteSettings/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/staff/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/staff/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/taxes/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/taxes/urls.ts(1,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/translations/urls.ts
ERROR in /home/asif/upwork/viets/eshop/saleor/static/dashboard-next/translations/urls.ts(2,26):
TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/postcss-loader/lib/index.js??ref--5-2!node_modules/sass-loader/lib/loader.js??ref--5-3!saleor/static/dashboard/scss/dashboard.scss:
    Entrypoint mini-css-extract-plugin = *
     [0] ./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./saleor/static/dashboard/scss/dashboard.scss 646 KiB {0} [built]
    [13] ./saleor/static/dashboard/images/chevron-right.svg 96 bytes {0} [built]
        + 12 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/postcss-loader/lib/index.js??ref--5-2!node_modules/sass-loader/lib/loader.js??ref--5-3!saleor/static/dashboard/scss/document.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./saleor/static/dashboard/scss/document.scss 7.12 KiB {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/postcss-loader/lib/index.js??ref--5-2!node_modules/sass-loader/lib/loader.js??ref--5-3!saleor/static/scss/storefront.scss:
    Entrypoint mini-css-extract-plugin = *
     [0] ./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./saleor/static/scss/storefront.scss 510 KiB {0} [built]
     [3] ./saleor/static/images/arrow-select.svg 95 bytes {0} [built]
     [4] ./saleor/static/fonts/Lato-Light.woff2 95 bytes {0} [built]
     [5] ./saleor/static/fonts/Lato-Light.woff 94 bytes {0} [built]
     [6] ./saleor/static/fonts/Lato-Light.ttf 93 bytes {0} [built]
     [7] ./saleor/static/fonts/Lato-Regular.woff2 97 bytes {0} [built]
     [8] ./saleor/static/fonts/Lato-Regular.woff 96 bytes {0} [built]
     [9] ./saleor/static/fonts/Lato-Regular.ttf 95 bytes {0} [built]
    [10] ./saleor/static/fonts/Lato-Bold.woff2 94 bytes {0} [built]
    [11] ./saleor/static/fonts/Lato-Bold.woff 93 bytes {0} [built]
    [12] ./saleor/static/fonts/Lato-Bold.ttf 92 bytes {0} [built]
    [13] ./saleor/static/images/block1.jpg 89 bytes {0} [built]
    [14] ./saleor/static/images/block2.jpg 89 bytes {0} [built]
    [15] ./saleor/static/images/block3.jpg 89 bytes {0} [built]
        + 2 hidden modules
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dominik-zeglen** [comment]
Have you seen this thread?
https://github.com/mirumee/saleor/issues/3886
