### ISSUE TITLE
Django related model issue

### ISSUE THREAD

**Issue by auvipy** [mirumee/saleor#3960]
after running the project and trying to access it, got the following traceback

File "/home/asif/upwork/viets/saleor/core/views.py", line 18, in home
    request.site.settings.homepage_collection)[:8]
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/fields/related_descriptors.py", line 415, in __get__
    self.related.get_accessor_name()
django.contrib.sites.models.Site.settings.RelatedObjectDoesNotExist: Site has no settings.

**Comment by NyanKiyoshi** [comment]
Hi,

Did you apply the migrations or edit in any way the migration files?

**Comment by auvipy** [comment]
yes, I removed all the migrations and regenerated them in a fresh local project. is my migration mission initial default data?

**Comment by NyanKiyoshi** [comment]
Yes, this one https://github.com/mirumee/saleor/blob/master/saleor/site/migrations/0002_add_default_data.py

**Comment by auvipy** [comment]
ohh!! great thanks, man :D

**Comment by auvipy** [comment]
btw this is the current migration finle in inittial site migration # Generated by Django 2.2 on 2019-04-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20190411_0851'),
        ('sites', '0002_alter_domain_unique'),
        ('menu', '0002_auto_20190411_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('include_taxes_in_prices', models.BooleanField(default=True)),
                ('display_gross_prices', models.BooleanField(default=True)),
                ('charge_taxes_on_shipping', models.BooleanField(default=True)),
                ('track_inventory_by_default', models.BooleanField(default=True)),
                ('default_weight_unit', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb'), ('oz', 'oz'), ('g', 'g')], default='kg', max_length=10)),
                ('automatic_fulfillment_digital_products', models.BooleanField(default=False)),
                ('default_digital_max_downloads', models.IntegerField(blank=True, null=True)),
                ('default_digital_url_valid_days', models.IntegerField(blank=True, null=True)),
                ('bottom_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.Menu')),
                ('homepage_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.Collection')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.Site')),
                ('top_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.Menu')),
            ],
            options={
                'permissions': (('manage_settings', 'Manage settings.'), ('manage_translations', 'Manage translations.')),
            },
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('header_text', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='site.SiteSettings')),
            ],
            options={
                'unique_together': {('language_code', 'site_settings')},
            },
        ),
        migrations.CreateModel(
            name='AuthorizationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook-Oauth2'), ('google-oauth2', 'Google-Oauth2')], max_length=20)),
                ('key', models.TextField()),
                ('password', models.TextField()),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.SiteSettings')),
            ],
            options={
                'unique_together': {('site_settings', 'name')},
            },
        ),
    ]

**Comment by auvipy** [comment]
in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/asif/upwork/viets/saleor/site/migrations/0002_add_default_data.py", line 11, in create_default_site
    'domain': 'localhost:8000'})
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 540, in get_or_create
    params = self._extract_model_params(defaults, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 606, in _extract_model_params
    "', '".join(sorted(invalid_params)),
django.core.exceptions.FieldError: Invalid field name(s) for model SiteSettings: 'domain', 'name'.

**Comment by NyanKiyoshi** [comment]
You are missing the `domain` and `name` fields in your `SiteSettings` model.

```
('domain', models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain')),
('name', models.CharField(max_length=50, verbose_name='name')),
```

**Comment by NyanKiyoshi** [comment]
You are missing the `domain` and `name` fields in your `SiteSettings` model.

```
('domain', models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain')),
('name', models.CharField(max_length=50, verbose_name='name')),
```

**Comment by NyanKiyoshi** [comment]
You are missing the `domain` and `name` fields in your `SiteSettings` model.

```
('domain', models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain')),
('name', models.CharField(max_length=50, verbose_name='name')),
```

**Comment by NyanKiyoshi** [comment]
You are missing the `domain` and `name` fields in your `SiteSettings` model.

```
('domain', models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain')),
('name', models.CharField(max_length=50, verbose_name='name')),
```

**Comment by NyanKiyoshi** [comment]
You are missing the `domain` and `name` fields in your `SiteSettings` model.

```
('domain', models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain')),
('name', models.CharField(max_length=50, verbose_name='name')),
```

**Comment by NyanKiyoshi** [comment]
You are missing the `domain` and `name` fields in your `SiteSettings` model.

```
('domain', models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain')),
('name', models.CharField(max_length=50, verbose_name='name')),
```

**Comment by NyanKiyoshi** [comment]
You are missing the `domain` and `name` fields in your `SiteSettings` model.

```
('domain', models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain')),
('name', models.CharField(max_length=50, verbose_name='name')),
```

**Comment by NyanKiyoshi** [comment]
You are missing the `domain` and `name` fields in your `SiteSettings` model.

```
('domain', models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain')),
('name', models.CharField(max_length=50, verbose_name='name')),
```

**Comment by NyanKiyoshi** [comment]
You are missing the `domain` and `name` fields in your `SiteSettings` model.

```
('domain', models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain')),
('name', models.CharField(max_length=50, verbose_name='name')),
```

**Comment by auvipy** [comment]
just wondering if there any better/alternative solution for this? the whole approach seems to be very faulty in my humble opiniton

**Comment by NyanKiyoshi** [comment]
I don't know. You are not supposed to delete the migrations of Saleor. A solution would be to squash the migrations. Refer to: https://docs.djangoproject.com/en/2.1/topics/migrations/#migration-squashing.

**Comment by auvipy** [comment]
that's not the solution btw,

https://github.com/mirumee/saleor/blob/master/saleor/site/models.py my model was exactly like this and didn't produce domain and name field in initial migration.

**Comment by auvipy** [comment]
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "site_id" violates not-null constraint
DETAIL:  Failing row contains (1, Saleor e-commerce, localhost:8000, Test Saleor - a sample shop!, , t, t, t, t, kg, f, null, null, null, null, null, null).

this is the latest issue I ma facing, should I replace the model method get_or_create with create only for now?

**Comment by NyanKiyoshi** [comment]
Make sure you created a `Site` entry and you pass it to the site settings.

**Comment by auvipy** [comment]
it would be nice to improve docs and if possible make the process less tricky

**Comment by Pacu2** [comment]
@auvipy We do not recommend removing all migrations from the project, as there are some data migrations included.

**Comment by auvipy** [comment]
I would try to come with a pr which mention this. btw even after pulling from master, my devserver is terribly slow and don't load homepage or dashboard anything :( plain ubuntu, any suggestion about that?

**Comment by Pacu2** [comment]
Have you generated static files? `npm start`

**Comment by auvipy** [comment]
thanks for the hint!! totally forgot!!

**Comment by aquaerius** [comment]
I believe the issue here was that you deleted the django.contrib.sites package migrations. This package has a model named "site".
