### ISSUE TITLE
[Refactor] Add function for creating orders

### ISSUE THREAD

**Issue by akjanik** [mirumee/saleor#3966]
In many places we use
```
order.events.create(
                parameters=<optional_dict>,
                type=<OrderEvents.some_type.value>,
                user=info.context.user)
```
I think we could get rid off a lot of boilerplate code if we add an util function that does that.

**Comment by maarcingebala** [comment]
We have an issue for reworking events - #2443. I suggest that we do the refactoring as a part of it.
