### ISSUE TITLE
Where can i change the variables?

### ISSUE THREAD

**Issue by texpress30** [mirumee/saleor#3977]
Hi,

I am trying to change the ```{{site.name}}``` variable, but i don't know where exactly to go in order to change it. I tried to go to the site folder, but there is no ```views.py``` file. From where exactly does Saleor takes that variable? Where is the context for it?

Also, how can i change the text on the header? For example, i want to change this: TEST SALEOR - A SAMPLE SHOP!, with something else. When i look into the base.html i see this for that specific paragraph ...

```
<p class="text-left">{{ site.settings.translated.header_text }}</p>
```

Where should i go to change that?

All the best.

**Comment by NyanKiyoshi** [comment]
Hi,

Just go in the site settings in your dashboard and change the display name!

**Comment by texpress30** [comment]
That is good answer, but still i wonder how to change {{site,name}}

**Comment by korycins** [comment]
@texpress30 The `site.name` can be changed in the same dashboard section as header text - you just need to modify `Display name`

**Comment by texpress30** [comment]
Thanks, i solved it.
