### ISSUE TITLE
Do not enable Debug Toolbar by default with DEBUG mode

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#3978]
### What I'm trying to achieve
Django Debug Toolbar combined with debugger causes on my env timeouts and unfortunately, it's turned on by default with DEBUG mode:
https://github.com/mirumee/saleor/blob/master/saleor/settings.py#L254

This tool should be enabled on demand, like Silk:
https://github.com/mirumee/saleor/blob/master/saleor/settings.py#L278

### Describe a proposed solution
- add separate setting for enabling DDT (new environment variable)
- the default setting should be discussed

**Comment by jxltom** [comment]
Is that a bug with debugtoolbar? It works fine for me locally.

**Comment by koradon** [comment]
@jxltom for me loading products list in dashboard take a lot of time.

**Comment by dushr** [comment]
@koradon are you sure its the debug toolbar? Have you tried loading the product list by explicitly removing debug toolbar from the installed apps?

If you're using dev server, the images are also served from the dev server - for me that was the problem - as it is one worker serving images (and if the size is not available, it is also resizing them)

**Comment by koradon** [comment]
@dushr yes I tried and without debug toolbar, it is very fast.

**Comment by krzysztofwolski** [comment]
As I wrote on @koradon s PR - DDT does not help at all when front uses GQL API. Which is our recommended way of doing new projects. Silk does not have this limitation.

@dushr How do you handle images on dev srv?
