### ISSUE TITLE
RazorPay enabled but unable to work

### ISSUE THREAD

**Issue by yourtechcare** [mirumee/saleor#3985]
![Saleor_Razorpay_Not_Working](https://user-images.githubusercontent.com/16338809/56343767-441c1780-61d9-11e9-858f-e55c0d323b35.JPG)
RazorPay enabled but unable to work,

Did input RazorPay config details correctly but while click on "Proceed To Payment" It doesn't redirect or show any form to pay.

**Comment by NyanKiyoshi** [comment]
Hi, does the browser console show any error? I will try to reproduce that later today.

**Comment by yourtechcare** [comment]
No Error. 
![Razorpay_Next_Stage](https://user-images.githubusercontent.com/16338809/56344635-8181a480-61db-11e9-9a53-eabe1db63249.JPG)

**Comment by yourtechcare** [comment]
What next to fix this issue ?

**Comment by NyanKiyoshi** [comment]
@yourtechcare I have to try to reproduce your issue to take a closer look at it, but I'm busy right now. I will be able to take a look later today.

**Comment by yourtechcare** [comment]
Any further tips so that i can investigate till you are busy.

**Comment by yourtechcare** [comment]
Also how can we configure TAX as per INDIAN GST System ?

**Comment by NyanKiyoshi** [comment]
It works for me. Can you take a look at the logs? You probably did not configure correctly your store, e.g. the currency currently in use may not be valid.

**Comment by yourtechcare** [comment]
CURRENCY : INR
Where i can find the logs ?

**Comment by NyanKiyoshi** [comment]
The currency should be fine then.
Depends how you are running saleor. If you are using `python manage.py runserver`, then it's on your terminal.

**Comment by yourtechcare** [comment]
I am using uwsgi command to run server & Apache configured with ProxyPass
![Payment_Stage_Razorpay](https://user-images.githubusercontent.com/16338809/56353220-8a2fa600-61ee-11e9-8abd-3b9da02000c5.JPG)

**Comment by NyanKiyoshi** [comment]
Alright, then try to take a look at the error logs of apache.

**Comment by yourtechcare** [comment]
No Error related to saleor in logs of apache.

**Comment by NyanKiyoshi** [comment]
In your screenshot, it looks like it's a client issue. Can you check the console of your browser and the network tab for any error?

**Comment by yourtechcare** [comment]
No Error in Console or Network - what next ?

![Saleor_Console](https://user-images.githubusercontent.com/16338809/56384365-d3591780-6239-11e9-9275-1d6605d2c900.JPG)
![Saleor_Network](https://user-images.githubusercontent.com/16338809/56384366-d3f1ae00-6239-11e9-9507-6c131fef3bf5.JPG)

**Comment by yourtechcare** [comment]
-------------------------------------------------------------------------------
INFO celery.app.trace Task saleor.order.emails.send_order_confirmation[fc7f2bcd-f9d9-4071-81a3-221eacf77f2d] succeeded in 0.06244322899999588s: None [PID:5044:Thread-4]
INFO django.server "POST /en/checkout/summary/ HTTP/1.1" 302 0 [PID:5044:Thread-4]
INFO django.server "POST /en/checkout/summary/ HTTP/1.1" 302 0 [PID:5044:Thread-4]
INFO django.server "POST /en/checkout/summary/ HTTP/1.1" 302 0 [PID:5044:Thread-4]
INFO django.server "GET /en/order/74c6b5c8-809b-4625-a369-7499ba640713/payment/ HTTP/1.1" 200 34368 [PID:5044:Thread-4]
INFO django.server "GET /en/order/74c6b5c8-809b-4625-a369-7499ba640713/payment/ HTTP/1.1" 200 34368 [PID:5044:Thread-4]
INFO django.server "GET /en/order/74c6b5c8-809b-4625-a369-7499ba640713/payment/ HTTP/1.1" 200 34368 [PID:5044:Thread-4]
INFO django.server "GET /static/images/placeholder60x60.png HTTP/1.1" 200 2284 [PID:5044:Thread-7]
INFO django.server "GET /static/images/placeholder60x60.png HTTP/1.1" 200 2284 [PID:5044:Thread-7]
INFO django.server "GET /static/images/placeholder60x60.png HTTP/1.1" 200 2284 [PID:5044:Thread-7]
INFO django.server "GET /en/jsi18n/ HTTP/1.1" 200 3223 [PID:5044:Thread-4]
INFO django.server "GET /en/jsi18n/ HTTP/1.1" 200 3223 [PID:5044:Thread-4]
INFO django.server "GET /en/jsi18n/ HTTP/1.1" 200 3223 [PID:5044:Thread-4]
INFO django.server "GET /en/checkout/dropdown/ HTTP/1.1" 200 488 [PID:5044:Thread-4]
INFO django.server "GET /en/checkout/dropdown/ HTTP/1.1" 200 488 [PID:5044:Thread-4]
INFO django.server "GET /en/checkout/dropdown/ HTTP/1.1" 200 488 [PID:5044:Thread-4]
INFO django.server "POST /en/order/74c6b5c8-809b-4625-a369-7499ba640713/payment/ HTTP/1.1" 302 0 [PID:5044:Thread-4]
INFO django.server "POST /en/order/74c6b5c8-809b-4625-a369-7499ba640713/payment/ HTTP/1.1" 302 0 [PID:5044:Thread-4]
INFO django.server "POST /en/order/74c6b5c8-809b-4625-a369-7499ba640713/payment/ HTTP/1.1" 302 0 [PID:5044:Thread-4]
INFO django.server "GET /en/order/74c6b5c8-809b-4625-a369-7499ba640713/payment/razorpay/ HTTP/1.1" 200 34172 [PID:5044:Thread-4]
INFO django.server "GET /en/order/74c6b5c8-809b-4625-a369-7499ba640713/payment/razorpay/ HTTP/1.1" 200 34172 [PID:5044:Thread-4]
INFO django.server "GET /en/order/74c6b5c8-809b-4625-a369-7499ba640713/payment/razorpay/ HTTP/1.1" 200 34172 [PID:5044:Thread-4]
INFO django.server "GET /en/jsi18n/ HTTP/1.1" 200 3223 [PID:5044:Thread-7]
INFO django.server "GET /en/jsi18n/ HTTP/1.1" 200 3223 [PID:5044:Thread-7]
INFO django.server "GET /en/jsi18n/ HTTP/1.1" 200 3223 [PID:5044:Thread-7]
INFO django.server "GET /en/checkout/dropdown/ HTTP/1.1" 200 488 [PID:5044:Thread-7]
INFO django.server "GET /en/checkout/dropdown/ HTTP/1.1" 200 488 [PID:5044:Thread-7]
INFO django.server "GET /en/checkout/dropdown/ HTTP/1.1" 200 488 [PID:5044:Thread-7]
INFO django.server "GET /en/manifest.json HTTP/1.1" 200 547 [PID:5044:Thread-8]
INFO django.server "GET /en/manifest.json HTTP/1.1" 200 547 [PID:5044:Thread-8]
INFO django.server "GET /en/manifest.json HTTP/1.1" 200 547 [PID:5044:Thread-8]
INFO django.server "GET /static/favicons/android-chrome-192x192.png HTTP/1.1" 200 7086 [PID:5044:Thread-9]
INFO django.server "GET /static/favicons/android-chrome-192x192.png HTTP/1.1" 200 7086 [PID:5044:Thread-9]
INFO django.server "GET /static/favicons/android-chrome-192x192.png HTTP/1.1" 200 7086 [PID:5044:Thread-9]
INFO django.server "GET /static/favicons/android-chrome-512x512.png HTTP/1.1" 200 20181 [PID:5044:Thread-9]
INFO django.server "GET /static/favicons/android-chrome-512x512.png HTTP/1.1" 200 20181 [PID:5044:Thread-9]
INFO django.server "GET /static/favicons/android-chrome-512x512.png HTTP/1.1" 200 20181 [PID:5044:Thread-9]

**Comment by yourtechcare** [comment]
Share what settings you made in settings.py so that i can cross-check ?

**Comment by yourtechcare** [comment]
Any updates ?

**Comment by NyanKiyoshi** [comment]
@yourtechcare when in the network tab, could you reload the page? So we can see the request to checkout.razorpay.com.

**Comment by yourtechcare** [comment]
![Saleor_Razorpay_Network_Status](https://user-images.githubusercontent.com/16338809/56453365-2a0c4180-635f-11e9-8fbd-e43ecda7b796.JPG)

**Comment by NyanKiyoshi** [comment]
Look for a request to checkout.razorpay.com.

**Comment by yourtechcare** [comment]
Somehow i did submitted request to Gateway and for Error : Gateway response validation failed
