### ISSUE TITLE
Failed to add stock: AttributeError, RelatedManager object has no attribute _prefetch_related_lookups

### ISSUE THREAD

**Issue by Cephlin** [mirumee/saleor#399]
AttributeError at /dashboard/products/4/stock/add/

'RelatedManager' object has no attribute '_prefetch_related_lookups'

Request Method: 	GET
Request URL: 	http://localhost:8000/dashboard/products/4/stock/add/
Django Version: 	1.8.6
Exception Type: 	AttributeError
Exception Value: 	

'RelatedManager' object has no attribute '_prefetch_related_lookups'

Exception Location: 	/home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/forms/models.py in __iter__, line 1095
Python Executable: 	/home/cephlin/Projects/Python/shop/env/bin/python
Python Version: 	2.7.6
Python Path: 	

['/home/cephlin/Projects/Python/shop/env/bin',
 '/home/cephlin/Projects/Python/shop',
 '/home/cephlin/Projects/Python/shop/env/lib/python2.7',
 '/home/cephlin/Projects/Python/shop/env/lib/python2.7/plat-i386-linux-gnu',
 '/home/cephlin/Projects/Python/shop/env/lib/python2.7/lib-tk',
 '/home/cephlin/Projects/Python/shop/env/lib/python2.7/lib-old',
 '/home/cephlin/Projects/Python/shop/env/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-i386-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages']

Server time: 	Sun, 22 Nov 2015 10:20:40 -0600
Error during template rendering

In template /home/cephlin/Projects/Python/shop/saleor/core/templates/materializecssform/field.html, error at line 92
'RelatedManager' object has no attribute '_prefetch_related_lookups'
82 	
83 	                    {% if field.help_text %}
84 	                    <p class="help-block">
85 	                        {{ field.help_text|safe }}
86 	                    </p>
87 	                    {% endif %}
88 	                </div>
89 	
90 	            {% else %}
91 	                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
92 	
                      
      {{field}}
      

      
93 	                {% for error in field.errors %}
94 	                    <p class="help-block materialize-red-text">{{ error }}</p>
95 	                {% endfor %}
96 	
97 	                {% if field.help_text %}
98 	                <p class="help-block">
99 	                    {{ field.help_text|safe }}
100 	                </p>
101 	                {% endif %}
102 	
Traceback Switch to copy-and-paste view

    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/core/handlers/base.py in get_response

                                    response = response.render()

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/response.py in render

                                self.content = self.rendered_content

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/response.py in rendered_content

                            content = template.render(context, self._request)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/backends/django.py in render

                            return self.template.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/base.py in render

                                        return self._render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/base.py in _render

                            return self.nodelist.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/base.py in render

                                    bit = self.render_node(node, context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/debug.py in render_node

                                return node.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/loader_tags.py in render

                            return compiled_parent._render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/base.py in _render

                            return self.nodelist.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/base.py in render

                                    bit = self.render_node(node, context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/debug.py in render_node

                                return node.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/loader_tags.py in render

                                    result = block.nodelist.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/base.py in render

                                    bit = self.render_node(node, context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/debug.py in render_node

                                return node.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/debug.py in render

                                output = self.filter_expression.resolve(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/base.py in resolve

                                    new_obj = func(obj, *arg_vals)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/materializecssform/templatetags/materializecss.py in materializecss

                        return render(element, markup_classes)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/materializecssform/templatetags/materializecss.py in render

                        return template.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/backends/django.py in render

                            return self.template.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/base.py in render

                                        return self._render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/base.py in _render

                            return self.nodelist.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/base.py in render

                                    bit = self.render_node(node, context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/debug.py in render_node

                                return node.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/defaulttags.py in render

                                    return nodelist.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/base.py in render

                                    bit = self.render_node(node, context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/debug.py in render_node

                                return node.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/defaulttags.py in render

                                    return nodelist.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/base.py in render

                                    bit = self.render_node(node, context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/debug.py in render_node

                                return node.render(context)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/template/debug.py in render

                                output = force_text(output)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/utils/encoding.py in force_text

                                    s = six.text_type(s)

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/utils/html.py in <lambda>

                            klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/forms/forms.py in __str__

                            return self.as_widget()

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/forms/forms.py in as_widget

                            return force_text(widget.render(name, self.value(), attrs=attrs))

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/forms/widgets.py in render

                            options = self.render_options(choices, [value])

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/forms/widgets.py in render_options

                            for option_value, option_label in chain(self.choices, choices):

         ...
    ▶ Local vars
    /home/cephlin/Projects/Python/shop/env/local/lib/python2.7/site-packages/django/forms/models.py in __iter__

                            method = 'all' if self.queryset._prefetch_related_lookups else 'iterator'

         ...
    ▶ Local vars

Request information
GET

No GET data
POST

No POST data
FILES

No FILES data
COOKIES
Variable 	Value
csrftoken 	

'eT6xWBixiphebINVajqt5coD7NbjnB4Z'

sessionid 	

'd9i83vag5j31b2miy94hsk6db9kvqqew'

META
Variable 	Value
RUN_MAIN 	

'true'

HTTP_REFERER 	

'http://localhost:8000/dashboard/products/4/update/'

LESS 	

'-R'

QT4_IM_MODULE 	

'xim'

SERVER_SOFTWARE 	

'WSGIServer/0.1 Python/2.7.6'

LC_CTYPE 	

'en_GB.UTF-8'

SCRIPT_NAME 	

u''

REQUEST_METHOD 	

'GET'

CSRF_COOKIE 	

u'eT6xWBixiphebINVajqt5coD7NbjnB4Z'

SERVER_PROTOCOL 	

'HTTP/1.1'

HOME 	

'/home/cephlin'

XDG_GREETER_DATA_DIR 	

'/var/lib/lightdm-data/cephlin'

DISPLAY 	

':0'

LANG 	

'en_GB.UTF-8'

VIRTUAL_ENV 	

'/home/cephlin/Projects/Python/shop/env'

SHELL 	

'/usr/bin/zsh'

XDG_DATA_DIRS 	

'/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/'

MANDATORY_PATH 	

'/usr/share/gconf/ubuntu.mandatory.path'

CLUTTER_IM_MODULE 	

'xim'

UPSTART_INSTANCE 	

''

JOB 	

'gnome-session'

TEXTDOMAIN 	

'im-config'

SERVER_PORT 	

'8000'

XMODIFIERS 	

'@im=ibus'

SELINUX_INIT 	

'YES'

PATH_INFO 	

u'/dashboard/products/4/stock/add/'

XDG_RUNTIME_DIR 	

'/run/user/1000'

VTE_VERSION 	

'3409'

UPSTART_EVENTS 	

'started starting'

UPSTART_SESSION 	

'unix:abstract=/com/ubuntu/upstart-session/1000/1075'

HTTP_HOST 	

'localhost:8000'

GNOME_KEYRING_PID 	

'1163'

XDG_SESSION_ID 	

'c1'

DBUS_SESSION_BUS_ADDRESS 	

'unix:abstract=/tmp/dbus-swO1n2eKE6'

GTK_MODULES 	

'overlay-scrollbar:unity-gtk-module'

HTTP_ACCEPT 	

'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'

DESKTOP_SESSION 	

'ubuntu'

wsgi.version 	

(1, 0)

DEFAULTS_PATH 	

'/usr/share/gconf/ubuntu.default.path'

wsgi.run_once 	

False

wsgi.errors 	

<open file '<stderr>', mode 'w' at 0xb75420d0>

wsgi.multiprocess 	

False

HTTP_ACCEPT_LANGUAGE 	

'en-GB,en;q=0.5'

INSTANCE 	

'Unity'

wsgi.input 	

<socket._fileobject object at 0xb3cc426c>

TMUX_PANE 	

'%0'

XDG_SEAT 	

'seat0'

HTTP_COOKIE 	

'csrftoken=eT6xWBixiphebINVajqt5coD7NbjnB4Z; sessionid=d9i83vag5j31b2miy94hsk6db9kvqqew'

GNOME_DESKTOP_SESSION_ID 	

'this-is-deprecated'

XDG_CURRENT_DESKTOP 	

'Unity'

QUERY_STRING 	

''

QT_IM_MODULE 	

'ibus'

LOGNAME 	

'cephlin'

USER 	

'cephlin'

GNOME_KEYRING_CONTROL 	

'/run/user/1000/keyring-a0ZBC6'

XDG_VTNR 	

'7'

PATH 	

'/home/cephlin/Projects/Python/shop/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

PS1 	

'(env)${ret_status}%{$fg_bold[green]%}%p %{$fg[cyan]%}%c %{$fg_bold[blue]%}$(git_prompt_info)%{$fg_bold[blue]%} % %{$reset_color%}'

ZSH 	

'/home/cephlin/.oh-my-zsh'

TERM 	

'screen'

HTTP_USER_AGENT 	

'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:42.0) Gecko/20100101 Firefox/42.0'

XDG_SESSION_PATH 	

'/org/freedesktop/DisplayManager/Session0'

XAUTHORITY 	

'/home/cephlin/.Xauthority'

LANGUAGE 	

'en_GB:en'

REMOTE_ADDR 	

'127.0.0.1'

SHLVL 	

'2'

QT_QPA_PLATFORMTHEME 	

'appmenu-qt5'

wsgi.url_scheme 	

'http'

COMPIZ_CONFIG_PROFILE 	

'ubuntu'

WINDOWID 	

'67108876'

SESSIONTYPE 	

'gnome-session'

IM_CONFIG_PHASE 	

'1'

GPG_AGENT_INFO 	

'/run/user/1000/keyring-a0ZBC6/gpg:0:1'

CONTENT_LENGTH 	

''

CONTENT_TYPE 	

'text/plain'

SSH_AUTH_SOCK 	

'/run/user/1000/keyring-a0ZBC6/ssh'

TMUX 	

'/tmp/tmux-1000/default,2817,0'

GDMSESSION 	

'ubuntu'

UPSTART_JOB 	

'unity-settings-daemon'

TEXTDOMAINDIR 	

'/usr/share/locale/'

wsgi.multithread 	

True

XDG_SEAT_PATH 	

'/org/freedesktop/DisplayManager/Seat0'

TZ 	

'America/Chicago'

_ 	

'/home/cephlin/Projects/Python/shop/env/bin/saleor'

HTTP_CONNECTION 	

'keep-alive'

GTK_IM_MODULE 	

'ibus'

LSCOLORS 	

'Gxfxcxdxbxegedabagacad'

XDG_CONFIG_DIRS 	

'/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg'

SERVER_NAME 	

'localhost'

GATEWAY_INTERFACE 	

'CGI/1.1'

REMOTE_HOST 	

''

OLDPWD 	

'/home/cephlin/Projects/Python/shop'

GDM_LANG 	

'en_GB'

CSRF_COOKIE_USED 	

True

PWD 	

'/home/cephlin/Projects/Python/shop'

DJANGO_SETTINGS_MODULE 	

'saleor.settings'

COLORTERM 	

'gnome-terminal'

wsgi.file_wrapper 	

''

PAGER 	

'less'

HTTP_ACCEPT_ENCODING 	

'gzip, deflate'

Settings
Using settings module saleor.settings
Setting 	Value
DEFAULT_WEIGHT 	

'lb'

SELECTABLE_ESCAPED_KEYS 	

u'********************'

SECURE_BROWSER_XSS_FILTER 	

False

USE_THOUSAND_SEPARATOR 	

False

CSRF_COOKIE_SECURE 	

False

LANGUAGE_CODE 	

'en-us'

ROOT_URLCONF 	

'saleor.urls'

MANAGERS 	

()

SILENCED_SYSTEM_CHECKS 	

[]

DEFAULT_CHARSET 	

'utf-8'

SESSION_SERIALIZER 	

'django.contrib.sessions.serializers.JSONSerializer'

STATIC_ROOT 	

'/home/cephlin/Projects/Python/shop/static'

SELECTABLE_MAX_LIMIT 	

25

GOOGLE_ANALYTICS_TRACKING_ID 	

None

ALLOWED_HOSTS 	

['localhost']

EMAIL_HOST 	

None

MESSAGE_STORAGE 	

'django.contrib.messages.storage.session.SessionStorage'

DEFAULT_CURRENCY 	

'USD'

EMAIL_SUBJECT_PREFIX 	

'[Django] '

SERVER_EMAIL 	

'root@localhost'

SECURE_HSTS_SECONDS 	

0

STATICFILES_FINDERS 	

['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']

SESSION_CACHE_ALIAS 	

'default'

SESSION_COOKIE_DOMAIN 	

None

SESSION_COOKIE_NAME 	

'sessionid'

TIME_INPUT_FORMATS 	

('%H:%M:%S', '%H:%M:%S.%f', '%H:%M')

SECURE_REDIRECT_EXEMPT 	

[]

DATABASES 	

{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.sqlite3',
             'HOST': '',
             'NAME': '/home/cephlin/Projects/Python/shop/dev.sqlite',
             'OPTIONS': {},
             'PASSWORD': u'********************',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': 'UTC',
             'USER': ''}}

EMAIL_SSL_KEYFILE 	

u'********************'

FILE_UPLOAD_DIRECTORY_PERMISSIONS 	

None

FILE_UPLOAD_PERMISSIONS 	

None

FILE_UPLOAD_HANDLERS 	

('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')

DEFAULT_CONTENT_TYPE 	

'text/html'

APPEND_SLASH 	

True

FIRST_DAY_OF_WEEK 	

0

DATABASE_ROUTERS 	

[]

DEFAULT_TABLESPACE 	

''

YEAR_MONTH_FORMAT 	

'F Y'

STATICFILES_STORAGE 	

'django.contrib.staticfiles.storage.StaticFilesStorage'

CACHES 	

{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}

SQLITE_DB_URL 	

'sqlite:////home/cephlin/Projects/Python/shop/dev.sqlite'

FACEBOOK_SECRET 	

u'********************'

SESSION_COOKIE_PATH 	

'/'

CHECKOUT_PAYMENT_CHOICES 	

[('default', 'Dummy provider')]

MESSAGE_TAGS 	

{40: 'danger'}

SECURE_CONTENT_TYPE_NOSNIFF 	

False

LOW_STOCK_THRESHOLD 	

10

MIDDLEWARE_CLASSES 	

['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'babeldjango.middleware.LocaleMiddleware',
 'saleor.cart.middleware.CartMiddleware',
 'saleor.core.middleware.DiscountMiddleware',
 'saleor.core.middleware.GoogleAnalytics',
 'saleor.core.middleware.CheckHTML']

USE_I18N 	

True

THOUSAND_SEPARATOR 	

','

SECRET_KEY 	

u'********************'

CANONICAL_HOSTNAME 	

'localhost:8000'

LANGUAGE_COOKIE_NAME 	

'django_language'

DEFAULT_INDEX_TABLESPACE 	

''

LOGGING_CONFIG 	

'logging.config.dictConfig'

SIGNING_BACKEND 	

'django.core.signing.TimestampSigner'

TEMPLATE_LOADERS 	

('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader')

WSGI_APPLICATION 	

'saleor.wsgi.application'

TEMPLATE_DEBUG 	

False

X_FRAME_OPTIONS 	

'SAMEORIGIN'

CSRF_COOKIE_NAME 	

'csrftoken'

SESSION_COOKIE_SECURE 	

False

FORCE_SCRIPT_NAME 	

None

USE_X_FORWARDED_HOST 	

False

PAYMENT_HOST 	

'localhost:8000'

EMAIL_TIMEOUT 	

None

SECURE_SSL_HOST 	

None

ACCOUNT_ACTIVATION_DAYS 	

3

AWS_MEDIA_ACCESS_KEY_ID 	

u'********************'

CSRF_COOKIE_DOMAIN 	

None

FILE_CHARSET 	

'utf-8'

DEBUG 	

True

LANGUAGE_COOKIE_DOMAIN 	

None

AWS_ACCESS_KEY_ID 	

u'********************'

DEFAULT_FILE_STORAGE 	

'django.core.files.storage.FileSystemStorage'

INSTALLED_APPS 	

['offsite_storage',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sitemaps',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.webdesign',
 'saleor.userprofile',
 'saleor.product',
 'saleor.cart',
 'saleor.checkout',
 'saleor.core',
 'saleor.order',
 'saleor.registration',
 'saleor.dashboard',
 'versatileimagefield',
 'babeldjango',
 'django_prices',
 'emailit',
 'mptt',
 'payments',
 'selectable',
 'materializecssform',
 'rest_framework']

LANGUAGES 	

(('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmal'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-cn', 'Simplified Chinese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese'),
 ('zh-tw', 'Traditional Chinese'))

USE_L10N 	

True

SECURE_HSTS_INCLUDE_SUBDOMAINS 	

False

STATICFILES_DIRS 	

['/home/cephlin/Projects/Python/shop/saleor/static']

PREPEND_WWW 	

False

SECURE_PROXY_SSL_HEADER 	

('HTTP_X_FORWARDED_PROTO', 'https')

LANGUAGE_COOKIE_AGE 	

None

SESSION_COOKIE_HTTPONLY 	

True

AWS_SECRET_ACCESS_KEY 	

u'********************'

FACEBOOK_APP_ID 	

None

DEBUG_PROPAGATE_EXCEPTIONS 	

False

CSRF_COOKIE_AGE 	

31449600

AWS_MEDIA_BUCKET_NAME 	

None

MONTH_DAY_FORMAT 	

'F j'

LOGIN_URL 	

'/account/login'

SESSION_EXPIRE_AT_BROWSER_CLOSE 	

False

TIME_FORMAT 	

'P'

AUTH_USER_MODEL 	

'userprofile.User'

DATE_INPUT_FORMATS 	

('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')

AUTHENTICATION_BACKENDS 	

('saleor.registration.backends.EmailPasswordBackend',
 'saleor.registration.backends.ExternalLoginBackend',
 'saleor.registration.backends.TrivialBackend')

EMAIL_HOST_PASSWORD 	

u'********************'

WARN_ABOUT_INVALID_HTML5_OUTPUT 	

False

PASSWORD_RESET_TIMEOUT_DAYS 	

u'********************'

SESSION_FILE_PATH 	

None

CACHE_MIDDLEWARE_ALIAS 	

'default'

SESSION_SAVE_EVERY_REQUEST 	

False

NUMBER_GROUPING 	

0

SESSION_ENGINE 	

'django.contrib.sessions.backends.cached_db'

CSRF_FAILURE_VIEW 	

'django.views.csrf.csrf_failure'

CSRF_COOKIE_PATH 	

'/'

LOGIN_REDIRECT_URL 	

'home'

PROJECT_ROOT 	

'/home/cephlin/Projects/Python/shop'

DECIMAL_SEPARATOR 	

'.'

IGNORABLE_404_URLS 	

()

LOCALE_PATHS 	

()

TEMPLATE_STRING_IF_INVALID 	

''

LOGOUT_URL 	

'/accounts/logout/'

EMAIL_USE_TLS 	

False

PAYMENT_MODEL 	

'order.Payment'

FIXTURE_DIRS 	

()

GOOGLE_CLIENT_ID 	

None

DATE_FORMAT 	

'N j, Y'

MEDIA_ROOT 	

'/home/cephlin/Projects/Python/shop/media'

DEFAULT_EXCEPTION_REPORTER_FILTER 	

'django.views.debug.SafeExceptionReporterFilter'

ADMINS 	

()

FORMAT_MODULE_PATH 	

None

DEFAULT_FROM_EMAIL 	

None

MEDIA_URL 	

'/media/'

DATETIME_FORMAT 	

'N j, Y, P'

TEMPLATE_DIRS 	

()

PAYMENT_VARIANTS 	

{'default': ('payments.dummy.DummyProvider', {})}

SITE_ID 	

1

DISALLOWED_USER_AGENTS 	

()

ALLOWED_INCLUDE_ROOTS 	

()

GOOGLE_CLIENT_SECRET 	

u'********************'

LOGGING 	

{'disable_existing_loggers': False,
 'filters': {'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'},
             'require_debug_true': {'()': 'django.utils.log.RequireDebugTrue'}},
 'formatters': {'simple': {'format': '%(levelname)s %(message)s'},
                'verbose': {'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'}},
 'handlers': {'console': {'class': 'logging.StreamHandler',
                          'filters': ['require_debug_true'],
                          'formatter': 'simple',
                          'level': 'DEBUG'},
              'mail_admins': {'class': 'django.utils.log.AdminEmailHandler',
                              'filters': ['require_debug_false'],
                              'level': 'ERROR'}},
 'loggers': {'django.request': {'handlers': ['mail_admins'],
                                'level': 'ERROR',
                                'propagate': True},
             'saleor': {'handlers': ['console'],
                        'level': 'DEBUG',
                        'propagate': True}},
 'version': 1}

SHORT_DATE_FORMAT 	

'm/d/Y'

TEMPLATES 	

[{'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': ['/home/cephlin/Projects/Python/shop/templates'],
  'OPTIONS': {'context_processors': ['django.contrib.auth.context_processors.auth',
                                     'django.core.context_processors.debug',
                                     'django.core.context_processors.i18n',
                                     'django.core.context_processors.media',
                                     'django.core.context_processors.static',
                                     'django.core.context_processors.tz',
                                     'django.contrib.messages.context_processors.messages',
                                     'django.core.context_processors.request',
                                     'saleor.core.context_processors.canonical_hostname',
                                     'saleor.core.context_processors.default_currency',
                                     'saleor.core.context_processors.categories'],
              'debug': True,
              'loaders': ['django.template.loaders.filesystem.Loader',
                          'django.template.loaders.app_directories.Loader',
                          'django.template.loaders.eggs.Loader'],
              'string_if_invalid': '<< MISSING VARIABLE >>'}}]

TEST_RUNNER 	

''

CACHE_MIDDLEWARE_KEY_PREFIX 	

u'********************'

SECURE_SSL_REDIRECT 	

False

TIME_ZONE 	

'America/Chicago'

FILE_UPLOAD_MAX_MEMORY_SIZE 	

2621440

EMAIL_BACKEND 	

'django.core.mail.backends.console.EmailBackend'

AWS_MEDIA_SECRET_ACCESS_KEY 	

u'********************'

EMAIL_USE_SSL 	

False

TEMPLATE_CONTEXT_PROCESSORS 	

('django.contrib.auth.context_processors.auth',
 'django.template.context_processors.debug',
 'django.template.context_processors.i18n',
 'django.template.context_processors.media',
 'django.template.context_processors.static',
 'django.template.context_processors.tz',
 'django.contrib.messages.context_processors.messages')

MIGRATION_MODULES 	

{}

SESSION_COOKIE_AGE 	

1209600

SETTINGS_MODULE 	

'saleor.settings'

USE_ETAGS 	

False

LANGUAGES_BIDI 	

('he', 'ar', 'fa', 'ur')

FILE_UPLOAD_TEMP_DIR 	

None

INTERNAL_IPS 	

['127.0.0.1']

STATIC_URL 	

'/static/'

EMAIL_PORT 	

None

USE_TZ 	

True

SHORT_DATETIME_FORMAT 	

'm/d/Y P'

TEST_NON_SERIALIZED_APPS 	

[]

PASSWORD_HASHERS 	

u'********************'

ABSOLUTE_URL_OVERRIDES 	

{}

LANGUAGE_COOKIE_PATH 	

'/'

PAYMENT_BASE_URL 	

'http://localhost:8000/'

CACHE_MIDDLEWARE_SECONDS 	

600

EMAIL_SSL_CERTFILE 	

None

CSRF_COOKIE_HTTPONLY 	

False

DATETIME_INPUT_FORMATS 	

('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')

AWS_STATIC_BUCKET_NAME 	

None

EMAIL_HOST_USER 	

None

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

**Comment by patrys** [comment]
This is a bug in Django 1.8.6. Please revert to 1.8.5 and wait for 1.8.7.
