### ISSUE TITLE
Migrate from `deprecated` fields

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3996]
Some GraphQL fields were recently deprecated in our API:
- OrderLine.thumbnailUrl
- Page.availableOn
- Page.isVisible
- ProductVariant.availability
- Product.availability -> pricing
- Product.availableOn
- Product.price
- Product.thumbnailUrl
- Collection.publishedDate

We should migrate queries in Dashboard 2.0 to use the new fields, so that we'll be able to drop the old ones from the schema.

**Comment by benekex2** [comment]
Field `Collection.publishedDate` is not used
