### ISSUE TITLE
Dashboard Voucher End-Date issues

### ISSUE THREAD

**Issue by AnkitKundariya** [mirumee/saleor#4000]
### What I'm trying to achieve
I tried to create a new voucher from the dashboard and try to give end date on same but I'm not able to select end date as the end date picker is continuously blinking.
### Steps to reproduce the problem
follow below video to reproduce the problem
1. https://www.loom.com/share/dda63e1f9cb54b02a6cf6c443812d42c

### What I expected to happen
…

### Screenshots

**System information**
Operating system:  Ubuntu 18.04
Browser: Chrome

**Comment by NyanKiyoshi** [comment]
Hi, thanks for reporting. It's a bug from Google Chrome, see https://github.com/mirumee/saleor/issues/3865#issuecomment-482097054 for more information. We don't provide a fix yet, we will discuss about a solution during this week.
