### ISSUE TITLE
TypeError: n.cart is undefined. JS not working in cart

### ISSUE THREAD

**Issue by whoizit** [mirumee/saleor#4001]
### What I'm trying to achieve
I'm trying run from Docker development guide https://saleor.readthedocs.io/en/latest/customization/docker.html#docker-dev

### Steps to reproduce the problem
1. git clone https://github.com/mirumee/saleor.git; cd saleor/
2. 
sudo docker-compose build
sudo docker-compose run --rm web python3 manage.py migrate
sudo docker-compose run --rm web python3 manage.py collectstatic
sudo docker-compose run --rm web python3 manage.py populatedb --createsuperuser
sudo docker-compose up
open in browser http://127.0.0.1:8000

### What I expected to happen
I want to remove the item from the cart, but it is not removed. After reloading the page it is not in the cart. So JS not works. I disable ad-block on this site http://127.0.0.1:8000/en/checkout/

### Screenshots
Firefox:
![2019-04-22-093409_1918x232_scrot](https://user-images.githubusercontent.com/359276/56487196-11c52f80-64e3-11e9-82c7-6656f18bb7bb.png)
Chromium:
![2019-04-22-094009_932x257_scrot](https://user-images.githubusercontent.com/359276/56487195-11c52f80-64e3-11e9-937a-9b7423596640.png)

**System information**
Operating system: Artix Linux (archlinux-based)
Browser: firefox 66.0.3, chromium 73.0.3683.103

**Comment by NyanKiyoshi** [comment]
```
Traceback:

File "/Users/Development/saleor-venv/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/Users/Development/saleor-venv/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/Users/Development/saleor-venv/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/Development/saleor/saleor/checkout/utils.py" in func
  235.             return view(request, checkout, *args, **kwargs)

File "/Users/Development/saleor/saleor/checkout/views/__init__.py" in update_checkout_line
  190.         updated_line = checkout.get_line(form.checkout_line.variant)

Exception Type: AttributeError at /en/checkout/update/195/
Exception Value: 'NoneType' object has no attribute 'variant'
```

**Comment by NyanKiyoshi** [comment]
I will provide a fix on that tomorrow. Thanks for reporting!
