### ISSUE TITLE
Payment Gateway Integration (2Checkout)

### ISSUE THREAD

**Issue by MartinCastellon** [mirumee/saleor#4011]
### What I'm trying to achieve
Hello, 
After reading the Saleor Docs, I noticed that only 3payment gateways are supported. Does this mean that I cannot use 2checkout to process payments on the Saleor platform?

I really can´t use braintree, razorpay, and stripe since they don't offer their services in Panama and Central America. 

### Describe a proposed solution
After investigating a bit more about 2Checkout, they generate an individual link to add a checkout for each product listed in the 2checkout platform. Which will obviously have to be the exact same products listed with saleor.

### Other solutions I've tried and won't work
I haven't really tried to come up with these since I am still deciding on which technology to use. Processing payments from central America require good planning. 
…

Looking forward to the responses. I highly appreciate good feedback. Pardon me for my ignorance in the topic but I am new in the e-commerce development world. After all, we are here to learn.

**Comment by NyanKiyoshi** [comment]
Hi,

Yes, as of now we only have three payment gateways (braintree, razorpay and stripe). We may implement Paypal this year (can't promise or tell anything certain). We will also integrate google pay soon (I can tell you that as I will be working on implementing it. But I also have no dates yet, depending on my work load it won't be certain. Maybe I will work on that during my days off.)

I would appreciate it if you had suggestion of payment gateways, so we could take them into consideration! (I'm looking toward adding a few of them). But once again, nothing is sure, and no date can be given.

**Comment by licht1stein** [comment]
As far as I understood from documentation, nothing stops us from implementing other checkouts and putting them under `saleor.payment.gateways`, is that right?

**Comment by MartinCastellon** [comment]
This is great news! It would be great to integrate 2Checkout.

I would love to work on it and commit on a separate branch on Github for
others to use. But I don't have any idea where to start. My experience
integrating payment gateways in Django is null :(. Where should I start?

Thank you so much in advance. Is great to talk to you guys

**Comment by NyanKiyoshi** [comment]
@licht1stein exactly. It's planned to separate de payment module from saleor, so users can easily write and add their own gateways without having to merge into Saleor's code (or the payment's code). They would only have to make a PR updating the gateways list with a link to the gateway's implementation github link (there are some requirements to meet though, I'm unsure about them. At least having everything tested through unitests; but anyway, those are matters that get discussed on PRs).

@MartinCastellon well... There is near to no django experience required to have to implement you own payment gateway. Our documentation [has a great explanation](https://docs.getsaleor.com/en/latest/guides/payments.html) on how to proceed.

One advice that I would have, is that you don't have to implement the gateway from scratch; for example implemented every endpoints, datastructure, error handling, etc. The best way, would be to look for a Python library (preferably an official one) to work with, which would make the gateway implementation a lot easier and quicker. Yet, keep their API documentation close to you, as they most likely will answer any of your questions or concerns.

**Comment by licht1stein** [comment]
@MartinCastellon we're planning to implement 2checkout too.

**Comment by ufuft** [comment]
i would love to see omise integrated!

**Comment by jamespsteinberg** [comment]
@licht1stein @NyanKiyoshi Any updates on other payment processors? Even if incomplete can put me in the right direction. I will try 2checkout as well

**Comment by NyanKiyoshi** [comment]
@jamespsteinberg thanks for asking. I did not get time to work on any, sadly 👍

**Comment by jamespsteinberg** [comment]
@NyanKiyoshi I just realized you already did the [integration for razorpay](https://github.com/mirumee/saleor/blob/master/saleor/payment/gateways/razorpay/__init__.py) which covers the same countries 2checkout does. Your documentation says it only supports INR, but razorpay [supports a lot](https://razorpay.freshdesk.com/support/solutions/articles/11000065529-what-currencies-does-razorpay-support-).

Maybe it only supported the one currency when you wrote that? It looks like simply changing INR to other currencies and making sure your dashboard is pretty much all it takes unless I am mistaken

I'll try it this month either way

**Comment by NyanKiyoshi** [comment]
It might have recently changed. It was only supporting `INR` and `USD` was not possible to pay with, but you could partially use it. I could check this out.

**Comment by NyanKiyoshi** [comment]
I just tried, it says the currency is not supported.

<div align='center'><img width="347" alt="Screenshot 2019-07-04 at 12 13 56" src="https://user-images.githubusercontent.com/6186720/60659246-3af42b80-9e55-11e9-8635-de5e20741faa.png"></div>

#

From the documentation, it looks like it is a closed feature, you have to request for using it:
> If you already have a Razorpay account, contact our Support Team to enable international payments. While submitting the activation form select the "Want to accept international payments".

**Comment by jamespsteinberg** [comment]
Thanks for the try, I will contact them and see if it works - will let you know what happens

**Comment by NyanKiyoshi** [comment]
Great! Let me know. We can add a flag to the gateway configuration to enable all currencies if the feature actually work.

**Comment by jamespsteinberg** [comment]
So technically it can, but unfortunately it will only work for companies incorporated in India :( 

I see there was some instruction on paypal a bit ago so I'm going to try that
https://github.com/mirumee/saleor/issues/2467

**Comment by NyanKiyoshi** [comment]
Okay! Thanks for the info!
