### ISSUE TITLE
"Discard changes" button doesn't work

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#4013]
Button "Discard changes" in the model translation view should cancel edit mode.

Reproduce:
    - Go to "Translations" section
    - Select a language
    - Select any translatable item e.g. "Categories" > "Accessories"
    - Click on the "Edit" button
    - Insert some text and click "Discard changes" -> nothing happens

Related changes:
    - Change "Discard changes" to "Discard" (according to mockups)
    - Change the background of an active input/textarea when adding a translation - see mockups:

![image](https://user-images.githubusercontent.com/5421321/56717682-7f6c9800-673d-11e9-82c9-c557c35168c7.png)

**Comment by dominik-zeglen** [comment]
Input's background comes from Material Design 2.0 and will be added when upgrading to `material-ui@3`.
