### ISSUE TITLE
Send fulfillment update mail after updating the tracking number

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4017]
### What I'm trying to achieve
Send an update email containing the new tracking number after invoking the `FulfillmentUpdateTracking` mutation.

### Describe a proposed solution
As done in dashboard 1.0, we would have a boolean field defaulted to `false` containing whether we should or not send an update mail to the customer.

#### Dashboard 1.0
https://github.com/mirumee/saleor/blob/2ec7faf34c5e674e15a3b27326956effb5f979ee/saleor/dashboard/order/views.py#L687-L694

#### Mutation
https://github.com/mirumee/saleor/blob/9b3990b90699cb484fcc7621beb63bcbef182787/saleor/graphql/order/mutations/fulfillments.py#L160-L173

**Comment by NyanKiyoshi** [comment]
Same thing for placing a draft order.

**Comment by maarcingebala** [comment]
We should send an email when a draft order is completed and turned into regular order. When draft order is created, no emails should be sent as this is a temporary state.
