### ISSUE TITLE
Some changes from branch "Improve the looks of checkout" doesn't work

### ISSUE THREAD

**Issue by mitcom** [mirumee/saleor#402]
After merge branch `patrys:feature/reorder-checkout` into my `mitcom:feature/reorder-checkout`.
run `npm install ` (likely just in case...), and `./node_modules/.bin/grunt` (even many times) - I can't finish checkout as previous. 'Shipping address step' and 'Summary step' submits form only if I provide new address. These doesn't submit if I try chose existing address or (in "Summary step") select copy address from shipping step.

Console catches errors like:
```
An invalid form control with name='shipping-address-first_name' is not focusable.
An invalid form control with name='shipping-address-last_name' is not focusable.
An invalid form control with name='shipping-address-street_address_1' is not focusable.
An invalid form control with name='shipping-address-city' is not focusable.
```

Temporary workaround is provide any validating address data, and then pick desirable action.

**Comment by patrys** [comment]
It works the same way it did previously: you still need to fill the address form. I did not have enough time to change that before leaving for vacation.
