### ISSUE TITLE
node-sass for node 12 does not exists

### ISSUE THREAD

**Issue by linuxluigi** [mirumee/saleor#4023]
### What I'm trying to achieve
Push latest commit to heroku.

### Steps to reproduce the problem
1. `git push heroku master`

### What I expected to happen
Commit deploy to heroku

### Screenshots
<img width="893" alt="Screenshot 2019-04-25 at 13 15 17" src="https://user-images.githubusercontent.com/8136842/56732011-55769e00-675c-11e9-8081-9c98349aa73e.png">

### Problem
The Problem was that node was updated on the [2019-04-23](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.0.0) and there was no update from [node-sass](https://github.com/sass/node-sass) for that release. 
To avoid this kind of problems in the future is maybe to set node always to an LTS version in `package.json` like:
```
  "engines": {
    "node": ">=10.6.0 <11.0",
    "npm": ">=6.1.0"
  },
```

**Comment by patrys** [comment]
Related upstream bug: https://github.com/sass/node-sass/issues/2632
