### ISSUE TITLE
Ability to save filters

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#4027]
Staff users should be able to save custom filters to be able to quickly access them, e.g.:

![image](https://user-images.githubusercontent.com/5421321/56736422-65947a80-6768-11e9-8ea4-c1e3277deb07.png)

We need to implement support for saving filters in the backend through API. Active filters can usually be persisted as URL query strings in the frontend and we could use them to save filters as well in the backend.

**Comment by NyanKiyoshi** [comment]
A note: we should limit the number of filters.

**Comment by dominik-zeglen** [comment]
> A note: we should limit the number of filters.

...but why?

Also, the `User` model should be able to return filters with linked objects, eg. product filters would look like this:
```graphql
type ProductFilterData {
  isPublished: Boolean
  collections: [Collection]
  categories: [Categories]
  price: PriceRangeInput
  attributes: [AttributeInput]
  stockAvailability: StockAvailability
  productType: ProductType
}

type ProductFilter {
  name: String!
  data: ProductFilterData!
}
```

**Comment by NyanKiyoshi** [comment]
> > A note: we should limit the number of filters.
> 
> ...but why?

The number of filters per user. So they can store like 100-1M filters into the database, which can be huge in data size in the db.

**Comment by dominik-zeglen** [comment]
> Staff users should be able to save custom filters

That implies that this feature would be available only for staff users.

**Comment by maarcingebala** [comment]
The initial version that we want to build now is meant only for staff users.

**Comment by maarcingebala** [comment]
It's possible to save filtering in the browser (without any calls to API). We decided that for now, this is a sufficient solution.
