### ISSUE TITLE
Variant Picker showing variants with ZERO STOCK

### ISSUE THREAD

**Issue by wulaaf** [mirumee/saleor#4029]
Prior to my most recent rebase, this was working as expected, variants with ZERO STOCK would not show up as an option on the detail page.

But now it's showing variants with ZERO STOCK as an option for the variant picker. NOTE: It doesn't let you add to cart though but it still shows up.

This is for regular dashboard.

<img width="666" alt="Screenshot 2019-04-26 12 30 17" src="https://user-images.githubusercontent.com/22291306/56790856-18bfab00-681f-11e9-8aaf-b38da01f6ae2.png">
<img width="535" alt="Screenshot 2019-04-26 12 30 25" src="https://user-images.githubusercontent.com/22291306/56790857-18bfab00-681f-11e9-8003-88b0f1d07e48.png">

**Comment by NyanKiyoshi** [comment]
Hi, it's a desired behavior, it's been at least there for more than a year, if not since the beginning. You could edit the storefront javascript code to exclude those though, it can be easily and quickly achieved.
