### ISSUE TITLE
django-offsite-storages raises NotImplementedError on image upload

### ISSUE THREAD

**Issue by iansprice** [mirumee/saleor#403]
An error is raised whenever a ProductImage's path property is called upon. I am not able to upload any media files due to this and not sure of a workaround. Everything works fine in local dev environment. I'm using Amazon S3 and my static files are working fine (different bucket, same credentials. 
/lib/python3.4/site-packages/offsite_storage/storages/s3.py in path
```python     
def listdir(self, name):
        raise NotImplementedError()
    def modified_time(self, name):
        raise NotImplementedError()
    def path(self, name):
                    raise NotImplementedError() 
```

Full traceback:
lib/python3.4/site-packages/django/core/handlers/base.py in get_response
                                response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
lib/python3.4/site-packages/django/contrib/auth/decorators.py in _wrapped_view
                            return view_func(request, *args, **kwargs) ...
/media/storage/Programming/sale/store/saleor/dashboard/product/views.py in product_image_edit
                    product_image = form.save() ...
lib/python3.4/site-packages/django/forms/models.py in save
                                         construct=False) ...
lib/python3.4/site-packages/django/forms/models.py in save_instance
                    instance.save() ...
/media/storage/Programming/sale/store/saleor/product/models/images.py in save
                    super(ProductImage, self).save(*args, **kwargs) ...
lib/python3.4/site-packages/django/db/models/base.py in save
                                   force_update=force_update, update_fields=update_fields) ...
lib/python3.4/site-packages/django/db/models/base.py in save_base
                        updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields) ...
lib/python3.4/site-packages/django/db/models/base.py in _save_table
                        result = self._do_insert(cls._base_manager, using, fields, update_pk, raw) ...
lib/python3.4/site-packages/django/db/models/base.py in _do_insert
                                           using=using, raw=raw) ...
lib/python3.4/site-packages/django/db/models/manager.py in manager_method
                            return getattr(self.get_queryset(), name)(*args, **kwargs) ...
lib/python3.4/site-packages/django/db/models/query.py in _insert
                    return query.get_compiler(using=using).execute_sql(return_id) ...
lib/python3.4/site-packages/django/db/models/sql/compiler.py in execute_sql
                        for sql, params in self.as_sql(): ...
lib/python3.4/site-packages/django/db/models/sql/compiler.py in as_sql
                            for obj in self.query.objs ...
lib/python3.4/site-packages/django/db/models/sql/compiler.py in <listcomp>
                            for obj in self.query.objs ...
lib/python3.4/site-packages/django/db/models/sql/compiler.py in <listcomp>
                                ) for f in fields ...
lib/python3.4/site-packages/versatileimagefield/fields.py in pre_save
                    file = super(VersatileImageField, self).pre_save(model_instance, add) ...

lib/python3.4/site-packages/django/db/models/fields/files.py in pre_save
                        print(file.path) ...

lib/python3.4/site-packages/django/db/models/fields/files.py in _get_path
                    return self.storage.path(self.name) ...

lib/python3.4/site-packages/offsite_storage/storages/s3.py in path
                    raise NotImplementedError() ...

**Comment by bogdal** [comment]
@iansprice Fix is on the way. `path` method shouldn't be called on the external storage.

**Comment by bogdal** [comment]
The new version of `django-offsite-storage` has been released.
```
pip install django-offsite-storage==0.0.7
```

**Comment by iansprice** [comment]
Works like a charm, thanks! Didn't want to go down the Boto road with this :)
