### ISSUE TITLE
Ubuntu bug recent pull pip dependency

### ISSUE THREAD

**Issue by afhaider** [mirumee/saleor#4031]
Building wheels for collected packages: uwsgi
  Building wheel for uwsgi (setup.py) ... error
.....
  ERROR: Failed building wheel for uwsgi

error cause ----              pipenv shell //reason of shell for virtual env cause failing uwsgi
                                      pip install -r requirements.txt

**Comment by NyanKiyoshi** [comment]
Hi, you need to install `python3-dev`

**Comment by afhaider** [comment]
haideraf@haiderAF-GT:~/Desktop/new/ecom/Beta/saleor$ sudo apt-get install build-essential python3-dev python3-pip python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
libffi-dev is already the newest version (3.2.1-8).
libgdk-pixbuf2.0-0 is already the newest version (2.36.11-2).
shared-mime-info is already the newest version (1.9-2).
python3-cffi is already the newest version (1.11.5-1).
libcairo2 is already the newest version (1.15.10-2ubuntu0.1).
libpango-1.0-0 is already the newest version (1.40.14-1ubuntu0.1).
libpangocairo-1.0-0 is already the newest version (1.40.14-1ubuntu0.1).
python3-dev is already the newest version (3.6.7-1~18.04).
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.


no luck

**Comment by afhaider** [comment]
Building wheels for collected packages: uwsgi
Building wheel for uwsgi (setup.py) ... error 

everything is running i want to know if uwsgi fail what error later i get ?

**Comment by NyanKiyoshi** [comment]
What's the output of those two commands:
```
pip --version
locate Python.h
```

**Comment by afhaider** [comment]
haideraf@haiderAF-GT:~$ pip --version
pip 19.0.3 from /home/haideraf/.local/lib/python3.6/site-packages/pip (python 3.6)
haideraf@haiderAF-GT:~$ locate Python.h
/home/haideraf/.local/share/virtualenvs/E-Bidding-System-master-jiRZRoRf/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/auctionApp-master-wvjRRHJH/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/biddingWeb-master-8TLpQ948/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/j-duPXzuSs/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/k-H54WrjDG/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/ka-xYFv9Msi/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/mk-EAZfYBbO/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/native-a8OCiSey/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/openbidding-master-AkgJJFaq/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/saleor-5ozzG_y4/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/saleor-EwE90_kW/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/saleor-He7KmJAd/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/saleor-Igb3RZH0/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/saleor-LRb4CGp8/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/saleor-U-RxpQN2/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/saleor-boN8DepK/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/saleor-idgbHbox/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/saleor-pU0hX4Tz/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/saleor-u0luLBua/include/python3.6m/Python.h
/home/haideraf/.local/share/virtualenvs/saleorz-V1LtePci/include/python3.6m/Python.h
/home/haideraf/Music/smpt/saleor/Include/Python.h
/snap/gimp/130/usr/include/python2.7/Python.h
/snap/gimp/165/usr/include/python2.7/Python.h
/snap/lightning-python/1/include/python3.6m/Python.h
/usr/include/python2.7/Python.h
/usr/include/python3.6m/Python.h
haideraf@haiderAF-GT:~$

**Comment by afhaider** [comment]
bro actually it work without pipenv shell 
inside virtual enviornment of pipenv making fail uwsgi

**Comment by afhaider** [comment]
https://drive.google.com/file/d/1x5WbyHx1f01kg6cRGLpjBHOfz69kI-uW/view?usp=sharing

TEST and test2 clear problem of saleor uwsgi arise after 1-2month new patches later their was no such kind of bug

**Comment by NyanKiyoshi** [comment]
@afhaider did you resolve your issue? In the comment you deleted, you said you found the reason (you were using a pipenv shell or something like that iirc).

**Comment by afhaider** [comment]
Issue was not resolved I don't know why wheel keep fail on salor pipenv run pip3 install uWSGI
This happen since 1-2month minor major update before it work well

**Comment by NyanKiyoshi** [comment]
But `pip install uwsgi` works, no?

**Comment by afhaider** [comment]
not inside pipenv of saleor folder

**Comment by NyanKiyoshi** [comment]
The best would be to see that directly with [pipenv](https://github.com/pypa/pipenv/).

**Comment by chetabahana** [comment]
I have fixed the uWsgi build with this
```
# Install python and pipenv
export DEBIAN_FRONTEND=noninteractive && export LC_ALL=C.UTF-8 && export LANG=C.UTF-8
apt-get install -qqy python3.7 python3.7-dev python3-pip
pip3 install --user pipenv

# Add pipenv (and other python scripts) to PATH
echo "PATH=$HOME/.local/bin:$PATH" >> ~/.bashrc && source ~/.bashrc

```

**Comment by afhaider** [comment]
worked man like a charm sorry for late reply having exam in college
