### ISSUE TITLE
Add Wishlist

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#4040]
When a product is not available, customer should be able to set notifications for this product.

-  [ ] One user has only one wishlist
- [ ] Wishlist can be shared with a special URL
- [ ] When a product gets back in stock, customer should be notified that observed product is now available
- [ ] When products get discounted, customer should be notified
- [ ] There should be possible to generate a report from all Wishlist items, once we add reports in #3901 
- [ ] It should be possible, to add the product to card straight from the Wishlist

@pwgryglak We need a design for the storefront

**Comment by biomassives** [comment]
i would like to help implement this as part our our tinyfood.org / tinyjunkyard.org project feature requirements

**Comment by Pacu2** [comment]
@biomassives I think no one is working on this issue yet if you like you can start straight away :)

**Comment by maarcingebala** [comment]
@biomassives If you were to start working on that feature so that we can later merge it to Saleor, I'd like to first what models would we use for that and maybe a few scenarios describing the flow we're going to implement.

**Comment by khalibloo** [comment]
I'd like to propose to allow for flexible creation of named lists rather than limiting it to one wishlist per user. Each list could be designated public or private, and can be shared through a link or even deleted. From a usability point of view, it would mean that as a user, I can choose what to share with whom I want. And sharing my wishlist will not be a permanent affair.

**Comment by pwgryglak** [comment]
I've created views for product page some time ago

**Comment by maarcingebala** [comment]
API for wishlist was added some time ago. We'll use a separate issue for implementation in the storefront.

**Comment by parthlawate** [comment]
Hello, 

Can you point to the documentation for the Wishlist API ?

**Comment by obinasBaba** [comment]
Hello, the same here. Where is the wishlist API at?
