### ISSUE TITLE
Auction enable for product

### ISSUE THREAD

**Issue by huuquynh** [mirumee/saleor#4043]
### What I'm trying to achieve
Hello Saleor!

I'm a newbie in Saleor while looking for an open source eCommerce. Saleor looks like a very promised project, while the team plans to expand to multi-vendors (marketplace) support. This is the very special feature could make Saleor becomes a completed solution! I'm very hungry while looking for this feature to develop...

While trying to read the document and install locally to dive into detail. I have another idea for a product to discuss here, sorry if wrong place, but I don't know there is the right place. My idea is not new, but it is from my need right now.

### Describe a proposed solution
Auctions: Could we expand/extend the product to bid by adding some attributes:

Auction enabled product.
- Started time (maybe use the publication_date, or adding one more field to attract customers and plan for future auction actions)
- End time (exactly the time to minute)
- Price for sale (if someone wants to buy now, not bid anymore).
- Started/Current price.
- Step increase. (the step increase maybe setup automatically, it belongs to the current price likes eBay).
- Auto setup new auction after end time for this product after some days (optional).

So, we need a category Auctions for all products are enabled auction function. This page will show all of them, may be separated by a group of product type too. We could separate the next auctions products in the case started time is coming. And products are in bidding now.

Each auction product displays the current price, next bidding price and bidding function for the member. It could display a thread of messages of bidding members while they are bidding for attractive another.

When auction finish it should show the winner and make it become an order like normal.

If this auction function could be developed, it should be enabled for multi-vendors (marketplace) too.

That's my simple ideas. So please tell me if this function could be developed/extend the current or not? Could we define in the attributes of product/product type, or must be extended by writing more code/module?

Thanks so much!

**Comment by qrider** [comment]
+1 for this
