### ISSUE TITLE
pip install django-compression-middleware   (SEO improvement )

### ISSUE THREAD

**Issue by afhaider** [mirumee/saleor#4046]
It is meant to be a drop-in replacement for Django’s GZipMiddleware. Its documentation — including security warnings — therefore apply here as well.

The middleware is focussed on the task of compressing typical Django responses such as HTML, JSON, etc. Both normal (bulk) and streaming responses are supported. For static file compression, have a look at other projects such as WhiteNoise.

Most browsers now support Brotli compression (check support status on Can I use… Brotli). The middleware will choose the best compression method supported by the client as indicated in the request’s Accept-Encoding header. In order of preference:

Brotli
gzip
[[
can u people make this middleware work i try and fail to make it work with heroku but in pythonanywhere.com it work correctly ]]

**Comment by NyanKiyoshi** [comment]
Hi,

It's the HTTP server's job to do that (nginx, Apache, etc.).

**Comment by afhaider** [comment]
https://drive.google.com/file/d/1sdIgC4MDxSb_oZVm73kfbEmrUg8xSajZ/view?usp=sharing

this is my seo

**Comment by afhaider** [comment]
HTMLmin / djangocompressor /gzip advance (compression-middleware)
what with apache anyway?
