### ISSUE TITLE
Voucher Min Amount Spent Blank After Creation

### ISSUE THREAD

**Issue by wulaaf** [mirumee/saleor#4052]
### What I'm trying to achieve
Add vouchers with min amount spent

### Steps to reproduce the problem
Create new voucher, fill in the fields, hit create.

### What I expected to happen
Find new voucher created in the Voucher list page

### What actually happened
The voucher was created but the min amount spent field is blank

### Screenshots
<img width="752" alt="Screenshot 2019-05-01 18 38 21" src="https://user-images.githubusercontent.com/22291306/57019562-5b7aec00-6c40-11e9-83e1-42ed0cf5362c.png">
<img width="977" alt="Screenshot 2019-05-01 18 38 29" src="https://user-images.githubusercontent.com/22291306/57019564-5cac1900-6c40-11e9-8fbb-f5ccaddfc292.png">

**System information**
Operating system: macOS Mojave
Browser: Chrome

**Comment by wulaaf** [comment]
Correction: THIS ONLY HAPPENS WHEN I SELECT

Specific collection of products

It works perfectly when it's all products or a specific product

**Comment by NyanKiyoshi** [comment]
Steps to reproduce:
1. Create a voucher;
1. Select a voucher type applicable for other than all products or shipping;
1. Give it a minimum amount.

The minimum amount field is not the same one on the other types as the 'all products' or 'shipping' type's minimum amount field. It seems like the value is not taken and no populated.
