### ISSUE TITLE
Add to cart for each item in category items view

### ISSUE THREAD

**Issue by heiqs** [mirumee/saleor#4063]
Hi,

Is it possible to add "Add to cart" button and "Quantity" field to the category items view? So, the user just can add to cart without clicking on the item?

**Comment by NyanKiyoshi** [comment]
Hi,

Yes it would be easy to do. You can take a look around the following:
1. The endpoint to add a product to the checkout is `product:add-to-checkout`, it takes a parameter `product_id`. You will need to `POST` to it with a `quantity` and a `variant` (id).
1. You will need to add some javascript/react code to handle the 'add to checkout' click action and to allow the user to select a variant (unless you don't have any variant or another mechanism);
1. You can edit the product listing template to add a button/js that will handle that.

**Comment by heiqs** [comment]
Thanks for your help. I tried the following code for the order form wrapped in a for loop of products: 

    <form id="product-form-{{product.pk}}" role="form" class="product-form clearfix" method="post"
          action="{% url 'product:add-to-checkout' product_id=product.pk slug=product.get_slug %}" novalidate>
      {% csrf_token %}
      <input type="hidden" name="variant" value={{product.pk}} id="id_variant">
      <div class="product__info__quantity">
        <div class="form-group">
          <label for="id_quantity">Quantity</label>
          <input type="number" name="quantity" value="1" min="0" max="999" class="form-control" placeholder="Quantity"
                 title="" required id="id_quantity">
        </div>
      </div>
      <div class="form-group product__info__button">
        <p>
          <button class="btn btn-primary narrow">
            {% trans "Add to cart" context "Product details primary action" %}
          </button>
        </p>
      </div>
    </form>

However, when I try to add an item to the cart, it always use the data from the first product in the page not the one which is clicked to be added.

Note that there is no other variant for each product.
Until now, I could not realize for the issue. Thanks for your help!

**Comment by NyanKiyoshi** [comment]
>   ```<input type="hidden" name="variant" value={{product.pk}} id="id_variant">```

Maybe that's your issue? It should be `value="{{product.pk}}"`. That may be it. Let me know!

**Comment by heiqs** [comment]
same as before. Still takes the first product and not the current one. Even for the quantity value, it uses the value of the first item.

**Comment by NyanKiyoshi** [comment]
Could you send me the whole file so I can take a look? That would be way easier than a snippet 👍 
You can send it to mikail@vanille.bid or here.

**Comment by heiqs** [comment]
I already send the file to you. thanks

**Comment by NyanKiyoshi** [comment]
Alright. It took me sometime but here you go. The issue is that the javascript code that is doing the ajax request when you click on "add to card" is getting the form values by using the HTML id. So it never looks at the actual form.

Here is the edits to make it work with any number of forms on a single page:
```diff
Index: saleor/static/js/components/checkout.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- saleor/static/js/components/checkout.js	(revision f53f2d201f4eff9fa57da75f114979669535af17)
+++ saleor/static/js/components/checkout.js	(date 1558976277991)
@@ -40,10 +40,11 @@
   });
   $('.product-form button').click((e) => {
     e.preventDefault();
-    let quantity = $('#id_quantity').val();
-    let variant = $('#id_variant').val();
+    let $target = $(e.target.form);
+    let quantity = $target.find('input[name="quantity"]').val();
+    let variant = $target.find('input[name="variant"]').val();
     $.ajax({
-      url: $('.product-form').attr('action'),
+      url: $target.attr('action'),
       type: 'POST',
       data: {
         variant: variant,
```

Also, you need to pass a variant id instead of passing the `product_id` for the variant id.

**Comment by NyanKiyoshi** [comment]
@heiqs we can probably close this now as you seem to have resolved your issue?

**Comment by heiqs** [comment]
Thanks for solving this issue.

> Also, you need to pass a variant id instead of passing the `product_id` for the variant id.

I needed to wrap the order from in an if block in case there is no variant picker



          {% if show_variant_picker %}
            {% csrf_token %}
            <div id="variant-picker" data-variant-picker-data="{{ variant_picker_data }}" data-action="{% url 'product:add-to-checkout' product_id=product.pk slug=product.get_slug %}"></div> {% else %}

And it worked with having product_id as variant_id. Maybe because I have only one variant for each product.

This issue can be closed. Thanks!

**Comment by heiqs** [comment]
>
