### ISSUE TITLE
Drop django_celery_results pkg

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#4065]
Saleor does not use celery task results, but uses `django_celery_results`. 

DoD:
- drop `django_celery_results` from requirements
- remove `CELERY_RESULT_BACKEND` setting
- ~~globally drop storing task results. I don't think we need to add manually `ignore_result=True` to every task (correct me if thats not good idea)~~ - changing global celery settings can interfere with existing systems

**Comment by patrys** [comment]
Not sure if it's a good idea to globally disable storing results. Imagine trying to add an external app that depends on the default being true.
