### ISSUE TITLE
Flickering unit test

### ISSUE THREAD

**Issue by zadigus** [mirumee/saleor#4081]
### What I'm trying to achieve

I am trying to make all unit tests pass all the time.

### Steps to reproduce the problem
1. Setup a Jenkins server (or whatever CI/CD server)
2. Run the tests every 30 minutes

The tests are run by following jenkins pipeline (which is self-explanatory):

```
stages {
    stage('Virtual Environment Installation') {
      steps {
        withEnv(["HOME=$WORKSPACE"]) {
          sh "virtualenv $VENV"
          sh "chmod u+x ./scripts/install/*.sh"
          sh ". $VENV/bin/activate && ./scripts/install/install.sh"
          sh ". $VENV/bin/activate && ./scripts/install/install-dev.sh"
        }
      }
    }
    stage('Build saleor frontend') {
      steps {
        withEnv(["HOME=$WORKSPACE"]) {
          sh "cd saleor && npm i && npm run build-assets && npm run build-emails"
        }
      }
    }
    stage('Performing saleor unit tests') {
      environment {
        DATABASE_URL = credentials('postgres-credentials')
        DJANGO_SETTINGS_MODULE = 'tests.settings'
        PYTHONPATH = "$PYTHONPATH:$WORKSPACE/saleor"
        SECRET_KEY = 'theSecretKey'
      }
      steps {
        sh ". $VENV/bin/activate && cd saleor && pytest -ra --junitxml=$REPORTS_FOLDER/unit-tests.xml"
      }
    }
  }
```

### What I expected to happen

100% success

### Screenshots

What I am experiencing is the following:

![image](https://user-images.githubusercontent.com/8761254/57349155-5eeb0780-7159-11e9-8a2a-961e84848493.png)

Sometimes the tests pass, sometimes not. The server configuration is always the same. The only job running on the server is that one. Every time the tests don't pass, the same test is responsible for failure: tests.api.test_category.test_category_image_query 

![image](https://user-images.githubusercontent.com/8761254/57349284-ca34d980-7159-11e9-84d6-28d45aac147a.png)

**System information**
Run in docker image `nikolaik/python-nodejs:latest`

Does anyone else experience that issue of flickering test?

**Comment by maarcingebala** [comment]
@korycins @NyanKiyoshi Do you know what might be the issue here?

**Comment by korycins** [comment]
@maarcingebala @zadigus  I've fixed it a couple of weeks ago. The problem was that one test: `test_create_thumbnails` didn't override settings correctly. 
Can you pull the newest changes and check if it works correctly?

**Comment by maarcingebala** [comment]
We're running tests on Travis for every PR plus on CircleCI for builds on master and they pass so I guess everything is correct.

**Comment by zadigus** [comment]
I am currently using release 2.6.0. What commit number can I checkout to double-check that on my side?

**Comment by korycins** [comment]
@maarcingebala It works because we execute tests on 2 Travis's cores
@zadigus  here you have a PR: https://github.com/mirumee/saleor/pull/3975/files#diff-cc4345db19ff44863e9122c74e9f383fR167
Here you have the commit with this fix: https://github.com/mirumee/saleor/pull/3975/commits/4f54876016a6187381d57ce571824a1edb9db7c6

**Comment by zadigus** [comment]
I confirm that this is now working with release 2.6.0. Thanks a lot for that!
