### ISSUE TITLE
Language File Path

### ISSUE THREAD

**Issue by gomezgleonardob** [mirumee/saleor#4088]
I started to translate for the Spanish (Spanish-Co), if you could help me the route to place the files.po

**Comment by maarcingebala** [comment]
Hey, we use [Transifex](https://www.transifex.com/mirumee/saleor-1/) to manage translations and we regularly sync Saleor with it. If you want to add some translations, create an account on Transifex and do it over there. Thanks!

**Comment by patrys** [comment]
You should be able to upload a .po file to Transifex as well!
