### ISSUE TITLE
Can Saleor do the job of Point of Sales system in a restaurant? Possible to create plugins that could make it work like that?

### ISSUE THREAD

**Issue by dnk8n** [mirumee/saleor#4091]
### What I'm trying to achieve
I have been asked by a small local coffee shop what it might take for their staff to have access to a POS system from their iPads when they take orders. I immediately thought of Saleor, but potentially this is outside of the area you hope to support.

### Describe a proposed solution
I want the waiters/waitresses to each have an iPad with Safari or Chrome (or your PWApp) connected to a local server (PC at the back of the restaurant). From here they would complete the order, which would generate an invoice payable by cash or credit card at the store front.

Is this already supported? A good idea? Or is there a better fitting open-source software for this? If so, is there integration? Because maybe the restaurant can use Saleor for online sales and the other system for taking orders and they can be integrated where necessary.

**Comment by maarcingebala** [comment]
Hey, sorry for the late response. It's definitely a good idea and it would be very exciting to support some POS solution with Saleor! Currently, there is no integration to support that, but that's an area that we'd like to explore at some point. I don't know how much customization to our PWA client it would require. But even if it meant building a new app from scratch, that should be definitely doable, since we have the GraphQL API. 

If you ever wanted to tackle that issue, feel free to reach out to us if you need any help!

**Comment by dnk8n** [comment]
I am quite keen to try a very simple front end built in Elm. I will share
here but I think it would be it's own project.

Could always make a more simple one for starters, then make plans to
support a more fully featured one after that.

Will post progress here soon.

**Comment by dnk8n** [comment]
Thinking about this a bit more.

Is it possible to have two instances of saleor server load-balanced and in-sync?

I am thinking one instance would be on an internal network local to the shop and the other would be public facing on the public internet. The two instances would be connected but the public could not access the shop's local saleor instance.

The reason is because I would want shoppers to be able to purchase from within the shop without going online. The shop frontend would talk directly to the local saleor server (which would then sync with the other instance). This reduces latency.

**For this issue, it would allow a much more responsive POS frontend client that only needs access to the local network and no internet usage at all.**

Thoughts / ideas?

**Comment by dnk8n** [comment]
Instead of some syncing functionality, all that would actually be needed is only one database, accessible to both instances. The instances themselves don't need access to each other actually.

**Comment by dnk8n** [comment]
So on further thoughts, a load-balancer isn't required at all. Sorry for the over-share of me thinking out loud (should have had coffee first).

This is what I mean. Maybe an image explains better

![internal_plus_external_saleor](https://user-images.githubusercontent.com/3307753/58239523-7d502600-7d49-11e9-87ad-65f72b95238b.png)

**Comment by patrys** [comment]
I have a Stripe POS terminal sitting on my desk currently so we're definitely looking at adding support for collecting payments physically ("card present"). Can't promise any dates though.

I imagine this would have to be a separate mutation in the API. I'm not sure whether any of this will ever get integrated into the PWA client though as it's built to be a typical online storefront. So even if we merge it your options could be limited to draft orders in the dashboard, or implementing a custom POS user interface.

**Comment by dnk8n** [comment]
I think many micro-servers each doing only one thing very well is the way to go.

So even if it is a new POS client + POS backend that syncs with the current Saleor backend via the graphql API.

**Comment by dnk8n** [comment]
But the idea is for Saleor to keep track of the stock and the accounting at the end of the day.

**Comment by maarcingebala** [comment]
Closing this for now. I'm pretty sure we'll get back to this idea in the future.
