### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by puneet41824** [mirumee/saleor#4104]
Now that PWA is on React, is there any plan to introduce mobile app (android, ios, react-native) which consumes the backend GraphQL API?

**Comment by maarcingebala** [comment]
There are no such plans. That exactly the role of PWA - it is supposed to give you the experience of a native mobile app with a mobile-first design, offline mode and notifications.

**Comment by bilalasif95** [comment]
Hi !
Can i get open source code of Saleor Android App ?
Thanks

**Comment by maarcingebala** [comment]
There is no Android app, the storefront app is built in JavaScript: https://github.com/mirumee/saleor-storefront/

**Comment by bilalrns** [comment]
@maarcingebala  Hi sir !
Can you please me ?
I am generating PWA apk of saleor but it's throwing following error.
Please tell me solution.
Thanks
![Screenshot from 2020-05-19 15-49-19](https://user-images.githubusercontent.com/55876274/82319158-86221900-99ea-11ea-90e4-00405ee54317.png)
