### ISSUE TITLE
Missing payment gateways in gql enum

### ISSUE THREAD

**Issue by koradon** [mirumee/saleor#4105]
### What I'm trying to achieve
gql enum `PaymentGatewayEnum` takes values from `settings.CHECKOUT_PAYMENT_GATEWAYS` instead of `settings.PAYMENT_GATEWAYS`.
This cause problem in storefront when the developer is calling `npm run codegen` on saleor default settings.

Those two variables should:
`settings.CHECKOUT_PAYMENT_GATEWAYS` - store information on available payments gateways in checkout
`settings.PAYMENT_GATEWAYS` - store information of all implemented payments gateways in saleor

### Steps to reproduce the problem
1. Checkout to clean saleor master branch.
2. Checkout to clean saleor-storefront branch.
3. Change some query or mutation in saleor-storefront
4. Call `npm run codegen`

### What I expected to happen
GrapQL schema has all the implemented payment gateways in enum.

**Comment by maarcingebala** [comment]
Fixed in #4108
