### ISSUE TITLE
Customize Filter view

### ISSUE THREAD

**Issue by dikshantsagar** [mirumee/saleor#4110]
### What I'm trying to achieve
…
I want to customize filters on the category page to show minimal icons too for eg in case of quantity I can show different size of bottle icons
### Describe a proposed solution
...

### Other solutions I've tried and won't work
…
I cant seem . to find the react component to edit this filter section
![Screenshot 2019-05-15 at 12 58 10 PM](https://user-images.githubusercontent.com/31593366/57756611-42c70780-7711-11e9-93cf-d8ac16d6e974.png)
something like this I want.
Can someone point me to the component file of the filter section where i can customize it.

**Comment by maarcingebala** [comment]
@dominik-zeglen / @benekex2 What files would you recommend to start looking to add such icons?

**Comment by dikshantsagar** [comment]
maybe start and try with a png.
