### ISSUE TITLE
Some phone numbers are accepted by validation, but are not saved in database

### ISSUE THREAD

**Issue by Kwaidan00** [mirumee/saleor#4120]
### What I'm trying to achieve
I'm trying to use invalid US phone number: +1 555 555 5555 in my `shippingAddress`. It passes validation (I have no error), but it is not saved in the database.

### Investigation
It's another consequences of the packages upgrade described in #4086. The new version of `django-phonenumber-field` calls `is_valid` method on the phone number before saving it to the database. On the other hand, backend validates shipping address with `I18nMixin` class, which uses https://github.com/mirumee/saleor/blob/master/saleor/account/i18n.py. There is used a concept of _possible_number_, not a valid number 

### Steps to reproduce the problem
1. Use that phone number in shipping address form in https://pwa.getsaleor.com/
2. Select shipping method
3. Phone number disappeared.

### What I expected to happen
Invalid phone numbers (like +1 555 555 5555) are rejected on validation *or*, if there is a decision to store possible and potentially invalid phone numbers in the database, 

### Screenshots

1.
<img width="717" alt="Zrzut ekranu 2019-05-16 o 13 27 31" src="https://user-images.githubusercontent.com/15018155/57850774-1a0d4380-77df-11e9-8f18-22c6532a5ca1.png">

2. 
<img width="586" alt="Zrzut ekranu 2019-05-16 o 13 27 48" src="https://user-images.githubusercontent.com/15018155/57850789-21345180-77df-11e9-89cb-914b857abaf6.png">

3. 
![Zrzut ekranu 2019-05-16 o 13 31 55](https://user-images.githubusercontent.com/15018155/57850803-27c2c900-77df-11e9-9fd9-931ac552e651.png)

**System information**
Operating system: n/a
Browser: n/a

**Comment by patrys** [comment]
I think the problem may be here: https://github.com/mirumee/saleor/blob/d212e1df89f73997138734c8cd6758912fab1e07/saleor/account/models.py#L21-L24

We're explicitly changing the default validators to less strict ones. There is no comment explaining the reasoning behind it though.
