### ISSUE TITLE
Changing quantity in bag removes item

### ISSUE THREAD

**Issue by iotmani** [mirumee/saleor#4128]
### What I'm trying to achieve
Remove item quantity in basket to make it e.g. from 1 to 2, removes the whole item as if I set it to 0.

### Steps to reproduce the problem
In pwa.getsaleor.com demo:
1. Add one or more items to basket
2. Go to my shopping bag, and attempt to change quantity

### What I expected to happen
Input box is empty so I can add a different number of items, instead of removing item

### Screenshots

**System information**
Operating system: iOS 12.1
Browser: Safari

**Comment by maarcingebala** [comment]
Hey, just to clarify, this issue affects the PWA storefront? We have [a separate repository for that](https://github.com/mirumee/saleor-storefront/), could you reopen the issue over there? 
Anyway, I'm trying to reproduce your issue but it all works fine for me. I'm testing locally and in the public demo (pwa.getsaleor.com).

**Comment by iotmani** [comment]
Thanks for the prompt response. Strange, I'm able to reproducing it each time.
I'll close this one and will need to open it against Storefront as you directed :).

**Comment by NyanKiyoshi** [comment]
@iotmani try on another browser/device as well, might come from the browser.
