### ISSUE TITLE
only pdf invoice is not working properly after deploying on digitalocean

### ISSUE THREAD

**Issue by MH-sabu** [mirumee/saleor#4130]
After deploying saleor on digitalocean everything working well except pdf invoice .
This is how it looks like . this image is screenshot of pdf

![Screenshot from 2019-05-21 11-34-25](https://user-images.githubusercontent.com/14260461/58071155-7ac0c580-7bbd-11e9-86bb-b4188193b490.png)

**Comment by NyanKiyoshi** [comment]
Hi, can you make sure localhost is redirected to 127.0.0.1 in `/etc/hosts`?

**Comment by MH-sabu** [comment]
@NyanKiyoshi   I watched this tutorial below  for deployment. I have not found the option you are mentioning.

https://gist.github.com/bradtraversy/cfa565b879ff1458dba08f423cb01d71

**Comment by NyanKiyoshi** [comment]
Please try redirecting localhost to 127.0.0.1 in `/etc/hosts`.

```
# echo 'localhost 127.0.0.1' >> /etc/hosts
```

**Comment by MH-sabu** [comment]
@NyanKiyoshi  localhost is redirected to 127.0.0.1 in /etc/hosts , but it does not work

**Comment by NyanKiyoshi** [comment]
Can you show the errors that you have in your django error logs?

**Comment by MH-sabu** [comment]
Thanks @NyanKiyoshi  , it works now, i had to add localhost in ALLOWED_HOSTS
