### ISSUE TITLE
Implement a bot reporting pre-commit results

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4131]
### What I'm trying to achieve
To view the pre-commit results on the PR comments.

### Describe a proposed solution
Implement a bot as a GitHub application to do it for us.

This will report:
- black
- flake8
- isort
- trailing blank spaces
- outdated GraphQL schema
- outdated Typescript types

### Other solutions I've tried and won't work
Travis, GitHub Actions, code climate...

**Comment by Satloff** [comment]
@NyanKiyoshi this seems like great idea. Any ETA on when you might have time to implement it?

**Comment by NyanKiyoshi** [comment]
Hi @Satloff, it was actually supposed to be done a few days ago but I got material issues (power supply died) so I was unable to work on it.

I am not sure when it will happen. I might do it this weekend (I want to this task to be done during my free time, off from work–so it depends on my availability).

This *will* be implemented as a GitHub action (unless impossible to work something out with the current limitation of this feature).
