### ISSUE TITLE
"Visibility" Card - Logic and Frontend Changes

### ISSUE THREAD

**Issue by pwgryglak** [mirumee/saleor#4137]
We need to change "Availability" Card title to "Visibility" as it was reported as confusing. 
We should also change the logic behind how publishing elements work according to design.

**Comment by maarcingebala** [comment]
To clarify, we need to migrate this:
![image](https://user-images.githubusercontent.com/5421321/58163233-eff6ce00-7c83-11e9-8928-de9dd40173b8.png)

to this:
![image](https://user-images.githubusercontent.com/5421321/58163267-fd13bd00-7c83-11e9-8c97-c6ea961301a7.png)

This applies to: products, collection, pages (detail views).

**Comment by maarcingebala** [comment]
State when the item is visible:
![image](https://user-images.githubusercontent.com/5421321/58163476-61cf1780-7c84-11e9-8046-2edfd11871fc.png)
