### ISSUE TITLE
Adding Start and End Hour in Discount Section

### ISSUE THREAD

**Issue by pwgryglak** [mirumee/saleor#4142]
### What I'm trying to achieve:
Adding Start Hour and End Hour inputs to Discount Information card in Discount. It will give more possibilities to store owners - such as Flash Sales

### Screenshots or mockups:
View in discounts section of Figma project

**Comment by maarcingebala** [comment]
@pwgryglak Are there any other inputs that we should migrate from just dates to date-times? What about publication dates for products, collections or pages?

**Comment by maarcingebala** [comment]
This requires changes in the backend and API, I'll open an issue once we know exactly which fields to migrate.

**Comment by pwgryglak** [comment]
I think that it is one of the things that we can discuss with Wilton to get actual use cases whether for example product should be published on a specific hour.
If there are no such cases then we shouldn't make unnecessary changes
