### ISSUE TITLE
Implement filters to products within a collection and a category

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4143]
We should be able to filter product within a collection/category, e.g. set the sort order.

**Comment by NyanKiyoshi** [comment]
Blocked by https://github.com/tfoxy/graphene-django-optimizer/issues/23.

**Comment by khalibloo** [comment]
Hi @NyanKiyoshi any updates on this? I can't seem to find any clean workarounds for filtering products in a category/collection.

**Comment by NyanKiyoshi** [comment]
Hi! I didn't get time to work on this yet.
