### ISSUE TITLE
Assigning orders to customers

### ISSUE THREAD

**Issue by wulaaf** [mirumee/saleor#4147]
Is there a way to assign orders to customers?

I know customers can either sign up for an account or log in to (if they already have an account) on the checkout-success page.

Assign a guest order to an already existing account or create an account for a guest order. Is it possible to do this from the dashboard? If not, then how would one go about doing it? Has anyone built something similar for their application?

**Comment by NyanKiyoshi** [comment]
That's not possible. It would be easy to add this feature if someone wants to pick this up. But we need to make sure it doesn't alter any data of the order, the order data in itself should remain unchanged (all the data used in the invoice).
