### ISSUE TITLE
Refactoring of password recovery system

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#4153]
Proposed changes:

- we don't have mutations for password recovery and account activation
- mutation which reset password should also return JWT token so user don't need to pass login/password twice (usually after password change user want to access page)
- for password recovery we are encoding user pk (`urlsafe_base64_encode(force_bytes(user.pk))`) which is not good practice (exposing database ids ). Much better would be using account email for that.
- mutation for password reset should have url for recovery view as additional field - GraphQL API does not know how routing in PWA looks like so backend cant ATM attach valid URL ino emai

Contact me if you need more background for why we need to include those changes

**Comment by NyanKiyoshi** [comment]
> mutation for password reset should have url for recovery view as additional field - GraphQL API does not know how routing in PWA looks like so backend cant ATM attach valid URL ino emai

I'm not sure what you mean there. Could you give more details about that?

**Comment by krzysztofwolski** [comment]
- backend currently act as GQL endpoint only, no other views should be needed
- all routing is handled by frontend SPA
- when generating password recovery email, we want to send user URL to right SPA view

To achive that, we should get url from frontend when user request password change and make sure that url is from our domain

**Comment by maarcingebala** [comment]
To restrict what URLs are allowed, we will need a whitelist of domains in the settings file.
