### ISSUE TITLE
Typo in Payment Gateway 'razorpay'

### ISSUE THREAD

**Issue by mainanick** [mirumee/saleor#4158]
### What I'm trying to achieve
…
Typo in Payment razorpay. https://github.com/mirumee/saleor/blob/0cf515b36501f341fda8f3310c6f0f570e6a5350/saleor/payment/gateways/razorpay/forms.py#L13

https://github.com/mirumee/saleor/blob/0cf515b36501f341fda8f3310c6f0f570e6a5350/saleor/payment/gateways/razorpay/forms.py#L16
### Steps to reproduce the problem
1. N/A

### What I expected it to be
…
Razorpay instead of Rozorpay
### Screenshots

**System information**
Operating system: N/A
Browser: N/A

**Comment by NyanKiyoshi** [comment]
Hi!

Thanks for finding the typo. Maybe you could open a PR for it?
