### ISSUE TITLE
page.translated.content doesn't render in page/details.html (Dashboard 2.0)

### ISSUE THREAD

**Issue by jervislam0911** [mirumee/saleor#4159]
### What I'm trying to achieve
Using Dashboard 2.0 to translate pages.

### Steps to reproduce the problem
1. Create a page and publish it in Dashboard 2.0
2. Go to Translations --> select another language and type in the translation and save it 
3. Go to the page URL and nothing shows up when switching to the language.

### What I expected to happen

- Title and content both are being translated.
- pages details (title, contents, SEO descriptions ) saved in dashboard 2.0 will be saved in the default dashboard.

### Actual result

- Only title shows and gets translated, the content did not render in the page details.
- Everything saved in the default dashboard, except content.

**System information**
Operating system:  MacOS
Browser: Chrome

**Comment by maarcingebala** [comment]
The rich-text editor in Dashboard 2.0 is writing content in a different format than the one supported by Storefront 1.0 (the one using HTML templates). Support for these fields will be added soon in Storefront 2.0 (see https://github.com/mirumee/saleor-storefront/issues/305).

**Comment by jervislam0911** [comment]
Thanks for clarifying that. Closing the issue.
