### ISSUE TITLE
Saleor will authorize and charge more than the order's total if allowed

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#4162]
### What I'm trying to achieve
I'm using the GraphQL API to create a checkout session and pay for it using Locust. Due to a copy-and-paste bug in my stress test suite, the total amount passed to `checkoutPaymentCreate` is higher than the order's total.

### Steps to reproduce the problem
1. Create a checkout session with `checkoutCreate`
2. Prepare the checkout sessions as needed (add billing and shipping addresses etc.)
3. Use the `checkoutPaymentCreate` mutation and pass a much higher `amount` that what the checkout object returns as total
4. Call `checkoutComplete` and observe that the store proceeds to capture more than the order's total

### What I expected to happen
Either get an error when attempting to create a payment object for the checkout or have the store automatically adjust the total down when capturing the payment.

### Screenshots
![image](https://user-images.githubusercontent.com/81205/58415794-dc7ea500-807f-11e9-8a52-271b94e0bc1b.png)

**Comment by iflare3g** [comment]
Hi @maarcingebala , is this one related to some PR already opened ? 😆

**Comment by NyanKiyoshi** [comment]
@iflare3g no, it's free to take

**Comment by iflare3g** [comment]
> @iflare3g no, it's free to take

Ok thanks, because before I've already opened a PR that was covered by an existing one.
So now it's better to ask you before working on it.

**Comment by iflare3g** [comment]
Glad to see it's closed! Sorry if I didn't get to resolve this , I totally finished the free time I could spend on this ☹️
Hope to contribute more into the future!
