### ISSUE TITLE
Setting CHECKOUT_PAYMENT_GATEWAYS as env variable?

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#4177]
### What I'm trying to achieve
Hi there,
We are trying to set-up saleor as our production backend for our existing webshop. With a first test we are using the official docker container from saleor in a kubernetes environment. Most things where straight-forward until now, but we are stuck trying to activate the payment gateway. Setting the ENV variable `CHECKOUT_PAYMENT_GATEWAYS` is not working as described here: https://docs.getsaleor.com/en/latest/gettingstarted/configuration.html#payments-gateways

It has no effect. We still just see the dummy gateway activated. Seems like we need to build our own docker container, that is replacing this setting: https://github.com/mirumee/saleor/blob/master/saleor/settings.py#L592

Is this the expected way of deploying to production? What is the reason for this decision, to make all settings ENV variables except the CHECKOUT_PAYMENT_GATEWAY?

**Comment by korycins** [comment]
Hi @JannikZed 
It seems that there is misleading information in the Configuration section about `CHECKOUT_PAYMENT_GATEWAYS` 
Yes, it should be also possible to configure directly from the env variables.
Same thing with the rest of the gateways' parameters

There is the discussion of this variable and their responsibility here: https://github.com/mirumee/saleor/issues/3250#issuecomment-436716040

In the meantime, you can create your own `settings_local` file with declared `CHECKOUT_PAYMENT_GATEWAYS`

**Comment by JannikZed** [comment]
hi there,
as we are running again and again in issues configuring the CHECKOUT_PAYMENT_GATEWAYS variable in our docker environment, I would like to try out now the settings_local file that you recommend.
Could you maybe provide us with further information on that? Afterwards, we can close this issue here.

**Comment by korycins** [comment]
set ENV - `DJANGO_SETTINGS_MODULE=saleor.settings_local`
```
from .settings import *

PAYMENT_GATEWAYS = {
    DUMMY: {
        'module': 'saleor.payment.gateways.dummy',
        'config': {
            'auto_capture': True,
            'connection_params': {},
            'template_path': "order/payment/dummy.html"
        }
    },
    BRAINTREE: {
        'module': 'saleor.payment.gateways.braintree',
        'config': {
            'auto_capture': False,
            "template_path": "order/payment/braintree.html",
            'connection_params': {
                'sandbox_mode': get_bool_from_env('BRAINTREE_SANDBOX_MODE', True),
                'merchant_id': os.environ.get('BRAINTREE_MERCHANT_ID', 'my_merchant'),
                'public_key': os.environ.get('BRAINTREE_PUBLIC_KEY', 'my_public'),
                'private_key': os.environ.get('BRAINTREE_PRIVATE_KEY', 'my_private')
            }
        }
    },
}

CHECKOUT_PAYMENT_GATEWAYS = {
    DUMMY: pgettext_lazy("Payment method name", "Dummy gateway"),
    BRAINTREE: pgettext_lazy("Payment method name", "Braintree Dummy gateway"),
}
```

**Comment by JannikZed** [comment]
Thank you very much! I works like this.
