### ISSUE TITLE
View of all products

### ISSUE THREAD

**Issue by heiqs** [mirumee/saleor#4180]
There is no endpoint for viewing all products on one single page in the storefront as the one in the dashboard.

Should I generate the view myself? Thanks.

**Comment by maarcingebala** [comment]
Hey, to render a product list you could use the following query:
```graphql
{
  products(first: 20) {
    edges {
      node {
        id
        name
      }
    }
  }
}
```
Isn't this what you're looking for? Pagination is mandatory for connections in our API and at maxium, you could fetch 100 products in one query.

**Comment by maarcingebala** [comment]
Please reopen if you have more questions about this.
