### ISSUE TITLE
No filter for categories

### ISSUE THREAD

**Issue by heiqs** [mirumee/saleor#4181]
There is not possible to have attributes for the categories. Is there any way to do that or should I implement myself?

**Comment by maarcingebala** [comment]
Hey, what attributes would you want to use with categories?

**Comment by heiqs** [comment]
similar to the ones for products. I don't understand why it is not possible to have the possibility to use attributes for the categories? Maybe there are some considerations which I am not aware of that.

Assume that your categories have an attribute of color and then you wanna filter only those categories with a specific color and then search on those products.

**Comment by maarcingebala** [comment]
It is totally possible to have them from the code perspective, but I guess we've never had a valid use case for that. From what I see in Magento or Shopify it's also not available.
