### ISSUE TITLE
comparison between two products

### ISSUE THREAD

**Issue by heiqs** [mirumee/saleor#4184]
### What I'm trying to achieve
Based on the data (attributes, description, etc.) for each product, I can be able to compare products with each other. A sample use case can be a website for selling cars.

### Describe a proposed solution
1. Click a product.
2. Click a comparison button.
3. A new view with n (a fixed number of compared products) columns and then for each column a search or dropdown button for finding the needed product for comparison.

### Other solutions I've tried and won't work
…

**Comment by NyanKiyoshi** [comment]
I feel like it would be more fit to post this to https://github.com/mirumee/saleor-storefront as it only requires front end changes for such feature.

**Comment by heiqs** [comment]
Hi, you are right. I will post it there.
