### ISSUE TITLE
[Cart] Changing quantity requires page refresh

### ISSUE THREAD

**Issue by bogdal** [mirumee/saleor#421]
Front-end issues:
- [ ] After changing the quantity I have to refresh the page manually to see the correct total price.
- [ ] Subtotal prices disappeared.

![image](https://cloud.githubusercontent.com/assets/1451824/11576528/906f9e50-9a17-11e5-9725-6b38c42a74f1.png)

**Comment by patrys** [comment]
Then it's a bug in how webpack was merged. I might have missed something when splitting the pull request.
