### ISSUE TITLE
I have this question about extending saleor

### ISSUE THREAD

**Issue by ppshobi** [mirumee/saleor#4234]
### What I'm trying to achieve
…
I have this question about extending saleor. How do I add new functionalities to saleor, Imagine extending an exisitng product model, and override some relationships in it. Maybe add a new api end point. Do I fork the repo and add functionalities directly on the source files?
How about upgrading to a newest version of saleor?

mirumee/saleor#1470 I was reading this and still has no clue about how to extend saleor without touching the source of saleor itself

**Comment by korycins** [comment]
Hi, 
Unfortunately, we don't have any standard approach for upgrading a base code.  I am afraid that you will have to do normal merge/rebase of saleor's code and solve all conflicts. 
We are working on a new approach which will introduce a plugin architecture. This will grant you more flexibility, but we don't know eta for now.
