### ISSUE TITLE
All dotfiles are ignored accross the whole repository by default

### ISSUE THREAD

**Issue by LeBenLeBen** [mirumee/saleor#4235]
We recently did a setup of Saleor as a clone of the repository. We then created our own SPA for the storefront within a subdirectory at the root level. We had multiple bugs causes by both inattention and the rules present in Saleor .gitignore file.

The rule that caused issues is the one on the second line (`.*`) which ignore all dot files across the whole repository. We ended-up having our own .eslintrc.js, .env, … files being ignored resulting in bugs on the CI for example.

I've removed this rule to fix our issues but did not see any other file appearing as unstaged in Git. Now I'm wondering what is the purpose of this global blacklist especially since all dotfiles are whitelisted explicitely right after this rule in the gitignore.

To avoid others falling in the same trap, I'd ask to reconsider these rules, either by removing them or at least by prefixing them with a slash to only target the root directory. I'd be happy to submit a MR once I got your opinion on that.

**Comment by patrys** [comment]
Many tools we use locally create their own dotfiles at the root level of the repository. It's easier to whitelist the selected few files that we do want to be tracked than it is to explicitly blacklist all of the other files.

**Comment by NyanKiyoshi** [comment]
I do believe it's a bit overkill to blacklist all the dotted files, even if there is a lot of cases where we don't want them.


I still do believe we should blacklist hidden (dotted) folders as most of the time they are create by IDEs–but iirc there are some cases where we want them, e.g. Elastic Beanstalk; in that case, one can simply force-add them. That shouldn't be an issue for deploying when the tool is using `gitignore` to ignore files (even if most of the time they provided their own file that we can add as well).

**Comment by LeBenLeBen** [comment]
I like to think that editors and user-specific files should be ignored by the users themselves in their own global `.gitignore`. But I guess it's not something everyone know and having to deal with it every once in a while when people submit PRs is just wasting time.

Would you agree on prefixing all the existing rules with a slash then?

**Comment by patrys** [comment]
I have them ignored globally but I believe I'm in the minority here.
