### ISSUE TITLE
Deploying to Heroku not currently working

### ISSUE THREAD

**Issue by rogueleaderr** [mirumee/saleor#424]
Screenshot from the deploy process:

![create_a_new_app___heroku](https://cloud.githubusercontent.com/assets/1051233/11701841/e4b121aa-9e86-11e5-9947-f4cca95259d2.png)

**Comment by patrys** [comment]
It's interesting as it's a squash migration that seems to conflict with the migration that it contains.

**Comment by patrys** [comment]
Indeed it fails on Heroku but seems to work fine with a local sqlite database :open_mouth:

**Comment by patrys** [comment]
It fails locally when used with Python 3.

**Comment by patrys** [comment]
Thanks, fixed now.

**Comment by patrys** [comment]
Related ticket in Django: https://code.djangoproject.com/ticket/25906
