### ISSUE TITLE
Split API tests by feature

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4243]
In addition to #3915, I believe we should refactor the API tests by splitting them into packages that contain each feature to test into a single file.

For example, on a product we want to test:
```
          tests
            |
           api
            |
        products____________________
       /        \        \          \
  attributes  sorting  images  product_types
```

**Comment by patrys** [comment]
We wanted to move tests into the actual packages instead of having a separate `tests` folder. We can use a root-level `pytest_plugins` setting to share fixtures between packages.

**Comment by NyanKiyoshi** [comment]
Even better.
