### ISSUE TITLE
Saleor e-commerce: How to batch insert products through python code or API

### ISSUE THREAD

**Issue by ironexmaiden** [mirumee/saleor#4246]
I am trying to do some tests on saleor e-commerce cms by adding some products automatically from some cvs file through python Unfotunately I have only found some examples GraphQL API for reading the existing products from the database <<https://stackoverflow.com/questions/53435400/saleor-product-bulk-upload-script>> but I can not find nothing for add a product with GraphQL API. Any suggestions?

**Comment by korycins** [comment]
@ironexmaiden  How about mutation -`ProductCreate` (`saleor/graphql/product/mutations/products.py`)? 
```
mutation{
  productCreate(input:{attributes:[{slug:"abc",value:"1"}], category: "Q2F0ZWdvcnk6Nw==",  chargeTaxes:true, name: "A13", price: "16", productType:"UHJvZHVjdFR5cGU6MTE="}){
    errors{
      field
      message
    }
    product{
      id
      name
    }
  }
}
```

**Comment by ironexmaiden** [comment]
I have tried the mutation you proposed through postman but I took this response
`{
    "errors": [
        {
            "message": "You do not have permission to perform this action",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "productCreate"
            ],
            "extensions": {
                "exception": {
                    "code": "PermissionDenied",
                    "stacktrace ": [
                        "Traceback (most recent call last):",
                        "  File \"/usr/local/lib/python3.7/site-packages/promise/promise.py\", line 487, in _resolve_from_executor",
                        "    executor(resolve, reject)",
                        "  File \"/usr/local/lib/python3.7/site-packages/promise/promise.py\", line 754, in executor",
                        "    return resolve(f(*args, **kwargs))",
                        "  File \"/usr/local/lib/python3.7/site-packages/graphql/execution/middleware.py\", line 76, in make_it_promise",
                        "    return next(*args, **kwargs)",
                        "  File \"/app/saleor/graphql/core/mutations.py\", line 204, in mutate",
                        "    raise PermissionDenied()",
                        "graphql_jwt.exceptions.PermissionDenied: You do not have permission to perform this action"
                    ]
                }
            }
        }
    ],
    "data": {
        "productCreate": null
    }
}`

I had acquire the JWT token and include it on authorization  as bearer token but I took the same response :(

**Comment by NyanKiyoshi** [comment]
Does the user has the 'manage products' permission?

Also, make sure you pass it like this: `Authorization: JWT THEN_PUT_YOUR_TOKEN_HERE`

You can also check that by executing:
```
{
  me {
    id
    permissions {
      name
    }
  }
}
```

**Comment by ironexmaiden** [comment]
I have done this but I took syntax error
`mutation{
 
  productCreate(input:{attributes:[{slug:"abc",value:"1"}], category: "Q2F0ZWdvcnk6Nw==",  chargeTaxes:true, name: "A13", price: "16", productType:"UHJvZHVjdFR5cGU6MTE=",  Authorization: JWT "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNTYwMTk0ODI0LCJvcmlnSWF0IjoxNTYwMTk0NTI0fQ.WUuy7s_sBniFTH9j7_K8wevF48OPtcbBcLf3BFTuOfg"}){
    errors{
      field
      message
    }
    product{
      id
      name
    }
  }
}`

**Comment by NyanKiyoshi** [comment]
The `Authorization` is to pass as an HTTP header, not as a variable.

**Comment by ironexmaiden** [comment]
I passed as:
Key:Authorization
Value:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNTYwMTk0ODI0LCJvcmlnSWF0IjoxNTYwMTk0NTI0fQ.WUuy7s_sBniFTH9j7_K8wevF48OPtcbBcLf3BFTuOfg

**Comment by ironexmaiden** [comment]
Sorry you are right I have change the bearer to JWT and it seems ok! thank you

**Comment by korycins** [comment]
@ironexmaiden Can we close this issue?

**Comment by ironexmaiden** [comment]
@korycins yes but refer it to the documentation that a JWT token is needed not a bearer one

**Comment by korycins** [comment]
@ironexmaiden  I think that this is already in docs - https://docs.getsaleor.com/en/latest/architecture/graphql.html#authorization
