### ISSUE TITLE
Multi vendor support

### ISSUE THREAD

**Issue by SFlame** [mirumee/saleor#4247]
Does Saleor support multi vendor store?
Like this module for Magento:

https://marketplace.magento.com/webkul-module-marketplace.html

**Comment by Satloff** [comment]
This is something that has been discussed before, but I don't it's in the works just yet. Check out: #1251

**Comment by SFlame** [comment]
Yes, I saw some medium article that suggest it should be available on Saleor 2.0, but I don't think it really happened.

**Comment by maarcingebala** [comment]
Closing in favor of #1251, also read our update on this on Spectrum: https://spectrum.chat/saleor/general/saleor-multi-vendor-when-this-feature-will-release~5c665517-170f-45b3-94f4-ae9f7d344ac9?m=MTU2MDc1NTExMTA3MA==
