### ISSUE TITLE
Where is `order.get_status_display` method defined?

### ISSUE THREAD

**Issue by chadsaun** [mirumee/saleor#425]
Can you tell me where this method is defined?

    {{ order.get_status_display }}

**Comment by patrys** [comment]
Since `Order.status` has `choices`, Django will automatically create a method that maps the current value to a label: [Model.get_FOO_display()](https://docs.djangoproject.com/en/1.8/ref/models/instances/#django.db.models.Model.get_FOO_display).

**Comment by chadsaun** [comment]
Ah, thank you
