### ISSUE TITLE
Allow to create attributes independently from product types

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#4250]
Backend should be adjusted to allow creating attributes independently from product types. It is possible to do with the current models, but we need to change the API. 

- [x] Adjust the `attributeCreate` mutation to use the new signature:

```
attributeCreate(input: AttributeCreateInput!): AttributeCreate
```

where:

```
type AttributeCreate {
    errors: [Error!]
    attribute: Attribute
}
```

**Comment by NyanKiyoshi** [comment]
We should also add a way to retrieve a single attribute as there is currently no way to retrieve a given attribute by id.
