### ISSUE TITLE
Setting ReCaptcha_PRIVATE_KEY is not of type <class 'str'>

### ISSUE THREAD

**Issue by NileshArnaiya** [mirumee/saleor#4261]
### What I'm trying to achieve
Installing Saleor on Windows using Anaconda and virtual env
### Steps to reproduce the problem
1. python manage.py migrate

### What I expected to happen
Must have installed correctly as SECRET_KEY and DATABASE_URL is correctly set in my environment variables and DATABASE has been created in postgresql[pgadmin]

### Screenshots

![ecomm](https://user-images.githubusercontent.com/10388565/59309235-b9c7cf80-8cc0-11e9-9d0c-71e73a3f27f1.JPG)

Any help will be appreciated on how to solve this :+1: 
**System information**
Operating system: Win 7
Platform : Anaconda

**Comment by korycins** [comment]
Can you confirm that you have correct values set for: 
```
RECAPTCHA_PUBLIC_KEY 
RECAPTCHA_PRIVATE_KEY 
```

**Comment by NileshArnaiya** [comment]
Yes, I had correct values for each of them, but somehow after a restart, it seems to be working. Now I ran into a new recaptcha problem
![Capture](https://user-images.githubusercontent.com/10388565/59347643-cdac1980-8d32-11e9-9f1a-0ad3998903c1.JPG)
Any help will be really appreciated! Thanks

**Comment by korycins** [comment]
@NileshArnaiya Are you using the correct version of key?
First google results gave me these urls:
https://stackoverflow.com/questions/53108522/google-recaptcha-v3-0-not-working-error-for-site-owner-invalid-key-type
https://github.com/mirumee/saleor/issues/3798
https://github.com/mirumee/saleor/issues/3625

**Comment by NileshArnaiya** [comment]
I will deploy it to heroku or docker and see if it works there, Thanks @korycins for the help
