### ISSUE TITLE
Add a crypto-payment gateway

### ISSUE THREAD

**Issue by raptored01** [mirumee/saleor#4274]
### What I'm trying to achieve
Add crypto-payments gateways for BTC, ETH and LTC

**Comment by korycins** [comment]
Hi @raptored01 
1. Next time, please add more description of the proposed feature.  Section "proposed solution" would be also very helpful.
For now, we don't have any resources to focus on any new gateway. 
Payment module in an easy way to extend. You can add a new gateway by yourself without modifying saleor's base code. 
Also, any PRs with new payment-gateway are welcome.

**Comment by timothymugayi** [comment]
@biagiodistefano am working on this

**Comment by ablazleon** [comment]
This feature seems useful. . .It will allow clients to save the 30 cents and the other percentage fee per transaction of Stripe and Braintree and avoid the business' fear of a great amount of chargeback fees. How is it feature going? Can I help in anyway? I don't know so much about blockchain, but this semester I'm having a subject about blockchain in my university. In which payment gateway are you thinking about?

**Comment by chrishp** [comment]
Any updates on this?

**Comment by TileThePlane** [comment]
Would like to see this cryptocurrency payments featured as it doesn't seem to be possible with any of the available payment integrations. Are there any plugins for extending payment gateways to do this?

**Comment by SHHSSH** [comment]
As a new observer, I am inquiring if there are any functional applications utilising crypto as a POS through Saleor?
