### ISSUE TITLE
Cannot set an image to a Product

### ISSUE THREAD

**Issue by ironexmaiden** [mirumee/saleor#4276]
Hello Guys I am trying to add an Image to a product I have just added to database through graphql 

 I am applying a succesfull productCreate mutatio and I store the id so I try to apply the second mutation to add the image
`
  mutation{
        productImageCreate(input:{product: "UHJvZHVjdDoxMg==", image: "https://kritsimis.gr/image/cache/catalog/Gouria2019/BI033-540x810.jpg"}){
        errors{
            field
            message
        }
        product{
            id
            name
        }
    }
}
`

So I took the following error:
b'{"errors": [{"message": "\'NoneType\' object has no attribute \'content_type\'", "locations": [{"line": 3, "column": 9}], "path": ["productImageCreate"], "extensions": {"exception": {"code": "AttributeError", "stacktrace ": ["Traceback (most recent call last):", "  File \\"/app/.heroku/python/lib/python3.7/site-packages/promise/promise.py\\", line 487, in _resolve_from_executor", "    executor(resolve, reject)", "  File \\"/app/.heroku/python/lib/python3.7/site-packages/promise/promise.py\\", line 754, in executor", "    return resolve(f(*args, **kwargs))", "  File \\"/app/.heroku/python/lib/python3.7/site-packages/graphql/execution/middleware.py\\", line 75, in make_it_promise", "    return next(*args, **kwargs)", "  File \\"./saleor/graphql/core/mutations.py\\", line 207, in mutate", "    response = cls.perform_mutation(root, info, **data)", "  File \\"./saleor/graphql/product/mutations/products.py\\", line 753, in perform_mutation", "    validate_image_file(image_data, \\"image\\")", "  File \\"./saleor/graphql/core/utils.py\\", line 29, in validate_image_file", "    if not file.content_type.startswith(\\"image/\\"):", "AttributeError: \'NoneType\' object has no attribute \'content_type\'"]}}}], "data": {"productImageCreate": null}}'

**Comment by maarcingebala** [comment]
`productImageCreate` expects an `Upload` type for an image, not a URL, and a multipart request compliant with this specification: https://github.com/jaydenseric/graphql-multipart-request-spec.
I don't know what GraphQL client you use, but e.g. Playground or GraphiQL don't support testing multipart requests. We have locally used [Insomnia](https://insomnia.rest/) client to test upload mutations. You can also inspect our Python tests to see how we construct the request, especially `test_product_image_create_mutation` and `get_multipart_request_body` function.

**Comment by ironexmaiden** [comment]
@maarcingebala thank you for your answer, I am using a python script through requests library. I was suspecting of something like this you are referring to, but I didn't apply. So, you are advising me to download the image through requests.get and set this image absolute path to upload it?

**Comment by MasterKeits** [comment]
@maarcingebala @ironexmaiden I'm also trying to figure out how to upload images via curl or with python script. Could you please provide an example?

**Comment by maarcingebala** [comment]
Please see this example: https://github.com/jaydenseric/graphql-multipart-request-spec#curl-request

**Comment by ironexmaiden** [comment]
> @maarcingebala @ironexmaiden I'm also trying to figure out how to upload images via curl or with python script. Could you please provide an example?

You have to create a folder called media inside your main project folder in there you must save the images and use the relative path to save it the database of ProductImages Tables

**Comment by MasterKeits** [comment]
@maarcingebala I have spent countless hours to get this working and I have studied graphql-multipart-request-spec#curl-request but I still get 400. Tried using built in methods but still nothing.

@ironexmaiden You are telling me that you didn't get it working either and found a workaround to save them directly via model?

**Comment by MasterKeits** [comment]
{'operations': '{"query": "\\n\\tmutation createProductImage($image: Upload!, $product: ID!) {\\n\\t\\tproductImageCreate(input: {image: $image, product: $product}) {\\n\\t\\t\\timage {\\n\\t\\t\\t\\tid\\n\\t\\t\\t}\\n\\t\\t}\\n\\t}\\n\\t", "variables": {"product": "UHJvZHVjdDo3Mw==", "image": "picture"}}', 'map': '{"picture": ["variables.file"]}', 'picture': <SimpleUploadedFile: picture.jpg (image/png)>}
Token Verify {'data': {'tokenVerify': {'payload': {'email': 'admin@example.com', 'exp': 1564132716, 'origIat': 1564132416}}}}

**Comment by tboulogne** [comment]
hello

Same hear. A working example into documentation could worth it :-).
Could not add image to product even after exploring tests suite ;-(

**Comment by tboulogne** [comment]
Get it works simply with a python graphql client : https://github.com/saltastro/graphql_requests

**Comment by amitosh1995** [comment]
I am also stuck at the same issue even at local development that i am unable to upload product images from dashboard.

**Comment by heiko-r** [comment]
After way too much effort, I came up with this basic example using python requests, in the hope that it helps:

```python
r = requests.post(
    endpoint,
    headers={'Authorization': f"JWT {token}"},
    data={
        'operations': json.dumps({
            "query": """
                mutation createProductMedia(
                    $product: ID!
                    $image: Upload
                ) {
                    productMediaCreate(
                        input: {
                            product: $product
                            image: $image
                        }
                    ) {
                        media {
                            id
                        }
                        errors {
                            field
                            message
                        }
                    }
                }
                """,
            'variables': {'product': product_id, 'image': None}
        }),
        'map': json.dumps({
            '0': ["variables.image"]
        })
    },
    files={'0': (filename, image, content_type)}
)
```

`filename` is simply a String and `image` should be the file content. `content_type` should be `"image/png"` or whatever the type of your file.
