### ISSUE TITLE
Publish on product date picker inconsistent

### ISSUE THREAD

**Issue by Akbarkz** [mirumee/saleor#4278]
### What I'm trying to achieve
Open date picker when clicking publish on date picker field

### Steps to reproduce the problem
1. Click publish on date (optional) field

### What I expected to happen
Open date picker. But its inconsistent. Opens only when clicking just below publish label

### Screenshots
![chrome-capture](https://user-images.githubusercontent.com/13500078/59405693-2def9980-8dcd-11e9-9b84-ee44cdc8cd5b.gif)

**System information**
Operating system: Ubbuntu 18.04
Browser: Chrome 75.0.3770.80 (Official Build) (64-bit)

**Comment by NyanKiyoshi** [comment]
This is a regression from google chrome–but might not get fixed by Google. This was fixed in a newer release of materialcss. More information here #3865.
