### ISSUE TITLE
No ./node-modules/.bin/

### ISSUE THREAD

**Issue by boopr** [mirumee/saleor#428]
Hello,
I'm a new saleor user and I'm trying to install it. The wiki is really poor...

In the section `Prepare assets:`, it tells to do :
```
$ ./node_modules/.bin/grunt
```
But it gives me the following error :
```
bash: ./node_modules/.bin/grunt: Aucun fichier ou dossier de ce type
(No file or folder)
```
And it's true, there is no `.bin` in the `node_modules` folder...

How can I fix it?  
Thanks for your help and merry christmas :santa: !

**Comment by patrys** [comment]
Did you complete `npm install` without errors?

**Comment by boopr** [comment]
I got soem warnings :
```
npm WARN unmet dependency /home/louis/Documents/saleor/node_modules/grunt-contrib-less requires less@'^1.7.2' but will load
npm WARN unmet dependency /home/louis/Documents/saleor/node_modules/less,
npm WARN unmet dependency which is version 2.5.3
materialize-sass-origin@0.97.0 node_modules/materialize-sass-origin
```

**Comment by vinamelody** [comment]
Check the package.json version using this https://github.com/tjunnone/npm-check-updates
I was able to pass through installation after doing `ncu -u` however I'm also not sure if anything breaks due to version bumps..

**Comment by pcompassion** [comment]
I had errors, because some of dependencies won't work with python3 during `npm install` and I solved it with `npm install --python=/usr/bin/python2.7'  

You may have to delete the `node_modules` dir before you try this.
