### ISSUE TITLE
Add mutation to allow authenticated user to change password

### ISSUE THREAD

**Issue by mateuszkula** [mirumee/saleor#4287]
### What I'm trying to achieve
~~I would like to use setPassword mutation for changing users password but I need one time token and there is no query right now for obtaining it.~~

~~setPassword mutation receives:
    token String! - A one-time token required to set the password
    password String! - Password~~

There is need for new mutation that will allow change of password for authenticated user that will take only new password.

**Comment by maarcingebala** [comment]
@mateuszkula Operations like password reset require email confirmation. Flow to obtain the token in that case would be as follows:
- users request an action (e.g. password reset, email change etc),
- the server sends an email with a link containing an expirable token,
- when users click the link they're redirected to a "password reset" view in the storefront that takes the token from URL and passes it to the mutation.

**Comment by mateuszkula** [comment]
@maarcingebala I agree that such flow for password reset and email change is reasonable  but what if I am logged in and I want to change password? Changing password by email sounds a little bit inconvinient for the end user. Right now in the storefront desing for password change user is required to use current password + new password typed twice. I checked it on few sites and it looks like a popular pattern(current pass + 2x new password). Maybe we need a new mutation for that particular case. What do you think?

**Comment by maarcingebala** [comment]
You're right, I was thinking about resetting the password when user forgot it. In a case when you're authenticated and you just want to change your password we don't need any emails. @fowczarek will work on a mutation for that.

**Comment by mateuszkula** [comment]
👍

**Comment by maarcingebala** [comment]
Also, we won't need any tokens here, we just need a mutation that takes the new password in the input.

**Comment by mateuszkula** [comment]
Changed description and title of issue.

**Comment by mateuszkula** [comment]
P.S.

We should also take current password in mutations input - what if I forgot to logout from public computer? Someone could change my password easily. This is justa bit of extra security.

**Comment by maarcingebala** [comment]
We'll need to merge #4510 first to unify account mutations. Then the signature for this one should be something like:

```
accountPasswordChange(oldPassword: String!, newPassword: String!): AccountPasswordChange

type AccountPasswordChange {
  errors: [Error!]
  user: User
}
```
