### ISSUE TITLE
is_success: bool Syntax Error on interface.py file 

### ISSUE THREAD

**Issue by sandeepl337** [mirumee/saleor#4296]
### What I'm trying to achieve
When I was trying to install the application using the `python3 manage.py migrate`

### Steps to reproduce the problem
You can find the screenshot below
![Snip20190615_3](https://user-images.githubusercontent.com/1310974/59550732-da777a00-8f8b-11e9-8d91-c2d7314f7851.png)

**System information**
Operating system: Deb 9

**Comment by NyanKiyoshi** [comment]
Hi!

Python 3.5 support was dropped. You need to upgrade to 3.6 or higher.

**Comment by sandeepl337** [comment]
Okay, thanks let me check.
