### ISSUE TITLE
VAT country taxes not available ?

### ISSUE THREAD

**Issue by mthnglac** [mirumee/saleor#4298]
I can not get the Turkey on the tax rate. I've been a member of **VatLayer**, but **VatLayer.com** doesn't have tax rates for my country and even takes my money during the development process. Is there another way to solve this situation, another option?

**Comment by Pacu2** [comment]
You can create VAT & TaxRates manually for all taxes you need, take a look at https://github.com/mirumee/django-prices-vatlayer which is used for handling taxes in Saleor

**Comment by mthnglac** [comment]
I don't know exactly how to do it.  VAT Customer service said:
"Unfortunately, our API only supports European Union countries. " 🤷🏻‍♂️

**Comment by NyanKiyoshi** [comment]
@mthnglac yes, only European countries are supported by VAT Layer.

You can do something like this inside Django:
```python
from django_prices_vatlayer.models import VAT

data = {"country_name":"Turkey","standard_rate":20,"reduced_rates":{"foodstuffs":10,"books":10,"pharmaceuticals":10}}

VAT.objects.update_or_create(
    country_code=country_code, defaults={'data': data})
```

Just remove the unneeded rates and change the standard rate to the Turkey's.

Here are the available reduced rates available (you most likely need none, so you can just do `data = {"country_name":"Turkey","standard_rate":20,"reduced_rates":{}`):

0 | "accommodation"
-- | --
1 | "admission to cultural events"
2 | "admission to entertainment events"
3 | "admission to sporting events"
4 | "advertising"
5 | "agricultural supplies"
6 | "baby foodstuffs"
7 | "bikes"
8 | "books"
9 | "childrens clothing"
10 | "domestic fuel"
11 | "domestic services"
12 | "e-books"
13 | "foodstuffs"
14 | "hotels"
15 | "medical"
16 | "newspapers"
17 | "passenger transport"
18 | "pharmaceuticals"
19 | "property renovations"
20 | "restaurants"
21 | "social housing"
22 | "water"
23 | "wine"


We are planning to add the options to allow storefront owners to add custom tax rates per country and type. But it won't happen yet (#2436).

**Comment by holyspice** [comment]
this doesn't enable the option to change taxes on a product type also it doesnt apply the standard tax rate defined

**Comment by mthnglac** [comment]
> @mthnglac yes, only European countries are supported by VAT Layer.
> 
> You can do something like this inside Django (I believe you can run this inside the django shell: `./manage.py shell`):
> 
> ```python
> from django_prices_vatlayer.models import VAT
> 
> data = {"country_name":"Turkey","standard_rate":20,"reduced_rates":{"foodstuffs":10,"books":10,"pharmaceuticals":10}}
> 
> VAT.objects.update_or_create(
>     country_code=country_code, defaults={'data': data})
> ```
> 
> Just remove the unneeded rates and change the standard rate to the Turkey's.
> 
> Here are the available reduced rates available (you most likely need none, so you can just do `data = {"country_name":"Turkey","standard_rate":20,"reduced_rates":{}`):
> 0 	"accommodation"
> 1 	"admission to cultural events"
> 2 	"admission to entertainment events"
> 3 	"admission to sporting events"
> 4 	"advertising"
> 5 	"agricultural supplies"
> 6 	"baby foodstuffs"
> 7 	"bikes"
> 8 	"books"
> 9 	"childrens clothing"
> 10 	"domestic fuel"
> 11 	"domestic services"
> 12 	"e-books"
> 13 	"foodstuffs"
> 14 	"hotels"
> 15 	"medical"
> 16 	"newspapers"
> 17 	"passenger transport"
> 18 	"pharmaceuticals"
> 19 	"property renovations"
> 20 	"restaurants"
> 21 	"social housing"
> 22 	"water"
> 23 	"wine"
> 
> We are planning to add the options to allow storefront owners to add custom tax rates per country and type. But it won't happen yet (#2436).

that worked, thanks a lot.
