### ISSUE TITLE
Refactor JSONB model fields to JSON

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4303]
On average, JSONB takes 0.15ms more than JSON to update and insert on a table because of internal indexing–which we don't use as we never filter this field. This is not a big issue unless bulk updating, so we still should change that.

This doesn't require any casting as the two types are compatible, so we simply need to change the type of the column, no further work should be needed.

The main issue of this, is that Django doesn't have a JSON PostgreSQL field (JSONField being actually a JSONB field, which is very misleading). So we will need to look if there is a library with this custom type or otherwise, make our own library–which might be cleaner than putting our custom type into the core package–but of course it's harder to maintain when we have a lot of packages.

**Comment by dominik-zeglen** [comment]
Is it really an issue?
I mean, even if you'd want to update 1000 descriptions in one shot ( is this even a valid case? ), it'd take ~150ms, which really fast anyway.

**Comment by NyanKiyoshi** [comment]
This is still 150ms where the Postgres instance could be doing something else. If we can use a faster field that use less CPU times and uses less db storage (JSONB indexes) without efforts, that's really nice to take.

This is why this issue is in backlog, it's not a big issue, but it would be good to get closed.

**Comment by maarcingebala** [comment]
Soon we'll be working tools to migrate to Saleor from other platforms and having to insert large datasets into Saleor might be a case.
