### ISSUE TITLE
need more info and modification support 

### ISSUE THREAD

**Issue by afhaider** [mirumee/saleor#4309]
or rel=unfollow is enough  for it?

**Comment by NyanKiyoshi** [comment]
Hi, you should provide your own `robots.txt` rules. But search engines would not index your dashboard anyway as they would get redirected to the logic page.

**Comment by afhaider** [comment]
do we need to add manually robot.txt file and make a url pattern with views.py 
or saleor provide  any auto feature for it?

**Comment by NyanKiyoshi** [comment]
It's a static file, this shouldn't be handled by django (you can if you want). I would personally recommend to add a rule in your web server (nginx, apache, ...), whether with a hard-coded response or redirecting to a static file.

I'm a bit lazy from time to time, that's what I do for example in ngnix:
```nginx
    location = /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }
```

But that's the solution for nginx. If you are using Apache, you can look it up on the Internet. Here is an example I found:
```apache
Alias /robots.txt /var/www/robots.txt
```

**Comment by afhaider** [comment]
thnx alot again bro =-=

**Comment by afhaider** [comment]
//saleor-core-views.py
from compression_middleware.decorators import compress_page

@compress_page
def home(request):
    products = products_for_homepage(
        request.user,
        request.site.settings.homepage_collection)[:8]
    products = list(products_with_availability(
        products, discounts=request.discounts, taxes=request.taxes,
        local_currency=request.currency))
    webpage_schema = get_webpage_schema(request)
    return TemplateResponse(
        request, 'home.html', {
            'parent': None,
            'products': products,
            'webpage_schema': json.dumps(webpage_schema)})

//in setting.py-middlware
'compression_middleware.middleware.CompressionMiddleware',

pipenv install django-compression-middleware
pip3 install --upgrade django-compression-middleware
pip freeze > requirements.txt

**Comment by afhaider** [comment]
{seo improved}
after so much research i make gzip work with more secuirty then normal gzip
i gave u this idea plz help me to modify it by applying django-htmlmin

//in setting.py
'htmlmin.middleware.HtmlMinifyMiddleware',
'htmlmin.middleware.MarkRequestMiddleware',

HTML_MINIFY = True
it doesnt let me add markrequest i mean they opposing each other

**Comment by NyanKiyoshi** [comment]
Hi,

It is no django's job to do that. It's the web server's job. You can do gzip compressions through nginx and there are plugins, like PageSpeed by Google.

Minifying the HTML doesn't save much. It will most-likely just waste CPU cycles where your workers could have done something else.

If you really want to minify the HTML, you should look for a template preprocessing plugin.

**Comment by afhaider** [comment]
between i need learn nginx first i want to know how u make ur server reactjs npm module and django possible to work 
can u teach me how react and django integrated app can be selfhosted in nginx is their any documentation u have cause i want to make more reactjs and django website  and want to host ownself

**Comment by afhaider** [comment]
right now i using heroku and ur concept based on nginx so i am bit excited to learn earliest as possible

**Comment by afhaider** [comment]
@compress_page
between this decorator trick i able to achieve certain amount of gzip seo score 
xD yah u absolute write it server job
