### ISSUE TITLE
Add filtering and sorting to the attributes query

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#4312]
Extend the `attributes` top-level query to support filtering and sorting similarly as other top-level queries (e.g. `filter` and `sortBy` in the `products` query).

Filters:
- search by attribute code or label
- is value required (boolean)
- is visible on the storefront (boolean)
- is used in the faceted search (boolean)
- is filterable in the dashboard (boolean)

The same fields should be available as sorting options.

**Comment by NyanKiyoshi** [comment]
> is visible on the storefront (boolean)

This would be only used by the staff users, right? The customers should not be able to query non-visible attributes.
