### ISSUE TITLE
Allow passing `country` and `currency` to `Product.pricing` and `ProductVariant.pricing`

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#4315]
### What I'm trying to achieve
We need to allow people to explicitly switch countries and have the correct prices displayed.

Current implementation relies on `request.country` but when using the GraphQL API it's always set to whatever GeoIP returned.

### Describe a proposed solution
Currently, the API looks like this:

```graphql
type Product {
  pricing: ProductPricingInfo
}

type ProductVariant {
  pricing: VariantPricingInfo
}

type ProductPricingInfo {
  available: Boolean
    @deprecated(
      reason: "This has been moved to the parent type as 'is_available'."
    )
  onSale: Boolean
  discount: TaxedMoney
  discountLocalCurrency: TaxedMoney
  priceRange: TaxedMoneyRange
  priceRangeUndiscounted: TaxedMoneyRange
  priceRangeLocalCurrency: TaxedMoneyRange
}

type VariantPricingInfo {
  available: Boolean
    @deprecated(
      reason: "This has been moved to the parent type as 'is_available'."
    )
  onSale: Boolean
  discount: TaxedMoney
  discountLocalCurrency: TaxedMoney
  price: TaxedMoney
  priceUndiscounted: TaxedMoney
  priceLocalCurrency: TaxedMoney
}

type TaxedMoney {
  currency: String!
  gross: Money!
  net: Money!
  tax: Money!
}

type Money {
  currency: String!
  amount: Float!
  localized: String!
}
```

I propose that we allow `country` and `currency` to be passed explicitly and that we drop the `Money.localized` field:

```graphql
type Product {
  pricing(country: CountryCode, currency: String): ProductPricingInfo
}

type ProductVariant {
  pricing(country: CountryCode, currency: String): VariantPricingInfo
}

type Money {
  currency: String!
  amount: Float!
}
```

If a value is not given, use the store's default country or currency (instead of falling back to GeoIP).

If a currency is given, return values in that currency (using the currency exchange rates) or return `null` if unable to do so.

If a country is given, calculate taxes according to that country's tax regulations.

**Comment by krzysztofwolski** [comment]
Will it affect product filtering? How to filter products by price without knowing taxes?

**Comment by maarcingebala** [comment]
Queries are one thing; the other is that we need to know the country in checkout mutations that check the stock quantity so that we can pick the right warehouse. We need to get rid of usages of `request.country` (or `info.context.country` in API) and instead have a country code explicitly provided by the user.

Also, we currently use countries to determine a warehouse, but I think we want to have better granularity and e.g. allow to define warehouses per state (that would be the use case in the US). Does it also affect pricing queries @patrys?
