### ISSUE TITLE
Product.availability and ProductVariant.availability have incorrect deprecation message

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#4320]
The message tells the user to use `is_available` on the parent type but the actual name is `isAvailable` as GraphQL uses camel case.

**Comment by MatthewBosek** [comment]
Hello, can I help out on this ticket?

**Comment by maarcingebala** [comment]
@MatthewBosek Sure, feel free to pick it up! AFAIK nobody in our team is working on that.

**Comment by MatthewBosek** [comment]
@maarcingebala Excellent! I will get on it in the evening when I return from work.

**Comment by MatthewBosek** [comment]
@maarcingebala I keep receiving this error when setting up the db:
raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

I have gone into the settings.py file and set a value to the SECRET_KEY.  How should I proceed? Thanks,

**Comment by maarcingebala** [comment]
Fixed in #4707
