### ISSUE TITLE
UI for managing landing pages (discussion)

### ISSUE THREAD

**Issue by wulaaf** [mirumee/saleor#4322]
### What I'm trying to achieve
A WordPress/Wagtail like workflow where I can easily change landing pages without having to write code every time in order to make changes to the existing site.

### Describe a proposed solution
As Saleor itself uses React, we can build a simple interface for managing landing pages and a few default layouts which include something like a hero, a hero+featured products or hero+featured products+popular products, so on and so forth. It would be nice to build this into modular chunks of code, similar to how Wagtail's StreamFields work. It doesn't necessarily have to be in React, it could very well be something else as well.

### Other solutions I've tried and won't work
There are a few articles that cover integrating Wagtail with Saleor but I haven't had any luck incorporating those into my project successfully. I believe the core team might be focused on more important things right now but I figured lets start a discussion about this and see how everyone who is using Saleor in production is tackling frequent changes to the landing pages.

So how exactly are you managing dynamic content that changes on a daily or weekly basis for your Saleor store? I'd love to hear more about your workflows.

**Comment by biomassives** [comment]
im interested in working on what i think is a 'landing page' . We are implementing a food hub system with Saleor and allowing users to manage collections they 'own' only and have a report and updates via email about sales or inquiry of items in that collection.. What you are asking for sounds like a way to extend templates for thins like 'categories or collections' but I am not sure.  Reading up on Wagtail, i see you are talking about something that generally is done in django with the extended users feature, https://www.accordbox.com/blog/how-build-landing-page-using-wagtail-cms/

**Comment by maarcingebala** [comment]
We had a discussion about this. While there are some CMS-like features like pages or navigation management, we decided that Saleor responsibility should be only the ecommerce part (so product, checkout, order processing etc.) while CMS features should be handled by dedicated tools (Contentful, GraphCMS, etc.)

**Comment by williamyorkl** [comment]
hi there, I think @mabdullahabid ‘s point is something like low-code UI editor for storefront website,,, system like Contentful, GraphCMS is just simply system manage “text” content, not for Ecommerce, but a low-code UI editor for storefront can change and manage the UI interface without code.... seems like have to build on oneself~
