### ISSUE TITLE
[bug] ModuleNotFoundError: No module named 'saleor.settings'

### ISSUE THREAD

**Issue by ducdk** [mirumee/saleor#4323]
### What I'm trying to achieve
… ModuleNotFoundError: No module named 'saleor.settings'

### Steps to reproduce the problem
1.  Build docker local
2. Save image 
3. Load on server
4. Run by docker-compose

### What I expected to happen
… Docker run error 
I exec in docker error importModule 'saleor.settings'

### Screenshots

![image](https://user-images.githubusercontent.com/20499340/59788788-b05ce980-92f6-11e9-8c2f-83efc7b08f8b.png)

**System information**
Operating system: 
Browser: chrome

**Comment by korycins** [comment]
Hi @ducdk 
Did you use our docker-compose file to create a saleor image? I've just created saleor image without any problems.
Another hint - You can try to overwrite env variable `DJANGO_SETTINGS_MODULE` to provide the path to the settings file.

**Comment by MsMansiDhruv** [comment]
Hey, I landed on the same issue. I created saleor image via docker-compose. Didn't you face the same bug?

**Comment by chiennguyen196** [comment]
@MsMansiDhruv I found out that cause in the docker-compose file overrided some folders in docker container with current project folder. The docker-compose.yml seems like just for developers and cannot run alone. You must to modify it to run in product environment.
