### ISSUE TITLE
Saleor on MS SQL

### ISSUE THREAD

**Issue by turtlepile** [mirumee/saleor#4326]
Hello everyone, 
First of all, we love Saleor, thank you so much, great work! 
Here's my issue:
We have a back-office system, developed by our team in **.net/c#** which runs on **MS SQL database (2017)**
And we want to use saleor as our e-commerce storefront.
We have some intersects like, customer table, accounts, products, purchase etc. 
 I was wondering, if someone must've faced same issue before?
What is the best road you suggest us?
How should i manage to synchronize my system & saleor database at the same time?

**Comment by patrys** [comment]
Good question, we usually solve situations like this by introducing explicit synchronization points between systems. Ideally a bridge would be an external application that uses APIs of both systems but until #3343 lands it may be easier to add such a script directly to Saleor's codebase and run it as a Celery beat task.

**Comment by turtlepile** [comment]
Thank you for the reply. Yeah, apparently that sounds like an option.

I really think, Saleor is an outstanding application. It would be amazing if it also run on Mssql.
