### ISSUE TITLE
Provide links to subcategories when viewing category

### ISSUE THREAD

**Issue by ssjhayes** [mirumee/saleor#4328]
I'd like to provide link to child subcategories when viewing a category.

Gaskets
--Automotive <- provide links to direct children in this view
----Domestic (link)
------Cylinder Head Gasket
------Exhaust Gasket
----Import (link)
------Cylinder Head Gasket
------Turbocharger Gasket

So when I am viewing the "automotive" category, I'd like to navigate to the child categories (Domestic, Import) without needing to go through the main menu dropdown again.

The part below is currently in the "Cylinder Head Gasket" category of "Domestic", I like how they show up in parent categories, but would like to be able to dial down into the subcategories easier than going through the menu again.

![image](https://user-images.githubusercontent.com/52075400/59926762-fb672180-9408-11e9-9064-62595ee1af52.png)

**Comment by ssjhayes** [comment]
So it seems this was already possibly a thing with the templates/product/_filters.html and templates/category/filters.html as the latter extends the former. I just had to add the title_tree block to products/_filters.html and modify some formatting in category/filters.html. Odd how category/filters.html claims to extend product/_filters.html but they aren't inherently linked out of the box.

**Comment by NyanKiyoshi** [comment]
It's the intended behavior 👍
