### ISSUE TITLE
NPM Install Fails on Ubuntu 18.04 - ENOENT: no such file or directory, rename /node_modules/@babel/.plugin-syntax-jsx.DELETE/node_modules/@babel

### ISSUE THREAD

**Issue by bmoe872** [mirumee/saleor#4333]
### What I'm trying to achieve
I'm following the installation instructions in the documentation. When I get to `npm install` it fails every time with this error:
```
npm ERR! path /vagrant/node_modules/@babel/.plugin-transform-react-display-name.DELETE/node_modules/@babel
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/vagrant/node_modules/@babel/.plugin-transform-react-display-name.DELETE/node_modules/@babel' -> '/vagrant/node_modules/@babel/plugin-transform-react-display-name/node_modules/@babel'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2019-06-22T22_47_41_028Z-debug.log
```

### Steps to reproduce the problem
1. Fresh install of Ubuntu 18.04 (I'm using vagrant with the bento/ubuntu-18.04 box, and VMware) 
2. Install all dependencies according to the docs including an up to date version of Node
3. run `npm install` and the error happens.

Node Version: 
v10.16.0

npm version:
6.9.0

I've already tried:
1) Deleting my node_modules and rerunning `npm install`
2) Using yarn to install (This successfully installs all the packages, but then trying to build the assets is failing. I also read yarn is not supported, so I don't think this is a good route anyways)
3) Using a different vagrant box generic/ubuntu1804
4) running `sudo npm install -g npm` (I had read in a different thread this can shake things loose, but it didn't work for me)

### What I expected to happen
Installing the npm packages

**System information**
Operating system: Ubuntu 18.04 (Virtualized through VMWare and Vagrant)
Browser: Chrome
Node: 10.16.0
Npm: 6.9.0

**Comment by kobayaba** [comment]
hi I have the same problem

**Comment by dominik-zeglen** [comment]
Please check that your machines have access to at least 2GB of ram (try adding even more if still wouldn't work) - our experiences show that this is the cause of almost all issues related to asset building.

**Comment by bmoe872** [comment]
I'm having an issue installing the npm packages, not building them.

My virtualized machine has 4GB of ram given to it.

**Comment by NyanKiyoshi** [comment]
This is not a memory issue. It is trying to rename a file that does not exist.

**Comment by bmoe872** [comment]
I don't think its a memory issue either. I just upped my box's memory to 5GB just to make sure, and I'm still getting the same issue.

**Comment by dominik-zeglen** [comment]
That's unusual. Can you post the log?

**Comment by bmoe872** [comment]
Here is the NPM Debug log that gets spit out after install. 

[2019-06-24T14_32_02_986Z-debug.log](https://github.com/mirumee/saleor/files/3322239/2019-06-24T14_32_02_986Z-debug.log)

**Comment by dominik-zeglen** [comment]
I have no idea. Can't reproduce it, logs do not mention anything why does it try to rename this file. Weird.

**Comment by bmoe872** [comment]
@dominik-zeglen are you using vagrant to try and reproduce? 

I've confirmed on multiple machines now that this problem persists.

**Comment by dominik-zeglen** [comment]
Just ubuntu 18.04, as I'm not familiar with using vagrant. I'll check it out later, but I don't see any reason why it would cause this. Did you try to build it outside vagrant?

**Comment by bmoe872** [comment]
I have not yet, as that is my desired workflow. I can try that tonight though just to see if somehow the virtualization is causing the issue. I'll report back later and see. 

Also just another quick-note. In a quick attempt to get it moving I tried:
`npm install --save-dev @babel/plugin-syntax-jsx`

And now it gets past not being able to remove that file, but now it looks like it halts at `@babel/plugin-transform-react-display-name`

**Comment by NyanKiyoshi** [comment]
Can you give us the output of the `mount` command?

**Comment by bmoe872** [comment]
@NyanKiyoshi here it is:
```
vagrant@ubuntu1804:/vagrant$ mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=1988744k,nr_inodes=497186,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=403968k,mode=755)
/dev/sda3 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14147)
mqueue on /dev/mqueue type mqueue (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
configfs on /sys/kernel/config type configfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /boot type ext4 (rw,relatime,data=ordered)
lxcfs on /var/lib/lxcfs type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=403964k,mode=700,uid=1000,gid=1000)
vmhgfs-fuse on /mnt/vagrant-mounts/1000-1000 type fuse.vmhgfs-fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
vmhgfs-fuse on /vagrant type fuse.vmhgfs-fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
```

**Comment by NyanKiyoshi** [comment]
Can you try building saleor in `/tmp` if you have enough RAM for it? (might want to give more RAM, like at least 2 GB). I think the issue is that you are building on a shared file system (vmhgfs-fuse) it might fail to handle a few things. Running the installation into `/tmp` will run into tmpfs, thus the RAM which shouldn't have side effects.

**Comment by bmoe872** [comment]
Hmm, even if I can build on `/tmp` that's not going to be a good solution for how I was hoping to use saleor. 

Surprised that, that would be the problem. I've run plenty of other Django Projects with npm using this same setup and no problems.

**Comment by bmoe872** [comment]
Is there anything on the forefront to support `yarn`?

I can install all the npm packages with yarn, without any problems, but the `build-assets` step then fails.

**Comment by NyanKiyoshi** [comment]
> Hmm, even if I can build on /tmp that's not going to be a good solution for how I was hoping to use saleor.

The idea is not to use saleor in production from the RAM. The idea is to look if the issue is the file system.

**Comment by bmoe872** [comment]
@NyanKiyoshi my apologies for misunderstanding what you were getting at.

So installing and building from `/tmp` does appear to have worked, let me know if you need any output from the install.

**Comment by NyanKiyoshi** [comment]
So the issue is caused by the filesystem at `/vagrant`, do you really need to use a shared filesystem? You could use a ext4 filesystem in your VM instance and maybe creating a link in `/vagrant` to you saleor project would allow you to access your files from your PC or whatever you are using the shared filesystem for? Note that your home and `/` are in ext4.

By googling I found someone that had the same idea: https://github.com/Hashnode/mern-starter/issues/185#issuecomment-238080329

I also found someone that said it was their antivirus (malwarebyte in their case) that was deleting files before `npm` was able to process them. You could also check if any of your antivirus(es) have deleted or quarantined files–the easiest might be to disable any protection and see if that works on `/vagrant`.

But I never heard anyone having issues with their antivirus for installing the dependencies, so I would be doubtful. But that's always good to give it a try.

**Comment by bmoe872** [comment]
Hmm thats a bummer, but makes sense. I can give that a go since now we know it's the shared filesystem causing all the problems. 

The `node_modules` folder does not need to live on the shared filesystem. Thanks for your help on this!
