### ISSUE TITLE
Default Dashboard 1.0 window panel is not clickable after upgrading to version 2.7

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor#4334]
### What I'm trying to achieve
…
After updating to version 2.7, 
1. the default dashboard is not clickable.
Example: When i click on the particular product, It does not work 
2. The left panel of the saleor default dashboard is not properly view as the screen shot below.
I try to fix all the npm dependencies issue but I don't know what lead to the problem like this.
### Screenshots
![Capture](https://user-images.githubusercontent.com/40449637/59974566-d8d73300-95d7-11e9-99f7-c9d6fedc299d.PNG)

**Comment by NyanKiyoshi** [comment]
@yinmazatinKIT did you recompile the assets?

**Comment by yinmazatinKIT** [comment]
@NyanKiyoshi Yes, i did.

**Comment by NyanKiyoshi** [comment]
Try doing a hard refresh in the dashboard from your web browser (CTRL+SHIFT+R).

**Comment by yinmazatinKIT** [comment]
I have tried but it doesn't work however i clear all the browser cache. Hopefully we can find the solution

**Comment by NyanKiyoshi** [comment]
Alright. Can you show us the inspector's network tab? Open it, then reload the dashboard.

Did you do any edit to saleor? You did not manually upgraded dependencies or deleted any files?

**Comment by zatin009** [comment]
![Capture](https://user-images.githubusercontent.com/40449637/59990754-9ca2e180-966e-11e9-9b24-7a55ff9980d6.PNG)

**Comment by zatin009** [comment]
I did not edit any a single file yet in saleor my fri. & Even did not manually upgraded dependencies.

**Comment by zatin009** [comment]
But I noticed that Every time I run the command " npm run build-assets " for more than 1 times it leads to the problem like this. it take me the whole night to find the solution for this issue but still not yet find

**Comment by zatin009** [comment]
& for the server log everything is working fine when I interacted with left panel button in the dashboard, But if I tried to click anything in the window dashboard panel the server log not load anything.
![Capture](https://user-images.githubusercontent.com/40449637/59991390-6581ff80-9671-11e9-8219-2f15993cd4f0.PNG)

**Comment by NyanKiyoshi** [comment]
What browser are you using? And what version?

**Comment by zatin009** [comment]
I use Google chrome which is the latest version.

**Comment by NyanKiyoshi** [comment]
Okay. There is no such problems for me... Can you try on a clean clone of saleor?

**Comment by zatin009** [comment]
Howdy, So what do mean buy " try on a clean clone of saleor " ?

**Comment by NyanKiyoshi** [comment]
Trying on a new clean clone that has no changes and is the latest to see if that fixes the problem.

**Comment by zatin009** [comment]
@NyanKiyoshi Additional infor, After we install the npm, the command usually tell us to fix the vulnerability of npm so if we execute the command "npm audit fix" it can fix some part of the npm vulnerability & run "npm run build-assets" many times, it does not occur the above problem. But  if we run "npm audit fix --force" & run "npm run build-assets" more than 1 time it leads to problem like this.

**Comment by NyanKiyoshi** [comment]
You shouldn't change the requirement versions, it will break some components. Most likely because you updated `materialcss` which is used by the dashboard 1.0 and the newest version (3.0 iirc) is incompatible with it.

We plan to drop the dashboard 1.0 soon so updating the dashboard to support the latest version of it would be too much work for nothing.

Can you try downloading the latest `package.json` and `package-lock.json` and overriding yours? Then redo `npm i && npm run build-assets` but don't `audit fix` (you don't need to worry about it, all the issues are checked and notified to us, nothing is concerning us–otherwise we would have applied a fix for it).

**Comment by zatin009** [comment]
I will tried it. Thank you so much for the information.
