### ISSUE TITLE
Renaming the folder issue & Moving the Folder issues 

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor#4335]
### What I'm trying to achieve
…

### Steps to reproduce the problem
1. After extract the folder name "saleor-master" & follow the installation instruction, it works fine 
2. Then I rename the folder "saleor-master" to other name "saleor-master-XX"  and run the server, & Even if i move the folder "saleor-master" from the original location  (_with "saleor-master.zip "_)to other location, It does leads to the problem like this :
**_Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'_**
& If i rename the folder to "saleor-master", it works fine. 

Could anyone try to explain what's reason behind this issue ?

**System information**
Operating system: Window 10
Browser: Chrome

**Comment by korycins** [comment]
Hi @zatin009 
I assume your issue can be connected with your environment. Do you use virtualenv?
It shows an error that django package cannot be found which shouldn't depend on salor's path or dir name.

**Comment by zatin009** [comment]
@korycins Thank your for your concern. Yes I do use virtualenv but based on what i understand during the "pip install -r requirements.txt" the library might take the path name of the saleor folder in order to install the django successfully. But I am not sure whether what i understand is Right or Wrong. I tested so many condition & I hope i can get clear & better explanation.

**Comment by NyanKiyoshi** [comment]
Where is the virtual environment located? I would recommend you to create it into the parent directory of saleor or another path, outside of saleor.

Also, I would recommend you to use `venv` instead (`python3 -m venv yourvenvname`) instead of virtualenv, sometimes it doesn't work properly depending on the use cases.

**Comment by zatin009** [comment]
The virtual environment "saleor-env" located in my "saleor-master" folder as the image below
![Capture](https://user-images.githubusercontent.com/40449637/60026377-a4da3b80-96c5-11e9-8411-e2e6f7c070d7.PNG)

**Comment by korycins** [comment]
@zatin009 And this is probably the main reason for your problem

**Comment by zatin009** [comment]
@korycins So Could you specific a bit more what are the issue in the folder of my screen shot image ?

**Comment by korycins** [comment]
Your virtual-env is inside the project directory and probably you broke some library paths when you moved project dir. I don't know Windows(OS) very well so it is hard to say what exactly happened.  I am closing this issue as it is not related to Saleor but with your configuration.

**Comment by zatin009** [comment]
Okay Suppose if i cloned the saleor 2.4 & saleor 2.7, So from your perspective, Would you create 2 virtual environments which located in each project ( 2.4 & 2.7 ) folder or we create only 1 virtual environment then activate to use in both projects (2.4 & 2.7). Thanks

**Comment by NyanKiyoshi** [comment]
> virtual environments which located in each project
I would recommend you to **keep the virtual environment out of the project**, by experience, I sometimes ran into problems when having a virtual environment inside a python project.

> if we clone the saleor 2.4 & saleor 2.7 folders
Don't use the same virtual environment if you use multiple versions. Use separated ones. Unless you are upgrading one's version.

Do something like `python -m venv ../saleor-venv-27` and `python -m venv ../saleor-venv-24`.
