### ISSUE TITLE
Upgrade django prices

### ISSUE THREAD

**Issue by korycins** [mirumee/saleor#4337]
With this PR: https://github.com/mirumee/django-prices/pull/73, django-prices will be able to support multi currencies. We should proceed with all described steps needed to upgrade package

**Comment by korycins** [comment]
Problem with django-prices 1.04 - #4378

**Comment by NyanKiyoshi** [comment]
Little update: I will start working on it from Wednesday after as we have a few things to discuss before migrating 👍
