### ISSUE TITLE
Dashboard2.0 doesn't update discount code.

### ISSUE THREAD

**Issue by korycins** [mirumee/saleor#4342]
### What I'm trying to achieve
I would like to update Discount Code field for a given Voucher.

### Steps to reproduce the problem
1. Create voucher
2. Change the value of discount code field -> click save. 
3. Refresh page. Discount Code hasn't changed

It seems that the dashboard doesn't send discount_code in API request. If this action is not allowed then this field should be blocked (like  `Type of Discount`)

**Comment by maarcingebala** [comment]
This action is now blocker in UI.
