### ISSUE TITLE
Error on braintree checkout

### ISSUE THREAD

**Issue by ironexmaiden** [mirumee/saleor#4364]
I have tried to add the braintree gateway for  paypal option in my site but when I tried testing it I got the following error 

> TypeError at /en/order/a608ad83-0b28-452d-9e5d-aa0988f3a59f/payment/braintree/
> get_client_token() got an unexpected keyword argument 'connection_params'

```
def get_client_token(config: GatewayConfig) -> str:
    gateway = get_braintree_gateway(**config.connection_params)
    client_token = gateway.client_token.generate()
    return client_token
```

I have fixed this bug by changing to this 

```
def get_client_token(connection_params) -> str:
    gateway = get_braintree_gateway(merchant_id = connection_params['merchant_id'], public_key = connection_params['public_key'], private_key = connection_params['private_key'], sandbox_mode=connection_params['sandbox_mode'])
    client_token = gateway.client_token.generate()
    return client_token
```

is this a right aprroach?

**Comment by NyanKiyoshi** [comment]
Hi again!

No this is not the right approach. Someone fixed it but was not merged. It will be done soon.

You need to change the signature of `get_client_token`, as simple as that.

**Comment by NyanKiyoshi** [comment]
What's your config? Can you show us `PAYMENT_GATEWAYS` from your settings?

**Comment by korycins** [comment]
@ironexmaiden  The last fix for payments was added 18 days ago ( https://github.com/mirumee/saleor/pull/4283 ) .
Can you check if this is a reason for your error?

**Comment by ironexmaiden** [comment]
@korycins yes it appears that this commit at #4283  is this that produce this error
I have also seen that after configuring a paypal sandbox account , connect it with braintree and make a test order and checkout the order is never fullfilled is this a right behavior?

**Comment by korycins** [comment]
Is your order fully paid on the dashboard side?
Order is fulfilled when you confirm that all required steps are done (like preparing the package and sending products to a customer). So your order will always have unfulfilled status after the payment is finished but you will have **payment status** set to 'Partially Paid/ Fully Paid`.
