### ISSUE TITLE
Sandbox paypal pay -through braintree- does not continue to successful pay

### ISSUE THREAD

**Issue by ironexmaiden** [mirumee/saleor#4371]
I have seen that after configuring a paypal sandbox account , connect it with braintree and make a test order and checkout the order is never fullfilled is this a right behavior?

**Comment by korycins** [comment]
Have you checked how other payment gateways behave? **Fulfiled** doesn't mean - `your order is fully paid`. It means: `Each order line is fulfilled in existing fulfillments. Order doesn’t require further actions by a shop operator.`
Here you can find more details:
https://docs.getsaleor.com/en/latest/architecture/orders.html?highlight=fulfilled#fulfillment

**Comment by ironexmaiden** [comment]
I can not understand if someone pays for an order then the order's status must change right?

**Comment by korycins** [comment]
Order has information about payment. Dashboard (1.0 and 2.0) has a separate section for payment. There you can find information if order has been already paid.
As I wrote in my previous comment. *Fulfilled* means `Order doesn’t require further actions by a shop operator.`
<img width="806" alt="image" src="https://user-images.githubusercontent.com/23282005/60509335-f3429800-9ccc-11e9-8515-776f1f24bbdf.png">
<img width="406" alt="image" src="https://user-images.githubusercontent.com/23282005/60509359-fe95c380-9ccc-11e9-8c08-de71169cabfb.png">
<img width="864" alt="image" src="https://user-images.githubusercontent.com/23282005/60509377-06edfe80-9ccd-11e9-91ae-c77c9704ffea.png">

**Comment by ironexmaiden** [comment]
No I have paid with sandbox account and the payment status still exists as NOT CHARGED

**Comment by korycins** [comment]
> No I have paid with sandbox account 

Do you mean Braintree sandbox or PayPal's sandbox connected to Braintree?

**Comment by ironexmaiden** [comment]
Paypal sandbox (facilitator-bussiness mode) connected to braintree

**Comment by NyanKiyoshi** [comment]
Does using the braintree works? e.g., try this VISA 4111 1111 1111 1111. If it does, it means there is something wrong with your Paypal.

**Comment by ironexmaiden** [comment]
Yes visa  4111 1111 1111 1111 works :(

**Comment by korycins** [comment]
You need to check configuration Paypal <-> Braintree. If `4111 1111 1111 1111` works then it means that configuration Braintree <-> Saleor is correct.
