### ISSUE TITLE
Use of django-countries

### ISSUE THREAD

**Issue by mjtamlyn** [mirumee/saleor#438]
I find it a little strange that when so many generic pieces of code (prices, carts etc) are handed off to other libraries that saleor includes its own list of countries. Have you considered using the `django-countries` app? It's very full featured and includes nice little features like flag icons, a wide range of pre-existing translations, a custom model field etc.

It's also maintained by a django core dev and has had regular releases in the last 2-3 years at least.

**Comment by patrys** [comment]
We have! I think there might even be another issue for that. The thing is there are always more pressing issues than refactoring a part that already works :wink:

**Comment by mjtamlyn** [comment]
Of course!
