### ISSUE TITLE
Incorrect filter name in voucher filters for old dashboard

### ISSUE THREAD

**Issue by fowczarek** [mirumee/saleor#4382]
In filters for old dashboard we use:

```
DISCOUNT_TYPE_CHOICES = (
    ("fixed", pgettext_lazy("Sale type filter choice", "USD")),
    ("percentage", pgettext_lazy("Sale type filter choice", "%")),
)
```

In model, we store this information in `discount_value_type` field. In `discount_type` field, we have information about voucher type e.g. `ENTIRE_ORDER`, `SPECIFIC_PRODUCT`, `SHIPPING`

**Comment by ChakshuGautam** [comment]
@fowczarek I would like to take this up. Can you please share where can I find the documentation on the data structure and relevant files.
I really like the product, really fast. (Almost felt like a static site). 
Thanks.

**Comment by fowczarek** [comment]
@ChakshuGautam  
In model(saleor/discount/models.py) we have Voucher definition. 
Voucher has  fields:
- `type` has the information about voucher type e.g `ENTIRE_ORDER`, `SPECIFIC_PRODUCT`, `SHIPPING`
- `discount_value_type` has the information it's fixed or percentage voucher. 

In dashboard1.0 filters we have an invalid `discount type` choice fields. 
![image](https://user-images.githubusercontent.com/43955230/66921139-e4d27f00-f024-11e9-81b3-c2238d5efb92.png)

In this place, we should filter by voucher `type` not by `discount_value_type`

**Comment by krustocious27** [comment]
Hi, I've made a PR for this above as it hasn't had any activity for a while.
