### ISSUE TITLE
Current Product Variant SKU is too short

### ISSUE THREAD

**Issue by petedermott** [mirumee/saleor#4389]
### What I'm trying to achieve
We have some products that may be made up of a number of SKU's combined into a single product. Whilst creating product "bundles" multiple products or variants tied into a single object could be an ideal solution, I can see this being niche feature that could cause complexity not just from a data modelling perspective but also from an admin UX perspective may provide little in the way of benefits for other developers.

### Describe a proposed solution
Instead, I would propose that a simple change to increase the ProductVariant sku field from 32 characters to somewhere in the region of 100 characters.

I don't really foresee any instances where this would cause breakages of current sites and it would be nice to have this standardised in the Saleor code base to remove the need for merge migrations and the like.

**Comment by ridiaz** [comment]
Hi,

In my case I used a hash function to generate sku's based on large product
names, like md5 or others.  Md5 fix well into 32 characters.

Just in case is a fair alternative to your use case.

Cheers

**Comment by petedermott** [comment]
I need to be able to display the SKU to customers and ideally use it as part of a Google Shopping feed, so I would hope to be able to use it "as is". 

I can certainly add my own fields to add similar functionality (and have already done so on my own fork) I felt it might be worth highlighting it as an "simple" potential improvement to Saleor

**Comment by maarcingebala** [comment]
I don't any reasons to limit the length of SKU so I would suggest using the maximum allowed value of 255 characters.

**Comment by NyanKiyoshi** [comment]
It doesn't have an impact on performances as well (unlike it would had on a `CHAR`).
