### ISSUE TITLE
Documenting the API's process through BPMN

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4395]
Quite some work has now been done for documenting the API processes. Each mutation’s process will be documented through BPMN, starting from the whole checkout process.

## 1 – Conventions
It is time to define/come up with conventions.

### 1.1 – File structure of the BPMN diagrams/project
I suggest that we have a folder for each process (checkouts, orders, accounts, etc.) which would incorporate the overview process in the base folder, e.g. `checkout_process.xml` and a folder containing the list of mutations that would consist of a `mutation.xml` to describe the mutation process and `validations.xml` to encapsulate all the validations done during `model.full_clean()`. Like so:

```
                  bpmn_____________________________
                 /                                 \
             checkouts______                       orders________
            /              \                     /             \
  checkout_process.xml  mutations______  order_process.xml  mutations
                       /               \                        |
                checkoutCreate  checkoutAddLines               ...
                       |                |
                 mutation.xml     mutation.xml
                       |                |
                validations.xml  validations.xml
```

### 1.2 – Guidelines for updating
In pull requests, we should add a check box asking the user to make sure they updated the BPMN diagrams (if any available) to their changes.

A pull request won’t be merged if a diagram is out of date.

### 1.3 – Naming conventions
Camunda has for conventions:
1. Tasks should be an action (a subject + a verb, e.g. `Delete the user`);
1. Gateways should be in a passive tense (e.g.: `user was deleted`);

Other things to consider:
1. A diagram should have a meaningful name `<mutation name>[task name, if any]`;
1. Invoking an external task should use a `send task` task (emoji), e.g. for saving a model;
1. Throwing validation errors should use an error boundary event and end the process;
1. A sub-task should have two end events: “Successful” and “Validation Error”;
1. When calling a validation task, the task should be green;
1. When writing into the database, the task should be blue.

### 1.4 – Miscellaneous conventions
We need a way of referencing/linking diagrams when a sub-task is called. This would be done by using a given property, e.g. `diagramId = checkoutCreateValidations`. This has to be decided when we adopt a custom BPMN rendering to properly link tasks.

## 2 – Publishing
- We might want to create a `bpmn` or `bpmn-processes` sub-folder into `docs` (?)
- We might need to have a way to generate recursively bitmaps from the XML.

**Comment by patrys** [comment]
Internal reference: https://www.notion.so/mirumee/Technical-documentation-939b499848be48f68e4016baf29ab486
