### ISSUE TITLE
Add description and deprecation support to filters

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4398]
`FilterInputObjectType` doesn't provide a way to document fields. We could add two fields to the meta-class: `descriptions = {field: description}` and `deprecations = {field: reason}`.

**Comment by michizhou** [comment]
Hi @NyanKiyoshi @maarcingebala I'd happy to work on this issue. Let me know if you have any pressing questions or information you'd like to share with me!
