### ISSUE TITLE
Can't build with command : npm run build-assets (on MAC)

### ISSUE THREAD

**Issue by xuanmaithanh** [mirumee/saleor#4408]
Hi,

I've clone the Saleor from github and try to build, but some errors happened as below when run command : npm run build-assets  (after I run : npm install)

Please take a look and give me the advice 

My environment:
- node : v10.10.0
- npm : 6.4.1
--------------------------------------------------------------------------------
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/components/AppLayout/AppLayout.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/components/AppLayout/AppLayout.tsx(194,14):
TS2558: Expected 2 type arguments, but got 1.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/components/Filter/FilterContent.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/components/Filter/FilterContent.tsx(50,19):
TS2554: Expected 1 arguments, but got 0.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/components/Filter/FilterElement.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/components/Filter/FilterElement.tsx(44,19):
TS2554: Expected 1 arguments, but got 0.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/components/TableFilter/FilterChips.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/components/TableFilter/FilterChips.tsx(30,19):
TS2554: Expected 1 arguments, but got 0.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/mutations.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/mutations.tsx(34,7):
TS2339: Property 'children' does not exist on type 'Pick<TypedMutationInnerProps<TData, TVariables>, Exclude<"children", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"onError", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/mutations.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/mutations.tsx(35,7):
TS2339: Property 'onCompleted' does not exist on type 'Pick<TypedMutationInnerProps<TData, TVariables>, Exclude<"children", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"onError", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/mutations.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/mutations.tsx(36,7):
TS2339: Property 'onError' does not exist on type 'Pick<TypedMutationInnerProps<TData, TVariables>, Exclude<"children", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"onError", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/mutations.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/mutations.tsx(37,7):
TS2339: Property 'variables' does not exist on type 'Pick<TypedMutationInnerProps<TData, TVariables>, Exclude<"children", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"onError", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/mutations.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/mutations.tsx(38,9):
TS2352: Conversion of type 'TypedMutationInnerProps<TData, TVariables>' to type 'Pick<TypedMutationInnerProps<TData, TVariables>, Exclude<"children", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"onError", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'TypedMutationInnerProps<TData, TVariables>' is not comparable to type 'Pick<InferProps<{ mutation: Validator<object>; variables: Requireable<object>; optimisticResponse: Requireable<object>; refetchQueries: Requireable<((...args: any[]) => any) | (string | object)[]>; ... 5 more ...; fetchPolicy: Requireable<...>; }>, Exclude<...> | ... 8 more ... | Exclude<...>>'.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/mutations.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/mutations.tsx(43,8):
TS2322: Type '{ children: any; mutation: any; onCompleted: any; onError: (err: any) => void; variables: any; update: MutationUpdaterFn<TData>; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<StrictTypedMutation> & Pick<Readonly<MutationProps<TData, TVariables>> & Readonly<{ children?: ReactNode; }>, Exclude<...> | ... 11 more ... | Exclude<...>> & Pick<...> & Pick<...>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<StrictTypedMutation> & Pick<Readonly<MutationProps<TData, TVariables>> & Readonly<{ children?: ReactNode; }>, Exclude<...> | ... 11 more ... | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/queries.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/queries.tsx(79,13):
TS2339: Property 'children' does not exist on type 'Pick<PropsWithChildren<TypedQueryInnerProps<TData, TVariables>>, Exclude<"require", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"children", IsExactlyAny<...> extends true ? "variables" : never> | Exclude<...> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/queries.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/queries.tsx(82,13):
TS2339: Property 'variables' does not exist on type 'Pick<PropsWithChildren<TypedQueryInnerProps<TData, TVariables>>, Exclude<"require", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"children", IsExactlyAny<...> extends true ? "variables" : never> | Exclude<...> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>'.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/queries.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/queries.tsx(84,15):
TS2352: Conversion of type 'PropsWithChildren<TypedQueryInnerProps<TData, TVariables>>' to type 'Pick<PropsWithChildren<TypedQueryInnerProps<TData, TVariables>>, Exclude<"require", IsExactlyAny<TVariables> extends true ? "variables" : never> | Exclude<"children", IsExactlyAny<...> extends true ? "variables" : never> | Exclude<...> | Exclude<...> | Exclude<...>> & Pick<...> & Pick<...>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'PropsWithChildren<TypedQueryInnerProps<TData, TVariables>>' is not comparable to type 'Pick<InferProps<{ client: Requireable<object>; children: Validator<(...args: any[]) => any>; fetchPolicy: Requireable<string>; notifyOnNetworkStatusChange: Requireable<boolean>; onCompleted: Requireable<...>; ... 6 more ...; returnPartialData: Requireable<...>; }>, Exclude<...> | ... 10 more ... | Exclude<...>>'.

ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/queries.tsx
ERROR in /Volumes/DATA/Papagroup/_learning/Saleor_framework/saleor/saleor/static/dashboard-next/queries.tsx(89,14):
TS2322: Type '{ children: (queryData: any) => any; fetchPolicy: string; query: any; variables: any; skip: boolean; context: { useBatching: boolean; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<StrictTypedQuery> & Pick<Readonly<QueryProps<TData, TVariables>> & Readonly<{ children?: ReactNode; }>, Exclude<"client", "query" | (IsExactlyAny<...> extends true ? "variables" : never)> | ... 14 more ... | Exclude<...>> & Pick<...> & Pick<...>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<StrictTypedQuery> & Pick<Readonly<QueryProps<TData, TVariables>> & Readonly<{ children?: ReactNode; }>, Exclude<"client", "query" | (IsExactlyAny<...> extends true ? "variables" : never)> | ... 14 more ... | Exclude<...>> & Pick<...> & Pick<...>'.
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/postcss-loader/lib/index.js??ref--5-2!node_modules/sass-loader/lib/loader.js??ref--5-3!saleor/static/dashboard/scss/dashboard.scss:
    Entrypoint mini-css-extract-plugin = *
     [0] ./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./saleor/static/dashboard/scss/dashboard.scss 657 KiB {0} [built]
    [13] ./saleor/static/dashboard/images/chevron-right.svg 96 bytes {0} [built]
        + 12 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/postcss-loader/lib/index.js??ref--5-2!node_modules/sass-loader/lib/loader.js??ref--5-3!saleor/static/dashboard/scss/document.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./saleor/static/dashboard/scss/document.scss 7.15 KiB {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/postcss-loader/lib/index.js??ref--5-2!node_modules/sass-loader/lib/loader.js??ref--5-3!saleor/static/scss/storefront.scss:
    Entrypoint mini-css-extract-plugin = *
     [0] ./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./saleor/static/scss/storefront.scss 530 KiB {0} [built]
     [3] ./saleor/static/images/arrow-select.svg 95 bytes {0} [built]
     [4] ./saleor/static/fonts/Lato-Light.woff2 95 bytes {0} [built]
     [5] ./saleor/static/fonts/Lato-Light.woff 94 bytes {0} [built]
     [6] ./saleor/static/fonts/Lato-Light.ttf 93 bytes {0} [built]
     [7] ./saleor/static/fonts/Lato-Regular.woff2 97 bytes {0} [built]
     [8] ./saleor/static/fonts/Lato-Regular.woff 96 bytes {0} [built]
     [9] ./saleor/static/fonts/Lato-Regular.ttf 95 bytes {0} [built]
    [10] ./saleor/static/fonts/Lato-Bold.woff2 94 bytes {0} [built]
    [11] ./saleor/static/fonts/Lato-Bold.woff 93 bytes {0} [built]
    [12] ./saleor/static/fonts/Lato-Bold.ttf 92 bytes {0} [built]
    [13] ./saleor/static/images/block1.jpg 89 bytes {0} [built]
    [14] ./saleor/static/images/block2.jpg 89 bytes {0} [built]
    [15] ./saleor/static/images/block3.jpg 89 bytes {0} [built]
        + 2 hidden modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! saleor@0.0.0 build-assets: `webpack -p`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2019-07-06T16_37_35_125Z-debug.log

**Comment by zatin009** [comment]
1. I think you can update the node js to the latest version which is 10.16 or better 12.6 and plz don't try to "npm run build-assets" more than 1 time. 
2. You have to delete the "node_modules" folder + package-lock.json in your folder project.
3. Run the "npm install" again 
4. If the issues stilll occur, plz uninstall the Node.js + Deleting all the file log and Registry file in Registry Editor and Reinstall the Node.js again.
Hopefully this will works.

**Comment by xuanmaithanh** [comment]
@zatin009 
Thanks for your advice, I did follow, try with both version 10.10 & 12.6 of Node, but the issue still be same  :D Do you have other suggestion for me?

**Comment by xuanmaithanh** [comment]
Hi, I've tried to use Docker and can build the Saleor successfully. Thanks a lot. I think that can close this issue
