### ISSUE TITLE
Docker: com.docker.hyperkit high CPU consumption

### ISSUE THREAD

**Issue by vladox** [mirumee/saleor#4409]
I'm using your docker-compose file to contribute to the project but I've noticed that com.docker.hyperkit is going over 100% when in idle state, normal should be around 10% or less. 
  
The host I'm currently using is a Mac Docker Desktop on MacOS 10.13.6.
  
We have seen this problem before with the Mac Docker Desktop and Django based projects, the solution is to use [pywatchman](https://pypi.org/project/pywatchman/) or [pyinotify](https://pypi.org/project/pyinotify/) depending on the Django version.
  
Since you are using Django 2.2 for Saleor the solution is to add pywatchman as a dependency to the dev requirements.

<img width="451" alt="Activity_Monitor__All_Processes_" src="https://user-images.githubusercontent.com/2648461/60767143-a63b3900-a0b3-11e9-9fa6-ed49e5066a44.png">

<img width="768" alt="1__vladox_Vladimirs-MBP____Dev_Python_Github_saleor__zsh_" src="https://user-images.githubusercontent.com/2648461/60767152-d1258d00-a0b3-11e9-8778-a91f53c64697.png">

![image](https://user-images.githubusercontent.com/2648461/60767180-45f8c700-a0b4-11e9-8445-b9d4e55011e1.png)

**Comment by arvandf** [comment]
The issue exists on windows as well and the CPU usage goes above 70% with a core i-7 CPU.
