### ISSUE TITLE
Cannot Create the Product in Dashboard 2.0

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor#4411]
For the Dashboard 2.0 Every time, we click the save button , it usually showed error in Product Type error " This field cannot be null" However we input the data in the field correctly as the shown image.
![Capture](https://user-images.githubusercontent.com/40449637/60770235-0ad1b480-a103-11e9-9ce9-8b5f79e897b0.PNG)

**Comment by ppshobi** [comment]
Any Idea on how to mitigate this?

**Comment by NyanKiyoshi** [comment]
@ppshobi a patch is available at #4423–but I'm not a frontend developer so it can be incorrect, but it works if you need a urgent fix.

**Comment by ppshobi** [comment]
Thanks for the patch
