### ISSUE TITLE
Change site logo from dashboard

### ISSUE THREAD

**Issue by umrashrf** [mirumee/saleor#4417]
### What I'm trying to achieve
Change website logo from the dashboard (https://demo.getsaleor.com/dashboard/settings/1/)

### Describe a proposed solution
Use the same header text from dashboard site settings and use special font (https://fonts.google.com/)

### Other solutions I've tried and won't work
Replace logo file in 
- saleor/static/images/logo-light.svg
- saleor/static/images/logo-white.svg
- saleor/static/images/logo-dark.svg

### Screenshots or mockups
![Screenshot from 2019-07-09 01-44-10](https://user-images.githubusercontent.com/652326/60862433-8a3ab300-a1eb-11e9-848b-48b44e8d2eb3.png)

**Comment by maarcingebala** [comment]
Hey, since we're focused on [Dashboard 2.0](https://demo.getsaleor.com/dashboard/next) (it's going to become the default one soon) we won't be working on new features in the old dashboard. For now, we recommend changing the logo in HTML for the old storefront or in JSX components in the new one.

**Comment by umrashrf** [comment]
@maarcingebala thanks, that's what I was thinking too
