### ISSUE TITLE
integration of translation into admin dashboard

### ISSUE THREAD

**Issue by snfxgsx** [mirumee/saleor#4439]
### What I'm trying to achieve
let the admin have control over translations of the front-end

### Describe a proposed solution
create an easy to use interface inside the admin to edit translation files

### Other solutions I've tried and won't work
Manually edit the translation files installed, it works but I have to manually restart the servers

**Comment by maarcingebala** [comment]
This feature is not planned currently. I'm not sure if this is actually possible in Django to have translations that are loaded dynamically.

For static translations, we use [Transifex](https://transifex.com/mirumee/saleor-1/) which provides a nice interface. For dynamic ones (translations of your models) we have the "Translations" section in Dashboard 2.0.
