### ISSUE TITLE
Clicking on product variant crashes Dashboard 2.0

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#4440]
### What I'm trying to achieve
Edit a product variant

### Steps to reproduce the problem
1. Click on a product variant listed under a product

### What I expected to happen
To be shown the variant editing page. Instead, I get the react error white screen. The browser console gives the following error `TypeError: a.attributes.filter(...)[0] is undefined`. An array index out of bounds error.

**System information**
Operating system: Windows 10 x64
Browser: Firefox 67

**Comment by NyanKiyoshi** [comment]
Why did you close it?

**Comment by khalibloo** [comment]
It no longer crashes. I thought it had been fixed.

**Comment by NyanKiyoshi** [comment]
Oh alright. It works as well for me now.
