### ISSUE TITLE
Where is `ReactJS` code?

### ISSUE THREAD

**Issue by elcolie** [mirumee/saleor#4451]
Where I can see `ReactJS` code?

**Comment by maarcingebala** [comment]
Hey, you'll find frontend code here:
- Dashboard 2.0 - [saleor/static/dashboard-next](https://github.com/mirumee/saleor/tree/master/saleor/static/dashboard-next) directory in Saleor's repo.
- PWA storefront lives in [mirumee/saleor-storefront](https://github.com/mirumee/saleor-storefront/)

**Comment by elcolie** [comment]
Thank you @maarcingebala
