### ISSUE TITLE
Submitting popup form resets the wider page form (Dashboard 2.0)

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#4462]
1. Edit a product type, e.g. uncheck a box or edit the name (don't save)
1. Add an attribute and save it
1. The changed data gets reset

### What I'm trying to achieve
When adding/editing a product type (other pages probably have the same issue), the form gets reset after submitting a popup form such as the add/edit attribute form. This is particularly noticeable because the workflow is typically like so:
Create product type
Check "product has variants"
Add variant attribute

At this point, you'll notice that the "product has variants" checkbox reverts to its unchecked state. After exploring further, I found it affects other fields in the form as well.

### Describe a proposed solution
Submitting an inner form should not reset the entire page form if it has unsaved changes.

**Comment by dominik-zeglen** [comment]
Nice catch

**Comment by khalibloo** [comment]
Just tried this. Works when editing an attribute, but still resets the form when adding an attribute

**Comment by dominik-zeglen** [comment]
How exactly?
I tried to reproduce this but I couldn't.

**Comment by khalibloo** [comment]
You're right. I tested a new saleor installation, and it works well. My apologies.
