### ISSUE TITLE
graphql-relay mismatched hashes error

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#4464]
### What I'm trying to achieve
When installing a new instance of saleor either locally or on Heroku, it fails due to mismatched hashes. It points to graphql-relay as the offending package.

### Steps to reproduce the problem
1. Clone saleor
2. Install python packages

**Comment by maarcingebala** [comment]
There is an issue with graphql-relay: https://github.com/graphql-python/graphql-relay-py/issues/23

**Comment by maarcingebala** [comment]
The issue in graphql-relay is now resolved.
