### ISSUE TITLE
NPM packages contain too many high vulnerabilities

### ISSUE THREAD

**Issue by xgenvn** [mirumee/saleor#4465]
### What I'm trying to achieve
- Install the npm dependencies with as few high vulnerablities as possible

### Steps to reproduce the problem
1. Clone repository
2. `npm i`

### What I expected to happen
- Least than 5 high vulnerablities when running `npm audit`

### Screenshots
```
added 3554 packages from 1343 contributors and audited 901496 packages in 88.629s
found 16843 vulnerabilities (2 low, 9 moderate, 16832 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**System information**
Operating system: Ubuntu 18.04.2
Browser:

### Notes:
- Doing `npm audit fix` can resolve most of out-dated dependencies
```
+ apollo@2.16.0
+ lodash@4.17.14
added 12 packages from 18 contributors, removed 14 packages and updated 83 packages in 61.313s
fixed 16837 of 16843 vulnerabilities in 901496 scanned packages
  2 vulnerabilities required manual review and could not be updated
  2 package updates for 4 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
```
For details of output please see `audit.log`

[audit.log](https://github.com/mirumee/saleor/files/3394837/audit.log)

**Comment by snfxgsx** [comment]
I think these vulnerabilities are related to materialized css packages, you can fix them but it will throw another vulnerabilities

**Comment by maarcingebala** [comment]
@dominik-zeglen is already working on that, it should be fixed today.

**Comment by xgenvn** [comment]
> @dominik-zeglen is already working on that, it should be fixed today.

Thanks for the quick update.
