### ISSUE TITLE
Unclear country input expectation for GraphQL checkout address attach mutation

### ISSUE THREAD

**Issue by adrienshen** [mirumee/saleor#4466]
### What I'm trying to achieve
I'm trying to create an shipping or billing address via GraphQL checkout attach. But it's unclear what is expected in the `AddressInput.country` field.

### Steps to reproduce the problem
1. Call `Mutations.checkoutShippingAddressUpdate` using string for country input like "USA", "United States"
2. We get back errors from Django GraphLQ saying that "invalid country code"

### What I expected to happen
There seems to validation going on in `saleor/graphql/account/i18n.py` that checks country string with phone number as well as converts country string to country code and checks against list of valid country codes. The problem, I see here is that because the GraphQL API expects a any string, it's not obvious what the correct string should be. I would make it a just to expect the country code instead and link in the documentations what the expected values are to make it easier for developers.

### Screenshots

https://www.dropbox.com/s/eow0x246dru5ga6/Screenshot%202019-07-16%2013.22.55.png?dl=0
https://www.dropbox.com/s/02w3fxi1r1x38ih/Screenshot%202019-07-16%2013.30.23.png?dl=0

**System information**
Operating system: MacOS
Browser: Chrome 75

**Comment by NyanKiyoshi** [comment]
It is expecting a two letter country code (ISO 3166-1), e.g. `US`, `PL`, `FR`, etc.

**Comment by maarcingebala** [comment]
So it seems that there is a wrong input type for the `country` field in `AddressInput` type. Instead of `String` it should use the `CountryCode` enum.

**Comment by adrienshen** [comment]
Yea, I agree. I think it should be Enum of CountryCode to avoid confusion.
