### ISSUE TITLE
items in the cart are subtracted from available stock

### ISSUE THREAD

**Issue by pcompassion** [mirumee/saleor#447]
I'm fairly new to ecommerce systems in general but this one seems odd to me.

When a store has 100 items in stock, and a user place 100 items in a cart. 
Other users see the items are no longer available.

**Comment by patrys** [comment]
This should not be the case. In fact there should be no direct modification of stock levels until an order is placed. What we do however is we prevent any particular user from placing more than the current stock's worth in their cart.

**Comment by pcompassion** [comment]
oh.. yes it was my mistake. sorry for the false call.
