### ISSUE TITLE
Product description field loses focus when typing (Dashboard 2.0)

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#4470]
### What I'm trying to achieve
When editing or adding a product, the description field loses focus after each key press. It appears to be similar to #3883 

### Steps to reproduce the problem
1. Type in the product description field

**System information**
Operating system: Windows 10 x64
Browser: Firefox 68

**Comment by NyanKiyoshi** [comment]
Note: next time please say which dashboard you are talking about 😉 But I do know you are talking about the 2.0, but it is always good to know for sure.

**Comment by dominik-zeglen** [comment]
Caused by #4467, now I know why description was taken directly from product. This time I'll add comment to avoid this next time.

**Comment by khalibloo** [comment]
You're right, @NyanKiyoshi. I forgot to mention that this time.
