### ISSUE TITLE
Error when creating product variant (Dashboard 2.0)

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#4474]
### What I'm trying to achieve
Create product variant. I verified the bug with a clean deployment of saleor.

### Steps to reproduce the problem
1. Create a product type with 2 variant attributes eg Size and Color
2. Create another product type with the exact same variant attributes
3. Create a product with one of the product types
4. Create a variant for that product

### What I expected to happen
The variant should have been created. I got an error message `get() returned more than one Attribute -- it returned 2!`. I suspect it is related to #3988 

### Screenshots
![image](https://user-images.githubusercontent.com/6402969/61324855-6e0ac780-a824-11e9-8812-6a181d78a932.png)

**System information**
Operating system: Windows 10 x64
Browser: Firefox 68

**Comment by maarcingebala** [comment]
Hey @khalibloo, could you check if this error still occurs on current `master`? I'm testing it after we merged #4351 and it seems to be resolved.

**Comment by khalibloo** [comment]
Thanks for the update. Yes, this is no longer an issue. #4351 is looking good!
