### ISSUE TITLE
Voucher Not working

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor#4486]
### What I'm trying to achieve
App Voucher Working

### Steps to reproduce the problem
In Both Dashboard 1.0 & 2.0
1. Click on App Navigation

Debug Log : 
**django.db.utils.ProgrammingError: column discount_voucher.apply_once_per_customer does not exist
LINE 1: ...date", "discount_voucher"."apply_once_per_order", "discount_...**

### What I expected to 
Voucher App 
### Screenshots
![Capture](https://user-images.githubusercontent.com/40449637/61382755-8daef800-a8d7-11e9-889a-647659984122.PNG)

**Comment by patrys** [comment]
It seems that you have unapplied database migrations.

**Comment by zatin009** [comment]
Thank you Dears, My friend run makemigrations that's why during running the server it doesn't not alert. I'll close the issue.
