### ISSUE TITLE
Query: Updated the authenticated user personal information

### ISSUE THREAD

**Issue by adrienshen** [mirumee/saleor#4496]
### What I'm trying to achieve
We're trying to update the "Customer Details" fields of "First name", "Last name", "Phone number". and "Email" through the GraphQL API. Currently, we don't see anyway to do this via the authenticated account in the storefront.

### Describe a proposed solution
Have GraphQL API to update the Authenticated Users' customer detail fields from storefront.

### Other solutions I've tried and won't work
We use the `Mutations.loggedUserUpdate` to update the default shipping and billing addresses. We can also extend this to include contact details?

### Screenshots or mockups
-

**Comment by NyanKiyoshi** [comment]
What about the `AddressUpdate` mutation? e.g. through:
```gql
{
  me {
    defaultShippingAddress {
      id
    }
  }
}
```

**Comment by maarcingebala** [comment]
@adrienshen We used to have `loggedUserUpdate` for that, but as you say - it only allowed to update the addresses. Just yesterday we deprecated this mutation in favor of `accountUpdate` - this will allow you to update first name, last name and default addresses. 

Updating an email is a bit different operation - emails have to be unique across the system and users will have to confirm them by clicking a link that we'll send. We're planning to add that operation soon.

We also want to introduce better naming consistency and prefix all mutations for logged-in customers with the word `account`.

**Comment by adrienshen** [comment]
@maarcingebala Alright, the accountUpdate seems to be what we're looking for. We'll need to update the app to the latest master branch, I guess. Yea, the naming was a bit confusing for us as well since many of the Customer.* operations were for Dashboard and not for the Storefront. I'm glad the new Account.* naming convention will make things easier.

I'm planning on using Saleor for all of our future eCommerce projects and it's looking to be a great framework.
