### ISSUE TITLE
`addressValidator` incorrectly handles its input

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#4514]
### What I'm trying to achieve
Use `addressValidator` query to obtain information about a country.

### Steps to reproduce the problem
Use the following query:

```graphql
{
  addressValidator(input: {countryCode: "GB"}) {
    addressFormat
  }
}
```

It crashes unless all optional fields of `AddressValidationInput` are specified.

I believe the `countryCode` should be marked as required (as it does not make sense to call the validator if the country is unknown). All other fields should be optional and the code should not crash if they are not given.

### What I expected to happen
No crash.

**Comment by patrys** [comment]
By the way, I find it interesting that it's a query yet has its arguments handled as if it was a mutation.

Wouldn't it be better to change it to:

```graphql
type Query {
  addressValidator(country: CountryEnum!, countryArea: String, city: String, cityArea: String): AddresValidationData
}
```

**Another bug:** The current definition of `AddressValidationInput` is missing the `city` field.

**Comment by Kwaidan00** [comment]
I wanted to fix it, but I've found that current `master` has other code for that: it does not use `AddressValidationInput` anymore. But `country` field is not required and there is still missing `city` field.
https://github.com/mirumee/saleor/blob/7feb6d97d5060a7cc7f2f46de6b760ca751dd8b7/saleor/graphql/account/schema.py#L77-L85

**Comment by maarcingebala** [comment]
@Kwaidan00 We should change the signature and use the one that @patrys suggested. I agree that it would be more suitable than the current `AddressValidationInput`.
