### ISSUE TITLE
Some bool env variables are not converted to boolean on load

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#4515]
In settings.py file there are some env variables, which expect to be boolean, but are not parsed to it (present as a string instead). Instead of `os.environ.get` we should use `get_bool_from_env` helper

eg. AVATAX_AUTOCOMMIT and STRIPE's configuration. 

Same with the PLUGINS env variable, as a default we are using empty list, while the value taken from the environment will be a str type.

**Comment by NyanKiyoshi** [comment]
Fixed by #4664
