### ISSUE TITLE
TypeError: Cannot read property 'url' of null

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor#4526]
### What I'm trying to achieve
Run Dashboard 2.0

### Steps to reproduce the problem
1. Clone the master branch.
2. and Install as procedures 

### Screenshots

![Capture](https://user-images.githubusercontent.com/40449637/61821106-acd1fa80-ae80-11e9-9d66-f9768804def7.PNG)
: 
Browser: Chrome

**Comment by korycins** [comment]
Can you share more details about steps that you did?

**Comment by maarcingebala** [comment]
I found a similar issue yesterday - when you log in to the dashboard and remove your avatar, it fails to renders the avatar component in the top right corner of the dashboard.

Steps to reproduce:
1. In the Dashboard 2.0 go to Configure > Staff Members
2. Go to your account details.
3. Hover on the avatar and click "Delete photo".
4. Reload the page.

**Comment by zatin009** [comment]
@maarcingebala  As what you said is correctly, So I solve the issue by comment the below chip & it works fine.

![Capture](https://user-images.githubusercontent.com/40449637/61854439-48e31c80-aee8-11e9-8666-45d851096e40.PNG)

**Comment by maarcingebala** [comment]
If I'm correct a fix for that would be to change this line:
https://github.com/mirumee/saleor/blob/730732000cf0139182c92c52ebd398ab6911d3a8/saleor/static/dashboard-next/components/AppLayout/AppLayout.tsx#L388

with this piece of code:
```
user.avatar ? (
  <Avatar alt="user" src={user.avatar.url} />
) : null
```

**Comment by maarcingebala** [comment]
@dominik-zeglen or @benekex2 if you could verify if this is correct ⬆️. If you have time maybe you can quickly fix it, if not, I'll try to take a look later.

**Comment by dominik-zeglen** [comment]
```
{user.avatar && <Avatar alt="user" src={user.avatar.url} />}
```
should be ok.
