### ISSUE TITLE
Allow to search for products by SKU in admin dashboard

### ISSUE THREAD

**Issue by jwm0** [mirumee/saleor#4531]
### What I'm trying to achieve
I'm looking to find a product by its SKU

### Describe a proposed solution
Tweak search engine settings to return products with full/partial SKU match.

**Comment by TJBANEY** [comment]
@maarcingebala I can take this up

**Comment by NyanKiyoshi** [comment]
Go for it 🎉 There is no need to ask to open a pull request 👍

**Comment by maarcingebala** [comment]
To support that we need to change behavior of `search` field in `ProductFilterInput` type to also look up products by their variants SKU.
