### ISSUE TITLE
Back button works sometimes–sometimes not

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4532]
1. Try multiple time to hover the back button (the text or the arrow)
2. Sometimes it might work, sometimes not (maybe when moving the cursor too fast onto it? I have a high sensibility mouse)

Tried on both chrome and firefox:

![ezgif-3-44447ffd8de3](https://user-images.githubusercontent.com/6186720/61874023-9a3edc00-aee7-11e9-920a-72e5348c65bf.gif)

**Comment by benekex2** [comment]
Repeated issue #4530
