### ISSUE TITLE
Create sales issue in Dashboard 2.0

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor#4533]
### What I'm trying to achieve
Able to Create sale in Dashboard 2.0
Error  : "Something went wrong: Network error: Response not successful: Received status code 400 " as screen image
### Steps to reproduce the problem
1. Click on Sale in Dashboard 2.0
2. Fill all the req
3. Click "Save" Button
### What I expected to happen
Create sale in Dashboard 2.0

### Screenshots

![Capture](https://user-images.githubusercontent.com/40449637/61939539-b2812a80-afbd-11e9-8d97-1e378ee53b3b.PNG)

**System information**
Operating system: 
Browser:

**Comment by korycins** [comment]
same as #4441
