### ISSUE TITLE
All products shouldn't be shippable by default

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#454]
We can add boolean field like shopify does:

![image](https://cloud.githubusercontent.com/assets/1870738/12653691/f1948754-c5f0-11e5-96aa-02b35b0d6439.png)

**Comment by artursmet** [comment]
In my opinion, weight field should be optional field (now it's required). And I agree that we should add boolean field as you suggest :+1:

**Comment by patrys** [comment]
:+1:

**Comment by artursmet** [comment]
@patrys What do you think about implementing `requries shipping` flag as a part of ProductClass?

**Comment by patrys** [comment]
I requested this when discussing product classes initially but it was not implemented.
