### ISSUE TITLE
Collection Bug in Dashboard 2.0

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor#4543]
### What I'm trying to achieve
1. Able to save the description of collection in Database
2. Able to display the created collection from dashboard 2.0 on the Home Page.

### Steps to reproduce the problem
1. Create on the collection as procedure

### What I expected to happen
Collection work fine
### Screenshots
1. I created the eample collection.
![Capture1](https://user-images.githubusercontent.com/40449637/61989524-e2cad680-b05a-11e9-97f3-3d2496dc8217.PNG)

2. Fill the requirenment & Description Text
![Capture2](https://user-images.githubusercontent.com/40449637/61989531-055cef80-b05b-11e9-87b4-ff87226a084c.PNG)

3. Published the the collection on Home Page but it now show
![Capture 3](https://user-images.githubusercontent.com/40449637/61989535-245b8180-b05b-11e9-8824-782da555332f.PNG)

4. Text description Input not saved in the database, but It saved in the text field of dashboard 2.0 if i checked with the collection again.
![Capture4](https://user-images.githubusercontent.com/40449637/61989560-a8ae0480-b05b-11e9-8014-ae871fbb9b69.PNG)

**Comment by NyanKiyoshi** [comment]
Hi! For the description, is the same as I said in https://github.com/mirumee/saleor/issues/4544#issuecomment-515662123.

For the menu, you have to go into the `Configure` section and then in `Navigation` to add the collection to the footer menu.
