### ISSUE TITLE
Text Description in Categories Not Save , Dashboard 2.0

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor#4544]
### What I'm trying to achieve
Able to save the text description

### Steps to reproduce the problem
1. Create the category as procedure
2. Fill all the requirement
3. Click Save then it saved in the dashboard 2.0 only
when check database not save
### What I expected to happen
Able to save the text description in Dashboard2.0

### Screenshots
![xxxx](https://user-images.githubusercontent.com/40449637/61989781-528e9080-b05e-11e9-8bd5-886e54016b01.PNG)
![Data not save](https://user-images.githubusercontent.com/40449637/61989783-57534480-b05e-11e9-8124-8fbc787a248c.PNG)

**System information**
Operating system: 
Browser:

**Comment by NyanKiyoshi** [comment]
Hi! It's saving into the `description_json` field. Note that if you are using storefront 1.0, you have to set the `USE_JSON` environment variable to `True` to enable the JSON rendering.

**Comment by zatin009** [comment]
@NyanKiyoshi Thank you for the infor. However, Could you tell me a bit about where to set the USE_JSON  to true ?

**Comment by zatin009** [comment]
I have seen it in the "description_json" field but it doesn't display in the storefront 1.0. How can I make it display ?

**Comment by NyanKiyoshi** [comment]
@zatin009 in your settings. Just like you set `SECRET_KEY` (environment variable).
