### ISSUE TITLE
Amazon S3 and sizing function on Heroku

### ISSUE THREAD

**Issue by anonthemon** [mirumee/saleor#4568]
I have configured saleor on heroku with the following vars:

AWS_ACCESS_KEY_ID
AWS_MEDIA_BUCKET_NAME
AWS_SECRET_ACCESS_KEY

When I upload a product photo on the dashboard, it is sent properly to my S3 bucket under the /products/ folder. However, the page is accessing the photo from the \__sized__ folder with different sized versions of the image. There is no sizing happening and no images in that folder. Am I configuring something wrong?

**Comment by NyanKiyoshi** [comment]
Just tried, it works perfectly fine for me. Can you check if the environment variables are properly set? Also what version of saleor are you using?
