### ISSUE TITLE
Does it support india market?

### ISSUE THREAD

**Issue by marmikdesai** [mirumee/saleor#4574]
Hi,

Does seleor support indian rupee, GST, indian payment gateway, shipping?

Marmik

**Comment by NyanKiyoshi** [comment]
Hi, yes, you can set the default currency to `INR`, set-up and enable the Razorpay payment gateway.

**Comment by marmikdesai** [comment]
Thanks for quick replay. What about [GST](https://www.gst.gov.in/)?

**Comment by NyanKiyoshi** [comment]
You can use Avatax or add your own tax rules.

<details><summary>Details about adding custom tax rates</summary>
<p>

You can do something like this inside Django (for example from the django shell: `./manage.py shell` or through a custom django command):
```python
from django_prices_vatlayer.models import VAT

data = {"country_name":"Turkey","standard_rate":20,"reduced_rates":{"foodstuffs":10,"books":10,"pharmaceuticals":10}}

VAT.objects.update_or_create(
    country_code=country_code, defaults={'data': data})
```

Just remove the unneeded rates and change the standard rate to the Turkey's.

Here are the available reduced rates available (you most likely need none, so you can just do `data = {"country_name":"Turkey","standard_rate":20,"reduced_rates":{}`):

0 | "accommodation"
-- | --
1 | "admission to cultural events"
2 | "admission to entertainment events"
3 | "admission to sporting events"
4 | "advertising"
5 | "agricultural supplies"
6 | "baby foodstuffs"
7 | "bikes"
8 | "books"
9 | "childrens clothing"
10 | "domestic fuel"
11 | "domestic services"
12 | "e-books"
13 | "foodstuffs"
14 | "hotels"
15 | "medical"
16 | "newspapers"
17 | "passenger transport"
18 | "pharmaceuticals"
19 | "property renovations"
20 | "restaurants"
21 | "social housing"
22 | "water"
23 | "wine"


We are planning to add the options to allow storefront owners to add custom tax rates per country and type. But it won't happen yet (#2436).
</p>

**Comment by ayushgangrade11** [comment]
This was helpful .... Thanks

**Comment by ayushgangrade11** [comment]
> This was helpful .... Thanks

I have added the tax corresponding to countrycode "IN" which is also my 
DEFAULT_COUNTRY = os.environ.get("DEFAULT_COUNTRY", "IN")

I can see these taxes popping up in the taxes section of dashboard. 

Now when I to assign these taxes to some of my products and product types by trying to select an option from the tax_rate drop down ... The drop down is unable to load these options as it usually do for other EU countries. 

Am I missing something ?


![image](https://user-images.githubusercontent.com/22194213/64556218-9f070480-d35c-11e9-8c47-4e30f52f3a54.png)

![image](https://user-images.githubusercontent.com/22194213/64556268-b9d97900-d35c-11e9-9068-4696e51d15f4.png)

![image](https://user-images.githubusercontent.com/22194213/64556313-cfe73980-d35c-11e9-96ea-b78625275b28.png)

I am kind of stuck here .... @NyanKiyoshi  Will you be able to guide me here ?
