### ISSUE TITLE
Page editor doesn't show changes for Dashboard 2.0

### ISSUE THREAD

**Issue by ChanceLeachman** [mirumee/saleor#4580]
### What I'm trying to achieve
… I have a brand new install. I am trying to edit the "About" page from Dashboard 2.0 (Configure -> Pages -> About). 
 
### Steps to reproduce the problem
1. Go to Configure -> Pages -> About
2. Change the text under the Content box.
3. Save
4. See that http://localhost:8000/en/page/about/ is the same as before.

### What I expected to happen
… I expect that the text on the about page changes. 

But anything I change under the "content" box doesn't show on the live version of the website. But the title does correctly change once saved, just not the content. I have made sure that it is marked visible too. Interestingly enough, while the new "content" isn't updated, it is saved so that the next time you view it in Dashboard 2.0, it is still there.

**System information**
Operating system: Linux
Browser: Firefox

**Comment by NyanKiyoshi** [comment]
Hi!

Did you set in your environment variables/settings.py `USE_JSON` to `True` to enable the new formatting? By default we set `USE_JSON` to `False` to temporarily keep compatibility with the old dashboard.

**Comment by ChanceLeachman** [comment]
Thank you for reaching out! 

So, now with USE_JSON enabled, it shows correctly in the original storefront on localhost:8000, but still not the new storefront which I have running on localhost:3000. I've cleared my cache and restarted the server, but it's not showing. When using the original Dashboard the new storefront updates immediately.

**Comment by ChanceLeachman** [comment]
okay, I see I can make a query for it under: 
`page.contentJson` 
But it's not been fully implemented at the moment.

**Comment by ChanceLeachman** [comment]
If you pass it back through Draft-JS again by adding it into the ReactJS page component, then the content can be displayed appropriately.

**Comment by ChanceLeachman** [comment]
Well I now see [storefront #305](https://github.com/mirumee/saleor-storefront/issues/305). But it looks like the products were updated to use the JSON format, but not the pages.

**Comment by ChanceLeachman** [comment]
Alright. Got it all fixed with RichTextContent I believe. Shall I submit a pull request?

**Comment by NyanKiyoshi** [comment]
Good to know. So that's an issue with the storefront 2.0 now, thanks for your contribution! 👍  I'm closing as it's now concerning the other repository and you managed to make the changes https://github.com/mirumee/saleor-storefront/pull/426.
