### ISSUE TITLE
Not all static assets are correctly referenced

### ISSUE THREAD

**Issue by umrashrf** [mirumee/saleor#4583]
### What I'm trying to achieve
All /static/ paths should use {% static %} decorator.

### Steps to reproduce the problem
1. Remove all static content from Heroku (https://demo.getsaleor.com/en/)
2. Put static content only in AWS (https://saleor-demo.s3.amazonaws.com)

### What I expected to happen
No 404 errors

### Screenshots
![image](https://user-images.githubusercontent.com/652326/62352318-e1276580-b4d5-11e9-8f0d-aae82d5f2f30.png)

**System information**
Operating system: Ubuntu 18.04 LTS
Browser: Brave (Chromium)

**Comment by NyanKiyoshi** [comment]
Hi!

It's normal for the storefront and dashboard bundle to be taken from the static files. They don't support S3 (CSS and JS), so 4 files are always served from the server.

**Comment by umrashrf** [comment]
I disagree but let's see what other people are saying.
