### ISSUE TITLE
Missing requirement: draftjs_sanitizer

### ISSUE THREAD

**Issue by umrashrf** [mirumee/saleor#4587]

**Comment by umrashrf** [comment]
Nevermind, the underscore confused me.

**Comment by yxh10** [comment]
@umrashrf , sorry just wondering how you solved it? Just add that module in the requirements.txt?

**Comment by NyanKiyoshi** [comment]
@yxh10 you need to install the newest version of the dependencies. Whether by using `pipenv install` or `pip install -r requirements.txt`.

**Comment by yxh10** [comment]
Thanks for replying. :) I installed those packages manually but will try
with the latest version of the dependencies later with my docker image.
