### ISSUE TITLE
Users can create the same address multiple times

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4592]
### Steps to reproduce the problem
1. Start checkout
1. Set a shipping address A
1. Set a billing address B
1. Place the order
1. Go to your account details
1. Edit the address B to have the same information than A
1. Checkout with A or B (or re-create it through a new address input?)
1. Place the order
1. The order should have failed because the same address exist two times: `get() returned more than one object`

### What I expected to happen
Have an error when updating the address, saying I already have that address.

**Comment by lelmedda** [comment]
Hey, is this project up for grabs, if so what part of the code the bug comes from?

**Comment by NyanKiyoshi** [comment]
Hi! We need to make the address model fully unique and then add a check whenever an address is updated and double check the API and dashboard properly check for the uniqueness.

It's not a really good issue to pickup. But do feel free to create a pull request if you feel like it.

For now I don't have time to do it yet. On my fork I only added the unique constraint on address—https://github.com/NyanKiyoshi/saleor/commit/52ce5b1d691158a896ada5596066d7392d5da493.

**Comment by NyanKiyoshi** [comment]
I mean... I wouldn't say no to socks 😄

**Comment by maarcingebala** [comment]
Core team members will get them as well 😀
