### ISSUE TITLE
Which IP to retrieve from the environment variables

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4595]
Currently we have this code to retrieve an IP:
https://github.com/mirumee/saleor/blob/35d8750ae07bddb57222f5fec3512c2788b56f5c/saleor/core/utils/__init__.py#L54-L58

Which is fine–apart the fact someone can inject any else than an IP.

The question is: should we really trust the `X-Forwarded-For` header? Shouldn't we let the web server handle this part and provide us the IP it believe is correct through `REMOTE_ADDR`?

For example, in nginx, we can get the environment variable `REALIP_REMOVE_ADDR` and thus leave the choice to the user of which IP(s) and header(s) are to be **trusted** and handle the IP **validation**. With the above snippet, we don't leave the choice to the user.

Another case, is when the user has their saleor workers behind a proxy, e.g. CloudFlare. The IP would be set from `CF-Connecting-IP` to `REALIP_REMOVE_ADDR` (nginx).

I believe we could do something like this:
```python
ip_headers = ["REALIP_REMOVE_ADDR", "WHATEVER_APACHE_USES", "REMOTE_ADDR"]

for header in ip_headers:
    ip = request.META.get(header, None)
    if ip and not valid_ip(ip):
        return ip
return None
```

**Comment by patrys** [comment]
What is the risk here? Proxies will append their own IP to the list so until there is a security risk involved, I'd rather err on the side of someone being able to spoof an IP (in which case we could also record the entire chain of IP addresses) than record incorrect addresses for legitimate users.

**Comment by NyanKiyoshi** [comment]
The only issue is when the user wants to set which IP to use. I cannot find an equivalent for Apache. But at least, we could support `REALIP_REMOVE_ADDR` from nginx so the user can provide the client's IP when the server is behind a proxy.

**Comment by patrys** [comment]
Saleor already unpacks `x-forwarded-for` so that case is covered.

**Comment by NyanKiyoshi** [comment]
Yes, but in the case of Cloudflare, for example, `X-Forwarded-For` is not used. Instead, it sets `CF-Connecting-IP` then in the nginx configuration, the IP is checked. If valid, it gets stored into `REALIP_REMOVE_ADDR`.

**Comment by patrys** [comment]
CloudFlare docs suggest that it's supported: https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-
