### ISSUE TITLE
Cannot Deploy to Linode Server 

### ISSUE THREAD

**Issue by NileshArnaiya** [mirumee/saleor#4599]
### What I'm trying to achieve
…
I tried everything in this blog - https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-18-04 and imported saleor into the project and did all the configuration required for saleor to work well

### Steps to reproduce the problem
1. python manage.py runserver ip:port     -->works fine
2. running on nginx I get this error from the logs when i run
 sudo tail -F /var/log/nginx/error.log

2019/08/06 00:12:07 [error] 20666#20666: *3086 no live upstreams while connecting to upstream, client: 172.105.51.116, server: www.buildawn.com, request: "GET / HTTP/1.0", upstream: "http://backend/", host: "buildawn.com"

My etc/nginx/sites-available/saleor 

upstream backend {
    server www.buildawn.com       weight=5;
}
server {
    listen 80;
    server_name www.buildawn.com;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /home/nilesh/saleor/saleor;
    }

    location / {
        include proxy_params;
        proxy_pass http://backend;
    }
}

### What I expected to happen
… Nginx should be running on my IP but gives a 502 bad gateway with upstream error 

Any help will be greatly appreciated as I've been struggling for days and in search of someone who can help me and guide me where I went wrong.

Thank you in advance.

**Comment by NyanKiyoshi** [comment]
What is the backend? `./manage.py runserver`?

You need to use uWSGI or gunicorn (I think we support it).

Also, is nginx on the same instance as the server? If so, it would be better to create a unix-socket file.

Your link describes how to do all that, did you follow everything?

**Comment by NileshArnaiya** [comment]
Yes I followed everything to the teeth and I created all the files that were required, I'm using wsgi and gunicorn as described in the tutorial and yes it is on same instance.

The backend is an upstream that people advised me to replace with proxy_pass
Earlier it was this - 

`proxy_pass http://unix:/run/gunicorn.sock;`
