### ISSUE TITLE
stock is not subtracted after placing an order or payment.

### ISSUE THREAD

**Issue by pcompassion** [mirumee/saleor#461]
I only see stock adjusting in `MoveItemsForm.move_items`  

Hope I'm not missing something obvious..

**Comment by patrys** [comment]
That is true, different stores handle stock differently (stock ino often comes from an external system) and we haven't implemented that part yet. The plan is to do what Oscar does and keep track of "allocated" stock next to the number of items in your warehouse so you know how many you can still sell and how many are reserved for pending orders.

**Comment by pcompassion** [comment]
thank you for the quick answer.

**Comment by patrys** [comment]
@pcompassion The current master branch now has stock allocation!

**Comment by pcompassion** [comment]
@patrys Thanks for the update!
