### ISSUE TITLE
Recurring Order

### ISSUE THREAD

**Issue by SFlame** [mirumee/saleor#4623]
### What I'm trying to achieve
Ability to let customers set an automatic order for set of items they have to purchase regularly, every X time. Maybe with an email/SMS confirmation before placed (user can choose when he sets his auto order)

### Describe a proposed solution
Not a subscription like Stripe billing, I think it should be an automate process inside the platform itself.
User can set an auto-order / mark his order as an auto-order that will be sent to him every X days/months/year. User can choose if he wants to re-confirm every order before paid (via email/sms notification sent to him a couple days before) or not.

**Comment by maarcingebala** [comment]
This is an interesting feature but it's also quite specific. It's not planned to be added in the nearest future. We could consider building it as an external plugin that can be turned on optionally. I can also imagine a dedicated service responsible for creating a recurring order that integrates with Saleor through API.
