### ISSUE TITLE
You cannot add a Weight Based Rate to shipping

### ISSUE THREAD

**Issue by MonikaMrozek** [mirumee/saleor#4628]
### What I'm trying to achieve
In Configure > Shipping Methods > Edit Shipping by Zone > Add Weight Based Rate adds this rate to Price Based Rate. 

### Steps to reproduce the problem
1.  Click Add Rate in the Weight Based card.
2.  Fill out the required fields. 
3. Click Create Rate
> As a result your newly created Weight Based Rate is added into the Price Based Rate card

**Comment by maarcingebala** [comment]
We'll have to check whether the bug is in the backend or it is the frontend sending incorrect data.

**Comment by maarcingebala** [comment]
Duplicated by #4527
