### ISSUE TITLE
Automatically enable tax plugins when configured

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4637]
Currently, users have no idea how to enable vatlayer/avatax. The set the keys as said in the documentation but are not told to update the `PLUGINS = []` settings.

I suggest we do the following:
```python
DEFAULT_PLUGINS = []

if VATLAYER_ACCESS_KEY:
    DEFAULT_PLUGINS.append("saleor.extensions.plugins.vatlayer.plugin.VatlayerPlugin")

if "PLUGINS" in os.environ:
    PLUGINS = get_list(os.environ.get("PLUGINS"))
else:
    PLUGINS = DEFAULT_PLUGINS
```

**Comment by korycins** [comment]
Saleor-docs contains information on how to append new plugin. Personally, I think that modifying settings.py is a bigger effort than benefit.  If someone wants to use avalara or vatlayer, she/he will need to check documentation no matter if we have this `if`, `else`.

**Comment by maarcingebala** [comment]
Closed since it's described in the docs.
