### ISSUE TITLE
Checkout steps list breaks on window resize

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#464]
![image](https://cloud.githubusercontent.com/assets/1870738/12851480/598435be-cc2a-11e5-8eed-20da4f11a091.png)

**Comment by patrys** [comment]
Welp, it used to work before you introduced a step for cart :wink:

**Comment by mociepka** [comment]
Cart step is not a problem:

![image](https://cloud.githubusercontent.com/assets/1870738/12865808/a2016e6e-ccb7-11e5-893a-657b1d4942ac.png)
