### ISSUE TITLE
Graphql query protected data ( orders, customers....)

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor#4641]
### What I'm trying to achieve
Querying the protected data 
### Steps to reproduce the problem

1. Created the token by using query :
_mutation {
  tokenCreate(email: "admin@example.com", password: "admin") {
    token
  }
}_ 
as doc
2. Placed the JWT token as in the screenshot image below
![Capture](https://user-images.githubusercontent.com/40449637/62995006-f2cf1c80-be88-11e9-9afc-ebf864cbe1c0.JPG)

### What I expected to happen
Able to query the protected data

**Comment by maarcingebala** [comment]
The format of headers seems invalid, you don't the `headers` key there. A correct format that you could use directly is just:

```
{
  "Authorization": "JWT token-here"
}
```

**Comment by zatin009** [comment]
@maarcingebala Thanks you
