### ISSUE TITLE
Provide pre-compiled email templates

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4644]
As it was discussed before, to make it simpler for users, we should provide email templates precompiled and add a travis check.

This will also make the first use experience better in the documentation.

**Comment by ruchikabgosain** [comment]
hello, can I take this up?

**Comment by NyanKiyoshi** [comment]
Hi! Sure!

**Comment by NyanKiyoshi** [comment]
Waiting for #5043
