### ISSUE TITLE
Mutation to change user email

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#4648]
### What I'm trying to achieve
To allow users to change their email addresses on saleor. I've searched through the graphql API and it appears there is no mutation for this.

**Comment by maarcingebala** [comment]
Hey, we had a quick internal discussion internally with the team and we agreed that it would be nice to have this feature in Saleor. I imagine this would work as a two-step process (two mutations):
1) Users provide the new email. First mutation checks if it is unique. If yes, it sends the confirmation email to the new address.
2) Users click the confirmation link in the email; once email is confirmed we run the second mutation that actually updates the email in the database.
There was also an idea to send a notification to the old address informing that the email was changed.

I'm trying to think if there are any edge-cases related to that feature. Few things to consider/discuss:
- When the new email address is already used with some anonymous orders, we should probably associate those orders with this user.
- Mailchimp doesn't allow for changing emails, so if we had any integration with it, we should take that into account.

**Comment by maarcingebala** [comment]
Another idea is that users should confirm their password when changing the email.

**Comment by khalibloo** [comment]
That sounds like a good way to approach this. I agree, the first mutation should require the user's password confirmation and should notify the current email address. This would also mean that there should be a way for the user to report to the admins if the change was unauthorized. Ordinarily, that should be easy enough, but how does the admin verify the previous email?

In clearer terms, here's a scenario:
1. Email was changed
2. Old email claims that it was an unauthorized change
3. Admin does not know if the claim is legitimate. The email address is no longer on record

Perhaps the old email can be preserved somehow?

**Comment by maarcingebala** [comment]
Changing the email should generate history events that could be viewed by admins on the user details page in the dashboard. We could use these events to store both email addresses.

**Comment by NyanKiyoshi** [comment]
> Users click the confirmation link in the email; once email is confirmed we run the second mutation that actually updates the email in the database.

At the same time, we could add this check ability to the registration (while keeping it disabled by default). This would help preventing hard bounces.

**Comment by khalibloo** [comment]
Not stale
