### ISSUE TITLE
Just curious why you using whitenoise with uwsgi?

### ISSUE THREAD

**Issue by MechanisM** [mirumee/saleor#465]
Why do you using whitenoise with uWSGI?
uWSGI can serve static assets much faster than whitenoise! 
Just look for options: "static-map" or "static-map2" in uWSGI docs.
http://uwsgi-docs.readthedocs.org/en/latest/StaticFiles.html

**Comment by patrys** [comment]
That's a good question. We used to use gunicorn on Heroku and then switched to uWSGI. This was never updated.
