### ISSUE TITLE
Production Version : PWA

### ISSUE THREAD

**Issue by puneet41824** [mirumee/saleor#4650]
Is there a date when the PWA would be ready for production use? Just waiting to launch the site using the new version. Thanks for all the great work that is going on to make this product great

**Comment by maarcingebala** [comment]
Hey! We're working on new versions of both backend and frontend parts and planning to release them all at the end of September. By that date, we want to have a version of the storefront that would be considered "stable" and ready for production use.

**Comment by puneet41824** [comment]
Do you have any further update to share on this? I checked the latest release statements but did not find any reference for the stable release.
