### ISSUE TITLE
Globaltype.ts

### ISSUE THREAD

**Issue by Pichnyty** [mirumee/saleor#4651]
### What I'm trying to achieve
Want to know where the file is generated from
![Hello](https://user-images.githubusercontent.com/54165288/63153663-15079c80-c039-11e9-9255-f33e44b72ce5.JPG)

### What I expected to happen
Could you please tell me where does the " globalTypes.ts " in "saleor\static\dashboard-next\types " generated from or using which command ?

**Comment by dominik-zeglen** [comment]
`npm run build-types` :)

**Comment by Pichnyty** [comment]
I want to add another new shippingMethod type which is based on the percentage per order.
The below Image is the Image coded that I added

![Capture](https://user-images.githubusercontent.com/54165288/63579397-c750de00-c5bc-11e9-99d6-56a769448ddd.JPG)

and 
This is what I expected to see after running the "num run build-types"  in globalTypes.ts.
![XXXX](https://user-images.githubusercontent.com/54165288/63579517-0da63d00-c5bd-11e9-9573-8edcf41b0b8a.JPG)

But after running the command "npm run build-types" I can't see the what i expected.

Another question : How about the types file like the image below. Does it generate from using the same command "npm run build-types"
![QQQ](https://user-images.githubusercontent.com/54165288/63579799-a472f980-c5bd-11e9-95eb-35da9d83fb34.JPG)

Looking for your reply soon.

**Comment by dominik-zeglen** [comment]
1. You need to rebuild schema first. `npm run build-schema`.
2. Yes, these files are generated per query/mutation

**Comment by maarcingebala** [comment]
Please use https://github.com/mirumee/saleor-dashboard/ repo for issues about the Dashboard.
