### ISSUE TITLE
Upgrade JWT middleware from 0.3.0 to 0.3.2

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4652]
The JWT middleware is no longer a django middleware, thus, upgrading to this new "minor" version is breaking the middlewares. *More* details here https://github.com/flavors/django-graphql-jwt/pull/125.

For reference about why those changes have happened: https://docs.djangoproject.com/en/2.2/topics/http/middleware/

**Comment by adithyabsk** [comment]
Might I suggest changing the `pyproject.toml` field for the `django-graphql-jwt` package? I spent quite a bit of time debugging an issue when the root cause was simply updating the poetry lock dependencies from the project. I can confirm that 0.3.1 does not work with the mainline codebase.

**Comment by NyanKiyoshi** [comment]
@adithyabsk what do you mean? I is already pinned to 0.3.0.

**Comment by adithyabsk** [comment]
@NyanKiyoshi When you run `poetry lock` the dependency will resolve to 0.3.1 because of semantic versioning:

https://github.com/mirumee/saleor/blob/2e94e8df80f305889434f549a4da6abc1257b598/pyproject.toml#L25

**Comment by NyanKiyoshi** [comment]
Ah I see 👍 I will try to see if there are updates about #5149 as it is supposed to fix that issue.
Feel free to open a pull request to fix the `pyproject.toml`!
