### ISSUE TITLE
issue when trying install django-log-viewer to saleor (using Docker)

### ISSUE THREAD

**Issue by xuanmaithanh** [mirumee/saleor#4672]
Hi,

I'm trying to install new python package ("django-log-viewer") to Saleor, by using Docker. It showed the message "install successfully" but later showed "the module not found".

Could you take a look at screenshot below and give me the advice.

Thanks

![image](https://user-images.githubusercontent.com/31360157/63446839-1f74cc80-c465-11e9-965f-a9f00b7382da.png)

**Comment by xuanmaithanh** [comment]
Can someone take a look and give me the advice?

**Comment by xgenvn** [comment]
> Can someone take a look and give me the advice?

Try adding django-log-viewer into pip, and do docker-compose build again

**Comment by NyanKiyoshi** [comment]
@xuanmaithanh wouldn't it be caused by `--rm` by any chance?

I second @xgenvn about adding your new dependencies to the new requirements so they automatically get installed for you.

**Comment by xuanmaithanh** [comment]
hi, many thanks. I will check again and update status to you.

**Comment by xuanmaithanh** [comment]
@xgenvn @NyanKiyoshi : thanks a lot for your advice.
- I tried to add "django-log-viewer" to Pipfile file and build image again with command "docker-compose build" but has the error.

![image](https://user-images.githubusercontent.com/31360157/64061953-322c9580-cc0b-11e9-811c-8876f2b66504.png)

**Comment by xgenvn** [comment]
Personally I see this as not an issue of Saleor. We can bring this discussion somewhere.
I believe the Pipfile and Pipfile.lock should be similar.
In your case, you can first try adding the dependencies directly into Dockerfile, either `pipenv install django-log-viewer` or `pip install django-log-viewer`, after (line 14) `RUN pipenv install --system --deploy --dev`.

Another attempt is to use `docker-compose exec` instead.

**Comment by NyanKiyoshi** [comment]
@xuanmaithanh you need to run `pip env lock` to update the `pipenv.lock` file

**Comment by xuanmaithanh** [comment]
thanks @xgenvn  & @NyanKiyoshi, I've tried to run command `pipenv lock` to update Pipfile.lock but it take too long and get the TIME OUT message.

If I did follow advice from @xgenvn, added `pip install django-log-viewer` to Dockerfile, it can work, but I think that it is just a TEST solution, image we need to add a lot of package :D



![image](https://user-images.githubusercontent.com/31360157/64071694-92721480-cca9-11e9-833e-025e32001cdb.png)

**Comment by xuanmaithanh** [comment]
I'm using `pipenv, version 2018.11.26`

**Comment by xuanmaithanh** [comment]
Hi,

I've updated Dockerfile a bit, change from pipenv to pip, and it works perfectly (easy to add new package).

Many thanks and we can close this issue 

![image](https://user-images.githubusercontent.com/31360157/64074239-04ab1f00-ccd3-11e9-8750-b1800ae36445.png)
