### ISSUE TITLE
Manual order: Discount get's deleted

### ISSUE THREAD

**Issue by jstrnbrg** [mirumee/saleor#4675]
### What I'm trying to achieve
I'm trying to create a manual order via the Dashboard and mark it as paid and fulfil it. 

There are a couple of problems:
1. In order to mark an order as paid it needs to have a shipping address (at least a country, name, surname) which isn't really necessary I would say. (Could be a overhand of a sample product in our offices). 
2. When I apply I discount when adding a manual order, click "create order" and then want to edit the shipping address, in order to be able to mark it as paid (due to problem 1), the discount get's deleted and there is no way to re-add a discount. That means I need to cancel the order and re-create it again, this time with the shipping address already added while creating the manual order. Which brings us to the next problem: 
3. In order to apply a discount to a manual order you must first add the shipping address and then apply a discount. If you do it the other way around the discount gets deleted again and needs to be re-applied. 

### Solution: 
 Fix bug that deletes discount when editing/adding a shipping address (solves 2 and 3) 

### Steps to reproduce the problem
1.  Create manual order
2. Add product
3. Apply discount
4. edit shipping address

### What I expected to happen
That no matter what I do to the shipping address the discount stays as is. 

**System information**
Operating system: Mac
Browser: Chrome

**Comment by jstrnbrg** [comment]
@salwator has this been addressed/looked into? Thanks :)

**Comment by maarcingebala** [comment]
Hey, we haven't looked into this issue yet. From what I see it affects the old dashboard which we're not developing anymore and we're planning to replace it entirely with Dashboard 2.0 by the end of the year. Creating discounts for manual orders is not yet supported in Dashboard 2.0, but I hope it will be fixed in incoming sprints.

**Comment by jstrnbrg** [comment]
Thanks for getting back to me and letting me know. We are planning to update to Dashboard 2.0 soon. 
When are you planning to make the next release? Do you think that functionality will be included in the next release?

**Comment by maarcingebala** [comment]
There is a lot of unreleased changes now and we're planning to at the end of October. I'm not sure if we'll manage to implement those changes in views related to order management, as we're focused on improvements to product management and some of the new features, such as webhooks and service accounts.
