### ISSUE TITLE
Add ability to list abandoned carts and checkouts

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#468]
I propose to save user cart in DB. Now we have two carts implementation `SessionCart` and `Cart`, both of them are stored in session so we don't knew how many abandoned carts we have in store.

We can easily save `Cart` object into DB instead of session without breaking current API and performance. Going forward we can use DB cart object as checkout storage. In this approach if `checkout_data` is not empty it means that we have not finished checkout.

With this approach we can list not finished checkouts and abandoned baskets in user profile.

As we discussed earlier one big issue will be synchronization `SessionCart` with `Cart`. If the same user starts more then one session, (many browsers open) more than one `SessionCart` will be created. If you add product in one window yours `SessionCart` won't be updated in second one.

Solution can be persistent user session cart. Maybe we will save user session cart in cache instead of session? What do you think @patrys ?

**Comment by mociepka** [comment]
I started playing with a model cart approach and the current session cart and I come up with conclusion that we over complicated things. Current session cart problems that I found:

* Session cart was designed for performance, but creates synchronization issue. We never refresh it so we can end up with basket with wrong prices or even basket which threw 500 error when products has been deleted.
* Session cart doesn't work with discounts. Now when we have discounts synchronization issue is even bigger.
* Different baskets in different browsers. If I open second browser with different session even if I am logged in user I get two different baskets on the same machine.

I want to start new discussion with problem definition that session cart try to solve at first place:

> We don't want to do a lot of SQL queries for cart in all views.

In others Ecommerce solutions we always end up with cart which query for products, products variants, products attributes, images etc. That slow down all views. Session basket looks like good solution because it always do one query so we dump the cart model approach. But now we end up with two session carts, one simple which has only basic information and second one which query DB for related data. And any of them can be easy aggregate for statistic.

I propose to try another round with the model cart. If we do it right it will cost us only one additionally query for all views. And solve all current problems.

## Problem redefinition

In my opinion problem exists only is in templates and only with use cease when we want to be able to show cart products on all sites (ex. drop down with cart summary). On sites showing only cart count that problem doesn't exist. It doesn't exist even on sites with cart list but cart content should be fetch by AJAX (that is the best way to do it in my opinion). With previous use cases in mind I propose new problem definition:

> We don't want to be able to do additional cart queries in templates.

If we pass cart object from ORM directly to templates there will be always problem with additionally queries. It is always tempting do stuff like iteration threw relation in templates, it doesn't requires any changes in views.

### Solution
We can use session cart approach in here. Now in session we are saving only data necessary for proper products list rendering: quantity, product name in some cases product image link. So we can for instance pass values list instead of queryset. That will eliminate queries in templates.

Values list is only a proposition we can use any other API. But it should be easy to use with templates.

If we agree on the model cart approach I will describe how I want to implement the whole functionality. Feedback needed @artursmet , @bogdal , @elwoodxblues , @patrys.

**Comment by patrys** [comment]
Definition of done:

* [ ] get rid of SessionCart
* [ ] in the context processor only fetch the aggregated total number of items in cart
* [ ] make sure templates outside of cart and checkout only use the aggregated total
* [ ] decide which parts of the test suite are relevant
* [ ] ensure we have full unit test coverage of Cart and CartLine
* [ ] propose an integration testing scenario if you can come up with one
