### ISSUE TITLE
Digital products not being automatically fulfilled

### ISSUE THREAD

**Issue by samuelOsborne** [mirumee/saleor#4682]
### What I'm trying to achieve
Automatic digital product fulfilment

### Steps to reproduce the problem
1. Fork the repo, create a new product type and set shipping to false, product type should say digital
2. Create a new product and set to this new type, however when checking in the database under producttype, the is_digital of this product is still set to false for some reason so I set it to true.
3. In the sitesettings I set automatic_fulfilment_digital_products to true also
4. When going through the purchase of this new product, the order status does not auto fulfil and stays on unfulfilled.

### What I expected to happen
On completion of payment that digital products auto fulfil when correct site settings are met

**System information**
Operating system: Windows
Browser: Chrome

Cheers

**Comment by korycins** [comment]
Hi @samuelOsborne 

1, 2 - Keep at mind that Dashboard2.0 doesn't have all fields mandatory for using digital products. We are working on it.
I see that naming convention in product_type can be misleading. Type `Digital` on `product types` page is connected with `is_shipping_required` only. 
`is_shipping_required` is not dedicated exactly to the digital product.  
 Digital product type needs to have `is_shipping_required` == False and `is_digital` == True. 
3 - You can use site_settings and custom config for the given digital product.
4 - I've checked the flow and it seems that update of order's status was missing after automatic fulfillment. 
Thanks for reporting this!

**Comment by samuelOsborne** [comment]
Thanks for the explanation, sorry for being a pain but does your pull request fix the auto-fulfilment or is there something else to be implemented before it is usable?

Thanks for your help

**Comment by korycins** [comment]
From API's view - Auto-fulfilment works (I've tested it today), but we didn't update an order status after automatic fulfillment. 
From the Dashboard2.0's view - it misses most of the fields mandatory to set up a product as digital.

**Comment by samuelOsborne** [comment]
Well I implemented your commit in order/utils.py, double checked that my product type has is_shipping_required=false and is_digital=true in my database and upon ordering the item with this type it is still stuck on unfulfilled in dashboard2.0 after a fully charged purchase?

**Comment by korycins** [comment]
Can you run `order.utils.order_needs_automatic_fullfilment` on your order? 
This method determines if the order should be automatically fulfilled.

**Comment by samuelOsborne** [comment]
How would I go about to do that?

**Comment by korycins** [comment]
You can do this from python shell

**Comment by korycins** [comment]
https://ancient-woodland-27187.herokuapp.com/en/products/digital-product-119/
You can check this instance. I've created a product with digital content. Order is automatically fulfilled. Steps to reproduce:
1. Update siteSettings over API (`shopSettingsUpdate` ) with `automaticFulfillmentDigitalProducts: true`
2. Create product Type over API `productTypeCreate(input:{name:"digital_type", hasVariants:false, isShippingRequired:false, isDigital:true, })` with isDigital == true and isShippingRequired==false
3. Create Product from dashboard  and assign it to created  digital productType.
4. Upload digital content by using mutation `createDigitalContent` and assign it to a digital variant. 
5. Proceed checkout. Order with digital content will be automatically fulfilled and the user will receive an email with the unique link to download his digital content. ( keep in mind that sending an email doesn't work on test saleor that I've shared above)

**Comment by samuelOsborne** [comment]
I just checked it out and saw that it works on your instance so thats cool, just having trouble trying to implement in on my side since i've not used GraphQL yet.

Is there a difference between using the API to change settings over using pgAdmin to directly change  database values?

**Comment by korycins** [comment]
If you are changing `SiteSettings` directly in DB there is a chance that working instance of Saleor will not have such data. Try to restart Saleor after you change `SiteSettings` or better us graphql API to change settings.

**Comment by korycins** [comment]
One note. You need to have digital content assigned to variant. I’ve uploaded it over API and assigned to digital product_variant on my Saleor's instance. Without that, it won't automatically fulfill your order.

**Comment by samuelOsborne** [comment]
Ah! Having digital content assigned fixed it straight away! However its going to be a pain to manually add the product_digitalcontent to every digital product I want to add, I'll have to modify the view that manages adding products and to a save to digitalcontent then?

Thanks for all your help this is great, I owe you one.

**Comment by korycins** [comment]
Yes, it can be painfull. We will extend a dashboard2.0 functionalities in the future. This will be helpful for using this feature. 
If you use dashboard1.0, this will be helpful for you: https://github.com/korycins/saleor/tree/digital_content_old_dash
Keep in mind that this is not tested and branch has over 5 months.
