### ISSUE TITLE
Variant filters not working

### ISSUE THREAD

**Issue by Tiagorsa** [mirumee/saleor#4685]
### What I'm trying to achieve
Filters by vairant attribute

### Steps to reproduce the problem
When i selected a variant attribute it gives the following message: 

"Sorry, no matches found for your request.
Try again or shop new arrivals."

The product matches all the variant types but it is not showing in the search result's page.

### What I expected to happen
Show the products that matches the selected variant attributes.

### Screenshots

![Captura de tela de 2019-08-26 20-09-25](https://user-images.githubusercontent.com/8277086/63729615-4b65c880-c83e-11e9-8138-90f769892717.png)

**System information**
Operating system:  Ubuntu 
Browser: Firefox and Google Chorme

**Comment by NyanKiyoshi** [comment]
Hi! Thanks for the report, it has been broken in https://github.com/mirumee/saleor/pull/4351/commits/fb5983e0064d0fe6e990a442e87d039a8ac8c0d6. Once #4663 is merged.
