### ISSUE TITLE
Saleor - Dashboard Next - Default currency changed to 'PTS-'

### ISSUE THREAD

**Issue by L-Leandro** [mirumee/saleor#4686]
### What I'm trying to achieve
I would like to set another type of coin/currency (as I am doing a project based on points, not actual money). 

### Steps to reproduce the problem
So if I do for example on the settings file:
DEFAULT_CURRENCY = os.environ.get("DEFAULT_CURRENCY", "PTS")
It will show the symbom 'PTS', which is what I want. But if I set for example to 'PTS-', the dashboard-next does not work anymore (I think is not able to reload the page).

### What I expected to happen
I would like to set my own curreny symbol (for points). Later I would like to use not only 'PTS-', but may end up using some complex characters (like https://www.compart.com/en/unicode/U+1F17F), and dashboard-next does not like that.

**System information**
Operating system: windows and linux
Browser:

**Comment by maarcingebala** [comment]
`DEFAULT_CURRENCY` expects a valid ISO 4217 three-letter currency code. I guess `PTS-` isn't a valid one.

**Comment by L-Leandro** [comment]
Hi,

thank you for your answer. 

If I set with for example 'PTS', or even 'ABC', it works.

I just tried with 'PT-', and did not worked, so it works in some cases, even if is not a valid currency. It does not work with some characters (this happens only on Dashboard-next, all the other pages work fine).

Thansk!
