### ISSUE TITLE
Refactor mutations, types and bulk mutations per group

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4688]
As we are extending the logic, some files are beginning to exceed the 1k lines.

I suggest we create a task to split the complex parts of the API.

For example:
- **products**
  - mutations
    - attributes
    - categories
    - collections
    - digital content
    - images
    - products
  - types
    - attributes
    - categories
    - collections
    - digital content
    - images
    - products

**Comment by korycins** [comment]
We should split tests file also. For now, we have single file for the most of the api's modules. Like `test_product`
