### ISSUE TITLE
docker-compose for local development returns 404 on static assets

### ISSUE THREAD

**Issue by nigfinch** [mirumee/saleor#4696]
### What I'm trying to achieve

Run Saleor in local dev on MBP using docker compose

### Steps to reproduce the problem

I followed the steps as per official docs to get a local dev up and running with docker-compose
https://docs.getsaleor.com/docs/customization/docker/

When I run "docker-compose up" all containers are brought up without error but when i go to localhost:8000 none of the css, images etc. are available 

### Screenshots

![image](https://user-images.githubusercontent.com/4235665/63889323-acc19f00-c9d8-11e9-84d3-3b86ebbd03f2.png)

**System information**
Operating system: MAC Book Mojave
Docker Version 2.1.0.1
Compose: 1.24.1

docker-compose.override.yml

`
version: '2'

services:
  web:
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./saleor/:/app/saleor:Z
      - ./templates/:/app/templates:Z
      - ./tests/:/app/tests
      # prevents overshadowing of build-time assets
      - /app/saleor/static/assets
      - /app/templates/templated_email/compiled
      # shared volume between celery and web for media
      - saleor-media:/app/media

  db:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379

  celery:
    volumes:
      - ./saleor/:/app/saleor:Z
      - ./templates/:/app/templates:Z
      # prevents overshadowing of build-time assets
      - /app/templates/templated_email/compiled
      # shared volume between celery and web for media
      - saleor-media:/app/media

volumes:
  saleor-media:
`

Thank you !

**Comment by funny-guy** [comment]
@nigfinch have you find out the solution? i got an exact same problem...

**Comment by mayank-budhiraja** [comment]
No, stil

> @nigfinch have you find out the solution? i got an exact same problem...

Still looking for the solution
