### ISSUE TITLE
Saleor - Gift Cards

### ISSUE THREAD

**Issue by L-Leandro** [mirumee/saleor#4703]
### What I'm trying to achieve
I would like to use Saleor, for a points based system.

### Describe a proposed solution
I can see on Saleor database, a table called gift_card. Is this table already being used for something? I don't see how your existing Gift Card system works. Or maybe is a new feature that still not finished?

### Other solutions I've tried and won't work
I have tried to use the voucher, but that is not related with gift cards.

**Comment by maarcingebala** [comment]
Hey, we've partially implemented this feature, but it's only available in the API and there is no frontend support yet. It works very basically - you can issue a gift card with a code and some balance, assign it to a customer email etc. There is support for using gift card codes similarly to discounts in the checkout. 

In the future we wanted to add ability to buy gift cards as products in the storefront. We were also considering rewriting them to fit into payment's architecture so they can be used just as other payment methods.

**Comment by maarcingebala** [comment]
Closing this for now. We will open dedicated issues when we start working on the frontend part.

**Comment by nusdavid** [comment]
`Closing this for now. We will open dedicated issues when we start working on the frontend part.
`

Hi @maarcingebala 

Any updated yet? I'm looking forward to this feature
