### ISSUE TITLE
Filter is not working

### ISSUE THREAD

**Issue by krlalit** [mirumee/saleor#4706]
I have installed the project in my ubuntu OS. It's installed successfully but I am facing filter problem by-product variant in product listing page filer down not working with example data. 
The filters also not working by entering direct URL with product variant
Please let me know how to fix this issue

**Comment by NyanKiyoshi** [comment]
Hi @krlalit, I believe you are talking about this issue https://github.com/mirumee/saleor/issues/4685? It was fixed in a pull request and should be merged into master soon (the bugged changes were not released yet).

**Comment by maarcingebala** [comment]
Let's close this if this is a duplicated issue.
