### ISSUE TITLE
How to disable category?

### ISSUE THREAD

**Issue by ruszhov** [mirumee/saleor#4712]
I can change category or delete. I want to make it disabled. Is there any suggestion to make it?

**Comment by maarcingebala** [comment]
I'm not sure I understand your use case. How do you want to disable the category? In Saleor category is a required field for a product, you cannot disable it by default.

**Comment by ruszhov** [comment]
I just wonder is there any way to make category unpublished (like product)? Or just hide menu item that category linked on. Let say I have category "Christmas" and I want to make it published in winter months.

**Comment by petedermott** [comment]
I think the general idea is that sometimes you want a category to be hidden, this could be because you are looking to populate it with products before putting it live or it is an targetted SEO landing page that you may want to be found by search engines but not linked directly from your store.

**Comment by AlexandrST** [comment]
> I just wonder is there any way to make category unpublished (like product)? Or just hide menu item that category linked on. Let say I have category "Christmas" and I want to make it published in winter months.

It seems to me that for such purposes it is better to use collections, rather than categories.
