### ISSUE TITLE
column "variant_name" of relation "order_orderline" does not exist

### ISSUE THREAD

**Issue by likewhoa** [mirumee/saleor#4713]
### What I'm trying to achieve
Complete checkout. Currently stuck at checkout/summary before exception is triggered.

### Steps to reproduce the problem
1. setup saleor (no sample data)
2. add a few products
3. continue to checkout

### What I expected to happen
…

### Screenshots
[traceback.txt](https://github.com/mirumee/saleor/files/3572050/traceback.txt)

**System information**
Operating system: linux
Browser: chromium

**Comment by maarcingebala** [comment]
Did you apply all migrations? This field was added few days ago.

**Comment by likewhoa** [comment]
Aye forgot this and I just got pull and merged. Thanks for reminder
