### ISSUE TITLE
Hi, can i host my customized Saleor on https://www.a2hosting.com

### ISSUE THREAD

**Issue by Menks** [mirumee/saleor#4718]
Hi i searched an adequate (in price and technologies (python and postgreSQL) Hosting provider to host my Saleor and i found this Provider.
https://www.a2hosting.com/web-hosting/compare

Please can someone Help me by thelling me if it is possible and wath is the mimimum offer (LITE ,SWIFT,TURBO) possible to choose ?

![Capture1](https://user-images.githubusercontent.com/6191474/64292295-9f1c9400-cf59-11e9-90d6-f969fc3fb526.PNG)

![Capture](https://user-images.githubusercontent.com/6191474/64292294-9f1c9400-cf59-11e9-8fe5-874ea9fe1245.PNG)

**Comment by NyanKiyoshi** [comment]
Closing in favor of #4704, let's just continue the discussion there :+1:
