### ISSUE TITLE
Enable mypy on CI

### ISSUE THREAD

**Issue by salwator** [mirumee/saleor#4720]
### What I'm trying to achieve

I would like to have no errors in mypy and take advantage of type hints to discover bugs as soon as possible.

### Describe a proposed solution
- [ ] Add _mypy_ check as separate step in CI or extend flake8 with additional check.
- [ ] Fix all existing type issues and keep it green forever

**Comment by krzysztofwolski** [comment]
Also worth considering - pyright. I use it with VSC and like it more than mypy. I get faster and better errors with it. But it's probably less stable than mypy which is more 'mature'

**Comment by salwator** [comment]
@maarcingebala this issue should not be auto-closed.

**Comment by maarcingebala** [comment]
No worries- this issue is scheduled for our second December's sprint.
