### ISSUE TITLE
What is the difference between a product's "purchaseCost" and its variants' "cost price"?

### ISSUE THREAD

**Issue by zadigus** [mirumee/saleor#4724]
### What I'm trying to achieve

I am working with saleor release 2.8.0.

I am trying to build up my products list in a consistent way. In particular, I need a clear relationship between what a product cost me and how much it will cost my buyers.

In the GraphQL API, I can find the field `purchaseCost` in the `product` query. That field is protected by the `manage_products` permission. Is that `purchaseCost` the amount I paid as a vendor to get that product in my shop?  To be more specific, let's say I have an e-commerce platform grouping the products I get from some people. I want to gain money on those products, so that I sell them on my platform a bit more expensive than what those people sold them to me. Is the `purchaseCost` the price those people sold me their products? 

I can also find a field `costPrice` in the `variants` field of the `product` query. That field is not protected with the `manage_products` permission. I expect this field to be related to the product's `purchaseCost`. Therefore I expect that field to be protected by the same permission.

But I might've misunderstood the purpose of those fields. What is the difference between a product's `purchaseCost` and a its variant's `costPrice`?

My assumption until now is that `purchaseCost` has the same relationship to the variants' `costPrice` as the product `priceRange` has to the variants' `pricing`. If that holds true, however, I don't understand why the variants `costPrice` isn't protected with the `product.manage_products` permission.

**Comment by NyanKiyoshi** [comment]
`purchaseCost` is a money range. The lowest purchase cost to the highest one of the product variants.

They should definitively be protected, yes. Thank you for the issue!
