### ISSUE TITLE
Why are product thumbnails of products without images bigger than asked for in the graphql query?

### ISSUE THREAD

**Issue by zadigus** [mirumee/saleor#4725]
### What I'm trying to achieve
```
{
  products(first:100, after: "", filter:{
    isPublished:true
  }) {
    totalCount
    edges {
      node {
        thumbnail(size: 500) {
          url
        }
      }
    }
  }
}
```
Note the `size: 500` above.

### What I expected to happen
```
{
  "data": {
    "products": {
      "edges": [
        {
          "node": {
            "thumbnail": {
              "url": "http://localhost:8000/static/images/placeholder500x500.png",
            },
          }
        },
        ...
```
Note the `500x500` in the above url.
### What I get instead
```
{
  "data": {
    "products": {
      "edges": [
        {
          "node": {
            "thumbnail": {
              "url": "http://localhost:8000/static/images/placeholder540x540.png",
            },
          }
        },
        ...
```
Note the `540x540` in the above url. This is not `500x500`, which is what I would've expected. Also, the actual image size is `540x540` and not `500x500`, i.e. it is not only a problem with the image's filename. 

Is that behavior really intended? If I ask for a thumbnail of some size, I expect to be provided with a thumbnail of that very size, not something else. Is there a reason for that behavior?

I am working with saleor release 2.8.0.

**Comment by maarcingebala** [comment]
Hey, this behavior depends on these settings in `settings.py` file:
- `VERSATILEIMAGEFIELD_RENDITION_KEY_SETS`
- `create_images_on_demand` in `VERSATILEIMAGEFIELD_SETTINGS`

With those settings, you can define if images should be generated on-demand or you want to allow only a few available sizes. If this is enabled, then the algorithm will try to match the closest size to the one that you requested. This is meant to prevent users from generating random sizes on demand as this would be inefficient for production machines.

Please check if this configuration works for you and you can adjust it to your needs.

**Comment by zadigus** [comment]
Ok, sure thing. I was not aware of those parameters, thank you for the hint. The philosophy behind them is totally reasonable. Now I understand why I am getting those strange sizes instead of those I am asking.
