### ISSUE TITLE
getting error while doing payment with stripe on saleor 2.0 version

### ISSUE THREAD

**Issue by ajaypratapyadav** [mirumee/saleor#4727]
**I'm trying to do checkout process in saleor 2.0 version** using stripe payment gateway but when i submit payment for its return me error "Oops, it looks like we were unable to contact the selected payment service"

The stripe.js version is changed, i that causing the issue ? if so the please give me the solution of this.
Actually i want to implement Strong Customer Authentication(SCA) but not able to do that.

Please provide any solution ?
![payForm](https://user-images.githubusercontent.com/31924970/64517654-67716b80-d30e-11e9-89c8-9da399829c9b.png)
![errorReturned](https://user-images.githubusercontent.com/31924970/64517672-6f311000-d30e-11e9-9339-69455787437b.png)

**Comment by NyanKiyoshi** [comment]
Hi, an error should have been logged into the Saleor console. A stacktrace should have been written into it and should help understand what is wrong.
