### ISSUE TITLE
Stripe with SCA with stripe.js

### ISSUE THREAD

**Issue by ajaypratapyadav** [mirumee/saleor#4737]
### Need to integrate SCA with stripe.js
I'm using saleor 2.0 old version in that saleor were using stripe.js v2 for payement
but right now stripe comes with new rules  Strong Customer Authentication (SCA)
**So, i need to integrate SCA with stripe.js on application but not be able to do that**

### Stripe document 

I followed their document that they have mention over their web site, but **how saleor has implemented in saleor 2.0 old version is need to be totally customise**  

### stripe.js v3 and their doc.

I tried stripe.js v3 and their doc. and try to integrate SCA but not able to do that.

**If anyone have done Stripe with SCA payment method by using stripe.js, please give me solution how can i achieve this**

I will be great thankful to you
Waiting for positive response   

Thank you

**Comment by ajaypratapyadav** [comment]
> It is already done. Check this PR - #4606

@korycins It is implemented in new version of saleor, but in old version payment module is not there.
 
how can do these process ?
can you please guide me?

**Comment by korycins** [comment]
#4606 implements stripe with SCA on the backend side. You can use it to understand what changes need to be applied on the Saleor side.

**Comment by ajaypratapyadav** [comment]
@korycins But on saleor, while implementing new code its also not working, giving error of create_form
I can see in new saleor version stripe.js code is removed 
there is not stripe.js in new version, it was in saleor 2.0 version
because implementing new copy in old running website is very time consuming and lengthy task as you suggested above
If i want to do with stripe.js what are the changes need to do ?
Please help me out in this ?

**Comment by salwator** [comment]
@ajaypratapyadav please read relevant [stripe documentation](https://stripe.com/docs/payments/payment-intents/web):
Current stripe implementation will create payment intent for you. In case of _action_required_ you will need to confirm payment via extra mutation.
