### ISSUE TITLE
Why are taxes dynamically changed ?!

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#4743]
We are having a hard time trying to understand the tax system implemented in Saleor. We are a German shop - meaning, that we ALWAYS have to add 7% to our product, as it's taking the reduced "foodstuff" tax rate. We have our own storefront using graphQL to communicate with the saleor backend - and now all our created orders show 6% as tax rate .. ?! I have no idea why.
When making some tests with the old saleor storefront now in Spain, I see a tax rate of 4%.. what exactly is the thought behind this? This is just totally wrong, as we have to pay taxes in the country our company is registered, no matter from where the user is ordering ..
Can we change this behaviour?

**Comment by korycins** [comment]
What version of Saleor do you use?
Do you use Avalara or Vatlayer?

**Comment by korycins** [comment]
AFAIK taxes should be paid based on the customer’s country.
https://europa.eu/youreurope/business/taxation/vat/cross-border-vat/index_en.htm

**Comment by J4NSS3NS** [comment]
True , link to eu rules does apply for your shop....BUT problems come when customer John Fake enters wrong information , the shopowner can be held responsible for not charging correct vat ...

I am looking to implement vat correctly. I think I need companyvatnumber  in account, then try to let vatlayer lookup the vatnumber ( you only know it is correct vatnumber, John Fake can stil enter vatnumber of random company) then manually set checkbox to true if company /user is legit. Intil checkbox is true charge your local Vat for not having problems with local taxadministration.

I try to make this work but I have problems with vatlayer API ... I think there are alot questions/problems/workarounds regarding Vat, maybe Saleor can try to group these comments so we can workout solution together

**Comment by JannikZed** [comment]
well - it should be pretty similar for all European shops. First of all, always charge the local taxes.
what you are talking about @J4NSS3NS is the case when a non-european business is ordering something. They might eligible for tax free ordering if they are able to enter a valid VAT number. But only in the case of a non-european company. 
This issue is pretty important for us, as we expect to have several orders from Belgium, Netherlands etc. this year but we are charging in the wrong tax rate! Could we get a quick fix for that already?

**Comment by J4NSS3NS** [comment]
Looks if your orders get tax of country where ordered... Spain has 4% vat on food, belguim had 6%.... if your shop is germany based but you ship it to belguim for belgain costumer the 6% will be added, see link koricyns ...

**Comment by JannikZed** [comment]
```
Selling goods to the final consumer in another EU country
If you sell goods and send them to consumers in another EU country, you usually need to register your business there and charge VAT at the rate applicable in that country - unless the total value of your sales to that country within the respective tax year falls below the limit set by the country.
``` 
-->  and these limits are in most cases not less than 30000€ !! So you only charge taxes of the foreign country if you registered your business there and sell more than 30k € per year .. most shops won't hit these thresholds - right?   This is called **"distance sale"**. 
It's also described here: https://www.avalara.com/vatlive/en/eu-vat-rules/distance-selling/internet-and-ecommerce-vat.html
```
For example, a German retailer sells handbags at the German VAT rate of 19% to French customers instead of French VAT rate of 20%
```
Also our tax accountant confirmed us, that we need to charge the regular german taxes when selling to private customers abroad in the EU. And that's the case for the whole European union, so more people should be interested in having that working correctly.

Here from the British government (as long as they are still EU ;) ): https://www.gov.uk/guidance/vat-exports-dispatches-and-supplying-goods-abroad#how-to-charge-vat-to-someone-in-another-eu-country

**Comment by korycins** [comment]
Hi @JannikZed How did you solved the problem? I assume that the fastest way was to create custom tax plugin or fulfilled database with tax information.
I reponed the issue as we need to solve this problem.

**Comment by JannikZed** [comment]
we just disabled taxes in saleor and just show gross prices. Invoices are created in a different software anyhow and there we calculate the taxes, or actually we always use the German taxes, as we do long distance selling only. 
When disabling taxes in general it's also not shown in the order confirmation E-Mails. We send out invoices to our customers afterwards with the taxes.
