### ISSUE TITLE
Disable sales: make the client see the products (without the ability to buy or login/signup) and the admin  load products to show (without price, quantity and so on).

### ISSUE THREAD

**Issue by marcoautiero** [mirumee/saleor#4747]
### What I'm trying to achieve
A client wants to setup an ecommerce website, but not immediately. For now he just wants a website to show his products, without giving the users the possibility to buy or to login/signup. By his side, he desires a light backend: only the possibility to load his categories of products and the products, with their images and characteristics; no prices,no quantities ecc ecc.

Then, in the future he wants the ecommerce on the same website.

I would like to know if currently Saleor has this ability: to suspend (for the customers and the admin) the ecommerce features, making the website a simple showcase of products. And then to eventually switching on the ecommerce features again.

Thank you

**Comment by korycins** [comment]
Have you tried to reduce quantity of products to 0? If you do that, you will receive products without prices.
Examples:
![image](https://user-images.githubusercontent.com/23282005/65243064-e1aca780-dae7-11e9-93f7-d89fc41834bc.png)
![image](https://user-images.githubusercontent.com/23282005/65243078-e8d3b580-dae7-11e9-84e1-e5c1ec0ad679.png)

**Comment by marcoautiero** [comment]
> Have you tried to reduce quantity of products to 0? If you do that, you will receive products without prices.
> Examples:
> ![image](https://user-images.githubusercontent.com/23282005/65243064-e1aca780-dae7-11e9-93f7-d89fc41834bc.png)
> ![image](https://user-images.githubusercontent.com/23282005/65243078-e8d3b580-dae7-11e9-84e1-e5c1ec0ad679.png)

well, this could be a fast solution for a single product, but I would prefer a switch that could completely change the user (and admin) experience; if I don't use the website as an ecommerce I could not need of many sections in the backend; and for the same reason, as user, I could not need to login/signup and several other things.

I understand that this is not an actual feature, but I wonder if there would be other people interest to develop it.

**Comment by korycins** [comment]
I don't think that we would like to have such a feature. I don't think that online shops want to turn off the possibility to sell their products. 
If reducing the quantity to 0 doesn't fit in your requirements, you could try to use our PWA storefront - https://github.com/mirumee/saleor-storefront but you will need to modify source code for your requirements
