### ISSUE TITLE
Custom Tax Rate based on province

### ISSUE THREAD

**Issue by IAmNatch** [mirumee/saleor#4755]
### What I'm trying to achieve
Currently, there is no way to set tax rate based on province. Since in Canada the tax rate is set based on which province the purchaser lives in, this step is necessary. I've noticed [here](https://github.com/mirumee/saleor/issues/4574#issuecomment-516877931) that you can add a custom country code, but for Canadian taxes to work we need to base it on province. 

Is there specific function that could be subclassed to handle this logic without writing an entirely new plugin?

**Comment by korycins** [comment]
Have you tried to use Avalara plugin? Maybe this is a solution for you. In other case, I assume that you need to write a new plugin.

**Comment by martcot** [comment]
Hi, I have the same problem here! @IAmNatch did you find any solution?

**Comment by martcot** [comment]
I will do my own plugin to manage Canada taxs thanks.

**Comment by IAmNatch** [comment]
I ended up going with Django-Oscar as it had more documentation and a wider
breadth of examples for such situations. It still required custom logic,
but seemed but manageable.

Definitely post here in the future. Saleor is a framework I’d love to work
with in the future.

**Comment by maarcingebala** [comment]
I thought Avalara cover cases like calculating taxes per province. Anyway, we'd appreciate some feedback in the future on this to improve the taxes system in Saleor.
