### ISSUE TITLE
preauth vs waiting, release vs refund

### ISSUE THREAD

**Issue by pcompassion** [mirumee/saleor#477]
I'm trying to understand what those are.

What do `preauth` and `wating` status mean?

How do `release` and `refund` differ?

Looking at source code, I find only few of payment backends (cybersource, stripe, paypal) does use `preauth` status, but only `preauth` state payment can be captured or released.

**Comment by patrys** [comment]
Preauth is when the card was authorised but not yet charged. The money is often locked by the bank and you usually have around 14–30 days to charge up to the amount preauthorised. You cannot refund as no money was transferred so far but you can release to indicate that you will never charge (and unlock the money).

Waiting is an indicator that we're waiting for a third party service to tell us whether a payment succeeded or not.

**Comment by pcompassion** [comment]
Thank you!
