### ISSUE TITLE
Can't see filters on category page

### ISSUE THREAD

**Issue by amorino** [mirumee/saleor#4771]
### What I'm trying to achieve
See filters on category

### Steps to reproduce the problem
1. Setup project
2. Don't use the prepopulated_data

### What I expected to happen
Be able to see filters using attributes on category page, I added multiple products with variants, type of products in a category.

### Screenshots
<img width="1184" alt="Screenshot 2019-09-27 01 41 56" src="https://user-images.githubusercontent.com/1342805/65747802-03012b00-e0c8-11e9-91b5-7d038747b834.png">

**System information**
Operating system:  MacOS 10.14.6
Browser: Chrome

**Comment by NyanKiyoshi** [comment]
Hi @amorino! Did you pull the latest master? This should have been fixed a few weeks ago by https://github.com/mirumee/saleor/pull/4705.
