### ISSUE TITLE
Error on checkoutPaymentCreate GraphQL

### ISSUE THREAD

**Issue by srendon** [mirumee/saleor#4775]
## What I'm trying to achieve
I'm traying to create a checkout payment throught `checkoutPaymentCreate` with a GraphQL request. There is an error that says: `Couldn't resolve to a node: 41eb582e-9d70-4195-a71a-cc41b4019e09` but that `checkoutId` exists on the `checkout` table. 

### Request:
```
mutation{
  checkoutPaymentCreate(checkoutId: "41eb582e-9d70-4195-a71a-cc41b4019e09", input:{
    gateway:"DUMMY",
    token: "41eb582e-9d70-4195-a71a-cc41b4019e09",
    amount: 1,
    billingAddress:{
      firstName:"Name",
      lastName: "Last",
      companyName: "Company",
      streetAddress1: "Street 1",
      streetAddress2: "Street 2",
      city: "city",
      cityArea: "area",
      postalCode: "10093",
      country: "country",
      countryArea: "area",
      phone: "66884894"
    }
  }){
    paymentErrors{
        field
        message
        code
    }
  }
}
```

### Response:
```
{
    "data": {
        "checkoutPaymentCreate": {
            "paymentErrors": [
                {
                    "field": "checkoutId",
                    "message": "Couldn't resolve to a node: 41eb582e-9d70-4195-a71a-cc41b4019e09",
                    "code": "NOT_FOUND"
                }
            ]
        }
    }
}
```
<img width="789" alt="db" src="https://user-images.githubusercontent.com/36519195/65798335-f667eb80-e136-11e9-86f0-56f98be807e0.PNG">

**Comment by bogdal** [comment]
@srendon Here you have the right solution https://github.com/mirumee/saleor/issues/4768#issuecomment-535663996.

You can use the following query to get a checkout ID:
```graphql
{
  checkout(token: "41eb582e-9d70-4195-a71a-cc41b4019e09") {
    id
  }
}

```

**Comment by srendon** [comment]
> @srendon Here you have the right solution [#4768 (comment)](https://github.com/mirumee/saleor/issues/4768#issuecomment-535663996).
> 
> You can use the following query to get a checkout ID:
> 
> ```graphql
> {
>   checkout(token: "41eb582e-9d70-4195-a71a-cc41b4019e09") {
>     id
>   }
> }
> ```

Thank you @bogdal that solved my problem.
