### ISSUE TITLE
Mailchimp eCommerce Plugin

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#4779]
### What I'm trying to achieve
Mailchimp is offering an eCommerce API in order to connect a shop to their system. This will alow you to easily build stuff like "Voucher on newsletter signup", product recommendations etc etc .. 

### Describe a proposed solution
The plugin infrastructure is perfect for this case. There is also a python library for the mailchimp v3 API: https://pypi.org/project/mailchimp3/

**Comment by maarcingebala** [comment]
The plugin architecture is still pretty fresh in Saleor, but we've built it to enable integrations like this one. I can't tell you yet when we'd be able to work on this, as we have few other integrations planned already. CC @korycins ⬆️.

**Comment by korycins** [comment]
We have integration with MailChimp  in our scope but we don't have any estimation when it will be ready. If you want to create own integration you could use our plugin logic and create your Plugin. We've added more hooks for extension manager a couple of days ago so you can use them. 
You could also use our webhook logic if you don't want to write a plugin ( I assume that this will require some proxy script to map Saleor's data into MailChimp format.)

**Comment by JannikZed** [comment]
thanks for the answer! I just wanted to keep track of this feature :) 
I also think having it as a plugin would be perfect. I will definitely start testing out at least some parts of the integration myself and maybe could bring back some of my experiences.
The first question, that comes to my mind: how to work with users acceptance during the order process. If you give the possibility to accept or decline promotional emails, we somehow need to process this meta-information, so that our plugin will only write a user to a MailChimp audience if they accepted it. So this information should be included when we are creating the checkout already (so when a user accepted promotional emails, a store operator could send them abandoned cart emails for example).
How would you implement this?

**Comment by korycins** [comment]
> The first question, that comes to my mind: how to work with users acceptance during the order process. If you give the possibility to accept or decline promotional emails, we somehow need to process this meta-information, so that our plugin will only write a user to a MailChimp audience if they accepted it. So this information should be included when we are creating the checkout already (so when a user accepted promotional emails, a store operator could send them abandoned cart emails for example).
How would you implement this?

Order and User models have meta fields. Your storefront can use it to pass and retireve data like this. Then your plugin can check the values in meta field for order or user.

**Comment by korycins** [comment]
Hhm, I think this is a bug. CheckoutUpdateMeta requires `manage_orders` permission which only staff user can have it.  
I think that updateMeta for Checkout and Order should be modifiable without permission. 
Question 1) - What should we do with the checkout meta fields when we create an order object.
