### ISSUE TITLE
Separate Django app for product description - Saleor

### ISSUE THREAD

**Issue by raratiru** [mirumee/saleor#4787]
We sell music media. 

The description of each product takes into account combinations of data regarding composers, compositions, artists per instrument (pianist and conductor), artists per media, artists per track etc. 

Inevitably, we have created a dedicated Django application that encapsulates the logic responsible for building the description of each product and this app uses Django admin.

How can I effectively integrate my app to Saleor in order to include all the necessary information in the description?

**Comment by maarcingebala** [comment]
Considering that you're running it as a separate app next to Saleor (if I understand correctly), I think you should build some synchronization script that would update descriptions in Saleor whenever you change them in the other app. You could use just a Python script that connects to both databases and exchanges data between them. It could be implemented as a Django command in either of the projects. You could run it on demand when the changes to your descriptions is first saved, or periodically with some task manager. You could also try to use our GraphQL API to update products in Saleor.

**Comment by raratiru** [comment]
OK, I understand: I should consider Saleor a stand alone project and add the description to the list of the data that will periodically be updated, such as quantities that change regularly from other points of sale, for example.

I am just browsing the API docs, it is indeed a great tool. Thank you!
