### ISSUE TITLE
Able to use OAuth2.0  without https

### ISSUE THREAD

**Issue by Pichnyty** [mirumee/saleor#4796]
### What I'm trying to achieve
Able to use OAuth2.0  without https
### Steps to reproduce the problem
1. Create credential of oAuth2 in " site setting " in admin dashboard
2. Login using google account
3. After I login, it result the below image
![Capture](https://user-images.githubusercontent.com/54165288/66101802-54368080-e5da-11e9-8365-676107bb0e6a.JPG)
4. But If I delete the change the https -> http as below
![dd](https://user-images.githubusercontent.com/54165288/66101931-ceff9b80-e5da-11e9-88f0-78c716209fdb.JPG)
to
![XXX](https://user-images.githubusercontent.com/54165288/66101998-0110fd80-e5db-11e9-9387-23c4a2200e39.JPG)

It works fine

**Comment by NyanKiyoshi** [comment]
In production we expect sites to always use and support HTTPS. But it might be useful for development to allow to bypass this restriction.

But most of the authentication providers disallow the usage how insecure HTTP for callbacks, i.e. it would be easy to redirect the user to a malicious website by intercepting the Wi-Fi packets. I believe Google is one of them, but maybe they allow it for localhost, I don't remember if they were fine with this one.

**Comment by Pichnyty** [comment]
@NyanKiyoshi @patrys Thank you for your response. So Could you tell me how to bypass that https->http because even I started to deploy it on my own internal Network in My local area server. I did not have the authorize to purchase the SSL yet because I'm a student who have no credit card yet.

**Comment by NyanKiyoshi** [comment]
For production, you can use Certbot: https://letsencrypt.org/. It is free, you don't have to pay for certificates.

For development only, you can easily edit the address once you get redirected to the HTTPS page from `https` to `http`.

Otherwise, for development only as well, you can override `SOCIAL_AUTH_REDIRECT_IS_HTTPS` from `True` to `False` in the `settings.py` or your django settings file.
