### ISSUE TITLE
Dashboard Updating subcategories redirecting to the wrong page

### ISSUE THREAD

**Issue by ccsv** [mirumee/saleor#4798]
### What I'm trying to achieve
Updating a subcategory needs to redirect to the Category page when done

### Steps to reproduce the problem
1.  Lets say I start on the Category Grocery page (http://localhost:8000/dashboard/categories/8/) and add a subcategory "grocery" and save it
2. Go update the subcategory you just created and click inside to update it this will redirect you to something like a page like: http://localhost:8000/dashboard/categories/23/ This is a page of the subcategory with a subcategory section you can add. What it should be redirect you back to the Category Grocery page to add additional groceries.

### What I expected to happen
1. Redirect to the categories page when finish updating. (Guessing issue is with how the view is written)
2. For the subcategories page you should not be able to add more subcategories 

### Screenshot

![Untitled1](https://user-images.githubusercontent.com/6316732/66124019-30eae180-e598-11e9-92ae-a522974c4fda.jpg)

**System information**
Operating system: Windows
Browser: Firefox
Saleor v 2.8

**Comment by iflare3g** [comment]
Hi! I can try to work on it 😁

**Comment by maarcingebala** [comment]
Go ahead! Hit us up if you need help with this 🙂

**Comment by iflare3g** [comment]
Just need to write tests and I'll publish the PR!

**Comment by maarcingebala** [comment]
The issue is invalid - details in PR #4814.
