### ISSUE TITLE
Dashboard icons

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#480]
We're now using materialize css icon set (old version) http://materializecss.link/icons.html
They are now replaced by Google font: http://materializecss.com/icons.html

We should consider migrating to new version.

**Comment by lavish205** [comment]
Hi @artursmet 
1st link is not working and moreover can you please provide more details regarding this bug so that we (contributors) can know where and how much icons need to be changed.

**Comment by patrys** [comment]
@lavish205 sorry but this turned out to be a rather tedious task so we've decided to fix this ourselves, I'll submit a pull request today.
