### ISSUE TITLE
Support GraphQL federation

### ISSUE THREAD

**Issue by salwator** [mirumee/saleor#4803]
### What I'm trying to achieve
I want to use saleor API in GraphQL federation.

### Describe a proposed solution
Graphene does not support federation out of a box, here is a disscuscion https://github.com/graphql-python/graphene/issues/953.

**Comment by salwator** [comment]
I did create issue on graphene repo to discuss possibility of native support without additional packages.
https://github.com/graphql-python/graphene/issues/1081

**Comment by JannikZed** [comment]
hey @salwator are you still using federation? I was trying to start that out, without success.. my Apollo Gateway gives me this response:
```
Error checking for changes to service definitions: Couldn't load service definitions for "saleor" at https://XXX.com/graphql/: Syntax Error: Unexpected Name "ObjectWithMetadata".
This data graph is missing a valid configuration. Couldn't load service definitions for "saleor" at https://XXX.com/graphql/: Syntax Error: Unexpected Name "ObjectWithMetadata".
```
I'm not deep into graphene or anything, I just start I could plug & play :D
