### ISSUE TITLE
Saleor install. Help plz. Windows.

### ISSUE THREAD

**Issue by fedonkin** [mirumee/saleor#4808]
Tried to establish saleor. 

### Steps to reproduce the problem
1. Downloaded archive. Unpacked.  
cd saleor/.
 Next python -m pip install -r requirements.txt

2. $env:SECRET_KEY = "<mysecretkey>"
Do so : set SECRET_KEY="gennnnereted keysss"
Do so : set SECRET_KEY='gennnnereted keysss'
Nothing works.

**Please tell us more how to install fully saleor. I need help. Thanks.**

Operating system: Windows.

**Comment by Anyman552** [comment]
What error do you get? Do you use a virtual environment?
**set** only modifies the current shell environment

**Comment by ccsv** [comment]
Just go into settings.py and manually put in a SECRET_KEY


# Make this unique, and don't share it with anybody.
SECRET_KEY =

**Comment by maarcingebala** [comment]
Please refer to our documentation:
- newest version compatible with `master` - https://docs.getsaleor.com/docs/next/getting-started/intro/
- docs for `2.8` release - https://docs.getsaleor.com/docs/getting-started/intro/

You can also use our [Gitter](https://gitter.im/mirumee/saleor) and [Spectrum](https://spectrum.chat/saleor) channels for quick questions about setting up Saleor.
