### ISSUE TITLE
User accounts are not made active after they confirm their email addresses and set their password

### ISSUE THREAD

**Issue by gourneau** [mirumee/saleor#481]
Using the latest code 3aa172375bd494a728518de5f41134160da49d59

A user can register an account. Once they have confirmed their email address and set a password, they are logged in.

If they then logout - they can't log back in because the account is not marked as active.

![Login flow](http://i.imgur.com/ODkKpqF.gif)

**Comment by gourneau** [comment]
My solution is to activate the account after they confirm their email address the PR is #482

**Comment by patrys** [comment]
Activating an inactive account could become a security concern in some scenarios. I've changed the code to activate users when the object is created (and ensuring their account is active before logging them in).

**Comment by patrys** [comment]
This is now fixed. Thank you for the very detailed reproduction steps!
