### ISSUE TITLE
Dynamic configuration for DEFAULT_FROM_EMAIL setting

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#4815]
We would like to be able to dynamically set the value of `DEFAULT_FROM_EMAIL` setting. A good place to store it is the `SiteSettings` model. We would need to extend the API to allow managing and retrieving it.

There is also `ORDER_FROM_EMAIL` setting which acts identically, except it's only used for sending order-related emails. I'm wondering whether it is actually needed or we could simplify it to have only one configuration. I'd like to hear some feedback on that.

**Comment by NyanKiyoshi** [comment]
To prevent header injection, we will have to validate the value doesn't contain any newlines before saving.
