### ISSUE TITLE
Make a payment throught GraphQL

### ISSUE THREAD

**Issue by srendon** [mirumee/saleor#4827]
I’m traying to make a payment using GraphQL requests. The steps I follow are the following: 
1.	Make a `checkoutPaymentCreate` request
2.	Make a `paymentCapture` request 

When I make the ` paymentCapture` request there is a `PAYMENT_ERROR` error that has the following message: ` Cannot find successful {kind.value} transaction`. How can I solve this problem?

**Comment by NyanKiyoshi** [comment]
Hi, you have to authorize the payment first through `checkoutComplete` see https://github.com/mirumee/saleor-docs/blob/99d83417f25f6fe39c854a0f197ea3896f1125f1/docs/api-process/check-out.md#completing-the-checkout for more information.

**Comment by srendon** [comment]
Thank you @NyanKiyoshi
