### ISSUE TITLE
301 redirects for moved or removed content

### ISSUE THREAD

**Issue by petedermott** [mirumee/saleor#4832]
### What I'm trying to achieve
Currently we have no "dashboard powered" method of managing 301 or 302 redirects when a product or category is removed from the site. This can be achieved via a some middleware on the frontend PWA but this isn't really suitable for most regular admins.

### Describe a proposed solution
Django already has a redirects app built in to it. I would propose we extend this by creating the appropriate dashboard forms to manage it and add a GQL query that would take the old URL and return the new URL that the site would need to redirect to.

**Comment by NyanKiyoshi** [comment]
Hi, what are we talking about? What URLs? Storefront 1.0?

**Comment by petedermott** [comment]
The "old URLs" are those of products that you may have removed or renamed to something else or replaced with other products, this could also apply to categories and static website content.

It would mostly apply to the 1.0 Storefront but it could be expanded to the PWA with appropriate GQL queries.

**Comment by NyanKiyoshi** [comment]
The products are always redirecting to the correct new URL if the link has changed. But there is currently no possibility to tell the client that X product was replaced by Y product as of now.

The best way would probably to have a possibility to be able to archive a product (putting it out of sale and in invisible mode from the product list page) and suggest other relevant products and by this way, we could have a way of manually supplying a list of alternative products as well as the generated list.

**Comment by petedermott** [comment]
What about those who are moving to Saleor from an existing e-commerce system? Search engines are generally a whole lot happier with redirects over standard 404 pages, plus if you just suggest relevant products then who is to say that you are suggesting the correct one?

301 redirects are already a feature of Shopify, Magento, WordPress and many other CMS systems, they should really be in Saleor
