### ISSUE TITLE
Problem with filtering products

### ISSUE THREAD

**Issue by mateuszkula** [mirumee/saleor#4837]
### What I'm trying to achieve
I want to filter out products from grocerries category but I receive results even when I should not.

### Steps to reproduce the problem
In groceries category there are two beers that have `abv` attribute with values: 51(5,1% alc) and 67(6,75 alc) but when filter with `abv` value set to 52 we receive `Carrot juice` 

Correct query:
```
query{	
  products(first: 100, attributes: ["abv:51"]){
  	edges {
      node {
        id
        name
      }
    }
  }
}
```
and correct result:
```
{
  "data": {
    "products": {
      "edges": [
        {
          "node": {
            "id": "UHJvZHVjdDo4Mw==",
            "name": "Seaman Lager"
          }
        }
      ]
    }
  }
}
```

Query with invalid value(abv set to 52):
```
query{	
  products(first: 100, attributes: ["abv:52"]){
  	edges {
      node {
        id
        name
      }
    }
  }
}
```
invalid result:
```
{
  "data": {
    "products": {
      "edges": [
        {
          "node": {
            "id": "UHJvZHVjdDo3Mw==",
            "name": "Carrot Juice"
          }
        }
      ]
    }
  }
}
```

### What I expected to happen
We should receive empty product list if passing abv value 52.

**Comment by NyanKiyoshi** [comment]
Most likely:
https://github.com/mirumee/saleor/blob/749b4e43ee9994d4c124fdf757b65f8f1cfd1b64/saleor/product/filters.py#L30-L40
