### ISSUE TITLE
updating year in footer of https://getsaleor.com

### ISSUE THREAD

**Issue by stratospher** [mirumee/saleor#4846]
year updation from 2018 to 2019 required in footer of https://getsaleor.com

**Comment by S3rbane** [comment]
I'll take this.

**Comment by stratospher** [comment]
> I'll take this.

I'm sorry but I already submitted a pull request.

**Comment by S3rbane** [comment]
Sorry not sure how I didn't see that

**Comment by maarcingebala** [comment]
Thanks for opening the issue. getsaleor.com is kept in a different repository and we already have an issue for that there.
