### ISSUE TITLE
Possibility to add more attributes to the products

### ISSUE THREAD

**Issue by Nykollas** [mirumee/saleor#4848]
### What I'm trying to achieve
I'm trying to add more attributes to the products like height, width and diameter. I need this feature because the service that is being used for shipping costs calculation, require this  attributes. How could that feature be implemented ? There's is a documentation that can help ?
I may dive into it.

**Comment by maarcingebala** [comment]
Hey, in Saleor you can assign any attributes to products using product types, have you tried it? Here is the link to our dashboard guide about product types- https://docs.getsaleor.com/docs/next/dashboard/configuration/products/. Another, more "low-level" way would be to use Meta fields, but this feature is available only in the API - https://docs.saleor.io/docs/next/api/metadata/.

**Comment by Nykollas** [comment]
Great!
