### ISSUE TITLE
JSONWebTokenMiddleware giving issues

### ISSUE THREAD

**Issue by RobinReborn** [mirumee/saleor#4870]
### What I'm trying to achieve
Get tests passing in tests/api
### Steps to reproduce the problem
1. run py.test tests/api

### What I expected to happen
Tests to pass

`TypeError: __init__() got an unexpected keyword argument 'get_response'`

This is in saleor/graphql/middleware.py

`jwt_middleware_inst = JSONWebTokenMiddleware(get_response=get_response)`

I have tried changing that line to just 

`jwt_middleware_inst = JSONWebTokenMiddleware()`

but that leads to other errors

Do I need to set some sort of key somewhere?
**System information**
Docker build

**Comment by NyanKiyoshi** [comment]
Hi! Two months ago we froze the JWT middleware (`django-graphql-jwt`) to `<0.2.2`. Make sure you do the same on your fork/version, and downgrade it: `django-graphql-jwt==0.2.1`.

Refer to https://github.com/mirumee/saleor/issues/4652.
