### ISSUE TITLE
Create order only after the payment are paid

### ISSUE THREAD

**Issue by michelveloso** [mirumee/saleor#4874]
### What I'm trying to achieve
In traditional B2C, the ShopBasket are only clean and the order is created, when the payment is confirmed

### Describe a proposed solution
A possible solution is only create the order when the payment is confirmed, is possible to pass only the checkout id to the gateway payment?
The create the order when the payment is confirmed?

**Comment by korycins** [comment]
Hi,
The proposed solution is already implemented in API. Here you have PR - https://github.com/mirumee/saleor/pull/4154

We are focusing on the API approach and we don't have enough resources to rebuild the whole checkout process in our old Django approach (which is quite really complicated). I recommend you to switch to API.

**Comment by michelveloso** [comment]
@korycins, by API you mean Graphql + React Fronted?

Regards

**Comment by korycins** [comment]
@michelveloso yes

**Comment by michelveloso** [comment]
@korycins thank you for the great job!
