### ISSUE TITLE
URGENT: Braintree gateway config not working for live

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#4879]
### What I'm trying to achieve
We found a bug in the plugin braintree configuration that is leading to complete non-functional braintree gateway for production. The error is coming from the sandbox_mode configuration parameter.
It works great for sandbox, as this is the standard config:
https://github.com/mirumee/saleor/blob/master/saleor/payment/gateways/braintree/__init__.py#L100
But it seems like sandbox_mode gets stored in saleor as string!! not as python boolean. We checked it by introducing a print(type)) like this, directly after line 100:
```
    print('Sandbox ? ', sandbox_mode)
    print(type(sandbox_mode))
    if not sandbox_mode:
        environment = braintree_sdk.Environment.Production
```
and it returns: 
```
Sandbox ? false
<class 'str'>
``` 
So here we have the core-issue .. 
We wanted to propose a merge request to fix this issue, but honestly I don't know where to fix it the best. This field should never be allowed to be a string, so it seems to be a core issue. 

## Steps to reproduce the problem
1. Use braintree with sandbox_mode disabled
2. try to create an order

**Comment by szewczykmira** [comment]
Hey, could you tell me more about this issue you are experiencing? What method did you use to change sandbox mode? Do you use dashboard 1.0 or 2.0.
I've checked this (changing sandbox mode to `True` via Dashboard 1.0) and that's what I get:
```python
In [25]: plugin._cached_config = None                                                                                                                                     

In [26]: plugin._initialize_plugin_configuration()                                                                                                                        

In [27]: plugin.config                                                                                                                                                    
Out[27]: GatewayConfig(gateway_name='Braintree', auto_capture=True, template_path='order/payment/braintree.html', connection_params={'sandbox_mode': False, 'merchant_id': '2', 'public_key': '2327', 'private_key': '22223'}, store_customer=False, require_3d_secure=False)

In [28]: gateway = get_braintree_gateway(**plugin.config.connection_params)                                                                                               

In [29]: gateway.config.environment.__dict__                                                                                                                              
Out[29]: 
{'__name__': 'production',
 '_Environment__server': 'api.braintreegateway.com',
 '_Environment__port': '443',
 'is_ssl': True,
 'ssl_certificate': '/Users/miraszewczyk/.virtualenvs/saleor/lib/python3.7/site-packages/braintree/ssl/api_braintreegateway_com.ca.crt',
 '_Environment__auth_url': 'https://auth.venmo.com',
 '_Environment__graphql_server': 'payments.braintree-api.com',
 '_Environment__graphql_port': '443'}
```

**Comment by szewczykmira** [comment]
Missclick

**Comment by maarcingebala** [comment]
I agree about the normalization that you suggest. Plus, it would be great if a developer could get a warning when the configuration is wrong. E.g. when providing boolean inside a string to get a message in the console "Value for the configuration key %s{key} is wrong".

**Comment by JannikZed** [comment]
I have a question in that. When you update these values via graphql it tells you, that it is if type BOOLEAN - so my assumption was, that it gets also saved in the database as boolean - no matter if the Apollo client is sending javascript boolean or not 🧐 
But it seems like I'm wrong 🙃 so where is the error appearing the first time? We would really like to deeply understand this case to fix it on our own the next time ;)

**Comment by korycins** [comment]
@JannikZed You are right. All plugins should overwrite `BasePlugin.validate_plugin_configuration` to confirm that their configuration is correct. Also, we need to add logic to:
   a) raise error in case when we try to save different type ov value that declared field 
   b) convert string `true`/`false` to `True`/`False`
I assume, it should be disscussed with some who is responisible for dashboard.
@szewczykmira  Our priority for us is to fix braintree asap, I suggest to use `xyz == "true"` for now. We will add validation in next release. @maarcingebala Do you agree?

**Comment by szewczykmira** [comment]
@korycins but if we add this check then saving data with dashboard 1.0 will be failing as there we are saving boolean values and not string. Unfortunately, this will not be as easy as we thought :(
