### ISSUE TITLE
Dashboard1.0 -/dashboard/payments/ fails when PaymentPlugin has wrong config

### ISSUE THREAD

**Issue by korycins** [mirumee/saleor#4898]
I've checked it only for braintree but I assume that problem can be for all payments. `http://127.0.0.1:8000/dashboard/payments/` view fails when Braintree `is_active` and configuration is wrong. Braintree raises an error and we don't catch it (`AuthenticationError`).
The second thing is that we shouldn't try to run plugin (Braintee) when we want to open view - `dashboard/payments/`

**Comment by szewczykmira** [comment]
Related #4861

**Comment by szewczykmira** [comment]
@korycins So we can agree that DOD:
- don't run plugins in dashboards view `dashboard/payment`?
