### ISSUE TITLE
back button after completing an order

### ISSUE THREAD

**Issue by pcompassion** [mirumee/saleor#490]
This is about user experience on browser navigation.

Pressing back button after completing an order should take the user to the page that user visited before he went to cart or checkout pages.

**Comment by patrys** [comment]
Do you have an idea how you'd solve that?

**Comment by pcompassion** [comment]
I think one should specify the desired behavior.

It's hard for me because I'm not sure what's possible in client side especially with History api.

I could think of

1. mark [beginning-of-checkout ........... end-of-checkout] and delete all histories inbetween.
2. mark each checkout-related page for deletion and delete them after end-of-checkout

I'm not sure but history api only gives us the option
to count # of pages we want to skip, and goBack(#)

I'll update you if I find a better way.

**Comment by patrys** [comment]
Tricky thing is that you can get any number of third-party 3-D secure redirects in between your views.

**Comment by pcompassion** [comment]
umm, how about if you hit checkout with empty cart, send the user to a specific page such as store home.

not sure if this is better than current implementation.

I want to see how other big players such as amazon handle this. currently nothing to buy :(
