### ISSUE TITLE
GraphQL errors shouldn't be logged

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4903]
### What I'm trying to achieve
Remove useless exception output.

### Steps to reproduce the problem
1. run `{ products { invalid } }`
2. an exception will be logged despite it was handled

### What I expected to happen
It shouldn't be logged. We could check whether the final exception is a GraphQL exception or an actual exception.

**Comment by NyanKiyoshi** [comment]
This would require overriding or silencing `graphql.execution.utils`'s logger from `ExecutionContext.report_error` to prevent it from sending unwanted logs.

**Comment by maarcingebala** [comment]
For sure we don't want to log errors like:
- `PermissionDenied`
- `ValidationError`

I don't know what do do with `GraphQLError` - it could be useful if you have broken queries in your client, but it shouldn't be the case with our demo stores that we control and test locally. Maybe we should only silence this error on `demo` branch?

**Comment by maarcingebala** [comment]
Also please take a look at: https://docs.sentry.io/error-reporting/configuration/filtering/?platform=python, maybe this would help.

**Comment by korycins** [comment]
https://github.com/mirumee/saleor/pull/4906#discussion_r339529371
