### ISSUE TITLE
Add js image selector

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#491]
After merging https://github.com/mirumee/saleor/pull/470 it's possible to attach images to particular variants. But images should also change, when user is selecting another variant from variant selector.
- [ ] switch active image (do not hide other images) when a variant is selected
- [ ] in cart display an image specific to a variant if one is available

**Comment by elwoodxblues** [comment]
@benekex2  Our variant picker is implemented in React and uses MobX store to track the selected variant. It should be possible to implement another React component that would render images and update them respectively based on changes in the store.

Displaying proper images in cart will probably require some backend changes so we can implement it later.

**Comment by michaelm6y** [comment]
Is this issue still underway, or are most of the front-end improvements in the old saleor project getting deferred for work on the PWA storefront? No worries either way, just curious :)
