### ISSUE TITLE
How to receive notification about customer's order?

### ISSUE THREAD

**Issue by ruszhov** [mirumee/saleor#4932]
I started use Saleor. When customer pressed key "Order & Pay" he receives an letter with order details. It is OK. But I don't receive any notification (letter) about customer's order. How can I fix that issue?

**Comment by ruszhov** [comment]
Hi @maarcingebala, actually you understood right. I can't check every time new orders in store. I just want to receive notification if they will be.

**Comment by kswiatek92** [comment]
ToDo list:
- `StaffNotification` model which will contains `email` and `user` fields
- `SiteSettings` will contain arrayField with `StaffNotification`
- email task and template for staff member when order is placed

**Comment by maarcingebala** [comment]
@ruszhov We've implemented backend part of this feature, soon we'll also add UI for that in the dashboard.

**Comment by giovannipiccinelli** [comment]
Hi, Any update on this?

**Comment by maarcingebala** [comment]
@giovannipiccinelli The backend functionality and API is implemented. Frontend part in the dashboard is missing and we had to postpone it due to other priorities, I'm not sure when it will be added.

**Comment by marounbtr** [comment]
Hello Everyone
Is the functionality available now?
