### ISSUE TITLE
Next dashboard not available

### ISSUE THREAD

**Issue by flaviocolonna** [mirumee/saleor#4935]
After the last release, the new dashboard is not available anymore. Are you going to reset it?

**Comment by flaviocolonna** [comment]
It has been moved to the saleor-storefront repo.

**Comment by maarcingebala** [comment]
It is [saleor-dashboard](https://github.com/mirumee/saleor-dashboard/) 😉

**Comment by NyanKiyoshi** [comment]
To the [saleor-dashboard repository](https://github.com/mirumee/saleor-dashboard/), yes 🎉

**Comment by flaviocolonna** [comment]
I was thinking it was in the saleor-storefront. By the way, many thanks!
