### ISSUE TITLE
google-i18n-address module breaks python3.5.0 compatability

### ISSUE THREAD

**Issue by awhillas** [mirumee/saleor#494]
Causes a Unicode error in python 3.5 when installed as per: 
https://github.com/mirumee/google-i18n-address/issues/9

Have made a pull request but not response yet...
https://github.com/mirumee/google-i18n-address/pull/10

Are you guys not testing in python 3?

**Comment by patrys** [comment]
If you look at Travis, you'll notice that we're testing with both 3.4 and 3.5. I'm also using 3.4 on my local machine and have never seen this problem.

**Comment by bogdal** [comment]
@awhillas What kind of environment/OS do you use? I'm not able to reproduce this error.
