### ISSUE TITLE
News on separating into modules

### ISSUE THREAD

**Issue by b99andla** [mirumee/saleor#4945]
### What I'm trying to achieve
Beeing able to update Saleor without manually merging from repo.

### Describe a proposed solution
Separating out the different parts into installable packages. 

We are investigating a futureproof e-commerceplatform for our company, and found that this project checks all boxes for this, except for the updatehandling. We found this issue which is now closed:
https://github.com/mirumee/saleor/issues/4234

Are there any news on an ETA to a simpler handling of updating and installing saleor? We would love to use this, but the need to manually merge makes this a none starter for us...

**Comment by patrys** [comment]
We're moving closer and closer towards a goal where you are able to extend Saleor without modifying any of its code. Ultimately you should be able to update Saleor by updating a Saleor Docker image and using the following mechanisms to extend it:

* in-process plugins (can be currently done by shadowing the `settings.py` file but we may introduce an explicit mechanism to do that using env variables)
* out-of-process extensions using Webhooks and Service Accounts
* GraphQL federation using the Apollo Gateway

I don't believe we intend to support installing Saleor in an existing Django project, especially so as we actively look to move from the WSGI stack to an ASGI one to enable asynchronous operation, support subscriptions and so on.

**Comment by b99andla** [comment]
> We're moving closer and closer towards a goal where you are able to extend Saleor without modifying any of its code. Ultimately you should be able to update Saleor by updating a Saleor Docker image and using the following mechanisms to extend it:
> 
> * in-process plugins (can be currently done by shadowing the `settings.py` file but we may introduce an explicit mechanism to do that using env variables)
> * out-of-process extensions using Webhooks and Service Accounts
> * GraphQL federation using the Apollo Gateway
> 
> I don't believe we intend to support installing Saleor in an existing Django project, especially so as we actively look to move from the WSGI stack to an ASGI one to enable asynchronous operation, support subscriptions and so on.

Thank you for the reply!

Is there any documentation available on how to go about getting closer to this setup? A sort of best practice? I am sufficient in docker, but have never used this way of extending a project...

**Comment by b99andla** [comment]
> @b99andla Hello! I'm currently managing a Saleor fork. Here some tips on how to make your life easier:
> 
> * keep your code formatted using `black` and `isort` (config already in the repo). Both tools produce code which should be easier to merge
> * if possible, keep your code in separate files (Want to write new mutation for synchronizing Products? Don't add it to the main `saleor/product/mutations.py`, create new `saleor/product/sync_mutations.py`). It makes rebase much, much easier because you don't need to solve too many conflicts in base files.
> * I recommend squashing commits before merging pull requests. Having one commit on master branch per PR/feature makes git history clean.
> * the new plugin system is 💯 - use it and expand plugin manager for new functions if there is something missing
> * rebase often, on a monthly basis. This way you will know early that something does not work as intended.
> * if test from saleor repository becomes irrelevant, we found marking them using `pytest.mark.skip` easier to manage than removing from the project. YMMV
> * A few of our features were implemented at first in Saleor upstream repository and then we rebased our project, it's awesome to improve open source projects :)

Thank you for the excellent reply!

Since we are a small consulting firm, we normally go for projects that dont require us to be this hands on when upgrading, its hard to motivate to our customers that we need a monthly or yearly budget for updates (sad but true). I appreciate your feedback and will take this to our team for consideration when choosing an e-commerce for our next project. Even if we are scared of the update paths I have seen a lot of talk in the issues that makes me sure that this team is working on it, and I must say that the techstack and solution seems excellent.
