### ISSUE TITLE
Dashboard should have separated assets

### ISSUE THREAD

**Issue by mociepka** [mirumee/saleor#495]
I need to implement saleor with the foundation. With this approach I need to remove all current styles and scripts. The problem is that we have one `package.json` file and I don't knew which packages I can remove without breaking dashboard.

I propose to move all dashboard static to `salor/dashboard/static` and create separate grunt and webpack files for it.

**Comment by elwoodxblues** [comment]
What about this issue? Is it still valid? Usually projects have single `package.json` file and I'd personally keep it like it is. What do you think?
