### ISSUE TITLE
Telegram chat

### ISSUE THREAD

**Issue by Zoxon470** [mirumee/saleor#4953]
Maybe will you open a telegram chat for supporting this project? Telegram very comfortable.

**Comment by maarcingebala** [comment]
We already have two channels - [Spectrum](https://spectrum.chat/saleor) and [Gitter](https://gitter.im/mirumee/saleor) and adding a third one would be difficult to handle for our team. I'm not familiar with Telegram, do you think it's better than the two that we use now?

**Comment by Zoxon470** [comment]
I don't think that telegram better that your two channels, but telegram too not bad. I needed help and I tried to find you in a telegram, I think people eventually switch to telegram too, because now all the IT-community is sitting there.
