### ISSUE TITLE
shipping zone within one country is supported or not ?

### ISSUE THREAD

**Issue by nasim31** [mirumee/saleor#4958]
Hello Team,
I have checked your "saleor" and liked it.
Just stopped at "shipping zone". As it's always asked for a country.
Suppose a businessman want to do the business within a city or within a state only. How saleor will solve his shipping issue ?
Is that currently supported or not ?

**Comment by korycins** [comment]
Hi, 
Saleor supports shipping zones only for countries. You can't create shipping_zone dedicated to the city or state.

**Comment by nasim31** [comment]
Hi korycins,
Thank you very much for your reply. Now i can understand saleor shipping system.
I would like to ask you one more thing that, By using saleor as an ecommerce enginge for a business what system (for shipping) can be integrate with it so that order created on saleor can be automatically processed for shipping. By using webhook or by any other methods.

**Comment by korycins** [comment]
Saleor hasn't had any built-in shipping integration yet. You can create your own shipping integration by using webhooks or our inline plugin system (https://docs.getsaleor.com/docs/advanced/extensions/).

**Comment by nasim31** [comment]
Hi Thanks for your time. I'll definitely try this out.
