### ISSUE TITLE
date picker 

### ISSUE THREAD

**Issue by mohammadhoseinazad** [mirumee/saleor#4959]
### What I'm trying to achieve

on page : https://demo.getsaleor.com/dashboard/discounts/voucher/add/ 
when i am trying to assign end date(optional) the date table twinkles and is not fix to choose date

### What I expected to happen

it should be fix date table

**System information**
Operating system: ubuntu
Browser:chrome

**Comment by NyanKiyoshi** [comment]
Regression from Google Chrome, there is currently no real fix apart hacky fixes. See https://github.com/mirumee/saleor/issues/3865.
