### ISSUE TITLE
Saleor - Graphql - Same table name for 2 diferent apps

### ISSUE THREAD

**Issue by L-Leandro** [mirumee/saleor#4961]
### What I'm trying to achieve
On a different app, I have created a table user. So I created the table with migrate (with a proper models system), it created with name 'app_name'_user. This table is linked directly to account_user. 

### Steps to reproduce the problem
After having everything created properly, created a folder saleor\graphql\'new_app_name' and here I have the mutations.py, resolvers.py, schema.py and types.py.

Then on the accounts/types.py in class class User(MetadataObjectType, CountableDjangoObjectType), I added (and this gives me error while compiling):

    user = gql_optimizer.field(
        PrefetchingConnectionField(
            "saleor.graphql.app_name.types.User",
            description="List of the extension User.",
        ),
        model_field="user",
    )

### What I expected to happen
I would like to be able to query, via graphql:
_query {
  user(id: "VXNIcjoyMQ==") {
    id
    firstName
    lastName    
	user(last:1) {
	edges{
		node{
			created
			updated
		}
	}
  }	
  }
}_

Note1: While compiling/building it gives an error:
AssertionError: Found different types with the same name in the schemaL User, User.

Note: So it does not like the fact of having a table called account_user and another called test_user. 
Do I need to change the table name to for exaple test_user_abc? or is there a way, I can have this name?

### Screenshots

**System information**
Operating system: windows
Browser:

**Comment by maarcingebala** [comment]
@L-Leandro In GraphQL you cannot have two types of the same name in one schema. It seems that your type `saleor.graphql.app_name.types.User` ends up in the schema as `User` and there already is a `User` type coming from Saleor. That would be my guess.
