### ISSUE TITLE
Having multiple error on dashboard-next upon installation of npm

### ISSUE THREAD

**Issue by paulon-zervoulakus** [mirumee/saleor#4966]
### What I'm trying to achieve
npm i

### Steps to reproduce the problem
1. rm -rf node_modules/
2. npm i

### What I expected to happen
clean installation

### Screenshots
`
ERROR in /home/app/multivendor/saleor/static/dashboard-next/auth/components/LoginPage/LoginPage.tsx
ERROR in /home/app/multivendor/saleor/static/dashboard-next/auth/components/LoginPage/LoginPage.tsx(123,9):
TS2741: Property 'loading' is missing in type '{ email: string; password: string; rememberMe: boolean; }' but required in type 'FormData'.

ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts
ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts(1,1):
TS6133: 'Money' is declared but its value is never read.

ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts
ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts(6,32):
TS2709: Cannot use namespace 'Money' as a type.

ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts
ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts(6,48):
TS2709: Cannot use namespace 'Money' as a type.

ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts
ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts(6,58):
TS2709: Cannot use namespace 'Money' as a type.

ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts
ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts(12,37):
TS2709: Cannot use namespace 'Money' as a type.

ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts
ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts(12,53):
TS2709: Cannot use namespace 'Money' as a type.

ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts
ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/Money/index.ts(12,63):
TS2709: Cannot use namespace 'Money' as a type.

ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/MoneyRange/MoneyRange.tsx
ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/MoneyRange/MoneyRange.tsx(5,1):
TS6133: 'IMoney' is declared but its value is never read.

ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/MoneyRange/MoneyRange.tsx
ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/MoneyRange/MoneyRange.tsx(8,10):
TS2709: Cannot use namespace 'IMoney' as a type.

ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/MoneyRange/MoneyRange.tsx
ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/MoneyRange/MoneyRange.tsx(9,8):
TS2709: Cannot use namespace 'IMoney' as a type.

ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/MoneyRange/MoneyRange.tsx
ERROR in /home/app/multivendor/saleor/static/dashboard-next/components/MoneyRange/MoneyRange.tsx(12,29):
TS2709: Cannot use namespace 'IMoney' as a type.

ERROR in /home/app/multivendor/saleor/static/dashboard-next/siteSettings/components/SiteSettingsPage/SiteSettingsPage.tsx
ERROR in /home/app/multivendor/saleor/static/dashboard-next/siteSettings/components/SiteSettingsPage/SiteSettingsPage.tsx(67,55):
TS2345: Argument of type '{ code: string; country: string; }' is not assignable to parameter of type 'SiteSettings_shop_companyAddress_country'.
  Property '__typename' is missing in type '{ code: string; country: string; }' but required in type 'SiteSettings_shop_companyAddress_country'.
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/lib/index.js??ref--6-2!node_modules/sass-loader/dist/cjs.js??ref--6-3!saleor/static/dashboard/scss/dashboard.scss:
    Entrypoint mini-css-extract-plugin = *
     [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/lib??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./saleor/static/dashboard/scss/dashboard.scss 676 KiB {0} [built]
    [13] ./saleor/static/dashboard/images/chevron-right.svg 96 bytes {0} [built]
        + 12 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/lib/index.js??ref--6-2!node_modules/sass-loader/dist/cjs.js??ref--6-3!saleor/static/dashboard/scss/document.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/lib??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./saleor/static/dashboard/scss/document.scss 7.31 KiB {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/lib/index.js??ref--6-2!node_modules/sass-loader/dist/cjs.js??ref--6-3!saleor/static/scss/storefront.scss:
    Entrypoint mini-css-extract-plugin = *
     [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/lib??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./saleor/static/scss/storefront.scss 737 KiB {0} [built]
     [3] ./saleor/static/images/arrow-select.svg 95 bytes {0} [built]
     [4] ./saleor/static/fonts/Lato-Light.woff2 95 bytes {0} [built]
     [5] ./saleor/static/fonts/Lato-Light.woff 94 bytes {0} [built]
     [6] ./saleor/static/fonts/Lato-Light.ttf 93 bytes {0} [built]
     [7] ./saleor/static/fonts/Lato-Regular.woff2 97 bytes {0} [built]
     [8] ./saleor/static/fonts/Lato-Regular.woff 96 bytes {0} [built]
     [9] ./saleor/static/fonts/Lato-Regular.ttf 95 bytes {0} [built]
    [10] ./saleor/static/fonts/Lato-Bold.woff2 94 bytes {0} [built]
    [11] ./saleor/static/fonts/Lato-Bold.woff 93 bytes {0} [built]
    [12] ./saleor/static/fonts/Lato-Bold.ttf 92 bytes {0} [built]
    [13] ./saleor/static/images/block1.jpg 89 bytes {0} [built]
    [14] ./saleor/static/images/block2.jpg 89 bytes {0} [built]
    [15] ./saleor/static/images/block3.jpg 89 bytes {0} [built]
        + 2 hidden modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! saleor@0.0.0 build-assets: `webpack -p`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the saleor@0.0.0 build-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-13T04_09_16_317Z-debug.log`

**System information**
npm 6.12.0
node v12.13.0

**Comment by korycins** [comment]
Hi @paulon-zervoulakus Can you precise what version of Saleor you use? 
FYI: Starting from v2.9, the dashboard has been moved to a separate repository.

**Comment by paulon-zervoulakus** [comment]
> Hi @paulon-zervoulakus Can you precise what version of Saleor you use?
> FYI: Starting from v2.9, the dashboard has been moved to a separate repository.

I believe it was 2.8.0 base on the changelog

> # Changelog

All notable, unreleased changes to this project will be documented in this file. For the released changes, please visit the [Releases](https://github.com/mirumee/saleor/releases) page.

## [Unreleased]

- Fix product type taxes select - #4453 by @benekex2
- Fix form reloading - #4467 by @dominik-zeglen
- Fix time zone based tests - #4468 by @fowczarek
- Move Django Debug Toolbar requirement to the "dev" one (also downgrade it 2.0 -> 1.11, see PR) - #4454 by @derenio


## 2.8.0

### Core

- Avatax backend support - #4310 by @korycins
- Add ability to store used payment sources in gateways (first implemented in Braintree) - #4195 by @salwator
- Add ability to specify a minimal quantity of checkout items for a voucher - #4427 by @fowczarek
- Change the type of start and end date fields from Date to DateTime - #4293 by @fowczarek
- Revert the custom dynamic middlewares - #4452 by @NyanKiyoshi

### Dashboard 2.0

**Comment by paulon-zervoulakus** [comment]
any updates regarding this?

**Comment by maarcingebala** [comment]
Dashboard lives in the separate repository [saleor-dashboard](https://github.com/mirumee/saleor-dashboard/). You can build it from `master` for the latest development version or using Github tags for a release version: https://github.com/mirumee/saleor-dashboard/releases/.

Please check again if you can build it after a clean clone and `npm install`. Please open an issue in the dashboard's repository if there are still problems with the installation.
