### ISSUE TITLE
Adding a command to clear the database

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4971]
One would want to keep their database structure but be able to clear the database from all the data they have (testings, populatedb(s), etc.).

We would like to have `./manage cleardb [--delete-staff]`

Default behaviors:
- Deletes everything except: `sites`, `site_settings` and staff users
- `--delete-staff` flag to still delete staff users, excluding the superuser
- We **do not** want to reset the tables sequences

**Comment by maarcingebala** [comment]
It's implemented on `demo` branch and could be simply moved to `master`

https://github.com/mirumee/saleor/blob/demo/saleor/core/management/commands/cleardb.py

The script should exit when run with `DEBUG=False` setting. We can add a flag to execute it anyway with this setting.

**Comment by NyanKiyoshi** [comment]
We should have a test to ensure that all the data is actuall gone, except the site settings and the staff users.

As here we give a list of models to delete. Maybe we could extend django's `django.core.management.sql.sql_flush` to provide a list of tables to keep as `flush` and `sqlflush` management commands don't accept models to exclude.
