### ISSUE TITLE
GraphQL customerNote support

### ISSUE THREAD

**Issue by tilman** [mirumee/saleor#4972]
### What I'm trying to achieve
There is already the field `customerNote` in the graphql `order` Object. But no way to attach a customerNote to an order or create an order with an customerNote. 

### Describe a proposed solution
i see 2 possible solutions:
1) add a new `customerNote` field to `DraftOrderInput!` and `CheckoutCreateInput!`
2) add a new mutation `orderAddCustomerNote`

### Other solutions I've tried and won't work
…

**Comment by maarcingebala** [comment]
Hey, we have an issue for that already: https://github.com/mirumee/saleor/issues/4799. We're going to extend the `DraftOrderInput`.

**Comment by tilman** [comment]
Okay cool! And what about `CheckoutCreateInput`? I see many use cases where a user wants to attach a note to his order. I thought the `customerNote` field is designed for that. If only `DraftOrderInput` will get updated, the user is still not able to add a note to his checkout/order.

**Comment by maarcingebala** [comment]
I agree that it should be also available in checkout mutations, but I'm not sure yet where to actually put it. One place would be `CheckoutCreateInput`, but this is only used in a mutation to create checkout. We don't have any general mutation to update checkout; instead there is a bunch of mutations to change particular parts of it. I think we would neeed to add a mutation for that - `checkoutUpdateCustomerNote`.
