### ISSUE TITLE
Dashboard 2.0 Automatic Login

### ISSUE THREAD

**Issue by dprad90** [mirumee/saleor#4991]
### What I'm trying to achieve
I would like to automatically login a (super)user into Dashboard 2.0 _after they have logged into their account_ without requiring the user to log in _again_ when accessing Dashboard 2.0 

### Describe a proposed solution
It would be nice if a user is a superuser and logged in, if they could access Dashboard 2.0 without having to log in again

### Other solutions I've tried and won't work
I have spent time attempting to modify the login view in saleor.account.views.py to the following code, but when I visit http://127.0.0.1:8000/dashboard/next/ the user is still being required to login:

```@find_and_assign_anonymous_checkout()
def login(request):
    kwargs = {"template_name": "account/login.html", "authentication_form": LoginForm}
    if request.method == 'POST':
        email = request.POST.get('username')
        password = request.POST.get('password')
        data = {"operationName": "TokenAuth", "variables": {"email": email, "password": password},
                "query": "fragment User on User {  id  email  firstName  lastName  isStaff  note  permissions {    code    name    __typename  }  __typename}mutation TokenAuth($email: String!, $password: String!) {  tokenCreate(email: $email, password: $password) {    token    errors {      field      message      __typename    }    user {      ...User      __typename    }    __typename  }}"}
        payload = {"Content-Type": "application/json"}
        r = requests.post('http://127.0.0.1:8000/graphql/', data=json.dumps(data), headers=payload)
        if r.status_code == 200:
            user = authenticate(username=email, password=password)
            if user is not None:
                auth_login(request, user)

    return django_views.LoginView.as_view(**kwargs)(request, **kwargs)```

**Comment by dprad90** [comment]
I have since modified my above code to the following:

```
@find_and_assign_anonymous_checkout()
def login(request):
    kwargs = {"template_name": "account/login.html", "authentication_form": LoginForm}
    # call dashboard 2.0 login query
    if request.method == 'POST':
        email = request.POST.get('username')
        password = request.POST.get('password')
        data = {"operationName": "TokenAuth", "variables": {"email": email, "password": password},
                "query": "fragment User on User {  id  email  firstName  lastName  isStaff  note  permissions {    code    name    __typename  }  __typename}mutation TokenAuth($email: String!, $password: String!) {  tokenCreate(email: $email, password: $password) {    token    errors {      field      message      __typename    }    user {      ...User      __typename    }    __typename  }}"}
        payload = {"Content-Type": "application/json"}
        r = requests.post('http://127.0.0.1:8000/graphql/', data=json.dumps(data), headers=payload)
        if r.status_code == 200:
            dashkey = 'superlongdashboardkeythatwasretrievedandaddedtosessionstorage'
            request.session['dashboardAuth'] = dashkey

    return django_views.LoginView.as_view(**kwargs)(request, **kwargs)
```

This allows me to add the key (which I retrieved via breakpoints while viewing the request in debug) to SessionStorage. When I visit http://127.0.0.1:8000/dashboard/next/ with the proper key saved in my SessionStorage. I can successfully login to Dashboard 2.0 this way. 

Does anyone have a better suggestion for doing this?

**Comment by patrys** [comment]
Are you using the legacy storefront (based on Django templates) with the new dashboard (using the GraphQL)? If so, there's no easy way to share sessions between them.

We strongly recommend switching to a PWA storefront (we provide an example implementation: https://github.com/mirumee/saleor-storefront) as the legacy storefront is not actively maintained and will be removed in future.

**Comment by dprad90** [comment]
Yes, I am using the old views based on Django templates hoping that I can pass/share the authenticated user session over to Dashboard 2.0. After working with this some more yesterday I **_am_** able to automatically log the user in to Dashboard 2.0 with a token I capture during login to their account called `dashboardAuth`. 

If I (manually) set a sessionStorage variable called `dashboardAuth` with javascript on the login.html page I am able to set this `dashboardAuth` value to the user's key. If I click on the Dashboard 2.0 link I set up (http://127.0.0.1:8000/dashboard/next/) or type in http://127.0.0.1:8000/dashboard/next/ manually after logging in **_I am able to successfully automatically log in without typing in a username or password for Dashboard 2.0_**.

```
    <script>
        var key = "reallylongcapturedtokenkeystring";
        if (typeof (Storage) !== "undefined") {
            sessionStorage.setItem("dashboardAuth", key);
        }
    </script>
```

I have not been able to do this without manually capturing and setting the key. Ideally I would like my view to look like it does below (using django sessions) and still be able to use that javascript code on login.html

```
@find_and_assign_anonymous_checkout()
def login(request):
    kwargs = {"template_name": "account/login.html", "authentication_form": LoginForm}
    # call dashboard 2.0 login query
    if request.method == 'POST':
        email = request.POST.get('username')
        password = request.POST.get('password')
        data = {"operationName": "TokenAuth", "variables": {"email": email, "password": password},
                "query": "fragment User on User {  id  email  firstName  lastName  isStaff  note  permissions {    code    name    __typename  }  __typename}mutation TokenAuth($email: String!, $password: String!) {  tokenCreate(email: $email, password: $password) {    token    errors {      field      message      __typename    }    user {      ...User      __typename    }    __typename  }}"}
        payload = {"Content-Type": "application/json"}
        r = requests.post('http://127.0.0.1:8000/graphql/', data=json.dumps(data), headers=payload)
        if r.status_code == 200:
            capturedtoken = 'reallylongkeytoken'
            request.session['dashboardAuth'] = capturedtoken
          
    return django_views.LoginView.as_view(**kwargs)(request, **kwargs)
```

```
    <script>
        var key = "{{ request.session.dashboardAuth }}";
        if (typeof (Storage) !== "undefined") {
            sessionStorage.setItem("dashboardAuth", key);
        }
    </script>
```

...but the above code does not work as intended because the variable is not passed correctly or not accessible due to the user session I assume. Any ideas that can point me in the right direction?

Thank you for the input, @patrys . I appreciate you getting back to me.
