### ISSUE TITLE
After run npm build-assets more than 2 times 

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor#4996]
### What I'm trying to achieve
build-assets success 
### Steps to reproduce the problem
1. run "npm install" 
2. run "npm audit fix"
3. run "npm audit fix --force"
4. run "npm run build-assets"
### What I expected to happen
See the store front UI build successfully built
### Screenshots

![Capture](https://user-images.githubusercontent.com/40449637/69246149-becb6c00-0bda-11ea-825f-d10c4933e24d.JPG)

**System informaion**
Operating system: Window 10
Browser: Chrome

**Comment by karolkielecki** [comment]
Hi @zatin009 ! Could you please tell me which versions of NodeJS and NPM are you using? Please make sure to use NodeJS > 10.x.

**Comment by zatin009** [comment]
Node : 12.7
npm : 6.11.3
