### ISSUE TITLE
Add posibility to query categories/collections/products using slug

### ISSUE THREAD

**Issue by mateuszkula** [mirumee/saleor#4999]
### What I'm trying to achieve
I would like to be able to fetch single category/product/collection using their slugs instead of ids.

Right now on storefront we must preserve DB id in url and get graphql id from that id when hitting saleor for data(for ex.) `https://pwa.saleor.io/category/groceries/8/`. 

### Describe a proposed solution
Use slug to get category:
```
query {
 category(slug: "groceries") {
  name
  id
 }
}

**Comment by maarcingebala** [comment]
Thanks for opening the issue, I think our storefront API should in fact allow to fetch common catalog-related objects by slug.

**Comment by fowczarek** [comment]
@maarcingebala An example solution for the `product` should look like this:
1. A new query like `product_by_slug` 
2. Query `product` should have 2 arguments `ID` and `slug`. The query should have one of them.
3. Query `product` should have 1 argument like id_or_slug, and try to get product by Id or slug?

**Comment by tboulogne** [comment]
Hello, a little up on this :-) 

@maarcingebala 
@mateuszkula 

thanks for all :-).
