### ISSUE TITLE
why does ProductVariant has attributes as json not as ManyToMany fields?

### ISSUE THREAD

**Issue by pcompassion** [mirumee/saleor#500]
Just curious, it seems like what `attributes` do is what M2M field do usually.

**Comment by patrys** [comment]
That's true but M2M fields are very expensive when updating data. We've built quite a number of stores that not only house tens of millions of products but also have to update them from external sources on a daily basis. Avoiding an additional table access makes this task much faster.

**Comment by pcompassion** [comment]
Thank you for quick answer.

**Comment by patrys** [comment]
We should really add this to the documentation.
