### ISSUE TITLE
Why saleor delete data from user detail when change password? 

### ISSUE THREAD

**Issue by nhetlinna** [mirumee/saleor#5003]
### What I'm trying to achieve
…

### Steps to reproduce the problem
1. When I fill the detail in my account already and click update account it will store in the database but when I change password user detail that I fill it all delete from database 
2. It deletes user detail not only change successfully even change not successfully it will update account successfully  

### What I expected to happen
1. when I change password already it will not update or delete user detail from databases 

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by NyanKiyoshi** [comment]
Hi! Could you give more information about where you are having the issue? A mutation? The storefront 1.0? 2.0?

Which data is deleted/not updated? The description seems to be contradictory, I'm not sure I get what you mean.

**Comment by nhetlinna** [comment]
I just only need to update the password, but it updates the password and also updates all the account information and it makes the whole information in that account detail lose. And it in the "Your Account " section.  
![Screenshot (141)](https://user-images.githubusercontent.com/45730535/69599359-54358880-103f-11ea-8a9a-ec6b89fd821a.png)
![Screenshot (142)](https://user-images.githubusercontent.com/45730535/69599392-6ca5a300-103f-11ea-9782-3ce25261bcf3.png)

**Comment by nhetlinna** [comment]
def get_or_process_password_form(request):
    form = ChangePasswordForm(data=request.POST or None, user=request.user)
    if form.is_valid():
        form.save()
        logout_on_password_change(request, form.user)
        messages.success(
            request, pgettext("Storefront message", "Password successfully changed.")
        )
    return form
   

this one

**Comment by karolkielecki** [comment]
@nhetlinna Hey! It looks like a bug. Sorry for the inconvenience. We'll try to find a solution as soon as we can. Please also keep in mind that we have Storefront 2.0 now. So all new updates will be available in v2.0. We highly recommend you to try 2.0 in the future :) 

https://github.com/mirumee/saleor-storefront#getting-started

**Comment by nhetlinna** [comment]
Can you solve it in v1.0? because I cannot solve it I need your help.

**Comment by maarcingebala** [comment]
We're already working on removing Storefront 1.0 from this repo. This bug will be fixed in repo https://github.com/mirumee/legacy-views which contains the legacy version of Saleor with all the Django views.

**Comment by nhetlinna** [comment]
Yes thank you
