### ISSUE TITLE
unable to checkout on graphql mutation [digital product]

### ISSUE THREAD

**Issue by trence** [mirumee/saleor#5006]
### What I'm trying to achieve
checkout error on when only digital product is left in the cart system, if there is shipping method assigned before

### Steps to reproduce the problem
1. add shippable product
2. add non-shippable (digital) product
4. add shipping method
3. remove all shippable product, left only non-shippable product
4. add shippable product again
5. Error "This checkout doesn't need shipping" caused by execution of graphql mutation `updateCheckoutLine`

### What I expected to happen
able to add shippable product to the checkout cart
suspected: shipping method is not removed when only digital product is left on the cart

**Comment by karolkielecki** [comment]
Thanks for reporting @trence ! We are aware of this issue. If we find a solution, I will let you know. And if you have any feedback or questions, we're happy to help you.
