### ISSUE TITLE
related attributes for product

### ISSUE THREAD

**Issue by pcompassion** [mirumee/saleor#501]
For example,

for starwars3,

if a `format` attribute - dvd is selected, 
one may need further select `region code` attribute.  
if a `format` attribute - book is selected,
one doesn't need to select `region code` attribute.

I guess I can program it, just wanted to make sure if there's a obvious tool that supports this because it seems quite a common requirement.

**Comment by patrys** [comment]
There is currently no way to represent such logic without writing code. I am not sure if it is common enough though. In most stores we built books would be a separate product with an entirely different set of attributes (number of pages, paper/cover type) and we'd use a separate model to represent products grouped together (so when visiting DVD you would see there's also a book, a console game, some stationery and perhaps even toys).

**Comment by pcompassion** [comment]
Thanks for the quick response.
