### ISSUE TITLE
orderUpdateMeta switched input from id:ID! to token:UUID!

### ISSUE THREAD

**Issue by tilman** [mirumee/saleor#5010]
### What I'm trying to achieve
the mutation `orderUpdateMeta` suddenly changed it's input variables from `id:ID!` to `token:UUID!` without a deprecation warning. Also all other `orderUpdate...` mutations are still using the `id:ID!`. So i'm wondering if this change was done by accident or if there was a reason for that.

### Steps to reproduce the problem
1. upgrade to newest version
2. use `orderUpdateMeta`

### What I expected to happen
throw at least a deprecation warning from the old field

**Comment by korycins** [comment]
master branch is still under development and we can't guarantee you that we won't change anything. This change happened only on the master branch, _not between our releases_. This is the reason why you didn't get any deprecation warning.  The second reason - there is no way to deprecate input fields.
According to the mutation `orderUpdateMeta` .  (See also query `orderByToken`.)
If the custom storefront wants to save some data in order (for logged-in customer and guest customer), it can use `orderUpdateMeta`. The previous version of `orderUpdateMeta` (with `ID`) was using permission -  `("order.manage_orders",)`. So only the staff user could change the meta field. 
Related problem - https://github.com/mirumee/saleor/issues/4881

**Comment by tilman** [comment]
Okay, thanks a lot for pointing that out. I was just a bit confused :D
