### ISSUE TITLE
Bump postgres version on CI (django 3.0)

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#5014]
### What I'm trying to achieve
Update psql version to at least 12

Logs from attempt running postgres 12 on tox: https://travis-ci.com/mirumee/saleor/jobs/260642329

**Comment by NyanKiyoshi** [comment]
I'm not sure travis is successfully starting postgres 12... On my branch I see the following:
```
[33;1mStarting PostgreSQL v12[0K
Assertion failed on job for postgresql@12-main.service.
sudo systemctl start postgresql@12-main
travis_time:end:1e5d8958:start=1575257444338539770,finish=1575257444599008071,duration=260468301,event=prepare
```

But no other information. I am not sure travis currently supports 12.

**Comment by krzysztofwolski** [comment]
Django 3.0 drops pg9.4 https://docs.djangoproject.com/en/3.0/releases/3.0/

**Comment by NyanKiyoshi** [comment]
Done for Circle-CI @ #5335
