### ISSUE TITLE
Search backend uses wrong description field

### ISSUE THREAD

**Issue by salwator** [mirumee/saleor#5016]
Saleor uses the new _description_json_ field but the search backend still uses the old _description_ field, which should be dropped by now.
Demo works because _populatedb_ fills both fields with the same content.

**Comment by thewhiterabbit** [comment]
Is this why I get these results?
![Capture](https://user-images.githubusercontent.com/5334222/107718880-c23d8e00-6c8b-11eb-9a04-c9c2c14d27f0.PNG)

Also, I don't want the description dropped because using description_json makes queries more difficult to get just the description text.

Am I wrong that the whole point of graphql is returning readable results?

Keep both! We need both.

**Comment by maarcingebala** [comment]
Descriptions are stored in JSON and this is a format that is used with the Dashboard's content editor [Editor.js](https://editorjs.io/). Internally we transform JSON to plaintext and store the plaintext as well in the database. The plaintext field is used with the product search.

**Comment by thewhiterabbit** [comment]
> 
> 
> Descriptions are stored in JSON and this is a format that is used with the Dashboard's content editor [Editor.js](https://editorjs.io/). Internally we transform JSON to plaintext and store the plaintext as well in the database. The plaintext field is used with the product search.

When I request a product, the description field is empty, only the descriptionJson field is populated. That behavior doesn't coincide with what you just said.

Please refer to f46 in the above image.

**Comment by maarcingebala** [comment]
Which version of Saleor are you using? The changes that I mentioned are very recent, they were merged last week and will be released in Saleor 3.0. `descriptionJson` field is now deprecated in the API and `description` is recommended. Both fields are now based on the same database field so they will be always populated with the same data.

**Comment by thewhiterabbit** [comment]
Installed v2.11.1 as recommended by the documents.
