### ISSUE TITLE
Drop Storefront 1.0

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#5017]
As [announced in the issue #4463](https://github.com/mirumee/saleor/issues/4463#issuecomment-553458615) we're planning to drop Storefront 1.0 from Saleor and archive the current version in [mirumee/legacy-views](https://github.com/mirumee/legacy-views) repository. 

The [removal of Dashboard 1.0](https://github.com/mirumee/saleor/pull/5000) is almost ready and soon afterwards we'll starting working on remove Storefront 1.0 views, templates and their dependencies from the core.

**Comment by MH-sabu** [comment]
@maarcingebala  does that means, we are getting a saleor project where backend +dashboard 2+pwa storefornt will work together  as one project?

**Comment by maarcingebala** [comment]
@MH-sabu These are three separate projects and you'll need to set up each part separatly. In the future we'd like to have some script to run everything with one command, but they will still be three separate processes.
