### ISSUE TITLE
mail translation problem: activate of translation missing

### ISSUE THREAD

**Issue by frankshwb** [mirumee/saleor#5020]
Cheers,

I customized email templates to let saleor send it automatically to our users (e.g. oder/fulfillment confirmation). I also modified translations files and did all necessary steps to make them work (build-emails, compilemessages,....)

Still, there seems to be a problem with translating the mails.

**When did it work?**
With adding the following to '/order/emails.py' in the "collect_data_for_email" function, I managed to let saleor send me perfectly translated mails:
```
language_code = "de"
activate(language_code)
```
So there seems to be a problem with activating translations for emails. Maybe this has something to do with the celery-worker which does not know which translation for a given template to use when sending a mail and therefore falls back on the default language of its configuration.

**Info**
Saleor Version 2.9.0

**Comment by frankshwb** [comment]
Doc I got the 'activate' info from:
[I18n-settings Celery](http://docs.celeryproject.org/projects/django-celery/en/2.4/faq.html#generating-a-template-in-a-task-doesn-t-seem-to-respect-my-i18n-settings)

**Comment by karolkielecki** [comment]
@frankshwb Hi there! 

It seems it's a bug. We'll take a look into this as soon as we can. If I have any news, I will come back to you.
