### ISSUE TITLE
Remove `get_absolute_url()` functions from models. 

### ISSUE THREAD

**Issue by IKarbowiak** [mirumee/saleor#5022]
Remove `get_absolute_url()` functions from models and all uses. It's not needed after removing storefront (#5043). It should be kept only for `DigitalContentUrl`

### Steps to reproduce the problem
1. Parts of saleor code use deprecated `get_absolute_url()`: e.g some emails functions, graphql types like Product.

### What I expected to happen
`get_absolute_url()` functions will be removed, the same as`url` field from Category and Product graphql types.

**Comment by krzysztofwolski** [comment]
How google feed will be able to generate urls to products?
