### ISSUE TITLE
AWS Ubuntu requirements.txt installation error " 

### ISSUE THREAD

**Issue by KristofTomase** [mirumee/saleor#5025]
Hej,
I try install saleor on EC2 , after "pip3 install -r requirements.txt"
I get an error "ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:"

### What I expected to happen
How can i fix it ?
### Screenshots
Error :

Collecting setuptools>=39.2.0
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    setuptools>=39.2.0 from https://files.pythonhosted.org/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl#sha256=c8abd0f3574bc23afd2f6fd2c415ba7d9e097c8a99b845473b0d957ba1e2dac6 (from cairocffi==1.1.0->-r requirements.txt (line 34))

**System information**
Operating system: Ubuntu 18.4 
Nginx
Node.js 10
Python v. 3.7
PostgreSQL 9.4

**Comment by maarcingebala** [comment]
I see that PR #5012 by @krzysztofwolski  changed format of `requirements.txt` and added hashes that were not present there before. I used to generate requirements without hashes and it worked well (`poetry export -f requirements.txt --without-hashes -o requirements.txt`). But I also see that the same requirements file works well on our CI servers (with hashes).

**Comment by maarcingebala** [comment]
@link2buy Does the installation work for you locally? We've also bumped Python to 3.8, maybe there's some issue with outdated `pip` ?

**Comment by krzysztofwolski** [comment]
New version of python and pip should handle it

**Comment by link2buy** [comment]
Hej ,
@maarcingebala i don't know i will check this on local machine and i will back to You , 
@krzysztofwolski ok ... i will try it tomorrow also ... 
Thx for help ;-)

**Comment by krzysztofwolski** [comment]
@link2buy no problem! BTW I really recommend using Docker for deployments. If you maintain your own fork, then you'll need to use an image repository (for example ECR). For easy deployments, you can use ECS or Beanstalk.

**Comment by littlehome-eugene** [comment]
it doesn't work on local ubuntu 28, pytho 3.6.7 pip 19.3.1

**Comment by link2buy** [comment]
Hej,
I have check this also on local , and EC2 python 3.8 ad pip 19.3.1 ...and  it is the same ... 
with Docker Compose all goes smooth :-)

**Comment by link2buy** [comment]
Hej , 
I see that "saleor-pwa" is in another repo.  and it's separate from Docker also...
What's your recomendation in this case to try saleor-storefront with my environment...  
AWS EC2 - Ubuntu 18.04
Nginx 
Docker Compose 

Regards,
Kris

**Comment by karolkielecki** [comment]
@link2buy Hi there! I’d suggest to use AWS S3 static website hosting and deploy storefront independent from backend. Just remember to build storefront with API_URI env variable pointing to your EC2 server graphql endpoint

**Comment by rafitamolin** [comment]
Getting this same error too with my Ubuntu 16 VPS, not hosted on Amazon AWS

**Comment by quinnmil** [comment]
Had this problem running with Python 3.6.4 and pip 19.3.1    
Fastest fix for me was to remove all the hashes from the requirements[_dev].txt. (Select all occurrences, delete the lines)

**Comment by maarcingebala** [comment]
The issue with hashes occurs on some machines/environments and we haven't yet determined the cause. On current `master` the hashes are removed, does this issue still happen @rafitamolin?
