### ISSUE TITLE
Importing product and variant rows from Airtable

### ISSUE THREAD

**Issue by adrienshen** [mirumee/saleor#5029]
### What I'm trying to achieve
We would like to fill Airtable rows for product data as it's easier for administration guys, and have it populate Saleor tables. Preferably, we we want to upload images this way as well.

### Describe a proposed solution
The ideal solution would be filling all products and variants using a spreadsheet like Airtable and importing using a script, or some UI view that admins can use. As for implementation details, if I were to do this, would I use the `productCreate` graphQL mutation or what's the best way to go about setting up this pipeline from Airtable to Saleor? Perhaps there's some internal hook available?

### Other solutions I've tried and won't work
Filling in products through dashboard, but it's too slow for thousands of products.

### Screenshots or mockups
[Example airtable template](https://airtable.com/shrPH2U1lCpSxNK4z)

**Comment by karolkielecki** [comment]
@adrienshen Hi Adrien! If you create a Service Account in the dashboard it will generate an authentication_token. It can be used for API and mutation 'productCreate' and then it will allow you to create products. If you have more questions, let me know and we'll try to help you.
