### ISSUE TITLE
shipping address shouldn't be editable while order is processed?

### ISSUE THREAD

**Issue by pcompassion** [mirumee/saleor#503]
Order has a foreign key to address for shipping address.  
With the current model, I think a user is able to change the address while the order is being processed (before shipped without realizing his past order might be affected)

**Comment by patrys** [comment]
Orders should always create a private copy of both addresses. If you can make it use the same instance that belongs to a user then it's a bug we should fix. The idea is that order should not depend on any external data, be it addresses, products or anything else. This is the only way to accurately represent orders from a long time ago.

**Comment by pcompassion** [comment]
oh.. I guess I was too hasty to ask the question.
I didn't notice the `editable=False` in the address foreignkey field.  

I guess assumption here is that you can edit the address before you create the address model instance.  
But once you have it, you can't change the address. 

I don't know if it would prevent me to present the address form and let users to edit the address.  
If not, I guess it would be a good candidate for documentation, that is `don't let users to edit his/her address`

I couldn't find much info on django doc about `editable=False on foreignkey`
Please correct me if I'm wrong about the assumption.

**Comment by patrys** [comment]
The editable attribute just prevents Django admin from displaying a list of all existing addresses when editing an order. The important bit is that when a user picks one of their addresses for billing or shipping, the order creates a private copy of the address so the user can freely edit their address book without affecting any of the orders. The site staff on the other hand can still modify the addresses assigned to a particular order without affecting user's address book.

**Comment by pcompassion** [comment]
oh where does the code create a private copy of the address? I don't see that.. :( sorry if this is obvious

**Comment by pcompassion** [comment]
@patrys I'm wondering if my last question was overlooked..

**Comment by patrys** [comment]
Oh, sorry. If you take a look at the [checkout code](https://github.com/mirumee/saleor/blob/master/saleor/checkout/core.py) you will notice it's one of the things that happen in `create_order`.

**Comment by pcompassion** [comment]
https://github.com/mirumee/saleor/blob/master/saleor/checkout/core.py#L185
checkout's _save_address()

https://github.com/mirumee/saleor/blob/master/saleor/userprofile/models.py#L107
UserManager's store_address

https://github.com/mirumee/saleor/blob/master/saleor/userprofile/models.py#L27
AddressManager's store_address

stores address and order only points to (foreign key) the stored address.
And I don't see `copying` happening.
Please take a close look.

**Comment by pcompassion** [comment]
I made a pull request, to show a possible `copying`.. 

https://github.com/mirumee/saleor/pull/508

**Comment by pcompassion** [comment]
@artursmet May I ask the expected date? I may implement it myself or wait for your implementation.
