### ISSUE TITLE
Not able access dashboard

### ISSUE THREAD

**Issue by samadak06** [mirumee/saleor#5034]
![Screenshot from 2019-12-04 20-49-49](https://user-images.githubusercontent.com/49633408/70155500-60bd7f00-16d8-11ea-8411-0976591c52b9.png)
 

Hi,

Is anybody help me to access dashboard, i created superuser and tried to login, even not able to access dashboard, Thanks

**Comment by karolkielecki** [comment]
@samadak06 Hi there. We do not maintain Dashboard 1.0 anymore. We're sorry for the inconvenience. We recommend you to try Dashboard 2.0. For more details, please take a look here: 

- https://github.com/mirumee/saleor/issues/4463
- https://github.com/mirumee/saleor/issues/5017
- https://github.com/mirumee/saleor-dashboard#getting-started

If you have any questions, we'll be happy to help you.

**Comment by samadak06** [comment]
> @samadak06 Hi there. We do not maintain Dashboard 1.0 anymore. We're sorry for the inconvenience. We recommend you to try Dashboard 2.0. For more details, please take a look here:
> 
> * #4463
> * #5017
> * https://github.com/mirumee/saleor-dashboard#getting-started
> 
> If you have any questions, we'll be happy to help you.

**Comment by samadak06** [comment]
How i could connect my saleor store front with this saleor-dashboard, i did the same as per the 
https://github.com/mirumee/saleor-dashboard#getting-started and saleor- dashbord works pretty

**Comment by karolkielecki** [comment]
You have to set the API_URI environment variable. API_URI has to be the same for both - storefront and dashboard. You can find more information on how to set up a storefront here:
https://github.com/mirumee/saleor-storefront#getting-started

**Comment by samadak06** [comment]
@karolkielecki  where i should set API_URL, in config.ts 
if not could direct me where i can do that. i'm new to this sorry for my silly questions.
![Screenshot from 2019-12-06 14-29-31](https://user-images.githubusercontent.com/49633408/70310156-02f27980-1835-11ea-8962-00731893a155.png)

**Comment by maarcingebala** [comment]
@samadak06 You need to set this env variable in the terminal where you're running your storefront/dashboard app. The syntax for commands you need to use may differ in various terminals/operating systems. What terminal are you using, `bash` or something else? In most UNIX-based systems you would need to run these commands in your terminal:

```bash
export API_URI="http://localhost:8000/graphql/" 
```

You can inspect if the variable is properly set with:

```bash
echo $API_URI
```

and value of that variabale should be printend in terminal.

If the value is set, in the same terminal you need to run `npm install` and `npm start`.

The examples above assume that I'm running my local Saleor backend at `localhost:8000` (which is the default setting).

Please read about setting environment variables in your terminal/operating system.

**Comment by Pichnyty** [comment]
Hi @maarcingebala I completed set the environment variable successfully However i tried to access to admin dashbard using admin@example.com & password : admin & the result show " saleor ran into unexpected problem" as below image
Terminal : Command Prompt window 10

**Comment by Pichnyty** [comment]
![ddd](https://user-images.githubusercontent.com/54165288/70726142-2daa6980-1d30-11ea-9661-496c046c187a.JPG)

**Comment by zatin009** [comment]
My npm console after run command "npm start"
![RRR](https://user-images.githubusercontent.com/40449637/70726319-7feb8a80-1d30-11ea-9325-ce9dbb884439.JPG)

**Comment by samadak06** [comment]
> Hi @maarcingebala I completed set the environment variable successfully However i tried to access to admin dashbard using [admin@example.com](mailto:admin@example.com) & password : admin & the result show " saleor ran into unexpected problem" as below image
> Terminal : Command Prompt window 10

@Pichnyty 
configure env variable as mentioned -

You need to set this env variable in the terminal where you're running your storefront/dashboard app. The syntax for commands you need to use may differ in various terminals/operating systems. What terminal are you using, bash or something else? In most UNIX-based systems you would need to run these commands in your terminal:

export API_URI="http://localhost:8000/graphql/" 
You can inspect if the variable is properly set with:

echo $API_URI
and value of that variabale should be printend in terminal.

If the value is set, in the same terminal you need to run npm install and npm start.

The examples above assume that I'm running my local Saleor backend at localhost:8000 (which is the default setting).

Please read about setting environment variables in your terminal/operating system.

**Comment by Pichnyty** [comment]
@samadak06 Yes I completed run in saleor instance already then I run "npm start" in saleor-dahsboard folder following the instruction however the superuser I created via django python command can access to storefront but not the admin dashboard I run.Here's mine nodeJs terminal
![70726319-7feb8a80-1d30-11ea-9325-ce9dbb884439](https://user-images.githubusercontent.com/54165288/70728253-a959e580-1d33-11ea-9d71-616bc16d6ff8.jpg)

& this is my browser console
![qqq](https://user-images.githubusercontent.com/54165288/70728394-e9b96380-1d33-11ea-8be1-27c96b096f68.JPG)

**Comment by Pichnyty** [comment]
![qqq](https://user-images.githubusercontent.com/54165288/70728518-25ecc400-1d34-11ea-9f8c-b6ce4d67c047.JPG)

**Comment by samadak06** [comment]
@Pichnyty do you set the env variable. 
see screeen shot of mine as its my saleor runs local host.
![Screenshot from 2019-12-12 23-01-13](https://user-images.githubusercontent.com/49633408/70735064-7283cf80-1d33-11ea-9c36-907e796f6937.png)

**Comment by zatin009** [comment]
@samadak06 Yes I did  which filename in the above image you set ?

**Comment by Pichnyty** [comment]
@samadak06 Yes I did Could you tell me which filename in the above image you set ?

**Comment by samadak06** [comment]
@Pichnyty src->config.ts

**Comment by alekmlynek** [comment]
I think this is a documentation problem. If you follow the Docker installation instructions, the last step simply tells you to create a superuser and the "next" set of instructions tell you to log in using project:port/dashboard which gives me a 404. For Saleor newbies that just want to get started this is really confusing.

I "think" you can download Saleor as a Django package which will include the storefront, but not the dashboard. You have to install that separate? 🤷‍♂️
