### ISSUE TITLE
Checkout page - mobile view 

### ISSUE THREAD

**Issue by car3oon** [mirumee/saleor#504]
Current checkout view on mobile devices looks like below:
![current-checkout-view](https://cloud.githubusercontent.com/assets/4738588/13567752/5bc19c0e-e45d-11e5-9c2d-bc4adff66f0d.png)

**Order summary** block is outside the form. In my opinion it should at least look like part of it. 
My proposition:
![new-checkout-view](https://cloud.githubusercontent.com/assets/4738588/13567785/a3dbaffc-e45d-11e5-8dc4-bc55bdb75cdc.png)
Of course heading `Order summary` might be visible only on mobile devices.

**Comment by patrys** [comment]
Not sure why it should look like part of the form (it has a separate submit button) but I agree that there should be a header on mobiles. Putting summary above button requires user to scroll past the same items on each checkout step.

**Comment by car3oon** [comment]
It was more like "it looks weird and empty" idea and i didn't consider the scroll case in which you're right . As you said adding header on mobiles should do the job.

**Comment by weronka** [comment]
Saleor storefront looks better now and has new UX in checkout so this issue can be closed.
