### ISSUE TITLE
(question) how does test cases use previous test's result?

### ISSUE THREAD

**Issue by littlehome-eugene** [mirumee/saleor#5040]
I see object_instance.save() inside many test functions.

For instance

 ```
def test_is_valid_shipping_method(checkout_with_item, address, shipping_zone):
     checkout = checkout_with_item
     checkout.shipping_address = address
     checkout.save()
```

I guess following tests are using the saved object instance, or am I misreading intention of the code? 

Maybe something like this?

```
order.save()

do_something(order_id=order.id)
def do_something(order_id):
   pass
```

**Comment by patrys** [comment]
All tests are separated and the changes they make are rolled back. The order in which tests are executed does not matter.

**Comment by littlehome-eugene** [comment]
Thanks for the answer
