### ISSUE TITLE
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==

### ISSUE THREAD

**Issue by tim-hub** [mirumee/saleor#5045]
Is OK to develop/install saleor with Python3.8 on Mac? It seemed that I cannot,  ` importlib-resources; python_version < "3.7"`

### What I'm trying to achieve
to install locally on mac
### Steps to reproduce the problem
1.  pip install -r requirements_dev.txt

### What I expected to happen
no errors

### Screenshots

error:
```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    importlib-resources; python_version < "3.7" from https://files.pythonhosted.org/packages/2f/f7/b4aa02cdd3ee7ebba375969d77c00826aa15c5db84247d23c89522dccbfa/importlib_resources-1.0.2-py2.py3-none-any.whl#sha256=6e2783b2538bd5a14678284a3962b0660c715e5a0f10243fd5e00a4b5974f50b (from pre-commit==1.20.0->-r requirements_dev.txt (line 521))
(
```

**System information**
Operating system:  Mac OS
Browser: None

**Comment by andy1729** [comment]
Hey @tim-hub  I am facing same issue while trying to run a fresh version. Did you able to solve this issue?? if yes, then how??
Please let me know!
Thanks!

**Comment by tim-hub** [comment]
> Hey @tim-hub I am facing same issue while trying to run a fresh version. Did you able to solve this issue?? if yes, then how??
> Please let me know!
> Thanks!

I indeed solve the problem, but sorry I forgot how I solved it, but it is like I use conda and I forgot to active python 3.7

**Comment by sakesun** [comment]
Got same problem with Python 3.7

**Comment by devyog** [comment]
yes i am also facing the same problem, please reopen this issue to get this addressed
OS: Ubuntu 18

**Comment by KhantZO** [comment]
I am facing this issue both on my pc and macbook when doing a fresh install. I attached a photo of the error I encountered on PC below.
![Capture](https://user-images.githubusercontent.com/32387965/71547267-4cfdf380-29cc-11ea-810a-5b2bf15c1ddb.JPG)

**Comment by NyanKiyoshi** [comment]
Looks like it might be because Poetry doesn't detect the wheels requirements and thus doesn't put them into the requirement file. I did not manage to find a proper fix for this sadly... For now we should stick to not using hashes 😕
