### ISSUE TITLE
django-cache-url deprecated notice

### ISSUE THREAD

**Issue by marquicus** [mirumee/saleor#5046]
django-cache-url==3.0.0 is an actual dependency to control CACHES django variable anyways it has a deprecation notice

### What I'm trying to achieve
Maintaining control over environment variables

### Describe a proposed solution
Use simple os.environ.get function or [django-environ](https://github.com/joke2k/django-environ)

### Other solutions I've tried and won't work
…

**Comment by NyanKiyoshi** [comment]
@IKarbowiak I think we can drop it in https://github.com/mirumee/saleor/pull/5043 if not already done? Can you check for me? Used by `saleor.settings.CACHES` and `saleor.core.check_session_caching`; we don't use sessions anymore–speaking of sessions, we should be able to drop `django.contrib.sessions.middleware.SessionMiddleware` I don't see any use anymore for it (apart... doing nothing whenever a GraphQL request is done 😉).

The `CACHES` were only used for sticky sessions behind load non-sticky balancers.

**Comment by IKarbowiak** [comment]
It's not done yet, I will drop it in #5043 :)
