### ISSUE TITLE
Can't Migrate Database

### ISSUE THREAD

**Issue by roshan172** [mirumee/saleor#5053]
I cloned this project in my localhost and I installed all the requirements as well that are mentioned in the requirements.py but when I enter "python manage.py makemigrations" it is not responding.

What is missing?

**Comment by korycins** [comment]
Hi
1) Please familiar with the definition of `makemigrations` https://docs.djangoproject.com/en/3.0/ref/django-admin/#makemigrations
2) We don't have file `requirements.py`. Do you mean `requirements.txt`?
3) Have you checked an installation section in our documentation?
4) Did you turn on a DB?

**Comment by roshan172** [comment]
Actually there was something wrong with the Database setup. Actually, I was having a '@' in my Postgres password.
