### ISSUE TITLE
Come up with a new test structure

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#5059]
Currently it is very awful experience when looking for given API tests. Now we are dropping the Django views, we should consider rethinking the structure for better readability, prevent human errors and missing tests.

For example, when looking at the structure we should be able to tell where to find a test for:
- filtering products by attributes;
- creating a product attribute;
- etc.

**Comment by krzysztofwolski** [comment]
Also - take logic out of gql code module. Some of Saleor mutations have lots of logic which shouldn't be there (I'm looking at you, checkoutComplete!).

At my other projects, I usually start with single `test.py` at the module level for general (integration?) tests and create `test_views.py`, `test_calculations.py` for unit tests. If some function has _lots_ of test cases then it's moved into a separate file to avoid >1kloc files.

Speaking of filtering: `saleor/product/test_filters.py` should contain all filters, right now it seems that `saleor/graphql/product/filters.py` has more than gql specific utils.  Resolving this issue would help with test placement.

**Comment by maarcingebala** [comment]
I think we can close this one. Tests have been splitter into smaller modules.
