### ISSUE TITLE
How to register model in admin panel

### ISSUE THREAD

**Issue by pandeyroshan** [mirumee/saleor#5062]
I have created one extra app and inside of which I have created several models, how can I register them into the admin site so that they become visible on the frontend.

**Comment by karolkielecki** [comment]
@pandeyroshan Hey! Are you talking about Dashboard 2.0? If yes, then please keep in mind that all modules use graphql API to communicate with the dashboard. If you would like to extend it, you need to become more familiar with saleor.graphql module.

**Comment by pandeyroshan** [comment]
Ok, now I'm a lot more clear than previously.
