### ISSUE TITLE
Is there anyway to change the authentication system with username or phone number instead email?

### ISSUE THREAD

**Issue by mjafari98** [mirumee/saleor#5065]
Hi,
I did install Saleor and tried hard to change the email authentication system to Username but I couldn't achieve this functionality.
And of course, I didn't find any options there to choose whether I want which one of the systems.
Is there anyway to change the authentication system with username or phone number instead email?

**Comment by karolkielecki** [comment]
@mjafari98 Hi there! Thanks for asking. So database table user uses an email as a unique field. Django requires to have a dedicated unique field for the user model, and for us it's an email.  There is no easy way to change email for the username. However, we'll think about what we can do/improve in this area.
