### ISSUE TITLE
How to Customize Model

### ISSUE THREAD

**Issue by pandeyroshan** [mirumee/saleor#5066]
I want to add some extra database tables in the existing project, how can I do that. I mean I just want to register the database table in the dashboard. How can I do that ??

**Comment by krzysztofwolski** [comment]
Is the existing project on Django?

Anyway, to add more functionality to the dashboard you have to extend API and then take care of the frontend part (add views and forms). 
Since we dropped Dashboard v1, we do not use Django modelforms and views anymore.
