### ISSUE TITLE
GraphQL sends over a 0 usage limit when creating vouchers on Dashboard 2.0

### ISSUE THREAD

**Issue by cheewoei1997** [mirumee/saleor#5068]
### What I'm trying to achieve
Add a new voucher in dashboard 2.0 with unlimited number of uses. This basically means not checking either boxes under usage limit.

### Steps to reproduce the problem
1. Create a new voucher in Dashboard 2.0
2. Leave the usage limit checkboxes unticked

### What I expected to happen
Create a voucher with no limit on the number of uses.

### Screenshots
<img width="1440" alt="Screenshot 2019-12-12 at 5 46 57 PM" src="https://user-images.githubusercontent.com/14294811/70701638-a943f080-1d07-11ea-823a-1385948052d4.png">
<img width="1440" alt="Screenshot 2019-12-12 at 5 49 33 PM" src="https://user-images.githubusercontent.com/14294811/70701707-caa4dc80-1d07-11ea-8a47-cffef4648d77.png">
<img width="1440" alt="Screenshot 2019-12-12 at 5 47 04 PM" src="https://user-images.githubusercontent.com/14294811/70701639-a943f080-1d07-11ea-951a-efbebe776e70.png">

**System information**
Operating system: macOS 10.15.1
Browser: Google Chrome Version 79.0.3945.79 (Official Build) (64-bit)

**Comment by NyanKiyoshi** [comment]
@maarcingebala it sends 0 as `usage_limit` which is handled as if it was 'only usable 0 times' instead of 'usable infinite times'. I think setting it 0 or `null` should have the same behavior. What do you think?

**Comment by fowczarek** [comment]
It's a bug related to the dashboard2.0. `usage_limit` is invalid only when creating a new voucher. When you update existing voucher and `usage_limit` is unchecked input have `null` instead of `0`.

**Comment by fowczarek** [comment]
I've created an issue in dashboard repo.
https://github.com/mirumee/saleor-dashboard/issues/322
