### ISSUE TITLE
staff user login Procedure

### ISSUE THREAD

**Issue by pandeyroshan** [mirumee/saleor#5069]
How can staff user login into the dashboard, I mean there is an option to add staff user from the admin site but where is the password field, it's very confusing.

**Comment by karolkielecki** [comment]
@pandeyroshan Hey! Could you tell us more details about your issue and provide the screenshots?

**Comment by pandeyroshan** [comment]
Everything is clear, I have figured it out. Thanks for your reply, I really appreciate that :-)

**Comment by Batgerel53** [comment]
@pandeyroshan  How do you that

**Comment by pandeyroshan** [comment]
Hey @Batgerel53 That was 2 years ago, I don't remember it properly now.

**Comment by Batgerel53** [comment]
okay thanks :)
