### ISSUE TITLE
Unable to deploy saleor on heroku trough deploy button.

### ISSUE THREAD

**Issue by giovannipiccinelli** [mirumee/saleor#5070]
### What I'm trying to achieve
Deploy on the heroku server

### Steps to reproduce the problem
1. Click on the deploy button

### What I expected to happen
Deployment

### Screenshots

![Screen Shot 2019-12-15 at 1 15 37 PM](https://user-images.githubusercontent.com/7911077/70862449-0379c700-1f3d-11ea-909a-bab3933f851f.png)
![Screen Shot 2019-12-15 at 1 15 32 PM](https://user-images.githubusercontent.com/7911077/70862451-0b396b80-1f3d-11ea-9bce-6f61d4ea567d.png)

**System information**
Operating system: Heroku
Browser: Chrome

**Comment by maarcingebala** [comment]
Hey, thanks for reporting. It's likely that the Heroku deploy is broken on `master` since we're doing a lot of changes in the core now, but we'll try to look at it as soon as possible.
