### ISSUE TITLE
Production deployement (without docker)

### ISSUE THREAD

**Issue by tboulogne** [mirumee/saleor#5073]
Hello,

Thanks for this great project. 
Juste missing a production deployement doc without docker :-(.
Any tips could be welcome.

Other question : Does celery required  (or we could drop)?

Thanks for help.

Regards

Thierry
Saleor newbie

**Comment by karolkielecki** [comment]
@tboulogne Hey! Please check does your cloud have instructions on how to deploy django and python apps. If you need more help, let us know.

**Comment by tboulogne** [comment]
@karolkielecki thanks i will try deployment. So, does celer required or could i drop it ?

Thanks

**Comment by korycins** [comment]
@tboulogne We are using celery in cases like - sending emails, minimal pricing calculation, sending webhooks, preparing images. If you want you can try to replace celery with something different (but this will require some development from you, and we don't have any guides for that). 
Or experiment with task-always-eager. https://docs.celeryproject.org/en/latest/userguide/configuration.html#task-always-eager
