### ISSUE TITLE
setting up saleor on subpath

### ISSUE THREAD

**Issue by maxim-devlop** [mirumee/saleor#5084]
Hi everyone,

i am trying to install saleor on my self hosted productive server, where i am already using nginx as proxy and have other projects. Saleor should still run on http, because nginx sets https and forwards on port 8000. Thereby i am forced to use saleor on subpath:
**www.example.com/shop**

I could not find any information about this, but tried to set force_script_name to shop

`FORCE_SCRIPT_NAME = "/shop"`

and also tried to change urls.py to something like:

```
prefixShop = "shop/";

non_translatable_urlpatterns = [
    url(rf'^{prefixShop}graphql/', csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(
        rf'^{prefixShop}sitemap\.xml$',
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(rf'^{prefixShop}i18n/$', set_language, name="set_language"),
    url(f'{prefixShop}', include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(rf'^{prefixShop}', include(core_urls)),
    url(rf'^{prefixShop}checkout/', include((checkout_urls, "checkout"), namespace="checkout")),
    url(rf'^{prefixShop}jsi18n/$', JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(rf'^{prefixShop}order/', include((order_urls, "order"), namespace="order")),
    url(rf'^{prefixShop}page/', include((page_urls, "page"), namespace="page")),
    url(rf'^{prefixShop}products/', include((product_urls, "product"), namespace="product")),
    url(rf'^{prefixShop}account/', include((account_urls, "account"), namespace="account")),
    url(rf'^{prefixShop}feeds/', include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(rf'^{prefixShop}search/', include((search_urls, "search"), namespace="search")),
]
```

But the setup also fails. Is there any possibility to setup saleor on subpath?

Thanks in advance

Regards,
Maxim

**Comment by korycins** [comment]
@maxim-devlop Why don't you forward load to saleor on the nginx lvl? Nginx should handle all requests which come to {prefixShop} and forward it to Saleor

**Comment by maxim-devlop** [comment]
@korycins ok, if its easier way. I will try in the next few days and give feedback. Thank you.

P.S. do you have sample nginx configuration for this purpose?

**Comment by korycins** [comment]
@maxim-devlop, unfortunately, I don't have any nginx config
