### ISSUE TITLE
Add isInWishlist to Product

### ISSUE THREAD

**Issue by gsoec** [mirumee/saleor#5086]
### What I'm trying to achieve
[Feature request]
Add `isInWishlist` to `Product` in order to indicate whether a product had been added to wishlist on detail page of product.

**Comment by maarcingebala** [comment]
There are two reasons I think this should be handled in the client (frontend):
- our wishlists API works only for authenticated customers. We don't use sessions in our API which means that for guest customers we need to implement the wishlist functionality in the frontend.
- we want our storefront to work offline and wishlist is one of the features that should work in that mode too. Again- this means that the client should implement the feature and only persist the wishlist in the backend for authenticated users, once they're online.
