### ISSUE TITLE
Variant attributes should be copied as well when order is placed

### ISSUE THREAD

**Issue by pcompassion** [mirumee/saleor#509]
as with shipping address in https://github.com/mirumee/saleor/issues/503

I think ProductVariant's attributes should be copied.

**Comment by patrys** [comment]
Most stores only need the SKU to fulfil an order. I'm not sure we need to copy all attribute values by default.

**Comment by pcompassion** [comment]
It came up when I needed to display what a user bought for himself.

Some of the attributes were important enough to show.  
Well I just wanted to share my thoughts.

**Comment by patrys** [comment]
We're open to discuss this. We have one store that also wants to show sizes as a separate field in order details (instead of part of the product's name).

**Comment by patrys** [comment]
@artursmet Want to share your insight?

**Comment by artursmet** [comment]
In my opinion we should also copy the attributes. As you mentioned, there are stores that have all variants with the same names, only size or color differ. 
We can implement it by the way with the fix for shipping address you mentioned above.
