### ISSUE TITLE
Easy way to distinct between environments

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#5090]
### What I'm trying to achieve
I would like to have a way to distinct dev, stage and prod environments visually when using dashboard. When working on a project which is already deployed, it's easy to open the wrong tab and make changes on production thinking it was dev env. 

### Describe a proposed solution
Allow the dashboard to change header color based on an environment variable.

**Comment by maarcingebala** [comment]
I think it's not related to the core, but it's a frontend task. Transfer to `saleor-dashboard`?

**Comment by krzysztofwolski** [comment]
I'm not sure if it can be done frontend only or have to be exposed in API
