### ISSUE TITLE
Assign countries to discounts

### ISSUE THREAD

**Issue by timuric** [mirumee/saleor#5091]
Our team would like to add ability to assign countries for discounts. 
By default discounts would apply to all countries unless at least one is specified. 

I am curious how this fits into Saleor's roadmap and if authors are interested in contribution.

**Comment by krzysztofwolski** [comment]
Note: ATM Discounts are the same for *all* the visitors which helps with price calculation and caching. Introducing country restriction for discounts will break this.

Making vouchers country-restricted is on the other hand really easy, its model already has country selection field, but only for shipping. Anyway, there will be need for custom code.

**Comment by maarcingebala** [comment]
@timuric I think this feature will be on our roadmap very soon as we're planning to build multi-channel support in Saleor to handle selling in different countries. No specific dates yet but it's planned for Q1 of 2020.

**Comment by timuric** [comment]
@maarcingebala awesome! thanks for clarifying it.
