### ISSUE TITLE
Problem with Heroku Button deployment

### ISSUE THREAD

**Issue by nasim31** [mirumee/saleor#5093]
### What I'm trying to achieve
…Deploying the demo with heroku.
 
### Steps to reproduce the problem
1. Deploy with heroku button on this page.
  https://github.com/mirumee/saleor

### What I expected to happen
… Heroku deployment shouls be finished successfully

### Screenshots

![heroku-error](https://user-images.githubusercontent.com/5971496/71263548-14c13a00-2368-11ea-9b7e-88b284b7cf53.png)

**System information**
Operating system:
Can I use the demo deployment for production use ?

**Comment by fowczarek** [comment]
Duplicated #5070
