### ISSUE TITLE
Saleor LOGO Alteration

### ISSUE THREAD

**Issue by pandeyroshan** [mirumee/saleor#5094]
Where I can edit the logo of the Saleor, in the navigation bar

**Comment by acidlake** [comment]
Hello there, I guess you are talking in the storefront right? if so go to:

`src/components/MobileNav/NavList.tsx `
and there you can change the code, I replaced the code with an img tag, and added a class on the sas file.

**Comment by pandeyroshan** [comment]
Thanks @acidlake
