### ISSUE TITLE
Add to Cart Notification Unclear on Demo

### ISSUE THREAD

**Issue by it-all** [mirumee/saleor#5097]
On the front end demo (is it running the latest version?), when you add an item to the shopping cart, it seems that the only notification is the number above the cart icon on top appearing or incrementing. However, if you've scrolled the page down just a bit so the cart icon is not visible, there is no indication.

https://pwa.saleor.io/product/t-shirt/112/

**Comment by karolkielecki** [comment]
@it-all Thanks for reporting. We'll investigate what's causing this issue. 
Best

**Comment by it-all** [comment]
Thanks. I noticed other minor but obvious things that are issues with the demo site, but I'm not sure you want them reported here. I suspect that demo issues could be affecting your adoption rate, though.
