### ISSUE TITLE
Add Schema.org markup to emails

### ISSUE THREAD

**Issue by bitrut** [mirumee/saleor#51]
To consider: https://developers.google.com/gmail/schemas/

**Comment by elwoodxblues** [comment]
We don't use Schema.org anymore.

**Comment by patrys** [comment]
Not sure about this one. `JSON LD` used by "inbox actions" Gmail feature does use schema.org schemas.

**Comment by elwoodxblues** [comment]
Issue #1371 contains more details about it.
