### ISSUE TITLE
css and js directories not found under static

### ISSUE THREAD

**Issue by tahaderouiche** [mirumee/saleor#510]
Hi,
Just wanted to check, as I cloned the project and started working on it, that I couldn't find the css and js under static folder (/saleor/saleor/static/* )

They are used by both base.html found under templates and dashboard.

I ended up copying them from another local version I had when I cloned the git version a week ago. 
Not sure why I am seeing this inconsistency, I verified and I can't see the folders on git now. Were they moved somewhere else
Thanks
Taha

**Comment by patrys** [comment]
The [installation](https://github.com/mirumee/saleor/wiki) steps 5 and 6 specifically install `grunt` and use it to build the files.

**Comment by tahaderouiche** [comment]
Thanks a lot, I missed that the second time I cloned it.
