### ISSUE TITLE
value too long for type character varying(100)

### ISSUE THREAD

**Issue by gsoec** [mirumee/saleor#5100]
```python
avatar = VersatileImageField(upload_to="user-avatars", blank=True, null=True)
```
max_length of `VersatileImageField` is default to 100.

Fix:
```python
avatar = VersatileImageField(upload_to="user-avatars", blank=True, null=True, max_length=200)
```

**Comment by karolkielecki** [comment]
@gsoec Hey! Thanks for reporting. We'll check it out as soon as we can.

**Comment by maarcingebala** [comment]
We could change all file fields to `max_length=255` consistently. @gsoec maybe you'd have time to provide a PR for this change? I'd be happy to offer any guidance on this 🙂

**Comment by gsoec** [comment]
@maarcingebala I’m a little overloaded right now, but i'd like to create PR when i have free time.
