### ISSUE TITLE
How to deploy Saleor on Centos 7?

### ISSUE THREAD

**Issue by theanhvo** [mirumee/saleor#5101]
I had config as into Document saleor but when enter http://localhost:8000 not display home page , it redirect /graphql . Please help me. Thanks team.

**Comment by acidlake** [comment]
Hello @theanhvo this is the API Backend part, you will only see the Graphql part, after that you need to downlod the [StoreFront](https://github.com/mirumee/saleor-storefront) :  to
 see the homepage and the [Dashboard ](https://github.com/mirumee/saleor-dashboard)  for the administration part, follow the guide:

`git clone https://url
cd folder-name
npm i or npm install or yarn install
Fore the storefront you only need to set the API_URI on your env. Or do it like this:
API_URI=‘http://IP:8000/graphql’ npm start


For the Dashboard 
API_URI=‘http://ip:8000/graphql’ APP_MOUNT_URI=‘/‘ npm start
`

Note: API_MOUNT_URI you set the url for the dashboard. Can be anything

**Comment by theanhvo** [comment]
> Hello @theanhvo this is the API Backend part, you will only see the Graphql part, after that you need to downlod the [StoreFront](https://github.com/mirumee/saleor-storefront) : to
> see the homepage and the [Dashboard ](https://github.com/mirumee/saleor-dashboard) for the administration part, follow the guide:
> 
> `git clone https://url
> cd folder-name
> npm i or npm install or yarn install
> Fore the storefront you only need to set the API_URI on your env. Or do it like this:
> API_URI=‘[http://IP:8000/graphql’](http://IP:8000/graphql%E2%80%99) npm start
> 
> For the Dashboard
> API_URI=‘[http://ip:8000/graphql’](http://ip:8000/graphql%E2%80%99) APP_MOUNT_URI=‘/‘ npm start
> `
> 
> Note: API_MOUNT_URI you set the url for the dashboard. Can be anything

Thanks very much @acidlake

**Comment by karolkielecki** [comment]
Also, if you would like to see static views, here is the link to our legacy Saleor: https://github.com/mirumee/legacy-views
