### ISSUE TITLE
npm run build-assets don't work

### ISSUE THREAD

**Issue by valentinc94** [mirumee/saleor#5104]
npm run build-assets

missing script: build-assets
did you mean;

build-schema
build-mails

and when i typing python manage.py runserver only show me

http://127.0.0.1:8000/graphql/ 

what happen?

**Comment by acidlake** [comment]
> npm run build-assets
> 
> missing script: build-assets
> did you mean;
> 
> build-schema
> build-mails
> 
> and when i typing python manage.py runserver only show me
> 
> http://127.0.0.1:8000/graphql/
> 
> what happen?

What are you trying to do? If you want the storefront you need download it from the repo and then you can go to the homepage

**Comment by valentinc94** [comment]
thanks can you help me with this

URI of a running instance of Saleor GraphQL API. If you are running Saleor locally with the default settings, set API_URI to: http://localhost:8000/graphql/.

can you help me explained this?

**Comment by acidlake** [comment]
Yes, if you do the setup local, the API_URI is: http://localhost:8000/graphql. You will use that url with the Store dashboard and the storefront

**Comment by theanhvo** [comment]
i had problem as you! :((

**Comment by acidlake** [comment]
> i had problem as you! :((

Did you manage to fix your problem?

**Comment by karolkielecki** [comment]
npm run build-assets - was related to the old storefront which is not available in the master repo.

**Comment by valentinc94** [comment]
But what i need to do? Running localhost manage.py runserver and npm start in storefront can you explained this i dont understand jeje

**Comment by acidlake** [comment]
> But what i need to do? Running localhost manage.py runserver and npm start in storefront can you explained this i dont understand jeje

Inside the storefront folder:
npm install
API_URI=‘http://localhost:8000/graphql’ npm start
After that you shoud go to http://localhost:3000 wait few minutes to compile and the storefront should be up

**Comment by rahimasgari** [comment]
> > But what i need to do? Running localhost manage.py runserver and npm start in storefront can you explained this i dont understand jeje
> 
> Inside the storefront folder:
> npm install
> API_URI=‘[http://localhost:8000/graphql’](http://localhost:8000/graphql%E2%80%99) npm start
> After that you shoud go to http://localhost:3000 wait few minutes to compile and the storefront should be up

I have the same problem.
where is storefront folder?
i think the installation documentation is outdated and confusing to new users.

**Comment by coolzilj** [comment]
I believe [storefront](https://github.com/mirumee/saleor-storefront) and [dashboard](https://github.com/mirumee/saleor-dashboard) are in seperate repos now.

**Comment by dkondraszuk** [comment]
Hello lads, 
Are there any plans to update documentation? Current one is outdated and really confusing for new users. 
Btw. when I hit the main page of storefront (localhost:3000) I have no content at this page except like header and footer. In the middle of page there are only moving 3 dots (like loading content) but it never loads anything. Is it correct?

**Comment by karolkielecki** [comment]
@dkondraszuk Hey. Yes, we're going to update our docs as soon as we can. Which version of Saleor are you using?

**Comment by dkondraszuk** [comment]
@karolkielecki Cześć. I'm using the latest master, so 2.9 :) Are there any plans to provide more templates for storefront? What date can we expect docs update?

**Comment by karolkielecki** [comment]
Hej! We have dropped Dashboard and Storefront 1.0 and we don't maintain them anymore. Versions 2.0 Storefront and Dashboard are in the separate repositories and here are the links:
https://github.com/mirumee/saleor-storefront
https://github.com/mirumee/saleor-dashboard

 We'll update the docs as soon as possible. There is no specific date.

**Comment by OmniOracle** [comment]
So do we need to clone the storefront and dashboard repo's into our main saleor folder in order to have a complete instance of saleor? Could we get some guidance on how to run a full instance of saleor locally?

**Comment by maarcingebala** [comment]
@OmniOracle Yes, this repo contains only the backend part now. [As it says in the README](https://github.com/mirumee/saleor/#pwa-storefront), you need to go [saleor-storefront](https://github.com/mirumee/saleor-storefront/) or [saleor-dashboard](https://github.com/mirumee/saleor-dashboard/) for the frontend parts.

We're planning to release a tool that will make it easier to setup all parts with one command so you don't have to go to three different repos.

**Comment by pljspahn** [comment]
Found this issue as I was hoping to test out Saleor as I migrate our brick and mortar's old Magento site to something new. I've been working on a custom django app and figured I'd try out Saleor just to see if it will be easier. 

Go to homepage, find github repo, follow instructions for installation, and I can't install because apparently the documentation is out of date and is giving me bad instructions? That's a very bad first impression and since I'm sure you're very busy you can appreciate that I am busy also and don't have time to chase down random discrepancies like this, let alone before I even get the project installed.

PTSD flashbacks to using Magento 1.2.

**Comment by AlvaroPica** [comment]
Same issue regarding `npm run build-assets` following the instruction guide for Windows (W10)

**Comment by NyanKiyoshi** [comment]
Make sure you are looking at the right version: 2.10 (top of the page, if not, hard refresh the page) https://docs.saleor.io/docs/developer/installation --- https://github.com/mirumee/saleor-docs/issues/123#issuecomment-626554887

**Comment by DevAbhinav2073** [comment]
3rd of June and yet the documentation is not up-to-date

**Comment by NyanKiyoshi** [comment]
@DevAbhinav2073 it looks up-to-date to me. If that's out-of-date, hard refresh the page.

**Comment by DevAbhinav2073** [comment]
@NyanKiyoshi Yes got it. Thank you

**Comment by mandjo2010** [comment]
> 



> Hej! We have dropped Dashboard and Storefront 1.0 and we don't maintain them anymore. Versions 2.0 Storefront and Dashboard are in the separate repositories and here are the links: https://github.com/mirumee/saleor-storefront https://github.com/mirumee/saleor-dashboard
> 
> We'll update the docs as soon as possible. There is no specific date.

@karolkieck, is there anyway to get back to the old version ?

**Comment by karolkielecki** [comment]
@mandjo2010 Hi, is there any reason you would like to get back to the old version? You can find the legacy fork here: https://github.com/mirumee/legacy-views. Please remember that we don't maintain it or provide any support related to the old version.

**Comment by mandjo2010** [comment]
Thank you @karolkielecki, I was finally able to lunch it.

**Comment by mandjo2010** [comment]
Hi Karol,

i don't know if you will be able to read this message. I have a couple of
questions about this repos.


Thanks
