### ISSUE TITLE
Saleor ran into an unexpected problem.  When login /dashboard? 

### ISSUE THREAD

**Issue by theanhvo** [mirumee/saleor#5106]
Saleor ran into an unexpected problem.  When login /dashboard.
Please help me !

**Comment by acidlake** [comment]
That’s problem with your API_URI. Open chrome and the developer tools, check the console. And paste the error here or an screenshot

**Comment by aselam** [comment]
> 
> 
> Saleor ran into an unexpected problem. When login /dashboard.
> Please help me !

I had the same issue when trying to connect to a remote installation (not on localhost).

I had to set API_URI and STATIC_URL to URLs with the right IPs (or FQDN), not localhost like in the documentation.

You can check that the dashboard is connecting to the right instance by checking with your browser developper tools as acidlake said above.

**Comment by milanmaximo** [comment]
@aselam So did you solve this on production ? I am trying to deploy everything on production, but I am not sure what need to change in settings.py 
I have the same problem as @theanhvo on localhost and I've decide to do on production, but not sure how to start with it. I have install saleor, storefornt and dashboard, but when I want to test my web server crashed. 
Have you any solution ?
Thanks

**Comment by joelunmsm2003** [comment]
index.js?cf67:88 POST http://localhost:9000/graphql/ 405 (Method Not Allowed)

**Comment by aselam** [comment]
@milanmaximo I was just testing saleor on a virtual machine, nothing fancy.

In production as you said, even if you installed all components on the same server, your browser is loading storefront/dashboard and making queries by themselves from your... browser. So from saleor's perspective, it's not a connection from localhost (the server), it's a remote connection (from your computer).

When you said it crashed, what crashed exactly?

By default, when you start saleor to **test** it:
-  it's listening on localhost. If you want to test it in a VM, you need to specify that the development server should listen on VM's private IP (``)
- it accepts remote connections only from localhost: you need to specify which IPs are allowed to connect to it by setting `ALLOWED_HOSTS` in django `settings.py`

Also, you need to set `API_URI` and `STATIC_URL` before starting Saleor:
```
export API_URL='http://<Saleor IP>:<Saleor port>/graphql/'
export STATIC_URL='http://<Dashboard IP>:<Dashboard port>'
```
Then, after starting saleor with `manager.py runserver <IP>:<port>`, you should see the GraphQL Playground

Regarding **Dashboard**, in a **test** environment, you'll need to configure webpack to start the server on your private IP in `webpack.config.js`:
```
devServer: {
      compress: true,
      contentBase: path.join(__dirname, dashboardBuildPath),
      historyApiFallback: true,
      hot: true,
      host: '0.0.0.0',
      port: <Dashboard port>
    },
```
After `npm start` (beware, can take some time), the dasboard should be up and running on http://<Dashboard IP>:<Dashboard port>

Regarding **Storefront**, still in a **test** environment, settings are in `cypress.json` 
```
"baseurl": "http://<Storefront IP>:<Storefront port>",
"env": {
"API_URI": "http://<Saleor IP>:<Saleor port>"
}
```
After `npm start` (beware again, can take some time), Storefront should be up and running on http://<Storefront IP>:<Storefront port>

**Note**: I'm not sure if it's the right file to set, as it's the first time I play with Nodejs and Webpack... maybe somewhere else in Webpack's configuration?..

**Comment by gComet** [comment]
I have the same problem. As I see everything  is configured as need.

**Comment by OmniOracle** [comment]
I have the same problem too and as I am still very new to django and webdev as a whole I am confused as to how to change the EnvironmentPlugin - API_URI and APP_MOUNT_URI variables. Because these are my errors when I try to access the dashboard: 
These are my dev logs 
- EnvironmentPlugin - API_URI environment variable is undefined.
- EnvironmentPlugin - APP_MOUNT_URI environment variable is undefined.

**Comment by acidlake** [comment]
@OmniOracle hello there, you just need to open a terminal, and:
`API_URI="http://yoururl:8000/graphql/" APP_MOUNT_URI="/" npm start`
and that's it, also this Repo is for SALEOR server, you should comment about this on the repo for the DASBOARD

**Comment by OmniOracle** [comment]
Thank you mate, Now I am getting somewhere!

**Comment by appleyuchi** [comment]
> @milanmaximo I was just testing saleor on a virtual machine, nothing fancy.
> 
> In production as you said, even if you installed all components on the same server, your browser is loading storefront/dashboard and making queries by themselves from your... browser. So from saleor's perspective, it's not a connection from localhost (the server), it's a remote connection (from your computer).
> 
> When you said it crashed, what crashed exactly?
> 
> By default, when you start saleor to **test** it:
> 
> * it's listening on localhost. If you want to test it in a VM, you need to specify that the development server should listen on VM's private IP (``)
> * it accepts remote connections only from localhost: you need to specify which IPs are allowed to connect to it by setting `ALLOWED_HOSTS` in django `settings.py`
> 
> Also, you need to set `API_URI` and `STATIC_URL` before starting Saleor:
> 
> ```
> export API_URL='http://<Saleor IP>:<Saleor port>/graphql/'
> export STATIC_URL='http://<Dashboard IP>:<Dashboard port>'
> ```
> 
> Then, after starting saleor with `manager.py runserver <IP>:<port>`, you should see the GraphQL Playground
> 
> Regarding **Dashboard**, in a **test** environment, you'll need to configure webpack to start the server on your private IP in `webpack.config.js`:
> 
> ```
> devServer: {
>       compress: true,
>       contentBase: path.join(__dirname, dashboardBuildPath),
>       historyApiFallback: true,
>       hot: true,
>       host: '0.0.0.0',
>       port: <Dashboard port>
>     },
> ```
> 
> After `npm start` (beware, can take some time), the dasboard should be up and running on http://:
> 
> Regarding **Storefront**, still in a **test** environment, settings are in `cypress.json`
> 
> ```
> "baseurl": "http://<Storefront IP>:<Storefront port>",
> "env": {
> "API_URI": "http://<Saleor IP>:<Saleor port>"
> }
> ```
> 
> After `npm start` (beware again, can take some time), Storefront should be up and running on http://:
> 
> **Note**: I'm not sure if it's the right file to set, as it's the first time I play with Nodejs and Webpack... maybe somewhere else in Webpack's configuration?..

could you tell me how to solve https://github.com/mirumee/saleor-storefront/issues/646  when in production mode?

**Comment by AgentIvan** [comment]
There is an error in documentation: https://docs.saleor.io/docs/developer/installation/windows#running-the-dashboard

**Command Prompt** it is written: _set API_URI "http://localhost:8000/graphql/"_
**But should be:** _set "API_URI=http://localhost:8000/graphql/"_
**or:** _set API_URI=http://localhost:8000/graphql/_

**Comment by PeaceAntoHim** [comment]
Hi i have same probleam
