### ISSUE TITLE
Split settings on modules 

### ISSUE THREAD

**Issue by Arthur264** [mirumee/saleor#5114]
### What I'm trying to achieve
Split setting on modules 

### Describe a proposed solution
Split settings file on modules (AWS, LOGGING, APPS, etc)

**Comment by karolkielecki** [comment]
@Arthur264 Hello Arthur. Currently, we have a holiday season. We'll get back to you as soon as possible. Thanks for understanding.

**Comment by karolkielecki** [comment]
@Arthur264 Thank you for your feedback. We really appreciate it! Our dev team will discuss it.
