### ISSUE TITLE
Express checkout for logged in users

### ISSUE THREAD

**Issue by gsoec** [mirumee/saleor#5116]
### What I'm trying to achieve
- Allow authenticated user to create a temporary `Checkout` for "buy now"
![image](https://user-images.githubusercontent.com/26665579/71480159-a8519b00-27ac-11ea-8049-a5b90c1643d1.png)

### Describe a proposed solution
https://github.com/mirumee/saleor/blob/9502467c0e745eb8afdbfa373d634814d133e864/saleor/graphql/checkout/mutations.py#L290-L300
According to the code above, a logged-in user is limited to have single `Checkout` while anonymous user can have multiple `Checkout`.
- Remove the limitation
- Add a new field `is_temporary`(for example) to `Checkout`
- Add a new parameter `is_temporary` to `CheckoutCreate` mutation. If `is_temporary` is true, create a new `Checkout` with `is_temporary` set to true.
- `Query.me.checkout` returns the latest `Checkout` with `is_temporary` set to false.

**Comment by karolkielecki** [comment]
@gsoec Hey! Due to the holiday season, our support is limited. We'll get back to you as soon as possible. Thanks for understanding.

**Comment by karolkielecki** [comment]
@gsoec I've sent your suggestion to our Saleor team. We appreciate your support!
