### ISSUE TITLE
Date fields in dashboard won't trigger Datepicker on click or keyup

### ISSUE THREAD

**Issue by iansprice** [mirumee/saleor#512]
Hello! 

I forked Saleor exactly one week age and cannot get datepicker to work on datefields. Triggering `$('.datepicker').pickadate({})` throws a _.datepicker is not definted_ error.

Behavoir - 
Date fields cannot be focused on click.
Datepicker widget will only be shown if field is focused via tab key and then the enter key pressed; no other keyup works and cannot trigger keyup or click events on input element; using `.trigger('click')` throws `trigger is not defined` error. 

I feel like I'm missing something, but am baffled after using Materialize outside of Saleor many times in the past. Any tips?  

As one example, here's the **product.available_on** field rendered in the dashboard.
`<input type="text" id="id_available_on" class="datepicker picker__input" name="" value="" readonly="" tabindex="-1" aria-haspopup="true" aria-expanded="false" aria-readonly="false" aria-owns="id_available_on_root">`

Thanks!
Ian

**Comment by InYourDreamz** [comment]
I'm having this exact same problem as well

**Comment by patrys** [comment]
This seems to be working fine now. Please let us know if the problem returns.
