### ISSUE TITLE
Trailing slash

### ISSUE THREAD

**Issue by Zyles** [mirumee/saleor#5121]
### What I'm trying to achieve

`/product-name/ and /product-name`

is not the same thing.

https://searchfacts.com/url-trailing-slash/

This will cause SEO issues.

### Steps to reproduce the problem

Install Saleor.

### What I expected to happen

301 redirect to url with trailing slash.

**Comment by NyanKiyoshi** [comment]
Closing in favor of https://github.com/mirumee/saleor-storefront/issues/553. This is related to the PWA storefront, which is definitively a bug 👍
