### ISSUE TITLE
macOS installation steps

### ISSUE THREAD

**Issue by drozdowsky** [mirumee/saleor#5127]
### What I'm trying to achieve
set up Saleor on macOS

### Steps to reproduce the problem

libmagic: 
1. brew install cairo pango gdk-pixbuf libffi  # missing libmagic?
2. pip install -r requirements.txt
3. python manage.py migrate
4. fails because libmagic is not found.
```
  File "/Users/hubertdrozdowski/.virtualenvs/saleor/lib/python3.8/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

build-assets:
1. `npm run build-assets   # build-emails succeeds`
2. ERR!
```
npm ERR! missing script: build-assets
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     build-schema
npm ERR!     build-emails
```

python3:
by default `brew install python3` installs python-3.7, not 3.8 which is suggested in README

### What I expected to happen
No errors

**System information**
Operating system: macOS Catalina

**Comment by NyanKiyoshi** [comment]
Hi! You need to run `brew install libmagic` 👍
The documentation is missing this right now (https://github.com/mirumee/saleor-docs/issues/86).

**Comment by bakhmurov** [comment]
libmagic is installed via brew, but anyway I have the same poblem:
npm ERR! missing script: build-assets

**Comment by infinitecipher** [comment]
@bakhmurov this is the same as [#5105](https://github.com/mirumee/saleor/issues/5105#issuecomment-576046942)

**Comment by maarcingebala** [comment]
Here is the recent version of the installation guide: https://docs.getsaleor.com/docs/next/getting-started/installation-macos/

If you're using the `master` branch you need to switch to the pre-release version of the docs. Be default 2.9` docs are shown and they're matching the `2.9` release tag: https://github.com/mirumee/saleor/releases/tag/2.9.0
