### ISSUE TITLE
INFO django.utils.autoreload Watching for file changes with StatReloader [PID:7464:MainThread]

### ISSUE THREAD

**Issue by engrmkchow** [mirumee/saleor#5134]
INFO django.utils.autoreload Watching for file changes with StatReloader [PID:7464:MainThread]
INFO django.utils.autoreload Watching for file changes with StatReloader [PID:7464:MainThread]
Performing system checks...

D:\eComDev\GlacierSaleor\saleor\saleor\urls.py:29: UserWarning: The debug toolbar was not installed. Ignore the error.             settings.py should already have warned the user about it.
  warnings.warn(
System check identified no issues (0 silenced).
January 04, 2020 - 12:58:52
![Saleor_Problem](https://user-images.githubusercontent.com/40333792/71761432-a5fde800-2ef4-11ea-8f16-cd9f842aaf02.png)

Django version 2.2.9, using settings 'saleor.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
INFO django.server "GET / HTTP/1.1" 302 0 [PID:7464:Thread-2]
INFO django.server "GET / HTTP/1.1" 302 0 [PID:7464:Thread-2]
INFO django.server "GET / HTTP/1.1" 302 0 [PID:7464:Thread-2]
INFO django.server "GET /graphql/ HTTP/1.1" 200 1551 [PID:7464:Thread-2]
INFO django.server "GET /graphql/ HTTP/1.1" 200 1551 [PID:7464:Thread-2]
INFO django.server "GET /graphql/ HTTP/1.1" 200 1551 [PID:7464:Thread-2]
INFO django.server "POST /graphql/ HTTP/1.1" 200 849061 [PID:7464:Thread-3]
INFO django.server "POST /graphql/ HTTP/1.1" 200 849061 [PID:7464:Thread-3]
INFO django.server "POST /graphql/ HTTP/1.1" 200 849061 [PID:7464:Thread-3]
INFO django.server "POST /graphql/ HTTP/1.1" 200 849061 [PID:7464:Thread-3]
INFO django.server "POST /graphql/ HTTP/1.1" 200 849061 [PID:7464:Thread-3]
INFO django.server "POST /graphql/ HTTP/1.1" 200 849061 [PID:7464:Thread-3]

**Comment by karolkielecki** [comment]
@engrmkchow Hi there! Probably you haven't installed graphql library packages: graphiql_debug_toolbar and debug_toolbar. They are not required, but they help to investigate the time of queries.
