### ISSUE TITLE
How to run saleor in production mode ?

### ISSUE THREAD

**Issue by nasim31** [mirumee/saleor#5135]
Hi,
Thanks for this awesome ecommerce app.
I have followed this doc. https://docs.saleor.io/docs/getting-started/installation-linux/
Not able to find anywhere about running the app in production mode.
Need a kind help please.

Regards,
nasim

**Comment by milanmaximo** [comment]
@nasim31 You need cloud server. Setup on AWS you have already inside of settings.py , but I am not sure how to do it with saleor 2.0 on Linode. I am using saleor 1.0 on Linode.

**Comment by nasim31** [comment]
Hi milanmaximo
Thanks for the reply.
I have google cloud instance. I can successfully run the saleor in development mode.
i.e. python manage.py runserver (Development server)
Next I'm trying to start production server.(Nginx/Apache with wsgi)
Example: " https://www.guguweb.com/2019/11/13/django-nginx-deploy-your-django-project-on-a-production-server/ "
But wsgi.py not found in path in saleor. Confusing what to do.
Anybody can help me out with this deployment "wsgi.py" ??

**Comment by milanmaximo** [comment]
@nasim31 I am looking for solution as well. I have complete confi from saleor 1.0 in production, but saleor 2.0 is totally different and now I am looking how to solve this. If I got something I will send you.

**Comment by nasim31** [comment]
@milanmaximo 
Now I'm confuse with uwsgi and gunicorn.
Unable to decide which one is good to go and start the production rightaway.

**Comment by milanmaximo** [comment]
@nasim31 Gunicorn is finished a job for me for saleor 1.0
I can add here files if you need.

**Comment by karolkielecki** [comment]
Hi there! Thank you for your support @nasim31 @milanmaximo! Please keep in mind that Saleor is a standard Django deployment app. Please take a look at Django docs: https://docs.djangoproject.com/en/3.0/howto/deployment/

**Comment by nasim31** [comment]
Hi all,
Thanks for your cooperation and support.
I can able to run in production mode. I'm using stable 2.9.0 version.
New issues are.
Not able to activate payment gateways under plugins.

**Comment by appleyuchi** [comment]
how much parametors about IP do we need to change when we are in production mode?
Thanks

**Comment by Olcaey** [comment]
So basically I am able to work django and graphql work. Yet, react storefront and dashboard do not load. Example domain I am trying to set this up is https://pikselly.com.

My file structure:
- saleor/saleor: django files (settings.py, urls.py and all other files/folders
- saleor/saleor-storefront: pwa (pwa github clone --> src, congif, nginx, app.json, etc.)
- saleor/saleor-dashboard: dashboard react files (dashboard github clone --> src, build, locale, app.json, etc.)

I have started 3 screens in parallel
- screen dj: serves graphql (as you can see on https://pikselly.com/graphql)
- screen pwa: I built the files with: API_URI=http://localhost:8000/graphql/ npm run build
- screen dashboard: I built the files with: API_URI=http://localhost:8000/graphql/ APP_MOUNT_URI=/dashboard/ npm run build

On my /etc/nginx/sites-available/pikselly.com, I have following setup:
server {
    listen [::]:80;
    listen 80;
    server_name pikselly.com www.pikselly.com;
    # redirect http to https www
    return 301 https://pikselly.com$request_uri;
}

server {
    listen [::]:443 ssl http2;
    listen 443 ssl http2;
    server_name pikselly.com;
    ssl_certificate /etc/letsencrypt/live/pikselly.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pikselly.com/privkey.pem;

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }
    location /graphql/ {
        proxy_pass http://localhost:8000;
    }
    location / {
        root /home/olcaey/saleor/saleor-storefront/src/;
    }
    location /dashboard/ {
        root /home/olcaey/saleor/saleor-dashboard/src/;
    }
}

server {
    server_name <IP_Adress>;
    return 301 https://pikselly.com$request_uri;
}

On https://pikselly.com/, favicon and some html is visible. Yet, I am still unable to make frontend work. Could you please recommend me how to make saleor work in production?

*I am not sufficient with react yet, therefore could not make this work.

**Comment by tomaszszymanski129** [comment]
@Olcaey you are poining both storefront and dashbaord to `src` dir that contains source only - nothing you should serve, when you run `npm run build` that compiles whatever is in `src` to `dist` directory and it contains compiled versions with `index.html` and everything

So in your case,
`location /` should point to
`root /home/olcaey/saleor/saleor-storefront/dist/;`
`location /dashboard/` should point to
`root /home/olcaey/saleor/saleor-dashboard/dist/;`

**Comment by milanmaximo** [comment]
> So basically I am able to work django and graphql work. Yet, react storefront and dashboard do not load. Example domain I am trying to set this up is https://pikselly.com.
> 
> My file structure:
> 
> * saleor/saleor: django files (settings.py, urls.py and all other files/folders
> * saleor/saleor-storefront: pwa (pwa github clone --> src, congif, nginx, app.json, etc.)
> * saleor/saleor-dashboard: dashboard react files (dashboard github clone --> src, build, locale, app.json, etc.)
> 
> I have started 3 screens in parallel
> 
> * screen dj: serves graphql (as you can see on https://pikselly.com/graphql)
> * screen pwa: I built the files with: API_URI=http://localhost:8000/graphql/ npm run build
> * screen dashboard: I built the files with: API_URI=http://localhost:8000/graphql/ APP_MOUNT_URI=/dashboard/ npm run build
> 
> On my /etc/nginx/sites-available/pikselly.com, I have following setup:
> 
> ```
> server {
>     listen [::]:80;
>     listen 80;
>     server_name pikselly.com www.pikselly.com;
>     # redirect http to https www
>     return 301 https://pikselly.com$request_uri;
> }
> 
> server {
>     listen [::]:443 ssl http2;
>     listen 443 ssl http2;
>     server_name pikselly.com;
>     ssl_certificate /etc/letsencrypt/live/pikselly.com/fullchain.pem;
>     ssl_certificate_key /etc/letsencrypt/live/pikselly.com/privkey.pem;
> 
>     location = /favicon.ico {
>         access_log off;
>         log_not_found off;
>     }
>     location /graphql/ {
>         proxy_pass http://localhost:8000;
>     }
>     location / {
>         root /home/olcaey/saleor/saleor-storefront/src/;
>     }
>     location /dashboard/ {
>         root /home/olcaey/saleor/saleor-dashboard/src/;
>     }
> }
> 
> server {
>     server_name <IP_Adress>;
>     return 301 https://pikselly.com$request_uri;
> }
> ```
> 
> On https://pikselly.com/, favicon and some html is visible. Yet, I am still unable to make frontend work. Could you please recommend me how to make saleor work in production?
> 
> *I am not sufficient with react yet, therefore could not make this work.

I am almost there, but still got some errors on production. Also I cant get login to /dashboard
'''etwork error: Unexpected token < in JSON at position 0'''

**Comment by milanmaximo** [comment]
@Olcaey 
I am almost there, but still got some errors on production. Also I cant get login to /dashboard
"Network error: Unexpected token < in JSON at position 0"

**Comment by milanmaximo** [comment]
> I am almost there, but still got some errors on production. Also I cant get login to /dashboard
'''etwork error: Unexpected token < in JSON at position 0'''

**Comment by Pyrross** [comment]
I am not trying to take over this thread, but what would an equivalent structure for `/etc/apache2/sites-available/` be? 
I have a working GraphQL server running in Apache, but I can't figure out how to do it with the Node.js servers.
My .conf :
`<VirtualHost *:80>
ServerAdmin admin@thunderusb.dk
DocumentRoot /home/ubuntu/saleor
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
Alias /static /home/ubuntu/saleor/saleor/static
<Directory /home/ubuntu/saleor/saleor/static>
Require all granted
</Directory>
<Directory /home/ubuntu/saleor/>
Require all granted
</Directory>
WSGIDaemonProcess saleor python-path=/home/ubuntu/saleor
WSGIProcessGroup saleor
WSGIScriptAlias / /home/ubuntu/saleor/saleor/wsgi/__init__.py
</VirtualHost>
`

**Comment by milanmaximo** [comment]
@Pyrross No problem about hijacking, but for the others it would be better to open new thread related to Apache and saleor. 
Here is defenetely lack of information reagrind Nginx and apache. 
I would like to help you, but still I got a problem with Nginx and setup. 

As I worked before with apache I can see that your path is not good. But as I said, I am not sure. 

Check this from @tomaszszymanski129 

So in your case,
`location / `should point to
`root /home/olcaey/saleor/saleor-storefront/dist/;`
location /dashboard/ should point to
`root /home/olcaey/saleor/saleor-dashboard/build/dashboard/;`

**Comment by ayavorskiy** [comment]
@milanmaximo the reason why you get error 'Unexpected token <' is that your index.html (that is located at saleor-dashboard/build/dashboard/index.html) is pointing to missing file on your server. To check this you can see Console and Network tab in Chrome and confirm that.
To build it properly with correct urls execute 
STATIC_URL="/dashboard/" API_URI="http://domain.com:8000/graphql/" APP_MOUNT_URI="/dashboard/" npm run build
from 'saleor-dashboard' directory

**Comment by milanmaximo** [comment]
@ayavorskiy thank you so much for an answer. I am sorry for delay. This setup is on docker file right ?
I am trying to do with nginx, simply as any other django apps, but still I can't figure out how to create blocks. I have try many options, but only I got front page with that error... 
If I finished or when I finished this I will add here complete nginx blocks.
Thanks one more time.

**Comment by ayavorskiy** [comment]
@milanmaximo this is not related to Docker. 
To configure nginx conf. file 
```
server {
       listen       80;
	server_name shop.com;


	location /graphql/ {
	proxy_pass http://localhost:8000;
	}

	location / {
	root /home/ubuntu/saleor-storefront/dist/;
        index  index.html;
        try_files $uri $uri/ /index.html;
	}

	location /dashboard/ {
	path /home/ubuntu/saleor-dashboard/build/;
	index  index.html;
	}
}
```

**Comment by milanmaximo** [comment]
@appleyuchi thank you! At least I can see dashboard 404 page. But obviously I am doing something wrong. 
Here is what I did.
At saleor/saleor-dashboard 
`$ export STATIC_URL="/dashboard/"`
`$ API_URI="http://mydomain.com:8000/graphql/" `
`$ APP_MOUNT_URI="/dashboard/" `
`$ npm run build`

At saleor/saleor-storefront
`$ npm run build`

Nginx
```
server {
        listen 80;
        listen [::]:80;
        server_name barkanatrebisnjici.com www.barkanatrebisnjici.com;
        index index.html index.htm;

        location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

   access_log /var/log/nginx/saleor_access.log;
   error_log /var/log/nginx/saleor_error.log;

        location /graphql/ {
        proxy_pass http://localhost:8000;
        }

        location / {
        root /var/www/saleor/saleor-storefront/dist/;
        index index.html;
        try_files $uri $uri/ /index.html;
        }

        location /dashboard/ {
        root /var/www/saleor/saleor-dashboard/build/dashboard/;
        index index.html;
        }
}

```
After all I got this errors.

storefront
`Network error: Failed to fetch`
![2](https://user-images.githubusercontent.com/28672914/80231212-5aae4780-8653-11ea-8d6a-7294bb8cfb34.png)


dashboard
`Network error: NetworkError when attempting to fetch resource.`
But I can see 404 page 
![1](https://user-images.githubusercontent.com/28672914/80231270-6ef24480-8653-11ea-8913-aeb94522c9ce.png)

**Comment by ayavorskiy** [comment]
@milanmaximo I provided working config, with 'path' command
```
	location /dashboard/ {
	path /home/ubuntu/saleor-dashboard/build/;
	index  index.html;
	}
```
which forms /home/ubuntu/saleor-dashboard/build/dashboard/

You have 
```
        location /dashboard/ {
        root /var/www/saleor/saleor-dashboard/build/dashboard/;
        index index.html;
        }
```
which will result in /var/www/saleor/saleor-dashboard/build/dashboard/dashboard/ and forms 404 status code, and in case if you will check Developers Tools in Chrome you could verify it that there is probably no such directory /var/www/saleor/saleor-dashboard/build/dashboard/dashboard/ on your server. 

More on this
https://stackoverflow.com/questions/10631933/nginx-static-file-serving-confusion-with-root-alias

**Comment by Reiasa** [comment]
@ayavorskiy Hi, whenever I try using the config you've used, I get the error saying `nginx: [emerg] unknown directive "path"` even though I am following exactly the config you've provided in my server block. Is there something am missing?

**Comment by ayavorskiy** [comment]
@Reiasa copy here your config entirely.

**Comment by Reiasa** [comment]
```
server {

        listen [::]:443 http2 ssl ipv6only=on;
        listen 443 http2 ssl;

        server_name www.domain.com domain.com;

        root /var/www/store/html;
        index index.html;

        
        ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; 
        ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

	location = /favicon.ico {
        access_log off;
        log_not_found off;
    	}

	location /dev {
        root /home/manager/saleor-storefront/dist/;
        index  index.html;
        try_files $uri $uri/ /index.html;
	}

	location /dashboard/ {
	path /home/manager/saleor-dashboard/build/;
	index  index.html;
	}
	    #proxy_set_header Host $host;
	    #proxy_set_header X-Real-IP $remote_addr;
	    #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    #proxy_set_header X-Forwarded-Proto $scheme;
}



server {
    if ($host = www.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;

        server_name www.domain.com domain.com;
    return 404; # managed by Certbot

}


```

**Comment by Reiasa** [comment]
@ayavorskiy any idea why its generating that error? When I switch `path` to `root` and configure the directories respectively on that, I only get a blank page. Thanks in advance.

**Comment by bboyadao** [comment]
So how nginx serving media files ? any example. ?
`location /static/ {
      alias /app/saleor/static/;
  }
  location /media/ {
      alias /app/saleor/media/;
  }`
i did try this but the image not show up!

**Comment by ayeedshaikh** [comment]
Hello I can help you install saleor in production mode on any linux based server with command line support. You can contact me on ayeed@hexesys.com.

**Comment by neerajgupta2407** [comment]
I am stuck with apache config. Below is my Virtualhost config and i am getting error.
`[Wed Jun 17 18:02:37.988738 2020] [core:notice] [pid 20293:tid 140668082637760] AH00051: child pid 20364 exit signal Aborted (6), possible coredump in /etc/apache2
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
`

### VirtualHost.:
`<VirtualHost *:80>
    ServerName api.pricemenu.in
    Alias /static  /home/ubuntu/codes/backend/saleor/static/
    <Directory /home/ubuntu/codes/backend/saleor/static/>
        Require all granted
    </Directory>

        WSGIDaemonProcess saleor python-path=/home/ubuntu/codes/backend/saleor python-home=/home/ubuntu/codes/backend/venv
        WSGIScriptAlias / /home/ubuntu/codes/backend/saleor/saleor/wsgi/__init__.py
        WSGIProcessGroup saleor
        WSGIPassAuthorization On

</VirtualHost>
`

**Comment by ayeedshaikh** [comment]
please share the apache2.conf
