### ISSUE TITLE
Create Product

### ISSUE THREAD

**Issue by joelunmsm2003** [mirumee/saleor#5136]
When I install pip install -r requirements.txt  not install en red:

Collecting importlib-metadata>=0.18; python_version < "3.8" (from kombu==4.6.7->-r requirements.txt (line 210))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    importlib-metadata>=0.18; python_version < "3.8" from https://files.pythonhosted.org/packages/e9/71/1a1e0ed0981bb6a67bce55a210f168126b7ebd2065958673797ea66489ca/importlib_metadata-1.3.0-py2.py3-none-any.whl#sha256=d95141fbfa7ef2ec65cfd945e2af7e5a6ddbd7c8d9a25e66ff3be8e3daf9f60f (from kombu==4.6.7->-r requirements.txt (line 210))

**Comment by Varghese-Thomas** [comment]
same case with a different error, python 3.6.8, ubuntu 18.10

In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    importlib-metadata>=0.18; python_version < "3.8" from https://files.pythonhosted.org/packages/e9/71/1a1e0ed0981bb6a67bce55a210f168126b7ebd2065958673797ea66489ca/importlib_metadata-1.3.0-py2.py3-none-any.whl#sha256=d95141fbfa7ef2ec65cfd945e2af7e5a6ddbd7c8d9a25e66ff3be8e3daf9f60f (from kombu==4.6.7->-r requirements.txt (line 210))

**Comment by joelunmsm2003** [comment]
Hello @Varghese-Thomas , I solved it by installing a virtual environment pyenv 3.80 and it worked my best regards

**Comment by karolkielecki** [comment]
@joelunmsm2003 Hi Joel! First, run this command to create requirements file without hashes: poetry export --without-hashes -f requirements.txt -o requirements.txt. 

And then run again pip-install command.

**Comment by karolkielecki** [comment]
@joelunmsm2003 I'm happy to hear that you found a solution. If you have any more questions, let us know. 

Best
