### ISSUE TITLE
Issues on Linode server and npm 

### ISSUE THREAD

**Issue by milanmaximo** [mirumee/saleor#5137]
I've installed saleor, saleor-storefront and saleor-dashboard.
In storefront and dashboard I was doing npm install and everythings goes fine, but when I try to do npm run build complete server is stuck.
Then I have trying with docker and I got this.

```docker build -t saleor-dashboard .```

Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! saleor-dashboard@2.0.0 build: `webpack -p`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the saleor-dashboard@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-06T04_04_31_891Z-debug.log
The command '/bin/sh -c STATIC_URL=${STATIC_URL} API_URI=${API_URI} APP_MOUNT_URI=${APP_MOUNT_URI} npm run build' returned a non-zero code: 137

Does anyone know what kind of error is this one. In log file is empty.
I am just looking for options how to deploy saleor on production

**Comment by mouchh** [comment]
Hey milanmaximo, if not mistaken I recall seeing such an issue when I was trying to build npm on a machine with only 1Gb of RAM.

The issue disappeared by itself when I upgraded my VM to 2 Gb of RAM.

My 2 cents, hope it can help!

**Comment by milanmaximo** [comment]
@mouchh 
Thank you so much! Yes, that was a problem.. Since I have more sites on the server I just upgrade on 4 GB of RAM.
It doesn't woirk on 2 Gb of RAM.

By the way, how did you solve Nginx blocks ?
I am not sure how to start in production ,even I got version saleor 1.0, but I have a problem with saleor 2.0 . Just don't know how to solve issues with Nginx blocks.
Thank you so much for this and I am sorry for bit late with answer.

**Comment by mouchh** [comment]
I decided to run Saleor for production without Docker (and use Docker for dev only).
So basically, I have supervisor daemons that are running uwsgi server and celery workers.
I configured Nginx to serve static files and to pass any other queries to my uwsgi server.

Something like that; it is a very comon integration of Nginx and uwsgi

```
server {
  listen 80;
  listen [::]:80;
  server_name whatever.com;
  
  access_log /var/log/nginx/saleor_access.log;
  error_log /var/log/nginx/saleor_error.log;

  # Reverse proxy the uwsgi Django server                     
  location / {
    include uwsgi_params;
    uwsgi_pass unix:///tmp/uwsgi.sock;
  }

  # Configure NGINX to deliver static content from the specified folder
  location /static {
      alias /var/www/saleor/static;
  }
  location /media {
      alias /var/www/saleor/media;
  }
}
```

It seems like you want to use Docker for production also so you might not want to implement Saleor this way; I just shared with you an example implementation.
At first try, when I used Docker for production also, I used the default docker-compose from the repository and simply exposed the uwsgi container. 
That is another implementation option. 
Both have pros and cons, it really depends on your needs/skills.
