### ISSUE TITLE
Managing products require more permissions than "Manage products"

### ISSUE THREAD

**Issue by simonbru** [mirumee/saleor#5138]
A staff member with only the "Manage products" permissions gets an unexpected error when creating a new product from the saleor dashboard. A `PermissionDenied` exception related to `quantityAllocated` is raised on submit. However, the product seems successfully created behind the scene.

Navigating to a product also raises errors related to `quantityAllocated`.

## Workaround
The issue does not occurs when the staff member also has the "Manage orders" permission.

## Versions
Saleor: master (docker setup)
Saleor-dashboard: master

## Annex
Request/response data: https://gist.github.com/simonbru/2cde1e0cf080cdcdd961bd61114cf843

**Comment by karolkielecki** [comment]
@simonbru Hey! We are aware of this issue. Our holiday season has just finished, so we have a lot of work to do for now. Once we have more free time, we'll try to fix it. Thanks for your patience and understanding.

**Comment by maarcingebala** [comment]
`quantityAllocated` and two other fields in the `Product` type require both permissions. But to be honest I think this could be changed to require only `MANAGE_PRODUCTS` in those cases.

**Comment by simonbru** [comment]
Great, thank you for the fix!
