### ISSUE TITLE
Paiement gateway documentation - need clarification

### ISSUE THREAD

**Issue by mouchh** [mirumee/saleor#5139]
Hello,

I'm currently implementing paiement gateway on my new shop. I read in your doc something I don't understand and would like a clarification just to make sure I will pick the paiement option that fit for my need.

Here is the detail about BrainTree (see https://docs.getsaleor.com/docs/integrations/payment-gateways/#braintree)

_This backend does not support fraud detection._

How can it be the fraud detection is not supported where my understanding of paiement services is that they handle everything on their side - meaning doing their own checks once the paiement is posted. Where Saleor capabilities could "limit" this process? Can you help me clarify this?

Also, I'm not seeing any note like that for Stripe. Should I conclude Stripe's fraud detection (Radar if not mistaken) is working properly - in opposite to BrainTree so?

Thank you for these details,

**Comment by karolkielecki** [comment]
@mouchh Hi there. BrainTree supports fraud detection by itself. I think fraud detection is a standard feature for payment gateways these days. However, fraud detection is not implemented in Saleor. If you have any more questions or feedback, let us know! 

Best
