### ISSUE TITLE
Product images dropzone doesn't work if there are no images

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#514]
When I'm trying to add some images to a product that currently doesn't have one, the dropzone doesn't work, because the image is just opened in a new tab, instead of getting uploaded. When there is already any image in the list, the dropzone works correctly.

**Comment by mikeres0** [comment]
+1, any update on this? Looking to start getting products imported into the store and this is a major blocker.

**Comment by mikeres0** [comment]
Or are you aware of a fix that can be implemented? Willing to create a PR. #515
