### ISSUE TITLE
npm run bild-assets

### ISSUE THREAD

**Issue by gComet** [mirumee/saleor#5141]
Hi there, I'm trying to install saleor on my Ubuntu local machine. I'm experiencing errors with npm with command npm run build-assets. 
It's giving me like npm run build-assets is missing script.
Why?

**Comment by milanmaximo** [comment]
@gComet 
First do npm install , after that npm run build , not npm run build-assets and wait.
It will be done after couple of minutes.

**Comment by afsangujarati93** [comment]
> @gComet
> First do npm install , after that npm run build , not npm run build-assets and wait.
> It will be done after couple of minutes.

Still getting the same error. 

```
$ npm run build
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/afsan.gujarati/.npm/_logs/2020-01-12T19_35_38_400Z-debug.log
```

**Comment by maarcingebala** [comment]
By default, the docs refer to the 2.9.0 version of Saleor where this command is still available. Docs for the pre-release version (`master`) can be found here: https://docs.getsaleor.com/docs/next/index.html.
