### ISSUE TITLE
Drop gettext occurrences from Python code

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#5143]
Since all static views and templates were dropped from Saleor, we don't need to use `gettext` anymore in the Python code. It's not useful in the API as well, as it's the client app's responsibility to provide translations. We should then remove all occurrences of `gettext` or similar functions (`pgettext` etc.).

We should though remember that we still have email templates in the backend and we should keep using translations there.

**Comment by patrys** [comment]
Should we also look into disabling Django's I18N support?

**Comment by maarcingebala** [comment]
We still use translations in email templates so I guess we can't do that yet.

**Comment by joacodf** [comment]
Question, if the responsibility for translating is on the frontend, why are there models for translating data?

**Comment by patrys** [comment]
@joacodf Frontend is perfectly capable of controlling how a button is labeled or what error message to show for a failed login, but it can't dynamically translate things like product information.
