### ISSUE TITLE
Services as product 

### ISSUE THREAD

**Issue by Cerix** [mirumee/saleor#5146]
Hello guys, my idea is to sell a service as a product, for example the customer sends a file when he places an order, this file will be processed manually by the staff and subsequently to the customer will be sent either a physical product or a digital product.

### Business examples:
- Custom Printed T-Shirts shop
- 3D print shop
- Translating services

### Additional features
Implement a custom function over the files (an automation), like for example a checksum control or file extension check, auto resize ecc..
calculation of additional costs based on size or others parameters 

is there a way to implement these features in Saleor?
can you kindly link me the suitable documentation to eventually try to develop these functions?

Thanks

**Comment by maarcingebala** [comment]
We do have basic support for digital products in the API, e.g. you can create a product type with `isDigital` flag set and later provide `digitalContent` objects that can hold e.g. files. It's still not supported in the UI yet.

But to sell e.g. a service which doesn't involve downloading any files, you can use products without shipping for that. Again, you need to create a product type and configure it as not requiring any shipping. This can be done in our dashboard:

![image](https://user-images.githubusercontent.com/5421321/72069649-edff7f00-32e7-11ea-8807-88257d8f2e5f.png)

Products that don't require shipping can be sold without providing shipping method and shipping address.

**Comment by Cerix** [comment]
thanks for the reply, currently there is no way to attach a file during checkout?
e.g
![ui-expample](https://user-images.githubusercontent.com/9200396/72150661-54e36d80-33a6-11ea-876b-c2bfb704cf16.jpg)

reading the API documentation, it would be nice to be able to pass a customFile object while creating a checkout object

```
mutation{
  checkoutCreate(input:{
    lines: { 
      quantity: 5
      variantId: "UHJvZHVjdFZhcmlhbnQ6NQ=="
      customFiles: [
          {
             id: "XXXX"
             url: "fileurls"
          },
         {
             id: "XX22"
             url: "fileurls2"
          }
      ]
    }
    email: "test@test.com"
    ...
      .....
```

**Comment by maarcingebala** [comment]
@Cerix No, there is no such feature in Saleor now. I can imagine that we could use for that our attributes system - each attribute has an input type and if we had "file input" type, then maybe that would be possible.
