### ISSUE TITLE
ProductVariant name based on sorted attributes

### ISSUE THREAD

**Issue by hetsch** [mirumee/saleor#5154]
Hi,

I'm not quite sure if I found a bug while working with the latest master branch of `saleor-storefront` and `saleor` backend.

I always got a blank page if i tried to browse a product page in the storefront app (e.g. `http://localhost:3000/product/foo/1/`). I nailed it down to the `getVariant` function and line `158` in https://github.com/mirumee/saleor-storefront/blob/master/src/components/ProductDescription/index.tsx#L158.
 This issue happens, if the sorting order of the naming parts (attributes) of my `variant.name` (e.g. `foo / bar`) are swapped (instead of `bar / foo` ), and therefore, no variant can be found.

Diving deeper, it might be an issue with the `generate_name_for_variant` method in https://github.com/mirumee/saleor/blob/master/saleor/product/utils/attributes.py#L20. In this method, there is a comment `FIXME: this should be sorted`, that might indicate the source of my problem.

I played around and the following fix worked for me (right now ...):

```diff
diff --git a/saleor/product/utils/attributes.py b/saleor/product/utils/attributes.py
index 9a8815307..d51279ccc 100644
--- a/saleor/product/utils/attributes.py
+++ b/saleor/product/utils/attributes.py
@@ -15,8 +15,7 @@ AttributeAssignmentType = Union[AssignedProductAttribute, AssignedVariantAttribu
 def generate_name_for_variant(variant: ProductVariant) -> str:
     """Generate ProductVariant's name based on its attributes."""
     attributes_display = []
-
-    for attribute_rel in variant.attributes.all():  # type: AssignedVariantAttribute
+    for attribute_rel in variant.attributes.order_by("assignment__sort_order").all():  # type: AssignedVariantAttribute
         values_qs = attribute_rel.values.all()  # FIXME: this should be sorted
         translated_values = [str(value.translated) for value in values_qs]
         attributes_display.append(", ".join(translated_values))

```

I'm just evaluating saleor and playing around, so I don't know the inner workigns and what other side effects this change might have.

**Comment by karolkielecki** [comment]
@hetsch Hi there! Could you please tell me which version of Saleor are you using? 2.9 or master one?

**Comment by hetsch** [comment]
@karolkielecki Hi Karol, latest master. Thx!

**Comment by karolkielecki** [comment]
Please install 2.9 - it's our latest stable version. The master one still needs improvements etc.

**Comment by hetsch** [comment]
I'll try master then. Maybe this may be helpful for future work ... Is `v2.9` compatible with `saleor-dashboard` v2.0 and `saleor-storefront` v0.7`?

**Comment by karolkielecki** [comment]
I recommend you using Saleor 2.9.0 (the latest stable version), not the master one. It should be compatible. If you have more questions, please don't hesitate to ask.
