### ISSUE TITLE
Checkout last change is not modified when it saved. Need to change 'auto_now_add' to 'auto_now'

### ISSUE THREAD

**Issue by juno05** [mirumee/saleor#5159]
### What I'm trying to achieve
Keep update the last change of CheckOut but it is set with 'auto_now_add'. 
So, it couldn't be changed after created.
Is it intended on purpose? Or bug?

### Steps to reproduce the problem
1. Create checkout with any item.
2. Add any item on checkout
3. Check data on database. There is no changes on 'last_change' field

### What I expected to happen
Whenever any information on CheckOut is changed, update 'last_change'

### Screenshots

**System information**
Operating system:

**Comment by maarcingebala** [comment]
Hey, thanks for reporting - it's a bug. The field definition should be: `last_change = models.DateTimeField(auto_now=True)`. Willing to open a PR @juno05? 😉
