### ISSUE TITLE
Why unit_price_net is not PriceField in OrderedItem?

### ISSUE THREAD

**Issue by pcompassion** [mirumee/saleor#516]
it's a question.

PriceField has `currency` concept attached to it whereas `unit_price_net` and `unit_price_gross` are plain DecimalField.

**Comment by patrys** [comment]
I'm not sure it was a conscious decision. There's a `get_price_per_item()` method that should return a proper Price object under all circumstances. I'd consider `unit_price_*` to be implementation detail as depending on them could lead to awkward errors such as using `self.unit_price_gross.net` which would return an incorrect value.

If/when we split `prices.Price` into `prices.Price` and `prices.Amount` it will make sense to turn these into `AmountField`s.

**Comment by pcompassion** [comment]
Since `currency` is not stored in the DB, if currency changes when order is placed, and when `get_price_per_item()` is called, it could lead to a different monetary value. 

I haven't checked if it could really happen with the current code.
