### ISSUE TITLE
Carry foreward arbitrary fields from checkout to order

### ISSUE THREAD

**Issue by dankolbman** [mirumee/saleor#5162]
### What I'm trying to achieve
I'd like to include additional fields during checkout for the customer to fill out, such as agreeing to some terms, which will carry forward to the  order so it may be validated or acted on by an administrator.

Currently, we can store metadata fields on the checkout to keep track of these additional values, but once the checkout is completed, the fields are lost.

### Describe a proposed solution
There are three different solutions I can think of right now.

#### Copy checkout metadata to order
Perhaps the easiest solution is to copy the metadata, public and private, from the checkout to the new order when an order is completed. This will allow our current approach of storing additional values on checkout metadata while the user fills out the form.

#### Allow plugins to modify order data
The `manager.preprocess_order_creation()` function could be allowed to modify the `order_data`during the `prepare_order_data()` call which would let a plugin modify an order before it's created using information from the checkout.

#### Manage everything on the frontend
The possible noop solution here could be to update the order information post-creation on the front end. I'm not sure this is possible due to permissions, though.
It still wouldn't be ideal for our use as we would want to still add some backend logic to prevent creating orders that violate some conditions.

**Comment by maarcingebala** [comment]
I think in your particular case, the fastest solution would be to build a plugin for that, so solution 2). But I think we should implement solution 1) anyway - if there is any additional metadata stored in checkout instance, it's likely that you may want to access it later once it becomes an order.

**Comment by dankolbman** [comment]
The plugin seems that it should be the easiest way to get this functionality, but if I'm reading it correctly, the `order_created()` hook gets called after the order has been created and the checkout has been deleted, making it difficult to do without managing some temporary storage for the plugin.
The `preprocess_order_creation()` could be allowed to modify and return the `order_data` before the new order is constructed, but this may be unsafe?

I PR'd what I'm using to copy the metadata, if you're ok with having what may be an inconsistency with how metadata is handled. Otherwise, it may be worth looking more into accommodating the plugin approach which may have more benefits, too.

**Comment by maarcingebala** [comment]
Fixed in #5165
