### ISSUE TITLE
Migrate failed while running project for the first time

### ISSUE THREAD

**Issue by UmarFarooq-Ch** [mirumee/saleor#5164]
I was trying to run saleor on my machine for the first time

Steps to reproduce the problem
create a new virtualenv and then install requirements.txt on that env
when you try to run `python manage.py migrate` the following error occurs.

FIX: add dataclasses in requirments.txt 

![image](https://user-images.githubusercontent.com/16037202/72347076-242e6b80-36f9-11ea-9af7-e34a5f7292ae.png)

Operating system:
Ubuntu 18

**Comment by karolkielecki** [comment]
@UmarFarooq-Ch Hey! Did you create a database instance and connect it to Saleor?

**Comment by UmarFarooq-Ch** [comment]
Yup

**Comment by karolkielecki** [comment]
@UmarFarooq-Ch Can you please tell us all the steps you have performed? It will help us to reproduce the issue because we haven't found any problem so far.

**Comment by UmarFarooq-Ch** [comment]
create a new virtualenv and then install requirements.txt on that env
when you try to run `python manage.py migrate` the error will occurred

**Comment by infinitecipher** [comment]
@UmarFarooq-Ch What version of python are you using? Try to use 3.8 instead.

**Comment by maarcingebala** [comment]
@UmarFarooq-Ch It seems you're using Python 3.6. Please upgrade to 3.8. If you're using the `master` branch of Saleor, refer to the pre-release version of our docs: https://docs.getsaleor.com/docs/next/getting-started/intro/
