### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by mengheangrat** [mirumee/saleor#5167]
Hello everyone here, 

Which branch is a stable version that we can use for production?
Sorry guys I'm so new to GraphQL and Django. 
Thanks.

**Comment by patrys** [comment]
You can find a list of stable releases in the [release section](https://github.com/mirumee/saleor/releases).

**Comment by mengheangrat** [comment]
Thank @patrys I have tried on this branch but I got old dashboard and storefront.
