### ISSUE TITLE
npm run build-assets missing script

### ISSUE THREAD

**Issue by sajalmia381** [mirumee/saleor#5182]
### Steps to reproduce the problem
accordion to documentation, command npm run but package.json has not enough dependency package.
### Main problem:   
$ npm run build-asstes, there is missing script: build-assets error.

**System information**
Operating system:
Ubuntu

**Comment by maarcingebala** [comment]
The default docs page refers to [Saleor 2.9](https://github.com/mirumee/saleor/releases/tag/2.9.0) where this command was used. If you're using Saleor from `master` refer to the [pre-release docs](https://docs.getsaleor.com/docs/next/getting-started/installation-macos/).

https://docs.getsaleor.com/versions/
