### ISSUE TITLE
POST GraphQL API redirects to playground

### ISSUE THREAD

**Issue by dsbrgg** [mirumee/saleor#5184]
### What I'm trying to achieve

Call the GraphQL API outside the playground environment.

### Steps to reproduce the problem

1.  Install & configure dependencies according to the [docker documentation](https://docs.getsaleor.com/docs/next/getting-started/docker/)
2. Call `tokenCreate` from the playground, will validate the user and return a token normally.
3. Call `tokenCreate` from another client (eg. Postman, Insomnia) and the playground HTML returns. 

### What I expected to happen

I expect that POST calls from outside the GraphQL playground will effectively execute the mutation/query without redirecting to the playground and not executing anything.

### Screenshots

- Call from Postman, django redirects
![Django redirects](https://i.ibb.co/VVWn5BQ/Screenshot-2020-01-21-at-17-15-29.png)

- Call from playground
*: The log "-----" is mine, while trying to debug [this](https://github.com/mirumee/saleor/blob/9ac4ee918c4879cf257b1bf81724cebf98e33e5c/saleor/graphql/views.py#L72), it's possible to see that in the previous case it's not even being logged
![Call from playground](https://i.ibb.co/P19cpn9/Screenshot-2020-01-21-at-17-40-18.png)

**System information**

Operating system: MacOS 10.14.6

**Comment by NyanKiyoshi** [comment]
Hi! You need to put the trailing slash. It is `/graphql/`, `/graphql` does not exist but is automatically redirected by django to help browser users.

**Comment by dsbrgg** [comment]
Thanks @NyanKiyoshi, that worked!
