### ISSUE TITLE
Can't access site because of GraphQL redirects

### ISSUE THREAD

**Issue by marciusl** [mirumee/saleor#5191]
### What I'm trying to achieve
Access website

### Steps to reproduce the problem
1. Installed and migrated everything
2. After I ran a site it always redirects to graphql, no matter where I would go

### What I expected to happen
To load site?

### Screenshots

**System information**
Operating system:
Windows 10 64 BIT

**Comment by patrys** [comment]
Saleor core does not have any other views, which is why DEBUG mode redirects you to `/graphql/`. Dashboard and storefront are separate projects.

**Comment by adithyabsk** [comment]
This might be helpful to mention in the docs as this is a change from the prior stable versions of saleor (ie 2.9.1)

**Comment by yanxun827** [comment]
> Saleor core does not have any other views
This is definitely not obvious and intuitive at all. The docs do not detail nor explain this behaviour, which confuses newcomers (me) that expect the guide to help me setup a local server to be able to test the site out.
The state of the introductory docs right now presents an unnecessary pain point for newcomers and could hinder adoption.

Related issue: #5237

**Comment by abiramnair** [comment]
Completely agree with yanxun827. Great piece of code. Documentation is a shame.

**Comment by maarcingebala** [comment]
Thank you for your feedback. We're working on improvements in the docs and planning to release it this week.

**Comment by abiramnair** [comment]
Thank you kindly for the prompt reply. Saleor is really great. I would like
to know if there is documentation around customising the react frontend.

Cheers.

**Comment by maarcingebala** [comment]
We don't have docs for the storefront yet. The plan is to finish the SDK (which allows you to interact with the API through JS functions and objects). Once it's done and we fully migrate to using it, it will be also much easier to customize the visual components. Then we'll also release docs for the SDK and basic theming of the app.
