### ISSUE TITLE
Docker installation docs can be improved

### ISSUE THREAD

**Issue by AlmogCohen** [mirumee/saleor#5195]
### What I'm trying to achieve

Point out that the Docker installation docs can be imporved

### Steps to reproduce the problem
1. Go to https://docs.getsaleor.com/docs/getting-started/docker/
2. See that the first instruction is about `docker-compose` but the way to obtain the actual code is missing.

### What I expected to happen
I expect the docs to have a more detailed instruction regarding cloning the code prior to running the docker-compose commands. In the other installation methods, this is very clear (for [example](https://docs.getsaleor.com/docs/getting-started/installation-linux/))

**Comment by karolkielecki** [comment]
Hey @AlmogCohen. Thanks for pointing this out. We are aware that we need to improve our docs. We'll start working on that as soon as we can. In the meantime, if you have any issues or feedback, please let us know.
