### ISSUE TITLE
Support for cloud database connection

### ISSUE THREAD

**Issue by daniel-rosiak** [mirumee/saleor#5201]
### What I'm trying to achieve
I'm trying to connect to SQL on Google Cloud Platform.
Saleor is not supporting cloud database connections because **dj_database_url** is not supporting them.

### Describe a proposed solution
1: 
There is an open pull request in [dj_database_url repo](https://github.com/jacobian/dj-database-url/pull/113). Push for this to be merged

2: 
Allow to specify connection manually, example solution:
[https://github.com/mirumee/saleor/blob/master/saleor/settings.py](https://github.com/mirumee/saleor/blob/master/saleor/settings.py)
```python
DATABASE_ENGINE = os.environ.get("DATABASE_ENGINE", "django.db.backends.postgresql")
DATABASE_HOST = os.environ.get("DATABASE_HOST", "")
DATABASE_USER = os.environ.get("DATABASE_USER", "saleor")
DATABASE_PASS = os.environ.get("DATABASE_PASS", "saleor")
DATABASE_DB = os.environ.get("DATABASE_DB", "saleor")

if not DATABASE_HOST:
    DATABASES = {
        "default": dj_database_url.config(
            default="postgres://saleor:saleor@localhost:5432/saleor", conn_max_age=600
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": DATABASE_ENGINE,
            "HOST": DATABASE_HOST,
            "NAME": DATABASE_DB,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASS,
            "CONN_MAX_AGE": 600
        }
    }
````

3:
Use some other library

### Other solutions I've tried and won't work
…

### Screenshots or mockups
...

**Comment by maarcingebala** [comment]
I can see that some PRs were merged recently but the last release of `dj_database_url` is from March 2018 which doesn't look too optimistic. If we want to support cases like this one, we would have to introduce additional configuration as you suggest @daniel-rosiak.
