### ISSUE TITLE
Navigator does not work on demo

### ISSUE THREAD

**Issue by akjanik** [mirumee/saleor#5202]
### What I'm trying to achieve
Using navigator featured in blog post
https://saleor.io/blog/increase-your-efficiency-with-dashboard-navigator-119/

### Steps to reproduce the problem
1. Log in to demo
2. Use key combination `ctrl + k`

### What I expected to happen
Navigator has been opened

### What actually happen
On Chromium based web browser - nothing
Using Mozilliza Firefox triggers search action (this is browser behavior):
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_search
I am not sure if Saleor aims to overwrite this feature.

**System information**
Operating system: MacOS

**Comment by maarcingebala** [comment]
On demo we're running Saleor 2.9 and Dashboard 2.0 versions, where Navigator hasn't been released yet. You can test it on `master` if you set it up locally or using our internal staging instance. We're planning to improve our release cycle to release more often after the 2.10 version.
