### ISSUE TITLE
draftOrderCreate won't accept valid variantId

### ISSUE THREAD

**Issue by dsbrgg** [mirumee/saleor#5203]
### What I'm trying to achieve

Create a draft order.

### Steps to reproduce the problem

1.  Initate the local dev server on `0.0.0.0:8000`
2.  Call GraphQL mutation `draftOrderCreate` with values from dev migrations and an admin token.

eg.
```
...
draftOrderCreate(input:{
    shippingAddress: {
    	city: "Cidade"
		},
		lines: [ {
			quantity: 5,
			variantId: 196
		} ]
  }) {
...
```

3. Returns an error:

```
"draftOrderCreate": {
      "errors": [
        {
          "field": "variants",
          "message": "Could not resolve to a node with the global id list of '['196']'."
        }
      ],
      "orderErrors": [
        {
          "code": "GRAPHQL_ERROR",
          "field": "variants",
          "message": "Could not resolve to a node with the global id list of '['196']'."
        }
      ],
      "order": null
    }
  }
```
### What I expected to happen

I expect to be able to create a draft order with admin credentials

**System information**

Operating system: macOS 10.14.6

**Comment by chrisyue1998** [comment]
Hey, were you able to find a fix to this?
