### ISSUE TITLE
Fully handle SCA flow in the checkout

### ISSUE THREAD

**Issue by salwator** [mirumee/saleor#5204]
### What I'm trying to achieve
When processing payment during _checkoutComplete_ mutation I need to be able to confirm payment and finish checkout process and get order. To do that I need extra step that https://github.com/mirumee/saleor/pull/5179 provides and additional payment context stored that right now does not exists.

### Describe a proposed solution
Taking stripe PaymentIntent flow as an example, what I need to do is:
- create payment intent on payment gateway
- store intents ID and potentially share it with client
- if additional action is required by client, PaymentIntent is confirmed externally and checkoutComplete is called again, now payment should be confirmed, not captured again. To do that we need to restore previously created intents ID.

To do all that we probably need to extract and save ID in payment object every time when 3D secure is enabled.

### Other solutions I've tried and won't work
Using token as a storage for intents ID, bad idea.

**Comment by patrys** [comment]
We should also update docs to mention this (and what's needed for SCA compliance).

**Comment by dbbk** [comment]
Is there any movement on this? 3D Secure is a requirement for businesses in Europe, but from what I can gather Saleor still does not support it via Stripe...

**Comment by korycins** [comment]
Hey, for Saleor3.0 we fully rebuild a Stripe plugin. It uses custom payment flow and payment intents. Here you can find more details - code: #7452 docs: mirumee/saleor-docs#277
Also, closing this issue as this is already handled by checkoutComplete and payment gateways such Stripe and Adyen
