### ISSUE TITLE
How info.context.country is made?

### ISSUE THREAD

**Issue by Boquete** [mirumee/saleor#5208]
When creating certain mutation from dashboard, for example ProductVariantUpdate -> quantity, quntity is changed in stock in certain country.

This information is resolved from info.context.country

Where is it declared what country is it? Is it HttpRequest parsed and added to graphql context? 
Or is it default_country for saleor?

**Comment by maarcingebala** [comment]
It's added to the request with a middleware `saleor.core.middleware.country`. See this function: https://github.com/mirumee/saleor/blob/master/saleor/core/middleware.py#L57. It uses GeoIP to determine the country of a person that sends the request.

It's part of the legacy Storefront and before we release a new version we want to change the API to be able to explicitly pass the country code in mutation input, see this issue for discussion: https://github.com/mirumee/saleor/issues/4315

**Comment by Boquete** [comment]
Great, thank you.
