### ISSUE TITLE
Node peerDependencies issue for Grunt when pushing to Heroku (regardless of node version)

### ISSUE THREAD

**Issue by iansprice** [mirumee/saleor#521]
I have an existing Saleor project that was forked about two months ago. Trying to push new commits, I get errors at the `npm install` stage. 

Traceback:
```
remote: 13612 verbose cwd /tmp/build_3352709514c6073540abbc12deb4ae94
remote: 13613 error Linux 3.13.0-79-generic
remote: 13614 error argv "/tmp/build_3352709514c6073540abbc12deb4ae94/vendor/node/bin/node" "/tmp/build_3352709514c6073540abbc12deb4ae94/vendor/node/bin/npm" "install" "grunt"
remote: 13615 error node v0.12.13
remote: 13616 error npm  v2.15.0
remote: 13617 error code EPEERINVALID
remote: 13618 error peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
remote: 13618 error peerinvalid Peer grunt-postcss@0.7.2 wants grunt@>=0.4.5
remote: 13618 error peerinvalid Peer grunt-contrib-copy@0.6.0 wants grunt@~0.4.0
remote: 13618 error peerinvalid Peer grunt-contrib-watch@0.6.1 wants grunt@~0.4.0
remote: 13618 error peerinvalid Peer grunt-contrib-less@0.11.4 wants grunt@~0.4.0
remote: 13619 verbose exit [ 1, true ]
remote: 
remote:  !     Push rejected, failed to compile Multipack app
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to saleor_app.
```

The confusing thing is that if I change the node version in packages.json to `0.12.11` or `0.12.12` and specify an exact version of grunt (`0.4.5`) I still get this issue and npm attempts to install grunt `1.0.1`. Nonetheless, my local environment still runs fine.

I cannot successfully push and am not sure what other steps to take (cleared my npm cache, turned off heroku npm caching, attempted reinstall). Since packages.json hasn't had a new commit in months I assume others may have this issue.

**Comment by patrys** [comment]
We'll look into that. In the meantime you may try to work around by running `npm shrinkwrap` and adding the resulting file to the repository.

**Comment by iansprice** [comment]
Thanks for the help! In case anyone else runs into this and is as npm illiterate as I am, here's what got me up and running:

1. `cd` to project root dir and run the following command. `--dev` flag is important; it includes the devDependencies in the shrinkwrap. Without this, the problem persisted.
`npm shrinkwrap --dev`
2. Commit the newly generated `npm-shrinkwrap.json` file
3. Push your commits. Voila!

Thanks @patrys , you guys are rockstars.

**Comment by iansprice** [comment]
Recent attempts to push failed unless I specified node version 4.2.6 and npm version 3.5.2.  
```
"engines": {
    "node": "4.2.6",
    "npm": "3.5.2"
  },
```

**Comment by patrys** [comment]
I've bumped the node version to 5.10 now.

**Comment by patrys** [comment]
I've also updated the buildpack list as Heroku now properly implements multiple buildpacks, everything should work as expected.
