### ISSUE TITLE
Low score on Page speed insight / Google Lighthouse report

### ISSUE THREAD

**Issue by joehua87** [mirumee/saleor#5214]
### What I'm trying to achieve
- I expected more higher score on the test.
- Because the Home page is not show very much content, it deserve the higher rate as it claims.

### Steps to reproduce the problem
1. Open Google Chrome Developer Tools, click the Audits Tab, run audit
2. Or, go to this link: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpwa.saleor.io%2F&tab=mobile

### What I expected to happen
Better performance

### Screenshots
<img width="841" alt="Screen Shot 2020-01-30 at 22 17 23" src="https://user-images.githubusercontent.com/11925924/73462401-548b3080-43ae-11ea-8c78-9cdb5dd95e8e.png">
<img width="836" alt="Screen Shot 2020-01-30 at 22 13 55" src="https://user-images.githubusercontent.com/11925924/73462113-d6c72500-43ad-11ea-92c9-010a1a5bd970.png">
<img width="788" alt="Screen Shot 2020-01-30 at 22 11 55" src="https://user-images.githubusercontent.com/11925924/73462150-e3e41400-43ad-11ea-9bc4-40d2c41e6043.png">

**System information**
Operating system:

**Comment by karolkielecki** [comment]
Hey @joehua87. Thank you for pointing this out. We're aware that it needs improvements and better optimization. PWA functionality is in beta, so we're working to fix it as soon as we can. Performance is one of our main priorities. If you have any questions or feedback, feel free to let us know.

**Comment by patrys** [comment]
While it was closed by the bot as stale, the issue should be already fixed on the master branch of `saleor-storefront`. We use Lighthouse as part of our continuous integration pipeline.
