### ISSUE TITLE
Enforce unique ordering in GraphQL queries

### ISSUE THREAD

**Issue by saschametz** [mirumee/saleor#5219]
Currently the GraphQL API allows queries like this:
```gql
{
  products(first: 10, sortBy: { field: PUBLISHED, direction: ASC }) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        id
        name
      }
    }
  }
}
```
which results in the following SQL query:
```sql
SELECT DISTINCT "product_product"."id",
       -- ...
FROM "product_product"
WHERE (("product_product"."publication_date" <= '2020-02-02'::date OR "product_product"."publication_date" IS NULL) AND "product_product"."is_published" = true)
ORDER BY "product_product"."is_published" ASC
LIMIT 10
```

The GraphQL query for the next page looks like this:
```gql
{
  products(
    first: 10
    sortBy: { field: PUBLISHED, direction: ASC }
    after: "YXJyYXljb25uZWN0aW9uOjk="
  ) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        id
        name
      }
    }
  }
}
```

The corresponding SQL query:
```sql
SELECT DISTINCT "product_product"."id",
       -- ...
FROM "product_product"
WHERE (("product_product"."publication_date" <= '2020-02-02'::date OR "product_product"."publication_date" IS NULL) AND "product_product"."is_published" = true)
ORDER BY "product_product"."is_published" ASC
LIMIT 10
OFFSET 10
```

Saleor allows to sort the entries by the `PUBLISHED` field which represents the boolean field `is_published` on the Product model. This field is not unique because many product entries can have the same value for this specific field.

In the Postgres docs it says: "When using `LIMIT`, it is important to use an `ORDER BY` clause that constrains the result rows into a **unique order**. Otherwise you will get an unpredictable subset of the query's rows" ([Reference](https://www.postgresql.org/docs/current/queries-limit.html))
(There are also a lot of useful posts on [Stack](https://stackoverflow.com/questions/13580826/postgresql-repeating-rows-from-limit-offset))

The `is_published` field ist not unique and when using the pagination feature of the GraphQL query this can lead to the following situation:

Query of the first page contains **Product 1**, Product 4, Product 7
Query of the second page contains Product 8, Product 9, **Product 1**
-> Product 1 is present on page 1 and 2

I agree that this situation doesn't happen often and can only occur under certain circumstances. But I had this exact same problem today with my own project and I fixed it by adding a second **unique field** to the ORDER BY clause.

**Comment by karolkielecki** [comment]
Hey @saschametz. Thanks for pointing this out. We'll be working on some changes related to this issue, but I don't know the details yet. In the meantime, if you have more questions or feedback, just let me know.

**Comment by NyanKiyoshi** [comment]
I think @IKarbowiak is working on that
