### ISSUE TITLE
Quantity 10 + in cart

### ISSUE THREAD

**Issue by kuba777** [mirumee/saleor#522]
Hi,

I cannot update quantity in cart after 10 + is selected. I get this and 400 error:
`storefront.js:26 Warning: ReactDOMComponent: Do not access .props of a DOM node; instead, recreate the props as `render` did originally or read the DOM properties/attributes directly from this node (e.g., this.refs.box.className). This DOM node was rendered by `t`.
t.production.t.env.NODE_ENV.r	@	storefront.js:26`

Where do I set my domain name for emails and redirection after payment?

**Comment by InYourDreamz** [comment]
We got the same bug as well.

**Comment by patrys** [comment]
Took me some time to find this but it's fixed now. :snail:
