### ISSUE TITLE
When I set GS_STORAGE_BUCKET_NAME , it throwed "Cannot determine path without bucket name"

### ISSUE THREAD

**Issue by lewis617** [mirumee/saleor#5222]
### What I'm trying to achieve
…

### Steps to reproduce the problem
1. set GS_STORAGE_BUCKET_NAME
2. docker-compose run --rm web python3 manage.py collectstatic

### What I expected to happen
…

### Screenshots
![image](https://user-images.githubusercontent.com/11524612/73646851-3b87c580-46b5-11ea-9aa7-d8eb721f0865.png)

**System information**
Operating system:

**Comment by elzerver** [comment]
Hi!

How it looks your docker compose ?
The error mentions that you need to specify the bucket name, besides this 
you could try to run the docker compose command like this :
```
docker-compose run -e GS_STORAGE_BUCKET_NAME=$VALUE --rm web python3 manage.py collectstatic
```

**Comment by lewis617** [comment]
> Hi!
> 
> How it looks your docker compose ?
> The error mentions that you need to specify the bucket name, besides this
> you could try to run the docker compose command like this :
> 
> ```
> docker-compose run -e GS_STORAGE_BUCKET_NAME=$VALUE --rm web python3 manage.py collectstatic
> ```

I added `GS_BUCKET_NAME = GS_STORAGE_BUCKET_NAME` in settings.py, and it worked well.

**Comment by elzerver** [comment]
Well done! ;)
