### ISSUE TITLE
Custom module graphql type issue

### ISSUE THREAD

**Issue by cc07** [mirumee/saleor#5225]
I have add a custom module exactly referring to the existing Page module, however, when i tried to generate graphql schema. The blog type became BlogTranslatableContent instead of Blog, i couldnt finger the reason.

```
type BlogCreate {
  errors: [Error!]
  blog: BlogTranslatableContent
}

type BlogDelete {
  errors: [Error!]
  blog: BlogTranslatableContent
}
```

**Comment by karolkielecki** [comment]
Hey @cc07. From what class inherit your BlogCreate mutation?

**Comment by cc07** [comment]
Thanks for help @karolkielecki. I actually cloned from Page module and renamed everything to Blog, but it just does not work as expected.

```
class BlogCreate(ModelMutation):
    class Arguments:
        input = BlogInput(
            required=True, description="Fields required to create a blog."
        )

    class Meta:
        description = "Creates a new blog."
        model = models.Blog
        # permissions = (BlogPermissions.MANAGE_BLOGS,)

    @classmethod
    def clean_input(cls, info, instance, data):
        cleaned_input = super().clean_input(info, instance, data)
        slug = cleaned_input.get("slug", "")
        title = cleaned_input.get("title", "")
        if title and not slug:
            cleaned_input["slug"] = slugify(title)
        clean_seo_fields(cleaned_input)
        return cleaned_input
```

**Comment by karolkielecki** [comment]
Did you set the correct mutation in the schema.py file? 

A page example: 
page_create = PageCreate.Field()
page_translate = PageTranslate.Field()

In your case, it should be like this:
blog_create = BlogCreate.Field()

Please also check if this schema is added in proper place in api,py file.

**Comment by cc07** [comment]
yes, exactly like that. I tried to replace `model = models.Blog` in `class BlogCreate(ModelMutation):` for testing, the schema will be like. How does the graphql get type that make it TranslatableContent?

```
type BlogCreate {
  errors: [Error!]
  blog: PageTranslatableContent
}
```

**Comment by karolkielecki** [comment]
What types do you have in blog/types.py?

**Comment by cc07** [comment]
```
from graphene import relay

from ...blog import models
from ..core.connection import CountableDjangoObjectType
from ..translations.fields import TranslationField
from ..translations.types import BlogTranslation


class Blog(CountableDjangoObjectType):
    translation = TranslationField(BlogTranslation, type_name="blog")

    class Meta:
        description = (
            "A static blog that can be manually added by a shop operator through the "
            "dashboard."
        )
        only_fields = [
            "content",
            "content_json",
            "created",
            "id",
            "is_published",
            "publication_date",
            "seo_description",
            "seo_title",
            "slug",
            "title",
        ]
        interfaces = [relay.Node]
        model = models.Blog
```

**Comment by selmanceker** [comment]
Hi @cc07,

I am trying make same thing for Comment model and facing the error below. 
`Unable to find type for model Comment in graphene registry`

Have you solved the problem and how I can generate graphql schema, can you share with me?
