### ISSUE TITLE
Facebook auth / saleor storefront / graphql

### ISSUE THREAD

**Issue by Boquete** [mirumee/saleor#5228]
### What I'm trying to achieve
Facebook authentication to user account, using graphql API
You guys any got tips how to implement it? Should we use external libraries?

### Describe a proposed solution
...

### Other solutions I've tried and won't work
…

**Comment by karolkielecki** [comment]
Hey @Boquete. Maybe you can try this solution: https://github.com/mirumee/saleor/issues/5119#issuecomment-569332978

**Comment by Boquete** [comment]
For anyone intrested: 
graphql/account/mutations/social_auth.py

```
import graphene
import logging
import django.conf as conf

from functools import wraps
from django.utils.translation import ugettext as _

from promise import Promise, is_thenable
from django.dispatch import Signal

from graphql_jwt.exceptions import JSONWebTokenError
from graphql_jwt.mixins import ResolveMixin, ObtainJSONWebTokenMixin
from graphql_jwt.decorators import setup_jwt_cookie
from graphql_jwt.settings import jwt_settings
from graphql_jwt.shortcuts import get_token
from graphql_jwt.refresh_token.shortcuts import refresh_token_lazy
from social_django.utils import load_strategy, load_backend
from social_django.compat import reverse

from ...account.types import User
from ...core.types import Error
from ...shop.types import AuthorizationKeyType
from ....site.models import AuthorizationKey

logger = logging.getLogger(__name__)

token_issued = Signal(providing_args=['request', 'user'])


def token_auth(f):
    @wraps(f)
    @setup_jwt_cookie
    def wrapper(cls, root, info, **kwargs):
        context = info.context
        context._jwt_token_auth = True

        def on_resolve(values):
            user, payload = values
            payload.token = get_token(user, context)

            if jwt_settings.JWT_LONG_RUNNING_REFRESH_TOKEN:
                payload.refresh_token = refresh_token_lazy(user)

            return payload

        token = kwargs.get('access_token')
        backend = kwargs.get('backend')

        if not hasattr(conf.settings, 'SOCIAL_AUTH_FACEBOOK_KEY') or not hasattr(conf.settings,
                                                                                  'SOCIAL_AUTH_FACEBOOK_SECRET'):
            authorization_key = AuthorizationKey.objects.get(name=backend)
            conf.settings.SOCIAL_AUTH_FACEBOOK_KEY = authorization_key.key
            conf.settings.SOCIAL_AUTH_FACEBOOK_SECRET = authorization_key.password

        context.social_strategy = load_strategy(context)
        # backward compatibility in attribute name, only if not already
        # defined
        if not hasattr(context, 'strategy'):
            context.strategy = context.social_strategy
        uri = reverse('social:complete', args=(backend,))
        context.backend = load_backend(context.social_strategy, backend, uri)

        user = context.backend.do_auth(token)

        if user is None:
            raise JSONWebTokenError(
                _('Please, enter valid credentials'))

        if hasattr(context, 'user'):
            context.user = user

        result = f(cls, root, info, **kwargs)
        values = (user, result)

        token_issued.send(sender=cls, request=context, user=user)

        if is_thenable(result):
            return Promise.resolve(values).then(on_resolve)
        return on_resolve(values)

    return wrapper


class JSONWebTokenMutation(ObtainJSONWebTokenMixin, graphene.Mutation):
    class Meta:
        abstract = True

    @classmethod
    @token_auth
    def mutate(cls, root, info, **kwargs):
        return cls.resolve(root, info, **kwargs)


class CreateOAuthToken(ResolveMixin, JSONWebTokenMutation):
    errors = graphene.List(Error, required=True)
    user = graphene.Field(User)

    class Arguments:
        access_token = graphene.String(description="Access token.")
        backend = AuthorizationKeyType(
            required=True, description="Authentication backend."
        )

    @classmethod
    def mutate(cls, root, info, **kwargs):
        try:
            result = super().mutate(root, info, **kwargs)
        except JSONWebTokenError as e:
            logger.error(e)
            return CreateOAuthToken(errors=[Error(message=str(e))])
        else:
            return result

    @classmethod
    def resolve(cls, root, info, **kwargs):
        return cls(user=info.context.user, errors=[])


class OAuthMutations(graphene.ObjectType):
    oauth_token_create = CreateOAuthToken.Field()
```

**Comment by Boquete** [comment]
settings.py

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email',
}

**Comment by maarcingebala** [comment]
Thanks for sharing. If it works well as it is, we should actually add it to Saleor. Do you use it with `saleor-storefront` @Boquete?

**Comment by maarcingebala** [comment]
I suppose we want to have Facebook auth for storefront customers, while for dashboard users we can keep using the standard JWT based authentication.

**Comment by Boquete** [comment]
> Thanks for sharing. If it works well as it is, we should actually add it to Saleor. Do you use it with `saleor-storefront` @Boquete?

yeah we use it in storefront.
Frontend is generating user token from Facebook, based on our Facebook public key (from social accounts schema), after that token is passed to mutation oauthTokenCreate(token:fb_token) 

the result of this mutation is JWT token. you can see sample on https://mamaginekolog.pl (upper right corner there is profile icon, and "Zaloguj przez Facebooka".

It creates user in first login, after that it's just log-in

**Comment by lbrito55** [comment]
@Boquete After you authenticate succesfully with facebook, are you storing the personal data thats given from facebook into the database table account_user?

Im currently trying to achive the same facebook login in my project.

>

**Comment by Boquete** [comment]
@lbrito55  yeah I do, but you need to extend facebook permission for user email.

After first login, saleor/account/user is made and after that user log in to it.

**Comment by dotslash227** [comment]
> > Thanks for sharing. If it works well as it is, we should actually add it to Saleor. Do you use it with `saleor-storefront` @Boquete?
> 
> @maarcingebala yeah we use it in storefront.
> Frontend is generating user token from Facebook, based on our authentication Facebook app public key (saleor authentication keys schema), after that token is passed to mutation oauthTokenCreate(token:fb_token, provider: facebook)
> 
> the result of this mutation is JWT token. you can see sample on https://mamaginekolog.pl (upper right corner there is profile icon, and "Zaloguj przez Facebooka".
> 
> It creates user in first login, after that it's just log-in

When I try to Pass google/facebook tokens to oauthTokenCreate(token:fb_token, provider: facebook), I get this error: AttributeError: 'WSGIRequest' object has no attribute 'session' 

Any idea how to fix it?

**Comment by Boquete** [comment]
Hey @dotslash227  do you mind sharing your settings.py MIDDLEWARE? Might be problem with https://stackoverflow.com/questions/39480179/wsgirequest-object-has-no-attribute-session-while-upgrading-from-django-1-3

```
MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "saleor.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    ....
    "saleor.core.middleware.jwt_refresh_token_middleware",
]

```

**Comment by timothymugayi** [comment]
Ain't this something, am working on the same implementation as we speak was planning to go the conventional way over graphql, The above code just opened up an alternative approach that's consistent with saleor design patterns.

**Comment by ieow** [comment]
ios safari has been blocking third party tracking which causing login using fb not working ( could not get the access token )
 instead we can use redirect which have "code" (query) params that can be used by server to obtain access token.

I am looking for direction on how to use Django social to do_auth via "code" instead of "access_token"
Anyone have this kinds of solution or hit similar issue?

**Comment by franchardin** [comment]
> settings.py
> 
> ```
> SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
> SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
>     'fields': 'id,name,email',
> }
> 
> SOCIAL_AUTH_POSTGRES_JSONFIELD = True
> SOCIAL_AUTH_URL_NAMESPACE = 'social'
> SOCIAL_AUTH_PIPELINE = (
>     'social_core.pipeline.social_auth.social_details',
>     'social_core.pipeline.social_auth.social_uid',
>     'social_core.pipeline.social_auth.social_user',
>     'social_core.pipeline.user.get_username',
>     'social_core.pipeline.user.create_user',
>     'social_core.pipeline.social_auth.associate_user',
>     'social_core.pipeline.social_auth.load_extra_data',
>     'social_core.pipeline.user.user_details',
>     'social_core.pipeline.social_auth.associate_by_email',
> )
> 
> AUTHENTICATION_BACKENDS = [
>     "social_core.backends.facebook.FacebookOAuth2",
> ```
> 
> and social_django in installed apps

Thank you so much!

**Comment by zamaniramin549** [comment]
> > Thanks for sharing. If it works well as it is, we should actually add it to Saleor. Do you use it with `saleor-storefront` @Boquete?
> 
> @maarcingebala yeah we use it in storefront. Frontend is generating user token from Facebook, based on our authentication Facebook app public key (saleor authentication keys schema), after that token is passed to mutation oauthTokenCreate(token:fb_token, provider: facebook)
> 
> the result of this mutation is JWT token. you can see sample on https://mamaginekolog.pl (upper right corner there is profile icon, and "Zaloguj przez Facebooka".
> 
> It creates user in first login, after that it's just log-in

How to pass the Public key and Secret key for FB to work?

**Comment by zamaniramin549** [comment]
> For anyone intrested: graphql/account/mutations/social_auth.py
> 
> ```
> import graphene
> import logging
> import django.conf as conf
> 
> from functools import wraps
> from django.utils.translation import ugettext as _
> 
> from promise import Promise, is_thenable
> from django.dispatch import Signal
> 
> from graphql_jwt.exceptions import JSONWebTokenError
> from graphql_jwt.mixins import ResolveMixin, ObtainJSONWebTokenMixin
> from graphql_jwt.decorators import setup_jwt_cookie
> from graphql_jwt.settings import jwt_settings
> from graphql_jwt.shortcuts import get_token
> from graphql_jwt.refresh_token.shortcuts import refresh_token_lazy
> from social_django.utils import load_strategy, load_backend
> from social_django.compat import reverse
> 
> from ...account.types import User
> from ...core.types import Error
> from ...shop.types import AuthorizationKeyType
> from ....site.models import AuthorizationKey
> 
> logger = logging.getLogger(__name__)
> 
> token_issued = Signal(providing_args=['request', 'user'])
> 
> 
> def token_auth(f):
>     @wraps(f)
>     @setup_jwt_cookie
>     def wrapper(cls, root, info, **kwargs):
>         context = info.context
>         context._jwt_token_auth = True
> 
>         def on_resolve(values):
>             user, payload = values
>             payload.token = get_token(user, context)
> 
>             if jwt_settings.JWT_LONG_RUNNING_REFRESH_TOKEN:
>                 payload.refresh_token = refresh_token_lazy(user)
> 
>             return payload
> 
>         token = kwargs.get('access_token')
>         backend = kwargs.get('backend')
> 
>         if not hasattr(conf.settings, 'SOCIAL_AUTH_FACEBOOK_KEY') or not hasattr(conf.settings,
>                                                                                   'SOCIAL_AUTH_FACEBOOK_SECRET'):
>             authorization_key = AuthorizationKey.objects.get(name=backend)
>             conf.settings.SOCIAL_AUTH_FACEBOOK_KEY = authorization_key.key
>             conf.settings.SOCIAL_AUTH_FACEBOOK_SECRET = authorization_key.password
> 
>         context.social_strategy = load_strategy(context)
>         # backward compatibility in attribute name, only if not already
>         # defined
>         if not hasattr(context, 'strategy'):
>             context.strategy = context.social_strategy
>         uri = reverse('social:complete', args=(backend,))
>         context.backend = load_backend(context.social_strategy, backend, uri)
> 
>         user = context.backend.do_auth(token)
> 
>         if user is None:
>             raise JSONWebTokenError(
>                 _('Please, enter valid credentials'))
> 
>         if hasattr(context, 'user'):
>             context.user = user
> 
>         result = f(cls, root, info, **kwargs)
>         values = (user, result)
> 
>         token_issued.send(sender=cls, request=context, user=user)
> 
>         if is_thenable(result):
>             return Promise.resolve(values).then(on_resolve)
>         return on_resolve(values)
> 
>     return wrapper
> 
> 
> class JSONWebTokenMutation(ObtainJSONWebTokenMixin, graphene.Mutation):
>     class Meta:
>         abstract = True
> 
>     @classmethod
>     @token_auth
>     def mutate(cls, root, info, **kwargs):
>         return cls.resolve(root, info, **kwargs)
> 
> 
> class CreateOAuthToken(ResolveMixin, JSONWebTokenMutation):
>     errors = graphene.List(Error, required=True)
>     user = graphene.Field(User)
> 
>     class Arguments:
>         access_token = graphene.String(description="Access token.")
>         backend = AuthorizationKeyType(
>             required=True, description="Authentication backend."
>         )
> 
>     @classmethod
>     def mutate(cls, root, info, **kwargs):
>         try:
>             result = super().mutate(root, info, **kwargs)
>         except JSONWebTokenError as e:
>             logger.error(e)
>             return CreateOAuthToken(errors=[Error(message=str(e))])
>         else:
>             return result
> 
>     @classmethod
>     def resolve(cls, root, info, **kwargs):
>         return cls(user=info.context.user, errors=[])
> 
> 
> class OAuthMutations(graphene.ObjectType):
>     oauth_token_create = CreateOAuthToken.Field()
> ```

I get "Cannot query field \"oauthTokenCreate\" on type \"Mutation\". error
