### ISSUE TITLE
Need multiple view of product currently only one photos shows for the product

### ISSUE THREAD

**Issue by niteshldd** [mirumee/saleor#5229]
### What I'm trying to achieve
…
Multiple display for product like front and back 

### Describe a proposed solution
...
Not currently in mind 

### Other solutions I've tried and won't work
…

### Screenshots or mockups

[](url)
<img width="729" alt="Screenshot 2020-02-06 at 5 31 43 PM" src="https://user-images.githubusercontent.com/36432860/73935590-e0e5a800-4906-11ea-8ae6-4631a4e4586b.png">

**Comment by maarcingebala** [comment]
Closing this since it's not related to Saleor core, it's more about saleor-storefront. We're working on a redesign of the product page where there will be multiple thumbnails of a product showed next the main image (https://github.com/mirumee/saleor-storefront/pull/592)
