### ISSUE TITLE
How do I Login into the admin area ?

### ISSUE THREAD

**Issue by quakig** [mirumee/saleor#523]
I installed Saleor on my localhost and tried to login into the dashboard at URL
http://127.0.0.1:8000/account/login/

with the Login credentials: admin@example.com/admin

However it gives the following errors:
![1](https://cloud.githubusercontent.com/assets/2546691/14885103/27c82110-0d67-11e6-8725-ec228fc15df6.png)

How do I login into the the admin area ?

**Comment by patrys** [comment]
The credentials are for Heroku. If you work with your local machine start with `python manage.py createsuperuser` to have Django create an admin user for you.

**Comment by quakig** [comment]
My bad.  Thanks for the prompt reply

**Comment by patrys** [comment]
You're welcome! :smile:
