### ISSUE TITLE
Payment gateway : external payment page

### ISSUE THREAD

**Issue by tboulogne** [mirumee/saleor#5232]
### What I'm trying to achieve
implement a payent gateway with external payment page

Hello,

I user my own saleor client (based on wagtail :-) ). I'd like to implement some payment gateway with external page.

1. Customer fulfill order on site
2. Confirm order and be redirected to external payment page.
3. external payment system confirm payment with callback url to wagtail
4. From information to the callback url i create payment on saleor and complete order.

I did not clearly understand from documentation how i could to this cleanly.

Does anyone could help on this please ?

Thanks for all

**Comment by tboulogne** [comment]
ok got it ;-) !

**Comment by cosmy81** [comment]
Hi, how did you managed it?

**Comment by tboulogne** [comment]
Hello, i manage all the process on the frontend :
> send amount to paiement gateway
> receive IPN,

and i wrote a saleor payement module called on receiving IPN, to validate the payment on saleor.

**Comment by cosmy81** [comment]
So you  create the ipn url in the frontend and then you pass it to paypal with a POST/GET submit, do you?
Where do you get the data to compose the amount and the configuration?
Inside PaymentGatewaysList component I receive a config object, but it doesn't contain all the plugin config I've inserted in the backoffice (merchant email, currency and so on). And the total amount seems to be outside the scope of this component.
And what about the return on the website? I immagine that inside the IPN you register the payment (what's the function to do it?) and create the order, but how do you manage the forward to the thank you page from paypal?
Thank you in advance

**Comment by tboulogne** [comment]
hey lot of questions :-) !
I will try to answer some. On the frontend you need to manage a cart system. On checkout, you use saleor API to create a checkout. You receive information of checkout to submit to paypal (frontend). You receive PayPal IPN on frontend. You show the thank you page and validate checkout on saleor and validate payment...
I hope you see the idea :-).

**Comment by tboulogne** [comment]
UPDATE :
You need to manage a cart system on frontend using saleor graphql api (create cart, addtocart, updatecarte, ....)

**Comment by cosmy81** [comment]
I've managed to integrate Paypal through react-paypal-js sdk. The paypal gateway is managed in frontend so you don't need IPN and server side calls. 
Just a little of work to understand the page redirects inside the storefront after payment actions.
