### ISSUE TITLE
How is Stripe payment Intents handled with the GraphQL Checkout

### ISSUE THREAD

**Issue by matthewhardern** [mirumee/saleor#5233]
Just come across this product, looks amazing. My question is brief and if there are some docs for this can you point me in the right direction. What mutations / queries do I need to perform in order to complete a checkout for Stripe payment intents? Sorry if this is the wrong place for this question

**Comment by karolkielecki** [comment]
Hey @matthewhardern! Welcome to Saleor. Thank you for your kind words. Of course, it's the right place to ask the questions :)

You can find more details about Stripe integration here: https://docs.saleor.io/docs/integrations/payment-gateways/#stripe

If you have any questions or feedback, you can also reach us at [Gitter](https://gitter.im/mirumee/saleor) or/and [Spectrum](https://spectrum.chat/saleor).
Best
