### ISSUE TITLE
Always redirect to graphql

### ISSUE THREAD

**Issue by vonsogt** [mirumee/saleor#5237]
### What I'm trying to achieve
Getting into dashboard/fronted-end

### Steps to reproduce the problem
1. after installing the tutorial in "https://docs.getsaleor.com/docs/next/getting-started/installation-windows/"
2. and run the server "python manage.py runserver"

### What I expected to happen
The browser will open dashboard/fronted-end

### Screenshots
![image](https://user-images.githubusercontent.com/35516476/74210852-fae50900-4cbf-11ea-801c-f9383ba4db76.png)

### I tried to fix:
- ENABLE_DEBUG_TOOLBAR = get_bool_from_env("ENABLE_DEBUG_TOOLBAR", False)
- ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL to false
and get new problem "The requested resource was not found on this server."

**System information**
Operating system:
Windows 10

**Comment by maarcingebala** [comment]
This guide only tells how to install the backend part so this is all correct. To set up the frontend apps, refer to installation guides in their readme's:
- https://github.com/mirumee/saleor-storefront/
- https://github.com/mirumee/saleor-dashboard/
