### ISSUE TITLE
How to get credit card information

### ISSUE THREAD

**Issue by srendon** [mirumee/saleor#5240]
### What I'm trying to achieve
Hi Saleor team, I'm implementing my own payment gateway. It requires card's information such as: Card number, Name on card, expiration date, and CVV. While in the process of a [checkout](https://docs.saleor.io/docs/next/api-process/check-out/#creating-the-checkout) there isn't a field for adding such information during the whole process. How can you manage to add credit cards ? What do you recommend me doing ?

**Comment by krzysztofwolski** [comment]
Hello! 
'Save card' functionality should be implemented using gateway API. I find Stripe docs the best in the class, I recommend it as an example: https://stripe.com/docs/payments/save-after-payment

So the workflow goes like: 
1. User use card for payment. Card details are exchanged using js without using your shop servers
2. Your server gets a payment **token** which is safe to use. Assign it to the user using gateway API
3. When user go to checkout next time, your backend can get list of saved cards from gateway API and send tokens with non confidential data (last 4 digits, name) so you can present it as choice for the user.

Friendly reminder: When working with credit cards, never, ever, send card details (number, cvv) to your server directly. It will create lots of trouble for you and your customers. Make sure it's not also in logs.

**Comment by alxvallejo** [comment]
@ krzysztofwolski

>Friendly reminder: When working with credit cards, never, ever, send card details (number, cvv) to your server directly. It will create lots of trouble for you and your customers. Make sure it's not also in logs.

So then why does Stripe's API documentation specifically reference server side handling of storing CCs? https://stripe.com/docs/api/cards/create?lang=python#create_card
