### ISSUE TITLE
Missing npm run build-assets script

### ISSUE THREAD

**Issue by beyzakilickol** [mirumee/saleor#5242]
&nbsp;&nbsp;&nbsp;I follow the steps on the link https://docs.saleor.io/docs/getting-started/installation-macos/ to install saleor.' npm run build-assets command' is giving 'missing script build-assets' error. I cloned the master branch and on package.json file, I do not see the that script either. Please see below.

    "scripts": {
    "build-schema": "python manage.py get_graphql_schema > saleor/graphql/schema.graphql",
    "heroku-postbuild": "npm run build-emails",
    "build-emails": "mjml --config.beautify false -l skip \"templates/templated_email/source/*.mjml\" -o templates/templated_email/compiled"
    }

Thanks in advance

**Comment by maarcingebala** [comment]
If you're using `master`, refer to the pre-release version in the docs: https://docs.getsaleor.com/docs/next/getting-started/installation-macos/

By default, the docs refer to the latest release which is 2.9.0 where `build-assets` command was available.
