### ISSUE TITLE
Error while install requirements.txt to own machine

### ISSUE THREAD

**Issue by nhetlinna** [mirumee/saleor#5246]
### I'm a beginner here
I've cloned the project this project and try to run `pip install -r requirements.txt`. It normally works fine but recently it shows error 

> Collecting colorama; platform_system == "Windows"
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Installing collected packages: defusedxml, pillow, tinycss2, cssselect2, cairosvg, kombu, pytz, redis, celery, certifi, dj-database-url, dj-email-url, six, sqlparse, django, django-appconf, django-babel, django-bootstrap4, django-cache-url, django-countries, python-dateutil, ipaddress, urllib3, elasticsearch, elasticsearch-dsl, django-elasticsearch-dsl, django-filter, pyjwt, rx, promise, graphql-core, graphql-relay, graphene, singledispatch, graphene-django, django-graphql-jwt, django-impersonate, django-js-asset, mpmath, sympy, measurement, django-measurement, django-mptt, django-phonenumber-field, typing, prices, django-prices, django-prices-openexchangerates, jsonfield, django-prices-vatlayer, django-recaptcha, django-redis, django-render-block, markupsafe, jinja2, gprof2dot, pygments, django-silk, pyasn1, pyasn1-modules, rsa, google-auth, google-resumable-media, protobuf, googleapis-common-protos, google-api-core, google-cloud-core, google-cloud-storage, django-storages, django-templated-email, django-versatileimagefield, django-webpack-loader, draftjs-sanitizer, text-unidecode, faker, freezegun, google-i18n-address, google-measurement-protocol, graphene-django-optimizer, lxml, html-to-draftjs, markdown, maxminddb, maxminddb-geolite2, oauthlib, phonenumberslite, psycopg2-binary, purl, pyphen, python3-openid, razorpay, requests-oauthlib, sentry-sdk, social-auth-core, social-auth-app-django, soupsieve, stripe, weasyprint, colorama, qrcode, django-phone-field, phonenumbers
  Attempting uninstall: pillow
    Found existing installation: Pillow 7.0.0
    Uninstalling Pillow-7.0.0:
      Successfully uninstalled Pillow-7.0.0
    Running setup.py install for pillow ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\nhetl\desktop\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nhetl\\AppData\\Local\\Temp\\pip-install-rgn21xtm\\pillow\\setup.py'"'"'; __file__='"'"'C:\\Users\\nhetl\\AppData\\Local\\Temp\\pip-install-rgn21xtm\\pillow\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\nhetl\AppData\Local\Temp\pip-record-jvzpv4qu\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\nhetl\desktop\env\include\site\python3.8\pillow'
         cwd: C:\Users\nhetl\AppData\Local\Temp\pip-install-rgn21xtm\pillow\
    Complete output (178 lines):
    C:\Users\nhetl\AppData\Local\Temp\pip-install-rgn21xtm\pillow\setup.py:29: RuntimeWarning: Pillow does not yet support Python 3.8 and does not yet provide prebuilt Windows binaries. We do not recommend building from source on Windows.
      warnings.warn(
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\PIL
    copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\features.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\FontFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\Image.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\OleFileIO.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\TarIO.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\_binary.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\_util.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\_version.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\__init__.py -> build\lib.win-amd64-3.8\PIL
    running egg_info
    writing src\Pillow.egg-info\PKG-INFO
    writing dependency_links to src\Pillow.egg-info\dependency_links.txt
    writing top-level names to src\Pillow.egg-info\top_level.txt
    reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs\_static'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis\*'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
    running build_ext

    

> The headers or library files could not be found for zlib,
>     a required dependency when compiling Pillow from source.
> 
>     Please see the install instructions at:
>        https://pillow.readthedocs.io/en/latest/installation.html
> 
>     Traceback (most recent call last):
>       File "C:\Users\nhetl\AppData\Local\Temp\pip-install-rgn21xtm\pillow\setup.py", line 765, in <module>
>         setup(name=NAME,
>       File "c:\users\nhetl\desktop\env\lib\site-packages\setuptools\__init__.py", line 144, in setup
>         return distutils.core.setup(**attrs)
>       File "C:\Users\nhetl\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
>         dist.run_commands()
>       File "C:\Users\nhetl\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
>         self.run_command(cmd)
>       File "C:\Users\nhetl\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "c:\users\nhetl\desktop\env\lib\site-packages\setuptools\command\install.py", line 61, in run
>         return orig.install.run(self)
>       File "C:\Users\nhetl\AppData\Local\Programs\Python\Python38\lib\distutils\command\install.py", line 545, in run
>         self.run_command('build')
>       File "C:\Users\nhetl\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "C:\Users\nhetl\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "C:\Users\nhetl\AppData\Local\Programs\Python\Python38\lib\distutils\command\build.py", line 135, in run
>         self.run_command(cmd_name)
>       File "C:\Users\nhetl\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "C:\Users\nhetl\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "C:\Users\nhetl\AppData\Local\Programs\Python\Python38\lib\distutils\command\build_ext.py", line 340, in run
>         self.build_extensions()
>       File "C:\Users\nhetl\AppData\Local\Temp\pip-install-rgn21xtm\pillow\setup.py", line 612, in build_extensions
>         raise RequiredDependencyException(f)
>     __main__.RequiredDependencyException: zlib
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\nhetl\AppData\Local\Temp\pip-install-rgn21xtm\pillow\setup.py", line 812, in <module>
>         raise RequiredDependencyException(msg)
>     __main__.RequiredDependencyException:
> 
>     The headers or library files could not be found for zlib,
>     a required dependency when compiling Pillow from source.
> 
>     Please see the install instructions at:
>        https://pillow.readthedocs.io/en/latest/installation.html
> 
> 
>     ----------------------------------------
>   Rolling back uninstall of Pillow
>   Moving to c:\users\nhetl\desktop\env\lib\site-packages\pil\
>    from C:\Users\nhetl\Desktop\env\Lib\site-packages\~il
>   Moving to c:\users\nhetl\desktop\env\lib\site-packages\pillow-7.0.0.dist-info\
>    from C:\Users\nhetl\Desktop\env\Lib\site-packages\~illow-7.0.0.dist-info
> ERROR: Command errored out with exit status 1: 'c:\users\nhetl\desktop\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nhetl\\AppData\\Local\\Temp\\pip-install-rgn21xtm\\pillow\\setup.py'"'"'; __file__='"'"'C:\\Users\\nhetl\\AppData\\Local\\Temp\\pip-install-rgn21xtm\\pillow\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\nhetl\AppData\Local\Temp\pip-record-jvzpv4qu\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\nhetl\desktop\env\include\site\python3.8\pillow' Check the logs for full command output.

### Anyone please help me with this issue

**Comment by maarcingebala** [comment]
In the traceback you have:
```
__main__.RequiredDependencyException: zlib
```

Please check this Stackoverflow question and answers, it seems that you need to install some additional packages in your system: https://stackoverflow.com/questions/41188838/cant-install-pillow-in-windows
