### ISSUE TITLE
Populatedb fail when running second or next time

### ISSUE THREAD

**Issue by IKarbowiak** [mirumee/saleor#5247]
Populatedb shouldn't failed when it's run more than ones.

### Steps to reproduce the problem
1.  Run populateb
2. Run populatedb again

### Screenshots

![image](https://user-images.githubusercontent.com/40886528/74442049-1f341780-4e71-11ea-8506-492887413b53.png)

**Comment by krzysztofwolski** [comment]
Whats the expected result of running populatedb twice? Twice the products, groups, admin accounts? Or rather flush db and one solid fixtures pack?
