### ISSUE TITLE
302 Status in Shipping Method. 

### ISSUE THREAD

**Issue by iraycd** [mirumee/saleor#526]
**TD;LR** When I enter the "Shipping Address" entire as anonymous or create a new address. It makes me submit it again and again.

Using c79bdbb13c399b253e3a26480d01f1cb219b4700

I get this most annoying bug. I can't solve from days. It only happens in the production site, not on the test as well as development. I really don't understand where I am going wrong.

What should really happen `Shipping Address(302) -> Shipping Method(200)`

Problem:
`Shipping Address(302) -> Shipping Method(302) -> Shipping Address(200)`.
This mean the users has to submit the form again and again.

Cases when `Shipping Method(200)` 
+ 3 to 5 attempts of submitting the form.
+ 2 to 5 minutes of waiting to submit again.

I have even done an attempt using the `old checkout`, when the billing address was the first form, Still result is the same.

**Comment by patrys** [comment]
Are you using multiple processes to run the site? I would assume so as this makes the most sense.

Do you have Django cache configured? If not, it will default to local process memory which means each of the web worker processes has a private cache that is not shared between them. This leads to a situation where every worker process has its own version of the user's current session. It could mean that submitting the shipping address saves it to session in process #1 but when you get redirected to the next step, you are served by process #2 that does not have the address so it asks you to provide it. If you are really unlucky you could keep sending data to process #1 and then get handled by any of the other processes so you'd be stuck in an infinite loop.

If this sounds like the problem at hand, consider using Redis or memcached to allow user sessions to be shared between workers. Or you could change the session storage backend that Django uses to a purely database-driven one but it hurt the performance slightly.
