### ISSUE TITLE
Bad Request (400) When I am trying to deploy saleor in heroku with the deploy button in readme

### ISSUE THREAD

**Issue by ironexmaiden** [mirumee/saleor#5276]
### What I'm trying to achieve
To experiment with saleor

### Steps to reproduce the problem
1.Fork saleor
2. Press the button in the readme section of saleor (of my fork) which redirects you to heroku deployment
3. Deploy saleor

### What I expected to happen
Bad Request (400)

**Comment by karolkielecki** [comment]
Hey @ironexmaiden! Could you please send some screenshots?
