### ISSUE TITLE
hasPreviousPage on pageInfo always returns false

### ISSUE THREAD

**Issue by daltonsena** [mirumee/saleor#5285]
Hello!

I've been researching issues and pull requests and haven't found any reference to it. So I will send it here.

And as the field still in the documentation (https://docs.saleor.io/docs/next/api/pagination/) I think it is worth checking out.

### What I'm trying to achieve
I would like to use hasPreviousPage inside pageInfo to enabled/disable a previous pagination button.

### Steps to reproduce the problem

1. Run simple products fetch in API
2. Go to any page that supposedly has a previous page

### What I expected to happen

The hasPreviousPage holds a true boolean value

### Screenshots

1.
![Screen Shot 2020-02-21 at 00 24 02](https://user-images.githubusercontent.com/247386/75001600-9bfe5d00-5440-11ea-9a36-97e522a01b5a.png)

2.
![Screen Shot 2020-02-21 at 00 25 40](https://user-images.githubusercontent.com/247386/75001683-d831bd80-5440-11ea-8fce-55983a88f478.png)

Thanks!

If it’s a problem, I’d love to help if I’m able

**Comment by NyanKiyoshi** [comment]
cc. @kswiatek92

**Comment by kswiatek92** [comment]
As I understand from description, this bug occurs in every case
if that's true then this PR is fixing it #5149

**Comment by maarcingebala** [comment]
We've merged #5149. I've checked on `master` and it seems to be fixed now.
