### ISSUE TITLE
Store Information with shadow Required fields.

### ISSUE THREAD

**Issue by Ulisses1478** [mirumee/saleor#5307]
### What I'm trying to achieve
Put data in Store Information without Country Area

### Steps to reproduce the problem
1. Fresh Install
2. Try to put some data but not Country Area

### What I expected to happen
To work?

**System information**
Operating system: Linux

**Comment by maarcingebala** [comment]
Is this a problem in API only or in the dashboard app?

**Comment by Ulisses1478** [comment]
Oh probably it is on the saleor-dashboard. Closing the issue and opening there.
