### ISSUE TITLE
Multi categories parents

### ISSUE THREAD

**Issue by arnaudjnn** [mirumee/saleor#5308]
### What I'm trying to achieve

Men > Denim > Denim Jacket = Men > Jacket & Coat > Denim Jacket

### Describe a proposed solution

Improve categories taxonomy with multi parents.

Denim Jacket:
Parent 1: Denim 
Parent 2: Jacket & Coat

**Comment by karolkielecki** [comment]
Hey @ArnaudJeannin. Thanks for your suggestion! We're not planning to do that, at least not for now. If you would like to have multi categories parents, then you can try to use logic from the menu.
