### ISSUE TITLE
Any thought on using Preact instead of React

### ISSUE THREAD

**Issue by mobop** [mirumee/saleor#5309]
### What I'm trying to achieve
Getting rid off lib dependency which is made by Facebook and improve performance.

### Describe a proposed solution
Switch to React. It's not that hard

### Other solutions I've tried and won't work
Unless you stop using vdom

### Screenshots or mockups

`import Preact from "preact" `

**Comment by mateuszkula** [comment]
We dont have plans for switching to preact. We are not observing performance issues while using our frontend apps so far. Personally I dont see benefits of doing such switch but you are more then welcome to fork and test this ;)
