### ISSUE TITLE
Cookiecutter intergration?

### ISSUE THREAD

**Issue by awhillas** [mirumee/saleor#531]
Have you guys thought about integrating with [Cookiecutter](https://github.com/pydanny/cookiecutter-django)? It would remove a lot of your deployment support problems (i.e. with docker or Heroku) and make it super easy for people to setup and get started without the need for support.

**Comment by solvire** [comment]
I'm going to second this and put in my experience testing Oscar. I wasn't a fan overall of the Oscar architecture, but I used cookie cutter to deploy a vanilla setup that I use on many projects and then just add in the Oscar library.  They had some bugs, but I know the other setup well and it uses a lot of best-of-class utilities.  My notes: http://scotttactical.com/post/django-ecommerce-in-30-minutes/ 

Setup and abstraction is key to adoption. I can spin up a PHP app in seconds and be taking orders in hours.

**Comment by kiran-capoor94** [comment]
+1 to this idea. I really love Cookiecutter by pydanny. Would love to help here to separate the env varaibles and provide abstractions.

**Comment by maarcingebala** [comment]
We're not going to work on that in the nearest future. If anyone wants to contribute to Saleor on pick this issue, we can offer guidance.

**Comment by adrianvanlan** [comment]
django cookiecutter is a great tool to put into production and has a great way of organizing settings. Is this topic ruled out or could it be taken up again, at least to discuss it?
