### ISSUE TITLE
Is this project ready for polish market out of the box?

### ISSUE THREAD

**Issue by unixconky** [mirumee/saleor#5312]
Context: I would like to use this solution instead of WooCommerce or other PHP based system.

* Integration with PayU and/or other polish payment systems
* Integration with polish delivery companies (Inpost, DHL, DPD)
* I have no experience in e-commerce but something related to polish taxes may be needed

**Comment by karolkielecki** [comment]
Hello @unixconky! Thanks for asking. Currently, we do not have an official integration with PayU and other polish payment systems. We support the following payment gateways for now: https://docs.saleor.io/docs/integrations/payment-gateways/#docsNav

However, you can create your own plugin and integrate it with Saleor. The same goes for delivery companies. Our platform is headless, so you can integrate your favourite tools and solutions. 

You can find more details and tips about the plugins under the links below:
- https://docs.saleor.io/docs/next/dashboard/configuration/plugins/#docsNav
- https://docs.saleor.io/docs/advanced/extensions/#tips-on-writing-your-own-plugin

**Comment by KrallXZ** [comment]
Hey, anything changed about InPost pickups in 2022? @karolkielecki

**Comment by karolkielecki** [comment]
Hi @KrallXZ, Saleor doesn't support it. If you want a specific delivery method, such as InPost, you need to create an app. You can find more info here: https://docs.saleor.io/docs/3.x/developer/extending
