### ISSUE TITLE
Products cannot be updated (field: minimalVariantPriceAmount)

### ISSUE THREAD

**Issue by selmanceker** [mirumee/saleor#5313]
I am trying to update products and having the error below. 
I have tried on master including recent commits.

Can anyone help me to fix this?

Thanks

`{"data": {"productUpdate": {"errors": [{"field": "minimalVariantPriceAmount", "message": "\u062a\u062d\u0642\u0642 \u0645\u0646 \u0623\u0646 \u062a\u062f\u062e\u0644 0 \u062e\u0627\u0646\u0627\u062a \u0639\u0634\u0631\u064a\u0629 \u0644\u0627 \u0623\u0643\u062b\u0631.", "__typename": "Error"}], "product": null, "__typename": "ProductUpdate"}}}`

**Comment by maarcingebala** [comment]
@selmanceker Does this error happen in the dashboard app or are you calling some API operation directly in the GraphQL Playground? We would need more accurate information to recreate and confirm the issue.

**Comment by selmanceker** [comment]
Hi @maarcingebala,

It happened in the dashboard app. I haven't tried in the GraphQL playground. 

I ran dashboard app and backend with populated db on my local environment, after that I tried to update products and had the error.

**Comment by NyanKiyoshi** [comment]
Hi, @selmanceker could you provide us steps on how to reproduce?

**Comment by selmanceker** [comment]
Hi @NyanKiyoshi,

I recloned repos and tried the process but I could not have the error again. 
Thanks a lot for your time.

**Comment by demux** [comment]
I'm having this issue in both 2.10 (latest) and 2.11.0-rc.3. It's happening in the dashboard. I changed `DEFAULT_CURRENCY`  to ISK. My guess is it has something to do with that.
