### ISSUE TITLE
Retrieving long products list

### ISSUE THREAD

**Issue by PiotrLaszczyk** [mirumee/saleor#5317]
### What I'm trying to achieve
I have let say 101 products, and I want to collect all of them. 

### Steps to reproduce the problem
List of 3 products.. and 

query { products(first: 2) {...
then
query { products(first: 2 after: "correctIdOfSecondProduct") {...

and I receive response same as in first scenario, like 'after' would be always overlooked.

**Comment by maarcingebala** [comment]
For pagination, you need to use the `cursor` field, not the `id`. You can get the cursor with a query like this:
```
{
  products(first: 2) {
    edges {
      cursor
      node {
        id
        name
      }
    }
  }
}
```

**Comment by PiotrLaszczyk** [comment]
Yes! Thx!

This interface is little bit tricky and sometimes its hard to distinguish if its not implemented or I'm doing it in wrong way  ;)

**Comment by maarcingebala** [comment]
Pagination should work consistently across all top-level queries, you can also see it in action in our dashboard.
