### ISSUE TITLE
webpack-bundle.json Error

### ISSUE THREAD

**Issue by dave4jr** [mirumee/saleor#532]
Getting a webpack-bundle.json error. For some reason it's not being generated for me.

**Comment by patrys** [comment]
Which commands are you running? We've recently switched to webpack so the commands have changed slightly.

**Comment by dave4jr** [comment]
Just followed the commands on the docs. I tried to figure out the issue by looking at the django-webpack app so I could atleast offer a solution but couldn't figure it out in the time I had. I know how much work it is to keep a project up like this, so really appreciate you sharing it with all of us! Dying to see what it looks like. Also, In the docs it's says to run the grunt command for all the static assets but you switched to web pack, so there's a different command yeah? I'm not really familiar with webpack. Lastly, do you have a separate branch for stable releases vs actively developed ones or just kinda keep everything together? Thanks again man!!

Dave

**Comment by patrys** [comment]
Oh, sorry, we've moved the documentation to Read the Docs but the Wiki failed to mention that. You can see the current installation docs at http://saleor.readthedocs.io/en/latest/install.html

Saleor is meant to be forked so we don't currently offer stable branches however we do plan to start providing "releases" that are known to work (along with their matching documentation).
