### ISSUE TITLE
assign product types to sale or voucher

### ISSUE THREAD

**Issue by javadfarah** [mirumee/saleor#5324]
hi.
**sorry for my poor English**
i want to assign vouchers or sales to product type!
what should i do?
i think in saleor we should create a range and assign to the voucher.
range can inclouded product types , categories , collections ,....etc

**Comment by karolkielecki** [comment]
Hey @javadfarah! Thank you for your suggestion. It's not possible to assign product types to sales or vouchers. You can find more information about creating the vouchers here: https://docs.saleor.io/docs/dashboard/discounts/vouchers/#docsNav

If you have any questions, you can also reach us at Gitter or Spectrum:
https://gitter.im/mirumee/saleor
https://spectrum.chat/saleor

**Comment by javadfarah** [comment]
hi @karolkielecki thanks for your reply.
i solved my issue ! 
add new field to the sale model.
`types = models.ManyToManyField("product.ProductType", blank=True)`

and just eddited _fetch_products in utils.py:
```
    types = Sale.types.through.objects.filter(producttype_id__in=sale_pks).values_list(
        "sale_id", "producttype_id"
    )
    for sale_id , producttype_id in types:
        Products_ = Product.objects.filter(product_type__pk=producttype_id).values_list(
        "pk"
    )
        for pk in Products_:
            product_map[sale_id].add(pk[0])
```

if there is any problem and mistake or any security issue.please tell me:)
regards.
