### ISSUE TITLE
docker compose run error occurred

### ISSUE THREAD

**Issue by gatspy** [mirumee/saleor#533]
follow document deployment section
docker-compose run web python manage.py migrate
ERROR: Container command '/app/compose/entrypoint.sh' not found or does not exist.

**Comment by patrys** [comment]
Are you following the old Wiki or the new docs at [Read the Docs](https://saleor.readthedocs.io/en/latest/)?

**Comment by gatspy** [comment]
Thanks for your reply.
this issue has been resolved,It is caused by boot2docker ,please close issue.
[Mount a non /Users directory as a data volume on OS X #1826](https://github.com/docker/machine/issues/1826)
[Mount Windows folder to Boot2Docker VM](http://tuhrig.de/mount-windows-folder-to-boot2docker-vm/)

**Comment by gatspy** [comment]
Aha,run docker-compose , see the test page , very beautiful!
