### ISSUE TITLE
This value is not valid for the address.

### ISSUE THREAD

**Issue by appleyuchi** [mirumee/saleor#5331]
![湖北升分](https://user-images.githubusercontent.com/27613483/76187722-0f5de800-6211-11ea-8fcb-0cd58c8fcb99.png)

It's very hard to add new address if your country is China

**Comment by maarcingebala** [comment]
We use Google's i18n address metadata repository for address validations. I'm not sure why it's not passing in your case, are you sure the zip code is sure for the given state and city?

**Comment by NyanKiyoshi** [comment]
The province is 湖北省 and the city is 武汉市.

**Comment by NyanKiyoshi** [comment]
For now I flag as support, let us know.

**Comment by appleyuchi** [comment]
I have solved according your guide.Much Thanks
