### ISSUE TITLE
no button to pay for an order

### ISSUE THREAD

**Issue by appleyuchi** [mirumee/saleor#5333]
### What I'm trying to achieve
…
I want to test saleor in the stage
"pay for the order"
### Steps to reproduce the problem
1. login
2. customer order and administrator full
3.try to find the "pay/charge" button

### What I expected to happen
…

### Screenshots

![没有支付按钮](https://user-images.githubusercontent.com/27613483/76191656-d32f8500-621a-11ea-8ab3-7c8563d39fc2.png)

**System information**
Operating system:
Ubuntu19.10
Chrome

**Comment by maarcingebala** [comment]
In Saleor you can only pay during the checkout to create an order. I see that you have an existing order - was it created in the checkout or by admin in the dashboard? What is exactly your use-case?

**Comment by appleyuchi** [comment]
Thanks for your replies @maarcingebala 
it is created in the checkout.
I guess it's my fault
![没有支付选项](https://user-images.githubusercontent.com/27613483/76274419-9ebfd580-62bb-11ea-98b4-b3c179f807e6.png)

**Comment by appleyuchi** [comment]
@maarcingebala 
I have configure saleor's settings.py according to 
https://github.com/mirumee/saleor/issues/2467
but the webpage is still "dummy"
Do I need to change the webpage's code and relevant views.py?
Thanks for your help

**Comment by maarcingebala** [comment]
To enable other gateways such as Braintree or Stripe you need to go to the dashboard app and provide configurations keys like API keys etc, see this manual page: https://docs.saleor.io/docs/next/dashboard/configuration/plugins/

To test one of these gateways you need to have sandbox accounts, create API keys and set them in our dashboard. See for example:
- https://www.braintreepayments.com/sandbox

**Comment by appleyuchi** [comment]
> To enable other gateways such as Braintree or Stripe you need to go to the dashboard app and provide configurations keys like API keys etc, see this manual page: https://docs.saleor.io/docs/next/dashboard/configuration/plugins/
> 
> To test one of these gateways you need to have sandbox accounts, create API keys and set them in our dashboard. See for example:
> 
> * https://www.braintreepayments.com/sandbox

Thanks for your replies.
I have already gone to the step of "place order" and the order then become "fully charged"
with sand-box braintree.

But I did not even input `my sandbox-account password` for payment,then the order become "full charged".
I remember that paypal sdk will require you to input password when you pay for something using sandbox-account,
but braintree did not require me to input password,

**Comment by maarcingebala** [comment]
You mean like manually typing a password when paying for a checkout? I haven't seen that but I'm only familiar with Braintree and Stripe. In these gateways, you only provide your API keys in the dashboard to activate them. Sometimes a client library needs a token to process the payment in the frontend, but it all depends on the gateway. To fetch any additional keys that may be needed use this query:

```
checkout {
      availablePaymentGateways {
        name
        config {
          field
          value
        }
      }
    }
```

If there is any additional key needed for the client library it would be returned in the `config` field.See this guide for more details: https://docs.saleor.io/docs/next/api-process/check-out/

**Comment by appleyuchi** [comment]
@maarcingebala Thanks for your kind-hearted replies,
It's very clear.
