### ISSUE TITLE
Stock.DoesnotExist on product creating

### ISSUE THREAD

**Issue by itzmanish** [mirumee/saleor#5346]
### What I'm trying to achieve
I am trying to add products with 1 SKU an 1 Inventory. I got error Stock.DoesnotExist but i make inventory 0 I don't get any error.

### Steps to reproduce the problem
1. Freshly installed saleor on AWS EC2 .
2. Connected with saleor dashboard and created shipping zones.

### What I expected to happen
Product should add successfully on inventory with stocks.

### Screenshots
[https://hastebin.com/tesecufeko.sql](https://hastebin.com/tesecufeko.sql)

**System information**
Operating system:
Ubuntu 18.04 LTS
AWS EC2

**Comment by karolkielecki** [comment]
@itzmanish Hi there! Thanks for reporting. We're aware that there are some issues with stocks in the dashboard. Are you using Saleor 2.9.1 or the master branch?

**Comment by itzmanish** [comment]
@karolkielecki  I am using master branch.

**Comment by itzmanish** [comment]
@karolkielecki I need an ecommerce setup urgently so if there is any stable branch available that I can use with dashboard and storefront will be much appreciated.

**Comment by karolkielecki** [comment]
The latest stable combination is:
https://github.com/mirumee/saleor/releases/tag/2.9.1
https://github.com/mirumee/saleor-storefront/releases/tag/v0.7.0
https://github.com/mirumee/saleor-dashboard/releases/tag/v2.0.0

I'm not sure when exactly the issues with stocks will be fixed. If I have any news, I will let you know. 
Best,

**Comment by Boquete** [comment]
As far as I know - when creating new Product when you don't specify / change default Inventory / Stock quantity it will not create Stock object.
But after changing quantity for any other then default (0) stock object will be created.

**Comment by itzmanish** [comment]
@Boquete That's exactly when error occurs. Also there are problem with storefront as it is not compiling on v0.7.0

**Comment by maarcingebala** [comment]
Should be fixed after we merge https://github.com/mirumee/saleor-dashboard/pull/390

**Comment by maarcingebala** [comment]
Closing as we already have #5180
