### ISSUE TITLE
a lot of sockjs-node/info?XXXXX

### ISSUE THREAD

**Issue by appleyuchi** [mirumee/saleor#5347]
### What I'm trying to achieve
…
I want to fix 404 in F12 when in production mode

### Steps to reproduce the problem
1. run saleor,saleor-dashboard and saleor-storefront
2. a lot of sockjs-node/info?XXXXX
I think I need to modify webpack.config.js in saleor-storefront.
but I' m weak in nodejs,
could anyone help me?
Thanks

### What I expected to happen
…

### Screenshots

![问题啊](https://user-images.githubusercontent.com/27613483/76497839-b7c0b600-6476-11ea-9358-5ae7a0744dd7.png)

the consoles of webpage is:
![页面报错](https://user-images.githubusercontent.com/27613483/76497913-dcb52900-6476-11ea-9add-a5cd4d9fca64.png)

**System information**
Operating system:
Ubuntu 19.10

**Comment by dominik-zeglen** [comment]
It's because you served storefront using webpacks development server and stopped it, so the storefronts application cannot connect to it.
