### ISSUE TITLE
where's the static files with suffix "G28OW5"?

### ISSUE THREAD

**Issue by appleyuchi** [mirumee/saleor#5358]
### What I'm trying to achieve
…

### Steps to reproduce the problem
1. VPS saleor-dashboard deployment
2. find errors in terminal of saloer(graphQL)

FileNotFoundError: [Errno 2] No such file or directory: '/root/saleor_docker/saleor/media/products/saleordemoproduct_cl_boot07_1_DlbVcl0.png'
FileNotFoundError: [Errno 2] No such file or directory: '/root/saleor_docker/saleor/media/products/saleordemoproduct_cl_boot07_1_DlbVcl0.png'
FileNotFoundError: [Errno 2] No such file or directory: '/root/saleor_docker/saleor/media/products/saleordemoproduct_paints_01_qApwUFq.png'
FileNotFoundError: [Errno 2] No such file or directory: '/root/saleor_docker/saleor/media/products/saleordemoproduct_paints_01_qApwUFq.png'
FileNotFoundError: [Errno 2] No such file or directory: '/root/saleor_docker/saleor/media/products/saleordemoproduct_cl_boot06_1_ansQhtr.png'
FileNotFoundError: [Errno 2] No such file or directory: '/root/saleor_docker/saleor/media/products/saleordemoproduct_cl_boot06_1_ansQhtr.png'
FileNotFoundError: [Errno 2] No such file or directory: '/root/saleor_docker/saleor/media/products/saleordemoproduct_fd_juice_06_aZNudCG.png'
FileNotFoundError: [Errno 2] No such file or directory: '/root/saleor_docker/saleor/media/products/saleordemoproduct_fd_juice_06_aZNudCG.png'
FileNotFoundError: [Errno 2] No such file or directory: '/root/saleor_docker/saleor/media/products/saleordemoproduct_cl_polo01_jG28OW5.png'
FileNotFoundError: [Errno 2] No such file or directory: '/root/saleor_docker/saleor/media/products/saleordemoproduct_cl_polo01_jG28OW5.png'

when I use violent search,I get:

# find ./ -name  "*saleordemoproduct_cl*"
./saleor/static/placeholders/saleordemoproduct_cl_boot01_1.png
./saleor/static/placeholders/saleordemoproduct_cl_boot01_2.png
./saleor/static/placeholders/saleordemoproduct_cl_boot07_1.png
./saleor/static/placeholders/saleordemoproduct_cl_bogo03_1.png
./saleor/static/placeholders/saleordemoproduct_cl_bogo04_2.png
./saleor/static/placeholders/saleordemoproduct_cl_polo03-woman.png
./saleor/static/placeholders/saleordemoproduct_cl_boot06_2.png
./saleor/static/placeholders/saleordemoproduct_cl_bogo02_1.png
./saleor/static/placeholders/saleordemoproduct_cl_polo01.png
./saleor/static/placeholders/saleordemoproduct_cl_boot03_1.png
./saleor/static/placeholders/saleordemoproduct_cl_bogo01_1.png
./saleor/static/placeholders/saleordemoproduct_cl_polo02.png
./saleor/static/placeholders/saleordemoproduct_cl_boot06_1.png
./saleor/static/placeholders/saleordemoproduct_cl_polo04-woman.png
./saleor/static/placeholders/saleordemoproduct_cl_boot01_3.png
./saleor/static/placeholders/saleordemoproduct_cl_boot07_2.png
./saleor/static/placeholders/saleordemoproduct_cl_boot03_2.png
./saleor/static/placeholders/saleordemoproduct_cl_bogo04_1.png

My static files have no suffix such as “G28OW5”，
Could you tell me where am I wrong?

Thanks for your help~!!!

Operating system: 
ubuntu18.04
Browser:
chrome

**Comment by karolkielecki** [comment]
@appleyuchi Hey! Can you tell us which version of Saleor are you using? Did you build the backend? Did you run python manage.py collectstatic?

**Comment by appleyuchi** [comment]
> @appleyuchi Hey! Can you tell us which version of Saleor are you using? Did you build the backend? Did you run python manage.py collectstatic?

#----------------------------------------------------------------------------------------
The reason why I did not use the stable version of saleor-storefront is that:
I have a same error as follows:
https://github.com/mirumee/saleor-storefront/issues/570

**Comment by karolkielecki** [comment]
I'm not sure what is Violent search. You should run python manage.py collectstatic.

**Comment by appleyuchi** [comment]
> I'm not sure what is Violent search. You should run python manage.py collectstatic.

sorry that I did not talk about it exactly.
I mean I searach all the file in the repository with the keyword "saleordemoproduct_cl"

**Comment by karolkielecki** [comment]
I think the best solution in your case is to build Saleor from the beginning:
- download repo
- install requirements
- create database 
- run python manage.py migrate, python manage.py collectstatic, python manage.py populatedb --createsuperuser

Please also follow our official docs and readme sections from each repo. 
https://docs.saleor.io/docs/
https://github.com/mirumee/saleor#installation
https://github.com/mirumee/saleor-storefront#getting-started
https://github.com/mirumee/saleor-dashboard#prerequisites
