### ISSUE TITLE
Page bulk mutations should be able to return BulkPageError

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#5359]
### What I'm trying to achieve
To format error messages in the client app.

### Describe proposed solution
```
type PageBulkDelete {
  errors: [Error!]!
  count: Int!
  pageErrors: [BulkPageError!]!
}

type PageBulkPublish {
  errors: [Error!]!
  count: Int!
  pageErrors: [BulkPageError!]!
}

type BulkPageError {
  field: String
  message: String
  code: PageErrorCode!
  index: Int
}
```

**Comment by maarcingebala** [comment]
For now, I've added `pageErrors: [PageError]` field as in most bulk mutations. There is no `index` field yet, as to add it we need to refactor all bulk mutations and I'd do that separately.
