### ISSUE TITLE
Meeting notes, 2nd August 2016

### ISSUE THREAD

**Issue by mirekm** [mirumee/saleor#536]
Saleor **for developers** (unsorted)
- Simple models and structure
- Dockerized
- Well-defined workflow
- Documentation
- Versioning (even if forkable by principle)
- Good internal API / Pluggable: Checkout, Product Form, …
- Customizable Dashboard (responsive, Material design)
- REST API
- Performance
- Tests workflow

Saleor **for easy deployment / out of the box use** (unsorted)
- EAV but we need a common API with non-EAV models (generator as a possible solution) 
- Good configuration options available from the Dashboard: payments, …
- Easy onboarding
- Customisation (themes) & branding (possibly themes marketplace, requires versioning)
### Changes required based on the latest commercial project (unsorted):
- [x] Simplify Delivery Groups handling (remove from Cart, rethink statuses and workflow in Dashboard)
- [x] Carts no longer in session - Issue #468
- [x] Cart requires better API (items, variants)
- [ ] Dropping CBV
- [x] Search API (Haystack)
- [ ] Dropping Satchless API
- [ ] Switching Payments to Decimals 
- [ ] Use Payment model for order creation
- [ ] No order creation on checkout
- [x] Integration with Google Merchant
- [ ] Rethink Categories and Taxonomies 
- [ ] Documentation
  - [ ] High level overview of architecture
  - [ ] Design your first Product (Model, Product Form)

**Comment by mirekm** [comment]
### Sprints proposal:

1. Cart related issues
* Cart no longer in session
* Simnplify delivery groups handling
* API update for items and variants

2. Categories and taxonomies
* Split into main category and additional taxonomies
* Integration with Google Merchant

3. Drop obsolete dependencies
* Dropping Satchless API
* Move `get_price_per_item` to helper (with rounding support)
* Dropping Class-based views
* Dropping `weight` from products

4. Payments
* Merge summary step with payments
* Create order model on payment success
* Create order from payment

5. Better payments integration (requires Payments sprint first)
* Use Payment model for order creation

6. Dashboard upgrade (TBD)
* Rethink how we extend dashboard

**Comment by patrys** [comment]
Closing this in favor of our [roadmap](https://github.com/mirumee/saleor/wiki/Roadmap)
