### ISSUE TITLE
Shipping fee based on number of items

### ISSUE THREAD

**Issue by selmanceker** [mirumee/saleor#5364]
### What I'm trying to achieve
I am trying to establish an e-commerce structure that receives a fixed shipping fee for each product. (one product, x shipping price; there products 3x shipping price) 

### Describe a proposed solution
Is it possible to add a shipping method that defines the default shipping weight unit as a unit and receives a shipping fee based on the number of products in the cart?

or what problems can I face if I use KG as a unit?

### Other solutions I've tried and won't work
I tried to use KG as a unit. One product 1 KG. In this case, each KG interval needs to be defined separately (At least 10-15 weight based rates). When I try this structure with a product, it shows the next shipping method with the right selection at the shipping selection stage.

**Comment by karolkielecki** [comment]
Hi @selmanceker. Thanks for pointing this out. You can only manage the shipping fees like it's written in our docs: https://docs.saleor.io/docs/dashboard/configuration/shipping/#docsNav

I'll pass your suggestion to the team. If there are any changes regarding shipping methods, I'll let you know.
