### ISSUE TITLE
Store Credit or Account Balance for Customers

### ISSUE THREAD

**Issue by oaksakal** [mirumee/saleor#5365]
### What I'm trying to achieve

I would like to add ability to store account balance for customers buy buying credits. or storing refunds.

### Describe a proposed solution

I thought of creating "vouchers" as products but storing adjusted balances is very complex.

Has anyone requested this feature before? Or is there a solution you can recommend me?

Thank you!

**Comment by karolkielecki** [comment]
Hello @oaksakal. Thank you for your suggestion. Unfortunately, there is no such feature in Saleor. I'll pass your idea to the team and we'll discuss it. Thanks!

**Comment by dawidjk** [comment]
Hello, have there been any thought about this? We'd love to use Saleor at `interviewing.io` but this is a feature that would make or break our choice. Apologies for bringing an old issue back to life!

**Comment by mehdiirh** [comment]
Hi, we need this feature in our startup platform, too. are there any updates about this?

We would greatly appreciate any information.

**Comment by kimus** [comment]
I'm also interested in the same thing. In our current platform we can do normal payments or pay with the customer balance that he could manually add new funds or by refunds.
