### ISSUE TITLE
After adding item to cart, initial cart empty, refresh page shows item added.

### ISSUE THREAD

**Issue by stedotmartin** [mirumee/saleor#537]
Hi, first thanks for a great product.

I have a problem with my store. I have just set it all up and honestly had to learn a lot of things to get it all going so I am hoping its something easy.

I have my store setup on Ubuntu 16.04 + NGINX + uwsgi and when I add an item to my cart the page redirects to /cart/ to show an empty cart, however if I refresh the page I see the item in the cart. I have this running locally on my macbook + pycharm and it works fine but in aws it seems to do this. I'm guessing this may be due to the fact i'm using NGINX + uwsgi in aws.

I'm using sqlite in both dev and prod.

Any thoughts?

Thanks.

**Comment by patrys** [comment]
I am guessing that you are running more than one web process and you don't use a shared cache server such as Redis. You should be getting a big warning in the console that sessions won't work properly for a setting like that as the fallback cache is in-memory and per-process.

**Comment by stedotmartin** [comment]
@patrys That was it, I dialled the uwsgi server down to one process and its working as expected. Will look into Redis thanks for the quick response much appreciated.
