### ISSUE TITLE
Updating Payment Status

### ISSUE THREAD

**Issue by srendon** [mirumee/saleor#5371]
Hi Saleor team. I’m implementing my own payment gateway. This gateway uses redirection so I was wondering how the payment status should be updated, from the back-end,  when I have a response.

**Comment by karolkielecki** [comment]
Hello @srendon. You can implement webhooks in this case. You can find more details here: https://docs.saleor.io/docs/dashboard/configuration/webhooks/#docsNav

If you have any questions, don't hesitate to let us know.

**Comment by srendon** [comment]
Hi @karolkielecki I don’t need to send a webhook to my payment gateway. I’ll receive a request from them and then I need to update if the payment was successful or not. My question is how you recommend me to update such information so a mail can be sent if the purchase was successful or not.

**Comment by karolkielecki** [comment]
Hey! We're working on the flow like this below, but it's not available yet: https://github.com/mirumee/saleor/issues/4955

**Comment by srendon** [comment]
Hey @karolkielecki ! That’s awesome. I’ll be aware of when that feature will be added. For now, I added my own view for my gateway requests. I have something like this: 
```
        if request.get('status').get('status') == 'APPROVED':
            payment = Payment.objects.get(token=request.get('token'))
            payment.charge_status = ChargeStatus.FULLY_CHARGED
            payment.save()
        elif request.get('status').get('status') == 'REJECTED':
            payment = Payment.objects.get(token=request.get('token'))
            payment.charge_status = ChargeStatus.NOT_CHARGED
            payment.save()
```

Do you recommend doing it like that? If I do it like that the confirmation email will be send automatically or I have to something else? 
Thank you for your patience.
