### ISSUE TITLE
Old non-React front is deprecated? 

### ISSUE THREAD

**Issue by wardal** [mirumee/saleor#5373]
Hey guys. Actually it's not a bug report, but just a question, where I can't set support label and didn't find any info.

I didn't find any news or press release about deprecating old front interface with this pirate in the cart.
We have pwa demo url and all old links I found is redirected to pwa also. So PWA is a default now or I have possibility to use an old interface?

Thanks

**Comment by NyanKiyoshi** [comment]
Hi! We can the django views at https://github.com/mirumee/legacy-views, if you need support about it, that's the place! But that is no longer actively maintained.
