### ISSUE TITLE
Adding Cash On Delivery

### ISSUE THREAD

**Issue by abdul-elah-js** [mirumee/saleor#5375]
I'm sorry I couldn't find a better way to ask this question, I'm totally new to Django and I have no idea how could I add a new payment method, I've read the documentation but it explained only the payment gateways services and how to integrate with them, I want to add `cash_on_delivery` to my project, how I might be able to do that ?

Thanks in advance for the help.

**Comment by karolkielecki** [comment]
Hello @abdul-elah-js. Thanks for asking. In this case, you can consider creating a plugin. You can find some useful info here: https://docs.saleor.io/docs/advanced/extensions/#tips-on-writing-your-own-plugin

If you have any questions, just let us know :)

**Comment by abdul-elah-js** [comment]
The problem is I've never used `django`, but I tried to install this plugin I found on the web [django-payments-cod](https://github.com/xtranophilist/django-payments-cod)  but I keep getting this error `ModuleNotFoundError: No module named 'payments'`, any solution out there someone might've tried ? please help on these as I'm running out of time. Thanks in advance @karolkielecki

**Comment by Dihfahsih1** [comment]
after installing the package django-payments-cod, i hope you added it to your installed apps in settings.py file of your project
