### ISSUE TITLE
List ordres for authenticated customer

### ISSUE THREAD

**Issue by tboulogne** [mirumee/saleor#5385]
### What I'm trying to achieve
Listing ordres with graphql for an authenticated customer

### query  + add customer token into headers
```
query{
  me{
    email
    checkout{
      totalPrice{
        gross{
          amount
        }
      }
    }
    orders(first: 100){
      totalCount
      edges{
        node{
          billingAddress{
            firstName
          }
        }
      }
    }
  }
}
```
### What I expected to happen
Retrieving orders.

I just retrieve the customer email. Did i miss something ?

Thanks for help.

Regards

**Comment by maarcingebala** [comment]
I'm not sure what's the problem. This query fetches three things:
- user's email,
- checkout (if there is any open checkout; an authenticated user can have only one open checkout
- user's orders
Are you sure that this user has any orders?

**Comment by tboulogne** [comment]
Yes user has orders.

Thierry BOULOGNE
06 43 18 31 19

**Comment by tboulogne** [comment]
@maarcingebala i got it !
As user account validate after order confirmation, order not affect to user (user_id empty).
suggestion : make an automatic matching of orders after account validation based on email :-)

Thanks for all
