### ISSUE TITLE
Email language in french

### ISSUE THREAD

**Issue by tboulogne** [mirumee/saleor#5388]
### What I'm trying to achieve
Have email in french

### my supervision conf
```
[program:shop]
environment=
        DEBUG="1";
        DJANGO_SETTINGS_MODULE=saleor.local_settings;
        SECRET_KEY=xxxxx;
        VATLAYER_ACCESS_KEY=xxxxx;
        DEFAULT_COUNTRY=FR;
        DEFAULT_CURRENCY=EUR;
```

### local_settings.py
```
LANGUAGE_CODE = "fr"
LANGUAGES = [
    ('fr', _("French"))
]
```

Mail stay in english. Did i miss something ?

Thanks for help.

Regards,

**Comment by tboulogne** [comment]
got it work

**Comment by tlosbar** [comment]
@tboulogne I have the same issue, please could you tell me how did you fix this?

**Comment by tboulogne** [comment]
@tlosbar (from FWI, Petit-bourg  ?) c'est vieux :-). 

Je pense que l'emplacement du fichier local_settings.py joue. Nnon pas à la racine de saleor, mais dans le dossier saleor.

Ensuite, plutôt :
```
LANGUAGE_CODE = "fr"
LANGUAGES = [
    ('fr', "French")
]
```

Que 

```
LANGUAGE_CODE = "fr"
LANGUAGES = [
    ('fr', _("French"))
]
```

Voilà.

**Comment by tlosbar** [comment]
Merci beaucoup.

Désolé je répond tardivement. Ça a marché :)

Oui. Je suis de Petit bourg. Et toi ?
