### ISSUE TITLE
Make it clear that cart operates on variants, not products

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#539]
The underlying `satchless` Cart class is a container of CartLines that in turn reference products. In Saleor's case a Product is just a collection of Variants.

* [x] change the field names to correctly reflect what they reference
* [ ] possibly stop extending the `satchless` classes in our cart implementation if they make it harder to implement the above (we are aiming to eventually drop Satchless in a separate milestone)
* [x] make sure existing test cases are relevant
* [ ] make sure cart has full unit test coverage

**Comment by kuba777** [comment]
I'm not sure if this is included in the list but I would like to suggest that variant pictures should be used in cart if they are available.

**Comment by patrys** [comment]
I'll open a separate ticket for displaying proper images in carts and mark this one as closed.
