### ISSUE TITLE
Match orders with new customer accounts

### ISSUE THREAD

**Issue by tboulogne** [mirumee/saleor#5398]
### What I'm trying to achieve
> Affect order to customer.

Case: 
Customer create an account and validité this account only after passing and order.
Order is not affect to this customer (**user_id** empty in **order_order** table)

### Describe a proposed solution
Modify mutation **orderUdapte** and add into **OrderUpdateInput**, **user_id field**.

Thanks

**Comment by maarcingebala** [comment]
Hey, correct me if I'm wrong - you want to be able to match existing orders with a user account? 

Example case - as a customer I placed an order with email "customer@example.com" (but I don't have any account in Saleor). Later I created an account for email "customer@example.com" and I don't see the order that I placed in the past. You want to be able to update the old order to match it with my new account?

**Comment by tboulogne** [comment]
Yes !!! :-)

Thierry BOULOGNE
06 43 18 31 19

**Comment by maarcingebala** [comment]
OK, so I think this should happen automatically when you create a new account. We used to have it in the "old" Saleor (in Django views) and should be added to the API as well.

**Comment by maarcingebala** [comment]
I mean we don't need a special mutation for that, instead, the mutation to create a new account (or confirm it, if there is email confirmation enabled) should look for orders with the email the account was created for and match it.

**Comment by tboulogne** [comment]
@maarcingebala on Account activation could be great.

**Comment by maarcingebala** [comment]
OK, I'll add it to our backlog and we'll try to take this issue as soon as we can.

**Comment by tboulogne** [comment]
thanks

**Comment by maarcingebala** [comment]
So I suggest that we add a function that looks for orders for the given email address and matches them with a new user. This function would be used in API mutations:
- `accountRegister` mutation - when email confirmation for new accounts is disabled 
- `confirmAccount` - when it's enabled.

Corner cases to consider:
- user can change the email address once the account is active - should we also match orders in this case?

**Comment by tboulogne** [comment]
Regarding the corner case... email should be link to an activation.
It's mean,  that user need to activate (confirm) he is the owner of the email. Don't know how saleor manage this...

So no match on email change, only on activation :-).
