### ISSUE TITLE
AWS elastic beanstalk deploy

### ISSUE THREAD

**Issue by Aisha-Barahim** [mirumee/saleor#5401]
Hi, 

I am facing trouble while I am deploying the project in AWS EBS. Here is the log screenshot. I followed the windows installation from ur docs and the zipped the project and deploy it in a Docker container.

![image](https://user-images.githubusercontent.com/61520246/77833730-989d7600-7150-11ea-88fc-c51c06bdc811.png)

**Comment by karolkielecki** [comment]
Hey @Aisha-Barahim. You can find more details on how to deploy a docker container on Amazon EBS here: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker.container.console.html

Good luck!
