### ISSUE TITLE
Unable to search in warehouses query without id

### ISSUE THREAD

**Issue by fowczarek** [mirumee/saleor#5410]
### What I'm trying to achieve
I want to filter through warehouses by name.
When I do 
```
{
  warehouses(first: 10, filter: {search: "as"}) {
    edges {
      node {
        name
      }
    }
  }
}
```
Response is:  `"message": "Field Warehouse.address cannot be both deferred and traversed using select_related at the same time.",`

If I add `id` to requested field query working.
```
{
  warehouses(first: 10, filter: {search: "as"}) {
    edges {
      node {
        id
        name
      }
    }
  }
}
```

**Comment by fowczarek** [comment]
After we fix it we should remove `id` from `QUERY_WAREHOUSES_PAGINATION`
in `saleor/tests/api/pagination/test_warehouse.py `

**Comment by koradon** [comment]
@fowczarek done

**Comment by koradon** [comment]
Fixed, closing
