### ISSUE TITLE
Allow to update/delete multiple metadata items at once

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#5417]
### What I'm trying to achieve
I'm trying to update/delete multiple metadata items. With the current implementation, I need to send multiple mutations, while I could just have one that updates/deletes multiple keys at once e.g. by passing input like `input: [{key: "key-a", value: "a"}, {key: "key-b", value: "b"}]`

### Describe a proposed solution
- [ ] change the signature of `updateMetadata` mutation to:
```
updateMetadata(id: ID!, input: [MetadataInput!]!): UpdateMetadata
```
- [ ] change `updatePrivateMetadata` accordingly

- [ ] change the signature of `deleteMetadata` to:
```
deleteMetadata(id: ID!, keys: [String!]!): DeleteMetadata
```
- [ ] change `deletePrivateMetadata` accordingly

**Comment by koradon** [comment]
@maarcingebala in `test_meta_mutations` we have tests for a single meta item for every model (User, Product, Order, etc). Do we want to have tests with multiple updated/deleted items for every model also?

**Comment by maarcingebala** [comment]
I think it's fine if we refactor them to use lists with one element, but there need to be some tests that actually check that the logic works for more than one as well.
