### ISSUE TITLE
Having trouble with the media URL'S in the backend

### ISSUE THREAD

**Issue by consultantsdei** [mirumee/saleor#5419]
Hello, 
Im having trouble setting up a proxy with nginx to run in the backend, but when it creates the URL's from media, its taking the proxy adress instead of the public IP of the service. Is there any way to change creation of these URL's to force  it to use a static ip?
![image](https://user-images.githubusercontent.com/58126707/78089563-d3442000-7395-11ea-8dba-2f969d586a74.png)

**Comment by makl11** [comment]
Hey there,
I had the same problem just today and managed to resolve it by adding `proxy_set_header Host $http_host;` in the proxies location section of my nginx configuration.
I hope this helps you too!
