### ISSUE TITLE
Running "npm run build-assets" results in error on Windows 10

### ISSUE THREAD

**Issue by wkk5** [mirumee/saleor#542]
Getting error when trying to build-assets with npm:

npm ERR! Failed at the saleor@0.0.0 build-assets script 'UV_THREADPOOL_SIZE=8 webpack -p --progress'.
npm ERR! This is most likely a problem with the saleor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     UV_THREADPOOL_SIZE=8 webpack -p --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs saleor

[npm-debug.txt](https://github.com/mirumee/saleor/files/417704/npm-debug.txt)

**Comment by patrys** [comment]
This assumes you have webpack installed and available somewhere on your %PATH%.

**Comment by wkk5** [comment]
Okay, thanks!  I just ran webpack directly to bundle, and this fixed the problem...
