### ISSUE TITLE
attaching price range shipping to manager

### ISSUE THREAD

**Issue by weestack** [mirumee/saleor#5422]
In the latest master, under the path saleor/checkout/utils.py on line 493.

it's stated that 

> # TODO: extension manager should be able to have impact on shipping price estimates
I would like to suggest that this gets added, as both myself and #5115, #5001 need's this exact feature. Other than personal interest, I believe it would be a great addition to saleor to add this feature to the manager, so one does not have change the core code, but can settle on creating a plugin instead, which ultimately would make it easier to update saleor between stable releases.

**Comment by korycins** [comment]
Hi @weestack,
We are planning to convert shipping to the plugin architecture. Same as we did with the payment. During this process, we will extend the possibility to customize shipping methods.
We are going to analyze and discover the best approach for this in future days. I hope it will be introduced in the next release after 2.10
