### ISSUE TITLE
Google Analytics isn't working

### ISSUE THREAD

**Issue by Krystex** [mirumee/saleor#5428]
### What I'm trying to achieve
Getting Google Analytics to work

### Steps to reproduce the problem
1. Set the environment variable **GOOGLE_ANALYTICS_TRACKING_ID**.
2. Start Saleor

### What I expected to happen
Statistics should be sent to Google Analytics. However when I go to the Analytics Dashboard, no data got collected.

### Screenshots

<img width="668" alt="image" src="https://user-images.githubusercontent.com/5840423/78455105-adbc5c80-769c-11ea-9cf4-b72afa8c7544.png">

**System information**
Operating system: Docker, Ubuntu Server

**Comment by Pyrross** [comment]
I have also encountered problems with the Analytics integration as it only showed GraphQL API traffic.

**Comment by karolkielecki** [comment]
@Krystex Hi there! Please use chrome plugins to debug the code. Then check if Google Analytics script connects to your web. Can you also tell us how do you run the code?

**Comment by Krystex** [comment]
Hi @karolkielecki :) From my understanding, google analytics are implemented server-side and therefore no analytics are sent via the browser. So when I'm debugging the client-side code with chrome I shouldn't see anything. 
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/5840423/78563483-51cc1200-781b-11ea-8cd5-c692db93b147.png">
The chrome console of course has no output or error messages.
Which chrome plugins do you mean exactly?

I run the application with Docker (build by the bundled Dockerfile).

**Comment by karolkielecki** [comment]
@Krystex Currently, the storefront doesn't have an integration with Google Analytics. We aim to deliver a full integration with Google Enhanced Ecommerce. If I have any news, I'll keep you updated.
