### ISSUE TITLE
Heroku Deployment Error

### ISSUE THREAD

**Issue by raymondfx** [mirumee/saleor#5436]
I tried deploying to Heroku, the build succeeds well, but when I open the app it directs me to GraphQl end points 
<img width="1257" alt="Screenshot 2020-04-06 at 09 39 32" src="https://user-images.githubusercontent.com/26685061/78529595-9b503900-77ea-11ea-8e5d-1f7981e556dc.png">

**Comment by maarcingebala** [comment]
That's the expected result - this repo only contains the Saleor backend - the GraphQL API. Any frontend client needs to be set up separately:
- https://github.com/mirumee/saleor-dashboard/
- https://github.com/mirumee/saleor-storefront/

For the development purposes, I recommend using saleor-platform repo which sets up all components with docker-compose:
- https://github.com/mirumee/saleor-platform

**Comment by raymondfx** [comment]
Hello, I get it now, thanks a lot.
