### ISSUE TITLE
Request for Quotation or Draft Purchase Order

### ISSUE THREAD

**Issue by sebasgoldberg** [mirumee/saleor#5447]
### What I'm trying to achieve
I'm trying that the client could create a quotation instead of a purchase order.

The quotation should be similar to a purchase order, but the difference is that must not be payed.

Once the quotation was created, the store should create the purchase order with final amount and send a link to the customer to perform the payment.

This is useful in cases where:
1) there is no way to assure the published unit price for requested products.
2) and when there is no guarantee of stock for the requested products.

### Describe a proposed solution
I do not have a proposed solution.

### Other solutions I've tried and won't work
I did not found other solutions.

### Screenshots or mockups
NA

**Comment by Kronos127** [comment]
This is actually a very important step in a e-commerce business and should be given way more importance and attention.

**Comment by Kronos127** [comment]
It seems that it became an important part of the saleor enterprise, not available for the common folk tho.

**Comment by timuric** [comment]
We are going to add this feature soon, you can track it here https://github.com/saleor/saleor/issues/5447
