### ISSUE TITLE
Yandex Checkout sdk integration. Please help!

### ISSUE THREAD

**Issue by NIKITAdotONE** [mirumee/saleor#5454]
Hello!
Please help, i'm would like to integrate [yandex-checkout-sdk-python](https://github.com/yandex-money/yandex-checkout-sdk-python) in saleor project. What's the best and simpliest way to do?
Need yout advice.

Best wishes!
Nikita

**Comment by karolkielecki** [comment]
Hey @NIKITAdotONE! I think the best way to do that by a plugin. You can find more detailed information here: https://docs.saleor.io/docs/advanced/extensions/#introduction

**Comment by NIKITAdotONE** [comment]
Ok, Thanks a lot! I try this way. Best wishes!
