### ISSUE TITLE
Having trouble with emails during order checkout

### ISSUE THREAD

**Issue by consultantsdei** [mirumee/saleor#5455]
### What I'm trying to achieve
…
Email sent with the order summary

### Steps to reproduce the problem
1. Register a new acc.
2. Pick desired items in the store.
3. Checkout with valid parameters.
4. Hit place order button.

### What I expected to happen
…
Celery worker sends email with order, instead it raises exception.

### Screenshots

![image](https://user-images.githubusercontent.com/58126707/78720154-2a487880-78f3-11ea-9ed9-f2d857b6b748.png)

**System information**
Operating system: Windows 10

**Comment by patrys** [comment]
It's a race condition in transaction concurrency, Celery worker picks the task before the transaction that created it is committed. @tomaszszymanski129 reassigning to myself as I already have a fix.
