### ISSUE TITLE
StockManager.allocate_stock - adds twice the quantity it is supposed to

### ISSUE THREAD

**Issue by AWalters15** [mirumee/saleor#547]
When an order is placed, the stock manager allocates twice the quantity it is supposed to.

The problem seems to be with  the F() expression.

`
stock.quantity_allocated = F('quantity_allocated') + quantity
`

If I replace that line with 
`
 stock.quantity_allocated += quantity
`

then my problem is fixed. (Though I imagine performance is worse)

I tested the issue from Django Shell and could replicate the error by doing:

`from saleor.product.models import Stock` 
`s = Stock.objects.get(pk=94)   `
`s.quantity_allocated   `
`Stock.objects.allocate_stock(s, 1)   `

If you reload the shell, the quantity allocated value has changed by two instead of one.

Can anyone else replicate the problem ?
Will there also be an issue with deallocate stock ?

**Comment by patrys** [comment]
I've added a test in code that verifies that stock is allocated correctly. Can you provide steps to reproduce?

**Comment by AWalters15** [comment]
Thanks, my installation passes all the tests.

However when I test the stock allocation manually from shell, it still increase by double the amount it should.

I am using PostgresSQL as my database.

Is it possible that the problems are related to DB engine used?

**Comment by AWalters15** [comment]
Sorry, I misread the test results.

Running the tests with an sqlite test DB I get the following:

assert stock.quantity_allocated == 1
E       assert 2 == 1
E        +  where 2 = \<Stock:  - Warehouse 2\>.quantity_allocated

It seems I'm getting the same problems in production with PostgresSQL and in tests with SQLite.

**Comment by patrys** [comment]
The quantity allocated is set to an expression on the stock record. Are you sure you don't accidentally save the record twice? Due to how Django ORM works each save would increase the number further.
