### ISSUE TITLE
 Plugin with path: saleor.plugins.vatlayer.plugin.VatlayerPlugin doesn't exist

### ISSUE THREAD

**Issue by genlearn** [mirumee/saleor#5488]
### My Problem
… First time installation, running `python manage.py migrate` and I got this

`D:\Projects\saleor\saleor\urls.py:29:`
`UserWarning: The debug toolbar was not installed. Ignore the error.`
`settings.py should already have warned the user about it.`
`warnings.warn(
SystemCheckError: System check identified some issues:`
`ERRORS:
?: Plugin with path: saleor.plugins.vatlayer.plugin.VatlayerPlugin doesn't exist `

### I tried:
1. Reinstalling Python and all packages
2. Adding PATH variable to my `venv\lib\site-packages`
3. Check installation path: `...saleor\plugins\vatlayer\plugin`, all seems correct

**System information**
Python 3.8.2
django 3.0.5 (installed in virtual env)
Windows 7

**Please let me know if you need more info.**

**Comment by maarcingebala** [comment]
@genlearn Can you pull the latest master and check if this issue still happens? It should be fixed by PR #5487.
