### ISSUE TITLE
ProductCreate weight mutation

### ISSUE THREAD

**Issue by jkain88** [mirumee/saleor#5496]
![p1](https://user-images.githubusercontent.com/36409853/79555939-f2032000-80d2-11ea-88cc-5e1809e51ec5.PNG)
![p2](https://user-images.githubusercontent.com/36409853/79556174-4b6b4f00-80d3-11ea-96d7-f06ee76bf1ee.PNG)

productCreate mutation

I followed the "amount unit" as said in the comment, but returns a "'StringValue(value='10.00 kg')' value must be a float."
Sorry just a beginner

**Comment by koradon** [comment]
Hi @jkain88 field `weight` is made by two other fields
- `unit`
- `value`

Try sth like this:
```
mutation{
  productCreate(
    input:{
      attributes: []
      basePrice: "300"
      category: "Q2F0ZWdvcnk6Nw=="
      chargeTaxes: false
      descriptionJson: "{}"
      isPublished: true
      name: "PRODUCT"
      productType: "UHJvZHVjdFR5cGU6MTE="
      seo:{
        description: "DESC"
        title: "TITLE"
      }
      sku: "ABC"
      quantity: 300
      weight: {
        unit: "KG"
        value: 10.0
      }
    }
  ){
    product{
      id
      name
      weight{
        unit
        value
      }
    }
  }
}
```

**Comment by jkain88** [comment]
any updates?

**Comment by koradon** [comment]
Hi @jkain88 
I am still debugging this error. It looks like `WeightScalar` is not working as expected. 
I will let you know when we fix this error. in the meanwhile, try to create products without weight param.

**Comment by jkain88** [comment]
ok. thank you
