### ISSUE TITLE
error with command "python manage.py migrate" PostgreSQL issues

### ISSUE THREAD

**Issue by onelsonic** [mirumee/saleor#5516]
when installing saleor I have an error at this step : 
`python manage.py migrate`

The installation failed : 
`django.db.utils.OperationalError: FATAL:  no pg_hba.conf entry for host "::1", user "DBuser", database "DBname", SSL off`

my guess is that I have an issue with connecting to the database PostGreSQL.
I tried the following in SSH : 
`psql -U DBuser -h 127.0.0.1 -p 5432 DBname `
I have the same error as well

**Comment by onelsonic** [comment]
when I use the command :
`psql -U DBuser -h localhost -p 5432 DBname`
I can connect to the PostGreSQL database,

I added the following to the settings.py file :
```
    "default": dj_database_url.config(
        default="postgres://DBuser:myPASSWORD@localhost:5432/DBname", conn_max_age=600
```

but still get the error : 
`django.db.utils.OperationalError: FATAL:  no pg_hba.conf entry for host "::1", user "webroser_postsalebase", database "webroser_SALEDB854fiig", SSL off`

**Comment by NyanKiyoshi** [comment]
Seems like you need to add `::1` to your `pg_hba.conf` file, refer to this [documentation](https://www.postgresql.org/docs/9.1/auth-pg-hba-conf.html).

**Comment by onelsonic** [comment]
I can now connect manually to the PostGreSQL database using : 
`psql -U DBuser -h 127.0.0.1 -p 5432 DBname`

but still have the installation error:
`django.db.utils.OperationalError: FATAL:  no pg_hba.conf entry for host "::1", user "DBuser ", database "DBname", SSL off`
is there a way to force Django/Saleor to connect using IPV4 so it connects to 127.0.0.1 and not ::1 ?
because I don't have access to the `pg_hba.conf`

**Comment by NyanKiyoshi** [comment]
>  is there a way to force Django/Saleor to connect using IPV4 so it connects to 127.0.0.1 and not ::1 ?

Yes, replacing `localhost` by `127.0.0.1` from `postgres://DBuser:myPASSWORD@localhost:5432/DBname`

**Comment by onelsonic** [comment]
@NyanKiyoshi , it worked like a charm, many thanks 👍
