### ISSUE TITLE
Missing requirement in docs: wheel

### ISSUE THREAD

**Issue by nidico** [mirumee/saleor#552]
The `pip install -r requirements.txt` step requires `wheel` to be installed, so we should first do:

    pip install wheel

Or, to be consistent with travis config:

    pip install -U pip setuptools wheel

**Comment by patrys** [comment]
@nidico Which version of `pip` are you using? Can you try upgrading it and report both the version before and after so we can update the docs?

`wheel` should not be required unless you plan to build your own wheels.

**Comment by nidico** [comment]
This issue happens with `pip-8.1.1` from ubuntu system packages. Upgrading locally to `pip-8.1.2` with `pip install -U pip` indeed solves the problem.
