### ISSUE TITLE
Database backup/recovery mechanism

### ISSUE THREAD

**Issue by PiotrLaszczyk** [mirumee/saleor#5536]
### What I'm trying to achieve
I observed that from time to time after hash update on one of branches or some other action done by /graphql/ or I simply did something wrong my database is broken or saleor start to have errornes behaviors. Simple solution is to erase data base and start from begging. Now its not problematic as its not working in production. But if it starts to work in production, customers have some orders, system is running, and then its happens then I'm in trouble... 

Do You have some plan to introduce some healthy monitor mechanism? Or some database recovery actions? Maybe some advises what steps should be made on user side to have some restore mechanisms?

**Comment by maarcingebala** [comment]
We haven't considered adding any kind of database recovery in Saleor yet, but I think it's nor the responsibility of Saleor itself, but of the environment where it's deployed. I think most cloud providers where you'd normally deploy Saleor provide database snapshots/recovery out-of-the-box. E.g. for Heroku: https://devcenter.heroku.com/articles/heroku-postgres-backups

**Comment by PiotrLaszczyk** [comment]
Hmm... I will try to add snapshot mechanism on heroku side,  but it would be good to do this in that way:

1) check if db is consistent and have no issues
2) trigger backup

I could do this in some 'umbrella' thread. Runs it every hour... but how to check if db is correct?
