### ISSUE TITLE
npm ERR! missing script: build-assets

### ISSUE THREAD

**Issue by lazydream** [mirumee/saleor#5539]
### What I'm trying to achieve
Running **npm run build-assets** from https://docs.saleor.io/docs/getting-started/installation-macos/
and got npm ERR! missing script: build-assets

npm ERR! Did you mean one of these?
npm ERR!     build-schema
npm ERR!     build-emails

Maybe documentation is outdated and I need to run **build-schema** instead?

**Comment by lazydream** [comment]
Yeah, when I ran npm run build-schema, and then npm run build-emails, the installation seems to work properly

**Comment by maarcingebala** [comment]
@lazydream `build-assets` is available in Saleor 2.9 - if you're using that release the command should work just fine. If you're on `master`, make sure to switch to the new version of docs: https://docs.saleor.io/versions/. On `master` this command is no longer available.

**Comment by Naweeda** [comment]
*Prepare front-end assets error* 
Running npm run build-assets from https://docs.saleor.io/docs/2.9.0/getting-started/installation-linux/
and getting the following error: 
npm ERR! missing script: build-assets
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     build-schema
npm ERR!     build-emails

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/naweed/.npm/_logs/2020-11-28T05_48_53_883Z-debug.log


I wasn't able to find an updated documentation of how to set it up in Linux Ubuntu, can anyone share me the link?
