### ISSUE TITLE
[suggestion] -  Add cash on delivery payment method

### ISSUE THREAD

**Issue by wael-mohamed** [mirumee/saleor#5540]
### What I'm trying to achieve
… Add cash on delivery payment method

### Describe a proposed solution
... I think the dummy payment method has the same meaning as cash on delivery method

**Comment by maarcingebala** [comment]
Hey, dummy payment is used mainly for development - when you don't have any payment gateways configured but still want to place orders and need some payment object.

Implementation of "cash on delivery" would probably look similar - it should be implemented as a payment plugin and just create new payment objects with the right status in the database. Maybe it would require to add some new status, I'm not sure. It's definitely on our roadmap but we haven't yet thought about the details of how it should work.
