### ISSUE TITLE
populatedb does not work with S3 bucket

### ISSUE THREAD

**Issue by elcolie** [mirumee/saleor#5545]
### What I'm trying to achieve
populatedb

### Steps to reproduce the problem
1. checkout `1ba7f4eb74c037edcabfe4b581713b9b80da2601`
2. configure `S3`
3. `python manage.py populatedb`

### What I expected to happen
When I open `storefront`. I would be able to see `pictures`

### Screenshots
![image](https://user-images.githubusercontent.com/18206728/80316325-694d5800-8827-11ea-8eb6-d573f25f2a9d.png)

**System information**
Operating system: Docker image `python:3.8`

**Comment by maarcingebala** [comment]
I have a staging test instance that runs on Heroku and uses S3 for images and it works fine with `populatedb`. Are you sure you configured all env variables necessary to run with S3?
- `AWS_ACCESS_KEY_ID`
- `AWS_MEDIA_BUCKET_NAME`
- `AWS_SECRET_ACCESS_KEY`
- `AWS_STORAGE_BUCKET_NAME`

You can read about it more here: https://docs.saleor.io/docs/next/developer/running-saleor/s3

**Comment by elcolie** [comment]
Thank you very much. I will check again
