### ISSUE TITLE
Query which OS to use

### ISSUE THREAD

**Issue by subha-py** [mirumee/saleor#555]
I am using ubuntu 16.04 and having lots of issues while installing. Can any one tell me which verison of ubuntu will go good for this? I am comfortable to switch to centos also.

**Comment by patrys** [comment]
Ubuntu 16.04 should work fine. Can you describe your problems?

**Comment by subha-py** [comment]
I am having problem when installing the webpack.
[https://github.com/npm/npm/issues/13880](issue 1) and while trying to solve this issue i counter this one [https://github.com/npm/npm/issues/13882](issue 2). Can you help me here?
@patrys

**Comment by patrys** [comment]
Which versions of Node.js and mom are you using?

**Comment by subha-py** [comment]
You can close the issue. It's been resolved. upgrading the npm solved the problem thanks,mate
