### ISSUE TITLE
Adding product metadata trough mutation throwing err in playground

### ISSUE THREAD

**Issue by giovannipiccinelli** [mirumee/saleor#5559]
### What I'm trying to achieve

I am trying to add metadata to a product using mutations but it is trowing backe the following error: "You do not have permission to perform this action" as shown in the picture. I even included authorization https headers {  "Authorization": "xyz..."}  but is not working.

### Steps to reproduce the problem
1.  Open the graphql playground
2. and type in the mutation as shown below according to the examples shown in https://docs.saleor.io/docs/api/example-query

### What I expected to happen
3. I expect the metadata to be added.

### Screenshots
![Schermata 2020-04-28 alle 00 01 15](https://user-images.githubusercontent.com/7911077/80425221-89425180-88e3-11ea-9ef2-b9f2f4e4bdf3.png)

**System information**
Operating system: Mac Os

**Comment by grll** [comment]
Hey, I just checked your example it is working fine in Saleor 2.9 but you need adequate permissions. First create an app or edit your app to have at least the manage_product permission using the following cli command (the command is for all permissions but you can adapt):

```bash
python manage.py create_app yourappname --permission account.manage_users \
                                    --permission account.manage_staff \
                                    --permission app.manage_apps \
                                    --permission app.manage_apps \
                                    --permission discount.manage_discounts \
                                    --permission plugins.manage_plugins \
                                    --permission giftcard.manage_gift_card \
                                    --permission menu.manage_menus \
                                    --permission order.manage_orders \
                                    --permission page.manage_pages \
                                    --permission product.manage_products \
                                    --permission shipping.manage_shipping \
                                    --permission site.manage_settings \
                                    --permission site.manage_translations \
                                    --permission webhook.manage_webhooks \
                                    --permission checkout.manage_checkouts
``` 

This command will return you a token that you need to set in the http header panel as follow:

```json
{
  "Authorization": "Bearer LcLNVgUt8mu8yKJ0Wrh3nADnTT21uv"
}
```

then you will have permission to perform any mutations allowed by the permissions that you just set on your app.

By the way the `errors` field that you use is deprecated your mutation should look like something like this:
```graphql
mutation {
  updateMetadata(
    id: "UHJvZHVjdDozNQ=="
    input: { key: "special_product", value: "bus" }
  ) {
    metadataErrors {
      field
      message
      code
    }
    item {
      metadata {
        key
        value
      }
    }
  }
}
```

**Comment by giovannipiccinelli** [comment]
@grll 
thanks that solved my problem 👏

**Comment by tiwiex** [comment]
Hello Gril,
Thanks for your insight. this didn't work for me. It generated the token as you said but still permission denied. I notice server cannot be reached in the inline graphicql address bar but it still works. Could this be the issue. I suspect and environment variable for that saying  Invalid HTTP_HOST header: <SimpleLazyObject: '*'>

What does create_app do anyway. I can't find reference to the created app anywhere. I can using startapp but that doesn't work with your example above so it must be a different command.

Pulling my head here.
Thanks again in anticipation.
Regards,
Taiwo
