### ISSUE TITLE
Adding other characteristics to products

### ISSUE THREAD

**Issue by michalstepniewski** [mirumee/saleor#556]
Hello,
I am thinking of writing a dietician app based on saleor. I though it would be as simple as adding eq. protein field to products and make it sum up in the cart. However in the cart I cannot seem to find the cart model where apart from get_total I could add for example 'get total protein' etc.

Cheers

Michal

**Comment by artursmet** [comment]
@michalstepniewski We've recently added `Cart` model, please take a look now, previously cart was not stored in database

**Comment by michalstepniewski** [comment]
Cool :)

**Comment by patrys** [comment]
Closing this since it's much easier to customize now.
