### ISSUE TITLE
autoreloading code in docker during development?

### ISSUE THREAD

**Issue by Wingie** [mirumee/saleor#557]
i tried
`sudo docker exec -i -t saleor_web_1 /bin/bash`
```
root@d8a227505292:/app# uwsgi saleor/wsgi/uwsgi.ini restart
[uWSGI] getting INI configuration from saleor/wsgi/uwsgi.ini
unable to load configuration from restart

```

**Comment by patrys** [comment]
With recent changes `docker-compose` should run `manage.py runserver` by default.

**Comment by Wingie** [comment]
ok thanks; am pulling master again.

[Wilson Wingston Sharon]

**Comment by patrys** [comment]
I'll close this assuming it works as expected.
