### ISSUE TITLE
Stock quantity is 0 despite that warehouse quantity has some items

### ISSUE THREAD

**Issue by PiotrLaszczyk** [mirumee/saleor#5578]
### What I'm trying to achieve
creating products with: two attributes, without variants, with stock and defined warehouse.

Im introducing support with stocks and warehouses... and I started to observe issue... 

Steps to reproduce:
1. creating warehouse
2. creating product type with 2 attributes
3. creating product with quantity in warehouse 88888...
---

params for productCreate: {'productType': 'UHJvZHVjdFR5cGU6Mw==', 'category': 'Q2F0ZWdvcnk6MTA=', 'name': 'name', 'basePrice': '14.08', 'sku': 'fc0d7642c38ab607aa7c07906216ed59', 'trackInventory': True, 'stocks': [{'warehouse': 'V2FyZWhvdXNlOjllM2U3YWNmLTIzNTQtNDcwOC05ZTgzLWMzYzQ4NTY0NzBmMA==', 'quantity': 88888}], 'isPublished': True, 'chargeTaxes': True, 'taxCode': 'STANDARD', 'descriptionJson': '{"blocks": [{"key": "", "data": {}, "text": "...", "type": "unstyled", "depth": 0, "entityRanges": [], "inlineStyleRanges": []}, {"key": "", "data": {}, "text": " ", "type": "unstyled", "depth": 0, "entityRanges": [], "inlineStyleRanges": []}], "entityMap": {"0": {"data": {"href": "https://github.com/mirumee/saleor"}, "type": "LINK", "mutability": "MUTABLE"}}}', 'attributes': [{'id': 'QXR0cmlidXRlOjI=', 'values': ['valueA']}, {'id': 'QXR0cmlidXRlOjE=', 'values': ['valueB']}], 'weight': 0.01}

response:
{'productCreate': {'product': {'id': 'UHJvZHVjdDo1', 'name': '...', 'category': {'name': '...'}, 'productType': {'name': '...'}, 'isPublished': True, 'chargeTaxes': True, 'taxType': {'taxCode': '', 'description': ''}, 'descriptionJson': '{"blocks": [{"key": "", "data": {}, "text": "...", "type": "unstyled", "depth": 0, "entityRanges": [], "inlineStyleRanges": []}, {"key": "", "data": {}, "text": " ", "type": "unstyled", "depth": 0, "entityRanges": [], "inlineStyleRanges": []}], "entityMap": {"0": {"data": {"href": "https://github.com/mirumee/saleor"}, "type": "LINK", "mutability": "MUTABLE"}}}', 'attributes': [{'attribute': {'id': 'QXR0cmlidXRlOjE=', 'name': '...'}, 'values': [{'name': '....', 'slug': '...'}]}, {'attribute': {'id': 'QXR0cmlidXRlOjI=', 'name': '....'}, 'values': [{'name': '....', 'slug': '....'}]}], 'weight': {'value': 0.01, 'unit': 'kg'}, 'variants': [{'id': 'UHJvZHVjdFZhcmlhbnQ6NQ==', 'sku': 'fc0d7642c38ab607aa7c07906216ed59', 'trackInventory': True, **'quantity': 0, 'stockQuantity': 0**, 'stocks': [{'warehouse': {'id': 'V2FyZWhvdXNlOjllM2U3YWNmLTIzNTQtNDcwOC05ZTgzLWMzYzQ4NTY0NzBmMA=='}, **'quantity': 88888**}]}], **'isAvailable': False**, 'pricing': {'onSale': False}}, 'errors': []}}

Whats strange is that, depends on situation (what I did before on DB) sometimes it works (shows quantity from warehouse) and sometimes shows 0...

**System information**
Operating system: heroku/local deployment

**Comment by PiotrLaszczyk** [comment]
Same code executed anther time... gives correct result.. so it depends on DB actual state... 

{'productCreate': {'product': {'id': 'UHJvZHVjdDoz', 'name': '...', 'category': {'name': '...'}, 'productType': {'name': '...'}, 'isPublished': True, 'chargeTaxes': True, 'taxType': {'taxCode': '', 'description': ''}, 'descriptionJson': '{"blocks": [{"key": "", "data": {}, "text": "...", "type": "unstyled", "depth": 0, "entityRanges": [], "inlineStyleRanges": []}], "entityMap": {"0": {"data": {"href": "https://github.com/mirumee/saleor"}, "type": "LINK", "mutability": "MUTABLE"}}}', 'attributes': [{'attribute': {'id': 'QXR0cmlidXRlOjE=', 'name': '...'}, 'values': [{'name': '...', 'slug': '...'}]}, {'attribute': {'id': 'QXR0cmlidXRlOjI=', 'name': '...'}, 'values': [{'name': '...', 'slug': '...'}]}], 'weight': {'value': 0.01, 'unit': 'kg'}, 'variants': [{'id': 'UHJvZHVjdFZhcmlhbnQ6Mw==', 'sku': '7656c16709d5df3f6422615ac1174cc2', 'trackInventory': True, **'quantity': 88888, 'stockQuantity': 50,** 'stocks': [{'warehouse': {'id': 'V2FyZWhvdXNlOjM4M2IyYzA1LTgyZGMtNDZjYy1hMzQwLTg0MzdlMjAyNzVkNA=='}, **'quantity': 88888}]}], 'isAvailable': True,** 'pricing': {'onSale': False}}, 'errors': []}}

**Comment by maarcingebala** [comment]
`ProductVariant.stockQuantity` field is deprecated. Please use the `stocks` field, which takes warehouses into account.
