### ISSUE TITLE
PostgreSQL third party extensions "pg_trgm" requiring Superuser Rights unable to use on Shared Hosting providers (example: A2hosting, pythonanywhere)

### ISSUE THREAD

**Issue by onelsonic** [mirumee/saleor#5579]
Using the flag set to false, the outdated extension "hstore" is not more required, this works greats 
https://github.com/mirumee/saleor/issues/5542 👍 

Following on the installation of Saleor on shared hosting services :
At the step : # python manage.py migrate

The migrations starts and works now fine except that it stops at this file :
**0037_auto_20171124_0847.py**

When digging into it. The problem is the way the database migration is handled. Having to rely on third party PostgreSQL extensions is creating and will create this problem on any Shared Hosting providers, reducing the scope of Saleor.

So it seem this process needs to be extended to the extensions used for the database migrations.
Digging into the topic, Oracle communicated as well on this issue when one migrates their database to PostgreSQL.

We need to bypass or process manually this extension "pg_trgm" as well.

```
Running migrations:
  Applying product.0022_auto_20161212_0301... OK
  Applying product.0023_auto_20161211_1912... OK
  Applying product.0024_migrate_json_data... OK
  Applying product.0025_auto_20161219_0517... OK
  Applying product.0026_auto_20161230_0347... OK
  Applying product.0027_auto_20170113_0435... OK
  Applying product.0013_auto_20161130_0608... OK
  Applying product.0014_remove_productvariant_attributes... OK
  Applying product.0015_productvariant_attributes... OK
  Applying product.0016_auto_20161204_0311... OK
  Applying product.0017_attributechoicevalue_slug... OK
  Applying product.0018_auto_20161212_0725... OK
  Applying product.0026_merge_20161221_0845... OK
  Applying product.0028_merge_20170116_1016... OK
  Applying product.0029_product_is_featured... OK
  Applying product.0030_auto_20170206_0407... OK
  Applying product.0031_auto_20170206_0601... OK
  Applying product.0032_auto_20170216_0438... OK
  Applying product.0033_auto_20170227_0757... OK
  Applying product.0034_product_is_published... OK
  Applying product.0035_auto_20170919_0846... OK
  Applying product.0036_auto_20171115_0608... OK
  Applying product.0037_auto_20171124_0847...Traceback (most recent call last):
  File "/virtualenv/web/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InsufficientPrivilege: permission denied to create extension "pg_trgm"
HINT:  Must be superuser to create this extension. 
```

For that we would need to change the logic of the product search:
https://github.com/mirumee/saleor/blob/d0f029e3c30d3ff64b01c60f3c0033febc69235c/saleor/search/backends/postgresql_storefront.py#L7-L24

**Comment by onelsonic** [comment]
this is an external extension that requires superuser rights to 
to calculate a trigram similarity between the two arguments.

Well writing an SQL function which will give a higher result on better
matches is maybe a good way to solve this without the need for an extension.
Something like this :

-----------------------------------------
NewGramSimilarity(match, against)
returnvalue:
The sum of
  1, or every matching character in the right place,
  0.2, for every character matching in the wrong place :


```
DROP FUNCTION IF EXISTS NewGramSimilarity;
delimiter //
CREATE FUNCTION NewGramSimilarity (v_match TEXT, v_against TEXT)
   RETURNS real
BEGIN
  DECLARE v_score REAL;
  DECLARE v_index INT;

  SET v_score = 0;

  SET v_index = 1;
  WHILE v_index <= LENGTH(v_against) DO
    IF substr(v_match,v_index,1) = substr(v_against,v_index,1) THEN
       SET v_score = v_score + 1.0;
    ELSE
       IF LOCATE(substr(v_match,v_index,1),
concat(substr(v_against,1,v_index-1),substr(v_against,v_index+1)))>0 THEN
         SET v_score = v_score + 0.2;
       END IF;
    END IF;

    SET v_index = v_index + 1;
  END WHILE;

  RETURN v_score;

END//
delimiter ;
```

===============================================
>>
```
SELECT NewGramSimilarity('roop','poor'),  2.4, '';
SELECT NewGramSimilarity('door','poop'),  2, '';
SELECT NewGramSimilarity('rood','poor'),  2.2, ''; 
SELECT NewGramSimilarity('poop','poop'),  4, '';
```


#############
I also found this : https://gist.github.com/DavidMikeSimon/1311207#file-gistfile1-txt
and this : https://gist.github.com/phpenterprise/be9560412824e5b05e1c1b3f38266b57

**Comment by patrys** [comment]
I suggest trying to resolve this with your hosting provider instead of looking for ways around this limitation. They should be able to create the extension in the `template1` database and have it automatically available for all customers.

While we could write a custom pure-SQL n-gram implementation, I doubt we could match the performance of `pg_trgm`, it would require us to create custom Django wrappers for the filters and indexes, and I'm not looking forward to maintaining all of this code.

**Comment by onelsonic** [comment]
sure thank you.
This add another level of complications...
no choice but to move to a dedicated hosting with full root access.

**Comment by NyanKiyoshi** [comment]
> no choice but to move to a dedicated hosting with full root access.

Or to contact support, that's their job to provide proper services.

**Comment by ernesthenry** [comment]
im running into this issue
