### ISSUE TITLE
Update Mongolian locale file

### ISSUE THREAD

**Issue by endigo** [mirumee/saleor#5594]
Hello,

We worked on Mongolian translations, but we haven't finished yet.
We want to use translation at least on demo.

Thanks

**Comment by endigo** [comment]
@maarcingebala @NyanKiyoshi 
Unfortunately, this PR not included Mongolian localization updates.

**Comment by maarcingebala** [comment]
@endigo Did you update your translations in [Transifex](https://www.transifex.com/)? Translators can use this platform to provide their translations and we synchronize them with the codebase.

**Comment by endigo** [comment]
@maarcingebala Yes, we updated in Transifex, but we don't have permission to review.

Is there any chance to give review permissions to me?

**Comment by maarcingebala** [comment]
OK let me check what's going on and I'll update you later today.

**Comment by maarcingebala** [comment]
@endigo From what I understand, strings don't need to be reviewed to be pulled from Transifex to Saleor. Reviews help you only if there is more translators and they should agree on some version of a translation.

**Comment by maarcingebala** [comment]
I see now on Transifex that the translations was edited on May 8th while we merged the PR earlier. Maybe we just have to sync the translations again which we will do before the final release of `2.10.0`.
