### ISSUE TITLE
2.10 populatedb don't check for slug in product

### ISSUE THREAD

**Issue by Boquete** [mirumee/saleor#5604]
### What I'm trying to achieve
Populatedb on existing database with previously populated data.

populatedb script when creating products, don't check for slug

2020-05-06 18:49:31
django.db.utils.IntegrityError: duplicate key value violates unique constraint "product_product_slug_key"
2020-05-06 18:49:31
DETAIL: Key (slug)=(polo-shirt) already exists.

ad:
```
def create_products(products_data, placeholder_dir, create_images):
    for product in products_data:
        pk = product["pk"]
        # We are skipping products without images
        if pk not in IMAGES_MAPPING:
            continue

        defaults = product["fields"]
        set_field_as_money(defaults, "price")
        defaults["weight"] = get_weight(defaults["weight"])
        defaults["category_id"] = defaults.pop("category")
        defaults["product_type_id"] = defaults.pop("product_type")
        product, _ = Product.objects.update_or_create(pk=pk, defaults=defaults)

        if create_images:
            images = IMAGES_MAPPING.get(pk, [])
            for image_name in images:
                create_product_image(product, placeholder_dir, image_name)

```

**Comment by maarcingebala** [comment]
Hm I couldn't reproduce this; I ran populatedb a few times and it worked, I'm on `master`.

**Comment by Boquete** [comment]
> Hm I couldn't reproduce this; I ran populatedb a few times and it worked, I'm on `master`.

did you tried re-running populate on with older version?

We had database with I think 2.8 populatedb data, after migrating in 2.10 and populating again this problem eccoured and we had to drop db.

I will try to reproduce it once again
