### ISSUE TITLE
bug on sign in to dashboard after migration

### ISSUE THREAD

**Issue by wael-mohamed** [mirumee/saleor#5610]
### What I'm trying to achieve
try to sign in to the dashboard after the migration

### What I expected to happen
get error: extensions.manage_plugins' is not a valid PermissionEnum

**Comment by wael-mohamed** [comment]
I've fixed it by deleting a row from auth_permission with content-id of extension

**Comment by d-wysocki** [comment]
Hey, could you tell which version/commit id of saleor you're using?
This bug are fixed in https://github.com/mirumee/saleor/commit/509eeb82f62024a51b21b0dd47063656bc82fcc3?diff=unified#diff-011d2378166da8d309679d66b437a554
