### ISSUE TITLE
Can't activate an account when activation link is lost

### ISSUE THREAD

**Issue by wael-mohamed** [mirumee/saleor#5615]
### What I'm trying to achieve
Activate an account when the activation link is lost, I've tried to restore the password, I get the expired link error message

### What I expected to happen
Resend a new account activation link email

**Comment by NyanKiyoshi** [comment]
Sounds like a bug. I would expect the password reset link to allow to bypass the activation as a feature.

**Comment by wael-mohamed** [comment]
No, when you get the password link and you try to restore it, you get token expired error

**Comment by NyanKiyoshi** [comment]
Yes, most likely because the user is flagged as inactive. It could be a feature to allow inactive users to reset their password in order to activate their account.
