### ISSUE TITLE
redirectUrl is required even though schema says it shouldn't be.

### ISSUE THREAD

**Issue by JustStanix** [mirumee/saleor#5626]
### What I'm trying to achieve
accountRegister mutation

### Steps to reproduce the problem
1. Run accountRegister without redirectUrl

### What I expected to happen
Account get's created and set as active. Instead it returns an error that redirectUrl is required.

**System information**
Operating system: OS X

**Comment by maarcingebala** [comment]
To use the `accountRegistration` without email activation set the env variable `ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL` to `False`. Please see the docs for more details: https://docs.saleor.io/docs/developer/users#creating-a-new-customer-account
