### ISSUE TITLE
unicode characters in SlugField

### ISSUE THREAD

**Issue by a-atalla** [mirumee/saleor#5640]
### What I'm trying to achieve
create a new category in the catalog with utf-8 name

### Steps to reproduce the problem
1. Catalog > Categories > Create Category
2. Type in Category name an Arabic name   for example `زيوت`
3. Click  the save button

### What happens
1. the save button converts to Error
2. the response says that the `slug` field is required

### What I expected to happen
1. expect to save the new category
2. generate the `UTF-8` slug from the name

### Solution
1. The SlugField has an option to enable `UTF-8` values
[SlugField.allow_unicode](https://docs.djangoproject.com/en/3.0/ref/forms/fields/#django.forms.SlugField.allow_unicode)

2. the util function slugify need `allow_unicode=True` as a second paramaeter 
[slugify(value, allow_unicode=True)](https://docs.djangoproject.com/en/3.0/ref/utils/#django.utils.text.slugify) otherwise it will return an empty string which causing the error

### Screenshots
<img width="1880" alt="Screen Shot 2020-05-14 at 4 28 54 AM" src="https://user-images.githubusercontent.com/536140/81886539-3d5b0200-959d-11ea-9663-5fe80e93cc84.png">

**System information**
Saleor Version: 2.10.0-rc.2
Operating system: macOS Catalina 10.15.4
Browser: Firefox

**Comment by korolevpavel** [comment]
Hello!

I have the same error when I create attributes in Cyrillic on Saleor 2.9
<img width="1092" alt="Снимок экрана 2020-05-14 в 15 23 51" src="https://user-images.githubusercontent.com/12083359/81934061-fac61380-95f6-11ea-9bd8-722159d4a586.png">
.

**Comment by korolevpavel** [comment]
I fixed it like this:
add `models.py` to `class AttributeValue`:
```python
 def get_slug(self):
        return slugify(smart_text(unidecode(self.name)))
```
and to `forms.py` edit `def save` to `class AttributeValueForm`:
```python
    def save(self, commit=True):
        self.instance.slug = AttributeValue.get_slug(self.instance)
        return super().save(commit=commit)
```

**Comment by korolevpavel** [comment]
> Hello!
> 
> I have the same error when I create attributes in Cyrillic on Saleor 2.9
> <img alt="Снимок экрана 2020-05-14 в 15 23 51" width="1092" src="https://user-images.githubusercontent.com/12083359/81934061-fac61380-95f6-11ea-9bd8-722159d4a586.png">
> .

I fixed it like this:
add models.py to class AttributeValue:

 def get_slug(self):
        return slugify(smart_text(unidecode(self.name)))
and to forms.py edit def save to class AttributeValueForm:

    def save(self, commit=True):
        self.instance.slug = AttributeValue.get_slug(self.instance)
        return super().save(commit=commit)
