### ISSUE TITLE
Install Khmer Language in Django

### ISSUE THREAD

**Issue by Pichnyty** [mirumee/saleor#5658]
Hi, This is not really issues but I would request whether the project are able to use "Khmer Language" or not ?

### What I'm trying to achieve
Install Khmer Language in Django
### Describe a proposed solution
To make the system able to translate to Khmer Language
### Other solutions I've tried and won't work
1. I include **_("km", _("Khmer")),_** as the below screenshot 
![Capture](https://user-images.githubusercontent.com/54165288/82137802-61d90780-9845-11ea-8c09-3197bf4f88b7.JPG)
2. Then I am able to select the Khmer Language Option as the below image
![Capture](https://user-images.githubusercontent.com/54165288/82137824-87661100-9845-11ea-9b9d-7d0b8a3d3e9a.JPG)
3. However After the selection the system unable to translate to Khmer Language as other language.

**Comment by maarcingebala** [comment]
Hey, from what I see there are no Khmer translations in Saleor so far. To add them, please register on Transifex where you can find Saleor and add translations there. Once you do that, we'll sync the translation strings and they'll be available to use in Saleor.

https://www.transifex.com
https://www.transifex.com/mirumee/saleor-1/language/km/

**Comment by Sokhavuth** [comment]
![picture](https://user-images.githubusercontent.com/49101948/181766902-b087bcad-6d72-4640-89a5-b1c43ba46b4d.jpg)
change in the settings.py file from 'en-US' to 'km-KH' as showing in the picture.
