### ISSUE TITLE
Dashboard front-end improvements

### ISSUE THREAD

**Issue by weronka** [mirumee/saleor#566]
- [x] open dashboard and storefront in separate tabs
- [x] fix datepicker
- [x] responsive breakpoints need to be fixed
- [x] fix inputs grid 
- [x] add drag and drop icon to sorting elements for better mobile scrolling experience
- [x] fix order filter form
- [x] show products in category view

**Comment by patrys** [comment]
Not sure about linking logo to the storefront. I think the dashboard is a separate domain of concern. We already provide a link under current user account but maybe it deserves to be a separate link (perhaps fixed at the bottom of the sidebar?).

**Comment by weronka** [comment]
@patrys 
But I think it's more common and intuitive for users when site logo on dashboard links to storefront rather then to dashboard home page. And we already have 'Home' link on dashboard menu.
And what do you think about opening all links to the storefront in a new tab? Editing content will be more convenient.

**Comment by patrys** [comment]
I don't think it's that common. The dashboard is a separate application and has its own home page. I am all for opening storefront and dashboard in separate tabs though (but it would make logo opening the storefront in a new tab even more uncommon).

If we were to change anything, I'd make the navigation bar span the entire width of the screen and make the sidebar collapsible. See [Google Keep](https://keep.google.com/) for an example.

Another issue is the tables often overflow their containers. We need to either ellipsize columns that are too long or make the tables scrollable.

**Comment by weronka** [comment]
@patrys I've fixed tables in the pull request but in some cases it'll be better to to rethink how to arrange information rather than make scrollable tables

**Comment by patrys** [comment]
I wholeheartedly agree but I think there may be places where tables are more than just navigation.
