### ISSUE TITLE
"'App' object has no attribute 'is_anonymous'" on creating orderfulfillment

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#5677]
### What I'm trying to achieve
I'm using an app user (serviceaccount ) with permissions manage_orders and manage_shipment.
I'm trying to create a fulfillment: 
```
mutation createFulfillment($orderId: ID!, $input: OrderFulfillInput!) {
  orderFulfill(order: $orderId, input: $input) {
    fulfillments {
      id
      status
    }
  }
}
```
attributes:
```
{
  "orderId": "T3JkZXI6Ng==" ,
  "input": { "lines": [{ "orderLineId": "T3JkZXJMaW5lOjU=", "stocks": [{  "quantity": 1, "warehouse": "V2FyZWhvdXNlOmI5ZTRlMjQzLWY0M2EtNDZkNy05NWZjLWE3NTY2ODUzMzE5OQ==" }] }] }
}
``` 

I receive the following message back: 
```
{
  "errors": [
    {
      "message": "'App' object has no attribute 'is_anonymous'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "orderFulfill"
      ],
      "extensions": {
        "exception": {
          "code": "AttributeError"
        }
      }
    }
  ],
  "data": {
    "orderFulfill": null
  }
}
```

I'm using saleor 2.10 stable.

logs: 
```
{
  "errors": [
    {
      "message": "'App' object has no attribute 'is_anonymous'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "orderFulfill"
      ],
      "extensions": {
        "exception": {
          "code": "AttributeError"
        }
      }
    }
  ],
  "data": {
    "orderFulfill": null
  }
}
```

### Steps to reproduce the problem
1. Create a serviceaccount with the permissions as above
2. Try to create a fulfillment for an order

### What I expected to happen
…

### Screenshots

**System information**
Operating system:

**Comment by korycins** [comment]
Hi @JannikZed 
Thanks for catching and reporting this.
The main issue is that `Events` doesn't support requests from `App`/`ServiceAccount`. There is an issue for this - https://github.com/mirumee/saleor/issues/5274.
After we rebuild the fulfillment to use more advanced warehouse system, we didn't discover that for `OrderFulfillment` we pass `User` **or** `App/ServiceAccount` and this raises an error.
