### ISSUE TITLE
Master branch broken with commit ae23560e199151caa996d1235609741cf5786d73

### ISSUE THREAD

**Issue by sailorfred** [mirumee/saleor#569]
I'm attaching the script I'm using with a fresh FreeBSD 10.3 VBox (tweak for Linux).

if you comment out the git checkout	971e6aa680504ac0b5062add393dd16cd06659d4 line or set it to a later commit, you always get:

ProgrammingError at /
relation "cart_cart" does not exist
LINE 1: ... "cart_cart"."total", "cart_cart"."quantity" FROM "cart_cart...

when visiting localhost:8000
[build-script.txt](https://github.com/mirumee/saleor/files/520033/build-script.txt)

**Comment by patrys** [comment]
This is already fixed on master branch.

**Comment by sailorfred** [comment]
It was broken yesterday, so I spent some time tracking down which commit killed it.

**Comment by patrys** [comment]
Sorry, I did not mean to be harsh 👍
