### ISSUE TITLE
graphql.error.base.GraphQLError: Fields "quantityAvailable" conflict because they have differing arguments. Use different aliases on the fields to fetch both if this was intentional.

### ISSUE THREAD

**Issue by neerajgupta2407** [mirumee/saleor#5705]
### What I'm trying to achieve
I have populated the default data.
While browsing Storefornt, on clicking checkout, getting the below error on graphql.
 
`graphql.error.base.GraphQLError: Fields "quantityAvailable" conflict because they have differing arguments. Use different aliases on the fields to fetch both if this was intentional.
`

### Steps to reproduce the problem
1. Install Storefront , saleor backend.
2. Add any product, click on "Bag" icon.

### What I expected to happen
Cart info should be available

### Screenshots

https://drive.google.com/file/d/1ClckmcveYwNMEXgova2hdhHfuPAgDscX/view?usp=sharing

**System information**
Operating system:

**Comment by maarcingebala** [comment]
This is a storefront issue and we have it already reported: https://github.com/mirumee/saleor-storefront/issues/732
