### ISSUE TITLE
Google Merchant Feed mechanism need to be updated

### ISSUE THREAD

**Issue by PiotrLaszczyk** [mirumee/saleor#5710]
### What I'm trying to achieve
Add shop to google merchant center

### Steps to reproduce the problem
.gz created according to instruction ... https://docs.saleor.io/docs/integrations/googleforretail/
then try to use it in GMC

### Errors
missing required field: link (url to product)
fields like description, pictures - they sometimes are empty (saleor allows that, GMC produce errors)
in title there is ...(id), why, is there some reason to do that ?

**Comment by maarcingebala** [comment]
Hey, the doc you've linked is for the version 2.9.0. We've made a lot of changes since then and the Google Feed implementation is a bit outdated, unfortunately. One of the problems now is that since the storefront is a separate app, we don't know in the backend what are the public product URLs. The solution would be to generate the feed in the frontend where all these information is known.

**Comment by PiotrLaszczyk** [comment]
I managed with that by writing additional script to rewrite this saleor feed to be compliant with GMC. But indeed direct url to product is missing and really don't have idea how to get this easily.... some hint for doing that would be helpful ;).

Consider that typically there is some script which updates backend database using graphql ifc. You did this project in that way that storefront only shows/visualize actual database state - great idea btw, but keeping this fact in mind You should be consistent with that and have information in database what is direct product url and storefront should use this information, not opposite ;)

**Comment by maarcingebala** [comment]
Not always - the storefront is optional in the headless approach, so there might be no storefront at all. You can also have more than one storefront or a mobile app could be your only interface. I'm not sure generating Google Feed should be part of Saleor core, maybe it should be an external script/app that knows how to generate the feed for a specific client/storefront.

**Comment by PiotrLaszczyk** [comment]
But way how storefront (this or other) creates its product urls need to be known from saleor/graphql user perspective, thats whats required.
