### ISSUE TITLE
Clicking Schema on graphql playground crashes the page

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#5719]
### What I'm trying to achieve
When the schema drawer to the right is clicked, the page crashes with the following errors
`TypeError: this.editor is undefined` and `TypeError: e.containerComponent is null`. Not sure if this is coming from saleor or from the playground package itself.

### Steps to reproduce the problem
1. open the graphql playground
2. open schema drawer

### What I expected to happen
To view the graphql schema.

**System information**
Operating system: Windows 10 x64

**Comment by maarcingebala** [comment]
Strange, it seems like the Playground is crashing with the current schema, but the schema is valid. Not sure what's causing the issue.

**Comment by Laendasill** [comment]
Seems like a bug in recent version of graphql-playground-react (1.7.23) Changing cdn link in playground.html:
https://github.com/mirumee/saleor/blob/ac7db9d50a714aadad360131729480ea0a95abb1/templates/graphql/playground.html#L9
to use 1.7.22 version will solve this problem for now.
`<script src="//cdn.jsdelivr.net/npm/graphql-playground-react@1.7.22/build/static/js/middleware.js"></script>`
