### ISSUE TITLE
Add GraphQL query for fetching staffNotificationRecipients

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#5721]
### What I'm trying to achieve
Currently the only way to manage which staff receive emails is through the GraphQL queries, as there is no UI for this on the dashboard. However, once `staffNotificationRecipient`s are created, there is no way to obtain their IDs to use in other mutations such as updating or deleting them.

### Describe a proposed solution
Add a GraphQL query to fetch `staffNotificationRecipients`.

**Comment by maarcingebala** [comment]
There is a field that returns this information in the `shop` query. You can use it like so:
```
{
  shop {
    staffNotificationRecipients {
      email
      id
      active
      user {
        email
      }
    }
  }
}
```

**Comment by khalibloo** [comment]
Ah I completely missed that. Thanks very much.
