### ISSUE TITLE
Backup and Restore feature on Dashboard?

### ISSUE THREAD

**Issue by blackyzero** [mirumee/saleor#5725]
### What I'm trying to achieve
Backup and Restore feature to local or S3 or network sharing.

### Describe a proposed solution
For backup or migration, support for Docker setup or regular Saleor setup.

### Other solutions I've tried and won't work

Postgresql backup and restore, but not sure it will be good solution and easy.

### Screenshots or mockups

Thank you.

**Comment by cyberdemic** [comment]
Here is a work around that I have been using to backup and restore the database as well as the media files using Docker.

**BACKUP**
This one liner creates a database dump file "offical_database.dump" as well as backs up the media files and compresses them into the file "media-files.tgz" and copies them to local directory.

docker-compose exec db pg_dump -U saleor -h localhost -F c -v -f official_database.dump saleor && docker cp $(docker ps --filter "name=api" -q):/app/media/ ./media && tar -czvf media-files.tgz media/ && rm –rf ./media && docker cp $(docker ps --filter "name=db" -q):/official_database.dump . 

**RESTORE**
This one liner starts the app, uncompresses the media files and copies them in, and uses pg_restore to restore the database using the "official_database.dump" file from backup command above.

COMPOSE_HTTP_TIMEOUT=300 docker-compose up -d && tar -zxvf media-files.tgz && docker cp media/ $(docker ps --filter "name=api" -q):/app/ && rm -rf media/ && docker-compose exec -T db pg_restore --no-owner -U saleor -C -d saleor -F c -v < official_database.dump 


I hope this helps.

**Comment by maarcingebala** [comment]
Hey, we're not planning to add any features related to database backup. Most hosting providers support various backup options and you should rely on what your provider recommends. For local development or custom deployments, methods like @cyberdemic describes should help.
