### ISSUE TITLE
npm run build-assets

### ISSUE THREAD

**Issue by Alquimar** [mirumee/saleor#5733]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build-assets' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose stack Error: missing script: build-assets
4 verbose stack     at run (/usr/share/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/share/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/share/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/share/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/share/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:300:12
4 verbose stack     at /usr/share/npm/node_modules/graceful-fs/graceful-fs.js:76:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd /home/alquimar/Documentos/Projetos/Saleor/saleor
6 error Linux 5.3.0-53-generic
7 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build-assets"
8 error node v8.10.0
9 error npm  v3.5.2
10 error missing script: build-assets
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by maarcingebala** [comment]
Hey, the `build-assets` command is not used anymore in Saleor 2.10, you can just skip it. We recommend using [saleor-platform](https://github.com/mirumee/saleor-platform)  for local development. See the [installation docs](https://docs.saleor.io/docs/developer/installation) for more details.
