### ISSUE TITLE
Broken link on project readme.

### ISSUE THREAD

**Issue by EndermanAPM** [mirumee/saleor#5756]
### What I'm trying to achieve
Navigate to the saleor Contributing Guide using the link located on line 140 on the readme.

https://github.com/mirumee/saleor/blob/master/README.md#L140

### Steps to reproduce the problem
1. Click on "Contributing Guide" in the readme
2. Profit!

### What I expected to happen
The browser navigates to the Contributing Guide, instead, I get a 404.

**Comment by maarcingebala** [comment]
Fixed, thanks for reporting!
