### ISSUE TITLE
Schema is not loading on demo.

### ISSUE THREAD

**Issue by zlosliwa** [mirumee/saleor#5788]
### What I'm trying to achieve
Open the schema tab in playground on demo(https://pwa.demo.saleor.rocks/graphql/).

### Steps to reproduce the problem
1. Go to https://pwa.demo.saleor.rocks/graphql/
2. Click on the "Schema" tab

### Screenshots

![image](https://user-images.githubusercontent.com/29308910/84686901-16497480-af3d-11ea-9757-260ac43c8260.png)

**System information**
Operating system:
Ubuntu 18.4
Browsers:
Fierfox / Chrome
WIn 10:
Firefox/Chrome

**Comment by fowczarek** [comment]
Same issue on local(master).

**Comment by maarcingebala** [comment]
Same as https://github.com/mirumee/saleor/issues/5719.

**Comment by maarcingebala** [comment]
Closing in favor of #5719
