### ISSUE TITLE
Stripe - A token may not be passed in as a PaymentMethod. Instead, use payment_method_data with type=card and card[token]

### ISSUE THREAD

**Issue by thomasjiangcy** [mirumee/saleor#5799]
### What I'm trying to achieve
Complete a checkout with Stripe as the payment method.

### Steps to reproduce the problem
1. Add keys to Stripe plugin
2. Retrieve token via StripeJS/Elements
3. Mutation createCheckoutPayment(...)
4. Mutation completeCheckout(...)

### What I expected to happen
Checkout to be completed, instead it throws an error

### Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/20501235/85039055-e6f36b80-b1b9-11ea-940b-436b93fcf8fe.png">

**System information**
Operating system:
MacOS Cataline 10.15.5
Running Saleor with Docker

**Comment by IKarbowiak** [comment]
Hi @thomasjiangcy,

Which version of Saleor are you using? I've just tested it with our storefront and everything works correctly. Please send exact mutation with input variables that cause the problem.

**Comment by Adeolamorren** [comment]
Hi I used the latest version of Saleor, and I'm experieincing the same issue version 2.10, I get the same error....

**Comment by jonathanawesome** [comment]
We're also experiencing this checkoutError on 2.10. It's happening after we call the `checkoutComplete` mutation with a valid checkoutId, which is being called after we await a call to `checkoutPaymentCreate` which contains a token that we've previously obtained from Stripe. 

The specific error we're receiving is ""A token may not be passed in as a PaymentMethod. Instead, use payment_method_data with type=card and card[token]=<% our_valid_stripe_token_here %>."

@IKarbowiak I had a look through the release notes and didn't find mention of a fix for this. When you tested, on which version did you run your tests?

**Comment by markedwards** [comment]
Doesn't the Stripe integration in Saleor expect a `paymentMethod.id` instead of a token?  Docs here: https://stripe.com/docs/payments/accept-a-payment-synchronously

**Comment by korycins** [comment]
Hey, for Saleor3.0 we fully rebuild a Stripe plugin. It uses custom payment flow and payment intents. Here you can find more details - code: #7452 docs: mirumee/saleor-docs#277
It has support for 3ds also and async communication with Stripe (Stripe's webhooks)
