### ISSUE TITLE
Cannot add new products to cart, stock quantity is failling

### ISSUE THREAD

**Issue by consultantsdei** [mirumee/saleor#5808]
### What I'm trying to achieve
After i create a new product in the dashboard, and it correctly shows in the storefront.

Im unable to add it to the cart, showing me an error 'out of stock'

It has enough items in the inventory as show below
…

### Steps to reproduce the problem
1. Create a product
2. Add product to cart

### What I expected to happen
Product is added to cart and ready to checkout

…

### Screenshots

request
![image](https://user-images.githubusercontent.com/58126707/85173259-c7535600-b240-11ea-9424-4656c2474375.png)
response
![image](https://user-images.githubusercontent.com/58126707/85173204-abe84b00-b240-11ea-8831-a7017349055e.png)
error logged in toast
![image](https://user-images.githubusercontent.com/58126707/85173317-f9fd4e80-b240-11ea-83bd-e7fe36d21631.png)
dashboard1
![image](https://user-images.githubusercontent.com/58126707/85173791-0a61f900-b242-11ea-81c7-b5a28e2bba92.png)
dashboard2
![image](https://user-images.githubusercontent.com/58126707/85173819-164dbb00-b242-11ea-9e29-9f93763fbd6f.png)

**System information**
Operating system: Windows
Saleor version: 2.0

**Comment by karolkielecki** [comment]
It seems you are using the older version. Please update Saleor components to the latest ones. 
- https://github.com/mirumee/saleor-dashboard/releases/tag/2.10.0
- https://github.com/mirumee/saleor/releases/tag/2.10.1
- https://github.com/mirumee/saleor-storefront/releases/tag/2.10.2

**Comment by drimailorr** [comment]
Hey @karolkielecki 
Thanks for the great product.
with the newest stack 
![image](https://user-images.githubusercontent.com/10425369/88479118-9eb42f80-cf55-11ea-8ce4-cb0478ec3cba.png)

I'm still getting the same issue:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/10425369/88479150-bc819480-cf55-11ea-8739-7f406854260c.png">

Default country = US
Wharehouse is in US
Shipping method has USA assigned country
Wharehouse is added to corresponding shipping method
Billing address country = USA

What's missing ?
Please assist

**Comment by jason-beach** [comment]
+1

**Comment by ohld** [comment]
+1

**Comment by garyrvaz** [comment]
> Hey @karolkielecki
> Thanks for the great product.
> with the newest stack
> ![image](https://user-images.githubusercontent.com/10425369/88479118-9eb42f80-cf55-11ea-8ce4-cb0478ec3cba.png)
> 
> I'm still getting the same issue:
> 
> <img alt="image" width="490" src="https://user-images.githubusercontent.com/10425369/88479150-bc819480-cf55-11ea-8739-7f406854260c.png">
> 
> API response on product:
> {
> "data": {
> "product": {
> "name": "partizan",
> "isAvailable": false,
> "variants": [
> {
> "name": "6-percent",
> "id": "UHJvZHVjdFZhcmlhbnQ6Nw=="
> }
> ],
> "isPublished": true,
> "category": {
> "name": "beer"
> }
> },
> "productVariant": {
> "trackInventory": false,
> "quantityAvailable": 50
> }
> }
> }
> 
> API response says that "quantityAvailable": 50
> but product "isAvailable": false
> 
> Default country = US
> Wharehouse is in US
> Shipping method has USA assigned country
> Wharehouse is added to corresponding shipping method
> Billing address country = USA
> The same above error if I toggle "Track Inventory" or not.
> 
> What's missing ?
> Please assist

I think this may happen when saleor has picked the country from the ip
```
def country(get_response):
    """Detect the user's country and assign it to `request.country`."""

    def _country_middleware(request):
        client_ip = get_client_ip(request)
        if client_ip:
            request.country = get_country_by_ip(client_ip)
        if not request.country:
            request.country = Country(settings.DEFAULT_COUNTRY)
        return get_response(request)

    return _country_middleware
```
This sets the `country` attribute of the graphQL context. So you have configured everything to serve US but if they're visiting from outside, it won't work.

**Comment by garyrvaz** [comment]
Also,
The country picked from the context is used to set the country for a checkout model instance, which gives the 0 stock quantity error when it checks for stock in the country set for the checkout instance which was initially set from the context which got the country from the middleware.
```
@classmethod
    def clean_input(cls, info, instance: models.Checkout, data, input_cls=None):
        cleaned_input = super().clean_input(info, instance, data)
        user = info.context.user
        country = info.context.country.code

        # set country to one from shipping address
        shipping_address = cleaned_input.get("shipping_address")
        if shipping_address and shipping_address.country:
            if shipping_address.country != country:
                country = shipping_address.country
        cleaned_input["country"] = country

        # Resolve and process the lines, retrieving the variants and quantities
        lines = data.pop("lines", None)
        if lines:
            (
                cleaned_input["variants"],
                cleaned_input["quantities"],
            ) = cls.process_checkout_lines(lines, country)

        cleaned_input["shipping_address"] = cls.retrieve_shipping_address(user, data)
        cleaned_input["billing_address"] = cls.retrieve_billing_address(user, data)

        # Use authenticated user's email as default email
        if user.is_authenticated:
            email = data.pop("email", None)
            cleaned_input["email"] = email or user.email

        return cleaned_input
```

```
@classmethod
    @transaction.atomic()
    def save(cls, info, instance: models.Checkout, cleaned_input):
        # Create the checkout object
        instance.save()
        country = cleaned_input["country"]
        instance.set_country(country, commit=True)

        # Retrieve the lines to create
        variants = cleaned_input.get("variants")
        quantities = cleaned_input.get("quantities")

        # Create the checkout lines
        if variants and quantities:
            for variant, quantity in zip(variants, quantities):
                try:
                    add_variant_to_checkout(instance, variant, quantity)
                except InsufficientStock as exc:
                    raise ValidationError(
                        f"Insufficient product stock: {exc.item}", code=exc.code
                    )
                except ProductNotPublished as exc:
                    raise ValidationError(
                        "Can't create checkout with unpublished product.",
                        code=exc.code,
                    )
            info.context.plugins.checkout_quantity_changed(instance)
        # Save provided addresses and associate them to the checkout
        cls.save_addresses(instance, cleaned_input)
```
So a checkout instance is created the moment a user adds something to their cart.

Here as you can see, when checkout is created, it depends on the country coming from shipping or billing address, which will work if the user is registered and has already saved that information. But for a user who is a guest it will fail if their IP is from outside the default country you have set.
