### ISSUE TITLE
Cannot query field "price" on type "ProductVariant". Did you mean "pricing"?

### ISSUE THREAD

**Issue by victorias** [mirumee/saleor#5809]
### What I'm trying to achieve
Setting up 2.10.1

### Steps to reproduce the problem
1. Set up a fresh database. 
2. Try to add a new product thru dashboard.
3. Get error: `Cannot query field "price" on type "ProductVariant". Did you mean "pricing"?`

### What I expected to happen
Product is added successfully.

**Comment by adavie1** [comment]
I have the same issue.

**Comment by neerajgupta2407** [comment]
@victorias @adavie1  Which dashboard version/ Saleor core version you are using? I recently installed saleor and working fine with stable branches of Dashboard and Saleor Core.

**Comment by d-wysocki** [comment]
Hey, for a while the master branch of dashboard and saleor was not synchronized. Now it is fixed and you can update saleor's master branch to resolve this issue.

**Comment by aKamrani** [comment]
I have the same issue on version 2.10.1 release.

**Comment by d-wysocki** [comment]
@aKamrani if you are using master branch of dashboard, you should also update master branch of saleor. Today we merged PR which resolve this issue.

**Comment by adavie1** [comment]
After `git pull` it's fixed for me.
