### ISSUE TITLE
Cannot register a new account on the demo

### ISSUE THREAD

**Issue by kyeljmd** [mirumee/saleor#581]
I tried running the getting started of Saleor. Upon running, I can't seem to find in the docs  for registering a user. I tried registering and it's saying it was sent to my email but I did not find any

**Comment by bogdal** [comment]
@kyeljmd Right now `Saleor` supports the `SendGrid` service which we use on Heroku. You can [deploy](https://heroku.com/deploy?template=https://github.com/mirumee/saleor/) the app once again to have everything configured by default.

**Comment by kyeljmd** [comment]
@bogdal Is it possible to not use sendgrid at all for registration?

**Comment by bogdal** [comment]
You can set your own email service using `EMAIL_URL` environment variable or (assuming that you don't have `SendGrid` addon) check the logs of your application where you should find the contents of all your emails.

**Comment by Pacu2** [comment]
Documentation was added for `EMAIL_URL` https://saleor.readthedocs.io/en/latest/gettingstarted/configuration.html
