### ISSUE TITLE
Order creation webhook doesn't send data with "application/json"

### ISSUE THREAD

**Issue by thomasjiangcy** [mirumee/saleor#5814]
### What I'm trying to achieve
Send order data to a web server via webhooks

### Steps to reproduce the problem
1. Create a simple server that prints out the JSON request body
2. Create a order creation webhook pointing to this server
3. Create a new order
4. Observe that the JSON request body sent to the server is empty

### What I expected to happen
Order data should be sent as JSON body

### Screenshots
<img width="409" alt="image" src="https://user-images.githubusercontent.com/20501235/85254204-4db2a680-b492-11ea-9272-c5a51cd69b98.png">

Second line is `console.log(req.body)` in an example expressjs server with `body-parser` JSON parser

After modifying the file in `saleor/plugins/webhook/tasks.py` to add the `Content-Type: application/json` header when sending the data, it worked as expected.

**Comment by NyanKiyoshi** [comment]
Looks like it, we send no content-type headers. https://github.com/mirumee/saleor/blob/0e7267bb26405100fbbcd6864c4123139129c62d/saleor/plugins/webhook/tasks.py#L47-L50

cc. @maciekjablonski
