### ISSUE TITLE
Checkout process doesn't go ahead from "Address"

### ISSUE THREAD

**Issue by m-n9** [mirumee/saleor#5830]
### What I'm trying to achieve
…
Purchase a product via checkout.

### Steps to reproduce the problem
1. Go to store-front
2. Login with your credentials
3. Select category from home page
4. Select product.
5. Select product variant and quantity.
6. Click on add to basket
7. Open basket and checkout
8. Link is: "localhost:3000/checkout/address"
9. Enter new address or select existing address and click continue to shipping.
10. Nothing at all happens. In developer tools/network tab the api hits with status 200 with the following error: 
"errors": [{"message": "'User' object is not iterable", "locations": [{"line": 170, "column": 3}], "path": ["checkoutCreate"], 

### What I expected to happen
Move to shipping 

### Screenshots

![image](https://user-images.githubusercontent.com/40482995/85885876-81792d80-b7fe-11ea-99b0-6bfb6c017e07.png)

**System information**
Operating system: N/A
Browser: Chrome (83.0)

**Comment by maarcingebala** [comment]
@m-n9 I've checked it yesterday and it's a bug. We're on it.

**Comment by WahabShah23** [comment]
I am having the same issue as well, doesn't go ahead from address. Has it been solved?

**Comment by maarcingebala** [comment]
@WahabShah23 It should be fixed already on `master` branch of Saleor.

**Comment by WahabShah23** [comment]
Okay I will check and update here then, thank you.

**Comment by m-n9** [comment]
> Hey @m-n9, it looks like a backend issue. Which version of Saleor backend are you using? Did you make any customizations to the backend source code?

Hi, the Saleor backend version is 2.10.1 and no customizations were made. 

Checking the updated master branch now to see for the fix.
