### ISSUE TITLE
Action order_created should trigger order_update

### ISSUE THREAD

**Issue by korycins** [mirumee/saleor#5838]
`saleor/order/actions.py::order_created` should trigger order_updated.
Actions like - `saleor/order/actions.py::handle_fully_paid_order` or `saleor/order/actions.py::cancel_order` already do that.
```
    manager.order_fully_paid(order)
    manager.order_updated(order)
```

**Comment by maarcingebala** [comment]
We don't want to run "updated" hook when order is created. Now this action calls `order_created` manager hook which is more appropriate.
