### ISSUE TITLE
Broken Schema tab in playground

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#5841]
### What I'm trying to achieve
Read schema

### Steps to reproduce the problem
1. https://pwa.demo.saleor.rocks/graphql/
2. Click on 
![image](https://user-images.githubusercontent.com/5188636/86344486-a1737b80-bc5a-11ea-85b6-237c6c8b5c81.png)
3. Instead of schema, whole app breaks and I see only white screen

### What I expected to happen
Schema tab displayed correctly

**System information**
Operating system: Linux
Browser: both chrome and firefox

**Comment by fowczarek** [comment]
Duplicat: #5788

**Comment by krzysztofwolski** [comment]
Closing duplicate
