### ISSUE TITLE
Custom Domain for Google Cloud Storage Bucket

### ISSUE THREAD

**Issue by FaisalAbid** [mirumee/saleor#5848]
### What I'm trying to achieve
In the documentation there is a flag to assign a custom domain to an AWS S3 bucket, however you can't achieve the same thing for Google Cloud Storage

**Comment by frozenpixel** [comment]
Adding this below `GS_AUTO_CREATE_BUCKET` in your settings.py, and defining the variables in your environment file should work:

`GS_CUSTOM_ENDPOINT = os.environ.get("GS_CUSTOM_ENDPOINT", None)` 
`GS_DEFAULT_ACL = os.environ.get("AWS_DEFAULT_ACL", None)`

Notes: Your custom domain must be verified by Google first, and set `GS_DEFAULT_ACL` value to `publicRead` in the environment file. Not doing so will result in permission errors making your static files not load correctly.
