### ISSUE TITLE
Translate from English

### ISSUE THREAD

**Issue by Chhunneng** [mirumee/saleor#5859]
I translate change language from English but when I click another link it will change to English back and can not change language anymore except back to home page.

**Comment by NyanKiyoshi** [comment]
Hi, please provide the steps to reproduce.

**Comment by Chhunneng** [comment]
In the home page, I change from English to other language but when I click on a category the language will change to English again.

**Comment by maarcingebala** [comment]
It sounds like the old storefront from [legacy-views](https://github.com/mirumee/legacy-views)? We don't have this functionality in [Saleor Storefront](https://github.com/mirumee/saleor-storefront/) yet.
