### ISSUE TITLE
bug deprecate user token when it's not activated

### ISSUE THREAD

**Issue by wael-mohamed** [mirumee/saleor#5863]
### What I'm trying to achieve
deactivate a user

### Steps to reproduce the problem
1. deactivate a user or delete a customer
2. user still connected and has a token

### What I expected to happen
the token must be deprecated

**Comment by krzysztofwolski** [comment]
@korycins Do you know if that's still an issue?

**Comment by korycins** [comment]
@krzysztofwolski, I don't think so. We fully rebuild whole jwt layer.
