### ISSUE TITLE
InconsistentMigrationHistory @master

### ISSUE THREAD

**Issue by Dom4n** [mirumee/saleor#5886]
### What I'm trying to achieve
migrate in newest master (commit  053173ccc72c9d03d6f707fe78a8112940c1cf01)

error:
`django.db.migrations.exceptions.InconsistentMigrationHistory: Migration invoice.0001_initial is applied before its dependency order.0085_delete_invoice on database 'default'.`

### What I expected to happen
migrate successfully

**System information**
Operating system:
Linux

**Comment by tomaszszymanski129** [comment]
@Dom4n Cannot reproduce, tried newest master, everything migrates properly both on my db and newly created one. Migrations dependencies are also set correctly. Could you share more details about your environment? Are you using saleor platform? Have you switched branches from master to any different before the error occured?

**Comment by Dom4n** [comment]
@tomaszszymanski129 thank You for response, it looks like user error indeed. I can not reproduce it now.
Sorry for lost time and thanks for checking it. Probably I had something in database already.
