### ISSUE TITLE
Product repetitions in homepage featured products

### ISSUE THREAD

**Issue by przlada** [mirumee/saleor#5888]
On Home page `FEATURED` products, I'm getting multiple instances of the same product (number of instances seems to match the number of product variants). I think it is the issue with the backend because the Graphql query returns the same product multiple times.

### Screenshots

![image](https://user-images.githubusercontent.com/6453010/87536871-0b981180-c69a-11ea-8195-1295a2e26585.png)

**System information**
Saleor platform (docker)
[storefront 44940260295f1fd495036c237fb3ddb57407aef8](https://github.com/mirumee/saleor-storefront/commit/44940260295f1fd495036c237fb3ddb57407aef8)
[api 053173ccc72c9d03d6f707fe78a8112940c1cf01](https://github.com/mirumee/saleor/commit/053173ccc72c9d03d6f707fe78a8112940c1cf01)

**Comment by maarcingebala** [comment]
Hey, thanks for opening the issue, I've noticed this bug already a few days ago - I think it's related to data loaders which we added to optimize the homepage database queries. I suppose there is a missing `distinct` somewhere in the dataloader implementation that causes the issue.

**Comment by przlada** [comment]
example query presenting bug:
``` graphql
query FeaturedProducts {
    shop {
      homepageCollection {
        id
        products(first: 20) {
          edges {
            node {
              id
              name
              category {
                id
                name
              }
            }
          }
        }
      }
    }
  }
```

**Comment by przlada** [comment]
As you said @maarcingebala the bug was caused by missing `distinct` but not in the dataloader implementation. I found it in `ProductsQueryset` after some debugging (preceded by binary search in working and nonworking commits :smile:). Please take a look at PR  #5892
