### ISSUE TITLE
TypeError: resolve_connection() got an unexpected keyword argument 'max_limit'

### ISSUE THREAD

**Issue by nobel101** [mirumee/saleor#5916]
### What I'm trying to achieve
i managed to install saleor successfully but i'm facing some issues i don't know where to start solving or if the problem was my configurations so blew some snapshots  

### What I expected to happen
…

### Screenshots
the storefront keep loading like that
![Screenshot from 2020-07-24 15-40-15](https://user-images.githubusercontent.com/21107163/88397774-bad49700-cdc4-11ea-82ba-eae9c1e05234.png)
**and i'm getting error at the back end like that**
![Screenshot from 2020-07-24 15-39-47](https://user-images.githubusercontent.com/21107163/88397785-bdcf8780-cdc4-11ea-84b4-6cf734df3b8b.png)

Operating system: Linux Mint 19.3 Cinnamon

**Comment by maarcingebala** [comment]
Please reinstall your backend dependencies with “pip install -r requirementes.txt”. The issue is related to outdated version of graphene.
