### ISSUE TITLE
Country code price tags

### ISSUE THREAD

**Issue by bhavesh2699** [mirumee/saleor#5917]
Acc. to popularity of this project I am pretty much sure that different countries people may be forking this project.
As different countries has different currencies, it will help admin to set product prices accordingly.
Like I am from India, and I would like to set product prices in Indian currency with rupees symbol but I didn't found any way. So it may help other people who is using this project to build their shop online in different countries as well.
Hope to see this feature.

**Comment by Sarowar-neo** [comment]
export DEFAULT_COUNTRY=IN
 export DEFAULT_CURRENCY=INR
Check it:
https://github.com/neerajgupta2407/saleor_course_resources/blob/master/setup_saleor_core.txt

**Comment by bhavesh2699** [comment]
> export DEFAULT_COUNTRY=IN
> export DEFAULT_CURRENCY=INR
> Check it:
> https://github.com/neerajgupta2407/saleor_course_resources/blob/master/setup_saleor_core.txt

Thanks @Sarowar-neo
