### ISSUE TITLE
Bulk discounts

### ISSUE THREAD

**Issue by zefman** [mirumee/saleor#5918]
### What I'm trying to achieve
I would like to apply a percentage discount to products automatically when a certain quantity has been added to the basket. As far as I can see this can currently be achieved with discount vouchers but not with standard sales discounts.

### Describe a proposed solution
Probably the easiest solution would be to add the minimum requirements options that feature on the voucher discount settings to the sales discount settings. This would allow you to set a minimum quantity of products purchased before the percentage discount kicks in.

**Comment by cr0nex** [comment]
Alternatively, this use case can be addressed by product bundles that are coming in saleor 3.0:
https://spectrum.chat/saleor/saleor-3-0/saleor-3-0-product-bundles~d20d3b38-be69-4982-b27c-8fdf4a9bb89b
