### ISSUE TITLE
FATAL ERROR: while building the Dashboard

### ISSUE THREAD

**Issue by onelsonic** [mirumee/saleor#5964]
Hi there,
I keep getting the following error on a machine : when trying to build the Dashboard :

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

this seems to be a nodejs error saying there is not enough memory? Anyone encounter this issue?
The machine has 2GB of memory, is there any memory restrictions in order to build the Dashboard? (if yes it should me mentioned somewhere...)
Any chance to bypass this error?

Otherwise can I build the Dashboard files locally, to then deploy them online?
Thanks

**Comment by nalimhahs** [comment]
Not sure about the error but you can build it locally and then deploy them online.

**Comment by neerajgupta2407** [comment]
@onelsonic While building dashboard build, memory spikes to approx. 3 gb. 
So make sure to have 4gb available memory while building dashboard.

or as you have mentioned, you can build locally with appropriate environment variables and deployed to your servers.
