### ISSUE TITLE
Wrong Invoice pdf url if you change Online store url in Dashbaord.

### ISSUE THREAD

**Issue by subodhu** [mirumee/saleor#6000]
### What I'm trying to achieve
The graphql api is running in localhost:8000 and storefront is running in localhost:3000. So I changed the url of my store as show in below screenshot. But when I was trying to view the invoice sent on email I can't open it. 

### Steps to reproduce the problem
1. Change the url of online store in Dashboard.
2. Generate and send the invoice to Customer.
3. Open the link in your email.

### What I expected to happen
Expected to view the invoice.
I think the url should be graphql_api host + media url but the email is sent with storefront_host + media url.

### Screenshots

![Site Settings ](https://user-images.githubusercontent.com/7992170/90238671-0b7c6480-de46-11ea-9a6c-29dbb1d83754.png)
![ Invoice 1 08 2020 ](https://user-images.githubusercontent.com/7992170/90238719-1c2cda80-de46-11ea-9590-7a7b5b743457.png)

When opening the link it gives this error:
![image](https://user-images.githubusercontent.com/7992170/90239279-f94ef600-de46-11ea-8f9a-62b79baa3708.png)

**System information**
Operating system: Arch linux

**Comment by IKarbowiak** [comment]
Hi, the link does not work because the `URL` in configuration should be a backend domain. So in your case, it should be  `localhost:8000`.

**Comment by subodhu** [comment]
Thanks @IKarbowiak . It does work if I put backend url in `URL` configuration. But then in sign up confirmation email the backend url is shown as `in order to log into localhost:8000`,  shouldn't this be frontend url like `in order to log into localhost:3000`. 
And I think it would be less confusing if the input label `URL of your online sotore` is changed to something link `URL of API` or `Backend URL`.
![image](https://user-images.githubusercontent.com/7992170/90478323-bb0a4d00-e14c-11ea-992b-cbb21c3f8418.png)

**Comment by maarcingebala** [comment]
In the dashboard, there is also a field "Name of your store" and if I'm correct, this should be the value that is used in templates like "In order to log into <name of you store>". If we use the backend domain there, maybe it's the issue with the templates?

**Comment by subodhu** [comment]
Yes the template is using backend domain.

https://github.com/mirumee/saleor/blob/4af8693bf2cad871ce19fc1d01d1b5497f44e7e2/templates/templated_email/account/confirm.email#L10-L12
So this `{{ domain }}` should be changed to `{{ stie_name }}`.
Do you want me to send pr with this change?

**Comment by maarcingebala** [comment]
I just checked and it seems most of the email templates use "domain" in the email body, while "site name" is only used in footers. I think it is a legacy from the old version of Saleor where everything (storefront, dashboard, backend) was hosted from the same domain. Now it doesn't make much sense and probably we should change it everywhere to "site name". @patrys Do you agree?

**Comment by patrys** [comment]
I agree. We should use the site name everywhere.

**Comment by maarcingebala** [comment]
@subodhu If you have time you can provide a PR witch replaces {{ domain }} with {{ site_name }} in email templates. Let me know if you can take it, otherwise I'll add it to our backlog.

**Comment by subodhu** [comment]
@maarcingebala Yes, I can take it.

**Comment by ashishkpaul** [comment]
**Store site settings are not visible**
I am using:
dashboard v3.7.8
core v3.7.22
![Screenshot_2022-10-12_16-12-14](https://user-images.githubusercontent.com/16308863/195323460-76a219d1-6dfd-4941-9e88-ff1bc50cc3f6.png)
