### ISSUE TITLE
Dashboard > configuration > staff members : unable to delete one member

### ISSUE THREAD

**Issue by onelsonic** [mirumee/saleor#6003]
I am logged in the Dashboard with another Admin user.
But I cannot delete this one : erica.ballard@example.com

I keep getting a red error.
![2020-08-14 18_35_50-erica ballard@example com _ Bfirst1 com](https://user-images.githubusercontent.com/53947594/90272182-4e960200-de5d-11ea-959e-78fb802a1175.png)

**Comment by onelsonic** [comment]
more on this one it seems that if you have a list of staff users, if you start deleting the staff, the last one cannot be deleted.

**Comment by maarcingebala** [comment]
Hey, can you check in the devtools console what is the mutation response? It looks like a validation error from API which may not be properly handled in the UI. In general, there are some rules around staff users and their permissions. For example, this particular user may have some permissions that you don't have or is the last person who has a particular permission. In such cases, you cannot remove such a user because you'd lost a access to that permission.

**Comment by onelsonic** [comment]
when building a superuser (John Doe) was created using : python manage.py createsuperuser
this superuser appears in the Staff section but does not have the Permissions settings showing up:
<img width="896" alt="2020-08-17 14_34_23-john@doe com _ Bfirst1 - Create Play Repeat" src="https://user-images.githubusercontent.com/53947594/90396614-d1ee6800-e096-11ea-9f23-fa6a6b782ed3.png">

Then we try to delete all existing staff members from the example database:
These members do have the Permissions settings showing up:
<img width="895" alt="2020-08-17 14_33_22-cheryl haynes@example com _ Bfirst1 - Create Play Repeat" src="https://user-images.githubusercontent.com/53947594/90396677-e7639200-e096-11ea-9c4f-764ffa30a494.png">
And the last of them cannot be removed.
The superuser should be the one we cannot remove and be able to remove all other staff members and should have all the given permissions when being created.
When trying to delete the last staff member (out of the superuser) the red error pops-up.

In the developer tools console I get the below :  
I guess the mutation error number is 164, not sure... , see below.

```
dashboard.97dba1ba95c56143b7c0.js?bea04ba54eca0dbe0bdf:164

 Uncaught Error: Value PermissionDenied not found in enum
    at Xd (dashboard.97dba1ba95c56143b7c0.js?bea04ba54eca0dbe0bdf:164)
    at mi (dashboard.97dba1ba95c56143b7c0.js?bea04ba54eca0dbe0bdf:164)
    at Array.some (<anonymous>)
    at dashboard.97dba1ba95c56143b7c0.js?bea04ba54eca0dbe0bdf:164
    at Object.next (dashboard.97dba1ba95c56143b7c0.js?bea04ba54eca0dbe0bdf:155)
    at b (dashboard.97dba1ba95c56143b7c0.js?bea04ba54eca0dbe0bdf:147)
    at y (dashboard.97dba1ba95c56143b7c0.js?bea04ba54eca0dbe0bdf:147)
    at t.value (dashboard.97dba1ba95c56143b7c0.js?bea04ba54eca0dbe0bdf:147)
    at b (dashboard.97dba1ba95c56143b7c0.js?bea04ba54eca0dbe0bdf:147)
    at y (dashboard.97dba1ba95c56143b7c0.js?bea04ba54eca0dbe0bdf:147)
```
