### ISSUE TITLE
ability to move over or copy subcategory from one category to another.

### ISSUE THREAD

**Issue by onelsonic** [mirumee/saleor#6006]
At the moment it is not possible from the Dashboard to easily move or copy subcategories from one category to another.
It will be great to have this function in order to move products in the store.

**Comment by AlexandrST** [comment]
How can this be done now? through graphQL ?

**Comment by mostghoste** [comment]
This issue was closed, but the dashboard still does not have any way to reparent a category. GQL also doesn't seem to support this action. Beware, for if you're reading this, you'll be doing some hacky bullshit soon.

**Comment by mostghoste** [comment]
For anyone who needs to reparent categories without deleting and recreating them, you can do it directly via the
  Django shell. Category extends MPTTModel, so use move_to() which correctly updates all MPTT tree fields:

```
  from saleor.product.models import Category

  parent = Category.objects.get(pk=NEW_PARENT_PK)
  for pk in [CHILD_PK_1, CHILD_PK_2]:
      cat = Category.objects.get(pk=pk)
      cat.move_to(parent, position='last-child')
```

  To get the integer PKs from GraphQL IDs, just base64-decode them - e.g. Q2F0ZWdvcnk6OTcw → Category:970 → pk 970.
