### ISSUE TITLE
PageFilterInput doesn't work

### ISSUE THREAD

**Issue by almousa1990** [mirumee/saleor#6010]
### What I'm trying to achieve
use "search" filter on pages query (using latest version -master-)

### Steps to reproduce the problem
1. use PageFilterInput "search" to filter results
2. It is ignored, all results are displayed

### What I expected to happen
show only filtered results

### Screenshots

**System information**
Operating system:

**Comment by maarcingebala** [comment]
I'm testing that on master and it works, when having two pages in the system I can use this input to search pages. The search takes page title and content into account. Can you provide more details about your case and how to reproduce the error?

**Comment by almousa1990** [comment]
My bad, sorry
