### ISSUE TITLE
Change storefront homepage 

### ISSUE THREAD

**Issue by pupattan** [mirumee/saleor#6055]
Unable to find how to change storefront homepage from the documentation
Is it possible to do from dashboard ?
If code changes require, where exactly codes need to be changed ?

**Comment by balibebas** [comment]
Take a look at `AppRoutes.tsx`. You'll want to adjust the `component` used for the `Route` with the `baseUrl`.

**Comment by maarcingebala** [comment]
This is a storefront issue, please refer to the README in saleor-storefront repo.
