### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by pupattan** [mirumee/saleor#6057]
I am trying to install saleor referring to page https://docs.saleor.io/docs/developer/installation/windows
When i do migrate the following issue is showing 

`
OSError: cannot load library 'gobject-2.0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0'`

Note: The requirements.txt was installed successfully

**Comment by pupattan** [comment]
I found the issue. Thanks

**Comment by anyaoqi** [comment]
@pupattan  I met the same problem. How did you solve it?

**Comment by loveJasmine** [comment]
me too

**Comment by AnthonyDreams** [comment]
Following this https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows is how I solve this
