### ISSUE TITLE
High CPU consumption when using Docker

### ISSUE THREAD

**Issue by arvandf** [mirumee/saleor#6063]
When running Saleor on Docker (for Windows 10 and Mac), the CPU usage goes above 50% (for a core i-7)at times even when the site is not used.  Is this caused by a background task or is it a bug?
This issue was previously reported for Mac as well in [here ](https://github.com/mirumee/saleor/issues/4409)

### Steps to reproduce the problem
1. Run Saleor on Docker

**System information**
Operating system:
Windows 10

**Comment by balibebas** [comment]
How many cores is your processor? Here's what I see running the stack on an i9:

<img width="839" alt="Screen Shot 2020-09-07 at 01 49 29" src="https://user-images.githubusercontent.com/65664227/92331920-8c78f580-f0ac-11ea-9ecb-16ff0b26286b.png">

**Comment by tegila** [comment]
```
root        3225 **50.2**  8.0 1531884 967512 ?      Rl   Sep23 446:15 /usr/local/bin/node --max-old-space-size=2048 /app/node_modules/fork-ts-checker-webpack-plugin/lib/service.js
```

Just found this issue and want to check my docker instance and got this process using near to 50% of my 16 core machine. 8% Mem. [centos 8 linux xen virtual machine]

Git checkout to version 2.11.0-rc.3 running saleor-platform in development environment. 
Production environment build is working but docker-compose.yml is only setup to environment and i'm new to this project so still somethings missing before I can help.

I'll try to fix the production environment to get rid of this hungry dev process.

**Comment by ellicodan** [comment]
I also experienced high CPU load with Saleor running idle. Running in a Docker container on Windows 11. The fix for me was to add `--noreload` to the `runsever` command when starting Saleor.

Here's link to this issue:
[https://superuser.com/questions/867067/djangos-dev-server-causes-permanent-high-cpu-load-with-python-3](url)
