### ISSUE TITLE
Cannot make productvariantBulkCreate request with a Bearer token

### ISSUE THREAD

**Issue by Shubhaankar-sharma** [mirumee/saleor#6070]
I was trying to create a product and the create its variant...
so i was testing the api out and it seems that with the bearer token i can create the token but cannot create the productvariants in bulk as it doesnt recognize the node

**but if i set the authorization to a JWT token then it works

Version Saleor Core 2.10 latest stable version deployed on heroku everything else works fine

**Comment by maarcingebala** [comment]
I'm not sure if I understand the issue. This mutation requires admin permissions so you need to pass a valid JWT token to run it.

**Comment by Shubhaankar-sharma** [comment]
how would i generate a jwt token? i currently inspect and take the jwt token from the request headers
