### ISSUE TITLE
Inactive customer accounts are able to request and perform password reset

### ISSUE THREAD

**Issue by artdiev** [mirumee/saleor#6071]
### Steps to reproduce the problem
1. Create a customer through the dashboard or the API
2. Set the account to IsActive = False (**_User account active_** = unchecked)
3. Using the storefront or the API request the password reset using customer's email
4. Customer email should get the reset link (tested with MailHog)
5. Now, the user can use the link to change the password but cannot login because the account is still set as inactive

### What I expected to happen
…
One of the two options:
1) Inactive accounts _cannot_ request a password reset at all
2) If they _can_ request a reset, doing so should set their accounts as active automatically

**System information**
Operating system:
Saleor platform (docker), 2.10
Win 10

**Comment by maarcingebala** [comment]
IMO we shouldn't send password reset links for inactive accounts. In the mutation that triggers sending password reset links, we should add validation for that. If the account is inactive, a validation error should be returned.

**Comment by artdiev** [comment]
@maarcingebala Yes that is a behavior I would expect as well. I may be able to do a pull request for that in the next two weeks.
