### ISSUE TITLE
PayPal failure with discount

### ISSUE THREAD

**Issue by m-sanders** [mirumee/saleor#611]
Firstly I am not sure if this is a Saleor bug or a django-payments one. 

## Saleor steps

Given a cart with:

* A single product price: 100
* Shipping at: 5
* Discount: 5

`payments.paypal.PaypalProvider#get_transactions_data` generates the following data:

```
{
    'intent': 'sale', 
    'transactions': [
        {'amount': {
            'details': {
                'tax': '0.00', 
                'shipping': '5.00', 
                'subtotal': '95.00'
            },
        'total': '100.00', 
        'currency': 'GBP'}, 
        'item_list': {
            'items': [
                {
                    'price': '100.00', 
                    'name': 'Error',
                    'quantity': '1',
                    'currency': 'GBP',
                    'sku': 'SKU'}
                ]
            }, 
        'description': 'Order #53'
    }]
}
```

This results in a PayPal API 400:

`Item amount must add up to specified amount subtotal (or total if amount details not specified)`

---

From my Googling the recommended approach is to pass in an `item` with a negative amount.

**Comment by patrys** [comment]
Yes, it looks like we need to pass the discount.

**Comment by m-sanders** [comment]
The workaround we are using is to add it as purchased item with a negative amount in `saleor.order.models.Payment#get_purchased_items`.

```
        if self.order.voucher and self.variant == 'paypal':
            items.append(PurchasedItem(
                name=self.order.discount_name,
                sku='DISCOUNT',
                quantity=1,
                price=-self.order.discount_amount.net,
                currency=settings.DEFAULT_CURRENCY,
            ))
```

This feels hacky but might help anyone else who is facing this issue right now.
