### ISSUE TITLE
Create a test settings file

### ISSUE THREAD

**Issue by rasovica** [mirumee/saleor#6122]
### What I'm trying to achieve
If you change some of the most common things people change in the settings file, like `DEFAULT_CURRENCY` or `LANGUAGES` around 70 tests get broken.

### Describe a proposed solution
I propose there should be a settings file that gets loaded for tests.

### Other solutions I've tried and won't work
Fixing by hand but it would take so long that I ended up detecting tests and defaulting back to original values if tests are running. It would be nice if this would happen out of the box

**Comment by patrys** [comment]
There is such a file in the `tests` directory. It's either lacking the necessary overrides for the settings you mention, or the related tests make assumptions about what settings are set and should instead use the `settings` fixture to ensure certain configuration.

**Comment by rasovica** [comment]
Sorry for not looking good enough into it. But yeah as you said it is lacking some of the overrides and it results in quite many tests failing... I think its very reasonable to assume those two would be changed quite often.
