### ISSUE TITLE
Adapt backend to support switchable templates

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#613]
To provide a feature introduced in #610 we should adapt backend to support multiple switchable themes.

A few initial assumptions:
* A theme is a reusable django app that provides theme-specific templates and static assets
* Themes are distributed as packages on PyPI and have versions
* Core saleor installation has basic theme as a requirement and requires latest available version of this theme

Ideas for future:
* Developer documentation should be provided to make theming easier for new developers (template names, available variables, available API endpoints etc)
* Themes may deliver a standard style-guide as a part of documentation (maybe it's possible to generate style guide automatically?)

@krzysztofwolski What do you think about it?

**Comment by patrys** [comment]
I don't see how we could provide PyPI-installable themes for something forkable by design?

**Comment by artursmet** [comment]
@patrys Ok, so probably not PyPI-installable, we can add github repository address in requirements, themes can be versioned like saleor itself, what do you think?

**Comment by patrys** [comment]
I think it would be easier to support themes in the same tree. Just add whichever you want to INSTALLED_APPS. The problem is how do we make sure they are all maintained?

**Comment by artursmet** [comment]
We decided to don't implement this. Changes will be too hard to maintain in the backend.
