### ISSUE TITLE
Cannot fulfill order when product quantity is 1

### ISSUE THREAD

**Issue by cyberdemic** [mirumee/saleor#6136]
### What I'm trying to achieve
I'm trying to fulfill an order in the dashboard where a product has a quantity of 1

### Steps to reproduce the problem
1. Create a product with quantity of 1
2. Create an order and add that product to the order and finalize/pay for it.
3. Try to fulfill the order and shows 0 in stock.

### What I expected to happen
I expect to be able to fulfill the order 

### Screenshots
Before order
![quantity](https://user-images.githubusercontent.com/54118049/93289985-8a8df100-f794-11ea-913a-ca6c960525f3.png)

Dashboard fulfillment after order is placed
![dashboard-quantity](https://user-images.githubusercontent.com/54118049/93290002-95488600-f794-11ea-89fe-5a50a190f6dc.png)

### Other info
After placing the order (and still unable to fulfill it) the product in the dashboard still shows a quantity of 1. However, the Storefront properly shows the product being out of stock.

**Comment by karolkielecki** [comment]
@cyberdemic Hey! Is it local development? What is your version of Saleor?

**Comment by cyberdemic** [comment]
@karolkielecki im using (Core 2.11.0-rc.4), (Dashboard 2.11.0-rc.4), and (Storefront 2.11.0-rc.2)

**Comment by cyberdemic** [comment]
If this isn't reproducible please let me know if possible

**Comment by cyberdemic** [comment]
I have updated to Core 2.11.0-rc.6, Dashboard 2.11.0-rc.6 and it still shows the same with 0 inventory (when having 1 in stock). However when I change to 1 / 0 and hit fulfill I get a couple error messages (posted below). If i hit back button, and go back to fulfill, it looks like product was fulfilled. I didn't see any place for adding tracking info.

## Errors
```
Uncaught Error: Error writing result to store for query:
 {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"AddressFragment"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Address"}},"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"city"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"cityArea"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"companyName"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"country"},"arguments":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"code"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"country"},"arguments":[],"directives":[]}]}},{"kind":"Field","name…
```

```
Uncaught (in promise) TypeError: e.graphQLErrors is undefined
```

## Screenshot

![fulfill-item-1](https://user-images.githubusercontent.com/54118049/94476394-47188700-0185-11eb-85df-f9879ba00533.png)

**Comment by hardhikgupta** [comment]
I want to work on this issue please assign it to me. And also guide me @hardhikgupta

**Comment by karolkielecki** [comment]
@hardhikgupta Hi there! Thanks for your willingness to help with this issue. Our team has already started to work on it - so it's in progress. Thanks!
