### ISSUE TITLE
Filtering products by multiple attributes doesn't yield any results

### ISSUE THREAD

**Issue by KerryMahne** [mirumee/saleor#6141]
### What I'm trying to achieve
I am trying to get products by filtering over more than one attribute

### Steps to reproduce the problem
I've did this on a fresh installation of Saleor.
1. Add the color attribute to the product "Polo Shirt"
2. View the product and assign it the color "Cyan" or whichever you want
3. Try to filter on the dashboard for Material = cotton and Color = cyan

### What I expected to happen
I expected to get just the Polo Shirt product back, instead I've received nothing

### Screenshots
![cottonAndCyan](https://user-images.githubusercontent.com/23449297/93594496-3bbfa180-f9b6-11ea-965f-11c83c4c691a.png)
![cotton](https://user-images.githubusercontent.com/23449297/93594498-3c583800-f9b6-11ea-85f8-b01d9d3d58b6.png)
![cyan](https://user-images.githubusercontent.com/23449297/93594499-3cf0ce80-f9b6-11ea-92f1-9005da0d7320.png)

CURL: `curl 'http://localhost:8000/graphql/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:8000' --data-binary '{"query":"fragment Money on Money {\n  amount\n  currency\n  __typename\n}\n\nfragment ProductFragment on Product {\n  id\n  name\n  thumbnail {\n    url\n    __typename\n  }\n  isAvailable\n  isPublished\n  basePrice {\n    ...Money\n    __typename\n  }\n  productType {\n    id\n    name\n    __typename\n  }\n  __typename\n}\n\nquery ProductList($first: Int, $after: String, $last: Int, $before: String, $filter: ProductFilterInput, $sort: ProductOrder) {\n  products(before: $before, after: $after, first: $first, last: $last, filter: $filter, sortBy: $sort) {\n    edges {\n      node {\n        ...ProductFragment\n        attributes {\n          attribute {\n            id\n            __typename\n          }\n          values {\n            id\n            name\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    pageInfo {\n      hasPreviousPage\n      hasNextPage\n      startCursor\n      endCursor\n      __typename\n    }\n    __typename\n  }\n}\n","variables":{"filter":{"attributes":[{"slug":"color","values":["cyan"]},{"slug":"material","values":["cotton"]}],"categories":null,"collections":null,"isPublished":null,"price":null,"productTypes":null,"stockAvailability":null},"first":20,"sort":{"direction":"ASC","field":"NAME"}}}' --compressed`
**System information**
Operating system: Linux

**Comment by KerryMahne** [comment]
Any updated regarding this :)? I'd love to debug this, but I have limited django knowledge...

**Comment by maarcingebala** [comment]
Thanks for reporting, we'll confirm and fix the issue if it's valid.

**Comment by satyam2912** [comment]
can i fix this? if it is not fixed yet would love to debug it

**Comment by maarcingebala** [comment]
This issue is fixed by #6215.
