### ISSUE TITLE
pip install -r requirements.txt errors on windows

### ISSUE THREAD

**Issue by mikeres0** [mirumee/saleor#615]
I am receiving an error whilst running `pip install -r requirements.txt` on Windows 10. 

```
File "C:\Users\MikeR\AppData\Local\Temp\pip-build-1orwqvlb\uwsgi\uwsgiconfig.py", 
line 8, in <module>
        uwsgi_os = os.uname()[0]
AttributeError: module 'os' has no attribute 'uname'

```

I think this is purely because I'm on a Windows machine where `uname` isn't available. Is there a way around this?

Thanks 👍

**Comment by mikeres0** [comment]
@artursmet fantastic thanks :)

**Comment by patrys** [comment]
This is also a third party library issue. You can find pre-built wheels of `lxml` here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

**Comment by mikeres0** [comment]
@patrys Thanks
