### ISSUE TITLE
Elasticsearch (re-)integration

### ISSUE THREAD

**Issue by hacfi** [mirumee/saleor#6179]
### What I'm trying to achieve
I would like to have the products synched to Elasticsearch so I can perform a full-text search on the product catalog and have performant filtering options.

### Describe a proposed solution
Reintegrate Elasticsearch

I saw that Elasticsearch integration was removed in December 2019 but there is no documentation about why this was done. Was it removed because of a technical issue or just because you wanted to drop official support for it? cc @IKarbowiak

**Comment by maarcingebala** [comment]
Hey @hacfi, this integration was added a long time ago in the times of the "old", pre-GraphQL Saleor. Over time it was not really used by us in later versions and thus, not really maintained. We also didn't saw much additional value in it, having a Postgres database that does a great job for all the things in Saleor now.

I understand that some people might want to use Elasticsearch with Saleor, but this feature is not on the roadmap of the Saleor team. I think the integration should be implemented as a plugin or external service (app) that is maintained by people who know Elasticsearch better than us and actually use it with Saleor. We would be happy to offer guidance and assist the community if there are people willing to work on that.
