### ISSUE TITLE
CheckoutCreate mutation returns open checkout when creating new one

### ISSUE THREAD

**Issue by ApathyElement** [mirumee/saleor#6185]
### What I'm trying to achieve
…As a logged in user, i would like to create a new checkout via graph ql mutation, however an old checkout is returned. This is not what is specified in the graphql schema  checkoutcreate - description: Create new checkout

### Steps to reproduce the problem
1. login 
2. create one checkout
3. try create a new checkout and the old basket will be returned
This is causing an issue in the saleor-storefront #852 which causes a cart to be replaced by the cart of an old checkout when a new one is expected.

### What I expected to happen
I expected/ would like to see a new checkout created even though there is an old checkout in the database. Maybe there could be a graphql query to return the last open checkout for the user, to access abandoned checkouts from the storefront.

### Screenshots

**System information**
Operating system:

**Comment by maarcingebala** [comment]
Maybe the description is wrong but currently, this works as intended. We assume that logged in users have only one active checkout.

**Comment by ApathyElement** [comment]
I see, renaming the mutation description would solve the ambiguity, although it would still be a bit counter intuitive, because when I send the mutation with new lines which a previous checkout does not have, no matter which checkout gets returned, it is reasonable to expect to receive back a checkout with those lines added, not discarded. if you assume only one active checkout, merging or replacing the lines in the checkout would solve the bug in the saleor storefront #6185.

**Comment by rmelisson** [comment]
hey there, I agree with @ApathyElement, this should be stated explicitly, either in the mutation description or at least in the documentation here :
https://docs.saleor.io/docs/developer/checkout#creating-a-checkout-session
It's quite confusing to receive different lines than the one passed in the create checkout mutation.

Let me know if the documentation is open to contributions, I would submit a PR

Thanks for the work, great product !
