### ISSUE TITLE
improve documentation's consistency and accuracy

### ISSUE THREAD

**Issue by JavierOramas** [mirumee/saleor#6188]
Im trying to deploy the project on my personal server, and it has been a bit frustrating.

 you should include at least a note on the installation section including a link to the deployment section,
in the other hand i've had to look in the ver 2.9 documentation, beacuse the current one lacks some information present and way more explained in the older version 
 its agreat project, and im just trying to make it better for future users, thx and good work

**Comment by LeOndaz** [comment]
I think the whole documentation is a shame, no offense for them, but I can't even move myself there, the docker installation installs the local development version (why?) and some other frustrating things I've seen. The document says "node" is self explained when I hover over in graphql, however, I didn't understand it. It's just bad. I'm still trying to study it then I'll create my own guides later

**Comment by JavierOramas** [comment]
Agree, i found this https://youtu.be/zG7bZ2aPDko , im going to try it tonight, and will give feedback here

**Comment by karolkielecki** [comment]
@JavierOramas @LeOndaz Hey! Could you please provide more feedback on the docs and what is missing? Your suggestions will help improve them.

**Comment by sk1122** [comment]
Documentation needs to be updated drastically. We can write a in-depth guide on Installation and also Deploying it on Heroku. Also in the Dashboard section, there is only a link to it, instead, we can have a Detailed Overview of What is there in Dasbhboard? We can also improve the Storefront Section to be more detailed. These changes can help beginners to understand Saleor easily & make cool stores with it.

**Comment by sk1122** [comment]
I'm interested in working on Documentation

**Comment by karolkielecki** [comment]
@sk1122 Thanks for your feedback and willingness to help us with the docs. Could you please tell us what exactly is missing? What would you like to write about installation? Recently, we have updated our docs about Heroku deployment: https://docs.saleor.io/docs/next/developer/running-saleor/heroku. 

What do you mean by there is only a link to the dashboard section? You can find info about every section of the dashboard: https://docs.saleor.io/docs/dashboard/index

Currently, there is no storefront section, and I agree that we should start to work on it. For now, we have a readme section about modifying the storefront: https://github.com/mirumee/saleor-storefront#modifying-the-storefront

**Comment by sk1122** [comment]
@karolkielecki I was telling about Github Docs of Saleor. We could include small but important parts from docs.saleor.com to README.md. It will be helpful for developers or contributors to be on Github and not redirect to other sites for installation and we can also include a small overview of the dashboard.

**Comment by sk1122** [comment]
@karolkielecki Installation Section, We can include How to Setup a Project with Saleor or How to configure Saleor. It will be a small tutorial but it will help developers with no experience of Saleor to Configure and use it without problem.

**Comment by karolkielecki** [comment]
In my opinion, the readme sections include the most important information. They should also be not too long. More details about installation and deployment and a general overview should be in actual documentation: https://docs.saleor.io/docs/. I agree about tutorials - after the upcoming releases, I hope we can start to work on it.

**Comment by sk1122** [comment]
@karolkielecki I am also very excited to work on this.
