### ISSUE TITLE
Make TIME_ZONE and LANGUAGE_CODE configurable via env vars

### ISSUE THREAD

**Issue by maersu** [mirumee/saleor#6210]
(Thank you so much for your great work, I really love saleor!)

### What I'm trying to achieve

I would like to configure TIME_ZONE and LANGUAGE_CODE via env vars

### Describe a proposed solution

https://github.com/mirumee/saleor/pull/6209

**Comment by karolkielecki** [comment]
@maersu Hi there! Thanks for your PR and your kind words. We'll be happy to review it as soon as we can.

**Comment by maarcingebala** [comment]
Closing as we continued the discussion in the PR.
