### ISSUE TITLE
RemoveCheckoutPromoCode does not return an error if called with wrong promo code

### ISSUE THREAD

**Issue by tilman** [mirumee/saleor#6226]
### What I'm trying to achieve
call `mutation RemoveCheckoutPromoCode` with an not existing promo code and receive an error

### Steps to reproduce the problem
1. create an checkout
2. call `mutation RemoveCheckoutPromoCode` with an promo code that does not exist

### What I expected to happen
Receive an error in the GraphQL response in `errors: checkoutErrors` if the submitted promo code does either not exist or is not added to the current checkout.

**System information**
Operating system:
Saleor API running in docker

**Comment by karolkielecki** [comment]
@tilman Hi there! Thanks for reporting. I've passed the issue to our team. Could you please tell me what your version of Saleor is?

**Comment by tilman** [comment]
Thanks! It's Version 2.11, Rc 7.
