### ISSUE TITLE
SSLCommerz integration

### ISSUE THREAD

**Issue by nikolas310** [mirumee/saleor#6227]
Anyone has tried Bangladeshi popular payment gateway [SSLCommerz](https://www.sslcommerz.com/) 
Plugin: https://github.com/sslcommerz/SSLCommerz-Python
If anyone interested can share idea here?

**Comment by Jahintaqi-Chisty** [comment]
You have to make raw code . No need to use saleor plugin manager . Integrate SSL commerce separately  through api calling .

**Comment by nikolas310** [comment]
@Jahintaqi-Chisty can you show me any example
