### ISSUE TITLE
Demo site is down 

### ISSUE THREAD

**Issue by indrajitsinh** [mirumee/saleor#6245]
### What I'm trying to achieve
Trying to visit Storefront and Dashboard Demo Site

### Steps to reproduce the problem
1. Open storefront demo (https://pwa.saleor.io/) OR  Open Dashboard demo ( https://pwa.saleor.io/dashboard/ )

### What I expected to happen
I should able to visit Storefront and Dashboard demo sites

### Screenshots

**System information**
Operating system: Mac 
Browser: Chrome

**Comment by patrys** [comment]
We're in the process of moving the demo to its original domain: https://demo.saleor.io/, proper redirects will appear soon.

**Comment by indrajitsinh** [comment]
Thank you, let me close this issue.
