### ISSUE TITLE
product_updated webhook not triggered on image editing or repositioning

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#6247]
### What I'm trying to achieve
I expect the product_updated webhook to be triggered every time I make any kind of change at a product. Even when rearranging images or adding ALT tags to images. This is not the case right now.

I'm using the newest 2.11 version.

### Steps to reproduce the problem
1. Enable the product_updated webhook
2. Add an alt description to a product image.

### What I expected to happen
…

### Screenshots

**System information**
Operating system:

**Comment by karolkielecki** [comment]
@JannikZed Hey! What would you like to achieve? You can find more info in the section where is this triggered: https://github.com/mirumee/saleor/pull/6100

**Comment by JannikZed** [comment]
the purpose is pretty simple: I'm syncing product details to Mailchimp. So every change should trigger the webhook so that our service could change the appropriate data in a different system. Pretty much the basic use-case what webhooks are there for.

**Comment by maarcingebala** [comment]
Thanks for reporting @JannikZed. I agree, changing anything related to images should also trigger this webhook. I'll add it to our backlog.

**Comment by JannikZed** [comment]
amazing :)
