### ISSUE TITLE
Heroku AWS S3 settings

### ISSUE THREAD

**Issue by mikeres0** [mirumee/saleor#625]
Hi all, 

In my Heroku app I've gone to the settings tab, then to the config vars and entered the required details for the AWS stuff:
* `AWS_ACCESS_KEY_ID`
* `AWS_MEDIA_BUCKET_NAME`
* `AWS_SECRET_ACCESS_KEY`

As a result `/dashboard/products/` now returns a 500 error, but if I navigate to a product directly it works: `/products/3/update/`

**Comment by patrys** [comment]
Do you know what the error is? If not, try enabling `DEBUG` or adding yourself to the `ADMIN_EMAILS` setting.

**Comment by mikeres0** [comment]
Sorted, thanks
