### ISSUE TITLE
Add landing page

### ISSUE THREAD

**Issue by mikeres0** [mirumee/saleor#626]
I think Saleor would benefit from having the ability to set up a landing page from within the dashboard. So instead of the root showing products, you can have banners and other content set up instead. 

I envisage this being a tick box option or something along those lines. 

As an idea for a template, we could have a full width banner across the top with other blocks underneath:

```
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<!-- Full width banner -->
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-6">
			<!-- Content -->
		</div>
		<div class="col-xs-12 col-sm-6">
			<!-- Content -->		
		</div>
	</div>
	<!-- Further rows if required -->
</div>
```

The images for which can be specified in a similar fashion to the product images. 

Any thoughts on this?

**Comment by patrys** [comment]
While it's true that most stores use such landing pages, it may be hard to come up with something that fits all of these scenarios. Providing a CMS is a similar problem.

**Comment by mikeres0** [comment]
True, it wouldn't be the easiest of things to implement. I may give this a go locally.

**Comment by mikeres0** [comment]
If it was done purely with banner images which can be set in the admin, which are linked to different categories or products I think this would be achievable. We could ship a default template, which can be expanded upon. The only difficultly would be displaying the correct amount of file pickers for the 'sections' within the template. Do you have any thoughts on how this could be done? Here's a mock up that I've made on my test site. 
![landing page](https://cloud.githubusercontent.com/assets/5929943/20424015/8595c442-ad6b-11e6-82f3-0eb843ba6432.PNG)

**Comment by patrys** [comment]
We have similar layouts in many of our own projects. Often the difference is whether you want this to be dashboard-driven (add as many banners as you want, template displays them all) or template-driven (the designed decides what blocks/sizes are available, allow one banner for each template block). I think we're slowly crossing into CMS territory.

**Comment by mikeres0** [comment]
I suppose this would be the only CMS element. It would probably work better dashboard-driven in my opinion, but that would mean dynamically creating the template on the fly I guess?
