### ISSUE TITLE
Invoices generated from the dashboard are public

### ISSUE THREAD

**Issue by gax97** [mirumee/saleor#6270]
### What I'm trying to achieve
I am trying to protect invoices links

### Steps to reproduce the problem
1. Go into the dashboard
2. Generate invoice from order
3. Go to the invoice
4. Invoice link is public.

### What I expected to happen
I don't want to be able to open invoice links from incognito. e.g. there should be authentication when you want to see an invoice.

**System information**
Operating system:
macOS Catalina
Saleor 2.11.0-rc.8

**Comment by korycins** [comment]
Hey @gax97, 
In your expected scenario, how would you send the invoice link when the user is anonymous?

**Comment by karolkielecki** [comment]
@gax97 Hey! Thanks for pointing this out. The link is not possible to guess because a pdf file contains UUID. In fact, many stores and invoice programs work similarly - the link is sent by email and to download it there is no log in required
