### ISSUE TITLE
Saleor deployment to Docker fails when adding new packages

### ISSUE THREAD

**Issue by ebolasudan** [mirumee/saleor#6286]
### What I'm trying to achieve
I am trying to add additional packages to saleor but I can't get docker to build the image.

### Steps to reproduce the problem
1. add a package to requirements.txt_dev or pyproject.toml (like stream-django) and make sure build-python is installing from the correct file. (it fails no matter which method you use)
2. enable the app in settings files (it will not throw an error unless you try and call to the module in installed apps)
3. docker-compose up

### What I expected to happen
I want it to work but docker saleor service fails to build and returns error `ModuleNotFoundError: No module named 'stream_django'
ERROR: Service 'saleor' failed to build : The command '/bin/sh -c SECRET_KEY=dummy STATIC_URL=${STATIC_URL} python3 manage.py collectstatic --no-input' returned a non-zero code: 1`

I think the error occurs due to whatever is being compiled with the package not being copied over to the final build but I am brand new to dev and am too inexperienced to fix it. So any help would be appreciated 

## Dockerfile
`
FROM python:3.8 as build-python

RUN apt-get -y update \
  && apt-get install -y gettext \

  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml /app/
WORKDIR /app
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install 

FROM python:3.8-slim

ARG STATIC_URL
ENV STATIC_URL ${STATIC_URL:-/static/}

RUN groupadd -r saleor && useradd -r -g saleor saleor

RUN apt-get update \
  && apt-get install -y \
  libxml2 \
  libssl1.1 \
  libcairo2 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libgdk-pixbuf2.0-0 \
  shared-mime-info \
  mime-support \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY . /app
COPY --from=build-python /usr/local/lib/python3.8/site-packages/ /usr/local/lib/python3.8/site-packages/
COPY --from=build-python /usr/local/bin/ /usr/local/bin/
WORKDIR /app

RUN SECRET_KEY=dummy STATIC_URL=${STATIC_URL} python3 manage.py collectstatic --no-input

RUN mkdir -p /app/media /app/static \
  && chown -R saleor:saleor /app/

EXPOSE 8000
ENV PORT 8000
ENV PYTHONUNBUFFERED 1
ENV PROCESSES 4
ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["uwsgi", "--ini", "/app/saleor/wsgi/uwsgi.ini"]`

## error
`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 
401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 
377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup    
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 90, in create    module = import_module(entry)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stream_django'
ERROR: Service 'saleor' failed to build : The command '/bin/sh -c SECRET_KEY=dummy STATIC_URL=${STATIC_URL} python3 manage.py collectstatic --no-input' returned a non-zero code: 1`

**System information**
Operating system: it's dockerized using the same images from the saleor-platform repo

**Comment by karolkielecki** [comment]
@ebolasudan Hey! What is your version of Saleor? Did you follow our docs: https://docs.saleor.io/docs/developer/running-saleor/docker? Dockerfile is ready for production. If you use the saleor-platform repo, please bear in mind that it's been designed only for local development.

**Comment by ebolasudan** [comment]
@karolkielecki thank you for responding! I downloaded whatever was the most recent version under Saleor-platform. As for launching the platform, It works just fine as it, but I was looking to modify and add packages to the backend which is where I am running into issues.  So I am trying to do local development but I can't seem to get any packages to be found despite them being added to the requirements/poetry files and being installed via the docker configuration provided within saleor. even with the Dockerfile config, I provided above the only thing that's different than the repos is the installation of packages via poetry instead of the requirements.txt_dev file. but while I can get saleors original installed apps to behave fine, any additional app installed throws an error during the build process stating that the module was not found despite it being part of the install list. I'm stumped lol.

**Comment by ebolasudan** [comment]
nevermind turns out it was an issue on my end. i thought all the modules had installed but the ones i happened to reference didn't work because they failed because they were on a list of packages and one of them failed the entire list because it didn't work with python 3.8 so i got it working thanks

**Comment by karolkielecki** [comment]
Thanks for letting me know that it works now @ebolasudan.
