### ISSUE TITLE
Introduce ProductClass concept

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#629]
`ProductClass` model should represent single product type (for example Shirt, Book). It will simplify adding new products in the dashboard.

Suggested fields:
* `name`
* `has_variants` - Boolean that will enable or disable multiple variants interface in dashboard
* `product_attributes` - M2M to `Attribute` - these attributes will be available in `Product`
* `variant_attributes` - M2M to `Attribute` - these attributes will be available in `ProductVariant`

Example:
```python
ProductClass(
    name='Shirt',
    has_variants=True,
    product_attributes=[Attribute('Color')]
    variant_attributes=[Attribute('Size')]
)
```
It will allow us to simplify product variants filtering and search. Attributes on Product level will allow to create for example Red Shirt with various Sizes.

**Comment by patrys** [comment]
Might be a good place for `is_shipping_required` and `is_stock_required` as well.
