### ISSUE TITLE
Collection products default sort order not working properly

### ISSUE THREAD

**Issue by almousa1990** [mirumee/saleor#6316]
### What I'm trying to achieve
Saleor provides a mechanism to set sort_order on CollectionProduct, it also provides a mechanism to properly reorder products within collection.
Collection resolver should return products sorted by CollectionProduct sort_order if no sort input was provided. However, it seems products PrefetchingConnectionField will provide 'Slug' as default sort order if nothing was provided. Hence, ignoring CollectionProduct sort_order.

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
…

### Screenshots
![image](https://user-images.githubusercontent.com/4084573/97039677-77c9c180-1575-11eb-8411-1ff3eee75d69.png)
![image](https://user-images.githubusercontent.com/4084573/97039690-7b5d4880-1575-11eb-9345-e0fb77090a38.png)
![image](https://user-images.githubusercontent.com/4084573/97039699-7dbfa280-1575-11eb-9587-645e87807391.png)

**System information**
Operating system:

**Comment by almousa1990** [comment]
The issue was closed without resolution!

**Comment by maarcingebala** [comment]
@almousa1990 Slugs are used as a default sorting value. Here is the example query to fetch a collection with products sorted by the collection-specific order; note that we use  `sortBy: { field: COLLECTION, direction: ASC }` params on the nested `products` field:

```graphql
{
  collection(id: "Q29sbGVjdGlvbjoz") {
    id
    name
    products(first: 5, sortBy: { field: COLLECTION, direction: ASC }) {
      edges {
        node {
          id
          name
        }
      }
    }
  }
}
```

An example mutation to move a product  within the collection by two positions forward:
```graphql
mutation {
  collectionReorderProducts(
    collectionId: "Q29sbGVjdGlvbjoz"
    moves: [{ productId: "UHJvZHVjdDo2MQ==", sortOrder: 2 }]
  ) {
    collectionErrors {
      field
      message
    }
  }
}```
