### ISSUE TITLE
Attributes in Product model

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#632]
Add attributes support ad `Product` instance level to provide better filtering API.
 
Refs #629

**Comment by artursmet** [comment]
We need to create architecture concept for this feature and check if it won't introduce new performance or database related issues.

**Comment by patrys** [comment]
Variant attributes are implemented as a field. I'm not sure how adding this field could introduce major performance bottlenecks 😉

**Comment by artursmet** [comment]
There was a little misunderstanding - we want to add attributes field to Product model - the same way as it exists in ProductVariant model (just a JSONField).

**Comment by artursmet** [comment]
Implemented with Product Classes.
