### ISSUE TITLE
Consider requiring PostgreSQL

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#633]
We don't want to rush it but the team seems to be convinced that requiring PostgreSQL may be a good idea. It would allow us to use `hstore` type columns instead of the current generic JSON field (which really is a text field and cannot be filtered or aggregated upon).

Compatibility: We require Django 1.8 and that's when most of `django.contrib.postgres` appeared. Not sure if there are good reasons to use Saleor with another database given that we perform most optimizations working with PostgreSQL. One downside is being unable to test locally with SQLite which is often expected. With good Docker support we should be able to make it a non-issue.

**Comment by mikeres0** [comment]
Requiring PostgreSQL for deployment would be great, but as for losing the ability to use SQLite in my development environment I'm not so keen.

**Comment by patrys** [comment]
Have you tried to use docker to get a working PostgreSQL instance for your project?

**Comment by mikeres0** [comment]
I haven't yet, I haven't needed to deploy anywhere.

**Comment by patrys** [comment]
I mean to try and use Docker for local development. `docker-compose` is a great tool that can get you started in no time.

**Comment by krzysztofwolski** [comment]
@mikeres0 For dev I like to run postgres in docker. For example:
```
docker run --name saleor-postgres -p 6432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=saleor -d postgres
```
It creates working db on port 6432. If I mess it up or just want to have clean DB, I remove container and create new one.

**Comment by mikeres0** [comment]
@patrys @krzysztofwolski I'll give this a go guys, cheers
