### ISSUE TITLE
Improve product/catalog search using advanced Postgres search techniques

### ISSUE THREAD

**Issue by kjkrupal** [mirumee/saleor#6364]
I see that saleor uses a simple `icontains` search to filter products. This search feature can be improved by combining a variety of postgres search techniques such as `SearchVector`, `SearchRank`, `TrigramSearch` and `TrigramSimilarity`.

![image](https://user-images.githubusercontent.com/17178403/97824637-7a6d9a80-1c8a-11eb-8f36-4d6be2b7ee49.png)

The function above is used by several packages to perform search operations. For entities like product where we can expect a fairly large queryset, using a simple `icontains` can have performance issues. Also as `icontains` expect we provide the exact matching substring to perform search which may lead to bad user experience. I propose that we use a combination of `SearchVector`, `SearchRank`, `TrigramSearch` and `TrigramSimilarity` along with `icontains` to get better results and improved user performance.

I have worked on a project where I implemented a similar feature and I'd like to go with it here as well.

**Comment by aditya04848** [comment]
I think this is a good idea.
