### ISSUE TITLE
Demo template: back end changes

### ISSUE THREAD

**Issue by weronka** [mirumee/saleor#637]
There are some changes which need to be applied for better usability and for adjusting templates to design

- [x] split apart 'register' and 'reset your password' views
- [x] add ability to display cart total amount and cart preview in dropdown in header
- [x] move 'delete address' functionality on user profile to modal
- [ ] move 'edit email' and 'edit password' forms to one view on user profile
- [x] don't redirect to cart after adding product to cart
- [ ] add radio forms on user profile>addresses to set default shipping / billing options
- [x] add delivery options (with estimated delivery time) to cart page
- [ ] show all checkout steps on one view
- [x] add login view as a first checkout step for unlogged users in separate view

**Comment by artursmet** [comment]
@weronka:
> don't redirect to cart after adding product to cart
What about returning some JSON response, when request to add to cart view is an ajax call?
