### ISSUE TITLE
StringDataRightTruncation: value too long for type character varying(128)

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#6410]
### What I'm trying to achieve
Editing the ALT Tag of images with a longer description.

### Steps to reproduce the problem
This is a part of the failing mutation, that I copied from sentry. 
```
{
"operationName": "ProductImageUpdate", 
"query": 
"fragment ProductErrorFragment on ProductError {
  code
  field
  __typename
}

fragment ProductImageFragment on ProductImage {
  id
  alt
  sortOrder
  url
  __typename
}

fragment Money on Money {
  amount
  currency
  __typename
}

fragment ProductVariantAttributesFragment on Product {
  id
  attributes {
    attribute {
      id
      slug
      name
      inputType
      valueRequired
      values {
        id
        name
        slug
        __typename
      }
      __typename
    }
    values {
  ..."
, 
"variables": {
"alt": "5 fabelhaft Lebkuchen aus der Metropolregion Nürnberg in verschiedenen Sorten. Nachhaltige Verpackung aus Bio-Folie und Banderole aus Naturpapier", 
"id": "UHJvZHVjdEltYWdlOjE5Nw=="
}
}
```

### What I expected to happen
Update the Alt successfully. 

### Screenshots

**System information**
Operating system:

**Comment by maarcingebala** [comment]
Does the API return a validation error or it crashes with some Python stack trace? The alt text field is limited to 128 characters in the database. I'm not sure if this is a problem since these alt texts should be rather short and descriptive.
