### ISSUE TITLE
Service 'storefront' failed to build

### ISSUE THREAD

**Issue by CrimsonKoba** [mirumee/saleor#6414]
### What I'm trying to achieve
Install

### Steps to reproduce the problem
1. I follow this https://docs.saleor.io/docs/developer/installation

## Here the output
```
$ docker-compose build

Building storefront
Step 1/9 : FROM node:10
 ---> 2457d5f85d32
Step 2/9 : WORKDIR /app
 ---> Using cache
 ---> 04ca353807a9
Step 3/9 : COPY package*.json ./
 ---> Using cache
 ---> a5aee4bb6ed7
Step 4/9 : RUN npm install
 ---> Running in f82966054de8

> phantomjs-prebuilt@2.1.16 install /app/node_modules/phantomjs-prebuilt
> node install.js


ERROR: Service 'storefront' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
```

**System information**
Operating system: Debian 10

**Comment by hundredeir** [comment]
Did you clone the repo using 

```git clone https://github.com/mirumee/saleor-platform.git --recursive --jobs 3```

**Comment by CrimsonKoba** [comment]
> Did you clone the repo using
> 
> `git clone https://github.com/mirumee/saleor-platform.git --recursive --jobs 3`

Yes, I tried again and the error keep appearing

**Comment by hundredeir** [comment]
Try following this
https://github.com/mirumee/saleor-platform/issues/43#issuecomment-709375453

**Comment by CrimsonKoba** [comment]
Still no luck, I had to update to the last _docker_ version because the one from _Debian_ repo does not support the option, but at the end I got the same output.

**Comment by CrimsonKoba** [comment]
This work for me; https://stackoverflow.com/a/55223081
I don't know why.
But this is my `saleor-storefront/Dockerfile.dev`

```
FROM node:10
WORKDIR /app
#COPY package*.json ./
RUN npm install
COPY . .
ARG API_URI
ENV API_URI ${API_URI:-http://localhost:8000/graphql/}

EXPOSE 3000
CMD npm start -- --host 0.0.0.0
```

**Comment by hundredeir** [comment]
Looks like there were issues with package-lock.

**Comment by instvin** [comment]
> This work for me; https://stackoverflow.com/a/55223081
> I don't know why.
> But this is my `saleor-storefront/Dockerfile.dev`
> 
> ```
> FROM node:10
> WORKDIR /app
> #COPY package*.json ./
> RUN npm install
> COPY . .
> ARG API_URI
> ENV API_URI ${API_URI:-http://localhost:8000/graphql/}
> 
> EXPOSE 3000
> CMD npm start -- --host 0.0.0.0
> ```

CrimsonKoba, your answer helped me a lot. Greetz from Russia.

**Comment by hmtanbir** [comment]
```
FROM node:16
WORKDIR /app

# Setup pnpm package manager
RUN npm install -g pnpm

# Setup proxy to API used in saleor-platform
RUN apt-get update && apt-get install -y nginx
COPY ./nginx/dev.conf /etc/nginx/conf.d/default.conf

COPY package.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install
COPY . .
ARG API_URI
ENV API_URI ${API_URI:-http://localhost:8000/graphql/}

EXPOSE 3000
CMD pnpm dev -- --hostname 0.0.0.0
```
ERROR: Service 'storefront' failed to build: The command '/bin/sh -c pnpm install' returned a non-zero code: 1
