### ISSUE TITLE
SystemCheckError: ERRORS: ?: Plugin with path saleor.payment.gateways.... doesn't exist

### ISSUE THREAD

**Issue by frixaco** [mirumee/saleor#6423]
### What I'm trying to achieve
Add my own payment gateway

### Steps to reproduce the problem
1. 
```
-saleor
--payment
---gateways
-----alfabank
------| __init__.py - import alfabank_api, implement methods (authorize, capture..)
------| plugin.py
------| alfabank_api.py - class with methods which makes post requests to api
```
and add to `PLUGINS` in `settings.py` in `/saleor/saleor`:
```
PLUGINS = [
    ...
    "saleor.payment.gateways.alfabank.plugin.AlfaBankGatewayPlugin",
]
```
2.
```
docker-compose build
docker-compose run --rm api python3 manage.py migrate
```

### Error I got:
```
Creating saleor-platform_api_run ... done
SystemCheckError: System check identified some issues:

ERRORS:
?: Plugin with path: saleor.payment.gateways.alfabank.plugin.AlfaBankGatewayPlugin doesn't exist
```

### What I tried
* It works when I just copy paste everything from `dummy` gateway  
* Recreating Docker images, container
* Reinstalling Saleor

### What I expected to happen
My payment gateway and its method implementations are working.
No errors.

### Screenshots

![image](https://user-images.githubusercontent.com/37442533/98339735-03d7f080-202e-11eb-99b6-eccb20f8804b.png)
![image](https://user-images.githubusercontent.com/37442533/98338996-db032b80-202c-11eb-8289-07c4ab28f3b1.png)
![image](https://user-images.githubusercontent.com/37442533/98339040-ebb3a180-202c-11eb-9d84-603d23068dd6.png)

**System information**
Operating system:
Python 3.8.5
Django 3.1.2 (and 3.0.5)
Saleor 2.11 (and 2.10)
Linux

**I read through docs about adding my own payment gateway(plugin). If I understood correctly, all I need to do is just create plugin class that inherits from `BasePlugin` in `plugin.py`, implement methods and add to `PLUGINS` list. Let me know if you need more info!**

**Comment by tomaszszymanski129** [comment]
@frixaco adding the line to PLUGINS eventually leads to import attempt which fails, interestingly paths seems to be all right. Could you push these changes to github so I can have a quick look? Should be an easy fix but I cannot see right away what is wrong without full code.

**Comment by frixaco** [comment]
> @frixaco adding the line to PLUGINS eventually leads to import attempt which fails, interestingly paths seems to be all right. Could you push these changes to github so I can have a quick look? Should be an easy fix but I cannot see right away what is wrong without full code.

Yeah, sure! https://github.com/frixaco/saleor-payment-gateway/tree/main/saleor

**Comment by frixaco** [comment]
I figured it out. It was import related. The problem was in this line in `alfabank_api.py` file:
```
from saleor.saleor.payment.interface import RegisterPreAuthParams,...
```
I was importing the way PyCharm suggested instead of `from ...interface import..` or `from saleor.payment.interface import ...`. Interestingly, IDE gave `Unresolved reference error` in the latter one, most likely it's because everything runs in Docker.
