### ISSUE TITLE
Webhook order_fully_paid gets called on failed payment

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#6428]
### What I'm trying to achieve
We are using the order_fully_paid webhook in order to mark an order as fully paid in our inventory system. 
When a customer gets for example a processor declined from braintree, so no money got captured, the webhook order_fully_paid is still called.. It says `captured_amount: '0.000',`, but still I wouldn't expect this webhook to be called, when the order is not fully paid.
Furthermore, it seems like the webhook gets not triggered again when the customer tries again successfully. 

### Steps to reproduce the problem
1. Consume the webhook order_fully_paid
2. Pay with a credit card that gets declined via a payment gateway like braintree.

**System information**
Saleor Version 2.11

**Comment by IKarbowiak** [comment]
Hi @JannikZed,
Thank you for reporting the issue. I would like to fix it but I had a problem with reproducing it. Could you tell me if the problem still occur? If yes, please send information about the mutations that you called, it'll help me a lot.

**Comment by JannikZed** [comment]
Hey Iga,

I couldn’t reproduce it with the current saleor Version. You could close the issue.
