### ISSUE TITLE
"Product Deleted" plugin event

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#6434]
### What I'm trying to achieve
I'm building a plugin to sync saleor products with a MeiliSearch server. Without a `product_deleted` plugin event, over time, I'd end up with deleted products still being searchable.

### Describe a proposed solution
Create a `product_deleted` event that plugins can implement.

### Other solutions I've tried and won't work
I thought about performing a full comparison with the entire product catalog on the plugin's init. But the init function is called pretty much on every page request, it seems (it's called just from refreshing a page on the dashboard for example). It would be too costly to perform such an operation that frequently. The next alternative is to schedule a periodic task to cleanup deleted products, but that's less than ideal.

**Comment by LeOndaz** [comment]
if your site is in production, A bad workaround is that you alter saleor files and override delete method till PRODUCT_DELETED is added

**Comment by maarcingebala** [comment]
Thanks for reporting, adding that to our backlog. This webhook is definitely needed for better integrations with Saleor.

**Comment by krzysztofwolski** [comment]
Feature added to the 3.0 branch
https://docs.saleor.io/docs/3.0/developer/extending/apps/#webhooks
