### ISSUE TITLE
Metadata for Menus and Menu Items

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#6437]
### What I'm trying to achieve
When building/customizing storefronts for saleor, we use navigation menus in a variety of situations, some requiring additional data that is simply not built into menu items. For example, in addition to the name and link, some use cases might call for an icon or image url. Other times, you might want to mark some items as disabled or give them special styling.

### Describe a proposed solution
Add metadata support for menus and menu items.

### Other solutions I've tried and won't work
When the menu item points to a collection/category, adding the metadata to the collection/category itself can sometimes be an option, but this doesn't work when the menu item is just a url. And when the menu item is updated to point to a different collection, one has to remember to set the metadata all over again.

**Comment by maarcingebala** [comment]
Thanks for reporting. Metadata is not supported in all models while it seems there are more and more use cases where we should add it.

**Comment by jmheidly** [comment]
It is shame that you find metadata in various data structures yet you cant access it from graphql.

i hope this changes quickly as it doesn't really require major platform reworks.
