### ISSUE TITLE
ASGIRequest has no attribute 'app'

### ISSUE THREAD

**Issue by LeOndaz** [mirumee/saleor#6445]
I'm creating a reviews plugin that exposes a GraphQL endpoint on it's own (it's up to the user to use federation to unify the /graphql/ and /plugins/reviews.plugin/ as one endpoint. Anyway, I'm using your GraphQLView implementation. here's my webhook

```
    def webhook(self, request: HttpRequest, path: str, previous_value) -> JsonResponse:
        return csrf_exempt(GraphQLView.as_view(schema=schema))(request)
```
and when I go to `http://localhost:8000/plugins/reviews.plugin/` everything works, my mutation inherits your `ModelMutation` and does some logic, unrelated for now, this is solved if I do this
```
    def webhook(self, request: HttpRequest, path: str, previous_value) -> JsonResponse:
        request.app = None  # here
        return csrf_exempt(GraphQLView.as_view(schema=schema))(request)
```
I found that the reason behind this is that the middleware that adds .app only works with the /graphql/ and not with plugins, like 
```
def app_middleware(next, root, info, **kwargs):

    app_auth_header = "HTTP_AUTHORIZATION"
    prefix = "bearer"
    request = info.context

    if request.path == API_PATH:    # here
        if not hasattr(request, "app"): 
            request.app = None
            auth = request.META.get(app_auth_header, "").split()
            if len(auth) == 2:
                auth_prefix, auth_token = auth
                if auth_prefix.lower() == prefix:
                    request.app = SimpleLazyObject(lambda: get_app(auth_token))
    return next(root, info, **kwargs)
```

**Comment by LeOndaz** [comment]
I think the first if statement is useless, plugins also need to work with the builtin methods (I don't mind writing my own, but I don't like repeating myself, so I used ModelMutation, get_node_or_error, some other stuff which needed the info.context to get the .app or .user out of it

**Comment by maarcingebala** [comment]
@korycins @patrys Can you take a look at this issue?

**Comment by korycins** [comment]
It seems that it something which was useful when we had the templates views. IMO we could drop it. 
@NyanKiyoshi  What do you think?

**Comment by patrys** [comment]
I'd drop that first `if`. There's no harm in setting `request.app` to `None`.

**Comment by LeOndaz** [comment]
I can help with a PR if you tell me the reason behind the first if in the first place

**Comment by LeOndaz** [comment]
not stale

**Comment by NyanKiyoshi** [comment]
The issue is known and occurs when requesting the GraphQL endpoint with another path than `/graphql/` which are to be returning 404. @fowczarek is assigned for this fix. Example of failing and common mistakes for people to check when they see that exception:`/graphql//`, `/graphql/graphql/`
