### ISSUE TITLE
'block' tag with name 'menu_sales_class' appears more than once

### ISSUE THREAD

**Issue by mikeres0** [mirumee/saleor#645]
![image](https://cloud.githubusercontent.com/assets/5929943/21018668/9288d194-bd65-11e6-9cc8-40de7ad127f4.png)

**Comment by artursmet** [comment]
@mikeres0 Could you show where the exception occurs (template name and line number)?
It would be also useful to know when you've forked the project.

**Comment by mikeres0** [comment]
Sorry guys in a rush today.

It occurs in the dashboard/base.html template. I think the line number is
on the screenshot? Away from my desk at the moment so replying via. Email.
I've just merged my fork with your master branch.

**Comment by mikeres0** [comment]
Lines 83 and 123 in `templates/dashboard/base.html`

**Comment by artursmet** [comment]
@mikeres0 Looks like wrong merge - please update with the master branch. Latest base.html template has only 107 lines.

**Comment by patrys** [comment]
I'm going to close this since there's nothing we can do to fix this as it's a problem of the forked repository.
