### ISSUE TITLE
Plugin with path: saleor.plugins.webhook.plugin.WebhookPlugin doesn't exist

### ISSUE THREAD

**Issue by KalaiSquareark** [mirumee/saleor#6464]
When I try to run the saleor core stable version,

I got below error

Plugin with path: saleor.plugins.webhook.plugin.WebhookPlugin doesn't exist

**Comment by karolkielecki** [comment]
@KalaiSquareark Hey. Please provide more details. What are you trying to achieve? Is it local dev?

**Comment by KalaiSquareark** [comment]
Yes it was in Development environment, I have tried to run the Saleor outside the Docker container. I have fixed it by running inside the pipenv..
