### ISSUE TITLE
Graphql checkoutCreate errors with You do not have permission to perform this action

### ISSUE THREAD

**Issue by jmheidly** [mirumee/saleor#6473]
### What I'm trying to achieve
I am trying to create a checkout with valid JWT token using the below query variables, and i am receiving a "You do not have permission to perform this action" however the record is created (as shown below).
{
  "checkoutInput": {
        "lines": [
            {
                "quantity": 2,
                "variantId": "UHJvZHVjdFZhcmlhbnQ6Mg=="
            }
        ],
        "shippingAddress": {
            "city": "",
            "companyName": "Zero",
            "country": "AE",
            "countryArea": "أبو ظبي",
            "firstName": "Jamal",
            "lastName": "Mh",
            "phone": "+971504576666",
            "postalCode": "",
            "streetAddress1": "Al",
            "streetAddress2": "street 45"
        },
        "billingAddress": {
            "city": "",
            "companyName": "Zero",
            "country": "AE",
            "countryArea": "أبو ظبي",
            "firstName": "Jamal",
            "lastName": "Mh",
            "phone": "+971504576666",
            "postalCode": "",
            "streetAddress1": "Al",
            "streetAddress2": "street 45"
  }
  }
}

### What I expected to happen
I expect the response to be without any error.

### Screenshots
{
  "errors": [
    {
      "message": "You do not have permission to perform this action",
      "locations": [
        {
          "line": 136,
          "column": 3
        }
      ],
      "path": [
        "checkoutCreate",
        "checkout",
        "lines",
        0,
        "variant",
        "stocks"
      ],
      "extensions": {
        "exception": {
          "code": "PermissionDenied",
          "stacktrace": [
            "Traceback (most recent call last):",
            "  File \"/usr/local/lib/python3.8/site-packages/promise/promise.py\", line 489, in _resolve_from_executor",
            "    executor(resolve, reject)",
            "  File \"/usr/local/lib/python3.8/site-packages/promise/promise.py\", line 756, in executor",
            "    return resolve(f(*args, **kwargs))",
            "  File \"/usr/local/lib/python3.8/site-packages/graphql/execution/middleware.py\", line 75, in make_it_promise",
            "    return next(*args, **kwargs)",
            "  File \"/app/saleor/graphql/decorators.py\", line 15, in wrapper",
            "    return func(info.context, *args, **kwargs)",
            "  File \"/app/saleor/graphql/decorators.py\", line 31, in wrapper",
            "    raise PermissionDenied()",
            "saleor.core.exceptions.PermissionDenied: You do not have permission to perform this action"
          ]
        }
      }
    }
  ],
  "data": {
    "checkoutCreate": {
      "errors": [],
      "checkout": {
        "token": "c5f52fae-7f45-4a13-8441-a5011af515de",
        "id": "Q2hlY2tvdXQ6YzVmNTJmYWUtN2Y0NS00YTEzLTg0NDEtYTUwMTFhZjUxNWRl",
        "totalPrice": {
          "gross": {
            "amount": 200,
            "currency": "AED",
            "__typename": "Money"
          },
          "net": {
            "amount": 200,
            "currency": "AED",
            "__typename": "Money"
          },
          "__typename": "TaxedMoney"
        },
        "subtotalPrice": {
          "gross": {
            "amount": 200,
            "currency": "AED",
            "__typename": "Money"
          },
          "net": {
            "amount": 200,
            "currency": "AED",
            "__typename": "Money"
          },
          "__typename": "TaxedMoney"
        },
        "billingAddress": {
          "id": "QWRkcmVzczo0Mg==",
          "firstName": "Jamal",
          "lastName": "Mh",
          "companyName": "Zero",
          "streetAddress1": "Al",
          "streetAddress2": "street 45",
          "city": "",
          "postalCode": "",
          "country": {
            "code": "AE",
            "country": "United Arab Emirates",
            "__typename": "CountryDisplay"
          },
          "countryArea": "أبو ظبي",
          "phone": "+971504576666",
          "isDefaultBillingAddress": null,
          "isDefaultShippingAddress": null,
          "__typename": "Address"
        },
        "shippingAddress": {
          "id": "QWRkcmVzczo0MA==",
          "firstName": "Jamal",
          "lastName": "Mh",
          "companyName": "Zero",
          "streetAddress1": "Al",
          "streetAddress2": "street 45",
          "city": "",
          "postalCode": "",
          "country": {
            "code": "AE",
            "country": "United Arab Emirates",
            "__typename": "CountryDisplay"
          },
          "countryArea": "أبو ظبي",
          "phone": "+971504576666",
          "isDefaultBillingAddress": null,
          "isDefaultShippingAddress": null,
          "__typename": "Address"
        },
        "email": "infoc@infoc.com",
        "availableShippingMethods": [
          {
            "id": "U2hpcHBpbmdNZXRob2Q6MQ==",
            "name": "shipping fee",
            "price": {
              "currency": "AED",
              "amount": 10,
              "__typename": "Money"
            },
            "__typename": "ShippingMethod"
          }
        ],
        "shippingMethod": null,
        "shippingPrice": {
          "gross": {
            "amount": 0,
            "currency": "AED",
            "__typename": "Money"
          },
          "net": {
            "amount": 0,
            "currency": "AED",
            "__typename": "Money"
          },
          "__typename": "TaxedMoney"
        },
        "lines": [
          {
            "id": "Q2hlY2tvdXRMaW5lOjEx",
            "quantity": 2,
            "totalPrice": {
              "gross": {
                "amount": 200,
                "currency": "AED",
                "__typename": "Money"
              },
              "net": {
                "amount": 200,
                "currency": "AED",
                "__typename": "Money"
              },
              "__typename": "TaxedMoney"
            },
            "variant": {
              "id": "UHJvZHVjdFZhcmlhbnQ6Mg==",
              "name": "",
              "sku": "panettone",
              "quantityAvailable": 50,
              "stocks": null,
              "pricing": {
                "onSale": false,
                "priceUndiscounted": {
                  "gross": {
                    "amount": 100,
                    "currency": "AED",
                    "__typename": "Money"
                  },
                  "net": {
                    "amount": 100,
                    "currency": "AED",
                    "__typename": "Money"
                  },
                  "__typename": "TaxedMoney"
                },
                "price": {
                  "gross": {
                    "amount": 100,
                    "currency": "AED",
                    "__typename": "Money"
                  },
                  "net": {
                    "amount": 100,
                    "currency": "AED",
                    "__typename": "Money"
                  },
                  "__typename": "TaxedMoney"
                },
                "__typename": "VariantPricingInfo"
              },
              "attributes": [],
              "product": {
                "name": "Panettone",
                "thumbnail": null,
                "thumbnail2x": null,
                "productType": {
                  "id": "UHJvZHVjdFR5cGU6MQ==",
                  "isShippingRequired": true,
                  "__typename": "ProductType"
                },
                "__typename": "Product"
              },
              "__typename": "ProductVariant"
            },
            "__typename": "CheckoutLine"
          }
        ],
        "isShippingRequired": true,
        "discount": {
          "currency": "AED",
          "amount": 0,
          "__typename": "Money"
        },
        "discountName": null,
        "translatedDiscountName": null,
        "voucherCode": null,
        "availablePaymentGateways": [
          {
            "id": "mirumee.payments.dummy",
            "name": "Dummy",
            "config": [
              {
                "field": "store_customer_card",
                "value": "false",
                "__typename": "GatewayConfigLine"
              }
            ],
            "currencies": [
              "AED"
            ],
            "__typename": "PaymentGateway"
          },
          {
            "id": "mirumee.payments.dummy_credit_card",
            "name": "Dummy Credit Card",
            "config": [
              {
                "field": "store_customer_card",
                "value": "true",
                "__typename": "GatewayConfigLine"
              }
            ],
            "currencies": [
              "AED"
            ],
            "__typename": "PaymentGateway"
          }
        ],
        "__typename": "Checkout"
      },
      "__typename": "CheckoutCreate"
    }
  }
}

**Comment by maarcingebala** [comment]
It seems that in the GraphQL query you're trying to fetch:
```
lines {
  variant {
    stocks
  }
}
```
where the `stocks` field is restricted to staff users and requires proper permission.
