### ISSUE TITLE
Quantity Available when fulfilling an order doesn't equal quantity available for the product

### ISSUE THREAD

**Issue by ssaeed003** [mirumee/saleor#6507]
### What I'm trying to achieve
Fulfill orders

### Steps to reproduce the problem
1. Make any order
2. Proceed to fulfil order
3. For the respective warehouse it shows 1 less than the product that's actually available as shown in image

### What I expected to happen
The quantities of the warehouse in the fulfilment view and product view to be equal
![Bildschirmfoto 2020-11-19 um 16 51 20](https://user-images.githubusercontent.com/2878360/99689884-cb9dcc80-2a87-11eb-822b-ad0fc6100931.png)

### Screenshots

**System information**
Operating system:
Saleor Version 2.10

**Comment by karolkielecki** [comment]
@ssaeed003 Hey! I think that we fixed it in Saleor 2.11. Can you check with the latest version? https://github.com/mirumee/saleor/pull/6333
