### ISSUE TITLE
Add random SKU option

### ISSUE THREAD

**Issue by decimoseptimo** [mirumee/saleor#6508]
Add an option to generate a random SKU in `create product/variant > inventory`. Perhaps a checkbox next to?
I suspect in some cases it's unnecessary to be original about it. Like during development, or when the store hasn't assigned those.

**Comment by karolkielecki** [comment]
@decimoseptimo Thanks for your suggestion. I'll pass it to our team.

**Comment by AgentIvan** [comment]
I replace this:
    sku: "",
by:
    sku: attributes
      .sort((a, b) => (a.attributeId < b.attributeId ? -1 : 1))
      .map(a =>
        a.attributeValueSlug
          .split("-")
          .map(a => a.charAt(0).toUpperCase() + a.substr(1))
          .join("_")
      )
      .join("-"),
