### ISSUE TITLE
npm ERR! when docker-compose building

### ISSUE THREAD

**Issue by swistov** [mirumee/saleor#6534]
### What I'm trying to achieve
I will run in docker

### Steps to reproduce the problem

1. git clone https://github.com/mirumee/saleor-platform.git --recursive --jobs 3
2. cd saleor-platform
3. docker-compose build

### Screenshots
`db uses an image, skipping
redis uses an image, skipping
jaeger uses an image, skipping
mailhog uses an image, skipping
Building storefront
Step 1/9 : FROM node:10
 ---> 2db91b8e7c1b
Step 2/9 : WORKDIR /app
 ---> Using cache
 ---> f9f04a455580
Step 3/9 : COPY package*.json ./
 ---> Using cache
 ---> 15f25c47652a
Step 4/9 : RUN npm install
 ---> Running in 6024c23da45e
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/@apollographql/graphql-language-service-types/-/graphql-language-service-types-2.0.2.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-26T08_46_32_575Z-debug.log
ERROR: Service 'storefront' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1`

**System information**
Operating system: CentOS 8
Docker-compose: 1.26.2, build eefe0d31
Docker: 19.03.13, build 4484c46d9d

**Comment by LightEmitting** [comment]
Hi, I'm facing the same error. Could you fix it?

**Comment by hariom-kumar-bs** [comment]
It's happening to me also

**Comment by metouitude** [comment]
Same

**Comment by metouitude** [comment]
Seems like a npm version problem, go to saleor storefront then open the Dockerfile and the Dockerfile.dev.
Before : RUN npm install
Add these lines

RUN npm update -g
RUN npm cache clean --force
RUN npm cache verify
RUN npm install - g npm

What this does is an update for the npm version inside the container, then it cleans the cache then it installs the rest.
If this persists on saleor dashboard do the same in the saleor dashboard dockerfiler.
