### ISSUE TITLE
Saleor support for older devices?

### ISSUE THREAD

**Issue by lbrito55** [mirumee/saleor#6543]
### What I'm trying to achieve
…
Trying to access demo.saleor.io page in a couple of old devices (iphone5, samsung galaxy s3 mini)
### Steps to reproduce the problem
1. grab old phone and head to demo.saleor.io
2. Hit enter

### What I expected to happen
…

Loads mobile version of demo.saleor.io 
I tried with multiple browsers and it doesnt work either. This has something to do with something in saleors configuration?

Any insights on what could be happening (bundle size, compression, something to do with graphQL?, javascript size?)

### Screenshots

![IMG_0034](https://user-images.githubusercontent.com/26174143/100491092-6dac5d00-30f7-11eb-9657-02fdcdf3c24e.PNG)

**System information**
Operating system: iOS, Android

**Comment by karolkielecki** [comment]
@lbrito55 Hey! Thanks for reporting. We'll check it out.
