### ISSUE TITLE
Add possibility to use a custom currency within Saleor

### ISSUE THREAD

**Issue by Mosselvla** [mirumee/saleor#6556]
### What I'm trying to achieve
I'm trying to implement Saleor as a digital-only shop which uses a custom currency: no real money/legal tender, but a coin currency that already exists within our current system. As such, there is no way to create/utilise a custom/blanco currency within Saleor, as far as I'm aware.

I've been trying to remove any connection to currencies within a Saleor copy (mainly within the storefront), but it proves quite difficult, and it also seems like it would make the application very difficult to update in the future.

As for the digital-only aspect, I've seen [this issue concerning digital fulfillment](https://github.com/mirumee/saleor/issues/2098) and am very glad to see that the necessary features will be added in the future. These will help make a digital-focused shop easier.

### Describe a proposed solution
A solution I would like to propose is to have a value that can be entered for the currency in the settings value to symbolize a custom/blanco currency. A name and symbol can be set for this currency. These can be used to show up on the storefront/dashboard. This way, Saleor can be used as a more generalised shop platform, while also supporting more widespread usage.

I would like to know if there are any plans to support a functionality like this or what your thoughts are on this idea. Your thoughts/points are very welcome! Thanks in advance.

### Other solutions I've tried and won't work
I've tried to change the existing GraphQL queries to not contain any reference to currencies, in a stretch to have them not appear on the frontend, but that did not work everywhere and is also a liability in terms of updatability. 

Aside from this, I have altered some of the existing pages to reflect how I would like to see the system function. This works, but might not be ideal for the same reasons as the first point.

### Screenshots or mockups

Here is an image of a product page that I've created using Saleor, which shows the US$ standard currency removed, and instead brandishing the necessary custom currency present within our system (Fynch Coins).
![image](https://user-images.githubusercontent.com/15121599/100622355-0e319580-3321-11eb-913c-e0ebcdd1b290.png)

**Comment by maarcingebala** [comment]
Hi @Mosselvla, have you seen our work regarding multi-channel? It has been merged quite recently to master and now it's in alpha which means there may be bugs and we will yet work on improving it. The overall idea of multi-channel is to represent different sales channels or markets where you're selling your products, but with this solution we also wanted to solve the multi-currency issue. For each channel that you add, you need to define the currency. You can choose from existing currency codes or provide your own, the only limitation is that it needs to be a three-letter currency code. Here is a quick example from the Saleor Dashboard version `3.0.0-a.2`:

![image](https://user-images.githubusercontent.com/5421321/101175634-b0b18780-3645-11eb-8860-7faa5f73e7cf.png)

With this configuration you can now define all prices in the system in the custom "FYN" currency which in the storefront you can represent as "Fynch Coins". Would that approach solve your issue?

**Comment by Mosselvla** [comment]
Hey @maarcingebala, thank you very much for your response! This would indeed help a lot with creating a proper implementation that suits our needs. I have not yet seen anything about multi-channel, but this looks promising! If I have any more questions, I'll drop another ticket. Thanks again! 👍
