### ISSUE TITLE
Why use null=false in some models?

### ISSUE THREAD

**Issue by cristian05** [mirumee/saleor#6570]
Why use `null=false` in some ForeignKey models if [this](https://docs.djangoproject.com/en/3.1/ref/models/fields/#null) is the default value inherit from `Field class`?...

https://github.com/mirumee/saleor/blob/65cf5b30e4b56faf20338952406f403206cfa368/saleor/warehouse/models.py#L90

Assuming that you use it to explicitly express that this field cant have `NULL` values, why don't you use this same convention in other models?

https://github.com/mirumee/saleor/blob/65cf5b30e4b56faf20338952406f403206cfa368/saleor/shipping/models.py#L169-L171

**Comment by maarcingebala** [comment]
I think it's just inconsistency, we should either add it in all places or remove it. Being explicit is always a good idea but here I think we could remove it, having less code is also a good idea ;)
