### ISSUE TITLE
WebpackError at / failed 

### ISSUE THREAD

**Issue by sagoyanfisic** [mirumee/saleor#658]
I'm using node 4.0, but it still generates the error, they could help me please

Node -> v4.0.0
NPM -> 2.14.2

> Hash: fe97e67c8fed5bb5e17f
> Version: webpack 1.13.2
> Time: 10531ms
>                              Asset     Size  Chunks             Chunk Names
>     vendor.d62854804a54a8ccbfdf.js   126 kB       0  [emitted]  vendor
>       cart.99db543b3b085841efcb.js   213 kB       1  [emitted]  cart
>  dashboard.e414fc4a3376a61f13f5.js   295 kB       2  [emitted]  dashboard
> storefront.922d6358df5fc38370f6.js  1.08 kB       3  [emitted]  storefront
>    [0] multi vendor 52 bytes {0} [built]
>     + 195 hidden modules
> 
> WARNING in vendor.d62854804a54a8ccbfdf.js from UglifyJs
> Condition always true [./~/jquery/dist/jquery.js:9778,0]
> Condition always true [./~/jquery.cookie/jquery.cookie.js:9,0]
> Dropping unreachable code [./~/jquery.cookie/jquery.cookie.js:12,2]
> 
> WARNING in cart.99db543b3b085841efcb.js from UglifyJs
> Condition always true [./~/react/lib/ReactMount.js:764,0]
> Condition always true [./~/react/lib/findDOMNode.js:46,0]
> Condition always true [./~/react/lib/instantiateReactComponent.js:80,0]
> Dropping unreachable code [./~/react/lib/shouldUpdateReactComponent.js:40,0]
> Condition always true [./~/react/lib/traverseAllChildren.js:158,0]
> Side effects in initialization of unused variable CartItemAmount [./saleor/static/js/components/cart.js:224,13]
> Side effects in initialization of unused variable CartItemSubtotal [./saleor/static/js/components/cart.js:238,13]
> Side effects in initialization of unused variable CartTotal [./saleor/static/js/components/cart.js:251,13]
> Condition always true [./~/react/lib/ReactDOMComponent.js:907,0]
> Dropping side-effect-free statement [./~/react/lib/ReactEventListener.js:72,0]
> Dropping unused function handleTopLevelWithPath [./~/react/lib/ReactEventListener.js:98,0]
> Dropping unused variable DOCUMENT_FRAGMENT_NODE_TYPE [./~/react/lib/ReactEventListener.js:26,0]
> 
> WARNING in dashboard.e414fc4a3376a61f13f5.js from UglifyJs
> Side effects in initialization of unused variable $menuToggle [./saleor/static/js/dashboard.js:33,6]
> Condition always true [./~/hammerjs/hammer.js:2633,0]
> Dropping unreachable code [./~/hammerjs/hammer.js:2637,1]
> Condition always true [./~/materialize-css/dist/js/materialize.js:10,0]
> Dropping unreachable code [./~/materialize-css/dist/js/materialize.js:14,0]
> Condition always true [./~/materialize-css/dist/js/materialize.js:233,3679]
> Condition always true [./~/materialize-css/dist/js/materialize.js:236,0]
> Dropping unreachable code [./~/materialize-css/dist/js/materialize.js:238,5]
> Side effects in initialization of unused variable windowWidth [./~/materialize-css/dist/js/materialize.js:1097,0]
> Side effects in initialization of unused variable windowHeight [./~/materialize-css/dist/js/materialize.js:1098,0]
> Dropping unused variable count [./~/materialize-css/dist/js/materialize.js:967,0]
> Dropping unused variable originalWidth [./~/materialize-css/dist/js/materialize.js:924,0]
> Dropping unused variable originalHeight [./~/materialize-css/dist/js/materialize.js:925,0]
> Side effects in initialization of unused variable window_width [./~/materialize-css/dist/js/materialize.js:1246,0]
> Dropping unused variable timeout [./~/materialize-css/dist/js/materialize.js:1382,0]
> Side effects in initialization of unused variable width [./~/materialize-css/dist/js/materialize.js:1735,0]
> Side effects in initialization of unused variable direction [./~/materialize-css/dist/js/materialize.js:2227,0]
> Side effects in initialization of unused variable y [./~/materialize-css/dist/js/materialize.js:2229,0]
> Side effects in initialization of unused variable velocityX [./~/materialize-css/dist/js/materialize.js:2230,0]
> Dropping unused variable unique_id [./~/materialize-css/dist/js/materialize.js:2455,0]
> Dropping unused variable chips [./~/materialize-css/dist/js/materialize.js:3790,0]
> Side effects in initialization of unused variable options [./~/materialize-css/dist/js/materialize.js:3930,0]
> Side effects in initialization of unused variable options [./~/materialize-css/dist/js/materialize.js:3976,0]
> Dropping unused variable time [./~/materialize-css/dist/js/materialize.js:4163,0]
> Condition always true [./~/materialize-css/dist/js/materialize.js:4400,0]
> Dropping unreachable code [./~/materialize-css/dist/js/materialize.js:4404,0]
> Condition always true [./~/materialize-css/dist/js/materialize.js:5521,0]
> Dropping unreachable code [./~/materialize-css/dist/js/materialize.js:5525,0]
> Dropping unused variable xTranslation [./~/materialize-css/dist/js/materialize.js:7141,0]
> Condition always true [./~/select2/dist/js/select2.js:9,0]
> Dropping unreachable code [./~/select2/dist/js/select2.js:12,3]
> Side effects in initialization of unused variable $label [./~/select2/dist/js/select2.js:972,0]
> Side effects in initialization of unused variable id [./~/select2/dist/js/select2.js:1350,0]
> Dropping unused variable self [./~/select2/dist/js/select2.js:1426,0]
> Dropping unused variable matches [./~/select2/dist/js/select2.js:3430,0]
> Side effects in initialization of unused variable tag [./~/select2/dist/js/select2.js:3608,0]
> Side effects in initialization of unused variable instance [./~/select2/dist/js/select2.js:5667,0]
> Condition always true [./~/sortablejs/Sortable.js:11,0]
> Dropping unreachable code [./~/sortablejs/Sortable.js:14,0]
> Side effects in initialization of unused variable slice [./~/sortablejs/Sortable.js:71,0]
> Condition always true [./~/underscore/underscore.js:48,0]
> Dropping unreachable code [./~/underscore/underscore.js:54,0]
> Condition always true [./~/underscore/underscore.js:1543,0]
> 
> ERROR in ./saleor/static/scss/cart.scss
> Module build failed: ReferenceError: Promise is not defined
>     at LazyResult.async (/home/msalinas/Documentos/e-commerce/saleor/saleor/node_modules/postcss/lib/lazy-result.js:237:31)
>     at LazyResult.then (/home/msalinas/Documentos/e-commerce/saleor/saleor/node_modules/postcss/lib/lazy-result.js:141:21)
>     at Object.module.exports (/home/msalinas/Documentos/e-commerce/saleor/saleor/node_modules/postcss-loader/index.js:93:10)
>  @ ./saleor/static/js/cart.js 23:0-28
> 
> ERROR in ./saleor/static/scss/dashboard.scss
> Module build failed: ReferenceError: Promise is not defined
>     at LazyResult.async (/home/msalinas/Documentos/e-commerce/saleor/saleor/node_modules/postcss/lib/lazy-result.js:237:31)
>     at LazyResult.then (/home/msalinas/Documentos/e-commerce/saleor/saleor/node_modules/postcss/lib/lazy-result.js:141:21)
>     at Object.module.exports (/home/msalinas/Documentos/e-commerce/saleor/saleor/node_modules/postcss-loader/index.js:93:10)
>  @ ./saleor/static/js/dashboard.js 19:0-33
> 
> ERROR in ./saleor/static/scss/storefront.scss
> Module build failed: ReferenceError: Promise is not defined
>     at LazyResult.async (/home/msalinas/Documentos/e-commerce/saleor/saleor/node_modules/postcss/lib/lazy-result.js:237:31)
>     at LazyResult.then (/home/msalinas/Documentos/e-commerce/saleor/saleor/node_modules/postcss/lib/lazy-result.js:141:21)
>     at Object.module.exports (/home/msalinas/Documentos/e-commerce/saleor/saleor/node_modules/postcss-loader/index.js:93:10)
>  @ ./saleor/static/js/storefront.js 11:0-34
> 
> 
And generating in the runserver generates the following error

> WebpackError at /
>             ModuleBuildError in 
>             Module build failed: ReferenceError: Promise is not defined
>     at LazyResult.async (/home/msalinas/Documentos/e-commerce/saleor/saleor/node_modules/postcss/lib/lazy-result.js:237:31)
>     at LazyResult.then (/home/msalinas/Documentos/e-commerce/saleor/saleor/node_modules/postcss/lib/lazy-result.js:141:21)
>     at Object.module.exports (/home/msalinas/Documentos/e-commerce/saleor/saleor/node_modules/postcss-loader/index.js:93:10)

**Comment by patrys** [comment]
Can you try upgrading to at least Node 4.2.x?
