### ISSUE TITLE
Saleor Lite

### ISSUE THREAD

**Issue by myaccountnameislost** [mirumee/saleor#6583]
Is there a Saleor lite version? with minimum functionality?

**Comment by karolkielecki** [comment]
@myaccountnameislost Hi there! There is no lite version of Saleor. Why are you interested in such a version? What would you like to achieve?

**Comment by myaccountnameislost** [comment]
Hey Karol, I have tried Saleor but it seems that the project is a bit heavy when I run it using docker, Im looking for a simplified version to use as a foundation for my project to only build the features on top of it, as for small projects I might not need all the functionalities that is comes with Saleor.

**Comment by karolkielecki** [comment]
I see. Unfortunately, there is no simplified version designed for docker. Maybe you could fork and modify the code. But it could be a lot of work and from that moment you will lose an easy way to keep up to date with Saleor's progress.

**Comment by myaccountnameislost** [comment]
is it possible to use Django templates instead of the React  and apis?

**Comment by krzysztofwolski** [comment]
It's not, it's headless (api only) by design.

**Comment by myaccountnameislost** [comment]
okay thanks.
