### ISSUE TITLE
Improve ProductClass implementation

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#664]
- [x] Rename Product Class to Product Type in UI
- [x] Add more verbose labels to particular attributes fields - `common for all variants` on product attributes field and `specific for each variant` for variant attributes
- [x] Rename `Migrated product class` to `Unnamed product type`
- [x] Display more details on product types list (product and variants attributes)
- [x] Simplify URL scheme, now we have `/products/base/<class_pk>/add` Change to `/products/add/<class_pk>`
- [x] Add a help text that will explain why user needs a product class

**Comment by krzysztofwolski** [comment]
@artursmet  "Add a help text that will explain why user needs a product class" - where that info should be placed?

**Comment by artursmet** [comment]
@krzysztofwolski We can initially place this text below the product class form. As you suggested, we should find a way to display similar help messages in other dashboard views. But this task requires more time for research purposes.

**Comment by krzysztofwolski** [comment]
@weronka Could you look at product class list? I'm not sure if my solution for presenting attributes is good enough. Could you suggest something better? 
![classlist](https://cloud.githubusercontent.com/assets/5188636/21316649/0b9534f2-c602-11e6-83d6-76ddb7e5693b.png)
