### ISSUE TITLE
Query Playground - Querying customers fails when authenticated

### ISSUE THREAD

**Issue by epigramengineer** [mirumee/saleor#6659]
### What I'm trying to achieve

Query the emails from customers in the query playground

### Steps to reproduce the problem
1. Run the default saleor-platform application
2. Generate a token with the following, which clearly has permission MANAGE_USERS
```
mutation {
  tokenCreate(email: "admin@example.com", password: "admin") {
    token
    user { permissionGroups {permissions {code}}}
  }
}
```
3. Set the HTTP Headers to be:
```
{
  "Authorization": "<the_token_field_from_above>"
}
```
4. Run the query:
```
{ customers(first:100) { edges {node{email}} } }
```

### What I expected to happen
Returns the list of all customer emails. Instead I get:

` "message": "You do not have permission to perform this action",`

**Comment by fowczarek** [comment]
Hi,

At point 3 you should pass "JWT" before token. 

```
{
    "Authorization": "JWT  <the_token_field_from_above>"
}
```

**Comment by epigramengineer** [comment]
Thanks!
