### ISSUE TITLE
Discussion, why do we have metadata and attributes (sometimes on the same model) ?

### ISSUE THREAD

**Issue by LeOndaz** [mirumee/saleor#6684]
Correct me if I'm mistaken, technically the attributes are a model instance with (key, value) fields and metadata items are JSONFields. Both are the same in terms of the idea (a dict is a key value) and how can we use them (at least the interface provided for usage can be the same), here's what I'm thinking

Attribute groups -> 
          - Group1 (Metadata)
               - SelectedAttr1 (attribute, values)
               - SelectedAttr2 (attribute, values)
               - ....
           - Group2 (Attributes)
               - SelectedAttr1
               -  ...
and we could (if we wanted) call a group "Metadata" and another "Attributes" instead of having 2 things that are implicitly sharing the same idea with different implementation

We can benefit from this a lot, lemme list some of them
- We can share the same dashboard implementation of both of them, so metadata items can have dropdowns, booleans, ...etc
- Faster queries on data intensive backends, (no JSON encoding or decoding happens for EACH element that we're comparing when querying metadata (a must have anyway, by my implementation or another) GH-6683

This of course is a breaking change, this is why this is a discussion.

**Comment by LeOndaz** [comment]
@patrys What do you think about this?

**Comment by patrys** [comment]
Attributes enforce a schema while metadata does not and it's often impractical for it to do so. We've intended metadata to serve machines (eg. to be constructed and consumed by code) while attributes serve humans (typical use case is to display information to customers).

**Comment by LeOndaz** [comment]
> Attributes enforce a schema while metadata does not and it's often impractical for it to do so. We've intended metadata to serve machines (eg. to be constructed and consumed by code) while attributes serve humans (typical use case is to display information to customers).

I understand, but attributes also can serve machines well (better performance, as mentioned) by adding a specific attribute group that plays the metadata role (conventionally, not enforced), I think if metadata serves machine then they shouldn't appear on the dashboard, but they do, so they serve both humans and machines, anyway what do you think about adding attributes to other models like category? for adding something like "Featured categories" ?

**Comment by LeOndaz** [comment]
@maarcingebala @korycins  any thoughts?

**Comment by krzysztofwolski** [comment]
We intend to cover most of the objects with metadata because thanks of its flexibility it will allow us to use it in different apps. For now, attributes will stay in products and pages.
