### ISSUE TITLE
Separate billing details from shipping address

### ISSUE THREAD

**Issue by sagital** [mirumee/saleor#6705]
### What I'm trying to achieve

Most of the customers will want to bill the purchased products to themselves . Others  will want to bill them to a company. And some other customers would want to be able to switch between billing to a person and billing to a company, depending on the products they purchase.

Issuing an invoice to a company requires some specific fields to be filled in, at the minimum `Tax Id` (VAT Number in Europe)  https://stripe.com/docs/billing/customer#tax 

In Romania for example. these fields are usually printed on the invoices: Company Name,  VAT number, Company Registration Number, Bank name , SWIFT/ IBAN 

### Describe a proposed solution

I think that it would make sense to be to add a `metadata` field to the `account_address` where we could keep all these fields  and indicate  if an address is a shipping address or billing details. Users could be able to select one of the stored billing addresses at checkout, depending if they want to bill to a company or to a regular person.

The other alternative would be to add some kind of attributes to the address, where we could specify that this is  a billing  address and add the extra fields.

I have opened a PR for the first variant

**Comment by AgentIvan** [comment]
Another issue is to allow users `buy and collect` at offline store

**Comment by AgentIvan** [comment]
Billing details for persons that need invoice have to include `Fiscal Code` in Italy

**Comment by EmanuilGerganov** [comment]
Is there any update on this issue? The current shipping/billing address system is not at all finished
