### ISSUE TITLE
The calculation of the tax is not accurate

### ISSUE THREAD

**Issue by AgentIvan** [mirumee/saleor#6720]
### What I'm trying to achieve
The accurate calculation of the TAX

### What's the bug:
Tax rate = 22%
45.60 - 45.60/1.22 = 8.22

how to calc Saleor:
0.05 - 0.05/1.22 = **0.009016** => 0.01
20 - 20/1.22 =       **3.606557** => 3.61

so we receive not:
112\*0.009016 + 2\*3.606557 = 8.222906
but:
112\*0.01 + 2\*3.61 = 8.34
with difference of 12 cent

### Steps to reproduce the problem
1. Create low price product
2. Buy many units of it
3. See resulted tax

### What I expected to happen
As for me the tax should be calculated/stored with **float** but not **integer** value

### Screenshots

![image](https://user-images.githubusercontent.com/16723960/104588991-8520b480-5669-11eb-9ec8-bb879f65c71d.png)

**System information**
Operating system:
Ubuntu
Saleor 2.11

**Comment by IKarbowiak** [comment]
Hi @AgentIvan,
Thank you for reporting the issue. Do you still have this problem? Which plugin are you using for calculating taxes? I was investigating the issue and with Avalara and Vatlayer, we get the rounded values from the plugins response, so the calculation is not on our site. Also we introduced some fixes corresponding to taxes, among others fix that gets tax rate from plugins and increase number of decimal places for the rate (#6649).
