### ISSUE TITLE
More than one channel exists. Specify which channel to use.

### ISSUE THREAD

**Issue by Sarowar-neo** [mirumee/saleor#6725]
```
{
  "errors": [
    {
      "message": "More than one channel exists. Specify which channel to use.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "products"
      ],
      "extensions": {
        "exception": {
          "code": "GraphQLError",
          "stacktrace": [
            "Traceback (most recent call last):",
            "  File \"/app/saleor/channel/utils.py\", line 27, in get_default_channel",``
```

**Comment by SuperCipher** [comment]
I got the same problem.
What are the issue and solutions?

**Comment by Sarowar-neo** [comment]
Here it is... 
![Screenshot from 2021-01-15 06-27-48](https://user-images.githubusercontent.com/22500875/112015903-6ef60f80-8b56-11eb-9dc1-79888955d1dd.png)

**Comment by SuperCipher** [comment]
@Sarowar-neo 
Thanks a lot this solved my problem.

**Comment by kissu** [comment]
As a possible helper for future people, this is how you access some collection slug in GraphQL
![image](https://github.com/saleor/saleor/assets/5133074/6b373bbb-3926-4bc7-b8e8-4ada0ae20526)
