### ISSUE TITLE
production with gunicorn, nginx

### ISSUE THREAD

**Issue by sdnnet3** [mirumee/saleor#6745]
### What I'm trying to achieve

Trying to start up a gunicorn socket with saleor.wsgi:application

### Steps to reproduce the problem
1. git clone https://github.com/mirumee/saleor-platform.git --recursive --jobs 3
2.create socket and service in gunicorn with a working path of home/clayton/saleor-platform/saleor/saleor

[Unit]
Description=saleor gunicorn daemon
Requires=saleor.socket
After=network.target

[Service]
User=clayton
Group=www-data
WorkingDirectory=/home/clayton/saleor-platform/saleor/saleor
ExecStart=/home/clayton/saleor-platform/env/bin/gunicorn \
          --access-logfile - \
          --workers 3 \
          --bind unix:/run/saleor.sock \
          saleor.wsgi:application

[Install]
WantedBy=multi-user.target

---and---

[Unit]
Description=saleor gunicorn daemon
Requires=saleor.socket
After=network.target

[Service]
User=clayton
Group=www-data
WorkingDirectory=/home/clayton/saleor-platform/
ExecStart=/home/clayton/saleor-platform/env/bin/gunicorn \
          --access-logfile - \
          --workers 3 \
          --bind unix:/run/saleor.sock \
          saleor.wsgi:application

[Install]
WantedBy=multi-user.target

### What I expected to happen
starting a gunicorn service, but testing the connection with 'sudo systemctl status saleor'  results in :
(env) clayton@Personal:/etc/nginx/sites-enabled$ sudo systemctl status saleor
● saleor.service - saleor gunicorn daemon
   Loaded: loaded (/etc/systemd/system/saleor.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2021-01-19 03:16:20 UTC; 1min 34s ago
 Main PID: 21965 (code=exited, status=3)

Jan 19 03:16:20 Personal gunicorn[21965]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jan 19 03:16:20 Personal gunicorn[21965]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jan 19 03:16:20 Personal gunicorn[21965]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jan 19 03:16:20 Personal gunicorn[21965]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jan 19 03:16:20 Personal gunicorn[21965]: ModuleNotFoundError: No module named 'saleor'
Jan 19 03:16:20 Personal gunicorn[21965]: [2021-01-19 03:16:20 +0000] [21992] [INFO] Worker exiting (pid: 21992)
Jan 19 03:16:20 Personal gunicorn[21965]: [2021-01-19 03:16:20 +0000] [21965] [INFO] Shutting down: Master
Jan 19 03:16:20 Personal gunicorn[21965]: [2021-01-19 03:16:20 +0000] [21965] [INFO] Reason: Worker failed to boot.
Jan 19 03:16:20 Personal systemd[1]: saleor.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jan 19 03:16:20 Personal systemd[1]: saleor.service: Failed with result 'exit-code'.

### Screenshots

![image](https://user-images.githubusercontent.com/9749815/104984197-1de56600-59c3-11eb-9ed9-f48ace3375b6.png)

**System information**
Ubuntu 18 on digitalocean

**Comment by thewhiterabbit** [comment]
From my experience you have three options...

1. Deploy an unsecured demo/development environment on your local machine.
2. Deploy an unsecured demo/development environment on your remote machine with Docker.
3. Pay $950/month to deploy a secured production environment on a remote machine (probably also with Docker which I don't find to be easy to secure, and securing your docker container is not in the scope of Mirumee's monthly fees because docker is not part of Saleor).

I'm working on a bash install script for secure Saleor production deployment on Ubuntu/Nginx and have gotten literally zero help form anyone at Saleor. They want that $950/mo. pretty bad. I don't blame them. This app was a lot of work to build, and remains a lot of work to maintain & update.

**Comment by sdnnet3** [comment]
> From my experience you have three options...
> 
> 1. Deploy an unsecured demo/development environment on your local machine.
> 2. Deploy an unsecured demo/development environment on your remote machine with Docker.
> 3. Pay $950/month to deploy a secured production environment on a remote machine (probably also with Docker which I don't find to be easy to secure, and securing your docker container is not in the scope of Mirumee's monthly fees because docker is not part of Saleor).
> 
> I'm working on a bash install script for secure Saleor production deployment on Ubuntu/Nginx and have gotten literally zero help from anyone at Saleor. They want that $950/mo. pretty bad. I don't blame them. This app was a lot of work to build, and remains a lot of work to maintain & update.

Gotcha, I was mostly interested in testing it, but the setup I had wasn't ultra powerful, which made the docker route less than ideal. I do all of my setups on django/gunicorn instances, so uwsgi wasn't a big stretch. I actually got a lot of it figured out, but it's definitely through research that veers heavily outside of the documentation.

**Comment by thewhiterabbit** [comment]
Check out this video I found on deploying projects like this to a production environment.

https://www.youtube.com/watch?v=ZpR1W-NWnp4

It's helping me a lot on trying to implement a production deployment of Saleor. Very relevant.
