### ISSUE TITLE
XML CORS configuration doesn't work in the new AWS S3 console (requires JSON)

### ISSUE THREAD

**Issue by roperi** [mirumee/saleor#6761]
### What I'm trying to achieve
Store Files on Amazon S3 using Saleor 2.11 documentation as a guide.  

### Steps to reproduce the problem
1. Configure a S3 bucket to allow cross-origin request
2. Copy pasting the following configuration into the AWS S3 bucket's Cross-origin resource sharing (CORS) field:
  ``` 
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
  </CORSRule>
</CORSConfiguration> 
```
3. It fails with error. [New S3 console doesn't accept XML but JSON](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/cors.html)

### What I expected to happen
- AWS S3 to accept the XML configuration. 
- A Saleor 2.11 documentation update to clarify JSON should be used when configuring CORS in AWS S3 bucket. 

[https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/cors.html](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/cors.html)
 
### Screenshots

**System information**
Operating system:  Debian 10 Buster

**Comment by h-2-0** [comment]
In case someone encounters this error. This is the JSON needed:

```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "HEAD",
            "GET",
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "https://www.example.org"
        ],
        "ExposeHeaders": [
             "ETag",
             "x-amz-meta-custom-header"]
    }
]
```
