### ISSUE TITLE
Payment on delivery

### ISSUE THREAD

**Issue by yassinebridi** [mirumee/saleor#6767]
### What I'm trying to achieve
Because almost all payment gateways are not supported in my country, we want the payment to be done on delivery, the current setup makes the payment process necessary.

### Describe a proposed solution
In the checkout flow, i only need the user to fill out the shipping infos, without the payment step, and let us handle payment manually, on delivery.

**Comment by h-2-0** [comment]
I'd also like to know how to achieve that. A general overview on how could it be done will be very helpful.
