### ISSUE TITLE
Storefront showing a truncated ISO currency code set with DEFAULT_CURRENCY

### ISSUE THREAD

**Issue by roperi** [mirumee/saleor#6771]
### What I'm trying to achieve
…Display the correct [ISO currency code](https://www.iso.org/standard/64758.html) (which is a three alphabetical code) in product prices. It displays only two letters instead of three. 

### Steps to reproduce the problem
1. Set environment variable `DEFAULT_CURRENCY=AUD`
2. Run storefront and check product prices. 

### What I expected to happen
Say a product costs 1000 Australian Dollars (AUD). So Instead of showing AUD$1000 (correct) it shows AU$1000 (incorrect). 

### Screenshots

**System information**
Operating system:

**Comment by krzysztofwolski** [comment]
Storefront does not intent to use 3 letter iso code, but format price according to your locale.
```
<span {...props}>
      {money.currency && money.currency !== ""
        ? money.amount.toLocaleString(process.env.LANGUAGE_LOCALE, {
            currency: money.currency,
            style: "currency",
          })
        : money.amount.toString()}
    </span>
```

https://developer.mozilla.org/pl/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
