### ISSUE TITLE
Add delivery and return policy information for product

### ISSUE THREAD

**Issue by abhikur** [mirumee/saleor#6788]
### What I'm trying to achieve
I have a simple requirement of showing the product delivery terms and conditions and return policy.

### Describe a proposed solution
Add product.delivery and product.return fields

### Other solutions I've tried and won't work
I tried to add these information in the metadata but we are using metadata for storing other information. So that didn't work for us.

### Screenshots or mockups
{
    product(id: 'someId') {
        delivery     // will return delivery terms and conditions text
        return       // will return return policy text
    }
}

**Comment by krzysztofwolski** [comment]
In Saleor 3.0 you can create reference type to the Page, you you could store delivery and returns policy as attributes
