### ISSUE TITLE
No query "webhooks" for an app.

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#6807]
### What I'm trying to achieve
List all Webhooks of an app

### Describe a proposed solution
Currently, there is no "webhooks" query that lists all webhooks. When you are coming with an App token, you are normally just allowed to create and delete your own webhooks, but you have no possibility to list the webhooks that are currently active. The only possibility is to grant the app permission to "MANAGE_APPS" - but that would be a very unsafe way.

We think that the app installation and configuration process will be fully automated, which is only possible if an app could see its own webhooks and create or update them accordingly.

### Other solutions I've tried and won't work
…

**Comment by korycins** [comment]
@JannikZed  thanks for reporting this. The requests with App token should be able to retrieve the own app details and their webhooks.

**Comment by maarcingebala** [comment]
The issue should be now fixed with PR #6928. To fetch the app's own information use the `app` query without passing any ID. It works in a similar way as the `me` query for users.
