### ISSUE TITLE
Docker Build 3.0 fails on Apple M1

### ISSUE THREAD

**Issue by benoj** [mirumee/saleor#6824]
### What I'm trying to achieve
Trying to build the docker image after checking out 3.0 branch

### Steps to reproduce the problem
1. checkout 3.0
2. docker build .

### What I expected to happen
Docker image built successfully

### Screenshots
```
docker build .
[+] Building 4.0s (19/19) FINISHED                                                                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                                                                            0.3s
 => => transferring dockerfile: 2.20kB                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                               0.5s
 => => transferring context: 34B                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim                                                                                                                              1.4s
 => [internal] load metadata for docker.io/library/python:3.9                                                                                                                                   1.5s
 => [build-python 1/5] FROM docker.io/library/python:3.9@sha256:37a5e011a522f3ba328e1ea30d2cb22513dbbfc99d6002bf37b205fab5a4564f                                                                0.0s
 => [internal] load build context                                                                                                                                                               0.3s
 => => transferring context: 135.80kB                                                                                                                                                           0.1s
 => [stage-1 1/9] FROM docker.io/library/python:3.9-slim@sha256:50328b4efe5ff8ef8bb2e62e088a4cefeace39062c483c04987f5820e7cf73b1                                                                0.0s
 => CACHED [stage-1 2/9] RUN groupadd -r saleor && useradd -r -g saleor saleor                                                                                                                  0.0s
 => CACHED [stage-1 3/9] RUN apt-get update   && apt-get install -y   libcairo2   libgdk-pixbuf2.0-0   liblcms2-2   libopenjp2-7   libpango-1.0-0   libpangocairo-1.0-0   libssl1.1   libtiff5  0.0s
 => CACHED [stage-1 4/9] RUN mkdir -p /app/media /app/static   && chown -R saleor:saleor /app/                                                                                                  0.0s
 => CACHED [build-python 2/5] RUN apt-get -y update   && apt-get install -y gettext   && apt-get clean   && rm -rf /var/lib/apt/lists/*                                                         0.0s
 => CACHED [build-python 3/5] COPY requirements_dev.txt /app/                                                                                                                                   0.0s
 => CACHED [build-python 4/5] WORKDIR /app                                                                                                                                                      0.0s
 => CACHED [build-python 5/5] RUN pip install -r requirements_dev.txt                                                                                                                           0.0s
 => CACHED [stage-1 5/9] COPY --from=build-python /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/                                                               0.0s
 => CACHED [stage-1 6/9] COPY --from=build-python /usr/local/bin/ /usr/local/bin/                                                                                                               0.0s
 => CACHED [stage-1 7/9] COPY . /app                                                                                                                                                            0.0s
 => CACHED [stage-1 8/9] WORKDIR /app                                                                                                                                                           0.0s
 => ERROR [stage-1 9/9] RUN SECRET_KEY=dummy STATIC_URL=/static/ python3 manage.py collectstatic --no-input                                                                                     1.5s
------                                                                                                                                                                                               
 > [stage-1 9/9] RUN SECRET_KEY=dummy STATIC_URL=/static/ python3 manage.py collectstatic --no-input:                                                                                                
#19 1.143 Traceback (most recent call last):                                                                                                                                                         
#19 1.143   File "/app/manage.py", line 10, in <module>                                                                                                                                              
#19 1.143     execute_from_command_line(sys.argv)                                                                                                                                                    
#19 1.143   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line                                                                 
#19 1.143     utility.execute()
#19 1.143   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
#19 1.143     django.setup()
#19 1.143   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
#19 1.143     apps.populate(settings.INSTALLED_APPS)
#19 1.143   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
#19 1.143     app_config = AppConfig.create(entry)
#19 1.143   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 116, in create
#19 1.143     mod = import_module(mod_path)
#19 1.143   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
#19 1.143     return _bootstrap._gcd_import(name[level:], package, level)
#19 1.143   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
#19 1.143   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
#19 1.143   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
#19 1.143   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
#19 1.143   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
#19 1.143   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
#19 1.143   File "/usr/local/lib/python3.9/site-packages/django/contrib/postgres/apps.py", line 1, in <module>
#19 1.143     from psycopg2.extras import (
#19 1.143   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 51, in <module>
#19 1.143     from psycopg2._psycopg import (                     # noqa
#19 1.143 ImportError: libpq.so.5: cannot open shared object file: No such file or directory
------
executor failed running [/bin/sh -c SECRET_KEY=dummy STATIC_URL=${STATIC_URL} python3 manage.py collectstatic --no-input]: exit code: 1
```

**System information**
Operating system:

**Comment by dieppv1** [comment]
I also got the same problem. is there any solution for it?


 [stage-1 9/9] RUN SECRET_KEY=dummy STATIC_URL=/static/ python3 manage.py collectstatic --no-input:
#19 7.638 Traceback (most recent call last):
#19 7.638   File "/app/manage.py", line 10, in <module>
#19 7.638     execute_from_command_line(sys.argv)
#19 7.638   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
#19 7.640     utility.execute()
#19 7.640   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
#19 7.641     django.setup()
#19 7.641   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
#19 7.641     apps.populate(settings.INSTALLED_APPS)
#19 7.641   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
#19 7.642     app_config.import_models()
#19 7.642   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
#19 7.644     self.models_module = import_module(models_module_name)
#19 7.644   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
#19 7.644     return _bootstrap._gcd_import(name[level:], package, level)
#19 7.644   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
#19 7.645   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
#19 7.645   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
#19 7.645   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
#19 7.645   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
#19 7.646   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
#19 7.647   File "/app/saleor/account/models.py", line 19, in <module>
#19 7.647     from versatileimagefield.fields import VersatileImageField
#19 7.647   File "/usr/local/lib/python3.9/site-packages/versatileimagefield/fields.py", line 10, in <module>
#19 7.648     from .files import VersatileImageFieldFile, VersatileImageFileDescriptor
#19 7.648   File "/usr/local/lib/python3.9/site-packages/versatileimagefield/files.py", line 8, in <module>
#19 7.649     from .mixins import VersatileImageMixIn
#19 7.649   File "/usr/local/lib/python3.9/site-packages/versatileimagefield/mixins.py", line 5, in <module>
#19 7.649     from .datastructures import FilterLibrary
#19 7.649   File "/usr/local/lib/python3.9/site-packages/versatileimagefield/datastructures/__init__.py", line 3, in <module>
#19 7.649     from .sizedimage import SizedImage
#19 7.649   File "/usr/local/lib/python3.9/site-packages/versatileimagefield/datastructures/sizedimage.py", line 8, in <module>
#19 7.651     from .base import ProcessedImage
#19 7.651   File "/usr/local/lib/python3.9/site-packages/versatileimagefield/datastructures/base.py", line 2, in <module>
#19 7.651     from PIL import Image
#19 7.651   File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 94, in <module>
#19 7.652     from . import _imaging as core
#19 7.652 ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
------
executor failed running [/bin/sh -c SECRET_KEY=dummy STATIC_URL=${STATIC_URL} python3 manage.py collectstatic --no-input]: exit code: 1

**Comment by benoj** [comment]
@dieppv1 are you using an M1 Mac by any chance?

**Comment by krzysztofwolski** [comment]
@benoj Whats your os version and cpu? (m1/intel)

**Comment by benoj** [comment]
I'm using latest M1 MPB.

I actually resolved this issue with the following:

```
export CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1

export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
```

**Comment by JinliangZ** [comment]
> I'm using latest M1 MPB.
> 
> I actually resolved this issue with the following:
> 
> ```
> export CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
> 
> export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
> ```

I am using M1 chip and facing the same issues as you, could you please tell me where to add these codes, in the .zshrc file or in a certain sopcal file?

**Comment by crukundo** [comment]
> I'm using latest M1 MPB.
> 
> I actually resolved this issue with the following:
> 
> ```
> export CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
> 
> export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
> ```

Same issue on M1 MPB. This didn't work for me.

**Comment by nolanbz** [comment]
@JinliangZ Did you ever figure this out?

**Comment by IBanda** [comment]
Hi @benoj 
Where exactly did you add those exports?
Thanks

**Comment by savager** [comment]
Just FYI, you can add 
```platform: "linux/amd64"```
to the docker-compose to force virtualization. 

I didn't even check which needed it I just added it to all of them 
![image](https://user-images.githubusercontent.com/1455337/148626156-30404417-d3db-4539-9b4b-b640fa9daf75.png)
