### ISSUE TITLE
Store form data after submission on custom made page - plugin

### ISSUE THREAD

**Issue by sidgangs99** [mirumee/saleor#6831]
### What I'm trying to achieve
...
I was implementing this via the plugin and found it really tough to do so, for B2B business clients there should be a form so that they can send their query via that, and you get the notification at the same time. Also, to store extra information on DB for later reference.

### Describe a proposed solution
...
From a Dashboard point of view:
1. We can add a custom plugin and store the data using graphql API.
2. We can create an app and link to it.

Form Admin point of view:
1. There should be a default plugin that the user can activate and edit it for form submission.

### Other solutions I've tried and won't work
…
1. I have tried implementing using custom plugin integration, but found difficult and at the end, just ended up researching that changing anything in saleor models would create problems later for updating, so tried creating another DB for storing this.

**Comment by krzysztofwolski** [comment]
I'm sorry, but it seems to be a very specific use case, just valid to your business. You will need to create your own plugin for such functionality.
