### ISSUE TITLE
Getting user.orders results in permission error 

### ISSUE THREAD

**Issue by LeOndaz** [mirumee/saleor#6842]
Getting user.orders results in PermissionError even though the requestor is the user himeself, I'm trying to get a list of orders created by a user (requestor)
``` 
query x {
user (email: $email){
       orders(...) {}
   }
}
```

and I get permission error, is it something I'm missing or a bug?

**Comment by sagital** [comment]
I am trying to achieve the same thing, using `2.11` but I am querying for user id.

```
query x {
  user (id: $id){
       orders(...) {}
   }
}
```
and I run in the same problem with permissions.  This was solved at some point, https://github.com/mirumee/saleor/pull/3202 but the functionality seems to be lost again.

The work around is to use a mutation, like `tokenVerify` where you pass in the current token but is kinda ugly.

**Comment by LeOndaz** [comment]
@sagital The solution is to use the `me` query actually

**Comment by krzysztofwolski** [comment]
For client side, intended way is accessing orders via me query.
