### ISSUE TITLE
Adding product reviews 

### ISSUE THREAD

**Issue by sidgangs99** [mirumee/saleor#6848]
### What I'm trying to achieve
…
The customer can rate the overall process and product about the product, so that I makes easier to identify poor sellers as well as poor products.

### Describe a proposed solution
...
We can just add another feature and merge PR, at this thread **https://github.com/mirumee/saleor/issues/3513** .

### Other solutions I've tried and won't work
…
I tried added plugin but faced some difficulties while merging it, also tried creating an Django app but again faced few difficulties maybe due to permissions in the database.

### Screenshots or mockups

![image](https://user-images.githubusercontent.com/32275795/107114905-401a2780-688f-11eb-8c52-0214b24027cf.png)
![image](https://user-images.githubusercontent.com/32275795/107114919-5cb65f80-688f-11eb-9b62-b51b709b5689.png)

**Comment by krzysztofwolski** [comment]
We are not planning on integrating additional reviews to the Saleor ATM. There are multiple external services you could use, with moderation tools, etc..

Related feature request: #7057
