### ISSUE TITLE
App is not able to get variant pricing

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#6881]
### What I'm trying to achieve
Using an AppToken (with manage products permission) I'm trying to get a product with its variants and price. Query looks like this; 
```
query getProductQuery($id: ID!){
    product(id: $id) {
      images{id url}
      productType{hasVariants}
      name
      slug
      updatedAt
      variants {
        id
        name
        sku
        pricing {
          price {
            gross {
              amount
            }
          }
        }
        quantityAvailable
        images {
          id
          url
        }
      }
    }
  }
```
The returned variant looks like this: 
```
{
  __typename: 'ProductVariant',
  id: 'UHJvZHVjdFZhcmlhbnXXXI=',
  name: '',
  sku: 'pf-leb-5-XXX',
  pricing: null,
  quantityAvailable: 100,
  images: []
}
```
unfortunately, the pricing is just null. I can get the pricing when querying unauthenticated.

### Steps to reproduce the problem
1. Use Saleor v3, create an AppToken and try to query a product variant
2.

**System information**

Operating system:
Saleor version: 3

**Comment by d-wysocki** [comment]
Hey, as a staff user or app you are able to get all products without providing channel but without pricing (which is related to specific channel). To get pricing you should add specific channel to query.

Your query should look like this from example below
```
query getProductQuery($id: ID!, $channel:String){
    product(id: $id, channel: $channel) {
      images{id url}
      productType{hasVariants}
      name
      slug
      updatedAt
      variants {
        id
        name
        sku
        pricing {
          price {
            gross {
              amount
            }
          }
        }
        quantityAvailable
        images {
          id
          url
        }
      }
    }
  }
```
