### ISSUE TITLE
Weight based rates not working as expected

### ISSUE THREAD

**Issue by KonstantinosPapadopoulos** [mirumee/saleor#6925]
### What I'm trying to achieve
…
Hi there 😃 I think there is a bug when setting up shipping methods. 
### Steps to reproduce the problem
1. Setup a "Weight Based Rate" and check the "There are no value limits" checkbox.
2. Go to the storefront checkout and see that the shipping method is not shown.

### What I expected to happen
I would expect "DHL Express" to show up when the "no value limits" is enabled instead of giving me an empty "availableShippingMethods" list?

### Screenshots
--- WITH "no value limits" DISABLED ---

![image](https://user-images.githubusercontent.com/33222461/108908864-bc489500-761b-11eb-9693-a7f086266cc4.png)

![image](https://user-images.githubusercontent.com/33222461/108908700-86a3ac00-761b-11eb-97df-d22af6885530.png)

--- WITH "no value limits" ENABLED ---

![image](https://user-images.githubusercontent.com/33222461/108909031-ebf79d00-761b-11eb-915f-250f74699bcf.png)

![image](https://user-images.githubusercontent.com/33222461/108908978-dbdfbd80-761b-11eb-8fec-70dc6ef2e5d7.png)

**System information**
Operating system: Windows 10 (WSL2)
Saleor/Saleor-storefront/Saleor-Dashboard version: 2.11

Apologies if I'm misunderstanding something or if this has already been raised - couldn't find it as an issue in any of the repos.

**Comment by krzysztofwolski** [comment]
Thanks for the reporting! We fixed the issue in the 3.0 branch and soon we will backport it to 2.11 :) 
#7021

**Comment by KonstantinosPapadopoulos** [comment]
Awesome thank you very much for the response - closing the issue then :)
