### ISSUE TITLE
duplicate key value violates unique constraint "cart_cart_pkey"

### ISSUE THREAD

**Issue by aravind12345** [mirumee/saleor#693]
After installing saleor on local machine.The error is coming .Please help

**Comment by krzysztofwolski** [comment]
@aravind12345 Hi! Could you provide more information and steps how to reproduce this error? Your OS, Python version, what database are you using.

**Comment by artursmet** [comment]
@aravind12345 Are you still experiencing this issue? Could you share some steps to reproduce it?

**Comment by patrys** [comment]
Closing until we can reproduce this.
