### ISSUE TITLE
Independent warehouse support for subset of product-types

### ISSUE THREAD

**Issue by fsaina** [mirumee/saleor#6953]
### What I'm trying to achieve

Sometimes it's easier to have dedicated warehouses for a particular subset of products (e.g. bottled products like vine, soda, etc.) which fall within an operation of a small set of particular warehouses. The feature request here is to localize the Saleor experience and all customer-facing process to one warehouse without exposing all the rest of customer/product information to other warehouses. 

### Describe a proposed solution

Add support for brand warehouses which operate only on a particular subset of products so that all the payment, order, invoicing, and staff information is contained and localized only as part of the members of one or multiple warehouse. This will allow for specialized warehouses which operate independently to get the currently missing web support from the Saleor platform. 

### Other solutions I've tried and won't work

I've went trough your demo/admin pages and as of this moment it is unclear how one could do that. Correct me if the behavior described is achievable already. Thanks for your help.

### Screenshots or mockups

No screenshots.

**Comment by krzysztofwolski** [comment]
Restricting access to the subset of order data is not possible in Saleor. You would need to extend Saleor based on your use case.
