### ISSUE TITLE
Add aggregations/facetting feature to search integration

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#696]
Elasticsearch integration should provide an API for using aggregations (with filtering ability)

**Comment by artursmet** [comment]
Also we should consider introducing API for filtering at SearchForm level - now all filters are deducted from queryset, it means that we should modify the queryset, basing on GET variables for the search view (for example when we want to filter products in particular price range).
@patrys What do you think about adding some abstraction there and introduce abstract filters on search form level? Filter parameters will be obtained from GET variables and then they'll be passed to elasticsearch query.

So search form will be aware of current page filtering options, for example:

```
class SearchForm(forms.Form):
    filters = {'price': SearchFilter(field='price'), 'availability': SearchFilter(field='availability')}
    aggregations = {'color': AttributeAggregation(attribute_name='color')}
```

It will keep the implementation more clear, when we define filters and aggregation on form class level instead of passing a dict to search method. What do you think?

**Comment by patrys** [comment]
Sounds like a good idea.

**Comment by artursmet** [comment]
As we discussed, we'll keep following approach:
```
class SearchForm(forms.Form):
    price_from = forms.DecimalField()
    price_to = forms.DecimalField()
    colors = forms.ChoiceField()
```
All facets will have corresponding SearchForm fields with correct data types, so validation will be handled there.
Form will also contain a special method, that will inject choices based on aggregation results.
