### ISSUE TITLE
Checkout - style should fit rest of the page.

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#699]
We've agreed to don't start whole checkout flow modification in this sprint, because lack of time. But the styles should be improved to deliver consistent experience across whole store.

* [x] Shipping method
* [x] Summary
* [x] Payment

**Comment by weronka** [comment]
Checkout steps with styles:

![ch1](https://cloud.githubusercontent.com/assets/9913546/21546331/5f1d770e-cdde-11e6-8745-b2ba87402121.png)
![ch2](https://cloud.githubusercontent.com/assets/9913546/21546330/5f1cd06a-cdde-11e6-8232-1eb7be0264e9.png)
![ch3](https://cloud.githubusercontent.com/assets/9913546/21546332/5f1e0e58-cdde-11e6-809b-3758b653c3e8.png)
![ch4](https://cloud.githubusercontent.com/assets/9913546/21546333/5f1e6268-cdde-11e6-998e-67c54ca4998b.png)
![ch5](https://cloud.githubusercontent.com/assets/9913546/21546334/5f1f68de-cdde-11e6-9350-2b4c315d628a.png)
