### ISSUE TITLE
The product listing page returns a huge amount of json data

### ISSUE THREAD

**Issue by liuxinnian** [mirumee/saleor#7004]
### What I'm trying to achieve
I am using saleor3 alpha, and I have uploaded 3,000 products in the system, and now it is very slow to open the product list page.
I checked the XHR request in chrome and found that the GraphQL interface returned 7.8MB of JSON data, with 110,000 rows after formatting. And the interface response time exceeds about 1 minute.
I'm not sure if this is a bug, but it is a serious problem. I uploaded the JSON data of the product list page, hope it helps.
[products.json.zip](https://github.com/mirumee/saleor/files/6138485/products.json.zip)

In addition, the number of rows in the database may help:
channel_channel: 9 rows
product_products: 3,391 rows
product_category: 235 rows,
product_collection: 93 rows,
attribute_attribue: 11 rows,
attribute_attributevalue: 4,661 rows,

### Steps to reproduce the problem
1. Upload a large number of products.
2. Open the product list page and view the JSON data returned by the GraphQL interface.

### Screenshots

![20210313151657](https://user-images.githubusercontent.com/562357/111022674-3005e280-840f-11eb-9b7b-d67de6c63f87.jpg)

I configured Jaege and found that the execution time of many requests exceeded 1 minute.
![20210313153123](https://user-images.githubusercontent.com/562357/111022972-34cb9600-8411-11eb-9269-69d269bcf8f8.jpg)

**System information**
Saleor version: 3.0.0-a.10

**Comment by mitraxis** [comment]
That's interesting. Any update @liuxinnian? Did you manage to solve the issue?

**Comment by liuxinnian** [comment]
> That's interesting. Any update @liuxinnian? Did you manage to solve the issue?

Not yet. I found some GraphQL statements that took a long time and returned too large data, but I still have no solution.

**Comment by liuxinnian** [comment]
After analyzing with Jaeger, it is found that when the File attribute is set, the File attribute will be repeatedly queried when reading the product list, which will generate hundreds of thousands of requests and take more than 10 seconds. We will look at the code to try to solve this problem.
![20210316113947](https://user-images.githubusercontent.com/562357/111252565-595f8200-864c-11eb-8c7d-4c47a3f6cb34.jpg)

**Comment by maarcingebala** [comment]
The issue may be on both sides - in the dashboard and in the API. First, it seems that the product list fetches `attributes` for each product and I'm wondering if that's needed for that view. Maybe we could optimize the query on the dashboard side and not fetch this field for each product as it is expensive. Second, we should make sure that API uses proper data loaders to fetch attributes from the database.

**Comment by liuxinnian** [comment]
Yes, this problem exists in both dashboard and api. We use this file attribute to configure a separate detailed picture for the product, and read this attribute on the front end. Maybe we shouldn't use it like this.

**Comment by maarcingebala** [comment]
Does it execute any duplicated database queries? It shouldn't since file attributes don't include any additional models, they just use Attribute and AttributeValue models and these should be optimized with data loaders in the API. I'm wondering what's the slow part when using file attributes. They only return plain URLs.

**Comment by liuxinnian** [comment]
It may not be a duplicated query, we think it should be a database relationship problem for reading attributes. There are only 3300 records, but after the product table and attribute table are joined, the query result returns 80,000 rows of data.

BTW: We just added the file attributes to the product, then upload the image, and then read it from the front end. I uploaded a screenshot to see it.
Dashboard:
![20210316181030](https://user-images.githubusercontent.com/562357/111293584-639d7280-8684-11eb-9bf4-afdd43ba76df.jpg)
Storefront: 
https://saleor.ohayobebe.com/product/110-160/2148/

**Comment by liuxinnian** [comment]
> Does it execute any duplicated database queries? It shouldn't since file attributes don't include any additional models, they just use Attribute and AttributeValue models and these should be optimized with data loaders in the API. I'm wondering what's the slow part when using file attributes. They only return plain URLs.

We made a small modification, and the execution time was reduced from 10 seconds to 3 seconds.

in salero-dashboard: 
src/searches/useProductTypeSearch.ts
`
export const searchProductTypes = gql`
  ${attributeValueFragment}
  ${pageInfoFragment}
  ${taxTypeFragment}
  query SearchProductTypes($after: String, $first: Int!, $query: String!) {
    search: productTypes(
      after: $after
      first: $first
      filter: { search: $query }
    ) {
      edges {
        node {
          id
          name
          hasVariants
          productAttributes {
            id
            inputType
            slug
            name
            valueRequired
            values {
              ...AttributeValueFragment
            }
          }
          taxType {
            ...TaxTypeFragment
          }
        }
      }
      pageInfo {
        ...PageInfoFragment
      }
    }
  }
`;
`

I commented these lines:
`
            values {
              ...AttributeValueFragment
            }
`

Then, the data is no longer returned as much, and the speed is much faster.

@maarcingebala   I'm not sure if this modification will cause other problems, do you have any suggestions?

**Comment by maarcingebala** [comment]
Thanks, I'll ask our frontend team to look at this issue and to verify the solution.

**Comment by jwm0** [comment]
After some more investigation on the frontend side we discovered there's some overlap in queries on the product list and the batched request can contain less queries. Attributes in general are being over-fetched and what you @liuxinnian suggested is part of the problem. We'll put this on our high-priority list and get this sorted soon. Thanks for bringing this up!

**Comment by liuxinnian** [comment]
Great, so that we won't worry about this problem anymore. 
However, we will no longer use file attributes to store product images.

**Comment by jwm0** [comment]
You can track the frontend part of this task here: https://github.com/mirumee/saleor-dashboard/pull/1016
