### ISSUE TITLE
Better search (using regexp in queries)

### ISSUE THREAD

**Issue by gax97** [mirumee/saleor#7019]
### What I'm trying to achieve
I would like to have more complex search queries.
If I want to search for 2 names of products for example I have to run two queries.

### Describe a proposed solution
Can we add support for regex strings in search?

**Comment by krzysztofwolski** [comment]
What's the use case for such search? Customer storefront/dashboar?

**Comment by gax97** [comment]
You can also access saleor from other apps, for that use-case it's useful to have more complex search queries when you want to get specific products.

**Comment by krzysztofwolski** [comment]
There was some research done on our side and we decided that we will come back to search later - probably in Saleor 4.0. So we are speaking about a year from now.

If you need more complicated requests right now there are 2 options:
- filter products on client-side
- create an app for product data synchronization and sync with elasticsearch

**Comment by gax97** [comment]
@krzysztofwolski Are there any docs on how to do the second option you mentioned?

**Comment by krzysztofwolski** [comment]
@gax97 https://docs.saleor.io/docs/3.0/developer/extending and section apps. 

As starting point for building apps you can use my personal boilerplate: https://github.com/krzysztofwolski/saleor-best-app
