### ISSUE TITLE
Buyer login using their Mobile Number

### ISSUE THREAD

**Issue by shailendrasingh** [mirumee/saleor#7024]
### Very important for Semi Literate Buyers in country like India

In India, still a lot of people do not have email or even if they have they rarely use it. So allowing a user to login using Mobile Number or Social Login like Facebook and Google is important for success of an e-commerce here in India.

### Proposed solution
We should be having a Login configuration in **Saleor Dashboard** to configure for Mobile number based login and Optional login using Social Sites.

**Comment by adlmez** [comment]
The same feature will be very useful for China!

**Comment by everestkid** [comment]
Is there any update on this feature
