### ISSUE TITLE
are product class labels switched?

### ISSUE THREAD

**Issue by itbabu** [mirumee/saleor#704]
Hello,
I'm looking at the new product class feature.

About the labels ... should not be the other way around?
https://github.com/mirumee/saleor/blob/master/saleor/dashboard/product/forms.py#L53-L59

![schermata del 2016-12-29 17-05-55](https://cloud.githubusercontent.com/assets/650691/21547927/6e6023b4-cde9-11e6-92a3-b1b16fa41ab1.png)

![schermata del 2016-12-29 17-06-31](https://cloud.githubusercontent.com/assets/650691/21547913/592f5636-cde9-11e6-83b3-40160b51b2b5.png)

**Comment by krzysztofwolski** [comment]
You are right! Thanks :)
