### ISSUE TITLE
Product and order review, and feedback features

### ISSUE THREAD

**Issue by Sarowar-neo** [mirumee/saleor#7057]

**Comment by krzysztofwolski** [comment]
Adding build-in reviews is not on our roadmap. You can integrate with any of the external services: https://www.predictiveanalyticstoday.com/top-product-reviews-platform/

Review platforms need additional management for spam, moderating content, etc., so it's a good idea to use a specialized platform for that.

**Comment by gorjan-mishevski** [comment]
This would be an awesome feature to have definitely. Especially in developing countries where online purchases are still not trusted.
