### ISSUE TITLE
`checkoutUpdate` mutation

### ISSUE THREAD

**Issue by sagital** [mirumee/saleor#7099]
### What I'm trying to achieve
The flow for my e-commerce store is to create a guest checkout where the users can add / delete items, actions which are tracked on the server side. At the end when the user enters his checkout information (email, shipping method, shippingAddress, billingAddress) I would like to update them all at once, now I have to perform 4 different actions in orders to achieve this ( `checkoutEmailUpdate`, `checkoutShippingAddressUpdate`, `checkoutShippingMethodUpdate`, `checkoutBillingAddressUpdate`)  
...

My suggestion is to create a mutation called let's say `checkoutUpdate` which takes any of these parameters and updates the checkout accordingly

**Comment by krzysztofwolski** [comment]
We don't plan such change in the near future. You can always batch queries and send them at once.

**Comment by sagital** [comment]
OK, but it worth noting that I can't batch all the queries because  `checkoutShippingAddressUpdate` must be called before `checkoutShippingMethodUpdate`  so all the request take a little over one second which is not  higher than the recommended treshold (500ms)
