### ISSUE TITLE
type of the id in PaymentGateway

### ISSUE THREAD

**Issue by gsoec** [mirumee/saleor#7128]
### What I'm trying to achieve
https://github.com/mirumee/saleor/blob/7ff1c9da21607e8265b5d2b76e3ccb9788ef3cc4/saleor/graphql/schema.graphql#L3758-L3763
The type of `id` should be `String!`?

### Steps to reproduce the problem
1.
2.

### What I expected to happen
…

### Screenshots

**System information**

Operating system:
Saleor version: latest

**Comment by krzysztofwolski** [comment]
ID type is intended :) 
You can read more about ID scalar at our docs: https://docs.saleor.io/docs/3.0/developer/api-reference/scalars/id

**Comment by gsoec** [comment]
I try to query
```graphql
{
  shop{
    availablePaymentGateways {
      id
    }
  }
}
```
return something like
```json
{
  "data": {
    "shop": {
      "availablePaymentGateways": [
        {
          "id": "mirumee.payments.dummy"
        },
        {
          "id": "mirumee.payments.dummy_credit_card"
        }
      ]
    }
  }
}
```
