### ISSUE TITLE
Product collections

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#720]
Add ability to organize products in collections. Collections should be manageable with the dasboard.

Collection is a set of products that can be in different categories (for example: New arrivals, Winter 2016/2017)

**Comment by artursmet** [comment]
As we discussed with @patrys, we should modify current Collections implementation:
* Product can be in many collections
* Collections shouldn't be displayed in site navigation
* On product page we should display a carousel (or a couple of them) with product from the same collection as currently viewed product
* Product carousels should be loaded asynchronously (a partial template can be loaded from dedicated view)

**Comment by elwoodxblues** [comment]
We've merged initial implementation of collections that adds necessary models and dashboard views. Instead of showing the products carousel, we've decided to add a list view similar to the category view, that will show all products from a collection (this will be added in a separate PR).
