### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by OsamaDaghestani** [mirumee/saleor#7203]
### What I'm trying to achieve
…
hello so i am get invalid syntax for every code with := in it example 
`    if file_url := instance.file_url:
        delete_from_storage_task.delay(file_url)`
do i have to change all the code with := to != or do i have to something else thanks in advance

Saleor version:
- [x] dev (current master)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

**Comment by d-wysocki** [comment]
Hey, assigment oparetor `:=` it's available from python 3.8, it's look like you're using wrong python version and this cause the syntax error. You should use python 3.8 or higher for Saleor also please check requirements in `README.md` before you will run Saleor.
https://github.com/mirumee/saleor#installation
