### ISSUE TITLE
Wishlists

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#721]
When product is not available, customer should be able to set a notifications for this product.

* One user has only one wishlist
* Wishlist can be shared with a special URL
* When combination of products does not exist, it should be possible to add it to a wishlist
* When product gets back in stock, customer should be notified that observed product is now available

**Comment by krzysztofwolski** [comment]
@artursmet 
> combination of products does not exist
Did you meant combination of attributes? (variant)

**Comment by artursmet** [comment]
@krzysztofwolski Yes, there was a typo

**Comment by Pacu2** [comment]
Closing in favor of https://github.com/mirumee/saleor/issues/4040
