### ISSUE TITLE
Bug: unable to look up configurable product variants by SKU

### ISSUE THREAD

**Issue by onecrayon** [mirumee/saleor#7245]
### What I'm trying to achieve

I created a ProductType with `hasVariants` set to `True`, and a single `variantAttribute` (dropdown named "Size" with values like "S", "M", or "L"). I then created a base product "Some Shirt" and productVariants with SKUs like `SOME-SHIRT-S` and `SOME-SHIRT-L`. When I try to query GraphQL for the variant SKUs, though, I get nothing back (I expect to get a normal response); querying by ID works perfectly. Am I misunderstanding how this is supposed to work? Why would querying by SKU be different than querying by ID?

### Steps to reproduce the problem

1. Setup your configurable product per instructions above (I'm assuming you have a channel named "default" setup)
2. Run the following query:
    ```
    query {
      productVariant (sku: "SOME-SHIRT-S", channel: "default") {
        id,
        sku,
      }
    }
    ```
3. You'll get a null response:
    ```
    {
      "data": {
        "productVariant": null
      }
    }
    ```
4. Look up the ID for the variant in the Dashboard, and query that:
    ```
    query {
      productVariant (id: "SOMEID", channel: "default") {
        id,
        sku,
      }
    }
    ```
5. This works:
    ```
    {
      "data": {
        "productVariant": {
          "id": "SOMEID",
          "sku": "SOME-SHIRT-S",
        }
      }
    }
    ```

Querying a simple product by SKU (with `hasVariants` set to `False`) works perfectly.

### What I expected to happen
Response from searching for the SKU should be identical to searching for the ID.

### Screenshots and logs

**System information**

Saleor version:
- [ ] dev (current master)
- [x] 3.0 (3.0.0-a.20)
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux (in Docker container provided by Saleor root project)
- [ ] MacOS
- [ ] Other

**Comment by Grunze1s** [comment]
Hi, I tried the steps to reproduce the problem but I could not reproduce them. Could you please provide more details on the problem?
I tried on both sku and id query. And also on both hasVariants set to True and False. all works perfectly.

**Comment by onecrayon** [comment]
@Grunze1s I will test this on my local install (and ensure that I'm running the latest alphas) tomorrow and let you know if it works or not!

**Comment by onecrayon** [comment]
@Grunze1s I think that an internal change must have fixed this as a side effect, because I am unable to reproduce it anymore with the most up-to-date alpha.
