### ISSUE TITLE
CheckoutCreate runs check_stock_quantity_bulk twice

### ISSUE THREAD

**Issue by gsoec** [mirumee/saleor#7286]
check_stock_quantity_bulk runs twice and a bit slow in a large database.
https://github.com/mirumee/saleor/blob/86aecd86220263ec456a33591357b07027ce0e0c/saleor/graphql/checkout/mutations.py#L253
https://github.com/mirumee/saleor/blob/86aecd86220263ec456a33591357b07027ce0e0c/saleor/graphql/checkout/mutations.py#L139
https://github.com/mirumee/saleor/blob/86aecd86220263ec456a33591357b07027ce0e0c/saleor/graphql/checkout/mutations.py#L367
https://github.com/mirumee/saleor/blob/86aecd86220263ec456a33591357b07027ce0e0c/saleor/checkout/utils.py#L133

**Comment by krzysztofwolski** [comment]
@fowczarek I think it's something you could investigate?
