### ISSUE TITLE
Links to Product with preselected variant attributes

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#729]
It would be nice to have links to product with selected variant attributes, even if there is no such varriant in database. This could be used for links in wishlist.
Use case:

1. User selects on product_details view product which is currently not available
2. User add it to wishlist
3. When clicking on this product in wishlist view
4. Details page should show product with chosen attributes

**Comment by krzysztofwolski** [comment]
@artursmet @maciekjablonski  What do you think about this feature? Any missing points?

**Comment by artursmet** [comment]
It looks good, we can serialize attributes set in GET variables and set initial state for variant selector
