### ISSUE TITLE
Add Login/signup through mobile number

### ISSUE THREAD

**Issue by Grunze1s** [mirumee/saleor#7354]
Add Login/signup through mobile number

In today's world with the increasing reach of smartphones in everyone's hand, people have been more accustomed to smartphone friendly system. Smartphone users make the bulk of web and e-commerce users. Due to this, simple sign up and verification with OTP sent to the mobile number has become popular in most e-commerce platforms and people are getting used to it. Furthermore, OTP sent to the mobile number is a more secure form of verification and multiple users with fake email registrations can be prevented using the OTP to mobile number verification.

1. Signup user either through mobile number or email in update user can add the missing field.
2. Login user through either mobile number or email - or both
3. Use OTP for verification for both mobile number and email - also include the url for email.

Proposed Solution
1. Add a new field phone_number with attribute unique=True, blank=True, null=True
2. Modify email field to unique=True, blank=True, null=True
3. Create a new mutation for signup using phone_number where phoneNumber field is required or Modify the existing accountRegister mutation to handle both phone_number and email with required = False and validation to have either one.
4. Same goes for login/tokenCreate mutation.

**Comment by krzysztofwolski** [comment]
Feature already requested in #7024
