### ISSUE TITLE
Why isn't Order included in updateMeta ? Can we add it?

### ISSUE THREAD

**Issue by LeOndaz** [mirumee/saleor#7355]
Quoted from the docs:

The following models contain metadata fields which data can be modified:
- Attribute
- Category
- Checkout
- Collection
- Product
- ProductVariant
- ProductType
- App
- User
- Warehouse

Can we add it? Is it included as a functionality but not in the docs or it's not included on purpose ?

**Comment by maarcingebala** [comment]
I think it's an omission in the docs because as I check it now, API allows updating metadata for orders.

**Comment by LeOndaz** [comment]
Okay thanks. I should've tested before posting this. I'll close.
