### ISSUE TITLE
Invoice plugin error django.core.exceptions.SuspiciousFileOperation

### ISSUE THREAD

**Issue by hernad** [mirumee/saleor#7377]
### What I'm trying to achieve

Generate invoice

### Steps to reproduce the problem

Try generate invoice from dashboard

### What I expected to happen

Exception error like:
<pre>
  File "/home/ernad.husremovic/saleor/saleor/saleor/plugins/manager.py", line 155, in __run_method_on_single_plugin
    returned_value = plugin_method(*args, **kwargs, previous_value=previous_value)
  File "/home/ernad.husremovic/saleor/saleor/saleor/plugins/invoicing/plugin.py", line 30, in invoice_request
    invoice.invoice_file.save(
  File "/home/ernad.husremovic/.local/lib/python3.9/site-packages/django/db/models/fields/files.py", line 88, in save
    name = self.field.generate_filename(self.instance, name)
  File "/home/ernad.husremovic/.local/lib/python3.9/site-packages/django/db/models/fields/files.py", line 316, in generate_filename
    filename = validate_file_name(filename)
  File "/home/ernad.husremovic/.local/lib/python3.9/site-packages/django/core/files/utils.py", line 8, in validate_file_name
    raise SuspiciousFileOperation("File name '%s' includes path elements" % name)
django.core.exceptions.SuspiciousFileOperation: File name 'invoice-1/05/2021-order-18-68d4bc37-bb91-496b-8699-0f63543d76bb.pdf' includes path elements
</pre>

### Screenshots and logs

**System information**

Saleor version:
- [x] dev (current master)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by hernad** [comment]
The cause of problem is US date format (slashes in date). This patch fixes the problem:

```
diff --git a/saleor/plugins/invoicing/plugin.py b/saleor/plugins/invoicing/plugin.py
index 2bd6e2ff6..39ea3cd68 100644
--- a/saleor/plugins/invoicing/plugin.py
+++ b/saleor/plugins/invoicing/plugin.py
@@ -28,7 +28,7 @@ class InvoicingPlugin(BasePlugin):
         file_content, creation_date = generate_invoice_pdf(invoice)
         invoice.created = creation_date
         invoice.invoice_file.save(
-            f"invoice-{invoice.number}-order-{order.id}-{uuid4()}.pdf",
+            f"invoice-{invoice.number.replace('/','-')}-order-{order.id}-{uuid4()}.pdf",
             ContentFile(file_content),
         )
         invoice.status = JobStatus.SUCCESS

```

**Comment by krzysztofwolski** [comment]
Thanks for reporting!
Fixed in https://github.com/mirumee/saleor/pull/7376
