### ISSUE TITLE
Consider running live demo somewhere on the internet

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#738]
Demo should be available from project page, new users should be able to login to the dashboard. Some auto-wipe mechanism should be implemented there.

Initial concept:
* Run two separate sites, one with storefront, second with the dashboard
* Storefront will contain generated database of products, checkout and dummy payment will be available there
* When anonymous user enters /dashboard/ he will be redirected to a form, where some basic information will be gathered like: name and e-mail. After submitting a form, someone from the team will execute a script that will create an superuser account on the dashboard instance.
* User will be notified with an e-mail, about superuser account

**Comment by krzysztofwolski** [comment]
[Saleor demo](http://demo.getsaleor.com/) is up and running
