### ISSUE TITLE
`Captured amount` is Twice the `Total` Amount Resulting in `Outstanding Balance`

### ISSUE THREAD

**Issue by Pczek** [mirumee/saleor#7399]
### What I'm trying to achieve
Every order has double the `captured amount` than the actual checkout had `total` costs. This is quite weird. 
We have two transactions for the `payment`, two times with the sum of the `total` of the checkout. No clue why this happens the `captured amount` should be the same as the checkout total. It's confusing that we have `outstanding balances`.  AFAIK we don't create the `transactions` ourselves. We only do a `checkoutPaymentCreate`, see below for further description.

<img width="861" alt="Screenshot 2021-05-26 at 13 23 49" src="https://user-images.githubusercontent.com/839848/119652874-f007a680-be26-11eb-8492-0fd1ea565373.png">

<img width="1751" alt="Screenshot 2021-05-26 at 13 25 49" src="https://user-images.githubusercontent.com/839848/119652880-f3029700-be26-11eb-84a5-3a8d67ba2287.png">

### Steps to reproduce the problem
We are using Saleor with Adyen as a payment gateway.
We are using this library to get he payment data to send via the `completeCheckout` mutation https://github.com/YouriT/react-native-adyen-drop-in

1. `checkoutCreate`
2. get `paymentData` via the Adyen React-Native Library
2. `checkoutPaymentCreate`
2. `checkoutComplete`

If I don't create a Payment (`checkoutPaymentCreate`) before completing the checkout I get the following errors:
`CHECKOUT_NOT_FULLY_PAID - Provided payment methods can not cover the checkout's total amount`

### What I expected to happen
…

### Screenshots and logs

**System information**
Saleor version:
- [ ] dev (current master)
- [ ] 3.0
- [x] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

**Comment by karolkielecki** [comment]
Thanks for reporting! I've passed the issue to the team.

**Comment by IKarbowiak** [comment]
Hi @Pczek,

Could you show us how the mutations you sent looks like? I was trying to reproduce your problem but I couldn't. Also, let us know what method are you using for Adyen payment. Are you testing it with example credit cards/klarna/paypal/paysafecard?

**Comment by Pczek** [comment]
@IKarbowiak  thanks for getting back to me. Here's a detailed description of the payment flow we are using.
I guess it's somehow related with the implementation of the `Adyen` Saleor Plugin 🤔 

1. Create Checkout via `checkoutCreate`:

```graphql
Apollo query mutation CreateSaleorCheckout($input: CheckoutCreateInput!) {
  checkoutCreate(input: $input) {
    checkout {
      ...SaleorCheckout
      __typename
    }
    checkoutErrors {
      ...SaleorCheckoutError
      __typename
    }
    __typename
  }
}
```

2. Optional: Retrieve Checkout via token using `checkout`: 

```graphql
Apollo query query GetSaleorCheckout($token: UUID!) {
  checkout(token: $token) {
    ...SaleorCheckout
    __typename
  }
}
```

3. Adding some MetaData to the checkout we need for delivery using `updateMetadata`:

```graphql
Apollo query mutation UpdateSaleorMetaData($id: ID!, $input: [MetadataInput!]!) {
  updateMetadata(id: $id, input: $input) {
    item {
      metadata {
        key
        value
        __typename
      }
      __typename
    }
    metadataErrors {
      ...SaleorMetaDataError
      __typename
    }
    __typename
  }
}
```

4. Adding a Shipping Method to the checkout using `checkoutShippingMethodUpdate`:

```graphql
Apollo query mutation UpdateSaleorCheckoutShippingMethod($checkoutId: ID!, $shippingMethodId: ID!) {
  checkoutShippingMethodUpdate(
    checkoutId: $checkoutId
    shippingMethodId: $shippingMethodId
  ) {
    checkout {
      ...SaleorCheckout
      __typename
    }
    checkoutErrors {
      ...SaleorCheckoutError
      __typename
    }
    __typename
  }
}
```

5. Making a Payment with the Adyen Drop In using a Stored Credit Card ⇒ getting `paymentData` to be sent to Saleor to complete the checkout in Step 8

<img width="487" alt="Screenshot 2021-06-03 at 12 09 22" src="https://user-images.githubusercontent.com/839848/120629615-48adf380-c466-11eb-852a-a5e7fc08a68c.png">


6. Update Billing Address with `checkoutBillingAddressUpdate`:

```graphql
Apollo query mutation UpdateSaleorCheckoutBillingAddress($checkoutId: ID!, $billingAddress: AddressInput!) {
  checkoutBillingAddressUpdate(
    checkoutId: $checkoutId
    billingAddress: $billingAddress
  ) {
    checkout {
      ...SaleorCheckout
      __typename
    }
    checkoutErrors {
      ...SaleorCheckoutError
      __typename
    }
    __typename
  }
}
```

7. Create a Payment

```graphql
Apollo query mutation CreateSaleorCheckoutPayment($checkoutId: ID!, $input: PaymentInput!) {
  checkoutPaymentCreate(checkoutId: $checkoutId, input: $input) {
    checkout {
      ...SaleorCheckout
      __typename
    }
    payment {
      ...SaleorPayment
      __typename
    }
    paymentErrors {
      ...SaleorPaymentError
      __typename
    }
    __typename
  }
}
```

With these variables:

QUESTION: what is the token here? I think we are sending the checkout token here again. Not sure what to use here 🤷

```graphql
Apollo variables {
    "checkoutId": "Q2hlY2tvdXQ6OTVkMTljZGUtODhjMS00ZTI0LWIyMjAtNWQyODFjYjAzNjEw",
    "input": {
        "gateway": "mirumee.payments.adyen",
        "token": "95d19cde-88c1-4e24-b220-5d281cb03610"
    }
}
```

8. Complete Checkout using `checkoutComplete` using the `paymentData` from step 5.

```graphql
Apollo query mutation CompleteSaleorCheckout($checkoutId: ID!, $paymentData: JSONString!) {
  checkoutComplete(checkoutId: $checkoutId, paymentData: $paymentData) {
    order {
      ...SaleorOrder
      __typename
    }
    checkoutErrors {
      ...SaleorCheckoutError
      __typename
    }
    confirmationNeeded
    confirmationData
    __typename
  }
}
```

After this I end up with the correct order and total amount but the `Captured amount` is twice as high.

<img width="865" alt="Screenshot 2021-06-03 at 12 21 36" src="https://user-images.githubusercontent.com/839848/120629567-3f248b80-c466-11eb-9c76-363c0311fa98.png">

Using this query I can see that we have two transactions with the same amount, maybe causing this doubled amount 🤔

```graphql
query{
  order(id:"T3JkZXI6MzQ3NTI="){
    payments{
      total{
        amount
      }
      gateway
      isActive
      chargeStatus
      transactions{
        kind
        error
        created
        isSuccess
        token
        
        amount{
          amount
        }
      }
      modified
      capturedAmount{
        amount
      }
      availableCaptureAmount{
        amount
      }
    }
  }
}
```

```json
{
  "data": {
    "order": {
      "payments": [
        {
          "total": {
            "amount": 0.29
          },
          "gateway": "mirumee.payments.adyen",
          "isActive": true,
          "chargeStatus": "FULLY_CHARGED",
          "transactions": [
            {
              "kind": "CAPTURE",
              "error": null,
              "created": "2021-06-03T10:12:48.794759+00:00",
              "isSuccess": true,
              "token": "1849227151686287",
              "amount": {
                "amount": 0.29
              }
            },
            {
              "kind": "CAPTURE",
              "error": null,
              "created": "2021-06-03T10:12:48.902805+00:00",
              "isSuccess": true,
              "token": "6249227151680061",
              "amount": {
                "amount": 0.29
              }
            }
          ],
          "modified": "2021-06-03T10:12:48.909222+00:00",
          "capturedAmount": {
            "amount": 0.58
          },
          "availableCaptureAmount": null
        }
      ]
    }
  }
}
```

**Comment by korycins** [comment]
Hey @Pczek 
- Can you provide more details about plugin's configuration on Saleor side? These switches will be enough 👇 
![image](https://user-images.githubusercontent.com/23282005/120975595-b5303780-c771-11eb-813d-73624e8cd851.png)
- Can you confirm that on the Adyen side you have enabled only one webhook for your Saleor instance?
- Does the issue happen on your local instance? Are you able to insert some print/debug breakpoint? Would be good to know what webhook's events you're receiving.
- Do you have any msg in order history section?

**Comment by Pczek** [comment]
Hi @korycins 
> Can you provide more details about plugin's configuration on Saleor side? These switches will be enough 👇

Both of these switches are on. While we struggled a bit connecting adyen with saleor we never gave to much thought about these switches. I still don't really know what these would mean for us right now. 🤔 

> Can you confirm that on the Adyen side you have enabled only one webhook for your Saleor instance?

Yep can confirm, we only have one `Standard Notification` per instance. (We had this issue even when we only single instance) We have `merchant-accounts` for each instance and have `Standard Notification` webhooks for each `merchant account`

> Does the issue happen on your local instance? Are you able to insert some print/debug breakpoint? Would be good to know what webhook's events you're receiving.

The instances run in kubernetes in production, so not super straightforward and a good idea to add some breakpoints 🙈 :)


> Do you have any msg in order history section?

Ah true, this looks odd! Looks like it really tried to capture the amount twice!
Is this related to the toggle setup? 🤔 

<img width="891" alt="Screenshot 2021-06-07 at 09 58 48" src="https://user-images.githubusercontent.com/839848/120980552-0262d800-c777-11eb-9bdf-00495d9505aa.png">

**Comment by korycins** [comment]
Hey @Pczek , 
Your configuration is incorrect.  The two switches are mutually exclusive. Now you tell Saleor to assume that all payments are captured on Adyen side and then you tell Saleor to make capture action (Some actions are process async so we are not able to know that you already mark this payment as a captured).  I know that interface for this is not very intuitive but it is related to the limitation of the dynamic plugins view. 

From the docs:
Assume all authorizations are automatically captured by Adyen: All authorized payments will be marked as captured. This should only be enabled if Adyen is configured to auto-capture payments. Saleor doesn’t support the delayed capture Adyen feature.

Automatically capture funds when a payment is made: If enabled, Saleor will automatically capture funds. If disabled, the funds are blocked but need to be captured manually.

Let me know if this solve your issue

**Comment by Pczek** [comment]
This did the trick. Thanks. Yes i realised it as well when i was reading the information bubbles in the ui. 
Maybe an additional hint underneath one of the toggles would help or can't the ui be responsive to deactivate the other if one is activated? 

Thanks for the help 🙏
