### ISSUE TITLE
Introduce VatLayer integration

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#742]
https://vatlayer.com/ integration will be a nice Addon to current saleor setup.

Couple of assumptions:
* Move to separated package like https://github.com/mirumee/django-prices-openexchangerates
* Package should deliver a Model that will keep vat rates
* Integration on saleor side has to be discussed - products should be tagged in some way, to use correct tax rate
* Package should deliver a manegement command that will handle rates update

**Comment by patrys** [comment]
Integration plan:

* [ ] provide a model to store per-country tax rates and reduced tax rates (JSON field? hstore?)
* [ ] write a function that makes a request to the `http://apilayer.net/api/rate_list` endpoint and updates the database accordingly
* [ ] write a management command that calls the above function so we can call it once per day
* [ ] write a function that takes a country code and a rate name (to handle reduced rates -- list available at `http://apilayer.net/api/types`) and returns a tax price modifier

**Comment by patrys** [comment]
For Saleor integration we need to introduce a country picker in the UI in case GeoIP gets it wrong.

**Comment by artursmet** [comment]
* [ ] Implement `PriceModifier` (ref: https://github.com/mirumee/django-prices-openexchangerates/blob/master/django_prices_openexchangerates/__init__.py#L16)
This modifier will apply a VAT to a `Price`
* [ ] Implement an utility function that will return correct `PriceModifier` for selected country

**Comment by curaloucura** [comment]
Hi, what is the status of this issue? This is currently a blocker for my project and before I start developing a palliative solution I'd like to double check the status as the last update is three months ago.

**Comment by patrys** [comment]
The prices library is in place, we're waiting for a legal review of tax intricacies involved in serving b2b and b2c clients.

**Comment by curaloucura** [comment]
Good to hear, so if time gets too tight for my project I will use the PR as an interim solution and see how to merge things later, not bothering redoing the wheel.

**Comment by curaloucura** [comment]
it's been six months since last update. Any new information about this implementation? Is there any shop online with Saleor? I can't imagine how it could go live without a proper VAT implementation and the VAT branch is quite outdated, so I was wondering if I still should use it.

**Comment by Pacu2** [comment]
Tax support was introduced in #1929 💸
