### ISSUE TITLE
can we integrate saleor and woocommerce? 

### ISSUE THREAD

**Issue by sidhumanjinder** [mirumee/saleor#7428]
### What I'm trying to achieve

... for example if i add,update,detete products or any item in saleor it shows output on woocommerce site.Any idea or reference...? Thanks..

**Comment by krzysztofwolski** [comment]
It would be possible by creating external app which would send data to woocommerce. Heres documentation for creating Saleor Apps: https://docs.saleor.io/docs/3.0/developer/extending/apps/key-concepts
