### ISSUE TITLE
REST API Documentation 

### ISSUE THREAD

**Issue by solvire** [mirumee/saleor#755]
I am trying to set up a trial ecommerce site and one of the more important elements to me is REST layers because we are going to support mobile heavily. 

What are the plans for REST. I don't see much talk going on and I would like to hear what is planned. Any enhancements to the documentation would be very beneficial.  

I think I'll fork this project and start to work on various features that might be useful. I also can start a side project to make the REST layer a plugin or extension if it makes sense.

**Comment by patrys** [comment]
We're about to merge a GraphQL-based API together with a JS implementation of some of the views. Will that help?

**Comment by solvire** [comment]
Maybe.  Most mobile products I've worked on used a REST layer so I know what to expect there.
I'll look through once it is merged. 

Is this the direction the app is going in terms of JS and mobile?

**Comment by patrys** [comment]
GraphQL seems to be a great match for mobile where a single API call can return most of the data. As for general direction I'd like to follow where Google is headed with Progressive Web and AMP before building a native client but I'm very much interested to know if there's anything stopping our users from delivering great mobile experiences.

**Comment by solvire** [comment]
About 90% of what we need can be browser. 10% camera and GPS.
Honestly, I am not a mobile guy so the tip about AMP is great. It led me to some other cool solutions. Thanks for that and I am glad you guys are going that way. Makes total sense and gives me confidence you guys are rocking it. 

At this point I don't see a need for REST.  Most don't do it well anyway. 

I am finishing up an article on setting up and deploying Saleor and I will put out some articles on the mobile/design side later. :)
