### ISSUE TITLE
Errors due to channel filter sent by storefront queries

### ISSUE THREAD

**Issue by tmechsner** [mirumee/saleor#7601]
### What I'm trying to achieve
Setting up a Saleor instance with 3.0 backend and 3.0 storefront.

### Steps to reproduce the problem
1. Follow the instructions to setup a basic demo configuration of backend, database and storefront with 3.0 branches.
2. Build the storefront with `npm run build` -> when collecting static props, requests being sent to the backend fail. The backend rejects queries being sent by the frontend because it does not expect the queries to include a "channel" filter. 

I could quickfix this by removing the channel filter from the storefront (see [my comment on a related issue in the storefront](https://github.com/mirumee/saleor-storefront/issues/1067#issuecomment-876131985)) Then, I could set up the system. However, then I run into the next problem, which is very similar:

1. Try opening a category page, like in the demo shop via "ACCESSORIES" or "GROCERIES" in the top left corner.
2. The dev console reports an error "400 - bad request" on the graphql request to the backend.

### What I expected to happen
I expect the current state of branch 3.0 of backend and storefront to work well together. As channels are a feature to be included in saleor 3.0 I guess it is correct that the frontend includes the channel filter. In this case the backend should accept it.

### Screenshots and logs

This error gets reported several times when trying to build the storefront with npm run build:

```
2021-07-06 15:44:05 > WARNING django.request Bad Request: /graphql/ [PID:14:ThreadPoolExecutor-44_0]
2021-07-06 15:44:05 > INFO saleor.graphql.errors.handled A query had an error [PID:13:ThreadPoolExecutor-1_0]
2021-07-06 15:44:05 > graphql.error.base.GraphQLError: Argument "filter" has invalid value {channel: $channel, inCollection: $collectionId, inCategory: $categoryId, filterableInStorefront: true}.
2021-07-06 15:44:05 > In field "channel": Unknown field.
```

After quickfixing the ShopAttributeQuery, when trying to open a category page:

```
2021-07-07 09:17:11 > WARNING django.request Bad Request: /graphql/ [PID:14:ThreadPoolExecutor-86_0]
2021-07-07 09:17:11 > INFO saleor.graphql.errors.handled A query had an error [PID:12:ThreadPoolExecutor-1_0]
2021-07-07 09:17:11 > Traceback (most recent call last):
  File "/app/saleor/graphql/views.py", line 283, in execute_graphql_request
    response = document.execute(  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/graphql/backend/core.py", line 32, in execute_and_validate
    return execute(schema, document_ast, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py", line 113, in execute
    exe_context = ExecutionContext(
  File "/usr/local/lib/python3.9/site-packages/graphql/execution/utils.py", line 113, in __init__
    variable_values = get_variable_values(
  File "/usr/local/lib/python3.9/site-packages/graphql/execution/values.py", line 74, in get_variable_values
    raise GraphQLError(
2021-07-07 09:17:11 > graphql.error.base.GraphQLError: Variable "$filter" got invalid value {"attributes": [], "categories": ["Q2F0ZWdvcnk6MjA="], "channel": "default-channel", "collections": [], "price": {"gte": null, "lte": null}}.
2021-07-07 09:17:11 > In field "channel": Unknown field.
```

**System information**
Saleor version:
- [ ] dev (current master)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Storefront version:
- [ ] dev (current master)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [x] MacOS
- [ ] Other

**Comment by iromli** [comment]
yliyyi

**Comment by tmechsner** [comment]
Okay I have a workaround now, which feels kinda dirty. The issue is that the backend does not expect the channel field on the ProductFilter and on the AttributeFilter. However, the value of the channel field is being used by these filters. Hence, I just added the field to the filter. Adding it in the `fields` attribute of the `Meta` subclass is not possible, as the filter model Attribute and Product do not have an attribute named `channel`. Hence, I added the field as custom filter without effect:

(`graphql/attribute/filters.py`)
```
class AttributeFilter(MetadataFilterBase):
    ...
    channel = django_filters.CharFilter(method="noop_filter")

    def noop_filter(self, queryset, name, value):
        return queryset
    ...
```

And exactly the same in the ProductFilter in `graphql/product/filters.py`.
Additionally, there are several requests that do not use the channel filter yet but only request the "default channel" to be used. This is problematic in the demo database, as this contains two channels. The `get_default_channel()` helper function in `channel/utils.py` however raises an exception in case there's more than one channel. So I replaced this line
`channel = Channel.objects.get()` with this line `channel = Channel.objects.get(slug="default-channel")` in order to retrieve the default channel, no matter how many other channels there are. 
This hard-coded string should be replaced by some environment variable though.

This feels like a dirty workaround but it gets the current 3.0 branch to work. I really hope there won't be any further problems like this... otherwise, awesome piece of software! :)

I leave this issue open as a note for the staff because they probably want their demo shop fixed in the official codebase.

**Comment by maarcingebala** [comment]
It is correct that the API doesn't accept `channel` in the `filter` inputs - we introduce this change in order to simplify the API and provide the `channel` param only once in the top-level query, for example:
```
{
  products(channel: "default-channel", filter: {search: "hoodie"}, first: 5) {
    edges {
      node {
        name
      }
    }
  }
}
```
Before you had to provide it twice - in the top-level query and in the `filter` input.

The storefront got broken after this change and we're now working on a fix that will remove usages of the `channel` param in filter inputs in the storefront queries. As you said - fixing it for now in the backend is kind of "dirty" and overall, I wouldn't recommend it, but if it works for you to run it locally, it's fine. Just remember to remove these changes after we release the fix in the storefront.

**Comment by maarcingebala** [comment]
Should be fixed now on master: https://github.com/mirumee/saleor-storefront/pull/1072
