### ISSUE TITLE
REQUEST: Upload Flutter project for Tutorial: GraphQL in Flutter - Building a Mobile Shop using Saleor API

### ISSUE THREAD

**Issue by lilayoung** [mirumee/saleor#7609]
This is an amazing tutorial. Thank you. However, it seems that the link to the full sample code goes to the saleor main repository and not to the sample Flutter build repository itself.  Would you please be able to provide that? 

While this is a simple flutter project, it might be useful to be able to skim the code quickly at once before reading the tutorial, as well as a helpful refresher for those who have read through the article to see how it all fits together when complete. 

### Discussed in https://github.com/mirumee/saleor/discussions/7523

<div type='discussions-op-text'>

<sup>Originally posted by **karolkielecki** June 23, 2021</sup>
Looking for a tutorial on how to create an e-commerce app using Flutter and the Saleor GraphQL API? We’ve got it covered!

Read [the tutorial here](https://saleor.io/blog/graphql-in-flutter-building-a-mobile-shop-using-saleor-api-143/).

Learn how to create your own app step by step and share your work in the comments!

------------------
- [Twitter](https://twitter.com/getsaleor/status/1407685874305933317)
- [LinkedIn](https://www.linkedin.com/posts/saleor_graphql-saleor-activity-6813453331449573377-yH8x)</div>

**Comment by krzysztofwolski** [comment]
Example of flutter app: https://github.com/saleor/example-flutter
