### ISSUE TITLE
Amount discounted is inclusive of taxes

### ISSUE THREAD

**Issue by onecrayon** [mirumee/saleor#7664]
I have been going through the Saleor codebase as I work on implementing #7526, and at https://github.com/mirumee/saleor/blob/master/saleor/product/utils/availability.py#L231 the code appears to be calculating the discounted price + taxes, then calculating the undiscounted price + taxes, then returning the difference as the total discount.

If I understand how discounts are applied, though, the actual process is to apply discounts and then apply taxes, which means that calculating the discount this way leads to wrong numbers. Take a scenario where I'm buying something that costs $299, have a 5% discount code, and owe 10.1% taxes. You can obtain the actual amount that is discounted by calculating `$299 x .05 = $14.95`. However, Saleor appears to be doing the following:

* My undiscounted price with taxes is `$299 x .101 = $329.20`
* My discounted price with taxes is `($299 - ($299 x .05)) x .101 = $312.74`
* The difference between those two is `$329.20 - $312.74 = $16.46`, which is **not** the actual amount that is being discounted per the calculation above

I wanted to ask about this, because I wasn't sure if it was a bug or if I was misunderstanding what the code was actually doing.

**Comment by patrys** [comment]
@onecrayon Are you checking `discount.net` or `discount.gross`? The net value should give you discount pre-taxes (which you'd likely show to a US customer). The gross value is the effective post-tax discount (something you'd expect to see in Europe). Can you confirm those are incorrect and provide a test case?

**Comment by onecrayon** [comment]
@patrys So the intent here is that whoever consumes the output will only access the `discount.net` value rather than `discount.gross`? Okay, that makes a certain amount of sense, because that value should be correct. It's a little weird that discounts are tracked as TaxedMoney, but I don't think this is a bug, per se.

**Comment by patrys** [comment]
@onecrayon It really depends on the intended audience. In Europe, all discounts are reported on after-tax values (all shelf prices are gross prices). In the US, discounts are reported on pre-tax values (and shelf prices are net prices), as the tax is only mentioned during checkout.
