### ISSUE TITLE
Shipping/Billing addresses are backward in Webhook

### ISSUE THREAD

**Issue by adiffmike** [mirumee/saleor#7683]
The webhook is sending billing as shipping and vice versa.

https://github.com/mirumee/saleor/blob/496d6baa3488398ea99fc48025013561984cf0b3/saleor/webhook/payloads.py#L263

**Comment by maarcingebala** [comment]
Fixed in https://github.com/mirumee/saleor/pull/7760. Thanks for reporting @adiffmike!
