### ISSUE TITLE
Improve grid usage

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#772]
Whole template should be reviewed for incorrect usage of Bootstrap's grid system.

Some elements are misaligned or have inconsistent position in grid.

* Header (logo, search bar, cart widget) 
* cart dropdown

**Comment by benekex2** [comment]
Mobile menu icon with and without "MENU" string to compare. In my opinion second option is more readable.

![](http://image.prntscr.com/image/a5257c1e093340ec83d93d7b1114169a.png)
![](http://image.prntscr.com/image/2770b9ebe8cd4bebab39c167769d2d09.png)

**Comment by patrys** [comment]
I don't think "menu" looking like a fourth stripe helps...

**Comment by mirekm** [comment]
All evidence shows that the plain burger icon is not a good pattern. Adding Menu word makes it clear thus better from the UX point of view (aesthetics is only a secondary concern here).

**Comment by mirekm** [comment]
So if we have no other options I choose the version with Menu label.

**Comment by patrys** [comment]
It's not the word that is the problem, it's that it looks like it's part of the icon.

**Comment by patrys** [comment]
Also we need a plan to localise the word for non-English locale.

**Comment by mirekm** [comment]
Still better than with no label. @subgrafik can you have a look/do some research if we can improve it?

**Comment by mirekm** [comment]
I don't think localization should be a concern here to be honest. It's a demo shop and Menu is quite an international phrase. But even if so I suppose the label could be just a plain text not part of the SVG icon itself, right?

**Comment by patrys** [comment]
Hint: most of the world does not use the Latin alphabet.

**Comment by mirekm** [comment]
Does demo shop feature any other language than English?

**Comment by patrys** [comment]
Yes, we're partly localised to all languages supported by Django and we're about to merge translation support for products. Also I want the code to behave correctly even where content is currently missing. We should do things correctly with regard to i18n/l10n/t9n.

**Comment by mirekm** [comment]
Nonetheless I can't see this to be an issue in either way — Menu word can be (and possibly should be) localized as any other label as soon as our demo is fully localized (but it is not for now as far as I'm aware).

**Comment by mirekm** [comment]
Of course we should do things correctly and consistently across the board — localization is not an exception here.

**Comment by patrys** [comment]
Ok, so we agree that "MENU" should be a regular string marked with `{% trans %}`. Can we also get a screenshot with clickable areas highlighted? We should make sure there are no dead zones in the header where the user expects the action to work (like between icons and the edge of the screen for example).

**Comment by benekex2** [comment]
"MENU" as string
![](http://image.prntscr.com/image/8dbb9898ff604de7ade6446dec243102.png)

@patrys @mirekm

**Comment by patrys** [comment]
Positioning looks good, screenshot looks like if it came from VHS 😂
