### ISSUE TITLE
Fix "app_job" (app_appinstallation) status "pending" after successful 3rd party app installation

### ISSUE THREAD

**Issue by williamabreu** [mirumee/saleor#7863]
### What I'm trying to achieve

After installing a Third Party App into Saleor, I realized on the dashboard that the app I just installed is listed in the "Ongoing Installations" with the label "Installing app..." forever, as is shown in the screenshot below.

I figured out the model app_appinstallation in the database keeps the status pending even after the installation.

### Steps to reproduce the problem

1. Run the 3rd party app installation: "python manage.py install_app url-to-manifest"
2. Access the dashboard > Go to Apps left menu
3. See the Ongoing Installations forever listing Installing app... (with circle loading)

### What I expected to happen
- After the installation, nothing related to the app's just been installed appearing in the Ongoing installations.

### Screenshots and logs

![image](https://user-images.githubusercontent.com/23266568/129725935-9dd2de71-51a5-4636-bd1e-da4b801c6a87.png)

**System information**

Saleor version:
- [x] dev (current master)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by Deni-Iconis** [comment]
#7390
