### ISSUE TITLE
Demo Playground GraphQL is broken

### ISSUE THREAD

**Issue by darth-veitcher** [mirumee/saleor#7991]
### What I'm trying to achieve
I wanted to review the demo.saleor.io/graphql code playground.

### Steps to reproduce the problem
1. Navigate to https://demo.saleor.io/graphql/
2. Attempt to run the example code that's pre-populated
3. Attempt to query for a product

### What I expected to happen
I expected to receive a response. Instead I receive null/errors. I believe the code sample is broken from a syntax perspective and, also, will not work because your products query now requires a channel to be passed into it. From the documentation I can see that only staff can access the channels so therefore I can't enumerate over a list of them to find an id to pass to the products query as an anonymous user.

Logging into the backend I can see these two channels.

![image](https://user-images.githubusercontent.com/1722315/131577943-f1900838-b730-45f3-a903-3923920fdeab.png)

Passing in one of these to a query no longer gives me an error, but returns a blank result (which is unexpected).

#### Initial populated screen with syntax error
![image](https://user-images.githubusercontent.com/1722315/131574217-b087169b-da5e-40c1-83af-6f91af4e49d4.png)

#### Fixed query (but still shows no results)
![image](https://user-images.githubusercontent.com/1722315/131578159-fad117eb-900b-4231-bf81-81ebfd0984be.png)

### Additional Info
For what it's worth I was attempting to follow along with the linked video [Building an E-Commerce App with React.js & GraphQL using Next.js & Saleor API](https://www.youtube.com/watch?v=85vMColDHEo). Whilst only from May 2021 there seem to be some big differences in the API on the demo site.

**Comment by maarcingebala** [comment]
Yep, the query passed to the template got broken, we will fix it- thanks for reporting. This query accepts channel slugs, so for example passing `default-channel` will work.

I believe when this video was created we were still running Saleor 2.11 on that demo instance, but recently we upgraded it to 3.0 beta which is the new version that we're building. Check out the docs for 3.0 for example queries that can be run there: https://docs.saleor.io/docs/3.0/developer
