### ISSUE TITLE
Review installation instructions, check if it's up-to-date

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#801]
Update if it's requried

**Comment by fgmacedo** [comment]
How to keep a project using saleor up to date? How is the process since the install instructions rely on a clone of the project, that seems to be the scaffolding code where we will build from. But if I do any changes, I will lose the glue with the main repo.

Any hints?  Best regards!

**Comment by maciekjablonski** [comment]
everything's alright

**Comment by krzysztofwolski** [comment]
@maciekjablonski Both docker and 'virtualenv way'?
