### ISSUE TITLE
All cursors are identical (and unworking) when using `filter` on `query.products`

### ISSUE THREAD

**Issue by onecrayon** [mirumee/saleor#8011]
### What I'm trying to achieve
We are attempting to paginate a filtered `products` query. However, all cursors reported are identical when using a search filter.

### Steps to reproduce the problem
1. Visit a playground with sufficient products that you can do a filtered search of them
2. Run a query similar to the following (but with a search term and channel that are appropriate to the install):
    ```
    query {
      products (
        first: 3, filter: { search: "Camera" }, channel:"msrp"
      ) {
        edges {
          node {
            id
          }
          cursor
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
        totalCount
      }
    }
    ```
3. Note that all reported cursors are identical. If you add `after: "CURSOR-HERE"` to the arguments, you receive the same list of products. 

### What I expected to happen
Cursors should be unique so that you can start pagination at those points.

### Screenshots and logs
Please let me know if you are unable to reproduce this; here's what it looks like for us:

![Screen Shot 2021-09-02 at 2 52 32 PM](https://user-images.githubusercontent.com/33501/131921413-c2cef764-3181-4f9e-8b6e-5b28b3b8bb71.png)

**System information**

Saleor version:
- [ ] dev (current master)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

**Comment by fowczarek** [comment]
If you need a workaround you can just add `sortBy:{field:NAME, direction:ASC}` to query.
