### ISSUE TITLE
Document GraphQL API

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#808]
* Which libraries are used (link to 3rd party documentation)
* Describe basic data flow (how records are fetched from the db and sent to the client)
* Describe how to add a new endpoint

**Comment by maarcingebala** [comment]
Not exactly what described in the issue, but we added docs about how to use our API recently: https://docs.getsaleor.com/docs/next/api/intro/. If anyone see any sections that are missing, let's discuss that in the [saleor-docs](https://github.com/mirumee/saleor-docs/) repo.
