### ISSUE TITLE
SEO: replace schema.org implementation with JSON-LD

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#834]
After recent merge of the demo branch the schema.org implementation is partially broken. It's a good moment to remove it from HTML (where it's hard to maintain) and replace it with JSON-LD which is currently the recommended way to embed metadata.

Things to consider:
* We should check whether it's possible to link to JSON-LD as an external URL (this would allow us to only generate it when requested)
* Google supports metadata injected by JS in case of single-page apps (in case we wanted to load it asynchronously)

**Comment by patrys** [comment]
Examples: http://jsonld.com/product/

**Comment by patrys** [comment]
As with Google Merchant feeds, we should use "brand" and "publisher" attributes to populate the brand field if present.

**Comment by krzysztofwolski** [comment]
Unfortunately, using external URLs is not supported. Tried it using Google validator tools.

Todo: Update shema in

- [ ] Product
- [ ] WebPage

**Comment by krzysztofwolski** [comment]
Having editable settings in dashboard would be usefull for better json-ld webpage descriptions.

**Comment by krzysztofwolski** [comment]
@patrys Product lists, product details and pages contains json-ld metadata. Also, old markings are removed. 
Does it cover this issue?

**Comment by patrys** [comment]
CC @mociepka

**Comment by mociepka** [comment]
We missed breadcrumbs and it will be nice to do research about `mainContentOfPage`. Right now we define site and below we define for instance product.

Maybe better will be site definition with `mainContentOfPage` set to product.

**Comment by patrys** [comment]
We don't tag the site, just products. Therefore there's nowhere to set `mainContentOfPage`/`mainEntityOfPage`.
