### ISSUE TITLE
cannot load products in safari, js has errors

### ISSUE THREAD

**Issue by osess** [mirumee/saleor#837]
When visiting products/category/blah/ in safari (tested in iphone, ipad, windows), the products in that cateogy are not listed. There are some errors in the js.

**Comment by artursmet** [comment]
Could you share content of these errors?

**Comment by osess** [comment]
![js_errors](https://cloud.githubusercontent.com/assets/4022671/22408278/87580390-e6db-11e6-8203-a89747f424fb.png)

Please see the upon image. BTW, the safari used in windows is 5.1.7, ios is 8.3.

**Comment by elwoodxblues** [comment]
@osess Thanks for reporting this issue. We've just merged PR #838 that should fix it.
