### ISSUE TITLE
Hide variant selector when there's only one variant

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#839]
When there's only one variant we shouldn't show select widget with one option. It should be the default.

**Comment by patrys** [comment]
...but we SHOULD display its attributes as if those belonged to the product itself (because you still need to know the material/size/CPU/ebook format etc.)

**Comment by artursmet** [comment]
Yes, but there's also another case, when product has no variant level attributes, so there is literally one available variant, for example red scarf in one size, then only product level attribtues will be displayed below description (color:red)

**Comment by Pacu2** [comment]
I think this is resolved by now
