### ISSUE TITLE
navbar and products list not shown correctly in old webkit based browser

### ISSUE THREAD

**Issue by osess** [mirumee/saleor#845]
I opened the homepage in safari (5.1.7). It works well when the width is normal. However, once I change it to a portrait view, it's rendered as below:

![image](https://cloud.githubusercontent.com/assets/4022671/22450018/b9a21b22-e7c8-11e6-96c6-86f931720483.png)

This also happens in several android mobiles(samsung, huawei). All the default browsers of these mobiles are using older webkit as the core.

**Comment by benekex2** [comment]
We support browsers with ES6. Safari 5.1.7 was as default on OS X Snow Leopard (over 5 years old). In version 6 this problem does not occur, the same as Chrome in version 37<
