### ISSUE TITLE
Front end storefront fixes

### ISSUE THREAD

**Issue by weronka** [mirumee/saleor#865]
- [x] add bigger active area to close button in search form on mobile

**Comment by benekex2** [comment]
- [ ] IE11 issues. For other browsers mistakes are repeated:

![bs_win10_ie_11 0 1](https://cloud.githubusercontent.com/assets/15363376/22543514/1d2a7d06-e931-11e6-88db-0f9be22d0f5b.jpg)
![bs_win10_ie_11 0 2](https://cloud.githubusercontent.com/assets/15363376/22543515/1d2caaf4-e931-11e6-88c7-c2e18d7a4093.jpg)
![bs_win10_ie_11 0](https://cloud.githubusercontent.com/assets/15363376/22543516/1d2d7aa6-e931-11e6-8f96-0a79319de7b8.jpg)
