### ISSUE TITLE
webpack : OSError: Error reading /app/webpack-bundle.json.

### ISSUE THREAD

**Issue by jujes** [mirumee/saleor#874]
someone know abut this issue?
all what I do is add in docker-compose.yml

```
    environment:
      - ALLOWED_HOSTS=anida.shop
```
here the log and the output:
thanks in advance,

```
web_1     | Internal Server Error: /
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.5/site-packages/webpack_loader/loader.py", line 25, in _load_assets
web_1     |     with open(self.config['STATS_FILE']) as f:
web_1     | FileNotFoundError: [Errno 2] No such file or directory: '/app/webpack-bundle.json'
web_1     | 
web_1     | During handling of the above exception, another exception occurred:
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
web_1     |     response = get_response(request)
web_1     |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
web_1     |     response = self._get_response(request)
web_1     |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
web_1     |     response = self.process_exception_by_middleware(e, request)

.
.
.
web_1     |   File "/usr/local/lib/python3.5/site-packages/webpack_loader/loader.py", line 59, in get_bundle
web_1     |     assets = self.get_assets()
web_1     |   File "/usr/local/lib/python3.5/site-packages/webpack_loader/loader.py", line 38, in get_assets
web_1     |     return self._load_assets()
web_1     |   File "/usr/local/lib/python3.5/site-packages/webpack_loader/loader.py", line 31, in _load_assets
web_1     |     self.config['STATS_FILE']))
web_1     | OSError: Error reading /app/webpack-bundle.json. Are you sure webpack has generated the file and the path is correct?
web_1     | [03/Feb/2017 19:12:13] "GET /account/login HTTP/1.1" 500 164777
web_1     | [03/Feb/2017 19:12:30] "GET /admin HTTP/1.1" 404 4332
```
![screenshot from 2017-02-04 02-13-33](https://cloud.githubusercontent.com/assets/2881017/22614288/6f34a810-ea80-11e6-97cb-2045af75f83d.png)

**Comment by elwoodxblues** [comment]
@jujes Have you resolved this issue? `webpack-bundle.json` file should be generated by Webpack, when you run: `yarn run build-assets`.

**Comment by yinxinwang** [comment]
Is there any solution to this problem?  thank you very much

**Comment by elwoodxblues** [comment]
@yinxinwang You have to build your assets by running `yarn run build-assets`. This will produce `webpack.config.js` file. Also make sure that you have correct path to this file in `settings.py` - (`STATS_FILE` in `WEBPACK_LOADER` setting).

**Comment by yinxinwang** [comment]
Thank you very much

**Comment by apburton84** [comment]
Hi, 

I have the same issues as above when using Docker.

    web_1     | During handling of the above exception, another exception occurred:
    web_1     |
    web_1     | Traceback (most recent call last):
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, 
    in inner
    web_1     |     response = get_response(request)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in 
    _get_response
    web_1     |     response = self.process_exception_by_middleware(e, request)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in 
    _get_response
    web_1     |     response = response.render()
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 106, in 
    render
    web_1     |     self.content = self.rendered_content
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 83, in 
    rendered_content
    web_1     |     content = template.render(context, self._request) 
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 
    61, in render
    web_1     |     return self.template.render(context)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 175, in render
    web_1     |     return self._render(context)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/test/utils.py", line 98, in 
    instrumented_test_render
    web_1     |     return self.nodelist.render(context)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    web_1     |     bit = node.render_annotated(context)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 910, in 
    render_annotated
    web_1     |     return self.render(context)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 155, in 
    render
    web_1     |     return compiled_parent._render(context)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/test/utils.py", line 98, in 
    instrumented_test_render
    web_1     |     return self.nodelist.render(context)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 943, in render
    web_1     |     bit = node.render_annotated(context)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 910, in 
    render_annotated
    web_1     |     return self.render(context)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/django/template/library.py", line 192, in 
    render
    web_1     |     output = self.func(*resolved_args, **resolved_kwargs)
    web_1     |   File "/usr/local/lib/python3.6/site- 
    packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
    web_1     |     tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/webpack_loader/utils.py", line 45, in 
    get_as_tags
    web_1     |     bundle = _get_bundle(bundle_name, extension, config)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/webpack_loader/utils.py", line 23, in 
    _get_bundle
    web_1     |     bundle = get_loader(config).get_bundle(bundle_name)
    web_1     |   File "/usr/local/lib/python3.6/site-packages/webpack_loader/loader.py", line 59, in 
    get_bundle
    web_1     |     assets = self.get_assets()
    web_1     |   File "/usr/local/lib/python3.6/site-packages/webpack_loader/loader.py", line 38, in 
    get_assets
    web_1     |     return self._load_assets()
    web_1     |   File "/usr/local/lib/python3.6/site-packages/webpack_loader/loader.py", line 31, in 
    _load_assets
    web_1     |     self.config['STATS_FILE']))
    web_1     | OSError: Error reading ./webpack-bundle.json. Are you sure webpack has generated the 
    file and the path is correct?
    web_1     | UWSGI uwsgi "GET /en/ HTTP/1.1" 500 175910 135ms [PID:15:Worker-4] [RSS:111MB]

After following these instructions https://saleor.readthedocs.io/en/latest/customization/docker.html#

When I login to the to ```web``` container and ```ls``` I see that ```./webpack-bundle.json``` exists.

```'STATS_FILE': os.path.join(PROJECT_ROOT, 'webpack-bundle.json')``` from ```saleor/settings.py``` is unchanged.

Thanks,
