### ISSUE TITLE
How to Add product 

### ISSUE THREAD

**Issue by tanvirraj** [mirumee/saleor#878]
hi , i am new to saleor . 
First of all thanks to the team.
 but i can't find admin panel or where i go to add product or change payment method or see my shop owner dashboard .

**Comment by artursmet** [comment]
Hello @tanvirraj.

When you log in as an administrator (execute `python manage.py createsuperuser` if you don't have credentials), you should be able to see Dashboard link on the top bar.
Or try accessing `/dashboard/`.

Payment method configuration is available only in code at the moment, you should take a look on settings.py file and `PAYMENT_VARIANTS` variable. This is configuration for https://github.com/mirumee/django-payments

**Comment by tanvirraj** [comment]
@artursmet . Thanks man . understand :)

**Comment by HawiCaesar** [comment]
I know this is closed but is it possible for this to be put in the documentation? I really struggled only to find out its a simple 
`python manage.py createsuperuser`
