### ISSUE TITLE
Document Social Auth

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#881]
* Describe how to add a new authorization backend
* Link to django-allauth docs

**Comment by artursmet** [comment]
@krzysztofwolski As we discovered, django-allauth introduces more problems than profits. There was a suggestion to migrate to another library, like https://github.com/python-social-auth/social-app-django
Some research will be required there, to check if python-social-auth delivers better API than allauth

**Comment by krzysztofwolski** [comment]
@artursmet Which parts of api caused most problems?

**Comment by krzysztofwolski** [comment]
@szewczykmira 
https://github.com/python-social-auth Changed a lot, it could be nice replacement for django-allauth. Could you try to integrate it with saleor or find better alternative? We want to have ability to specify facebook (and other social) settings at runtime in SiteSettings dashboard.

**Comment by patrys** [comment]
We've already settled on replacing it with `python-social-auth`. Sorry if this was not documented properly.

**Comment by krzysztofwolski** [comment]
@patrys It has no problems with providing social API tokens on runtime? Did somebody started implementing it?

**Comment by patrys** [comment]
No idea about that but it seems to be of better code quality than allauth is.
