### ISSUE TITLE
docker-compose up no run   >>  webpack : OSErro

### ISSUE THREAD

**Issue by jujes** [mirumee/saleor#886]
Hi, someone can tell me how make a local deploy using **docker-machine** and **virtualbox**?

**step by step:**
```
$ eval $(docker-machine env saleorServer)
# inside the saleor folder:
add ALLOWED_HOSTS >> docker-compose.yml
$ docker-compose build
$ docker-compose run web python manage.py migrate
$ docker-compose run web python manage.py populatedb --createsuperuser
$ docker-compose up
```
Thanks in advance :)

**Comment by johnjullies** [comment]
@jujes I just had this Error earlier when attempting to run with `docker-compose up` and this is what I did, on my local machine, run:
```
$ npm install
$ npm run build-assets
```
then on the docker web container, run:
```
$ python manage.py collectstatic
```

**Comment by krzysztofwolski** [comment]
@jujes Did John's answer solved your problem?

**Comment by jujes** [comment]
hi @krzysztofwolski , thanks @johnjullies 

Yes: problem solved!

Here all my deploy guide... if you have a clean virtual machine ;)
```
# APT: basic software installation
$ sudo apt update && sudo apt-get install -y build-essential git

# NODE install
$ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
$ vi ~/.bashrc
# add this in the .bashrc
vim export NVM_DIR="/home/docker/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
$ . ~/.bashrc

# REPO: clone
$ git clone https://github.com/mirumee/saleor.git && cd saleor

# setup the host in my case: saleor.dev >> ALLOWED_HOSTS >> docker-compose.ym
$ vi docker-compose.yml

# NODE
$ nvm use
$ nvm install 6
$ npm install
$ npm run build-assets

# DOCKER
$ docker-compose build
$ docker-compose run web python manage.py migrate
$ docker-compose run web python manage.py populatedb --createsuperuser
__
$ docker-compose up
$ docker-compose run web python manage.py collectstatic
```

now I need run reel in saleor, here my issue, some of you know how do it?
https://github.com/mirumee/saleor/issues/935

thanks in advance

**Comment by kacharif** [comment]
Hello,
I have problem when i execute 

$ docker-compose run web python manage.py collectstatic

I receive in terminal :  

Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
