### ISSUE TITLE
Drop url-loader

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#888]
We should drop `url-loader` from webpack and stick to the `file-loader`. Url-loader inlines the SVG images in the CSS file outputted by Webpack which makes this file to have 1.6 MB size.

**Comment by elwoodxblues** [comment]
It should work fine with the `InlineSVG` library that we use for rendering SVG's in React.

**Comment by benekex2** [comment]
@elwoodxblues Import svg file with file-loader returns only file name with hash but not path to file.

**Comment by patrys** [comment]
@benekex2 That's fine. `file-loader` returns the URL to the file and `<InlineSVG/>` React component takes care of downloading and inlining. Unless you need to use the files outside of React it should work as expected.
