### ISSUE TITLE
Page with read-only warning.

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#892]
Theres need for page with info about read only demo. We want to move it from dashboard panel info separate view.

**Comment by subgrafik** [comment]
![zejak](https://cloud.githubusercontent.com/assets/7837760/22735495/3c94b18e-edfa-11e6-8e8d-24acb20b523d.jpg)

A) gallery - with randomly displayed pictures
B) full screen (a bit in  wetransfer spirit) 4 to 8 random illustrations with Saleor Pirate and things,
every time user click sth without action will see different pics 

Thoughts?

**Comment by krzysztofwolski** [comment]
Feature implemented. 
Try changing password to get awesome splash screens.
