### ISSUE TITLE
Error linking uWSGI - Mac OSX

### ISSUE THREAD

**Issue by indranil-tiwary** [mirumee/saleor#897]
when trying to run this command:
`
pip install -r requirements.txt
`
I am getting uWSGI error linking everytime.

Error:

 clang: error: linker command failed with exit code 1 (use -v to see invocation)
    *** error linking uWSGI ***
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/j6/jrlq9lsx6kndlqsmchbh6x9c0000gn/T/pip-build-uvQlMg/uwsgi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/j6/jrlq9lsx6kndlqsmchbh6x9c0000gn/T/pip-JFDZYy-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/j6/jrlq9lsx6kndlqsmchbh6x9c0000gn/T/pip-build-uvQlMg/uwsgi/

**Comment by krzysztofwolski** [comment]
@indranil-tiwary  Strange, I had no problems installing it on my machine. 
Have you tried this solution? https://github.com/unbit/uwsgi/issues/600

**Comment by maciekjablonski** [comment]
@indranil-tiwary could you attach full pip response?

**Comment by krzysztofwolski** [comment]
Looks like problems on user machine. Closing.

**Comment by patrys** [comment]
It would be nice to get to the bottom of this. Maybe we could add a macOS-specific paragraph to the installation docs.
