### ISSUE TITLE
how can I install/use only Add to cart functionality of Saleor in my project.

### ISSUE THREAD

**Issue by prashante114** [mirumee/saleor#924]
Hi, 

I have created a Project in django, in that I created an app. I want to insall Shopping cart / Add to cart plug in of Saleor in my project. 

I am facing difficulty in installing ONLY Add to cart functionality of saleor. 
For eg. I do install a third party package by pip install package name, and add the app/package name to INSTALLED APPS in settings.py file. 

my question is, how can I just install Add to cart and use it in my project? Or  Can I customize Saleor's functinality or only front end can be customized?
PS: I am new to Django and Saleor.

**Comment by krzysztofwolski** [comment]
Hey, I suggest you to clone Saleor and cut off or adapt parts you don't need. This project is not designed to be installed via PIP.

**Comment by prashante114** [comment]
Hi,

Thanks for your reply. But I still have a query. 

Like you said, if I want to use only "cart" app of Saleor, do I need to delete other folders from the Saleor?
Or, Can I inherit, like import cart from Saleor something like this, in my existing project?

I found that these apps have dependency on each other.

**Comment by askamist** [comment]
Ideal way to do it would be to read and understand how Saleor cart works, and write you own cart as per your requirements.

Apps in the Saleor project are not designed to be independent of each other. So even if you are deleting some other folder you have make sure that cart is not dependent on them. If it is then you will have to keep them or provide your own alternatives.

for example:
cart app depends on product app, for the add to cart functionalities. you will have to patch it with your own product app or what ever it is you are adding to cart..

**Comment by patrys** [comment]
I'll close this as I think enough information was provided. Thank you @askamist! ✨
