### ISSUE TITLE
Json Apis for whole application?

### ISSUE THREAD

**Issue by Aravind-Rajendran** [mirumee/saleor#926]
We wanna separate  front end as a stand alone application so that i can use angular or react . 
We wanna continue get updates from saleor for backend. Is it possible? do you guys have any plans?

**Comment by patrys** [comment]
There's already an initial implementation of a GraphQL API in place. It's not complete yet as it lacks mutations but you should be able to consume it with a client library like Apollo or Relay. We're open to extend it to allow a single-page application acting as a front-end. It would be great if you wanted to drive this effort by opening issues for missing pieces of the API and maybe even providing parts of the implementation as pull requests. This could be paired with an OAuth backend to allow full separation but is not necessary for same domain access.

**Comment by elwoodxblues** [comment]
We're going to work on extending the GraphQL API, relevant issues about this will be added soon.
