### ISSUE TITLE
Question about product details page without variant parameters

### ISSUE THREAD

**Issue by itbabu** [mirumee/saleor#928]
Hello,

Click on any product on the category pages or any product on homepage. 
no variant is selected and the add to cart button is disabled.
eg http://demo.getsaleor.com/products/johnson-conrad-112/

As user I felt a bit confused the first times.
Shouldn't be the user redirected to one of the product variants?

**Comment by patrys** [comment]
It's a known bug caused by the recent changes made to the variant picker.

**Comment by krzysztofwolski** [comment]
https://github.com/mirumee/saleor/pull/922 
This bug is fixed and we redeploy demo today.
