### ISSUE TITLE
Error accessing dashboard/products

### ISSUE THREAD

**Issue by kaustubhrpatil** [mirumee/saleor#930]
New fresh installation with example data populated. When trying to access products in the dashboard (admin login), I get the following error:

Error during template rendering
In template /root/webapps/scirepl/saleor/templates/dashboard/product/list.html, error at line 41
2

The code seems to access non-existent images files, e.g.:

IOError at /dashboard/products/

[Errno 2] No such file or directory: u'/root/webapps/scirepl/saleor/media/products/saleor/static/placeholders/coffee/coffee_03_4CC8nze.jpg'

I tried repeatedly creating fake files but stopped after 10 or so.

**Comment by patrys** [comment]
Did you get any errors during `populatedb`? The files should be created by this command.

**Comment by zbloss** [comment]
I have had this same issue. I ran populatedb, collectstatic, npm run build-assets all in different sequences trying to fix it.

My problem was solved by creating a new Postgres database (psql createdb "nameofdb(withoutquotes)") and then pointing to that new DB in the settings.py file. You will need to re-run the migrate and populatedb commands

**Comment by elwoodxblues** [comment]
I'm closing the issue due to no response and no other reports. Please reopen if it happens again.
