### ISSUE TITLE
Use AdminLTE theme in Dashboard

### ISSUE THREAD

**Issue by meigallodixital** [mirumee/saleor#947]
Have you considered the use of the AdminLTE theme to style the Dashboard? It is MIT licensed.

I think it could lighten the job quite a bit and it's very visually appealing.

**Comment by patrys** [comment]
Please see #920 for the ongoing work on improving the dashboard.

**Comment by elwoodxblues** [comment]
AdminLTE is a good alternative but it's based on Bootstrap, so switching to it would require rewriting all dashboard templates. We're planning to stick to MaterializeCSS for now. Recently we've released a major upgrade to styles and markup in dashboard so you might want to check it.
