### ISSUE TITLE
Fetaure request: no price and rating/comments

### ISSUE THREAD

**Issue by kaustubhrpatil** [mirumee/saleor#950]
Hi this is not really an issue but I am not sure where to post feature requests. I have two requests:

1) Is it possible to assign a zero price to each product and default quantity to 1, so that the price and quantity do not show up on the product page and are nor necessary to make a purchase. What is the best way to achieve this?

2) Is there a possibility to allow customers to rate products and the vendors (added as a product attribute) to rate customers? Also any way to allow comments on products?

Thanks

**Comment by elwoodxblues** [comment]
Hi @kaustubhrpatil,
as for the first question, Saleor doesn't support such scenario by default. It's possible to have a product with zero price, add it to basket and finalize checkout, but the order management dashboard doesn't provide ways to fulfill such order, as it can only finalize orders that are fully paid. I see the following solution for your case:
1. Add a new field to `ProductClass` class that will allow you to track the information whether the product requires price, something like `is_price_required` could work here.
2. Having this field you can update your storefront templates to hide the price and quantity for products that don't require price.
3. Add an action in order details dashboard view that will allow you to mark order with such products as completed.

As for the second question, there is no ability to rate or comment products at the moment and we're not planning to add it now. However I think it should be relatively easy to implement. Feel free to open a pull request to Saleor if you come up with an implementation :)

I hope this answers your questions.
