### ISSUE TITLE
Styleguide

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#957]
It would be very useful to have an interactive styleguide in Saleor, that would mainly serve two purposes:
- documenting the current styles used in Saleor
- helping developers to build new views

When viewing styleguide page people should be able to inspect styles and components with their devtools to quickly learn how they are built and how to reuse them. Ideally developers working on templates should be able to copy and paste component they would like to use and just fill it with correct data and adjust to the view they're building.

The styleguide should contain all styles and components used in Saleor:
- [x] color palette, specification of used fonts and text sizes, paddings and margins
- [x] CSS classes and helpers
- [x] buttons (in all states - enabled, disabled, primary, secondary etc.), forms, widgets
- [x] validation errors,
- [x] styleguide should be implemented as a single view returning a static template and necessary context (forms etc.) available under `/styleguide` URL.    

Bootstrap documentation is a good example of how it might look (of course it would be much simpler in our case):
http://getbootstrap.com/css/
http://getbootstrap.com/components/

**Comment by weronka** [comment]
Before creating style guide we can think how to better organize existing styles and scss files inside the projects and check are we using BEM methodology everywhere in the right way.

My propose is to divide styles to /elements (buttons, forms, breadcrumbs etc) and /templates (home, product page, checkout etc). And keep all global variables like font sizes and colors in separate variables.scss file. It'll be easier to edit particular components styles and we will be able to provide clean code examples in style guide.

@benekex2 what do you think?

**Comment by patrys** [comment]
We're talking about MaterializeCSS here. Since most components we style come from the framework there's not much we can do about the structure I'm afraid.

**Comment by elwoodxblues** [comment]
I thought we are talking about styleguide for our storefront. For sure we need a styleguide for the dashboard too.

**Comment by weronka** [comment]
@patrys I was thinking about style guide for storefront writing about the files structure.

**Comment by benekex2** [comment]
With @weronka we decide to create styleguide to storefront and dashboard at the same time. This is good opportunity to clean styles and improve their organization with the same schema.
