### ISSUE TITLE
Read-only details views

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#958]
We should implement read-only detail views for all types of objects that we allow to manage in dashboard. It should work as follows:
- [x] clicking on a list of objects should take user to the ready-only details view
- [x] details view should present relevant information about the viewed object and provide links to "edit view" and "delete view".
- [x] as a results of actions in "edit view" user should be redirected to the details view
- [x] after removing a object user should be redirected to the list view
- [x] unify naming convention of our dashboard templates

**Comment by patrys** [comment]
Jus to clarify, "details view" is not the same as "form with fields disabled". We need something similar to order details but designed specifically for each type of object.
