### ISSUE TITLE
ImportError: cannot import name 'PaymentStatus'

### ISSUE THREAD

**Issue by johnjullies** [mirumee/saleor#962]
I'm getting an error and can't run the shop after updating my local copy of master
```
web_1     |   File "/app/saleor/order/models.py", line 16, in <module>
web_1     |     from payments import PaymentStatus, PurchasedItem
web_1     | ImportError: cannot import name 'PaymentStatus'
```

**Comment by patrys** [comment]
We've updated the dependencies to include a new version of `django-payments`. You will need to install it for things to work.
