### ISSUE TITLE
Consider integration with popular enterprise communication software

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#965]
Slack is a major target. Others include Hipchat and Skype for Business (former Lync).

Ideally we'd push the same notifications we usually e-mail to admins. Some other ideas come to mind such as warning about product stock becoming low.

**Comment by patrys** [comment]
Related: https://apps.shopify.com/slackify

**Comment by mikeres0** [comment]
+1 for a slack integration. I can lay some of the ground work if need be.

**Comment by maarcingebala** [comment]
With plugin architecture this would be now much easier to implement. I imagine that we might want to add such plugins in the future.
