### ISSUE TITLE
Moving order lines to processed delivery groups

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#969]
It seems that we allow moving unprocessed order lines to delivery groups that are already processed (`fully-paid` or `shipped`). We should only allow moving order lines to `new` or `pending` delivery groups. Or is there some use-case for this behavior?

https://github.com/mirumee/saleor/blob/master/saleor/dashboard/order/forms.py#L125-L126

**Comment by patrys** [comment]
I'm not sure about enforcing things like that. We could warn about their status in the delivery group selector but I'm not convinced we should prevent staff from doing it. Say I forgot to move one item before marking package as shipped but the package actually contains it.

**Comment by elwoodxblues** [comment]
OK, I agree that we should remain flexible and this constraint is not necessary at the moment.
