### ISSUE TITLE
Attempted to add noncontiguous index to GraphQLSegment : warning on Category page.

### ISSUE THREAD

**Issue by askamist** [mirumee/saleor#971]
I am using saleor for my project and I got this Warning on Category page.

```
Attempted to add an ID already in GraphQLSegment: client:client:-11802100631:UHJvZHVjdFR5cGU6OTY3
storefront.3d9905fadad1356fe561.js:formatted:8568 Attempted to add noncontiguous index to GraphQLSegment: 4 to (0, 1)
```

and only the products till the index in the warning are rendered. like Only 3 products were rendered in the above case.

based on the answer on [this issue](https://github.com/graphql-python/graphene-django/issues/1) adding distinct() resolved it.

I couldn't find any instructions for contributing. So posting it as a issue.

Thank you guys for the awesome project. Hope this helps.

**Comment by elwoodxblues** [comment]
Hi @askamist, Relay assumes that nodes are unique within the connection ([related issue](https://github.com/facebook/relay/issues/1319)), so you must have had duplicated objects in your `products` queryset used by GraphQL. Did this happen in the "clean" Saleor version or did you make some customizations in your models or category/product querysets?

**Comment by elwoodxblues** [comment]
I'm closing the ticket due to no response and no other reports of the issue. Please reopen if necessary.
