### ISSUE TITLE
Migrations wont be applied due to "changes" in django_prices_openexchangerates

### ISSUE THREAD

**Issue by tillkolter** [mirumee/saleor#976]
Hi,
I couldnt migrate my own models due to Django's understanding of model changes concerning fields with choices and your package `django-prices-openexchangerates` with a constantly seeming order change.

I proposed a pull request: https://github.com/mirumee/django-prices-openexchangerates/pull/17

**Comment by patrys** [comment]
I believe this is fixed now. 👌
