### ISSUE TITLE
Hide shipping calculation in cart when shipping is not required

### ISSUE THREAD

**Issue by elwoodxblues** [mirumee/saleor#982]
I think we should hide "CALCULATE SHIPPING COST" section in cart, when products that are currently in cart don't require shipping. It should be only displayed when there is at least one item that does require shipping.

**Comment by patrys** [comment]
I think we should also move shipping to the cart table. I think currently we say "shipping calculated during checkout" and immediately below display the shipping cost.

**Comment by szewczykmira** [comment]
@patrys What do you mean by "move shipping to the cart table"? Do you want to move "Calculate shipping cost" to cart table or something else?
