### ISSUE TITLE
separate Product vs Product page?

### ISSUE THREAD

**Issue by littlehome-eugene** [mirumee/saleor#988]
I'm using forked saleor.  

Recently I found that we are treating `Product` as `Product page` .  

One consequence is that, 

since product_variant is tied to a single product, you can only list a specific product variant in a single product page. 

I think one should be able to use a product variant in multiple product pages.

**Comment by patrys** [comment]
I'm not sure I follow. What is your use case?

**Comment by littlehome-eugene** [comment]
Suppose I sell computers. 

I can sell a cpu separately in one product page , and can bundle it with other parts in another product page. 


(I don't think you can bundle product variants in current saleor, but I'm just trying to illustrate)

**Comment by patrys** [comment]
Variants are subtypes of a particular product, not its ingredients. I think what you're looking for are product bundles (collections of variants belonging to multiple products) but these should be separate from products.
