### ISSUE TITLE
Graphql addToCart mutation and how to set the anonymous cart cookie

### ISSUE THREAD

**Issue by tillkolter** [mirumee/saleor#995]
Hi,
I dont know if you plan to implement this at some point in your framework, but I am currently extending/overwriting your architecture to a SPA with VueJS. I came to the point of mutating the cart now and was hoping for some opinion. Sorry for bothering if this is the wrong place of discussion to start this kind of opinionated discussion.

GraphQL-wise everything works well now, but I ran into the problem, that the signed `cart` cookie can not be set on the response from inside the mutation as you do it after the form validation in `product_add_to_cart` as the response is created on a much higher stack level.

I am new to cookie handling but my way to solve this problem would be to define `cartCookie` and `maxAge` as mutation output fields and then set the cookie in the frontend, but this somehow feels wrong and error prone.

Is anyone willing to share an opinion on this?

Cheers
Till

**Comment by patrys** [comment]
I think with SPA approach storing the cart cookie could be considered client's responsibility. Paired with OAuth this could let you host the back end separately from the client.

**Comment by tillkolter** [comment]
@patrys Thanks for your opinion, although I am not sure if I got you right. To unsign the cookie in the backend correctly I still need to generate the value in the backend right? At the end I solved it as I suggested outputing the cookie and save the raw data in the frontend. Works for now.

**Comment by patrys** [comment]
Sorry for brevity, I was suggesting having the client maintain and pass the cart ID instead of the GraphQL endpoint depending on the cookie.

**Comment by tillkolter** [comment]
Ok, I got you right then (and ignored it for now 😄 ). I decided to move forward for now with my crooked solution because I wanted to avoid touching too much of your backend logic until I finished porting the frontend. Thanks for the advise. Case closed 👍
